{
  "hash": "23d37a0d9fd2aee5fd12cb2274b7a60a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Data, Distributions, and Variation\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-cap: true\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\n\nChapter 1 explained what study observations represent and how they\narise. This chapter develops their descriptive use: how to read the\nrecorded data and turn measurements into useful displays and summaries.\nIts small invented examples make the arithmetic visible before we\nreturn to a larger school dataset. A final simulation extends the same\nideas of center, spread, and shape to summaries from repeated samples,\npreparing us to understand statistical uncertainty.\n\nBy the end of the chapter you will be able to read a dataset as cases,\nvariables, and values, recognize long and wide layouts, and identify\nthe denominator and sample-selection procedure; see and summarize one\ndistribution by shape, center, and spread, telling a left from a right\nskew by its long tail; compare groups while keeping\ntheir variation visible; connect variable forms to probability models,\ncalculate transformations and Normal areas, and describe a relationship\nwith a graph, covariance, correlation and linear adjustment; interpret\neach description within its study setting;\nexplain what a sampling distribution and standard error show about\nrepeated samples and how sample size and the sampling design change\nthem; and distinguish one sample's sampling error from that\ndistribution and its standard error.\n:::\n\n## Understanding the Dataset\n\nChapter 1 connected study units and measurement procedures to the\nobservations available for analysis. Here we examine the resulting\nrecords: how observations are arranged, what scales and codes mean,\nand which cases and denominator support each summary. These details\nturn the study's account of its evidence into data we can describe.\n\nSchools often want to know whether students with more absences tend to\nreceive lower grades. Before choosing a statistical method, it helps to\nsee what information is actually available.\n\nOur main example uses the mathematics dataset from Cortez and Silva's\nstudent-performance study, based on school reports and questionnaires\nfrom two Portuguese secondary schools [@cortez2008using; @cortez2008data].\nIt contains data for **395 students**, including their absence counts and\nfinal mathematics grades. The repository also provides a separate\nPortuguese-language dataset; the calculations here use the mathematics\ndata.\n\nWe will ask: **Among these 395 students, how do recorded absences and final\nmathematics grades vary together?** To answer, we first describe grades\non their own, then compare groups and examine relationships. We put that\ndescription back into its school setting before asking a related question:\nhow could a summary change if we observed a different sample?\n\n### Cases, variables, values, and data layout\n\nA **dataset** brings together information about people, objects, or\nmeasurement occasions. A **case** is the entity or occasion being\ndescribed. In this dataset each case is one student. A **variable** is a\nfeature that can differ across students, such as absences or final grade;\na **value** is the measurement or category for a particular student.\n\n@tbl-student-preview shows six selected students. The student IDs are\nlabels added for this tutorial. School codes GP and MS identify the two\nschools. Reading across U001's row gives six absences and a final grade\nof six: the same numeral for two different measurements, a count and a\nscore. Reading down the Absences column compares that count across\nstudents. The identifier keeps the two measurements linked to the\nstudent they describe.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n\n::: {#tbl-student-preview .cell layout-align=\"center\" tbl-cap='Selected students from the mathematics dataset' tbl-colwidths='[23,19,25,33]'}\n::: {.cell-output-display}\n\n\n|Student ID |School | Absences| Final grade|\n|:----------|:------|--------:|-----------:|\n|U001       |GP     |        6|           6|\n|U002       |GP     |        4|           6|\n|U003       |GP     |       10|          10|\n|U350       |MS     |       10|          13|\n|U351       |MS     |        8|           8|\n|U352       |MS     |        2|          13|\n\n\n:::\n:::\n\n\nThe two numerical columns can also be written as a **data matrix**,\nwith one row for each displayed student and one column for each variable.\nLet $x_{ij}$ denote the entry in row $i$ and column $j$: here $j=1$\nmeans absences and $j=2$ final grade. The first index numbers these six\ndisplayed rows, rather than their positions in the original dataset.\nThus $x_{31}=10$ absences and $x_{42}=13$ grade points.\n\n$$\n\\mathbf X=(x_{ij})=\n\\begin{pmatrix}6&6\\\\4&6\\\\10&10\\\\10&13\\\\8&8\\\\2&13\\end{pmatrix},\n\\qquad i=1,\\ldots,6,\\quad j=1,2.\n$$\n\nEach column can be summarized separately. The symbol $\\sum$ means to\nadd the indicated entries. For example, the sum for the first column is\n$\\sum_{i=1}^6 x_{i1}=6+4+10+10+8+2=40$, so its mean is\n$40/6=6.6667$ absences. The grade column has mean $56/6=9.3333$\ngrade points. These summarize the six displayed cases; the later\nsummaries use all 395 students. In general, for $n$ rows,\n\n$$\n\\bar x_j=\\frac1n\\sum_{i=1}^n x_{ij},\\qquad\ns_j^2=\\frac1{n-1}\\sum_{i=1}^n(x_{ij}-\\bar x_j)^2.\n$$\n\nThe first formula gives a column's mean. The second gives its sample\nvariance, developed through a small calculation in Section 2.2. This\nnotation organizes numerical entries; identifiers and school labels\nstill have their own meanings and are not quantities to average.\nFor two named variables we can write $x_i=x_{i1}$ and $y_i=x_{i2}$.\nSubscripts have locally stated meanings: an index for a column here\ncan have a different declared use in a later grouped-data calculation.\n\nChapter 1 distinguished the units a study observes from the occasions\non which they are measured. We can recognize that connection in a\ndataset's arrangement. Suppose a separate, invented study records a\nscore for each of 120 students at the beginning and end of a term,\nwith both scores observed for every student. There are 120 students\nand 240 measurement occasions. In a **long layout**, each row describes\none student on one occasion; an occasion column identifies when the\nscore was recorded. In a **wide layout**, each row describes one\nstudent, and separate columns hold the beginning and end scores.\n@tbl-ch02-layout-long and @tbl-ch02-layout-wide show the same six\ninvented scores for three of the students.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n| Student ID | Occasion | Score |\n|:--|:--|--:|\n| S001 | Beginning | 52 |\n| S001 | End | 58 |\n| S002 | Beginning | 61 |\n| S002 | End | 64 |\n| S003 | Beginning | 47 |\n| S003 | End | 53 |\n\n: Invented repeated scores in long form {#tbl-ch02-layout-long tbl-colwidths=\"[30,40,30]\"}\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n\\phantomsection\n```\n\n| Student ID | Beginning score | End score |\n|:--|--:|--:|\n| S001 | 52 | 58 |\n| S002 | 61 | 64 |\n| S003 | 47 | 53 |\n\n: The same invented scores in wide form {#tbl-ch02-layout-wide tbl-colwidths=\"[30,35,35]\"}\n\nFor all 120 students, the long table contains 240 rows and the wide\ntable contains 120 rows. Both contain 240 scores from the same 120\npeople. The identifier links each student's two scores, whether they\noccupy two rows or two columns. Reshaping changes the arrangement while\npreserving the observations and their connections. The 240 scores\ndescribe repeated observations of 120 students. Treating every score\nas independent would ignore the pairing used to describe change. In\nlongitudinal or panel data, these identifiers let us follow the same people. Repeated\ncross-sectional data instead describe different samples on successive\noccasions, so they cannot by themselves show each person's change.\nGroup identifiers, such as school, can accompany either layout. In our\nmain dataset, each student's absence count and final grade contribute\none pair to the relationship we examine.\n\n### Variable forms and roles\n\nNumerical, or **quantitative**, variables describe amounts. Counts such\nas absences take discrete values: a student can have two or three counted\nabsences. An absence count also depends on the number of scheduled\nsessions in its measurement period. Elapsed time can vary continuously,\neven if a device rounds it to whole seconds. Equal differences in\nminutes represent equal amounts of elapsed time: from 20 to 25 minutes\nand from 40 to 45 minutes both add five minutes. Final grades here are\ndiscrete numerical scores on a 0--20 scale, recorded in whole points.\nA one-point difference is a difference on that grading scale; its\nmeaning for learning also depends on what the assessment measures.\n\n**Categorical** variables place cases in groups. A nominal category,\nsuch as school, names a group without ranking it. An ordinal category\nalso has an order, as with low, moderate, and high satisfaction.\nNumerical codes can represent these categories, but an average of school\ncodes would have no useful meaning. For ordered categories, the spacing\nbetween codes need not represent equal differences in the underlying\nexperience.\n\nVariable form helps us choose a description: counts and proportions\nshow how cases fall into categories, while a graph or numerical\nsummary can show the distribution of amounts. Roles come from the question.\nFor the absence--grade question, absences is the **predictor** and final\ngrade is the **outcome**. These are the explanatory and response roles\ndeveloped in Chapter 1, Section 2.1. The roles organize the comparison; the study\ndesign determines whether a causal interpretation is justified. School\ncould instead define groups for a comparison of grade distributions.\n\nA **codebook** explains the variables, their units, coding rules, and\nmeasurement periods. Here it identifies the final grade as G3,\nrecorded from 0 to 20, and the\nsecond-period grade as G2. We use readable variable names in the\ncalculations while preserving the source values. A binary pass indicator\nwill later distinguish grades of 10 or above from grades below 10.\n\n### Coding, missing values, and denominators\n\nA codebook distinguishes a recorded value from its meaning. Zero can\nbe an observed count; a missing value means the intended measurement\nis unavailable. The UCI documentation reports no missing values, but\nthe joint pattern of zero grades and zero absences needs contextual\nchecking, as Section 3.4 explains.\n\nThe **analysis sample** is the set of cases contributing to a particular\ncalculation. Its denominator can change with the measurements that\ncalculation needs. In a separate invented clinic dataset of 1,240\nvisits, 36 lack waiting times, 81 lack return statuses, and 10 lack both.\nThe available counts are\n\n$$\nn_{\\text{wait}}=1240-36=1204,\\qquad\nn_{\\text{return}}=1240-81=1159,\n$$\n\n$$\nn_{\\text{both}}=1240-(36+81-10)=1133.\n$$\n\nAdding 36 and 81 counts the 10 visits missing both measurements twice;\nsubtracting that overlap once counts each incomplete visit once.\nThese denominators describe visits, not necessarily distinct patients.\nLikewise, 20% of sessions and 20% of students answer different questions.\nName the contributing cases and measurement period with each summary.\n\n### The students observed and the population of interest\n\nChapter 1 distinguished whom a study's question concerns from the\nunits that supply its observations. Consider an invented school system\nthat wants to describe all 20,000 students enrolled on a particular\ndate and selects 100 of them. The 20,000 students form the **population**,\nthe collection about which the system wants to learn; the 100 selected\nstudents form its **sample**. A sample may come from a probability\nselection process, volunteers, or an available source. How the students\nenter the sample matters for extending a description to the population.\n\nThe next subsection compares selection procedures in this invented\nsystem. Section 4 returns to it to examine repeated samples, and\nSection 4.4 compares two designs with the same sample size. Our\n395-student dataset comes instead from two schools. Its source supports\na description of these students, while extending the description to all\nsecondary students would need an additional basis.\n\nThe distinction is practical. The mean calculated from all 395 supplied\ngrades describes that collection directly. A statement about students\nelsewhere asks more of the study. For now, we will develop the\ndescription first and revisit its scope at the end.\n\nThe Student Performance resource is distributed under\n[Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/)\n[@cortez2008data]. This tutorial selects and renames variables, adds\nidentifiers and a pass indicator, and retains the original selected\nvalues.\n\n### How samples are selected\n\nChapter 1, Section 3.2 explained how study entry differs from the\nallocation of conditions among participants. We now make the selection\nprocedure visible in the invented school system. This example lets us\ncompare ways of selecting students; the source of the separate\nPortuguese dataset does not establish a probability sample of all\nsecondary students.\n\nThe school system's population contains 20,000 eligible students. A\n**sampling frame** is the list or other operational record used to\nidentify units for selection: here it could be an up-to-date student\nregister. The **sampling design**, also called the **sampling scheme**,\nspecifies how selection proceeds. It can include several stages and\nuse information about the students or their schools.\n\nChapter 1 introduced **random sampling**, also called **probability\nsampling**. Under such a design, every eligible unit in the population\ncovered by the frame has a known, nonzero chance of inclusion. That\nunit's chance of entering the sample is its **inclusion probability**;\nthe probabilities need not be equal. Coverage matters: if eligible\nstudents are absent from the register, random selection from that\nregister cannot select them.\n\nDesigns can use groups in different ways. **Strata** partition the\npopulation into defined groups, such as school types, with a sample\nselected within every stratum. **Clusters** are groups that can be\nselected as units, such as schools whose students will be observed.\n@tbl-ch02-sampling-schemes compares five probability designs\n[@statcan2021probability]; its illustrations use our invented school\nsystem.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n| Scheme | Selection rule | Invented school-system illustration |\n|:--|:--|:--|\n| Simple random sampling | Every possible sample of the specified size has the same probability. | Select 100 distinct students from the full register, giving every possible set of 100 the same chance. |\n| Systematic sampling | Choose a random start, then every $k$th unit. | Select a start at random from 1 to 200, then every 200th student on the 20,000-student list. |\n| Stratified random sampling | Select a probability sample within every defined stratum. | Divide the register by school type, then randomly select students within each type. |\n| Cluster sampling | Select groups through a probability mechanism; in the simplest version, include all eligible units in them. | Randomly select schools from the school list and include all their eligible students. |\n| Multistage sampling | Use probability selection at each stage. | Randomly select schools, then randomly select students within each selected school. |\n\n: Probability sampling schemes in one invented school system {#tbl-ch02-sampling-schemes tbl-colwidths=\"[22,37,41]\"}\n\nThe distinction between simple random and systematic sampling concerns\nthe possible samples. In the systematic design, a random start from 1\nto 200 followed by every 200th student gives each student an inclusion\nprobability of $1/200$. There are only 200 possible samples, one for each\nstarting position. Simple random sampling permits every possible set\nof 100 students. Equal individual chances alone therefore do not define\nsimple random sampling. The ordering of a systematic-sampling list\nalso matters: a repeating pattern that matches the interval can make\nthe selected students unusually alike.\n\nStratification samples within every stratum, while cluster sampling\nselects some clusters. A design can combine these features, such as\nstratifying schools before selecting schools and then their students.\n\n**Convenience sampling** might use students available in a nearby\nclassroom. Their inclusion probabilities are not supplied by a\nprobability design [@statcan2021nonprobability]. Similarly, an open\ninvitation describes how volunteers enter a dataset, rather than a\nprobability selection mechanism. After random selection, some selected\nstudents may decline to participate. Frame coverage, selection and\nsubsequent nonresponse are distinct parts of the account.\n\nGroups also enter three different parts of a study. Clustered data\ndescribe relationships among observations, such as students sharing a\nschool. Cluster sampling selects groups into the sample. Cluster\nrandom assignment allocates participating groups to conditions. The\nsame study may use more than one of these features, so identifying\ngrouped observations alone does not establish how groups were selected\nor assigned.\n\nSelection and dependence matter when a sample supports a population\nsummary. If students have unequal inclusion probabilities, the\ncalculation can require weights to account for how they were selected.\nIf observations are related, their contribution to precision differs\nfrom that of independent observations: Section 4.4 shows what selecting\nschools first and then students within them does to the spread of\nsample means. Chapter 3 develops\nuncertainty for paired and clustered observations and for\nfinite-population sampling without replacement. Section 4.1 below\nrepeats the simple random sampling procedure from this overview. Its\nlater waiting-time illustration uses a separate independent-observation\nmodel; an SE from that model does not apply unchanged to every sampling\nscheme.\n\n## Describing Distributions and Groups\n\nA **distribution** describes how a variable's values are arranged across cases.\nWhen it describes observed data, we call it an **empirical distribution**.\nWe begin with the distribution of final mathematics grades. A graph shows\nwhere students' values cluster and how far they spread; the numerical\nsummaries then give concise descriptions of those features.\n\n### See shape before reducing it\n\n\nA display is useful when its features answer the descriptive question.\n@tbl-ch02-graph-choices gives a small guide. A **histogram** counts\nquantitative values in adjacent intervals; changing the intervals can\nchange the visible shape. A **boxplot** marks the median inside a box\nspanning the middle half of the values. In the convention used here,\nwhiskers reach the most extreme observations within 1.5 IQRs of the\nbox ends, and more distant observations appear separately. These are\npotential outliers to investigate, not automatic errors. The plotting\nquartiles use R's convention, which can differ from a hand-calculation\nconvention in a small sample.\n\n| Data and question | Useful display | What to read |\n|:--|:--|:--|\n| Category frequencies | Bar chart; pie chart for a simple part-to-whole display | Counts or proportions with their denominator; bars ease comparisons |\n| Quantitative values | Dot plot or histogram | Individual values or counts in intervals; inspect gaps, tails and bin choices |\n| Center and spread across groups | Side-by-side boxplots with points where feasible | Medians, IQRs, overlap and potential outliers |\n| Smoothed shape | Density curve | Area across a range; height is not the probability of one exact value |\n| Two quantitative variables | Scatterplot | Paired positions; developed in Section 3.2 |\n\n: Graphs answer different descriptive questions. {#tbl-ch02-graph-choices tbl-colwidths=\"[27,31,42]\"}\n\n@fig-ch02-graph-gallery shows how those choices work with invented\nlearning records. Bars ease comparisons between category counts;\na pie chart emphasizes shares of a whole. The four displays of\ncompletion times use the same sixteen values. A **density curve**\nsmooths their shape, with the degree of smoothing controlled by a\nbandwidth. Its height is not the probability of one exact time.\nHere the smoother is shown only over feasible positive times; it is\nan exploratory summary rather than a fitted probability law. Individual\npoints keep the observations visible in a small sample.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Several views of invented learning records: category proportions and the distribution of completion times.](chapter_02_files/figure-html/fig-ch02-graph-gallery-1.png){#fig-ch02-graph-gallery fig-align='center' fig-pos='!ht' fig-alt='Bar and pie panels show counts four, seven and five for three learning formats. A histogram, density curve and boxplot show the same sixteen completion times, with a long right tail. The final panel shows individual times.' width=100%}\n:::\n:::\n\n\n@fig-grade-distribution displays all 395 final grades. The graph makes\nseveral features visible: the score is bounded between 0 and 20, centered near\n11, discrete rather than continuous, and has a visible group at zero.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Distribution of final mathematics grades for the 395 students. Dashed and dotted lines mark the mean and median, respectively.](chapter_02_files/figure-html/fig-grade-distribution-1.png){#fig-grade-distribution fig-align='center' fig-pos='!ht' fig-alt='A histogram of grades from zero to twenty is centered near eleven, bounded at both ends, and shows a visible group at zero.' width=100%}\n:::\n:::\n\n\nDescribe a distribution with four kinds of language:\n\n- **Shape:** symmetry or skewness, clusters, gaps, and discreteness.\n- **Center:** where a typical or balancing value lies.\n- **Spread:** how widely observations vary.\n- **Striking patterns and potential outliers:** values, clusters or gaps\n  needing contextual checking.\n\nAn unusual value is not automatically a mistake. Its recorded meaning and\nprovenance should be investigated before it is changed or removed.\n\nShape often begins with symmetry. A distribution is **skewed** when one\ntail stretches further from the center than the other, and the\ndirection of the skew is named by that longer tail. In a\n**right-skewed** (positively skewed) distribution most values sit\ntoward the lower end and the long tail reaches toward larger values, as\nwith waiting times or incomes; in a **left-skewed** (negatively skewed)\ndistribution the long tail reaches toward smaller values, as with\nscores on an easy test. The mean usually lies toward the longer tail.\nEvery value contributes to the mean, so a few far values in one tail\npull it their way, while the median depends only on the middle position\nof the ordered values.\n\n@fig-ch02-skew-centers shows three invented sets of 300 test scores on\na 0--100 scale. In the right-skewed panel the mean, 19.5477, lies above\nthe median, 13.7055. The left-skewed panel reflects those scores, so\nits mean, 80.4523, lies the same distance below its median, 86.2945; in\nthe symmetric panel the two lines nearly coincide. The ordering is a\ncommon pattern rather than a rule: a gap, a second cluster or many tied\nvalues on a discrete scale can break it, so read it together with the\ngraph.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Three invented distributions of 300 test scores. The long tail names the direction of a skew, and the mean lies toward it; dashed and dotted lines mark the mean and median.](chapter_02_files/figure-html/fig-ch02-skew-centers-1.png){#fig-ch02-skew-centers fig-align='center' fig-pos='!ht' fig-alt='Three histograms of invented test scores share an axis from 0 to 100. In the left-skewed panel most scores lie above 70 and a long tail reaches down toward 15; the dashed mean line, at 80.4523, lies left of the dotted median line, at 86.2945. The symmetric panel is centered near 50, with the two lines almost together. The right-skewed panel mirrors the left one: most scores lie below 30, a long tail reaches up toward 85, and the mean, 19.5477, lies right of the median, 13.7055.' width=100%}\n:::\n:::\n\n\nThe 395 grades in @fig-grade-distribution are left-skewed. Their long\ntail is the separate group of 38 zero grades at the lower bound, and\nthe dashed mean line lies below the dotted median line: the zeros pull\nthe mean down, while the median stays at the middle position. Section\n2.3 shows how each summary changes when that group is set aside.\n\nSkewness concerns the balance of the two tails; **kurtosis** concerns\ntheir weight. It compares how much of a distribution lies far from its\ncenter with a Normal curve of the same mean and standard deviation,\nthe bell-shaped probability model that Section 2.5 introduces. A\ndistribution with heavier tails than that curve has more values far\nfrom the center, and one with lighter tails, such as a flat, evenly\nspread distribution, has fewer. A symmetric distribution can still have\nheavy tails, so symmetry and tail weight are separate questions, and\nkurtosis does not measure how peaked a distribution looks. The grades\ngive a concrete case. Section 2.6 sets them beside a Normal curve with\ntheir own mean and SD: the curve expects 6.0136 grades at or below 0.5,\nyet 38 students have zero grades, so the lower tail is far heavier than\nthe curve's. Statistical software summarizes the two features with\ncoefficients. Skewness is negative for a left skew, near zero for a\nsymmetric distribution and positive for a right skew; excess kurtosis\nis near zero for a Normal distribution, positive when the tails are\nheavier and negative when they are lighter. This chapter reads skew\nfrom histograms and tail weight from tail counts set against a Normal\ncurve, and computes neither coefficient.\n\n### Five summaries with distinct jobs {#sec-ch02-summaries}\n\nWe use five summaries to describe center and spread: mean, median, variance,\nstandard deviation, and interquartile range. A small example shows what each\none contributes before we write the general formulas.\n\nConsider four invented completion times, already ordered: **1, 3, 3, and 5\nminutes**. Their sum is $1+3+3+5=12$. The **mean** shares that total equally\nacross the four observations, giving $\\bar x=12/4=3$ minutes. The **median**\nis the middle of the ordered values: here the two middle observations are both\n3, so their average is also 3 minutes.\n\n**Quartiles** locate the lower and upper quarters of an ordered distribution.\nThe first quartile $Q_1$ is approximately the 25th percentile and the third\nquartile $Q_3$ approximately the 75th. For these small examples, use the median\nof the lower half and the median of the upper half, excluding the overall\nmiddle observation when the number of values is odd. Here,\n\n$$\nQ_1=(1+3)/2=2,\\qquad Q_3=(3+5)/2=4,\\qquad\n\\operatorname{IQR}=4-2=2\\text{ minutes}.\n$$\n\nThe **interquartile range (IQR)** is the width of the middle half of the\ndistribution. Software may interpolate between ordered values instead; the\nlarge-data summaries in this chapter use R's default quartile convention.\nDifferent conventions can give slightly different answers in small datasets.\n\nTo describe spread around the mean, consider each observation's **deviation**:\nits value minus the mean. The deviations sum to zero because positive and\nnegative distances cancel. Squaring them preserves the contribution of each\ndistance to spread.\n\n| Observation $x_i$ | Deviation $x_i-3$ | Squared deviation $(x_i-3)^2$ |\n|-----------------:|-----------------:|----------------------------:|\n| 1 | $-2$ | 4 |\n| 3 | 0 | 0 |\n| 3 | 0 | 0 |\n| 5 | 2 | 4 |\n| **Sum** | **0** | **8** |\n\n: *Working from observations to squared-deviation spread.* {#tbl-worked-variance tbl-colwidths=\"[25,30,45]\"}\n\nThe conventional **sample variance** divides this sum of squared deviations\nby $n-1$, where $n$ is the number of observations. The **sample standard\ndeviation (SD)** is its square root:\n\n$$\ns^2=\\frac{8}{4-1}=\\frac83=2.6667\\text{ squared minutes},\\qquad\ns=\\sqrt{\\frac83}=1.633\\text{ minutes}.\n$$\n\nKeep the unrounded variance while taking its square root. Variance expresses\nspread in squared units; SD returns to the units of the observations and gives\na scale for their deviations from the mean.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n\\phantomsection\n```\n\nWhy does $n-1$ appear? Deviations from their own mean must sum to zero. Once\nthe first three deviations $-2,0,0$ are known, the last must be 2. Only three\ncan vary freely. More generally, estimating the center uses one **degree of\nfreedom**, leaving $n-1$. This explains how many deviations can vary freely\nunder the zero-sum constraint.\nThe formula can summarize a fixed set of observed values. Its further role\nin estimating a population variance, including the sampling reason for this\ndivisor, will be developed with estimation.\n\nWe can now write the general formulas. In $x_1,\\ldots,x_n$, the subscript\n$i$ identifies an observation. The symbol $\\sum$ means to add the indicated\nterms: $\\sum_{i=1}^n x_i=x_1+x_2+\\cdots+x_n$.\n\n$$\n\\bar{x}=\\frac{1}{n}\\sum_{i=1}^{n}x_i,\\qquad\ns^2=\\frac{1}{n-1}\\sum_{i=1}^{n}(x_i-\\bar{x})^2,\n$$\n\n$$\ns=\\sqrt{s^2},\\qquad \\operatorname{IQR}=Q_3-Q_1.\n$$\n\nFor any ordered dataset, the median is the middle observation when $n$ is\nodd and the average of the two middle observations when $n$ is even.\n@tbl-five-summaries brings the five summaries together.\n\n| Summary | Interpretive job | Units | Main caution |\n|:--------|:-----------------|:------|:-------------|\n| Mean $\\bar{x}$ | Arithmetic balance point | Original units | Can move strongly with skewness or extreme values |\n| Median | Ordered midpoint | Original units | Does not describe spread or tail shape |\n| Sample variance $s^2$ | Squared-deviation spread, using divisor $n-1$ | Squared units | Harder to interpret directly on the original scale |\n| Sample standard deviation $s$ | Scale of deviation around the mean | Original units | Can be influenced by extreme values |\n| IQR | Width of the middle half | Original units | Leaves the tails undescribed |\n\n: *Five selected summaries and the questions they answer.* {#tbl-five-summaries tbl-colwidths=\"[19,33,17,31]\"}\n\nThese five summaries differ from the **five-number summary**, which lists\nthe minimum, $Q_1$, median, $Q_3$, and maximum.\n\nA fixed set of values also has a mean squared deviation obtained by dividing\nby $n$: $8/4=2$ squared minutes here. Both conventions describe spread when\nclearly named. We use the conventional sample variance throughout, including\nwhen describing the 395 grades. The choice of divisor alone says\nnothing about how the observations were selected. The mean is also the\ncenter that makes the sum of squared deviations as small as possible:\naround 3 the four squared deviations sum to 8, around 4 they sum to\n$9+1+1+1=12$, and every other center gives a sum larger than 8.\n\n\n::: {#tbl-grade-summary .cell layout-align=\"center\" tbl-cap='Five numerical summaries of final mathematics grade.' tbl-colwidths='[32,24,28]'}\n::: {.cell-output-display}\n\n\n|Summary                   |   Value|Units                |\n|:-------------------------|-------:|:--------------------|\n|Mean                      | 10.4152|grade points         |\n|Median                    | 11.0000|grade points         |\n|Sample variance           | 20.9896|squared grade points |\n|Sample standard deviation |  4.5814|grade points         |\n|IQR                       |  6.0000|grade points         |\n\n\n:::\n:::\n\n\nThe mean grade is 10.4152 and the median is 11. The variance is 20.9896 squared\ngrade points; SD is 4.5814 grade points, and IQR is 6 grade points. The graph\nhelps us interpret these summaries, particularly the visible group at zero.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n### Equal means can hide different distributions\n\n@fig-same-mean shows three invented distributions with the same mean\nof 10. Their shapes and spreads are plainly different.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Three invented distributions share a mean of 10 but differ in shape and spread.](chapter_02_files/figure-html/fig-same-mean-1.png){#fig-same-mean fig-align='center' fig-pos='!ht' fig-alt='Faceted dot plots show a concentrated distribution around ten, a broad evenly spaced distribution, and a right-skewed distribution. Each has mean ten.' width=100%}\n:::\n:::\n\n\nThe mean gives a balance point, while the graph shows how the values are\narranged around it. Mean and SD are useful when the center and spread around\nthat center serve the question. Median and IQR are **resistant** summaries:\nthey change relatively little when a small number of extreme values changes.\nThey often describe a skewed distribution more clearly. In either case,\nthe graph supplies information about tails, gaps, and clusters.\n\nThe school grades show resistance on real data. The 38 zero grades\nform a separate cluster below the rest of the distribution\n(@fig-grade-distribution). @tbl-ch02-zero-grades compares each summary\nfor all 395 students with the same summary for the 357 students whose\ngrades are above zero. The comparison shows how each summary responds\nto one cluster. It does not treat the zeros as errors, and the\ndescription of all 395 students remains the primary one.\n\n```{=latex}\n\\Needspace{13\\baselineskip}\n\\phantomsection\n```\n\n\n::: {#tbl-ch02-zero-grades .cell layout-align=\"center\" tbl-cap='What 38 zero grades do to each summary' tbl-colwidths='[30,22,26,22]'}\n::: {.cell-output-display}\n\n\n|Summary                   | All 395 students| 357 without zero grades|   Change|\n|:-------------------------|----------------:|-----------------------:|--------:|\n|Mean                      |          10.4152|                 11.5238|   1.1086|\n|Median                    |          11.0000|                 11.0000|   0.0000|\n|Sample variance           |          20.9896|                 10.4187| −10.5709|\n|Sample standard deviation |           4.5814|                  3.2278|  −1.3536|\n|IQR                       |           6.0000|                  5.0000|  −1.0000|\n\n\n:::\n:::\n\n\nRemoving the cluster raises the mean by more than a grade point and\nroughly halves the variance; the SD falls from 4.5814 to 3.2278. The\nmedian does not move. The IQR narrows by one grade point because the\nlower quartile rises from 8 to 9: with almost a tenth of the students\nremoved from one end, even a resistant summary shifts a little.\nResistance is a matter of degree, and here the median and IQR change\nfar less than the mean and SD. Without the zeros the mean lies above\nthe median, so the left skew of all 395 grades (Section 2.1) comes\nfrom that one cluster. Section 3.4 returns to the same 38 students\nwhen it examines the absence--grade relationship.\n\n### Comparing groups while keeping their variation visible {#sec-ch02-groups}\n\nA single distribution can combine groups with different centers or\nspreads. In the school data, grades can be displayed separately for\nstudents who did and did not report an intention to pursue higher\neducation. Before doing that with 395 students, consider six invented\ntask-completion times from two training groups:\n\n| Group | Completion times (minutes) | Number of learners | Mean (minutes) |\n|:------|:---------------------------|-------------------:|---------------:|\n| A | 1, 3 | 2 | 2 |\n| B | 3, 3, 5, 9 | 4 | 5 |\n\n: *A small grouped dataset for describing center and spread* {#tbl-ch02-group-times tbl-colwidths=\"[15,39,24,22]\"}\n\nA **grouping variable** identifies the groups being compared. The\ntwo-category variable here is **binary**, or **dichotomous**. We can\nrepresent it by an **indicator**, also called a **dummy variable**:\nlet $D_i=1$ for Group B and $D_i=0$ for Group A. In row order,\n\n$$\n(D_1,\\ldots,D_6)=(0,0,1,1,1,1),\\qquad\n\\bar D=\\frac46=.6667.\n$$\n\nThe mean of a 0/1 indicator is the proportion in the coded-one category.\nReversing the coding changes that category and the direction used for\na difference between the group means; the observed groups remain the\nsame. With three or more categories, codes 1, 2 and 3 do not establish\nquantitative spacing. Later regression uses a declared set of indicators\nto represent such group membership.\n\nGroup B takes three minutes longer on average, but its learners are\nalso more spread out. The dotplot in @fig-ch02-groups keeps both\nfeatures visible. Some learners in different groups have the same time,\nand the group means summarize rather than replace those observations.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Completion times and group means in the invented six-learner example](chapter_02_files/figure-html/fig-ch02-groups-1.png){#fig-ch02-groups fig-align='center' fig-pos='!ht' fig-alt='Group A has times one and three, with mean two. Group B has times three, three, five, and nine, with mean five. The two three-minute learners in group B are shown separately. Diamonds mark group means.' width=100%}\n:::\n:::\n\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\nThe **grand mean** is the mean across all six learners:\n\n$$\n\\bar x=\\frac{1+3+3+3+5+9}{6}=\\frac{24}{6}=4\\text{ minutes}.\n$$\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\nWe can obtain it from the group means too, provided each group receives\nits learner count as a weight:\n\n$$\n\\bar x=\\frac{2(2)+4(5)}{2+4}=4.\n$$\n\nThe unweighted average $(2+5)/2=3.5$ would give the two groups equal\ninfluence despite their different sizes. That answers a different\naveraging question. When the aim is to describe all learners equally,\nthe larger group contributes more to the grand mean.\n\nThere is also variation **within** each group. For Group A, the squared\ndeviations from 2 are 1 and 1, so its sample variance is\n$2/(2-1)=2$ and its SD is 1.4142 minutes. For Group B, deviations from\n5 are $-2,-2,0,4$. Thus,\n\n$$\ns_B^2=\\frac{4+4+0+16}{4-1}=8,\\qquad\ns_B=\\sqrt{8}=2.8284\\text{ minutes}.\n$$\n\nKeeping each group's spread makes the comparison more informative than\nreporting two means alone. These calculations describe the groups; they\ndo not assume a common variance.\n\nFinally, one learner's distance from the grand mean can be understood\nin two steps. The nine-minute learner belongs to Group B, whose mean\nis five minutes. That learner is four minutes above the group mean,\nand the group mean is one minute above the grand mean:\n\n$$\n9-4=(9-5)+(5-4)=4+1=5\\text{ minutes}.\n$$\n\nIn words, the total deviation combines the learner's position\n**within the group** and the group's position relative to the\n**overall mean**. This elementary identity prepares the later\nanalysis of between-group and within-group variation. For now,\nthe displays, means, and separate SDs give the descriptive comparison.\n\nThe same reasoning applies to the school grades. The dataset records\nwhether each student reported an intention to pursue higher\neducation; this is a reported intention, not eventual enrollment.\n@fig-ch02-intention-groups shows every student's grade in the two\ngroups, with a boxplot for each group and a diamond at each mean. The\ndashed line separates passing grades, 10 or above, from the rest, so\nthe share of each group to its right is the passing proportion that\nSection 3.1 compares.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Final mathematics grades of the 395 students by reported higher-education intention. Boxes mark quartiles and medians, diamonds the group means, and the dashed line the pass mark between 9 and 10; points are jittered slightly to separate students with equal grades.](chapter_02_files/figure-html/fig-ch02-intention-groups-1.png){#fig-ch02-intention-groups fig-align='center' fig-pos='!ht' fig-alt='Horizontal boxplots with every student\\'s grade shown as a point. The 20 students with no intention have a box from zero to ten, median eight and mean 6.8, with six zero grades. The 375 students with the intention have a box from nine to fourteen, median eleven and mean 10.6, with 32 zero grades set apart from the rest of their group.' width=100%}\n:::\n:::\n\n\n```{=latex}\n\\Needspace{8\\baselineskip}\n\\phantomsection\n```\n\n\n::: {#tbl-ch02-intention-summary .cell layout-align=\"center\" tbl-cap='Final-grade summaries by reported higher-education intention' tbl-colwidths='[24,6,10,10,10,10,17,13]'}\n::: {.cell-output-display}\n\n\n|Group                    |   n|    Mean|     SD| Median| IQR|  Zero grades|  Passing|\n|:------------------------|---:|-------:|------:|------:|---:|------------:|--------:|\n|No intention             |  20|  6.8000| 4.8297|      8|  10| 6 (30.0000%)| 35.0000%|\n|Intends higher education | 375| 10.6080| 4.4934|     11|   5| 32 (8.5333%)| 68.8000%|\n|All students             | 395| 10.4152| 4.5814|     11|   6| 38 (9.6203%)| 67.0886%|\n\n\n:::\n:::\n\n\nThe two distributions differ in more than their centers. The middle\nhalf of the 375 students reporting the intention runs from 9 to 14\ngrade points; the middle half of the 20 without it runs from 0 to 10,\nand six of those 20, 30.0000%, have zero grades, against 8.5333% of the\nlarger group. The smaller group's mean of 6.8 lies below its median\nof 8 because its zeros pull the balance point down. The group\nmeans differ by 3.808 grade points, but the small group's wide spread\nand its zero cluster belong in the description as well.\n\nThe overall mean can be rebuilt from the group means, provided each\ngroup receives its size as a weight. With $j$ indexing the $J$ groups,\n$n_j$ the size of group $j$ and $\\bar x_j$ its mean, each product\n$n_j\\bar x_j$ recovers a group's total:\n\n$$\n\\bar x=\\frac{\\sum_{j=1}^{J}n_j\\bar x_j}{\\sum_{j=1}^{J}n_j}\n=\\frac{20(6.800)+375(10.608)}{20+375}\n=\\frac{136+3978}{395}=\\frac{4114}{395}=10.4152 .\n$$\n\nThis equals the mean of all 395 grades in @tbl-grade-summary. The\nunweighted average of the two group means, $(6.800+10.608)/2=8.704$,\ngives the 20 students as much influence as the 375: it answers a\nquestion about the two groups as groups, not about the students. With\ngroups this unequal the two averages differ by 1.7112 grade points;\nwith equal group sizes they would agree.\n\n### Common probability models\n\nAn empirical distribution describes recorded observations. A\n**probability model** instead describes possible observations and their\nprobabilities. A **random variable** gives a numerical description of a\npossible observation: uppercase $X$ denotes the variable, and lowercase\n$x$ an observed or specified value. A categorical observation can be\nrecorded by a label or represented by indicators; arbitrary category\ncodes do not become quantitative measurements.\n\nThe model mean, or **expectation**, $E(X)$ is a probability-weighted\naverage. With finitely many possible values,\n\n$$\nE(X)=\\sum_x xP(X=x).\n$$\n\nFor a Bernoulli response, $X=1$ means correct and $X=0$ incorrect. If\n$P(X=1)=p$, its mean is $0(1-p)+1p=p$. A correct-response probability\nof .7 therefore gives a model mean of .7, even though each individual\nresponse is either zero or one. The model variance,\n$\\operatorname{Var}(X)$, describes squared spread around that mean.\n@tbl-ch02-models connects several familiar variable forms to useful\nmodels [@nistDistributionGallery]. The mathematical properties in the\nlast column describe those models; an observed shape alone does not\nestablish that a model is appropriate.\n\n| Model and support | Meaning and educational example | Parameters and useful properties |\n|:--|:--|:--|\n| Bernoulli: $X=0,1$ | One correct/incorrect response | $P(X=1)=p$; $E(X)=p$, $\\operatorname{Var}(X)=p(1-p)$ |\n| Binomial: $X=0,\\ldots,m$ | Number correct in $m$ independent trials with common success probability; item heterogeneity can violate the model | $X\\sim\\operatorname{Bin}(m,p)$; mean $mp$, variance $mp(1-p)$ |\n| Categorical: one of $K$ labels | A student's selected learning format | Probabilities $\\pi_1,\\ldots,\\pi_K$ sum to one; each category has an indicator; numerical means of arbitrary labels are not meaningful |\n| Poisson: $X=0,1,\\ldots$ | Number of help requests during a specified observation period | $X\\sim\\operatorname{Pois}(\\lambda)$; mean and variance $\\lambda$; different exposures require explicit treatment |\n| Normal: real values | A continuous score model when its symmetric shape is adequate | $X\\sim N(\\mu,\\sigma^2)$; mean $\\mu$, SD $\\sigma$ |\n| Lognormal: positive values | A positive completion time under a multiplicative model | $\\log X\\sim N(\\mu_{\\log},\\sigma_{\\log}^2)$; median $\\exp(\\mu_{\\log})$, mean $\\exp(\\mu_{\\log}+\\sigma_{\\log}^2/2)$ |\n\n: Models for different kinds of possible observations. {#tbl-ch02-models tbl-colwidths=\"[23,40,37]\"}\n\nThe notation $\\sim$ means \"is distributed as.\" For example,\n$X\\sim\\operatorname{Bin}(m,p)$ states a Binomial model with $m$ trials\nand common success probability $p$. Here $m$ counts trials within one\nmodeled observation, while $n$ counts recorded cases. One Bernoulli\ntrial is a Binomial with $m=1$ and also a two-category categorical model.\nA Binomial count has an upper bound $m$; a Poisson count has no fixed\nupper bound. Observation periods matter for counts: a help-request\nrate for one lesson cannot be applied unchanged to a whole term.\nThe Lognormal describes positive values whose logarithms follow a\nNormal model; its log-scale SD differs from its original-scale SD.\n\nFor **discrete** outcomes, probabilities at the possible values add to\none. For a **continuous** variable, a density curve has total area one,\nand the probability of a range is its area. A curve height is not a\nprobability at one exact value. @fig-ch02-model-gallery shows masses\nand densities separately. The displayed axes show informative ranges;\nthey do not make a Normal, Lognormal or Poisson tail end at the plot\nboundary. Positive skew alone establishes none of these models.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Six probability models with declared parameters: masses for discrete outcomes and density curves for continuous outcomes.](chapter_02_files/figure-html/fig-ch02-model-gallery-1.png){#fig-ch02-model-gallery fig-align='center' fig-pos='!ht' fig-alt='Bernoulli probabilities at zero and one are .3 and .7. A Binomial with ten trials and success probability .7 peaks near seven. Three category probabilities are .2, .5 and .3. A Poisson with mean three has a right tail. A Normal with mean fifty and SD ten is symmetric; a Lognormal with log mean two and log SD 0.5 is positive and right-skewed.' width=100%}\n:::\n:::\n\n\nThe **cumulative distribution function (CDF)**,\n$F(x)=P(X\\le x)$, gives the probability up to a specified value.\nA **quantile** is a value reaching a stated cumulative probability.\nThese ideas let us ask both \"What proportion is below this score?\"\nand \"What score marks the upper 5%?\" The next subsection works both\nquestions with a Normal model.\n\nA brief preview connects this catalogue to later regression. The\n**logistic distribution** is continuous and symmetric, with location\n$\\mu_L$ and positive scale $s_L$ [@rCoreLogistic]:\n\n$$\nF(x)=\\frac{1}{1+\\exp[-(x-\\mu_L)/s_L]},\\qquad\nSD(X)=\\frac{\\pi s_L}{\\sqrt3}.\n$$\n\nIts scale is therefore different from its SD. With location zero and\nscale one, its S-shaped CDF is the inverse-logit mapping used in\nChapter 11 to turn a linear predictor into a probability. The binary\noutcome in logistic regression follows a Bernoulli model; it is not\nitself a continuous logistic variable.\n\n### Linear transformations, standardized values, and Normal areas\n\nChanging measurement units connects numerical summaries to the scale\non which we read them. Suppose $w_i=a+bx_i$: every value is multiplied\nby the same constant $b$, then shifted by $a$. Substitution into the mean\ngives\n\n$$\n\\bar w=\\frac1n\\sum_{i=1}^n(a+bx_i)\n=a+b\\bar x.\n$$\n\nEach deviation becomes $w_i-\\bar w=b(x_i-\\bar x)$. Squaring the\ndeviations therefore multiplies their sum by $b^2$, so\n\n$$\ns_w^2=b^2s_x^2,\\qquad s_w=|b|s_x.\n$$\n\nThe four completion times 1, 3, 3 and 5 minutes have mean 3\nminutes and SD 1.633 minutes. Converting to seconds multiplies the\nmean by 60 to give 180 seconds and the unrounded SD by 60 to give\n97.9796 seconds. Adding a constant moves the center without changing\nthe spread. A negative multiplier reverses the order, while its absolute\nvalue scales SD. A zero multiplier produces a constant with zero spread.\nThe corresponding model properties are\n\n$$\nE(a+bX)=a+bE(X),\\qquad\n\\operatorname{Var}(a+bX)=b^2\\operatorname{Var}(X).\n$$\n\nA **standardized score**, or **z score**, expresses distance from a\nspecified mean in SD units. In an invented commute sample with mean\n26 minutes and SD 6 minutes, a 38-minute commute gives\n\n$$\nz=\\frac{38-26}{6}=2.\n$$\n\nFor observed values, $z_i=(x_i-\\bar x)/s$. Subtracting the mean\nchanges the origin and dividing by a positive SD changes the scale.\nThe ordering and shape remain the same; standardizing skewed values\nleaves them skewed. Standardization is undefined when the SD is zero.\n\nA Normal model supplies the additional information needed for Normal\nprobability calculations. If $X\\sim N(\\mu,\\sigma^2)$, then\n\n$$\nZ=\\frac{X-\\mu}{\\sigma}\\sim N(0,1).\n$$\n\nThe **standard Normal distribution** has mean zero and SD one. Its\nsymmetry and density let us read central probabilities in\n@fig-standard-normal:\n\n$$\nP(|Z|\\le1)=.6827,\\quad P(|Z|\\le2)=.9545,\\quad P(|Z|\\le3)=.9973.\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Central Normal probabilities within one, two and three SDs.](chapter_02_files/figure-html/fig-standard-normal-1.png){#fig-standard-normal fig-align='center' fig-pos='!ht' fig-alt='Three identical standard Normal curves shade the areas between minus and plus one, two, and three. Their central probabilities are .6827, .9545 and .9973.' width=100%}\n:::\n:::\n\n\nThese give the familiar approximate 68%, 95%, 99.7% rule. The exact\ncentral 95% range uses approximately $\\pm1.96$ rather than exactly\n$\\pm2$. Let $\\Phi$ denote the standard Normal CDF and $\\Phi^{-1}$ its\nquantile function. Under a score model $X\\sim N(50,10^2)$, a score of\n65 is $(65-50)/10=1.5$ SDs above the mean. Therefore,\n\n$$\nP(X\\le65)=P(Z\\le1.5)=\\Phi(1.5)=.9332.\n$$\n\nAbout 93.3193% of values lie at or below 65 under this model. To find the\n95th percentile, begin with the standard Normal value\n$\\Phi^{-1}(.95)=1.6449$ and transform back, retaining its unrounded\nvalue during calculation:\n\n$$\nx_{.95}=50+10\\Phi^{-1}(.95)=66.4485.\n$$\n\nThe subscript on $x_{.95}$ marks a percentile, rather than a case\nnumber. About 95% of the model's values are at or below 66.4485.\nThe calculations use a supplied probability table or quantile value.\nApplying them to recorded scores requires a suitable Normal model;\ncomputing sample z scores alone does not establish that suitability.\n\nHow can we judge whether a Normal model suits recorded scores? Compare\nwhat the model predicts with what was observed. For the 395 grades,\ntake the Normal model with the observed mean 10.4152 and SD 4.5814.\n@fig-ch02-normal-check draws that model's density over a histogram of\nthe grades, scaled so that bar areas are proportions, and\n@tbl-ch02-within-k-sd compares the shares the model predicts within\none, two and three SDs of the mean with the shares observed. Its last\nrow compares the zero grades with the model's whole lower tail at or\nbelow 0.5, which also contains negative values that no grade can take.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Checking a Normal model against the 395 final grades. The curve is the Normal density with the observed mean and SD; the darker band marks one SD and the lighter band two SDs on each side of the mean.](chapter_02_files/figure-html/fig-ch02-normal-check-1.png){#fig-ch02-normal-check fig-align='center' fig-pos='!ht' fig-alt='A histogram of the grades, scaled to proportions, with a Normal curve centered near 10.4. Across the middle grades the bars and the curve broadly agree. At zero a bar of 38 students stands far above the curve, which expects between two and three students in that bar, and no student has a grade of one, two or three although the curve is above zero there. The curve also extends below zero, where no grade can occur.' width=100%}\n:::\n:::\n\n\n```{=latex}\n\\Needspace{9\\baselineskip}\n\\phantomsection\n```\n\n\n::: {#tbl-ch02-within-k-sd .cell layout-align=\"center\" tbl-cap='Observed and Normal-model shares of the 395 grades' tbl-colwidths='[17,25,14,14,14,16]'}\n::: {.cell-output-display}\n\n\n|Check       |Grade range        | Observed students| Observed share| Model share| Model students|\n|:-----------|:------------------|-----------------:|--------------:|-----------:|--------------:|\n|Within 1 SD |5.8337 to 14.9966  |               276|          .6987|       .6827|       269.6623|\n|Within 2 SD |1.2523 to 19.5781  |               356|          .9013|       .9545|       377.0274|\n|Within 3 SD |−3.3291 to 24.1595 |               395|         1.0000|       .9973|       393.9336|\n|Lower tail  |At or below 0.5    |                38|          .0962|       .0152|         6.0136|\n\n\n:::\n:::\n\n\nThe middle of the distribution agrees with the model: a share of .6987\nof the grades lies within one SD, against the model's .6827. The lower\ntail does not. Thirty-eight students have zero grades. The model expects\nonly 2.6173 grades in the zero bar of @fig-ch02-normal-check and 6.0136 in\nits whole lower tail at or below 0.5, a tail that includes probability\n.0115 below zero, where no grade can occur. The same cluster explains\nwhy only .9013 of the grades lie within two SDs rather than .9545: 38\nof the 39 grades outside that range are zeros. A Normal model could\ndescribe the typical grades reasonably well but would misstate any\nquestion about the lowest grades, and standardizing the grades would\nnot change that, since standardization preserves shape. With\nwhole-number grades, read the tail counts rather than small\ndifferences between the shares.\n\n## Describing and Interpreting Relationships\n\nDescribing a relationship means keeping two measurements together.\nThe useful summary depends on what those measurements represent. We\nfirst use two categorical variables from the school dataset to show how\ncounts become meaningful percentages. We then return to the chapter's\nabsence--grade question, which pairs two quantitative variables. The\nlast two subsections interpret the resulting description in the study\nsetting that produced it.\n\n### Counts and proportions for two categorical variables\n\nSection 2.4 compared the grades of students who did and did not report\nan intention to pursue higher education. We now count how many in each\ngroup passed. **Pass status** is defined here as a final mathematics\ngrade of 10 or higher. The following table counts every student once.\n\n```{=latex}\n\\Needspace{9\\baselineskip}\n\\phantomsection\n```\n\n\n::: {#tbl-ch02-intention-pass .cell layout-align=\"center\" tbl-cap='Higher-education intention and mathematics pass status for the 395 students' tbl-colwidths='[40,20,22,18]'}\n::: {.cell-output-display}\n\n\n|Intends higher education | Passed| Did not pass| Total|\n|:------------------------|------:|------------:|-----:|\n|No                       |      7|           13|    20|\n|Yes                      |    258|          117|   375|\n|Total                    |    265|          130|   395|\n\n\n:::\n:::\n\n\nA **two-way frequency table** groups cases by two categorical variables.\nHere the counts tell us that 20 students reported no intention to pursue\nhigher education and 375 reported that intention. Because the groups\nare so different in size, their raw passing counts are an incomplete\ncomparison.\n\nTo compare passing within the two groups, divide each passing count by\nthe size of its own group:\n\n$$\n\\frac{7}{20}=.350=35.0\\%,\\qquad\n\\frac{258}{375}=.688=68.8\\%.\n$$\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\nThese are **conditional proportions**: each describes passing among\nstudents meeting a stated condition. The difference is\n\n$$\n68.8\\%-35.0\\%=33.8\\text{ percentage points}.\n$$\n\nThus the passing proportion is higher among the students reporting a\nhigher-education intention. Percentage points express the subtraction\nof two percentages; the calculation above is not a relative percentage\nincrease. The left panel of @fig-ch02-conditional-bars draws the two\nconditional proportions.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The same 395 students read in two directions. Left: percent passing among each intention group. Right: percent reporting the intention among each pass-status group. Each bar's denominator is the group named beneath it.](chapter_02_files/figure-html/fig-ch02-conditional-bars-1.png){#fig-ch02-conditional-bars fig-align='center' fig-pos='!ht' fig-alt='Two bar charts. On the left, 35.0 percent of the 20 students without the intention passed, against 68.8 percent of the 375 with it. On the right, 97.3585 percent of the 265 students who passed reported the intention, against 90.0000 percent of the 130 who did not pass.' width=100%}\n:::\n:::\n\n\nChanging the question changes the denominator. The right panel of\n@fig-ch02-conditional-bars conditions on pass status instead: among\nthe 265 passing students, $258/265=97.3585\\%$ reported the intention,\nand among the 130 who did not pass, $117/130=90.0000\\%$ did. Read this\nway the two groups look alike, because 375 of the 395 students report\nthe intention whatever their result; read the first way, passing\ndiffers sharply between the intention groups. Both panels describe the\nsame table, and the word *among* names the conditioning group. For\nreference, $258/395=65.3165\\%$ of all students both report the\nintention and pass, and overall passing is $265/395=67.0886\\%$. These\nare descriptions of observed counts. Intention was not randomly\nassigned, so their difference alone does not establish a causal\neffect.\n\n### Form before coefficient\n\nFor two quantitative variables, a scatterplot shows one point for each\npaired observation. The four invented examples in @fig-relationship-forms\nshow how different relationships can look before we summarize them with\na coefficient.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Linear, curvilinear, and patternless relationships require different descriptions.](chapter_02_files/figure-html/fig-relationship-forms-1.png){#fig-relationship-forms fig-align='center' fig-pos='!ht' fig-alt='Four panels show a positive line, a negative line, a U-shaped curve, and no clear pattern.' width=100%}\n:::\n:::\n\n\nDescribe a scatterplot by:\n\n1. **form**: linear, curved, clustered, or otherwise structured;\n2. **direction**: increasing, decreasing, or mixed;\n3. **strength**: how tightly observations follow the form;\n4. **support**: where observations actually occur; and\n5. **unusual observations**: points or groups that may change the summary.\n\n*Nonlinear* or *curvilinear* describes form. It does not mean random,\nunimportant, or causal. A strong U-shaped relationship can have Pearson's\ncorrelation near zero because its negative and positive linear tendencies\ncancel.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n### Covariance and Pearson's correlation {#sec-ch02-correlation}\n\n**Covariance** describes how paired deviations vary together. Deviations\non the same side of their respective means give a positive product:\nboth values can be above their means or both can be below them.\nDeviations on opposite sides give a negative product. A value exactly\nat its mean contributes a zero deviation and hence a zero product.\n\nConsider measurements on four invented learners with $x=(1,3,3,5)$ practice hours\nand $y=(2,2,4,4)$ score points. Both means are 3. The deviations and their\nproducts are\n\n$$\nx_i-\\bar x=(-2,0,0,2),\\qquad y_i-\\bar y=(-1,-1,1,1),\n$$\n\n$$\n(x_i-\\bar x)(y_i-\\bar y)=(2,0,0,2).\n$$\n\nThe first pair shows why two below-mean values contribute positively:\n$(-2)(-1)=2$. The products sum to 4. Dividing by $n-1=3$ gives the sample covariance\n$s_{xy}=4/3=1.3333$ hour-points. The positive value agrees with the pattern: the\nlarger practice values tend to accompany the larger scores.\n\nFor any paired observations, the calculation is\n\n$$\ns_{xy}=\\frac{1}{n-1}\\sum_{i=1}^{n}\n(x_i-\\bar{x})(y_i-\\bar{y}).\n$$\n\nCovariance carries the product of the two measurement units. To express the\nlinear relationship on a common, unit-free scale, **Pearson's correlation**\ndivides covariance by the two SDs:\n\n$$\nr=\\frac{s_{xy}}{s_xs_y}.\n$$\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\nFor the four pairs, $s_x=\\sqrt{8/3}$ and $s_y=\\sqrt{4/3}$. Substitution gives\n\n$$\nr=\\frac{4/3}{\\sqrt{8/3}\\sqrt{4/3}}\n=\\frac{4}{\\sqrt{8\\times4}}=0.7071.\n$$\n\nThe units cancel as well: hour-points divided by hours times points is\nunit-free. If hours become minutes, both covariance and $s_x$ are multiplied\nby 60. Covariance becomes $60(4/3)=80$ minute-points, while $r$ remains .7071.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\nThe formula also has a useful squared-deviation form:\n\n$$\nr=\\frac{\\sum_i(x_i-\\bar{x})(y_i-\\bar{y})}\n{\\sqrt{\\sum_i(x_i-\\bar{x})^2\\sum_i(y_i-\\bar{y})^2}}.\n$$\n\nThe $n-1$ factors cancel between covariance and the two SDs. This connection\nbetween paired variation and squared deviations will also be useful in\nregression.\n\nA second connection uses standardized values. With\n$z_{xi}=(x_i-\\bar x)/s_x$ and $z_{yi}=(y_i-\\bar y)/s_y$,\n\n$$\nr=\\frac{1}{n-1}\\sum_{i=1}^n z_{xi}z_{yi}.\n$$\n\nPositive standardized products contribute to a positive linear association;\nnegative products contribute to a negative one. The divisor is $n-1$\nbecause these z scores use sample SDs. Correlation keeps its value under\npositive rescaling and reverses sign when one scale is reversed. If either\nSD is zero, the denominator is zero and correlation is undefined.\n\nCorrelation cannot leave the range from $-1$ to 1. Because\n$\\sum_i z_{xi}^2=\\sum_i z_{yi}^2=n-1$ and $\\sum_i z_{xi}z_{yi}=(n-1)r$,\nexpanding the square gives $\\sum_i(z_{xi}-z_{yi})^2=2(n-1)(1-r)$. A\nsum of squares cannot be negative, so $r\\le1$, and the same argument\nwith $z_{xi}+z_{yi}$, whose squares sum to $2(n-1)(1+r)$, gives\n$r\\ge-1$. The endpoints mark exact lines: $r$ reaches 1 only when\nevery standardized pair is equal, so the points lie exactly on a rising\nline, and $-1$ only when every pair is opposite, so they lie exactly on\na falling line.\n\nA correlation of zero can still accompany a perfectly patterned\nrelationship. For five invented pairs with $y=x^2$,\n@tbl-ch02-zero-correlation works the covariance, with means\n$\\bar x=0$ and $\\bar y=2$. The two outer pairs contribute $-4$ and\n$+4$, the next two $+1$ and $-1$, and the middle pair 0, so the\nproducts cancel: covariance and correlation are both 0, although\neach $y$ is determined exactly by its $x$. The U-shaped graph supplies\nthe relationship that the linear coefficient leaves out.\n\n```{=latex}\n\\Needspace{11\\baselineskip}\n\\phantomsection\n```\n\n| $x_i$ | $y_i=x_i^2$ | $x_i-\\bar x$ | $y_i-\\bar y$ | Product |\n|--:|--:|--:|--:|--:|\n| $-2$ | 4 | $-2$ | 2 | $-4$ |\n| $-1$ | 1 | $-1$ | $-1$ | 1 |\n| 0 | 0 | 0 | $-2$ | 0 |\n| 1 | 1 | 1 | $-1$ | $-1$ |\n| 2 | 4 | 2 | 2 | 4 |\n| **Sum** | **10** | **0** | **0** | **0** |\n\n: A perfect curve with zero correlation, in invented values {#tbl-ch02-zero-correlation tbl-colwidths=\"[16,22,20,20,22]\"}\n\n| Feature | Sample covariance $s_{xy}$ | Pearson correlation $r$ |\n|:--------|:-------------------------------|:--------------------------|\n| What it summarizes | Sum of paired-deviation products divided by $n-1$ | Standardized linear direction and strength |\n| Units | Product of the two variables' units | None |\n| Range | Unbounded; scale dependent | From $-1$ to $1$ |\n| Effect of changing measurement units | Magnitude changes | Unchanged by positive linear rescaling |\n| What it cannot reveal alone | Curvature, clusters, restricted support, or influential observations | The same omissions; near zero is not proof of no relationship |\n\n: *Covariance and Pearson's correlation have connected but different jobs.* {#tbl-covariance-correlation tbl-colwidths=\"[23,38,39]\"}\n\n\nThe graph remains essential: covariance and correlation summarize a linear\npattern, while a display shows curvature, clusters, sparse regions, and\nunusual observations.\n\n```{=latex}\n\\Needspace{8\\baselineskip}\n\\phantomsection\n```\n\n\n@fig-ch02-r-gallery makes direction and strength visible on common\naxes. Each panel contains 80 simulated pairs, and each label reports\nthe correlation actually computed from its displayed points. Moving\nfrom a strong negative to a strong positive coefficient changes the\nlinear pattern. The earlier U-shaped example remains a reminder that\none linear summary cannot describe every form of relationship.\n\nDifferent questions can motivate different correlations\n[@rCoreCorrelation]. **Ranks** replace each value by its ordered\nposition. Spearman correlation applies Pearson's calculation to those\nranks, so it can summarize a monotonic pattern that consistently rises\nor falls without being straight. For Kendall's coefficient, consider\ntwo cases at a time: their ordering is concordant if the case with the\nhigher value of one variable also has the higher value of the other,\nand discordant if the order reverses. A tie-aware version handles equal\nvalues. @tbl-ch02-correlation-types places these summaries beside\nPearson's coefficient.\n\n| Correlation | Useful question | Key qualification |\n|:--|:--|:--|\n| Pearson $r$ | How strongly do two quantitative variables follow a linear pattern? | Always inspect their scatterplot and influential values |\n| Spearman rank correlation $r_s$ | Do larger ranks on one variable tend to accompany larger ranks on the other? | Pearson correlation of ranks; describes monotonic rather than specifically linear association |\n| Kendall $\\tau_K$ | Do pairs of cases tend to have concordant rather than discordant ordering? | Use a version accounting for ties when needed; its scale is not numerically interchangeable with Pearson's |\n| Point-biserial correlation | How does a quantitative outcome relate to a binary group indicator? | Pearson correlation with a 0/1 variable; reversing the coding reverses its sign |\n\n: Different correlations summarize different patterns. {#tbl-ch02-correlation-types tbl-colwidths=\"[23,39,38]\"}\n\nWe use $\\tau_K$ for Kendall's coefficient to distinguish it from a\nlater mean-difference estimand. Point-biserial correlation is the\nordinary Pearson correlation when one variable is coded zero/one;\nreversing the group coding reverses its sign. A non-Normal histogram\nby itself does not determine which coefficient answers the relationship\nquestion. Inspect the paired pattern, variable meaning and unusual\nobservations before choosing a summary.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Six simulated scatterplots show different directions and strengths of linear association; labels report the sample correlation of each panel.](chapter_02_files/figure-html/fig-ch02-r-gallery-1.png){#fig-ch02-r-gallery fig-align='center' fig-pos='!ht' fig-alt='Six panels use common horizontal and vertical scales and equal sample sizes. They range from strongly negative through weak association to strongly positive. Each label gives its computed Pearson correlation.' width=100%}\n:::\n:::\n\n\n### Returning to absences and grades\n\nWe can now specify the **estimand** for the school comparison: the Pearson\ncorrelation between recorded absences and final mathematics grade among the\n395 students. An estimand is the precisely specified quantity\nsought by the question. Here it describes the linear relationship in this\ncomplete paired dataset.\n\n@fig-absence-grade preserves all 395 paired observations. Jitter makes\noverlapping integer-valued points visible; it does not change the values used\nfor the coefficient.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Recorded absences and final mathematics grade in the observational two-school dataset.](chapter_02_files/figure-html/fig-absence-grade-1.png){#fig-absence-grade fig-align='center' fig-pos='!ht' fig-alt='A jittered scatterplot shows most students below twenty absences, a concentrated set at zero absences and zero final grade, a few much larger absence counts up to seventy-five, and little overall linear pattern. The smooth rises from zero absences to low positive counts, then declines, with fewer students in the high-absence tail.' width=100%}\n:::\n:::\n\n\nMost students have relatively few recorded absences; a smaller number have\nmuch larger counts. The sample covariance is 1.2557 absence-count-by-grade-point\nunits, and Pearson's $r=.0342$. The coefficient is positive but small: the overall linear\nassociation among these students is close to zero. A **smooth** is a curve\nsummarizing nearby observations, helping us inspect a relationship's form.\nHere it rises from zero absences to the low positive counts, then declines\ngradually. The high-absence tail contains fewer students and supplies less\ninformation about the curve's shape. The overall linear coefficient and\nthe local curve therefore describe different features of the same data.\n\nBecause all 395 pairs defining this estimand are observed, the\ncalculated correlation gives its value for this dataset directly. Coding and measurement questions remain relevant to its meaning.\nExtending the result to students outside this dataset would require an\nappropriate sampling design or other explicit basis for that inference.\n\nAll 38 zero-grade students also have zero absences; 25 have positive\nsecond-period grades from 4 to 10. The accessible codebook leaves this\njoint pattern unexplained. A **sensitivity analysis** examines how a\nresult changes when an analytical choice changes. Section 2.3 showed\nwhat omitting these 38 records does to each summary of grade\n(@tbl-ch02-zero-grades); for the relationship, it gives $r=-.2131$\namong 357 students, compared with $.0342$ among all 395. Relative to the original means, the $(0,0)$ observations\ncontribute positive products of deviations; removing them also changes\nthe means used for every remaining deviation.\n\nThe omission is a diagnostic of a different record set, rather than\nevidence that the zeros are errors. Its 357-student correlation describes\na different set from the original estimand. We keep the full set primary\nand use the contrast to show why the unexplained coding pattern matters.\n\n### Relationships after linear adjustment\n\nA different descriptive question keeps the same cases and accounts for\na third variable. Consider separate, invented summaries of practice\ntime $x$, final score $y$, and baseline score $z$. Suppose the Pearson\ncorrelations are $r_{xy}=.6$, $r_{xz}=.5$, and $r_{yz}=.6$, all\ncalculated from the same complete set of students. These are stipulated\nsummary inputs, not correlations from the Portuguese school dataset.\n\nThe **partial correlation** of practice time and final score after\nlinear adjustment for baseline is\n\n$$\nr_{xy\\cdot z}=\\frac{r_{xy}-r_{xz}r_{yz}}\n {\\sqrt{(1-r_{xz}^2)(1-r_{yz}^2)}}\n=\\frac{.6-(.5)(.6)}{\\sqrt{(1-.5^2)(1-.6^2)}}\n=.433.\n$$\n\nTo understand the operation, imagine removing each variable's fitted\nstraight-line relationship with baseline score, then correlating the\ntwo remaining parts. Those remaining parts are **residuals**. Chapter 7\ndevelops fitted lines and their residual calculations, while Chapter 8\nextends the adjustment to several variables. The formula above gives\nthe descriptive calculation directly. In this example, adjustment\nreduces the correlation from .600 to .433.\n\nThe result describes association after this specified linear adjustment.\nIt does not establish a direct causal effect, remove every influence of\nbaseline, repair an ambiguous code or adjust for omitted variables.\nChoosing what to adjust for depends on the study question and design.\nA variable along the process from practice to the outcome, or one\naffected by both quantities, can change or distort the intended\ncomparison when included as a control.\n\nThe two descriptions therefore answer different questions: the\nzero-code check changes the cases being described; partial correlation\nkeeps the same cases and removes their linear relationships with a\nstated third variable. Neither operation replaces the other.\n\n### Interpret and report the relationship\n\nThe calculations now give us a description of the school dataset. To explain\nwhat it means, we connect the patterns to the way the students were observed\nand the measurements were made. This develops Chapter 1's design discussion\nthrough the data we have just examined.\n\nBefore reporting the relationship, ask what could have produced it.\nPrior academic difficulty, motivation, or illness could influence both\nattendance and final performance, providing common-cause explanations\nof the observed relationship. Earlier low grades might instead lead\nto disengagement and later absence, illustrating reverse direction.\nThese are possibilities to investigate. The recorded pairs alone do\nnot establish which explanation applies; we need the timing of the\nabsences and assessments and a design that supports the intended\ncomparison. Chapter 1, Section 3.2 explains how sampling and assignment\ncontribute to that design.\n\nAssociation in a causal comparison need not appear as a nonzero\nPearson correlation or a statistically significant result in the\nsense Chapter 1 defines. A near-zero overall correlation can conceal\ncurvature or different subgroup patterns. Its value summarizes the\nlinear relationship among the recorded measurements; it does not\nsettle what would happen if attendance were changed.\n\nWe can now answer the chapter's question about how absences and grades\nvary together in this set of students. A near-zero\nlinear correlation cannot settle the effect of changing attendance, and\nthe omission check shows why the coding context matters.\n\nA results paragraph can state both the primary description and the\nsensitivity:\n\n> Among the 395 students recorded in two secondary schools, recorded absences\n> and final mathematics grades showed almost no overall linear association\n> ($r=.0342$). Omitting the 38 unexplained zero-grade students as a diagnostic\n> gave a modest negative correlation ($r=-.2131$). The interpretation is\n> therefore sensitive to those values. These observational results do not\n> establish the effect of changing attendance or its importance for students\n> in other settings.\n\nEach qualification has a concrete role. The named students identify who was\ndescribed; *linear* identifies the feature summarized; the omission check\nmakes the sensitivity visible; and *observational* connects the\ninterpretation to the design. Rather than repeat a generic caution, explain the particular\nlimitation that matters for the result.\n\nFurther investigation would first seek an explanation of the joint zero\npattern in the codebook or source records. A newly discovered coding error\ncould be corrected and the calculations repeated with the change documented.\nA causal question about improving attendance would instead need a design\nthat supports that comparison. These are different research tasks, even\nwhen some data can be reused.\n\n### From describing these students to learning about others\n\nIn the school dataset, no attendance intervention was assigned, and\nthe accessible source does not establish random sampling from all\nsecondary students. These features bound what the results can tell us\nabout changing attendance or describing students elsewhere.\n\nThis still leaves a useful task: describing these students accurately.\nThe analysis identifies the grade distribution, a difference in passing\nproportions, and an absence--grade correlation that changes when a\nparticular set of values is omitted. Each result names what it\ndescribes and supplies a starting point for further investigation.\n\nIf we instead selected another sample from a defined population, its\ngrades and summaries could differ. We can begin to understand that\nrepeat-to-repeat variation using the same tools we have already used:\ngraphs, means, and standard deviations. The next section makes the\nrepetition explicit, first through an invented school system and then\nthrough a simulation whose behavior we can inspect.\n\n## From One Sample to Repeated Samples\n\nUntil now, our distributions have described measurements from the\nstudents or other cases in a dataset. A second kind of distribution\ndescribes what happens to a summary when the sample changes. Seeing\nthis distinction is an important step toward understanding uncertainty:\na mean calculated from one sample is useful, but another sample could\ngive a different mean.\n\n### From one sample to several sample means\n\nReturn to the invented school system introduced in Section 1.4 and the\nselection procedure described in Section 1.5. The system contains\n**20,000 enrolled students** on a specified date. We want their mean grade and select\n100 students by simple random sampling without replacement. Each\npossible set of 100 students has the same chance of selection, and a\nstudent can appear only once in that sample. This setting supplies a\nstated sampling design; it makes no additional claim about the\nselection of the 395 students in the Portuguese dataset.\n\nThe mean grade of all 20,000 students is a **parameter**: a numerical\ncharacteristic of the defined population. It is the estimand for this\nquestion. The mean calculated from the 100 selected students is a\n**statistic**: a numerical summary calculated from sample data. It\nprovides an estimate of the population mean. The contrast is simple:\nthe population mean is what we want to know, while the sample mean is\nwhat we can calculate from the selected students.\n\nSuppose the first sample mean is 10.6 grade points. If we could repeat\nthe same selection process, a second sample might give 11.2 and a third\n10.9. These are illustrative values, not results calculated from the\nPortuguese dataset. The population and its mean stay the same across\nthese imagined selections; the selected students, and therefore the\nsample means, change. Students selected in one sample can appear\nagain in another, because each repetition starts from the full\npopulation.\n\nThere are now two different sets of numbers to keep in view. Within\nthe first sample, the 100 individual grades have a distribution. Across\nrepetitions, the sample means 10.6, 11.2, 10.9, and so on have another\ndistribution. A dot in the first distribution represents a student's\ngrade; a dot in the second represents the mean from an entire sample\nof 100 students.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Repeating the same sampling process produces a distribution of sample means. The grade values are invented illustrations.](chapter_02_files/figure-html/fig-ch02-sampling-process-1.png){#fig-ch02-sampling-process fig-align='center' fig-pos='!ht' fig-alt='The same population of twenty thousand students supplies three repeated samples of one hundred. Their sample means are ten point six, eleven point two, and ten point nine. The individual grades within a sample and the sample means across repetitions form different distributions.' width=100%}\n:::\n:::\n\n\nThe **sampling distribution** of a statistic describes its possible\nvalues under a specified repetition of the sampling or data-generating\nprocess. Here the statistic is the mean, the sample size is 100, and\nthe process is simple random selection from the school system. Naming\nthese features matters: changing the sample size, or selecting\nschools first and then students within them, would change the\nrepetition we are considering, as Section 4.4 shows.\n\nIn practice, researchers usually have one sample. Repeated sampling\nhelps us reason about the variation behind that one result. Simulation\nmakes this idea visible by creating many samples under conditions we\nhave explicitly chosen.\n\n### See repeated sampling in a waiting-time model {#sec-ch02-repeated-sampling}\n\nWe now change from bounded grades to waiting times in an invented\nservice where people wait for assistance. The chosen model allows\nnonnegative waiting times without a fixed upper limit, making a\nright-skewed distribution and its repeated means easy to inspect.\nWe use an **exponential probability model** for\nindividual waiting times. This model allows many short waits and\noccasional long waits, giving a right-skewed distribution. We choose a\npopulation mean of 10 minutes and a population SD of 10 minutes. The\ntwo values are equal for this particular model; means and SDs generally\ndescribe different features and need not be equal.\n\nEach simulated waiting time is generated independently from that same\nmodel. This simplifies the example: actual service data might show\ndependence because several people arrive during the same busy period.\nThe simulation asks what happens under the specified independent\nprocess, rather than claiming that all waiting-time data behave this\nway.\n\nThe procedure is straightforward. First generate five waiting times,\nthen calculate their mean. Start afresh and do this 5,000 times,\nsaving one mean from each repetition. Next repeat the procedure with\n30 waiting times per sample, and finally with 100. The first panel of\n@fig-ch02-sampling-means shows the model for individual waits; each of\nthe other three summarizes **5,000 sample means**, not 5,000 individual\nwaiting times.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Individual waiting times and simulated sampling distributions of their mean. The first panel shows the exponential model for individual waits, with population mean and SD both 10 minutes, scaled to the counts expected among 5,000 waits. Each other panel contains 5,000 sample means from independent waits at the stated sample size, labelled with their SD, the empirical SE. The dashed line marks the population mean.](chapter_02_files/figure-html/fig-ch02-sampling-means-1.png){#fig-ch02-sampling-means fig-align='center' fig-pos='!ht' fig-alt='Four panels share an axis from zero to thirty-five minutes. The model for individual waits falls steadily from zero with a long right tail and SD 10. Means of five waits are broad and right-skewed, with SE 4.5395. Means of thirty are narrower and more symmetric, with SE 1.7878. Means of one hundred are tightly concentrated around ten and approximately bell-shaped, with SE 1.0076.' width=100%}\n:::\n:::\n\n\nThe three distributions of sample means are centered near 10 minutes,\nthe mean built into the model. With only five people per sample, the means vary\nconsiderably and the distribution still has a noticeable right tail.\nOne long wait can pull a small sample's mean upward. With 100 people\nper sample, individual long waits have less influence on the average,\nand sample means tend to be closer to 10.\n\nThe simulation also connects with the Normal model introduced earlier.\nThe first panel shows that the individual waits stay right-skewed, with\nSD 10 minutes, at every sample size, while the means concentrate and\nbecome more nearly bell-shaped as sample size increases. The variable\nbeing graphed has changed: it is now a mean calculated from several\nwaiting times. Neither collecting more cases nor standardizing their\nvalues makes the distribution of the individual waiting times Normal.\n\n### Standard error as the spread of sample means\n\nWe can summarize each histogram just as we summarized grades: find its\ncenter and its spread. The mean of the 5,000 sample means describes\nthe center. Their SD describes how much those means vary across the\nsimulated repetitions.\n\nThis introduces **standard error (SE)**: the standard deviation of a\nstatistic's sampling distribution. For a sample mean, SE describes\nvariation among sample means under the specified repetition. In this\nsimulation, the SD of the 5,000 means is an empirical approximation\nto that SE. Statistical procedures can also calculate or estimate SE\nfrom a model and the information in one sample; those calculations\nbuild on the meaning we can see here.\n\n\n::: {#tbl-ch02-sampling-summary .cell layout-align=\"center\" tbl-cap='Center and spread of the simulated sample means, in minutes' tbl-colwidths='[18,27,28,27]'}\n::: {.cell-output-display}\n\n\n| Sample size| Mean of sample means| Empirical SE| Model SE|\n|-----------:|--------------------:|------------:|--------:|\n|           5|              10.0141|       4.5395|   4.4721|\n|          30|               9.9626|       1.7878|   1.8257|\n|         100|              10.0027|       1.0076|   1.0000|\n\n\n:::\n:::\n\n\nThe empirical SE column in @tbl-ch02-sampling-summary comes from the\nsimulation. The model SE column gives the corresponding reference\nvalues for the independent waiting-time model; the general calculation\nis developed with statistical inference. Comparing the two columns\nchecks whether the simulation is behaving as expected. Their small\ndifferences reflect the finite number of simulation repetitions.\n\nThe panel labels of @fig-ch02-sampling-means place the two kinds of\nspread side by side. The **10-minute SD of individual waiting times**\nstays the same whatever the sample size, while the SE of the mean falls\nfrom 4.5395 minutes for samples of five to 1.0076 minutes for samples\nof 100. SD and SE therefore answer different questions: how much do\npeople's waiting times differ, and how much would the mean differ\nacross samples of the stated size?\n\nIt also helps to distinguish SE from the discrepancy in one particular\nsample. Suppose one sample of 100 has a mean of 11.3 minutes. Because\nthe model's population mean is known to be 10, this sample's estimation\nerror is $11.3-10=1.3$ minutes. **Sampling error** is the part of an\nestimate's departure from the population quantity that arises from\nobserving a sample rather than the whole population. Under this\nillustration's stated model, the 1.3-minute departure is attributable\nto sampling. Other samples can have positive or\nnegative errors. SE describes the spread across those possible\nresults; it is neither the signed error of this one result nor a bound\nthat every error must fall within. In an actual study the population\nmean is usually unknown, so the exact error of the observed estimate\nis unknown too.\n\nCoverage, nonresponse, and measurement error are separate sources of\nerror. A missing group in the sampling frame, a selected student's\nnonresponse, or an inaccurate measurement can change what an estimate\ndescribes. SE characterizes sampling spread under the stated process;\nit does not encompass every source of error in a study.\n\n### Sample size, repetitions, and sampling design {#sec-ch02-sample-size-design}\n\nThe simulation has two counts with different jobs. **Sample size** is\nthe number of people whose waits enter one mean: 5, 30, or 100.\n**Number of repetitions** is the number of independently generated\nsamples used to display how that mean varies: 5,000 for each condition.\n\nIncreasing sample size changes the statistic's sampling distribution.\nEach mean combines more observations, and in this independent model\nits spread becomes smaller. Increasing the number of repetitions gives\na clearer picture of the sampling distribution for the existing\nsample size. For example, generating 20,000 samples of five would make\nthe first histogram smoother and its empirical SE more stable. It\nwould still describe means based on five people, with an SE close to\n4.4721 minutes.\n\nThe model SE column shows a useful square-root regularity. Moving\nfrom 5 to 100 people multiplies sample size by 20, while SE falls\nfrom about 4.4721 to 1.0000, a reduction by about $\\sqrt{20}=4.4721$ rather\nthan by 20. Under the same independent model, quadrupling sample\nsize from 100 to 400 would halve SE from 1.0 to 0.5 minute. This\nexplains why substantial gains in precision can require substantial\nincreases in sample size.\n\nThese comparisons hold the model and the sampling process constant.\nSample size is not, however, the only feature of a design that sets\nthe spread of sample means. Suppose the invented school system's\n20,000 students attend 100 schools of 200 students each, and students\nin the same school tend to have similar grades. We compare two ways of\nselecting 100 students: a simple random sample from the whole\nregister, and a multistage sample that randomly selects 4 schools and\nthen 25 students within each selected school.\n@fig-ch02-design-effect repeats each design 5,000 times from the same\ninvented population.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Same sample size, different design. Each panel contains 5,000 means of 100 grades drawn from one invented population of 20,000 students in 100 schools. The dashed line marks the population mean, 10.4397, and the shading the range within one grade point of it.](chapter_02_files/figure-html/fig-ch02-design-effect-1.png){#fig-ch02-design-effect fig-align='center' fig-pos='!ht' fig-alt='Two histograms on a shared axis from seven to fourteen. Means from simple random samples of 100 students cluster tightly around 10.4, with SD 0.4397. Means from samples of 4 schools with 25 students each spread about twice as widely, with SD 0.8730, and many fall more than one grade point from the population mean.' width=100%}\n:::\n:::\n\n\nBoth designs select 100 students, and both sets of means center on the\npopulation mean of 10.4397. Their spreads differ. The multistage means\nhave SD 0.8730, about twice the 0.4397 of simple random samples, and\nonly .7396 of them fall within one grade point of the population mean,\nagainst .9778 for simple random samples. Twenty-five students from the\nsame school share that school's teaching and circumstances, so they\nsupply overlapping information about the whole system.\n\nThe **intraclass correlation (ICC)** describes how strongly units in\nthe same cluster resemble one another: it is the share of the\noutcome's variance lying between clusters. Because this invented\npopulation is complete, we describe its spread with the mean squared\ndeviation, dividing by the number of values. The total grade variance\nis 19.5885. Of this, 2.5546 is the variance of the 100 school means\naround the population mean, and 17.0339 is the average variance of\ngrades around their own school's mean. The two parts add to the total,\njust as a deviation split into within-group and group-to-overall parts\nin Section 2.4. Thus\n\n$$\n\\mathrm{ICC}=\\frac{2.5546}{2.5546+17.0339}=\\frac{2.5546}{19.5885}=.1304 .\n$$\n\nWhen each selected cluster contributes $m$ units, the variance of the\nsample mean is multiplied, relative to a simple random sample of the\nsame size, by about the **design effect**\n\n$$\n\\mathrm{deff}=1+(m-1)\\,\\mathrm{ICC}=1+(25-1)(.1304)=4.1299,\n$$\n\ncalculated from the unrounded ICC. The SE is multiplied by the square\nroot, $\\sqrt{4.1299}=2.0322$, close to the ratio of the two simulated\nSDs, 1.9856. Put another way, the 100 students carry about as much\ninformation about the population mean as $100/4.1299=24.2137$\nstudents selected independently. The formula shows its two\ningredients: when the ICC is 0, or when each cluster contributes a\nsingle unit ($m=1$), the design effect is 1, and a larger ICC or more\nunits per cluster make it larger. Here $m$ counts students per\nselected school, a different quantity from the number of Binomial\ntrials in Section 2.5. Chapter 3, Section 2.3, uses the design effect\nto calculate the SE of a clustered mean.\n\nThe same reasoning applies whenever observations share a source:\nstudents in the same class, or patients seen during the same busy\nperiod, supply less independent information than the same number of\nunrelated observations. More cases improve precision but leave a\nsystematic selection problem in place; a very large volunteer sample\nmay describe its volunteers precisely and still differ from the\npopulation of interest.\n\n### What stabilizes and what becomes more nearly Normal\n\nReturning to the waiting-time panels of @fig-ch02-sampling-means, two\nchanges are visible as sample size increases, and it helps to describe\nthem separately. First, the means concentrate more closely around 10.\nLarger samples are less likely to give a mean far from the model's\npopulation mean, because short and long waits tend to balance across\nmany observations. Second, the distribution of sample means becomes\nmore nearly symmetric and bell-shaped, while the individual waits in\nthe first panel stay right-skewed. Shape and spread are different\nfeatures: a narrow distribution need not be Normal, and a Normal\ndistribution can be wide or narrow.\n\nThese are interpretations of one explicitly stated simulation. A sample\nsize such as 30 is not a universal threshold; the behavior depends on\nthe distribution and dependence of the observations. The law of large\nnumbers gives the formal account of the concentration, and the central\nlimit theorem that of the shape, each under its own conditions. Chapter 3 states both results with those conditions and\ndevelops the general formulas, using the stated repetition to quantify\nuncertainty about an estimand from the one sample actually available.\n\n## Reading Bridge\n\nThis chapter began by reading cases, variables, layouts, denominators,\nand sample-selection procedures. We then turned measurements into\ndescriptions: the shape, center, and spread of one distribution, with\na skew named by its long tail and resistant summaries for a skewed or\nclustered one; group means with\nseparate spreads and a count-weighted grand mean; conditional\nproportions for two categorical variables, read in both directions;\nand a scatterplot with covariance and correlation for two quantitative\nones. Grouping indicators made category membership explicit.\nProbability models describe possible values; standardization and\nNormal areas connect measurement scales with probabilities, and\ncomparing a model's predictions with the recorded grades shows where\nit fits. Partial correlation adds a specified linear adjustment while\nretaining the same cases.\n\nWe then interpreted a description in its study setting and watched the\nsame tools describe sample means under a stated repetition. A sampling\ndistribution shows how a statistic varies, and its standard error\ndescribes that spread. One sample's sampling error is its particular\ndeparture attributable to sampling. Larger samples and more simulation\nrepetitions change different things, and the selection design matters\ntoo: selecting schools first and then students within them widens\nthe spread of sample means, and the design effect summarizes by how\nmuch.\n\nChapter 3 uses the stated repetition and its conditions to calculate\nuncertainty for an estimate from one sample, through standard errors,\nconfidence intervals, and tests. Chapter 4 uses group means, deviations,\nand spread to compare several groups with one-way and two-way analysis\nof variance.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n### Key terms {.unnumbered #sec-ch02-key-terms}\n\nUse this short reference to revisit the main concepts as needed. The\nPart One Concept Reference gives the broader reference and the\nprincipal home of each concept; familiar alternative labels appear\nthere when helpful.\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Case | The entity or measurement occasion described in a dataset. Depending on the study, a case may be a student, a class, or one measurement occasion for a student. |\n| Variable | A characteristic that can take different values across cases or occasions. A dataset records values of one or more variables for its cases. |\n| Quantitative variable (numerical variable) | A variable expressing an amount, including continuous measurements and discrete counts or scores. Its units and scale determine what numerical differences mean. |\n| Categorical variable | A variable whose values identify categories. Nominal categories have no intrinsic order; ordinal categories have an order; a binary variable has two categories. |\n| Population | The collection of units a question concerns. It may be the participating students themselves or a wider collection to which the findings might extend. |\n| Sample | A selected set of units from a larger collection. Calling a set a sample does not by itself explain how it was selected or which population it represents. |\n| Analysis sample | The units whose data contribute to a particular analysis. Eligibility, missing measurements, and exclusions can make this set and its denominator differ across analyses. |\n| Sampling design (sampling scheme) | The specified procedure for selecting a sample, including selection stages, grouping, and, for probability sampling, the selection probabilities. |\n| Simple random sampling | Selection in which every possible sample of the specified size has the same probability of being chosen. |\n| Empirical distribution (observed distribution; data distribution) | How the observed values are distributed across values or intervals, including their frequencies, center, spread, and shape. A probability model is a separate description of possible values. |\n| Skewness and kurtosis (left or negative skew; right or positive skew; tail weight) | Skewness describes asymmetry: in a right (positive) skew the long tail points toward larger values and the mean usually lies above the median; in a left (negative) skew the long tail points toward smaller values and the mean usually lies below the median. Kurtosis describes tail weight relative to a Normal distribution with the same mean and SD, not peakedness. |\n| Mean (arithmetic mean) | The sum of the numerical values divided by their count. Every included value contributes, so unusual values can shift the mean. |\n| Median | The middle value after ordering the data, or the average of the two middle values when the count is even. It describes the center by position. |\n| Quartile | A cut point dividing ordered data into quarters. The first and third quartiles mark approximately the lower and upper edges of the middle half; calculation conventions can differ. |\n| Interquartile range (IQR) | The third quartile minus the first quartile: the width of the middle half of the ordered data, expressed in the variable's original units. |\n| Variance | A measure of spread based on squared deviations from the mean. The usual sample variance divides their sum by $n - 1$ and is expressed in squared units. |\n| Standard deviation (SD) | The square root of the variance, expressing spread around the mean in the variable's original units. Applied to individual observations, it describes variation among their values; applied to a statistic's sampling distribution, it is the SE. |\n| Grand mean | The mean across all included cases. It equals the average of the group means weighted by their group counts, so larger groups contribute more. |\n| Degrees of freedom (df) | A count reflecting freely varying information after constraints or fitted quantities are taken into account. The $n$ deviations from their own mean sum to zero, leaving $n - 1$ free. |\n| Standardized value (z score) | A value minus a specified mean, divided by a specified standard deviation. It expresses distance in SD units; standardizing alone preserves the distribution's shape. |\n| Normal distribution (Gaussian distribution) | A symmetric, bell-shaped probability model described by a mean and standard deviation. The standard Normal has mean zero and SD one; observed data need not follow this model. |\n| Conditional proportion | The proportion in one category among cases satisfying a stated condition. Its denominator is the count in that conditioning group, such as students in one education-intention category. |\n| Covariance | A summary based on products of paired deviations from the two means. Its sign shows the direction of joint variation; its magnitude depends on both variables' units and spreads. |\n| Pearson's correlation (Pearson's r; product-moment correlation) | Covariance divided by the product of the two SDs. For variables with nonzero spread, it describes direction and strength of linear association on a scale from $-1$ to 1. |\n| Sampling distribution | The distribution of a statistic, such as a sample mean, across repeated samples generated by a stated sampling procedure or model. Repeated sample summaries in a simulation approximate this distribution. |\n| Sampling error | The part of an estimate's departure from the population quantity that arises from observing a sample rather than the whole population. It varies across repetitions, and its spread is the SE; coverage, nonresponse, and measurement error are separate. |\n| Standard error (SE) | The standard deviation of a statistic's sampling distribution under a stated sampling procedure or model. It describes spread across repeated sample summaries, distinct from individual-value SD and one sample's difference from the population quantity. |\n| Design effect (deff) | The factor by which a sampling design multiplies the variance of a statistic relative to simple random sampling of the same size. For a mean from equal clusters of $m$ units it is about $1+(m-1)\\,\\mathrm{ICC}$, where the intraclass correlation (ICC) is the share of outcome variance lying between clusters: units in one cluster supply overlapping information. |\n| Data matrix | A rectangular arrangement with cases in rows and variables in columns; $x_{ij}$ denotes case $i$ on variable $j$. |\n| Binary variable (0/1 coding) | A binary variable has two possible categories; a 0/1 coding marks membership or occurrence. Its sample mean is the proportion coded 1. |\n| Linear transformation | $Y=a+bX$ changes the center to $a+bE(X)$ and the SD to $\\lvert b\\rvert SD(X)$; a negative $b$ also reverses order. |\n| Bernoulli; binomial; categorical; Poisson; lognormal; logistic | Respectively a binary outcome, a count of successes in fixed independent equal-probability trials, one category, an event count under a specified rate model, a positive variable with Normal log, and a continuous symmetric distribution used here as a preview. Logistic regression later models Bernoulli outcomes. |\n| Density; cumulative distribution function; quantile | Density determines probability by area for a continuous variable; the CDF gives $P(X\\le x)$; a quantile is a value reaching the stated cumulative probability. |\n| Rank correlation; point-biserial correlation | Spearman uses ranks; Kendall summarizes concordance; point-biserial is Pearson correlation with one binary variable coded 0/1. Each addresses a specified relationship. |\n| Partial correlation | Correlation between two variables after their linear relationships with stated controls are removed by regression; it describes residual association and does not establish causal adjustment. |\n| Parameter | A numerical characteristic of a population or probability model, such as a population mean. A parameter may be the estimand; the question determines which quantity is sought. |\n| Statistic | A quantity calculated from sample data, such as a sample mean or proportion. The same statistic can summarize the sample or serve as an estimate for a wider target. |\n\n: Selected concepts for describing data and sampling variation {#tbl-ch02-key-terms tbl-colwidths=\"[28,72]\"}\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n### Further reading {.unnumbered #sec-ch02-further-reading}\n\n- OpenIntro connects graphical descriptions, numerical summaries, and\n  foundations for inference [@cetinkaya2024].\n- The ASA GAISE College Report emphasizes learning statistics through\n  questions, data, analysis, and interpretation [@asa2016gaise].\n- Moore, McCabe, and Craig develop the connections among descriptive\n  summaries, sampling, and inference [@moore2014].\n- NIST's distribution gallery and the R reference explain distribution\n  properties and correlation definitions [@nistDistributionGallery;\n  @rCoreCorrelation; @rCoreLogistic].\n- The UCI source supplies the student-performance data and codebook\n  [@cortez2008data].\n- Statistics Canada's introductory sampling overview compares probability\n  schemes and nonprobability selection\n  [@statcan2021probability; @statcan2021nonprobability].\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n## Exercises {.unnumbered #sec-ch02-exercises}\n\nThese exercises can be completed by hand with a standard calculator.\nEach supplies its own data or study description.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E01 -->\n### Exercise 1: Understand the cases and variables (Foundational) {.unnumbered #ex-ch02-01}\n\nAn invented clinic dataset contains information for individual visits. Some\npatients have several visits. The variables are patient ID, clinic, visit\ndate, waiting time in minutes,\nand whether the patient returned within 30 days. Of 1,240 visits, waiting time\nis missing for 36, return status is missing for 81, and 10 visits are missing\nboth.\n\nIdentify:\n\n1. the case represented by each observation;\n2. the observational unit or occasion;\n3. one identifier, one quantitative variable, and one categorical variable;\n4. why 1,240 visits should not be described as 1,240 independent patients;\n5. the error in a report that $1240-36-81=1123$ visits have both waiting\n   time and return status, and the correct complete-case denominator for\n   an analysis using both; and\n6. one question that must be answered before generalizing beyond these visits.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E02 -->\n### Exercise 2: See and summarize one distribution (Foundational) {.unnumbered #ex-ch02-02}\n\nEight invented completion times, in minutes, are:\n\n> 2, 4, 4, 4, 5, 5, 7, 9\n\n1. Sketch a dotplot or ordered display. From its shape, predict\n   whether the mean lies above or below the median, and explain why.\n2. The five summaries of these times are mean 5, median 4.5,\n   sample variance 4.5714, sample standard deviation 2.1381, and IQR\n   2, with quartiles taken as the medians of the lower and upper\n   halves, 4 and 6. Check your prediction from part 1. Then explain which\n   values the standard deviation and the IQR each use to describe spread.\n3. State the units of the variance and standard deviation.\n4. Suppose the 9 should have been recorded as 90. Before\n   recalculating, predict which of the five summaries in part 2 change\n   and which stay the same. Then recalculate the mean only, and use the\n   ordered values to check your prediction for the median and IQR.\n5. If the question asks for a resistant description of typical time\n   and spread, choose a pair of summaries and explain why, using part 4.\n   Name one feature that the chosen pair does not show.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E03 -->\n### Exercise 3: Interpret a Normal model and standardized value (Foundational) {.unnumbered #ex-ch02-03}\n\nA reference model for a score is Normal with mean 50 and standard deviation 10.\nA learner receives 38.\n\n1. Calculate and interpret the learner's z score.\n2. Distinguish this model-based standardization from using a sample mean and\n   sample standard deviation.\n3. Explain why transforming every observed score to z scores would not make a\n   skewed observed distribution Normal.\n4. A separate invented class of 20 records these quiz scores: 0, 0,\n   52, 58, 61, 63, 65, 66, 68, 70, 71, 72, 74, 75, 77, 79, 81, 84,\n   88, 95. Their mean is 64.95 and their SD is 24.468. Count the scores\n   within one SD and within two SDs of the mean, and compare those\n   shares with the Normal values .6827 and .9545. A Normal model with\n   this mean and SD gives $P(X<40)=.1539$. Would you use that model to\n   describe how many learners scored below 40? Explain, including what\n   the two zeros do.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E04 -->\n### Exercise 4: Compare a graph, covariance, and correlation (Foundational) {.unnumbered #ex-ch02-04}\n\nIn an invented study, a scatterplot of weekly practice hours and assessment score follows a clear\nU-shaped curve. The sample covariance is 0.8 hour-points and Pearson's\ncorrelation is .03.\n\n1. Why can the graph show a strong relationship while $r$ is near zero?\n2. What does the positive sign of the covariance summarize?\n3. Why is the covariance magnitude not directly comparable across measurement\n   units?\n4. If hours are converted to minutes, what happens to the covariance and to\n   Pearson's correlation?\n5. Write one descriptive sentence that reflects the pattern in the graph.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E05 -->\n### Exercise 5: Choose the denominator for a categorical comparison (Foundational) {.unnumbered #ex-ch02-05}\n\nIn the mathematics dataset, 375 students reported an intention to pursue\nhigher education: 258 passed and 117 did not. Of the 20 students without\nthat intention, 7 passed and 13 did not. Among students with the\nintention, 68.8% passed; among those without it, 35.0% passed.\n\n1. Name the denominator of each passing percentage, and explain why\n   their difference, 33.8, is a difference in percentage points\n   rather than a 33.8% relative increase.\n2. Among the 265 students who passed, 97.3585% reported the intention;\n   among the 130 who did not pass, 90.0000% did. Explain why these\n   denominators differ from those in part 1, and why the two pass groups\n   look alike when the counts are read in this direction.\n3. Suppose, as an invented change, that the dataset had held 200\n   students without the intention, passing at the same rate of\n   35%, with the 375 students who reported the intention unchanged.\n   Before calculating, predict which of the four percentages in parts 1\n   and 2 change. Then calculate the new percentage of passing students\n   who reported the intention, and explain the change.\n4. Explain why comparing 258 passes with 7 passes alone would be\n   misleading.\n5. Give one plausible reason for the association other than a causal\n   effect of the reported intention.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E06 -->\n### Exercise 6: Describe groups and their grand mean (Integrative) {.unnumbered #ex-ch02-06}\n\nAn invented task produces the following completion times, in minutes:\n\n- Group A: 2, 4 (mean 3).\n- Group B: 4, 4, 6, 10 (mean 6).\n\nAcross all six learners the grand mean is 5 minutes. The sample\nstandard deviations are 1.4142 minutes for Group A and 2.8284 minutes\nfor Group B.\n\n1. Display the observations by group and mark each group mean. What\n   does the display show that the two means alone do not?\n2. Explain, using the group sizes, why the grand mean lies closer to\n   Group B's mean than to Group A's.\n3. Explain why an unweighted average of the two group means gives a\n   different answer.\n4. Using the standard deviations and your display, describe the\n   difference between the groups in both center and spread. Which time\n   contributes most to Group B's larger standard deviation?\n5. Does the difference in group means establish that membership in\n   Group B caused a longer completion time? State the design\n   information you would need.\n6. Suppose Group B's times had instead been 5, 6, 6, 7, with Group A\n   unchanged. Before calculating, predict which of the values given\n   above change. Then calculate Group B's new standard deviation, and\n   explain why the same difference in group means is now easier to see\n   in the display.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E07 -->\n### Exercise 7: Interpret an incomplete observational dataset (Integrative) {.unnumbered #ex-ch02-07}\n\nA report asks: \"Among 260 volunteers in an online training course, how strong\nis the linear relationship between logged study minutes and final quiz score?\"\nIt documents measurements for each volunteer, 18 missing quiz scores, a Pearson\ncorrelation of .41 among 242 complete cases, and a scatterplot showing a\nmoderate positive linear pattern and two volunteers whose study times are\nmuch higher than those of the other volunteers.\nThe report concludes: \"More study time raises scores for online learners\neverywhere.\" The course platform's codebook is available, but the recruitment\nnotice and analysis script are not supplied.\n\n1. Identify the predictor and outcome, their observational unit,\n   and the group named by the research question. What precisely is the\n   estimand for that group?\n2. Explain why the calculated correlation uses 242 rather than 260 volunteers.\n   Does it describe the relationship among all 260 without further information\n   or assumptions about the missing scores?\n3. Interpret $r=.41$ alongside the scatterplot. Explain what the coefficient\n   summarizes and what inspecting the two unusually high study times could add.\n4. Identify two things you would seek in the codebook, methods, or analysis\n   details before interpreting the result more broadly. Explain why each\n   would matter.\n5. Explain the difficulty with \"raises scores\" and \"online learners everywhere.\"\n   Which features of the design and participant selection would be needed to\n   support those claims?\n6. Rewrite the conclusion for the 242 complete cases, preserving the\n   distinction from the original 260-volunteer question and the uncertainty\n   created by the missing scores.\n7. Suppose checking those two volunteers' measurements reveals a coding error.\n   Explain how you would correct and report the analysis. How would this\n   differ from asking a new causal question about assigning additional\n   study time?\n\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH02-E08 -->\n### Exercise 8: Distinguish individual variation from sampling variation (Integrative) {.unnumbered #ex-ch02-08}\n\nUse the same kind of independent waiting-time model as in Section 4,\nwith population mean and SD both 10 minutes. For this exercise, suppose\na simulation generates 5,000 samples of 100 waiting times each and\nsupplies the following illustrative results: the mean of the 5,000\nsample means is 10.02 minutes, their SD is 1.01 minutes, and one sample\nhas a mean of 11.3 minutes. These supplied results serve the exercise;\nthe chapter's particular seeded run has its own reported summaries.\nThe model SE for samples of 100 is 1 minute.\n\n1. Identify the population parameter being estimated and the statistic\n   calculated in each sample. What does one value in the simulated\n   sampling distribution represent?\n2. Explain the different meanings of the individual SD of 10 minutes\n   and the empirical SE of 1.01 minutes. What does comparing 1.01 with\n   the model SE of 1.00 help you check?\n3. Calculate the estimation error of the sample mean 11.3. Explain how\n   this one error differs from SE, and why its exact value is known in\n   this simulation but usually unknown in a study.\n4. Under the same independent model, what approximate SE would you\n   expect for samples of 400? Explain using the square-root regularity.\n   What would change instead if you kept sample size at 100 but\n   generated 20,000 simulation repetitions?\n5. A student concludes that individual waiting times must become\n   Normally distributed when the sample size is large. Use the\n   simulation to distinguish the distribution of individual waits\n   from the distribution of their sample mean.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n## References {.unnumbered #sec-ch02-references}\n",
    "supporting": [
      "chapter_02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}