{
  "hash": "041a7a7bfe1d29d6aa49f76c15fd199b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Evaluating and Comparing Confirmatory Factor Models\"\nauthor: \"Jinsong Chen\"\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\nformat:\n  pdf:\n    output-file: chapter_04.pdf\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    include-in-header:\n      - file: ../supplement/pdf-graphics-compat.tex\n      - text: |\n          \\setlength{\\parindent}{0pt}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{caption}\n          \\captionsetup[table]{position=above,format=plain,justification=raggedright,singlelinecheck=false,labelsep=newline,labelfont=bf,textfont=it}\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-tip title=\"Chapter box\"}\n**Central question:** How should a fitted CFA be evaluated, compared\nwith planned rivals, and revised without confusing development with\nindependent support; what do higher-order and bifactor representations\nadd, and what can fit not decide between them?\n\n**Prerequisites:** The covariance equation, restrictions, identification,\nML estimation, parameter metrics, and uncertainty from Chapters 1--3.\n\n**Record:** The exact twelve-indicator SLE fit from Chapter 3, plus a\nseparate six-indicator continuous microcase for compact comparisons.\n\n**Destination:** A reproducible evaluation, an explicit decision about\na tentative revision, higher-order and bifactor extensions, a retrospective\nknown-population audit, and bounded interpretations of reliability and\nscores. Fit does not establish construct reality, invariance, or causality.\n:::\n\n# From an estimated model to an evaluation record\n\n## Begin with what is already fixed\n\nChapter 3 supplied a converged, admissible estimate of M1-cross on\nSample B. The candidate was frozen using Sample A: twelve continuous\nindicators, three correlated factors, P4 additionally loading on Strategy,\nand S4 additionally loading on Belonging. All other cross-loadings and\nall residual covariances are zero. Factor variances equal one, and\nthe primary model is covariance-only. It has 29 free parameters and\n49 df.\n\nThis chapter reads the saved fitted object directly. It does not\nreconstruct the baseline from rounded estimates, change the item order,\nor substitute a simple-structure model. The inherited object includes\nthe data role, codebook, parameter table, software settings, warnings,\nand sample covariance under the normal-likelihood convention.\n\n```r\nhandoff <- readRDS(\n  \"chapter_03_chapter_04_handoff.rds\")\nfit <- handoff$fit\nlavaan::fitMeasures(fit, handoff$fit_measure_names)\n```\n\nThe code is short because the previous chapter preserved the record.\nIt is not a license to skip checking it. The render verifies the\ncandidate and Sample B hashes, package version, item order, and\nestimation gates before using any fit statistics.\n\n## Separate five questions\n\n| Question | Evidence | What a favorable answer does not establish |\n|:--|:--|:--|\n| Did the optimizer finish? | Convergence, gradients, warnings | Admissibility or adequacy |\n| Is the solution admissible? | Variances, covariance matrices, local rank | Small model discrepancy |\n| How large is global discrepancy? | Model test and fit profile | Absence of important local problems |\n| Where are discrepancies located? | Residual patterns and parameter diagnostics | A unique explanation |\n| Is interpretation defensible? | Content, estimates, uncertainty, analytic history | Validity for every score use |\n\nThese questions are related but not interchangeable. An optimizer can\nconverge to a badly fitting model. A globally favorable fit profile can\ncoexist with a questionable item or weakly identified parameter. A\nwell-measured factor can still be used in an inappropriate substantive\nanalysis.\n\nThe conventional output order often begins with the test statistic,\nbut our reading order starts with the model and estimation contract.\nFit measures belong to a specified analysis, not to the data set in\nisolation.\n\n## Keep the evidence roles visible\n\nSample A developed the loading candidate. Sample B estimates and\nevaluates that frozen candidate and its planned rivals. A new relation\nsuggested by B is exploratory in B, even if only one path is changed.\nSample C can assess that relation independently only after the changed\nspecification is frozen. All three samples have 360 cases from the same\ndocumented synthetic continuous population; no new seed is selected to\nobtain a preferred teaching outcome.\n\nThe six-indicator donor microcase is separate. Its 500 newly generated\ncontinuous records illustrate four model specifications and transparent\nlikelihood comparisons. They are not a recoded version of the donor's\nordinal observations and cannot borrow the SLE samples' development\nor confirmation status.\n\n# What estimation is fitting: one continuous ML family\n\n## Reconstruct the discrepancy before interpreting it\n\nWrite the implied covariance as\n\n$$\n\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)\n=\\boldsymbol\\Lambda\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}\n+\\boldsymbol\\Theta.\n$$\n\nFor $p$ continuous outcomes and the declared sample covariance,\n\n$$\nF_{\\mathrm{ML}}=\n\\log|\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)|\n+\\operatorname{tr}\\{\\mathbf S\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)^{-1}\\}\n-\\log|\\mathbf S|-p.\n$$\n\nThe first two terms depend on the model. The remaining terms make the\ndiscrepancy zero when the implied covariance equals the observed one.\nThe fitted value is the minimum over the specified parameter space,\nnot necessarily a small number by any substantive standard.\n\nIn our normal-likelihood analysis, $\\mathbf S=\\mathbf S_N$ uses\ndivisor $N$, and the model statistic is\n\n$$\nT_M=N\\widehat F_{\\mathrm{ML}}.\n$$\n\nFor M1-cross, the reconstructed discrepancy is\n0.134653; multiplying by 360 gives\n48.475. The calculation agrees with the stored\nsoftware statistic. This check catches mismatched divisors, a wrongly\nordered matrix, or an incorrect dimension term before those mistakes\npropagate into fit-index calculations.\n\n```r\nS <- lavaan::lavInspect(fit, \"sampstat\")$cov\nSigma <- lavaan::fitted(fit)$cov\np <- ncol(S)\nFml <- determinant(Sigma, logarithm = TRUE)$modulus +\n       sum(diag(solve(Sigma, S))) -\n       determinant(S, logarithm = TRUE)$modulus - p\nas.numeric(nrow(handoff$input$x) * Fml)\n```\n\n## Do not mix normal, Wishart, and robust conventions\n\nR's ordinary sample covariance uses divisor $N-1$. With raw-data\nnormal ML, `lavaan` handles conversion to divisor $N$ internally.\nWishart ML uses an $N-1$ covariance and test multiplier. The\n[official estimator documentation](https://lavaan.ugent.be/tutorial/est.html)\nexplains this distinction. A small difference between test statistics\ncan be a convention difference rather than a scientific disagreement.\n\nChanging an observed unit can leave ML discrepancy unchanged when\nthe entire model and all restrictions are transformed consistently.\nLeaving a raw-loading equality unchanged after changing an item's\nunit is not such a transformation. Scale invariance is conditional\non comparing equivalent model specifications.\n\nThe present calculations use conventional ML throughout. Later robust\nML procedures adjust standard errors and tests for particular forms\nof nonnormality; one cannot subtract two displayed scaled statistics\nand assume an ordinary difference test. FIML later handles missing\ncontinuous observations under stated missingness and model assumptions.\nNeither topic supplies a categorical-indicator measurement model,\nwhich is outside this series' present scope.\n\n## Large-sample properties are conditional\n\nConsistency concerns increasing sample size under identification and\nother appropriate conditions, not merely increasing the number of\nindicators. Asymptotic normality of estimates and chi-square references\nare approximations, not guarantees for every finite sample or boundary\nconfiguration. More indicators can add information, but also add\nparameters, content heterogeneity, and possible misspecification.\n\nDifferent starts need not always converge to the same optimum. Negative\nresidual variances, singular factor covariance matrices, or very large\nstandard errors call for investigation. Here all planned SLE and\ndonor-model fits pass the recorded convergence and admissibility gates.\nThat makes ordinary evaluation interpretable; it does not predetermine\nthe evaluation's conclusion.\n\n# Read global fit as a profile\n\n## The exact-fit null\n\nThe covariance-only null is that there exists an admissible parameter\nvector such that\n\n$$\nH_0:\\boldsymbol\\Sigma_{\\mathrm{population}}\n=\\boldsymbol\\Sigma(\\boldsymbol\\vartheta).\n$$\n\nUnder regularity and the conventional ML assumptions,\n$T_M\\ \\dot\\sim\\ \\chi^2_{df_M}$ when that null holds. The dot\nmarks an asymptotic approximation. The df refer to distinct covariance\nrestrictions after identification and parameter accounting, not\n$N$ minus the number of regression coefficients.\n\nFor M1-cross, $T_M=$ 48.475 on 49 df, with\n$p=$ 0.494. We fail to reject exact fit under\nthis test. We do not “accept the true model.” Sampling variability,\npower, alternative covariance-equivalent models, and departures not\nwell detected by the test remain relevant.\n\nLarge samples can detect small fixed discrepancies. That is not a\nreason to declare the test untrustworthy solely because $N$ is large;\nit is a reason to separate evidence against *exact* fit from the\nmagnitude and consequences of the discrepancy. Conversely, a small\nsample can fail to reject a consequential departure.\n\n## RMSEA: discrepancy per degree of freedom\n\nFor the present $N$ convention,\n\n$$\n\\widehat{\\mathrm{RMSEA}}\n=\\sqrt{\\max\\left\\{\\frac{T_M-df_M}{N\\,df_M},0\\right\\}}.\n$$\n\nUnder the commonly taught $N-1$ convention, replace $N$ by $N-1$.\nState which calculation is being used. The numerator estimates a\nnoncentrality contribution; it is truncated at zero when $T_M\\leq df_M$.\nThus RMSEA equal to zero does not require zero residuals or $T_M=0$.\n\nThe interval is obtained by inverting a noncentral chi-square reference\nand transforming its noncentrality limits onto the RMSEA scale. A\n90% interval is conventional in this literature, whereas the parameter\nintervals in Chapter 3 were 95%. These different levels should be\nlabelled, not silently mixed.\n\nFor M1-cross, RMSEA is 0.000, with 90% interval\n[0.000,\n0.034]. The zero estimate arises because\nthe test statistic is slightly below its df. The nonzero upper limit\nexpresses uncertainty about population approximation error.\n\nLow-df models can have unstable RMSEA estimates and broad intervals.\nA point estimate without its interval can conceal that uncertainty.\nNor does an interval imply equal plausibility of every value inside\nit. Explicit close-fit or not-close-fit hypotheses require stated\npopulation thresholds and their own tests; a threshold should not\nbe inferred retroactively from whichever endpoint looks favorable.\nThe interval and power perspective is developed by @maccallum1996.\n\n## CFI and TLI need a baseline\n\nFor continuous covariance analysis, the usual independence baseline\nfrees the observed variances and fixes covariances to zero. With twelve\nindicators, it has 66 covariance restrictions. It is not a competing\nsubstantive theory of the three factors; it supplies a reference for\nincremental improvement.\n\nOne conventional CFI expression is\n\n$$\n\\widehat{\\mathrm{CFI}}\n=1-\\frac{\\max(T_M-df_M,0)}\n{\\max(T_M-df_M,T_B-df_B,0)}.\n$$\n\nIf the denominator is zero, this expression requires special handling;\nit is not an ordinary ratio with a meaningful zero denominator. In\nour record the baseline statistic is\n1594.445 on 66 df, so that issue does not\narise. A high CFI means the model improves substantially relative to\nthis baseline under the stated correction, not that the construct\ninterpretation has been established.\n\nFor positive baseline discrepancy, TLI can be written\n\n$$\n\\widehat{\\mathrm{TLI}}\n=\\frac{T_B/df_B-T_M/df_M}{T_B/df_B-1}.\n$$\n\nUnlike a correlation coefficient, this formula need not remain between\nzero and one. A value slightly above one is possible when $T_M<df_M$;\nit is not “better than perfect measurement.” We retain the software's\nuncapped conventional value rather than altering it to look more\nfamiliar.\n\nBaseline dependence explains why a model with substantial local\ndiscrepancy can still have a high incremental index. The baseline\nmay be much worse. An index's favorable appearance must be interpreted\nrelative to the question it answers.\n\n## Compare the planned profiles\n\n\n::: {#tbl-cfa-planned-fit .cell layout-align=\"center\" tbl-cap='Sample B planned models, all using identical observations, indicators, and conventional normal ML. M1-cross is the inherited target.'}\n::: {.cell-output-display}\n\n\n|Model         |T       |df |p     |RMSEA |CI90           |CFI   |TLI   |SRMR  |\n|:-------------|:-------|:--|:-----|:-----|:--------------|:-----|:-----|:-----|\n|M0_simple     |135.142 |51 |<.001 |0.068 |[0.054, 0.082] |0.945 |0.929 |0.063 |\n|M1_cross      |48.475  |49 |0.494 |0.000 |[0.000, 0.034] |1.000 |1.000 |0.032 |\n|M2_orthogonal |121.189 |52 |<.001 |0.061 |[0.047, 0.075] |0.955 |0.943 |0.139 |\n|M3_equal      |54.948  |50 |0.293 |0.017 |[0.000, 0.039] |0.997 |0.996 |0.039 |\n|M4_one        |695.266 |54 |<.001 |0.182 |[0.170, 0.194] |0.580 |0.487 |0.134 |\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![RMSEA point estimates and 90 percent intervals for the planned models. No traffic-light cutoffs are imposed.](chapter_04_files/figure-html/fig-cfa-rmsea-1.png){#fig-cfa-rmsea fig-align='center' fig-pos='H' fig-alt='Horizontal intervals compare five planned SLE models. M1 and M3 have low estimates, M0 and M2 have larger estimates, and the one-factor model has the largest.' width=1088}\n:::\n:::\n\n\nThe profiles do not reduce to unanimous votes. M2-orthogonal has CFI\nabout .955 but SRMR about .139: appreciable standardized residual\ndiscrepancy remains despite a sizable improvement over independence.\nM3-equal has a favorable global profile even though the targeted\nloading-equality test is opposed. Global approximation and a focused\nparameter restriction are different questions.\n\nM1-cross has the most favorable overall balance among these\nprespecified alternatives. M0-simple leaves more discrepancy after\nforcing the two secondary loadings to zero. M4-one does not provide\na satisfactory broad covariance representation relative to these\nmulti-factor alternatives. These are judgments about this synthetic\nsample and candidate set, not universal thresholds for instrument\nvalidation.\n\n# Locate local discrepancy\n\n## Three residual scales\n\nThe raw covariance residual is\n\n$$\ne_{jk}=s_{jk}-\\widehat\\sigma_{jk}.\n$$\n\nIts unit is the product of the two indicators' units. A residual of\n10 has a different meaning for indicators with SDs 2 and 3 than for\nindicators with SDs 10 and 12. Two useful rescalings are\n\n$$\ne_{jk}^{(s)}=\\frac{s_{jk}-\\widehat\\sigma_{jk}}\n{\\sqrt{s_{jj}s_{kk}}},\n\\qquad\ne_{jk}^{(r)}=r_{jk}-\\widehat r_{jk}.\n$$\n\nThe first divides both observed and fitted covariance by *observed*\nSDs. The second separately converts each covariance matrix to a\ncorrelation matrix. They coincide off the diagonal when the observed\nand fitted variances match; otherwise they can differ. Neither is a\nresidual divided by its sampling standard error. A standardized residual\nin the variance-scaling sense is not automatically a $z$ test.\n\nFor this covariance-only ML model with free residual variances, fitted\nvariances closely reproduce observed variances, so the two off-diagonal\nrescalings are numerically very close. The script nevertheless calculates\nthem separately and checks the actual relationship rather than assuming\nit in every future model.\n\n## SRMR is a root mean square, not a mean absolute residual\n\nFor the covariance-based convention verified here,\n\n$$\n\\mathrm{SRMR}=\\sqrt{\\frac{2}{p(p+1)}\n\\sum_{j=1}^p\\sum_{k=1}^j\\left(e_{jk}^{(s)}\\right)^2}.\n$$\n\nThe average includes the diagonal and one triangle. Squaring gives\nlarge discrepancies extra influence, and the square root returns the\nscale to standardized covariance units. This differs from the mean\nabsolute residual and from Chapter 2's off-diagonal-only RMS.\n\nThe direct calculation gives 0.032,\nmatching the package SRMR. A small summary does not imply every cell\nis small: many near-zero cells can dilute a few larger ones. Mean\nstructures, multiple groups, and alternative estimators require their\nown checked conventions.\n\n## Read patterns in the twelve-item system\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![M1-cross standardized covariance residuals in Sample B, lower triangle including the diagonal. Numeric cells retain the sign of observed minus implied covariance.](chapter_04_files/figure-html/fig-cfa-local-residuals-1.png){#fig-cfa-local-residuals fig-align='center' fig-pos='H' fig-alt='A twelve-by-twelve lower-triangle residual display shows several negative residuals involving B4 and smaller positive and negative discrepancies elsewhere.' width=1088}\n:::\n:::\n\n\n\n::: {#tbl-cfa-local-pairs .cell layout-align=\"center\" tbl-cap='Eight largest absolute standardized covariance residuals. Raw and correlation residuals are shown separately.'}\n::: {.cell-output-display}\n\n\n|Item1 |Item2 |Observed |Implied |Raw     |Std    |Correlation |\n|:-----|:-----|:--------|:-------|:-------|:------|:-----------|\n|B4    |S3    |-0.371   |10.660  |-11.031 |-0.093 |-0.093      |\n|B4    |P3    |-0.270   |11.407  |-11.677 |-0.092 |-0.092      |\n|B4    |P4    |2.598    |10.883  |-8.285  |-0.088 |-0.088      |\n|B4    |P2    |1.789    |10.597  |-8.809  |-0.082 |-0.082      |\n|S3    |P2    |33.518   |24.903  |8.615   |0.072  |0.072       |\n|B3    |P2    |16.920   |11.118  |5.802   |0.070  |0.070       |\n|B3    |S3    |17.477   |11.183  |6.293   |0.069  |0.069       |\n|B4    |P1    |3.409    |8.554   |-5.145  |-0.061 |-0.061      |\n\n\n:::\n:::\n\n\nFor B4 and S3, the observed covariance is\n-0.371 and the implied covariance is\n10.660. Their raw residual is\n-11.031; scaled by the observed SDs it\nis -0.093. The model overpredicts\nthis pair's covariance. Several other negative cross-domain residuals\nalso involve B4, so it is reasonable to inspect that item rather than\ntreat the largest cell as an isolated software signal.\n\nB4 concerns connection to the institution as a whole, whereas B1--B3\nrefer more directly to peers, participation, and classroom voice.\nThat distinction suggests questions about content breadth and local\nheterogeneity. It does not uniquely imply that B4 should load negatively\non Planning. A cross-loading, an omitted narrower factor, a response\nprocess difference, and sampling fluctuation can leave overlapping\nresidual patterns.\n\nBefore modifying anything, check coding, distributions, data dependence,\nand whether the proposed relation changes the intended measurement\nmeaning. A globally favorable fit does not prohibit local investigation,\nbut it also does not require a modification merely to make every\nresidual smaller.\n\n# Compare planned rivals and test constraints\n\n## Establish nesting by exact restrictions\n\nFor compatible conventional ML fits, if restricted model $R$ is\nregularly nested in unrestricted model $U$,\n\n$$\n\\Delta T=T_R-T_U,\n\\qquad \\Delta df=df_R-df_U,\n\\qquad \\Delta T\\ \\dot\\sim\\ \\chi^2_{\\Delta df}\n$$\n\nunder the null restrictions and regularity conditions. The null is a\npopulation parameter restriction, not that the two observed fit\nstatistics are literally equal. The larger model cannot have a worse\noptimized likelihood if both optimizations have found the corresponding\noptima. That monotonicity alone does not establish the chi-square\nreference.\n\nFor M0 versus M1, set the P4-on-Strategy and S4-on-Belonging loadings\nto zero. For M2 versus M1, set all three factor correlations to zero.\nFor M3 versus M1, impose the one raw-loading equality. These are\ndifferent hypotheses with different df changes.\n\n```r\nlavaan::lavTestLRT(fit_M1, fit_M0, method = \"standard\")\n```\n\nThe compatible fits must use identical indicators, cases, data scale,\nmean structure, likelihood convention, and sampling assumptions.\nA smaller free-parameter count is not proof of nesting. The one-factor\nmodel's relation to a three-factor model passes through degenerate\nlatent covariance configurations, so we do not assign an ordinary\nchi-square difference test to M4 merely by subtracting df.\n\n\n::: {#tbl-cfa-planned-lr .cell layout-align=\"center\" tbl-cap='Eligible planned restrictions tested against M1 in Sample B. Values reproduce lavTestLRT under conventional ML.'}\n::: {.cell-output-display}\n\n\n|Comparison |Delta T |Delta df |p     |\n|:----------|:-------|:--------|:-----|\n|M0_vs_M1   |86.667  |2        |<.001 |\n|M2_vs_M1   |72.714  |3        |<.001 |\n|M3_vs_M1   |6.473   |1        |0.011 |\n\n\n:::\n:::\n\n\nThe two zero cross-loading restrictions cost\n86.667 chi-square units on two\ndf. The orthogonality restrictions cost\n72.714 on three df. Under this\nfamily, both are strongly opposed. The raw-loading equality costs\n6.473 on one df, with\n$p=$ 0.011. Its relatively favorable\nglobal fit profile did not make that particular restriction innocuous.\n\nFailure to reject a restriction would not establish equivalence.\nIt would leave the data insufficient to reject it at the chosen level\nunder that test. If practical equivalence is the question, specify a\nmeaningful discrepancy region and an appropriate procedure rather\nthan translate nonsignificance into equality.\n\n## The donor's four-model comparison, rebuilt continuously\n\nThe separate donor registry specifies the following models before\nthe continuous microcase is generated. All use fixed-factor scaling,\nfree residual variances, diagonal residual covariance, and conventional\nnormal ML.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n```\n\n| Model | F1 indicators | F2 indicators | Factor relation | Free / df |\n|:--|:--|:--|:--|:--|\n| D1 | Y1, Y2, Y3 | Y4, Y5, Y6 | Correlated | 13 / 8 |\n| D2 | Y1, Y2 | Y3, Y4, Y5, Y6 | Correlated | 13 / 8 |\n| D3 | Y1, Y2, Y3 | Y3, Y4, Y5, Y6 | Correlated | 14 / 7 |\n| D4 | Y1, Y2, Y3 | Y3, Y4, Y5, Y6 | Orthogonal | 13 / 8 |\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Three different one-parameter restrictions of D3. D1 and D2 are not nested in one another merely because both have eight df.](chapter_04_files/figure-html/fig-cfa-donor-nesting-1.png){#fig-cfa-donor-nesting fig-align='center' fig-pos='H' fig-alt='D3 branches to D1 by fixing lambda32 to zero, to D2 by fixing lambda31 to zero, and to D4 by fixing the factor covariance to zero.' width=1120}\n:::\n:::\n\n\n\n::: {#tbl-cfa-donor-fit .cell layout-align=\"center\" tbl-cap='Recomputed fit profiles for the independent continuous donor microcase, N = 500. These are not the archived donor\\'s numerical results.'}\n::: {.cell-output-display}\n\n\n|Model |T       |df |p     |RMSEA |CI90           |CFI   |TLI   |SRMR  |\n|:-----|:-------|:--|:-----|:-----|:--------------|:-----|:-----|:-----|\n|D1    |42.463  |8  |<.001 |0.093 |[0.067, 0.121] |0.974 |0.952 |0.053 |\n|D2    |334.998 |8  |<.001 |0.286 |[0.260, 0.312] |0.756 |0.542 |0.173 |\n|D3    |8.469   |7  |0.293 |0.020 |[0.000, 0.061] |0.999 |0.998 |0.016 |\n|D4    |17.980  |8  |0.021 |0.050 |[0.018, 0.081] |0.993 |0.986 |0.068 |\n\n\n:::\n:::\n\n\nD1 has CFI about .974 but RMSEA about .093, with a 90% upper limit\nabove .12. This is another reason not to label models by one index.\nD3's additional loading changes the covariance representation and\nsubstantially reduces discrepancy. The D1--D3 difference is\n33.994 on one df.\nIts result is computed for this new continuous microcase; it is not\ninherited from an older example with different data.\n\nThe two-indicator F1 block in D2 is not isolated: it is linked through\na freely estimated nonzero factor covariance to a factor with several\nindicators. That distinguishes it from Chapter 3's orthogonal isolated-\nblock counterexample. The actual numerical fits pass the local and\nadmissibility checks. A generic “two indicators always fail” rule\nwould miss the role of the rest of the model.\n\n## Score, Wald, and LR: three views of one restriction\n\nIn D2, $\\lambda_{31}=0$: Y3 has no F1 loading. D3 frees it.\nThe score test uses the restricted fit and asks whether the likelihood\nhas a slope suggesting that release. A modification index is the\ncorresponding local one-parameter score statistic. The Wald test uses\nthe unrestricted estimate and its uncertainty. The LR test fits both\nand compares their optimized likelihoods.\n\n\n::: {#tbl-cfa-test-triangle .cell layout-align=\"center\" tbl-cap='Three tests of the same D2-to-D3 loading restriction. All use one df, but their finite-sample numerical values differ.'}\n::: {.cell-output-display}\n\n\n|Test              |Statistic |df |\n|:-----------------|:---------|:--|\n|Score (MI in D2)  |231.629   |1  |\n|Wald (D3 loading) |360.919   |1  |\n|LR (D2 versus D3) |326.529   |1  |\n\n\n:::\n:::\n\n\nThe numbers are not interchangeable. Here the omitted loading is large\nenough that the local score approximation and unrestricted Wald\napproximation differ appreciably from the actual LR change. Their\nasymptotic relationship under regular local conditions does not\nrequire exact numerical agreement in every finite example.\n\nFor equality constraints, use an appropriate score-test routine such\nas `lavTestScore()` rather than assuming the ordinary zero-parameter\nMI table tests every labelled equality. The chapter's analysis does\nnot request MIs for the equality-constrained models, avoiding that\nmisinterpretation.\n\n## AIC and BIC compare eligible likelihoods\n\nFor log likelihood $\\ell(\\widehat{\\boldsymbol\\vartheta})$ and the\nsoftware's effective parameter count $q$,\n\n$$\n\\mathrm{AIC}=-2\\ell+2q,\n\\qquad\n\\mathrm{BIC}=-2\\ell+q\\log N.\n$$\n\nSmaller values indicate a relative preference within the eligible\nset under each criterion's tradeoff. Neither is a model-test $p$ value,\nan absolute adequacy index, or a guarantee that the preferred candidate\nis scientifically meaningful. AIC and BIC can disagree because they\npenalize complexity differently.\n\n\n::: {#tbl-cfa-information .cell layout-align=\"center\" tbl-cap='Likelihood and information criteria for planned Sample B models. Compare rows within this table, not against another sample or the donor microcase.'}\n::: {.cell-output-display}\n\n\n|Model         |logl      |npar |aic      |bic      |\n|:-------------|:---------|:----|:--------|:--------|\n|M0_simple     |-15249.32 |27   |30552.64 |30657.56 |\n|M1_cross      |-15205.98 |29   |30469.97 |30582.67 |\n|M2_orthogonal |-15242.34 |26   |30536.68 |30637.72 |\n|M3_equal      |-15209.22 |28   |30474.44 |30583.25 |\n|M4_one        |-15529.38 |24   |31106.76 |31200.03 |\n\n\n:::\n:::\n\n\nFor M1, the package count is 29. Substituting its log likelihood and\n$N=360$ reproduces both criteria. The same observations and outcomes\nmake these rows comparable; the one-factor model can enter this\nrelative likelihood comparison without being assigned a regular\nnested LR reference.\n\nD1 and D2 provide a compact nonnested comparison with the same six\noutcomes and 500 cases. Their AICs are\n14135.81 and\n14428.35, respectively. D1 has\nthe smaller value, but D3's profile still matters in the larger\ncandidate set. Being preferable to a poor alternative does not\nestablish adequate fit.\n\nDo not compare AIC/BIC across A, B, and C, across item subsets or\nparcels, or across incompatible likelihood definitions. Do not carry\nan EFA statistic with the same printed name into this table without\nchecking its exact definition. Eligibility precedes arithmetic.\n\n## Loading equality is not full parallelism\n\nM3 tests a raw-loading equality for P1 and P2. As a separate teaching\nsensitivity, V1 constrains their *residual variances* equal while\nleaving their loadings free. V1 is not retroactively listed as an\nA-frozen rival; it illustrates a different measurement restriction.\nIts LR difference from M1 is\n9.158 on one df, with\n$p=$ 0.002.\n\nThese restrictions concern different aspects of the model and are\nscale-dependent. Equal loadings plus equal residual variances are\nstill not a complete statement about parallel measurements when\nintercepts and means matter. Equal intercepts and the appropriate\ncommon true-score structure must also be considered. Nonsignificant\ntests would not establish exact parallelism, and a loading equality\nfor just one pair would not establish it for an entire instrument.\n\n# Extensions of the measurement model\n\n## Ask what accounts for the factor correlations\n\nM1-cross represents Planning, Strategy, and Belonging as three correlated\nfirst-order factors. That representation estimates their associations\nwithout claiming what produces them. A higher-order model asks a more\nrestrictive question: can one additional latent variable reproduce the\ncovariance among those first-order factors?\n\nLet $\\boldsymbol\\Lambda_l$ contain the item loadings on the first-order\nfactors. A one-factor higher-order model writes\n\n$$\n\\boldsymbol\\eta_l=\\boldsymbol\\gamma G+\\boldsymbol\\delta,\n\\qquad\n\\boldsymbol\\Phi_l\n=\\boldsymbol\\gamma\\boldsymbol\\gamma^{\\mathsf T}\n +\\boldsymbol\\Psi_h,\n$$ {#eq-cfa-higher-phi}\n\nwhere $G$ has unit variance for convenience and\n$\\boldsymbol\\Psi_h$ is diagonal in this version. Substitution into the\nmeasurement covariance gives\n\n$$\n\\boldsymbol\\Sigma\n=\\boldsymbol\\Lambda_l\n (\\boldsymbol\\gamma\\boldsymbol\\gamma^{\\mathsf T}\n  +\\boldsymbol\\Psi_h)\n \\boldsymbol\\Lambda_l^{\\mathsf T}\n +\\boldsymbol\\Theta.\n$$ {#eq-cfa-higher-sigma}\n\nThe components of $\\boldsymbol\\delta$ are first-order *disturbances*: the\nparts of Planning, Strategy, and Belonging not represented by $G$. They are\nnot indicator residuals. The diagram retains M1-cross's two frozen secondary\nitem loadings; changing those while adding $G$ would confound two model\nchanges.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Higher-order representation of the inherited SLE measurement model. General accounts for first-order factor covariances; first-order disturbances remain, and the P4-on-Strategy and S4-on-Belonging loadings are retained.](chapter_04_files/figure-html/higher-b3a894dfffdf.png){#fig-cfa-higher-order fig-align='center' fig-pos='H' fig-alt='One General factor predicts Planning, Strategy, and Belonging. Those three first-order factors predict their four indicators, with two dashed secondary loadings retained. Each first-order factor has a disturbance and each item has a residual.'}\n:::\n:::\n\n\nAn arrow from $G$ to a first-order factor represents a hypothesized common\nsource of covariance. Cross-sectional covariance data do not establish that\ncausal direction. Nor does a favorable fit show that $G$ has the intended\nsubstantive meaning.\n\n## Three correlations exactly determine three higher-order loadings\n\nWith three standardized first-order factors and positive nonzero\ncorrelations,\n\n$$\n\\phi_{12}=\\gamma_1\\gamma_2,\n\\qquad \\phi_{13}=\\gamma_1\\gamma_3,\n\\qquad \\phi_{23}=\\gamma_2\\gamma_3.\n$$\n\nMultiplying the first two equations and dividing by the third yields\n\n$$\n\\gamma_1^2=\\frac{\\phi_{12}\\phi_{13}}{\\phi_{23}},\\qquad\n\\gamma_2^2=\\frac{\\phi_{12}\\phi_{23}}{\\phi_{13}},\\qquad\n\\gamma_3^2=\\frac{\\phi_{13}\\phi_{23}}{\\phi_{12}}.\n$$ {#eq-cfa-higher-inversion}\n\nSigns are chosen consistently with the factor orientation. Each ratio must\nbe nonnegative and finite, and the standardized disturbance variances\n$1-\\gamma_j^2$ must be nonnegative. These are substantive parameter-space\nconditions, not algebraic decoration.\n\nFor the fitted Sample B M1-cross factor correlations, the calculation is:\n\n\n::: {#tbl-cfa-higher-loadings .cell layout-align=\"center\" tbl-cap='Closed-form higher-order coordinates from the fitted Sample B first-order factor correlations. These are standardized coordinates, not the SLE-generating population values.'}\n::: {.cell-output-display}\n\n\n|Factor    |Gamma |Disturbance |\n|:---------|:-----|:-----------|\n|Planning  |0.637 |0.594       |\n|Strategy  |0.637 |0.595       |\n|Belonging |0.454 |0.794       |\n\n\n:::\n:::\n\n\nThus $\\widehat\\gamma_1=$ 0.637,\n$\\widehat\\gamma_2=$ 0.637, and\n$\\widehat\\gamma_3=$ 0.454.\nFor example, the ratio for $\\widehat\\gamma_1^2$ is\n0.406 times 0.289, divided by\n0.289, which equals\n0.406.\n\nThe raw higher-order loadings printed by `lavaan` are on a different\nfirst-order disturbance metric when `std.lv = TRUE`; their standardized\nvalues are the coordinates that reproduce the fitted factor-correlation\nmatrix above. Mixing the raw and standardized columns would break the\nclosed-form check.\n\n## With three first-order factors, fit cannot choose between the forms\n\nThe correlated model estimates $m(m-1)/2$ first-order factor correlations.\nThe one-factor higher-order form estimates $m$ higher-order loadings. Their\ndifference is\n\n$$\n\\frac{m(m-1)}2-m=\\frac{m(m-3)}2.\n$$ {#eq-cfa-higher-count}\n\nFor $m=3$, the difference is zero. At a regular admissible solution, the\nthree correlations and three higher-order loadings are alternative\ncoordinates for the same information. The fitted records confirm this\nequivalence rather than treating matching fit as accidental.\n\n\n::: {#tbl-cfa-extension-fit .cell layout-align=\"center\" tbl-cap='Sample B fit profiles for M1-cross, its equivalent higher-order representation, and the nonnested orthogonal bifactor rival. The extension fits are didactic post-confirmation analyses, not Sample-A-frozen rivals.'}\n::: {.cell-output-display}\n\n\n|Model        |T      |df |p     |RMSEA |CI90           |CFI   |TLI   |SRMR  |\n|:------------|:------|:--|:-----|:-----|:--------------|:-----|:-----|:-----|\n|M1_cross     |48.475 |49 |0.494 |0.000 |[0.000, 0.034] |1.000 |1.000 |0.032 |\n|Higher_order |48.475 |49 |0.494 |0.000 |[0.000, 0.034] |1.000 |1.000 |0.032 |\n|Bifactor     |69.258 |42 |0.005 |0.042 |[0.023, 0.060] |0.982 |0.972 |0.046 |\n\n\n:::\n:::\n\n\nM1-cross and the higher-order form have 29 free covariance parameters,\n49 df, the same fitted covariance matrix to numerical tolerance, and the\nsame likelihood, AIC, and BIC. Therefore these data cannot decide which\nstory is preferable. Interpretation must come from the intended construct\nrepresentation and from evidence beyond the reproduced covariance.\n\nFor $m=4$, six factor correlations are replaced by four higher-order\nloadings, so the higher-order model imposes two restrictions. The\nfour-factor model introduced in Chapter 3 therefore supplies a testable\ncase; three first-order factors do not. More first-order factors do not make\nthe model automatically correct---they merely create restrictions that can\nbe evaluated.\n\n## A bifactor model allocates item covariance directly\n\nA standard bifactor model takes a different route. Every item loads directly\non one general factor and on one assigned domain-specific factor:\n\n$$\nY_{ij}=\\nu_j+\\lambda_{jg}G_i+\\lambda_{js}S_{is}+\\epsilon_{ij}.\n$$\n\nIn the version fitted here, $G$, Planning-specific, Strategy-specific, and\nBelonging-specific are mutually orthogonal, residual covariances are zero,\nand each item has exactly one specific loading. A specific factor represents\ncommon variance among its assigned items after the general factor is held\nconstant; it is not an item residual.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Orthogonal SLE bifactor model. General and the three domain-specific factors load directly on items; all four factors are mutually orthogonal and unshown loadings are zero.](chapter_04_files/figure-html/bifactor-134306dadbcc.png){#fig-cfa-bifactor fig-align='center' fig-pos='H' fig-alt='A General factor loads on all twelve items. Planning-specific, Strategy-specific, and Belonging-specific each load on their four assigned items. No factor covariance arrows are present, and each item has a residual.'}\n:::\n:::\n\n\nThe corresponding core syntax is explicit about orthogonality:\n\n```r\nGeneral =~ P1 + P2 + P3 + P4 + S1 + S2 + S3 + S4 +\n           B1 + B2 + B3 + B4\nPlanning_s  =~ P1 + P2 + P3 + P4\nStrategy_s  =~ S1 + S2 + S3 + S4\nBelonging_s =~ B1 + B2 + B3 + B4\nGeneral ~~ 0*Planning_s + 0*Strategy_s + 0*Belonging_s\nPlanning_s ~~ 0*Strategy_s + 0*Belonging_s\nStrategy_s ~~ 0*Belonging_s\n```\n\nFixed-factor scaling leaves 24 loadings and 12 item residual variances,\nso $t=36$ and $df=78-36=42$. Relative to M1-cross, the bifactor adds a\ngeneral loading for every item but also removes the three factor\ncorrelations and replaces the two M1 secondary loadings with exclusive\ndomain-specific assignments. It is therefore a distinct, nonnested rival,\nnot M1 plus twelve harmless arrows. An ordinary likelihood-ratio difference\ntest between the two is not licensed.\n\n\n::: {#tbl-cfa-bifactor-loadings .cell layout-align=\"center\" tbl-cap='Fully standardized bifactor loadings in Sample B. Specific-factor coefficients describe covariance remaining after the orthogonal general factor; they need not all be large or positive.'}\n::: {.cell-output-display}\n\n\n|Item |General |Factor      |Specific |p specific |\n|:----|:-------|:-----------|:--------|:----------|\n|P1   |0.322   |Planning_s  |0.701    |0.000      |\n|P2   |0.329   |Planning_s  |0.671    |0.000      |\n|P3   |0.262   |Planning_s  |0.637    |0.000      |\n|P4   |0.554   |Planning_s  |0.476    |0.000      |\n|S1   |0.672   |Strategy_s  |0.328    |0.007      |\n|S2   |0.628   |Strategy_s  |0.385    |0.005      |\n|S3   |0.611   |Strategy_s  |0.316    |0.007      |\n|S4   |0.889   |Strategy_s  |-0.180   |0.570      |\n|B1   |0.418   |Belonging_s |0.776    |0.000      |\n|B2   |0.344   |Belonging_s |0.716    |0.000      |\n|B3   |0.326   |Belonging_s |0.521    |0.000      |\n|B4   |0.194   |Belonging_s |0.411    |0.000      |\n\n\n:::\n:::\n\n\nThe bifactor fit converges, has a full-rank local derivative matrix, and has\npositive estimated residual variances. Yet the Strategy-specific loading for\nS4 is -0.180,\nwith $p=$ 0.570.\nThat weak negative coefficient is not a numerical failure, but it strains a\nsimple claim that every item carries a clear positive domain-specific signal.\nThe bifactor also has higher AIC and BIC than M1-cross. Greater flexibility\nand a familiar name do not guarantee a more useful representation.\n\n## Omega-hierarchical answers a score-specific question\n\nFor declared score weights $\\mathbf w$, the share of observed score variance\nattributable specifically to the bifactor general factor is\n\n$$\n\\omega_h(\\mathbf w)=\n\\frac{(\\mathbf w^{\\mathsf T}\\boldsymbol\\lambda_g)^2\\phi_{gg}}\n     {\\mathbf w^{\\mathsf T}\\boldsymbol\\Sigma\\mathbf w}.\n$$ {#eq-cfa-omega-h}\n\nFor the unit-weighted sum of all 12 items, the fitted bifactor gives\n$\\omega_h=$ 0.612 and total model-based omega\n$=$ 0.884. Thus about\n0.693 of the score's modeled\nreliable variance is attributed to the general factor. The remainder is\nmodeled reliable specific-factor variance, not automatically error.\n\nThese coefficients are conditional on this model, these weights, and this\nsample. A substantial $\\omega_h$ does not prove essential unidimensionality,\nvalidate the score interpretation, or erase the weak specific-loading\npattern. It answers a narrower variance-decomposition question.\n\n# Diagnose, revise, and revalidate\n\n## MI and EPC are conditional local diagnostics\n\nA modification index approximates the improvement in the model\nstatistic if one fixed parameter were released and the model re-estimated.\nThe expected parameter change, EPC, approximates the parameter's change\nunder that local release. The standardized EPC expresses a corresponding\nrescaled magnitude, with the exact scale depending on the parameter type.\n\nRead them together with the residual pattern, parameter meaning, and\nanalytic history:\n\n$$\n(\\mathrm{MI},\\mathrm{EPC},\\mathrm{standardized\\ EPC},\n\\mathrm{residual\\ pattern},\\mathrm{meaning},\\mathrm{status}).\n$$\n\nAn MI is not the exact LR change, a posterior probability of a missing\npath, or a guarantee that the proposed parameter is substantively real.\nSearching many MIs and reporting only the largest ordinary $p$ value\ndoes not retain the interpretation of a single prespecified test.\nThe [official modification-index guide](https://lavaan.ugent.be/tutorial/modindices.html)\nalso distinguishes the different standardized EPC columns.\n\n\n::: {#tbl-cfa-mi .cell layout-align=\"center\" tbl-cap='Largest one-parameter diagnostics for M1 in Sample B. No cutoff is used as an automatic release rule.'}\n::: {.cell-output-display}\n\n\n|Left     |Relation |Right |MI    |EPC    |Std.EPC |\n|:--------|:--------|:-----|:-----|:------|:-------|\n|Planning |=~       |B4    |4.949 |-1.300 |-0.126  |\n|P4       |~~       |S3    |4.252 |-6.996 |-0.138  |\n|Planning |=~       |S1    |3.741 |-1.064 |-0.106  |\n|S3       |~~       |B3    |3.671 |6.010  |0.115   |\n|S3       |~~       |B4    |3.608 |-8.506 |-0.111  |\n|S2       |~~       |B3    |3.125 |-3.977 |-0.108  |\n\n\n:::\n:::\n\n\nThe top suggestion is a negative B4 loading on Planning, with MI\n4.949 and EPC\n-1.300. It aligns with some negative\ncross-domain residuals involving B4. But institutional connection\nwording does not offer a compelling Planning mechanism. The numerical\nclue is therefore weaker than a justified measurement revision.\n\nBy contrast, the D2 microcase's missing F1 loading on Y3 was already\none of the registry's specified alternatives. A planned rival and a\nnewly discovered relation may be represented by the same software\noperation, yet have different analytic status.\n\n## A deliberately tentative one-path sensitivity\n\nFor teaching, we retain one tentative model, **R1-B4**, which frees\nPlanning's loading on B4 while leaving all other M1 restrictions\nunchanged. It has 30 free parameters and 48 df. This is a transparent\nsensitivity demonstration, not a recommendation to modify a favorable\nmodel whenever an MI is available.\n\nThe revision's syntax, rationale limitations, parent model, and handoff\nhash were frozen before Sample C was read. Only this one diagnostic\nrevision is fitted. We do not chase additional MIs, remove items,\nselect a new seed, or invent an explanation after seeing C.\n\nIn Sample B, the actual decrease in the model statistic is\n5.040 on one df, close to but not\nidentical to the MI. The estimated added loading is\n-1.318, with 95% interval\n[-2.468, -0.169].\nIts conventional same-sample LR $p$ value is\n0.025. Because this path was selected from\nthe diagnostics, that value is descriptive of the refit, not an\nunadjusted confirmatory discovery.\n\n## The frozen retest does not support the added path\n\n\n::: {#tbl-cfa-revalidation .cell layout-align=\"center\" tbl-cap='One frozen revision across its development and revalidation records. Compare models within B or within C; do not compare likelihood values across samples.'}\n::: {.cell-output-display}\n\n\n|Model |T      |df |p     |RMSEA |CI90           |CFI   |TLI   |SRMR  |\n|:-----|:------|:--|:-----|:-----|:--------------|:-----|:-----|:-----|\n|B_M1  |48.475 |49 |0.494 |0.000 |[0.000, 0.034] |1.000 |1.000 |0.032 |\n|B_R1  |43.435 |48 |0.660 |0.000 |[0.000, 0.029] |1.000 |1.004 |0.025 |\n|C_M1  |43.794 |49 |0.684 |0.000 |[0.000, 0.028] |1.000 |1.004 |0.026 |\n|C_R1  |43.750 |48 |0.648 |0.000 |[0.000, 0.029] |1.000 |1.003 |0.026 |\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The added B4-on-Planning loading in the sample that suggested it and in the untouched retest. Intervals are 95 percent conventional parameter intervals.](chapter_04_files/figure-html/fig-cfa-revision-1.png){#fig-cfa-revision fig-align='center' fig-pos='H' fig-alt='The added loading is negative in B with an interval below zero, but near zero in C with an interval spanning both signs.' width=1088}\n:::\n:::\n\n\nIn Sample C the added coefficient is\n0.124, with interval\n[-1.039, 1.287].\nThe LR improvement is only 0.043 on\none df, with $p=$ 0.835.\nThe candidate relation does not receive independent support in this\nretest. We retain M1-cross as the course's working measurement model\nand do not promote R1 to the final specification.\n\nThis is not proof that the population coefficient is exactly zero.\nIt is a bounded decision based on weak content justification, a\ndata-selected improvement in B, and no corresponding evidence in C.\nThe failed sensitivity remains in the report rather than disappearing\nfrom the analytic history.\n\n## What revalidation does and does not fix\n\nA held-out sample protects a specified retest from using the same\nsampling fluctuations that suggested the change. It does not repair\npoor content coverage, turn simulation into external validity, or\njustify unlimited searches in the held-out record. Once C is used to\nchoose further modifications, it becomes development evidence for\nthose decisions.\n\nRevalidation here means re-estimating and evaluating a frozen model\nstructure in independent observations from the same synthetic\npopulation. It does not mean holding every B estimate fixed as a\npredictive parameter value. That would be a different, more stringent\nout-of-sample prediction question requiring its own objective and\nevaluation protocol.\n\n```{=latex}\n\\Needspace{22\\baselineskip}\n```\n\n| Stage | Decision | Evidence role |\n|:--|:--|:--|\n| A | Retain three factors and two secondary loadings | Development |\n| Before B | Freeze M0--M4 and M1 target | Specification fixed |\n| B, Chapter 3 | Estimate M1 and audit its solution | Confirmation-record estimation |\n| B, Chapter 4 | Evaluate planned models; inspect local diagnostics | Planned evaluation plus labelled exploration |\n| Before C | Freeze tentative R1-B4 without further changes | Retest specification fixed |\n| C | Evaluate M1 and R1; do not search again | Independent synthetic revalidation |\n| Report | Retain M1; disclose unsupported R1 | Bounded conclusion |\n\n# Audit the frozen model against the known population\n\n## Reveal the generating feature only after the B/C sequence\n\nThe SLE records are synthetic, so the generating covariance is available to\nthe course author. It was deliberately withheld while the frozen B/C\nsequence was conducted. We now use it retrospectively to ask what the\nworking M1-cross representation misses. This audit cannot retroactively make\na diagnostic planned, and it does not authorize another model search.\n\nThe generating residual covariance between B1 and B2 is\n0.120 on the\nstandardized item scale (14.400\non the raw covariance scale). M1-cross fixes that relation to zero. A simple\nfour-indicator tetrad makes the restriction visible. In the generating\ncorrelation matrix,\n\n$$\nr_{12}r_{34}-r_{13}r_{24}\n=.712(.335)-.536(.370)=.0402,\n$$\n\nwhereas the fitted one-factor Belonging block imposes zero, apart from\nnumerical tolerance. The nonzero population tetrad identifies a specific\ncovariance restriction that global indices summarize but cannot name.\n\nNow that the generator is revealed, its first-order correlations also give a\nclean higher-order calculation:\n\n$$\n\\gamma_1^2=\\frac{.42(.30)}{.35}=.36,\n\\qquad\n\\boldsymbol\\gamma=(.60,.70,.50)^{\\mathsf T},\n\\qquad\n\\operatorname{diag}(\\boldsymbol\\Psi_h)=(.64,.51,.75).\n$$\n\nThese are **generating-population coordinates**, not the Sample B estimates\nin Section 6. Because three factor correlations can be reparameterized this\nway, the calculation does not show that a higher-order causal process\ngenerated the data; the documented SLE generator simply used a correlated\nfactor covariance matrix.\n\n## Population fitting separates displacement from sampling fluctuation\n\nFit the unchanged M1-cross model directly to the exact generating covariance\nmatrix. The optimizer then finds the population-ML, or pseudo-true,\ncoordinates under that misspecified model. No random sample is involved in\nthe following loading displacement:\n\n\n::: {#tbl-cfa-population-displacement .cell layout-align=\"center\" tbl-cap='Belonging loadings in the generating model and at the population-ML optimum under M1-cross. Displacement is deterministic under these two specifications; it is not inferred from one realized sample.'}\n::: {.cell-output-display}\n\n\n|Item |Generating |Pseudo true |Displacement |\n|:----|:----------|:-----------|:------------|\n|B1   |0.800      |0.868       |0.068        |\n|B2   |0.740      |0.811       |0.071        |\n|B3   |0.670      |0.625       |-0.045       |\n|B4   |0.500      |0.471       |-0.029       |\n\n\n:::\n:::\n\n\nThe two indicators sharing the omitted residual relation have higher\npseudo-true primary loadings; the other two have lower loadings. This is a\nsystematic consequence of fitting the stated restricted model to the stated\npopulation covariance. By contrast, comparing two estimates in Sample B can\nshow sensitivity to a specification choice but cannot by itself establish\nestimator bias.\n\n## Population discrepancy is not the sample RMSEA formula\n\nFor population covariance $\\boldsymbol\\Sigma_0$ and its pseudo-true fitted\ncovariance $\\boldsymbol\\Sigma^*$, define\n\n$$\nF_0=log|\\boldsymbol\\Sigma^*|\n+\\operatorname{tr}(\\boldsymbol\\Sigma_0\n \\boldsymbol\\Sigma^{*-1})\n-\\log|\\boldsymbol\\Sigma_0|-p.\n$$\n\nThe audit gives $F_0=$ 0.01159907.\nPopulation RMSEA is therefore\n\n$$\n\\operatorname{RMSEA}_0=\\sqrt{F_0/df}\n=\\sqrt{0.01159907/49}\n=0.015.\n$$\n\n\n::: {#tbl-cfa-population-fit .cell layout-align=\"center\" tbl-cap='Population discrepancy measures versus sample-index formulas applied to the same population covariance with N = 360. The latter are not observed-sample evidence.'}\n::: {.cell-output-display}\n\n\n|Quantity        |Population definition |Sample formula at N360 |\n|:---------------|:---------------------|:----------------------|\n|Model statistic |NA                    |4.176                  |\n|df              |49.000                |49.000                 |\n|RMSEA           |0.015                 |0.000                  |\n|CFI             |0.997                 |1.000                  |\n|SRMR            |0.011                 |0.011                  |\n\n\n:::\n:::\n\n\nApplying the ordinary finite-sample formulas at $N=360$ to population input\nproduces RMSEA .000 and CFI 1.000 because their degree-of-freedom corrections\ntruncate the small discrepancy. Those numbers do **not** make the model true:\nthe population discrepancy, the tetrad, and the loading displacement remain\nnonzero. Even exact knowledge of the population covariance does not turn a\nglobal index into a certificate of specification.\n\n# Interpret parameters, reliability, and score boundaries\n\n## Parameters still depend on the model\n\nChapter 3's parameter intervals remain conditional on M1's restrictions\nand ML assumptions. The favorable fit profile makes ordinary\ninterpretation more defensible than it would be under severe\nmisspecification, but it does not remove that conditionality.\nResidual inspection also shows that individual relations are not\nreproduced perfectly.\n\nB4's relatively weak primary loading can reflect a broader or different\ncontent emphasis. Removing it would alter the domain represented by\nBelonging. It would also change the observed outcome set and invalidate\na direct AIC/BIC comparison with the twelve-item fit. “Higher loading\nafter deletion” is not a complete scale-development rationale.\n\nFactor correlations are estimated associations, not reliability\ncoefficients or directional effects. A correlation close to one can\nraise a question about empirical separation, but a universal cutoff\ncannot replace checking uncertainty, item content, and alternative\nmodel structures. The present three correlations are moderate positive\nrelations in the fixed-factor metric.\n\n## Define a score before calculating reliability\n\nFor a continuous composite\n\n$$\nc_i=\\mathbf w^{\\mathsf T}\\mathbf y_i,\n$$\n\nits model-implied variance is\n$\\mathbf w^{\\mathsf T}\\boldsymbol\\Sigma\\mathbf w$.\nThe proportion attributed to all modeled common factors is\n\n$$\n\\omega(\\mathbf w)=\n\\frac{\\mathbf w^{\\mathsf T}\\boldsymbol\\Lambda\n\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}\\mathbf w}\n{\\mathbf w^{\\mathsf T}\\boldsymbol\\Sigma\\mathbf w}.\n$$\n\nThe numerator is the variance of the model's common part for that\nweighting rule. The denominator also includes\n$\\mathbf w^{\\mathsf T}\\boldsymbol\\Theta\\mathbf w$.\nThis expression retains cross-loadings, factor correlations, and any\nmodeled residual covariances. A shortcut based only on selected\nloadings may omit essential terms.\n\nFor the course example, define four scores on the *raw process-index\nscale*: the mean of P1--P4, the mean of S1--S4, the mean of B1--B4,\nand the mean of all twelve indicators. Weights are .25 on the relevant\nfour items and zero elsewhere for a subscale, or $1/12$ on all items\nfor the total. A standardized-item mean would be a different weighting\nrule and requires a separately defined calculation.\n\n\n::: {#tbl-cfa-reliability .cell layout-align=\"center\" tbl-cap='Model-conditional common-variance proportions for explicitly defined raw-item composites under M1 in Sample B. These are point estimates, not validation thresholds.'}\n::: {.cell-output-display}\n\n\n|Composite      |Common variance proportion |\n|:--------------|:--------------------------|\n|Planning mean  |0.811                      |\n|Strategy mean  |0.812                      |\n|Belonging mean |0.792                      |\n|All-item mean  |0.881                      |\n\n\n:::\n:::\n\n\nThe all-item mean has a larger common-variance proportion than the\nindividual subscale means, but that does not make it unidimensional.\nIts numerator combines common variance from three correlated factors.\nSimilarly, the Planning and Strategy means include their retained\nsecondary-loading contributions. Their values are not proportions\nattributable exclusively to the intended named factor.\n\nReliability concerns a specified score under a specified model and\npopulation. It does not establish dimensionality, content coverage,\nfairness, predictive usefulness, or invariance across groups. The\nreported estimates also have sampling uncertainty. A bootstrap interval\nwould require a declared resampling design, model-refitting checks,\nand an explicit treatment of failed or improper solutions; it would\nnot account automatically for every earlier model-selection decision.\n\n## A small calculation exposes the assumptions\n\nFor a unit-weighted sum of three indicators loading only on a\nunit-variance factor, with loadings $.8,.7,.6$ and uncorrelated residual\nvariances $.36,.51,.64$,\n\n$$\n\\omega=\\frac{(.8+.7+.6)^2}\n{(.8+.7+.6)^2+.36+.51+.64}\n=\\frac{4.41}{5.92}\\approx .745.\n$$\n\nIf the first two residuals instead have covariance .10, the denominator\nincreases by $.20$, because both symmetric covariance entries enter\nthe sum variance. The common numerator is unchanged. Ignoring that\nresidual relation would overstate the common-variance proportion.\n\nThe signs also matter. Replacing loadings by absolute values silently\nchanges the implied score unless the indicator coding and weights\nare correspondingly changed. Reliability is not improved by hiding\nopposing contributions inside an absolute-value formula.\n\nAVE can summarize the average communality for a simple,\nfully-standardized single-factor item set. It is not interchangeable\nwith reliability of a weighted composite, and the SLE cross-loading\nsubscales do not satisfy that simple interpretation without qualification.\nCoefficient $H$ requires its own optimal-weighting conditions and is\nleft to the optional note.\n\n## Factor scores are predictions, not observed latent values\n\nA factor score uses a model-dependent weighting matrix:\n\n$$\n\\widehat{\\boldsymbol\\eta}_i\n=\\mathbf A(\\mathbf y_i-\\widehat{\\boldsymbol\\mu})\n$$\n\nunder the zero latent-location convention. The regression score\ntargets a conditional mean under a normal model and typically shrinks\nuncertain individuals toward the latent mean. Bartlett's score uses\na different weighting criterion, emphasizing residual-variance\nweighting. Both use estimated parameters and can differ for the same\nperson under the same fitted covariance model.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Two ways of scoring Planning in the same synthetic Sample B. Agreement is not identity and neither axis is an observed true factor value.](chapter_04_files/figure-html/fig-cfa-scores-1.png){#fig-cfa-scores fig-align='center' fig-pos='H' fig-alt='A scatterplot compares regression and Bartlett Planning scores, with an identity reference line; points are closely related but do not lie exactly on that line.' width=1072}\n:::\n:::\n\n\nUnder the fitted normal model with parameters treated as known, the\nconditional SDs of the three latent factors given the indicators are\napproximately 0.428, 0.417, 0.365.\nThe factors have unit marginal variance, so these are not zero\nuncertainties. They also omit parameter-estimation and model-selection\nuncertainty. A numerical score is a prediction, not the elimination\nof the measurement problem.\n\nExporting estimated factor scores into an ordinary regression and\ntreating them as perfectly measured covariates can change the target\nand distort inference. For many substantive questions, a joint latent\nSEM is the appropriate next representation, provided its measurement\nand structural assumptions are justified. Scores can still be useful\nfor clearly stated descriptive purposes; their method, scale, and\nuncertainty should accompany them.\n\n# Report a reproducible CFA evaluation\n\n## Report in the order of dependence\n\nA report should state the sample and data role, indicators and coding,\nmodel restrictions, factor metric, estimator and likelihood convention,\nmean structure, and missing-data/design handling before presenting\nfit. Follow with convergence and admissibility, global and local\nevidence, planned comparisons, any data-developed changes, parameter\ninterpretation, and the limits of the conclusion.\n\nA possible compact report for this record is:\n\n> We evaluated a previously frozen twelve-indicator, three-factor model\n> in a simulated confirmation sample of 360 complete continuous records.\n> The model retained two specified secondary loadings, free factor\n> correlations, unit factor variances, and diagonal residual covariance.\n> Conventional normal ML was used without a mean structure. The fit\n> converged without warnings and was admissible. M1-cross had\n> $\\chi^2(49)=$ 48.47,\n> $p=$ 0.494, RMSEA =\n> 0.000 (90% CI\n> [0.000,\n> 0.034]), CFI =\n> 1.000, TLI = 1.000,\n> and SRMR = 0.032.\n> Planned restrictions removing the secondary loadings or forcing\n> orthogonality were opposed by compatible ML difference tests.\n> Local residuals involving B4 motivated one tentative sensitivity\n> model. Its added loading did not receive support in an independent\n> frozen retest of 360 simulated records, so the primary model was\n> retained. Reliability estimates refer to declared raw-item composites\n> and do not establish unidimensionality or general validity.\n\nThe report includes a favorable conclusion about a working covariance\nrepresentation without claiming the factors have been directly\nobserved or the measurement theory uniquely confirmed. It also retains\nthe unsuccessful sensitivity analysis, a material part of what was done.\n\n## Preserve reproducibility without overwhelming the main text\n\nArchive the exact syntax, data manifest and codebook, parameter tables,\nfitted objects, comparison eligibility checks, software versions, and\nfrozen revision record. The main text need not print every diagnostic\nrow, but its selected rows must be traceable and must not conceal an\nimproper fit or unsuccessful comparison.\n\nThe canonical analysis reconstructs the ML statistic, RMSEA and its\ninterval, CFI, TLI, SRMR, AIC, BIC, and eligible LR differences from\nthe same fitted family. Reproduction is an arithmetic and provenance\ncheck; it does not replace substantive review. Public chapter renders\nhave no dependency on private teaching files or archived donor data.\n\n# Bridge from CFA to structural equation modeling\n\n## Add structural restrictions without discarding measurement\n\nThe measurement equation remains\n$\\mathbf y=\\boldsymbol\\nu+\\boldsymbol\\Lambda\\boldsymbol\\eta\n+\\boldsymbol\\epsilon$.\nA later structural model can write\n\n$$\n\\boldsymbol\\eta=\\boldsymbol\\alpha+\\mathbf B\\boldsymbol\\eta\n+\\boldsymbol\\Gamma\\boldsymbol\\xi+\\boldsymbol\\zeta,\n$$\n\nwhere $\\mathbf B$ contains latent structural paths,\n$\\boldsymbol\\Gamma$ links exogenous predictors, and\n$\\boldsymbol\\zeta$ is a structural disturbance. If\n$\\mathbf I-\\mathbf B$ is invertible,\n\n$$\nE(\\boldsymbol\\eta)=\n(\\mathbf I-\\mathbf B)^{-1}\n\\{\\boldsymbol\\alpha+\\boldsymbol\\Gamma E(\\boldsymbol\\xi)\\}.\n$$\n\nThus $\\boldsymbol\\alpha$ remains the latent *intercept*, not generally\nthe marginal latent mean. In the earlier CFA, $\\mathbf B=\\mathbf0$\nand there were no predictor terms, so the two coincided. No new\nintercept symbol is required when structural paths arrive.\n\nLet $\\boldsymbol\\Psi=\\operatorname{Var}(\\boldsymbol\\zeta)$.\nIf predictors and disturbances are uncorrelated, the total latent\ncovariance is\n\n$$\n\\boldsymbol\\Phi=\n(\\mathbf I-\\mathbf B)^{-1}\n\\{\\boldsymbol\\Gamma\\operatorname{Var}(\\boldsymbol\\xi)\n\\boldsymbol\\Gamma^{\\mathsf T}+\\boldsymbol\\Psi\\}\n(\\mathbf I-\\mathbf B)^{-\\mathsf T}.\n$$\n\n$\\boldsymbol\\Phi$ still means total latent covariance;\n$\\boldsymbol\\Psi$ now means structural disturbance covariance;\n$\\boldsymbol\\Theta$ remains indicator residual covariance. Keeping\nthese roles distinct prevents a notation change from hiding a change\nin the statistical model.\n\n## What the next chapters will add\n\nPath analysis first makes structural restrictions visible with\nobserved variables. General SEM then combines those restrictions with\nmeasurement models and develops direct and indirect effects. Invariance\nexamines whether measurement parameters can be linked across groups\nor occasions. SEM-based latent growth uses structured loadings and\nmeans to represent trajectories. Multilevel growth belongs to Part\nThree.\n\nThe familiar checks do not disappear: identification, scaling,\nestimation, global and local evaluation, and analytic history remain\nnecessary. A favorable CFA is not automatic permission to interpret\nevery later path causally. Nor does adding structural arrows repair a\npoor measurement model. The first four chapters establish the\nmeasurement foundation on which those later restrictions will depend.\n\n# Summary and reading bridge\n\nCFA evaluation is not a vote among fit-index cutoffs. The model test\naddresses exact covariance restrictions; RMSEA describes approximation\nper df with uncertainty; CFI and TLI use a baseline; SRMR summarizes\nstandardized covariance residuals. Local patterns and parameter\nmeaning remain necessary after those summaries are read.\n\nPlanned comparisons require exact nesting and compatible likelihoods.\nInformation criteria require comparable observations and outcomes.\nScore, Wald, and LR tests take different views of a restriction and\nneed not agree numerically. Modification indices are local\napproximations whose interpretation changes when selected from a\nsearch.\n\nThe SLE record supports retaining M1-cross as a working measurement\nmodel within the synthetic course example. A tentative B4 cross-loading\nimproved its development record but failed to receive support in the\nuntouched retest. Reliability calculations remain conditional on the\nmodel and weighting rule; factor scores remain uncertain predictions.\n\nThe fitted three-factor higher-order form is an admissible\nreparameterization of M1-cross, so identical fit cannot choose between\ntheir interpretations. The orthogonal bifactor model is a nonnested rival:\nit fits reasonably but less well by AIC/BIC here and contains a weak negative\nspecific loading. Omega-hierarchical describes the declared all-item score's\ngeneral-factor variance; it does not certify unidimensionality. Finally, the\nknown-population audit reveals a nonzero omitted B1--B2 residual relation,\nloading displacement, and population discrepancy even though finite-sample\nfit formulas applied at $N=360$ look perfect.\n\nFor further study, return to @bollen1989 and @brown2006 for the\nmeasurement-model framework, and @maccallum1996 for the connection\nbetween fit uncertainty and power. Read software tutorials alongside\ntheir fitted-object definitions, not as authority for universal\ncutoffs. The next topic is how structural restrictions change the\nmodel-implied latent means and covariances while retaining the\nmeasurement system.\n\n# Exercises {.unnumbered}\n\n1. **Foundational -- reconstruct ML.** For\n   $\\mathbf S=\\begin{bmatrix}1&.5\\\\.5&1\\end{bmatrix}$ and\n   $\\boldsymbol\\Sigma=\\begin{bmatrix}1&.3\\\\.3&1\\end{bmatrix}$,\n   calculate $F_{\\mathrm{ML}}$ and $NF_{\\mathrm{ML}}$ for $N=200$.\n   Explain why a chi-square reference still requires the model's df\n   and regularity conditions, not only this arithmetic.\n2. **Foundational -- RMSEA and uncertainty.** Compute RMSEA under the\n   $N$ convention for $T=60$, $df=40$, $N=400$, and for $T=35$ with\n   the same df and $N$. Explain why the second result does not imply\n   zero residuals. What does a wide 90% interval add to interpretation?\n3. **Foundational -- baseline dependence.** With $T_M=60$, $df_M=40$,\n   compare CFI when $(T_B,df_B)=(500,60)$ versus $(100,60)$.\n   Explain why the same target-model statistic can yield different\n   incremental fit and why neither result establishes construct truth.\n4. **Foundational -- distinguish residual scales.** Let observed\n   variances be 4 and 9, fitted variances 5 and 8, observed covariance\n   2, and fitted covariance 1.5. Calculate the raw residual, the\n   observed-SD-standardized covariance residual, and the correlation\n   residual. Explain why they are not all the same number.\n5. **Foundational -- establish nesting.** Show the exact restrictions\n   producing D1, D2, and D4 from D3. Use the printed statistics to\n   calculate D4 versus D3's LR difference and df. Explain why D1 and\n   D2 cannot be compared by the same ordinary subtraction test.\n6. **Foundational -- likelihood eligibility.** Recompute M1's AIC and\n   BIC from its log likelihood and free-parameter count. Explain why\n   comparison with M4 is eligible here but comparison with the donor\n   microcase, Sample C, or a ten-item short form is not.\n7. **Foundational -- define the composite.** For loadings $.7,.6,.5$\n   on a unit-variance factor and residual variances $.51,.64,.75$,\n   compute the common-variance proportion of a unit-weighted sum.\n   Recompute it with residual covariance .08 between the first two\n   indicators. State every assumption needed for the calculation.\n8. **Integrative -- interpret disagreement.** Compare M2's CFI and\n   SRMR, and M3's global profile and equality test. Explain the\n   distinct questions rather than selecting one statistic to override\n   the others.\n9. **Integrative -- evaluate the tentative revision.** Combine B4's\n   wording, residual pattern, MI/EPC, B refit, and C retest. Explain\n   the decision to retain M1 without claiming that C proves the added\n   loading is exactly zero. What would be lost by omitting R1 from\n   the report?\n10. **Integrative -- compare three tests.** Use D2/D3 to explain where\n    the score, Wald, and LR statistics obtain their information. Why\n    do they differ numerically, and why should an equality-constrained\n    model not be diagnosed solely with ordinary zero-parameter MIs?\n11. **Integrative -- scores are not measurements without error.**\n    Compare a raw Planning mean with a regression factor score.\n    Describe their weights, model dependence, scale, and uncertainty.\n    Explain the risk of treating exported factor scores as error-free\n    predictors in a later regression.\n12. **Integrative -- write the report and next step.** Draft an\n    evaluation paragraph that includes the primary model, sample roles,\n    estimation family, global/local evidence, planned comparisons,\n    unsupported revision, and reliability scope. Then explain how\n    adding $\\mathbf B$ changes the meanings of latent intercepts,\n    latent means, total latent covariance, and disturbance covariance.\n13. **Integrative -- invert three factor correlations.** Starting from\n    the fitted Sample B correlations in Section 6, recover the three\n    standardized higher-order loadings and disturbance variances. State\n    the sign, denominator, and admissibility conditions. Explain why the\n    higher-order form has the same df and fit as M1-cross, and why a\n    four-first-order-factor version would impose two restrictions.\n14. **Integrative -- compare a bifactor rival.** Count the 36 free\n    covariance parameters and 42 df in the displayed bifactor model.\n    Explain why it is not nested in M1-cross, interpret the weak\n    Strategy-specific S4 loading, and compare their fit profiles without\n    claiming that a general factor has been proved.\n15. **Integrative -- read the population audit.** Use the displayed\n    tetrad and loading-displacement table to identify the omitted\n    restriction. Explain why the population RMSEA is nonzero while the\n    finite-$N$ sample formulas applied to the population covariance return\n    RMSEA .000 and CFI 1.000, and why neither result is a specification\n    certificate.\n\n# Appendix: Interval and score calculations {.unnumbered}\n\n## Inverting the noncentral chi-square reference {.unnumbered}\n\nLet $G(t;d,\\delta)$ be the noncentral chi-square CDF with df $d$\nand noncentrality $\\delta$. For a two-sided 90% interval, solve\n\n$$\nG(T_M;df_M,\\delta_L)=.95,\n\\qquad\nG(T_M;df_M,\\delta_U)=.05,\n$$\n\nwith a lower boundary of zero when an interior solution does not\nexist. Transform the limits using\n$\\sqrt{\\delta/(Ndf_M)}$ under this chapter's convention. The\nshared numerical helper brackets the roots and reproduces the package\nintervals for every displayed model. The numerical inversion is\noptional; interpreting why a point estimate needs uncertainty is core.\n\n## Regression and Bartlett weights {.unnumbered}\n\nWith a jointly normal model, zero latent mean, and fitted parameters\ntemporarily treated as known, the regression weights are\n\n$$\n\\mathbf A_R=\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}\n\\boldsymbol\\Sigma^{-1},\n$$\n\nand the conditional covariance is\n\n$$\n\\operatorname{Var}(\\boldsymbol\\eta\\mid\\mathbf y)\n=\\boldsymbol\\Phi-\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}\n\\boldsymbol\\Sigma^{-1}\\boldsymbol\\Lambda\\boldsymbol\\Phi.\n$$\n\nFor nonsingular residual covariance and a full-column-rank loading\nmatrix, Bartlett weights are\n\n$$\n\\mathbf A_B=\n(\\boldsymbol\\Lambda^{\\mathsf T}\\boldsymbol\\Theta^{-1}\n\\boldsymbol\\Lambda)^{-1}\n\\boldsymbol\\Lambda^{\\mathsf T}\\boldsymbol\\Theta^{-1}.\n$$\n\nThese formulas clarify why scoring depends on more than selecting the\nlargest loadings. With nonzero latent means, add the appropriate\nlatent mean and center indicators at their implied means. Parameter\nuncertainty and model uncertainty require additional treatment; the\nconditional covariance above does not include them.\n\nFor a factor $a$, model-based regression-score determinacy is the\ncorrelation between the latent factor and its regression prediction.\nUnder the stated model its square is\n$1-\\operatorname{Var}(\\eta_a\\mid\\mathbf y)/\\phi_{aa}$.\nHigh determinacy is not proof of a correct measurement model, and\nit does not eliminate prediction error for individuals.\n\n## Coefficient H under a restrictive one-factor model {.unnumbered}\n\nFor a single unit-variance factor with diagonal positive residual\ncovariance, let\n$a=\\boldsymbol\\lambda^{\\mathsf T}\\boldsymbol\\Theta^{-1}\n\\boldsymbol\\lambda$. The maximum common-variance proportion among\nlinear composites is\n\n$$\nH=\\frac{a}{1+a}.\n$$\n\nWith fully standardized simple indicators,\n$a=\\sum_j\\lambda_j^2/(1-\\lambda_j^2)$.\nThis is an optimal-weighting result under specific assumptions,\nnot reliability of every unit-weighted score and not a general\nformula for a multifactor cross-loading subscale. It should not\nbe attached to the SLE factors by ignoring their other loadings.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}