{
  "hash": "1b128e1257d9d78d6388a1d648b17a32",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Specifying and Estimating Confirmatory Factor Models\"\nauthor: \"Jinsong Chen\"\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\nformat:\n  pdf:\n    output-file: chapter_03.pdf\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{caption}\n          \\captionsetup[table]{position=above,format=plain,justification=raggedright,singlelinecheck=false,labelsep=newline,labelfont=bf,textfont=it}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nA confirmatory factor model makes a measurement proposal precise enough to\nconfront observations. This chapter starts with its general equations and a\nfully disclosed simulated population. We distinguish the population we\npropose, the sample we observe and the moments a fitted model reproduces.\nWe then write a small model in words, equations, matrices and a diagram;\nidentify free parameters and scale conventions; and ask whether the observed\nmoments can determine those parameters. Estimation supplies coefficients and\nuncertainty, while global and local evaluation examine the model's observed\nimplications. A twelve-item learning-experience questionnaire and nine\nhistorical ability tests provide two applications. The latter is fitted from\nboth individual records and their summary covariance matrix. By the end,\nyou should be able to explain what was assumed, what was estimated, what the\nfit evidence says and what remains unestablished. Comparison, revision and\nindependent validation extend this basic analysis in the next chapter.\n:::\n\nSuppose a research team argues that several questionnaire responses reflect\nplanning, study strategy and belonging. The claim concerns variables the\nteam cannot observe directly. How does it become a statistical model, and\nwhich aspects of it can the recorded responses challenge?\n\nA factor model answers by specifying how the unobserved variables relate to\nthe indicators and what remains outside those relations. It also imposes\nrestrictions: an item may load on one factor but not another; two residuals\nmay be assumed unrelated; two coefficients may be required to agree. These\ndecisions determine both what can be learned from the data and which patterns\nthe model can fail to reproduce. They should therefore be visible before a\ntable of estimates or fit indices appears.\n\n> How do a measurement proposal, its statistical restrictions and its observed\n> implications fit together in one defensible analysis?\n\nThe examples below keep three kinds of evidence separate. Stipulated\npopulation values make an implication exact; a simulated sample shows how\nsampling changes the observed pattern; empirical records require an account\nof the actual measurements and design.\n\n# Formulate a general confirmatory factor model\n\n## The general measurement model\n\nLet $\\mathbf y_i$ contain the $p$ recorded indicators for person $i$, and let\n$\\boldsymbol\\eta_i$ contain $m$ factors. A linear measurement model is\n\n$$\n\\mathbf y_i=\\boldsymbol\\nu+\\boldsymbol\\Lambda\\boldsymbol\\eta_i\n +\\boldsymbol\\epsilon_i.\n$$\n\nThe intercept vector $\\boldsymbol\\nu$ sets indicator origins. Each row of the $p\\times m$ loading matrix\n$\\boldsymbol\\Lambda$ describes one indicator's relations with the factors.\nThe residual vector $\\boldsymbol\\epsilon_i$ contains influences left outside\nthose relations. We assume $E(\\boldsymbol\\epsilon_i)=\\mathbf0$ and\n$\\operatorname{Cov}(\\boldsymbol\\eta_i,\\boldsymbol\\epsilon_i)=\\mathbf0$.\nWriting $E(\\boldsymbol\\eta_i)=\\boldsymbol\\alpha$,\n$\\boldsymbol\\Phi=\\operatorname{Var}(\\boldsymbol\\eta_i)$ and\n$\\boldsymbol\\Theta=\\operatorname{Var}(\\boldsymbol\\epsilon_i)$ gives\n\n$$\n\\boldsymbol\\mu=\\boldsymbol\\nu+\\boldsymbol\\Lambda\\boldsymbol\\alpha,\n\\qquad\n\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)\n=\\boldsymbol\\Lambda\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}\n +\\boldsymbol\\Theta.\n$$\n\nHere $\\boldsymbol\\Phi$ is $m\\times m$ and $\\boldsymbol\\Theta$ is $p\\times p$.\nThe free-parameter vector $\\boldsymbol\\vartheta$ collects the entries we\nestimate under the restrictions; it is distinct from the residual covariance\nmatrix $\\boldsymbol\\Theta$. The equations separate the proposed common\nsources of association from residual association. Their covariance implication\nrequires finite second moments and the stated uncorrelatedness assumption;\na Normal sampling distribution is an additional assumption used later for\nconventional likelihood inference.\n\nTo read the equation as a conditional mean, assume additionally that\n$E(\\boldsymbol\\epsilon_i\\mid\\boldsymbol\\eta_i)=\\mathbf0$. Then\n$\\boldsymbol\\nu$ gives expected indicator levels at zero factor values and\nthe loadings describe their linear change as factors vary. Joint Normality\nwith zero factor--residual covariance supplies this conditional-mean property.\n\nIn a path diagram, ellipses denote factors, rectangles denote recorded\nindicators, directed arrows denote loadings, and curved double-headed arrows\ndenote covariances. A loading arrow represents a conditional linear relation:\nit does not by itself establish a causal measurement process. A diagram also\nneeds a parameter ledger. An arrow may have a free coefficient, a value fixed\nto set units, or a value constrained to equal another coefficient; an absent\narrow commonly denotes a fixed zero.\n\nThe *confirmatory* specification declares these restrictions before the\nanalysis being evaluated. It might assign each indicator to one factor,\nallow a prespecified secondary loading, constrain selected loadings to equality,\nor allow a justified residual covariance. Those restrictions, rather than the\nname of a fitting routine, give the model its testable implications.\n\n```{=latex}\n\\Needspace{14\\baselineskip}\n```\n\n| Question | Exploratory factor model | Confirmatory factor model |\n|:--|:--|:--|\n| Which loadings are estimated? | All, before choosing an orientation | Only the declared free relations |\n| How is orientation handled? | Rotation and subsequent labels | Loading restrictions and factor metrics |\n| What determines the candidate? | Development evidence plus content | A fixed specification, with named rivals |\n| What data role is being used? | Records used to develop the specification | Records used to evaluate an already declared specification |\n| What is not established by the model label? | Unique substantive interpretation | Adequacy, validity, or causality |\n\n“Confirmatory” describes restrictions and analytic history, not a\nguaranteed favorable conclusion. A CFA estimated after repeated same-data\nchanges is still mathematically a CFA, but the changed specification is\ndata-developed. Conversely, a prespecified cross-loading does not make a\nmodel nonconfirmatory merely because it departs from independent-clusters\nsimple structure.\n\n## Missing arrows have statistical consequences\n\nAn absent loading arrow generally means a coefficient fixed to zero.\nIt does not mean that the indicator and factor are uncorrelated. Under\ncorrelated factors, an indicator can correlate with a factor on which\nit has no direct loading. For example, if $Y_2=.8\\eta_1+\\epsilon_2$ and the factors correlate,\n$Y_2$ can covary with $\\eta_2$ even though its loading on $\\eta_2$ is zero.\n\nAn absent residual covariance means that two residuals are uncorrelated\nunder the model. That is a moment restriction. To assert conditional\nindependence of indicators given the factors, we additionally need an\nappropriate conditional distribution or factorization; in a jointly\nnormal linear model, diagonal residual covariance supplies that stronger\nproperty. Zero covariance alone does not generally imply independence.\n\nA factor-to-indicator arrow specifies a loading relation. Interpreting\nthe arrow causally requires design and substantive assumptions beyond\nthe covariance equation. Good fit cannot supply temporal precedence or\nexclude every alternative explanation.\n\nConsider two indicators with loadings .8 and 1.2 on a factor of variance 4,\nand residual variances 3 and 4. Their common-factor covariance is\n$.8(1.2)(4)=3.84$. Now suppose the two questions share wording whose influence\nremains after holding the factor fixed. Represent that possibility by a\nresidual covariance of .5, leaving every other parameter unchanged.\n\n::: {.callout-note title=\"Predict and explain\"}\nBefore inspecting the second case, predict whether the marginal indicator\ncovariance, the covariance conditional on the true factor, or both will\nchange. Would the absence of a residual arrow mean that the two recorded\nindicators are independent without conditioning?\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Two stipulated measurement models differ only in a residual relation. The dotted covariance arc in the right panel joins the residuals, not the factor or the indicators' shared factor paths.](chapter_03_files/figure-html/fig-cfa-local-dependence-1.png){#fig-cfa-local-dependence fig-align='center' fig-pos='H' fig-alt='In both panels one factor predicts Y2 and Y3. Only the right panel has a double-headed residual covariance arc between their remaining influences.' width=1120}\n:::\n:::\n\n\n| Quantity for $Y_2,Y_3$ | Residual covariance 0 | Residual covariance .5 |\n|:--|--:|--:|\n| Marginal covariance | 3.84 | 4.340 |\n| Covariance conditional on the true factor | 0.00 | .500 |\n| Residual correlation | 0.00 | .144 |\n\n: Local dependence changes association remaining after the true factor is held fixed. {#tbl-cfa-local-dependence tbl-colwidths=\"[48,26,26]\"}\n\nThe residual correlation is $.5/\\sqrt{3(4)}=.144$. In the jointly Normal\nmodel, the first case gives **local independence** conditional on the true\nfactor. The indicators remain marginally associated because they share that\nfactor. The second case retains an additional conditional association.\nShared wording is one possible design explanation; the covariance alone\ncannot establish it. Conditioning on *estimated factor scores* is also a\ndifferent operation: predictions of the factor are not the true factor\nvalues being held fixed in this calculation.\n\n## From a known population to one simulated sample\n\nA small known population lets us see the model-to-data link before fitting a\nsubstantive example. Introduce two zero-mean factors, measured by six indicators.\nTheir generating loadings, factor covariance and residual variances are\n\n$$\n\\boldsymbol\\Lambda_0=\n\\begin{bmatrix}1.00&0.00\\\\.80&0.00\\\\1.20&.25\\\\0.00&1.00\\\\0.00&1.10\\\\0.00&.90\\end{bmatrix},\n\\quad\n\\boldsymbol\\Phi_0=\\begin{bmatrix}4&1.2\\\\1.2&9\\end{bmatrix},\n\\quad\n\\boldsymbol\\Theta_0=\\operatorname{diag}(2,3,4,3,4,5).\n$$\n\nThe indicator intercepts are $(10,12,11,15,14,13)$. Factors are jointly\nNormal; residuals are mutually independent Normal variables and independent\nof the factors. Each simulated person is independent of the others. The\nextra .25 loading allows $Y_3$ to reflect both factors. These are *declared\npopulation values*, not estimates selected because they fit a sample well.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The disclosed generating model for the six-indicator simulation. Y3 has two loadings. The Y1 and Y4 loadings equal one, setting the factor units. Residual covariances and unshown loadings are zero.](chapter_03_files/figure-html/fig-cfa-generated-model-1.png){#fig-cfa-generated-model fig-align='center' fig-pos='H' fig-alt='F1 predicts Y1, Y2 and Y3; F2 predicts Y4, Y5 and Y6 plus a secondary path to Y3. Factors covary and each indicator has its own residual.' width=1088}\n:::\n:::\n\n\nWhen this structure is fitted, the two marker loadings stay fixed at one.\nThe other displayed nonzero values become quantities to estimate. Treating\nevery generating number as fixed would instead test a much narrower model.\n\n| Parameter family | Free covariance-model parameters |\n|:--|--:|\n| Nonmarker loadings, including $Y_3$'s second loading | 5 |\n| Two factor variances and their covariance | 3 |\n| Indicator residual variances | 6 |\n| Total | 14 |\n\n: A free-parameter ledger for the simulated model. {#tbl-cfa-generated-ledger}\n\nSix variances and fifteen distinct covariances supply $6(7)/2=21$ distinct\nmoments, leaving $21-14=7$ degrees of freedom. These 21 moments are\nsummaries of a distribution, not 21 people. Counting is a necessary check;\nSection 6 explains why it does not alone establish identification.\n\n\n::: {#tbl-cfa-generated-covariance .cell layout-align=\"center\" tbl-cap='Known population covariance for the disclosed six-indicator model. These moments follow exactly from the generating matrices, before any sample is drawn.'}\n::: {.cell-output-display}\n\n\n|   |Y1   |Y2    |Y3     |Y4    |Y5     |Y6     |\n|:--|:----|:-----|:------|:-----|:------|:------|\n|Y1 |6.00 |3.200 |5.100  |1.20  |1.320  |1.080  |\n|Y2 |3.20 |5.560 |4.080  |0.96  |1.056  |0.864  |\n|Y3 |5.10 |4.080 |11.043 |3.69  |4.059  |3.321  |\n|Y4 |1.20 |0.960 |3.690  |12.00 |9.900  |8.100  |\n|Y5 |1.32 |1.056 |4.059  |9.90  |14.890 |8.910  |\n|Y6 |1.08 |0.864 |3.321  |8.10  |8.910  |12.290 |\n\n\n:::\n:::\n\n\nWe generate 500 independent records from these declarations, using seed\n20260930 with the Mersenne-Twister generator, Normal inversion and the\nstated indicator order. The values and seed are held fixed. The resulting\nsample is separate from the later learning-experience samples; knowing this\npopulation supplies no advance knowledge about that other case.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Known population, one sample and the correctly specified fitted covariance. All panels use the same indicator order and color scale; the selected entries below give the numerical comparisons. The third panel will be explained through estimation and evaluation.](chapter_03_files/figure-html/fig-cfa-population-sample-1.png){#fig-cfa-population-sample fig-align='center' fig-pos='H' fig-alt='Three six-by-six covariance heatmaps compare the known generating matrix, sample covariance with divisor N, and fitted matrix. Broad blocks remain similar but sample and fitted cells differ from their population targets.' width=1120}\n:::\n:::\n\n\n\n::: {#tbl-cfa-population-sample .cell layout-align=\"center\" tbl-cap='Selected covariance entries from the three panels. The sample uses divisor N, matching the normal-likelihood fitted model.'}\n::: {.cell-output-display}\n\n\n|Entry       |Population |Sample |Fitted |\n|:-----------|:----------|:------|:------|\n|Y2, Y3      |4.080      |4.471  |4.494  |\n|Y3, Y5      |4.059      |3.518  |3.710  |\n|Y3 variance |11.043     |10.415 |10.415 |\n|Y1, Y6      |1.080      |1.342  |1.026  |\n\n\n:::\n:::\n\n\nThe population and sample panels answer different questions. The first is\nwhat the declared model generates on average; the second is what these 500\npeople happened to produce. Estimation selects one member of the restricted\nmodel family, shown in the third panel. Even a correctly specified model\nneed not reproduce the sample matrix exactly or recover each generating\nparameter exactly. We return to that distinction after developing estimation.\nFor exact arithmetic in Sections 2--5, a simpler *controlled population*\nsets the extra loading to zero; it is explicitly distinguished from this\nsampled population.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Specification, recoverability, and numerical estimation are distinct tasks; evaluating the fitted record is a fourth.](chapter_03_files/figure-html/fig-cfa-sequence-1.png){#fig-cfa-sequence fig-align='center' fig-pos='H' fig-alt='Four linked boxes show restrictions, identification, estimation, and evaluation.' width=1120}\n:::\n:::\n\n\n# Write one model four ways\n\n## A verbal specification\n\nBegin with six continuous indicators, $Y_1,\\ldots,Y_6$, and two\ncorrelated factors. The first three indicators load only on $\\eta_1$;\nthe last three load only on $\\eta_2$. All six residual variances are\nfree and all residual covariances are zero. Factors and residuals are\nuncorrelated. Use $Y_1$ and $Y_4$ as markers, fixing their loadings to\none. The factor variances and their covariance remain free.\n\nThe labels are intentionally neutral. This compact model is adapted from\na two-factor, six-indicator teaching structure, not extracted\nfrom the SLE items. It lets us follow each restriction without introducing\na second substantive measurement story.\n\n## Six scalar equations\n\nWith zero latent intercepts and zero-mean residuals,\n\n$$\n\\begin{aligned}\nY_{i1}&=\\nu_1+\\eta_{i1}+\\epsilon_{i1},&\nY_{i4}&=\\nu_4+\\eta_{i2}+\\epsilon_{i4},\\\\\nY_{i2}&=\\nu_2+\\lambda_{21}\\eta_{i1}+\\epsilon_{i2},&\nY_{i5}&=\\nu_5+\\lambda_{52}\\eta_{i2}+\\epsilon_{i5},\\\\\nY_{i3}&=\\nu_3+\\lambda_{31}\\eta_{i1}+\\epsilon_{i3},&\nY_{i6}&=\\nu_6+\\lambda_{62}\\eta_{i2}+\\epsilon_{i6}.\n\\end{aligned}\n$$\n\nThe subscript $i$ denotes a person; the first subscript of\n$\\lambda_{ja}$ identifies the indicator, and the second identifies\nthe factor. Writing all six equations is useful once: it prevents a\ncompact diagram from hiding a cross-loading or a mistaken marker.\nLater, matrix notation avoids repeating the same structure.\n\n## Three parameter matrices\n\nThe same model is\n\n$$\n\\boldsymbol\\Lambda=\n\\begin{bmatrix}\n1&0\\\\\\lambda_{21}&0\\\\\\lambda_{31}&0\\\\\n0&1\\\\0&\\lambda_{52}\\\\0&\\lambda_{62}\n\\end{bmatrix},\\qquad\n\\boldsymbol\\Phi=\\begin{bmatrix}\\phi_{11}&\\phi_{12}\\\\\n\\phi_{12}&\\phi_{22}\\end{bmatrix},\\qquad\n\\boldsymbol\\Theta=\\operatorname{diag}(\\theta_{11},\\ldots,\\theta_{66}).\n$$\n\nThere are twelve loading slots, not twelve freely estimated loadings:\nfour are free, two are fixed at one for scaling, and six are fixed at\nzero. Symmetry means $\\phi_{12}$ and $\\phi_{21}$ are the same covariance,\nnot two independent parameters. Likewise, a freely estimated residual\ncovariance would occupy two symmetric matrix entries but add only one\nfree parameter.\n\nThe implied mean vector is\n$\\boldsymbol\\mu=\\boldsymbol\\nu+\\boldsymbol\\Lambda\\boldsymbol\\alpha$.\nHere $\\boldsymbol\\alpha=\\mathbf0$, so\n$\\boldsymbol\\mu=\\boldsymbol\\nu$. The latent intercept equals the\nlatent mean because this CFA has no structural paths or latent\npredictors. This convention will need an explicit distinction between\nintercepts and marginal means once structural regressions enter.\n\n## A diagram and the free parameters it implies\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Marker-scaled six-indicator CFA. Residual variances are free; residual covariances and unshown loadings are zero. Intercepts are omitted from this covariance diagram.](chapter_03_files/figure-html/fig-cfa-six-1.png){#fig-cfa-six fig-align='center' fig-pos='H' fig-alt='F1 predicts Y1, Y2, and Y3; F2 predicts Y4, Y5, and Y6. The Y1 and Y4 loadings equal one. Factor variances and their covariance are free.' width=1120}\n:::\n:::\n\n\nThe diagram and matrices together determine a free parameter vector.\nUnder the stated marker constraints it is\n\n$$\n\\boldsymbol\\vartheta=(\\lambda_{21},\\lambda_{31},\\lambda_{52},\\lambda_{62},\\;\n\\phi_{11},\\phi_{12},\\phi_{22},\\;\n\\theta_{11},\\theta_{22},\\theta_{33},\\theta_{44},\\theta_{55},\n\\theta_{66})^{\\mathsf T}.\n$$\n\nThat is thirteen entries. Everything else in the three matrices is fixed:\n$\\lambda_{11}=\\lambda_{42}=1$, the six remaining loadings at zero, and\n$\\theta_{jk}=0$ for $j\\neq k$. Section 6.2 counts the same thirteen against\nthe twenty-one available moments.\n\nA convenience fitting function supplies free indicator residual\nvariances and fixes unmentioned residual covariances to zero in this\nmodel. Defaults must still be checked; a short specification is not a\ncomplete parameter ledger. The [official CFA tutorial](https://lavaan.ugent.be/tutorial/cfa.html)\nis a useful orientation to the specify--fit--extract workflow.\n\n| Representation | What to check |\n|:--|:--|\n| Words | Indicator assignments, residual assumptions, metric, and means |\n| Scalar equations | Every indicator has exactly the stated loading terms |\n| Matrices | All zero, fixed, and shared entries are explicit |\n| Diagram and syntax | Every drawn or coded relation matches the same ledger |\n\nIf two representations disagree, no amount of numerical convergence can\nresolve which model the researcher intended. Fix the specification before\ninterpreting output.\n\n## Transfer the grammar to four factors\n\nA larger diagram should be read with the same ledger rather than as a new\nkind of model. As a published-reading exercise, reconstruct the topology of\nFigure 3 in @chou2021 [p. 6]: four correlated factors---self-efficacy, school\nsupport, privacy concerns, and technostress---each measured by four\nindicators. The reconstruction below records the displayed assignments and\nfactor relations; it does not reproduce the paper's estimated coefficients\nor imply that every software default used in the original analysis is known.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Four-factor, sixteen-indicator CFA reconstructed as a diagram-reading transfer. All six factor correlations are free; fixed-factor scaling is used for the count.](chapter_03_files/figure-html/fig-cfa-four-1.png){#fig-cfa-four fig-align='center' fig-pos='H' fig-alt='Four correlated factors called Self-efficacy, School support, Privacy concerns, and Technostress each predict four separate indicators. Each indicator has a residual.' width=1120}\n:::\n:::\n\n\nUnder fixed-factor scaling the reconstruction has parameter matrices\n\n$$\n\\boldsymbol\\Lambda=\n\\begin{bmatrix}\n\\boldsymbol\\lambda_1&\\mathbf 0&\\mathbf 0&\\mathbf 0\\\\\n\\mathbf 0&\\boldsymbol\\lambda_2&\\mathbf 0&\\mathbf 0\\\\\n\\mathbf 0&\\mathbf 0&\\boldsymbol\\lambda_3&\\mathbf 0\\\\\n\\mathbf 0&\\mathbf 0&\\mathbf 0&\\boldsymbol\\lambda_4\n\\end{bmatrix},\n\\qquad\n\\boldsymbol\\Phi=\n\\begin{bmatrix}\n1&\\phi_{12}&\\phi_{13}&\\phi_{14}\\\\\n\\phi_{12}&1&\\phi_{23}&\\phi_{24}\\\\\n\\phi_{13}&\\phi_{23}&1&\\phi_{34}\\\\\n\\phi_{14}&\\phi_{24}&\\phi_{34}&1\n\\end{bmatrix},\n$$\n\nwith $\\boldsymbol\\Lambda$ of order $16\\times4$, each $\\boldsymbol\\lambda_g$ a\n$4\\times1$ vector of free loadings, each $\\mathbf 0$ a $4\\times1$ vector of\nfixed zeros, and $\\boldsymbol\\Theta$ diagonal of order sixteen.\nThe omitted loading arrows are those fixed zeros, the four unit latent\nvariances set the factor metrics, and the six pairwise factor covariances,\nhere correlations, are free. With 16\ncontinuous indicators, the covariance ledger is therefore\n\n$$\nu=\\frac{16(17)}2=136,\\qquad\nt=16\\text{ loadings}+16\\text{ residual variances}\n  +\\frac{4(3)}2\\text{ factor correlations}=38,\n\\qquad df=98.\n$$\n\nThis transfer matters because visual density can conceal a counting error.\nFour double-headed arrows would omit two factor correlations; counting 16\ndrawn loading slots as 16 *free* loadings would be wrong under marker\nscaling but correct under the fixed-factor convention used here. Always\nstate the metric before reading freedom from a diagram.\n\n# Free, fixed, and constrained parameters\n\n## Different restrictions do different jobs\n\nA free parameter is estimated from the data under the other restrictions.\nA fixed parameter is assigned a known constant. An equality constraint\nrequires two or more parameter entries to share a value; it does not\nnecessarily assign that value in advance. A bound restricts the allowable\nrange. A defined parameter is a computed function of fitted parameters\nand does not add a new free parameter.\n\n```{=latex}\n\\Needspace{18\\baselineskip}\n```\n\n| Entry | Status | Statistical role | Reason to state |\n|:--|:--|:--|:--|\n| $\\lambda_{11}=1$ | Fixed | Factor metric | Marker choice |\n| $\\lambda_{21}$ | Free | Target loading | Indicator assignment |\n| $\\lambda_{22}=0$ | Fixed | Excluded secondary loading | Content/design restriction |\n| $\\lambda_{21}=\\lambda_{31}$ | Equality | Shared loading value | Equality on a stated scale |\n| $\\theta_{23}=0$ | Fixed | Residual relation excluded | Local measurement assumption |\n| $\\phi_{12}$ | Free | Factor association | Correlation permitted |\n| $\\theta_{jj}>0$ | Admissibility condition | Positive residual variance | Statistical parameter space |\n| $\\lambda_{21}-\\lambda_{31}$ | Defined | Loading difference | Derived estimand, not extra freedom |\n\nFixing one loading to one selects a unit. Fixing a secondary loading to\nzero excludes a relation. They are both constants in software, but only\nthe latter ordinarily adds a substantive covariance restriction when\nthe former replaces another valid scale normalization.\n\n“Unconstrained” is also relative. A free loading is estimated within a\nmodel whose other loadings, residual structure, and factor variances\nmay be strongly restricted. Its estimate is not model-free evidence\nabout that indicator.\n\n## Change one loading restriction\n\nAllow $Y_3$ to load on factor 2 as well:\n\n$$\nY_{i3}=\\nu_3+\\lambda_{31}\\eta_{i1}\n+\\lambda_{32}\\eta_{i2}+\\epsilon_{i3}.\n$$\n\nOne formerly zero matrix entry becomes free. The new coefficient affects\nthe variance of $Y_3$ and its covariances with all indicators connected\nto either factor. It does not merely repair the covariance of one chosen\npair. The coefficient's interpretation is conditional on factor 1, just\nas an oblique EFA pattern coefficient was conditional on the other factors.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A single additional loading changes several implied moments. The dashed path is $\\lambda_{32}$.](chapter_03_files/figure-html/fig-cfa-cross-1.png){#fig-cfa-cross fig-align='center' fig-pos='H' fig-alt='The six-indicator model adds one dashed arrow from F2 to Y3; all other relations match the marker-scaled base model.' width=1120}\n:::\n:::\n\n\n## Change one residual relation instead\n\nAlternatively, retain the original loading matrix but free\n$\\theta_{23}=\\operatorname{Cov}(\\epsilon_2,\\epsilon_3)$.\nThen only the $(2,3)$ and $(3,2)$ entries of the residual matrix change.\nThis can represent item-specific shared wording, a common task, or\nanother source of association outside the two modeled factors.\nIts meaning must be justified; “the software suggested it” is not a\nmeasurement explanation.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A residual covariance is a different model change from a cross-loading. The dotted relation connects $\\epsilon_2$ and $\\epsilon_3$.](chapter_03_files/figure-html/fig-cfa-residual-1.png){#fig-cfa-residual fig-align='center' fig-pos='H' fig-alt='The base six-indicator model adds a covariance between residuals e2 and e3 without adding a factor-to-indicator loading.' width=1120}\n:::\n:::\n\n\nBoth changes add one parameter, but they generally produce different\nsets of implied covariance matrices. Equal df therefore does not imply\nequivalent models. When two modifications improve the same observed\npair, their consequences for the other pairs help distinguish them.\nLocal diagnosis depends on that difference.\n\n## Equality requires a common metric\n\nThe restriction $\\lambda_{21}=\\lambda_{31}$ states equal raw changes\nin $Y_2$ and $Y_3$ for a one-unit change in their common factor. If\n$Y_3$ is rescaled from points to tens of points, the equivalent restriction\nmust be transformed. Repeating the old equality on rescaled data tests\na different hypothesis.\n\nEquality of loadings is not equality of residual variances, intercepts,\nor item distributions. Equal loadings with unequal residual variances\nallow different precision. Stronger parallel-measurement conditions\nrequire additional restrictions. A short-form scale cannot be justified\nsimply by retaining the largest estimated loadings; content coverage\nand intended score use also change when items are removed.\n\n# Give latent variables a metric\n\nA change of factor units, a change of indicator units, and a new substantive\nrestriction do different work. Factor rescaling preserves the implied\ncovariance in the original observed units. Indicator rescaling expresses the\nsame information in new observed units, with every affected model quantity\ntransformed. A substantive restriction instead excludes covariance patterns\nthat were previously allowed. The examples below keep those changes apart.\n\n## Marker scaling and fixed-factor scaling\n\nLatent variables have no observed unit until we assign one. Under marker\nscaling, $\\lambda_{11}=1$ means that a one-unit change in $\\eta_1$\ncontributes one unit to $Y_1$ through its loading relation. It does not\nset the factor variance to one or make the marker error-free.\n\nUnder fixed-factor scaling, set $\\phi_{11}=\\phi_{22}=1$ and estimate\nall six target loadings. A factor unit is then one model-standard-deviation\nunit in this single-group CFA. The indicators retain their raw units.\nIn `lavaan`, `std.lv=TRUE` requests this scale choice. It is not a command\nto standardize every observed column.\n\n| Quantity | Marker scaling | Fixed-factor scaling |\n|:--|:--|:--|\n| Marker loadings | Fixed at one | Free |\n| Factor variances | Free | Fixed at one |\n| Free target loadings | 4 | 6 |\n| Free factor variance/covariance entries | 3 | 1 |\n| Free residual variances | 6 | 6 |\n| Total free covariance axes | 13 | 13 |\n\nOne must also choose factor signs. With unit factor variances, changing\nthe sign of a factor and every loading on it leaves the covariance\nunchanged. A declared positive orientation for central indicators makes\nreported signs interpretable; a negative factor does not represent a\ndifferent fit merely because its column points the other way.\n\n## Derive the reparameterization\n\nFor an invertible diagonal $m\\times m$ matrix $\\mathbf D$, define\n\n$$\n\\boldsymbol\\eta_i^*=\\mathbf D\\boldsymbol\\eta_i,\n\\qquad\n\\boldsymbol\\Lambda^*=\\boldsymbol\\Lambda\\mathbf D^{-1},\n\\qquad\n\\boldsymbol\\Phi^*=\\mathbf D\\boldsymbol\\Phi\\mathbf D^{\\mathsf T}.\n$$\n\n\\Needspace{5\\baselineskip}\n\nThe implied covariance is unchanged:\n\n$$\n\\boldsymbol\\Lambda^*\\boldsymbol\\Phi^*\n(\\boldsymbol\\Lambda^*)^{\\mathsf T}\n=\\boldsymbol\\Lambda\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}.\n$$\n\nFor positive factor variances, choosing\n$\\mathbf D=\\operatorname{diag}(\\phi_{11}^{-1/2},\\phi_{22}^{-1/2})$\nmakes the transformed factor variances one. The residual matrix is\nunchanged. If latent means are modeled, transform\n$\\boldsymbol\\alpha^*=\\mathbf D\\boldsymbol\\alpha$ as well.\n\nUse the following controlled values for hand calculation:\n\n$$\n\\boldsymbol\\Lambda=\n\\begin{bmatrix}1&0\\\\.8&0\\\\1.2&0\\\\0&1\\\\0&1.1\\\\0&.9\\end{bmatrix},\n\\quad\n\\boldsymbol\\Phi=\\begin{bmatrix}4&1.2\\\\1.2&9\\end{bmatrix},\n\\quad\n\\boldsymbol\\Theta=\\operatorname{diag}(2,3,4,3,4,5).\n$$\n\nThe transformation divides factor 1 by 2 and factor 2 by 3. Accordingly,\nthe transformed loading columns multiply by 2 and 3. The covariance\n1.2 becomes a correlation $1.2/(2\\times3)=.2$. The transformed\nprimary loading of $Y_2$ is 1.6, but its implied variance has not changed.\n\n\n::: {#tbl-cfa-scale-values .cell layout-align=\"center\" tbl-cap='Controlled values under two metrics; these are stipulated parameters, not sample estimates.'}\n::: {.cell-output-display}\n\n\n|Item |Marker loading |Fixed factor loading |Residual variance |Implied variance |\n|:----|:--------------|:--------------------|:-----------------|:----------------|\n|Y1   |1.0            |2.0                  |2                 |6.00             |\n|Y2   |0.8            |1.6                  |3                 |5.56             |\n|Y3   |1.2            |2.4                  |4                 |9.76             |\n|Y4   |1.0            |3.0                  |3                 |12.00            |\n|Y5   |1.1            |3.3                  |4                 |14.89            |\n|Y6   |0.9            |2.7                  |5                 |12.29            |\n\n\n:::\n:::\n\n\nThis is a reparameterization of the same covariance model, not evidence\nthat marker and fixed-factor methods estimate different constructs.\nEquivalence can fail if a constraint is not transformed with the metric,\nif a required marker loading is zero, or if a factor variance is on an\ninadmissible boundary. Multigroup means and nonlinear models need\nadditional care. A convenient single-group result should not be\ngeneralized without checking those conditions.\n\n## Changing observed units is a different operation\n\nLatent rescaling leaves the observed variables untouched. Changing an\nindicator from raw points to tens of points changes the numerical record\nitself. Let\n\n$$\n\\mathbf y_i^*=\\mathbf b+\\boldsymbol\\Delta\\mathbf y_i,\n$$\n\nwhere $\\boldsymbol\\Delta$ is a nonsingular diagonal matrix of observed-unit\nconversion factors. The matching model is\n\n$$\n\\begin{aligned}\n\\boldsymbol\\nu^*&=\\mathbf b+\\boldsymbol\\Delta\\boldsymbol\\nu,\n&\\boldsymbol\\Lambda^*&=\\boldsymbol\\Delta\\boldsymbol\\Lambda,\\\\\n\\boldsymbol\\Theta^*&=\\boldsymbol\\Delta\\boldsymbol\\Theta\n\\boldsymbol\\Delta^{\\mathsf T},\n&\\boldsymbol\\Sigma^*&=\\boldsymbol\\Delta\\boldsymbol\\Sigma\n\\boldsymbol\\Delta^{\\mathsf T}.\n\\end{aligned}\n$$ {#eq-cfa-observed-rescaling}\n\nThus multiplying one indicator by 10 multiplies its intercept and loading by\n10, its variance and residual variance by 100, and its covariance with an\nunchanged indicator by 10. A fixed shift changes its intercept and mean but\nnot its covariance. Nothing is unidentified in this operation: the same\nobserved information is expressed in different units, and every affected\nmodel quantity must change coherently.\n\nLet $\\mathbf D_y=\\operatorname{diag}(\\boldsymbol\\Sigma)$ contain the positive\nobserved variances. The corresponding correlation model is\n\n$$\n\\begin{aligned}\n\\mathbf R\n&=\\mathbf D_y^{-1/2}\\boldsymbol\\Sigma\\mathbf D_y^{-1/2}\\\\\n&=\\widetilde{\\boldsymbol\\Lambda}\\boldsymbol\\Phi\n\\widetilde{\\boldsymbol\\Lambda}^{\\mathsf T}\n+\\widetilde{\\boldsymbol\\Theta},\n\\end{aligned}\n$$ {#eq-cfa-correlation-reparameterization}\n\nwhere $\\widetilde{\\boldsymbol\\Lambda}=\\mathbf D_y^{-1/2}\n\\boldsymbol\\Lambda$ and $\\widetilde{\\boldsymbol\\Theta}=\n\\mathbf D_y^{-1/2}\\boldsymbol\\Theta\\mathbf D_y^{-1/2}$. This standardizes\nthe indicators, not the factors. With continuous ML and a consistently\ntransformed model, observed-unit rescaling does not change fit. Repeating an\nuntransformed numerical equality constraint after changing units, however,\ntests a different model.\n\n## Three kinds of coefficient output\n\nFor a loading $\\lambda_{ja}$, latent-standardized and fully standardized\nversions are, respectively,\n\n$$\n\\lambda_{ja}^{(\\mathrm{lv})}\n=\\lambda_{ja}\\sqrt{\\phi_{aa}},\n\\qquad\n\\lambda_{ja}^{(\\mathrm{all})}\n=\\lambda_{ja}\\frac{\\sqrt{\\phi_{aa}}}{\\sqrt{\\sigma_{jj}}}.\n$$\n\nThe first expresses a factor change in standard-deviation units while\nretaining the indicator's raw unit. The second standardizes both. In\nour fixed-factor CFA, raw and latent-standardized loadings coincide,\nbut fully standardized loadings generally differ.\n\nStandardizing output after fitting does not impose equal indicator\nvariances during estimation. Moreover, the uncertainty of a standardized\ncoefficient depends on the estimated quantities used in the\ntransformation. Dividing a raw standard error by a displayed rounded\nstandard deviation is not generally the correct standard error for the\nfully standardized coefficient.\n\nA loading greater than one in raw units is unremarkable. Even a\nstandardized pattern coefficient needs to be interpreted in its\nmultivariate context; admissibility concerns the full covariance\ndecomposition. For a single-loading item with uncorrelated residuals,\nthe squared fully standardized loading is its communality. For a\ncross-loading item, use the full quadratic form, not a single square.\n\nThe canonical analysis fits raw observations and then reports standardized\ncoefficients. A correlation matrix removes the original indicator units;\ncovariance-model standard errors computed from that input are not\nautomatically standard errors of fully standardized parameters, whose\ntransformation uses estimated variances. For a CFA whose restrictions are\ninvariant to rescaling, the fit statistic can nevertheless stay the same.\nUnit-dependent equality restrictions, the covariance divisor, and the\nlikelihood convention need their own checks. Section 6.2 distinguishes the\ninformation counts, and Section 7.3 states the divisor convention.\n\n# Trace restrictions into implied moments\n\n## Within-factor and between-factor covariance\n\nFrom the controlled marker-scaled model,\n\n$$\n\\begin{aligned}\n\\operatorname{Var}(Y_2)&=\\lambda_{21}^2\\phi_{11}+\\theta_{22},\\\\\n\\operatorname{Cov}(Y_2,Y_3)&=\\lambda_{21}\\lambda_{31}\\phi_{11},\\\\\n\\operatorname{Cov}(Y_2,Y_5)&=\\lambda_{21}\\lambda_{52}\\phi_{12},\\\\\n\\operatorname{Cov}(Y_5,Y_6)&=\\lambda_{52}\\lambda_{62}\\phi_{22}.\n\\end{aligned}\n$$\n\nThe numerical values are $5.560$, $3.840$, $1.056$, and $8.910$.\nEach expression has a reason. $Y_2$'s variance contains common and\nresidual variance. $Y_2$ and $Y_3$ share factor 1. $Y_2$ and $Y_5$\nare connected through the factor covariance. There is no residual\ncross-term because the base residual matrix is diagonal.\n\nThe diagonal and off-diagonal equations do different work during\nestimation. The covariances inform relations among loadings and factor\ncovariances; the variances also constrain residual variances. An\nimplausibly large common part may force a residual variance toward zero\nor below it. A Heywood case is therefore a symptom of the whole\ndecomposition, not a harmless cosmetic warning.\n\n\n::: {#tbl-cfa-six-sigma .cell layout-align=\"center\" tbl-cap='Full implied covariance matrix from the controlled six-indicator model.'}\n::: {.cell-output-display}\n\n\n|Indicator |Y1    |Y2    |Y3    |Y4     |Y5     |Y6     |\n|:---------|:-----|:-----|:-----|:------|:------|:------|\n|Y1        |6.000 |3.200 |4.800 |1.200  |1.320  |1.080  |\n|Y2        |3.200 |5.560 |3.840 |0.960  |1.056  |0.864  |\n|Y3        |4.800 |3.840 |9.760 |1.440  |1.584  |1.296  |\n|Y4        |1.200 |0.960 |1.440 |12.000 |9.900  |8.100  |\n|Y5        |1.320 |1.056 |1.584 |9.900  |14.890 |8.910  |\n|Y6        |1.080 |0.864 |1.296 |8.100  |8.910  |12.290 |\n\n\n:::\n:::\n\n\nEvery entry of that table comes from the same assembly, and the four\nexpressions above are four of its entries:\n\n$$\n\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)\n=\\boldsymbol\\Lambda\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}\n+\\boldsymbol\\Theta,\n\\qquad\n\\mathbf R=\\mathbf D_y^{-1/2}\\boldsymbol\\Sigma\\mathbf D_y^{-1/2}.\n$$\n\nThe second expression, in the $\\mathbf D_y$ notation of Section 4.3,\nchanges covariance units to correlations; it does not re-estimate the model.\nIn a fitted model, compare the implied covariance to the sample covariance\nusing matching divisors and variable order. Rescaling the fitted matrix to\ncorrelations makes the same implications readable without the original units.\n\n## What the cross-loading adds\n\nNow add $\\lambda_{32}$ to the third indicator's row. Its variance is\n\n$$\n\\sigma_{33}=\\lambda_{31}^2\\phi_{11}\n+\\lambda_{32}^2\\phi_{22}\n+2\\lambda_{31}\\lambda_{32}\\phi_{12}+\\theta_{33}.\n$$\n\nThe covariances with $Y_2$ and $Y_5$ become\n\n$$\n\\begin{aligned}\n\\sigma_{23}&=\\lambda_{21}\n(\\lambda_{31}\\phi_{11}+\\lambda_{32}\\phi_{12}),\\\\\n\\sigma_{35}&=\\lambda_{52}\n(\\lambda_{31}\\phi_{12}+\\lambda_{32}\\phi_{22}).\n\\end{aligned}\n$$\n\nIf $\\lambda_{32}=.25$ while the other controlled parameters stay fixed,\n$\\sigma_{23}$ increases by $.8\\times.25\\times1.2=.240$,\nwhereas $\\sigma_{35}$ increases by $1.1\\times.25\\times9=2.475$.\nThe unequal changes follow from the pathways and factor variances,\nnot a software accident.\n\nThe 500-record simulation introduced in Section 1.3 includes this $.25$\nsecondary loading. The base model here holds it at zero to isolate the\nconsequence of removing one relation. Fitting the complete generating\nspecification later allows us to compare estimates with known truth. This\nsix-indicator example remains separate from the twelve-indicator questionnaire.\n\n## What a residual covariance adds\n\nInstead, in the base model, adding $\\theta_{23}=.5$ changes\n$\\sigma_{23}$ from 3.84 to 4.34 and leaves all other unique covariance\nentries unchanged when the remaining parameters are held fixed.\nThis contrasts sharply with the cross-loading's multi-pair changes.\n\nAfter refitting, other estimates will generally change too. The\ncontrolled comparison holds them fixed only to expose the direct\nalgebraic consequences of the specification. Do not confuse that\nhand calculation with the total change after an optimizer re-estimates\nevery free parameter.\n\n## Means are a separate set of moments\n\nIn covariance-only analysis there are $p(p+1)/2$ observed moments.\nAdding a mean structure adds $p$ more:\n\n$$\nu_{\\mathrm{cov}}=\\frac{p(p+1)}2,\n\\qquad\nu_{\\mathrm{mean+cov}}=\\frac{p(p+1)}2+p.\n$$\n\nIf all indicator intercepts are free and latent intercepts are fixed\nto zero, the extra $p$ mean moments are matched by $p$ extra parameters.\nThe covariance restrictions and df are unchanged. This is different\nfrom testing structured mean differences or constraining intercepts\nacross groups, topics that will become important later.\n\nFreeing every indicator intercept and every latent intercept at once\ndoes not identify a latent origin. For any vector $\\mathbf c$,\n\n$$\n\\boldsymbol\\alpha^*=\\boldsymbol\\alpha+\\mathbf c,\n\\qquad\n\\boldsymbol\\nu^*=\\boldsymbol\\nu-\\boldsymbol\\Lambda\\mathbf c\n$$\n\nproduce the same observed means. Location restrictions are needed in\naddition to scale restrictions. Fixing factor variances to one does not\nremove this location ambiguity.\n\n# Can the parameters be recovered?\n\n## Identification is about the parameter-to-moment mapping\n\nIdentification is a property of the mapping from parameters to moments, and it\nhas to be established for each specification rather than assumed; @bollen1989\ndevelops the general treatment and @joreskog1969 the confirmatory factor case.\nAfter accounting for scale and sign conventions, global identification\nrequires that\n\n$$\n\\boldsymbol\\Sigma(\\boldsymbol\\vartheta_1)\n=\\boldsymbol\\Sigma(\\boldsymbol\\vartheta_2)\n\\quad\\Longrightarrow\\quad\n\\boldsymbol\\vartheta_1=\\boldsymbol\\vartheta_2\n$$\n\nfor admissible parameter vectors in the declared model. Local\nidentification requires uniqueness in a neighborhood. Generic\nidentification permits exceptional parameter sets, such as special\nzero loadings, where recoverability fails. For models with means,\nreplace the covariance mapping by the joint mean-and-covariance mapping.\n\nIdentification is not the existence of an exact solution to every\nsample covariance matrix. An identified overrestricted model usually\ncannot reproduce arbitrary sample moments exactly; estimation finds\nthe closest admissible representation under a stated discrepancy.\nConversely, multiple parameter vectors can reproduce the same moments\neven if an optimizer prints only one of them.\n\n## Count moments and free parameters\n\nCounting begins by choosing one coherent moment representation. For $p$\ncontinuous indicators, a covariance matrix supplies $p(p+1)/2$ distinct\nvariances and covariances. A correlation matrix supplies only $p(p-1)/2$\nfreely varying off-diagonal entries because its $p$ diagonal entries equal\none. Adding an unrestricted observed mean vector contributes another $p$\nmoments.\n\nFor six indicators this gives\n\n| Moment representation | Distinct information |\n|:--|--:|\n| Covariances, including variances | $6(7)/2=21$ |\n| Correlations, with unit diagonals fixed | $6(5)/2=15$ |\n| Covariances plus observed means | $21+6=27$ |\n\nIn covariance form, the fixed-factor two-factor simple-structure model has\nsix loadings, one factor correlation, and six residual variances: $t=13$ and\n$df=21-13=8$. That is the count previewed in Chapter 1, Section 5.3, completed\nhere in both moment representations rather than restated.\nIn correlation form, the six unit-diagonal equations determine\nthe six residual variances, leaving seven free parameters and the same\n$df=15-7=8$. Subtracting all 13 covariance-model parameters from 15\ncorrelations would count standardization twice.\n\nFor the marker-scaled six-indicator base model,\n\n$$\nu=\\frac{6(7)}2=21,\\qquad\nt=4+3+6=13,\\qquad df=21-13=8.\n$$\n\nAdding one cross-loading yields $t=14$, $df=7$. Adding one residual\ncovariance instead gives the same count but a different model. Adding\nboth gives $t=15$, $df=6$. A single independent equality constraint\non two otherwise free loadings reduces the free-axis count by\none. Merely giving a free parameter a label does not change the count.\n\n```{=latex}\n\\Needspace{16\\baselineskip}\n```\n\n| Six-indicator specification | Loading axes | Factor covariance axes | Residual axes | Candidate df |\n|:--|--:|--:|--:|--:|\n| Marker-scaled base | 4 | 3 | 6 | 8 |\n| Fixed-factor base | 6 | 1 | 6 | 8 |\n| Base plus one cross-loading | 5 | 3 | 6 | 7 |\n| Base plus one residual covariance | 4 | 3 | 7 | 7 |\n| Base with one loading equality | 3 | 3 | 6 | 9 |\n\nThe count $df=u-t$ is necessary bookkeeping, not sufficient proof.\nThe term “observed moments” is preferable to “number of observations”\nhere: 21 unique covariance entries are not 21 people. Increasing the\nsample size improves precision under suitable conditions but does not\ncreate new types of covariance moments or repair structural\nnonidentification.\n\nThe same bookkeeping clarifies why a displayed unrestricted EFA loading\nmatrix contains more entries than the model has distinguishable parameters.\nWith six indicators and two unit-variance orthogonal factors, there are 12\nraw loading entries and six residual variances. A two-factor orthogonal\nrotation has $2(2-1)/2=1$ continuous degree of freedom and changes the loading\ndisplay without changing its reproduced covariance. The generic dimension is\n\n$$\nt_{\\mathrm{EFA}}=12+6-\\frac{2(2-1)}2=17,\n\\qquad df=21-17=4.\n$$ {#eq-cfa-efa-dimension}\n\nThis subtraction counts distinct covariance-model axes at regular,\nfull-rank parameter points. It does not declare any substantively preferred\nloading to be known, and it does not replace an identification analysis.\n\nFor the twelve-indicator SLE family, $78/(27+k)/(51-k)$ summarizes moments,\nfree parameters and degrees of freedom when $k$ secondary loadings are free.\nIt applies to twelve active indicators, three correlated unit-variance\nfactors, diagonal residual covariance and no equality restriction. Removing\nan indicator changes the available moments; freeing a residual covariance\nchanges another parameter block; an equality removes a free coordinate.\nEach needs its own ledger rather than an adjustment to $k$.\n\nThe task here is to trace a specification into its count and read what an\nidentification diagnostic adds. It does not require deriving an information\nmatrix, proving global identification with a Jacobian, or implementing an\noptimizer.\n\n## A recoverable block and a counterexample {#sec-recoverable}\n\nFor a single marker-scaled factor with three indicators and diagonal\nresiduals,\n\n$$\n\\sigma_{12}=\\lambda_2\\phi,\n\\quad \\sigma_{13}=\\lambda_3\\phi,\n\\quad \\sigma_{23}=\\lambda_2\\lambda_3\\phi.\n$$\n\nWhen the relevant covariances are nonzero, these imply\n\n$$\n\\phi=\\frac{\\sigma_{12}\\sigma_{13}}{\\sigma_{23}},\n\\quad \\lambda_2=\\frac{\\sigma_{23}}{\\sigma_{13}},\n\\quad \\lambda_3=\\frac{\\sigma_{23}}{\\sigma_{12}}.\n$$\n\nThe diagonal equations then determine residual variances. These\nexpressions explain generic recoverability for this simple block,\nsubject to admissibility. If a denominator vanishes, the reasoning\nmust be revisited; a generic result does not cover every exceptional\nconfiguration.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A marker-scaled three-indicator block. The three off-diagonal covariances can recover the factor variance and two non-marker loadings at regular, nonzero parameter points.](chapter_03_files/figure-html/fig-cfa-three-indicator-1.png){#fig-cfa-three-indicator fig-align='center' fig-pos='H' fig-alt='One factor predicts three indicators, the first loading is fixed to one, and each indicator has a residual.' width=896}\n:::\n:::\n\n\nNow consider two *orthogonal*, isolated two-indicator factors, with\nunit factor variances. Each block has two free loadings and two residual\nvariances but only three covariance moments. Across both blocks there\nare ten available covariance entries and eight free parameters, giving\na superficially favorable $df=2$. Yet the cross-block covariances are\nall fixed to zero and provide no information to separate the two\nloadings within either block. For one block,\n\n$$\n\\sigma_{12}=\\lambda_1\\lambda_2,\n\\quad \\theta_{11}=\\sigma_{11}-\\lambda_1^2,\n\\quad \\theta_{22}=\\sigma_{22}-\\lambda_2^2.\n$$\n\nA range of choices for $\\lambda_1$ can yield the same moments by\nadjusting $\\lambda_2$ and both residual variances, while retaining\npositive variances. The whole-model count did not reveal the local\ndeficiency. Additional indicators or justified restrictions can help;\nadding an arbitrary constraint solely to make software run changes the\nmeasurement model and needs a rationale.\n\nThe diagram pair makes the missing information visible. In the isolated\nmodel, all four cross-block covariances are fixed to zero, so the positive\nwhole-model df do not help identify either two-indicator block. Allowing a\nnonzero factor covariance connects the blocks: cross-block moments then\ncontain products of loadings from both factors. The connected model has nine free parameters and nominal $df=1$, compared\nwith eight and nominal $df=2$ for the isolated model. It is\ngenerically identified under regular nonzero loadings and\n$\\phi_{12}\\ne0$; the argument degenerates when that connection is zero.\n\n\n::: {#fig-cfa-identification-pair .cell layout-ncol=\"2\" layout-align=\"center\"}\n::: {.cell-output-display}\n![Isolated orthogonal blocks](chapter_03_files/figure-html/fig-cfa-identification-pair-1.png){#fig-cfa-identification-pair-1 fig-align='center' fig-pos='H' fig-alt='The left panel shows two separate two-indicator factors. The right panel adds a covariance between the two factors.' width=672}\n:::\n\n::: {.cell-output-display}\n![Connected correlated blocks](chapter_03_files/figure-html/fig-cfa-identification-pair-2.png){#fig-cfa-identification-pair-2 fig-align='center' fig-pos='H' fig-alt='The left panel shows two separate two-indicator factors. The right panel adds a covariance between the two factors.' width=672}\n:::\n\nBoth two-indicator models have positive nominal degrees of freedom, yet different recoverability. Adding the covariance edge increases the free-parameter count from eight to nine and supplies informative cross-block moments.\n:::\n\n\n[]{#sec-single-indicator-reliability}\n\n**One indicator needs external measurement information.** Suppose a study\nhas one continuous score with variance 25. A centered measurement model\nwrites $x=\\eta+\\epsilon$, with loading one and\n$\\operatorname{Cov}(\\eta,\\epsilon)=0$. Its sole variance equation is\n$25=\\phi+\\theta$. Naming the factor and fixing its loading set a metric;\nthey do not separate the two unknown variance components. Repeating the\nsame score would add no observed information.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A one-indicator model needs a scale choice and substantive information about measurement error. The unit loading and externally specified residual variance are fixed; the factor variance is recovered from the observed variance.](chapter_03_files/figure-html/fig-cfa-single-indicator-1.png){#fig-cfa-single-indicator fig-align='center' fig-pos='H' fig-alt='A latent factor eta has a fixed loading of one on observed score x. Its residual epsilon has externally fixed variance (1 minus rho) times 25; the factor variance phi is the one free parameter.' width=1024}\n:::\n:::\n\n\nExternal reliability $\\rho$ means the fraction of this score's variance\nattributable to $\\eta$ under that decomposition. Fixing $\\rho=.8$ fixes\n$\\theta=(1-.8)25=5$, leaving $\\phi=20$. One free variance now matches one\nobserved variance; there is no remaining covariance restriction to test.\nThe fixed error variance contributes measurement information. The fixed\nloading contributes the scale convention.\n\n**Predict and explain.** Keep the observed variance at 25 and assume higher\nreliability. Which component must grow, and which must shrink? Can the\nunchanged reproduction of 25 decide which assumption is credible?\n\n| Externally fixed reliability | Fixed residual variance | Recovered factor variance |\n|--:|--:|--:|\n| .7 | 7.5 | 17.5 |\n| .8 | 5.0 | 20.0 |\n| .9 | 2.5 | 22.5 |\n| 1.0 | 0.0 | 25.0 |\n\n: Exact one-indicator population-moment reconstructions. Every row reproduces observed variance 25; the final row assumes error-free measurement. {#tbl-single-indicator-reliability}\n\nThe higher assumed reliability allocates more variance to the factor and\nless to error without changing the fit to the single available moment.\nThe error-free row is a stronger measurement assumption, not a finding\nfrom the data. These are population-moment illustrations, with no empirical\nsample size or sampling interval.\n\nAn external reliability study must concern the same score definition,\nrelevant population and intended use. A borrowed value is an assumption\nto investigate, and an estimated reliability has its own uncertainty.\nThe rows are an assumption-sensitivity analysis rather than a confidence\ninterval. Fixing one estimated value in a larger model does not propagate\nthat uncertainty. Cronbach's alpha is not automatically a known true\nreliability. The resulting model can represent an error-prone single score,\nbut the restriction still requires a measurement justification [@kline2013].\n\n## Restriction is what replaces rotation\n\nIt is worth being explicit about why identification becomes a live question\nhere rather than earlier. An exploratory model is unidentified by\nconstruction: for any nonsingular $\\mathbf T$, the pair\n$\\boldsymbol\\Lambda\\mathbf T^{-1}$ and\n$\\mathbf T\\boldsymbol\\Phi\\mathbf T^{\\mathsf T}$ reproduces the same covariance,\nso a whole continuous family of loading matrices is observationally\nequivalent, and rotation selects one member of it by a stated criterion.\n\nA confirmatory model does not select from that family; it removes it. Once\nenough loadings are fixed at zero, no nontrivial $\\mathbf T$ maps the pattern\nonto itself -- a rotation that preserved the zeros would have to be diagonal,\nand the scaling convention then fixes what remains up to sign. That is the\ntrade. Exploratory analysis buys freedom from prior commitment at the cost of\nnever identifying its axes; confirmatory analysis buys identified parameters\nat the cost of having to defend every zero.\n\nBecause the zeros do the work, identification now depends on *where* they are,\nnot only on how many there are. Two sufficient conditions cover most applied\nspecifications [@bollen1989; @brown2006], and both assume a diagonal residual\ncovariance matrix and a scale fixed for each factor:\n\n- **Three indicators per factor.** A factor with at least three indicators\n  that load on it alone is identified, whether or not it correlates with\n  anything else. @sec-recoverable did this case explicitly.\n- **Two indicators per factor.** A factor with only two exclusive indicators\n  is identified when it is *connected* to the rest of an identified\n  measurement model: it must have a nonzero covariance with at least one other\n  identified factor, and the parameter values must be regular, meaning that\n  the cross-block covariances carrying the information are not themselves\n  zero. The orthogonal counterexample above fails exactly this condition --\n  the connecting covariances were fixed at zero, so no information reached the\n  block.\n\nStated with those conditions attached, both are sufficient for generic\nidentification; they are not necessary, and models that violate them may still\nbe identified. The second rule is the more fragile of the two, because it\ndepends on a quantity that is estimated rather than assumed. If the connecting\ncorrelation is genuinely zero in the population, the rule simply does not\napply. If it is nonzero in the population but estimated near zero in a\nparticular sample, the model remains identified in principle while behaving in\nestimation as though it were not. That is the situation the next section calls\nweak identification, and its symptoms are unstable estimates and enormous\nstandard errors rather than an error message.\n\n## Structural, weak, and numerical problems\n\nStructural nonidentification is built into the parameter mapping.\nWeak identification describes a formally recoverable model whose\nparameters are poorly distinguished in a particular configuration.\nSmall loadings, nearly proportional loading columns, or factor\ncorrelations close to one can make very different parameter vectors\nproduce nearly indistinguishable moments. Numerical difficulty is\nanother issue: unsuitable starts or badly scaled variables can impede\nan optimizer even when a well-behaved optimum exists.\n\n```{=latex}\n\\Needspace{18\\baselineskip}\n```\n\n| Check | Warning | What it warrants |\n|:--|:--|:--|\n| Moment count | More free parameters than moments | Reconsider specification |\n| Metric and sign | No normalization or inconsistent orientation | Specify units and signs |\n| Local connections | Isolated insufficient indicator block | Examine block equations |\n| Loading rank | Redundant factor patterns | Examine distinct common directions |\n| Factor covariance | Near singularity | Investigate weak separation |\n| Residual variances | Zero or negative estimates | Inspect admissibility and misspecification |\n| Information/SEs | Singular matrix or unstable large SEs | Check recoverability and numerical behavior |\n| Starts and gradients | Different optima or nonzero gradient | Resolve optimization before interpretation |\n\nA numerical derivative matrix provides a local diagnostic. If\n$\\mathbf s(\\boldsymbol\\vartheta)$ stacks the distinct implied moments,\nits Jacobian is\n$\\partial\\mathbf s/\\partial\\boldsymbol\\vartheta^{\\mathsf T}$.\nFull column rank at a regular point supports local identification;\nit does not prove global uniqueness or uniform stability throughout\nthe parameter space. Students need not derive this matrix to understand\nwhat the diagnostic adds beyond counting.\n\nThe SLE primary fit has numerical Jacobian rank\n29 for 29 free parameters.\nThat is a useful local check of the actual fitted candidate. The\nthree blocks also have several pure primary indicators, so the two\nretained cross-loadings do not leave every factor's orientation open\nas in unrestricted EFA.\n\n## Nested, nonnested, and equivalent models\n\nA restricted model is nested in another if every covariance matrix it\ncan generate belongs to the larger model's covariance set. Show the\nrestrictions that produce that inclusion; a parameter-count comparison\nalone is not enough. The base six-indicator model is nested in its\ncross-loading extension by setting $\\lambda_{32}=0$.\n\nTwo models can have the same df and different covariance sets, as with\nan alternative indicator assignment. They can also have different-looking\nparameters but identical covariance sets, as with the regular marker\nand fixed-factor reparameterizations. Observational equivalence limits\nwhat covariance data can distinguish. It does not establish that\nhigher-order, bifactor, and correlated-residual models are generally\nequivalent; each such claim requires an exact mapping and conditions.\n\nOne deliberately constrained example shows what an exact mapping looks like.\nFor two positively correlated first-order factors, fix both second-order\nloadings to one, set $\\operatorname{Var}(G)=\\phi_{12}$, and set the two\nfirst-order disturbance variances to $\\phi_{11}-\\phi_{12}$ and\n$\\phi_{22}-\\phi_{12}$. When these variances are nonnegative, the second-order\nparameterization reproduces exactly the same $2\\times2$ factor covariance\nmatrix. Without the two extra scale/equality restrictions, two first-order\nfactors do not by themselves identify a second-order factor. Chapter 4 develops the case with three first-order factors and then a\ndistinct bifactor structure. Those models express alternative measurement\nstructures; they are not generic remedies for a weak initial model.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A correlated two-factor model and one constrained second-order reparameterization. The equivalence requires the stated fixed loadings and admissible disturbance variances.](chapter_03_files/figure-html/fig-cfa-equivalent-pair-1.png){#fig-cfa-equivalent-pair fig-align='center' fig-pos='H' fig-alt='The left model connects two first-order factors with a covariance. The right model replaces that covariance with one general factor loading one-to-one on each first-order factor.' width=1120}\n:::\n:::\n\n\nThese distinctions prepare comparison. They do not yet say which\ncandidate is adequate or which restriction the data oppose.\n\n# What estimation does\n\n## Minimize a stated discrepancy\n\nLet $\\mathcal P$ be the admissible parameter space and $\\mathbf S$\nthe sample covariance under a declared divisor. Covariance estimation\ncan be written\n\n$$\n\\widehat{\\boldsymbol\\vartheta}\n=\\arg\\min_{\\boldsymbol\\vartheta\\in\\mathcal P}\nF\\{\\mathbf S,\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)\\}.\n$$\n\nFor normal-theory ML, a conventional covariance discrepancy is\n\n$$\nF_{\\mathrm{ML}}\n=\\log|\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)|\n+\\operatorname{tr}\\{\\mathbf S\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)^{-1}\\}\n-\\log|\\mathbf S|-p.\n$$\n\nThe determinant summarizes multivariate dispersion; the trace term\ncompares the sample covariance to the model's inverse-covariance\nweighting. The last two terms depend only on the input matrix and\ndimension. They normalize the discrepancy to zero when\n$\\boldsymbol\\Sigma=\\mathbf S$, because\n$\\operatorname{tr}(\\mathbf S\\mathbf S^{-1})=p$.\nThe dimension term is the number of observed variables, not the\nnumber of indicators plus factors.\n\nAt a proper optimum, numerical changes in the free parameters cannot\nmaterially lower the objective under the specified constraints.\nThat is an optimization statement. It does not imply small absolute\ndiscrepancy, plausible parameter meaning, or a unique substantive model.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Conceptual estimation geometry. The curve represents a restricted set of moments, not the literal dimension or shape of this CFA.](chapter_03_files/figure-html/fig-cfa-estimation-1.png){#fig-cfa-estimation fig-align='center' fig-pos='H' fig-alt='Observed moments lie away from a curve of model-implied moments; a dashed arrow points to a selected model point, with a warning that ML is not Euclidean distance.' width=1056}\n:::\n:::\n\n\n## Normality belongs to the likelihood contract\n\nThe factor covariance equation follows from linearity, finite second\nmoments, and the stated zero covariances. It does not require normality.\nConventional normal-theory ML standard errors and tests additionally\nuse sampling and distributional regularity. Where the departure is\nnonnormality of the observed variables under independent sampling, scaled\ncorrections to the test statistic and standard errors are the standard remedy\n[@satorraBentler1994]. They do not address dependence between cases,\nclustering, or selection, each of which needs its own treatment. Independently distributed\nnormal factors and normal residuals give a jointly normal observed\nvector in this linear model. Marginally normal histograms alone do not\nestablish multivariate normality or independent sampling.\n\nSample B consists of 360 complete, independently simulated continuous\nrecords. There is no silent missing-case removal, imputation, weighting,\nclustering adjustment, or ordinal recoding. The raw indicators retain\nthe fixed process-index units.\n\nThe estimated model is the inherited candidate, unchanged:\n\n```{=latex}\n\\Needspace{18\\baselineskip}\n```\n\n$$\n\\boldsymbol\\Lambda=\n\\begin{bmatrix}\n\\boldsymbol\\lambda_{\\mathrm P}&\\mathbf 0&\\mathbf 0\\\\\n\\mathbf 0&\\boldsymbol\\lambda_{\\mathrm S}&\\mathbf 0\\\\\n\\mathbf 0&\\mathbf 0&\\boldsymbol\\lambda_{\\mathrm B}\n\\end{bmatrix}\n\\ \\text{with two entries freed},\n\\qquad\n\\boldsymbol\\Phi=\n\\begin{bmatrix}\n1&\\phi_{12}&\\phi_{13}\\\\\n\\phi_{12}&1&\\phi_{23}\\\\\n\\phi_{13}&\\phi_{23}&1\n\\end{bmatrix}.\n$$\n\nHere $\\boldsymbol\\Lambda$ is $12\\times3$, with\n$\\boldsymbol\\lambda_{\\mathrm P}$, $\\boldsymbol\\lambda_{\\mathrm S}$ and\n$\\boldsymbol\\lambda_{\\mathrm B}$ each $4\\times1$ and free. The two freed\nentries are P4 on Strategy, in the fourth row of the second column, and S4 on\nBelonging, in the eighth row of the third column. Fourteen of the thirty-six\nloading slots are therefore free and twenty-two are fixed at zero;\n$\\boldsymbol\\Theta$ is diagonal of order twelve; and the Planning\ncoefficients of P1 and P2 are the two named for the planned equality of\nSection 8.5.\n\nThe estimation settings are stated rather than inherited: normal-theory\nmaximum likelihood on the raw records, the normal likelihood scaling of the\ncovariance discrepancy, unit factor variances rather than marker loadings, no\nmean structure, listwise deletion of incomplete cases, conventional standard\nerrors and a conventional test statistic, and expected information for both.\nSection 7.3 records the divisor the normal scaling implies.\n\nSample B is the confirmation record in the released\n`sle_continuous.csv`; the exploratory chapter's data appendix gives the\ncodebook and sample manifest.\nBefore fitting, the chapter source checks the released file against the\ndeclared population: the column names and order, the row count for each\nsample, the case identifiers, and every indicator value. Numerically coded columns alone are not sufficient evidence\nof a continuous measurement scale.\n\nCategorical indicators are covered elsewhere. Categorical group labels\nand dummy predictors remain available for later multigroup and MIMIC\nmodels. Later SEM chapters address robust ML inference for nonnormality\nand FIML for missing continuous data under suitable assumptions; neither\nis a categorical-measurement switch.\n\n## Record the covariance divisor\n\nThe normal-likelihood convention uses\n\n$$\n\\mathbf S_N=\\frac1N\\sum_{i=1}^N\n(\\mathbf y_i-\\bar{\\mathbf y})(\\mathbf y_i-\\bar{\\mathbf y})^{\\mathsf T}\n=\\frac{N-1}{N}\\mathbf S_{N-1}.\n$$\n\nR's `cov()` uses $N-1$; `lavaan` performs the normal-likelihood\nrescaling internally. Do not pre-rescale raw observations to compensate.\nWhen working from a covariance matrix rather than raw data, disclose\nthe supplied divisor and package rescaling options. The [estimator\ndocumentation](https://lavaan.ugent.be/tutorial/est.html) distinguishes\nthe normal and Wishart conventions explicitly.\n\nFor the normal convention, the model statistic uses $N$ times the\ncovariance discrepancy. The Wishart convention uses an $N-1$ covariance\nand multiplier. Chapter 2's corrected exploratory statistic is a\nfurther distinct finite-sample convention. This chapter records the\nnormal family without interpreting its model test.\n\n## A small mean-structure comparison\n\nThe fixed M1-cross has 78 covariance moments, 29 free covariance\nparameters, and 49 df. Adding twelve free indicator intercepts while\nkeeping latent intercepts zero gives 90 moments, 41 free parameters,\nand the same 49 df. For the stricter M0-simple model the corresponding\ncounts are 78/27/51 and 90/39/51.\n\n\n::: {#tbl-cfa-mean-counts .cell layout-align=\"center\" tbl-cap='Counts verified against actual fitted parameter tables. The mean extension does not constrain the indicator means.'}\n::: {.cell-output-display}\n\n\n|Model              |Moments |Free |Df |\n|:------------------|:-------|:----|:--|\n|M1 covariance      |78      |29   |49 |\n|M1 free intercepts |90      |41   |49 |\n|M0 free intercepts |90      |39   |51 |\n\n\n:::\n:::\n\n\nThe largest difference between the M1 covariance-only and free-intercept\nimplied covariance matrices is\n0e+00.\nThe estimated free intercepts reproduce the sample means. This verifies\nthe intended separation of covariance restrictions from an unrestricted\nmean extension. It does not justify freely estimating latent origins\nwithout additional constraints.\n\n# Read estimates and evaluate the model\n\n## Convergence and admissibility first\n\nConvergence, admissibility, gradients, and local rank are checked before\nany coefficient or fit index is read. These numerical checks establish that\nthe solution can be interpreted; global and local evaluation follow in\nSection 8.8.\n\nThe optimizer reports convergence for the inherited M1-cross model,\nwith no captured fitting warnings. The maximum absolute gradient is\n3.5e-07.\nAll residual variances are positive, the factor covariance and implied\ncovariance matrices are positive definite, and standard errors are\navailable. The smallest information-matrix eigenvalue is positive,\nalthough its magnitude depends on parameter scaling and is not a\nuniversal quality index.\n\n\n::: {#tbl-cfa-audit .cell layout-align=\"center\" tbl-cap='Selected estimation gates for the actual Sample B primary fit. Passing these gates does not establish adequate fit.'}\n::: {.cell-output-display}\n\n\n|Check                       |Passed |\n|:---------------------------|:------|\n|Converged                   |TRUE   |\n|No warnings                 |TRUE   |\n|Positive residual variances |TRUE   |\n|Positive factor covariance  |TRUE   |\n|Positive implied covariance |TRUE   |\n\n\n:::\n:::\n\n\nIf convergence fails, first inspect the stated model, data, scale, and\nstarting values. If convergence succeeds but a variance is negative,\nthe solution is improper for this model. Do not proceed directly to\nfit-index interpretation or replace the negative value by zero in a\nreport. If an admissible fit has large standard errors or near-perfect\nfactor correlations, examine weak separation and sensitivity. Different\nwarnings imply different investigations.\n\nThese checks are reproducible from `lavInspect()` and the parameter\ntable. They are diagnostics at the fitted point; they do not substitute\nfor the earlier structural identification reasoning.\n\n```{=latex}\n\\Needspace{26\\baselineskip}\n```\n\n## Read loadings in their stated units\n\n\n::: {#tbl-cfa-loadings .cell layout-align=\"center\" tbl-cap='Sample B loadings for the frozen M1-cross. Intervals are 95 percent normal-approximation intervals for raw coefficients. Std. all is a point estimate on the fully standardized metric.'}\n::: {.cell-output-display}\n\n\n|Factor    |Item |Raw   |SE    |Lower |Upper  |Std.all |\n|:---------|:----|:-----|:-----|:-----|:------|:-------|\n|Planning  |P1   |6.304 |0.407 |5.507 |7.102  |0.770   |\n|Planning  |P2   |7.810 |0.520 |6.791 |8.830  |0.751   |\n|Planning  |P3   |8.407 |0.629 |7.174 |9.640  |0.684   |\n|Planning  |P4   |4.734 |0.472 |3.809 |5.658  |0.519   |\n|Strategy  |S1   |7.524 |0.494 |6.556 |8.493  |0.751   |\n|Strategy  |S2   |6.114 |0.422 |5.287 |6.940  |0.724   |\n|Strategy  |S3   |7.860 |0.579 |6.725 |8.996  |0.687   |\n|Strategy  |S4   |5.438 |0.424 |4.607 |6.270  |0.622   |\n|Strategy  |P4   |3.288 |0.460 |2.387 |4.190  |0.361   |\n|Belonging |B1   |8.619 |0.450 |7.737 |9.502  |0.888   |\n|Belonging |B2   |9.210 |0.565 |8.102 |10.317 |0.784   |\n|Belonging |B3   |4.925 |0.407 |4.127 |5.723  |0.616   |\n|Belonging |B4   |4.695 |0.554 |3.608 |5.781  |0.453   |\n|Belonging |S4   |2.569 |0.398 |1.790 |3.348  |0.294   |\n\n\n:::\n:::\n\n\nFor P1, a one-standard-deviation increase in Planning corresponds to\nan estimated 6.304 process-index-point change through\nthe specified loading relation. Its standard error is\n0.407, and its 95% interval runs from\n5.507 to 7.102.\nThe fully standardized loading, 0.77, expresses\nthe same relation relative to P1's model-implied standard deviation.\nNeither magnitude is a causal effect established by this analysis.\n\nP4 and S4 each have two rows because two loadings were fixed as free\nbefore Sample B was inspected. In this restricted CFA, the secondary\ncoefficients are estimated jointly with all other free parameters.\nThey need not equal the rotated EFA coefficients from another sample,\nanother matrix metric, and a less restricted loading model.\n\nThe signs and intervals support reading these as positive conditional\nrelations within the specified model. They do not license removing\nother restrictions without evaluation. A precise coefficient can be\nestimated inside a model whose broader covariance representation is\ninadequate.\n\n```{=latex}\n\\Needspace{9\\baselineskip}\n```\n\n## Standard errors, intervals, and tests\n\nFor a regular interior parameter with null value $\\vartheta_0$,\n\n$$\nz=\\frac{\\widehat\\vartheta-\\vartheta_0}\n{\\operatorname{SE}(\\widehat\\vartheta)},\n\\qquad\n\\widehat\\vartheta\\ \\pm\\ 1.96\\operatorname{SE}(\\widehat\\vartheta)\n$$\n\ngive a conventional asymptotic test and 95% interval under the stated\nML assumptions. The interval concerns repeated-sample coverage of a\npopulation parameter under that model. It is not a range containing\n95% of individual factor scores or item responses.\n\nNormal approximations deserve particular caution for boundary variances,\nstrongly asymmetric sampling distributions, weak identification, and\nmisspecified distributional assumptions. A fixed parameter has no\nsampling standard error as a freely estimated quantity: its printed\nvalue of one or zero is a specification, not a highly precise discovery.\nSoftware may print zero SE and omit its $z$ test for that reason.\n\nStatistical significance also differs from measurement importance.\nA small loading can be precisely estimated in a large sample; a\ncontent-essential loading may be uncertain in a small sample. Deleting\nitems solely because $p>.05$ changes the model and the content represented.\nThat decision needs more than a significance column.\n\n## Factor relations and residual variance\n\n\n::: {#tbl-cfa-factor-relations .cell layout-align=\"center\" tbl-cap='Estimated factor correlations under fixed-factor scaling, with raw-metric intervals. Here the raw factor covariance is itself a correlation.'}\n::: {.cell-output-display}\n\n\n|Factor1  |Factor2   |Correlation |SE    |Lower |Upper |\n|:--------|:---------|:-----------|:-----|:-----|:-----|\n|Planning |Strategy  |0.406       |0.058 |0.292 |0.519 |\n|Planning |Belonging |0.289       |0.059 |0.174 |0.405 |\n|Strategy |Belonging |0.289       |0.060 |0.171 |0.407 |\n\n\n:::\n:::\n\n\nAll three correlations are positive and distinct from one in the\nreported point solution. A correlation is not the percentage of one\nfactor caused by another. It also does not measure the reliability\nof either factor. Later structural models place restrictions on these\nassociations; measurement estimation alone does not select their\ndirection.\n\nFor a single-loading item, the standardized residual variance is\n$\\theta_{jj}/\\sigma_{jj}$ and the common proportion is its complement.\nFor a cross-loading item,\n\n$$\nh_j^2=\\frac{\\boldsymbol\\lambda_j^{\\mathsf T}\n\\boldsymbol\\Phi\\boldsymbol\\lambda_j}{\\sigma_{jj}}.\n$$\n\nThe numerator includes cross-products involving factor correlations.\nIt is not generally the sum of two squared standardized coefficients.\nResidual variance can include specific stable influences and random\nmeasurement error; the factor model does not automatically separate\nthose components.\n\n## A planned equality test\n\nM3-equal was named in Chapter 2: it constrains the raw Planning loadings\nof P1 and P2 to equality. Let $\\mathbf R\\boldsymbol\\vartheta=\\mathbf r$\nrepresent $q$ independent linear restrictions. The Wald statistic is\n\n$$\nW=(\\mathbf R\\widehat{\\boldsymbol\\vartheta}-\\mathbf r)^{\\mathsf T}\n\\left[\\mathbf R\\widehat{\\operatorname{Var}}\n(\\widehat{\\boldsymbol\\vartheta})\\mathbf R^{\\mathsf T}\\right]^{-1}\n(\\mathbf R\\widehat{\\boldsymbol\\vartheta}-\\mathbf r).\n$$\n\nUnder suitable regularity, its reference is $\\chi_q^2$. For one\nloading difference, the estimated variance is\n\n$$\n\\operatorname{Var}(\\widehat\\lambda_{\\mathrm{P1}}\n-\\widehat\\lambda_{\\mathrm{P2}})\n=\\operatorname{Var}(\\widehat\\lambda_{\\mathrm{P1}})\n+\\operatorname{Var}(\\widehat\\lambda_{\\mathrm{P2}})\n-2\\operatorname{Cov}(\\widehat\\lambda_{\\mathrm{P1}},\n\\widehat\\lambda_{\\mathrm{P2}}).\n$$\n\nIgnoring the covariance between estimates can give the wrong test.\nWith the free parameters in the order the fitted model reports them, the\nplanned restriction is the single row\n\n$$\n\\mathbf R=(\\,1,\\;-1,\\;0,\\ldots,0\\,),\n\\qquad \\mathbf r=0,\\qquad q=1,\n$$\n\nthe $1$ and $-1$ standing in the positions of the two named Planning\ncoefficients, so those two are the only parameters the test touches.\nThe equality can also be imposed and the restricted model refitted;\nthat supplies a likelihood-ratio view of the same substantive restriction.\n\nHere $W=$ 6.911 on one df, with\n$p$ = 0.009. Under the declared model and\nnormal approximation, the data oppose this particular raw-loading\nequality. This is not a test that M1 is globally adequate, nor a\ntest of equality of fully standardized loadings. The Wald perspective is\none of three views of the same restriction; the restricted-model and\nlikelihood-ratio views belong with model comparison.\n\n## Carry the exact candidate, not an assumed baseline\n\nThe inherited model has twelve indicators, three correlated factors,\nand two additional loadings. Its fixed-factor covariance ledger is\n\n$$\nu=78,\\qquad\nt=14\\text{ loadings}+12\\text{ residual variances}\n+3\\text{ factor correlations}=29,\\qquad df=49.\n$$\n\nThe simpler 27-parameter, 51-df model remains M0-simple, a named rival.\nIt is not silently substituted for the inherited model. The all-item\none-factor rival, the orthogonal restriction, and the raw-loading\nequality retain their Chapter 2 definitions. Models keep their M0--M4\nidentifiers across the three chapters; the separate example models use\nD1--D4, and a later data-developed revision will use an R identifier.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The exact M1-cross structure carried into evaluation, not a redrawn simple-structure substitute.](chapter_03_files/figure-html/fig-cfa-handoff-1.png){#fig-cfa-handoff fig-align='center' fig-pos='H' fig-alt='Three correlated SLE factors have twelve primary indicator relations and the two frozen additional loadings, P4 on Strategy and S4 on Belonging.' width=1120}\n:::\n:::\n\n\n```{=latex}\n\\Needspace{25\\baselineskip}\n```\n\n## Save what another analyst needs\n\n| Record component | What the reproducible record carries |\n|:--|:--|\n| Evidence identity | Sample B role, 360 rows, item order and case identifiers |\n| Measurement specification | Fixed syntax, active item list, factors and all rivals |\n| Parameter conventions | Unit factor variances, zero latent location, covariance-only model |\n| Estimation | ML, normal likelihood, expected-information standard errors |\n| Data handling | Complete continuous raw observations; no weights or clustering |\n| Numerical status | Convergence, warnings, gradients, admissibility, local rank |\n| Parameter output | Full free/fixed ledger, estimates, SEs, intervals, standardizations |\n| Fitted moments | Observed $\\mathbf S_N$ and exact model-implied covariance |\n| Evaluation fields | Conventional test, df, RMSEA/interval, CFI/TLI, SRMR, log likelihood, AIC/BIC |\n| Reproduction | R and package versions, and the model syntax |\n\nKeep full-precision fitted results with the model declarations and analysis\nsettings. Rounded tables make the study readable, but reconstructing a\ncovariance matrix from those rounded coefficients can introduce avoidable\ndifferences. Another analyst should be able to refit the same observations\nunder the same specification and recover the results within numerical\ntolerance. Later comparisons must preserve this analysis identity while\nmaking each changed restriction explicit.\n\nThe numerical marker/fixed-factor comparison also succeeds for both\nrecords. For the SLE fit, the largest absolute difference in implied\ncovariance is\n1.4e-04;\nfor the six-indicator example fit it is\n2.5e-06.\nThe small numerical tolerances reflect separate optimization, not a\ntheoretical discrepancy between valid scale choices.\n\nThe record preserves both results and their conditions of interpretation.\nThe following basic evaluation belongs to that record; it neither selects\na revised model nor spends the independent validation sample.\n\n## Complete a basic global and local evaluation\n\nAn estimate says which member of the specified model family best reproduces\nthe records under the chosen discrepancy. Evaluation asks how that member\nrelates to the observations and to the population claim. Start with the\n**exact-fit hypothesis**: some admissible parameter vector reproduces the\npopulation covariance,\n\n$$\nH_0:\\ \\boldsymbol\\Sigma(\\boldsymbol\\vartheta)=\\boldsymbol\\Sigma_0.\n$$\n\nUnder independent, jointly Normal observations and suitable identification\nand regularity conditions, $T=N\\widehat F_{\\mathrm{ML}}$ has an asymptotic\nchi-square reference with $df=u-t$. The tail probability describes evidence\nagainst this exact restriction. A large value can oppose exact fit without\nshowing where the discrepancy lies or whether it is consequential for the\nintended use. Nonrejection indicates compatibility at the available precision;\nit does not accept the measurement model as true.\n\nThe rest of the basic profile addresses related questions. **RMSEA** estimates\ndiscrepancy per degree of freedom, truncating negative estimates of the\nunderlying noncentrality at zero. Its 90% interval reminds us that the point\nestimate is uncertain. **CFI** and **TLI** compare the model with a declared\nbaseline, usually one that retains indicator variances while setting their\ncovariances to zero. **SRMR** summarizes observed-minus-implied covariance\nresiduals after scaling by observed indicator standard deviations. These\nmeasures do not supply interchangeable verdicts.\n\n| Evidence | Question it addresses | Limit of the answer |\n|:--|:--|:--|\n| Chi-square test and $p$ value | Are the exact population moment restrictions opposed? | Sensitive to sample size; does not locate or measure substantive importance |\n| RMSEA and 90% interval | How large is estimated discrepancy per df, with what uncertainty? | Depends on model size and df; zero can arise from truncation |\n| CFI and TLI | How much does the target improve over its baseline? | A poor baseline can make improvement look impressive |\n| SRMR | How large are scaled covariance residuals on average? | Many small cells can conceal a few consequential discrepancies |\n\n: A basic fit profile asks several questions about the same declared model. {#tbl-cfa-basic-fit-meanings tbl-colwidths=\"[24,38,38]\"}\n\n\n::: {#tbl-cfa-basic-profiles .cell layout-align=\"center\" tbl-cap='Basic profiles for two separate examples. Each row evaluates its own declared model and evidence; it is not a likelihood comparison between rows. RMSEA brackets are 90 percent intervals.'}\n::: {.cell-output-display}\n\n\n|Model         |Chi square |df |p     |RMSEA |CI 90      |CFI   |TLI   |SRMR  |\n|:-------------|:----------|:--|:-----|:-----|:----------|:-----|:-----|:-----|\n|Simulation    |8.469      |7  |0.293 |0.02  |[0, 0.061] |0.999 |0.998 |0.016 |\n|Questionnaire |48.475     |49 |0.494 |0.00  |[0, 0.034] |1.000 |1.000 |0.032 |\n\n\n:::\n:::\n\n\nFor the correctly specified simulated model, $T=8.469$ on 7 df gives\n$p=.293$. The result is compatible with the generating structure, but the\nsample has not recovered population values without error. For example, the\nsecond loading of $Y_3$ was generated as .25; under the same marker metric\nits estimate is 0.232.\nThe population/sample/fitted panels in @fig-cfa-population-sample now have\nseparate roles: known truth for the simulation, realized evidence, and the\nmodel's best-fitting reproduction.\n\nThe questionnaire's fixed candidate has a favorable global profile. Its zero\nRMSEA is a truncation, not an assertion that all residuals are zero. Its TLI\nis slightly above one before reporting precision; an incremental index need\nnot be a proportion bounded by one. Neither fact licenses a universal\nacceptance rule. We still need to inspect where the covariance reproduction\nsucceeds or strains.\n\nDefine a covariance residual and its observed-SD-scaled form by\n\n$$\ne_{jk}=S_{N,jk}-\\widehat\\Sigma_{jk},\n\\qquad\ne^{(s)}_{jk}=\\frac{e_{jk}}{\\sqrt{S_{N,jj}S_{N,kk}}}.\n$$\n\nThe sign is informative: a positive entry means that the model reproduces\nless association than the sample contains. A raw residual uses the product\nof the indicators' units; the scaled value facilitates comparison across\npairs. It is neither an estimated residual-covariance parameter in\n$\\boldsymbol\\Theta$ nor a discrepancy divided by its sampling standard error.\nCalling it a $z$ statistic would attach an unsupported reference distribution.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Observed-SD-scaled covariance residuals for the fixed questionnaire model in Sample B. The lower triangle includes the diagonal; color limits are minus .1 and plus .1. Numeric signs identify over- and under-reproduction.](chapter_03_files/figure-html/fig-cfa-basic-local-residuals-1.png){#fig-cfa-basic-local-residuals fig-align='center' fig-pos='H' fig-alt='A twelve-indicator residual matrix has small average discrepancy but several negative residuals involving B4, including minus .093 with S3.' width=1088}\n:::\n:::\n\n\nFor B4 and S3, the observed covariance is $-.371$ and the fitted covariance\nis $10.66$, giving a raw residual of $-11.031$ and a scaled residual of\n$-.093$. The model over-reproduces this particular cross-domain association.\nThat localized discrepancy can coexist with SRMR .032 and a nonrejected\nexact-fit test. It raises a question about the representation without\nuniquely identifying a cause or justifying a new path. Selecting and testing\na revision requires an explicit account of how the change was chosen and\nwhat fresh evidence can assess it.\n\n## An empirical model from raw and summary information\n\nThe previous simulation tells us the generating structure because we supplied\nit. Historical measurements do not offer that privilege. Holzinger and\nSwineford's ability-test records, distributed with the `lavaan` package,\nprovide 301 pupils from the Pasteur and Grant-White schools. The\n[documented nine-test example](https://lavaan.ugent.be/tutorial/cfa.html)\nuses three proposed domains: visual, textual and speed. The records come from\nseventh- and eighth-grade pupils; we pool the two schools for this illustration.\nPooling is an analysis decision, not evidence that the measurement relations\nare invariant across schools.\n\n| Proposed domain | Indicators in this analysis |\n|:--|:--|\n| Visual | x1 visual perception; x2 cubes; x3 lozenges |\n| Textual | x4 paragraph comprehension; x5 sentence completion; x6 word meaning |\n| Speed | x7 speeded addition; x8 counting dots; x9 straight-curved capitals |\n\n: Nine recorded test scores and their proposed domains. {#tbl-cfa-empirical-indicators}\n\nFit one correlated three-factor model with each indicator loading on its\nassigned factor only. Set factor variances to one, free the three factor\ncovariances and nine residual variances, and set residual covariances to\nzero. All nine selected scores are observed for all 301 pupils. Keep the\nnormal-theory ML convention, expected-information standard errors and\ncovariance-only model. The ledger is $9(10)/2=45$ distinct moments minus\n$9+9+3=21$ free parameters, giving 24 df.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A declared three-factor model for the nine historical tests. Factor variances equal one, all three factor covariances are free, and unshown loadings and residual covariances are zero.](chapter_03_files/figure-html/fig-cfa-empirical-model-1.png){#fig-cfa-empirical-model fig-align='center' fig-pos='H' fig-alt='Visual predicts x1 to x3, Textual predicts x4 to x6 and Speed predicts x7 to x9. The three factors covary and each test has its own residual.' width=1040}\n:::\n:::\n\n\n\n::: {#tbl-cfa-empirical-loadings .cell layout-align=\"center\" tbl-cap='One selected loading from each domain, under unit-factor-variance scaling. Intervals and standard errors are on the raw indicator metric; the last column is a standardized point estimate.'}\n::: {.cell-output-display}\n\n\n|Domain  |Indicator |Estimate |SE    |Lower |Upper |Standardized |\n|:-------|:---------|:--------|:-----|:-----|:-----|:------------|\n|Visual  |x1        |0.900    |0.081 |0.741 |1.058 |0.772        |\n|Textual |x4        |0.990    |0.057 |0.879 |1.101 |0.852        |\n|Speed   |x7        |0.619    |0.070 |0.483 |0.756 |0.570        |\n\n\n:::\n:::\n\n\nA visual-factor increase of one model SD corresponds to an expected x1\nincrease of .9 test-score units, with a 95% interval [.741, 1.058]. This\nconditional measurement relation does not mean that manipulating an\nunobserved ability would necessarily change the test score by that amount.\nBefore treating any loading as a satisfactory measurement relation, consider\nthe model that makes its interpretation possible.\n\n\n::: {#tbl-cfa-empirical-fit .cell layout-align=\"center\" tbl-cap='The same empirical model fitted from individual records and their exact derived covariance matrix. The rows use identical likelihood, scaling, missing-data and uncertainty conventions.'}\n::: {.cell-output-display}\n\n\n|Model   |Chi square |df |p      |RMSEA |CI 90          |CFI   |TLI   |SRMR  |\n|:-------|:----------|:--|:------|:-----|:--------------|:-----|:-----|:-----|\n|Raw     |85.306     |24 |< .001 |0.092 |[0.071, 0.114] |0.931 |0.896 |0.065 |\n|Summary |85.306     |24 |< .001 |0.092 |[0.071, 0.114] |0.931 |0.896 |0.065 |\n\n\n:::\n:::\n\n\nThe exact-fit test rejects at $p<.001$: $T=85.306$ on 24 df. RMSEA .092 has\n90% interval [.071, .114], CFI is .931, TLI .896 and SRMR .065. The model\nsummarizes substantial association, but its exact restrictions are opposed\nand its local discrepancies merit attention. The x7--x8 raw covariance\nresidual is .082 and its observed-SD-scaled value is .075. A clear loading\nestimate and an imperfect covariance representation can occur together;\nneither finding should erase the other. This section evaluates the declared\nmodel without searching for a better-fitting replacement.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Local discrepancy in the empirical nine-test model. Cells show observed-SD-scaled covariance residuals, with a symmetric color scale centered at zero. Positive cells are under-reproduced associations; negative cells are over-reproduced. Bounds distinguish very small nonzero residuals from exact zeros.](chapter_03_files/figure-html/fig-cfa-empirical-residuals-1.png){#fig-cfa-empirical-residuals fig-align='center' fig-pos='H' fig-alt='A numbered lower triangle of nine-test covariance residuals. The x7--x8 residual is positive 0.075, and several other cells have larger absolute discrepancies, showing why a single selected residual does not describe the whole pattern.' width=1040}\n:::\n:::\n\n\nThe .075 entry is one location in this pattern, not the largest residual or\na decision threshold. Its positive sign says that the model leaves part of\nthe association between speeded addition and counting dots unexplained.\nThe whole pattern helps locate strain; substantive knowledge is needed to\nchoose among explanations.\n\nThe second row uses the lower-triangle covariance matrix in\n@tbl-cfa-empirical-summary and $N=301$. The matrix is **derived from these\nsame raw records**, using divisor $N-1$. It is not transcribed from a\npublished summary table or offered as an independent replication. Variable\norder, test-score units, sample size and divisor are part of the input.\n\n\n::: {#tbl-cfa-empirical-summary .cell layout-align=\"center\" tbl-cap='Derived sample covariance of the nine test scores, N = 301, divisor N minus 1. Display cells are rounded to three decimals; the raw/summary agreement check uses the unrounded matrix.'}\n::: {.cell-output-display}\n\n\n|   |x1    |x2     |x3    |x4    |x5    |x6    |x7    |x8    |x9    |\n|:--|:-----|:------|:-----|:-----|:-----|:-----|:-----|:-----|:-----|\n|x1 |1.363 |       |      |      |      |      |      |      |      |\n|x2 |0.409 |1.386  |      |      |      |      |      |      |      |\n|x3 |0.582 |0.453  |1.279 |      |      |      |      |      |      |\n|x4 |0.507 |0.210  |0.209 |1.355 |      |      |      |      |      |\n|x5 |0.442 |0.212  |0.113 |1.101 |1.665 |      |      |      |      |\n|x6 |0.456 |0.248  |0.245 |0.899 |1.018 |1.200 |      |      |      |\n|x7 |0.085 |-0.097 |0.089 |0.220 |0.143 |0.145 |1.187 |      |      |\n|x8 |0.265 |0.110  |0.213 |0.126 |0.181 |0.166 |0.537 |1.025 |      |\n|x9 |0.460 |0.245  |0.375 |0.244 |0.296 |0.237 |0.375 |0.459 |1.018 |\n\n\n:::\n:::\n\n\nNormal ML rescales this unbiased covariance once to divisor $N$. With the\nsame restrictions and conventions, the raw and summary fits agree in\ncoefficients, conventional standard errors, fitted covariance, log likelihood\nand test statistic within $10^{-7}$. The largest fitted-covariance difference\nhere is 0e+00.\nRefitting the rounded display matrix would be a different numerical input,\nso it need not reproduce these numbers to that tolerance. The models shown\nhave no mean structure; a model for intercepts would additionally require\nsample means.\n\n| Information supplied | Analyses it supports here | Information still absent |\n|:--|:--|:--|\n| Covariance, $N$, order, units and divisor | Normal-theory covariance-model estimates, conventional uncertainty and fit | Which pupils contributed particular score patterns |\n| Individual records | The same fit, case inspection, individual factor-score prediction and case bootstrap | Design-based justification of causal measurement claims |\n\n: Raw records and summary moments support overlapping, not identical, investigations. {#tbl-cfa-raw-summary-information tbl-colwidths=\"[28,38,34]\"}\n\nThe three-factor form is a familiar teaching model, not a newly preregistered\ndiscovery in these records. Reusing the dataset therefore supplies an empirical\nillustration rather than fresh independent confirmation. This boundary differs\nfrom the published four-factor diagram in Section 2.5, which supplied topology\nonly and no fitted empirical evidence, and from the simulation, whose truth\nwas known by construction.\n\n# Summary and reading bridge\n\nFive equations organize the chapter: the scalar measurement equation,\nthe covariance decomposition, the scale transformation, the\nparameter-to-moment identification mapping, and the discrepancy\nminimization. Together they distinguish a proposed structure from a\nrecoverable parameterization and a successful numerical estimate.\n\nA disciplined specification check asks whether words, equations,\nmatrices, diagram, and syntax describe the same model. A parameter check\nthen separates free entries, scale normalizations, substantive zeros,\nequalities, and derived quantities. The count of distinct moments minus\nfree parameters is essential but does not replace local-block or\nidentification reasoning. Mean models need location conventions as well\nas factor scales.\n\nThe Sample B candidate passes the stated estimation and admissibility\nchecks. Its parameters can be read with explicit units and conventional\nuncertainty. Their interpretation is then examined against the global\nprofile and local covariance residuals. **An identified, converged, admissible\nestimate is necessary for ordinary interpretation; the evaluation adds\nevidence about observed implications, not a certificate of measurement\nvalidity.** The historical-test example completes this route from both raw\nand derived-summary inputs under the same assumptions.\n\nThe technical route follows the CFA specification tradition developed\nin @joreskog1969, @bollen1989, and @brown2006. For software details,\nthe [parameter-syntax tutorial](https://lavaan.ugent.be/tutorial/syntax2.html)\nand [output-extraction guide](https://lavaan.ugent.be/tutorial/inspect.html)\nhelp connect restrictions and fitted-object components. What follows\ndevelops the calibration of fit measures, compares planned rivals, and\nexamines the conditions under which a revision needs new evidence.\n\n# Exercises {.unnumbered}\n\n1. <!-- prompt-id: PT2-CH03-E01 --> **Represent a model.** Write the six-indicator base\n   model in equations, matrices, and a path diagram. Use a free/fixed\n   parameter ledger to identify its four free non-marker loadings, two\n   marker constraints, six target zeros, and residual assumptions. Explain\n   why no drawn arrow is causal proof.\n2. <!-- prompt-id: PT2-CH03-E02 --> **Trace a changed relation.** Using the controlled\n   parameter values in Section 4, compute $\\sigma_{16}$ and\n   $\\sigma_{36}$. Add $\\lambda_{32}=.25$ and recompute the affected\n   moments. Contrast adding $\\theta_{23}=.5$ instead.\n3. <!-- prompt-id: PT2-CH03-E03 --> **Transform the metric.** For marker-scale factor\n   variances 9 and 4, covariance 1.8, and target loadings\n   $(1,.7,1.1)$ and $(1,.8,1.2)$, obtain the fixed-factor loading matrix\n   and factor correlation. Verify a within-factor and a between-factor\n   covariance before and after transformation.\n4. <!-- prompt-id: PT2-CH03-E04 --> **Count carefully.** Evaluate the six-indicator base,\n   its one-cross-loading extension, and its loading-equality restriction.\n   Reconstruct the four-factor, sixteen-indicator count\n   $136-(16+16+6)=98$. Then derive $78/(27+k)/(51-k)$ for twelve\n   indicators and $k$ extra free cross-loadings under the stated\n   simple-structure assumptions.\n5. <!-- prompt-id: PT2-CH03-E05 --> **Count is not identification.** Construct two\n   distinct admissible loading/residual-variance parameter vectors for\n   a two-indicator unit-variance factor with\n   $\\sigma_{11}=\\sigma_{22}=1$ and $\\sigma_{12}=.4$. Explain how\n   an isolated copy of this block can remain unidentified inside a\n   positive-df whole model. Then use the single-indicator sensitivity table\n   to explain why fixing the loading alone is insufficient. Predict how the\n   recovered latent variance changes when the externally fixed reliability\n   rises from .7 to .9, and explain why unchanged reproduction of the\n   observed variance cannot select the reliability assumption.\n6. <!-- prompt-id: PT2-CH03-E06 --> **Read uncertainty.** From the Sample B loading\n   table, interpret P3's raw coefficient, SE, interval, and fully\n   standardized coefficient. Explain why its raw coefficient above\n   one is not an improper solution and why the printed raw SE is not\n   the fully standardized SE.\n7. <!-- prompt-id: PT2-CH03-E07 --> **Examine the contract.** An analyst feeds R's `cov()`\n   matrix into another program, leaves its divisor unspecified, fixes\n   marker loadings to one, and compares its test directly with this\n   chapter's raw-data fit. List the settings and invariances that must\n   be checked before interpreting a numerical difference.\n8. <!-- prompt-id: PT2-CH03-E08 --> **Test a restriction.** Explain the P1/P2 raw-loading\n   equality, write its $\\mathbf R$ row, and identify the covariance\n   term required for the variance of the estimated difference. Why\n   does this test not decide global fit or full parallel measurement?\n   The same fitted model has $T=48.475$ on 49 df, $p=.494$, and\n   a B4--S3 observed-SD-scaled covariance residual of $-.093$. Explain\n   how those results can coexist with the targeted equality test, and\n   identify what remains unestablished about the measurement claim.\n\n# Appendix: Structured means and parcels {.unnumbered}\n\n## Latent location is not identified by naming a factor {#sec-latent-location .unnumbered}\n\nThe mean equation $\\boldsymbol\\mu=\\boldsymbol\\nu+\n\\boldsymbol\\Lambda\\boldsymbol\\alpha$ contains both indicator\nintercepts and latent intercepts. In a single group, zero latent\nintercepts with free indicator intercepts are a convenient reference\nconvention. In multigroup work, some intercept restrictions can anchor\nlatent mean differences, but those restrictions carry measurement\ncontent. A numerical origin does not arise from labeling one group\n“control” or one factor “ability.” Later invariance chapters develop\nthe required scale and location links.\n\nThe covariance-only model is unaffected by translating every observed\ncolumn by a constant. A structured-mean model need not be. Similarly,\nrescaling a factor requires transforming its loadings, covariance, and\nlatent intercept; rescaling an observed variable requires transforming\nits intercept and residual variance as well. An equality imposed after\nonly some of these transformations can silently change the hypothesis.\n\n## Parceling changes the observed system {#sec-parceling .unnumbered}\n\nCombining items into parcels before fitting is common and contested; the\ntrade-offs are set out in @little2002. The algebra below shows why the choice\nis not cosmetic. Let a vector of parcel scores be $\\mathbf z=\\mathbf A\\mathbf y$,\nwhere rows of $\\mathbf A$ specify item averages or sums. Then\n\n$$\nE(\\mathbf z)=\\mathbf A\\boldsymbol\\mu,\n\\qquad\n\\operatorname{Var}(\\mathbf z)\n=\\mathbf A\\boldsymbol\\Sigma\\mathbf A^{\\mathsf T}.\n$$\n\nIf $\\mathbf A$ reduces dimension, several different item-level\ncovariance patterns can yield the same parcel covariance. Opposing\nsecondary loadings or local dependencies may partly cancel within\naverages. A well-fitting parcel model therefore does not establish\nthat the item-level restrictions would fit, and its AIC/BIC is not\ndirectly comparable to an item-level model with different outcomes.\n\nParceling can be useful under a justified measurement design, but it\nis not a generic normality repair or a route around identification\nand dimensionality questions. Evaluate item structure and preserve\nthe meaning of the resulting score before changing the observed\nsystem. No parcels are used in the SLE course record.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}