{
  "hash": "64248226fce8b25de011ac2b2166d2c2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"From Latent-Variable Modeling to Factor Analysis\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    output-file: chapter_01.pdf\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-cap: true\n    tbl-cap: true\n    fig-align: center\n    include-in-header:\n      text: |\n        \\setlength{\\parindent}{0pt}\n        \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n        \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n        \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n        \\ifdefined\\pdfvariable\n          \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n        \\fi\n        \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n        \\addtokomafont{sectionentry}{\\scriptsize}\n        \\let\\chapteroldtableofcontents\\tableofcontents\n        \\renewcommand{\\tableofcontents}{\\begingroup\\scriptsize\n          \\setlength{\\parskip}{0pt}\\chapteroldtableofcontents\\endgroup}\n        \\usepackage{caption}\n        \\captionsetup[table]{\n          position=above, format=plain, justification=raggedright,\n          singlelinecheck=false, labelsep=newline, labelfont=bf, textfont=it\n        }\n        \\usepackage{booktabs}\n        \\usepackage{longtable}\n        \\usepackage{array}\n        \\usepackage{float}\n        \\usepackage{needspace}\n        \\usepackage{etoolbox}\n        \\AtBeginEnvironment{CSLReferences}{\\small\\setlength{\\parskip}{1pt}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-tip title=\"Chapter box\"}\n**Five themes.**\n\n*A latent variable is introduced, not found.* It is an unobserved random\nvariable in a model, distinct from the construct that names it, from a\ncomposite of the items, and from any score computed for a person.\n\n*One model, four representations.* The common-factor model can be written\nas scalar equations, as matrices, as a path diagram, and as a sentence.\nThe four must agree, and moving between them is how a specification is\nchecked.\n\n*A factor has no scale of its own.* Units, sign and origin are not inherited\nfrom anything; conventions supply them, and several different metrics\ndescribe the same observed covariance equally well.\n\n*Covariance splits into two parts.* The model implies\n$\\boldsymbol{\\Sigma}=\\boldsymbol{\\Lambda}\\boldsymbol{\\Phi}\n\\boldsymbol{\\Lambda}^{\\mathsf T}+\\boldsymbol{\\Theta}$: a common part\ncarried by the factors and a residual part. Communality and uniqueness are\nconditional on the declared model, and a residual is not the same thing as\nmeasurement error.\n\n*Restrictions make a model refutable.* A model with fewer free parameters\nthan distinct moments asserts something about those moments that could turn\nout false. Exact reproduction shows compatibility; it does not establish\nthat the factors are the attributes they are named for.\n\n**Prerequisites.** Variance, covariance, correlation, random variables, and\nlinear regression notation. Part One Chapter 1 is an optional reference for\nthe collection's general reading method; no argument framework vocabulary is\nrequired for the core chapter.\n\n**Scope.** We formulate, translate and interrogate a common-factor model\nusing exact teaching matrices. No data are estimated and no learner-facing\nsoftware is used. Indicators are treated as continuous throughout Part Two;\nmethods for ordered-categorical indicators belong elsewhere and receive one\nshort scope note.\n:::\n\n# Latent variables and what they model {#sec-lvm}\n\n## Observed responses, an unobserved account {#sec-what-is-latent}\n\n**Guiding question.** When several indicators covary, when is a latent\nfactor a useful statistical account, and when may it be interpreted as the\nconstruct named in a study?\n\n**Provisional answer.** A common-factor model can represent their covariance\nthrough unobserved factors and residuals. Compatibility with that covariance\nsupports the statistical representation. Interpreting a factor as a construct\nadditionally requires a defensible account of the indicator domain, response\nprocess, population, and intended use. Naming a factor, obtaining a simple\npattern, or even reproducing covariance exactly is not enough.\n\nBehavioral and social research often concerns attributes that are not\nrecorded directly. A dataset may contain responses to several planning\nitems, but no column contains planning ability itself. A test records\nitem scores, not error-free proficiency. Symptoms may be observed while\nthe syndrome proposed to organize them remains a theoretical and\nstatistical construction.\n\nA latent-variable model does not turn the proposed attribute into an\nobservation. Instead, it introduces one or more unobserved random\nvariables and states how they are related to the variables that were\nrecorded. The useful question is therefore not simply whether a factor\ncan be named. It is whether the proposed model has observable\nconsequences, and what conclusions those consequences support.\n\nAnswering that pair takes both halves: a covariance representation that can\nbe checked, and a conclusion that stays within what such a check can\nestablish. The first task is to distinguish the quantities that enter the\nrepresentation.\n\n@tbl-quantities keeps four kinds of quantity apart.\n\n| Quantity | Status | Example |\n|:--|:--|:--|\n| **Observed variable** | Recorded for each unit | An item response $Y_j$ |\n| **Latent random variable** | Introduced by the model; not recorded | A common factor $\\eta_k$ |\n| **Unknown fixed parameter** | A population quantity to be estimated | A loading $\\lambda_{jk}$ |\n| **Residual random variable** | The part of an indicator the declared factors do not represent | $\\epsilon_j$ |\n\n: *Four kinds of quantity in a factor model.* {#tbl-quantities}\n\nA factor is not merely a parameter; it is a random variable in the\nmodel, with a distribution over units. A loading is not a hidden score\nattached to a person; it is a parameter describing how the model relates\nan indicator to a factor. A residual is unobserved too, but that does\nnot make it a substantive construct: it collects whatever the declared\ncommon factors leave out.\n\n@fig-lvm shows the smallest interesting case. Three observed indicators\nare drawn as rectangles, one unobserved variable as a circle, and the\nsingle-headed arrows run from the unobserved variable to the observed\nones.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A latent variable with three indicators. Rectangles are recorded variables, the circle is a variable introduced by the model, and single-headed arrows denote loading relations.](chapter_01_files/figure-html/fig-lvm-1.png){#fig-lvm fig-align='center' fig-alt='One latent factor eta points to observed indicators Y1 through Y3; each indicator also receives a residual epsilon arrow.' width=58%}\n:::\n:::\n\n\nFor three indicators, the picture summarizes equations of the form\n\n$$\nY_{ij} = \\nu_j + \\lambda_j\\eta_i + \\epsilon_{ij},\n\\qquad j = 1,2,3 .\n$$\n\nThe indicator $Y_{ij}$ is observed. The factor $\\eta_i$ and residual\n$\\epsilon_{ij}$ are random variables introduced by the model. The\nintercept $\\nu_j$ and loading $\\lambda_j$ are fixed but unknown\npopulation parameters.\n\nThe arrows deserve care. They state a *direction of representation*: the\nmodel writes each indicator as a function of the factor plus a residual,\nnot the reverse. That is a modeling choice with real consequences, and\nit is the choice this book makes throughout. It is not, by itself,\nevidence that the factor causes the responses. A diagram is a compact\nstatement of a model; establishing that a latent attribute produces\nobserved behavior requires theory about the response process and a\ndesign capable of supporting the claim. Model fit does not supply either.\n\nTwo inferential links are easy to conflate. First, relations among\npredictors, exposures and outcomes require a design capable of supporting\ncausal interpretation; sampling units from a target population bears mainly\non population generalization. Second, relating a proposed construct to a set\nof indicators requires defensible coverage of the construct's content or\nbehavioral domain. This second task is often called **domain sampling**,\nalthough indicator selection is commonly systematic and theory-guided rather\nthan a literal probability sample.\n\nDomain coverage supports a broad construct interpretation, but it is not\nsufficient by itself: the response process, dimensionality, population and\nintended use still matter. Without such a warrant, a factor may remain useful\nas a statistical device - for example, as a method factor - without being\ninterpreted as the construct itself. Likewise, drawing an arrow from a factor\nto an indicator states the model's reflective direction; neither domain\ncoverage nor the arrow alone establishes a causal effect.\n\nTwo matters here remain genuinely contested, and it is worth knowing that\nbefore the algebra makes them invisible. The first is what a latent variable\n*is*: whether it should be treated as a real attribute that produces the\nresponses, as a summary construction with no existence beyond the model, or as\nshorthand for the measuring operations themselves [@borsboom2003]. The algebra\nbelow is compatible with all three readings and settles none of them. The\nsecond is the direction just described. For some constructs - socioeconomic\nstatus is the standard example - the indicators arguably *produce* the\nconstruct rather than express it, and under that formative reading internal\nconsistency stops being a virtue and the common-factor model no longer applies\n[@bollenLennox1991; @edwardsBagozzi2000]. This book takes the reflective\ndirection throughout, which is a choice rather than a discovery.\n\nWhy introduce something that is not observed? Because the model has\nconsequences for quantities that are. Under assumptions developed below,\ntwo indicators connected to the same factor have the common covariance\ncontribution\n\n$$\n\\lambda_j\\operatorname{Var}(\\eta)\\lambda_k .\n$$\n\nWhen their residual covariance is zero, this is their entire model-implied\ncovariance. @sec-implied derives the complete result rather than asking\nthe reader to accept this preview.\n\nOnly after the model and its terms are clear will we ask it to reproduce\nparticular numerical patterns. The two six-indicator matrices in\n@sec-numbers are constructed, known-value teaching matrices. They are not\nsample correlations or evidence that particular constructs exist.\n\n## Classical test theory and the common-factor model {#sec-ctt}\n\nReaders arriving from measurement courses will know classical test\ntheory, which decomposes an observed score into a true score and an\nerror:\n\n$$\nX_{ir} = T_i + E_{ir},\n\\qquad\nT_i = E_r\\!\\left(X_{ir} \\mid i\\right),\n\\qquad\nE_r\\!\\left(E_{ir} \\mid i\\right) = 0 .\n$$\n\nHere $X_{ir}$ is the score of person $i$ on a hypothetical repetition\n$r$ of a specified measurement procedure, $T_i$ is its expected value\nover those repetitions, and $E_{ir}$ is the deviation. The expectation\nholds the person fixed and averages over measurement conditions; it does\nnot average over people. The true score is therefore a property of a\nperson *and a procedure*, not automatically a pure measure of the\nintended attribute: an influence that is stable across repetitions stays\ninside $T_i$ whether or not it belongs to the construct\n[@livingston2018].\n\nThe two frameworks overlap, but neither is simply a relabeling of the\nother. Under additional assumptions, a classical true-score\ndecomposition can be represented as a one-factor model by identifying\nthe common factor with true-score variation and fixing the relevant\nloadings at one. A common-factor model need not impose that restriction:\nit can let indicators relate to one or more factors with different\nstrengths and can examine the resulting covariance restrictions. The\nconnection is useful precisely because its assumptions must be stated;\nclassical test theory does not in general assert that every set of item\nresponses follows a one-factor model.\n\nThat is a difference in scope, not a ranking. Classical test theory\nanswers questions about a score and its replication conditions with very\nfew assumptions, and it remains the right tool for many of them.\nCommon-factor models, item-response models and the neighboring\nfamilies add structure to the joint distribution of responses, and buy\nitem-level and multidimensional statements at the price of stronger\nassumptions and larger samples. A residual in a factor model is also not\nautomatically classical error: stable item-specific content sits in the\nresidual without being error under the declared repetition procedure.\nReliability connects the two decompositions and needs conditions from\nboth; it is not derivable from a loading pattern alone.\n\n## A map of latent-variable models {#sec-map}\n\n@tbl-map crosses the form of the latent variable with the form of the\nobserved indicators to give a serviceable orientation.\n\n| Latent variable | Observed indicators | Common model families |\n|:--|:--|:--|\n| Continuous | Continuous | Common-factor models, confirmatory factor analysis, many structural equation models |\n| Continuous | Binary or ordered | Item-response models, categorical factor models |\n| Categorical | Continuous | Latent-profile and finite-mixture models |\n| Categorical | Categorical | Latent-class models, cognitive diagnosis models |\n\n: *A qualified map of latent-variable model families.* {#tbl-map}\n\nThe map is an orientation, not a set of sealed boxes. Factor models can\nbe fitted to ordered indicators through underlying-response\nformulations; item-response theory and categorical factor analysis share\ndeep mathematical connections while using different parameterizations\nand traditions; mixture models combine continuous and categorical latent\nstructure. Structural equation modeling is broader still, and can\ncontain a factor measurement portion, regressions among variables, or\nboth.\n\nThis chapter takes the first row: continuous factors and continuous\nindicators. Part Two as a whole stays there. That narrowing is what\nallows the algebra to be seen plainly before estimation choices and\nsoftware output accumulate. Responses are treated as continuous throughout\nPart Two.\n\n## Exploratory and confirmatory orientations {#sec-orientations}\n\nThe same common-factor equation can be used with very different amounts\ndeclared in advance.\n\nAn **exploratory** analysis ordinarily lets every indicator relate to\nevery retained factor and uses rotation or equivalent constraints to\nchoose an interpretable orientation. It suits situations where a construct\nexists conceptually but its dimensionality is unsettled. A\n**confirmatory** analysis fixes or constrains loadings and residual\nrelations according to a specification stated before the focal analysis,\nand asks what follows.\n\nThe words describe orientations, not two unrelated models. Both use the\nsame covariance decomposition. Theory can inform an exploratory\nanalysis, and a confirmatory model can be revised after data are\ninspected. What separates them is the *restrictions* and the *history of\nthe decisions* — not the name of the procedure. Practice usually falls\nsomewhere along the continuum rather than at either end. @sec-approaches\nreturns to the distinction once the shared model is in hand.\n\n# The common-factor model {#sec-model}\n\n## One indicator at a time {#sec-scalar}\n\nWrite $y_{ij}$ for the response of unit $i$ on indicator $j$. The\ncommon-factor model expresses it as\n\n$$\ny_{ij} = \\nu_j + \\boldsymbol{\\lambda}_j^{\\mathsf T}\\boldsymbol{\\eta}_i\n         + \\epsilon_{ij},\n$$ {#eq-scalar}\n\nwhere $i = 1,\\ldots,n$ indexes units, $j = 1,\\ldots,p$ indexes\nindicators, $\\nu_j$ is an intercept, $\\boldsymbol{\\lambda}_j$ is an\n$m \\times 1$ vector of loadings, $\\boldsymbol{\\eta}_i$ is the\n$m \\times 1$ vector of common factors for unit $i$, and $\\epsilon_{ij}$\nis the residual. With two factors this reads\n\n$$\ny_{ij} = \\nu_j + \\lambda_{j1}\\eta_{i1} + \\lambda_{j2}\\eta_{i2}\n         + \\epsilon_{ij} .\n$$\n\nThe resemblance to multiple regression is useful and has one decisive\nlimit: the predictors $\\eta_{i1}$ and $\\eta_{i2}$ are not columns in the\ndataset. Their scale and orientation must be supplied by model\nconstraints, and the parameters are learned from the joint pattern among\nall $p$ indicators rather than from a single outcome at a time.\n\n## From equations to matrices {#sec-matrix}\n\nCollecting the $p$ indicators for unit $i$ into $\\mathbf{y}_i$,\n\n$$\n\\mathbf{y}_i = \\boldsymbol{\\nu} + \\boldsymbol{\\Lambda}\\boldsymbol{\\eta}_i\n               + \\boldsymbol{\\epsilon}_i ,\n$$ {#eq-matrix}\n\nwith $\\mathbf{y}_i$, $\\boldsymbol{\\nu}$ and $\\boldsymbol{\\epsilon}_i$ in\n$\\mathbb{R}^{p}$, $\\boldsymbol{\\eta}_i$ in $\\mathbb{R}^{m}$, and\n$\\boldsymbol{\\Lambda}$ a $p \\times m$ loading matrix. The multiplication\nconforms because a $p \\times m$ matrix times an $m \\times 1$ vector\nreturns a $p \\times 1$ vector: one common-factor contribution for each\nindicator. Row $j$ of $\\boldsymbol{\\Lambda}$ is\n$\\boldsymbol{\\lambda}_j^{\\mathsf T}$.\n\nThe model's moment assumptions are\n\n$$\n\\begin{aligned}\nE(\\boldsymbol{\\eta}_i) &= \\boldsymbol{\\alpha}, &\n\\operatorname{Var}(\\boldsymbol{\\eta}_i) &= \\boldsymbol{\\Phi}, \\\\\nE(\\boldsymbol{\\epsilon}_i) &= \\mathbf{0}, &\n\\operatorname{Var}(\\boldsymbol{\\epsilon}_i) &= \\boldsymbol{\\Theta}, \\\\\n\\operatorname{Cov}(\\boldsymbol{\\eta}_i, \\boldsymbol{\\epsilon}_i)\n  &= \\mathbf{0}. & &\n\\end{aligned}\n$$ {#eq-assumptions}\n\n$\\boldsymbol{\\Phi}$ is the $m \\times m$ matrix of factor variances and\ncovariances; $\\boldsymbol{\\Theta}$ is the $p \\times p$ matrix of\nresidual variances and any residual covariances the model permits. Both\nare symmetric and positive semidefinite. The zero matrix in the last\nline is $m \\times p$.\n\nThe notation $\\boldsymbol{\\alpha}$ is chosen deliberately. It is the\nlatent intercept vector. In this chapter there are no regressions among\nlatent variables, so $\\boldsymbol{\\alpha}=E(\\boldsymbol{\\eta}_i)$. Once\na structural coefficient matrix $\\mathbf B$ is introduced later, the\nmarginal mean becomes\n$E(\\boldsymbol{\\eta}_i)=(\\mathbf I-\\mathbf B)^{-1}\n\\boldsymbol{\\alpha}$. We will therefore call $\\boldsymbol{\\alpha}$ the\nfactor mean only in the present measurement-only setting.\n\nEach assumption does a specific job, and it is worth naming them\nseparately rather than accepting them as a block. The factor–residual\ncondition is what will let the covariance decomposition split cleanly\ninto two parts in @sec-implied. The mean conditions are what let the\nmodel say anything about $E(\\mathbf{y}_i)$. Note also what has *not*\nbeen assumed: zero covariance between factors and residuals is a moment\nrestriction, not a statement that they are statistically independent,\nand $\\boldsymbol{\\Theta}$ has not been required to be diagonal.\n\n## What a residual contains {#sec-residual}\n\nIt is tempting to read every $\\epsilon_{ij}$ as measurement error. That\nis too narrow. Residual variation can include random response\nfluctuation, but also stable item-specific content, wording or method\neffects, occasion effects, an omitted common factor, or a\nmisspecification of the model. A residual *covariance* $\\theta_{jk}$\nrepresents a relation between two indicators that the declared common\nfactors do not account for. Whether such a relation is substantively\ndefensible is a modeling question, not something a large diagnostic\nstatistic settles on its own.\n\nA diagonal $\\boldsymbol{\\Theta}$ has a precise but limited meaning, and\nthree claims are worth keeping apart. Under the moment assumptions of\n@eq-assumptions, a diagonal $\\boldsymbol{\\Theta}$ says that distinct\nresidual components have zero **unconditional** covariance. If we add\nthe conditional moment assumptions\n$E(\\boldsymbol{\\epsilon}_i \\mid \\boldsymbol{\\eta}_i) = \\mathbf{0}$ and\n$\\operatorname{Var}(\\boldsymbol{\\epsilon}_i \\mid \\boldsymbol{\\eta}_i)\n= \\boldsymbol{\\Theta}$, it also gives zero **conditional** residual\ncovariance. Full **local independence** — the indicators being\nconditionally independent given the factors — is stronger still, and\nneeds a distributional statement or an explicit factorization of the\nconditional response distribution. Zero covariance is not independence:\ntwo variables can have zero correlation and remain functionally related.\nNone of the three claims says that the observed items are unrelated;\nthat is the whole point of the model.\n\n# One model, four representations {#sec-four-ways}\n\nWe now fix a single system and keep it in view for the rest of the\nchapter: six observed indicators and two common factors. Allowing every\nindicator to relate to both factors gives six equations,\n\n$$\n\\begin{aligned}\ny_{i1} &= \\nu_1 + \\lambda_{11}\\eta_{i1} + \\lambda_{12}\\eta_{i2} + \\epsilon_{i1},\\\\\ny_{i2} &= \\nu_2 + \\lambda_{21}\\eta_{i1} + \\lambda_{22}\\eta_{i2} + \\epsilon_{i2},\\\\\ny_{i3} &= \\nu_3 + \\lambda_{31}\\eta_{i1} + \\lambda_{32}\\eta_{i2} + \\epsilon_{i3},\\\\\ny_{i4} &= \\nu_4 + \\lambda_{41}\\eta_{i1} + \\lambda_{42}\\eta_{i2} + \\epsilon_{i4},\\\\\ny_{i5} &= \\nu_5 + \\lambda_{51}\\eta_{i1} + \\lambda_{52}\\eta_{i2} + \\epsilon_{i5},\\\\\ny_{i6} &= \\nu_6 + \\lambda_{61}\\eta_{i1} + \\lambda_{62}\\eta_{i2} + \\epsilon_{i6},\n\\end{aligned}\n$$ {#eq-six}\n\nwhich collect into the loading matrix\n\n$$\n\\boldsymbol{\\Lambda} =\n\\begin{bmatrix}\n\\lambda_{11} & \\lambda_{12}\\\\\n\\lambda_{21} & \\lambda_{22}\\\\\n\\lambda_{31} & \\lambda_{32}\\\\\n\\lambda_{41} & \\lambda_{42}\\\\\n\\lambda_{51} & \\lambda_{52}\\\\\n\\lambda_{61} & \\lambda_{62}\n\\end{bmatrix},\n\\qquad\n\\boldsymbol{\\Phi} =\n\\begin{bmatrix}\n\\phi_{11} & \\phi_{12}\\\\\n\\phi_{12} & \\phi_{22}\n\\end{bmatrix} .\n$$ {#eq-general-loading}\n\nRows of $\\boldsymbol{\\Lambda}$ belong to indicators and columns to\nfactors, so $\\lambda_{42}$ relates $Y_4$ to the second factor. Reading\nthe subscripts in that order is the quickest way to catch a path diagram\nthat disagrees with its matrix. The residual covariance matrix is\nsymmetric and $6 \\times 6$; a diagonal working version is\n$\\boldsymbol{\\Theta} = \\operatorname{diag}(\\theta_{11},\\ldots,\\theta_{66})$.\n\n@fig-general draws the same system. Every indicator receives an arrow\nfrom both factors, and the double-headed arrow between the factors is\nthe covariance $\\phi_{12}$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The two-factor, six-indicator system with every loading present. Single-headed arrows denote loading relations; the double-headed arrow denotes the factor covariance.](chapter_01_files/figure-html/fig-general-1.png){#fig-general fig-align='center' fig-alt='Both correlated factors point to all six indicators; cross-loading paths are dashed, and each indicator has a residual.' width=88%}\n:::\n:::\n\n\n## Restricting the pattern {#sec-simple}\n\nSetting the cross-loadings to zero, so the first three indicators relate\nonly to $\\eta_1$ and the last three only to $\\eta_2$, gives\n\n$$\n\\boldsymbol{\\Lambda}_{\\text{simple}} =\n\\begin{bmatrix}\n\\lambda_{11} & 0\\\\\n\\lambda_{21} & 0\\\\\n\\lambda_{31} & 0\\\\\n0 & \\lambda_{42}\\\\\n0 & \\lambda_{52}\\\\\n0 & \\lambda_{62}\n\\end{bmatrix} .\n$$ {#eq-simple-loading}\n\n@fig-simple redraws the same system after the cross-loadings are fixed at\nzero.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The same system restricted to a simple structure. Each indicator has one loading and one residual; the six cross-loadings are fixed at zero.](chapter_01_files/figure-html/fig-simple-1.png){#fig-simple fig-align='center' fig-alt='Eta 1 points only to Y1 through Y3 and eta 2 only to Y4 through Y6; the factors covary and every indicator has a residual.' width=88%}\n:::\n:::\n\n\nEach zero is a restriction, not a drawing convenience. It says that,\naccording to this model, the second factor makes no direct contribution\nto $Y_1$. Restrictions of this kind are the substance of a confirmatory\nspecification, and they are what make a model capable of being wrong: a\nmodel in which everything is free forbids nothing.\n\nThe four representations must agree, and it is worth checking that they\ndo. For the restricted model: the path from $\\eta_1$ to $Y_4$ is absent\nin the diagram; $\\lambda_{41} = 0$ in the equations; row 4, column 1 of\n$\\boldsymbol{\\Lambda}$ is zero; and any common covariance between $Y_1$\nand $Y_4$ must therefore travel through $\\phi_{12}$, unless a residual\ncovariance is also permitted. The fourth representation is the sentence:\n*six indicators are represented by two possibly correlated factors; each\nindicator has one loading and one residual; cross-loadings and residual\ncovariances are fixed at zero.* That sentence should be recoverable from\nany of the other three without guessing.\n\n## Reading a parameter family {#sec-families}\n\nCounting arrows in a diagram is not a reliable way to know what a model\ncontains, because the same picture can represent different models. What\nmatters is the status of each element. @tbl-families turns that status into\nfour sets of questions that should be answered for every specification.\n\n| Family | Matrix | Questions to settle |\n|:--|:--|:--|\n| Intercepts | $\\boldsymbol{\\nu}$ | Are means modeled, or is the analysis covariance-only? |\n| Loadings | $\\boldsymbol{\\Lambda}$ | Which entries are fixed at zero, fixed for scale, constrained equal, or free? |\n| Factor variances and covariances | $\\boldsymbol{\\Phi}$ | Are variances fixed to set a scale? Is the covariance free? |\n| Residual variances and covariances | $\\boldsymbol{\\Theta}$ | Is the matrix diagonal? Are any residual covariances justified and free? |\n\n: *Parameter families and what must be declared about each.* {#tbl-families}\n\nA loading can also be fixed at a value other than zero or one. That\npossibility looks like a technicality here and becomes central later:\ngrowth models fix a whole column of $\\boldsymbol{\\Lambda}$ to values\nsuch as $0, 1, 2, 3$ so that the corresponding factor expresses change\nper unit of time. The point is that fixed, free and constrained are three\ndifferent things, and a diagram alone does not distinguish them.\n\n\\Needspace{0.22\\textheight}\n\n# The factor scale {#sec-factor-scale}\n\nAn observed variable arrives with a scale: if height is recorded in\ncentimetres, a one-unit change means something definite. An unobserved\nfactor arrives with nothing. This section works through the\nconsequences, which are less an inconvenience than a permanent feature\nof latent-variable models.\n\n## The factor scale is indeterminate {#sec-scale}\n\nTake a one-factor model and any nonzero constant $a$. Define\n\n$$\n\\eta_i^{*} = a\\,\\eta_i, \\qquad\n\\alpha^{*} = a\\,\\alpha, \\qquad\n\\lambda_j^{*} = \\lambda_j / a, \\qquad\n\\phi^{*} = a^{2}\\phi .\n$$ {#eq-rescale}\n\nThe factor's contribution to an indicator's mean is unchanged, since\n$\\lambda_j^{*}\\alpha^{*} = (\\lambda_j/a)(a\\alpha) = \\lambda_j\\alpha$, and\nits contribution to a covariance is unchanged too:\n\n$$\n\\lambda_j^{*}\\phi^{*}\\lambda_k^{*}\n= \\frac{\\lambda_j}{a}\\,\\bigl(a^{2}\\phi\\bigr)\\,\\frac{\\lambda_k}{a}\n= \\lambda_j\\phi\\lambda_k .\n$$\n\nConcretely, with $\\lambda_j = .80$ and $\\phi = 1$, setting $a = 2$ gives\na loading of $.40$ and a factor variance of $4$; the common contribution\nto the indicator's variance is $.40^{2}(4) = .64$ either way. Everything\nelse — $\\nu_j$, $\\epsilon_{ij}$, $\\theta_{jk}$ — is untouched, because\nthe transformation acts only on the factor's own metric. The observed\ndata cannot choose between these descriptions, because they imply\nexactly the same observed moments.\n\n@tbl-scaling contrasts two conventions in general use. Both simply fix a\nmetric.\n\n| Convention | What is fixed | What is estimated |\n|:--|:--|:--|\n| **Marker variable** | One loading per factor, usually at 1 | The factor variance and the remaining loadings |\n| **Fixed factor** | The factor variance, usually at 1 | All permitted loadings |\n\n: *Two ways to give a factor a scale.* {#tbl-scaling}\n\nNeither is superior. Unstandardized loadings and factor variances differ\nbetween them; the implied covariance among the indicators does not.\n\nWith several factors, the freedom is wider than changing one scale at a\ntime. A nonsingular transformation can mix or rotate the\nfactor axes while corresponding changes to the loading and\nfactor-covariance matrices leave the observed covariance unchanged. The\nnew loadings can look quite different even though they\nrepresent the same common covariance. @sec-argument works one orthogonal\nexample numerically; the general transformation belongs with rotation,\nwhere the freedom is used deliberately for interpretation.\n\n## Sign and location {#sec-sign-location}\n\nSetting $a = -1$ in @eq-rescale reverses the sign of every factor value\nand every loading while leaving each product, and therefore the implied\ncovariance, unchanged. A factor with loadings $(.80, .70, .60)$ and one\nwith $(-.80, -.70, -.60)$ describe the same observed correlations. The\ndirection is fixed by convention and by what the items say, not by the\ndata; a negative sign is not by itself a problem, and a sign flip\nbetween two equivalent solutions is not evidence that anything changed.\n\nLocation behaves the same way once means are in the model. For any fixed\n$m \\times 1$ vector $\\mathbf{c}$,\n\n$$\n\\boldsymbol{\\eta}_i^{*} = \\boldsymbol{\\eta}_i + \\mathbf{c},\n\\qquad\n\\boldsymbol{\\alpha}^{*} = \\boldsymbol{\\alpha} + \\mathbf{c},\n\\qquad\n\\boldsymbol{\\nu}^{*} = \\boldsymbol{\\nu} - \\boldsymbol{\\Lambda}\\mathbf{c},\n$$ {#eq-location}\n\nleaves the implied mean untouched:\n$\\boldsymbol{\\nu}^{*} + \\boldsymbol{\\Lambda}\\boldsymbol{\\alpha}^{*}\n= \\boldsymbol{\\nu} + \\boldsymbol{\\Lambda}\\boldsymbol{\\alpha}$. So the\nobserved means alone cannot determine both unrestricted factor means and\nunrestricted intercepts. In a single-group model the usual convention\nfixes the factor means at zero and estimates the intercepts. Comparing\nlatent means across groups or occasions requires additional equality\nrestrictions and a reference group; that is the subject of measurement\ninvariance, later in Part Two, and it is worth noticing now that the\nquestion is one of *identification*, not of finding a better estimator.\n\n## Changing the units of the indicators {#sec-units}\n\nA different operation is to rescale the observed variables themselves —\nrecording a test in percentages rather than raw points, say. This also\nproduces a model that fits equally well, but for an entirely different\nreason: the loadings, residual variances and implied covariances all\nchange in step with the new units, coherently and predictably. Nothing\nis indeterminate here; the information is the same information in a\ndifferent metric.\n\nThe distinction matters because the two are easy to conflate. Choosing a\nfactor's scale is supplying a metric to something that has none.\nChanging an indicator's units is re-expressing something that already\nhad them. The same distinction governs the relationship between analysing\na covariance matrix and analysing a correlation matrix.\n\n# The model-implied covariance structure {#sec-implied}\n\nThe common-factor model earns its keep because it implies a specific\ncovariance structure among the observed indicators. That structure, not\nthe raw data, is what most factor-analytic estimation actually works\nwith — which is why factor analysis and structural equation modeling are\ntogether known as **covariance structure analysis**. We derive the\nstructure rather than quote it.\n\nFor indicators $j$ and $k$, subtract the means and use @eq-scalar:\n\n$$\n\\begin{aligned}\ny_{ij} - E(y_{ij}) &=\n  \\boldsymbol{\\lambda}_j^{\\mathsf T}\n  (\\boldsymbol{\\eta}_i - \\boldsymbol{\\alpha}) + \\epsilon_{ij}, \\\\\ny_{ik} - E(y_{ik}) &=\n  \\boldsymbol{\\lambda}_k^{\\mathsf T}\n  (\\boldsymbol{\\eta}_i - \\boldsymbol{\\alpha}) + \\epsilon_{ik} .\n\\end{aligned}\n$$\n\nExpanding the covariance shows all four contributions:\n\n$$\n\\begin{aligned}\n\\operatorname{Cov}(y_{ij},y_{ik})\n={}&\n\\boldsymbol{\\lambda}_j^{\\mathsf T}\\boldsymbol{\\Phi}\n  \\boldsymbol{\\lambda}_k \\\\\n&+\\operatorname{Cov}\\!\\left[\n  \\boldsymbol{\\lambda}_j^{\\mathsf T}\n  (\\boldsymbol{\\eta}_i-\\boldsymbol{\\alpha}),\\epsilon_{ik}\\right] \\\\\n&+\\operatorname{Cov}\\!\\left[\n  \\epsilon_{ij},\n  \\boldsymbol{\\lambda}_k^{\\mathsf T}\n  (\\boldsymbol{\\eta}_i-\\boldsymbol{\\alpha})\\right]\n  +\\theta_{jk}.\n\\end{aligned}\n$$\n\nThe first term is the common-factor contribution, the middle two are\nfactor–residual cross terms, and the last is the residual covariance.\nThe factor–residual assumption in @eq-assumptions sets both middle terms\nto zero, leaving\n\n$$\n\\boxed{\\;\n\\operatorname{Cov}(y_{ij}, y_{ik})\n= \\boldsymbol{\\lambda}_j^{\\mathsf T}\\boldsymbol{\\Phi}\n  \\boldsymbol{\\lambda}_k + \\theta_{jk} \\; }\n$$ {#eq-cov}\n\nand, for $j = k$,\n\n$$\n\\operatorname{Var}(y_{ij})\n= \\boldsymbol{\\lambda}_j^{\\mathsf T}\\boldsymbol{\\Phi}\n  \\boldsymbol{\\lambda}_j + \\theta_{jj} .\n$$ {#eq-var}\n\nStacking over all pairs gives the matrix form:\n\n$$\n\\boxed{\\;\n\\boldsymbol{\\Sigma}(\\boldsymbol{\\vartheta})\n= \\boldsymbol{\\Lambda}\\boldsymbol{\\Phi}\\boldsymbol{\\Lambda}^{\\mathsf T}\n  + \\boldsymbol{\\Theta} \\; }\n$$ {#eq-implied}\n\nwhere $\\boldsymbol{\\vartheta}$ collects the free parameters and\n$\\theta_{jk}$ remains an entry of $\\boldsymbol{\\Theta}$. Every observed\ncovariance is thus split into a **common** part, carried by the factors,\nand a **residual** part. If $\\theta_{jk}=0$, a strong covariance requires\nthe two indicators to receive a sufficiently strong joint contribution\nfrom shared factors. If $\\theta_{jk}\\ne0$, residual association can also\ncontribute; the decomposition prevents that association from being\nsilently attributed to the factors.\n\nThis identity needs finite second moments and the stated moment\nrestrictions. It does not need normality. Distributional assumptions\nenter separately, through particular estimators, standard errors and test\nstatistics; that boundary is worth keeping explicit.\n\nThe same assumptions give a second useful matrix:\n\n$$\n\\operatorname{Cov}(\\mathbf y_i,\\boldsymbol{\\eta}_i)\n=\\boldsymbol{\\Lambda}\\boldsymbol{\\Phi}.\n$$\n\n$\\boldsymbol{\\Lambda}$ is the **pattern matrix**: its entries are the\ncoefficients in the equations for the indicators.\n$\\boldsymbol{\\Lambda}\\boldsymbol{\\Phi}$ is the **structure matrix**: its\nentries are indicator–factor covariances. They are indicator–factor\ncorrelations only when both sides have been standardized. When factors\nare orthogonal and have unit variance, pattern and structure coincide;\nwhen factors correlate, they need not. The two matrices have to be read\nside by side whenever an oblique solution is interpreted.\n\n## Communality and uniqueness {#sec-communality}\n\nThe common part of an indicator's variance,\n\n$$\nh_j^{2}\n= \\boldsymbol{\\lambda}_j^{\\mathsf T}\\boldsymbol{\\Phi}\n  \\boldsymbol{\\lambda}_j ,\n$$ {#eq-communality}\n\nis its **communality under the declared model**. The qualifier matters:\nchanging the number of factors, the loading pattern, or the factor\ncovariances changes $h_j^{2}$. For a standardized indicator whose\nvariance decomposes into just these two parts,\n$1 = h_j^{2} + \\theta_{jj}$, so the residual variance $\\theta_{jj}$ —\noften called the **uniqueness** — is $1 - h_j^{2}$. The larger the share\nthe factors account for, the smaller the remainder.\n\nIf a standardized indicator has one nonzero loading on a unit-variance\nfactor, this reduces to $h_j^{2} = \\lambda_j^{2}$. That shortcut is used\nconstantly and is not the general definition. With two correlated\nfactors the communality expands to\n\n$$\nh_j^{2} = \\lambda_{j1}^{2}\\phi_{11}\n        + 2\\lambda_{j1}\\lambda_{j2}\\phi_{12}\n        + \\lambda_{j2}^{2}\\phi_{22},\n$$ {#eq-communality-two}\n\nand the middle term is why squared loadings cannot simply be added when\nfactors correlate. In an admissible standardized solution the\ncommunality lies between zero and one; an estimated $\\theta_{jj} < 0$ is\nan improper, or **Heywood**, solution and signals a problem to\ninvestigate rather than a discovery that an indicator has more than\n100% common variance.\n\nUniqueness means variance the declared common factors do not represent.\nIt does not mean that all of that variance is random error, for the\nreasons given in @sec-residual.\n\n## A moment structure, not only a covariance structure {#sec-moments}\n\nThe same assumptions also imply a mean structure:\n\n$$\nE(\\mathbf{y}_i)\n= \\boldsymbol{\\mu}(\\boldsymbol{\\vartheta})\n= \\boldsymbol{\\nu} + \\boldsymbol{\\Lambda}\\boldsymbol{\\alpha} .\n$$ {#eq-mean}\n\nMost of Part Two analyses covariances alone, holding the mean structure\naside, and that is a legitimate and common choice. It is worth being\nclear that it is a *choice*. Means are part of the model even when they\nare set aside, and two of Part Two's later destinations depend on them\nentirely: measurement invariance compares intercepts and factor means\nacross groups, and latent growth models place a whole trajectory in\n$\\boldsymbol{\\alpha}$ while fixing $\\boldsymbol{\\Lambda}$ to a\ntime basis.\n\nA brief look at the second of those makes the point concrete. Suppose\nfour measurements are taken on the same people at equally spaced\noccasions, with\n\n$$\n\\boldsymbol{\\Lambda} =\n\\begin{bmatrix}\n1 & 0\\\\ 1 & 1\\\\ 1 & 2\\\\ 1 & 3\n\\end{bmatrix},\n\\qquad\n\\boldsymbol{\\alpha} = (\\alpha_1, \\alpha_2)^{\\mathsf T} .\n$$\n\nEvery loading is fixed. The column of ones makes the first factor\ncontribute equally at every occasion, so $\\alpha_1$ is an average\nstarting level; the column $0, 1, 2, 3$ is a time basis, so $\\alpha_2$\nis an average change per occasion. With intercepts fixed at zero, the\nimplied means $\\boldsymbol{\\nu} + \\boldsymbol{\\Lambda}\\boldsymbol{\\alpha}$\ntrace the average trajectory. The variances and covariances in\n$\\boldsymbol{\\Phi}$ then describe how much individuals differ in where\nthey start and how fast they change, which is usually the substantive\npoint. We are not fitting this model here, and its full assumptions come\nmuch later. It is shown because it uses only @eq-matrix and\n@eq-mean, with the loadings fixed to substantively chosen values rather\nthan estimated — a possibility @tbl-families raised and this makes real.\n\n## What a restriction buys {#sec-counting}\n\nA model that could not be wrong is not worth testing, so it is worth asking\nwhat a set of restrictions actually commits us to. The question is settled by\ncounting, and the count has three ingredients.\n\nThe first is how much distinct information the observed variables supply. For\n$p$ indicators the covariance matrix is symmetric, so its distinct entries\nnumber\n\n$$\nu=\\frac{p(p+1)}{2},\n$$ {#eq-moments}\n\nwhich is $21$ for the six indicators used here. These are the *distinct\nmoments*: 21 numbers, not 21 observations. Collecting more respondents\nestimates the same 21 quantities more precisely; it never creates a\ntwenty-second.\n\nThe second is how many quantities the model leaves free. Here @sec-factor-scale\nmatters directly. A factor has no scale of its own, so a model that left both\nthe loadings and the factor variance free would be asking the data to\ndetermine something they cannot: infinitely many pairs give identical implied\nmoments. A scaling convention removes that indeterminacy, and in doing so\nremoves a parameter from the free count. Restrictions of every kind - a\ncross-loading fixed at zero, a residual covariance forbidden, two loadings\nconstrained equal - do the same arithmetic.\n\nThe third is the difference between them,\n\n$$\ndf=u-t,\n$$ {#eq-df}\n\nwith $t$ the number of free parameters. For the two-factor simple-structure\nmodel of @sec-scenario-two, with the factor variances fixed at one, $t$ counts\nsix loadings, one factor correlation and six residual variances: $t=13$ and\n$df=21-13=8$. The one-factor model of @sec-scenario-one has six loadings and\nsix residual variances, so $t=12$ and $df=9$.\n\nThose nine degrees of freedom are the sense in which the one-factor model\n*forbids* something, and @sec-tetrad makes one of the prohibitions visible: a\nsingle factor with uncorrelated residuals requires every tetrad to vanish, and\na matrix in which one does not cannot be reproduced. A model with $df<0$ asks\nthe data for more than they contain. A model with $df=0$ has used up its\nbudget without spending any on restrictions, so it cannot be contradicted by\nthe *count*; whether it can reproduce a given matrix is a further question\nabout that particular parameterization, since equality constraints, fixed\nvalues and the requirement that variances stay nonnegative can all keep a\njust-identified model from reaching every covariance matrix of its size.\n\nTwo cautions belong with the count, because it is easy to ask more of it than\nit can deliver. A nonnegative $df$ does not establish that the parameters can\nbe recovered at all: whether the moments determine the parameters uniquely is\na separate question - **identification** - which counting can rule out but\nnever confirm. And a positive $df$ says the model is refutable, not that it is\ntrue. Both questions are taken up systematically once models are estimated, where\nthe count becomes a routine check rather than a passing observation.\n\n# Reading the numbers {#sec-numbers}\n\nWe can now put numbers into the representation. Both correlation matrices in\nthis section are constructed: the parameters came first and the correlations\nwere computed from them. That is deliberate. Because the values are\nexact, any disagreement is an arithmetic error rather than sampling\nvariation. They are ideal for learning the algebra and useless as\nevidence about any real population.\n\n## One common factor {#sec-scenario-one}\n\nThe first matrix, shown in @tbl-record-one, has the same $.49$ correlation for\nevery distinct pair.\n\n\\Needspace{0.30\\textheight}\n\n| | $Y_1$ | $Y_2$ | $Y_3$ | $Y_4$ | $Y_5$ | $Y_6$ |\n|:--|--:|--:|--:|--:|--:|--:|\n| $Y_1$ | 1.00 | | | | | |\n| $Y_2$ | .49 | 1.00 | | | | |\n| $Y_3$ | .49 | .49 | 1.00 | | | |\n| $Y_4$ | .49 | .49 | .49 | 1.00 | | |\n| $Y_5$ | .49 | .49 | .49 | .49 | 1.00 | |\n| $Y_6$ | .49 | .49 | .49 | .49 | .49 | 1.00 |\n\n: *A constructed one-factor correlation matrix.* {#tbl-record-one}\n\nThe repeated value suggests a single common contribution shared evenly\nacross all six indicators. Let us check that representation rather than\ninfer it from appearance alone.\n\nLet all six standardized indicators relate to a single unit-variance\nfactor with loading $.70$:\n\n$$\n\\boldsymbol{\\Lambda}_1 = (.70,\\,.70,\\,.70,\\,.70,\\,.70,\\,.70)^{\\mathsf T},\n\\qquad\n\\boldsymbol{\\Phi}_1 = [1],\n\\qquad\n\\boldsymbol{\\Theta}_1 = .51\\,\\mathbf{I}_6 .\n$$\n\n@fig-onefactor draws this parameterization before the entrywise check.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The one-factor model that reproduces the first record. Every loading is .70.](chapter_01_files/figure-html/fig-onefactor-1.png){#fig-onefactor fig-align='center' fig-alt='One factor points to six indicators, with every loading labeled point 70 and a separate residual for every indicator.' width=64%}\n:::\n:::\n\n\nApply @eq-cov and @eq-var. Each diagonal entry is\n$.70^{2} + .51 = .49 + .51 = 1$, as a correlation matrix requires. Each\noff-diagonal entry is $.70 \\times 1 \\times .70 = .49$. That reproduces\n@tbl-record-one exactly. Every communality is $.70^{2} = .49$ and every\nuniqueness is $1 - .70^{2} = .51$.\n\nThe column sum of squared loadings is $6(.70^{2}) = 2.94$. This quantity\nis often called the factor's eigenvalue, and the label is safe only\nunder specific conditions. Here it is the sum of squares of a loading\ncolumn — an **SS loading**. It happens to equal the single nonzero\neigenvalue of the common part\n$\\boldsymbol{\\Lambda}_1\\boldsymbol{\\Lambda}_1^{\\mathsf T}$, but it is\n*not* an eigenvalue of the correlation matrix in @tbl-record-one, whose\neigenvalues are $3.45$ and five values of $.51$. Adding $.51$ to the\ndiagonal shifts every eigenvalue by $.51$. Wherever eigenvalues do real\nwork in deciding how many factors to retain, the matrix being decomposed\nhas to be named; the habit starts here.\n\n## Two orthogonal factors {#sec-scenario-two}\n\nThe second matrix in @tbl-record-two has two blocks: correlations are $.64$\nwithin the first three indicators, $.36$ within the last three, and zero\nacross blocks.\n\n| | $Y_1$ | $Y_2$ | $Y_3$ | $Y_4$ | $Y_5$ | $Y_6$ |\n|:--|--:|--:|--:|--:|--:|--:|\n| $Y_1$ | 1.00 | | | | | |\n| $Y_2$ | .64 | 1.00 | | | | |\n| $Y_3$ | .64 | .64 | 1.00 | | | |\n| $Y_4$ | .00 | .00 | .00 | 1.00 | | |\n| $Y_5$ | .00 | .00 | .00 | .36 | 1.00 | |\n| $Y_6$ | .00 | .00 | .00 | .36 | .36 | 1.00 |\n\n: *A constructed two-factor correlation matrix.* {#tbl-record-two}\n\nFor the second matrix, let the first three indicators relate to $\\eta_1$\nwith loading $.80$ and the last three to $\\eta_2$ with loading $.60$,\nwith the factors uncorrelated:\n\n$$\n\\boldsymbol{\\Lambda}_2 =\n\\begin{bmatrix}\n.80 & 0\\\\ .80 & 0\\\\ .80 & 0\\\\\n0 & .60\\\\ 0 & .60\\\\ 0 & .60\n\\end{bmatrix},\n\\qquad\n\\boldsymbol{\\Phi}_2 = \\mathbf{I}_2,\n\\qquad\n\\boldsymbol{\\Theta}_2 = \\operatorname{diag}(.36,.36,.36,.64,.64,.64).\n$$\n\n@fig-orthogonal draws the corresponding two-factor parameterization.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The orthogonal two-factor model that reproduces the second record.](chapter_01_files/figure-html/fig-orthogonal-1.png){#fig-orthogonal fig-align='center' fig-alt='Eta 1 loads point 80 on Y1 through Y3, eta 2 loads point 60 on Y4 through Y6, and their covariance is zero.' width=88%}\n:::\n:::\n\n\nWithin the first block,\n$\\operatorname{Cov}(Y_1, Y_2) = .80 \\times 1 \\times .80 = .64$. Within\nthe second, $.60 \\times 1 \\times .60 = .36$. Across the blocks,\n\n$$\n\\operatorname{Cov}(Y_1, Y_4) =\n\\begin{bmatrix} .80 & 0 \\end{bmatrix}\n\\begin{bmatrix} 1 & 0 \\\\ 0 & 1 \\end{bmatrix}\n\\begin{bmatrix} 0 \\\\ .60 \\end{bmatrix} = 0 ,\n$$\n\nwhich reproduces @tbl-record-two. The first three communalities are\n$.64$ with uniquenesses $.36$; the last three are $.36$ with\nuniquenesses $.64$. The SS loadings are $3(.80^{2}) = 1.92$ and\n$3(.60^{2}) = 1.08$.\n\nThe exact zeros between blocks follow from three restrictions acting\ntogether: the simple-structure loading pattern, the orthogonality of the\nfactors, and the absence of cross-block residual covariances. They are\nnot a general property of two-factor models.\n\n## Why one factor will not do {#sec-tetrad}\n\nThe first matrix yielded to a single factor; the second did not. It is\nworth seeing that this is a fact about the numbers, not an impression\nfrom the layout.\n\nUnder a one-factor model with uncorrelated residuals, any covariance is\n$\\sigma_{jk} = \\lambda_j \\phi \\lambda_k$. Take any four indicators and\nform two products of two covariances each:\n\n$$\n\\sigma_{12}\\sigma_{45} - \\sigma_{14}\\sigma_{25}\n= \\lambda_1\\lambda_2\\lambda_4\\lambda_5\\phi^{2}\n- \\lambda_1\\lambda_4\\lambda_2\\lambda_5\\phi^{2}\n= 0 .\n$$ {#eq-tetrad}\n\nThe two products contain the same four loadings and must cancel. This\n**tetrad** restriction is a testable consequence: a single factor\npredicts it for every set of four indicators, whatever the loadings are.\n\nIn @tbl-record-one the restriction holds, as it must. In\n@tbl-record-two, taking $Y_1, Y_2, Y_4, Y_5$,\n\n$$\n\\sigma_{12}\\sigma_{45} - \\sigma_{14}\\sigma_{25}\n= (.64)(.36) - (0)(0) = .2304 \\ne 0 ,\n$$\n\nso no one-factor model with uncorrelated residuals can reproduce that\nmatrix exactly, whatever values its loadings take. The result concerns\nexact reproduction of this known-value matrix; approximate fit to a\nsample covariance matrix is a different question. This is the first\ngenuine model comparison in the book: a restriction with observable\nconsequences, and a set of numbers that violates it. Degrees of freedom are a\nsystematic count of restrictions of exactly this kind.\n\n## Letting the factors correlate {#sec-correlated}\n\nOrthogonality was an assumption, not a finding. Replacing\n$\\boldsymbol{\\Phi}_2 = \\mathbf{I}_2$ with\n\n$$\n\\boldsymbol{\\Phi}_{2\\rho} =\n\\begin{bmatrix} 1 & \\rho \\\\ \\rho & 1 \\end{bmatrix},\n\\qquad -1 \\leq \\rho \\leq 1 ,\n$$\n\nwith strict $|\\rho|<1$ when a nonsingular factor covariance matrix is\nrequired, and keeping the residuals diagonal gives a cross-block\ncovariance of\n\n$$\n\\operatorname{Cov}(Y_1, Y_4) = .80\\,\\rho\\,(.60) = .48\\rho .\n$$ {#eq-cross}\n\nAt $\\rho = .40$ this is $.192$, and every one of the nine cross-block\npairs becomes nonzero. The calculation shows exactly what the\northogonality restriction had been doing, and it also sets a ceiling:\nbecause the common part of a covariance is bounded by the product of the\ntwo communality square roots, no factor correlation can push\n$\\operatorname{Cov}(Y_1, Y_4)$ beyond $.48$ under this loading pattern.\nIf two such indicators correlated at $.60$, no two-factor model of this\nshape could account for it.\n\nReal sample covariance matrices do not usually repeat these clean values\nor contain exact structural zeros. Their deviations combine population\ndiscrepancy with sampling variation, so arithmetic reconstruction gives\nway to estimation, uncertainty, and model evaluation. No empirical result\nis smuggled\ninto the present known-value demonstration.\n\n## Neighboring objects {#sec-objects}\n\nSeveral things get loosely called a dimension or a score, and none of them is\ninterchangeable with another. @tbl-objects separates them before we compare\nfactor-score estimates and principal components more closely.\n\n| Object | What it is | Recorded for unit $i$? |\n|:--|:--|:--|\n| **Construct** | A concept in the research question, such as planning; its meaning comes from theory, item content, response processes, population and intended use | Not made observable by naming a factor |\n| **Common factor** $\\eta_{ik}$ | An unobserved random variable in the model | No |\n| **Factor-score estimate** $\\hat{\\eta}_{ik}$ | A prediction from observed responses, a fitted model and a scoring rule | Computed, but not the factor itself |\n| **Principal component** | A weighted composite of observed variables chosen to summarize variance | Computed from the data |\n| **Prespecified composite** | A declared rule such as a sum or mean of items | Computed from the data |\n\n: *Five objects that are easy to conflate.* {#tbl-objects}\n\nA factor-score estimate depends on the fitted parameters, the items\nincluded, their coding and the scoring rule; different rules give\ndifferent numbers from the same fitted model. Because the factor itself\nis never observed, no scoring rule turns an estimate into an error-free\nmeasurement of it.\n\nPrincipal component analysis deserves a sentence of its own, because it\nis often reached for in the same situations. A principal component is a\nweighted composite of the observed variables, with weights chosen to\ncapture as much observed variance as possible. The common-factor model\nproposes something different in kind: a decomposition of the covariance\ninto a common part and a residual part, as in @eq-implied. The two can\nproduce similar-looking numbers and answer different questions.\nSubstituting one for the other changes what is being claimed; neither is\ngenerally superior.\n\n## Exploratory, confirmatory and hybrid uses {#sec-approaches}\n\nWith the model in hand, the orientations of @sec-orientations can be\nstated more precisely. @tbl-approaches summarizes what each orientation\ndeclares in advance and what it asks the analysis to choose.\n\n| Approach | What is declared in advance | What the analysis chooses |\n|:--|:--|:--|\n| **Exploratory** | The items, the range of factor counts considered, and the estimation and rotation choices | The number of factors, and the loading pattern within an equivalent family of orientations |\n| **Confirmatory** | The number of factors, the loading pattern, factor relations and residual structure | Parameter values, and whether the declared restrictions are compatible with the evidence |\n| **Hybrid or partial** | Some relations prespecified, others left free | Depends on the exact parameterization, which must be stated |\n\n: *What each orientation fixes and what it leaves open.* {#tbl-approaches}\n\nExploratory analysis is not mechanical discovery: the items entered, the\nassociation matrix, the number of factors considered, the extraction\ncriterion, the rotation family and the interpretation are all decisions.\nConfirmatory analysis is not automatic confirmation: it evaluates the\nconsequences of a specification and can expose strain, equivalent\nalternatives, or evidence too weak to distinguish anything.\n\nThe two are often combined, and there is a real hazard in doing so\ncarelessly. A pattern discovered in one body of evidence and then\n\"confirmed\" on the same evidence has not been confirmed; the second\nanalysis is a restatement of the first. The remedy is not to avoid\ncombining them but to keep the *analytic status* of each decision\nvisible: what was specified in advance, what was chosen after looking,\nand what evidence has been used already. A structure chosen using one\nbody of evidence receives a genuinely new confirmatory test only from\nevidence not used to choose it - for example, a prespecified split or a\nnew sample. If evidence is reused, the resulting analysis should be\ndescribed as exploratory or revised rather than independently confirmed.\n\n## The exploratory-to-confirmatory workflow {#sec-workflow}\n\nThe two orientations are most often used in sequence, and the sequence has a\nstructural requirement that is easy to state and easy to violate. An\nexploratory analysis chooses a factor count, a loading pattern and a set of\ninterpretations *by consulting the data*. A confirmatory analysis asks\nwhether a stated pattern is compatible with the data. If both consult the same\ndata, the second analysis can still fail - it imposes exact zeros and other\nrestrictions the exploratory solution never contained, and those can be\ncontradicted. What it cannot do is provide *independent* support, because the\nrestrictions were selected for their agreement with these very numbers. The\nresult is a test whose apparent evidential value has been inflated by the\nselection that preceded it, not a test that is guaranteed to pass.\n\nThe remedy is to give the two stages different evidence. In practice this\nmeans splitting the available data into at least two parts before the\nexploratory work begins - one part to develop on, one held back - or\ncollecting a second sample. The split must be declared in advance and made\nwithout reference to the outcome; a split chosen after seeing which half\nbehaves better is not a split at all.\n\nSplitting is not free. Two halves of $n$ each carry less information than one\nsample of $2n$, and factor recovery degrades in small samples with modest\nloadings, so a study too small to split may be too small for the sequence\n[@fabrigar1999]. The honest alternatives are to collect more data, to report\nthe analysis as exploratory and leave confirmation to later work, or to\ndeclare the model in advance and skip the exploratory stage entirely. What is\nnot an alternative is to run both stages on one sample and describe the\nsecond as confirmation.\n\nPassing a model from one stage to the other requires more than a factor\ncount. @tbl-transition lists what has to be fixed in writing before the held-back\ndata are opened, because each of these is a decision the exploratory stage\nmade and the confirmatory stage must not remake.\n\n| What is transferred | Why it must be fixed in advance |\n|:--|:--|\n| The item set and its order | Dropping a poorly behaved item after seeing the second sample makes that sample exploratory too |\n| The number of factors | The count is the exploratory stage's principal finding, and the claim under test |\n| Which loadings are free and which are fixed at zero | The zeros are the restrictions being tested; adding one back is a new model |\n| Factor variances, covariances and the scaling convention | These determine the metric in which every coefficient is read |\n| The residual structure | A residual covariance freed after inspecting fit is a revision, not a confirmation |\n| Named rival models | Comparisons decided in advance are interpretable; comparisons invented afterwards are selected on the same evidence |\n\n: *What the transition from exploratory to confirmatory work has to declare.* {#tbl-transition}\n\nA revision discovered while examining the held-back sample is a legitimate and\noften necessary thing to do. It simply changes the status of that sample: it\nhas now been used to develop, and the revised model needs evidence of its own.\nAnalyses can move down this ladder freely and never move back up.\n\nA third option refuses the sequence. Exploratory structural equation modeling\nestimates a measurement model with rotational freedom retained inside a larger\nstructural model, rather than forcing every cross-loading to zero\n[@asparouhovMuthen2009; @marsh2014]. It trades the sharpness of exact zero\nrestrictions for a specification that does not pretend to a precision the\nevidence never supplied - a trade whose merits are still actively argued.\n\n## A note on response scales {#sec-response}\n\nThe indicators here are treated as continuous, and Part Two keeps that\ntreatment throughout. Many questionnaire items are recorded on ordered\ncategories, and treating such responses as continuous is a modeling\ndecision with a literature behind it — generally defensible with enough\ncategories and reasonably symmetric distributions, and less so with few\ncategories or strong floor and ceiling effects. The alternative is to\nmodel an underlying continuous response together with thresholds, which\nchanges the estimator and the interpretation of the parameters. That\nroute belongs to a different course. What matters here is that the\nchoice be made deliberately and stated, not made by default.\n\n# Applying the argument-based approach to latent variables (Optional) {#sec-argument}\n\nThis optional section returns to the Chapter Box using the argument\nvocabulary of Part One Chapters 1 and 1a. It may be skipped without loss.\n\n## Can covariance select a unique set of factor axes?\n\nSections 2 to 6 established the statistical account. Here we ask whether\ncovariance selects a unique set of latent axes.\n\n> **Operational question.** Do the original and a rotated two-factor\n> description imply the same six-indicator covariance, and which parts\n> of their interpretation survive the change of axes?\n\nUsing the constructed record in @tbl-record-two, begin with\n$\\boldsymbol{\\Lambda}_2$ and $\\boldsymbol{\\Phi}_2=\\mathbf I_2$ from\n@sec-scenario-two and define the orthogonal matrix\n\n$$\n\\mathbf Q=\\frac{1}{\\sqrt{2}}\n\\begin{bmatrix}\n1&-1\\\\\n1& 1\n\\end{bmatrix},\n\\qquad\n\\boldsymbol{\\eta}_i^*=\\mathbf Q^{\\mathsf T}\\boldsymbol{\\eta}_i,\n\\qquad\n\\boldsymbol{\\Lambda}_2^*=\\boldsymbol{\\Lambda}_2\\mathbf Q .\n$$\n\nBecause $\\mathbf Q^{\\mathsf T}\\mathbf Q=\\mathbf I_2$, the rotated factor\ncovariance remains $\\boldsymbol{\\Phi}_2^*=\\mathbf I_2$. The loading\nmatrix becomes\n\n$$\n\\boldsymbol{\\Lambda}_2^*=\n\\begin{bmatrix}\n.80/\\sqrt{2}&-.80/\\sqrt{2}\\\\\n.80/\\sqrt{2}&-.80/\\sqrt{2}\\\\\n.80/\\sqrt{2}&-.80/\\sqrt{2}\\\\\n.60/\\sqrt{2}& .60/\\sqrt{2}\\\\\n.60/\\sqrt{2}& .60/\\sqrt{2}\\\\\n.60/\\sqrt{2}& .60/\\sqrt{2}\n\\end{bmatrix}.\n$$\n\nThe simple zeros have disappeared, yet the implied covariance has not.\nFor example, the common covariance of $Y_1$ and $Y_4$ is now\n\n$$\n\\frac{.80}{\\sqrt{2}}\\frac{.60}{\\sqrt{2}}\n+\n\\frac{-.80}{\\sqrt{2}}\\frac{.60}{\\sqrt{2}}\n=.24-.24=0.\n$$\n\nEvery other entry is preserved by the same matrix identity,\n$\\boldsymbol{\\Lambda}_2^*\\boldsymbol{\\Phi}_2^*\n\\boldsymbol{\\Lambda}_2^{*\\mathsf T}\n=\\boldsymbol{\\Lambda}_2\\boldsymbol{\\Phi}_2\n\\boldsymbol{\\Lambda}_2^{\\mathsf T}$. Indicator communalities therefore\nstay at $.64$ for $Y_1$ to $Y_3$ and $.36$ for $Y_4$ to $Y_6$. What\nchanges is the allocation to the two columns, as @tbl-axis-ss shows:\n\n| Axes | SS loading 1 | SS loading 2 | Total common variance |\n|:--|--:|--:|--:|\n| Original | 1.92 | 1.08 | 3.00 |\n| Rotated | 1.50 | 1.50 | 3.00 |\n\n: *Factor-specific allocations change while their total is invariant.* {#tbl-axis-ss}\n\n## Does exact reproduction confirm two constructs?\n\nSuppose a results section uses the original simple axes and states:\n\n> \"Because the two-factor model reproduces the six-indicator matrix exactly,\n> the analysis confirms that Planning and Strategy are two distinct\n> psychological constructs.\"\n\nThe arithmetic in the first clause is correct. The conclusion is not. The\nsame covariance matrix admits the rotated description, whose columns no\nlonger preserve the proposed Planning and Strategy partition. The four\nargument roles make the break visible.\n\n**Evidence.** The evidence is the declared correlation matrix together\nwith the original and rotated numerical representations. Its provenance\nmatters: the matrix was constructed from parameters, not estimated from\nrespondents. Exact arithmetic is therefore available, but sampling and\ngeneralization claims are not.\n\n**Justification.** The common-factor covariance equation\n@eq-implied, the unchanged residual covariance matrix, and the\northogonality of $\\mathbf Q$ connect the two loading matrices to the same\nobservable covariance. The choice of axes belongs here as a convention;\nit is not an observed finding.\n\n**Inference.** Substitution gives the same implied covariance,\ncommunalities, and total common variance of $3.00$. The displayed\ncancellation $.24-.24=0$ verifies a cross-block entry, while the SS\nloading calculation shows that factor-specific allocations change from\n$1.92$ and $1.08$ to $1.50$ and $1.50$.\n\n**Claim.** The quoted claim moves from exact reproduction to distinct\npsychological constructs. That transition requires a substantive warrant\nabout indicator content and response processes which the constructed matrix\ndoes not provide.\n\n## Evaluate the claim\n\n@tbl-transition-verdicts applies the six evaluation questions to the quoted\nclaim. The mixed verdicts matter: correct arithmetic at one stage does not\nrepair an unsupported transition at a later one.\n\n\\Needspace{0.72\\textheight}\n\n| Evaluation question | Verdict | Reason in these numbers |\n|:--|:--|:--|\n| Question alignment | Satisfied | The sentence addresses whether the proposed factors may be interpreted as distinct constructs. |\n| Evidence integrity | Satisfied within the declared matrix | All numbers come from the two stated parameterizations of one constructed matrix. |\n| Justification adequacy | Partly satisfied | Orthogonality and @eq-implied license covariance reproduction and equivalence, not the construct labels. |\n| Inferential adequacy | Not satisfied | The equivalent rotation prevents these numbers from selecting the original pair of axes uniquely. |\n| Transition fidelity | Not satisfied | The sentence moves from a statistical representation to psychological entities without a domain or response-process warrant. |\n| Claim calibration | **Not satisfied** | Exact reproduction cannot by itself confirm that Planning and Strategy are distinct psychological constructs. |\n\n: *Six applied evaluation verdicts for an overclaim based on the comparison of axes.* {#tbl-transition-verdicts}\n\n## Repair the claim\n\nA calibrated replacement is:\n\n> \"The matrix is compatible with the displayed two-factor parameterization,\n> but the equivalent rotated description shows that covariance reproduction\n> does not uniquely identify Planning and Strategy axes. Interpreting those\n> axes as distinct constructs requires theory, defensible domain coverage,\n> response-process evidence, and relevant empirical checks.\"\n\n**Answer returned to the opening pair.** The two descriptions imply the\nsame indicator covariance, communalities, and total common variance of\n$3.00$. Their loadings and factor-specific SS allocations\ndiffer. Thus the covariance representation survives the change of axes, whereas the convenience and factor-specific allocation of the\noriginal simple axes do not. The rotated description is outside the\noriginal fixed-zero CFA class: equivalence in the broader factor\nrepresentation does not imply that an identified restricted CFA lacks a\nunique fitted solution.\n\nAs an optional transfer exercise, rewrite the quoted overclaim as four\nsentences - one each for evidence, justification, inference and claim - and\nidentify every phrase you changed to keep covariance compatibility separate\nfrom construct interpretation.\n\n# Summary and reading bridge {#sec-summary}\n\n@fig-chapter-route retraces the chapter's route from observed covariance to a\nbounded interpretation.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The chapter's route from observed covariance to a calibrated conclusion.](chapter_01_files/figure-html/fig-chapter-route-1.png){#fig-chapter-route fig-align='center' fig-alt='A six-step vertical sequence runs from observed indicators covary, through proposing factors and residuals, translating the model, supplying the factor scale, and deriving implied moments and restrictions, to calibrating the substantive claim.' width=78%}\n:::\n:::\n\n\nThe model is\n\n$$\n\\mathbf{y}_i = \\boldsymbol{\\nu} + \\boldsymbol{\\Lambda}\\boldsymbol{\\eta}_i\n               + \\boldsymbol{\\epsilon}_i ,\n\\qquad\n\\boldsymbol{\\Sigma}\n= \\boldsymbol{\\Lambda}\\boldsymbol{\\Phi}\\boldsymbol{\\Lambda}^{\\mathsf T}\n  + \\boldsymbol{\\Theta} ,\n\\qquad\n\\boldsymbol{\\mu}\n= \\boldsymbol{\\nu} + \\boldsymbol{\\Lambda}\\boldsymbol{\\alpha} .\n$$\n\nIts loadings, factor covariances and residual covariances jointly\ndetermine the observed moments. Its factors have no inherited scale, sign or\nlocation, and several metrics describe the same observed covariance. Communality and uniqueness are conditional on\nthe declared model. A diagonal residual covariance matrix does not by\nitself establish local independence.\n\nWhat this chapter could not do is the point of the next one. Every\nnumber here was exact by construction. Given a sample\ncorrelation matrix that no simple model reproduces exactly, how many\nfactors should be retained, how should the axes be chosen, and\nhow much residual discrepancy is tolerable? Chapter 2 takes those\nquestions up as an exploratory analysis, with the retention decision —\nthe one this chapter supplied by construction — treated as the\nconsequential judgment it is.\n\nFor fuller treatments of latent-variable representation and\ncovariance-structure modeling, see @bartholomewKnott1999, @mulaik2010,\n@joreskog1969, @bollen1989 and @brown2006. This chapter uses their\nshared vocabulary selectively and leaves estimation and model evaluation\nto later chapters.\n\n# Exercises {.unnumbered}\n\nShow your assumptions and arithmetic, and end every numerical answer\nwith a sentence of interpretation. None of these requires software.\n\n## Exercise 1 - Classify the quantities {.unnumbered .unlisted}\n\nFor each item below, say whether it is an observed variable, a latent\nrandom variable, an unknown fixed parameter, or a residual random\nvariable. Then explain, in one or two sentences, what distinction is\nlost if every unobserved quantity is simply called \"latent\".\n\n1. A respondent's answer to Item 4.\n2. The loading relating Item 4 to the second factor.\n3. The value of the second factor for that respondent.\n4. The part of Item 4 not represented by the declared factors.\n5. The population covariance between the two factors.\n\n## Exercise 2 - Place the model {.unnumbered .unlisted}\n\n1. Using @tbl-map, say which family fits each of: a five-category\n   attitude scale analyzed with a continuous latent trait; a set of\n   continuous school-performance measures thought to identify unobserved\n   groups of schools; six continuous items thought to reflect two\n   continuous attributes.\n2. Under what additional interpretation can a classical true-score\n   decomposition be represented as a one-factor model? State the\n   equal-loading restriction, then explain why the two frameworks are\n   not generally interchangeable.\n3. Give one question about a six-item scale that an exploratory\n   orientation suits, and one that a confirmatory orientation suits.\n   Explain what makes each appropriate.\n\n## Exercise 3 - Translate between representations {.unnumbered .unlisted}\n\nConsider a two-factor model in which $Y_1, Y_2, Y_3$ relate only to\n$\\eta_1$, $Y_4, Y_5, Y_6$ relate only to $\\eta_2$, the factors may\ncorrelate, and all residual covariances are zero.\n\n1. Write the six scalar equations.\n2. Write $\\boldsymbol{\\Lambda}$, $\\boldsymbol{\\Phi}$ and\n   $\\boldsymbol{\\Theta}$, marking which elements are fixed and which are\n   free.\n3. Sketch the path diagram.\n4. Describe the model in one paragraph, then check that every statement\n   in your paragraph is visible in all three of the other\n   representations.\n\n## Exercise 4 - Reconstruct and perturb {.unnumbered .unlisted}\n\n1. For the model of @sec-scenario-one, recompute one diagonal and one\n   off-diagonal entry of the implied correlation matrix, the communality\n   and uniqueness of any indicator, and the SS loading. State which\n   quantity in your answer is *not* an eigenvalue of @tbl-record-one,\n   and why.\n2. For the model of @sec-scenario-two, recompute one within-block entry\n   from each block and one cross-block entry.\n3. Now suppose $Y_1$ also relates to $\\eta_2$ with a loading of $.25$,\n   with the factors still uncorrelated. Which entries of the implied\n   matrix change, and which do not? Recompute\n   $\\operatorname{Cov}(Y_1, Y_4)$.\n4. Instead of the cross-loading, suppose a residual covariance\n   $\\theta_{14} = .05$ is permitted. Which entries change now? Explain\n   why these two modifications are not interchangeable.\n\n## Exercise 5 - Scale and conventions {.unnumbered .unlisted}\n\nBegin with a standardized one-factor indicator having $\\lambda = .80$,\n$\\phi = 1$ and $\\theta = .36$.\n\n1. Rescale the factor by $a = 2$. Give the new loading and factor\n   variance, and verify that the implied indicator variance is\n   unchanged.\n2. Set $a = -1$. What changes, and what does not? Would you be able to\n   tell the two solutions apart from the correlations alone?\n3. State the difference between fixing a factor's scale and changing the\n   units in which an indicator is recorded. Give an example of each.\n4. In a single-group model the factor mean is usually fixed at zero.\n   Using @eq-location, explain why some such convention is unavoidable.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}