{
  "hash": "f9cfebaeb01e5b839e05ed41418401d1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Extending the GLM: Nominal, Ordinal, and Count Outcomes\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    documentclass: scrartcl\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    latex-auto-install: false\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{16\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nAn outcome's measurement determines what a model must represent. This\nchapter extends regression to three kinds of outcome: a category with no\nassumed ordering, an ordered category with unknown spacing, and a count\nobserved over a specified window. A household employment study, four\ncountries' opinions and school absences connect the equations to the\ncomparisons they answer. The chapter develops probability compositions,\ncumulative odds, exposure offsets and conditional dispersion, and uses\nfitted values to make the size of each comparison intelligible.\n:::\n\nThree questions motivate the models. Among 263 Canadian women surveyed in\n1977, how does labour-force participation differ across household income\nand the presence of children? Among 5,381 respondents in four countries,\nhow does opinion about government effort for people in poverty differ\nacross country and recorded characteristics? Among 146 Australian pupils,\nhow does expected absence in an academic year differ across the study's\nrecorded groups? The outcomes are respectively a composition, an ordered\nresponse and a count. Each needs a mean structure respecting what was\nmeasured, rather than an arbitrary numerical score followed by a line.\n\nThe records come from `carData::Womenlf`, `carData::WVS` and `MASS::quine`\n[@carData2022; @fox2019; @venables2002]. The package extracts carry no\nsampling weights, clustering or stratification information. Their\navailability does not establish a probability sample, so the inferential\nreadings below are conditional comparisons among the recorded units under\nworking independent-row models. The exposure simulation later is explicitly\ninvented. The distinction between those sources matters for what a model\ncan demonstrate and what a study can establish.\n\nDisplayed results are rounded to four decimal places, with trailing zeros\ndropped unless they align a comparison. Calculations using different\nrounding or software settings may differ slightly.\n\n## One Family, Three Outcomes {#ch12-family}\n\n### Keep the predictor; change the response structure\n\nA generalized linear model separates a response distribution, a linear\npredictor $\\eta_i=\\mathbf{x}_i^{\\mathsf T}\\boldsymbol\\beta$, and a link connecting the\nconditional mean to that predictor [@nelder1972]. A binary logistic model\nuses a Bernoulli outcome and a logit link. Nominal and ordinal models\nextend the idea to several category probabilities; count models connect\na nonnegative expected count to a log predictor. These are related\nregression structures, not identical single-response GLMs in every detail.\nIn the vector notation, $\\mathbf{x}_i$ includes an initial 1 when the\nmodel contains an intercept. The ordered model below uses thresholds\ninstead and omits that entry.\n\n| Outcome | Random component | Link and mean | Conditional variance | Home |\n|:--|:--|:--|:--|:--|\n| Quantitative score | Normal | identity, $\\mu_i=\\eta_i$ | $\\sigma^2$, a free parameter | Ch. 7--9 |\n| Binary event | Bernoulli | logit, $\\pi_i=\\operatorname{logit}^{-1}(\\eta_i)$ | $\\pi_i(1-\\pi_i)$ | Ch. 11 |\n| Unordered categories | Categorical, $K$ classes | generalized logit, $K-1$ equations | multinomial | Sec. 2 |\n| Ordered categories | Categorical, $K$ ordered classes | cumulative logit, $K-1$ thresholds | multinomial | Sec. 3 |\n| Count or rate | Poisson | log, $\\mu_i=t_ie^{\\eta_i}$ | $\\mu_i$ | Sec. 4 |\n| Overdispersed count | Quasi-Poisson or negative binomial | log, as above | $\\phi\\mu_i$ or $\\mu_i+\\mu_i^2/\\theta$ | Sec. 5 |\n\n: A common predictor framework, with different response and variance specifications. The linear predictor is the same object throughout. {#tbl-ch12-components tbl-colwidths=\"[20,21,25,22,12]\"}\n\n\nThe predictor remains a sum of terms, but a coefficient's interpretation\nchanges with the response and link. Full probability models use maximum\nlikelihood. Quasi-Poisson is the exception: it specifies a mean and variance\nwithout a full probability distribution, so it has no ordinary likelihood\nor information criterion.\n\n### Decide what the outcome records\n\n| Outcome kind | What one value records | Model in this collection |\n|:--|:--|:--|\n| Binary event | Whether an event occurred | Logistic regression, Chapter 11 |\n| Nominal categories | A category with no defensible ordering: field of study, party voted for, mode of transport | Generalized (baseline-category) logits, Section 2 |\n| Ordered categories | A rank on one substantive dimension with unknown spacing: agreement, severity stage, service rating | Cumulative logits, Section 3 |\n| Count | How many events occurred in a window supplied by the design | Poisson-family regression, Sections 4--5 |\n| Rate | How many events per unit of exposure, when windows differ across units | Count regression with an exposure offset, Section 4.3 |\n| Proportion of known trials | How many of a known number of trials succeeded | Binomial regression with a denominator, named only |\n| Duration until an event | How long until an event, possibly not yet observed | Survival models, outside this collection |\n\n: Outcome triage. The classification is a measurement judgment made before any model is fitted. {#tbl-ch12-triage tbl-colwidths=\"[22,48,30]\"}\n\n\nThe distinction between nominal and ordered categories is substantive.\nEmployment status can be studied as different roles, or ordered by work\nintensity if that is the declared construct. Coding an order does not\nestablish it. Even when an order is defensible, the distances between\ncategories need not be known. Giving them scores 0, 1 and 2 imposes both\nordering and equal spacing; it answers a mean-score question that may\nnot match the intended composition question.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$score <- ifelse(dat$partic == \"not.work\", 0,\n  ifelse(dat$partic == \"parttime\", 1, 2))\nscored <- lm(score ~ hincome + children, data = dat)\nrange(fitted(scored))\n```\n:::\n\n\n\nThe scored labour-force fit ranges from $-.2099$ to 1.5278, including\nfour negative fitted means, and supplies no probability for any category.\nA count likewise needs its observation window: ten incidents in one\nmonth and ten in a year are different rates. A successes count out of a\nknown number of trials can instead be modeled as binomial; having a count\ndoes not automatically imply a Poisson response.\n\nAll three empirical examples use the full distributed extract, with no\nmissing analysis values. `Womenlf` records 155 not working, 66 full time\nand 42 part time. `WVS` has 2,708 Too Little, 1,862 About Right and 811\nToo Much responses. `quine` has integer absence counts from 0 to 81,\nincluding nine zeros. Auditing those definitions and denominators comes\nbefore fitting.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(dat$partic)\ntable(opinion$poverty)\nrange(absence$Days)\ncolSums(is.na(opinion))\n```\n:::\n\n\n\n### Likelihood and comparison carry over\n\nA likelihood evaluates the observed outcomes under specified probabilities,\nwith the data fixed. Maximizing it selects coefficients; the **deviance**\ncompares that maximum with a saturated model fitting each observation:\n\n$$\nD=2\\{\\ell_{\\mathrm{saturated}}-\\ell(\\widehat{\\boldsymbol\\beta})\\}.\n$$ {#eq-ch12-deviance}\n\nDifferences between regular nested models with the same outcome and rows\ncan yield likelihood-ratio tests. AIC and BIC add a parameter penalty to\n$-2\\ell$. A smaller deviance by itself is neither proof of adequate fit\nnor permission to compare any two models by chi-square. In particular,\nchanging the family can change the saturated likelihood, and quasi-Poisson\nhas no full likelihood. Section 6 makes these distinctions concrete.\n\n## Nominal Outcomes: The Generalized Logit {#ch12-nominal}\n\n### Several category probabilities, one reference\n\nLet $Y_i$ take one of $K$ unordered categories, with\n$\\pi_{ik}=P(Y_i=k\\mid \\mathbf{x}_i)$. Choosing category $K$ as the baseline,\nthe **generalized logit**, or baseline-category multinomial logit, states\n\n$$\n\\log\\frac{\\pi_{ik}}{\\pi_{iK}}=\\beta_{0k}+\\sum_{j=1}^p\\beta_{jk}x_{ij},\n\\qquad k=1,\\ldots,K-1.\n$$ {#eq-ch12-baseline-logit}\n\nThere are $K-1$ equations, each with its own intercept and slopes. One\nbaseline sets the coordinate system; it does not make the category more\nfundamental. Writing its predictor as $\\eta_{iK}=0$, the probabilities are\n\n$$\n\\pi_{ik}=\\frac{e^{\\eta_{ik}}}{\\sum_{m=1}^K e^{\\eta_{im}}}.\n$$ {#eq-ch12-baseline-probs}\n\nThey sum to one by construction. A new reference changes the printed\ncoefficient equations while preserving the same fitted probabilities.\nThe rows must still support the comparisons: a tiny or empty category\nwithin a predictor region can destabilize an estimate.\n\n### Name both categories in every ratio\n\nThe exponentiated coefficient $e^{\\beta_{jk}}$ is the factor by which\n$\\pi_k/\\pi_K$ differs for units one predictor unit apart, holding the\nother predictors fixed. It is conventionally called a **relative-risk\nratio** (RRR), also interpretable as a pairwise-category odds ratio when\nthe comparison is restricted to those two categories. It is not the\ncumulative odds ratio developed in Section 3.\n\nAn RRR above one need not make category $k$'s own probability rise: a\nthird category may rise faster, changing the shared denominator. The\nratio names both compared categories, its predictor unit and adjustment\nset. Probabilities then show the whole composition, which a single\npairwise ratio cannot do [@long2000].\n\n### Labour-force composition in the household records\n\nThe unit is one recorded woman. Husband's income is in thousands of 1977\ndollars, and children are coded absent or present. We ask about conditional\nlabour-force composition within these records, choosing not working\noutside the home as the baseline. With children absent, 46 of 79 women\nworked full time; with children present, 20 of 184 did. Part-time counts\nare 7 and 35. These observations motivate separate category probabilities,\nwithout themselves proving or disproving an ordered model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$partic <- relevel(dat$partic, \"not.work\")\nnom <- nnet::multinom(partic ~ hincome + children, data = dat, trace = FALSE)\nexp(coef(nom))\nexp(confint(nom))\n```\n:::\n\n\n| Equation and term | Coefficient | SE | RRR | 95% interval |\n|:--|--:|--:|--:|:--|\n| Full time: intercept | 1.9828 | 0.4842 | --- | --- |\n| Full time: husband's income | $-0.0972$ | 0.0281 | 0.9073 | [0.8587, 0.9587] |\n| Full time: children present | $-2.5586$ | 0.3622 | 0.0774 | [0.0381, 0.1574] |\n| Part time: intercept | $-1.4323$ | 0.5925 | --- | --- |\n| Part time: husband's income | 0.0069 | 0.0235 | 1.0069 | [0.9617, 1.0543] |\n| Part time: children present | 0.0215 | 0.4690 | 1.0217 | [0.4075, 2.5619] |\n\n: Generalized logits for labour-force participation, with not working outside the home as baseline. Deviance 422.8819 on six parameters; AIC 434.8819. {#tbl-ch12-nominal-fit tbl-colwidths=\"[34,14,12,12,28]\"}\n\n\nAn additional thousand dollars of husband's income multiplies the\nfull-time-to-not-working probability ratio by .9073. Children present\nare associated with .0774 times that ratio, at the same income. The\npart-time-to-not-working intervals both cover one. That leaves a wide\nrange of compatible comparisons rather than proving no association.\nEach predictor appears in two equations, so testing its removal as a\nblock uses two df: the income block gives $\\chi^2(2)=15.1532$,\n$p=.0005$, and the children block 63.5586, $p<.0001$.\n\n### Read the fitted composition\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- expand.grid(hincome = c(5, 15, 25),\n  children = c(\"absent\", \"present\"))\npredict(nom, grid, type = \"probs\")\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Fitted participation probabilities across income, with observed income support shown below.](chapter_12_files/figure-html/fig-ch12-nominal-fitted-1.png){#fig-ch12-nominal-fitted fig-pos='!ht' fig-alt='Full-time probability falls as income increases in both panels, especially with children present. Not-working and part-time probabilities take the remaining share. Rugs show that observations are concentrated at lower incomes.' width=595.2}\n:::\n:::\n\n\nFull-time probabilities decline with income, while part-time probabilities\nrise. The middle-category rise is possible under a proportional-odds\nmodel too; it is not by itself evidence against ordering. The curves answer the composition question directly: each vertical slice\nallocates one whole probability across three categories. With children\nabsent, full-time probability falls from .7817 at income 5 to .3323 at 25;\nwith children present it falls from .2164 to .0369. Thus the same income\nrelative-risk ratio need not imply the same probability difference.\nPredict how changing the reference category would change this figure:\nits fitted curves would stay in place. At income\n25 with children present the observed full-time cell is empty, making\nthe small fitted probability dependent on the regression's pooling across\nincome values, rather than a precise direct estimate for that cell.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Observed participation composition by income band and children present; bar labels are counts.](chapter_12_files/figure-html/fig-ch12-nominal-observed-1.png){#fig-ch12-nominal-observed fig-pos='!ht' fig-alt='Full-time participation declines across income bands, especially among women with children present, where the highest-income band has no full-time workers. Part-time and not-working categories carry different patterns.' width=595.2}\n:::\n:::\n\n\n\n### A different reference gives the same fitted surface\n\nWith full-time work as the reference, the not-working coefficients become\n$-1.9828$, .0972 and 2.5586; the part-time coefficients become\n$-3.4151$, .1041 and 2.5801. Deviance remains 422.8819. Fitted\nprobabilities agree with the first fit to within $5\\times10^{-5}$,\nreflecting numerical tolerance. Predict this invariance before refitting:\nrelabeling a denominator cannot change the modeled distribution of the\nsame outcome.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nother <- dat\nother$partic <- relevel(other$partic, \"fulltime\")\nrefit <- nnet::multinom(partic ~ hincome + children, data = other, trace = FALSE)\npredict(refit, grid, type = \"probs\")\n```\n:::\n\n\n\nThese are cross-sectional comparisons. \"Women whose husbands earned\nmore were less likely to work full time\" describes them; \"raising the\nhusband's income would move a woman out of full-time work\" requires a\ncausal design and assumptions the records do not supply.\n\n## Ordered Outcomes: The Cumulative Logit {#ch12-ordinal}\n\n### Cumulative probabilities and thresholds\n\nFor a defensible order $1<\\cdots<K$, define\n$\\gamma_{ij}=P(Y_i\\le j\\mid \\mathbf{x}_i)$ for $j=1,\\ldots,K-1$. Each is\na cumulative probability at one **cut point**. Category probabilities\nare differences of successive cumulative probabilities. A cumulative\nlogit model with proportional odds is\n\n$$\n\\log\\frac{P(Y_i\\le j\\mid \\mathbf{x}_i)}{P(Y_i>j\\mid \\mathbf{x}_i)}\n=\\zeta_j-\\mathbf{x}_i^{\\mathsf T}\\boldsymbol\\beta,\\qquad\n\\zeta_1<\\cdots<\\zeta_{K-1}.\n$$ {#eq-ch12-cumulative-logit}\n\nThe ordered $\\zeta_j$ are thresholds, not effects. The predictor vector here\nomits the intercept entry because the thresholds supply the location\nconstants. The minus sign used by `ordinal::clm()` and `MASS::polr()`\nmeans that a positive coefficient shifts probability toward higher\ncategories. Thus $e^{\\beta_j}$ multiplies the odds **above** either cut,\nnot a single pair of categories.\n\nOne useful picture imagines a continuous response\n$Y_i^*=\\mathbf{x}_i^{\\mathsf T}\\boldsymbol\\beta+\\varepsilon_i$ with standard logistic\nerror, observed only as the interval between fixed thresholds into which\nit falls. The shift changes how much probability lies in each interval.\nThis is a representation of the model, not proof that an actual latent\nattitude has a logistic distribution.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same thresholds divide two shifted logistic distributions into three ordered categories.](chapter_12_files/figure-html/fig-ch12-thresholds-1.png){#fig-ch12-thresholds fig-pos='H' fig-alt='Fixed thresholds at minus one half and one and a half divide a logistic density. Moving its centre from minus one to plus one shifts probability from the lowest to the highest category.' width=595.2}\n:::\n:::\n\n\n\n### The common-slope restriction is testable\n\nThe model uses the same slope vector at every cut. Consequently the\ncumulative log-odds difference between two otherwise comparable units is\nthe same at each cut: **proportional odds**. A cut-specific alternative\nreplaces $\\boldsymbol\\beta$ by $\\boldsymbol\\beta_j$. The common-slope\nmodel is nested in that alternative, so their likelihood comparison tests\na real restriction [@mccullagh1980]. Ordering the outcome alone does not\nimpose or justify it.\n\n**Start with a process whose truth is known.** Imagine a study of\nconfidence, recorded as Low, Middle or High, and a preparation score $x$\nrescaled to lie between $-1$ and 1. We generate independent records with\n$x$ uniform over that range. For the two cumulative probabilities, set\n\n$$\n\\operatorname{logit}\\{P(Y\\le 1\\mid x)\\}=-.5-b_1x,\\qquad\n\\operatorname{logit}\\{P(Y\\le 2\\mid x)\\}=2-b_2x.\n$$ {#eq-ch12-po-truth}\n\nThese cumulative probabilities stay ordered throughout the chosen range,\nso their differences give valid Low, Middle and High probabilities. The\nfirst process uses $b_1=b_2=.6$: preparation has the same above-cut\nodds ratio at both splits. The second uses $b_1=.3$ and $b_2=1.5$:\npreparation is much more strongly related to reaching High than to\nleaving Low. Both processes describe ordered responses; only the first\nhas proportional odds.\n\n**Predict and explain.** We fit a common-slope model to 4,000 records\nfrom each process. Which fitted lines must be parallel, and where might\nthat restriction conceal a category-probability difference?\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Known cumulative logits and the common-slope fits to two generated samples. The lower row makes the imposed restriction visible.](chapter_12_files/figure-html/fig-ch12-po-process-1.png){#fig-ch12-po-process fig-pos='H' fig-alt='Four panels compare truth and fit. Common generating slopes of .6 yield a fitted common slope .5253. Different generating slopes .3 and 1.5 are forced into parallel fitted lines with slope .6673, hiding their different changes across preparation.' width=595.2}\n:::\n:::\n\n\nThe fitted common slopes are .5253 and .6673. Sampling variation explains\nthe first estimate's difference from its truth of .6. In the second\nsample, the model forces a compromise: its coefficient is a restricted\nlikelihood summary, not an arithmetic average of the two true slopes.\nAt $x=1$, the second process has High probability .3775, whereas its\ncommon-slope fit gives .2406. A plausible-looking coefficient can thus\nconceal a consequential error on the response scale.\n\nFreeing the slope at the second cut adds one parameter. The nested\nlikelihood comparisons give $\\chi^2(1)=.3466$, $p=.556$ for the first\nsample and $\\chi^2(1)=176.0519$, $p<.0001$ for the second. The first\nresult is compatible with common slopes; a nonsignificant test does not\nestablish that restriction in an unknown population. For the second\nsample, the strong evidence and the probability discrepancy point in\nthe same direction.\n\n\\Needspace{5\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- ordinal::clm(y ~ x, data = sim2)\nfree2 <- ordinal::clm(y ~ 1, nominal = ~x, data = sim2)\nanova(fit2, free2)\n```\n:::\n\n\n**Detection also depends on study size.** A less obvious departure,\n$b_1=.6$ and $b_2=.85$, illustrates why a diagnostic $p$-value needs\ncontext. Hold that process fixed and generate 500 independent studies at\neach of two sample sizes. Repeat the same comparison under the true\ncommon-slope process as a reference.\n\n| Process | Records per study | Rejections in 500 studies | Rejection proportion | Monte Carlo SE |\n|:--|--:|--:|--:|--:|\n| Common slopes | 300 | 25 | .050 | .0097 |\n| Common slopes | 6,000 | 23 | .046 | .0094 |\n| Different slopes | 300 | 75 | .150 | .0160 |\n| Different slopes | 6,000 | 470 | .940 | .0106 |\n\n: Repeated tests at the .05 level, with thresholds and predictor distribution held fixed. All fitted comparisons were valid; the 500 repetitions describe sampling variation across studies. {#tbl-ch12-po-detection tbl-colwidths=\"[16,18,25,23,18]\"}\n\nThe first two rows estimate false-positive rates when common slopes are\ntrue. The last two estimate power against this particular alternative.\nThe same modest departure is detected much more often in the larger\nstudies. More observations improve detection; they do not make the\nunderlying departure larger. Conversely, a small study can miss a\nrestriction that matters for its intended probability comparison.\n\nEach reported proportion also has simulation uncertainty. Its Monte\nCarlo standard error is $\\sqrt{\\widehat r(1-\\widehat r)/500}$, where\n$\\widehat r$ is the rejection proportion. This describes the precision\nof the simulation's rate estimate, not the uncertainty of a coefficient\nin one study. One simulated sample supplies one test result; repeated\nsamples are needed to estimate a rejection rate. In an empirical study,\nwe still need the fitted category probabilities and substantive context\nto judge what a detected departure means.\n\nThe World Values Survey records order opinion as Too Little, About Right,\nToo Much government effort. Observed country proportions offer an early\nwarning: Sweden's cumulative logit differs from Australia's by .3826\nat the lower cut but 2.009 at the upper. The gaps are not parallel.\nThese are marginal summaries, so an adjusted model must still be checked\nrather than treating the graph as its formal test.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Observed cumulative logits by country, before adjustment.](chapter_12_files/figure-html/fig-ch12-observed-logits-1.png){#fig-ch12-observed-logits fig-pos='!ht' fig-alt='Country gaps differ greatly between the two cut points. Norway and Sweden have much larger upper-cut logits than Australia, while the United States is lower at both cuts.' width=595.2}\n:::\n:::\n\n\n\n### Fit and interpret opinion among the recorded respondents\n\nThe four samples contain 1,874 Australian, 1,127 Norwegian, 1,003 Swedish\nand 1,377 United States respondents. The comparison adjusts for age,\nrecorded gender, membership of a religion and university degree. There\nare few Too Much responses in Norway (36) and Sweden (25), a support\nfeature that will matter when checking fitted composition.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npo <- ordinal::clm(poverty ~ religion + degree + country + age + gender,\n  data = opinion)\nexp(confint(po, type = \"Wald\"))\n```\n:::\n\n\n| Term | Coefficient | SE | OR | 95% interval |\n|:--|--:|--:|--:|:--|\n| Threshold Too Little $\\mid$ About Right | 0.7298 | 0.1041 | --- | --- |\n| Threshold About Right $\\mid$ Too Much | 2.5325 | 0.1103 | --- | --- |\n| Member of a religion | 0.1797 | 0.0773 | 1.1969 | [1.0285, 1.3928] |\n| University degree | 0.1409 | 0.0662 | 1.1513 | [1.0112, 1.3108] |\n| Norway against Australia | $-0.3224$ | 0.0738 | 0.7244 | [0.6269, 0.8371] |\n| Sweden against Australia | $-0.6033$ | 0.0795 | 0.5470 | [0.4681, 0.6392] |\n| United States against Australia | 0.6178 | 0.0707 | 1.8548 | [1.6149, 2.1303] |\n| Age, per year | 0.0111 | 0.0016 | 1.0112 | [1.0081, 1.0143] |\n| Male against female | 0.1764 | 0.0530 | 1.1929 | [1.0752, 1.3234] |\n\n: Proportional-odds fit for opinion about government effort; $-2\\ell=10402.5924$ on nine parameters, AIC 10420.5924. A positive coefficient shifts probability toward the higher ordered categories, from Too Little through About Right to Too Much. {#tbl-ch12-ordinal-fit tbl-colwidths=\"[36,14,12,12,26]\"}\n\n\nUnder this restriction, United States respondents have 1.8548 times the\nAustralian respondents' cumulative odds above either cut at the same\nother predictor values: About Right/Too Much versus Too Little, and\nToo Much versus Too Little/About Right. It is not the odds of Too Much\nversus Too Little with About Right discarded.\n\nCheck the sign convention on a profile. For a 45-year-old religious woman\nwithout a degree in Norway, subtract the linear predictor from each\nthreshold and apply the inverse logit. The cumulative probabilities are\n.5917 and .8979; subtracting gives category probabilities .5917, .3062\nand .1021. A positive predictor shift decreases the cumulative probability\nbelow each cut and moves mass upward, as claimed.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofile <- data.frame(religion = \"yes\", degree = \"no\",\n  country = \"Norway\", age = 45, gender = \"female\")\npredict(po, profile, type = \"prob\")\n```\n:::\n\n\n\n### Let the cut points have different contrasts\n\n`nominal_test()` checks a predictor's proportional-odds restriction by\nallowing its effects to differ across cuts within the cumulative-link\nfamily. Country gives $\\chi^2(3)=362.3463$, $p<.0001$; degree gives\n10.2866 ($p=.0013$), age 5.0587 ($p=.0245$), gender 3.0902\n($p=.0788$) and religion .414 ($p=.52$). These checks identify a large\ncountry departure and smaller possible departures; a large p-value does\nnot establish a restriction.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nordinal::nominal_test(po)\ncutfit <- ordinal::clm(poverty ~ religion + degree + age + gender,\n  nominal = ~ country, data = opinion)\nanova(po, cutfit)\n```\n:::\n\n\n| Country against Australia | Common log-odds coefficient | Lower cut | Upper cut |\n|:--|--:|--:|--:|\n| Norway | $-0.3224$ | $-0.1227$ | $-1.7812$ |\n| Sweden | $-0.6033$ | $-0.4449$ | $-2.0687$ |\n| United States | 0.6178 | 0.3626 | 0.8727 |\n\n: One common coefficient against two cut-specific ones, all in the direction of the higher ordered categories. {#tbl-ch12-cutspecific tbl-colwidths=\"[34,22,22,22]\"}\n\n\nFor Norway, the single common coefficient $-.3224$ masks a small lower-cut\ncontrast and a much larger upper-cut contrast. The striking feature is\nhow few Norwegian respondents choose Too Much. AIC falls from 10420.5924\nto 10064.2461 for three more parameters; the fitted Too Much probability\nat the Norway profile falls from .1021 to .0289. This **partial\nproportional-odds** model frees country while retaining common slopes for\nthe other predictors. Those remaining restrictions still require checking;\nfreeing the largest departure does not settle every condition.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relaxing the country restriction reallocates probability across the opinion categories.](chapter_12_files/figure-html/fig-ch12-ordinal-comparison-1.png){#fig-ch12-ordinal-comparison fig-pos='!ht' fig-alt='Four country panels compare common and cut-specific country slopes at the same profile. Norway Too Much falls from .1021 to .0289; the United States About Right category also changes substantially.' width=595.2}\n:::\n:::\n\n\nThe paired bars hold age, religion, degree and gender fixed. Follow all\nthree probabilities when the country restriction is relaxed: probability\nremoved from Norway's Too Much category must go somewhere else. In the\nUnited States panel the largest shift is in About Right. The figure shows\nhow a restriction can alter the substantive description, not just a\np-value. These are conditional profile comparisons, not country averages;\nbetter in-sample agreement does not establish the remaining restrictions.\n\nA common-slope estimate after a demonstrated violation is at best a\nmodel-dependent compromise, not a literal arithmetic average of the\ncut-specific coefficients. Report cut-specific comparisons and fitted\nprobabilities when they explain the substantive pattern.\n\nThe known-truth example in Section 3.2 separated detection from its\nconsequences. Here the generating process is unknown, but the same\ninterpretive step is available: inspect the probabilities at profiles\nthat matter. The simulation's rejection rates are not power estimates\nfor these survey records. The Norwegian profile shows a practical\nconsequence of this fitted restriction beyond the small $p$-value.\n\n### Separate ordering from proportional odds\n\nReturn to employment and stipulate the order not working, part time,\nfull time. The proportional-odds fit has four parameters, deviance\n441.663 and AIC 449.663; the nominal fit has six parameters, deviance\n422.8819 and AIC 434.8819. The lower nominal AIC favors its probability\nsurface among these candidates on the same records.\n\nThese are generally **nonnested** families. Linear cumulative logits do\nnot generally produce linear baseline-category logits, so subtracting\nthe two deviances and calling the difference chi-square on two df is\ninvalid. Valid common-slope checks compare cumulative models with common\nand cut-specific slopes: here income gives 4.1382 ($p=.0419$), and\nchildren 11.2982 ($p=.0008$). They challenge proportional odds, not the\nlogical ordering of employment intensity.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$ord <- factor(dat$partic,\n  levels = c(\"not.work\", \"parttime\", \"fulltime\"), ordered = TRUE)\nord <- MASS::polr(ord ~ hincome + children, data = dat, Hess = TRUE)\nAIC(ord, nom)\nordinal::nominal_test(ordinal::clm(ord ~ hincome + children, data = dat))\n```\n:::\n\n\n\nA nominal analysis remains natural for a question about distinct employment\nroles. If an ordered construct is substantively warranted, relaxing\nproportional odds can preserve that ordering. Conversely, good fit cannot\nmake an arbitrary ordering meaningful. Collapsing adjacent categories\nalso changes the measurement and estimand; a better statistic on the\ncollapsed outcome cannot justify the merge because the outcome changed.\n\n\n## Counts and Rates: Poisson Regression {#ch12-counts}\n\n### A positive mean with a specified variance\n\nFor count $Y_i$, the Poisson model assigns probabilities\n$P(Y_i=y\\mid \\mathbf{x}_i)=e^{-\\mu_i}\\mu_i^y/y!$ for integers $y\\ge0$.\nThe **log link** connects its positive mean to a linear predictor:\n\n$$\n\\log\\mu_i=\\eta_i=\\beta_0+\\sum_j\\beta_jx_{ij},\\qquad\n\\mu_i=e^{\\beta_0}\\prod_j e^{\\beta_jx_{ij}}.\n$$ {#eq-ch12-log-link}\n\nAdding a coefficient on the log scale multiplies the expected count by\nits exponential. Unlike an unrestricted straight mean, this function\ncannot predict a negative count. A fitted mean can be fractional even\nthough an observed count is an integer, because it is an expectation\nover repeated observations rather than one possible observation.\n\nThe Poisson distribution ties spread to the mean:\n\n$$\n\\operatorname{Var}(Y_i\\mid \\mathbf{x}_i)=E(Y_i\\mid \\mathbf{x}_i)=\\mu_i.\n$$ {#eq-ch12-poisson-var}\n\nThere is no separately fitted residual SD. As the mean rises the spread\nrises, while the distribution becomes less skewed. This variance condition\nwill be the central problem in the absence data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndpois(0:5, lambda = 2)\nexp(c(0, 1, 2))\n```\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Poisson distributions at means 2, 8 and 20; the conditional variance equals the mean in each panel.](chapter_12_files/figure-html/fig-ch12-poisson-pmf-1.png){#fig-ch12-poisson-pmf fig-pos='!ht' fig-alt='Three bar distributions over nonnegative integers become wider and less right-skewed as their means rise from two to eight to twenty.' width=595.2}\n:::\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![An additive log mean implies multiplicative expected counts.](chapter_12_files/figure-html/fig-ch12-log-link-1.png){#fig-ch12-log-link fig-pos='!ht' fig-alt='A straight line on the log-mean scale corresponds to a rising convex curve for expected counts.' width=595.2}\n:::\n:::\n\n\n\n### Ratios and counts in the absence study\n\nFor one predictor unit at the same other predictor values,\n$\\mu(x_j+1)/\\mu(x_j)=e^{\\beta_j}$. This **incidence-rate ratio**\n(IRR) compares expected counts when windows are common, or expected\nrates when exposure is accounted for. It is not a probability, an odds\nratio or a within-person change. A constant ratio already implies larger\nabsolute differences at larger baseline means; a ratio that itself\nchanges with another predictor is an interaction on the log scale.\n\nThe `quine` study records days absent in one academic year. Its ethnic\nand learner classifications are the historical study's own labels, not\nclaims about inherent group qualities. We use the stated common academic\nyear as the exposure, while recognizing that unrecorded enrollment or\nattendance-recording differences would undermine that comparison.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Recorded days absent among 146 pupils in a rural New South Wales study.](chapter_12_files/figure-html/fig-ch12-absence-distribution-1.png){#fig-ch12-absence-distribution fig-pos='!ht' fig-alt='Absences have a floor at zero, with nine zero counts, and a long right tail extending to eighty-one days.' width=595.2}\n:::\n:::\n\n\n\nThe observed mean is 16.4589 days, variance 264.1673, and quartiles\n5, 11 and 22.75. That marginal variance is much larger than the marginal\nmean, but heterogeneous expected means alone can create such a difference.\nWe must first condition on the predictors before diagnosing overdispersion.\n\n| Field | What it records | Reference level in the model |\n|:--|:--|:--|\n| Days | Days absent in the academic year | Outcome count |\n| Eth | Historical Aboriginal/not-Aboriginal classification | A: Aboriginal |\n| Sex | Recorded sex | F: female |\n| Age | School form, a four-level factor | F0: primary form |\n| Lrn | Historical learner classification | AL: average learner |\n\n: Variables and reference levels in the absence analysis. {#tbl-ch12-count-data tbl-colwidths=\"[18,47,35]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmp <- glm(Days ~ Eth + Sex + Age + Lrn,\n  family = poisson(link = \"log\"), data = absence)\nexp(coef(mp))\n```\n:::\n\n\n| Term | Coefficient | SE | IRR |\n|:--|--:|--:|--:|\n| Intercept | 2.7154 | 0.0647 | 15.1104 |\n| Not Aboriginal | $-0.5336$ | 0.0419 | 0.5865 |\n| Male | 0.1616 | 0.0425 | 1.1754 |\n| Form 1 | $-0.3339$ | 0.0701 | 0.7161 |\n| Form 2 | 0.2578 | 0.0624 | 1.2941 |\n| Form 3 | 0.4277 | 0.0677 | 1.5337 |\n| Slow learner | 0.3489 | 0.0520 | 1.4176 |\n\n: Poisson fit for days absent; residual deviance 1696.7066 on 139 df, null deviance 2073.5328 on 145, AIC 2299.1836. Reference child: Aboriginal, female, primary form, average learner. {#tbl-ch12-poisson-fit tbl-colwidths=\"[34,22,22,22]\"}\n\n\nThe reference child's fitted expected absence is 15.1104 days.\nThe not-Aboriginal/Aboriginal IRR is .5865, at the same other recorded\nclassifications. That ratio is interpretable only beside its baseline:\nit implies 8.862 expected days for a female average learner in F0\nclassified as not Aboriginal. These are conditional group descriptions,\nnot effects of changing an identity or classification.\n\nThe output's small p-values might initially appear impressive, but its\nresidual deviance is 1696.7066 on 139 df. The conditional variance check\nin Section 5 shows why the usual Poisson standard errors are too small.\nThe number of small p-values alone is not the diagnosis.\n\n### Exposure is part of the estimand\n\nIf unit $i$ is observed for $t_i$ days, person-years or another exposure,\nlet $\\lambda_i$ denote its event rate. Then $\\mu_i=t_i\\lambda_i$.\nA log-linear rate model gives\n\n$$\n\\log\\mu_i=\\log t_i+\\beta_0+\\sum_j\\beta_jx_{ij}.\n$$ {#eq-ch12-offset}\n\nThe exposure term has a coefficient fixed at one. Such a known-coefficient\npredictor is an **offset**. Doubling exposure doubles the expected count\nwhile retaining the same rate, a substantive restriction about how events\naccumulate. It is appropriate only when that relation matches the process\nand the exposure has been measured adequately.\n\nBefore fitting a rate model, name the event, the observation window and\nwhether that window differs across units. Without the offset the\ncoefficients compare counts over those potentially different windows;\nwith it they compare rates. When exposure is related to predictors,\nomitting it can move slopes as well as the intercept. Even with equal\nexposure, naming it tells the reader what a count means.\n\nAn offset has no estimated coefficient, SE or p-value. To assess the\nproportional-exposure restriction, fit a free coefficient $\\gamma$ on\n$\\log t_i$ and compare it with 1. Here $\\gamma$ is a locally defined\nexposure coefficient, distinct from the cumulative probabilities\n$\\gamma_{ij}$ in Section 3. The question is whether the stipulated\naccumulation rule is consistent with the data, not whether exposure is\n\"significant\" and can therefore be dropped.\n\n### A known process with unequal observation windows\n\nThe invented district example records behavioral referrals for 500\nstudents. Higher screening risk makes mobility more probable, so students\nwith higher rates tend to have fewer enrolled days. Mentoring is related\nto risk in the generated records. The declared conditional process is\n\n$$\n\\log\\lambda_i=-4.2-.35\\,\\mathrm{mentor}_i+.45\\,\\mathrm{risk}_i,\n\\qquad Y_i\\sim\\operatorname{Poisson}(t_i\\lambda_i).\n$$ {#eq-ch12-sim-truth}\n\nThe true mentoring and risk IRRs are .7047 and 1.5683. At seed 1202,\n125 students have fewer than the full 180 days; exposure ranges from\n31 to 180, correlating $-.2976$ with risk. The 79,090 enrolled days\ncontain 1,195 referrals. Thus observation time and propensity for events\nmust be separated to recover the declared rate comparison.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nratefit <- glm(events ~ mentor + risk, offset = log(days),\n  family = poisson, data = sim)\ncountfit <- glm(events ~ mentor + risk, family = poisson, data = sim)\nexp(coef(ratefit))\nexp(coef(countfit))\n```\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Counts depend on both rate and exposure in the invented 500-student study.](chapter_12_files/figure-html/fig-ch12-exposure-1.png){#fig-ch12-exposure fig-pos='!ht' fig-alt='Two scatterplots by mentoring show incident counts rising in spread with enrolled days, with a dense stripe at one hundred eighty days.' width=595.2}\n:::\n:::\n\n\n| Quantity | Truth | Offset model | Offset omitted |\n|:--|--:|--:|--:|\n| Mentoring IRR | 0.7047 | 0.7024 | 0.7174 |\n| Risk IRR | 1.5683 | 1.5700 | 1.4192 |\n| Intercept, daily rate | 0.0150 | 0.0157 | --- |\n| Residual deviance | --- | 521.9792 | 666.1568 |\n| Pearson dispersion statistic | 1 | 0.9438 | 1.2050 |\n\n: A declared process recovered with and without its exposure offset; 500 generated students, seed 1202. {#tbl-ch12-offset tbl-colwidths=\"[36,16,24,24]\"}\n\n\nThe offset fit recovers the declared IRRs: .7024 [.6202, .7955] for\nmentoring and 1.57 [1.4791, 1.6665] for risk. Omitting exposure moves\nthe risk IRR to 1.4192, because less observed time partly conceals higher\nrates. The demonstration concerns a stipulated conditional process; it\ndoes not make observational mentoring coefficients causal in a real district.\n\nA free exposure coefficient gives 1.1631 (SE .1124), with interval\n[.9429, 1.3833]. Testing $\\gamma=1$ gives Wald $z=1.4517$,\n$p=.1466$, and a nested likelihood statistic 2.197, $p=.1383$.\nThe records are compatible with proportional accumulation, while the\ninterval describes the remaining uncertainty about that restriction.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreefit <- glm(events ~ mentor + risk + log(days),\n  family = poisson, data = sim)\nconfint.default(freefit)[\"log(days)\", ]\n```\n:::\n\n\n| Profile | Rate per 100 enrolled days | Expected count, 180 days | Expected count, 60 days |\n|:--|--:|--:|--:|\n| Not mentored, average risk | 1.5721 | 2.8298 | 0.9433 |\n| Mentored, average risk | 1.1043 | 1.9877 | 0.6626 |\n| Not mentored, risk one SD higher | 2.4682 | 4.4427 | 1.4809 |\n| Mentored, risk one SD higher | 1.7337 | 3.1206 | 1.0402 |\n\n: Fitted rates at four profiles and the counts they imply over two observation windows; 500 generated students, seed 1202. {#tbl-ch12-rates-counts tbl-colwidths=\"[34,22,22,22]\"}\n\n\nThe rates in a row are stable across windows, but the 180-day expected\ncount is three times the 60-day count. One fitted number without its\nwindow would leave the study's main distinction invisible. These generated\ncounts have marginal variance-to-mean ratio 1.599, yet the correctly\nspecified conditional Pearson ratio is .9438. A marginal ratio above\none therefore does not establish conditional overdispersion.\n\n## Overdispersion: Quasi-Poisson and the Negative Binomial {#ch12-dispersion}\n\n### Compare spread around conditional means\n\n**Overdispersion** means conditional variance exceeds the conditional\nmean, relative to the Poisson variance assumption. If $k$ coefficients\nare estimated, a common diagnostic is the mean squared Pearson residual:\n\n$$\n\\widehat\\phi=\\frac{1}{n-k}\\sum_i\\frac{(y_i-\\widehat\\mu_i)^2}{\\widehat\\mu_i}.\n$$ {#eq-ch12-dispersion}\n\nWith an adequate Poisson mean and variance it estimates a value near one.\nThe deviance ratio $D/(n-k)$ is a rough companion diagnostic, whose\nbehavior also depends on the expected counts. It is not automatically a\nconservative or interchangeable estimate of dispersion.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(residuals(mp, type = \"pearson\")^2) / df.residual(mp)\ndeviance(mp) / df.residual(mp)\nvar(absence$Days) / mean(absence$Days)\n```\n:::\n\n\n\nThe absence fit has Pearson ratio 13.1668, deviance ratio 12.2065\nand marginal ratio 16.0501. The first two already condition on the four\nrecorded predictors. Binning similar fitted means makes the excess spread\nconcrete, although bins still contain some mean heterogeneity and their\nraw variance-to-mean ratios are descriptive rather than exact tests.\n\n| Fitted-value bin | Children | Observed mean | Observed variance | Variance / mean |\n|:--|--:|--:|--:|--:|\n| 1 | 36 | 8.0000 | 55.1429 | 6.8929 |\n| 2 | 26 | 11.6538 | 91.8354 | 7.8803 |\n| 3 | 33 | 19.6364 | 374.9886 | 19.0966 |\n| 4 | 29 | 17.5172 | 193.8300 | 11.0651 |\n| 5 | 22 | 29.8182 | 437.2987 | 14.6655 |\n\n: Observed mean and variance within five bins of Poisson-fitted values. Bins pool unequal fitted means, so their ratios are descriptive; some excess above 1 can come from remaining mean variation within a bin. {#tbl-ch12-bins tbl-colwidths=\"[22,16,20,22,20]\"}\n\n\nBefore changing the variance family, consider the mean, exposure,\nrecording process and dependence. All four predictors are factors, but\nthe additive log mean still restricts interactions. Adding ethnicity by\nform improves deviance by 153.87 on three df and leaves a Pearson ratio\nof 11.7342. This particular interaction explains little of the excess\nspread; it does not prove every other mean specification correct. The\ncomparison below retains the additive mean as a working approximation\nwhile examining what variance assumptions do to uncertainty.\n\nIf the mean is correct and independent-row regularity conditions hold,\nPoisson estimating equations can consistently estimate its coefficients\neven with a wrong variance [@cameron2013]. The conventional model-based\nSEs can then be seriously wrong. Under variance $\\phi\\mu$, a variance\nmultiplier near 13 makes those SEs too small by about $\\sqrt{13}$.\nThat mechanism, rather than impressive-looking p-values, motivates a remedy.\n\n### Quasi-Poisson preserves the fitted mean\n\nQuasi-Poisson keeps the same log mean and specifies\n$\\operatorname{Var}(Y_i\\mid \\mathbf{x}_i)=\\phi\\mu_i$. Its coefficient estimating\nequations match the Poisson equations, so the estimates are identical;\nSEs multiply by $\\sqrt{\\widehat\\phi}$. Here the multiplier is 3.6286.\nR's summary coefficient tests use an approximate $t$ reference. The\nreported `confint.default()` intervals instead use the large-sample\nNormal Wald reference, a distinction that should remain explicit.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmq <- glm(Days ~ Eth + Sex + Age + Lrn,\n  family = quasipoisson, data = absence)\nexp(confint.default(mq))\ndrop1(mq, test = \"F\")\n```\n:::\n\n\n\nThe not-Aboriginal IRR stays .5865, while its interval widens from\n[.5403, .6367] to [.4354, .7900]. None of the three individual form\ncontrasts excludes one, yet the whole form block gives\n$F(3,139)=4.5966$, $p=.0042$. A joint factor comparison and a single\ncontrast against one arbitrary reference answer different questions.\n\nQuasi-likelihood specifies no complete outcome distribution. Consequently\nthere is no ordinary log-likelihood, AIC or BIC, and R returns `NA` for\nAIC deliberately. Nested quasi-Poisson mean models can be compared using\napproximate scaled-deviance $F$ tests. A predictive count distribution\nalso needs assumptions beyond this mean-and-variance specification.\n\n### Negative binomial changes the distribution and weighting\n\nThe negative binomial supplies a full distribution with\n\n$$\nE(Y_i\\mid \\mathbf{x}_i)=\\mu_i,\\qquad\n\\operatorname{Var}(Y_i\\mid \\mathbf{x}_i)=\\mu_i+\\frac{\\mu_i^2}{\\theta},\\qquad\\theta>0.\n$$ {#eq-ch12-nb-var}\n\nOne interpretation mixes Poisson rates across units sharing the same\nobserved predictors, with a gamma mixing factor of mean one. That gives\nquadratic extra variance in the mean [@hilbe2011]. It is a possible\nmechanism, not something uniquely established by a fitted negative-binomial\ncurve. Small $\\theta$ means more overdispersion; as $\\theta$ grows,\nthe variance approaches Poisson.\n\nQuasi-Poisson has constant variance-to-mean multiplier $\\phi$, whereas\nthe negative binomial's multiplier $1+\\mu/\\theta$ increases with the\nmean. Thus the two families disagree about how variability grows across\nprofiles, not merely about one correction factor.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmn <- MASS::glm.nb(Days ~ Eth + Sex + Age + Lrn, data = absence)\nmn$theta\nexp(confint.default(mn))\n```\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Variance functions fitted to the absence records, with descriptive binned means and variances.](chapter_12_files/figure-html/fig-ch12-variance-functions-1.png){#fig-ch12-variance-functions fig-pos='!ht' fig-alt='The Poisson identity line lies far below the observed binned variation. The quasi-Poisson straight line and negative-binomial curve cross around mean fifteen and a half days.' width=595.2}\n:::\n:::\n\n\n\nThe fit gives $\\widehat\\theta=1.2749$ (SE .161) and Pearson ratio\n.9912. Large fitted means receive less information weight relative to\nPoisson, so coefficients change as well as SEs. The not-Aboriginal IRR\nbecomes .5659 with interval [.4190, .7643]. This is a new likelihood\nfit, not the old fit with a rescaled covariance matrix.\n\n### Compare remedies against the question and the evidence\n\n| Term | IRR, Poisson and quasi | SE, Poisson | SE, quasi | IRR, negative binomial | SE, negative binomial |\n|:--|--:|--:|--:|--:|--:|\n| Intercept | 15.1104 | 0.0647 | 0.2347 | 18.0759 | 0.2284 |\n| Not Aboriginal | 0.5865 | 0.0419 | 0.1520 | 0.5659 | 0.1533 |\n| Male | 1.1754 | 0.0425 | 0.1543 | 1.0858 | 0.1599 |\n| Form 1 | 0.7161 | 0.0701 | 0.2543 | 0.6386 | 0.2397 |\n| Form 2 | 1.2941 | 0.0624 | 0.2265 | 1.0921 | 0.2362 |\n| Form 3 | 1.5337 | 0.0677 | 0.2456 | 1.4289 | 0.2483 |\n| Slow learner | 1.4176 | 0.0520 | 0.1888 | 1.3392 | 0.1865 |\n\n: Days absent under three variance specifications on the same 146 records. SEs are on the log-coefficient scale, not the IRR scale. The conditional-dispersion evidence motivates comparing uncertainty specifications. {#tbl-ch12-three-fits tbl-colwidths=\"[24,17,13,13,17,16]\"}\n\n\nThe SE columns are on the coefficient's log scale, not the IRR scale.\nQuasi-Poisson multiplies them all by 3.6286; negative binomial changes\nthem by different factors. Under both, ethnicity is the only individual\ncontrast whose 95% interval excludes one. Form remains jointly informative:\nnegative-binomial deletion tests give approximately $\\chi^2(3)=11.979$,\n$p=.0075$. These package deletion tests hold its fitted dispersion\nparameter fixed; refitting dispersion in every reduced model is a different\nlikelihood comparison and should be labeled as such.\n\n| Response | Target it serves | Plausible mechanism | Checking evidence |\n|:--|:--|:--|:--|\n| Quasi-Poisson | The same mean model with honest uncertainty, where no likelihood-based comparison is needed | A constant variance-to-mean multiplier across the fitted range | $\\widehat\\phi$ far above 1, with the binned variance-to-mean ratio roughly level in the fitted mean |\n| Negative binomial | A full likelihood, for information criteria, intervals or a predicted count distribution | The Poisson mean varies across units sharing predictor values, so variability grows with the mean | $\\widehat\\phi$ far above 1, with the binned ratio rising in the fitted mean, and a Pearson statistic near 1 after the refit |\n| Revise the mean instead | The same question, answered with a mean the records support | An omitted predictor, an unmodelled interaction, or a missing exposure | Enriching the mean removes most of the excess spread |\n\n: Choosing a variance specification from the target, the mechanism and the checking evidence. {#tbl-ch12-family-choice tbl-colwidths=\"[16,28,28,28]\"}\n\n\nAIC is 2299.1836 for Poisson and 1109.151 for negative binomial; there\nis no quasi-Poisson entry. The Poisson limit is $1/\\theta=0$, on the\nboundary of the negative-binomial parameter space. Under appropriate\nregularity conditions the likelihood-ratio null reference is a half-mass\nat zero and half $\\chi^2_1$ mixture, not ordinary chi-square on one df.\nHere the large likelihood improvement accompanies compelling dispersion\nevidence; it does not excuse checking mean structure or dependence.\nOther mixture or zero-inflation comparisons can have further unidentified\nparameters, so this exact mixture must not be assumed universal.\n\nBefore reading the diagnostic numbers, predict which model can place more\nprobability in both tails while retaining similar mean comparisons.\n\nA fitted count mean does not show how much probability the model assigns\nto zero or to a long upper tail. For each pupil, the fitted model assigns\na probability to each count band. Adding those probabilities across\npupils gives the expected number in that band. This preserves the pupils'\ndifferent fitted means. Substituting one overall mean would instead\ncreate a different distribution.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(dpois(0, fitted(mp)))\nsum(dnbinom(0, mu = fitted(mn), size = mn$theta))\nsum(ppois(50, fitted(mp), lower.tail = FALSE))\n```\n:::\n\n\n\n\n::: {#tbl-ch12-count-bands .cell tbl-cap='Observed and fitted count-band totals; the final band includes the entire upper tail.' tbl-colwidths='[25,25,25,25]'}\n::: {.cell-output-display}\n\n\n|Band       | Observed| Poisson| Negative binomial|\n|:----------|--------:|-------:|-----------------:|\n|0          |        9|  0.0141|            6.2136|\n|1-2        |       10|  0.4492|           14.4933|\n|3-5        |       26|  5.2770|           21.0057|\n|6-10       |       24| 29.6620|           28.4776|\n|11-20      |       35| 70.6830|           35.3951|\n|21-50      |       34| 39.9072|           33.0525|\n|51 or more |        8|  0.0074|            7.3623|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Observed and fitted count-band totals show where the two count distributions differ.](chapter_12_files/figure-html/fig-ch12-count-bands-1.png){#fig-ch12-count-bands fig-pos='!ht' fig-alt='The Poisson model assigns almost no pupils to zero or above fifty days absent, although nine and eight were observed. Negative binomial places appreciable mass in both tails and reduces the Poisson excess in the eleven-to-twenty-day band.' width=595.2}\n:::\n:::\n\n\nThe Poisson fit expects almost no zero counts and almost no counts above\n50; nine and eight were observed. The negative-binomial distribution\nplaces appreciable probability in both regions. Its total expectations\nsum to 146, just as the observed counts do. Summing only counts from 0\nto 100 would silently lose some of its upper tail, so the last band is\ncalculated with the distribution function all the way to infinity.\n\nThese are fitted, model-dependent comparisons. Their discrepancy is a\nuseful diagnostic, not automatically a chi-square test with a degrees-of-\nfreedom count obtained by subtracting arbitrary numbers of bins and\nparameters. Several expected Poisson totals are very small, and every\npupil has a different fitted distribution. A reference distribution for\na formal statistic would need an argument or a simulation reflecting\nthis fitting procedure.\n\nQuasi-Poisson specifies a mean and a variance, not a full count\ndistribution. There is therefore no corresponding quasi-Poisson column\nof expected band probabilities without adding a distributional\nassumption. This is the same reason its fitted variance alone does not\nsupply a likelihood-based AIC.\n\n\n## Check and Compare Across the Family {#ch12-checking}\n\n### Residuals use a model-specific yardstick\n\nFor counts, a Pearson residual is\n$(y_i-\\widehat\\mu_i)/\\sqrt{V(\\widehat\\mu_i)}$; a signed deviance\nresidual uses the square root of that observation's deviance contribution.\nThey are read against their own response family, not against an assumed\nNormal residual cloud. The largest absolute Pearson residual in the\nabsence fit falls from 13.5933 under Poisson to 3.7975 under negative\nbinomial; the corresponding maximum deviance residual falls from 9.9091\nto 2.7918. The pupil absent 81 days has fitted means 27.7199 and 26.4371:\nthe large change is the variance yardstick, not a disappearance of the\nunusual observation.\n\n### Compare observed and fitted composition\n\nFor categories, group records meaningfully and sum fitted probabilities\nto obtain expected counts. The descriptive discrepancy\n$X^2=\\sum(O-E)^2/E$ shows where a model misses. Automatically attaching\na chi-square reference is risky when continuous predictor values are\npooled into coarse cells, parameters were estimated on ungrouped data,\nor expected cells are small.\n\nFor the nominal labour-force fit, total fitted category counts match\n155, 66 and 42 to numerical precision because of the intercept score\nequations. Within eight income-band-by-children groups, $X^2=12.4195$,\nwith smallest fitted cell 1.0738. Read that as a display diagnostic,\nnot a calibrated goodness-of-fit test with a mechanically subtracted df.\nThe empty high-income full-time cell with children present remains a\nsupport question even if overall composition looks reasonable.\n\n| Country | Observed Too Much | Proportional odds | Cut-specific |\n|:--|--:|--:|--:|\n| Australia | 300 | 271.1860 | 300.0223 |\n| Norway | 36 | 126.8882 | 36.3260 |\n| Sweden | 25 | 89.7115 | 24.9734 |\n| United States | 450 | 344.1366 | 448.1760 |\n\n: Observed and fitted counts in the highest ordered category, by country. Over all twelve country-by-category cells, $X^2=322.9447$ under proportional odds and 0.0164 under the cut-specific model. {#tbl-ch12-composition tbl-colwidths=\"[28,24,24,24]\"}\n\n\nThe proportional-odds fit expects about 127 Norwegian and 90 Swedish\nToo Much responses where 36 and 25 occurred. The cut-specific model\nbrings those expectations much closer. This discrepancy shows what the\nrestriction was concealing on the scale of the data. Close in-sample\nagreement after adding flexibility is useful but is not held-out validation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvars <- c(\"religion\", \"degree\", \"country\", \"age\", \"gender\")\nP <- predict(po, newdata = opinion[, vars], type = \"prob\")$fit\ncolSums(P)\ntable(opinion$country, opinion$poverty)\n```\n:::\n\n\n\n### Match comparison rules to the fitted models\n\nAIC and BIC use $-2\\ell+2k$ and $-2\\ell+k\\log n$, counting all estimated\nparameters. Nominal slopes enter $K-1$ equations; cumulative models count\nthresholds; negative-binomial criteria count dispersion as well as mean\ncoefficients. Compare likelihoods only for the same records, outcome\ncoding and likelihood convention.\n\n| Records and outcome | Model | $k$ | Deviance or $-2\\ell$ | AIC |\n|:--|:--|--:|--:|--:|\n| 263 women, three participation categories | Null | 2 | 500.4926 | 504.4926 |\n| | Husband's income only | 4 | 486.4405 | 494.4405 |\n| | Children only | 4 | 438.0351 | 446.0351 |\n| | Proportional odds, both predictors | 4 | 441.6630 | 449.6630 |\n| | Generalized logits, both predictors | 6 | 422.8819 | 434.8819 |\n| 5,381 respondents, three ordered categories | Null | 2 | 10740.3765 | 10744.3765 |\n| | Without country | 6 | 10653.4731 | 10665.4731 |\n| | Proportional odds | 9 | 10402.5924 | 10420.5924 |\n| | Cut-specific country | 12 | 10040.2461 | 10064.2461 |\n| 146 pupils, days absent | Poisson | 7 | 1696.7066 | 2299.1836 |\n| | Quasi-Poisson | 7 | 1696.7066 | none |\n| | Negative binomial | 8 | 167.9518 | 1109.1510 |\n\n: Likelihood criteria within each set of records. Check nesting separately; count-model deviances use different saturated likelihoods. {#tbl-ch12-criteria tbl-colwidths=\"[30,28,8,17,17]\"}\n\n\nWithin the women block, the proportional-odds and generalized-logit rows\ncan be compared by AIC but are not a nested chi-square comparison. Within\nthe opinion block, freeing country slopes is a nested comparison in the\nsame cumulative-link family. In the count block, Poisson and\nnegative-binomial deviances use different saturated likelihoods: their\ndeviance difference is not their likelihood-ratio statistic. Their AICs\nuse comparable complete likelihoods, with the boundary qualification for\na formal test. Nothing is comparable across the three datasets' blocks.\n\n### What changing a family cannot repair\n\nA variance remedy cannot supply a missing exposure, recover an unmeasured\npredictor, undo measurement error or establish independent sampling.\nPupils within schools, patients within clinics and repeated observations\nneed dependence-aware uncertainty or models. Counts truncated or censored\nby a recording rule need that rule represented; an estimated population\ndenominator adds uncertainty that a fixed offset does not include.\nThe choice set in a nominal model and the substantive order in an ordinal\nmodel are also claims about measurement, not facts certified by a small\nresidual or a favorable criterion.\n\n## From Analysis to a Defensible Claim {#ch12-claim}\n\n### Use the outcome scale alongside the ratio\n\nA report states the analytic units and question, response model and coding,\nratio and its interval, fitted probabilities or counts at named profiles,\ncondition checks, and limits of extension. These are pieces of a reasoned\naccount, not a required six-sentence ritual. A fitted probability without\nan interval is a point summary, not an exact quantity; an interval on a\ncoefficient elsewhere in the paragraph does not quantify every derived\nprobability or count. Evaluating a rule on new cases is a separate task\nfrom illustrating its fitted means.\n\n### Three reports, each bounded by its study\n\n::: {.callout-tip title=\"Labour-force composition\"}\nAmong the 263 women recorded in the 1977 Canadian extract, an additional\nthousand dollars of husband's income was associated with a full-time-to-not-working\nRRR of .9073 (95% interval [.8587, .9587]), adjusting for children\npresent. With no children present, fitted full-time probabilities were\n.7817 at income 5 and .3323 at 25 thousand dollars. Part-time comparisons\nwere less precisely determined. A nominal composition model had lower\nAIC than the candidate proportional-odds model, whose common-slope\nrestriction was also challenged by within-family tests. These conditional\ncomparisons do not identify consequences of changing household income\nor childbearing.\n:::\n\n::: {.callout-tip title=\"Opinion about government effort\"}\nOpinion was ordered from Too Little through About Right to Too Much in\n5,381 recorded respondents. A common-slope cumulative model gave a United\nStates/Australia odds ratio of 1.8548 [1.6149, 2.1303] above either cut,\nbut country effects differed substantially across cuts\n($\\chi^2(3)=362.3463$, $p<.0001$). Allowing cut-specific country\ncoefficients reduced AIC from 10420.5924 to 10064.2461 and better\nrepresented the few Too Much responses in Norway and Sweden. These are\nconditional cross-sectional comparisons. The extract does not supply\nsurvey-design information, and remaining common-slope restrictions require\nfurther checking.\n:::\n\n::: {.callout-tip title=\"Absence counts\"}\nDays absent during a common academic year were modeled for 146 recorded\npupils. The Poisson Pearson dispersion ratio was 13.1668; one additional\ninteraction left 11.7342. A negative-binomial fit gave\n$\\widehat\\theta=1.2749$ (SE .161) and Pearson ratio .9912. The\nnot-Aboriginal/Aboriginal IRR was .5659 [.4190, .7643] at common recorded\nsex, form and learner classification. For female average learners in F0,\nfitted expectations were 18.0759 and 10.2288 days respectively. A\nquasi-Poisson fit gave a similar substantive reading with wider uncertainty\nthan Poisson. The historical group labels describe this study; the\ncomparison does not identify an effect of changing a classification,\nand dependence or unrecorded differences remain possible.\n:::\n\n### Diagnose an overclaim before calculating again\n\n\"The relative-risk ratio was .9073\" omits the compared categories.\n\"Swedes had lower odds\" omits the cumulative direction. \"The offset was\nnot significant\" mistakes a fixed coefficient for an estimate.\n\"The model predicted well\" confuses in-sample fit with evaluated\nperformance. Each repair restores the missing statistical meaning,\nnot merely a cautious adjective.\n\nAn interval covering one is also a quantitative result. The\nnegative-binomial male/female IRR interval [.7936, 1.4855] permits\nsubstantively lower or higher expected absence. Whether that range is\nsmall enough for a decision depends on the question, not only on its\np-value [@wasserstein2016].\n\n## Reading Bridge\n\nNominal models explain a composition through several baseline-category\nlogits; ordinal models use cumulative probabilities and testable slope\nrestrictions; count models connect positive means to exposure and a\nvariance assumption. Their ratios are different quantities, each needing\nan outcome-scale comparison and a stated scope. Chapter 13 changes the\ngoal: evaluating how a fitted rule performs on records it has not seen.\n\n## Key terms {.unnumbered}\n\nThese are the concepts introduced here. The Part One Concept Reference\nlocates likelihood, links, model comparison and other earlier concepts.\n\n| Term and common alternatives | Meaning or essential distinction |\n| :-- | :-- |\n| Outcome triage | The measurement judgment, made before any model is fitted, classifying an outcome as binary, nominal, ordered, a count, a rate, a proportion of known trials, or a duration. The model follows the classification and cannot establish it. |\n| Generalized logit model (baseline-category logit; multinomial logistic regression) | For $K$ unordered categories, $K-1$ log-ratio equations against one baseline, each with its own intercept and slopes. The fitted probability surface is the same whichever baseline is chosen; the coefficients are not. |\n| Baseline outcome category | The outcome category in the denominator of every generalized-logit equation: a coordinate choice, distinct from the reference level of a categorical *predictor*, whose change alters every reported ratio. |\n| Relative-risk ratio (RRR) | The exponentiated generalized-logit coefficient: the factor by which one category's probability relative to the baseline's differs per predictor unit. It is not a probability difference, and is incomplete unless both compared categories are named. |\n| Independence of irrelevant alternatives (IIA) | The generalized logit's assumption that the ratio of two categories' probabilities does not depend on which other categories were available: a claim about the choice set, argued rather than settled by one test. |\n| Cumulative probability and cumulative logit | $\\gamma_{ij}=P(Y_i\\le j)$ at each of the $K-1$ cut points, and its log-odds. A category probability is a difference of two adjacent cumulative probabilities. |\n| Threshold (cut point; ordinal intercept) | One of the ordered constants $\\zeta_1<\\cdots<\\zeta_{K-1}$ placing the cut points on the logit scale. Their ordering keeps fitted probabilities nonnegative; they are not comparisons and are not read as effects. |\n| Proportional odds (common-slope restriction; partial proportional odds) | The restriction that one slope vector governs every cut point, so a single odds ratio applies at all of them. It is imposed by the analyst, not conferred by ordering the levels, and is testable against a cut-specific alternative. |\n| Poisson regression (log-linear count model) | A GLM with a Poisson random component and a log link, so the conditional mean is positive and differences are multiplicative on the count scale. Its conditional variance is not free: it is forced to equal the mean. |\n| Incidence-rate ratio (IRR; rate ratio) | The exponentiated coefficient of a count or rate model: the factor by which the expected count, or rate when an exposure is included, differs per predictor unit. It hides its baseline, so an absolute difference is not recoverable from it alone. |\n| Exposure and offset | The window over which each unit was observed, and $\\log t_i$ entered with its coefficient fixed at one so the model describes a rate. An offset is a decision about the estimand, not an estimate: no SE, no $p$-value, and freeing its coefficient gives a testable alternative. |\n| Overdispersion and the dispersion statistic | Conditional variance exceeding the conditional mean, assessed by the mean squared Pearson residual $\\widehat\\phi$ under a suitable mean model; the deviance ratio is a rough diagnostic and need not be near 1 for sparse counts even under a correct Poisson model. The diagnosis is conditional; a marginal ratio above one is not evidence. |\n| Quasi-Poisson (quasi-likelihood; scaled Poisson) | The Poisson mean with variance $\\phi\\mu$: identical estimates and every SE multiplied by $\\sqrt{\\widehat\\phi}$. No full distribution is specified, so there is no log-likelihood and no AIC or BIC. |\n| Negative-binomial regression | A count model with variance $\\mu+\\mu^2/\\theta$, arising when the Poisson mean varies across units sharing predictor values. A different likelihood, not a rescaling: estimates move because large fitted means are down-weighted, and the Poisson comparison sits on the boundary $1/\\theta=0$. |\n\n: Concepts introduced here. {#tbl-ch12-key-terms tbl-colwidths=\"[31,69]\"}\n\n\n## Further reading {.unnumbered}\n\nAgresti [@agresti2010; @agresti2018] develops categorical models;\nMcCullagh [@mccullagh1980] gives the cumulative-link framework. Cameron\nand Trivedi [@cameron2013] and Hilbe [@hilbe2011] develop counts and\ndispersion. The `ordinal`, `nnet` and `MASS` documentation gives the\nparameterizations used here [@christensen2025; @venables2002].\n\n## Exercises {.unnumbered}\n\n<!-- prompt-id: CH12-E01 -->\n\n### Exercise 1: Triage four outcomes and find the exposure (Foundational). {.unnumbered}\n\nFor each of the following, state the outcome kind\nfrom the chapter's triage table, name the model family, and say in one\nsentence what the exposure is or why none is needed. (1) The field of\nstudy a first-year student enrols in, from six faculties. (2) A\npatient's self-rated recovery, recorded as worse, unchanged, or better.\n(3) The number of behaviour referrals recorded for each of 400 pupils\nduring one full school year. (4) The number of emergency presentations\nfrom each of 60 districts during 2023, where the districts have\npopulations from 4,000 to 210,000. (5) A pupil's score out of 20 on a\nspelling test. For (4), write the linear predictor with its offset term\nand say which quantity the coefficients then compare.\n\n<!-- END exercise-id: CH12-E01 -->\n\n<!-- prompt-id: CH12-E02 -->\n\n### Exercise 2: Read a generalized-logit result (Foundational). {.unnumbered}\n\nA\ngeneralized-logit model of labour-force participation among 263 women,\nwith not working outside the home as the baseline, reports\nrelative-risk ratios of 0.9073 per thousand dollars of husband's income\nand 0.0774 for children present in the full-time equation, and 1.0069\nand 1.0217 in the part-time equation, with intervals [0.8587, 0.9587],\n[0.0381, 0.1574], [0.9617, 1.0543] and [0.4075, 2.5619]. (1) Write one\ncomplete sentence reporting the 0.9073, naming both compared\ncategories. (2) State what the part-time equation does and does not\nestablish. (3) A colleague reports \"the relative-risk ratio for\nchildren was 0.0774\" with no other wording. Say what is missing and why\nthe number cannot be checked without it. (4) The same data refitted\nwith full-time work as the baseline give a children coefficient of\n2.5586 in the not-working equation. Explain why the two fits are the\nsame model.\n\n(5) Use the chapter's fitted-probability curves to explain why a\nconstant full-time versus not-working relative-risk ratio does not give\na constant full-time probability difference. Predict what happens to all\nthree curves when the reference category changes.\n\n<!-- END exercise-id: CH12-E02 -->\n\n<!-- prompt-id: CH12-E03 -->\n\n### Exercise 3: State the cumulative direction (Foundational). {.unnumbered}\n\nA\ncumulative-logit model of opinion about government effort, coded so\nthat a positive coefficient shifts probability toward the higher\nordered categories from Too Little through About Right to Too Much,\nreports thresholds 0.7298 and 2.5325 and coefficients 0.1797\n(religion), $-0.3224$ (Norway against Australia), 0.6178 (United States\nagainst Australia) and 0.0111 per year of age. (1) Report the United\nStates odds ratio of 1.8548 in one sentence with its direction and its\nconditioning set. (2) Say what the Norway coefficient means in the same\nterms. (3) Calculate the fitted probability of answering Too Little for\na 45-year-old religious woman without a degree in Norway, using\n$\\operatorname{logit}(\\gamma_1)=\\zeta_1-\\mathbf{x}^{\\mathsf T}\\boldsymbol\\beta$\nand the coefficients above. (4) Explain in one sentence why the\nthresholds are not reported as effects.\n\n(5) The common-slope model gives Too Much probability .1021 at this\nNorway profile, whereas the partial model gives .0289. Use the paired\nprobability display to explain what the common restriction was\nconcealing, and name one reason why the better fitted picture does not\nsettle the analysis. Predict what would happen to the frequency of\nrejection if a fixed modest slope departure were studied with 6,000\nrather than 300 records. Explain why this change would not by itself\nshow a larger practical consequence.\n\n<!-- END exercise-id: CH12-E03 -->\n\n<!-- prompt-id: CH12-E04 -->\n\n### Exercise 4: The offset is a decision, not an estimate (Foundational). {.unnumbered}\n\nFive hundred students were observed for between 31\nand 180 enrolled days, and behavioural incidents were counted. Two\nPoisson models were fitted to the same records: one with\n$\\log(\\text{days enrolled})$ as an offset, giving a risk\nincidence-rate ratio of 1.57, and one without it, giving 1.4192. (1)\nState the estimand of each model in one sentence each. (2) The data\nwere generated with a true risk rate ratio of 1.5683. Explain why\nomitting the offset moved a slope and not only the intercept. (3) A\nreviewer asks for the offset's standard error and $p$-value. Explain\nwhy there are none, and describe the model that would answer the\nunderlying question. (4) At a fitted rate of 1.5721 incidents per 100\nenrolled days, give the expected number of incidents over 180 days and\nover 60 days, and say which of the three numbers is the stable\nquantity.\n\n<!-- END exercise-id: CH12-E04 -->\n\n<!-- prompt-id: CH12-E05 -->\n\n### Exercise 5: Diagnose dispersion before choosing a family (Integrative). {.unnumbered}\n\nA Poisson regression of days absent on four\ncategorical predictors, fitted to 146 children, has residual deviance\n1696.7066 on 139 degrees of freedom and a Pearson dispersion statistic\nof 13.1668; every coefficient has $p<.001$. (1) State what the\ndispersion statistic estimates under a correct Poisson model, and by\nwhat rescaling factor the quasi-Poisson variance model would imply. (2) Adding an\nethnicity-by-form interaction improves the deviance by 153.87 on\nthree degrees of freedom but leaves the dispersion statistic at\n11.7342. Explain what this says about that particular interaction and what it leaves unresolved. (3) A quasi-Poisson refit leaves the\nnot-Aboriginal incidence-rate ratio at 0.5865 and raises its log-coefficient\nstandard error from 0.0419 to 0.1520; a negative-binomial refit gives 0.5659\nwith log-coefficient standard error 0.1533. Explain why one estimate moved and the\nother did not. (4) The quasi-Poisson fit has no AIC and the\nnegative-binomial fit has AIC 1109.151 against the Poisson 2299.1836.\nSay which comparisons are legitimate and which is not, and why.\n\n(5) Nine pupils have zero absences and eight exceed 50 days. Poisson\nexpects .0141 and .0074 in these bands; negative binomial expects 6.2136\nand 7.3623. Explain what this adds to the coefficient and AIC\ncomparisons, and why there is no comparable quasi-Poisson probability\ncolumn without a further assumption.\n\n<!-- END exercise-id: CH12-E05 -->\n\n<!-- prompt-id: CH12-E06 -->\n\n### Exercise 6: Critique a categorical-outcome report (Integrative). {.unnumbered}\n\nA\nreport states: \"Multinomial logistic regression showed that higher\nhousehold income reduced the relative-risk ratio to 0.91. An ordinal\nmodel showed that Swedish respondents had significantly lower odds\n(OR = 0.55). A Poisson model of clinic visits showed that every\npredictor was highly significant ($p<.001$), and the exposure offset\nwas retained because it was significant.\" (1) Name five distinct omissions or unsupported readings, using the chapter's vocabulary. (2) Rewrite the passage as\nthree defensible sentences, inventing no new numbers but adding the\ninformation each claim requires. (3) State one check the authors should\nhave reported for each of the three models, and say what each check\nwould and would not establish.\n\n<!-- END exercise-id: CH12-E06 -->\n\n\n## Appendix A: Choice Sets and Cut-specific Structure {.unnumbered}\n\n### What a nominal choice model assumes {.unnumbered .unlisted}\n\nIn a baseline-category multinomial logit, the probability ratio for two\ncategories depends on their two linear predictors. Adding a third\ncategory changes the denominator of both probabilities, so it leaves\ntheir ratio unchanged if those predictors stay fixed. This property is\ncalled **independence of irrelevant alternatives** (IIA).\n\nImagine a travel choice between a car and a blue bus. If an otherwise\nidentical red bus becomes available, people who preferred the bus might\nsplit between the two colours, leaving car use nearly unchanged. A model\nthat treats red and blue buses as independent alternatives instead\nredistributes probability according to a more restrictive rule. The\nproblem is substantive similarity between alternatives, rather than a\nminor numerical imperfection. The same question matters if two response\ncategories are nearly interchangeable or the available choice set\nvaries between people.\n\nFor labour-force participation, consider whether part-time and full-time\nwork are substitutes in the same way as not working and either work\ncategory. The observed labels alone do not answer that question. IIA\nchecks and more flexible choice models can be useful, but a small-sample\nformal test cannot establish a plausible choice mechanism. The nominal\nfit in this chapter is a conditional description of the recorded\ncomposition, with the stated working structure.\n\n### A partial proportional-odds comparison {.unnumbered .unlisted}\n\nThe opinion example can be fitted through `MASS::polr()` or\n`ordinal::clm()` using the same ordered response, rows, formula and logit\nlink. The coefficient vectors agree to numerical tolerance (within\n$10^{-5}$ here), and both give AIC 10420.5924. Different function defaults\nor reversed category order would prevent this direct comparison.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbridge <- MASS::polr(poverty ~ religion + degree + country + age + gender,\n                     data = opinion, Hess = TRUE)\nAIC(bridge, po)\nnominal_test(po)\n```\n:::\n\n\n\nRelaxing the country restriction allows a separate country comparison\nat each cut point, while retaining common slopes for religion, degree,\nage and gender. The fitted signs must be translated to the same\nabove-cut direction before comparison. @tbl-ch12-partial-full\nreports that direction: a positive coefficient increases the log-odds\nof a response **above** the named split, conditional on the remaining\nvariables. Australia is the reference country.\n\n\n\n::: {#tbl-ch12-partial-full .cell tbl-cap='Country comparisons at the two cumulative splits, with common slopes for the remaining recorded predictors.' tbl-colwidths='[32,22,22,24]'}\n::: {.cell-output-display}\n\n\n|Comparison          | Above-cut coefficient|     SE| Odds ratio|\n|:-------------------|---------------------:|------:|----------:|\n|Norway, lower split |               -0.1227| 0.0778|     0.8845|\n|Norway, upper split |               -1.7812| 0.1817|     0.1684|\n|Sweden, lower split |               -0.4449| 0.0824|     0.6409|\n|Sweden, upper split |               -2.0687| 0.2134|     0.1264|\n|USA, lower split    |                0.3626| 0.0734|     1.4370|\n|USA, upper split    |                0.8727| 0.0867|     2.3935|\n\n\n:::\n:::\n\n\nThe remaining coefficients and thresholds complete the partial model.\nThresholds retain the cumulative-link convention $\\zeta_j-\\mathbf{x}_i^{\\mathsf T}\\boldsymbol\\beta$;\nthey receive no odds-ratio interpretation.\n\n\n::: {#tbl-ch12-partial-common .cell tbl-cap='Thresholds and common slopes in the partial proportional-odds fit.' tbl-colwidths='[45,18,18,19]'}\n::: {.cell-output-display}\n\n\n|Parameter               | Estimate|     SE|Odds ratio |\n|:-----------------------|--------:|------:|:----------|\n|Lower threshold         |   0.7178| 0.1040|---        |\n|Upper threshold         |   2.3609| 0.1146|---        |\n|Religion: yes versus no |   0.1491| 0.0762|1.1608     |\n|Degree: yes versus no   |   0.1414| 0.0666|1.1519     |\n|Age per year            |   0.0106| 0.0016|1.0107     |\n|Male versus female      |   0.1738| 0.0529|1.1899     |\n\n\n:::\n:::\n\n\nThe likelihood-ratio comparison with the common-slope model is nested:\nit frees three country contrasts at a second cut point. It gives\n$\\chi^2(3)=362.3463$, $p<.0001$, and reduces AIC from 10420.5924 to\n10064.2461. This is evidence against a common country slope in this\nspecified model. Other restrictions and the observational interpretation\nstill require judgment. Allowing country to vary by cut does not\nestablish that every other term satisfies proportional odds.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(po, cutfit)\nAIC(po, cutfit)\n```\n:::\n\n\n\nThe probability comparison below holds religion at \"yes\", university\ndegree at \"no\", age at 45 and gender at \"female\". The profiles define\nwhat is being compared. They are not national population averages.\nProbabilities are reported in the recorded order Too Little, About\nRight, Too Much; inspect the changed allocation across all three,\nrather than treating a threshold coefficient as a category probability.\n\n\n\n::: {#tbl-ch12-partial-probs .cell tbl-cap='Profile probabilities under common and country-specific cumulative slopes.' tbl-colwidths='[19,24,19,19,19]'}\n::: {.cell-output-display}\n\n\n|Country   |Model                | Too Little| About Right| Too Much|\n|:---------|:--------------------|----------:|-----------:|--------:|\n|Australia |Common slopes        |     0.5122|      0.3521|   0.1357|\n|Norway    |Common slopes        |     0.5917|      0.3062|   0.1021|\n|Sweden    |Common slopes        |     0.6575|      0.2634|   0.0791|\n|USA       |Common slopes        |     0.3614|      0.4130|   0.2255|\n|Australia |Cut-specific country |     0.5229|      0.3271|   0.1500|\n|Norway    |Cut-specific country |     0.5533|      0.4178|   0.0289|\n|Sweden    |Cut-specific country |     0.6310|      0.3472|   0.0218|\n|USA       |Cut-specific country |     0.4326|      0.2704|   0.2970|\n\n\n:::\n:::\n\n\nAn adjacent-category logit instead compares neighbouring categories;\na continuation-ratio logit describes successive transitions conditional\non reaching a stage. Those models answer differently structured\nquestions. Category order is the starting point, but the response\nprocess and the desired comparison determine which ordered model is\nuseful [@agresti2010].\n\n## Appendix B: Residuals and Two-process Explanations {.unnumbered}\n\n### Residuals and one influential record {.unnumbered .unlisted}\n\nA Pearson residual divides the observed-minus-fitted difference by the\nmodel's fitted standard deviation. A deviance residual gives a signed\ncontribution to discrepancy under the likelihood. Neither should be\nread as an ordinary Normal residual merely because it is called a\nresidual. Discreteness and changing means shape both displays.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residuals on each count model's own variance and likelihood scales.](chapter_12_files/figure-html/fig-ch12-residuals-1.png){#fig-ch12-residuals fig-pos='!ht' fig-alt='Four panels show Pearson and deviance residuals against fitted means for Poisson and negative-binomial fits. The pupil with 81 absent days is identified; the Poisson scale exaggerates the spread relative to its assumed variance.' width=595.2}\n:::\n:::\n\n\n\nThe largest absence count is 81 days. Removing that record asks a\nsensitivity question; it does not establish that the record is an error.\nRefitting without it should report the changed dispersion parameter,\nthe ethnicity interval and the continued need for a plausible variance\nmodel. Automatic deletion would conceal the very upper-tail behaviour\nthe model is meant to explain.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreduced <- subset(absence, Days < 81)\ncheck <- MASS::glm.nb(Days ~ Eth + Sex + Age + Lrn, data = reduced)\ncheck$theta\nexp(confint.default(check)[\"EthN\", ])\n```\n:::\n\n\n\n### When zero has a separate mechanism {.unnumbered .unlisted}\n\nA pupil who was eligible to miss school but happened to attend every day\nand a record that could never register an absence can both show zero.\nThe first belongs to the same count process as other pupils. The second\nsuggests a separate eligibility or recording process. Many zeros alone\ndo not distinguish them: an ordinary negative-binomial model can already\nproduce more zeros than a Poisson model with the same mean.\n\nA **hurdle model** separates whether the count crosses zero from its\npositive magnitude; its positive-count component is truncated at zero.\nA **zero-inflated model** mixes a structural-zero component with an\nordinary count component that can itself produce zero [@mullahy1986;\n@lambert1992]. These are different accounts of how records arise. An\nextra zero parameter should be motivated by that account and checked\nagainst its fitted consequences.\n\nComparisons with an ordinary count model can put mixture probabilities\non a boundary and can leave additional parameters unidentified under\nthe null. The usual interior chi-square likelihood-ratio reference is\ntherefore not automatic, nor is one universal half-and-half mixture\nformula adequate for every such comparison. Specialist model-specific\nmethods or a carefully designed parametric bootstrap are needed before\nattaching a calibrated p-value.\n\nFor further practice, explain why the quasi-Poisson fit cannot supply the\nband-probability table, and carry out the 81-day sensitivity comparison.\nIn each case, distinguish what changes numerically from what still needs\na study-design or measurement justification.\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_12_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}