{
  "hash": "134b8126c19de38a51cf0c4e6a85d9cd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Binary Logistic Regression\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    documentclass: scrartcl\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    latex-auto-install: false\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{16\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nA yes-or-no outcome has a mean that is a probability. This chapter builds\na model for that probability, connects it to odds and log-odds, and explains\nwhy the same odds ratio can imply very different probability differences.\nA known-process certification example makes the model's behavior visible;\na study of student volunteering supplies the empirical analysis. Maximum\nlikelihood, model comparisons and diagnostic displays lead to a report\nwhose event, scale, uncertainty and scope are explicit. The appendices\nextend numerical fitting and simulation without supplying a prerequisite\nfor the main analysis.\n:::\n\nCowles and Davis recorded personality scores and volunteering for an\nexperiment among 1,421 introductory psychology students [@cowles1987].\nThere were 597 volunteers and 824 non-volunteers. The question is how the\nprobability of volunteering differs across extraversion scores, and how\nthat comparison changes after allowing for recorded sex and neuroticism.\nA department interested in recruitment needs an answer on a usable scale:\na detectable association need not separate future volunteers from other\nstudents well enough to guide a decision.\n\nThe distributed records are `carData::Cowles` [@carData2022; @fox2019].\nThey contain one row per student, with no missing values in these fields.\nThe extract supplies no probability-sampling or classroom-clustering\ninformation. The fitted comparisons therefore describe these recorded\nstudents under a working independent-row model; generalization and causal\ninterpretation require additional design information.\n\n\n\nDisplayed results are rounded to four decimal places, with trailing zeros\ndropped unless they align a comparison. Calculations using different\nrounding or software settings may differ slightly.\n\n## A Binary Outcome and Its Probability {#ch11-binary}\n\n### Define the event and the comparison {#ch11-event}\n\nA binary outcome has two categories. A binary model treats one as the\n**event**, coded 1, and the other as the **non-event**, coded 0. Naming\nthe event determines what every coefficient and predicted probability\nmeans. Here the event is volunteering, and the **prevalence**, the\nproportion of records that are events, is .4201. The recorded non-event\nmeans only that the student did not volunteer; it does not tell us whether\nthe student declined, was unavailable, or never received the invitation.\nThose distinctions concern measurement, before any statistical fit.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd0 <- carData::Cowles\ndat <- d0\ndat$event <- as.integer(dat$volunteer == \"yes\")\ntable(dat$sex, dat$event)\nmean(dat$event)\n```\n:::\n\n\n\n\n| Recorded sex | Volunteers | Non-volunteers | Proportion volunteering | Odds of volunteering |\n|:--|--:|--:|--:|--:|\n| Female | 349 | 431 | .4474 | .8097 |\n| Male | 248 | 393 | .3869 | .6310 |\n\n: One observed table supports more than one scale of comparison. {#tbl-ch11-crude tbl-colwidths=\"[22,16,18,22,22]\"}\n\nThe female-minus-male probability difference is .0605; the ratio of their\nodds is 1.2832. Both describe the same table, but they answer different\nquestions. The first compares proportions directly. The second compares\nevents relative to non-events in each group. Neither adjusts for the two\npersonality scores or identifies a consequence of changing a person's sex.\n\nWrite $\\pi(x)=P(Y=1\\mid X=x)$. Three possible comparisons of units\none predictor point apart are\n\n$$\n\\pi(x+1)-\\pi(x),\\qquad\n\\frac{\\pi(x+1)}{\\pi(x)},\\qquad\n\\frac{\\pi(x+1)/\\{1-\\pi(x+1)\\}}{\\pi(x)/\\{1-\\pi(x)\\}}.\n$$\n\nThey are the probability difference, risk ratio and odds ratio. A model\nwith a constant logistic slope holds the third constant across $x$;\nthe other two generally vary. An estimand for a binary outcome must name\nits scale as well as the units and comparison.\n\n### A probability model and its link {#ch11-glm}\n\nApplying least squares to a 0/1 outcome gives a **linear probability\nmodel**. Its slope is already on a probability-difference scale, which\ncan be useful over a limited range. Its weakness as a general probability\nmodel is visible before fitting: an unrestricted line can leave $[0,1]$,\nand one fixed probability difference cannot remain plausible near both\nboundaries. Moreover a binary outcome has variance $\\pi(1-\\pi)$, so its\nconditional variance changes with its mean. Ordinary constant-variance\nstandard errors are inappropriate; robust uncertainty can address that\nvariance calculation but cannot keep a straight mean function in range.\nNormal-error small-sample $t$ theory does not apply to two-valued errors.\n\nThe logistic alternative declares the outcome model and mean function\nseparately:\n\n$$\nY_i\\mid \\mathbf{x}_i\\sim\\operatorname{Bernoulli}(\\pi_i),\\quad\nE(Y_i\\mid \\mathbf{x}_i)=\\pi_i,\\quad\n\\operatorname{Var}(Y_i\\mid \\mathbf{x}_i)=\\pi_i(1-\\pi_i),\n$$\n\n$$\n\\eta_i=\\beta_0+\\sum_{j=1}^{p}\\beta_jx_{ij},\\qquad\n\\operatorname{logit}(\\pi_i)=\\log\\frac{\\pi_i}{1-\\pi_i}=\\eta_i,\n\\qquad \\pi_i=\\frac{1}{1+e^{-\\eta_i}}.\n$$\n\nHere $\\eta_i$ is the **linear predictor**, an additive combination of\npredictors. The **link** connects the conditional mean to that predictor;\nit transforms the probability, not the observed 0 or 1. The inverse logit\nturns any finite $\\eta_i$ into a probability strictly between 0 and 1.\nIt passes through .5 at $\\eta_i=0$ and is steepest there. The model is\nlinear in log-odds and curved in probability. It has no separate residual\nvariance parameter because the Bernoulli mean determines its variance.\n\nA response distribution, a linear predictor and a link form the generalized\nlinear model (GLM) framework [@nelder1972]. Changing the response and link\nextends this framework to other outcomes, while retaining the distinction\nbetween model scale and reporting scale.\n\n\n| Component | Chapter 11 | Chapter 12, nominal or ordered | Chapter 12, counts |\n|:--|:--|:--|:--|\n| Outcome | Binary event | Nominal or ordered category | Count, with an exposure where needed |\n| Response distribution | Bernoulli or binomial | Multinomial | Poisson or negative binomial |\n| Link | Logit | Generalized or cumulative logit | Log |\n| Exponentiated coefficient | Odds ratio | Relative-risk or cumulative odds ratio | Rate ratio |\n\n: Only the response distribution and the link change. {#tbl-ch11-glm-components tbl-colwidths=\"[24,24,28,24]\"}\n\n\n\n### Conditions and the scope of interpretation {#ch11-conditions}\n\n| Condition | What it supplies or limits |\n|:--|:--|\n| AS1: a Bernoulli outcome with a well-defined event | The meaning of $\\pi_i$ and its variance; coding must represent the question |\n| AS2: the log-odds is linear in the entered terms | The conditional comparison represented by each coefficient; curves or products require explicit terms |\n| AS3: independent rows given the predictors | The likelihood product and its usual standard errors; repeated and clustered rows need dependence-aware methods |\n| AS4: predictors are measured and coded as intended | The interpretation of a comparison; measurement error can change the relationship being estimated |\n| AS5: supported profiles, overlap and no separating predictor combination | A defensible comparison and a finite maximum-likelihood estimate |\n| AS6: no perfect linear dependence among predictor columns | Unique coefficient coordinates; near dependence can make estimates imprecise |\n\n: Conditions of the working logistic model. {#tbl-ch11-conditions tbl-colwidths=\"[44,56]\"}\n\nThere is no homoskedasticity or Normal-residual condition. The mean model\nis checked on the logit scale, and the study design supplies information\nabout independence. Observing both events and non-events in the dataset\nis necessary but does not rule out a combination of predictors that\nseparates them perfectly. Nor must both outcomes appear at every exact\ncontinuous predictor value. Support means that the proposed profiles and\ncontrasts are represented well enough to make their interpretation credible.\n\nA coefficient compares units agreeing on the other included predictors.\nIt becomes a causal effect only with an adequate design and identification\nargument. A further complication is **noncollapsibility**: a conditional\nodds ratio can differ from a marginal odds ratio even without confounding,\nbecause averaging nonlinear probabilities does not preserve an odds ratio\n[@agresti2018]. Movement after adjustment alone therefore does not diagnose\nconfounding. A standardized probability comparison names an averaging\npopulation explicitly and can make the substantive magnitude clearer.\n\n## Three Scales: Probability, Odds, and Log-Odds {#ch11-scales}\n\n### Translate one quantity three ways {#ch11-conversions}\n\nA probability compares events with all units. Odds compare events with\nnon-events. Log-odds put that positive ratio on an additive, unbounded scale:\n\n$$\n\\text{odds}=\\frac{\\pi}{1-\\pi},\\qquad\n\\pi=\\frac{\\text{odds}}{1+\\text{odds}},\\qquad\n\\text{log-odds}=\\log\\frac{\\pi}{1-\\pi}.\n$$\n\nAt probability .5, events and non-events are equally common: odds are 1\nand log-odds are 0. At probability .75, there are three events per\nnon-event. The three scales contain the same information; they organize\ncomparisons differently.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- c(.05, .20, .42, .50, .75, .90)\ncbind(probability = p, odds = p / (1 - p), log_odds = qlogis(p))\n```\n:::\n\n\n\n| Probability | Odds | Log-odds |\n|--:|--:|--:|\n| .05 | .0526 | $-2.9444$ |\n| .20 | .2500 | $-1.3863$ |\n| .42 | .7241 | $-.3228$ |\n| .50 | 1.0000 | .0000 |\n| .75 | 3.0000 | 1.0986 |\n| .90 | 9.0000 | 2.1972 |\n\n: Probability, odds, and log-odds for selected probabilities; the odds scale is multiplicative around 1 and the log-odds scale additive around 0. {#tbl-ch11-scales tbl-colwidths=\"[34,33,33]\"}\n\n\n\nOdds exceed probabilities for $0<\\pi<1$, with a widening gap toward\n1. Complementary probabilities have log-odds equal in magnitude and\nopposite in sign. These features explain why an event reversal inverts\nan odds ratio, and why odds and risk ratios agree approximately only\nwhen both compared probabilities are small.\n\n### Equal logit steps, unequal probability steps {#ch11-curve}\n\nThe inverse-logit function is the cumulative distribution function of a\nstandard logistic variable, evaluated at $\\eta$. This mathematical\nconnection offers a threshold-crossing intuition without changing the\nobserved Bernoulli outcome model. A one-unit step in $\\eta$ has the same\nsize everywhere on the logit scale; its probability consequence depends\non the starting point.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplogis(c(-3, -2, 0, 1))\ndiff(plogis(c(-3, -2)))\ndiff(plogis(c(0, 1)))\n```\n:::\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Equal steps on the linear-predictor scale give unequal probability differences.](chapter_11_files/figure-html/fig-ch11-logit-curves-1.png){#fig-ch11-logit-curves fig-pos='!ht' fig-alt='An S-shaped inverse-logit curve rises through probability one half at zero. A one-unit step near the centre raises probability by .2311, compared with .0718 in the left tail.' width=595.2}\n:::\n:::\n\n\n\n\nMoving from $-3$ to $-2$ raises probability by .0718; moving from 0\nto 1 raises it by .2311, 3.2191 times as much. A statement that one more\nunit adds a fixed number of percentage points is therefore incomplete\nfor a logistic model. Coefficients and their uncertainty are convenient\non the logit scale, multiplicative comparisons on the odds scale, and\nmost practical decisions on the probability scale.\n\n## Fit by Maximum Likelihood {#ch11-likelihood}\n\n### From one probability to a coefficient vector {#ch11-loglik}\n\nFor a common probability, 32 successes in 50 fixed trials produce a\nbinomial likelihood maximized at .64. Here each student's probability\ncan differ through the predictor values, but the principle is the same:\nhold the observed data fixed and ask which parameter values make them\nmost probable.\n\nA small example makes the likelihood's job concrete. Three invented\nobservations have predictor values 0, 1 and 2 and outcomes 1, 0 and 1.\nCompare two proposed models, A with logit $-1+x$ and B with logit $-2+x$.\nThe likelihood uses the probability of what happened: $p$ for an event\nand $1-p$ for a non-event.\n\n\\Needspace{10\\baselineskip}\n\n| $x$ | $y$ | A: event | A: observed | B: event | B: observed |\n|--:|--:|--:|--:|--:|--:|\n| 0 | 1 | .2689 | .2689 | .1192 | .1192 |\n| 1 | 0 | .5000 | .5000 | .2689 | .7311 |\n| 2 | 1 | .7311 | .7311 | .5000 | .5000 |\n\n: Each observed outcome contributes its own probability. {#tbl-ch11-small-likelihood tbl-colwidths=\"[8,8,21,21,21,21]\"}\n\nPredict which model has the larger product before calculating. Model A\nhelps both events but makes the non-event less probable. Its total\nlog-likelihood is nevertheless larger: $-2.3197$ against $-3.1333$.\nImproving total fit need not improve every observation. Neither candidate\nhas yet been claimed to maximize likelihood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(0, 1, 2); y <- c(1, 0, 1)\nsum(dbinom(y, 1, plogis(-1 + x), log = TRUE))\nsum(dbinom(y, 1, plogis(-2 + x), log = TRUE))\n```\n:::\n\n\nWith independent rows,\n\n$$\nL(\\boldsymbol\\beta)=\\prod_{i=1}^{n}\\pi_i^{y_i}(1-\\pi_i)^{1-y_i},\\qquad\n\\ell(\\boldsymbol\\beta)=\\sum_{i=1}^{n}\\{y_i\\log\\pi_i+(1-y_i)\\log(1-\\pi_i)\\},\n$$\n\nwhere $\\pi_i=\\operatorname{logit}^{-1}(\\mathbf{x}_i^{\\mathsf T}\\boldsymbol\\beta)$ and\n$\\mathbf{x}_i$ includes the intercept entry 1. Each observed event contributes\nits fitted probability and each non-event its fitted complement. Larger\nlog-likelihood means better agreement for these observations. The\nlikelihood is a function of parameters with the data fixed, not a\nprobability distribution over those parameters.\n\n**Maximum likelihood** chooses the coefficient vector maximizing this\nfunction. Its score equations are\n\n$$\n\\frac{\\partial\\ell}{\\partial\\boldsymbol\\beta}\n=\\sum_i \\mathbf{x}_i(y_i-\\pi_i)=0.\n$$\n\nThe equation for the intercept says that the residuals sum to zero:\nfitted probabilities total the observed event count. Aggregate calibration\nis therefore built into a converged, unpenalized logistic fit with an\nintercept; it cannot by itself establish a good model. The remaining\nequations need numerical solution because the probabilities depend\nnonlinearly on all coefficients.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- glm(event ~ sex + neuroticism + extraversion,\n  data = dat, family = binomial(link = \"logit\"))\nlogLik(m2)\nsum(fitted(m2))\n```\n:::\n\n\n\n\nThe adjusted volunteering fit has log-likelihood $-953.0306$.\nDirectly summing its Bernoulli contributions gives the same value, and\nits fitted probabilities sum to 597, the observed number of volunteers.\nAppendix A connects this numerical fitting to scalar boundary cases,\nmultiple starting values and local curvature.\n\n### Curvature, uncertainty and convergence {#ch11-irls}\n\n`glm()` uses **iteratively reweighted least squares** (IRLS): it forms\na working linear regression with adjusted outcomes and weights\n$\\widehat\\pi_i(1-\\widehat\\pi_i)$, updates the coefficients, and repeats.\nFor a full-rank design without separation the logistic log-likelihood has\na unique finite maximum. A stopping flag says the algorithm met its\nnumerical criterion; the data and model still require scrutiny. This fit\nreports convergence after four iterations.\n\nBefore reading a covariance matrix, consider what the curve is measuring.\nIn an invented two-group study, ten observations have $x=-1$ and ten have\n$x=1$. Use the one-coefficient model $\\operatorname{logit}(p)=b x$, whose\nintercept is fixed at zero. If the groups contain 2 and 8 events, the\nlikelihood peaks at $b=\\log4=1.3863$: moving either way makes the observed\npattern less probable. If instead they contain 0 and 10 events, increasing\n$b$ keeps improving the likelihood. Every finite curve leaves some chance\nof a contrary outcome, so the maximum is approached only as $b$ diverges.\nThis second pattern is **complete separation**.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Changing the event counts changes whether the likelihood has a finite maximum.](chapter_11_files/figure-html/fig-ch11-likelihood-shapes-1.png){#fig-ch11-likelihood-shapes fig-pos='!ht' fig-alt='For ten observations at each of x minus one and plus one, two and eight events give a curved peak at b 1.3863. Zero and ten events give a curve increasing toward zero without a finite peak.' width=595.2}\n:::\n:::\n\n\nThe dashed zero line represents the best attainable log-likelihood in the\nfinite case and the limiting value in the separated case. A flat tail is\nnot evidence for a small coefficient; here it shows why a finite maximum\nis absent. Section 6.3 returns to this issue in the volunteering records.\n\nNear the maximum, curvature describes how quickly fit deteriorates as\na coefficient moves. Flat curvature allows many neighboring values and\ntherefore larger standard errors. With design matrix $\\mathbf X$ and diagonal\nweight matrix $\\mathbf W$, the model-based covariance is\n\n$$\n\\widehat{\\mathbf V}=(\\mathbf{X}^{\\mathsf T}\\mathbf{W}\\mathbf{X})^{-1},\\qquad\n\\mathbf W=\\operatorname{diag}\\{\\widehat\\pi_i(1-\\widehat\\pi_i)\\},\\qquad\nSE(\\widehat\\beta_j)=\\sqrt{\\widehat{\\mathbf V}_{jj}}.\n$$\n\nA weight is largest at .5 and small near either boundary. Precision also\ndepends on predictor spread and overlap, so neither total sample size nor\nevent count alone determines it. Independent-row standard errors cannot\nrepair dependence or measurement error.\n\nA **Wald interval** is $\\widehat\\beta_j\\pm1.96SE$ for 95% coverage\nunder the large-sample Normal approximation, then exponentiated if the\nreported quantity is an odds ratio. A **profile-likelihood interval**\ninstead keeps values not rejected by an appropriate likelihood-ratio\ncomparison while optimizing the other coefficients. It can reflect\nasymmetry the Wald interval misses. The two approaches here differ by at\nmost .0015 on the odds-ratio scale; they can diverge markedly in small\nsamples or near separation [@hosmer2013].\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2$converged\nm2$iter\nexp(confint.default(m2))\nexp(confint(m2))\n```\n:::\n\n\n\n\nA declared linear combination $C=\\mathbf{c}^{\\mathsf T}\\boldsymbol\\beta$ has estimated\nvariance $\\mathbf{c}^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf c$. The off-diagonal covariance terms matter when\ncombining coefficients, including for a predicted logit or a conditional\nslope. The familiar contrast rule remains; its covariance now comes from\nlikelihood curvature.\n\n### A known process: certification success {#ch11-simulation}\n\nConsider an invented certification course. Passing is the event; study\nhours span 0 to 20, and tutoring is an indicator with probability .35,\nindependent of hours in this constructed process. Declare\n\n$$\n\\operatorname{logit}\\{P(\\text{pass})\\}=-2.2+.3\\,\\text{hours}+.6\\,\\text{tutor}.\n$$\n\nAt seed 1010, 1,500 students give 961 passes. Fitting the declared model\nreturns $-2.2271$, .3024 and .5264, with all three generating values\ninside their Wald intervals. This is recovery under a known process,\nnot evidence that an empirical study follows that process.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1010)\nhours <- round(runif(1500, 0, 20), 1)\ntutor <- rbinom(1500, 1, .35)\npass <- rbinom(1500, 1, plogis(-2.2 + .30 * hours + .60 * tutor))\nglm(pass ~ hours + tutor, family = binomial)\n```\n:::\n\n\n\n| Study hours | Probability | Probability at one more hour | Probability difference | Odds ratio |\n|--:|--:|--:|--:|--:|\n| 2 | .1680 | .2142 | .0462 | 1.3499 |\n| 7 | .4750 | .5498 | .0748 | 1.3499 |\n| 12 | .8022 | .8455 | .0434 | 1.3499 |\n| 17 | .9478 | .9608 | .0130 | 1.3499 |\n\n: One constant odds ratio, four different probability differences, in the known generating process. {#tbl-ch11-sim-nonconstant tbl-colwidths=\"[18,20,26,22,14]\"}\n\n\n\nFor students without tutoring, the declared one-hour odds ratio is\n$e^{.3}=1.3499$ everywhere, yet the probability difference is .0748\nat seven hours and .013 at seventeen. The starting probability makes\nthe practical benefit different even before sampling variation enters.\nThe estimated hours odds ratio, 1.3531, closely recovers that truth.\n\nRepeating the declared generation at seed 1012 for 500 samples of 300\ngives an hours coefficient averaging .3068 with SD .0359 and empirical\nWald coverage .948. The Monte Carlo SE of that coverage is .0099, so\nthis run is compatible with .95 coverage. Finite-sample logistic estimates\ncan be biased away from zero; simulation separates that tendency from\nvariation in one sample. Tutoring's coefficient varies much more here\n(SD .3309): the two predictors have different scales and information,\nso their coefficient SDs should not be read as a general comparison of\nbinary and continuous predictors.\n\nThe same generated data also let us compare mean functions honestly.\nThe fitted linear probability model gives .0492 per hour but produces\n193 fitted values above 1. Its fitted range is .1253 to 1.1861.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Two mean functions fitted to the same invented certification records, for students without tutoring.](chapter_11_files/figure-html/fig-ch11-sim-lpm-1.png){#fig-ch11-sim-lpm fig-pos='!ht' fig-alt='A logistic curve levels off below probability one, while the fitted straight line crosses one before twenty study hours.' width=595.2}\n:::\n:::\n\n\n\n\nThis example deliberately uses a logistic truth and approaches the\nboundaries. It shows why an unbounded line can fail; it does not show\nthat logistic regression must be right for every dataset. The volunteering\nanalysis below supplies the complementary case in which both mean\nfunctions are numerically close over the observed range.\n\n## Read Coefficients on Interpretable Scales {#ch11-reading}\n\n### What an odds ratio compares {#ch11-odds-ratio}\n\nIf a predictor enters additively, increasing it by one unit while holding\nthe others fixed changes the log-odds by $\\beta_j$:\n\n$$\n\\operatorname{logit}\\{\\pi(x_j+1)\\}-\\operatorname{logit}\\{\\pi(x_j)\\}=\\beta_j,\n\\qquad\n\\frac{\\pi(x_j+1)/\\{1-\\pi(x_j+1)\\}}{\\pi(x_j)/\\{1-\\pi(x_j)\\}}=e^{\\beta_j}.\n$$\n\nFirst fit extraversion alone. The coefficient is .0656 (SE .0141), giving\nan odds ratio of 1.0678 and a 95% interval [1.0386, 1.0978]. Each extra\nextraversion point is associated with 1.0678 times the odds of volunteering\nrather than not volunteering. Five points compound multiplicatively to\n1.3883, rather than adding five copies of the odds ratio.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- glm(event ~ extraversion, data = dat, family = binomial)\nexp(coef(m1))\nexp(confint.default(m1))\n```\n:::\n\n\n\n\nFour qualifications make this a complete comparison: the predictor's\n**units**, any factor's **reference category**, the **event**, and the\n**adjustment set**. Changing a unit changes the contrast; changing the\nevent or reference changes its direction; adding controls changes the\nconditional comparison. The intercept $-1.1394$ describes extraversion\nzero, outside the observed 2--23 range, so it is a mathematical anchor\nrather than a supported student profile.\n\nAn odds ratio is not a risk ratio. At a prevalence near .42, saying\n\"1.5 times the odds\" as \"50 percent more likely\" can substantially\nexaggerate a probability comparison. The approximation is useful only\nwhen the event probabilities in both groups are small.\n\nThe local slope on the probability scale is\n\n$$\n\\frac{\\partial\\pi}{\\partial x_j}=\\beta_j\\pi(1-\\pi).\n$$\n\nIts absolute value is bounded by $|\\beta_j|/4$, attained at .5.\nThis also bounds the magnitude of a one-unit finite probability difference\nwhen the logit is additive in that predictor. The derivative is a local\nrate, not exactly the difference between two profiles one full unit apart;\ncompute both fitted probabilities when that finite contrast is wanted.\n\n### Reverse the event, preserve the underlying probabilities {#ch11-reversal}\n\nBefore looking at new output, predict the result of coding non-volunteering\nas 1. The probability must become $1-\\widehat\\pi_i$, the log-odds must\nchange sign, and the odds ratio must become its reciprocal. The simple\nextraversion coefficient becomes $-.0656$ and its odds ratio .9365.\nTheir signed $z$ statistics reverse too. Standard errors, two-sided\np-values, deviance and McFadden's pseudo $R^2$ stay the same. After\ntranslating back to the original event, every student still has the same\nfitted probability of volunteering.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat$no <- 1 - dat$event\nrev <- glm(no ~ extraversion, data = dat, family = binomial)\nexp(coef(rev))\nmax(abs(fitted(rev) + fitted(m1) - 1))\n```\n:::\n\n\n\n\nChanging a predictor factor's reference instead changes coefficient\ncoordinates while retaining the same outcome event and fitted\nprobabilities. For a binary factor the focal comparison reverses, but\nits intercept moves and other coefficient changes depend on the model's\nterms. These recodings change what a printed coefficient names, not the\nfitted probability surface.\n\n### Adjusted results and probabilities at supported profiles {#ch11-multiple}\n\nThe multiple model is\n\n$$\n\\log\\frac{\\pi_i}{1-\\pi_i}=\\beta_0+\\beta_1\\,\\mathrm{male}_i+\\beta_2N_i+\\beta_3E_i,\n$$\n\nwhere $N$ and $E$ are the recorded neuroticism and extraversion scores.\nFemale is the reference sex category. The fitted table attaches each\ncoefficient to that event, coding and adjustment set.\n\n\n| Term | Estimate (log-odds) | SE | $z$ | Odds ratio | OR 95% lower | OR 95% upper |\n|:--|--:|--:|--:|--:|--:|--:|\n| Intercept | $-1.1165$ | .2491 | $-4.4829$ | .3274 | .2010 | .5335 |\n| Sex: male versus female | $-.2352$ | .1112 | $-2.1151$ | .7904 | .6357 | .9829 |\n| Neuroticism | .0064 | .0114 | .5602 | 1.0064 | .9842 | 1.0290 |\n| Extraversion | .0663 | .0143 | 4.6512 | 1.0686 | 1.0391 | 1.0989 |\n\n: Multiple logistic regression of volunteering on sex, neuroticism, and extraversion; Wald 95% intervals, female as the reference category, event coded as volunteering. {#tbl-ch11-fit2 tbl-colwidths=\"[28,16,10,12,12,11,11]\"}\n\n\n\nAmong students of the same recorded sex and neuroticism, an extra\nextraversion point is associated with an odds ratio of 1.0686, close to\nthe unadjusted 1.0678. Male students have .7904 times the odds of female\nstudents of the same personality scores. Neuroticism has no detected\nadjusted association in this additive model ($p=.5754$), but its interval\nadmits odds ratios from .9842 to 1.0290 per point; a large p-value does\nnot prove no relationship.\n\nChoose profiles before interpreting their estimates: a female student at\nneuroticism 11, its median, and at extraversion 10, 13 or 15, its quartiles.\nThese values sit within the observed support. Prediction first gives the\nlogit and its SE; transform the two confidence limits to probability.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid <- data.frame(sex = \"female\", neuroticism = 11,\n  extraversion = c(10, 13, 15))\npred <- predict(m2, grid, type = \"link\", se.fit = TRUE)\nplogis(cbind(pred$fit - 1.96 * pred$se.fit,\n  pred$fit, pred$fit + 1.96 * pred$se.fit))\n```\n:::\n\n\n\n| Extraversion | Fitted log-odds | SE (log-odds) | Fitted probability | 95% lower | 95% upper |\n|--:|--:|--:|--:|--:|--:|\n| 10 | $-.3833$ | .0830 | .4053 | .3668 | .4451 |\n| 13 | $-.1843$ | .0742 | .4541 | .4183 | .4903 |\n| 15 | $-.0516$ | .0813 | .4871 | .4474 | .5269 |\n\n: Fitted probability of volunteering for a female student at the median neuroticism score, at the quartiles of extraversion, with intervals built on the log-odds scale and transformed. {#tbl-ch11-predictions tbl-colwidths=\"[16,18,18,20,14,14]\"}\n\n\n\nThe probability rises from .4053 to .4871 across the middle half of\nextraversion, a difference of .0818. Its interval is asymmetric because\nit is transformed from the logit scale. This is uncertainty about a\nconditional probability, not a prediction interval for an individual\nstudent: the next student's outcome remains either 0 or 1. Comparing two\nseparate intervals is also not a test of their difference; that contrast\nuses their joint covariance.\n\n### Profile and average probability comparisons {#ch11-average}\n\nA **case-specific comparison** fixes the other predictor values and\ncompares fitted probabilities at two profiles. An **averaged comparison**\ncomputes the contrast for each recorded student's other predictor values\nand then averages it. This makes the averaging population explicit rather\nthan treating one artificial \"average student\" as representative.\n\n\n\n\n\n\n\nAveraging is a substantive choice even when the model is already fixed.\nConsider the invented model $p(x,u)=\\operatorname{logit}^{-1}(x+u)$ and\ncompare $u=1$ with $u=0$. One population has equal numbers at $x=-.5$\nand $.5$; another has equal numbers at $x=-4$ and 4. Both have mean zero.\nPredict which population has the larger average probability difference\nfrom the vertical gaps in @fig-ch11-averaging.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same probability model gives different average differences in two populations.](chapter_11_files/figure-html/fig-ch11-averaging-1.png){#fig-ch11-averaging fig-pos='H' fig-alt='Both panels show the same pair of logistic curves. Equal-weight profiles near zero have average difference .22; profiles at minus four and plus four have average .0204. Both sets have mean zero, where the difference is .2311.' width=595.2}\n:::\n:::\n\n\nThe central profiles give average difference .22 and the tail profiles\ngive .0204. In contrast, evaluating both at the common mean $x=0$ gives\n.2311. The coefficient of $u$ and its conditional odds ratio $e$ are\nidentical throughout. The average changes because the populations place\ndifferent weight on steep and flat portions of the same probability\ncurves. A profile at the average predictor is therefore not interchangeable\nwith an average over the actual profiles. These are model comparisons,\nnot causal effects supplied by the invented equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(-.5, .5)\nmean(plogis(x + 1) - plogis(x))\nx <- c(-4, 4)\nmean(plogis(x + 1) - plogis(x))\nplogis(1) - plogis(0)\n```\n:::\n\n\nReturn now to the recorded volunteering profiles.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplus <- dat\nplus$extraversion <- plus$extraversion + 1\nmean(predict(m2, plus, type = \"response\") - fitted(m2))\n```\n:::\n\n\nThe average one-point extraversion difference is .0159. The local\nmaximum bound is .0166, and an additive linear probability fit gives\n.0158. Here its fitted values remain within [.2261, .6188], near the\nmiddle of the logistic curve, so the two mean functions agree closely.\nThe familiar least-squares constant-variance uncertainty still needs\ncorrection, and a new predictor range can expose the line's boundaries.\nThe one-point standardization also moves the single student at score 23\nto 24, just outside the recorded range; that small extrapolation is part\nof this explicitly defined average, not evidence about students at 24.\n\nAssigning each observed profile first the female and then the male\nindicator gives an averaged male-minus-female probability difference of\n$-.0562$. This is about 5.6 percentage points, whereas the odds ratio\n.7904 describes odds about 21 percent lower. The distinction changes\nwhat a reader imagines about actual volunteering rates.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Adjusted volunteering probabilities at neuroticism 11, with pointwise Wald 95% bands and observed score support.](chapter_11_files/figure-html/fig-ch11-fitted-1.png){#fig-ch11-fitted fig-pos='!ht' fig-alt='Two gently rising curves overlap in uncertainty bands, with the female curve higher. Bands widen at sparse extremes; the rug is dense in the middle of the extraversion range.' width=595.2}\n:::\n:::\n\n\n\n\nThe two lines are parallel on the logit scale because the additive model\ncontains no product term. Their probability separation varies. Additivity\nbelongs to a named scale, a distinction that matters when we next allow\nconditional contrasts to differ.\n\n## Compare and Test {#ch11-compare}\n\n### Deviance and a declared model comparison {#ch11-deviance}\n\nThe **deviance** compares a fitted model with the saturated model that\nfits every observation exactly. For individual binary observations the\nsaturated log-likelihood is zero, so\n\n$$\nD=-2\\ell(\\widehat{\\boldsymbol\\beta}),\\qquad\nG^2=D_A-D_B\\ \\dot\\sim\\ \\chi^2_q\n\\quad\\text{for regular nested models }A\\subset B.\n$$\n\nHere $q$ counts the restrictions defining the smaller model. The\ncomparison requires the same rows and event, finite well-identified\nestimates, and an adequate large-sample approximation. The absolute\nungrouped binary deviance has no simple chi-square goodness-of-fit reading;\nits difference can test a declared nested comparison.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m0, m2, test = \"LRT\")\nsmall <- glm(event ~ sex + extraversion, data = dat, family = binomial)\nanova(small, m2, test = \"LRT\")\n```\n:::\n\n\n\n| Comparison | Added | df | $G^2$ | $p$ |\n|:--|:--|--:|--:|--:|\n| Intercept only versus full | Sex, neuroticism, extraversion | 3 | 27.4447 | $<.0001$ |\n| Without neuroticism versus full | Neuroticism | 1 | .3139 | .5753 |\n\n: Two declared likelihood-ratio comparisons on the same 1,421 rows and the same event. {#tbl-ch11-lrt tbl-colwidths=\"[36,30,10,12,12]\"}\n\n\n\nThe full block reduces deviance from 1933.5060 to 1906.0613. Its statistic\n27.4447 exceeds the 5% critical value 7.8147 on three df. This establishes\ninformation in the block under the model, not a separate association for\neach member. Removing neuroticism alone costs only .3139 on one df,\nwith $p=.5753$.\n\n### Wald tests and likelihood comparisons {#ch11-wald-lrt}\n\nA single-coefficient Wald test uses $z=\\widehat\\beta/SE$, or $z^2$\nwith a chi-square reference on one df. The likelihood-ratio test instead\ncompares the best fits allowed by two models. For neuroticism the two\nagree: $z=.5602$, $z^2=.3138$, $p=.5754$, against $G^2=.3139$,\n$p=.5753$. Close agreement is expected when the likelihood is nearly\nquadratic near its maximum. With strong asymmetry or unstable estimates,\nthe Wald approximation can be misleading. Separation below shows an\nextreme case in which its statistic shrinks despite a perfect pattern.\n\n### Criteria rank models; they do not certify them {#ch11-criteria}\n\nFor $k$ estimated coefficients and $n$ records,\n\n$$\nAIC=-2\\ell+2k,\\qquad BIC=-2\\ell+k\\log n,\\qquad\nR^2_{\\mathrm{McF}}=1-\\frac{\\ell}{\\ell_0}.\n$$\n\nThere is no separately estimated variance parameter in the logistic\nmodel. AIC and BIC penalize in-sample likelihood by model size; smaller\nvalues are preferred among models fitted to the same records and outcome\n[@akaike1974; @schwarz1978]. McFadden's pseudo $R^2$ compares with the\nintercept-only maximum $\\ell_0$. It is not a proportion of variance\nexplained and should not be read against linear-model $R^2$ benchmarks.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(m0, m1, m2)\nBIC(m0, m1, m2)\n1 - as.numeric(logLik(m2) / logLik(m0))\n```\n:::\n\n\n\n| Model | $k$ | Deviance | AIC | BIC | McFadden pseudo $R^2$ |\n|:--|--:|--:|--:|--:|--:|\n| Intercept only | 1 | 1933.5060 | 1935.5060 | 1940.7651 | .0000 |\n| Extraversion | 2 | 1911.4838 | 1915.4838 | 1926.0020 | .0114 |\n| Sex, neuroticism, extraversion | 4 | 1906.0613 | 1914.0613 | 1935.0977 | .0142 |\n\n: Model comparison for the volunteering analysis; both criteria are comparative and neither certifies adequacy. {#tbl-ch11-criteria tbl-colwidths=\"[34,8,16,14,14,14]\"}\n\n\n\nAIC prefers the adjusted model; BIC prefers extraversion alone. At\n$n=1421$, BIC charges $\\log n=7.2591$ per coefficient against AIC's\n2, explaining the difference. Neither criterion is a test or a held-out\nprediction score. The small McFadden value .0142 is compatible with a\ndetectable association and little ability to distinguish volunteers.\n\n### A product term changes a conditional contrast {#ch11-product}\n\nAllow the extraversion contrast to vary with neuroticism:\n\n$$\n\\operatorname{logit}(\\pi_i)=\\beta_0+\\beta_1\\mathrm{male}_i+\\beta_2N_i+\n\\beta_3E_i+\\beta_4N_iE_i,\\qquad\n\\frac{\\partial\\operatorname{logit}(\\pi)}{\\partial E}=\\beta_3+\\beta_4N.\n$$\n\nThe product coefficient is $-.0086$ (SE .0029). The nested likelihood\ncomparison gives $G^2(1)=8.6213$, $p=.0033$. The lower-order extraversion\ncoefficient .1668 is its contrast at neuroticism zero, not a summary\nfor every student. The additive model's undetected neuroticism term and\nthe detected product answer different questions, so hierarchical model\nconstruction retains both lower-order terms.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- glm(event ~ sex + neuroticism * extraversion,\n  data = dat, family = binomial)\nanova(m2, m3, test = \"LRT\")\n```\n:::\n\n\n\n| Neuroticism | Log-odds contrast | SE | Odds ratio | OR 95% lower | OR 95% upper | Students within one point |\n|--:|--:|--:|--:|--:|--:|--:|\n| 8 | .0984 | .0184 | 1.1034 | 1.0644 | 1.1438 | 276 |\n| 11 | .0727 | .0146 | 1.0755 | 1.0451 | 1.1067 | 302 |\n| 15 | .0385 | .0170 | 1.0393 | 1.0052 | 1.0746 | 242 |\n\n: Conditional extraversion odds ratios at the quartiles of neuroticism, each comparing students differing by one extraversion point at the stated neuroticism score. {#tbl-ch11-conditional tbl-colwidths=\"[13,18,11,14,15,15,14]\"}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same product-term fit on log-odds and probability scales, for female students.](chapter_11_files/figure-html/fig-ch11-interaction-1.png){#fig-ch11-interaction fig-pos='!ht' fig-alt='Three straight lines on the logit scale cross near extraversion thirteen and are steepest at neuroticism eight. Their probability curves have the same crossing but unequal changes across the range.' width=595.2}\n:::\n:::\n\n\n\n\nThe table evaluates $\\beta_3+\\beta_4N$ at supported quartiles, with\nSEs from $\\mathbf{c}^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf c$. At extraversion 13, the probabilities for\nneuroticism 8 and 15 are nearly equal (.4519 and .4512), but a one-point\nextraversion difference is .0245 at the former and .0096 at the latter.\nConversely, different probability differences can arise with a constant\nodds ratio simply because baseline probabilities differ. An interaction\nclaim therefore names its scale. Chapter 10 develops centering and\nprobing; the new issue here is the nonlinear transfer between scales.\n\n## Check Calibration, Fit, and Influence {#ch11-checks}\n\n### Form and observed support {#ch11-form}\n\nAn observed proportion at each extraversion score makes both the pattern\nand its support visible. An **empirical logit**\n$\\widetilde\\eta=\\log\\{(y+.5)/(n-y+.5)\\}$ adds half a count to keep\ngroups with zero or all events finite. It is a plotting device rather\nthan a replacement for the fitted Bernoulli likelihood.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(event ~ extraversion, data = dat, mean)\nanova(m2, mq, test = \"LRT\")\n```\n:::\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Observed volunteering by score: empirical proportions and logits, with point area showing the number of students.](chapter_11_files/figure-html/fig-ch11-proportions-1.png){#fig-ch11-proportions fig-pos='!ht' fig-alt='Most students lie in the middle scores, where proportions and empirical logits rise gently. Score twenty-two contains five volunteers and score twenty-three one non-volunteer; their extreme proportions have very little support.' width=595.2}\n:::\n:::\n\n\n\n\nScore 13 has 151 students. Score 22 has five, all volunteers; score 23\nhas one non-volunteer. Their extreme empirical logits, 2.3979 and\n$-1.0986$, deserve less weight than the densely populated middle.\nThe observed proportions need not increase at every score: sampling\nvariation around an increasing conditional mean remains.\n\nThe grouped pattern gives no compelling curvature, and adding squared\nextraversion gives $G^2(1)=1.4257$, $p=.2325$. This does not prove\nlinearity in the logit; it says this particular alternative is not clearly\ndistinguished by the available records. A one-predictor empirical-logit\ndisplay is also a marginal diagnostic, not a complete check of the\nadjusted model's functional form.\n\n### Residuals and influence {#ch11-residuals}\n\nRaw residuals are $y_i-\\widehat\\pi_i$. At a fitted probability they\ntake only $1-\\widehat\\pi_i$ or $-\\widehat\\pi_i$, so the raw plot has\ntwo lines rather than a Normal cloud. Pearson residuals divide by\n$\\sqrt{\\widehat\\pi_i(1-\\widehat\\pi_i)}$; signed deviance residuals\nhave squares summing to deviance. None is expected to be Normal.\n\nA **binned residual plot** instead groups nearby fitted probabilities\nand compares their average residuals with zero. The displayed pointwise\nbands, $\\pm2\\sqrt{\\bar\\pi(1-\\bar\\pi)/n_{\\mathrm{bin}}}$, are a rough\nvisual reference for groups with similar fitted probabilities; they are\nnot a simultaneous test and ignore parameter-estimation effects.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Mean residuals in twenty fitted-probability bins, with approximate pointwise two-SE reference bands.](chapter_11_files/figure-html/fig-ch11-binned-1.png){#fig-ch11-binned fig-pos='!ht' fig-alt='Twenty mean residuals fluctuate on both sides of zero without an evident trend. One lies outside the approximate two-standard-error bands.' width=595.2}\n:::\n:::\n\n\n\n\nOne bin falls outside its reference band. That is compatible with chance\nvariation and does not certify the form. The largest Cook's distance is\n.0051. Removing that row moves the extraversion coefficient from .0663\nto .0679, with a maximum coefficient change of .0304 elsewhere. A deletion\nrefit asks whether a conclusion depends on one observation; it supplies\nno automatic reason to discard it. The principal analysis retains the row.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwhich.max(cooks.distance(m2))\ncoef(m2)\ncoef(md)\n```\n:::\n\n\n\n\n### Separation: a strong pattern with no finite estimate {#ch11-separation}\n\nA sparse category supplies little information. **Complete separation**\nis more specific: a predictor combination places every event on one side\nand every non-event on the other. With **quasi-complete separation**, some\nobservations lie on the separating boundary. In these circumstances one\nor more coefficients can increase in magnitude without reaching a finite\nlikelihood maximum [@albert1984]. A number printed by software can be\nmerely the point at which iteration stopped.\n\nMake this failure visible with a deliberately constructed subset, not a\nsubstantive analysis. Retain non-volunteers scoring at most 8 and\nvolunteers scoring at least 17, then sample 60 eligible rows at seed\n1011. There is a gap between the two outcomes by construction.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm(event ~ extraversion, data = sep, family = binomial)\n```\n:::\n\n\n\n\n| Output feature | Constructed separated fit | What it signals here |\n|:--|--:|:--|\n| Extraversion coefficient | 5.5928 | An iteration moving toward an infinite limit |\n| Standard error | 8014.9006 | Nearly flat local information in the escaping direction |\n| Wald $z$ and two-sided $p$ | .0007; .9994 | A failed Wald approximation, not absence of the observed pattern |\n| Residual deviance | $5.642\\times10^{-10}$ | Almost perfect fit on the selected rows |\n| Fitted probabilities | about $2.22\\times10^{-16}$ and 1 | Numerical boundary values |\n| Iterations | 25 | Far more than the four needed by the regular adjusted fit |\n\n: Symptoms of this complete-separation example, read together. {#tbl-ch11-separation tbl-colwidths=\"[26,25,49]\"}\n\nThe selected rows reproduce the separated pattern in\n@fig-ch11-likelihood-shapes: increasing the slope can approach perfect\nclassification without a finite likelihood peak.\n\nThe tiny Wald statistic is particularly instructive: it does not negate\nthe perfect ordering. The coefficient and SE have both become enormous,\nand the usual local approximation is unusable. These are characteristic\nsymptoms in this example, not a checklist every separated model must\nsatisfy. Quasi-complete separation need not make the whole deviance zero,\nand a warning is neither necessary nor sufficient for diagnosis.\n\nThe full data offer an unwarned example. If scores 22 and 23 are separate\nfactor levels, one contains five events and the other one non-event.\nTheir coefficients become 15.2161 (SE 394.7749) and $-13.916$\n(SE 882.7434). Combining the substantively adjacent upper bands as\n18+ gives 130 students with 71 events and a finite coefficient .8352\n(SE .2222). That demonstrates what the sparse bands were doing; such a\nmerge still requires a meaningful category definition, not merely a\nwish for smaller standard errors.\n\n\n| Option | What it does | When it is appropriate |\n|:--|:--|:--|\n| Collapse categories | Merges a sparse level with a substantively adjacent one | The merged levels are defensibly similar on subject-matter grounds |\n| Drop the term | Removes the separating predictor | The predictor is not central to the question and its removal is reported |\n| Report the boundary honestly | States the direction, notes that the magnitude is not identified, and reports any unbounded profile limit | The separating pattern is itself the finding |\n| Penalized likelihood | Adds a penalty giving finite estimates with reduced small-sample bias, as in Firth's method | A finite estimate is needed and the penalty is disclosed |\n| Collect more data | Fills the empty cell | The design permits it |\n\n: Options when a logistic model shows separation. {#tbl-ch11-separation-options tbl-colwidths=\"[24,40,36]\"}\n\n\n\nFirth's penalized likelihood is one way to obtain finite estimates with\nreduced small-sample bias [@firth1993]. It is a different estimation rule,\nwhose penalty must be stated. It does not make the original infinite\nmaximum-likelihood estimate finite. More generally, a finite estimate\nshould be interpreted only where the data support the intended comparison.\n\n### Calibration and discrimination {#ch11-calibration}\n\n**Calibration** asks whether assigned probabilities agree with observed\nevent frequencies: among students assigned about .4, do roughly 40%\nvolunteer? **Discrimination** asks whether probabilities tend to rank\nvolunteers above non-volunteers. They answer distinct questions. A\nconstant fitted prevalence has perfect aggregate agreement but ranks\nnobody; a rule can rank well and systematically overstate probabilities.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![In-sample calibration by fitted-probability decile; vertical segments show one observed-proportion SE.](chapter_11_files/figure-html/fig-ch11-calibration-1.png){#fig-ch11-calibration fig-pos='!ht' fig-alt='Nine of ten groups lie reasonably near the equality line. The fifth decile is assigned about .413 but has an observed proportion about .297.' width=595.2}\n:::\n:::\n\n\n\n\nThe fifth decile is assigned .4126 but has observed proportion .2966,\na gap of .1161 or 3.0596 observed-proportion SEs. This deserves\ninvestigation rather than dismissal. Because the group was noticed among\nten and the model was fitted to these same rows, this descriptive SE\ncomparison is not a calibrated global test of fit. Aggregate agreement\nfrom the intercept says nothing about agreement within each decile.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Fitted probabilities overlap strongly between volunteers and non-volunteers.](chapter_11_files/figure-html/fig-ch11-discrimination-1.png){#fig-ch11-discrimination fig-pos='!ht' fig-alt='Two boxplots overlap almost entirely across fitted probabilities from about .24 to .62, showing weak descriptive separation.' width=595.2}\n:::\n:::\n\n\n\n\nFitted probabilities average .4313 among volunteers and .412 among the\nrest, a difference of .0192, and span only [.2418, .6235]. The boxes\noverlap strongly. Extraversion is detectably associated with volunteering,\nyet the fitted probabilities separate these students poorly. A small\ncoefficient p-value is not evidence of useful prediction [@shmueli2010].\nBoth displays reuse the fitting data and are optimistic as performance\nassessments. Chapter 13 develops held-out evaluation, including AUC,\nBrier score, log loss and threshold choice.\n\n{{< pagebreak >}}\n\n### What changed under sensitivity analysis {#ch11-sensitivity}\n\n\n| Specification | Extraversion odds ratio per point |\n|:--|--:|\n| Simple model, extraversion only | 1.0678 |\n| Additive model, sex and neuroticism added | 1.0686 |\n| Additive model, most influential row removed | 1.0703 |\n| Additive model plus quadratic extraversion, local at extraversion 13 | 1.0745 |\n| Product-term model, at median neuroticism | 1.0755 |\n\n: Sensitivity of the extraversion odds ratio to modeling and sample choices; each row refits the model with one feature changed. {#tbl-ch11-sensitivity tbl-colwidths=\"[70,30]\"}\n\n\n\nThe quadratic entry is a local derivative-based odds ratio at score 13;\nit is not exactly the finite 13-to-14 contrast. The product entry fixes\nneuroticism at its median. These definitions keep the compared quantities\nclear. The values remain close, but every specification uses the same\nunderlying study, measurements and design. Stability across them cannot\nestablish accurate volunteering records, valid personality measurement,\nindependent classrooms or absence of unmeasured common causes.\n\n## From Analysis to a Defensible Claim {#ch11-claim}\n\n### Report the magnitude and the limit together {#ch11-report}\n\nThe event and analytic unit come before any ratio. The model, predictor\nunits and reference categories make the comparison reproducible. A\nprobability-scale result then says what the ratio means in this study,\nwhile checks and uncertainty qualify the conclusion.\n\n::: {.callout-tip title=\"A bounded reporting example\"}\nAmong 1,421 recorded introductory psychology students, the volunteering\nproportion was .4201. Adjusting for recorded sex and neuroticism, each\nextraversion point was associated with 1.0686 times the odds of\nvolunteering rather than not volunteering (95% CI [1.0391, 1.0989]). The\naveraged one-point probability difference was .0159 over the observed\nprofiles. For a female student at neuroticism 11, fitted probabilities\nwere .4053 [.3668, .4451] at extraversion 10 and .4871 [.4474, .5269]\nat 15. The additive neuroticism association was not detected, although a\nneuroticism-by-extraversion product improved fit and showed a weaker\nextraversion contrast at higher neuroticism. A quadratic check and a\nsingle-row deletion gave similar local comparisons. Sparse extreme scores\nlimited their own interpretation; one calibration decile showed a material\ndeparture, and fitted probabilities overlapped strongly by outcome. These\nare conditional associations among recorded students. They establish\nneither a causal effect of personality nor useful prediction in a new cohort.\n:::\n\nThe report can contain a null comparison, a detected interaction and weak\ndiscrimination together. They address different aspects of the research\nquestion. Describing them faithfully is more useful than converting a\ncoefficient table into a general claim that the model \"worked\".\n\n### Recognize the claim a number supports {#ch11-attractive}\n\n| Tempting sentence | What the evidence supports |\n|:--|:--|\n| \"Volunteering is about 7% more likely per extraversion point.\" | Odds are 1.0686 times as large; the averaged probability difference is .0159. |\n| \"Neuroticism has no relationship with volunteering.\" | The additive adjusted interval admits small associations in both directions; the product term asks another question. |\n| \"The product coefficient is the extraversion effect.\" | Evaluate the conditional contrast at a stated neuroticism value and name its scale. |\n| \"The small p-value means the model predicts well.\" | A coefficient test, calibration check and held-out performance assessment answer different questions. |\n| \"The separated fit found a very large, imprecise effect.\" | Ordinary maximum likelihood has no finite estimate for that separated magnitude. |\n\n: Interpretation depends on the quantity and its conditions. {#tbl-ch11-attractive tbl-colwidths=\"[43,57]\"}\n\nA reusable report makes seven elements recoverable: event and unit;\nmodel and coding; a coefficient-scale estimate with uncertainty; a\nprobability-scale comparison; evidence for a declared term or block;\nadequacy and sensitivity; and the claim's boundary. They need not appear\nas seven ritual sentences. Their function is to let a reader judge what\nwas estimated and why its interpretation is warranted.\n\nThe empirical analyses use all Cowles records, except the explicitly\nlabelled deletion and constructed separation checks. The certification\nsample uses seed 1010, its repetition uses 1012, and the separated subset\nuses 1011. More than two categories, event counts, dependence, severe\nmeasurement error and sparse events each require a reconsidered model\nor inferential calculation, not a stronger reading of this coefficient\ntable.\n\n## Reading Bridge\n\nA logistic model connects a Bernoulli event to a linear predictor through\nthe logit link. Maximum likelihood supplies estimates and uncertainty;\nprobabilities give the substantive magnitude. Event coding, support,\nseparation and the distinction between calibration and discrimination\nremain part of interpreting every result. Chapter 12 extends the same\nframework to nominal categories, ordered categories and counts, each with\na new response structure and a new meaning for an exponentiated coefficient.\n\n## Key terms {.unnumbered}\n\nThis reference collects the concepts introduced here. The Part One Concept\nReference locates the broader ideas, including likelihood, coefficient\ncovariance and model comparison.\n\n\n| Term and common alternatives | Meaning or essential distinction |\n| :-- | :-- |\n| Event and non-event (the category coded 1) | The category a binary model treats as occurring, named together with the category coded 0. Reversing the event reciprocates the odds ratios and complements fitted event probabilities; probabilities for the original event agree after relabelling. |\n| Prevalence (event rate) | The proportion of analytic rows that are events. Coefficient precision also depends on conditional probabilities, predictor spread and overlap; the rare-outcome approximation of an odds ratio by a risk ratio depends on the risks being compared. |\n| Generalized linear model (GLM) | A response distribution, a linear predictor and a link connecting the conditional mean to the linear predictor; changing the response distribution and link gives the models of Chapters 11 and 12. |\n| Link function; logit link and inverse logit (logistic function) | The logit is the log of the odds and its inverse the S-shaped function bounded in $(0,1)$, equal to one half and steepest at a linear predictor of zero. |\n| Odds and log-odds | The odds are $\\pi/(1-\\pi)$ and the log-odds their logarithm; the three scales describe one quantity with null values 1 and 0, and the log-odds scale is symmetric under reversing the event. |\n| Odds ratio (OR) | The factor $e^{\\beta_j}$ by which the odds differ between units differing by one unit in a predictor and agreeing on the others; it depends on the units, reference, event and adjustment set, is not a risk ratio unless the event is rare, and implies no constant probability difference. |\n| Noncollapsibility (of the odds ratio) | A conditional odds ratio generally differs from the marginal one even with no confounding, so a coefficient that moves under adjustment is not by itself evidence of confounding. |\n| Bernoulli likelihood and score equations (binary-outcome likelihood) | The probability of the observed data as a function of the parameters, maximized to estimate them; for a binary outcome it is a product of Bernoulli probabilities whose score equations have no closed form, and a model with an intercept reproduces the observed event total. |\n| Iteratively reweighted least squares (IRLS) | The algorithm that repeatedly solves a weighted linear regression with weights $\\widehat\\pi_i(1-\\widehat\\pi_i)$ until the coefficients stop changing; its convergence flag and iteration count belong in the record and establish no adequacy. |\n| Deviance and the likelihood-ratio test ($G^2$) | For ungrouped binary data the deviance is $-2$ times the maximized log-likelihood and carries no goodness-of-fit reading alone, while the difference between nested models on the same rows and event is referred to chi-square. |\n| Wald test and profile-likelihood interval | The Wald statistic squares the estimate-to-SE ratio while a profile interval collects the values the log-likelihood does not reject; they diverge for rare events, small samples or near-infinite estimates. |\n| McFadden pseudo $R^2$ | One minus the ratio of the fitted to the intercept-only maximized log-likelihood: bounded in $[0,1]$, not a proportion of variance explained, and routinely small for useful models. |\n| Empirical logit | The log-odds of a grouped event count with one half added to each count, plotted against a predictor to check linearity of the log-odds in that predictor as entered. |\n| Binned residual | The mean raw residual within a bin of rows sorted by fitted probability, against a two-standard-error band; it replaces the residual-versus-fitted plot, which shows only two curved bands here. |\n| Separation (complete; quasi-complete) | A predictor pattern separates events from non-events completely or on a boundary, so at least one coefficient has no finite ordinary maximum-likelihood estimate. Diverging coefficients, large standard errors and convergence warnings can be symptoms; no one warning or numerical pattern is required. |\n| In-sample calibration and discrimination checks (fitted-probability checks) | Calibration asks whether fitted probabilities match observed event frequencies, discrimination whether they rank events above non-events; the two answer distinct questions, and honest evaluation of new-case performance requires held-out data. |\n| Linear probability model (LPM) | Ordinary least squares on a 0/1 outcome, whose coefficients are probability differences but whose mean function is unbounded and whose conditional variance cannot be constant. |\n| Averaged probability difference (average marginal comparison) | The mean, over the analytic rows with their own other predictor values, of the difference between fitted probabilities at two values of one predictor. |\n\n: Concepts introduced in this chapter. {#tbl-ch11-key-terms tbl-colwidths=\"[30,70]\"}\n\n\n\n## Further reading {.unnumbered}\n\nAgresti [@agresti2018] and Hosmer, Lemeshow and Sturdivant [@hosmer2013]\ndevelop logistic models and diagnostics. Gelman, Hill and Vehtari\n[@gelman2020] emphasize probability-scale interpretation. The R\n`glm()`, `family()` and `predict.glm()` documentation explains the\nimplementation [@rCoreLogistic; @rcore2025].\n\n## Exercises {.unnumbered}\n\n\n<!-- prompt-id: CH11-E01 -->\n\n### Exercise 1: Read a logistic result on three scales (Foundational). {.unnumbered}\n\nA\nlogistic regression of whether a student volunteered for an experiment\non an extraversion score in integer points, adjusting for recorded sex\nand a neuroticism score, gives an extraversion coefficient of .0663 with\nstandard error .0143. The event is volunteering, the reference sex\ncategory is female, extraversion runs from 2 to 23, and the prevalence\nis .4201. (1) Give the odds ratio and its Wald 95% interval, and write\none sentence interpreting them with the units, the event and the\nadjustment set explicit. (2) Give the odds ratio for a five-point\ndifference. (3) Give the divide-by-four bound on the probability\ndifference per point, compute the local rate of change at a fitted\nprobability of .12 from $\\partial\\pi/\\partial x=\\beta\\,\\pi(1-\\pi)$, and\nexplain why it must be smaller than the bound. (4) Name three\nconclusions the interval excluding 1 does not establish.\n\n<!-- END exercise-id: CH11-E01 -->\n\n\n<!-- prompt-id: CH11-E02 -->\n\n### Exercise 2: Declare the event, then reverse it (Foundational). {.unnumbered}\n\nA\nresearcher codes program *completion* as the event and reports an odds\nratio of .62 per additional hour of paid weekly employment, with a 95%\ninterval of [.51, .75]. (1) State in one sentence what this odds ratio\ncompares, including the event and the units. (2) Give the odds ratio and\ninterval the same fitted model would report with *non-completion* as the\nevent, showing the arithmetic. (3) State which of these change under the\nrecoding and which do not: the coefficient signs, the standard errors,\nthe $z$ statistics, the p-values, the deviance, the fitted probability\nof completion for a given student, and McFadden's pseudo $R^2$. (4) The\nresearcher also relevels the employment-status factor so that \"employed\"\nis the reference, and a reviewer complains that the results changed.\nExplain in what sense they did and did not change.\n\n<!-- END exercise-id: CH11-E02 -->\n\n\n<!-- prompt-id: CH11-E03 -->\n\n### Exercise 3: Odds ratios are not probability differences (Foundational). {.unnumbered}\n\nTwo studies report the same adjusted odds ratio of\n2. In Study A the comparison group's event probability is .04; in\nStudy B it is .45. (1) For each study compute the exposed group's event\nprobability, the probability difference and the risk ratio. (2) Explain\nwhy the odds ratio and the risk ratio nearly coincide in one study and\ndiverge in the other. (3) A policy brief states that \"an odds ratio of\n2 means the risk is doubled\" for both. Say where this is approximately\nacceptable and where it is not, and quantify the error. (4) Explain why\nnoncollapsibility means an adjusted odds ratio can differ from an\nunadjusted one even when the added predictor is unrelated to the focal\npredictor. (5) Recommend, with reasons, which scale you would lead with\nin a report for school administrators, and which you would also supply.\n(6) In the invented model $p(x,u)=\\operatorname{logit}^{-1}(x+u)$,\ncompare $u=1$ with $u=0$. Population C has equal numbers at $x=-.5$ and\n$.5$; Population D has equal numbers at $x=-4$ and 4. Before\ncalculating, predict which has the larger average probability\ndifference. Explain why their common mean $x=0$ and common conditional\nodds ratio do not make these averages equal.\n\n<!-- END exercise-id: CH11-E03 -->\n\n\n<!-- prompt-id: CH11-E04 -->\n\n### Exercise 4: Deviance, Wald, and the criteria by hand (Foundational). {.unnumbered}\n\nOn 1,421 rows with the same event, an intercept-only logistic model has\ndeviance 1933.506 and a model with sex, neuroticism and extraversion\nhas deviance 1906.0613 with four fitted coefficients; the 5% critical\nvalue of $\\chi^2_3$ is 7.8147 and $\\log 1421=7.259116$. The neuroticism\ncoefficient is .0064 with standard error .0114. (1) Calculate the\nlikelihood-ratio statistic for the three-predictor block, give its df,\nand state the decision at 5% and what it does and does not say about the\nthree added columns. (2) Calculate AIC and BIC for the fuller model and\nsay which model each criterion prefers, given the single-predictor\nmodel's AIC 1915.4838 and BIC 1926.002. (3) Calculate the Wald\nstatistic for neuroticism, compare it with the likelihood-ratio value\n.3139, and say when the two would be expected to disagree. (4) Explain\nwhy a deviance of 1906.0613 on its own says nothing about fit.\n\n<!-- END exercise-id: CH11-E04 -->\n\n\n<!-- prompt-id: CH11-E05 -->\n\n### Exercise 5: Evaluate a product term, do not read it (Integrative). {.unnumbered}\n\nA\nlogistic model of volunteering contains sex, neuroticism $N$,\nextraversion $E$ and their product, with $\\widehat\\beta_E=.1668$ and\n$\\widehat\\beta_{NE}=-.0086$; neuroticism runs from 0 to 24 with\nquartiles 8, 11 and 15, the likelihood-ratio test of the product gives\n$G^2(1)=8.6213$, $p=.0033$, and neuroticism alone had $p=.5754$ in the\nadditive model. (1) Give the conditional extraversion log-odds contrast\nand odds ratio at each quartile. (2) Explain what .1668 refers to and\nwhy it is not \"the extraversion effect\". (3) Explain how a term with no\ndetected additive association can participate in a detected product, and\nwhy the additive term is kept. (4) At extraversion 13 a female student's\nfitted probability is .4519 at neuroticism 8 and .4512 at 15, and the\none-point probability differences are .0245 and .0096. Explain why the\nprobability and log-odds pictures can agree here and disagree elsewhere,\nand what a report must name before claiming an interaction.\n\n<!-- END exercise-id: CH11-E05 -->\n\n\n<!-- prompt-id: CH11-E06 -->\n\n### Exercise 6: Read a separated output and a calibration display (Integrative). {.unnumbered}\n\nA logistic regression fitted to 60 rows returns a\ncoefficient of 5.5928 with standard error 8014.9006, $p=.9994$, a\nresidual deviance of $5.642\\times10^{-10}$, fitted probabilities of\nessentially 0 and 1, and 25 iterations against the four a well-behaved\nmodel needed. A separate, well-behaved model has one calibration decile\nwith mean fitted probability .4126 against an observed proportion of\n.2966, whose standard error is .0379, while the other nine lie within\n1.4 standard errors; its fitted probabilities span .2418 to .6235. (1)\nName the pattern producing the first output and say why the Wald test\nreports no evidence for the strongest possible pattern. (2) State what a\nreport can and cannot say about that coefficient, and name two remedies\nwith the condition each requires. (3) Express the calibration gap in\nstandard errors and say how much weight one such decile deserves among\nten. (4) State what the fitted-probability range says about\ndiscrimination, why that differs from calibration, and why both are\noptimistic when computed on the fitting rows.\n(5) Sketch the qualitative likelihood shape for a finite estimate and\nfor the separated example. Explain why a finite stopping point and a\nvery small change in likelihood do not establish a finite maximum.\n\n<!-- END exercise-id: CH11-E06 -->\n\n\n\n## Appendix A: Likelihood Mathematics and Numerical Checks {#ch11-likelihood-appendix .unnumbered}\n\nA numerical optimum, a finite identified parameter and an adequate scientific model are different claims. The following two examples make their checks concrete.\n\n### Interior and boundary solutions {.unnumbered}\n\nFor $s$ successes in $n>0$ independent Bernoulli trials with common\nprobability $p$,\n\n$$\nL(p)=\\binom{n}{s}p^{s}(1-p)^{n-s},\\qquad\n\\ell(p)=\\log\\binom{n}{s}+s\\log p+(n-s)\\log(1-p).\n$$\n\nFor $0<s<n$, differentiating on $0<p<1$ gives\n\n$$\n\\ell'(p)=\\frac{s}{p}-\\frac{n-s}{1-p},\\qquad \\widehat p=\\frac{s}{n}.\n$$\n\nThe binomial coefficient is constant in $p$, so recording only the count\nrather than the particular observed 0/1 pattern does not change the\nmaximizing $p$: the Bernoulli product $p^{s}(1-p)^{n-s}$ and the binomial\nlikelihood share a maximizer. With only an intercept in a logistic model,\n$p=\\operatorname{logit}^{-1}(\\beta_0)$, so the interior solution is\n$\\widehat p=s/n$ with\n$\\widehat\\beta_0=\\operatorname{logit}(s/n)$. At $s=0$ or $s=n$ the\nlikelihood is maximized at a boundary probability of 0 or 1 and there is\nno finite intercept estimate, which is the one-parameter form of the\nseparation problem Section 6.3 develops for predictor patterns; the\nanalogy motivates, and does not replace, that section's conditions.\nEvaluate the boundaries explicitly, because an interior numerical search\ncan return a point near an endpoint without ever evaluating it.\n\nThe 14 of 32 `mtcars`\nrecords reaching 20 mpg supply a transparent illustration under a separately stipulated binomial model. Counting those outcomes does not establish\nindependent Bernoulli sampling of car models; the records and their\nillustrative qualification are those of Chapters 5 and 6, and no new\nextract or file is created.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnll <- function(p) -dbinom(14, 32, p, log = TRUE)\noptimize(nll, c(0, 1))\n14 / 32\n```\n:::\n\n\n\nBoth displayed proportions are .4375 to four decimals; the small\ndifference from exactly 14/32 is optimization tolerance. `dbinom()`\nincludes the combinatorial term, which does not move the maximizer, and\nits `log = TRUE` form avoids taking a logarithm after underflow.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(0, 32, 0, log = TRUE)\ndbinom(32, 32, 1, log = TRUE)\nqlogis(c(0, 14/32, 1))\n```\n:::\n\n\n\nThe three fitted probabilities are 0, .4375 and 1, with minimum negative\nlog-likelihoods 0, 1.9588 and 0. `qlogis()` returns negative and positive\ninfinity at the two boundaries: these are exact mathematical results, not\nrounded small positive probabilities, and displaying them at four decimals\nwould misrepresent them. The intercept-only logistic fit returns\n$-.2513$, which is $\\operatorname{logit}(.4375)$, closing the loop between\nthe scalar binomial case and the regression model of Section 3.\n\n### Several parameters and local curvature {.unnumbered}\n\nUnder a hypothetical independent Normal model for a quantitative outcome,\n\n$$\n-\\ell(\\mu,\\sigma)=\\frac n2\\log(2\\pi)+n\\log\\sigma\n+\\frac{\\sum_i(y_i-\\mu)^2}{2\\sigma^2},\\qquad \\sigma>0 .\n$$\n\nParameterize $\\sigma=e^{\\eta}$, so an unconstrained search in $\\eta$ keeps\nthe scale positive. The parameters are then $(\\mu,\\eta)$ rather than\n$(\\mu,\\sigma)$, which also fixes the scale on which a numerical Hessian is\nreported. With positive observed variation the analytic maximizers are\n\n$$\n\\widehat\\mu=\\bar y,\\qquad\n\\widehat\\sigma_{\\mathrm{ML}}=\\sqrt{\\frac1n\\sum_i(y_i-\\bar y)^2},\n$$\n\nso the maximum likelihood scale divides by $n$ where `sd()` divides by\n$n-1$; this is the same distinction Chapter 9 makes before AIC and BIC.\nAll-equal data require separate treatment, because the Normal likelihood\nis unbounded as $\\sigma$ tends to zero and no finite positive-scale\nmaximizer exists. The `mpg` values below have positive variation. This\nillustration concerns a different model and a generic optimizer: it does\nnot claim that car outcomes follow a Normal process, and it does not claim\nthat `glm()` uses BFGS.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloss <- function(par) {\n  -sum(dnorm(mtcars$mpg, par[1], exp(par[2]), log = TRUE))\n}\nstart <- c(mean(mtcars$mpg) - 1, log(sd(mtcars$mpg)))\na <- optim(start, loss, method = \"BFGS\", hessian = TRUE)\na$convergence\neigen(a$hessian, symmetric = TRUE)$values\n```\n:::\n\n\n\n| Check | Reproduced anchor | Meaning |\n|:--|:--|:--|\n| Analytic mean and ML scale | 20.0906; 5.9320 | Closed-form benchmark on the recorded data; `sd()` gives 6.0269 |\n| First-start estimates | 20.0908; 5.9320 | Numerical tolerance can move the last displayed digit even when convergence is reported |\n| Both convergence codes | 0 | The algorithm's stopping criterion was met |\n| First negative log-likelihood | 102.3778 | The same objective is compared under both starts |\n| First minus second objective | About $-5.99\\times10^{-7}$ | Near equality supports reproducibility of the numerical solution; it is not a test of the model |\n| Hessian eigenvalues in $(\\mu,\\eta)$ | About 64.0006 and .9094 | Positive local curvature of the negative log-likelihood at the returned point |\n\n: Numerical and analytic values have different roles. {#tbl-ch11-optimizer tbl-colwidths=\"[28,26,46]\"}\n\nA stopping code alone establishes neither\nagreement at the reporting precision, nor a global optimum, nor\nidentification, nor scientific adequacy: compare starts and objective\nvalues, use an analytic benchmark where one exists, and read the returned\nlocal curvature. Section 3.2's IRLS report applies the same discipline to\nthe fitting routine actually used, and Section 6.3 shows its symptoms when\nno maximum exists. **Extended practice.** Compare an interior binomial\ncase with the zero-success and all-success cases, checking endpoint\nlikelihoods explicitly and saying which constraint changes; for the Normal\nexample compare the two starts with the analytic solution and state what\nthe convergence codes and Hessian do and do not establish. \n\n\n\n\n## Appendix B: Changed Conditions in the Generating Process {.unnumbered}\n\nThe certification process in Section 3.3 is a reference, not a universal\nperformance guarantee. The three changes below retain the hours coefficient\n.3 and alter one feature at a time. A smaller study reduces information;\na lower intercept changes where observations lie on the logistic curve;\na narrower range removes contrast in hours. None changes the declared\ncoefficient being estimated.\n\n| Condition | Change from the baseline | Consequence to investigate |\n|:--|:--|:--|\n| Smaller study | Reduce 1,500 students to 100 | More sampling variation and greater risk of unstable estimates |\n| Lower baseline | Set the intercept to $-5$ | More probabilities near zero, reducing typical Bernoulli information |\n| Narrower hours | Generate hours uniformly from 8 to 12 | Less predictor spread for identifying the hours slope |\n\n: One changed feature per simulation condition. {#tbl-ch11-sim-conditions tbl-colwidths=\"[22,34,44]\"}\n\nFor each condition, generate 500 independent datasets and retain the hours\nestimate, its standard error, the Wald interval and any fitting warning.\nThe estimate distribution, its mean and SD, and coverage of .3 answer\ndifferent questions: sampling stability, finite-sample bias, precision and\ninterval calibration. Record estimates with absolute magnitude above 5\nand separation warnings rather than silently deleting those replications.\nA warning is a screening signal, not a complete separation diagnosis.\n\nA baseline of $-5$ does not make every profile's event rare: at twenty\nhours without tutoring the logit is 1, so the probability is .7311.\nDescribe it as a lower-baseline process and inspect its actual prevalence.\nWhen comparing coverage across 500 repetitions, Monte Carlo variation\nmatters: near .95 coverage its SE is about .0097. An apparent difference\nof a few thousandths is not compelling evidence of changed calibration.\n\nFinally fit a linear probability model to one generated dataset from each\ncondition and count fitted values outside $[0,1]$. A narrower range can\nmake the line's boundary problem less visible while making its slope less\nprecise. Boundary protection, sampling precision and correct interpretation\nare distinct reasons for preferring or questioning a model.\n\n## References {.unnumbered}\n\n",
    "supporting": [
      "chapter_11_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}