{
  "hash": "5bbe6e858417a53b71a590806e4d7005",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Regression I: Conditioning, Checks, and Coordinated Questions\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\n\\clearpage\n\n::: {.callout-note title=\"Chapter overview\"}\nOne set of records can owe several answers, and multiple regression is\nthe model behind most of them. This chapter first writes the multiple\nregression model, says what a partial slope compares, and draws a\nsimulated process with two predictors. It then fits the model to the\n98 occupations of Chapter 7 that have a recorded type, attaches\nuncertainty to the education slope and checks the model, computes a\nfitted profile and an average over named profiles, and compares two\nprediction rules on held-out occupations. It closes with a short report\nthat owes three answers, a marginal description, a conditional\nassociation and a prediction comparison, and reads and evaluates them.\nBy the end you will be able to write, fit and read an additive multiple\nregression in R, keep changes of records, comparison, coefficient\ncoordinates and uncertainty calculation apart, judge a held-out\ncomparison, and evaluate coordinated answers without merging them.\n:::\n\nA report on occupational income may ask whether education and income move\ntogether, whether that relationship remains when other characteristics of\nthe occupations are held constant, and whether those characteristics help\npredict income. The questions inform one another, but answering one does\nnot answer the other two.\n\nWe use a **retrospective teaching study written for this chapter**. Its\nrecords are the *Prestige* data distributed with the carData package\n[@carData2022; @fox2019], whose documentation describes the data; the\nanalyses and the short report are ours.\n\nA simple regression models an outcome with one predictor,\n$Y_i=\\beta_0+\\beta_1x_i+\\varepsilon_i$. Multiple regression keeps that\nform and adds one term for each further predictor.\n\n## Model Formulation and Interpretation {#sec-ch8-comparisons}\n\n### The population and observation forms\n\nWith several predictors, the model for an outcome is\n\n$$\nY=\\beta_0+\\beta_1x_1+\\cdots+\\beta_{p-1}x_{p-1}+\\varepsilon,\n$$\n\n$$\nE(\\varepsilon\\mid x_1,\\ldots,x_{p-1})=0,\\qquad\n\\operatorname{Var}(\\varepsilon\\mid x_1,\\ldots,x_{p-1})=\\sigma^2;\n$$\n\n$$\nY_i=\\beta_0+\\beta_1x_{i1}+\\cdots+\\beta_{p-1}x_{i,p-1}+\\varepsilon_i,\n\\qquad i=1,\\ldots,n.\n$$\n\nThe part $\\beta_0+\\beta_1x_1+\\cdots+\\beta_{p-1}x_{p-1}$ is the mean of\n$Y$ among units that share those predictor values, and the error\n$\\varepsilon$ collects everything else. The model has $p$\ncoefficients, counting the intercept. $\\beta_0$, the intercept, is the\nmean when every predictor is zero; it anchors the equation and\ndescribes real units only if that combination is plausible within the\ndata. $\\beta_j$, a partial slope, is the difference in the mean of $Y$\nfor a one-unit difference in $x_j$, holding the other predictors\nfixed. $\\sigma$ is the typical spread of outcomes around the mean at\nfixed predictor values. The conditions apply at every combination of\npredictor values: the errors average zero and\nshare one variance $\\sigma^2$; they are independent of one another,\nwhich comes from how the data arose; and for the exact $t$ reference\nthey are Normal. The intervals used here require independent errors, the classical SE\nalso needs the common variance, and the exact $t$ also needs Normal\nerrors; the HC3 covariance of Section 3.3 relaxes the common variance\nunder its own large-sample conditions.\n\nUnder the Normal-error model, $Y_i$ at its fixed predictor values is\nNormal with mean $\\beta_0+\\sum_{j=1}^{p-1}\\beta_jx_{ij}$ and SD\n$\\sigma$. Estimating $p$ coefficients leaves $n-p$ residual degrees of\nfreedom. A factor with $J$ categories contributes $J-1$ indicator\ncolumns, as Section 2.3 explains using the occupation records.\n\n### What a partial slope compares {#ch08-several-controls}\n\nTake two predictors, $x$ and $z$. The model mean is\n$\\mu(x,z)=\\beta_0+\\beta_Xx+\\beta_Zz$. Comparing two means a unit apart\nin $x$ at the same $z$ gives\n\n$$\n\\mu(x+1,z)-\\mu(x,z)=\\beta_X(x+1)-\\beta_Xx=\\beta_X.\n$$\n\nAll the shared terms cancel. Holding constant names this comparison of\nmodel means; it does not mean that $x$ was changed experimentally, that\ntwo observed units match on everything else, or that unmeasured\ndifferences have been controlled. A partial slope's meaning belongs to\nits named conditioning set. The same predictor can have a different\ncoefficient when a different set is held fixed. The **additive** form\nalso makes its comparison the same at every value of the other\npredictors; Chapter 10 asks when that comparison itself varies.\n\nPartial correlation holds variables fixed another way, by\nresidualizing: it removes their fitted linear parts from two variables\nbefore correlating what remains. A fitted equation with\nseveral predictors holds the others fixed directly, because two of its\nfitted means that differ in one predictor share every other term;\nSection 3.1 shows that the two routes give the same slope. Chapter 9,\nSection 2, applies the same idea to adjusted group means in the\nanalysis of covariance.\n\n### Simulating and graphing a two-predictor model\n\nA known process makes the comparison concrete. Suppose\n\n$$\nY=50+2X+5Z+\\varepsilon,\n\\qquad E(\\varepsilon\\mid X,Z)=0,\n$$\n\nwith finite variances and\n$\\operatorname{Cov}(X,Z)/\\operatorname{Var}(X)=0.65$.\nThe conditional $X$ coefficient is 2, and the marginal linear slope is\n\n$$\n\\frac{\\operatorname{Cov}(X,Y)}{\\operatorname{Var}(X)}\n=2+5\\frac{\\operatorname{Cov}(X,Z)}{\\operatorname{Var}(X)}\n=2+5(0.65)=5.25.\n$$\n\nGenerate independent standard Normal values $X$ and $U$, let\n$Z=.65X+\\sqrt{1-.65^2}U$, and add independent Normal errors with SD 6.\nBoth predictors then have variance one and correlation .65.\n@fig-ch8-known-process draws one generated sample of 250 cases from this\nprocess, with the process's own mean lines rather than fitted ones. Each\nsolid line holds $Z$ at one value and rises 2 for each unit of $X$. The\ndashed marginal line rises 5.25, because higher $X$ comes with higher $Z$\n(the darker points sit toward the upper right) and the marginal line\ncarries that association along.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![One generated sample from the known process, with its marginal line and three lines at fixed $Z$.](chapter_08_files/figure-html/fig-ch8-known-process-1.png){#fig-ch8-known-process fig-pos='!ht' fig-alt='Scatterplot of 250 generated points of Y against standardized X, shaded by Z, with darker points higher and to the right. Three parallel solid lines at Z equal to minus one, zero and one rise with slope 2. A steeper dashed line, the marginal line, rises with slope 5.25 and crosses the three solid lines.' width=585.6}\n:::\n:::\n\n\nWith these generated columns named `x`, `z` and `y` in `sim`, the\nfollowing calls estimate the marginal and conditional equations. The\nshort examples throughout this chapter show the statistical operation\non the data just described.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(lm(y ~ x, data = sim))\ncoef(lm(y ~ x + z, data = sim))\n```\n:::\n\n\nIn this sample the fitted $X$ coefficient is 3.0259 (SE 0.5325), the\n$Z$ coefficient 4.3991 (SE 0.5282), and the marginal slope 5.9971\n(SE 0.4466). Each lies within two SEs of its programmed value, 2, 5,\nand 5.25 respectively. A single sample estimates the process rather\nthan reproducing its parameters exactly.\n\nMapping `x` and `y` to position and `z` to colour draws the points in\n@fig-ch8-known-process. The fitted slopes and the known process lines\nanswer related but distinct questions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(sim, aes(x, y, colour = z)) + geom_point()\n```\n:::\n\n\nThe two slopes answer different questions: one holds $Z$ fixed, the\nother includes how $Z$ moves with $X$, and neither alone says what would\nhappen if someone intervened on $X$. Calling 5.25 \"biased\" requires\nnaming the target it is used for; as the marginal linear slope it is\ncorrect. Appendix A gives the derivation and the repeated samples.\n\n## Estimating the Model on the Occupation Records {#sec-ch8-questions}\n\n### The records and the working model\n\nA row is an **occupation**, not a worker. Income is the occupation's\naverage annual income in 1971 Canadian dollars, divided here by 1,000;\neducation is average years of education; *women* is the percentage of\nwomen; prestige is a rating from a mid-1960s survey, earlier than the\n1971 income and education; and type is blue-collar (*bc*),\nprofessional/managerial/technical (*prof*), or white-collar (*wc*). These\nhistorical occupational averages are not current individual earnings.\n\nChapter 7 used all 102 occupations. The full variable set leaves 98\ncomplete records, because athletes, newsboys, babysitters, and farmers\nhave no recorded type; the three types keep 44, 31, and 23 records. We\nkeep the source row order, which also makes the validation split of\nSection 6 reproducible. The original 102 records are `d0`; `dat` holds\nthe 98 complete records, with `income_k` in thousand dollars and type\nlevels ordered `bc`, `prof`, `wc`.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(original = nrow(d0), retained = nrow(dat))\ntable(dat$type)\n```\n:::\n\n\nWe refit the education-only model on these **same 98 records** before any\nadjusted comparison, so that the move from 102 to 98, a change in which\nrecords are described, is never presented as an adjustment effect.\nComplete records make the computations comparable; they do not make the\nomitted occupations irrelevant or the 98 a probability sample of Canadian\noccupations.\n\nThe working occupation model is\n\n$$\n\\mathrm{income}_k=\\beta_0+\\beta_Ee+\\beta_Pp+\\beta_Ww\n+\\delta_{\\mathrm{prof}}D_{\\mathrm{prof}}+\\delta_{\\mathrm{wc}}D_{\\mathrm{wc}}\n+\\varepsilon,\n$$\n\nwhere $e$ is education, $p$ prestige, $w$ percentage of women, and each\nindicator $D$ is 1 for its named type. Blue-collar, with both indicators\nzero, is the reference type. There are six coefficients. The\nconditional question concerns $\\beta_E$, comparing education at the same\nprestige, women and type. Least squares describes the recorded\noccupations whether or not that stochastic model holds; Section 3\napplies its conditions to attach uncertainty.\n\nA **best linear projection**, summarizing a curved relationship over a\nstated predictor distribution, is a different declared target, not a\nrescue adopted after curvature appears. Chapter 9, Appendix A,\ndevelops it.\n\n### Least squares and the fits on the same rows\n\nLeast squares chooses the coefficients that make the residual sum of\nsquares smallest. Its residual SD,\n$s_e=\\sqrt{RSS/(n-p)}$, describes the typical residual size; the full\nmodel below gives 2.6187 thousand dollars on 92 df. $R^2$ is the share\nof centered outcome variation accounted for in these records; Appendix B\nintroduces its adjusted version.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- lm(income_k ~ education, data = dat)\nm_w <- lm(income_k ~ education + women, data = dat)\nm1 <- lm(income_k ~ education + prestige, data = dat)\nm2 <- lm(income_k ~ education + prestige + women + type, data = dat)\ncoef(m_w)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   education       women \n-1.19760964  0.92922682 -0.06536432 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   education    prestige       women    typeprof \n  0.4205235   0.1164336   0.1406054  -0.0535047   0.3241934 \n     typewc \n  0.2353306 \n```\n\n\n:::\n:::\n\n\n| Records and predictors | Education slope | In-sample $R^2$ | Role here |\n|:--|--:|--:|:--|\n| Earlier 102, education only | 0.8988 | .3336 | Chapter 7's line on different records |\n| Same 98, education only | 0.8830 | .3296 | The marginal description |\n| Same 98, education and women | 0.9292 | .5641 | Holds women fixed; the slope barely moves |\n| Same 98, education and prestige | $-0.2179$ | .4996 | Holds prestige fixed; the slope changes sign |\n| Same 98, all declared predictors | 0.1164 | .6362 | The conditional answer about $\\beta_E$ |\n\n: The model sequence separates sample composition from conditioning. {#tbl-ch8-sequence tbl-colwidths=\"[36,18,16,30]\"}\n\nThe education-and-women fit gives a concrete reading: two occupations\none year apart in education, with the same percentage of women, differ\nin fitted income by 0.9292 thousand dollars (education SE 0.1044).\nAt the same education, one percentage point more women corresponds to\n0.0654 thousand dollars lower fitted income (SE 0.0091). Its $R^2$ is\n.5641. These are comparisons of occupations, not effects of changing an\nindividual's education or occupation.\n\nWhy does adding prestige reverse the education slope while adding\nwomen barely changes it? Education correlates .8665 with prestige and\n.0619 with women. Correlation alone is only part of the explanation:\nhow far the education slope moves depends on the added predictor's\ncoefficient *and* its slope on education. For least-squares fits on the\nsame rows, the sample omitted-variable identity is\n\n$$\n\\begin{aligned}\n\\text{marginal slope}&=\\text{slope with }Z\\\\\n&\\quad+(\\text{coefficient of }Z)(\\text{slope of }Z\\text{ on education}),\\\\\n0.8830&=-0.2179+0.2043(5.3884)\\qquad(Z=\\text{prestige}),\\\\\n0.8830&=0.9292+(-0.0654)(0.7069)\\qquad(Z=\\text{women}).\n\\end{aligned}\n$$\n\nAppendix A derives the identity; the displayed numbers are rounded.\nThe carried parts are 1.1009 for prestige and $-0.0462$ for women.\n@fig-ch8-grid shows the corresponding fitted lines beside the marginal\nline, extending the known-process display to real records.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Fitted income against education at three held values of prestige (a) or of the percentage of women (b), each line drawn over the education observed near its held value, with the dashed marginal education-only line.](chapter_08_files/figure-html/fig-ch8-grid-1.png){#fig-ch8-grid fig-pos='!ht' fig-alt='Both panels show the 98 occupation records and a rising dashed marginal line. In panel a, gently falling solid lines at prestige 30, 50 and 70 sit over successively higher education ranges. In panel b, rising solid lines at 10, 50 and 90 percent women are almost parallel to the marginal line, with the line for more women lower.' width=614.4}\n:::\n:::\n\n\nIn panel (a), each solid line falls 0.2179 per education year at fixed\nprestige. The higher-prestige lines sit over higher education, so the\nrising marginal line crosses them. In panel (b), the solid lines rise\n0.9292 per year, nearly the marginal slope, because women hardly tracks\neducation. Each line uses the education range among records within 7.5\npoints of its held value, a display choice that respects nearby\nobservations; Section 4.2 checks support more fully.\n\nFor example, the first panel's line at prestige 50 combines the fitted\nintercept with $50\\widehat\\beta_P$; its slope is $\\widehat\\beta_E$.\nThe nearby points keep the comparison close to observed education\nvalues.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnear <- dat[abs(dat$prestige - 50) <= 7.5, ]\nggplot(near, aes(education, income_k)) + geom_point() +\n  geom_abline(intercept = coef(m1)[1] + 50*coef(m1)[\"prestige\"],\n              slope = coef(m1)[\"education\"])\n```\n:::\n\n\nThe sequence of slopes names different comparisons; it is not a true\neffect being explained away. Adding predictors on the same rows cannot\nincrease the smallest achievable RSS, so training $R^2$ cannot fall.\nThe separate gains need not add up: women adds .2345, prestige adds\n.1701, and the full model adds .3066 over education alone. These gains\nconcern training fit, not held-out prediction.\n\n### Indicators and a fitted profile\n\nA three-level factor needs two indicators. With blue-collar as reference,\n$D_{\\mathrm{prof}}$ and $D_{\\mathrm{wc}}$ identify the other types;\nthe full occupation fit is\n\n$$\n\\begin{aligned}\n\\widehat{\\mathrm{income}}_k\n={}&0.4205+0.1164e+0.1406p-0.0535w\\\\\n &+0.3242D_{\\mathrm{prof}}+0.2353D_{\\mathrm{wc}}.\n\\end{aligned}\n$$\n\nSubtract two fitted means one education year apart at the same prestige,\npercentage of women and type. Every term except education cancels:\n\n$$\n\\widehat m(e+1,p,w,t)-\\widehat m(e,p,w,t)=\\widehat\\beta_E=0.1164.\n$$\n\nThus two such occupations differ by about 116 dollars in fitted income.\nAt the same values of all the other predictors, a prestige point compares\nabout 141 dollars more, and a percentage point more women compares about\n54 dollars less. Each sentence names what is held fixed.\n\nFor a white-collar profile with education 11, prestige 45, and women 50,\n$D_{\\mathrm{prof}}=0$ and $D_{\\mathrm{wc}}=1$, and the unrounded fitted\ncoefficients give\n\n$$\n\\begin{aligned}\n\\widehat m_*\n={}&\\widehat\\beta_0+11\\widehat\\beta_E+45\\widehat\\beta_P\n+50\\widehat\\beta_W+\\widehat\\delta_{\\mathrm{wc}}\\\\\n\\approx{}&5.5886,\n\\end{aligned}\n$$\n\na fitted mean of about 5,589 dollars on the historical income scale, not\na guarantee for any occupation or worker.\n\nThe intercept refers to zero education, prestige, and women in the\nreference type; it anchors the fitted surface and need not describe a\nplausible occupation. Nor is one type coefficient \"the effect of\noccupational type\". When a factor stands alone, each coefficient is a\ndifference between group means; here each type\ncoefficient compares fitted means at the same education, prestige, and\nwomen. Appendix A gives the group-mean and releveling calculations, and\nChapter 9 develops contrasts, block tests, and the analysis-of-variance\nidentity.\n\nThe substitution uses six multipliers, one for each coefficient.\n@tbl-ch8-design-rows puts them in coefficient order for three actual\noccupations and for the declared profile. The first multiplier is 1\nbecause every fitted value includes the intercept. A professional\nrecord selects the professional coefficient, a white-collar record the\nwhite-collar coefficient, and a blue-collar record selects neither.\n\n| Record or profile | Intercept | Education | Prestige | Women | Professional | White-collar |\n|:--|--:|--:|--:|--:|--:|--:|\n| Nursing aides | 1 | 9.45 | 34.9 | 76.14 | 0 | 0 |\n| Government administrators | 1 | 13.11 | 68.8 | 11.16 | 1 | 0 |\n| Medical technicians | 1 | 12.79 | 67.5 | 76.04 | 0 | 1 |\n| Declared white-collar profile | 1 | 11.00 | 45.0 | 50.00 | 0 | 1 |\n\n: Each row lists the multipliers of the six coefficients. {#tbl-ch8-design-rows tbl-colwidths=\"[30,9,12,12,11,13,13]\"}\n\nThis gives a concrete meaning to the vector notation. Write the\nmultipliers as the column vector\n$\\mathbf x_i=(1,e_i,p_i,w_i,D_{\\mathrm{prof},i},D_{\\mathrm{wc},i})^{\\mathsf T}$\nand the corresponding coefficients as\n$\\boldsymbol\\beta=(\\beta_0,\\beta_E,\\beta_P,\\beta_W,\n\\delta_{\\mathrm{prof}},\\delta_{\\mathrm{wc}})^{\\mathsf T}$.\nA **vector** is an ordered collection of numbers; the superscript\n$\\mathsf T$ denotes the transpose, which turns a column into a row.\nThe product $\\mathbf x_i^{\\mathsf T}\\boldsymbol\\beta$ adds the six\nmultiplier--coefficient products, exactly as the scalar equation does.\n\nStacking the 98 observed rows gives the $98\\times6$ **design matrix**\n$\\mathbf X$. Stacking the outcomes and errors gives the compact model\n$\\mathbf Y=\\mathbf X\\boldsymbol\\beta+\\boldsymbol\\varepsilon$.\nThe design matrix stores predictors and indicators, not income. Distinct\ncoefficients require that no column be an exact linear combination of\nthe others, the **full-column-rank condition**. Near collinearity affects\nprecision, as Section 4.2 explains. The\nprofile is a new row for prediction, not an extra record used to fit\nthe model. `model.matrix()` recovers the observed multiplier rows;\nmultiplying `row` by the fitted coefficients recovers the profile mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrows <- c(\"nursing.aides\", \"gov.administrators\", \"medical.technicians\")\nmodel.matrix(m2)[rows, ]\nrow <- c(1, 11, 45, 50, 0, 1)\nsum(row * coef(m2))\n```\n:::\n\n\nSection 5 uses this notation to carry coefficient uncertainty to the\nprofile; Chapter 9, Appendix A, develops the matrix mathematics. Section 4.2 checks whether the three continuous values of that white-collar\nprofile occur together, using a weighted combination of observed records.\n\n## Inference for the Partial Slope {#sec-ch8-estimate}\n\nApply Section 1.1's model to the occupation records: incomes vary\nindependently around the linear mean of Section 2.1 at the recorded\npredictor rows, with a common error SD $\\sigma$. The residual SD 2.6187\nestimates it on 92 df. The repetition imagined for the classical\nintervals is new incomes at the same 98 predictor rows; the historical\nrecords do not establish that model or a probability sample.\n\n### The partial slope from residuals {#ch08-partial-regression}\n\nThe partial slope can be recovered by removing the fitted parts of\nthe other predictors from both variables. Regress education on\nprestige, percentage of women, and type and keep the residuals\n$r_{E,i}$; do the same for income to obtain $r_{Y,i}$. Both auxiliary\nfits include an intercept and use exactly the 98 rows of the full fit.\nThen\n\n$$\nb_E=\\frac{\\sum_i r_{E,i}r_{Y,i}}{\\sum_i r_{E,i}^2}\n    =r_{EY\\cdot Z}\\frac{s_{r_Y}}{s_{r_E}},\n$$\n\nwhere $Z$ denotes the control columns and $r_{EY\\cdot Z}$, the\ncorrelation of the two residual vectors, is the partial correlation. The\nnumerator is the linear co-variation left after the controls and the\ndenominator the education variation left; the ratio of residual SDs turns\nthe unit-free correlation into thousand dollars per education year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr_E <- residuals(lm(education ~ prestige + women + type, data = dat))\nr_Y <- residuals(lm(income_k ~ prestige + women + type, data = dat))\nsum(r_E * r_Y) / sum(r_E^2)\n```\n:::\n\n\nThe uncertainty must count the fitted controls. Prestige and women supply\none column each and type two, so with education and the intercept the\nmodel estimates $p=6$ coefficients from $n=98$ rows, leaving $n-p=92$\nresidual degrees of freedom. Using the residual variance $s_e^2=RSS/(n-p)$ of Section 2.2,\n\n$$\nSE(b_E)=\\sqrt{\\frac{s_e^2}\n                         {\\sum_i r_{E,i}^2}},\n\\qquad\nt_E=r_{EY\\cdot Z}\\sqrt{\\frac{n-p}{1-r_{EY\\cdot Z}^2}}.\n$$\n\nThe slope identity is algebraic; the SE and the $t_{92}$ reference for\n$H_0:\\beta_E=0$ rest on the classical model of Section 1.1. In\n@tbl-ch8-partial-df the first row is the full model's education row,\nwhich these formulas reproduce, and the second is a fresh fit of residual\nincome on residual education.\n\n\\Needspace{10\\baselineskip}\n\n| Calculation on the same 98 rows | Slope | SE | df | $t$ | $p$ |\n|:--|--:|--:|--:|--:|--:|\n| Full model `m2`, education row; the residual formulas with $n-p=92$ | 0.1164 | 0.2752 | 92 | 0.4230 | .6732 |\n| A fresh fit of residual income on residual education | 0.1164 | 0.2694 | 96 | 0.4321 | .6666 |\n\n: The residual slope reproduces the full-model coefficient; only the full model's df gives its uncertainty. {#tbl-ch8-partial-df tbl-colwidths=\"[44,11,11,8,12,14]\"}\n\nBoth rows share the slope 0.1164 and the partial correlation .0441. The\nfresh fit counts $98-2=96$ df, as if fitting the four control columns had\ncost nothing, so its SE is smaller by the factor $\\sqrt{92/96}$. Use\n`m2`, or the formulas with $n-p=92$, for uncertainty.\n\nOnly the education variation left after the controls informs this\ncoefficient: its residual SD is 0.9661 years, against 2.7489 before\nresidualizing. The added-variable display below shows what remains.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Marginal and residualized income--education comparisons in the same 98 occupations.](chapter_08_files/figure-html/fig-ch8-partial-1.png){#fig-ch8-partial fig-pos='!ht' fig-alt='The marginal scatterplot has a positive fitted line. After linearly removing prestige, women, and type from both variables, the fitted line is nearly flat and substantial residual variation remains.' width=614.4}\n:::\n:::\n\n\n@fig-ch8-partial sets the two comparisons side by side. The marginal\nline rises 0.8830 per year; after the fitted linear parts of prestige,\nwomen, and type are removed from both variables, the residual line rises\nonly 0.1164, with wide scatter around it. Residualizing removes those\n**fitted linear components**, not every substantive difference between\noccupations. The residualized panel can be drawn directly from these\ntwo residual vectors and the full model's slope.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(r_E, r_Y), aes(r_E, r_Y)) + geom_point() +\n  geom_abline(intercept = 0, slope = coef(m2)[\"education\"])\n```\n:::\n\n\n### Two covariance matrices\n\nCovariance now has two meanings. `cov()` describes how\nrecorded variables spread and move together; `vcov()` estimates the\ncovariance of the fitted coefficients. @tbl-ch8-covariance-objects\ncompares them on the same 98 rows.\n\n\\Needspace{16\\baselineskip}\n\n| | Recorded-data covariance | Coefficient covariance |\n|:--|:--|:--|\n| R call | `cov()` of income, education, prestige and women | `vcov(m2)` |\n| Rows and columns | 4 numeric variables; the type factor is left out | 6 fitted coefficients, including the intercept and two type indicators |\n| Diagonal entries | Sample variances | Squared coefficient SEs |\n| Off-diagonal entries | Sample covariances between variables | Joint uncertainty of two coefficients |\n| Education entry | 7.5567 years squared | 0.0757; its square root is the SE 0.2752 |\n| Question it answers | How the recorded variables spread and move together across occupations | How uncertain the fitted coefficients are, and how their errors move together |\n\n: Two covariance matrices from the same 98 records answer different questions. {#tbl-ch8-covariance-objects tbl-colwidths=\"[22,39,39]\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncov(dat[c(\"income_k\", \"education\", \"prestige\", \"women\")])\nvcov(m2)\n```\n:::\n\n\nThe education entries differ by a factor of about 100 because they\nmeasure different things: the spread of education across occupations\nand the squared uncertainty of one fitted coefficient. The matrices are\nnot interchangeable; Section 5 uses the coefficient covariance in\n$\\mathbf x_*^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf x_*$.\n\n### Interval and tests\n\nWith 92 residual degrees of freedom, the classical 95% interval for\neducation is\n\n$$\n\\begin{aligned}\nb_E\\pm t_{.975,92}SE(b_E)\n &=0.1164\\pm1.9861(0.2752)\\\\\n &\\approx[-0.4302,\\ 0.6631].\n\\end{aligned}\n$$\n\nUnder the classical assumptions the interval is compatible with negative\nand positive conditional slopes, including differences of several\nhundred dollars per year of education. With no margin of practical\nequivalence declared, the direction and the practically relevant size\nremain unresolved; the interval does not show that the slope is zero or\nthat adjustment has removed an effect of education.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(m2, \"education\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               2.5 %    97.5 %\neducation -0.4301895 0.6630567\n```\n\n\n:::\n\n```{.r .cell-code}\nhc3_covariance <- sandwich::vcovHC(m2, type = \"HC3\")\nhc3_se <- sqrt(hc3_covariance[\"education\", \"education\"])\ncoef(m2)[\"education\"] + c(-1, 1) * qt(.975, 92) * hc3_se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.6429122  0.8757794\n```\n\n\n:::\n:::\n\n\nHC3 keeps the coefficient and replaces its covariance estimate, giving\nSE 0.3823 and, with the same $t_{92}$ convention, the approximate\ninterval $[-0.6429,0.8758]$. It allows unequal error variances among\nindependent observations under large-sample conditions and is not an\nexact small-sample guarantee. Neither interval allows for unmodeled\ndependence, selection, measurement error, or a wrong mean form.\n\nThe matching test addresses $H_0:\\beta_E=0$ in the stated full model,\nnot \"education has no effect\". Its classical $t=0.423$ and $p=.6732$ do\nnot prove the null, and the test does not decide which of the three\nquestions deserves an answer.\n\nThe **overall $F$ test** compares the full regression with a one-mean\nmodel on the same rows, setting all $p-1$ non-intercept coefficients to\nzero. This extends Chapter 4's comparison of named mean models. Under\nthe same Normal-error conditions as the coefficient tests,\nits statistic is\n\n$$\nF_{\\mathrm{overall}}=\n\\frac{RegSS/(p-1)}{RSS/(n-p)},\n\\qquad RegSS=\\sum_i(\\widehat y_i-\\bar y)^2.\n$$\n\n\\Needspace{10\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2)$fstatistic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  value   numdf   dendf \n32.1747  5.0000 92.0000 \n```\n\n\n:::\n:::\n\n\nThe full model gives $F(5,92)=32.1747$, $p<.0001$; the education-only model on the\nsame 98 records gives $F(1,96)=47.1956$. For education alone the statistic is the square of its slope's\n$t=6.8699$. Each tests its stated joint restriction; the full-model test\ndoes not identify which coefficient differs from zero. Neither verifies the\nmean function or shows how well the fitted rule will predict a held-out\noutcome. Chapter 9 develops the general nested comparison behind this\nstatistic, its matrix form, and the contrasts, block tests, and adjusted\ngroup means that a factor with several levels invites.\n\nNot every change to a model changes the scientific estimand. In a\nrandomized study, well-specified covariate adjustment can estimate the\nsame declared average assignment effect more precisely; releveling a\nfactor changes the coefficient coordinates but not the fitted values;\nand a different uncertainty estimator changes the interval but not the\ncoefficient.\n\n## Checking the Model {#sec-ch8-check}\n\nWhat would these plots look like if the working model described the\ndata well? A fit produces numbers even when its mean or uncertainty\nmodel is unsuitable. Checking asks which part of the interpretation the\nevidence supports; no single graph passes or fails the model.\n\n### Residuals, leverage, and influence\n\nA residual is an observed deviation from a fitted value, not the\nunobserved error. Leverage measures how unusual a record's combination\nof predictor values is; a high-leverage record pulls the fit toward\nitself, so its residual tends to be smaller. A standardized residual\ntherefore divides each residual by its own estimated SD, which combines\nthe common residual scale with the record's leverage, and an externally\nstudentized residual does the same with the scale estimated with that\nrecord left out. Influence, measured by Cook's distance, combines\nleverage with the size of the residual [@cook1977]. This call lists\nthe five occupations with the largest Cook's distance.\n\n\\Needspace{8\\baselineskip}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(cooks.distance(m2), decreasing = TRUE)[1:5]\n```\n:::\n\n\n@fig-ch8-diagnostics shows four views. If the linear mean described the\nrecords well, the residuals in panel (a) would scatter evenly around zero\nwith a flat smooth; here the smooth drifts downward and the scatter\nwidens at high fitted income. With constant spread, the smooth in panel\n(b) would stay level; it rises. Panel (c) follows the Normal reference\nline in the middle but departs in both tails, most strongly on the\nright, where a few occupations earn far more than the model predicts;\non the left, ministers earn far less. The two largest positive\nresiduals, general managers and physicians in the printed list, also\nhave the largest Cook's distances, drawn as the biggest circles in\npanel (d).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Four complementary diagnostic views for the full additive model.](chapter_08_files/figure-html/fig-ch8-diagnostics-1.png){#fig-ch8-diagnostics fig-pos='!ht' fig-alt='Residual and scale plots show structure and changing spread. A normal quantile plot departs in both tails, most strongly on the right. The final panel relates leverage and studentized residuals, with point sizes indicating Cook\\'s distance.\n' width=643.2}\n:::\n:::\n\n\nThe first panel compares fitted means with observed deviations. A\nhorizontal reference at zero makes systematic departures visible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck <- data.frame(fit = fitted(m2), resid = residuals(m2))\nggplot(check, aes(fit, resid)) + geom_point() +\n  geom_hline(yintercept = 0)\n```\n:::\n\n\nThese features challenge the linear mean form and the constant-variance\ndescription, and the heavy tails matter for exact small-sample\nNormal-theory inference, although OLS can still be calculated. A large\nresidual, high leverage, and high influence are different features, and\nnone alone shows that a record is invalid. No residual graph can\nestablish that occupations are independent draws from a wider\npopulation.\n\n### Joint support and collinearity\n\nJoint support concerns combinations of predictor values. First,\n@tbl-ch8-support asks a coarser question: how far does each variable\nextend within each recorded type?\n\n```{=latex}\n\\Needspace{8\\baselineskip}\n```\n\n\n::: {#tbl-ch8-support .cell tbl-cap='Predictor ranges within each recorded occupation type.'}\n::: {.cell-output-display}\n\n\n|Type |  n|Education    |Prestige   |Women       |\n|:----|--:|:------------|:----------|:-----------|\n|bc   | 44|6.38--10.93  |17.3--54.9 |0.00--90.67 |\n|prof | 31|11.09--15.97 |53.8--87.2 |0.58--96.12 |\n|wc   | 23|9.17--12.79  |26.5--67.5 |3.16--97.51 |\n\n\n:::\n:::\n\n\nBlue-collar education ends at 10.93 years, below the professional minimum\nof 11.09, so comparing those types at the same education crosses a gap\nwith no records. The model still returns predictions there, but software\noutput does not create observations: a lack of support limits what the\ndata can say about a comparison without making the comparison undefined.\n\nDo the three values of Section 2.3's white-collar profile, education\n11, prestige 45 and women 50, occur together in the records?\nSeparate ranges cannot say. A **convex combination** of records is a\nweighted average whose weights are nonnegative and sum to one, and a\n**joint-support witness** is a convex combination of observed records\nthat returns the profile. The four white-collar records in\n@tbl-ch8-profile-support, weighted as listed, return education 11,\nprestige 45, and women 50 at once.\n\n\\Needspace{11\\baselineskip}\n\n\n::: {#tbl-ch8-profile-support .cell tbl-cap='Four observed white-collar records recover the declared profile.'}\n::: {.cell-output-display}\n\n\n|Occupation          | Education| Prestige| Women| Weight|\n|:-------------------|---------:|--------:|-----:|------:|\n|Radio/TV announcers |     12.71|     57.6| 11.15|  .2452|\n|Tellers/cashiers    |     10.64|     42.3| 91.76|  .2310|\n|Receptionists       |     11.04|     38.7| 92.86|  .2261|\n|Sales supervisors   |      9.84|     41.5| 17.04|  .2976|\n\n\n:::\n:::\n\n\nThe four weights are positive and sum to one. With the records in\n`support_rows` and the unrounded weights in `support_weights`, the\nweighted column sums recover all three profile values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolSums(support_rows * support_weights)\n```\n:::\n\n\nThe witness places the profile\ninside the joint covariate hull of the white-collar records on all three\ncontinuous predictors. It does not show that many occupations lie near\nthe profile, that one matches it exactly, or that a causal comparison is\nsupported.\n\nSection 2.2's adjusted-versus-marginal figure restricts its lines to\nnearby records. Its education ranges are plotting neighborhoods, not a\nformal guarantee of support for the full-model profile.\n\n**Collinearity** means that a predictor is strongly linearly related to\nthe other predictors, so they largely predict it, and it costs\nprecision. The auxiliary $R^2$ from regressing education on the other\npredictors, .8765, measures how strongly: they account for most of\neducation's variation, and education's **variance inflation factor** is\n\n$$\nVIF_E=\\frac{1}{1-R^2_{E\\mid P,W,T}}\\approx8.0968,\n\\qquad \\sqrt{VIF_E}\\approx2.8455.\n$$\n\n@fig-ch8-vif draws the SE multiplier $\\sqrt{VIF}$ against the auxiliary\n$R^2$ for the three continuous predictors. The curve rises slowly at\nfirst, so women (auxiliary $R^2$ .2312, multiplier 1.1405) loses little\nprecision, and it climbs steeply beyond about .8, where prestige (.8066,\nmultiplier 2.2738) and education sit.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The SE multiplier grows steeply as the other predictors account for more of a predictor's variation.](chapter_08_files/figure-html/fig-ch8-vif-1.png){#fig-ch8-vif fig-pos='!ht' fig-alt='A curve of the square root of the VIF against the auxiliary R-squared rises slowly from 1 at zero and steeply beyond about 0.8. Points mark women near 0.23 with multiplier 1.14, prestige near 0.81 with 2.27, and education near 0.88 with 2.85.' width=585.6}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2 <- summary(lm(education ~ prestige + women + type, data = dat))$r.squared\nc(VIF = 1/(1 - r2), SE_multiplier = sqrt(1/(1 - r2)))\n```\n:::\n\n\nUnder the classical model, holding the residual variance and education's\ntotal variation fixed, education's SE is 2.8455 times what it would be in\nan orthogonal design, where education is uncorrelated with the other\npredictors. This compares two variance formulas: deleting a predictor\nwould change the comparison and can change the residual variance, so a\nVIF is not a deletion rule, and near collinearity does not by itself\nbias the coefficient under the maintained zero-conditional-mean model.\n\n### Sensitivity to curvature and to one record\n\nA regression is linear in its coefficients: a squared predictor can\nenter a linear model even though its mean curve bends. Its form is a\nchanged specification to assess, not a transformation selected\nautomatically by a significant test.\n\nA component-plus-residual plot adds the fitted prestige term back to\neach residual, $e_i+\\widehat\\beta_P P_i$. In @fig-ch8-partial-residual\nthe smooth bends upward at high prestige, away from the straight fitted\ncomponent. That motivates a declared form sensitivity; it does not show\nthat any one curve is the true process.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The prestige component plus residual in the full additive model.](chapter_08_files/figure-html/fig-ch8-partial-residual-1.png){#fig-ch8-partial-residual fig-pos='!ht' fig-alt='A component-plus-residual scatterplot has a positive trend. A curved smooth bends upward at high prestige relative to the straight fitted component.\n' width=585.6}\n:::\n:::\n\n\nThe refit adds a squared prestige term to *m2*. The two fits are\n**nested**: they share the outcome and the 98 rows, and the smaller\nfit's predictors are a subset of the larger fit's. The comparison of\nnamed mean models applies here with continuous predictors. Its null hypothesis is that the squared-prestige\ncoefficient is zero, so that *m2*'s mean function suffices; the\nstatistic sets the residual sum of squares that the added term removes\nagainst the larger fit's residual variance, on 1 and $98-7=91$ degrees\nof freedom. A small $p$-value says the term removes more variation than\nthe error scale would ordinarily produce under that null. It does not\nmake the enlarged equation the correct mean function, and it is not a\nrule for choosing a model; Chapter 9 develops the general comparison.\n\n\\Needspace{26\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nch8_curve <- update(m2, . ~ . + I(prestige^2))\nanova(m2, ch8_curve)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|    Pr(>F)|\n|------:|--------:|--:|---------:|--------:|---------:|\n|     92| 630.8897| NA|        NA|       NA|        NA|\n|     91| 587.4085|  1|  43.48117| 6.736004| 0.0110146|\n\n</div>\n:::\n\n```{.r .cell-code}\nc(full_education = unname(coef(m2)[\"education\"]),\n  curve_education = unname(coef(ch8_curve)[\"education\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n full_education curve_education \n     0.11643361     -0.02980032 \n```\n\n\n:::\n:::\n\n\nThe comparison gives $F(1,91)=6.736$ and $p=.011$, and education moves\nfrom 0.1164 to $-0.0298$; in the enlarged equation the prestige slope,\n$\\beta_P+2\\beta_{P^2}P$, depends on prestige. This is a focused\nsensitivity for Pair 2, not a replacement for the prediction rule that\nPair 3 fixed in advance.\n\nGeneral managers have the largest Cook's distance, about 0.4467; a high\nincome relative to the model is not proof of an error. Refitting the\nformula to the other 97 records moves\neducation from 0.1164 to 0.4372. We keep the full-data estimate and\ndisclose the sensitivity: excluding a record needs evidence about its\ncoding, measurement, or distinctiveness, never a more attractive\n$p$-value. @tbl-ch8-checks collects what each check shows and what\nfollows for the answer.\n\n```{=latex}\n\\Needspace{30\\baselineskip}\n```\n\n| Check | What is visible here | Consequence for the answer |\n|:--|:--|:--|\n| Functional form | Adding a prestige-squared term changes the education slope to about $-0.0298$ | Treat the additive form as a working approximation; do not silently reinterpret it as an exact conditional law |\n| Spread | HC3 raises the education SE from 0.2752 to 0.3823 | Show sensitivity; a robust SE does not repair all model problems |\n| Influence | Removing the record for general managers, which has the largest Cook's distance, gives an education slope about 0.4372 | Inspect the record and disclose sensitivity; do not delete it merely to obtain a preferred result |\n| Collinearity | Education's auxiliary $R^2$ is .8765 | Little education variation remains after the other predictors; separate conditional coefficients can be imprecise |\n| Joint support | Professional and blue-collar education ranges do not overlap | Cross-type comparisons at common covariates may depend heavily on extrapolation |\n| Dependence and scope | Occupational aggregates have shared economic and classification contexts | Independence and same-source transport are assumptions, not verified by a residual plot |\n\n: Checks change the bounded answer rather than producing one omnibus pass/fail score. {#tbl-ch8-checks tbl-colwidths=\"[19,38,43]\"}\n\nAppendix B gives the formulas for Cook's distance, the HC3 covariance,\nthe generalized VIF, and the model-comparison criteria; the results\nneeded to interpret the answer are all in this section.\n\n## Fitted and Standardized Quantities {#sec-ch8-quantities}\n\nThe fitted model also gives quantities for particular profiles: a fitted\nmean with its two intervals, and an average over a named set of\nprofiles. These are teaching extensions of the model, not further\nanswers the study owes; Pair 2 remains about $\\beta_E$.\n\n### A fitted mean and its two intervals\n\nFor a complete input row, `predict()` returns two intervals:\n`interval = \"confidence\"` concerns the model's mean at that profile, and\n`interval = \"prediction\"` concerns one new outcome at the same profile.\nBoth use the full fitted model and its classical assumptions.\n\n\\Needspace{17\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprofile <- data.frame(education = 11, prestige = 45, women = 50,\n                      type = factor(\"wc\", levels = levels(dat$type)))\npredict(m2, newdata = profile, interval = \"confidence\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 5.588634 4.486469 6.690799\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(m2, newdata = profile, interval = \"prediction\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit       lwr      upr\n1 5.588634 0.2722037 10.90506\n```\n\n\n:::\n:::\n\n\nWhere do these intervals come from? Use the Section 2.3 profile vector\n$\\mathbf x_*=(1,11,45,50,0,1)^{\\mathsf T}$. With\n$\\widehat{\\mathbf V}$, the coefficient\ncovariance of Section 3.2, the fitted mean and its estimated classical\nvariance are\n\n$$\n\\widehat m_*=\\mathbf x_*^{\\mathsf T}\\widehat{\\boldsymbol\\beta},\\qquad\n\\widehat{\\operatorname{Var}}(\\widehat m_*)=\\mathbf x_*^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf x_*,\n\\quad \\widehat{\\mathbf V}=\\operatorname{vcov}(m2).\n$$\n\nThe variance includes the coefficient variances **and their\ncovariances**: two terms $a\\widehat\\beta_j+b\\widehat\\beta_k$ contribute\n$a^2\\widehat{\\operatorname{Var}}(\\widehat\\beta_j)+\nb^2\\widehat{\\operatorname{Var}}(\\widehat\\beta_k)+\n2ab\\widehat{\\operatorname{Cov}}(\\widehat\\beta_j,\\widehat\\beta_k)$.\nAdding coefficient SEs, or ignoring the covariances, is a different\ncalculation, and the square root comes only after the variance is\ncomplete. Here the fitted mean is 5.5886, its variance 0.308, and its SE\n0.5549 thousand dollars, giving the fitted-mean interval\n$[4.4865,6.6908]$ that `predict()` printed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(drop(row %*% vcov(m2) %*% row))\n```\n:::\n\n\n**One new outcome** adds its own error variance, $s^2=6.8575$, so its SE\nis $\\sqrt{s^2+\\mathbf x_*^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf x_*}\\approx2.6768$\nand its interval $[0.2722,10.9051]$. @fig-ch8-bands draws both intervals\nacross the white-collar education range at prestige 45 and women 50. The\ndark fitted-mean band is narrowest near education 11.2, about 2.2\nthousand dollars wide, and widens toward the edges of the records, to\nabout 3.1 at 9.17 years. The light band for one new occupation stays\nbetween about 10.6 and 10.9 wide along the whole range, because the new\noccupation's error variance, 6.8575, dominates a fitted-mean variance of\nabout 0.3.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Two 95% intervals for a white-collar profile at prestige 45 and women 50, across the white-collar education range.](chapter_08_files/figure-html/fig-ch8-bands-1.png){#fig-ch8-bands fig-pos='!ht' fig-alt='A nearly flat fitted line runs from about 5.4 to 5.8 thousand dollars as education rises from 9.17 to 12.79 years. A narrow dark band around it, the fitted-mean interval, is narrowest near 11 years and widens toward both ends. A much wider light band, the interval for one new occupation, runs from about 0 to 11 thousand dollars along the whole range. A dotted vertical line marks education 11.' width=585.6}\n:::\n:::\n\n\nBoth intervals rest on the independent, Normal, common-variance model,\nwhich the checks of Section 4 qualify rather than confirm; replacing\n$\\widehat{\\mathbf V}$ with HC3 alone does not estimate a new outcome's\nconditional error distribution. Neither interval says how accurately a\nlearning rule predicts held-out records; that is Pair 3's question.\n\n### Standardizing over the observed profiles\n\nA standardized fitted value averages over a named set of profiles rather\nthan using one. Copy the 98 observed profiles, change every type to\nwhite-collar, predict each fitted value, and average them with equal\nweights.\n\n\\Needspace{11\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwhite_profiles <- dat\nwhite_profiles$type <- factor(\"wc\", levels = levels(dat$type))\nmean(predict(m2, newdata = white_profiles))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.016406\n```\n\n\n:::\n:::\n\n\nThe result, 7.0164, is an average of model predictions after a specified\nchange of profile, not the observed white-collar group mean. Every one\nof the 98 profiles receives weight $1/98$. For its uncertainty, use\nSection 5.1's coefficient-covariance formula with the average of these\n98 design rows replacing the single profile row $\\mathbf x_*$. This\ngives SE 0.6177 and classical interval $[5.7896,8.2432]$, treating the\nprofiles and weights as fixed. The predictions share fitted coefficients;\naveraging their interval endpoints would ignore that joint uncertainty.\nRepeating the operation for each type gives @tbl-ch8-standardized,\nwhich sets the results beside the observed\nmean income of each type.\n\n\\Needspace{9\\baselineskip}\n\n| Type | Observed mean | Standardized estimate | SE | Lower | Upper |\n|:--|--:|--:|--:|--:|--:|\n| bc | 5.3741 | 6.7811 | 0.6942 | 5.4023 | 8.1598 |\n| prof | 10.5595 | 7.1053 | 0.9011 | 5.3156 | 8.8950 |\n| wc | 5.0523 | 7.0164 | 0.6177 | 5.7896 | 8.2432 |\n\n: Observed type means and empirical-profile standardization under the full additive model. {#tbl-ch8-standardized tbl-colwidths=\"[12,18,22,14,17,17]\"}\n\nThe observed means differ sharply: professional occupations average\n10.5595 thousand dollars, about twice the other two types, but they also\nhave more education, higher prestige, and different percentages of\nwomen. The standardized estimates give every type the same 98 profiles,\nso they differ only by the type coefficients, 0.3242 for professional\nand 0.2353 for white-collar relative to blue-collar.\n\nBecause *m2* is linear and additive in the continuous predictors, its\naverage fitted value equals its fitted value at their means (education\naverages 10.7951 years); with squared terms, interactions, or a\nnonlinear response function, the prediction at the means need not equal\nthe mean prediction. Any other fixed weighting used for all three\ntypes, whether another named set of profiles or unequal weights on these\n98, would move the three standardized levels but leave their differences\nat the type coefficients.\n\nRelabelling every profile professional or white-collar creates some\ncombinations the records do not support, and averaging does not remove\nthat problem; the white-collar profile of Section 5.1 is a different,\nlocally supported quantity. Standardization alone neither identifies a\ncausal effect nor validates out-of-sample performance.\n\n\\Needspace{12\\baselineskip}\n\n## The Held-Out Prediction Question {#sec-ch8-prediction}\n\n### Learning rules and the loss\n\nA learning rule says how training records become a prediction equation.\nOur two rules are fixed: education-only OLS, and the full additive OLS\nequation with education, prestige, women, and type. OLS **fits** by\nminimizing squared training errors; we separately choose the **mean\nabsolute error (MAE)** to evaluate the predictions in income units.\n\nA prediction opportunity here is a hypothetical same-source occupation\nwhose predictors are all available before its income is used, not a\nforecast from information that arrives later. The records cannot show\nthat this exchangeability holds for other countries, periods, individual\nworkers, or types absent from the dictionary.\n\nFor held-out outcomes $y_i$ and predictions $\\widehat y_i^{(-)}$ fitted\nwithout those outcomes,\n\n$$\nMAE=\\frac{1}{n_{\\mathrm{test}}}\n       \\sum_{i\\in\\mathrm{test}}\\left|y_i-\\widehat y_i^{(-)}\\right|.\n$$\n\nA smaller MAE means a smaller average absolute error on the evaluated\ncases, not a better prediction for every case.\n\n### Shared ten-fold validation\n\nIn shared ten-fold cross-validation the 98 records are divided into ten\nfolds, and each fold takes a turn as the held-out set: both rules are\nfitted to the other records and predict the held-out cases\n(@fig-ch8-folds), and the 98 case-level errors are then pooled.\n@tbl-ch8-validation records the protocol.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Shared held-out cases let two fixed learning rules face the same prediction task.](chapter_08_files/figure-html/fig-ch8-folds-1.png){#fig-ch8-folds fig-pos='!ht' fig-alt='A training-record box branches to education-only OLS and full OLS. Both arrows lead to predictions for the same held-out records, then to paired absolute errors. The diagram is repeated over ten folds.' width=604.8}\n:::\n:::\n\n\n\\Needspace{17\\baselineskip}\n\n| Decision | Frozen teaching protocol | Why it matters |\n|:--|:--|:--|\n| Candidates | Education-only and the declared full additive OLS rule | No search for the best-looking model after validation |\n| Folds | Shared balanced random ten-fold assignment, seed 80806 | Both rules face the same held-out cases |\n| Summary | Pool absolute errors over all 98 held-out cases | Each case receives equal weight; folds of different size do not |\n| Sensitivity | 200 new resplits of the same records, seed 80807 | Describes sensitivity to splitting, not new independent studies |\n\n: The internal-validation protocol was fixed before this teaching comparison. {#tbl-ch8-validation tbl-colwidths=\"[20,42,38]\"}\n\nThis is a retrospective reanalysis of familiar data, so \"fixed before\nthis comparison\" is not a claim of historical preregistration. It means\nthat the candidates were not revised after the primary errors were seen.\nThe sensitivity refits of Section 4 are not added to the candidate set.\nThe 98 complete rows, unit conversion and type dictionary stay fixed.\nEvery training set must contain all types and have full column rank.\nOne fold illustrates the protocol: fold 9 holds the first source record,\ngovernment administrators, with eight other occupations. `train` contains\nthe other 89 records and `held` these nine cases. Both rules use the\nsame training records and predict the same held-out records.\n\n\\Needspace{10\\baselineskip}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfold_simple <- lm(income_k ~ education, data = train)\nfold_full <- lm(income_k ~ education + prestige + women + type,\n                data = train)\npred <- predict(fold_full, newdata = held)\n```\n:::\n\n\nBoth fits exclude government administrators' outcome. Every training\nset in this comparison contains all three types and has full column\nrank, so both specified rules are estimable. Chapter 13 develops the\nvalidation protocol further.\n\nNo held-out outcome is used to estimate a coefficient. Learned\npreprocessing, such as scaling, imputation, or variable selection, would\nalso have to be fitted on training records only; a fixed unit conversion\nsuch as dollars to thousands is not learned.\n\n### Held-out errors and resplits\n\nFor government administrators, observed income is 12.351 thousand\ndollars. The full-rule prediction is 11.5948, giving\n\n$$\n|12.351-11.5948|=0.7562,\n$$\n\nand the education-only prediction is 8.9461, giving\n$|12.351-8.9461|=3.4049$.\nThis record favors the full rule, but one record is not the comparison;\n@tbl-ch8-mae pools all 98 errors.\n\nFor the nine cases in the illustrated fold, the MAE formula becomes\none average of absolute prediction errors:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(abs(held$income_k - pred))\n```\n:::\n\n\nThe table uses the errors from **all ten folds**, so every one of the\n98 records contributes once.\n\n| Learning rule | Held-out MAE (thousand dollars) |\n|:--|--:|\n| Education-only OLS | 2.4031 |\n| Full additive OLS | 1.5412 |\n| Difference: full minus education-only | $-0.8619$ |\n\n: Case-weighted absolute errors from the frozen shared-fold comparison. {#tbl-ch8-mae tbl-colwidths=\"[60,40]\"}\n\nThe full rule's average held-out absolute error is about 862 dollars\nlower. Because the two errors are subtracted for **each same case**\nbefore averaging, differences in difficulty between cases cannot favor\neither rule through different test sets. The same predictions give the\nroot mean squared error, which weights large errors more heavily: 3.5051\nfor education-only and 2.7111 for the full rule, the same preference\nhere, although the two losses need not agree in other data.\n\nEight fits use 88 training records and two use 89; the pooled errors\ndescribe the learning rules at those training sizes, not the one\nequation fitted to all 98. Chapter 13, Section 2, develops the full\nprotocol and the training-size mixture.\n\nThe 200 resplits give differences from $-0.914$ to $-0.741$, all\nfavoring the full rule; this is sensitivity to splitting the same\nrecords, not a confidence interval from independent studies.\nNew-sample uncertainty is not quantified, so the advantage remains\nprovisional.\n\nThe comparison supports lower internal held-out error for the full rule\nin these records under this protocol. It does not isolate the predictive\ncontribution of education, because the rules differ by prestige, women,\nand type together, and it does not establish external transport,\nindividual earnings prediction, or a causal education effect.\n\n\\Needspace{14\\baselineskip}\n\n## Reading and Evaluating the Three Answers {#sec-ch8-coordinate}\n\n### The study report\n\n```{=latex}\n\\Needspace{20\\baselineskip}\n```\n\n| Pair and role | Question | Estimand and owed answer |\n|:--|:--|:--|\n| **1. Contextual description** | How does income vary linearly with education across the 98 retained occupations? | The finite-record marginal least-squares slope; a descriptive answer for these records |\n| **2. Primary conditional association** | How does income differ with education at the same prestige, percentage of women, and type, within support? | The linear conditional-mean coefficient $\\beta_E$ under the declared working model; fitted $b_E$ is its estimate from the 98 retained records |\n| **3. Secondary prediction analysis** | Does the full additive learning rule predict eligible same-source occupation records with lower expected absolute error than the education-only rule? | Difference in expected absolute error of the two learning procedures at the declared training sizes; an internal validation answer |\n\n: Three separately owed answers in the occupation teaching study. {#tbl-ch8-pairs tbl-colwidths=\"[22,36,42]\"}\n\nEach row is a question--answer pair with **one argument with linked\nlayers**. The three are not statistical strands of one argument: the\nreport owes separate conclusions about marginal association, conditional\nassociation, and prediction. Estimands become strands only when one\nintegrated conclusion needs them all, and printing several coefficients\ncreates neither extra questions nor extra strands.\n\nThe report below gathers the analyses of Sections 1--6. It is our\nteaching record, not a statement by the source investigators.\n\n> **R0 -- Common record and declared scope.** We analyzed the 98 complete\n> occupation records described in @sec-ch8-questions. Income was\n> scaled to thousand\n> 1971 Canadian dollars. Education and income were historical occupational\n> averages; prestige came from an earlier rating survey. We retained the\n> same rows for all three questions and make no claim of verified probability\n> sampling or randomized education.\n>\n> **R1 -- Marginal answer.** Across these records the education-only\n> least-squares slope was 0.883 thousand dollars per year. This is a\n> descriptive linear summary: occupations with more education tended to\n> have higher average income. It is not an individual or causal effect.\n>\n> **R2 -- Conditional answer.** The intended estimand was the linear\n> conditional-mean education coefficient $\\beta_E$, comparing education at the\n> same prestige, percentage of women, and occupational type. Its fitted\n> estimate was $b_E=0.1164$, with a classical 95% interval [$-0.4302$, 0.6631]\n> under the independent linear conditional-mean working model with common\n> variance. HC3 gave [$-0.6429$, 0.8758]. Influence, functional-form, and support\n> checks limit that model's interpretation. The direction and practically\n> relevant magnitude remain unresolved under these calculations; the result\n> does not establish no conditional relationship.\n>\n> **R3 -- Prediction answer.** The two fixed OLS learning rules were compared\n> with the shared ten-fold protocol in @sec-ch8-prediction. The full\n> rule had MAE\n> 1.5412 versus 2.4031 for education-only, difference $-0.8619$. The examined\n> resplits all favored the full rule. This is internal evidence about\n> learning procedures trained on 88/89 eligible records under the stated\n> same-source exchangeability assumptions. Lower expected error is a\n> provisional conclusion because new-sample uncertainty is not quantified;\n> this is not external validation of a final 98-record equation.\n>\n> **R4 -- Synthesis.** Education has a positive marginal linear association\n> with income in these historical records. Its conditional association is\n> imprecisely resolved by the specified additive model, while the full\n> learning rule predicts the held-out records more accurately than the\n> education-only rule. These conclusions answer different questions and\n> do not establish that changing education would change income.\n\n### Functions and traces in the report\n\nReading starts by locating what each passage does. In Chapter 1's\nterms, a component is a logical function, such as STAT-E or SUB-J, and\nthe report's study-specific content serves it. One passage can serve\nseveral functions. R0, for example, identifies the records for STAT-E\nand supplies their historical context for SUB-E. It would become\njustification (J) content only if it offered a reason connecting those\nrecords to an inference; \"we used R\" offers none. @tbl-ch8-traces lists\neach function once, with the content shared by the three pairs and the\ncontent specific to each.\n\n| Function | Shared or pair-specific content | Trace in this teaching record |\n|:--|:--|:--|\n| **STAT-E** | Named 98 rows, variables, exclusions, and computations' inputs | R0; the row audit and import code in @sec-ch8-questions |\n| **SUB-E** | Occupations rather than workers; historical dollars, education, ratings, and types | R0; variable/source descriptions |\n| **STAT-J** | Pair 1: fixed-record least-squares definition. Pair 2: declared stochastic model and uncertainty conditions. Pair 3: held-out fitting, fixed rules, loss, and exchangeability | R1--R3; model declaration; validation protocol and code |\n| **SUB-J** | Reasons connecting those measurements and comparisons to historical occupational income, with limits on individual, current, and causal interpretations | R0--R3; unit/time explanations and prediction-opportunity definition |\n| **STAT-I** | Pair 1's 0.8830 slope; Pair 2's 0.1164 estimate, intervals, coefficient test and checks; Pair 3's case-level errors, MAEs, and split sensitivity | @sec-ch8-estimate through @sec-ch8-prediction; R1--R3 |\n| **STAT-C** | Descriptive positive marginal slope; unresolved conditional slope under the model; smaller internal error for the full rule under the protocol | R1, R2, and R3 respectively |\n| **SUB-I** | Interpret years, income units, conditioning, and prediction errors in the named historical occupation setting | Worked substitutions and error calculation; R1--R3 |\n| **SUB-C** | Each question-facing answer with its own limits; none supplies a causal or individual-earnings answer | R1--R3; their distinctions preserved in R4 |\n\n: Reading the linked-layer functions without three duplicate maps. {#tbl-ch8-traces tbl-colwidths=\"[15,47,38]\"}\n\nSUB-E situates the evidence, SUB-J **augments and contextualizes** the\nstatistical justification, SUB-I interprets the inference, and SUB-C\nbounds the substantive answer. Sharing a dataset does not make Pair 2's\nindependent-error model into Pair 3's validation procedure.\n\nFor each supporting statement, record what the report says and where\nthe reader finds it: in the report, the data documentation, or the\nexecutable calculations. Gaps and conflicts are stated in ordinary\nprose. R2 states the independence assumption, for example, but nothing in\nthe record shows that independence holds under the original selection of\noccupations; a stated assumption and evidence for it are different\ninformation. The unit conversion, by contrast, makes reading 0.883\nthousand dollars as about 883 dollars traceable. This record contains no\nconflicting source, though a real study may contain incompatible\ndescriptions to record and investigate. A reason's documentary status is\nsimply what has been stated or located and which support is missing; it\nis not a quality score or a set of categories to learn.\n\nProfessional knowledge helps identify a trace's function but does not\nlicense adding an unreported design feature. An invalid reason such as\n\"all rows are in the same dataset, therefore they are independent\" is\nstill **stated J**, whose adequacy is judged separately: reading records\nthe reason actually offered, not a repaired one.\n\n### Evaluating each answer\n\nEvaluation now judges the quality of the reasoning just identified.\nChapter 1's six questions apply to each argument (@tbl-ch8-quality); they\nare not six scores to total.\n\n| Quality-evaluation question | Application to these arguments |\n|:--|:--|\n| **Question alignment** | R1 matches its finite-record slope. R2 names $\\beta_E$, its fitted estimate, the conditioning set, and the model extension. R3 names the learning procedure, loss, and training sizes rather than substituting a coefficient test. |\n| **Evidence integrity** | The 102-to-98 accounting and common rows are explicit. Missing type still limits what is represented. CV excludes held-out outcomes from fitting; source selection is not repaired by that procedure. |\n| **Justification adequacy** | Least squares is sufficient for the declared finite description. Pair 2's model conditions and Pair 3's same-source exchangeability remain assumptions with incomplete empirical support. Statistical computation alone cannot establish them. |\n| **Inferential adequacy** | The slope, intervals, error arithmetic, and comparisons are reproducible. Neither zero-crossing nor a large p-value proves absence; repeated folds are not independent replication. Substantive reasoning must retain those distinctions. |\n| **Transition fidelity** | Occupation-level average income remains occupation-level average income; partial adjustment is not a causal intervention, and model fit is not held-out performance. |\n| **Claim calibration** | R1 remains finite and historical; R2 reports unresolved magnitude/direction rather than no relationship; R3 remains internal and procedure-specific. No claim extends to individual workers or modern populations. |\n\n: Apply the six questions before evaluating the study-level synthesis. {#tbl-ch8-quality tbl-colwidths=\"[28,72]\"}\n\nChapter 1 distinguishes judgments about a reason from the conclusion\nabout a whole question--answer pair. Here the finite description is\n**supported as stated**; the explicitly unresolved conditional answer is\nalso **supported as stated**, under its disclosed model limits. A\ncorrectly reported inconclusive answer need not establish a stronger\nclaim to be supported. The prediction comparison is supported as a\nqualified internal result, while external superiority of the final\nall-record equation is **not assessable from the accessible record**.\nArgument Chapter B, Section 4, develops the full judgment account and\nits alternatives.\n\n### Is the synthesis coherent?\n\nCoordinated questions add one evaluation question, **Cross-question\ncoherence**: does the synthesis preserve the distinct questions,\nestimands, methods, analytic statuses, uncertainty, and limits of the\nseparate answers? We introduce it here; Argument Chapter B develops it\nfurther but is not needed to apply it.\n\nR4 reports a positive marginal slope, an unresolved conditional slope,\nand better internal prediction. **Predict and explain:** can an interval\nthat includes zero for the education coefficient coexist with a lower\nheld-out MAE for the full rule? Identify the question each result\nanswers before reading this alternative synthesis:\n\n> Once the other predictors were controlled, education had no effect;\n> nevertheless, the significant full regression proves it will predict\n> workers' incomes accurately.\n\nThe results can coexist: the interval concerns one conditional\ncoefficient, whereas the rules differ by prestige, women and type\ntogether. Better predictions from the full rule do not isolate\neducation's contribution. R4 retains these distinct answers.\n\nReading first identifies the inference and claim the alternative offers. Evaluation\nthen finds three failures: \"no effect\" substitutes a causal null for the\nconditional-association answer, an omnibus significance test is not\nheld-out validation, and occupations have become workers. The corrected\nsynthesis is R4, not a fourth overarching argument that erases the\nseparate conclusions.\n\nThese records were collected for earlier purposes, not prospectively\nfor our three teaching questions. Chapter 1's repair-versus-new-cycle\nrule applies: correcting an error under the same target is a repair;\nchoosing a causal target after seeing an association is a revised or\nnew cycle whose timing must be stated. Argument Chapter B, Section 5,\ndevelops the full coordinated construction workflow.\n\n## Reading Bridge {#sec-ch8-summary}\n\nStart with a model naming its outcome, predictors, coefficients and\nerror variation. The known process showed partial slopes at fixed other\npredictors before the occupation records supplied estimates. Multiple\nregression adds conditional comparisons without conferring automatic\ncausal control. Subtracting fitted means showed what a coefficient compares;\nresidualizing connected it to covariance; residual, influence, support,\nand precision checks each bounded the answer differently; a fitted\nprofile and a standardized average extended the conditional model; and\nheld-out errors answered a separately owed question. The occupation study\nowed three answers, a finite-record marginal description, a working-model\nconditional interval with unresolved magnitude, and a qualified internal\nprediction comparison, and its shared records made the questions\ncoordinated without making their justifications identical. Chapter 9 develops extensions of this model (factors with several levels and their\ncontrasts, nested model comparison and information criteria, changed\npredictor and outcome forms, and robust, clustered, and bootstrap\nuncertainty) and transfers the reading to Project STAR, where a\nrandomized design supplies a different warrant. Chapter 10 then extends\nthe interaction reasoning of Chapters 4 and 6 to regression.\n\n\\Needspace{22\\baselineskip}\n\n### Key terms {.unnumbered}\n\nUse this short reference to revisit the concepts introduced here. The\nPart One Concept Reference gives the broader reference and the principal home\nof each concept; the simple-regression, interval, ANOVA, and reading\nvocabulary used in this chapter is explained in Chapters 1--4 and 7.\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Multiple regression (multiple regression model; additive model) | A model in which an outcome's mean is an intercept plus one term per predictor, $E(Y\\mid x_1,\\ldots,x_{p-1})=\\beta_0+\\beta_1x_1+\\cdots+\\beta_{p-1}x_{p-1}$, with errors of one common SD $\\sigma$; its $p$ coefficients leave $n-p$ residual df, and least squares estimates them. Each coefficient compares means at the same values of the other predictors; the additive form assumes each comparison is the same across those values. |\n| Partial slope (conditional coefficient; adjusted coefficient) | The difference in fitted outcome per one-unit difference in one predictor, holding the model's other predictors fixed. Its meaning depends on the conditioning set named with it; it is not an intervention effect or a claim about unmeasured differences. |\n| Indicator variable (dummy variable) and reference category | A 0/1 variable marking membership in one category of a factor; a factor with $J$ levels needs $J-1$ indicators, and the omitted level is the reference. The intercept refers to the reference category; each indicator coefficient is a difference from it at the same other predictors. Releveling changes coordinates, not fitted values. |\n| Partial regression (residualization; added-variable form) | Regressing both the outcome and one predictor on the other predictors, then relating their residuals. The residual slope equals the partial slope; the residual correlation is the partial correlation, unit-free. |\n| Coefficient covariance matrix | The estimated variances and covariances of the fitted coefficients (`vcov()` in R). Any linear combination of coefficients, such as a fitted mean or a contrast, has variance $\\mathbf c^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf c$; adding SEs or ignoring covariances is a different, incorrect calculation. |\n| Variance inflation factor (VIF) | One divided by one minus the $R^2$ from regressing a predictor on the other predictors. Its square root multiplies that coefficient's SE relative to an orthogonal design, holding residual variance fixed; it describes precision, not bias, and is not a deletion rule. |\n| Joint support (covariate hull) | Whether a combination of predictor values lies within the region where observations actually occur, not merely within each variable's separate range. A fitted value outside joint support is extrapolation even if each coordinate is observed somewhere. |\n| Standardization over a named distribution (model-averaged fitted value) | Averaging the model's fitted values after setting one predictor to a chosen value for every profile in a declared set with fixed weights. Its uncertainty uses the coefficient covariance; it is not an observed group mean, a causal effect, or held-out performance. |\n| Learning rule (learning procedure) | A fixed recipe that turns training records into a prediction equation, such as fitting a declared OLS formula. Prediction performance concerns the rule at stated training sizes, not one final fitted equation. |\n| Cross-validation (held-out validation) | Dividing records into folds, fitting a rule on the other folds, predicting the held-out fold, and pooling the errors so that no outcome contributes to its own prediction. Resplits describe sensitivity to the partition, not new independent studies. |\n| Mean absolute error (MAE) | The average absolute difference between held-out outcomes and their predictions, in outcome units. It is an evaluation loss chosen separately from the squared-error criterion that OLS minimizes. |\n| Cross-question coherence | The additional evaluation question for coordinated answers: does the synthesis preserve the distinct questions, estimands, methods, uncertainty, and limits of the separate answers rather than merging them into one omnibus claim? |\n\n: Selected concepts for multiple regression across coordinated questions. {#tbl-ch08-key-terms tbl-colwidths=\"[28,72]\"}\n\n\n### Further reading {.unnumbered}\n\n- The [OpenIntro multiple-predictor tutorial](https://openintro-ims.netlify.app/model-mlr)\n  offers concrete equations and indicator interpretations; this chapter\n  borrows its equation-first device but not its stepwise selection.\n- The [ISLR regression lab](https://hastie.su.domains/ISLR2/Labs/Rmarkdown_Notebooks/Ch3-linreg-lab.html)\n  connects fitting, coefficients, checks, and predictions, and the\n  [ISLR cross-validation lab](https://hastie.su.domains/ISLR2/Labs/Rmarkdown_Notebooks/Ch5-resample-lab.html)\n  develops the train, predict, and check sequence [@james2021].\n- The [carData documentation](https://cran.r-project.org/web/packages/carData/carData.pdf)\n  [@carData2022; @fox2019] supplies the Prestige variable meanings and\n  provenance; the three questions and the R0--R4 report are this\n  chapter's own.\n- Fox [@fox2016] and Kutner and colleagues [@kutner2005] develop the\n  linear-model algebra behind partial slopes, indicators, and\n  diagnostics, and Argument Chapter B develops coordination and its\n  auxiliary construction workflow in greater detail.\n\n## Exercises {.unnumbered}\n\nUse the supplied numbers; rounding within 0.02 thousand dollars is\nacceptable unless a different precision is requested. These prompts do not\nrequire Argument Chapter B or the appendices.\n\n\\Needspace{18\\baselineskip}\n\n<!-- prompt-id: CH08-E01 -->\n### Exercise 1: Keep the three answers distinct (Foundational) {.unnumbered #ex-ch08-01}\n\nA report promises: (a) a description of education and income across 98\noccupations, (b) an education comparison at the same prestige, women, and\ntype, and (c) a comparison of two prediction rules on held-out records.\n\n1. Explain why these are three question--answer pairs rather than three\n   statistical strands serving one integrated answer.\n2. For each, name its estimand in plain language and one kind of output\n   that could contribute to its answer.\n3. Does sharing the same 98 records establish the same justification for\n   all three? Give one concrete reason.\n\n\\Needspace{18\\baselineskip}\n\n<!-- prompt-id: CH08-E02 -->\n### Exercise 2: Name what changes (Foundational) {.unnumbered #ex-ch08-02}\n\nClassify each change as primarily changing the records, the comparison,\nthe coefficient coordinates, or the uncertainty calculation. State whether\nit necessarily creates a new scientific question.\n\n1. Refit education-only regression after excluding four missing-type records.\n2. Add prestige, women, and type to the education-only association equation.\n3. Change the reference category from blue-collar to white-collar.\n4. Keep the fitted equation but replace classical SEs with HC3 SEs.\n\nFinally, explain why appropriately specified adjustment in a randomized\nstudy need not change its declared average assignment-effect estimand.\n\n<!-- prompt-id: CH08-E03 -->\n### Exercise 3: Interpret a fitted comparison (Foundational) {.unnumbered #ex-ch08-03}\n\nUse this rounded hypothetical equation, with income in thousand dollars:\n\n$$\n\\widehat y=1+0.20e+0.10p-0.04w+0.30D_{\\mathrm{prof}}\n           +0.15D_{\\mathrm{wc}}.\n$$\n\n1. Two white-collar profiles share prestige $p=40$ and women $w=50$;\n   one has education $e=12$ and the other $e=10$. Which terms cancel\n   when their fitted means are subtracted? Give the modeled difference\n   and interpret it in dollars.\n2. What does the coefficient 0.15 compare, and at which values of the\n   other predictors?\n3. What must be checked before calling the education comparison in\n   part 1 supported by the observed data?\n4. Why is the modeled difference not an estimate of the effect of\n   giving a worker two more years of education?\n\n\\Needspace{18\\baselineskip}\n\n<!-- prompt-id: CH08-E04 -->\n### Exercise 4: Read held-out errors (Foundational) {.unnumbered #ex-ch08-04}\n\nFour held-out occupations have the observed incomes and predictions\nbelow, in thousand dollars. Each prediction was fitted without the\ncorresponding outcome.\n\n| Occupation | Observed | Education-only prediction | Full-rule prediction |\n|:--|--:|--:|--:|\n| 1 | 5 | 4 | 6 |\n| 2 | 8 | 10 | 8 |\n| 3 | 10 | 7 | 9 |\n| 4 | 13 | 12 | 11 |\n\n1. Calculate the MAE of each rule.\n2. Explain why the average of the four paired differences, full minus\n   education-only, equals the difference between the two MAEs, and why\n   it matters that both rules predict the same four occupations.\n3. Does the better average rule have to be better for every\n   occupation? Point to the table.\n4. Explain why this comparison is neither a coefficient interval nor\n   validation of a model subsequently fitted to all available records.\n\n\\Needspace{22\\baselineskip}\n\n<!-- prompt-id: CH08-E05 -->\n### Exercise 5: Locate a reason before judging it (Integrative) {.unnumbered #ex-ch08-05}\n\nAn accessible report states:\n\n> We retained the same 98 occupations for both equations. This makes the\n> observations independent. The full equation has higher training\n> $R^2$, so we conclude it predicts new occupations more accurately.\n\nThe report provides import code and fitted-model output, but no validation\nsplit, held-out predictions, or study-specific evidence about dependence.\n\n1. Identify the reasons offered, the inference, and the claim.\n2. Record the documentary status of the independence reason and the\n   held-out prediction evidence separately. Do not rewrite “stated” as\n   “not located” merely because a reason is wrong.\n3. Apply Justification adequacy, Inferential adequacy, and Claim calibration.\n4. Give a whole-pair evaluation conclusion for the prediction answer and\n   name the additional work it would require.\n\n\\Needspace{25\\baselineskip}\n\n<!-- prompt-id: CH08-E06 -->\n### Exercise 6: Evaluate the study-level synthesis (Integrative) {.unnumbered #ex-ch08-06}\n\nUse the occupation study's reported results: marginal slope 0.883;\nfitted conditional estimate $b_E=0.1164$ of $\\beta_E$, with classical\ninterval [$-0.4302$, 0.6631];\nand held-out MAEs 2.4031 for education-only versus 1.5412 for the full rule.\n\nA summary says:\n\n> Education does not matter after adjustment, but the model proves that\n> increasing workers' education raises income and predicts earnings well\n> in other countries.\n\n1. Predict whether the conditional interval's including zero conflicts\n   with the full rule's lower held-out MAE. Explain which question each\n   result answers, then identify the claims actually offered in the\n   summary before evaluating them.\n2. Identify which separate answer obligation is being replaced or exceeded\n   by each clause.\n3. Apply Cross-question coherence and write a corrected three-sentence\n   synthesis that retains the three reported answers and their limits.\n4. If the authors now want a causal effect of education, is that a repair\n   of their existing uncertainty calculation or a new/revised question-level\n   cycle? Explain.\n\n## Appendix A: Omitted Variables and Group Means {.unnumbered #app-ch8-a}\n\nThis appendix develops the mathematics behind @sec-ch8-comparisons. Its\noccupation calculations use the same 98-row object *dat*, the models *m0*,\n*m1*, and *m2* of the main text, and the type codes *bc*, *prof*, and\n*wc*; they introduce no other sample. Chapter 9 develops contrasts, block\ntests, adjusted means, the matrix form, and the Project STAR transfer.\n\n### Why the marginal slope includes another association {.unnumbered}\n\nSuppose a population process is\n\n$$\nY=\\beta_0+\\beta_X X+\\beta_Z Z+\\varepsilon,\n\\qquad E(\\varepsilon\\mid X,Z)=0,\n$$\n\nwith finite variances and $\\operatorname{Var}(X)>0$. The marginal\nleast-squares slope is a covariance divided by a variance. Substituting\nthe outcome equation gives\n\n$$\n\\begin{aligned}\n\\frac{\\operatorname{Cov}(X,Y)}{\\operatorname{Var}(X)}\n&=\\frac{\\beta_X\\operatorname{Var}(X)\n+\\beta_Z\\operatorname{Cov}(X,Z)\n+\\operatorname{Cov}(X,\\varepsilon)}{\\operatorname{Var}(X)}\\\\\n&=\\beta_X+\\beta_Z\n\\frac{\\operatorname{Cov}(X,Z)}{\\operatorname{Var}(X)}.\n\\end{aligned}\n$$ {#eq-ch8a-omission}\n\nThe zero-error-covariance condition removes the final term. The sample\ncounterpart holds exactly for least-squares fits on the same rows, as\nSection 2.2's prestige and women calculations show. The\ndiscrepancy therefore involves both the association between $X$ and $Z$\nand $Z$'s coefficient in the outcome model; neither ingredient alone\ndetermines its size. If the target is the conditional coefficient,\nomitting $Z$ creates bias relative to that target. If the target is the\nmarginal slope, that marginal quantity is not a biased version of an\nunstated conditional target. The two coefficients name different\ncomparisons, and neither supplies a causal warrant for observational\nvariables.\n\n### Repeated samples from the known process {.unnumbered}\n\nLet independent standard Normal variables $X$ and $U$ generate\n$Z=.65X+\\sqrt{1-.65^2}U$, so that both predictors have variance one and\ncorrelation .65. Independently generate a Normal error with SD 6, and set\n\n$$\nY=50+2X+5Z+\\varepsilon.\n$$ {#eq-ch8a-sim-process}\n\nThis is the process of @sec-ch8-comparisons: the marginal slope is\n$2+5(.65)=5.25$ and the conditional $X$ slope is 2. The sample in\n@fig-ch8-known-process has 250 observations and uses seed 82108. Its\nmarginal slope is 5.9971 and its conditional slope 3.0259: within two SEs of their\ntargets, as Section 1.3 reads from the generated sample.\n\nA separate repeated-study design, with its own stated sample size, shows\nthe sampling variation: 1,000 samples of 150 observations each, with seed\n82109. Each sample fits the marginal and conditional equations to new\nobservations from the same process. The density curves summarize their\nestimated slopes.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-ch8a-repeated .cell tbl-cap='Targets and results across 1,000 generated samples.'}\n::: {.cell-output-display}\n\n\n|Model       | Target|   Mean|     SD|\n|:-----------|------:|------:|------:|\n|Marginal    |   5.25| 5.2581| 0.5952|\n|Conditional |   2.00| 2.0010| 0.6707|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Sampling distributions around two different targets.](chapter_08_files/figure-html/fig-ch8a-repeated-1.png){#fig-ch8a-repeated fig-pos='!ht' fig-alt='Separate panels show marginal slopes centered near 5.25 and conditional slopes centered near 2. Dashed lines mark their respective population targets.\n' width=585.6}\n:::\n:::\n\n\nBoth procedures center near their own targets. The conditional estimates\nare more variable here, because separating correlated predictors leaves\nless residual variation in $X$. That is a result of this specified\nprocess, not a general promise that adjustment always lowers precision:\nprognostic covariates and their relations to the focal predictor both\nmatter. A simulation shows the consequences of its assumptions; it cannot\ncertify the observational occupation study.\n\n\\Needspace{12\\baselineskip}\n\n### Fitted group means from indicators {.unnumbered}\n\nStart with a model containing only the three-level type factor. With\nblue-collar as reference,\n\n$$\n\\widehat y_g=\\widehat\\alpha+\n\\widehat\\delta_{\\mathrm{prof}}D_{\\mathrm{prof}}+\n\\widehat\\delta_{\\mathrm{wc}}D_{\\mathrm{wc}}.\n$$\n\nThe fitted means are $\\widehat\\mu_{\\mathrm{bc}}=\\widehat\\alpha$,\n$\\widehat\\mu_{\\mathrm{prof}}=\\widehat\\alpha+\\widehat\\delta_{\\mathrm{prof}}$,\nand $\\widehat\\mu_{\\mathrm{wc}}=\\widehat\\alpha+\\widehat\\delta_{\\mathrm{wc}}$.\nOLS minimizes squared deviations separately within each group, so these\nequal the observed group means; the hats distinguish fitted summaries\nfrom hypothetical population means.\n\n@tbl-ch8a-group-means reads the fit on the 98 records. The group-only\ncoefficients are $\\widehat\\alpha=5.3741$, $\\widehat\\delta_{\\mathrm{prof}}=5.1853$\nand $\\widehat\\delta_{\\mathrm{wc}}=-0.3218$; each fitted mean combines them\nas the indicator columns direct and equals the observed mean income of\nits type. Sums of the rounded coefficients can differ from the fitted\nmeans in the last digit.\n\n\\Needspace{9\\baselineskip}\n\n| Type | $D_{\\mathrm{prof}}$ | $D_{\\mathrm{wc}}$ | Coefficients combined | Fitted mean | Observed mean |\n|:--|--:|--:|:--|--:|--:|\n| bc | 0 | 0 | $\\widehat\\alpha$ | 5.3741 | 5.3741 |\n| prof | 1 | 0 | $\\widehat\\alpha+\\widehat\\delta_{\\mathrm{prof}}$ | 10.5595 | 10.5595 |\n| wc | 0 | 1 | $\\widehat\\alpha+\\widehat\\delta_{\\mathrm{wc}}$ | 5.0523 | 5.0523 |\n\n: The type-only regression reproduces the three observed group means. {#tbl-ch8a-group-means tbl-colwidths=\"[10,10,10,34,18,18]\"}\n\nThis group-only description is not the adjusted type comparison in *m2*,\nwhere the indicators compare fitted values at the same education,\nprestige, and percentage of women. The factor is one term represented by\ntwo columns; it is neither an ordered numeric score nor one selected\nreference-category coefficient.\n\n\\Needspace{8\\baselineskip}\n\nReleveling changes the intercept and indicator coefficients, not the\nfitted values, the residuals, or a fixed substantive contrast;\nreleveling leaves the fitted values equal up to floating-point noise. No new question\nappears merely because the coordinates changed. Centering the continuous\npredictors likewise changes the intercept's reference profile without\nchanging the fitted values, and it cannot create cross-type support.\n\n## Appendix B: Formulas Behind the Checks and Criteria {.unnumbered #app-ch8-b}\n\nThis appendix gives the formulas and fuller tables behind Sections 3\nand 4, on the same *dat*, *m0*, *m1*, and *m2*. None of these refinements supplies a missing\ndesign, measurement, independence, or transport warrant.\n\n\\Needspace{12\\baselineskip}\n\n### Cook's distance {.unnumbered}\n\nWith $p$ coefficient columns including the intercept, leverage is\n$h_{ii}=\\mathbf x_i^{\\mathsf T}(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf x_i$. Cook's distance can be calculated as\n\n$$\nD_i=\\frac{e_i^2}{p s^2}\\frac{h_{ii}}{(1-h_{ii})^2}\n=\\frac{(\\widehat{\\boldsymbol\\beta}-\\widehat{\\boldsymbol\\beta}_{(-i)})^{\\mathsf T}\\mathbf X^{\\mathsf T}\\mathbf X\n(\\widehat{\\boldsymbol\\beta}-\\widehat{\\boldsymbol\\beta}_{(-i)})}{p s^2}.\n$$\n\nThe second expression measures the change in all coefficients when\nrecord $i$ is deleted, in the design matrix's metric rather than as an\nunweighted sum of squared coefficients with incompatible units.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n```\n\n\n::: {#tbl-ch8b-influence .cell tbl-cap='The five largest Cook\\'s distances in the full fit.'}\n::: {.cell-output-display}\n\n\n|Occupation       |  Residual| Leverage| Cook's distance|\n|:----------------|---------:|--------:|---------------:|\n|general.managers |   14.2061|   0.0775|          0.4467|\n|physicians       |   11.0092|   0.0785|          0.2724|\n|ministers        | $-7.7616$|   0.0396|          0.0628|\n|lawyers          |    5.3848|   0.0628|          0.0504|\n|surveyors        | $-4.9007$|   0.0634|          0.0422|\n\n\n:::\n:::\n\n\nGeneral managers have the largest Cook's distance, approximately 0.4467,\nand Section 4.3 explains why the record is inspected and retained.\nRefitting without it moves education from 0.1164 to 0.4372, and the type\ncoefficients move as well. The comparison records a diagnostic perturbation of the fit,\nnot six new research questions or evidence that the reduced sample is\npreferable.\n\n\\Needspace{9\\baselineskip}\n\n### The HC3 covariance {.unnumbered}\n\nFor independent observations, the HC3 covariance estimator is\n\n$$\n\\widehat{\\mathbf V}_{\\mathrm{HC3}}=(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\n\\left\\{\\sum_i \\mathbf x_i\\mathbf x_i^{\\mathsf T}\\frac{e_i^2}{(1-h_{ii})^2}\\right\\}\n(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}.\n$$\n\nThe outer factors are the familiar design component. The middle\ncomponent lets each record carry its own residual scale, inflated for\nleverage [@long2000; @zeileis2004]. The OLS coefficients do not change;\nonly their covariance does, as @tbl-ch8b-hc3 shows for all six\ncoefficients; `vcovHC()` evaluates this covariance calculation.\n\n\n::: {#tbl-ch8b-hc3 .cell tbl-cap='Coefficient estimates and two covariance summaries.'}\n::: {.cell-output-display}\n\n\n|Term        |  Estimate| Classical SE| HC3 SE|\n|:-----------|---------:|------------:|------:|\n|(Intercept) |    0.4205|       1.9573| 2.7741|\n|education   |    0.1164|       0.2752| 0.3823|\n|prestige    |    0.1406|       0.0354| 0.0387|\n|women       | $-0.0535$|       0.0097| 0.0079|\n|typeprof    |    0.3242|       1.4631| 2.0928|\n|typewc      |    0.2353|       0.9848| 1.0548|\n\n\n:::\n:::\n\n\nEducation's HC3 SE is 0.3823 rather than 0.2752, and with $t_{92}$ as an\napproximate reference the interval is $[-0.6429,0.8758]$; this is not an\nexact finite-sample HC3 coverage result. Women's HC3 SE is smaller than\nits classical counterpart: robust covariance need not widen every\ninterval.\n\nFor a maintained linear conditional mean, HC3 addresses unequal variance\namong independent observations. For a random-design best-linear-projection\ntarget, a suitable sandwich covariance can support large-sample\nprojection inference without making the mean exactly linear. Neither use\nrepairs measurement error, dependence, selection, causal identification,\nor absent joint support.\n\n\\Needspace{13\\baselineskip}\n\n### VIF and generalized VIF {.unnumbered}\n\nFor a single predictor column, the classical conditional variance of its\ncoefficient can be written\n\n$$\n\\operatorname{Var}(\\widehat\\beta_j\\mid\\mathbf X)=\n\\frac{\\sigma^2}{\\sum_i(X_{ij}-\\bar X_j)^2}\n\\frac{1}{1-R_j^2}.\n$$\n\nHere $R_j^2$ comes from regressing that predictor on the remaining\ncolumns, including the intercept. The variance inflation factor is\n$VIF_j=1/(1-R_j^2)$, and its square root is an SE multiplier, holding the\nresidual variance and the focal predictor's variation fixed\n[@kutner2005]. Education gives $R_j^2=.8765$, VIF 8.0968, and SE\nmultiplier 2.8455 (Section 4.2), from the auxiliary regression or\n`car::vif(m2)`. The education--prestige\ncorrelation is .8665, but the VIF uses all the other columns, not just\nthat pair.\n\nThe two-column type term has a generalized VIF. Its raw GVIF is 7.7001;\nthe dimension-adjusted value $GVIF^{1/(2\\,df)}=1.6658$ is on a scale\ncomparable to the square root of a one-column VIF [@fox2019], whereas the\nraw two-column GVIF is not comparable with an ordinary one-column VIF.\n\nExact collinearity makes the design rank-deficient. Near collinearity\nleaves the coefficients estimable but possibly imprecise, and under the\nmaintained zero-conditional-mean model it does not by itself bias OLS. A\ncutoff of 5 or 10 neither establishes the model's assumptions nor\njustifies removing a variable the question requires. Measurement problems\nneed their own evidence: the familiar attenuation story requires\nclassical error assumptions and is not a rule for every coefficient in a\nmultiple-predictor model.\n\n### The Normal likelihood, AIC, and BIC {.unnumbered}\n\nChapter 6 varied the candidate probability for a fixed binomial count of\n32 successes in 50 trials. Here the data again stay fixed, but the\nresponse is continuous and the parameters are several coefficients plus\nan error scale. For a declared independent Normal linear model, the\n**likelihood** is the joint density of the observed outcomes at their\nfixed predictor values, viewed as a function of those parameters; it is\nnot a probability assigned to a parameter, nor the probability of the\nexact observed vector. The **log-likelihood** adds the log densities of\nthe independent records.\n\nWrite the predictor row for record $i$ as $\\mathbf x_i^{\\mathsf T}$ and let $\\sigma>0$ be the\nerror SD. Before fitting, the log-likelihood is\n\n$$\n\\ell(\\boldsymbol\\beta,\\sigma)=-n\\log\\sigma-\\frac n2\\log(2\\pi)\n-\\frac{1}{2\\sigma^2}\\sum_i(y_i-\\mathbf x_i^{\\mathsf T}\\boldsymbol\\beta)^2.\n$$\n\nAt any fixed positive scale only the last term changes with the\ncoefficients, so maximizing over $\\boldsymbol\\beta$ minimizes the residual\nsum of squares: the Normal maximum-likelihood coefficients equal the OLS\ncoefficients. This connects Chapter 7's squared-loss criterion to this\nparticular distributional model, although least squares did not need the\nmodel to calculate a minimizing line.\n\nMaximizing over the scale gives\n$\\widehat\\sigma_{\\mathrm{ML}}=\\sqrt{RSS/n}$, whereas the residual SD used\nfor classical coefficient uncertainty is $s=\\sqrt{RSS/(n-p)}$, with $p$\ncounting the regression coefficients. The two serve different purposes,\nand the ML scale, not the residual SD, belongs in the fitted likelihood.\nAt the fitted coefficients and ML scale,\n\n$$\n\\ell(\\widehat{\\boldsymbol\\beta},\\widehat\\sigma_{\\mathrm{ML}})\n=-\\frac n2\\left\\{\\log(2\\pi)+1+\\log(RSS/n)\\right\\}.\n$$\n\nR's `logLik()` returns this maximized value for an `lm()` fit: the Normal\nlog densities of the 98 outcomes at their fitted means and the ML scale\nadd to the same number. Two\ninformation criteria combine it with a penalty for the number of\nparameters:\n\n$$\nAIC=-2\\log\\widehat L+2k,\\qquad\nBIC=-2\\log\\widehat L+k\\log n.\n$$\n\nHere $k$ counts the regression coefficients **and** the estimated\nresidual variance, so the full occupation model has $k=7$. Smaller values\nare preferred under each criterion; neither is a held-out MAE\n[@akaike1974; @schwarz1978]. For *m2* the ML scale is 2.5373 and the\nresidual SD 2.6187; the maximized log-likelihood is $-230.302$, so its\nAIC is 474.6040 and its BIC 492.6988.\n\n@tbl-ch8b-criteria compares the three declared models on the same 98\nrows, response scale, and likelihood convention. Its adjusted $R^2$, $1-(1-R^2)(n-1)/(n-p)$,\ncharges each added coefficient a small penalty: it rises only when the\nadded terms' nested-model $F$ statistic exceeds 1. Like $R^2$, AIC and\nBIC, it is computed from the fit to the same 98 rows, so it is an\nin-sample summary, not a held-out measure. Chapter 11 develops likelihood\nfitting further for binomial outcomes; this local Normal-model\ncalculation does not need it.\n\n\\Needspace{9\\baselineskip}\n\n| Model | $k$ | $R^2$ | Adjusted $R^2$ | AIC | BIC |\n|:--|--:|--:|--:|--:|--:|\n| m0 | 3 | .3296 | .3226 | 526.5052 | 534.2601 |\n| m1 | 4 | .4996 | .4891 | 499.8328 | 510.1727 |\n| m2 | 7 | .6362 | .6164 | 474.6040 | 492.6988 |\n\n: In-sample summaries for comparable income models. {#tbl-ch8b-criteria}\n\nA criterion printed for a log-income model is not comparable with these\nraw-income values, because changing the response scale changes the\nlikelihood's reference measure; a common-scale comparison would need the\ncorresponding transformation adjustment.\n\nNo residual graph establishes independence: the occupations share one\nhistorical labour market, and clustered or repeated records would need\ndependence-aware uncertainty, which HC3 alone does not supply. Rules\nfor choosing a causal adjustment set, about confounders, mediators, and\ncolliders, apply to a declared causal target (Chapter 14), not to\nassociation or prediction.\n\n\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_08_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}