{
  "hash": "de1ff6924a6dd22f7168db55cfaec7f0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Quantitative Research Journey\"\nauthor: \"Jinsong Chen\"\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\nreferences:\n  - id: hernan2020causal\n    type: book\n    title: \"Causal inference: What if\"\n    author:\n      - family: Hernán\n        given: Miguel A.\n      - family: Robins\n        given: James M.\n    issued:\n      date-parts: [[2020]]\n    publisher: Chapman & Hall/CRC\n    URL: https://miguelhernan.org/whatifbook\n  - id: angrist1996iv\n    type: article-journal\n    title: \"Identification of causal effects using instrumental variables\"\n    author:\n      - family: Angrist\n        given: Joshua D.\n      - family: Imbens\n        given: Guido W.\n      - family: Rubin\n        given: Donald B.\n    issued:\n      date-parts: [[1996]]\n    container-title: Journal of the American Statistical Association\n    volume: 91\n    issue: 434\n    page: 444-455\n    DOI: 10.1080/01621459.1996.10476902\n  - id: box1976\n    type: article-journal\n    title: \"Science and statistics\"\n    author:\n      - family: Box\n        given: George E. P.\n    issued:\n      date-parts: [[1976]]\n    container-title: Journal of the American Statistical Association\n    volume: 71\n    issue: 356\n    page: 791-799\n    DOI: 10.1080/01621459.1976.10480949\n  - id: box1979\n    type: chapter\n    title: \"Robustness in the strategy of scientific model building\"\n    author:\n      - family: Box\n        given: George E. P.\n    editor:\n      - family: Launer\n        given: Robert L.\n      - family: Wilkinson\n        given: Graham N.\n    issued:\n      date-parts: [[1979]]\n    container-title: Robustness in Statistics\n    publisher: Academic Press\n    publisher-place: New York\n    page: 201-236\n  - id: bloom2015wfh\n    type: article-journal\n    title: \"Does working from home work? Evidence from a Chinese experiment\"\n    author:\n      - family: Bloom\n        given: Nicholas\n      - family: Liang\n        given: James\n      - family: Roberts\n        given: John\n      - family: Ying\n        given: Zhichun Jenny\n    issued:\n      date-parts: [[2015]]\n    container-title: The Quarterly Journal of Economics\n    volume: 130\n    issue: 1\n    page: 165-218\n    DOI: 10.1093/qje/qju032\n  - id: realinho2022\n    type: article-journal\n    title: \"Predicting student dropout and academic success\"\n    author:\n      - family: Realinho\n        given: Valentim\n      - family: Machado\n        given: Jorge\n      - family: Baptista\n        given: Luís\n      - family: Martins\n        given: Mónica V.\n    issued:\n      date-parts: [[2022]]\n    container-title: Data\n    volume: 7\n    issue: 11\n    page: 146\n    DOI: 10.3390/data7110146\n  - id: uci697\n    type: dataset\n    title: \"Predict students' dropout and academic success\"\n    author:\n      - family: Realinho\n        given: Valentim\n      - family: Vieira Martins\n        given: Mónica\n      - family: Machado\n        given: Jorge\n      - family: Baptista\n        given: Luís\n    issued:\n      date-parts: [[2021]]\n    publisher: UCI Machine Learning Repository\n    DOI: 10.24432/C5MC89\n  - id: bates2015lmm\n    type: article-journal\n    title: \"Fitting linear mixed-effects models using lme4\"\n    author:\n      - family: Bates\n        given: Douglas\n      - family: Mächler\n        given: Martin\n      - family: Bolker\n        given: Ben\n      - family: Walker\n        given: Steve\n    issued:\n      date-parts: [[2015]]\n    container-title: Journal of Statistical Software\n    volume: 67\n    issue: 1\n    page: 1-48\n    DOI: 10.18637/jss.v067.i01\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    documentclass: scrartcl\n    fontsize: 11pt\n    linestretch: 1.06\n    geometry: margin=1in\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    keep-tex: false\n    include-in-header:\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          % Preserve the imported PDF's transparency group in an outer Form XObject.\n          % Exact-token checks fail on an unexpected driver so the patch can be reviewed.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup\\clearpage}\n          \\usepackage{caption}\n          \\captionsetup[table]{position=above,format=plain,justification=raggedright,singlelinecheck=false,labelsep=newline,labelfont=bf,textfont=it}\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\renewcommand{\\arraystretch}{1.1}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\n\n::: {.callout-note title=\"Chapter overview\"}\nThis chapter follows the research journey from questions to data, research\ndesign, methods, and interpretation. Published studies of student outcomes and working\nfrom home, together with invented feedback, measurement, and language\nexamples, make the ideas concrete. The feedback study then shows how\nthese contributions form an argument. Reading and comprehending a study\nis the approach's primary use; evaluating its quality is a separate\nsecondary use that depends on that reading. A brief construction\nworkflow offers auxiliary guidance for conducting research. Fuller\ndocumentary readings and coordinated studies are supplementary depth.\nBy the end of the chapter you will be able to frame a concern as a\nquestion with an estimand, identify the data and how they were produced,\nrecognize a method family and the reasons for its use, distinguish an\nestimate from its uncertainty and interpretation, and follow the support\nto a bounded answer.\n:::\n\nFive concerns give the methods in this chapter a purpose. A college\nwants to identify students who may need support. Teachers wonder whether\na different feedback format would help students learn. An employer is\nconsidering working from home. A researcher wants to understand\nstudents' confidence and sense of belonging. A language program wants\nto follow how its students progress over a year.\n\nHow can a concern become a quantitative question, and how do measurement,\ndesign, and statistical methods connect that question to an answer with\nstated bounds?\n\n## From a Substantive Problem to a Quantitative Question\n\nWhy do some students thrive while others struggle? What shapes a\nperson's decision to seek help? Does a change in working conditions\nimprove performance? Curiosity about social and behavioral life often\nbegins with questions like these. They are familiar enough to invite an\nimmediate explanation, yet complex enough that several explanations may\nseem plausible. Personal experience can suggest a useful idea. Research\ngives us ways to examine that idea beyond the experiences that first\nbrought it to mind.\n\n**Empirical research** grounds knowledge in systematically obtained\nobservations and experience. Researchers connect what they propose to\nwhat they can observe, then use those observations to develop, examine,\nor revise their account. An explanation about motivation, for example,\nneeds some way of connecting that idea to students' responses or\nbehavior. Theory helps decide what would be informative; observation\nhelps reveal where an expectation holds, where it changes, and what\nremains unresolved.\n\nQuantitative research is one way of being empirical. It records\nobservations numerically and uses statistical methods to study\n**variation**: differences across people, places, conditions, and time.\nThe numbers might be amounts, scores, or counts of people in categories.\nTheir value comes from what they represent and the comparisons they\nmake possible. Qualitative research also uses empirical evidence;\nmixed-methods research brings quantitative and qualitative inquiry\ntogether. The methods developed here are quantitative.\n\nA social or behavioral outcome usually varies for many reasons at once.\nAny statistical model selects some of those features and leaves others\nin the background. **Parsimony** is a useful modeling principle: seek a\nreasonably simple account that retains what matters for the question.\nA more elaborate model earns its complexity when it represents\nimportant differences or improves the intended inference. When we try\nto model the complexity of the world with parsimony, a familiar caution\napplies: as the statistician George Box put it, all models are wrong,\nbut some are useful [@box1976; @box1979]. A model earns its place by\nwhat it helps us learn, rather than by reproducing every feature of\nthe world.\n\nSome questions go further than describing variation. They ask whether\nchanging one thing would produce a change in another. **Causal\nquestions** require support for that proposed comparison, beyond\nobserving that two things vary together. They are one important kind of\nquantitative question, alongside questions about what is present, how\nvariables are associated, and what can be predicted. The kind of answer\nwanted determines what the research needs to establish.\n\nThe five opening concerns each present a different research difficulty.\n\n**Student support: who might need help?** A college wants to help\nstudents before difficulties accumulate. Prior grades, age, finances,\ncourse choices, and family circumstances may all matter. Students share\ncourses and enter in different years, while their eventual outcomes\nbecome known much later. At enrollment, the college can act only on\ninformation available then. Which of those details could help it\nrecognize a need for support?\n\n**Feedback: would a different format help?** Teachers spend considerable\ntime commenting on assignments, yet students repeat similar mistakes.\nLearning also depends on prior achievement, the teacher, and the class.\nClassmates share conditions, and students may respond differently to the\nsame comments. Teachers choose formats for reasons that may themselves\naffect learning. How could a study distinguish what the feedback\ncontributes?\n\n**Working from home: what changes?** An employer wonders whether working\nfrom home helps or harms performance. Job responsibilities, tenure, home\nconditions, and commuting may matter, and performance changes from week\nto week. Employees who volunteer to work from home may differ from\nothers. The arrangement could affect performance through several\nintervening changes. What comparison would help the employer understand\nits consequences?\n\n**Confidence and belonging: what do students feel?** A college wants to\nknow whether students feel able to handle their coursework and whether\nthey feel part of the academic community. Neither feeling appears on a\ntranscript, and students may describe similar experiences in different\nwords. A student who is confident about the work can still feel out of\nplace. How could a college find out what its students feel?\n\n**Language progress: what changes over a year, and for whom?** A\nlanguage program wants to know how students improve across a year.\nProgress may come quickly at first and then slow, and two students who\nfinish at the same level may have arrived there very differently.\nClassmates also share a teacher and a timetable. What would show how\nlearning unfolds and how students differ?\n\nThese complexities give statistical methods a purpose. Several\nsimultaneous influences motivate comparisons that take more than one\nvariable into account. Ideas such as confidence need observable\nindicators. Shared classrooms and repeated occasions call for attention\nto dependence. Self-selection makes design important, and intervening\nchanges invite questions about pathways.\n\n### Questions, aims, theory, and hypotheses\n\nTake the feedback concern: \"Does a different kind of feedback improve\nstudents' learning?\" It is a useful starting point, but *learning* could mean\nperformance on an immediate quiz, a delayed assessment, course\ncompletion, or confidence. *Students* could refer to one class or to a\nwider educational system. *Improve* could refer to a change observed\nover time or to an effect caused by the feedback. An answerable\nquantitative question names whom or what it concerns, the outcome,\nthe comparison or relationship, and the kind of answer sought.\n\nA **topic** identifies an area of interest, such as student support. An\n**aim** states what the study intends to accomplish: for example, to\nassess how well information available at enrollment predicts later\nrecorded student outcomes. A **research question** expresses the uncertainty\nmore directly: how well does a stated prediction rule perform for new\nstudents represented by these data? An aim can be sufficiently\nspecific to supply a question even when a paper has no sentence ending\nwith a question mark.\n\nSubstantive theory helps explain why the question matters and what might\nbe expected. A theory of feedback might propose that explanations help\nstudents recognize errors and choose more effective practice. A\n**substantive hypothesis** could therefore predict better achievement\nunder explanatory feedback than under the usual format. In the invented\nfeedback study, classes in both conditions follow the same six-week\nprogram; the feedback format differs.\nThat expectation also suggests possible measurements,\nsuch as practice time and the kinds of errors students make.\n\nA **statistical hypothesis** states a proposition about a specified\nstatistical quantity or model. For the feedback question, one\nproposition, the one a test usually assumes, is that the average\nassignment effect on the follow-up score is zero. That proposition is\nthe **null hypothesis**. It is more precise, and narrower in scope, than\nthe theory that feedback helps learning, and Section 4.4 shows how the\nevidence is examined for compatibility with it. A statistical test\nexamines a proposition under stated conditions; the broader educational\nexplanation needs additional support.\n\nA **result** is a quantity produced by analysis, such as a mean,\ndifference, interval, or prediction. A **claim** is a statement the\nresearchers make after interpreting the result. These terms are related,\nbut they are not interchangeable. The order of responsibility is:\n\n1. The question states the answer obligation.\n2. A hypothesis may record an expectation before the focal evidence is\n   examined.\n3. Analysis produces one or more results.\n4. Reasoning connects those results to an eventual bounded answer, which\n   may itself be inconclusive.\n\nDescriptive and exploratory questions can be valuable without a\ndirectional hypothesis. When a hypothesis is present, its content and its\ntiming are separate pieces of information. A hypothesis about a mean\ndifference has the same statistical meaning whether formulated before\ndata collection or suggested by a plot; its status as prospectively\nspecified or exploratory differs. A transparent study preserves both.\n\n### Description, association, prediction, and causal effects\n\nConsider four questions a college might ask. How are recorded student\noutcomes distributed? How is admission grade associated with those\noutcomes? How well does an enrollment-time prediction rule perform for\nother students? What would a feedback intervention change in achievement?\nAdministrative records contribute to the first three; an intervention\nstudy can supply a designed comparison for the fourth. A common interest\nin student success gives these questions context, while their intended\nanswers require different support.\n\nThese are **descriptive**, **associational**, **predictive**, and **causal**\nquestions. @tbl-journey-question-modes summarizes their different\ntasks. Its third column introduces the **estimand**: the quantity the study\nseeks to learn. The next subsection explains how to specify it.\n\nFor the feedback question, the **causal effect** is the contrast between\nthe achievement outcomes that would occur under assignment to explanatory\nfeedback and to the usual format for the same students. That contrast could be zero.\nLearning about it requires a comparison supported by the study design and\nits assumptions; Section 3.1 develops this reasoning.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Mode | Beginner question form | Example estimand | Typical support question |\n|:--|:--|:--|:--|\n| **Descriptive** | What is present, how much is there, or how is it distributed? | A mean or proportion for a named group, place, and period | Are the cases and measurements suitable for what is being described? |\n| **Associational** | How do measured variables differ or vary together? | A difference or relationship for named variables and cases | Does the comparison describe an association without implying causation? |\n| **Predictive** | How well can an outcome be predicted for new cases, settings, or times? | A specified performance measure for a stated prediction rule in a defined population of new cases, settings, or times | Was prediction checked on suitable observations not used to fit the procedure? |\n| **Causal** | What would differ under one intervention or exposure rather than another? | An average outcome contrast under two named alternatives | Do the design and assumptions permit the intended causal comparison? |\n\n: Four question modes, example estimands, and support questions. {#tbl-journey-question-modes tbl-colwidths=\"[18,27,25,30]\"}\n\nA descriptive answer may be exactly what a decision requires. Knowing\nwhich students are missing from a service can be more useful than fitting\na complex model to those already attending. Likewise, a prediction can\nbe useful without explaining why an outcome occurs, provided its\nperformance and intended use are understood. The four modes describe\ndifferent tasks rather than a ranking of research quality.\n\nThe word *explain* deserves attention. Explaining an observed admission-grade\nassociation may mean describing how recorded outcomes vary with that grade. Explaining\na causal mechanism asks how changing something produces a change in an\noutcome. A regression equation can organize the first task without\nestablishing the second.\n\nMeasurement and growth questions fit within this map. Describing the\nrelationships among confidence indicators is an associational task;\npredicting later achievement from them is predictive. Describing an\naverage achievement trajectory differs from asking whether a policy\ncauses that trajectory to change. The subject matter and the intended\nclaim work together to define the question.\n\n### The estimand and the eventual answer\n\nAn **estimand** is the target quantity: what the study seeks to learn for\nthe named units, conditions, outcome, and scope. An **estimate** is the\nnumerical value calculated from the available data. Put simply, the\nestimand is what you want to learn; the estimate is what the analysis\nproduces as its numerical approximation [@lundberg2021].\n\nFor the student-outcomes question, an estimand could be a probability of\nrecorded Dropout status at a specified admission grade and age. For\nfeedback, it could be the average difference in follow-up achievement if\nthe same eligible students' classes were assigned explanatory feedback\nrather than the usual format. For prediction, it could be a stated\nrule's average probability prediction error for new students represented\nby the source dataset: on average, how far the probabilities the rule\nassigns fall from what actually happened for students it has not seen.\nA predicted probability for one student is an output of that rule; its\nperformance across new students is a different quantity. A later question\nabout next year's entrants adds a future-cohort scope that also needs\nevidence about stability over time.\n\nThese specifications carry information that an everyday question can\nleave implicit. A feedback-effect estimand needs the students of\ninterest, the two assignments being compared, the assessment and its\ntiming, and the way individual effects are averaged. An average that gives\neach student equal weight can differ from one that gives each school\nequal weight when school sizes vary. Both can be useful, but they answer\ndifferent questions.\n\nFor a purely descriptive question about a complete, fixed dataset, the\nestimand may be its exact mean or proportion. Once those data are\navailable, calculating that quantity leaves no sampling uncertainty about\nthat particular dataset. Questions about recording errors, missing people,\nor a wider population can still remain. The word *estimand* identifies\nthe quantity sought; it leaves the source and extent of uncertainty to be\nspecified.\n\nAn estimand usually supplies the numerical focus of a **question-answer\npair**. The question states what needs answering, and the reported claim\nsupplies the study's eventual answer. A readable question can remain short,\nwith its full specification beside it. For the feedback study:\n\n> **Question:** What is the average effect of assigning\n> explanatory feedback rather than the usual format on the\n> eligible students' follow-up achievement?\n>\n> **Specification:** The students belong to 24 participating classes in\n> 12 schools. Achievement is the score on a common 0-40 assessment two\n> weeks after a six-week program. The comparison gives each of the 480\n> eligible students equal weight and concerns assignment of their class\n> to a format, regardless of their individual attendance.\n\n## Producing Evidence: From People and Concepts to Data\n\nData are recorded information, and a dataset organizes that information\nfor a study. It is already the product of several decisions. Someone\ndefined eligibility, selected a\nsource, administered an instrument, recorded a response, or applied a\ncoding rule. Understanding those decisions makes the numbers informative.\n\nBegin with information about one student in each case. The student-outcomes\ndataset combines admission information with an eventual administrative\noutcome, so its variables concern different times. The feedback dataset\ncombines the student's assigned class, format, and delayed assessment\nscore. Understanding whom and what the data describe gives meaning to\na count, average, or comparison.\n\nThis section follows how a study produces evidence: what it concerns,\nhow measurements are made, how observations connect, and what becomes\navailable for analysis. Chapter 2 takes the resulting dataset as its\nstarting point. It develops the reading of records, layouts, variable\nforms, and codes, then establishes which observations support each\ncalculation. Understanding the study gives meaning to the file; examining\nthe file shows how those meanings are represented in the analysis.\n\n### Units, variables, and study scope\n\nFor the student-support concern, a real study provides a useful dataset.\nRealinho and colleagues studied dropout and academic success at a\nPortuguese polytechnic [@realinho2022]. The released file contains 4,424\nstudents: 1,421 with recorded **Dropout** status, 794 **Enrolled**, and\n2,209 **Graduate** at the normal duration of their degree [@uci697].\nThe study built machine-learning models to predict these outcomes. A\nsimplified analysis here uses logistic regression, which we will\ndescribe in words before following its implications.\n\nA **case** is the entity or measurement occasion described by the data;\nhere each case is a student. A **unit** is the entity selected, assigned,\nmeasured, or analyzed in a particular operation. These operations may\nconcern different entities. In the feedback study, whole classes receive\nan assignment, achievement is measured on students, and the analysis\ncompares the class means under the two formats. Identifying the operation makes the\nunit clear. Measurement units such as points or minutes have a different\nrole: they express the amount recorded, rather than identifying the\nentity studied. Section 2.3 uses these entities to explain the connections\namong their observations.\n\nA **population** is the collection of units a question concerns. A\n**sample** is a set of units selected or observed from that collection. The scope\ndepends on the question: the participating students may themselves be the\npopulation of interest for a narrowly specified assignment effect. A\nwider question about all students in the region would need an account of\nhow the participants relate to that wider population.\n\nA **variable** is a characteristic that can take different values across\nunits or occasions. Admission grade, age at enrollment, course, and\nrecorded student status are variables in the administrative file.\nQuantitative variables express amounts: time on task is a continuous\nmeasurement, while an approved-unit count or a whole-number score takes\ndiscrete values. Categorical variables identify groups. Course is\nnominal, with no intrinsic order; a low-to-high confidence rating is\nordinal, with an order but no established equal spacing. A Dropout\nindicator is binary, with two categories. A numerical course code remains\ncategorical because its number names a course rather than an amount.\nChapter 2 develops these forms and their implications for calculations.\n\nIn the released student data, $1{,}421/4{,}424\\approx0.3212$, or 32.1203%,\nhave recorded Dropout status. A Dropout-versus-other-status question\ncombines the 794 Enrolled and 2,209 Graduate students as the other\ncategory, while keeping their distinct meanings. Recorded Dropout can\ninclude changing course or institution; it need not mean leaving higher\neducation altogether [@realinho2022; @uci697].\n\nVariables also have **roles** in a question. The outcome is what an\nanalysis seeks to describe, compare, or predict; predictors help express\nits relationship with other information. In the simplified student-outcome\nanalysis, recorded Dropout is the outcome to be predicted, while admission\ngrade and age at enrollment are predictors. Achievement is an outcome when\nasking about feedback, but prior achievement can be a predictor when\nforecasting a later recorded outcome. The same kind of score can therefore serve\ndifferent roles at different times or in different questions.\n\nThe prediction time also determines which information is available.\nFirst-semester results arrive too late for a prediction made at enrollment,\nhowever strongly they relate to the eventual outcome. They may be useful\npredictors when the question concerns a prediction made after that\nsemester. The question specifies both what is to be predicted and when\nthe prediction will be made.\n\nThe familiar labels **response variable** and **dependent variable**\noften refer to the outcome; **explanatory variable** and **independent\nvariable** often refer to a predictor. In an experiment, a predictor\nmay be deliberately assigned; in an observational study it may simply\nbe measured. These role labels alone establish neither causation nor\nstatistical independence. More specific labels, such as treatment or\nconfounder, describe the variable's role in the study's design.\n\n### Measurement instruments, procedures, and meaning\n\nIn an invented measurement study, researchers want to study\n*learning confidence*: students' confidence in understanding course\nmaterial and dealing with unfamiliar problems. They collect three\ncontinuously scored indicators, each from 0 to 100: confidence in explaining\nan idea, applying it to a new problem, and checking a solution. They also\ncollect three indicators of *belonging*: feeling accepted, included,\nand able to participate in the academic community. Confidence concerns\none's ability to handle learning tasks; belonging concerns one's place\nin that community. Each has its own proposed meaning and indicators.\n\nThe substantive ideas are **constructs**: concepts defined through\nknowledge of the domain. The recorded responses are **observed\nvariables**, and the observed variables chosen to represent a construct\nare its **indicators**.\nAn instrument links them through questions, tasks, instructions, response\nscales, and scoring procedures. The data are more informative when these\ndetails are available: a response given immediately after a difficult test\nmay have a different meaning from one given at the beginning of a semester.\n\nA researcher might average the three confidence indicators to form a\n**composite score**. For example, one student's responses of 60, 80, and\n70 give an average of $(60+80+70)/3=70.0000$. The three responses are observed\nindicator values; their average is a calculated score. Another researcher\nmight use a factor model to represent their\nrelationships through a **latent variable**, a variable specified within\nthe model rather than directly observed. The construct guides the choice\nand interpretation of indicators; the latent variable supplies a\nparticular statistical representation of their shared variation. A\nscore estimated from this factor model depends on the model and scoring\nmethod. The construct, the latent variable, and a calculated score are\nrelated, but each has a different role. Some studies use observed\nmeasures or composites without specifying a latent variable.\n\nTo see why the distinction matters, imagine that all three indicators\nrespond strongly to test anxiety. Their scores could move together even\nif they cover only a narrow part of learning confidence. Factor analysis\ncan describe their statistical relationship. Theory, item content,\nresponse processes, and other evidence help explain what that\nrelationship means. A suitable statistical model and a convincing\nsubstantive interpretation contribute different kinds of support.\n\nMeasurement also involves **reliability** and **validity**. Reliability\nconcerns the consistency or precision of scores under specified\nconditions. Validity concerns the support for proposed interpretations\nand uses of those scores. Consistent scoring is valuable, while the\nmeaning of a score still depends on what the instrument measures and how\nit is used [@aeraApaNcme2014].\n\nFor the feedback study, a common scoring guide helps make scores\ncomparable across formats. An assessment blueprint connecting tasks\nto the taught material gives reasons for interpreting those scores as\ncourse-topic achievement. Extending them to creativity or lifelong\nlearning would require additional evidence. The instrument and procedure\ntell us how observations were produced; the reasons for their interpretation\nbecome important when explaining why an interpretation is supported.\nChapter 2 uses this account of measurement when interpreting recorded\nscales and codes and choosing suitable numerical descriptions.\n\n### Data structure: how observations are connected\n\nOnce we have identified the units and measurements, we can ask how their\nobservations connect. A **cross-sectional** view describes units for a\nparticular occasion or period. **Longitudinal** data follow the same units\nover time; **panel data** commonly organize that follow-up into successive\nwaves. Following the same students supports description of individual\nchange. **Repeated cross-sectional** observations instead describe a\npopulation at successive times without necessarily following the same\npeople, so changes in the population can involve different individuals.\n\nAn invented language-learning study follows students across four equally\nspaced assessments. Student A scores 58, 65, 68, and 76; Student B scores\n62, 63, 67, and 68. Their successive gains are 7, 3, and 8 points, and\n1, 4, and 1 point. Across three intervals, average changes are\n$(76-58)/3=6.0000$ and $(68-62)/3=2.0000$ points. Equal time spacing thus accompanies\nuneven progress. Keeping the sequences reveals differences that a single\naverage for each student would hide.\n\nRepeated measurements can also concern conditions within one session,\nsuch as the same students completing tasks under two sets of\ninstructions. The observations share a person even when the question\nconcerns conditions rather than change over a year. Administrative fields\ncollected at different times can describe a student's history; studying\na growth trajectory additionally requires repeated measurements of the\noutcome on a common scale and their occasions.\n\nA **long** arrangement records one student at one occasion per row,\nwith the score and relevant identifiers. Student and occasion identifiers\nconnect that student's repeated observations; classroom and school\nidentifiers show group membership. Chapter 2 develops record counts and\nequivalent long and wide layouts.\n\nStudents sharing a classroom experience some common teaching conditions;\nclassrooms can in turn share a school. This is a **hierarchical**\narrangement: occasions within students, students within classrooms, and\nclassrooms within schools. Sharing people or groups creates\n**clustering**. These features can coexist: the language study is\nlongitudinal and clustered. Section 3.3 considers what those connections\nmean for comparisons, information, and uncertainty.\n\n### Implementation, exclusions, and missing observations\n\nA record of feedback assignment tells us which format a class was offered.\nAttendance and delivery records tell us what students and teachers\nactually did. Both can matter. An assignment-effect question follows\nstudents according to the assigned format; a question about attending\nevery session asks something different, because attendance may depend on\nmotivation, health, or difficulty with the material.\n\nSimilarly, a student-support study needs to establish who appears in its\nfile. Consider an invented alternative to the released student data:\nan administrative extract contains only students still enrolled at year\nend. That file can describe year-end enrollees. Studying withdrawal\nrequires the entering cohort and information about who left, including\nstudents absent from the year-end file. A missing score for an included\nstudent and a person omitted from the dataset are different problems\nfor understanding the data.\n\nThe **analysis sample** is the set of cases or observations used in a\nparticular analysis. Eligibility, participation, available measurements,\nand exclusions can make this set differ from the observations originally\nsought or collected. It may also differ across outcomes or methods. A\nstudent with a recorded baseline score but no follow-up score supplies\nbaseline information, for example, but cannot supply an observed\nbefore–after change. Following the study from entry through assessment\nto analysis explains how the available evidence took shape.\n\nReading the collection and preparation account helps establish who\nentered the study and analysis and which observations became available.\nA **data codebook** records variable meanings, units, and codes.\nChapter 2 develops its practical use alongside missing values,\npreparation decisions, and the denominator for each calculation.\n\n## Research Design and Assumptions: What Supports an Inference?\n\nAn achievement difference of 2.5 points can arise in several kinds of\nstudy. Classes might have been randomly assigned to two formats.\nTeachers might have chosen whether to adopt explanatory feedback. Or one\nclass might have improved by 2.5 points between a pretest and a\nposttest. The numerical\ndifference alone leaves the interpretation open.\n\n**Research design** connects the question to a plan for producing an\ninformative comparison. Reading that plan means identifying both what\nwas done and why the study treats it as support for its inference.\n\n### Causal comparisons and study designs\n\nA causal question compares what would happen under different conditions.\nFor one student, imagine the follow-up score if the class were assigned\nexplanatory feedback and the score if it were assigned the usual format. Only\none is observed. The other is the **counterfactual** outcome: the outcome\nunder the alternative condition. The causal effect compares the outcomes\nunder these two specified conditions for the same student. An average\ncausal effect makes that comparison for the named units or target\npopulation; it can be zero. The counterfactual is an outcome, whereas the\neffect is a contrast between outcomes. Because each student's two\ncondition-specific outcomes cannot both be observed, the design and its\nassumptions must supply a defensible comparison.\n\nAn **experiment** deliberately assigns conditions; a randomized experiment\nuses a specified probability mechanism for that allocation. The mechanism\ngives the comparison a known basis, such as the random draw allocating\nclasses to the two formats in the feedback study. Chance imbalances can\nstill occur in the realized groups. Section 3.2 explains how the actual\nallocation design supports the causal comparison and how this differs\nfrom selecting participants.\n\nIn an **observational study**, the investigator records conditions or\nexposures without assigning the focal intervention or exposure. Suppose\nbetter-resourced teachers are more likely to adopt explanatory feedback,\nand their resources also improve achievement. The observed difference\nthen mixes the feedback format with other relevant differences.\n**Confounding** occurs when a comparison mixes the exposure's effect with\neffects of other factors that influence both exposure and outcome.\nA mediator instead lies along a proposed pathway through which the exposure\naffects the outcome. Measuring and adjusting for common causes can help,\nunder conditions that need to be stated and supported.\n\nA **quasi-experimental study** uses a design-based comparison around an\nintervention or exposure without randomized allocation. For example, a\nclearly enforced eligibility threshold might supply a useful comparison\nbetween otherwise similar units close to that threshold. Its causal\ninterpretation depends on how that rule operates and the assumptions\naround the comparison. Voluntary adoption alone describes a selection\nprocess; a credible quasi-experimental argument needs more than that\nlabel [@shadish2002].\n\nThree considerations help organize causal reasoning: an association or\ncontrast in outcomes, the appropriate temporal order, and support for\naddressing alternative explanations. Confounding is one such explanation.\n**Reverse direction** is another: an outcome or its earlier development\nmay influence the exposure, reversing the proposed direction of\ninfluence. For example, earlier achievement difficulties might prompt a\nteacher to adopt a new feedback format, so a relationship between format\nand achievement would need an account of that sequence.\nMaturation, concurrent curriculum changes, changes in measurement,\nselective follow-up, and influence between classes can also matter. These\nconsiderations work together rather than acting as three boxes whose\ncompletion automatically establishes causality.\n\n### Sampling, assignment, and self-selection {#sampling-and-assignment-answer-different-questions}\n\n**Sampling or recruitment** concerns how units enter a study, through\nprobability selection, volunteering, or availability. **Assignment**\nconcerns the conditions allocated to participating units. The condition\nassigned and the treatment actually received can differ: a class assigned\nexplanatory feedback might receive only part of the planned program.\nStudy entry, allocation, and receipt therefore identify different parts\nof how the evidence was produced.\n\n**Random sampling**, also called **probability sampling**, selects units\nthrough a probability mechanism that gives every eligible unit in a\ndefined population or sampling frame a known, nonzero chance of selection.\nThose chances need not be equal. Here a frame identifies the units from\nwhich selection is made; Chapter 2 develops this idea and compares\nsampling schemes. The phrase *random selection* alone can describe other\nchance-based decisions, so identifying what is selected and for what\npurpose makes its meaning clear. Probability sampling supplies a basis\nfor population inference under the selection design, contributing to\n**generalizability or external validity**: support for extending findings\nto other people or settings.\n\n**Random assignment** uses a specified probability mechanism to allocate\nconditions among participating units.\nThe assigned units may be individuals or groups. This mechanism\ncontributes to **internal validity**: support for a causal interpretation\nof the comparison within the study. A study may use either, both, or\nneither form of randomization. Each contribution depends on implementation\nand analysis; population selection and causal allocation answer different\nquestions [@shadish2002].\n\nThe causal justification follows the actual assignment design. Chance\nallocation supplies a known basis for comparison; the realized groups\ncan still differ in prior characteristics. The analysis must respect the\nallocation mechanism and consider any later selection into the available\noutcomes.\n\nIn the invented feedback study, 12 schools volunteer, each contributing\ntwo classes with 20 eligible students per class. A random allocation\nassigns 12 of the 24 classes to explanatory feedback and the remaining\n12 to the usual format. Assignment therefore concerns classes, while the\noutcome is measured on students. Comparing equally weighted class means\nalso gives students equal weight because class sizes are equal. The\ncomparison concerns these participating students. A claim about other\nschools needs further support concerning recruitment, curriculum,\nresources, and implementation.\n\nThe working-from-home concern was examined in a real experiment by\nBloom and colleagues at Ctrip, a Chinese travel company. Employees first\nvolunteered and met eligibility conditions; 249 were then randomly\nassigned, 131 to home work and 118 to office work. Home assignment meant\nfour days at home and one in the office each week over nine months\n[@bloom2015wfh, p. 169 and Appendix Table A.2]. These employees chose to\nenter the experiment; the allocation procedure then determined their\nassigned working arrangement.\n\n**Self-selection** occurs when people's choices influence participation,\nexposure, or continued involvement. At the sampling or recruitment stage,\nvolunteering chiefly raises a question about generalizability. For example,\nvolunteers' home circumstances might make home work more beneficial for\nthem than for other employees. Random allocation among volunteers can\nstill support their treatment comparison; extending that effect requires\nadditional evidence. Self-selection names a process, rather than proving\nthat every estimate is biased.\n\nAt the assignment or exposure stage, imagine instead that employees\nchoose home or office work. If prior managerial support influences both\ntheir choice and performance, it is a **confounder**. Random assignment\naddresses this source of systematic difference; a voluntary-choice\ncomparison needs other support for its causal interpretation.\n\n**Selection bias** concerns systematic distortion relative to the\ndeclared estimand arising from which people or observations enter the\ncomparison or analysis. Terminology varies: treatment-choice confounding\nis sometimes called selection bias; identifying the mechanism is more\ninformative than the label alone. Recruitment chiefly raises external\nvalidity concerns, while allocation chiefly raises internal validity\nconcerns. The distinction is a guide, not an exclusive division: selective\nloss of outcomes after allocation can also undermine a randomized\ncomparison [@hernan2020causal].\n\nResponses should match that mechanism. Suitable sampling, recruitment,\nand follow-up, together with information about nonparticipants or losses,\nhelp establish whom the findings can describe. Adjustment or weighting\ncan support a broader inference under explicit assumptions about\nselection and relevant measured differences. For treatment comparisons,\nregression adjustment, matching, or weighting may address measured common\ncauses; unmeasured confounding requires additional support. More elaborate\ndesigns include **regression discontinuity**, comparing units near an\nassignment threshold, and **difference-in-differences**, comparing changes\nacross groups under assumptions about their untreated trends\n[@hernan2020causal; @shadish2002].\n\nAn **instrumental variable** changes treatment take-up, as a lottery\noffer might do in an invented program. Its use requires support for\nindependence from other outcome determinants and an effect on the outcome\nonly through treatment. Further assumptions determine the identified\neffect, often for people whose take-up the offer changes. This supports\na particular causal comparison without establishing volunteer\nrepresentativeness [@angrist1996iv].\n\nOther variable roles become visible in invented extensions of the\nworking-from-home setting. If home work reduced commuting stress, which\nthen affected performance, stress would be a proposed **mediator**, or\nintervening process. A baseline characteristic would be a **moderator**\nif the effect varied across its values. If both job satisfaction and\nhealth affected participation in a follow-up survey, participation would\nbe a **collider**, a common consequence of the two. Restricting the analysis\nto survey participants can create an association\nbetween satisfaction and health even if none existed beforehand. The\nrestriction is a form of **conditioning**: considering the relationship\namong people who share a value of another variable, here participation.\nThe pattern can arise from who participated rather than a relationship in\nthe full employee group [@hernan2020causal]. These examples illustrate roles;\nthey are not pathways established by the original working-from-home study.\n\nA variable's timing and role help determine whether adjusting for it\nclarifies the intended comparison or changes or biases it.\n\n### Timing, comparisons, and dependence\n\nThe units identified in Section 2.1 and the connections among observations\nin Section 2.3 help us understand what a comparison can establish. A\n**between-subjects** comparison contrasts different people or groups;\na **within-subjects** comparison uses repeated observations of the same\npeople across occasions or conditions. Both kinds of comparison can occur\nin experimental, quasi-experimental, and observational studies.\n\nReturn to the language-learning scores measured four times during a year.\nMeasurements from the same student share a history. Students within a\nschool also share some conditions. These connections can create\ndependence, affecting the information supplied by the data. Four scores from one\nstudent answer questions about that student's trajectory, while four\nstudents measured once provide information about differences between\nstudents. The same number of measurements can support quite different questions.\n\nTiming helps establish the order of an exposure and an outcome.\nRepeated measurements can also contribute to a causal question. A\nfeedback rollout observed in intervention and comparison classes before\nand after implementation helps reveal pre-existing differences and\nchanges over time. Its causal interpretation still needs reasons that\nthe comparison describes what would have happened without the rollout.\nA new teaching policy introduced only in the intervention classes, for\nexample, could provide another explanation for their change.\n\nCombining groups and time phases creates a richer design. Read its\nallocation, comparison conditions, timing, and dependence together.\nSuch combinations make experimental design a substantial field of\nstudy in its own right.\n\nThe level of a relationship matters too. A change within a language\nlearner differs from a difference between learners' average scores.\nComparing classroom averages introduces another level. Each can answer a\nuseful question, provided the units and comparison remain clear.\n\nDesign also affects the uncertainty of an estimate. Many measurements\nof the same students or classes cannot automatically replace information\nfrom more units. Reading a study's account of allocation, measurement,\nand dependence helps explain how informative its comparison can be.\nChapter 3 develops precision, power, and their roles in planning.\n\n### Reasons for analytical choices and the assumptions they invoke\n\nA method is usually selected through several connected considerations:\nthe question and estimand, the outcome's scale, the structure of the\ndata, the design, and the intended use of the result. A numerical score\nalone points to no unique procedure. Comparing two independently assigned\ngroups, describing repeated scores, and predicting a new student's score\ngive that score different analytical roles.\n\nAn **assumption** is a condition invoked in the reasoning. A straight-line\nbaseline-to-delayed-achievement model represents a constant slope over its\nstated range. A procedure for independent observations requires an account\nof what makes that independence plausible. A growth model instead\nrepresents dependence among repeated measurements. A causal\ninterpretation of observational adoption of explanatory feedback needs\nreasons for addressing confounding and for comparing sufficiently\nsimilar classes.\n\nSeveral familiar names identify statistical conditions. **Linearity**\ndescribes the form of a modeled relationship; **independence** concerns\nconnections among observations or errors. **Normality** may concern a\nmodel's conditional errors, the parts of an outcome the model does not\naccount for, or an approximation used by the procedure that produces the\nestimate, rather than every recorded variable. **I.i.d.** means independent and\nidentically distributed. Repeated observations or shared classroom\nconditions often call for a representation of their dependence instead.\nThese conditions belong to particular methods and inferences; the task\nis to recognize which ones the study actually invokes.\n\n**Causality is an interpretation of a comparison**, supported by design\nand causal identification assumptions, such as a defensible account of\nconfounding. Assuming normally distributed errors or specifying a straight\nline supplies no causal interpretation by itself. Statistical assumptions\nand causal support answer related but distinct questions.\n\nSubstantive reasons accompany these statistical ones. The choice of a\nfollow-up assessment depends on what it represents; a proposed mediation\npath depends on a plausible sequence of events; interpretation of a\nconfidence factor depends on the indicators and the setting. Statistical\nand substantive knowledge therefore contribute from the beginning.\n\nNotice the distinction between identifying a reason and judging its\nadequacy. A report might state that it used a straight-line model because\nthe baseline-to-delayed-score plot appeared approximately linear. That sentence\ndocuments the offered rationale. Whether the plot and other checks\nsufficiently support the choice is a further question. We return to this\ndistinction when reading and evaluating the argument.\n\n@tbl-journey-feedback-designs compares the randomized feedback study\nwith two invented redesigns. Each arrangement names its own causal\nquestion, students, outcome period, and intended estimand.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Research design | Research question | Intended estimand | Possible confounding and other threats |\n|:--|:--|:--|:--|\n| **Experimental:** 24 classes randomly allocated between two formats | What would assigning explanatory feedback rather than the usual format change in delayed achievement for the eligible students? | Average assignment effect on the common delayed score for eligible students in participating classes | Random assignment addresses systematic allocation by prior achievement or teacher resources. Chance imbalance remains possible; loss of students and influence between classes are additional threats. |\n| **Quasi-experimental:** designated rollout classes and comparable not-yet-treated classes, with baseline information | What would delayed achievement in rollout classes have been under explanatory rather than usual feedback? | Average effect of replacing usual with explanatory feedback for eligible students in rollout classes at the stated follow-up | Prior achievement, teacher resources, and reasons for rollout timing may affect adoption and outcomes. The rollout rule and comparison need to support the counterfactual. |\n| **Repeated measurement within a quasi-experimental design:** intervention and comparison classes at several pre- and post-rollout occasions | What effect did explanatory feedback have on average achievement during the named post-rollout period for eligible students in rollout classes? | Average effect on scores in that period for those students, relative to continuing usual feedback | Different pre-existing trends, group-specific maturation, or concurrent teaching changes can distort the comparison. Repeated measurements help examine these possibilities. |\n\n: Causal questions and intended estimands under three feedback-study arrangements. {#tbl-journey-feedback-designs tbl-colwidths=\"[25,24,24,27]\"}\n\nRepeated measurement is a feature that can accompany different assignment\ndesigns, which is why the last design also names a quasi-experimental\narrangement. A one-group before-and-after dataset can describe change;\nattributing that change to feedback requires further support for the\nunobserved alternative. An adjusted association or an average pre-post\nchange can be an estimand in its own right, under its own question.\nKeeping the intended estimand distinct from an available comparison helps\nthe reader understand what the analysis is trying to establish.\n\n## Statistical Methods, Models, and Analysis\n\nStatistical analysis connects data to questions through summaries,\nrelationships, estimates, and uncertainty. Method names help readers\nrecognize what an analysis learns.\n\n### A question-led map of method families\n\nDescriptive statistics summarize observed data through means,\nproportions, measures of variation, and plots. A mean can describe the\ndelayed achievement of a class; a proportion can describe what share of\nstudents have recorded Dropout status. Variation shows how much the\nobservations differ around such summaries. Plots make patterns visible,\nincluding features a single number might conceal.\n\nRead @tbl-journey-method-families by connecting each question, method\nfamily, and estimated quantity. Each entry maps the possible questions\nwithin a case rather than a single question-answer pair. Held-out data\nare set aside while a rule is developed. The surrounding explanation\nidentifies the data and comparison; the second table\ndevelops their connection to design.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Familiar case and question | Related method families | What the analysis estimates |\n|:--|:--|:--|\n| **Student outcomes:** How does the chance of recorded dropout relate to admission grade and age, and how well can enrollment-time information predict the outcome for other students? | Proportions and descriptive summaries; binary regression within generalized linear models (GLMs); prediction checked on held-out data | A proportion in each recorded status; a conditional probability of recorded dropout; the average error of a fixed prediction rule for new students represented by the dataset |\n| **Feedback:** What is the average effect of assigning explanatory feedback rather than the usual format on delayed achievement? | Mean comparisons, analysis of variance (ANOVA), and regression with a format indicator | The student-average achievement contrast under the two assignments in the named classes and period |\n| **Working from home:** What did assignment to home work change in performance, and might the effect differ across employees or work through an intervening change? | Group comparison and regression with repeated outcomes; moderation and mediation as previews | The average assignment effect on a named performance outcome over the experiment; a difference in effects across a baseline characteristic; a proposed indirect effect, which needs its own support |\n| **Confidence and belonging:** What do several indicators have in common, and how are the two constructs related? | Exploratory and confirmatory factor analysis (EFA, CFA) and structural equation modeling (SEM) | Indicator-factor relationships (loadings); correlations or modeled relationships between factors (factor correlations or structural coefficients) |\n| **Language progress:** How does achievement change over four occasions, and how do trajectories differ among students who share classrooms? | Linear mixed-effects models (LMM) and longitudinal models; latent growth as a related representation | An average rate of change and between-student variation in trajectories for a stated model and time scale |\n\n: Questions, method families, and what each analysis estimates in the five cases. {#tbl-journey-method-families tbl-colwidths=\"[36,30,34]\"}\n\nFor student outcomes, first describe the proportions recorded as\nDropout, Enrolled, and Graduate. A two-way frequency table could count\nthese statuses within each course; dividing by the number of students\nin that course gives its outcome proportions. Binary regression can\nthen express the probability of dropout given admission grade and age.\nThis is a conditional probability because it refers to specified\npredictor values. A prediction assessment checks those probabilities\non held-out students. Look for the outcome definition and the distinction\nbetween fitting a rule and assessing it on other students' data.\n\nFor feedback, mean comparisons estimate the average difference under\nthe two assigned formats. Analysis of variance (ANOVA) relates variation\nbetween group means to variation within groups. A **grouping factor**\nis a categorical variable defining groups; the two formats are levels\nof one factor. One-way and two-way ANOVA use one and two grouping\nfactors, respectively, each of which can have several levels.\n\nIn the feedback study, class means represent outcomes under the two\nassigned formats. The analysis accounts for class allocation when\nestimating the difference and its uncertainty. The 480 student scores\nsupply measurements from 24 assigned units. Regression can express the\nformat comparison while retaining that design and the intended student\nweighting.\n\nFor working from home, regression can compare performance under the\ntwo assignments while accounting for repeated measurements from each\nemployee. Many weekly measurements represent repeated observations of\nthe same people, rather than that many independent employees. A report\nmay present an average performance difference and a plot of how the\ngroups compare over time. Further analyses could ask whether the effect\nvaries across employees or works through an intervening change.\nIdentify the performance outcome, period, and employees each result\nconcerns, and whether a proposed pathway belongs to the original study\nor an invented extension.\n\nFor confidence and belonging, the measurements are several indicators\nintended to represent two substantive ideas. EFA explores how their\nshared variation might be represented\nby fewer latent variables; CFA examines\na specified representation. Here a factor is a latent variable, distinct\nfrom the categorical grouping factor in ANOVA. A loading describes an indicator's relationship with\na factor, and a factor correlation describes how two factors vary\ntogether. SEM can also express\nrelationships between factors through structural coefficients, each a\nmodeled relationship between one factor and another [@bollen1989].\n@fig-journey-measurement-map in the appendix pictures the six indicators\nand two proposed factors. These outputs become interpretable alongside\nthe item content, scoring, and intended construct definitions. A\nreport should let you recognize both what the indicators measure and\nwhat the proposed model says about their relationships.\n\nFor language progress, repeated assessments reveal starting levels and\nchange within students. An LMM can represent\nan average trajectory while allowing students to differ around it,\nincluding when they share classrooms or schools [@bates2015lmm]. The\nmixed-effects results might describe average improvement per assessment\ninterval and\nvariation in students' starting scores or rates of improvement. Latent\ngrowth is an alternative representation of the same trajectories within\na factor model of the kind just described. In a report,\nidentify the time scale and distinguish an average trajectory from\nthe individual patterns contributing to it. A rising group average\ncan coexist with students who improve quickly, slowly, or very little.\n\nThe second table connects each case's data and design to the method\nfamilies.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Familiar case and data | Research design and structure | Related method families | What connects them |\n|:--|:--|:--|:--|\n| Student outcomes: admission information and three recorded outcome categories | Observational administrative data; each case is a student, with variables measured at different times | Binary regression within GLMs; predictive modeling | Define the outcome and the prediction time; use predictors available then; assess performance on held-out data |\n| Feedback: delayed achievement and assigned format | Random allocation of 24 classes to two formats | Group comparisons, ANOVA, and regression | Match the mean contrast, uncertainty, and weighting to class assignment |\n| Working from home: assigned location and repeated employee outcomes | Individual randomization among eligible volunteers; repeated measurements | Comparisons and regression; longitudinal or LMM extensions | Represent assignment and dependence; added pathway questions need their own support |\n| Confidence and belonging: multiple indicator scores | Observational measurement study; a separate dataset for examining a proposed representation | EFA, CFA, and SEM | Represent shared variation; connect measurement and structural relationships to construct meaning |\n| Language progress: repeated scores from students sharing classrooms or schools | Longitudinal and hierarchical data; experimental or observational depending on allocation | LMM and multilevel models; latent growth | Represent within-person dependence, grouping, and variation in trajectories |\n\n: How data, design, and methods connect in the five cases. {#tbl-journey-data-design-methods tbl-colwidths=\"[23,26,22,29]\"}\n\nThese connections are many-to-many. Regression can serve association,\nprediction, or a design-supported causal comparison. Repeated binary\noutcomes combine an outcome-scale question with a dependence question.\nMethod choice therefore connects the estimand, measurements, design,\nand assumptions.\n“Mixed effects” in an LMM names statistical effects, distinct from\nquantitative-qualitative mixed-methods research.\n\n### Regression as a connecting language\n\nConsider delayed achievement plotted against baseline achievement in\na small invented feedback dataset. Each point represents two scores\nfor one student: the baseline score gives its horizontal position, and\nthe delayed score gives its vertical position. A fitted line summarizes\nhow delayed scores tend to differ across baseline scores. Students with\nthe same baseline score can still have different delayed outcomes;\nthe line describes a pattern around which individual scores vary.\n\nThe line's **intercept** is the fitted delayed score at baseline zero.\nIts **slope** is the fitted difference in delayed score for each\nadditional baseline point. A **residual** is an observed delayed score\nminus its fitted value. A point above the line has a positive residual;\na point below it has a negative residual. Residuals make the gaps\nbetween the summary and the individual observations visible.\n\nThe data in @fig-journey-feedback-pattern are separate\nfrom the 480-student experimental dataset. Both panels have the same\naverage delayed score and the same fitted straight line:\n\n$$\n\\widehat{Y}=8+0.70x.\n$$\n\nHere $x$ is baseline achievement and $\\widehat{Y}$, read “Y-hat,” is\nfitted delayed achievement, both in assessment points. The intercept\nis 8 and the slope is 0.70. At baseline 20, the fitted score is\n$8+0.70(20)=22.0000$. The left-panel student with an observed score of 21\nis one point below that fitted value, so its residual is $-1.0000$\npoint. The slope describes an association between the two scores;\nit does not by itself describe what an intervention raising baseline\nachievement would do.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Feedback-score patterns with the same fitted straight line. The left panel follows that line closely; on the right the same line, drawn dashed, misses a pattern that flattens at higher baseline scores, which the solid curve follows.](chapter_01_files/figure-html/fig-journey-feedback-pattern-1.png){#fig-journey-feedback-pattern fig-pos='H' fig-alt='Two panels plot delayed achievement against baseline achievement. The left scores follow a straight pattern and the right scores follow a flattening curve. Both have the same fitted straight line, delayed score equals eight plus zero point seven times baseline score, drawn solid on the left and dashed on the right beside a solid curved fit.' width=600}\n:::\n:::\n\n\nThe right-hand pattern flattens as baseline achievement increases,\nalthough its mean and fitted line match the left-hand example. Reading\nthe graph alongside the summary reveals the difference. Section 4.5\nreturns to this curve as an example of model modification.\n\nRegression also connects to the feedback group comparison. Code usual\nfeedback as 0 and explanatory feedback as 1, and a model can express\nthe difference between their means. Adding baseline achievement allows\nthe analysis to describe how delayed scores relate to both starting\nachievement and format. An interaction allows the baseline relationship\nitself to differ by format, rather than requiring the same slope in\nboth groups. In the class-randomized experiment, the analysis still\nneeds to respect class assignment and the intended student weighting [@gelman2020].\n\nIn an invented working-from-home extension, moderation asks whether the\nassignment effect varies with baseline commuting time, while mediation\nasks whether fewer interruptions help account for an effect on\nperformance. The proposed pathway needs additional evidence and\nassumptions because randomizing work location also leaves other\ninfluences on interruptions and performance to be considered.\n\nThe language-learning data add change over time. Student A's scores\nare 58, 65, 68, and 76 across four equally spaced occasions; Student B's\nare 62, 63, 67, and 68. Their mean rises from 60.0000 at the first assessment\nto 72.0000 at the last, but their starting levels and patterns differ.\nStudent A's successive gains are 7, 3, and 8 points; Student B's are\n1, 4, and 1. The total gains of 18 and 6 points correspond to average\nchanges of 6.0000 and 2.0000 points per interval. Those averages summarize the\nwhole period, while the observed changes vary from one interval to the\nnext.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Two invented language-learning trajectories. Equally spaced assessment times allow uneven score changes; the lines join observations rather than represent a fitted growth model.](chapter_01_files/figure-html/fig-journey-growth-1.png){#fig-journey-growth fig-pos='H' fig-alt='At four equally spaced occasions, Student A scores 58, 65, 68, and 76, while Student B scores 62, 63, 67, and 68. Student A starts lower and gains more overall. Both trajectories have uneven interval gains. Points mark observed scores, joined by lines.' width=600}\n:::\n:::\n\n\nAn LMM can represent an average trajectory together with differences\namong students and occasion-to-occasion variation. Even a model with a\nstraight average trajectory allows observed scores to depart from that\nline. If students share classrooms, the model can also represent relevant\ngrouping. An average rate of improvement and differences among students\nanswer related but distinct questions. The two trajectories in\n@fig-journey-growth show why both matter; data from more students are needed to\nestimate the proposed student and classroom variation.\n\n### Model building and estimation\n\n**Model specification** means deciding what statistical relationship\nto represent: the outcome, its predictors, the form of their relationship,\nand any dependence among observations. For the fitted line above,\ndelayed achievement is the outcome, baseline achievement is the\npredictor, and the chosen form is straight. This choice represents\nthe same fitted increase per baseline point throughout the range\nbeing described. A curve would allow that increase to change.\n\nAdding feedback format changes what the model represents. A common\nbaseline slope describes the same baseline-to-delayed relationship in\nboth formats while allowing their fitted levels to differ. Allowing\nformat-specific slopes gives a more flexible description. These choices\nshould follow the question and the patterns the analysis seeks to\nrepresent. The average assignment effect remains a different quantity\nfrom the association between baseline and delayed scores, even when\nboth are examined using the same students' data.\n\nA model and an estimation method do different work. The model states\nthe proposed relationship and its conditions. The estimation method\nuses the observations to find numerical values for its unknown\nquantities. **Least squares**, for example, chooses the fitted line\nthat minimizes the sum of squared residuals. Squaring prevents positive\nand negative residuals from canceling each other and gives larger\ngaps more weight. The resulting line makes those squared gaps as\nsmall as possible overall; it need not pass through every observation.\n\nSoftware performs the specified calculations. R, the computational\ntool used throughout this series, can fit the line, calculate fitted\nvalues, and produce the graph. “Analyzed in R” identifies the software.\nThe equation, data description, and analytical explanation identify\nthe model, estimation method, and uncertainty procedure it implemented.\n\nThe **generalized linear model (GLM)** family extends regression to\ndescribe different kinds of outcomes, including a probability or an\nexpected count [@nelder1972]. The recorded-dropout question concerns\na probability, which stays between zero and one. **Logistic\nregression** is a commonly used member of this family for a two-category\noutcome; it is the rule used here for recorded dropout and reported in\nthe appendix. A question about calls handled during a defined work\nperiod concerns a count. The model should represent that outcome\nappropriately, and the reported result should name its scale. A count\nmodel is one possible analysis of call counts, rather than a\ndescription of every analysis in the working-from-home paper.\n\nFor the student-outcome analysis, keep three quantities distinguishable.\nA student's recorded status is an observation. The proportion with\ndropout status summarizes a collection of observations. A fitted\nprobability describes the model's estimated chance of recorded dropout\ngiven its predictors. Students recorded as Enrolled remain distinct\nfrom graduates, even though the binary question combines both as\noutcomes other than dropout. That coding answers the defined dropout\nquestion without predicting eventual graduation for enrolled students.\n\n### Statistical uncertainty, hypothesis testing, and model comparison\n\nAn estimate summarizes the available observations, while the quantity\nit seeks to describe can remain uncertain. **Standard deviation (SD)**\nsummarizes spread around a mean. Applied to students' scores, it describes\nvariation among those scores. Repeating a stated sampling or assignment\nprocess can instead produce different estimates. Their distribution is\na **sampling distribution**, and its SD is the **standard error (SE)**.\nSE therefore describes the variation of a statistic used as an estimate,\nunder the specified repetition and conditions.\n\nFor feedback, different allowed assignments of classes could produce\ndifferent estimates of the effect. This is assignment variation within\nthe participating cohort, rather than selection of new students.\nThe important distinction is whose variation is summarized: individual\nmeasurements or estimates across the relevant repetitions.\n\nA **confidence interval** combines an estimate with an uncertainty\nprocedure. Under the procedure's conditions, its confidence level\ndescribes how often intervals constructed across the relevant\nrepetitions would cover the estimand. The reported interval indicates\nthe range left compatible with the data by that procedure. It concerns\nuncertainty about the estimated quantity, rather than a range containing\n95% of individual students' outcomes.\n\nFor this reading example, the invented feedback report supplies an\nestimated effect of 2.50 points and a 95% confidence interval from 1.00 to\n4.00 points. The single-number estimate is the **point estimate**. The\nreport's uncertainty procedure reflects assignment of classes, while the\nresult concerns the eligible students in those classes. Complete follow-up\nstill leaves uncertainty about the average assignment effect because\neach student was observed under only one assigned format. The appendix\nprovides the study description and supporting extracts; the reported\nquantities are supplied for interpretation here.\n\nA statistical hypothesis states a proposition about a statistical\nquantity or model. One null hypothesis for feedback is that the\naverage assignment effect is zero. A test asks how incompatible the\nobserved results are with that proposition under stated conditions.\nThe test expresses discrepancy through a test statistic. Its\n**p-value** is the probability, assuming the null hypothesis and the\nstated conditions, of a test statistic as extreme as or more extreme\nthan the one observed, with “extreme” defined by that test. A result is\ncalled **statistically significant** when its p-value falls below a\nthreshold stated in advance. For a two-sided test at the 5% level built\nfrom the same procedure, the 95% confidence interval excludes the null\nvalue when the result is statistically significant.\nA smaller p-value indicates greater incompatibility by that measure;\nit gives neither the probability that the null is true nor the\npractical importance of the effect [@wasserstein2016]. The estimate\nand its interval remain needed to describe the size and uncertainty\nof the difference.\n\n**Model comparison** asks a further question about competing descriptions.\nFor the same feedback data, a model with a common baseline slope\ncan be compared with one allowing a different slope in each format.\nThe comparison examines whether the extra flexibility helps describe\nthe relationship under the chosen comparison procedure. The outcome,\ndata, and purpose of the comparison need to remain clear. In\nprediction, the relevant comparison instead asks which fixed rule\ndoes better on suitable data excluded from its development.\nFitting the available observations more closely and predicting other\nobservations better are distinct achievements.\n\n### Model diagnostics, modification, sensitivity, and validation\n\nAfter fitting a model, examine what it captures. **Diagnostics** check\nparticular features of the fitted analysis. In the feedback example,\nresiduals that trace a curved pattern suggest that the straight\nbaseline relationship misses something systematic. The points are\nnot simply scattered above and below the line: their positions change\nin a recognizable way across baseline scores. The diagnostic directs\nattention to the shape of the relationship.\n\n**Model modification** changes a specification in response to\nsubstantive reasoning or analytical evidence. Allowing a justified\ncurve is one response to that residual pattern. The report should\nexplain what changed, why it changed, and whether the choice was\nplanned or informed by the observed results. The revised model then\nneeds examination too. Keeping the change visible helps readers\nunderstand which description was originally proposed and what the\nanalysis contributed to its development.\n\n**Sensitivity analysis** examines how a result depends on choices\nor assumptions. For feedback, one possible check compares the declared average assignment\ncontrast with an analysis that adjusts for baseline achievement while\nretaining the design and intended student weighting. The comparison\nshows whether the estimated answer changes appreciably when that\nadditional information is used. Interpreting the comparison requires\nthe same question to remain visible; an analysis of a different\noutcome or population may be answering a different question.\n\n**Validation** checks a prediction rule on suitable observations\noutside its development data. The simplified student-outcome\nanalysis builds a dropout rule from admission grade and age for\none group of students and checks it on held-out students. A comparison\nrule gives every held-out student the same probability: the dropout\nproportion calculated from the training data. Under a simple\nmeasure of probability error, the average squared gap between each\npredicted probability and the recorded outcome coded 0 or 1, the\nfitted rule performs somewhat better. This is an internal check within\nthe released dataset; a later cohort would provide a different test of\nits performance [@james2021].\n\nThe held-out observations are useful because their outcomes did not\nguide the original fit. Repeatedly consulting them to choose model\nchanges turns them into development information, so a final assessment\nthen needs its own protected evidence. **Data leakage** occurs when\ninformation unavailable at the intended prediction time, or information\nreserved for assessment, improperly enters development. Using later\nsemester results to make an enrollment-time prediction is one example\nthat can make the rule appear more useful than it would be then.\n\n## Interpreting Results and Formulating Bounded Answers\n\nNumerical results become answers through interpretation. An estimated\ndifference is an analytical output; a statistical conclusion states\nwhat it indicates about the declared comparison; a substantive\ninterpretation explains what that comparison means in its setting.\nFollowing this movement keeps the participants, outcome, conditions,\nand uncertainty attached to the answer.\n\n### From numerical output to a statistical conclusion\n\nThe feedback result is an estimated average assignment effect of\n2.50 points, with an approximate 95% interval of 1.00 to 4.00 points\nfor the eligible cohort. A statistical conclusion can state that\nthe comparison indicates a positive average effect under the\nreported analysis, while retaining uncertainty about its size.\nThe estimate concerns assignment to a format, rather than the\neffect of attending an additional session. It is an average, rather\nthan a claim that every student benefits by the same amount.\n\nFor the dropout rule, the statistical conclusion concerns prediction\non held-out students in the released dataset. The simplified rule\nperformed somewhat better than the comparison rule using the\ndropout proportion from the training data for everyone. This supports a\nconclusion about that internal assessment, with performance potentially\nvarying across other partitions or groups of students. A claim about\nfuture cohorts is a further question, requiring evidence about\nprediction in those cohorts and at the intended decision time.\n\n### Substantive meaning, importance, and scope\n\nUnits are part of meaning. A difference of 2.50 achievement points\nrefers to the named delayed assessment and the course topics it\ncovers. Interpreting it as improved learning depends on what that\nassessment measures and when it was administered. A reader should\nbe able to carry the result back to recognizable tasks students\nwere expected to perform, rather than treating “achievement” as\nan unlimited description of educational benefit.\n\nFor an explicitly illustrative comparison, suppose two groups have\nrecorded dropout proportions of 20% and 30%. Their difference is\nten percentage points. These figures illustrate the unit; they are\nnot outputs from the fitted student-outcome rule. Whether a support\nintervention would reduce dropout remains a separate question.\n\nBloom and colleagues reported about 13% more calls per week under\nhome assignment among the 134 order takers included in that analysis\nover the nine-month experiment [@bloom2015wfh, pp. 187--188]. This\noutcome and subgroup matter: the result concerns weekly calls among\nthose order takers. “Calls per week” gives the observation period\nthat turns a count into a rate. Calls per minute of working time\nwould describe a different aspect of performance.\n\n**Practical importance** connects the size of a result to a\nsubstantive concern. The feedback **protocol**, the document recording\nthe study's planned decisions before the data were examined, identifies\na two-point improvement as a locally meaningful benchmark. Its\nscoring guide awards two points for a fully correct application task,\nand the curriculum team judged an average gain of that size worth\nconsidering relative to modest additional preparation. The benchmark\ntherefore has a stated educational rationale; it is not a universal\nthreshold for useful feedback.\n\nThe estimate exceeds two points, while its interval spans values\nbelow and above that benchmark. The estimated improvement is\npositive, with its practical size still uncertain.\n\nIn the student case, using probabilities to flag students requires choosing\na cut-off. At 0.5, the rule identifies 73 of the 427 held-out students\nrecorded as Dropout: $73/427\\approx17.0960\\%$. Better average probability\npredictions can therefore coexist with missing many recorded dropouts at\na selected cut-off. Choosing a cut-off requires considering missed cases\nand unnecessary alerts. Recorded dropout is also only one possible sign\nof support need. The effectiveness of any subsequent support remains a\nseparate question; prediction and substantive judgment inform different\nparts of that decision.\n\n### Reading numerical results accurately\n\n**Read an estimate with its estimand.** “The difference is 2.50”\ngives a number. “The estimated student-average assignment effect\nis 2.50 points on the delayed assessment in the eligible cohort”\nidentifies the quantity it is intended to describe. Keep that\ncomparison and scope when moving from a table to a written answer.\n\n**Read significance alongside magnitude and uncertainty.** A\nsmall p-value describes incompatibility with a stated null under\nstated conditions. A large benefit is a statement about magnitude.\nThe estimate, its units, and the interval are needed to see how\nlarge and how precisely estimated a difference is; substantive\nknowledge helps explain why its size matters.\n\n**Read a nonsignificant finding through its interval and question.**\nUsing the two-sided test and interval procedure described in Section 4.4,\nan illustrative 95% interval from -8 to 8 points contains zero and gives\na nonsignificant result. It leaves\nsubstantial effects in both directions unresolved. An interval from\n-0.3 to 0.3 would be much more informative if the study had justified\none point as the smallest important difference. Evidence that an effect\nis small needs an appropriate comparison and sufficient precision;\n“nonsignificant” alone establishes neither equality nor absence\nof an effect.\n\n**Read a fitted model as a specified account of relationships.**\nA well-fitting measurement model represents relationships among\nthe indicators under its conditions. Item content and substantive\nknowledge help explain what the factors mean. Similarly, interpreting\na fitted pathway as a causal mechanism needs temporal, measurement,\nand design support beyond the existence of a fitted arrow.\n\n**Read results as contributions to an answer.** Retain the outcome,\ntiming, assessment, and intended use when paraphrasing a reported\nconclusion.\n\n### Following the reported answer and its qualifications\n\nConsider these excerpts from the feedback report:\n\n> **Results:** The estimated student-average assignment effect was\n> 2.50 points on the 0-40 assessment administered two weeks after the\n> six-week program. The approximate 95% confidence interval was\n> 1.00 to 4.00 points, with uncertainty reflecting class assignment.\n>\n> **Discussion:** Assignment to explanatory feedback improved average\n> performance on the assessed course topics for eligible students in\n> these participating classes, under the reported implementation and\n> inferential conditions. Whether the improvement reached the locally\n> selected two-point benchmark remained uncertain. Broader learning,\n> other settings, and individual effects require additional evidence.\n\nThe Results excerpt states the statistical comparison. The Discussion\nconnects it to course performance while preserving participants,\nassessment, conditions, and unresolved magnitude. Reading identifies\nwhat the authors claim. If an exercise asks you to formulate an answer\nfrom supplied results, that answer is your own synthesis. Keeping these\nactivities recognizable lets a subsequent evaluation examine the\nreported claim without silently substituting a different one.\n\n## Connecting Evidence to Answers: The Argument-Based Approach\n\nSo far, you have followed a question through its data, design,\nanalysis, and interpretation. An **argument-based approach** connects\nthese contributions to the study's answer. An argument here means the\naccount of how evidence and reasons support an inference and a claim.\n\nOne question-answer pair has **one argument with linked layers**. Count\npairs by separately owed substantive answers, rather than by estimates,\ntests, or coefficients. Several results can contribute to one answer.\nThe statistical layer (STAT) concerns recorded variables, statistical\nsupport, analysis, and the statistical conclusion. The substantive layer\n(SUB) connects these contributions to the people, practices, meanings,\nand setting named by the question. Substantive reasoning enters when a\nquestion and its measures are chosen, as well as when results are\ninterpreted.\n\n### Recognizing the four functions in Sections 2–5\n\nThe four functions already have familiar work to do:\n\n- **Evidence (E):** observations and their production, developed in\n  Section 2.\n- **Justification (J):** reasons and conditions supporting the comparison,\n  developed in Section 3.\n- **Inference (I):** analysis and interpretation connecting that support\n  to a conclusion, developed in Sections 4 and 5.\n- **Bounded claim (C):** the reported answer with its conditions and\n  limits, developed in Section 5.\n\nTheir logical connection is **E + J → I → C**. Each layer contributes\nall four functions, as @tbl-journey-component-definitions explains.\nThe component names identify what information does in an argument.\nA design paragraph, for example, may describe an allocation procedure\nand explain why that procedure supports a comparison. These are\ndifferent functions within the same paragraph.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Function | Statistical component | Substantive component | Cross-layer action |\n|:--|:--|:--|:--|\n| **Evidence (E)** | **STAT-E:** information about the observations, variables, and procedures through which the analysis data were produced or acquired | **SUB-E:** information about the people, setting, activities, and substantive meaning represented by those data | SUB-E **situates** STAT-E |\n| **Justification (J)** | **STAT-J:** reasons and conditions invoked to support the intended statistical comparison and inference | **SUB-J:** domain-based reasons supporting measurement meaning, implementation, explanation, and applicability | SUB-J **augments and contextualizes** STAT-J |\n| **Inference (I)** | **STAT-I:** the analytical reasoning and work connecting evidence and justification to statistical conclusions, including estimates, uncertainty, comparisons, and checks | **SUB-I:** interpretation of that statistical inference in substantive terms, retaining the relevant uncertainty and conditions | SUB-I **interprets** STAT-I |\n| **Bounded claim (C)** | **STAT-C:** the reported statistical conclusion about the estimand, with uncertainty, conditions, and scope | **SUB-C:** the reported question-facing answer, with its substantive scope, qualifications, and unresolved matters | SUB-C **bounds** the substantive reach of STAT-C |\n\n: The component functions in the linked statistical and substantive layers. {#tbl-journey-component-definitions tbl-colwidths=\"[17,30,32,21]\"}\n\nThe cross-layer arrows in @fig-journey-linked-argument run from the\nsubstantive components to the statistical components they situate,\naugment and contextualize, interpret, or bound. These contributions give\nstatistical work its meaning for the question. They operate alongside\nthe within-layer support relation, rather than marking separate stages\nof research.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![One argument with linked layers: logical support and substantive meaning.](chapter_01_files/figure-html/fig-journey-linked-argument-1.png){#fig-journey-linked-argument fig-pos='H' fig-alt='Four boxes in the statistical layer are Evidence, Justification, Inference, and bounded Claim. Evidence plus Justification support Inference, which supports Claim. The substantive layer has the same structure. Upward links from the substantive to the statistical components are labeled situates, augments and contextualizes, interprets, and bounds. These links describe logical contributions, not a sequence of research stages.' width=600}\n:::\n:::\n\n\nFollow the feedback study's Methods, protocol, assessment and\nimplementation supplement, and analytical supplement through their\nextracts in the appendix. @tbl-journey-argument-functions identifies\nhow these materials contribute to the study's average assignment-effect\nargument. Focus on what each contribution does; quality evaluation\nconsiders its adequacy separately.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Function | Statistical contribution in the feedback study | Substantive contribution in the same argument |\n|:--|:--|:--|\n| Evidence (E) | **STAT-E:** eligible students and classes; class allocation; assignment, assessment, follow-up, and analysis-sample information | **SUB-E:** who the students are; what explanatory and usual feedback involved; what the achievement assessment represents |\n| Justification (J) | **STAT-J:** reasons class randomization, the class-level comparison, declared weighting, and the uncertainty procedure support the assignment-effect inference | **SUB-J:** reasons the assessment meaning, comparable teaching conditions, and delivery records support the educational interpretation |\n| Inference (I) | **STAT-I:** the specified analysis; the estimated student-average contrast and its interval; coding, follow-up, and sensitivity checks | **SUB-I:** interpretation of the contrast and uncertainty on the achievement scale at the stated follow-up, against the local benchmark |\n| Bounded claim (C) | **STAT-C:** the reported assignment-effect conclusion for the eligible cohort, with uncertainty and inferential conditions | **SUB-C:** the reported answer about assessed performance in these classes and conditions, with its qualifications and unresolved matters |\n\n: Four functions connecting statistical work to a substantive answer. {#tbl-journey-argument-functions tbl-colwidths=\"[18,41,41]\"}\n\nMethod families and argument components organize different things.\nRegression is a family of statistical tools; its study-specific use\ncontributes across components. The variables and data contribute\nevidence, reasons for the comparison contribute justification, modeling\nand estimation contribute inference, and the reported conclusion\ncontributes a claim. STAT-I usually holds the most technically demanding\nstatistical work. It traces the central statistical information of the\nargument: how evidence, analyzed under the study's stated conditions and\njustification, supports a statistical conclusion. Learning methods\ndevelops that reasoning together with an understanding of the evidence\nand support it requires.\n\n### Traceable information and where to find it\n\n**Traceable information** is specific study content through which you\ncan identify an argument component's function at a documentary location.\nIt may describe an action or state an assumption, interpretation, or\nclaim. It bridges a general function and the passage or material doing\nthat work:\n\n**Question-answer pair → argument component → traceable information →\ndocumentary location.**\n\nYou can begin with a component and look for its contribution, or begin\nwith an informative passage and ask what function it performs. For\nexample, \"12 of the 24 classes were randomly allocated to each format\" describes\nevidence production in STAT-E. The protocol's explanation that this\nallocation supports the assignment comparison gives a reason in STAT-J.\nThe topic is shared, while the particular information performs\ndifferent work.\n\nSimilarly, \"the common assessment was scored without knowledge of\nformat\" describes a measurement procedure in STAT-E. The assessment\nblueprint's reasons for treating its tasks as evidence of taught-topic\nachievement support SUB-J. Describing which topics the tasks cover\nsituates the data in SUB-E. Professional knowledge helps you identify\nthese functions: knowing what random assignment or an assessment\nblueprint contributes makes the corresponding information recognizable.\nReading records the offered reasons faithfully; their adequacy is a\nfurther question.\n\n@tbl-journey-study-locations shows where each part of this chain\nusually sits in a study's materials.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Part of the argument | Possible study location | Information a reader may seek |\n|:--|:--|:--|\n| **Question and candidate answer** | Abstract, introduction, or protocol | Purpose, quantitative question, the kind of answer sought (descriptive, associational, predictive, or causal), hypothesis when present, and important planned choices |\n| **Evidence and its production** | Methods, data-collection and preparation documentation, instrument documentation, data codebook | Population and unit, recruitment, assignment or exposure, measurement, timing, implementation, exclusions, and completeness |\n| **Design and justification** | Protocol, Methods, analysis plan, supplement | Why the evidence, comparison, measurement interpretation, and uncertainty procedure can support the intended move |\n| **Analysis and inference** | Results, code, or analytical supplement | Estimates such as differences, slopes, probabilities, loadings, or trajectories; uncertainty; and relevant checks |\n| **Bounded answer and reservations** | Discussion and conclusion | Substantive meaning, stated answer, scope, alternatives, and unresolved reservations |\n\n: Where support for a question-answer pair may appear. {#tbl-journey-study-locations tbl-colwidths=\"[25,31,44]\"}\n\nThe information's function determines its component. Methods may\ncontain both production\ndetails and supporting reasons. Results may contain calculations and\nclaims. A reason may also be distributed across the paper, protocol,\nand supplement. Keep a useful page, paragraph, table, or code reference\nso another reader can follow your interpretation.\n\nWhen something consequential remains unclear, describe it in ordinary\nlanguage. If a paper and supplement give different follow-up counts,\nidentify both accounts and the unresolved difference. If you cannot find\nhow allocation was performed, say which materials you examined and what\ntheir account leaves unclear. This describes the accessible support,\nwhile leaving open what may have occurred beyond the available record.\n\n### Reading first, with quality evaluation available separately\n\nReading asks what the study's argument contains and how its contributions\nfit together. **Quality evaluation** asks whether that support is\nadequate for the question and answer. It is a separate, secondary use\nthat depends on understanding the study. You may notice a concern while\nreading and record it alongside your interpretation; identification and\njudgment remain distinguishable without requiring two rigid passes.\n\nThe six evaluation questions in @tbl-journey-evaluation fall into three\ngroups: alignment, support, and translation.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Group | Evaluation question | What to consider |\n|:--|:--|:--|\n| **Alignment** | **Question alignment** | Whether the question, estimand, design, evidence, analysis, and answer remain directed at the same aim |\n| **Support** | **Evidence integrity** | Whether the observations and contextual records, their production, and their representation are trustworthy, traceable, and appropriate |\n| **Support** | **Justification adequacy** | Whether the statistical, design, measurement, and contextual reasons warrant the proposed moves |\n| **Support** | **Inferential adequacy** | Whether reasoning within both layers is adequate, including estimation, uncertainty, checks, sensitivity, and substantive interpretation |\n| **Translation** | **Transition fidelity** | Whether the links between layers retain meaning, uncertainty, design status, and scope |\n| **Translation** | **Claim calibration** | Whether the reported answer's strength and breadth match its support |\n\n: Six questions for evaluating one question-level argument. {#tbl-journey-evaluation tbl-colwidths=\"[17,28,55]\"}\n\nFor an individual evaluation question, use one of four judgments:\n**adequate for this purpose**, **needs revision**, **insufficient\ninformation to judge**, or **not applicable**. Add a reason explaining\nthe particular function or connection being judged.\n\nConsider a variant of the feedback Discussion: \"The program produces\nimportant gains in every form of learning for all students.\" The\nnumerical results stay the same. Reading identifies the claim;\nevaluation identifies why it **needs revision** under Transition\nfidelity and Claim calibration. A course-topic assessment has become\nevery form of learning, and a cohort-average effect has become a benefit\nfor every student. The claim also settles practical importance more\nfirmly than the interval permits.\n\nThe whole question-answer pair also receives one **whole-pair\nconclusion**:\n\n- **Supported as stated:** the available support warrants the answer as\n  reported, including a carefully bounded answer that remains\n  inconclusive.\n- **Supported only after narrowing or revision:** a defensible answer\n  remains after correcting its wording, scope, or analytical support.\n- **Not supported:** the available record gives sufficient grounds to\n  conclude that the proposed answer is unwarranted.\n- **Not assessable from the accessible record:** essential information\n  for judging the whole answer remains unavailable or unresolved.\n\nThe first two conclusions identify an answer warranted by the record,\neither as reported or after revision. The last two distinguish an\nunwarranted answer from one whose support cannot be assessed from the\naccessible record. An argument can fail to support a causal answer\nwithout showing that the effect is absent, and an appropriately\ninconclusive answer can still be supported as stated.\n\nThe overextended feedback variant is **supported only after narrowing\nor revision**, provided the remaining support warrants the narrower\nanswer. A revised answer keeps the positive average estimate, its\ninterval, the eligible cohort, the assessed topics and conditions, and\nuncertainty about the two-point benchmark. This preserves the original\nquestion while correcting what is claimed for its answer. An unclear\nallocation account could instead leave Justification adequacy with\n**insufficient information to judge**; a local judgment and a whole-pair\nconclusion answer different questions.\n\nA fuller supplementary reading tutorial develops practice in tracing\nthese contributions, and an advanced supplementary tutorial develops\ncoordinated questions.\n\n## Conducting Research and Making Its Support Visible\n\nResearchers face the complementary task of producing an informative\nstudy and making its support accessible. Ethics, documentation, and\nreporting accompany this work throughout.\n\n### Ethics and responsibility across the study\n\nIn the feedback study, participation arrangements, consent where\nrequired,\nconfidentiality, and fair access to instruction deserve attention before\nallocation. Implementation needs to respect those arrangements, and\nreporting should describe relevant departures. Protecting students and\npreserving an interpretable comparison are connected responsibilities.\n\nIn student support, the use of a prediction also matters. A rule with\nreasonable average performance may still systematically miss some\nstudents who need help or falsely label others. What follows a prediction\ncan change the consequences: offering an additional conversation differs\nfrom withholding a service. Understanding those consequences calls for\nsubstantive and ethical judgment as well as statistical evaluation.\n\nIn the working-from-home case, linking employee surveys and performance\nrecords also calls for confidentiality and care about employment\nconsequences. A question about performance can be legitimate while the\nhandling and use of identifiable records remain consequential.\n\nResponsibilities extend to access and communication. Researchers can\nmake aggregate results and analysis procedures inspectable while\nprotecting identifiable student records. An account of exclusions and\nmissing outcomes lets readers understand whose experience contributes\nto the findings. Ethical responsibility belongs throughout the study,\nrather than in a final checkbox or a single argument component.\n\n### Reproducibility, reporting, and a visible decision history\n\nA protocol records intended decisions. A data codebook explains the\ndataset. An analytical script connects the designated data to outputs.\nAn assessment guide and implementation account explain their substantive\nmeaning. Together these materials let a reader follow the support\nidentified in the location table.\n\n**Computational reproducibility** means that the same data and specified\ncomputations can produce the reported results [@peng2011]. This makes\ncalculations checkable; design and substantive reasoning determine what\ntheir interpretation supports.\n\nReporting also preserves the history of decisions. A study can identify\nwhat was planned, what was implemented, what changed, when it changed,\nand what evidence was available at the time. Exploratory work has a\nlegitimate place in that history. Its value is clearer when the reader\ncan distinguish an analysis suggested by the results from one specified\nbefore those results were examined.\n\nLarger studies require deliberate coordination among analysts, subject\nspecialists, and authors so that results remain connected to their\nquestions and support. Interpreting and evaluating that support still\nrequires their expertise.\n\n### A compact construction-workflow overview\n\nThe **construction workflow** organizes the work of developing one\nquestion-level argument in six stages and two phases. It covers much\nof the research process, while project administration, collaboration,\nand ongoing ethical responsibilities extend across and beyond its\nstages. Within this approach, it is an auxiliary use for conducting\nresearch.\n\n**Phase 1: Understand and plan**\n\n1. **Review the problem, setting, and relevant literature.** Develop the\n   statistical and substantive reasons for the study.\n2. **Frame the question and, where useful, a candidate answer.** State\n   what needs answering and its intended scope.\n3. **Align design, measurement, estimand, evidence-production or\n   acquisition plan, and inferential plan.** Specify how the proposed\n   data and analysis will address that question.\n\n```{=latex}\n\\Needspace{8\\baselineskip}\n```\n\n**Phase 2: Produce and complete**\n\n4. **Produce or acquire, and document, empirical and contextual\n   evidence.** Preserve the observations and the information needed to\n   understand their production and meaning.\n5. **Estimate, check, and analyse.** Carry out and examine the analytical\n   work while recording relevant results and changes.\n6. **Contextualize, interpret, and complete the bounded answer.** Connect\n   the inference to the substantive question with its uncertainty and\n   scope.\n\nIteration stays within each phase of a cycle: planning can refine the\nquestion and design, while completion can revisit calculations, checks,\nand interpretation. The Stage 3-to-4 handoff is one-way within that\ncycle. This convention makes prior commitments and their revision\nvisible; it leaves room for practical research to reuse data and\nprocedures. For an existing dataset, producing evidence can mean\nacquiring or designating the question-specific analysis data.\n\nThere are three ways a cycle can end. **Normal completion** preserves\nthe question, estimand, and prior commitments, even when the answer is\ninconclusive or contradicts an expectation. **Phase 2 repair** corrects\nwork within those commitments, such as a scoring error, and repeats the\naffected analysis. Once Phase 2 has begun, changing the question,\nestimand, or a prior commitment starts an **additional or revised\ncycle**. When the planned evidence cannot answer the original question,\nrecord that cycle as **not answerable as planned**. That label describes\nthe cycle rather than adding a fourth ending. A new outcome chosen after\nexamining relevant results receives an explicitly exploratory question and\ncycle for those data. A documented revision made before access to those\nresults can remain prospectively specified; preserve its timing and reasons.\nThe appendix gives the fuller Phase 1 anchor and\nshows how the feedback records keep these commitments visible.\n\n## Reading Bridge\n\nAcross the five cases, you can now frame a question and its estimand,\nidentify the data and how they were produced, and recognize a method\nfamily and the reasons for its use. You can also distinguish an estimate\nfrom its uncertainty and interpretation, then follow the support to a\nbounded answer. The argument-based approach connects these contributions\nfor reading a study. Quality evaluation remains a separate secondary\nuse, and the construction workflow an auxiliary use for conducting\nresearch.\n\nChapter 2 builds on this account of how observations arise by examining\nrecorded data: what the entries\nrepresent, how they are organized, which cases support a calculation,\nand how those cases were selected. It then develops distributions, group\nsummaries, and relationships, applying the design reasoning when\ninterpreting them.\nThe same ideas of center, spread, and shape then describe statistics\nacross repeated samples, giving meaning to sampling distributions and\nSE. Statistical inference develops the\ncalculations and conditions for estimates, intervals, and tests.\nGroup comparisons bring these ideas together through one-way and two-way\nANOVA, contrasts, and multiple comparisons. Computational practice in R\nand regression develop their application further.\nGeneralized linear models extend the kinds of outcomes a\nregression can represent; factor analysis and SEM develop measurement\nand linked relationships; mixed-effects models address grouped and\nrepeated observations.\n\nFor further reading, *Introduction to Modern Statistics*\n[@cetinkaya2024] connects questions, data, and statistical reasoning,\nand *Regression and Other Stories* [@gelman2020] connects regression,\ndesign, and interpretation. Work on estimands [@lundberg2021],\neducational measurement standards [@aeraApaNcme2014], and the ASA\nstatement on p-values [@wasserstein2016] develops specific distinctions.\n\nThe argument-based approach is a tutorial synthesis informed by\nToulmin's account of argument [@toulmin2003], LeMire's pedagogical link\nbetween testing and subject-matter claims [@lemire2010], and Kane's\nargument-based treatment of interpretation and use [@kane2013]. The\nlinked components, evaluation questions, and workflow convention bring\nthose influences together for this tutorial, rather than reproducing\none source's arrangement.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n### Key terms {.unnumbered}\n\nUse this short glossary to revisit the chapter's own vocabulary. The\nconcept reference in the Part One introduction gives common\nalternative names and the main explanation of the statistical ideas\nthe later chapters develop.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Question-answer pair | What a study asks and the answer it eventually offers for that question. Each separately owed substantive answer has its own argument. |\n| Traceable information | Specific study content through which an argument component's function can be identified at a documentary location. Identifying that contribution precedes judging its adequacy. |\n| Estimand | The target quantity sought for the named units, conditions, outcome, and scope. It can concern a fixed dataset, a population, a comparison, or prediction performance. |\n| Outcome variable (response variable; dependent variable) | The variable an analysis seeks to describe, compare, or predict. These alternative names share that role in many analyses; a variable's role depends on the question. |\n| Predictor variable (explanatory variable; independent variable) | A variable used to represent an outcome's relationship with other information. These analytical-role labels alone establish neither a causal effect nor statistical independence. |\n| Sampling (recruitment; selection into a study) | How units come to enter a study, by probability selection, volunteering, or availability. It is contrasted with assignment, which concerns the conditions allocated to participating units. |\n| Assignment (allocation) | The allocation of study conditions to participating units, by any mechanism. Actual treatment received may differ from the assigned condition. |\n| Random sampling (probability sampling) | Selecting units from a defined population or sampling frame through a probability mechanism that gives every eligible unit a known, nonzero chance of selection, not necessarily the same chance. \"Random selection\" alone can describe other chance-based decisions. |\n| Random assignment (random allocation) | Allocating study conditions to participating units through a specified probability mechanism. The assigned units may be individuals or groups; realized groups need not be identical. |\n| Causal effect (counterfactual contrast) | The difference between the outcomes that would occur for the same units or target population under two specified conditions, only one of which is observed for each unit. The contrast may be zero; interpreting a comparison causally needs design and identification support. |\n| Confounding | Mixing an exposure's effect with effects of other factors that influence both exposure and outcome. Such a factor is a confounder, a specific causal role. |\n| External validity (generalizability) | Support for extending findings to other people, settings, or conditions. The intended extension determines which similarities and differences matter. |\n| Unit | The entity selected, assigned, measured, or analyzed in a particular operation. The units of assignment, measurement, and analysis can differ, and all are distinct from measurement units such as points or minutes. |\n| Evidence | Observations and contextual records contributing to an answer, including information about how they were produced. |\n| Justification | Reasons and conditions invoked to support a comparison, analytical move, or interpretation. |\n| Inference | Reasoning and analysis connecting evidence and justification to a conclusion. |\n| Bounded claim | The reported conclusion with its uncertainty, conditions, and scope: in the statistical layer, the conclusion about the estimand; in the substantive layer, the question-facing answer with its qualifications. |\n\n: Selected terms for the quantitative research journey. {#tbl-journey-glossary tbl-colwidths=\"[28,72]\"}\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n\\phantomsection\n```\n\n## Exercises {.unnumbered}\n\nEach exercise stands on its own and can be completed by hand, with no\nsoftware required. **Foundational** exercises isolate one reading move.\n**Integrative** exercises combine the moves. Use only the evidence\nprovided unless a prompt explicitly invites outside material.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH01-E01 -->\n### Exercise 1: Read a research question and answer (Foundational) {.unnumbered #ex-ch01-01}\n\nConsider this short passage from an invented feedback study:\n\n> We asked whether assigning explanatory feedback rather than the usual\n> format would improve delayed achievement for eligible students in\n> 24 participating classes. We expected explanatory feedback to help\n> students apply the taught material. Classes were randomly allocated to\n> the two formats. The estimated average assignment effect was 2.50 points\n> on a common assessment two weeks after the six-week program, with a\n> 95% confidence interval from 1.00 to 4.00 points. We conclude\n> that assignment improved average performance on the assessed topics in\n> these classes under the study conditions.\n\na. Identify the research question, substantive expectation, numerical\n   result, and reported answer. Explain how the result contributes to the\n   answer and what the answer adds.\nb. State the estimand in words, including the comparison, outcome,\n   students, and timing. Explain how it differs from the estimate of\n   2.50 points.\nc. Write a descriptive question that the same assessment records could\n   address. Explain how the answer sought differs from the assignment\n   effect in the passage.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH01-E02 -->\n### Exercise 2: Make sense of variables and records (Foundational) {.unnumbered #ex-ch01-02}\n\nThe student-outcomes codebook includes admission grade, first-semester\napproved-unit count, and course and outcome categories. An invented\nextension adds a low-to-high ordered rating of confidence. A separate\ninvented language-learning record stores student ID, classroom ID,\nschool ID, assessment occasion, and achievement score in long form,\nwith four equally spaced occasions for each student. Student A's scores\nare 58, 65, 68, and 76; Student B's are 62, 63, 67, and 68.\n\na. Identify quantitative measurements or scores, discrete counts,\n   nominal categories, and ordinal categories. Explain why a course\n   code remains categorical even when its stored value is a number.\nb. For enrollment-time prediction, identify the outcome and one eligible\n   predictor from the codebook. Explain why a first-semester result\n   would become available too late, even if it predicts the outcome\n   well. What would change if the prediction were made after that\n   semester?\nc. Describe what one row represents in the language-learning record and\n   where repeated and hierarchical structure appear. Name one item a\n   codebook or data-record description should clarify. Use the two\n   score sequences to explain how equally spaced assessment times can\n   accompany uneven changes in achievement.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH01-E03 -->\n### Exercise 3: Read design before interpreting a difference (Integrative) {.unnumbered #ex-ch01-03}\n\nTwo invented studies concern peer study and course achievement.\n\n- **Study A:** A probability sample of 1,000 students from a university\n  reports its weekly participation in peer study. Researchers obtain\n  semester grades and compare participants with nonparticipants.\n- **Study B:** Among 160 eligible volunteers at the same university,\n  researchers randomly assign 80 to an offer of a peer-study program and\n  80 to usual study arrangements. All supply semester grades. Some\n  students offered the program attend few sessions.\n\na. Identify how students entered each study and whether the researchers\n   assigned a condition. Explain what random sampling and random\n   assignment contribute to the respective comparisons.\nb. Study A finds higher average grades among peer-study participants.\n   Explain how prior motivation could contribute to that difference.\n   What causal question can Study B's assigned-group comparison address,\n   and why does it differ from the effect of attending every session?\nc. For each study, state a population or group its result could concern\n   under the stated design. Identify one piece of further information\n   needed before extending Study B's finding to all university students.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH01-E04 -->\n### Exercise 4: Connect methods to the work they perform (Foundational) {.unnumbered #ex-ch01-04}\n\nConsider enrollment-time prediction of recorded Dropout status,\ncomparing delayed achievement after class-randomized feedback, and\nexamining language scores recorded repeatedly for students who share\nclassrooms.\n\na. Suggest a method family for each question and explain one reason\n   involving the outcome, design, or data structure. More than one\n   family may provide a reasonable representation.\nb. In the feedback analysis, distinguish specifying a straight-line\n   relationship between baseline and delayed scores, estimating its\n   intercept and slope, comparing a common slope with format-specific\n   slopes, and modifying the specification after seeing a curved\n   residual pattern.\nc. Explain why a GLM could be useful for the student prediction\n   question. What would held-out records tell you after model\n   development? What additional evidence would strengthen a claim about\n   performance for students enrolling in a later cohort?\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH01-E05 -->\n### Exercise 5: Turn a result into a bounded answer (Integrative) {.unnumbered #ex-ch01-05}\n\nIn the feedback study, the estimated assignment effect is 2.50 points on\nthe common 0 to 40 delayed achievement assessment, with an approximate\n95% interval from 1.00 to 4.00 points. The local educational benchmark\nis two points and has a stated assessment-based rationale. The study\nconcerns eligible students in participating classes, assessed two weeks\nafter a six-week program.\n\na. Distinguish the estimand, point estimate, and interval. What does the\n   interval leave unresolved about the size of the effect relative to\n   the benchmark?\nb. Explain why this result alone would leave a claim about all learning,\n   in all schools, over a full year unresolved.\nc. Write a short answer to the original feedback question that retains\n   magnitude, uncertainty, and the stated outcome and setting.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n<!-- prompt-id: CH01-E06 -->\n### Exercise 6: Read an argument, then evaluate its quality (Integrative) {.unnumbered #ex-ch01-06}\n\nUse the feedback study's report and protocol extracts in the appendix.\n\na. Identify the question-answer pair. Find information contributing to\n   each statistical component and explain its function, indicating the\n   passage or material that helped you identify it.\nb. Identify substantive information that situates the scores, augments\n   the statistical justification, interprets the result, and bounds the\n   question-facing answer. Explain one of these connections in your own\n   words.\nc. Now evaluate the variant conclusion, \"This format produces\n   substantial, lasting improvements in learning in any school.\" Apply\n   Question alignment and Claim calibration, and any other question\n   needed for your reasoning. Give a whole-pair conclusion and a\n   justified revised answer, clearly separating this evaluation from\n   your reading account.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n\\phantomsection\n```\n\n## Appendix: Records for the Shared Cases {.unnumbered}\n\nThese records supply the material behind the examples. Use them to\nfollow a reported number, revisit a study's conditions, or locate\ninformation for the worked reading and exercises.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n### Student outcomes {.unnumbered}\n\nThe source follows entrants at the Polytechnic Institute of Portalegre,\nPortugal, from 2008/09 to 2018/19. Outcomes were recorded at the normal\nduration of their degree: three years, or four for nursing\n[@realinho2022]. Recorded Dropout can include a change of course or\ninstitution; Enrolled means still enrolled at that endpoint. Graduate\nidentifies completion. The released data cover 4,424 students\n[@uci697].\n\nThe simplified analysis asks how well admission grade and age at\nenrollment predict recorded Dropout versus the other two categories\ncombined. It retains the original categories in the dataset and assigns\nabout 70% of each binary outcome group to training, leaving the rest\nfor an internal assessment.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n| Dataset | Dropout | Enrolled | Graduate | Total |\n|:--|--:|--:|--:|--:|\n| Full release | 1,421 | 794 | 2,209 | 4,424 |\n| Training | 994 | 562 | 1,540 | 3,096 |\n| Held-out test | 427 | 232 | 669 | 1,328 |\n\n: Students in the simplified prediction analysis. {#tbl-journey-student-record tbl-colwidths=\"[30,17,17,18,18]\"}\n\nOn the held-out data, average squared prediction error was 0.2000 for\nthe logistic rule using admission grade and age, against 0.2182 for\npredicting the training-data dropout proportion for everyone:\n\n$$\n\\frac{1}{1328}\\sum_i(\\widehat p_i-y_i)^2=0.2000\\ \\text{(logistic rule)}\n\\qquad\\text{versus}\\qquad 0.2182\\ \\text{(training-prevalence rule)},\n$$\n\nwhere $\\widehat p_i$ is the predicted probability and $y_i$ the recorded\nDropout indicator, coded 1 for Dropout and 0 otherwise, for each of the\n1,328 held-out students.\nAt a probability threshold of 0.5, the logistic rule\nidentified 73 of the 427 students with recorded Dropout status, about\n17.0960%. Its use for later cohorts and the value of acting on an alert\nremain to be established. Semester results\nwere excluded because they become available after enrollment; the\nreleased file also has no cohort-year field for a later-cohort check.\n\nThe data are provided by Realinho, Vieira Martins, Machado, and\nBaptista under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)\n[@uci697]. The three fields used here, the binary coding, the split, and\nthe logistic rule are adaptations for this chapter; the source authors\nbuilt other machine-learning classifiers, and the analysis can be\nrepeated from the public release. Reading the chapter requires no\nprogramming.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n### Feedback {.unnumbered}\n\nThe invented report supplies an estimated assignment effect of 2.50\npoints and a 95% interval from 1.00 to 4.00 points. These quantities support\nthe chapter's reading exercises; a numerical derivation is outside this\nexample.\n\nThe report and supporting materials describe the study as follows.\n\n> **Paper, Methods:** Twelve participating schools contributed two\n> classes each, with 20 eligible students per class. Before the six-week\n> program, 12 of the 24 classes were randomly assigned to each format\n> across the full class pool. A common 0-40 assessment was administered two weeks after the\n> program. All 480 eligible students supplied scores and were analyzed\n> according to their class's assignment.\n>\n> **Protocol, design and analysis:** Random allocation supplies the\n> basis for the assignment comparison. Comparing equally weighted class\n> means gives students equal weight because class sizes are equal. The\n> uncertainty procedure reflects assignment of classes. The inference assumes implementation of the allocation,\n> a common outcome definition, complete follow-up, and no influence of\n> one class's assignment on another class's outcomes.\n>\n> **Assessment and implementation supplement:** Both formats used the\n> same taught topics and scheduled time. Explanatory feedback added\n> explanations of errors; the usual format supplied correctness\n> feedback. Delivery logs documented these activities and separate\n> materials. The assessment blueprint linked tasks to the topics,\n> and scorers worked without knowledge of format. The curriculum team\n> judged a two-point gain, equivalent to full credit on an application\n> task, worth considering against the additional preparation.\n>\n> **Analytical supplement:** Checks confirmed the score range, class\n> assignments, denominators, and complete outcomes. Recalculating the\n> mean contrast with each school omitted in turn left the point estimate\n> positive.\n> Those reduced-record checks describe influence on the estimate;\n> the full eligible cohort remains the basis of the primary answer.\n\nThe report concludes that assignment improved average assessed\ncourse-topic performance in these classes and conditions, with the\npractical size uncertain and broader learning and individual effects\nunresolved. Its Results and Discussion excerpts appear in Section 5.\nThe separate straight-line and curved plots illustrate relationships\nwith baseline achievement; their values are separate from the supplied\nassignment-effect result.\n\nThe **Phase 1 anchor** records the question and mode, estimand, design,\nmeasurement, evidence-production or acquisition plan, inferential plan,\nand, where relevant, a stopping rule stating when data collection can\nend. Here the protocol commits to the\neligible-cohort assignment effect, formats, delayed assessment, student\nweighting, and analysis. The codebook records school, class, assigned\nformat, pre-program baseline achievement score, delayed assessment score,\nand analysis membership. The analysis record connects\nthose commitments to the contrast, interval, checks, and reported\nanswer, while dated changes remain visible.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n### Short supporting records {.unnumbered}\n\n**Working from home.** Group counts are 131 assigned to home work and\n118 to office work (Appendix Table A.2, p. 214); eligibility and the\nnine-month, four-home-day schedule appear on p. 169. Table II, column 4\n(p. 187) reports the result for 134 order takers, interpreted on p. 188\nas about 13% more weekly calls [@bloom2015wfh]. Other outcomes use\ndifferent measures or employee groups. The\n[author's paper, appendix, and replication materials](https://nbloom.people.stanford.edu/research)\nalso include nonexperimental employees for Table IV; record analysis\nmembership when reusing these files.\n\n**Confidence and belonging.** Confidence concerns handling learning\ntasks; belonging concerns acceptance and inclusion in the academic\ncommunity. Three 0-100 confidence indicators concern explaining,\napplying, and checking; three belonging indicators concern acceptance,\ninclusion, and participation. @fig-journey-measurement-map shows a\ncandidate representation. Each indicator also has variation beyond\nits factor; item content, scoring, and occasion help establish what the\nrepresentation means.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![A candidate measurement map for confidence and belonging. Arrows show proposed measurement relationships; the two-headed link represents a possible factor correlation. Indicator-specific variation is omitted from this sketch.](chapter_01_files/figure-html/fig-journey-measurement-map-1.png){#fig-journey-measurement-map fig-pos='H' fig-alt='A confidence factor points to explaining, applying, and checking indicators. A belonging factor points to acceptance, inclusion, and participation indicators. A two-headed link connects the factors. This is a proposed measurement map, not an estimated model.' width=600}\n:::\n:::\n\n\n**Language-learning progress.** The four equally spaced assessments\nuse a common 0-100 scale. Student A scores 58, 65, 68, and 76; Student B\nscores 62, 63, 67, and 68. Their successive gains are 7, 3, and 8 points\nand 1, 4, and 1 point, respectively. Student, classroom, school, and\noccasion identifiers preserve the grouping and timing. These trajectories\nshow different starting levels, overall gains, and uneven changes\nbetween assessments. A full growth study would also document other\nstudents, scoring comparability, missed occasions, and changing learning\nconditions.\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n\\phantomsection\n```\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}