{
  "hash": "509931c45cab5992493da9fa034265e1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Regression II: Categorical Predictors, Model Comparison, Nonlinearity, and Robust Uncertainty\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{16\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\\clearpage\n\n::: {.callout-note title=\"Chapter overview\"}\nChapters 7 and 8 fitted lines and additive models and read them as\nconditional comparisons. Along the way they used tools they could only\nname: a factor coded as 0/1 columns, a contrast between two categories, a\njoint test of several added coefficients, an information criterion, a\nsquared predictor, a logged outcome, a covariance estimate that allows\nunequal spread, and a covariance that respects pupils sitting in schools.\nThis chapter develops each of them once, on the same 98 occupation\nrecords, on a small randomized reading study with a pretest, and then on\nProject STAR, where a randomized design supplies a different warrant. By\nthe end of the chapter you will be able to code and read a factor with\nseveral levels, estimate a contrast with the right uncertainty, read an\nanalysis of covariance as a regression on a randomized pretest--posttest\nstudy, compare nested models and read AIC and BIC, change a predictor's\nform or an outcome's scale and say what question changed, choose between\nclassical, HC3, cluster-robust, and bootstrap uncertainty for a stated\nreason, and say what none of these calculations repairs.\n:::\n\nA regression report rarely stops at one additive equation. It compares\ngroups that are categories, adjusts a comparison for a baseline score,\nasks whether a set of added variables matters jointly, ranks candidate\nmodels, lets a relationship curve or a scale change, and reports\nuncertainty calculated in more than one way. Each of these steps has a\nsmall mathematics of its own and a temptation of its own: reading a\ncoefficient as \"the effect of type\", adding two standard errors,\ncomparing criteria across different outcomes, or treating a robust\nstandard error as a repair for a design problem.\n\nWe keep the occupation records of Chapter 8, with their 98 complete rows,\nincome in thousand 1971 Canadian dollars, and the additive model of\neducation, prestige, percentage of women, and type, so that every tool is\nseen on numbers already read. Two further studies join them where the\noccupations cannot teach the point: a randomized reading study with a\npretest, for the analysis of covariance, and Project STAR, where the\nuncertainty calculation has to follow the design that produced the data.\nKeeping the records fixed makes one distinction visible throughout:\nchanging a model, changing a question, and changing an uncertainty\ncalculation are three different acts.\n\nThe R code shown is the one call that produces each new quantity; the\nComputer Lab carries the preparation, the checks and the variations. The\ntype levels remain *bc*, *prof*, and *wc*, the full additive formula\nremains `income_k ~ education + prestige + women + type`, and every\nadjusted type comparison names education, prestige, and the percentage of\nwomen as its conditioning set. Where Chapter 8's appendices already\nworked a tool through on these records (the group means recovered by\nindicators, the overall $F$, the HC3 covariance, and the Normal\nlikelihood behind AIC and BIC), this chapter points back to that\nworking and adds the new use.\n\n\\clearpage\n\n## Predictors That Are Categories {#sec-ch9-factors}\n\n### One indicator, then several\n\nChapter 7, Section 3.3, fitted a single 0/1 predictor to 24 invented\nfeedback-by-practice scores. The fitted line passed through the two group\nmeans, its slope was the difference between them, 4 with SE 1.6967 and\n$t=2.3575$ on 22 df, and that test was the equal-variance two-sample test\nwritten as a regression. Nothing about that arrangement is special to two\ngroups.\n\nA factor with $J$ levels enters a regression as $J-1$ indicator columns.\nOne level is omitted and becomes the **reference**: the intercept is its\nfitted mean, and each indicator coefficient is a difference from it. With\nthree occupation types and blue-collar as the reference,\n\n$$\n\\widehat y_g=\\widehat\\alpha+\\widehat\\delta_{\\mathrm{prof}}D_{\\mathrm{prof}}\n+\\widehat\\delta_{\\mathrm{wc}}D_{\\mathrm{wc}},\\qquad\n\\widehat\\mu_{\\mathrm{bc}}=\\widehat\\alpha,\\quad\n\\widehat\\mu_{\\mathrm{prof}}=\\widehat\\alpha+\\widehat\\delta_{\\mathrm{prof}},\\quad\n\\widehat\\mu_{\\mathrm{wc}}=\\widehat\\alpha+\\widehat\\delta_{\\mathrm{wc}}.\n$$\n\nTwo indicators, not three, carry three means. A third column would equal\nthe intercept column minus the other two, so the design matrix would lose\nfull rank and no coefficient would be separately estimable. Which level\nis omitted is therefore a choice of coordinates, not a choice of model.\n\nThe occupation records and models are those of Chapter 8, re-created here\nso that every later calculation has a stated origin: `m0`, `m1`, and `m2`\nare the education-only, the education-and-prestige, and the full additive\nmodels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprestige <- carData::Prestige\nprestige$income_k <- prestige$income / 1000\nd <- prestige[!is.na(prestige$type), ]\nd$type <- factor(d$type, levels = c(\"bc\", \"prof\", \"wc\"))\nm0 <- lm(income_k ~ education, data = d)\nm1 <- lm(income_k ~ education + prestige, data = d)\nm2 <- lm(income_k ~ education + prestige + women + type, data = d)\n```\n:::\n\n\nThe 98 retained records hold 44 blue-collar, 31 professional, and 23\nwhite-collar occupations, and the full model fits six coefficients, leaving\n92 residual degrees of freedom. Complete-case selection is how these rows\nwere chosen; it is not random sampling from a labour market\n[@carData2022; @fox2019].\n\n### Indicators recover fitted group means\n\nFit income on type alone and read the coefficients against\n@fig-ch9-indicators. A blue-collar occupation carries 0 in both indicator\ncolumns, a professional one a 1 in the first, and a white-collar one a 1\nin the second, so each type's fitted value is the intercept plus that\ntype's coefficient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_fit <- lm(income_k ~ type, data = d)\ncoef(group_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)    typeprof      typewc \n   5.374136    5.185315   -0.321832 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Income of the 98 occupations by type. Bars mark the group means; the dashed line is the blue-collar mean, the intercept, and the arrows are the two indicator coefficients, 5.1853 and −0.3218.](chapter_09_files/figure-html/fig-ch9-indicators-1.png){#fig-ch9-indicators fig-pos='!ht' fig-alt='Jittered open circles of income in thousand dollars for 44 blue-collar, 31 professional and 23 white-collar occupations, with a thick bar at each group mean, about 5.37, 10.56 and 5.05. A dashed horizontal line at the blue-collar mean runs across the plot. An upward arrow from the dashed line to the professional mean is labelled 5.1853 higher and a short downward arrow to the white-collar mean is labelled 0.3218 lower. Professional incomes spread from about 4.6 to 25.9 thousand dollars; the other two types stay below 9.' width=614.4}\n:::\n:::\n\n\nThe coefficients are 5.3741, 5.1853, and $-0.3218$. The intercept is the\nblue-collar mean, the dashed line in the figure, and each coefficient is\nan arrow from that line to another type's mean: professional occupations\naverage 5.1853 thousand dollars more, white-collar occupations 0.3218\nless. The fitted means, 5.3741, 10.5595, and 5.0523, are exactly the\nobserved means, for the reason Chapter 8, Appendix A, gave: with one\nfree parameter per group, least squares returns each group's own mean. A\ngroup-only regression is therefore a description of three means with no\nadjustment in it at all.\n\nThe figure also shows what three means leave out. Professional incomes\nspread from about 4.6 to 25.9 thousand dollars, while the other two types\nstay below 9; Section 5 returns to that difference in spread.\n\nKeep this description apart from the adjusted comparison of the full\nmodel. In `m2` the professional and white-collar coefficients are 0.3242\nand 0.2353: they compare fitted incomes at the *same* education,\nprestige, and percentage of women, not the observed incomes of\ndifferently composed groups. The raw professional advantage of 5.1853\nthousand dollars and the adjusted 0.3242 answer different questions, and\nneither is \"the effect of occupational type\".\n\n### Releveling and centering change coordinates, not the fit\n\nReleveling makes a different level the reference. Refit the group-only\nmodel with white-collar as the reference:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroup_fit_wc <- lm(income_k ~ relevel(type, ref = \"wc\"), data = d)\ncoef(group_fit_wc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  (Intercept)   relevel(type, ref = \"wc\")bc \n                     5.052304                      0.321832 \nrelevel(type, ref = \"wc\")prof \n                     5.507147 \n```\n\n\n:::\n:::\n\n\nThe coefficients are now 5.0523, 0.3218, and 5.5071: the intercept is the\nwhite-collar mean, and the two coefficients measure the blue-collar and\nprofessional means from it. The fitted values and residuals are\nunchanged, as Chapter 8, Appendix A, stated; the same three means are\nreported in a different coordinate system. The full model behaves the\nsame way. Releveling `m2` to\nwhite-collar gives intercept 0.6559, blue-collar $-0.2353$, and\nprofessional 0.0889, while the education, prestige, and women\ncoefficients stay exactly as they were.\n\nCentering a continuous predictor is the analogous operation: subtracting\na constant moves the profile the intercept refers to, and leaves every\nfitted value, residual, and fixed substantive contrast alone. Two\nconsequences are worth keeping. A coefficient's size means nothing\nwithout its reference; \"the professional coefficient\" is short for\n\"professional minus whichever level is currently omitted\". And neither\nreleveling nor centering creates information. Chapter 8 documented how\nthin the joint support across types is at common education and prestige\nvalues; changing coordinates adds no observed comparison.\n\n### The one-way analysis of variance of Chapter 4 as a regression\n\nChapter 4 tested equality of several group means with a one-way analysis\nof variance. In the group-only regression that null says that both\nindicator coefficients are zero, so the reduced model is the\nintercept-only model, whose residual sum of squares is the total sum of\nsquares about the grand mean. Comparing the two models gives\n\n$$\nF=\\frac{(RSS_{\\mathrm{reduced}}-RSS_{\\mathrm{full}})/2}\n{RSS_{\\mathrm{full}}/(98-3)}\n=\\frac{(1734.0792-1138.123)/2}{1138.123/95}=24.8725.\n$$\n\nThe numerator is the reduction in residual sum of squares that the two\nindicators buy, per indicator; the denominator is the group-only model's\nresidual mean square on its 95 degrees of freedom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(lm(income_k ~ 1, data = d), group_fit)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F| Pr(>F)|\n|------:|--------:|--:|---------:|--------:|------:|\n|     97| 1734.079| NA|        NA|       NA|     NA|\n|     95| 1138.123|  2|  595.9562| 24.87246|      0|\n\n</div>\n:::\n:::\n\n\n`aov()` returns the same statistic from the same fitted means, the same\nresidual sum of squares, and the same degrees of freedom. The equality is\nalgebraic. It holds whether or not group membership was randomized, so it\nsupplies no causal warrant of its own; Section 7 shows what a randomized\ndesign adds. The Chapter 4 cautions travel with the identity. An omnibus\n$F$ says that the three means are not all equal under the stated\nreference distribution; it does not say which differ, and any comparison\nchosen after looking at this result still needs the family calibration of\nChapter 4. The next section gives the calculation that a single declared\ncomparison requires.\n\n## Contrasts and Adjusted Group Comparisons {#sec-ch9-contrasts}\n\n### A contrast needs coefficient covariance\n\nA **contrast** is a declared linear combination of coefficients,\n$C=\\mathbf c^{\\mathsf T}\\boldsymbol\\beta$, named before the comparison is\nread. Its estimate is the same combination of the fitted coefficients,\nand its variance is the corresponding quadratic form in the coefficient\ncovariance matrix $\\widehat{\\mathbf V}$:\n\n$$\n\\widehat C=\\mathbf c^{\\mathsf T}\\widehat{\\boldsymbol\\beta},\\qquad\n\\widehat{\\operatorname{Var}}(\\widehat C)=\\mathbf c^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf c,\\qquad\nSE(\\widehat C)=\\sqrt{\\mathbf c^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf c}.\n$$\n\nFor a difference of two coefficients the quadratic form reduces to\n$\\operatorname{Var}(b_1)+\\operatorname{Var}(b_2)-2\\operatorname{Cov}(b_1,b_2)$.\nTake professional minus white-collar in `m2`, whose coefficients are\nordered intercept, education, prestige, women, professional,\nwhite-collar, so that $\\mathbf c=(0,0,0,0,1,-1)^{\\mathsf T}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc_vec <- c(0, 0, 0, 0, 1, -1)\nV <- vcov(m2)\nc(estimate = sum(c_vec * coef(m2)),\n  SE = sqrt(drop(c_vec %*% V %*% c_vec)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  estimate         SE \n0.08886278 1.07999307 \n```\n\n\n:::\n:::\n\n\nThe estimate is $0.3242-0.2353=0.0889$ thousand dollars. Its variance\nassembles the two coefficient variances and their covariance,\n\n$$\n2.1406+0.9698-2(0.972)=1.1664,\n$$\n\nso the SE is 1.08 and, with $t_{.975,92}=1.9861$, the 95% interval is\n$[-2.0561,\\ 2.2338]$.\n\nThe covariance matters because the two type coefficients move together.\nBoth are measured from the same blue-collar reference at the same values\nof the continuous predictors, and their estimated correlation is .6746: a\nsample that overstates one tends to overstate the other, so their\ndifference varies less than either movement alone suggests. Dropping the\ncovariance would give an SE of 1.7636, and adding the two standard\nerrors, $1.4631+0.9848=2.4479$, gives a number that is not the standard\nerror of anything. Only the quadratic form is the variance of the\ndeclared comparison.\n\nThe vector $\\mathbf c$ is the question written down. One entry set to 1\nand the rest to 0 returns an ordinary coefficient with its usual SE.\nEntries on the type coefficients that sum to zero, with the intercept\nentry 0, make a contrast in the Chapter 4 sense, and such a contrast names\nthe same comparison whichever level is the reference; that is why Section\n1.3 found the same 0.0889 as the professional coefficient of the releveled\nfit. Declaring the comparison in advance matters as much as computing it\ncorrectly: a contrast chosen because it looked large in the fitted\ncoefficients is a selection from a family, and it needs Chapter 4's\ncalibration for that family.\n\nRead the interval for what it is: a working-model benchmark for\nprofessional against white-collar occupations at the same education,\nprestige, and percentage of women. It covers zero, so these records leave\nthe comparison unresolved, and its width does not overcome the thin\ncross-type support that Chapter 8 documented. An interval can be\narithmetically correct and still describe a comparison that the records\nbarely observe.\n\n### Adjusted block tests\n\nA contrast tests one declared combination. A **block test** asks whether\na set of coefficients is jointly zero; it is the nested-model comparison\nof Section 1.4 with a different reduced model. Two blocks are worth\ntesting here, and they are different questions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nno_type <- lm(income_k ~ education + prestige + women, data = d)\nanova(m1, m2)\nanova(no_type, m2)\n```\n:::\n\n\nAdding the percentage of women and the two type indicators to `m1` tests\nthree restrictions against the full model's 92 residual degrees of\nfreedom; dropping type from the full model tests two restrictions against\nthe same denominator.\n\n| Added | df | $F$ | $p$ |\n|:--|--:|--:|--:|\n| Women and type | 3 | 11.5088 | $<.0001$ |\n| Type after women | 2 | 0.0319 | .9686 |\n\n: Two declared adjusted block comparisons. {#tbl-ch09-blocks tbl-colwidths=\"[40,15,20,25]\"}\n\nThe first block is strongly supported: $F(3,92)=11.5088$ against a 5%\ncritical value of 2.7036. The second is not: $F(2,92)=0.0319$ with\n$p=.9686$ against a critical value of 3.0954. Neither result says what it\nis often read as saying. Joint evidence for the first block does not\nestablish that each of the three added columns contributes; the\npercentage of women could be carrying the whole block. And the second\nresult is not proof that occupational type is irrelevant. It says that,\nonce education, prestige, and the percentage of women are in the\nequation, the two type indicators add no detectable reduction in residual\nsum of squares *on these 98 records*, where the types barely overlap on\nthe other predictors.\n\nTwo further distinctions matter. `anova(m2)` on a single model gives\n**sequential** sums of squares in formula order: each line tests a term\ngiven only the terms above it, so the answers depend on the order in which\nthe formula was written, and only the last line coincides with the\ncorresponding block test. And Welch-type and robust-covariance tests are\ndifferent procedures with different reference distributions; Section 5\ngives the robust version of this type block.\n\n### The analysis of covariance as regression {#ch09-ancova}\n\nA randomized study with a baseline measurement asks the group question in\na sharper form. Baumann and colleagues randomly assigned 68 fourth-grade\npupils in one school to three reading-instruction conditions\n[@baumann1992]: DRA, a directed reading activity from the basal\nprogramme; DRTA, a directed reading-thinking activity; and think-aloud\nstrategy instruction. Before and after the lessons, each pupil took an\nerror-detection test of comprehension monitoring. The `carData::Baumann`\ndistribution holds the 66 pupils with a recorded first posttest, 22 per\ngroup. The analysis here uses the first pretest and the first posttest,\nlabels the groups DRA, DRTA, and Think-aloud, and takes DRA as the\nreference; the original investigators analysed further outcomes and both\npretests.\n\nThe **analysis of covariance** adds the pretest to the group comparison\nas one more predictor with a single slope:\n\n$$\nY_{ij}=\\mu_j+\\beta(X_{ij}-\\bar X)+\\varepsilon_{ij},\\qquad\n\\bar Y_j^{\\,\\mathrm{adj}}=\\bar Y_j-\\widehat\\beta(\\bar X_j-\\bar X).\n$$\n\nHere $Y_{ij}$ and $X_{ij}$ are the posttest and pretest of pupil $i$ in\ngroup $j$. The group terms $\\mu_j$ shift the line up or down, and the\npretest enters once, so every group's line has the same slope $\\beta$. An\n**adjusted mean** is a group's fitted mean at a stated pretest value. At\nthe grand pretest mean $\\bar X$ it is the group's observed posttest mean\n$\\bar Y_j$ moved along the common slope by the group's pretest departure\nfrom $\\bar X$, which is the second equation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreading <- carData::Baumann\nreading$group <- factor(reading$group,\n  levels = c(\"Basal\", \"DRTA\", \"Strat\"),\n  labels = c(\"DRA\", \"DRTA\", \"Think-aloud\"))\nancova <- lm(post.test.1 ~ group + pretest.1, data = reading)\ncoef(ancova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     (Intercept)        groupDRTA groupThink-aloud        pretest.1 \n      -0.5966478        3.6265538        2.0361644        0.6931872 \n```\n\n\n:::\n\n```{.r .cell-code}\npredict(ancova, interval = \"confidence\",\n  newdata = data.frame(group = levels(reading$group),\n    pretest.1 = mean(reading$pretest.1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr       upr\n1 6.188185 5.143481  7.232889\n2 9.814739 8.779995 10.849482\n3 8.224349 7.181274  9.267425\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Posttest against pretest for the 66 Baumann pupils. The parallel lines are the common-slope fit over the common pretest support 6--14; each filled symbol marks a group's observed pretest and posttest means, and its arrow follows the group's line to the grand pretest mean 9.7879, where the open symbol marks the adjusted mean.](chapter_09_files/figure-html/fig-ch9-ancova-1.png){#fig-ch9-ancova fig-pos='!ht' fig-alt='Grey points for DRA (circles), DRTA (triangles) and Think-aloud (squares) pupils, pretest from 4 to 16 and posttest from 1 to 15, slightly jittered. Three parallel fitted lines with slope about 0.69 run from pretest 6 to 14: DRTA highest, Think-aloud in the middle and DRA lowest. A vertical line marks the grand pretest mean 9.79, where open symbols mark the adjusted means. The DRA mean, a filled circle at pretest 10.5 and posttest 6.68, moves down its line to 6.19; the Think-aloud mean, at 9.14 and 7.77, moves up to 8.22; the DRTA mean, at 9.73 and 9.77, barely moves, to 9.81, so its filled and open triangles almost coincide.' width=614.4}\n:::\n:::\n\n\nRead @fig-ch9-ancova from each filled symbol, which marks a group's\nobserved pretest and posttest means, to the open symbol on the vertical\nline, which marks its adjusted mean. The DRA group happened to start\nhighest, 0.7121 points above the grand pretest mean of 9.7879. Following\nits line to the grand mean lowers its posttest mean by\n$0.6932\\times0.7121$, from 6.6818 to 6.1882. Think-aloud started 0.6515\npoints below the grand mean and rises from 7.7727 to 8.2243, while DRTA,\nalmost exactly at the grand mean, barely moves, from 9.7727 to 9.8147.\nThe fit gives the common slope 0.6932 (SE 0.1015), the differences from\nDRA of 3.6266 (SE 0.7362) for DRTA and 2.0362 (SE 0.7450) for\nThink-aloud, and a residual mean square of 5.894 on 62 degrees of\nfreedom. Tested together after the pretest, the two group coefficients\ngive $F(2,62)=12.1689$, $p<.0001$, and the printed adjusted means carry\nthe 95% intervals $[5.1435,\\ 7.2329]$, $[8.7800,\\ 10.8495]$, and\n$[7.1813,\\ 9.2674]$.\n\nThree conditions carry that reading. The adjusted means need a **common\nreference**, here the grand pretest mean. That reference must lie inside\nevery group's observed pretest range, the **common support**: the groups'\npretests run from 4 to 16, 6 to 16, and 4 to 14, so the lines are drawn\nover 6 to 14, and an adjusted comparison read outside that band would rest\non extrapolation. And the comparison needs a stated **averaging\npopulation**: for this additive linear model, predicting every group at\nthe grand pretest mean gives the same values as predicting every group\nover the pupils' common pretest distribution and averaging. Because the\nlines are parallel, the adjusted differences, 3.6266 and 2.0362, are the\nsame at any pretest value inside the common support; the adjusted means\nthemselves are not, which is why the reference value is always stated.\n\n### Posttest only, gain score, and covariance adjustment as one regression {#ch09-ancova-pretest}\n\nThree analyses are common for a randomized pretest--posttest study:\ncompare the posttest means, compare the gains (posttest minus pretest), or\nadjust for the pretest as above. They are one regression that differs only\nin the pretest coefficient $\\gamma$:\n\n$$\nY_i-\\gamma X_i=\\alpha+\\delta_{\\mathrm{DRTA}}D_{\\mathrm{DRTA},i}\n+\\delta_{\\mathrm{TA}}D_{\\mathrm{TA},i}+\\varepsilon_i,\\qquad\n\\gamma=0,\\ 1,\\ \\text{or estimated}.\n$$\n\nWith $\\gamma=0$ the model compares posttest means, with $\\gamma=1$ it\ncompares gains, and with $\\gamma$ estimated it is the analysis of\ncovariance. In R, `offset()` enters the pretest with its coefficient fixed\nat 1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npost_only <- lm(post.test.1 ~ group, data = reading)\ngain <- lm(post.test.1 ~ group + offset(pretest.1), data = reading)\n```\n:::\n\n\n| Analysis | Pretest coefficient | DRTA minus DRA (SE) | Think-aloud minus DRA (SE) | Residual SD (df) |\n|:--|:--|:--|:--|:--|\n| Posttest only | 0 | 3.0909 (0.9614) | 1.0909 (0.9614) | 3.1885 (63) |\n| Gain score | 1 | 3.8636 (0.7779) | 2.4545 (0.7779) | 2.5799 (63) |\n| Analysis of covariance | 0.6932, estimated | 3.6266 (0.7362) | 2.0362 (0.7450) | 2.4278 (62) |\n\n: Three analyses of the Baumann records as one regression. {#tbl-ch09-three-analyses tbl-colwidths=\"[24,18,20,20,18]\"}\n\nUnder random assignment the expected pretest difference between groups is\nzero, so all three analyses estimate the same average difference in\nposttest scores. Strictly, random assignment covers the 68 pupils\nassigned, while these analyses use the 66 with a recorded first\nposttest; the argument carries over to the 66 if, for example, the two\nposttests went missing for reasons unrelated to what those pupils would\nhave scored, a complete-record condition that the design does not\nguarantee and the records cannot check. The three analyses differ in precision and in how\nthis sample's chance pretest imbalance enters. Here the pretest means\nare 10.5000, 9.7273, and 9.1364, so DRA started with a head start of 0.7727 points over DRTA,\nabout a quarter of the pretest SD of 3.0205 across all 66 pupils. The\nsize of that gap is what matters. A significance test of it would add\nnothing: random assignment already makes any baseline gap a chance gap,\nso such a test would examine a null hypothesis known to be true.\n\nThe gap accounts exactly for the spread of the estimates in\n@tbl-ch09-three-analyses. Each DRTA estimate is the posttest-only\ndifference plus $\\gamma$ times the DRA group's pretest head start,\n$3.0909+\\gamma(10.5-9.7273)$, which gives 3.0909, 3.8636, and 3.6266\nfor the three values of $\\gamma$ (3.6266 from full precision; 3.6265\nfrom the rounded inputs).\n\nThe last column shows why the estimated coefficient is usually preferred.\nThe pretest predicts the posttest with a slope near 0.7, so fixing its\ncoefficient at 0 leaves the pretest's predictive information in the error\n(residual SD 3.1885), and fixing it at 1 over-corrects (2.5799).\nEstimating it leaves the smallest residual SD, 2.4278, and the smallest\nstandard errors. The choice among the three belongs in the analysis plan,\nmade before the outcomes are seen; picking whichever estimate looks best\nafter fitting all three turns three defensible analyses into one selected\nresult.\n\n### What adjustment cannot supply {#ch09-ancova-limits}\n\nA common slope is a condition, not a finding. The check adds the\ngroup-by-pretest product block, which lets each group have its own slope,\nand compares the two named models on the same records:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvarying_slopes <- lm(post.test.1 ~ group * pretest.1, data = reading)\nanova(ancova, varying_slopes)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|    Pr(>F)|\n|------:|--------:|--:|---------:|--------:|---------:|\n|     62| 365.4307| NA|        NA|       NA|        NA|\n|     60| 347.9697|  2|  17.46099| 1.505389| 0.2301931|\n\n</div>\n:::\n:::\n\n\nThe product block gives $F(2,60)=1.5054$, $p=.2302$, with group slopes of\n0.4663 (DRA), 0.6868 (DRTA), and 0.8768 (Think-aloud). These 66 records do\nnot distinguish the two models, which is not the same as showing that the\nslopes are equal. When slopes do differ, an adjusted difference depends on\nthe pretest value at which it is read; Chapter 10 develops that\nvarying-slope model as an interaction.\n\nWhat adjustment supplies depends on how the groups were formed. In groups\nformed by random assignment, the pretest only sharpens a comparison that\nthe design already warrants. In observational groups, a fitted comparison\nat a common covariate value cannot balance what was not measured; a\ncovariate measured with error under-adjusts, leaving part of the\nbaseline difference in place (Chapter 14, Section 5.1); and a covariate\nrecorded after the groups formed can remove part of the effect being\nestimated.\n\n**Lord's paradox** makes the point with intact groups that differ at\nbaseline [@lord1967]: the gain-score analysis asks whether the groups\nchanged by different amounts, the covariance analysis asks whether pupils\nwith the same pretest ended differently, and the two can reach opposite\nconclusions from the same records, partly through the regression toward\nthe mean of Chapter 7, Section 7. Neither analysis says which question is\nthe causal one; the design does, and Chapter 14 returns to what a design\nsupplies that adjustment cannot.\n\n## Compare Nested Models {#sec-ch9-comparison}\n\n### The extra-sum-of-squares statistic\n\nSections 1.4 and 2.2 used one statistic. Let the reduced model be the\nfull model with $q$ coefficients set to zero, both fitted to the same\nrecords and the same outcome. Then\n\n$$\nF=\\frac{(RSS_{R}-RSS_{F})/q}{RSS_{F}/(n-p)}.\n$$\n\nThe numerator is the extra sum of squares that the added block buys, per\ncoefficient it spends. The denominator is the fuller model's residual\nmean square, the same $s^2$ that appears in every classical standard\nerror. Under the Normal linear model with independent common-variance\nerrors, the ratio has an $F$ reference with $q$ and $n-p$ degrees of\nfreedom.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residual sum of squares as columns are added to the occupation model on the same 98 records; each label gives the drop that the added column or block buys.](chapter_09_files/figure-html/fig-ch9-rss-1.png){#fig-ch9-rss fig-pos='!ht' fig-alt='Horizontal bars of residual sum of squares for five nested models. The intercept-only bar is labelled RSS 1734.0792; adding education drops it by 571.5324, adding prestige by 294.8931, adding the percentage of women by 236.3266, and adding the two type columns by only 0.4375, so the last two bars look the same length.' width=614.4}\n:::\n:::\n\n\n@fig-ch9-rss shows that bargain for the occupation models. Education buys\n571.5324 of the total 1734.0792, and prestige a further 294.8931. The\npercentage of women then buys 236.3266 for one coefficient, while the two\ntype columns buy only 0.4375 for two. Set against the full model's\nresidual mean square of 6.8575, the type block's 0.4375 spread over two\ncoefficients gives $F(2,92)=0.0319$, and the women-and-type block's 236.764\nover three gives 11.5088, the entries of @tbl-ch09-blocks. Section 1.4's\ntest was the same comparison with the intercept-only model as the reduced\nmodel.\n\nThe subtraction means something only when the two models use the same\nrows and the same outcome, and when the reduced model is obtainable from\nthe fuller one by restrictions; Chapter 8's complete-case selection is why\nevery comparison in this chapter runs on the same 98 records. The\n**overall** regression test is the special case whose reduced model is\nthe intercept alone, so that all $p-1$ non-intercept coefficients are set\nto zero. Chapter 8, Appendix A, gave its formula and read it from\n`summary()`: the full model gives $F(5,92)=32.1747$, and the\neducation-only model on the same 98 records gives $F(1,96)=47.1956$.\nPlaced beside the general statistic, the two values are easy to misread.\nThe larger one is not evidence that `m0` is the better model, because the\ntwo statistics test different restrictions in different models, each\nagainst the intercept alone. Neither verifies the mean function, the\nerror model, or the independence of the rows, and neither says how a\nfitted rule would perform on records it has not seen, which is a separate\nquestion with a separate calculation (Chapter 13).\n\n### Restrictions in matrix form\n\nThe same statistic has a compact matrix form, worth one pass because it\nmakes clear what \"the same records\" is doing in every comparison above.\nLet $\\mathbf X$ hold $n$ rows and $p$ coefficient columns including the\nintercept, with full column rank. Minimizing\n$(\\mathbf y-\\mathbf X\\boldsymbol\\beta)^{\\mathsf T}(\\mathbf y-\\mathbf X\\boldsymbol\\beta)$\ngives the normal equations\n$\\mathbf X^{\\mathsf T}(\\mathbf y-\\mathbf X\\widehat{\\boldsymbol\\beta})=\\mathbf 0$ and\nhence\n$\\widehat{\\boldsymbol\\beta}=(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf X^{\\mathsf T}\\mathbf y$,\n$\\widehat{\\mathbf y}=\\mathbf H\\mathbf y$ with\n$\\mathbf H=\\mathbf X(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf X^{\\mathsf T}$, and\n$\\widehat{\\mathbf V}=s^2(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}$. For $q$ independent\nlinear restrictions $\\mathbf R\\boldsymbol\\beta=\\mathbf r$,\n\n$$\nF=\\frac{(\\mathbf R\\widehat{\\boldsymbol\\beta}-\\mathbf r)^{\\mathsf T}\\,\n[\\mathbf R(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf R^{\\mathsf T}]^{-1}\\,\n(\\mathbf R\\widehat{\\boldsymbol\\beta}-\\mathbf r)}{q\\,s^{2}}\\sim F_{q,\\,n-p}.\n$$\n\nFor `m2`, $\\mathbf X$ has six columns and rank 6: the two type indicators\ndo not reproduce the intercept column, so every coefficient is separately\nestimable. Choosing the two rows of $\\mathbf R$ that select the type\ncoefficients, with $\\mathbf r=\\mathbf 0$, returns 0.0319, the adjusted\ntype block test of Section 2.2, without fitting a second model.\n\nTwo practical points follow. `lm()` does not form\n$(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}$; it uses a QR decomposition, which\nis numerically better behaved, so the displayed equation explains what the\nestimator *is*, not how R computes it [@fox2016; @fox2019]. And because\n$\\widehat{\\mathbf y}=\\mathbf H\\mathbf y$ is a projection onto the column\nspace of $\\mathbf X$, any full-rank recoding of a factor spans the same\nspace and leaves the fitted vector alone, which is Section 1.3's\nreleveling result stated geometrically. Appendix A carries the\nderivation.\n\n### A local Normal likelihood and information criteria\n\nNested $F$ tests compare two models when one contains the other.\nInformation criteria rank models that need not be nested, using a\ndifferent quantity: the maximized likelihood, penalized for the number of\nfitted parameters.\n\nChapter 8, Appendix B, built that likelihood for these occupation models\nby carrying Chapter 6's binomial likelihood, for 32 successes in 50\ntrials, over to outcomes treated as independent Normal draws around the\nregression. Three of its results carry the reading here. Maximizing the\nNormal likelihood over the coefficients reproduces least squares. Its\nscale estimate divides the residual sum of squares by $n$,\n$\\sqrt{RSS/n}=2.5373$, where the residual SD reported by `lm()` divides\nby the residual degrees of freedom, $\\sqrt{RSS/(n-p)}=2.6187$. And AIC\nadds $2k$ to $-2\\log\\widehat L$ while BIC adds $k\\log n$, where $k$\ncounts the fitted coefficients **and** the residual variance, so `m2` has\n$k=7$, not 6. One call returns the maximized log-likelihood and both\ncriteria for a fitted model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(logLik = logLik(m2), AIC = AIC(m2), BIC = BIC(m2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   logLik       AIC       BIC \n-230.3020  474.6040  492.6988 \n```\n\n\n:::\n:::\n\n\nFor `m2` it returns $-230.3020$, 474.6040, and 492.6988. Chapter 8,\nAppendix B, set the same criteria for the three nested models side by\nside: AIC 526.5052, 499.8328, and 474.6040 for `m0`, `m1`, and `m2`, and\nBIC 534.2601, 510.1727, and 492.6988. Smaller is preferred under either\ncriterion, and both prefer `m2` here.\n\nWhat this chapter adds is how to use them as tools for comparing models.\nBIC charges the same seven parameters $7\\log 98=32.0948$ instead of AIC's\n14, because at $n=98$ the factor $\\log n=4.585$ exceeds 2. The two\ncriteria can therefore disagree, and a disagreement is information about\nhow strongly the extra parameters are being charged, not a tie to be\nbroken by preference. The conditions for reading them are strict and easy\nto breach. The candidates must be fitted to the same records, with the\nsame outcome on the same scale, under the same likelihood convention;\nSection 4.2 shows what happens when the scale changes. Above all, neither\ncriterion is a held-out error. Both are calculated on the records that\nfitted the model, and both are comparative rather than absolute: a\nsmaller AIC says one candidate is preferred to another, not that either\ndescribes the records well [@akaike1974; @schwarz1978]. Chapter 11\ndevelops likelihood fully, for models where least squares is no longer\navailable.\n\n## Change the Form of a Predictor or the Scale of the Outcome {#sec-ch9-forms}\n\n### A polynomial term\n\nChapter 8, Section 4.3, refitted the full model with a squared prestige\nterm as a disclosed sensitivity check on functional form. Here that refit\nis the worked example. A squared term is an ordinary extra column,\n`I(prestige^2)`, and the model is still linear in its coefficients. What\nchanges is the reading:\n\n$$\nE(Y\\mid x,\\ldots)=\\beta_0+\\beta_1x+\\beta_2x^2+\\cdots,\\qquad\n\\frac{\\partial E(Y)}{\\partial x}=\\beta_1+2\\beta_2x,\\qquad\nx^{*}=-\\frac{\\beta_1}{2\\beta_2}.\n$$\n\nThe predictor no longer has a single slope. It has a slope that depends on\nits own value, $\\beta_1+2\\beta_2x$, and a turning point $x^{*}$ where that\nslope is zero.\n\n```{=latex}\n\\Needspace{18\\baselineskip}\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2q <- lm(income_k ~ education + prestige + I(prestige^2) + women + type,\n  data = d)\nanova(m2, m2q)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|    Pr(>F)|\n|------:|--------:|--:|---------:|--------:|---------:|\n|     92| 630.8897| NA|        NA|       NA|        NA|\n|     91| 587.4085|  1|  43.48117| 6.736004| 0.0110146|\n\n</div>\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Component-plus-residual display for prestige in the model with a squared prestige term. The solid curve is the fitted quadratic component and the dashed line the linear component of the additive model; the labels give the curve's slope at prestige 30, 50 and 70.](chapter_09_files/figure-html/fig-ch9-quadratic-1.png){#fig-ch9-quadratic fig-pos='!ht' fig-alt='Open grey circles for the 98 occupations, prestige from 17.3 to 87.2 on the horizontal axis and component plus residual from about −6 to 18 on the vertical axis. A solid curve rises slowly at low prestige and more steeply at high prestige; a dashed straight line crosses it twice. Black dots on the curve at prestige 30, 50 and 70 carry the labels slope 0.0697, slope 0.1665 and slope 0.2633.' width=614.4}\n:::\n:::\n\n\nThe quadratic coefficient is 0.0024 with SE 0.0009 and $t=2.5954$; the\none-restriction block test gives $F(1,91)=6.736$ with $p=.011$; and the\ncriteria move from 474.6040 and 492.6988 to 469.6058 and 490.2855. Adding\nthe term also changes the education coefficient from 0.1164 to $-0.0298$,\na reminder that coefficients in an additive model are defined relative to\nthe other columns present.\n\n@fig-ch9-quadratic, the component-plus-residual display of Chapter 8 with\nthe fitted curve added, shows what the squared term claims. With linear\ncoefficient $-0.0754$ and quadratic coefficient 0.0024, the curve's slope\nis 0.0697 thousand dollars per prestige point at prestige 30, 0.1665 at\n50, and 0.2633 at 70: income rises with prestige throughout the records,\nand rises faster at the top, where the straight line of the additive\nmodel falls below several high-prestige occupations. The turning point,\n15.5906, lies below the smallest observed prestige of 17.3, so the\ndescending branch of the parabola is entirely outside the records.\nReporting a \"negative prestige coefficient\" from this model would misread\nthe coordinate $-0.0754$, which is the slope at prestige zero, a value no\noccupation has.\n\nCentering repairs that coordinate problem without changing the curve,\nbecause it is a change of coordinates. Prestige and its square correlate\n.9849; centering prestige at its mean, 47.3276, before squaring lowers\nthat correlation to .3216. The quadratic coefficient and its SE stay\n0.0024 and 0.0009, and every fitted value stays the same. The linear\ncoefficient becomes 0.1536 with SE 0.0347: it now estimates the slope at\nthe mean prestige, a different quantity from $-0.0754$, the slope at\nprestige zero, whose SE is about 2.6 times as large. The smaller SE\nbelongs to a slope read in the middle of the records, not to a sharper\nestimate of the old one. Keep the status of the exercise straight:\nthis is a disclosed sensitivity check on functional form, declared before\nthe refit, and its result is that a modest curvature is detectable on\nthese records. It is not a search across candidate terms for the smallest\n$p$-value, and a $p$-value read after such a search would not mean what it\nappears to mean.\n\n### A log-transformed outcome\n\nChanging a predictor's form keeps the question. Changing the outcome's\nscale changes the question, and that difference is the point of this\nsubsection.\n\n$$\n\\log Y_i=\\beta_0+\\sum_j\\beta_jx_{ij}+\\varepsilon_i,\\qquad\n100\\,(e^{\\beta_j}-1)\\ \\text{percent per unit of } x_j .\n$$\n\nA coefficient in a log-income model is an additive difference in expected\nlog income. Exponentiating turns it into a multiplicative difference in\ngeometric mean income under that model, and $100(e^{\\widehat\\beta}-1)$\nexpresses that multiplier as a percentage. The geometric mean is not the\narithmetic mean, so this is not automatically a statement about average\nincome in dollars.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_log <- lm(log(income) ~ education + prestige + women + type, data = d)\n100 * (exp(coef(m_log)[c(\"education\", \"prestige\", \"women\")]) - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n education   prestige      women \n 0.7660700  2.0964846 -0.8429719 \n```\n\n\n:::\n:::\n\n\n| Term | Log coefficient | Percent | Lower | Upper |\n|:--|--:|--:|--:|--:|\n| education | 0.0076 | 0.7661 | $-4.2041$ | 5.9941 |\n| prestige | 0.0207 | 2.0965 | 1.4351 | 2.7622 |\n| women | $-0.0085$ | $-0.8430$ | $-1.0189$ | $-0.6667$ |\n\n: Log-model contrasts on a geometric-mean percent scale. {#tbl-ch09-log tbl-colwidths=\"[22,22,18,19,19]\"}\n\nOne more prestige point is associated with about 2.0965 percent higher\ngeometric-mean income at the same education, percentage of women, and\ntype, with interval $[1.4351,\\ 2.7622]$ percent; one more percentage point\nof women with about $-0.843$ percent. The two type coefficients, $-0.0137$\nand 0.0708 on the log scale, are $-1.3584$ and 7.3341 percent. The\nintervals in @tbl-ch09-log are the classical log-scale intervals with both\nendpoints transformed, which is legitimate because the transformation is\nmonotone; they inherit the log-scale working model and supply no new\nwarrant.\n\nThe criteria will not travel across this change. This model's AIC is\n8.091 against `m2`'s 474.604, and the difference says nothing at all:\nthe two likelihoods are densities of different response variables, so\ntheir values are not on a common scale. The discipline to keep is simple:\nfix the outcome and the question inside any comparison, and treat a scale\nchange as a new question rather than as data cleaning [@fox2019].\n\n### Coefficient scales: standardized coefficients and unique contributions\n\nTwo summaries are often asked for once several predictors are in an\nequation, and both are more limited than their names suggest:\n\n$$\n\\beta_j^{*}=\\widehat\\beta_j\\frac{s_{x_j}}{s_y},\\qquad\n\\Delta R^2_j=R^2_{\\mathrm{full}}-R^2_{\\mathrm{without}\\ j}.\n$$\n\nA **standardized coefficient**, or beta weight, rescales a partial slope\ninto outcome-SD units per predictor SD. A **drop-one $R^2$** reports how\nmuch of the explained variation disappears when one predictor is removed\nfrom the full model. The beta weights are 0.0757, 0.5685, and $-0.3971$\nfor education, prestige, and the percentage of women, and education's\ndrop-one $R^2$ is .0007: removing it from the full model costs essentially\nnothing in fit, the same message the education coefficient's wide interval\ncarried in Chapter 8.\n\nBoth quantities are rescalings of an in-sample fit, and neither measures\nimportance. A standardized coefficient depends on the predictor's observed\nspread in these particular records, so a restricted range shrinks it for\nreasons that have nothing to do with the relationship. It also differs\nfrom the standardization over named profiles that Chapter 8 used, which\naverages fitted values over a declared distribution rather than dividing\nby an SD. The drop-one change describes only the *unique* contribution:\nbecause predictor information overlaps, the separate drop-one values need\nnot sum to the joint $R^2$, and a predictor that duplicates another can\nshow a near-zero value while mattering. Neither number establishes a\ncausal ranking or predicts held-out performance.\n\n## Robust Uncertainty Under Unequal Spread {#sec-ch9-hc3}\n\n### The HC3 covariance\n\nEvery classical standard error so far assumed one common error variance\nfor all 98 occupations. @fig-ch9-spread shows why that assumption is\ndoubtful here.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residuals of the full occupation model by type, with each type's residual SD.](chapter_09_files/figure-html/fig-ch9-spread-1.png){#fig-ch9-spread fig-pos='!ht' fig-alt='Jittered open circles of residuals in thousand dollars, one column per type, around a horizontal line at zero. Blue-collar and white-collar residuals stay between about −2.4 and 2.6, with SDs 1.0437 and 1.0243; professional residuals run from about −7.8 to 14.2, with SD 4.3242.' width=614.4}\n:::\n:::\n\n\nThe residuals of professional occupations spread about four times as\nwidely as the others: their SD is 4.3242 thousand dollars against 1.0437\nfor blue-collar and 1.0243 for white-collar occupations. A single $s^2$\naverages these very different spreads, so it overstates the uncertainty\ncontributed by some rows and understates it for others.\n\nThe remedy is already in hand. Chapter 7, Section 6.1, first used a\nrobust standard error on the simple regression line, where the education\nslope's SE moved from 0.1270 to 0.1491. Chapter 8 then applied the same\nHC3 estimator to the full model: its Section 3.3 computed the education\ninterval with `sandwich::vcovHC()`, and its Appendix B displayed the\nestimator, which keeps the design component outside and replaces the\nsingle $s^2$ inside by each row's own leverage-adjusted squared\nresidual, and set classical and HC3 standard errors side by side for all\nsix coefficients [@white1980; @mackinnon1985; @long2000; @zeileis2004].\nAppendix A of this chapter shows where the estimator comes from.\n\nWhat the figure adds is a reason for the pattern in that table. The\nprofessional coefficient's SE grows by about 40%, from 1.4631 to 2.0928,\nas the wide professional spread predicts, while the white-collar SE grows\nby only about 7%, from 0.9848 to 1.0548. The education SE grows from\n0.2752 to 0.3823, and its 95% interval on the robust covariance is\n$[-0.6429,\\ 0.8758]$: wider than the classical one, with the same\nreading of an imprecisely estimated comparison. Every coefficient, fitted\nvalue, and residual stays exactly what it was, because HC3 replaces a\ncovariance estimate, not a fit.\n\nThe percentage of women is the instructive case: its SE *falls* from\n0.0097 to 0.0079. A robust covariance is not a penalty applied to every\ncoefficient.\nIt is a different estimate of the same target, and where the classical\ncommon-variance assumption happened to overstate a coefficient's\nvariability, the robust version is smaller. Reporting only the\ncoefficients whose intervals widened, or switching estimators after seeing\nwhich choice gives the preferred conclusion, turns a stated method into a\nselection.\n\n### A block test with a robust covariance\n\nThe restriction statistic of Section 3.2 needs only a coefficient vector\nand a covariance matrix. Substituting the HC3 covariance\n$\\widehat{\\mathbf V}_{\\mathrm{HC3}}$ for $\\widehat{\\mathbf V}$ gives an\napproximate Wald version of the same block test. For the type block it\ngives 0.0345, with $p=.9661$, against\nthe classical 0.0319 and .9686: here the substitution changes nothing of\nsubstance. The reason is that the type coefficients sit close to the\nrestriction, each within a quarter of its classical SE of zero, so both\nstatistics are near zero; the SEs would have to shrink about tenfold\nbefore either statistic reached the .05 critical value, 3.0954. A change\nof covariance matters most when a block statistic lies near its critical\nvalue.\n\nThe reference distribution is where the two differ in kind. The classical\nstatistic has an exact $F_{2,92}$ distribution under the stated Normal\nlinear model. The robust version has only an approximate reference,\njustified as the sample grows, and $F$ with the same degrees of freedom is\na convention rather than a derivation. Quoting the robust $p$-value to\nseveral digits, or treating it as the same object as the classical one\nbecause both are labelled $F$, overstates what the calculation delivers.\n\n### What HC3 does not repair\n\nHC3 has one job. Under a maintained linear conditional mean and\nindependent observations, it estimates the coefficient covariance without\nassuming a common error variance.\n\nIt does not repair curvature: if the mean function is wrong, the\ncoefficients estimate a different quantity (Appendix A names it), and a\nrobust covariance describes that quantity's variability more honestly\nwithout making it the quantity of interest. It does not repair dependence:\nrows that are not independent break the estimator's own derivation, and\nSection 7 shows a case where a robust row-level SE and a naive one agree\nclosely while both understate the uncertainty by nearly half. It does not\nrepair selection or missing outcomes, which change what the records\nrepresent, and it does not supply causal identification, which comes from\ndesign or from an argument about the conditioning set. Error in measuring\na predictor also pulls its slope toward zero, by roughly the predictor's\nreliability when it is the only predictor, and no covariance estimator\nrepairs it [@cohen2003]; independent mean-zero error in the outcome, by\ncontrast, widens the residual spread and the standard errors but leaves\nthe slope's target unchanged. Chapter 14, Section 5.1, develops\nattenuation.\nNor does HC3 create joint support: the type contrast's robust SE of 1.1827\nis still the uncertainty of a comparison the records barely observe.\n\nThe practical response is to say which estimator was used and why, and to\nkeep the answer's limits attached to it. Chapter 8's advice holds here:\nreport the named comparison, its form and influence sensitivities, and the\ncovariance calculation, rather than treating any one of them as a\npass/fail certificate.\n\n## Resample the Records {#sec-ch9-bootstrap}\n\n### Why resample, and which scheme\n\nEvery uncertainty statement so far came from a formula: a coefficient\ncovariance matrix, classical or robust, propagated through a linear\ncombination. Resampling offers a different approximation. Refit the model\nto many resamples of the records, and read the spread of the refitted\nestimates directly [@efron1979; @efron1993; @davison1997]. Where the\nformula and the resampling distribution disagree, the disagreement is\nitself informative.\n\nThe choice of what to resample is an assumption, not a default.\n\n- **Case resampling** draws whole records with replacement and refits. It\n  inherits whatever unequal spread the rows contain, but it requires the\n  resampling unit to match the sampling unit, with units independent and\n  exchangeable.\n- **Residual resampling** holds the design fixed, resamples rescaled\n  residuals, and adds them back to the fitted values. It assumes\n  identically distributed errors, the assumption HC3 exists to relax.\n- **The wild bootstrap** also holds the design fixed but multiplies each\n  rescaled residual by an independent mean-zero, unit-variance draw, so\n  every record keeps its own error scale.\n\nThis chapter uses case resampling, for two stated reasons. The occupation\npredictors were not designed: no one assigned education or prestige to an\noccupation, so a joint-sampling view of the rows is the natural one. And\nthe residual spread differs by type, as @fig-ch9-spread showed, so the\nidentically distributed errors behind residual resampling are not\navailable [@freedman1981]. Appendix B compares the other two schemes on\nthe same targets.\n\n### Case resampling for the full model\n\nResample the 98 rows with replacement, refit `m2`, and keep the education\nslope. The seed and the number of resamples $B$ belong in the record, so\nboth appear in the code; $B$ counts bootstrap resamples here, as it\ncounted simulation repetitions in Chapter 5.\n\n```{=latex}\n\\Needspace{14\\baselineskip}\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(90909)\nB <- 2000\nboot_education <- replicate(B, {\n  rows <- sample.int(nrow(d), replace = TRUE)\n  coef(lm(income_k ~ education + prestige + women + type,\n    data = d[rows, ]))[\"education\"]\n})\nc(SE = sd(boot_education), quantile(boot_education, c(.025, .975)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        SE       2.5%      97.5% \n 0.3698895 -0.6829568  0.7439809 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The 2,000 case-resampled education slopes (seed 90909). Solid lines mark the percentile interval; the dashed curve is the Normal distribution with the classical SE 0.2752.](chapter_09_files/figure-html/fig-ch9-bootstrap-1.png){#fig-ch9-bootstrap fig-pos='!ht' fig-alt='Histogram of refitted education slopes from about −1.2 to 1.1, centred near 0.1 and slightly longer on the left, with solid vertical lines at −0.683 and 0.744. A dashed Normal curve centred at 0.1164 is narrower and taller than the histogram.' width=614.4}\n:::\n:::\n\n\n@fig-ch9-bootstrap is the resampling distribution itself. The 2,000\nrefitted slopes spread more widely than the Normal curve built from the\nclassical SE: their SD, the bootstrap SE, is 0.3699, and their middle 95%,\nthe percentile interval, runs from $-0.683$ to 0.744. The same resamples\ngive the other two targets of @tbl-ch09-bootstrap, the\nprofessional-minus-white-collar contrast and the professional coefficient.\nA resample could omit an entire occupational type, and its refit would\nthen lose a type coefficient; here all 2,000 resamples contained all\nthree types, so all 2,000 refits are usable, and that count is part of\nthe result rather than an assumption.\n\n| Target | Estimate | Classical SE | HC3 SE | Bootstrap SE | Percentile 2.5% | Percentile 97.5% |\n|:--|--:|--:|--:|--:|--:|--:|\n| Education slope | 0.1164 | 0.2752 | 0.3823 | 0.3699 | $-0.6830$ | 0.7440 |\n| prof $-$ wc | 0.0889 | 1.0800 | 1.1827 | 1.1187 | $-1.9613$ | 2.4313 |\n| prof coefficient | 0.3242 | 1.4631 | 2.0928 | 1.9926 | $-3.1416$ | 4.5443 |\n\n: Model-based, HC3, and case-bootstrap uncertainty for three targets in the full occupation model (seed 90909, $B=2000$). {#tbl-ch09-bootstrap tbl-colwidths=\"[22,12,14,12,14,13,13]\"}\n\nRead the table one row at a time. The education slope's bootstrap SE of\n0.3699 sits between the classical 0.2752 and the HC3 0.3823: three\ncalculations, one conclusion that this comparison is imprecise. The type\ncontrast's bootstrap SE of 1.1187 exceeds the classical 1.0800, with\npercentile interval $[-1.9613,\\ 2.4313]$. The professional coefficient\nshows the largest movement, from a classical 1.4631 to 1.9926, close to\nthe HC3 2.0928; with only 31 professional occupations spreading as widely\nas @fig-ch9-spread shows, a resample's composition matters, and the\nformula that assumes a common error variance is the most optimistic of the\nthree.\n\nAgreement between HC3 and the bootstrap is not independent confirmation.\nBoth are sensitivity procedures applied to the same 98 records, and both\ninherit the same limitations of those records; agreement means the two\napproximations behave similarly here, not that the answer has been\nreplicated. Monte Carlo variation also means that the last decimal of a\nbootstrap summary carries no weight: a different seed would move it, which\nis exactly why the seed and $B=2000$ are reported.\n\n### Which interval, and what resampling does not repair\n\nTwo intervals come directly from the resampling distribution. The\n**percentile interval** takes its 2.5th and 97.5th percentiles, as in\n@fig-ch9-bootstrap. The **normal-approximation interval** takes the\noriginal estimate plus and minus 1.96 bootstrap standard errors. The two\nagree when the resampling distribution is roughly symmetric; here the\nthree distributions have skewness $-0.3891$, 0.2635, and 0.3785, read by\ntheir sign as in Chapter 2, Section 2.1: the education slopes have the\nslightly longer left tail visible in the figure, the other two a slightly\nlonger right tail. The asymmetry is mild enough that the two kinds of\nendpoint agree closely. For a strongly skewed or biased resampling\ndistribution, **bootstrap-$t$** and **BCa** intervals are the higher-order\nalternatives; Appendix B defines both in words.\n\nWhat resampling cannot do matters more than which interval to choose.\nDrawing occupations with replacement treats them as independent and\nexchangeable draws from one population, and there are stated reasons to\ndoubt both. The occupations share one historical labour market, where\ncommon conditions can move related occupations' incomes together; the\n98 rows were chosen by complete records rather than sampled at random\nfrom a population of occupations; and their measurements are aggregates\nover workers. Resampling does not repair the thin cross-type support, correct the measurement problems Chapter 8\ndocumented, or convert an observational comparison into a causal one. And\nif a design contained clusters, strata, or weights, the resampling unit\nwould have to follow the design rather than the rows, which is the subject\nof the next section.\n\n## Dependence in the Design: Project STAR {#sec-ch9-star}\n\n```{=latex}\n\\hypertarget{sec-ch9-star}{}\n```\n\n\n::: {.cell}\n\n:::\n\n\nEvery calculation so far has used observational records or one small\nexperiment, and every qualification has been about what those records\ncannot support. This section changes the design. Project STAR randomized\nkindergarten pupils to class types within their schools, which supplies a\nwarrant no amount of adjustment can manufacture, and a dependence\nstructure that the uncertainty calculation must follow.\n\n### A different design supplies a different warrant\n\nThe question is specific:\n\n> Among eligible kindergarten pupils in the participating Tennessee\n> schools, what was the mean reading-score difference under assignment to\n> a small rather than a regular class?\n\nThe outcome is `readk`, an end-of-kindergarten reading scale score. The\nfield `stark` records the kindergarten class-type condition. Reading its\nsmall-versus-regular comparison as an assignment comparison rests on the\ndocumented experimental protocol, not on the column name or on the `lm()`\ncall: random assignment occurred **within** participating schools\n[@finn1990; @mosteller1995]. The regular-with-aide arm is outside this\ndeclared two-arm comparison and is excluded by design, not dropped for\nconvenience.\n\nThree limits belong with the question from the start. Class **type** is\nnot a measured headcount, so this analysis estimates no dose response in\npupils per room. The distributed field does not independently verify each\npupil's original randomized assignment; an assignment-effect reading\nadditionally requires linking the recorded type to the assignment record\nand checking switches and implementation deviations, which this teaching\nreanalysis does not supply. And the scientific target is the\npupil-weighted mean assignment effect for the eligible cohort in\nparticipating schools, while a common coefficient from a complete-record\nmodel is an estimator that needs further links, a common effect across\nschools or an explicit weighting argument, to reach that target.\n\nThe data are distributed as `AER::STAR`, accompanying *Applied\nEconometrics with R* and following the version used by Stock and Watson\n[@kleiber2008; @stock2007]. They are loaded from the package rather than\nredistributed here, and the analysis is retrospective rather than\npreregistered.\n\n### Separate eligibility from missingness\n\nTwo different reasons for a record's absence from an analysis are easy to\nmerge and must be kept apart. Some distributed rows belong to pupils who\nentered the study after kindergarten: they have no kindergarten condition\nat all, and their absence is **structural ineligibility**. Other rows\nbelong to eligible kindergarten pupils whose reading score or covariates\nwere not recorded: that is **missingness**, and it can distort a\ncomparison. Only the variables a calculation actually uses may enter its\ncomplete-record rule; in particular, a missing mathematics score (`mathk`)\nmust not exclude an otherwise usable reading record.\n\n\\Needspace{12\\baselineskip}\n\n| Stage | $n$ |\n|:--|--:|\n| Distributed records | 11,598 |\n| Kindergarten condition recorded | 6,325 |\n| Eligible small or regular | 4,094 |\n| Eligible, reading observed | 3,745 |\n| Complete primary records | 3,735 |\n| Primary regular | 2,001 |\n| Primary small | 1,734 |\n| Primary schools | 79 |\n\n: STAR eligibility and reading-analysis completeness. {#tbl-ch09-star-sample tbl-colwidths=\"[60,40]\"}\n\nOf 11,598 distributed records, 5,273 have no kindergarten condition; they\nare later entrants, not 5,273 failed measurements. The remaining 6,325\nhave a recorded kindergarten arm, and across all three arms 536 lack a\nreading score. Restricting to the two declared arms leaves 4,094 eligible\nrecords, of which 349 lack reading, 188 in the regular arm and 161 in the\nsmall arm, leaving 3,745 with an observed reading score, 2,006 regular and\n1,739 small.\n\nSimilar missing percentages in the two arms are reassuring but prove\nnothing: the absent scores could differ systematically within either arm,\nand no observed value can reveal that. Complete-record inference here\nrequires an assumption that, given the declared covariates and within arm\nand school, observation does not depend on the reading score that would\nhave been recorded. Stating the assumption is not verifying it. Among the\nobserved-reading records across all arms, 38 lack at least one of lunch\nstatus, gender, ethnicity, and teacher experience; within the two focal\narms, ten do. The primary common-covariate sample therefore has 3,735\npupils, 2,001 regular and 1,734 small, in 79 schools, and the\nobserved-reading sample keeps all 3,745 focal records as a declared\nsensitivity, not as an alternative headline.\n\n### The binary slope recovers the observed arm means\n\nSection 1.1's identity applies unchanged. With $D_i=1$ for the small arm\nand 0 for regular,\n\n$$\n\\widehat Y_i=\\widehat\\alpha+\\widehat\\delta D_i,\\qquad\n\\widehat\\alpha=\\bar Y_{D=0},\\qquad\n\\widehat\\delta=\\bar Y_{D=1}-\\bar Y_{D=0}=440.5474-434.7323=5.8151.\n$$\n\nOn the 3,745 observed-reading records the regression slope reproduces the\narm difference of 5.8151 reading points exactly, as Chapter 7's binary\npredictor did on 24 pupils. The identity is algebraic and requires no\nrandomization; what randomization adds is the reason to read the\ndifference as an assignment comparison.\n\nTwo cautions attach to the number itself. Under independent\ncommon-variance rows, the slope's $t$ test equals the pooled two-sample\ntest, here $t=5.6039$; that row-level reference ignores the fact that\npupils sit in schools, which Section 7.5 addresses. And raw arm means\nweight each school by its own arm-specific pupil count, so the pooled\ndifference equals the pupil-weighted cohort target only under common\nassignment probabilities and comparable observation patterns, or after\nexplicit standardization to target school weights.\n\n### Compare two specifications on identical primary rows\n\nThe adjusted model adds free-lunch status, gender, ethnicity, teacher\nexperience, and school indicators. School indicators respect the\nassignment blocks; the remaining covariates are the declared adjustment\nspecification, not a substitute for randomization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstar_unadjusted <- lm(readk ~ stark, data = star_df)\nstar_primary <- lm(readk ~ stark + lunchk + gender + ethnicity +\n  experiencek + schoolidk, data = star_df)\n```\n:::\n\n\nOn the common 3,735 primary rows, the unadjusted difference is 5.8955 and\nthe adjusted coefficient is 6.6575. Adjustment can improve precision when\nthe added variables are prognostic for reading, and school indicators\nmatch the blocks in which assignment happened. It is not needed to remove\nbaseline confounding that a successfully implemented randomization\nalready prevents, and it does not automatically preserve a causal target:\ntiming, selection, and the fitted comparison still need scrutiny. This is\nSection 2.5's point about randomized groups, on a larger design.\n\nThe earlier 5.8151 comes from 3,745 rows and must not serve as the\nsame-row unadjusted baseline for 6.6575. Comparing 5.8151 with 6.6575\nwould confound two changes, a change of records and a change of\nspecification, and the whole discipline of this chapter is to keep those\napart. The same-row pair to compare is 5.8955 against 6.6575. Similar\nunadjusted and adjusted coefficients are consistent with successful\nrandomization; they are not proof that implementation, missingness, or\nweighting problems are absent.\n\n### Cluster uncertainty follows the design\n\nPupils are the outcome units. Schools are the randomization blocks and the\napproximately independent units for the uncertainty calculation; the\nschools themselves were not assigned to arms. Chapter 3, Section 2.3,\nshowed that the uncertainty of a school-blocked comparison follows its\nwithin-school comparisons, and @fig-ch9-star-schools shows those\ncomparisons for STAR.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Small-minus-regular mean reading difference in each of the 78 schools that observed both class types, ordered by size. The dashed line is their unweighted mean, 6.7094.](chapter_09_files/figure-html/fig-ch9-star-schools-1.png){#fig-ch9-star-schools fig-pos='!ht' fig-alt='Dot plot of 78 school differences, one dot per school, rising from about −32 to 59 reading points in an S-shaped column; 25 dots lie left of the solid zero line, and a dashed line marks the mean, about 6.71.' width=614.4}\n:::\n:::\n\n\nIn the 78 schools that observed pupils in both arms, the small-class\nadvantage ranges from about $-32$ to 59 reading points, and it is negative\nin 25 schools. Pupils in one school share whatever made their school's\ndifference large or small: its teachers, its intake, its classrooms. The\n3,745 pupils therefore do not supply 3,745 independent pieces of\ninformation about the arm difference; the schools do. A rough check makes\nthe scale visible. An average of 78 independent differences with SD\n15.4192 has SE $15.4192/\\sqrt{78}=1.7459$, the size of the clustered\nstandard errors below and far from the row-level 1.0377.\n\nFor school $g$, form its score $\\mathbf s_g=\\mathbf X_g^{\\mathsf T}\\mathbf e_g$\nby summing the residual contributions **within** the school before taking\nan outer product. The CR1/HC1 cluster-robust covariance is then\n\n$$\n\\widehat{\\mathbf V}_{\\mathrm{CR1}}=c_G(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\n\\Big(\\sum_{g=1}^{G}\\mathbf s_g\\mathbf s_g^{\\mathsf T}\\Big)(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1},\n\\qquad \\mathbf s_g=\\mathbf X_g^{\\mathsf T}\\mathbf e_g,\\qquad\nc_G=\\frac{G}{G-1}\\frac{n-1}{n-p}.\n$$\n\nThe within-school cross-products are exactly what distinguishes this from\ntreating every pupil as independent, and $c_G$ is the finite-cluster\ncorrection. With $G=79$ schools, intervals use a $t_{78}$ critical value,\n1.9908 [@zeileis2020].\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstar_V <- sandwich::vcovCL(star_primary, cluster = star_df$schoolidk,\n  type = \"HC1\", cadjust = TRUE)\nsqrt(star_V[\"starksmall\", \"starksmall\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.697409\n```\n\n\n:::\n:::\n\n\n\\Needspace{12\\baselineskip}\n\n| Model | $n$ | Estimate | SE | Interval |\n|:--|--:|--:|--:|:--|\n| Observed: unadjusted | 3,745 | 5.8151 | 1.8476 | [2.1368, 9.4935] |\n| Primary: unadjusted | 3,735 | 5.8955 | 1.8491 | [2.2143, 9.5767] |\n| Primary: adjusted | 3,735 | 6.6575 | 1.6974 | [3.2782, 10.0368] |\n| Observed: school-adjusted | 3,745 | 6.6273 | 1.7797 | [3.0842, 10.1703] |\n\n: Class-type comparisons and school-clustered intervals. {#tbl-ch09-star-estimates tbl-colwidths=\"[34,12,16,14,24]\"}\n\n@tbl-ch09-star-estimates holds four distinct calculations, each with its\nown records and its own specification; each row's interval uses the\nschool identifiers from that model's own rows. Changing the model or its\nrecords is a different act from changing the covariance calculation, and\nthe table keeps them separable.\n\nSet the clustered SE beside Section 5's robust one. For the same\n3,745-record unadjusted comparison, treating pupils as independent rows\ngives SE 1.0377; HC3 gives 1.0416, barely different; school clustering\ngives 1.8476, nearly twice as large. Unequal spread across pupils was not\nthis design's problem. Dependence within schools was, and no row-level\nrobust covariance addresses it. The adjusted primary model shows the same\npattern: its row-level SE is 0.9161 and its HC3 SE 0.9509, against the\nclustered 1.6974.\n\nThese are cluster-asymptotic approximations with 79 clusters, not exact\nrandomization inference and not a multilevel model. A residual plot\ncannot choose the independence unit; the design does. And a count of 79\nclusters does not certify the approximation: the balance of information\nacross clusters and the influence of particular schools also matter.\n\n### Read the bounded answer, then evaluate its support\n\nA chapter-authored report can now state:\n\n> On 3,735 complete two-arm kindergarten records, the common adjusted\n> small-versus-regular class-type coefficient was 6.6575 reading points,\n> with approximate school-clustered interval [3.2782, 10.0368]. Its causal\n> mean-effect interpretation relies on documented within-school\n> randomization, a verified link from recorded class type to original\n> assignment, suitable complete-record selection, independent-school\n> uncertainty, and a common-effect or target-matching weighting argument.\n> It concerns assigned class type, one kindergarten reading outcome, and\n> participating Tennessee schools, not realized headcount or a portable\n> policy dose response.\n\nRead the report's functions before judging it, applying Chapter 1's\nargument components as Chapters 7 and 8 did. The sample audit and the\nmodel code carry **STAT-E** content; the design and covariance reasoning\nsupplies **STAT-J**; the estimate and its clustered interval supply\n**STAT-I**; and the first sentence is the bounded **STAT-C** answer.\n**SUB-E** situates the pupils, the test, the cohort, and the school\ncontext; **SUB-J** adds the assignment record together with the selection\nand weighting qualifications; **SUB-I** reads the coefficient as\nassignment-related only under that support; and **SUB-C** bounds the\nsubstantive claim. These are linked functions within one argument, not two\narguments.\n\nThen separate what is *stated* from what is *demonstrated*. The report\nstates the selection and weighting conditions; stating them does not\nestablish that they hold. The randomization protocol is documented in the\nstudy's own publications, not shown by this coefficient table. The link\nfrom the recorded class-type field to the original assignment is asserted\nhere and not verified. Where a necessary link cannot be assessed, the\nhonest move is to report the limitation rather than to invent it or to\nquietly substitute a different target.\n\nThe design literature documents implementation and interpretation issues\nthat a single coefficient cannot settle [@krueger1999; @hanushek1999;\n@nye2000; @chetty2011]. Nor does this result transport by itself to\nnonparticipating schools, another period, another outcome, or another\neducation system. Those limits belong inside the answer, not in a list\nappended after an unrestricted claim, and a crossed significance boundary\nis not what makes a result [@gelman2006; @gelman2020]. Chapter 14 returns\nto dependence as a design fact, reuses this calculation as its example,\nand asks what a design supplies that adjustment cannot.\n\n## Reading Bridge {#sec-ch9-summary}\n\nA factor enters a regression as indicators, and its fitted means,\ncontrasts, and omnibus test are the analysis of variance written as a\nmodel; a contrast's uncertainty needs the covariance between coefficients,\nnot the sum of two standard errors. The analysis of covariance is the same\nregression with a pretest added: the posttest-only, gain-score, and\nadjusted analyses differ only in the pretest coefficient, and adjustment\nsharpens a randomized comparison without supplying what randomization\nsupplies. Nested models compare on the same records and the same outcome\nby an extra-sum-of-squares $F$, and information criteria rank them by\npenalized in-sample fit, never by held-out error. A squared predictor\ngives a comparison that depends on the predictor's value; a logged outcome\nchanges the question to a geometric-mean scale, and its criteria no longer\nspeak to the original one. HC3, the case bootstrap, and a clustered\ncovariance each change the uncertainty calculation for a stated reason and\nleave the fitted coefficients alone; none repairs curvature, missing\noutcomes, weighting, or the absence of a design. Project STAR showed the\nuncertainty following the design: schools, not pupils, were the\napproximately independent units, and the difference was nearly a factor of\ntwo.\n\nChapter 10 asks a different question of the same equations. Every\ncomparison in this chapter was the same at every value of the other\npredictors, which is what \"additive\" means, and Section 2.5's common-slope\ncheck was the first test of it. Chapter 10 lets a comparison itself vary\nwith another predictor, and develops how to read, probe, and report such\nan interaction.\n\n\\Needspace{14\\baselineskip}\n\n### Key terms {.unnumbered}\n\nUse this short reference to revisit the concepts introduced here. The\nPart One Concept Reference gives the broader reference and the principal\nhome of each concept; indicator coding, partial slopes, coefficient\ncovariance, and HC3 are explained in Chapters 7 and 8, and regression\ntoward the mean in Chapter 7.\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| ANCOVA (analysis of covariance) | A regression comparing groups while including a quantitative covariate with one common slope; its adjusted group means are read at a stated covariate value within common support. The posttest-only, gain-score and ANCOVA analyses are one regression whose pretest coefficient is 0, 1 or estimated; adjustment cannot supply what random assignment supplies. |\n| Homogeneity of regression slopes (parallel slopes) | ANCOVA's condition that the outcome--covariate slope is the same in every group, checked by testing the group-by-covariate product block; when the slopes differ, the adjusted difference depends on the covariate value at which it is read. |\n| Nested-model $F$ test (extra sum of squares; block test) | Compares a reduced model with a fuller one fitted to the same records and outcome: the RSS reduction per added coefficient, divided by the fuller model's residual mean square, referred to $F$ with the number of restrictions and the fuller model's residual df. It tests the added block jointly, not each coefficient separately. |\n| Information criteria (AIC; BIC) | Penalized in-sample fit: $-2\\log\\widehat L$ plus $2k$ (AIC) or $k\\log n$ (BIC), with $k$ counting the coefficients and the residual variance. Smaller is preferred among models fitted to the same records and outcome scale; neither is held-out error. |\n| Polynomial term (quadratic term; curvature) | A power of a predictor added as a further column so that the fitted mean can curve. The predictor's comparison then depends on its value; centering before squaring reduces collinearity without changing the fitted curve. |\n| Log-transformed outcome (geometric-mean scale) | Fitting the logarithm of the outcome, so that a coefficient is an additive difference in expected log outcome and $100(e^{\\beta}-1)$ percent is a multiplicative difference in geometric means. A changed outcome scale is a changed question, and its criteria are not comparable with the original scale's. |\n| Standardized coefficient (beta weight) | A partial slope rescaled by the predictor and outcome SDs, in outcome-SD units per predictor SD, with the other predictors held fixed. It differs from standardization over named profiles and does not measure causal importance. |\n| Bootstrap (case resampling; percentile interval) | Refitting the model to many resamples of the records drawn with replacement and using the spread of the refitted estimates as an SE, or their middle 95% as a percentile interval. It treats the resampled units as independent and exchangeable; it does not repair dependence, thin support, measurement error, or an observational design. |\n| Cluster-robust standard error (school-clustered covariance) | A coefficient covariance that sums residual contributions within clusters, such as schools, before combining them, allowing dependence within clusters under an approximation that treats clusters as independent. It changes uncertainty, not the coefficient, and does not repair missing outcomes or weighting. |\n\n: Selected concepts for the regression toolbox. {#tbl-ch09-key-terms tbl-colwidths=\"[28,72]\"}\n\n### Further reading {.unnumbered}\n\n- The [OpenIntro multiple-predictor and model-selection tutorial](https://openintro-ims.netlify.app/model-mlr)\n  gives concrete indicator interpretations and criterion-based reading. We\n  use its equation-first device without adopting automatic stepwise\n  selection.\n- The [ISLR regression lab](https://hastie.su.domains/ISLR2/Labs/Rmarkdown_Notebooks/Ch3-linreg-lab.html)\n  and the [ISLR resampling lab](https://hastie.su.domains/ISLR2/Labs/Rmarkdown_Notebooks/Ch5-resample-lab.html)\n  connect fitting, factors, criteria, and resampling in one workflow\n  [@james2021].\n- Fox [@fox2016] and Kutner and colleagues [@kutner2005] develop the\n  linear-model algebra, the restriction statistic, and the diagnostics\n  behind this chapter's matrix section.\n- Efron and Tibshirani [@efron1993] and Davison and Hinkley [@davison1997]\n  are the standard bootstrap references, including the bootstrap-$t$ and\n  BCa intervals named in Section 6.3.\n- The [sandwich documentation](https://cran.r-project.org/web/packages/sandwich/sandwich.pdf)\n  specifies the HC and CR covariance calls used here [@zeileis2020].\n\n## Exercises {.unnumbered}\n\nUse the supplied numbers; rounding within 0.02 is acceptable unless a\ndifferent precision is requested. These prompts do not require the\nappendices.\n\n\\Needspace{12\\baselineskip}\n\n<!-- prompt-id: CH09-E01 -->\n### Exercise 1: Read indicator coefficients (Foundational) {.unnumbered #ex-ch09-01}\n\nA group-only regression of income (thousand dollars) on occupation type\nhas observed group means 5.3741 (blue-collar, 44 records), 10.5595\n(professional, 31), and 5.0523 (white-collar, 23). (1) With blue-collar as\nreference, give the intercept and the two indicator coefficients. (2) Give\nthe intercept and both coefficients with white-collar as reference. (3)\nExplain why the fitted values are the same under both codings. (4) The\nfull additive model's professional coefficient is 0.3242. Explain why it\ndiffers from the professional coefficient in (1) and why neither is \"the\neffect of occupational type\".\n\n\\Needspace{10\\baselineskip}\n\n<!-- prompt-id: CH09-E02 -->\n### Exercise 2: A contrast needs covariance (Foundational) {.unnumbered #ex-ch09-02}\n\nIn the full additive model the professional and white-collar coefficients\nare 0.3242 and 0.2353, with estimated variances 2.1406 and 0.9698 and\ncovariance 0.9720, on 92 residual df. (1) The\nprofessional-minus-white-collar contrast is 0.0889. Calculate its\nvariance, and explain why the covariance enters with a minus sign and what\na positive covariance does to the result. (2) The contrast's SE is 1.08\nand its 95% interval is $[-2.0561,\\ 2.2338]$. A student instead adds the\ntwo coefficient SEs (1.4631 and 0.9848). State what that number is and why\nit is wrong. (3) Explain what the interval does and does not say about the\ntwo types.\n\n\\Needspace{10\\baselineskip}\n\n<!-- prompt-id: CH09-E03 -->\n### Exercise 3: A nested comparison from residual sums of squares (Foundational) {.unnumbered #ex-ch09-03}\n\nOn the same 98 records, the model with education and prestige has RSS\n867.6537 on 95 df, and the full model adding the percentage of women and\nthe two type indicators has RSS 630.8897 on 92 df. The 5% critical value\nof $F(3,92)$ is 2.7036. (1) Calculate the $F$ statistic for the added\nblock. (2) State the decision at 5% and what it does and does not say\nabout the three added columns. (3) Explain why the sequential sums of\nsquares from a single `anova()` call on the full model would not answer\nthis question.\n\n\\Needspace{10\\baselineskip}\n\n<!-- prompt-id: CH09-E04 -->\n### Exercise 4: What information criteria compare (Foundational) {.unnumbered #ex-ch09-04}\n\nThe full additive model has maximized log-likelihood $-230.302$ on 98\nrecords, with AIC 474.6040 and BIC 492.6988; the model with education and\nprestige only has AIC 499.8328 and BIC 510.1727. (1) The criteria count\nseven fitted parameters for the full model. Say what the seven are, and\nwhy BIC charges the full model more for them than AIC does\n($\\log 98=4.585$). (2) Which model do the criteria favour, and on what\ncondition is that comparison meaningful? (3) A log-income version of the\nfull model has AIC 8.091. Explain why this number cannot be compared with\n474.604.\n\n\\Needspace{10\\baselineskip}\n\n<!-- prompt-id: CH09-E05 -->\n### Exercise 5: Percent and curvature (Integrative) {.unnumbered #ex-ch09-05}\n\nTwo changed models of the occupation records raise different questions.\n(1) In a log-income model the prestige coefficient is 0.0207. Give the\npercent difference in geometric-mean income per prestige point and say\nwhat \"geometric mean\" adds to the reading. (2) In an income model with a\nsquared prestige term, the fitted slope is 0.0697 thousand dollars per\nprestige point at prestige 30, 0.1665 at 50 and 0.2633 at 70, and the\nturning point is at prestige 15.5906; prestige ranges from 17.3 to 87.2.\nExplain why the model has no single prestige slope, and what the position\nof the turning point tells you. (3) State in one sentence what the curve\nclaims about income and prestige over the observed range, and one reason\nthat claim is a sensitivity check rather than a discovery.\n\n\\Needspace{10\\baselineskip}\n\n<!-- prompt-id: CH09-E06 -->\n### Exercise 6: Choose the uncertainty calculation (Integrative) {.unnumbered #ex-ch09-06}\n\nIn Project STAR the small-minus-regular kindergarten reading difference on\n3,745 observed records is 5.8151 points. Three standard errors are\navailable: 1.0377 treating pupils as independent, 1.0416 with HC3, and\n1.8476 clustering pupils within their 79 schools. Treating pupils as\nindependent gives the 95% interval $[3.7807,\\ 7.8496]$. (1) Using\n$t_{.975,78}=1.9908$, give the interval under the clustered calculation\nand compare its width with the first. (2) Say which interval a report\nshould use and why, naming the unit at which assignment happened, and\nexplain why HC3 barely changes the first standard error. (3) Name two\nproblems that none of the three calculations repairs.\n\n\\Needspace{10\\baselineskip}\n\n<!-- prompt-id: CH09-E07 -->\n### Exercise 7: One randomized study, three analyses (Integrative) {.unnumbered #ex-ch09-07}\n\nIn the Baumann records, 66 pupils in three randomized instruction groups\nhave a pretest and a posttest. With DRA as reference, the DRTA difference\nis 3.0909 (SE 0.9614) from the posttest alone, 3.8636 (SE 0.7779) from the\ngain score, and 3.6266 (SE 0.7362) from the analysis of covariance, whose\npretest coefficient is 0.6932; the DRA and DRTA pretest means are 10.5000\nand 9.7273. (1) Write the three analyses as one regression and give the\npretest coefficient each uses. (2) Explain why all three estimate the same\naverage difference under random assignment, and show how the pretest gap\naccounts for the differences between the three estimates. (3) Say which\nanalysis you would report, and when that choice has to be made. (4)\nSuppose the groups had been intact classes that differed at the pretest.\nExplain what changes, naming the paradox that can arise.\n\n## Appendix A: Matrix Geometry, Restrictions, and Sandwich Constructions {.unnumbered #app-ch9-a}\n\nThis appendix derives the results that Sections 3.2, 5.2, and 7.5 used,\nincluding the HC3 estimator that Chapter 8, Appendix B, stated, and\nnames the target least squares estimates when a linear mean is only an\napproximation. It is reference material: the exercises do not require\nit, and the main route is complete without it. The Computer Lab carries\nthe numerical reproductions of each construction.\n\n### Projection and the normal equations {.unnumbered}\n\nLet $\\mathbf X$ be $n\\times p$ with full column rank, so\n$\\mathbf X^{\\mathsf T}\\mathbf X$ is invertible. The least-squares\ncriterion is\n$S(\\boldsymbol\\beta)=(\\mathbf y-\\mathbf X\\boldsymbol\\beta)^{\\mathsf T}(\\mathbf y-\\mathbf X\\boldsymbol\\beta)$.\nExpanding gives\n$S=\\mathbf y^{\\mathsf T}\\mathbf y-2\\boldsymbol\\beta^{\\mathsf T}\\mathbf X^{\\mathsf T}\\mathbf y\n+\\boldsymbol\\beta^{\\mathsf T}\\mathbf X^{\\mathsf T}\\mathbf X\\boldsymbol\\beta$,\nand differentiating with respect to $\\boldsymbol\\beta$ yields the normal\nequations\n\n$$\n\\mathbf X^{\\mathsf T}\\mathbf X\\widehat{\\boldsymbol\\beta}=\\mathbf X^{\\mathsf T}\\mathbf y,\n\\qquad\\text{equivalently}\\qquad\n\\mathbf X^{\\mathsf T}(\\mathbf y-\\mathbf X\\widehat{\\boldsymbol\\beta})=\\mathbf 0 .\n$$\n\nThe second form is the geometry: the residual vector is orthogonal to\nevery column of $\\mathbf X$. Hence\n$\\widehat{\\mathbf y}=\\mathbf X\\widehat{\\boldsymbol\\beta}=\\mathbf H\\mathbf y$\nwith $\\mathbf H=\\mathbf X(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf X^{\\mathsf T}$,\nand $\\mathbf H$ is symmetric and idempotent, the orthogonal projection\nonto the column space of $\\mathbf X$. Its trace is $p$, which is why the\nleverages $h_{ii}$ sum to the number of fitted coefficients; for `m2` they\nsum to 6.\n\nTwo consequences used earlier follow immediately. Any full-rank recoding\n$\\mathbf X\\mathbf A$, with $\\mathbf A$ invertible, spans the same column\nspace, so $\\mathbf H$ and $\\widehat{\\mathbf y}$ are unchanged: releveling a\nfactor or centering a predictor cannot alter a single fitted value. Adding\na genuinely new column enlarges the space and can change every fitted\nvalue. And under the classical error model,\n$\\widehat{\\mathbf V}=s^2(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}$ with\n$s^2=RSS/(n-p)$, which is where every classical standard error in this\nchapter came from. Solving the normal equations directly for `m2`\nreproduces `lm()`'s coefficients to about $10^{-13}$.\n\n### General linear restrictions {.unnumbered}\n\nLet $\\mathbf R$ be $q\\times p$ of rank $q$ and consider\n$\\mathbf R\\boldsymbol\\beta=\\mathbf r$. Since $\\widehat{\\boldsymbol\\beta}$\nhas covariance $\\sigma^2(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}$ under the\nclassical model, the vector $\\mathbf R\\widehat{\\boldsymbol\\beta}-\\mathbf r$\nhas covariance\n$\\sigma^2\\mathbf R(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf R^{\\mathsf T}$.\nStandardizing by that covariance and dividing by $q$ gives the statistic of\nSection 3.2, which has an exact $F_{q,\\,n-p}$ reference under Normal\nerrors, because its numerator and denominator quadratic forms are\nindependent chi-squares.\n\nIt is the same number the extra-sum-of-squares formula produces.\nMinimizing $S(\\boldsymbol\\beta)$ subject to\n$\\mathbf R\\boldsymbol\\beta=\\mathbf r$ with a Lagrange multiplier gives the\nrestricted estimator\n$\\widetilde{\\boldsymbol\\beta}=\\widehat{\\boldsymbol\\beta}\n-(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf R^{\\mathsf T}\n[\\mathbf R(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf R^{\\mathsf T}]^{-1}\n(\\mathbf R\\widehat{\\boldsymbol\\beta}-\\mathbf r)$, a correction applied\nonly in the directions the restriction touches. Substituting it into the\ncriterion shows that the increase in residual sum of squares is\n\n$$\nRSS_R-RSS_F=(\\mathbf R\\widehat{\\boldsymbol\\beta}-\\mathbf r)^{\\mathsf T}\n[\\mathbf R(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf R^{\\mathsf T}]^{-1}\n(\\mathbf R\\widehat{\\boldsymbol\\beta}-\\mathbf r),\n$$\n\nwhich is exactly the numerator of the restriction statistic. Fitting the\nreduced model and differencing, or evaluating the quadratic form in the\nunrestricted fit, are two routes to one number; for the two type\ncoefficients of `m2` both return 0.0319. Replacing\n$s^2(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}$ by a robust covariance in the\nmiddle of the expression gives the Wald statistic of Section 5.2. The\nalgebra survives the substitution; the exact reference distribution does\nnot.\n\n### The HC3 sandwich {.unnumbered}\n\nChapter 8, Appendix B, stated the HC3 estimator; this subsection shows\nwhere it comes from. Write the coefficient error as\n$\\widehat{\\boldsymbol\\beta}-\\boldsymbol\\beta\n=(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf X^{\\mathsf T}\\boldsymbol\\varepsilon$.\nUnder independent rows with possibly different variances $\\sigma_i^2$, its\nexact covariance is\n\n$$\n(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\n\\Big(\\sum_i\\sigma_i^2\\,\\mathbf x_i\\mathbf x_i^{\\mathsf T}\\Big)\n(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1},\n$$\n\na *sandwich* with the design component as bread and the error-scale\ncomponent as filling. The classical estimator substitutes a common $s^2$,\nwhich collapses the filling to $s^2\\mathbf X^{\\mathsf T}\\mathbf X$. The HC\nfamily substitutes each row's own squared residual instead. Because\n$E(e_i^2)=\\sigma_i^2(1-h_{ii})$ under the classical model, the raw residual\nunderstates the error at high-leverage rows; HC3 corrects by dividing by\n$(1-h_{ii})^2$, which is deliberately slightly conservative and performs\nwell in small samples [@mackinnon1985; @long2000]. Built directly from\nthese pieces, the estimator reproduces `sandwich::vcovHC(m2, type = \"HC3\")`\nto about $10^{-12}$.\n\n### The CR1 cluster sandwich {.unnumbered}\n\nCluster robustness changes the filling, not the bread. Partition the rows\ninto $G$ clusters and let $\\mathbf X_g$ and $\\mathbf e_g$ hold cluster\n$g$'s rows and residuals. The cluster score\n$\\mathbf s_g=\\mathbf X_g^{\\mathsf T}\\mathbf e_g$ sums the within-cluster\ncontributions *before* the outer product is taken, so the estimator of\nSection 7.5 retains the within-cluster residual correlations that the\nindependent-row filling discards. If every cluster held one row, the\nfilling would reduce to the HC0 form, which is why a row-level robust SE\nis the special case that assumes away the dependence.\n\nThe asymptotics are in $G$, not in $n$: 3,745 pupils in 79 schools supply\n79 approximately independent pieces of information for this covariance,\nwhich is why the clustered SE of 1.8476 is so much larger than the\nrow-level 1.0377 and why a $t_{G-1}$ reference is used. For the\nobserved-reading model the finite-cluster factor is $c_G=1.0131$, and\nbuilding the estimator from the school scores reproduces\n`sandwich::vcovCL(..., type = \"HC1\", cadjust = TRUE)` to about $10^{-13}$.\n\n### What least squares estimates when the mean is not linear {.unnumbered #app-ch09-projection-target}\n\nA linear regression is often fitted where the conditional mean of the\noutcome is not exactly linear in the predictors, as Section 4.1's curved\nprestige component shows. Least squares then still estimates a defined\ntarget: the **best linear projection**, the coefficients that minimize\nexpected squared error over the population the records represent,\n\n$$\n\\begin{gathered}\n(\\beta_0^*,\\beta_1^*)=\\arg\\min_{a,b}E\\{(Y-a-bX)^2\\},\\qquad\n\\beta_1^*=\\frac{\\operatorname{Cov}(X,Y)}{\\operatorname{Var}(X)}, \\\\\n\\boldsymbol\\beta^*=\\{E(\\mathbf x\\mathbf x^{\\mathsf T})\\}^{-1}E(\\mathbf x Y).\n\\end{gathered}\n$$\n\nWith one predictor the target slope is the population covariance over the\npredictor's variance, the population version of Chapter 7's\ncovariance-to-slope identity; with several, it is the population version\nof the normal equations. The target is well defined, but it is an\naverage: the projection slope of income on prestige in the additive model\naverages the curve's steeper and flatter stretches, weighted by where the\noccupations' prestige values fall. Its value therefore depends on the\ndistribution of the predictors, and a sample with a different prestige\nmix would have a different target even with the same curve. It is a\ndeclared alternative target, not a rescue for a misspecified mean. HC3\nstandard errors remain appropriate for it under independent sampling,\nbecause the curvature the linear fit misses behaves like one more source\nof unequal spread [@fox2016].\n\n## Appendix B: Bootstrap Schemes and Intervals {.unnumbered #app-ch9-b}\n\nSection 6 used case resampling and said why. @tbl-ch09-schemes sets it\nbeside the other two schemes on the same model, the same three targets,\nthe same seed, and $B=2000$.\n\n| Scheme | What is resampled | Assumption carried | Education slope | prof $-$ wc | prof coefficient |\n|:--|:--|:--|--:|--:|--:|\n| Case | Whole records | Records independent and exchangeable | 0.3699 | 1.1187 | 1.9926 |\n| Residual | Rescaled residuals, moved across records; design fixed | One error distribution for every record | 0.2820 | 1.1081 | 1.4861 |\n| Wild | Each record's own rescaled residual, sign flipped at random; design fixed | Each record keeps its own error scale | 0.3673 | 1.1151 | 1.9767 |\n\n: Three bootstrap schemes for the full occupation model, with each scheme's bootstrap SE for three targets (seed 90909, $B=2000$). {#tbl-ch09-schemes tbl-colwidths=\"[11,27,24,13,12,13]\"}\n\nBoth design-fixed schemes rebuild outcomes from the fitted values.\nResidual resampling draws leverage-rescaled residuals $e_i/\\sqrt{1-h_{ii}}$\nwith replacement and adds them to the fitted values, which treats the\nrescaled residuals as exchangeable across rows. The wild bootstrap keeps\neach row's own rescaled residual and multiplies it by $\\pm1$ with equal\nprobability, so each row retains its own error scale.\n\nRead the table by column. For the education slope the residual scheme is\nthe outlier, 0.2820, close to the classical 0.2752, which is what one\nshould expect, since both assume one common error distribution. The wild\nbootstrap, which does not, lands at 0.3673, near the case result and near\nHC3's 0.3823. For the professional coefficient the pattern repeats more\nstrongly: 1.9926, 1.4861, and 1.9767. When the schemes disagree, the\ndisagreement is about the error model, not about the data, and it is a\nreason to say which scheme was used.\n\nFour interval definitions are worth distinguishing in words.\n\n- The **percentile interval** takes the 2.5th and 97.5th percentiles of\n  the resampling distribution of the estimate.\n- The **normal-approximation interval** takes the original estimate plus\n  and minus 1.96 bootstrap standard errors. It uses the resampling\n  distribution only for its spread, so it is insensitive to skewness.\n- The **bootstrap-$t$ interval** resamples a studentized quantity, the\n  resampled estimate minus the original estimate, divided by the\n  resample's own standard error, and inverts the empirical quantiles of\n  that ratio. It needs a standard error inside every resample, and it is\n  more accurate when the studentized quantity is closer to pivotal than\n  the estimate itself.\n- The **BCa interval** adjusts the percentile endpoints for median bias\n  and for an acceleration constant that captures how the standard error\n  changes with the parameter. It is the usual recommendation when the\n  resampling distribution is visibly skewed [@efron1993; @davison1997].\n\nFor the three targets of Section 6 the skewness values $-0.3891$, 0.2635,\nand 0.3785 are mild, so percentile and normal-approximation endpoints agree\nclosely and the higher-order corrections would change little. That\nagreement is a property of this example, not a general licence.\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_09_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}