{
  "hash": "9d4af24ccc98f046666912f7d09aa882",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Prediction, Cross-Validation, and Regularization\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{16\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\\newpage\n\n::: {.callout-note title=\"Chapter overview\"}\nA regression equation can describe a conditional comparison and still predict individuals poorly. This chapter asks how accurately a fitted rule will predict outcomes it has not seen, at the moment the prediction is needed. We begin with two fixed rules on 98 occupation records, then follow a school prediction problem through held-out evaluation, information leakage, regularization, probability scoring and changes of setting. By the end, you should be able to define a prediction target and loss, explain which information a fit may use, interpret a tuning curve and a probability, and qualify a predictive claim by the records and validation design that support it.\n:::\n\nA district wants to identify students who may finish the year below the passing standard in mathematics. It needs the predictions early enough to offer support. A final-grade model built from second-period grades might predict very well, but it cannot supply a September list. A model built from background information may be available earlier and predict much less well. Neither a small coefficient $p$-value nor a high in-sample $R^2$ settles which rule will help.\n\nThe timing requirement belongs to the research question. So do the mistakes that matter: missing a student who needs help and offering tutoring to one who would pass have different consequences. The chapter develops these choices alongside the statistical machinery, using a deliberately modest predictive result as seriously as a successful one.\n\n## Prediction Is a Different Aim {#ch13-aims}\n\n### Four aims, one equation\n\nThe same fitted mean can serve four aims. Description summarizes the records; association estimates a conditional comparison and its uncertainty; a causal interpretation needs a design and identification argument; prediction concerns the error on new units. These aims have different evidence requirements [@shmueli2010]. A predictor may help forecast an outcome without being a useful intervention target. Conversely, a carefully estimated association can explain little of the variation between individual outcomes.\n\n| Aim | What is estimated | What settles the answer | Chapter |\n|:--|:--|:--|:--|\n| Description | A summary of the records in hand | The records and the summary's definition | 2, 5 |\n| Association | A conditional comparison and its uncertainty | The sampling or model repetition behind the SE | 3, 7--12 |\n| Causal explanation | A contrast of outcomes under two conditions | Design, assignment, and identification conditions | 1, 9, 14 |\n| Prediction | The error a fixed rule will make on unseen units | A loss, a deployment moment, and held-out data | 13 |\n\n: The same fitted equation can serve four aims, which are settled by different information. {#tbl-ch13-aims tbl-colwidths=\"[18,32,34,16]\"}\n\nA downstream measurement can be valuable for a late forecast and unavailable for an early one. An administrative marker may predict who receives a service without identifying what the service changes. Choosing a predictive aim therefore fixes a target and an evaluation design; adding the word \"predict\" to an associational report is insufficient.\n\n### Specify the prediction problem before fitting\n\nThe district's proposed unit is one student in one school year. Its targets are the final mathematics grade, an integer from 0 to 20, and the probability that this grade is below 10. Its proposed deployment moment is the first weeks of the year, its horizon the end of that year, and its action an offer of tutoring. Squared error will assess grade predictions; log loss and the Brier score will assess probabilities; a stated ratio of error costs will assess the tutoring decision.\n\nThe intended population might be students in a district, but the available public records come from only two Portuguese secondary schools. That is a gap to evaluate, not a population definition supplied by the dataset. A second gap concerns timing: the source describes school reports and questionnaires but does not establish when every background and support field became available. Our twelve-variable early set is therefore a candidate specification for a teaching analysis. A real September service would first have to verify each field's timestamp and meaning.\n\nA predictor is admissible only if its value would be known when a new prediction must be made. A year-end absence total fails that test just as clearly as a second-period grade. Replacing it by absences accumulated before the prediction date would define a different variable that these records do not supply.\n\n### Generalization error: which expectation?\n\nLet $\\widehat f$ be a rule fitted to training records $\\mathcal D$, and let $\\mathcal L$ measure prediction loss. Its **conditional generalization error** is\n\n$$\n\\mathrm{Err}(\\widehat f\\mid\\mathcal D)=E\\Big(\\mathcal L\\big(Y_{\\mathrm{new}},\\widehat f(X_{\\mathrm{new}})\\big)\\mid\\mathcal D\\Big).\n$$ {#eq-ch13-risk}\n\nHere the fitted training set is fixed and the expectation is over a new unit from the deployment distribution. Averaging this quantity also over training sets of size $m$ gives the risk $R_m$ of the **learning rule**: a procedure for turning $m$ eligible records into predictions. These are related but distinct targets. A held-out test set evaluates a fitted rule; repeated training and evaluation concern a procedure and its training size.\n\nNeither population expectation is directly observed. We estimate it by keeping outcomes away from the procedure that predicts them. The model's own fitted residuals measure **apparent error**. Because those outcomes helped choose the fit, their average loss usually looks too favourable for future use. The gap is called optimism [@hastie2009]. A coefficient interval, a new-case prediction interval and a held-out average loss answer three different questions: uncertainty about a conditional comparison, uncertainty about one future outcome, and performance of a predictive rule.\n\n## Apparent Versus Held-Out Error {#ch13-heldout}\n\n### Start with two declared rules\n\nThe occupation example uses 98 type-complete rows of `carData::Prestige`. Income is measured in thousand 1971 dollars. One rule uses education; the other adds prestige, the proportion of women and occupation type. Both are fixed additive regressions, compared on the same records. The full fit has six coefficients including the intercept; the education-only fit has two.\n\nFitted on all 98 rows, their MAEs are 2.3668 and 1.4785. Their fitted values have already used the corresponding income observations. To estimate prediction performance, we instead withhold groups of records, fit to the remaining rows and predict the withheld outcomes.\n\nThe comparison fixes both candidate rules, uses the same complete records and income conversion, and requires all three occupation types and a full-rank model in every training set. Each withheld occupation receives equal weight. These choices make the comparison interpretable; they do not make the eligible occupations a random sample of every population to which a reader might wish to apply it.\n\n### One fold makes the boundary visible\n\nA shared balanced ten-fold partition uses seed 80806. Eight assessment folds contain ten occupations and two contain nine. The first record, government administrators, belongs to fold 9; that fold uses 89 training records and nine assessment records. The following fragment exposes the essential boundary: neither model sees fold 9 while it estimates coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain <- dat[fold != 9, ]; test <- dat[fold == 9, ]\nm0 <- lm(income_k ~ education, data = train)\nm1 <- lm(income_k ~ education + prestige + women + type, train)\ncbind(test$income_k, predict(m0, test), predict(m1, test))\n```\n:::\n\n\nGovernment administrators have observed income 12.351, with predictions 8.9461 and 11.5948: absolute errors 3.4049 and 0.7562. Surveyors have income 5.902, with predictions 8.316 and 11.098: errors 2.414 and 5.196. The larger rule wins the first comparison and loses the second. Performance is a summary over eligible cases, not a promise that every prediction improves.\n\n**Predict and explain.** If the full rule has lower average error, must its prediction improve for every withheld occupation? Compare the two sets of segments in @fig-ch13-withheld before reading the pooled result. Each segment is one prediction error; its length matters, and its direction shows overprediction or underprediction.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The full rule helps some withheld occupations and misses others by more.](chapter_13_files/figure-html/fig-ch13-withheld-1.png){#fig-ch13-withheld fig-pos='!ht' fig-alt='Nine occupations withheld in fold 9 have observed and predicted incomes joined by segments. The full rule reduces the error for government administrators but increases it for surveyors; a better overall average need not improve every case.' width=643.2}\n:::\n:::\n\n\nEach fold takes this turn once. Pooling all 98 held-out errors gives\n\n$$\nMAE=\\frac1n\\sum_i|y_i-\\widehat y_i^{(-k(i))}|,\n\\qquad RMSE=\\sqrt{\\frac1n\\sum_i(y_i-\\widehat y_i^{(-k(i))})^2},\n$$\n\nwhere $k(i)$ is the fold containing case $i$, and the superscript means its prediction came from a fit without that fold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolMeans(abs(pred - dat$income_k))\nsqrt(colMeans((pred - dat$income_k)^2))\n```\n:::\n\n\n| Learning rule | Apparent MAE | Held-out MAE | Apparent RMSE | Held-out RMSE |\n|:--|--:|--:|--:|--:|\n| Education-only OLS (2 coefficients) | 2.3668 | 2.4031 | 3.4442 | 3.5051 |\n| Full additive OLS (6 coefficients) | 1.4785 | 1.5412 | 2.5373 | 2.7111 |\n| Difference: full minus education-only | $-0.8883$ | $-0.8619$ | $-0.9070$ | $-0.7940$ |\n\n: Apparent and pooled held-out errors for two fixed rules on the same 98 occupation records, thousand 1971 dollars. {#tbl-ch13-optimism tbl-colwidths=\"[36,16,16,16,16]\"}\n\nBoth rules look better on the outcomes they fitted. The MAE gaps are 0.0363 and 0.0627; the RMSE gaps are 0.0609 and 0.1739. More fitting produced more optimism in this example, although this is not a universal ordering for every pair of models or every loss. The held-out comparison still favours the full rule by 0.8619 thousand dollars in MAE.\n\nThe comparison concerns rules trained on 88 or 89 records: eighty assessment cases use fits trained on 88 rows and eighteen use fits trained on 89. It therefore estimates performance at those training sizes, rather than the risk of a final fit to all 98. The training sets overlap, so the held-out errors are not results from 98 independent fitted models. Random fold labels establish neither exchangeability of the eligible records nor population representativeness.\n\n### Choose the loss and its reference\n\nMAE treats each additional unit of absolute error equally. Squared loss gives a large miss disproportionate weight. Errors $(1,1,1,1,6)$ and $(2,2,2,2,2)$ both have MAE 2, but their RMSEs are 2.8284 and 2. The choice says what kinds of mistakes matter and should precede the comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ne <- c(1, 1, 1, 1, 6)\nc(MAE = mean(abs(e)), RMSE = sqrt(mean(e^2)))\n```\n:::\n\n\nA loss also needs a reference. The constant predictor assigns each assessment case the mean outcome of its training rows. Against that deployable reference,\n\n$$\nR^2_{\\mathrm{out}}=1-\\frac{\\sum_i(y_i-\\widehat y_i^{(-k(i))})^2}{\\sum_i(y_i-\\bar y^{(-k(i))})^2}.\n$$\n\nA negative value means that the rule predicts worse than the reference. This is not the in-sample $R^2$ of a fitted regression. Using the assessment mean would give the reference information unavailable at deployment.\n\nPooling records weights every case equally. Averaging fold MSEs weights every fold equally, which differs when their sizes differ. Averaging fold RMSEs additionally takes the square root before averaging. We use pooled case loss for the occupation comparison and explicitly labelled equal-fold summaries for the student teaching calculations. Software conventions must be checked: `cv.glmnet()` weights fold means by their assessment sizes.\n\n### A split can change without a new study\n\nThe ten occupation-fold MAE differences have SD 0.6256; folds 9 and 10 favour the smaller rule. Redrawing the partition 200 times with seed 80807 gives a mean pooled difference of $-0.8311$, range [$-0.914,-0.741$] and SD 0.0285. Every resplit favours the full rule, although its margin moves.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The full rule wins every resplit of these records, but its estimated advantage changes.](chapter_13_files/figure-html/fig-ch13-resplits-1.png){#fig-ch13-resplits fig-pos='!ht' fig-alt='A histogram of 200 pooled MAE differences lies entirely below zero, between minus .914 and minus .741.' width=604.8}\n:::\n:::\n\n\nThe fold spread describes small assessment groups within one partition. The resplit spread describes sensitivity to reallocating the same records. Neither is a confidence interval over new studies, and the 200 partitions are not 200 independent samples. Overlapping training sets also make the usual independent-fold SE formula an unreliable sampling uncertainty calculation. Later we use resplit sensitivity to inform a declared practical selection tolerance, while keeping it separate from an inferential claim of equal population performance.\n\n## Leakage and the Fitting Boundary {#ch13-leakage}\n\n### Every data-adaptive choice is part of fitting\n\n**Data leakage** occurs when a prediction uses information unavailable at its intended deployment moment or information from the outcomes and records reserved to evaluate it [@kaufman2012]. A coefficient fit is only one data-adaptive step. Choosing predictors, estimating an imputation mean, scaling a column, selecting a cutpoint and tuning a penalty can also change with the training sample. To assess the full procedure, each such step must be learned from that fold's training records and then applied unchanged to its assessment records.\n\nThe distinction is between a fixed specification and a learned quantity. The codebook may define a factor's levels, and a fixed division by 1,000 may convert units before splitting. The sample mean used to center a variable must instead come from the training part. Screening by outcome correlation clearly uses the outcome; scaling still learns from records even though it does not use their outcomes. Both belong inside a procedure intended to act on genuinely new cases.\n\nThe boundary also depends on what will be new when the rule is used. **Predict and explain:** suppose each pupil supplies three subject records, and the service will assess pupils it has never seen. Would randomly withholding individual subject rows reproduce that task? Training could still contain the same pupil's other records, including information about that pupil that a genuinely new pupil would not supply.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![What must be new determines what the assessment must withhold.](chapter_13_files/figure-html/fig-ch13-splits-1.png){#fig-ch13-splits fig-pos='!ht' fig-alt='Four schematic strips show an individual row held out, all records of one pupil held out, all pupils from one school held out, and later years assessed after earlier training. Grey cells are training and blue cells are assessment.' width=643.2}\n:::\n:::\n\n\nFor an independent new record, a row can be the appropriate assessment unit. For a new pupil with repeated measurements, keep all of that pupil's records together. For a new school, withhold its pupils together: a pupil split within the same schools assesses a different question. In @fig-ch13-splits, the letters identify pupils in the second row and schools in the third; the marks illustrate split designs rather than measured data. For a later period, train on earlier information and assess later outcomes. A known pupil's later measurement is another valid target, but its permitted prior history must be stated explicitly.\n\nThese designs change the question the performance estimate can answer. Holding out one school or period supplies evidence about that particular transfer; it does not guarantee successful use at every other site or time. Nested resampling, developed in Appendix B, applies the same boundary to the procedure that chooses a rule.\n\n### The prediction date excludes otherwise useful information\n\n::: {.callout-note title=\"Data and software source\"}\nThe empirical analysis uses a curated, nonsensitive subset of the UCI Student Performance mathematics data: 395 students and 18 documented fields from two Portuguese secondary schools [@cortez2008using; @cortez2008data]. The accompanying CSV retains the selected source values and the Creative Commons Attribution licence; sensitive family, alcohol-use and health fields are excluded. A final grade below 10 defines the at-risk event. Availability of public records establishes neither probability sampling nor early availability of every field. Penalized models use `glmnet` in R [@friedman2010; @glmnet2025; @rcore2025].\n:::\n\nThere are 349 students from Gabriel Pereira (GP) and 46 from Mousinho da Silveira (MS), with no missing values in the curated fields. The mean final grade is 10.4152, SD 4.5814, and 38 grades are zero; 130 students are below the passing standard, an event rate of .3291. These observations are a fixed school record, not a representative district sample.\n\nThe candidate early set has twelve variables: school, age, urban home, travel time, study time, prior failures, school support, family support, paid tutoring, activities, higher-education plans and internet access. Its use in September remains conditional on a field-by-field timing audit. The later set adds the recorded absence total and grades from periods one and two. Those grades correlate .8015 and .9049 with the final grade. They may be sensible inputs to a later forecast but cannot be inputs to the proposed September rule.\n\nWe reserve 98 rows as a protected test set, drawing separately within the two event groups with seed 1305. The other 297 rows form the development set. Their event rates are .3265 and .3300 respectively. Development has 263 GP and 34 MS students. All candidate comparisons use one balanced ten-fold assignment, seed 9702, with seven folds of 30 and three of 29.\n\nTraining, validation and test describe roles. Training estimates one candidate; validation compares candidates or tunes choices; the protected test assesses the frozen choice. A fold's assessment rows become validation information when its results guide selection. The final test remains protected from that selection.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Development rows support fitting and selection; the protected test evaluates the frozen choice.](chapter_13_files/figure-html/fig-ch13-roles-1.png){#fig-ch13-roles fig-pos='!ht' fig-alt='A bar separates 297 development rows from 98 protected test rows. Nine training folds and one assessment fold sit below development; the test is reached only after the rule is frozen.' width=604.8}\n:::\n:::\n\n\nA short formula makes the candidate comparison visible. Here `early` names the twelve-field formula, `late` adds the unavailable later measurements, and `train` and `test` refer to one development fold.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- lm(early, data = train)\nm1 <- lm(late, data = train)\npredict(m0, newdata = test)\npredict(m1, newdata = test)\n```\n:::\n\n\n| Quantity | Early-warning set | Later predictor set | Constant predictor |\n|:--|--:|--:|--:|\n| Apparent RMSE, development rows | 4.1457 | 1.9242 | 4.5714 |\n| Cross-validated RMSE, root mean fold MSE | 4.3727 | 2.0660 | 4.5880 |\n| SD of the ten fold RMSEs | 0.8015 | 0.6216 | --- |\n| Cross-validated MAE, mean over folds | 3.2944 | 1.3551 | 3.4231 |\n| Out-of-sample $R^2$, mean over folds | .0847 | .7953 | 0 |\n| Out-of-sample $R^2$, worst fold | $-.2787$ | .5819 | --- |\n\n: One shared ten-fold assignment inside the 297 development rows; the two sets differ only in the deployment moment. {#tbl-ch13-early-late tbl-colwidths=\"[40,20,20,20]\"}\n\nThe early rule improves only modestly on the constant predictor: RMSE 4.3727 against 4.5880. The later rule reaches 2.066, but answers a later question. An error measured at the wrong prediction moment cannot certify the proposed use.\n\nThe early predictions span 1.2687 to 13.2678 while observed grades use the full 0-to-20 scale. They are concentrated around the overall level because the admissible signals explain relatively little individual variation. This is a substantive limit of the available information, not a reason to seek an impressive coefficient table.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Out-of-fold predicted against observed final grade for the early-warning and end-of-year predictor sets, using the same 10 folds of the development set. The diagonal is perfect prediction.](chapter_13_files/figure-html/fig-ch13-predictions-1.png){#fig-ch13-predictions fig-alt='In the early-warning panel the out-of-fold predictions occupy a band between about 1 and 13 while observed grades run from 0 to 20, and most predictions sit between 8 and 13, so the cloud is much flatter than the diagonal. In the end-of-year panel the points lie close to the diagonal across the whole range, with a group of observed zeros predicted between about minus 2 and 8.' width=624}\n:::\n:::\n\n\nFor example, the early-model coefficient for prior failures is $-1.8099$, SE 0.3581, $t=-5.0535$, $p<.0001$. Under its working model, a conditional-mean difference is clearly detected. Yet the mean fold out-of-sample $R^2$ is only .0847. The first comparison measures a mean difference relative to its SE; the second measures prediction error relative to individual outcome spread. Both can be correct [@shmueli2010; @wasserstein2016].\n\nThe summary convention matters here. The root of mean fold MSE is 4.3727; mean fold RMSE is 4.3061; case-pooled RMSE is 4.3763. Pooled reference RMSE is 4.5884, giving pooled $R^2_{\\mathrm{out}}=.0903$. These summaries differ by more than the fourth decimal. They should not be silently exchanged.\n\nFive-fold, ten-fold and leave-one-out RMSEs for this fixed rule are 4.4621, 4.3727 and 4.3512. Smaller $k$ trains on fewer records and may therefore evaluate a weaker version of the procedure, but the observed ordering is not a theorem. Larger $k$ costs more fitting and increases the overlap of training sets. Twenty repeated ten-fold partitions (seed 2026) give mean 4.3585, SD 0.0331 and range [4.3044,4.4159], whereas the ten fold RMSEs in the original partition have SD 0.8015. These are partition sensitivity and assessment-group variability, respectively; neither measures all uncertainty about future populations.\n\n### A leak, measured\n\nTo expose outcome-informed screening, add 200 independent standard Normal noise columns to the twelve numeric candidate columns (seed 5150). The noise has no population relationship with the outcome by construction. Selecting the 15 largest absolute correlations from all 297 development rows chooses ten noise columns. The largest noise correlation, .1747, looks useful after searching across 200 opportunities.\n\nNow compare two otherwise identical procedures. One screens once, then cross-validates its selected formula. The other repeats the screening using each fold's training rows before fitting and predicting. Only the second keeps an assessment outcome out of the decision that produced its prediction.\n\n| Procedure | Cross-validated RMSE |\n|:--|--:|\n| Screen once on all development rows, then cross-validate | 4.1493 |\n| Screen inside each fold, on its analysis rows only | 4.6786 |\n| No screening: the twelve early-warning variables | 4.3727 |\n| Constant predictor fitted within each analysis fold | 4.5880 |\n\n: The procedures share ten folds. The two screening procedures search 212 candidate columns, including 200 constructed noise columns; the unscreened and constant rules do not use those noise columns. {#tbl-ch13-leakage tbl-colwidths=\"[70,30]\"}\n\nMoving selection inside the fold raises reported RMSE from 4.1493 to 4.6786, a 12.7563% increase. The honest estimate is worse than the constant predictor's 4.588. Screening this wide field harmed prediction; leaked information hid the harm. These numbers demonstrate a procedure's failure, not a substantive relationship among the students.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- cor(train[, candidates], train$grade)\nkeep <- candidates[order(abs(r), decreasing = TRUE)[1:15]]\nm <- lm(reformulate(keep, \"grade\"), data = train)\npredict(m, newdata = test)\n```\n:::\n\n\nThe same boundary applies to selecting transformations, missing-value replacements or outcome definitions. There is no universal formula making leakage proportional to the amount of search. Its magnitude depends on the procedure and data; its direction can still be consequential even when each individual step looks ordinary. With repeated, clustered or time-ordered records, the split itself must also respect what a new deployment unit means (Appendix B).\n\n## Regularization: Ridge and the Lasso {#ch13-penalty}\n\n### Flexibility can follow signal or noise\n\nA small constructed experiment lets us see what an empirical dataset hides: the mean that generates the observations. Generate 40 training outcomes around\n\n$$Y=2+1.5x-2x^2+\\varepsilon, \\qquad \\varepsilon\\sim N(0,0.6^2),$$\n\nat evenly spaced values of $x$ from $-1$ to 1. The errors are independent. Before examining any new outcomes, declare three candidate rules: a straight line, a quadratic, and a degree-12 polynomial. The quadratic can represent this particular mean exactly; the other candidates help distinguish missing its curvature from fitting its noise.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(y ~ x, dat)\nm2 <- lm(y ~ poly(x, 2), dat)\nm12 <- lm(y ~ poly(x, 12), dat)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same observations support curves with very different flexibility.](chapter_13_files/figure-html/fig-ch13-flex-curves-1.png){#fig-ch13-flex-curves fig-pos='!ht' fig-alt='Three panels share forty generated training observations and a dashed quadratic true mean. The straight line misses the curvature, the quadratic follows it, and the degree-12 polynomial follows additional fluctuations in the training sample.' width=643.2}\n:::\n:::\n\n\n**Predict and explain.** The degree-12 curve fits these training observations most closely. Which of its additional bends would you expect to persist when we generate new outcomes from the dashed mean? The straight line leaves systematic curvature unexplained. The quadratic follows the mean with some estimation error. The more flexible curve also follows some fluctuations that belong to this sample.\n\nNow generate 10,000 independent fresh cases from the same relationship, with $x$ uniformly distributed from $-1$ to 1 and the same noise SD. The fitted coefficients stay fixed. The training RMSEs are 0.7926, 0.4991 and 0.4280; the fresh-case values are 0.8641, 0.6136 and 0.6713. The gain from fitting the quadratic persists, while the gain from its degree-12 competitor reverses on these fresh cases.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(mean(resid(m2)^2))\nsqrt(mean((fresh$y - predict(m2, fresh))^2))\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Closer training fit need not mean better prediction of fresh outcomes.](chapter_13_files/figure-html/fig-ch13-flex-errors-1.png){#fig-ch13-flex-errors fig-pos='!ht' fig-alt='Training RMSE falls from 0.7926 to 0.4991 to 0.4280 as polynomial degree rises from one to two to twelve. Fresh-case RMSE is 0.8641, 0.6136 and 0.6713: the quadratic has the smallest fresh error in this experiment.' width=643.2}\n:::\n:::\n\n\nThis controlled illustration holds the training observations, outcome mechanism and assessment distribution fixed while changing the fitted rule. It does not establish that a moderately flexible model always wins. A different mean, noise level or training sample can change the comparison. The fresh errors describe these three fits conditional on this training sample, not variation across newly collected training samples. Once used to guide further choices, these fresh outcomes would become development information rather than an untouched final test. Appendix A separates approximation bias, training-sample variation and irreducible outcome noise.\n\nReturn to the student records, where the mean is unknown.\n\nAllowing all pairwise products of the twelve candidate fields produces 78 columns. One is identically zero: no MS student in these development rows receives school support. Keeping the remaining 77 columns on 297 rows is a much more flexible rule than the original additive fit. The factor dictionary and product terms are prespecified. Any empirically learned removal or scaling step must be learned within training data and carried into assessment unchanged.\n\nUnpenalized OLS now achieves apparent RMSE 3.5244 and in-sample $R^2=.4056$, but its held-out RMSE rises to 5.8848. Better reproduction of these outcomes accompanies worse prediction of withheld outcomes. The model has used its many columns to fit variations that do not recur reliably.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Adding many columns improves apparent fit while damaging held-out prediction in this example.](chapter_13_files/figure-html/fig-ch13-optimism-1.png){#fig-ch13-optimism fig-pos='!ht' fig-alt='Three horizontal segments compare apparent and held-out RMSE. The 77-column rule has the lowest apparent error and the highest held-out error.' width=604.8}\n:::\n:::\n\n\n**Regularization** restricts coefficient magnitude to make the fitted rule less sensitive to the particular sample. It accepts bias in exchange for a possible variance reduction. Biased estimation is not automatically disqualified by an inferential aim either: the relevant issue is the target and the validity of the uncertainty procedure. Here the criterion is held-out predictive loss.\n\n### Two penalties, one family\n\nWrite $\\mathbf x_i$ for the column vector of non-intercept predictor values for case $i$, and $\\boldsymbol\\beta$ for their coefficient vector. Each element corresponds to one predictor column of the design matrix; the intercept is written separately as $\\beta_0$. With an unpenalized intercept, ridge uses a squared-magnitude penalty,\n\n$$\n(\\widehat\\beta_0,\\widehat{\\boldsymbol\\beta})_{\\mathrm{ridge}}\n=\\arg\\min_{\\beta_0,\\boldsymbol\\beta}\\Big\\{\\sum_i(y_i-\\beta_0-\\mathbf x_i{}^{\\mathsf T}\\boldsymbol\\beta)^2+\\lambda\\sum_j\\beta_j^2\\Big\\},\n$$\n\nwhile the lasso replaces $\\sum_j\\beta_j^2$ by $\\sum_j|\\beta_j|$ [@hoerl1970; @tibshirani1996]. The squared penalty generally shrinks without selecting exact zeros. The absolute-value penalty has a corner at zero and can set coefficients exactly to zero. A zero is a feature of the penalized solution, not evidence of an absent relationship.\n\nThe elastic net combines the penalties [@zou2005]. For Gaussian outcomes, `glmnet()` minimizes\n\n$$\n\\frac1{2n}\\sum_i(y_i-\\beta_0-\\mathbf x_i{}^{\\mathsf T}\\boldsymbol\\beta)^2\n+\\lambda\\left[\\frac{1-\\alpha}{2}\\sum_j\\beta_j^2+\\alpha\\sum_j|\\beta_j|\\right].\n$$\n\nHere $\\alpha=0$ is ridge, $\\alpha=1$ is lasso, and intermediate values mix the penalties. The numerical meaning of $\\lambda$ depends on the objective's scaling, so penalties from differently scaled formulas cannot be compared directly. The intercept remains unpenalized.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nridge <- glmnet::glmnet(X, y, alpha = 0)\nlasso <- glmnet::glmnet(X, y, alpha = 1)\n```\n:::\n\n\nThe penalty compares coefficient magnitudes, so predictor units matter. `glmnet()` estimates column standardization within each fit and returns coefficients on their original scales. Each fold's fit sees only its training rows. Penalized estimates and selected sets also do not inherit ordinary OLS coefficient SEs or $p$-values. Appendix A connects shrinkage to the bias–variance decomposition of squared prediction error.\n\n### Choose a penalty using held-out loss\n\nEach training fold fits a common grid of 80 penalties from 500 down to 0.005. Its assessment rows evaluate the entire path. Averaging each grid position's fold losses gives a tuning curve. The smallest observed mean loss selects $\\lambda_{\\min}$. The **one-standard-error rule** instead selects the largest penalty satisfying\n\n$$\n\\widehat{\\mathrm{CV}}(\\lambda)\\le\\widehat{\\mathrm{CV}}(\\lambda_{\\min})+\n\\widehat{SE}(\\lambda_{\\min}).\n$$\n\nThe hand calculation uses equal-fold mean MSE and the SD of fold MSEs divided by $\\sqrt{k}$. Because folds overlap, this is a conventional preference for a more penalized model, not a confidence-bound guarantee about population risk. In particular, an observed cost in CV error is not a known cost in true future performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncv <- glmnet::cv.glmnet(X, y, alpha = 1, foldid = fold)\nc(cv$lambda.min, cv$lambda.1se)\n```\n:::\n\n\n| Penalty family | $\\alpha$ | $\\lambda_{\\min}$ | CV RMSE | Nonzero | $\\lambda_{1SE}$ | CV RMSE | Nonzero |\n|:--|--:|--:|--:|--:|--:|--:|--:|\n| Ridge | 0 | 7.3034 | 4.3087 | 77 | 373.5835 | 4.5298 | 77 |\n| Elastic net | .5 | 0.4581 | 4.3110 | 15 | 2.6332 | 4.5206 | 3 |\n| Lasso | 1 | 0.2558 | 4.3082 | 14 | 1.2707 | 4.4963 | 1 |\n\n: Cross-validated tuning of three penalty families on the 77-column early-warning design matrix, using the shared ten folds. {#tbl-ch13-tuning tbl-colwidths=\"[20,10,14,12,10,14,12,8]\"}\n\nThe package's default mean weights folds by their sizes, unlike the equal-fold hand summary in the table. With the same grid and fold assignment, it selects the same minimum and 1SE penalties here; this agreement does not make its metric convention identical. Always check both the partition and the averaging rule when reproducing a result.\n\nThe three minimized RMSEs span 0.0028 grade points. We declare a practical tolerance of 0.0662, twice the 0.0331 resplit SD of the twelve-variable rule, for this teaching comparison. This is a preference for simplicity informed by partition sensitivity, not a confidence interval for differences between candidate risks. Under that rule all three penalties and the twelve-variable OLS fit at 4.3727 remain candidates. Penalization has rescued the 77-column fit; the tiny ordering of penalty families supplies little practical reason to favour one.\n\nAt the lasso's 1SE penalty only prior failures remains nonzero, with coefficient $-0.4831$ and intercept 10.4472. The observed RMSE rises by 0.1881, from 4.3082 to 4.4963. That is the visible price of a much simpler fitted rule on these folds.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Cross-validation curves for ridge, elastic net, and lasso on the early-warning design matrix. The shaded band is one standard error around the lasso curve; the vertical lines mark the lasso minimizing and one-standard-error penalties.](chapter_13_files/figure-html/fig-ch13-tuning-1.png){#fig-ch13-tuning fig-alt='All three curves are U-shaped in the log penalty. Cross-validated RMSE falls from about 5.16 for ridge and 4.96 for lasso at the smallest penalties to a shallow common minimum near 4.31, then rises to between 4.54 and 4.59 at the largest penalties. The lasso minimum sits at a log penalty near minus 1.36 and its one-standard-error penalty near plus 0.24.' width=624}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Coefficient paths for ridge and lasso over the penalty grid, per one sample SD of each predictor. Each line is one of the 77 design columns.](chapter_13_files/figure-html/fig-ch13-path-1.png){#fig-ch13-path fig-alt='In the ridge panel all 77 lines shrink smoothly and together toward zero as the log penalty increases, and none reaches zero within the plotted range. In the lasso panel lines drop to exactly zero one after another, so that only a handful remain nonzero by a log penalty near zero.' width=652.8}\n:::\n:::\n\n\n### Selection is not an importance ranking\n\nChanging only the folds can change the selected set. Fifty new fold assignments (seed 4411) select between 7 and 26 columns at $\\lambda_{\\min}$, with median 24. Twenty-eight columns appear at least once; only five appear every time. Correlated columns can substitute for one another, and weak signals move around a selection boundary.\n\nA lasso coefficient therefore describes the fitted rule under its tuning choices. It does not establish a causal effect, a stable scientific ranking or a variable's irrelevance when its coefficient is zero. If variable stability matters to the research question, report it explicitly. Ridge avoids a variable-selection claim but does not turn prediction into causal explanation.\n\n## Classification Performance {#ch13-classification}\n\n### The same fit, read as a prediction\n\nA logistic model estimates probabilities by maximum likelihood, as developed in Chapter 11. Here the question concerns their performance on new students. We fit the early and later predictor sets within the same development folds and preserve their out-of-fold probabilities. The tutoring action remains separate from the probability until costs are stated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- glm(risk ~ ., data = train, family = binomial())\np <- predict(m, newdata = test, type = \"response\")\n```\n:::\n\n\nThe response `risk` is 1 when the final grade is below 10; the training frame here contains that response and the declared predictor set. Fitting a probability model is the same operation as before. Keeping its assessment outcomes outside the fit changes the evidence supplied by the reported scores.\n\n### Score probabilities before choosing labels\n\nFor observed events $y_i\\in\\{0,1\\}$ and held-out probabilities $\\widehat p_i$, two proper scores are\n\n$$\n\\mathrm{LogLoss}=-\\frac1n\\sum_i\\{y_i\\log\\widehat p_i+(1-y_i)\\log(1-\\widehat p_i)\\},\n\\qquad\n\\mathrm{Brier}=\\frac1n\\sum_i(\\widehat p_i-y_i)^2.\n$$\n\nBoth are minimized in expectation by the true probability, so they reward an honest expression of uncertainty [@brier1950]. Both increase when a prediction is confidently wrong. If an event occurs, probabilities .8 and .1 give Brier losses .04 and .81 and log losses 0.2231 and 2.3026. A confident error is especially expensive under log loss.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ny <- 1; p <- c(.8, .1)\n-log(p)\n(p - y)^2\n```\n:::\n\n\n**Discrimination** concerns ranking. The AUC is the probability that a randomly chosen event receives a higher prediction than a non-event, with half credit for ties. A strictly increasing transformation of probabilities preserves their ranking and AUC, even if their numerical values become poorly calibrated. AUC .5 is chance ranking; 1 is perfect separation of these assessed cases.\n\n**Calibration** concerns the probability values themselves: among cases predicted near $p$, does the event occur about $p$ of the time? A model that gives everyone the correct base rate may be calibrated while offering no ranking information. Good ranking alone also supplies no assurance about calibration.\n\n| Quantity | Constant rate | Early-warning set | Later predictor set |\n|:--|--:|--:|--:|\n| Log loss, mean over folds | 0.6373 | 0.6087 | 0.2511 |\n| Log loss, SD over folds | --- | 0.1051 | --- |\n| Brier score, mean over folds | .2225 | .2044 | .0724 |\n| Brier score, SD over folds | --- | .0407 | --- |\n| AUC, mean over folds | .5000 | .6751 | .9671 |\n| AUC, SD over folds | --- | .0877 | --- |\n| AUC, worst fold | --- | .5249 | .9400 |\n| AUC, best fold | --- | .8100 | 1.0000 |\n\n: Cross-validated binary metrics on the shared ten development folds; the constant rate is refitted within each analysis fold. {#tbl-ch13-binary tbl-colwidths=\"[40,20,20,20]\"}\n\nThe reference gives every assessment case its training fold's event rate. The early rule improves mean log loss by 4.4884%, with AUC .6751. Individual fold AUCs range from .5249 to .8100: on approximately 30 assessed students the estimate can change greatly. The pooled out-of-fold AUC is .6731, a different summary from the mean fold AUC. The later rule's .9671 ranking is much stronger, but unavailable to a September decision; its strong association with final grades is not an algebraic circularity.\n\nTo inspect calibration, divide the early out-of-fold probabilities into five approximately equal-sized bins. Within each bin compare the mean prediction with the observed event rate.\n\n| Bin | Records | Mean predicted | Observed rate | Difference |\n|:--|--:|--:|--:|--:|\n| 1 (lowest) | 60 | .1514 | .1667 | .0152 |\n| 2 | 59 | .2128 | .2373 | .0244 |\n| 3 | 59 | .2693 | .2712 | .0018 |\n| 4 | 59 | .3583 | .4068 | .0485 |\n| 5 (highest) | 60 | .6495 | .5667 | $-.0829$ |\n\n: Five equal-sized bins of the out-of-fold early-warning probabilities, development rows. {#tbl-ch13-calibration tbl-colwidths=\"[16,14,24,24,22]\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Calibration and discrimination of the out-of-fold development predictions. The left panel bins the early-warning predictions into five equal-sized groups and plots the observed at-risk rate against the mean predicted probability. The right panel gives receiver operating characteristic curves for both predictor sets. The diagonal is perfect calibration on the left and chance ranking on the right.](chapter_13_files/figure-html/fig-ch13-calibration-1.png){#fig-ch13-calibration fig-alt='In the calibration panel five points run just above the diagonal for the four lower bins, predicting about .15, .21, .27, and .36 against observed rates near .17, .24, .27, and .41, while the highest bin predicts about .65 and observes about .57, falling below the diagonal. In the discrimination panel the end-of-year curve rises almost immediately to a true positive rate near 1 and hugs the top-left corner, while the early-warning curve lies much closer to the chance diagonal, reaching a true positive rate of about .6 at a false positive rate of about .3.' width=633.6}\n:::\n:::\n\n\nThe top bin's predicted rate .6495 exceeds its observed rate .5667 by .0829. This is a diagnostic discrepancy, not proof of systematic overprediction. A rate near .6 estimated from about 60 students already has sampling SE around .06, before considering the shared fitted models. The lower bins are close to their diagonals, but these records do not demonstrate exact calibration either. A new, larger evaluation could clarify whether the upper-range gap recurs.\n\n### A threshold belongs to the decision\n\nSuppose missing an at-risk student costs $c_{\\mathrm{miss}}$, and offering tutoring to a student who would pass costs $c_{\\mathrm{tutor}}$. With correctly calibrated risk $p$, flagging has expected cost $(1-p)c_{\\mathrm{tutor}}$ and not flagging has cost $pc_{\\mathrm{miss}}$. Choose the action with lower expected cost, which gives\n\n$$\np\\ge\\frac{c_{\\mathrm{tutor}}}{c_{\\mathrm{tutor}}+c_{\\mathrm{miss}}}.\n$$ {#eq-ch13-threshold}\n\nAt a 2-to-1 cost ratio, the theoretical threshold is $1/3=.3333$; at 8 to 1 it is $1/9=.1111$. These expressions assume the stated cost model and meaningful probabilities. Capacity constraints or other costs would define another decision problem.\n\nWe also examine a grid of thresholds on the development predictions. Its empirical minimum is .3 under 2 to 1, with average cost 0.4680, 41.4141% flagged, recall .6122 and precision .4878. Under 8 to 1 its minimum is .1, flagging 99.6633% with recall 1 and cost 0.6667, almost the 0.67 cost of flagging everyone. The grid optima differ from the theoretical thresholds because they use a finite sample and a coarse set of candidates.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Average cost per student against the flagging threshold, for two cost ratios, computed from out-of-fold development predictions. Points mark the minimizing threshold on each curve.](chapter_13_files/figure-html/fig-ch13-cost-1.png){#fig-ch13-cost fig-alt='The 2-to-1 curve falls from about .67 at a threshold of .05 to a minimum of about .47 at a threshold of .3, then rises back to about .66 at .95. The 8-to-1 curve is lowest at about .67 for thresholds .05 and .10 and then rises steadily to about 2.62 at a threshold of .95.' width=595.2}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflag <- p >= .30\nmean(2 * (y == 1 & !flag) + (y == 0 & flag))\n```\n:::\n\n\nThe probabilities did not change between the cost scenarios; the action did. Under the higher cost of missed risk, this model adds almost nothing to offering support broadly. Reporting AUC alone would conceal that decision consequence. Selecting a threshold from development outcomes is another fitting choice; freeze it before the protected test evaluation.\n\n## Dataset Shift and Transport {#ch13-shift}\n\n### What resampling assumes\n\nInternal validation concerns new records drawn like the source records under the declared unit and split. It cannot by itself establish performance in a different district, year or measurement system. **Dataset shift** names a difference between source and deployment distributions.\n\nThree useful special cases separate where the change occurs. Under covariate shift, predictor distributions change while the conditional outcome distribution given predictors stays fixed. Under label shift, outcome frequencies change while predictor distributions conditional on outcome stay fixed. Under concept shift, the conditional outcome relationship itself changes. Real settings may combine these changes; observing a changed event rate alone does not establish label shift.\n\nThe remedies concern design and evidence: evaluate in the proposed setting, inspect measurement and selection changes, monitor performance and define when to update the rule. A larger model fitted to the same source records supplies no automatic repair [@shadish2002].\n\n### A small transfer probe, honestly read\n\nUsing only development rows, fit to 263 GP students and assess the 34 MS students. Remove school from the formula because its training value is constant. This probes another-school prediction while preserving the final test's independence. Compare the predictor distributions before reading performance.\n\n| Quantity | Gabriel Pereira (263) | Mousinho da Silveira (34) |\n|:--|--:|--:|\n| Mean age | 16.4867 | 18.0294 |\n| Mean travel time | 1.3726 | 2 |\n| Mean prior failures | 0.3194 | 0.4412 |\n| Proportion urban home | .8365 | .4412 |\n| Proportion with internet | .8517 | .6765 |\n| SD of the final grade | 4.6899 | 3.6142 |\n| Held-out RMSE | 4.3907 (ten-fold within GP) | 3.9748 (transfer) |\n| Out-of-sample $R^2$ | .1225 | $-.2053$ |\n| AUC for the at-risk probability | .6714 (ten-fold within GP) | .6813 (transfer) |\n\n: A development-set transportability probe; the two schools differ in their predictor distributions. {#tbl-ch13-shift tbl-colwidths=\"[36,32,32]\"}\n\nThe transfer RMSE of 3.9748 is lower than the within-GP value of 4.3907. Yet the transfer $R^2_{\\mathrm{out}}$ is negative: the GP-fitted rule predicts MS outcomes worse than the GP training mean. These statements are compatible. Absolute error depends partly on how variable the assessment outcomes are; MS grades have SD 3.6142 against GP's 4.6899. Relative performance also depends on the chosen reference. The denominator here is the error of the GP mean, not simply the variance around the MS mean.\n\nThe transfer AUC .6813 is close to the within-GP .6714, but 34 students give little precision. A percentile bootstrap over MS assessment rows (seed 717, 2,000 resamples) gives RMSE interval [3.0921,4.8715] and AUC interval [.4545,.8735]. These intervals condition on the fitted GP rule; they describe variation in the small assessment sample, not all variation in fitting another rule or transporting to another school.\n\nThe defensible conclusion is limited: the two schools have different observed predictor distributions, while the small transfer sample leaves a wide range of performance plausible. It does not demonstrate that the model transports well, nor isolate which form of shift caused any performance difference. One school is one site; resampling its students creates no new sites.\n\n## From Analysis to a Defensible Claim {#ch13-claim}\n\n### Freeze the choice before final evaluation\n\nThe continuous-outcome selection rule is now fully specified: find the lowest development equal-fold CV RMSE; retain candidates within the declared practical tolerance 0.0662; choose the simplest of those. The candidate values are lasso 4.3082, ridge 4.3087, elastic net 4.311 and twelve-variable OLS 4.3727. Their span is 0.0645, so this preference selects twelve-variable OLS. The tolerance is a teaching decision informed by one rule's resplit sensitivity, not a claim that all four population risks are equal.\n\nFor the binary target, retain the early logistic model and the development-selected threshold .3 under 2-to-1 costs. The later predictor set is outside the proposed deployment specification. Refit the selected grade and probability rules to all 297 development rows, then evaluate the frozen choices on the 98 protected test rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- lm(early, data = dev)\np <- predict(m, newdata = tst)\nc(RMSE = sqrt(mean((tst$grade - p)^2)),\n  MAE = mean(abs(tst$grade - p)))\n```\n:::\n\n\n| Quantity | Test set (98) | Baseline rule | Development estimate |\n|:--|--:|--:|--:|\n| RMSE, final grade | 4.3550 | 4.5957 | 4.3727 |\n| MAE, final grade | 3.4264 | 3.4999 | 3.2944 |\n| Out-of-sample $R^2$, final grade | .1020 | 0 | .0847 |\n| Log loss, at-risk probability | 0.5574 | 0.6317 | 0.6087 |\n| Brier score, at-risk probability | .1889 | .2199 | .2044 |\n| AUC, at-risk probability | .7273 | .5000 | .6751 |\n| Average decision cost per student, 2 to 1 | 0.4694 | 0.6531 | 0.4680 |\n\n: The single final evaluation, beside the constant-predictor baseline and the development cross-validated estimate. {#tbl-ch13-final tbl-colwidths=\"[40,20,20,20]\"}\n\nThe grade rule improves RMSE by 5.2378% over the development-mean reference, yet its mean absolute error is 3.4264 points on the 0-to-20 scale. MAE is an average absolute error, not a guarantee that every student is predicted within that distance. The logistic rule has AUC .7273 and Brier score .1889. These are modest predictive results that still deserve a complete report.\n\nAt threshold .3, the decision table is:\n\n| Decision | Below standard | At or above standard | Total |\n|:--|--:|--:|--:|\n| Offer tutoring | 20 | 22 | 42 |\n| Do not offer | 12 | 44 | 56 |\n| Total | 32 | 66 | 98 |\n\n: Protected-test decisions under the frozen threshold and cost ratio. {#tbl-ch13-decisions}\n\nThe flagged proportion is .4286, recall is $20/32=.625$ and precision is $20/42=.4762$. The average declared cost is $(2\\times12+22)/98=0.4694$, against 0.6531 for flagging nobody and 0.6735 for flagging everybody. More than half of those offered support would pass under the recorded outcome, and twelve at-risk students are missed. Whether this is useful depends on the actual consequences and alternatives.\n\nA protected test has value because its results did not guide the choices it evaluates. Recomputing the same frozen analysis does not destroy that independence. Trying another penalty, threshold or predictor set because the test result disappoints does: the test becomes development information, and a new protected evaluation is needed for the revised procedure [@simmons2011; @steegen2016].\n\n### Predictions and uncertainty on a meaningful scale\n\nPredicted test grades span 1.3815 to 12.3017; predicted risks span .1217 to .9353. The risk range is broad, but its endpoints alone establish neither discrimination nor calibration. Those properties require observed outcomes and the comparisons already developed.\n\nTwo uncertainties remain distinct. An individual grade prediction has uncertainty because students vary around a conditional mean; a predictive interval is the relevant quantity. A reported performance estimate has uncertainty because its training and assessment records could differ. Our repeated partitions describe only sensitivity to folds, and the transfer bootstrap only assessment variation given one fitted rule. Neither establishes what happens after an unobserved change of district, year or recording system.\n\n### A model card and a bounded claim\n\nA short model card records the conditions under which a result can be used. It is a description of the task, evidence and limits, not an aggregate quality score [@nationalAcademies2019; @peng2011; @apa2020].\n\n| Field | Entry |\n|:--|:--|\n| Purpose | Rank students by end-of-year mathematics risk at the start of the year, to allocate tutoring |\n| Targets | `final_grade` on 0--20; `at_risk`, the final grade below 10 |\n| Deployment moment and horizon | First weeks of the school year; end of the same year |\n| Development data | 297 students from the curated UCI subset [@cortez2008data]; 98 held back and opened once |\n| Admissible predictors | Twelve candidate early variables; source documentation does not establish intake availability for every field. Period grades and full-year absences excluded by design |\n| Fitting procedure | Least squares on the twelve candidate early variables, selected by the declared rule from a field of four candidates within 0.0645; logistic regression for the probability |\n| Test performance | RMSE 4.355; MAE 3.4264; out-of-sample $R^2$ .102; log loss 0.5574; Brier .1889; AUC .7273 |\n| Baseline | Constant predictor: RMSE 4.5957; log loss 0.6317 |\n| Calibration | Top-bin gap $-.0829$ is a descriptive diagnostic, too imprecise to establish systematic miscalibration |\n| Decision rule | Flag when the predicted risk is at least .3, selected on the development threshold grid under a 2-to-1 cost ratio; the calibrated-probability formula gives .3333 |\n| Known limitations | Weak discrimination; unstable selected set in the penalized alternative; transportability probed in 34 students only; no drift monitoring |\n| Prohibited uses | Any causal claim; any high-stakes individual decision; any use as evidence that a predictor matters |\n| Resampling | Ten folds; 20 repeated cross-validations; 2,000 bootstrap resamples; 50 selection refolds |\n| Reproducibility | Seeds 1305, 9702, 2026, 5150, 4411, 3311, 717; package and R versions recorded at render |\n\n: A model card for the early-warning system. {#tbl-ch13-card tbl-colwidths=\"[24,76]\"}\n\n::: {.callout-tip title=\"A bounded predictive claim\"}\nUnder a hypothetical early-prediction specification, a twelve-variable regression fitted to 297 students from two Portuguese schools predicted final grades in 98 protected test records with RMSE 4.355 and MAE 3.4264, compared with reference RMSE 4.5957. A logistic rule for finishing below 10 had log loss 0.5574, Brier score .1889 and AUC .7273. The development-selected .3 threshold under 2-to-1 error costs gave average test cost 0.4694, versus 0.6531 for offering support to nobody. These records support a modest same-source prediction result. They do not establish that every candidate field was available in September, that predictions transport to another district, or that changing a predictor would improve achievement.\n:::\n\nFor another predictive study, follow the same reasoning in its own setting: identify the target, deployment moment and eligible inputs; identify which outcomes were withheld from each fitting choice; read each metric against its reference and uncertainty; examine changes of population and measurement; then compare the resulting decision with realistic alternatives. These questions expose consequential weaknesses without treating a correctly run algorithm as a complete research argument.\n\n## Reading Bridge\n\nPrediction evaluates a fitted rule on outcomes it did not use. A learning-rule comparison also names the procedure and training size. Apparent fit, held-out loss and partition sensitivity therefore describe different quantities. Every data-adaptive step belongs within the appropriate fitting boundary; a regularization penalty is another choice that needs evaluation. Probabilities need calibration and discrimination before a threshold translates them into decisions. None of these operations supplies evidence for a deployment setting the study never assessed.\n\nChapter 14 asks the complementary question: even when the calculation is correct, does the study's design and measurement support the claim being made? A predictive success is one kind of evidence within that larger research argument.\n\n### Key terms {.unnumbered}\n\n| Term and common alternatives | Meaning or essential distinction |\n|:--|:--|\n| Generalization error (prediction error; risk) | Expected loss on a new unit from the stated deployment distribution. It can be defined for one fitted model conditional on its training data, or averaged over training samples for a learning rule at a stated training size; held-out observations estimate the chosen target. |\n| Deployment moment (prediction time) | The point at which a prediction must be produced, which decides whether a predictor is available. A variable recorded later may improve measured performance but cannot be used for that earlier prediction task. |\n| Apparent error (training error; resubstitution error) | Loss on the records used to fit the rule. Using those outcomes in fitting generally makes this loss optimistic for new-case performance; greater fitting flexibility can increase that optimism, without guaranteeing an ordering in every sample or for every loss. |\n| Root mean squared error (RMSE) | The square root of the mean squared prediction error, in outcome units. It penalizes a large error far more than MAE does, so the choice between them states which mistakes matter. |\n| Out-of-sample $R^2$ | One minus the held-out squared error divided by the held-out squared error of a named constant reference fitted in the same analysis rows. It can be negative and is not the in-sample $R^2$ of Chapter 7. |\n| Data leakage (information leakage) | Using information unavailable at the deployment moment, or letting held-out records influence a training or selection step used to predict them. It can make performance estimates optimistic; there is no general proportional rule for the size of that optimism. |\n| Development and test split (holdout set) | A partition in which fitting, screening and tuning use the development records, while test outcomes remain protected until the rule is fixed. Adapting the rule after seeing test results uses the test set for development; repeating an unchanged calculation does not itself do so. |\n| Penalized regression (shrinkage; ridge; lasso; elastic net) | Fitting that adds a coefficient penalty to the loss, trading bias against variance. Ridge's squared penalty generally shrinks coefficients without selecting exact zeros; the lasso's absolute-value penalty can set coefficients to zero, and elastic net combines the penalties. |\n| Tuning parameter (penalty; $\\lambda$) | A quantity that indexes a family of fits and is chosen from data the fit did not see. Choosing it is itself a data-dependent step and belongs inside the resample. |\n| One-standard-error rule | A convention choosing the largest penalty whose observed cross-validated loss is within the estimated standard error at the minimum. It prefers a simpler fit under that empirical tolerance; it does not bound the increase in true prediction error. |\n| Proper scoring rule (log loss; Brier score) | A score for a predicted probability that is minimized in expectation by the true probability, so that honest uncertainty is rewarded. Accuracy and a single confusion matrix are not proper scores. |\n| Calibration | Agreement between predicted probabilities and observed event rates among cases with similar predictions. It is invisible in a ranking measure such as AUC and is checked on held-out predictions. |\n| Discrimination (AUC; concordance) | The probability that a randomly chosen event case receives a higher score than a non-event case, with half credit for tied scores. It depends on ranking and does not establish calibration of the probabilities. |\n| Decision threshold (operating point) | The predicted probability above which an action is taken, determined by the ratio of the costs of the two errors and not by the model. Two decision-makers with different costs read the same probabilities and act differently. |\n| Dataset shift (covariate, label, and concept shift) | A difference between the distribution the rule was developed in and the distribution where it is used: in the predictors, in the outcome rate, or in the relationship itself. Resampling within one sample cannot detect it. |\n\n: Concepts introduced here. {#tbl-ch13-key-terms}\n\n### Further reading {.unnumbered}\n\nJames and colleagues [@james2021], Chapters 5 and 6, develop resampling and regularization through worked examples. Hastie, Tibshirani and Friedman [@hastie2009] give the mathematical detail and uncertainty cautions. The official `glmnet` introduction [@glmnet2025] specifies its objective, standardization and validation conventions. Shmueli [@shmueli2010] develops the separation of explanation and prediction, and Kaufman and colleagues [@kaufman2012] examine leakage. The UCI record [@cortez2008data] supplies the student data's provenance and licence.\n\n## Exercises {.unnumbered}\n\n<!-- prompt-id: CH13-E01 -->\n### Exercise 1: Apparent and held-out error (Foundational) {.unnumbered}\n\nTwo fixed\nlearning rules are compared on the same 98 occupation records. Fitted\nto all 98 records, the education-only rule has mean absolute error\n2.3668 and the full additive rule 1.4785. Under a shared balanced\nten-fold assignment, the pooled held-out mean absolute errors are 2.4031\nand 1.5412. (1) Give the optimism of each rule and say which is larger.\n(2) Explain in one sentence why the apparent errors are the smaller\nones. (3) The held-out difference is $-0.8619$. State what this number\ncompares, and name the training sizes the comparison actually concerns.\n(4) The (education-only, full) absolute errors are (3.4049, 0.7562)\nfor government administrators and (2.414, 5.196) for surveyors.\nPredict whether the fuller rule must improve every occupation when its\npooled MAE is smaller, and use these two cases to explain your answer.\n\n<!-- prompt-id: CH13-E02 -->\n### Exercise 2: Choose the loss, then the reference (Foundational) {.unnumbered}\n\nRule A makes held-out absolute errors of 1, 1, 1, 1 and 6 grade points\non five students; rule B makes errors of 2, 2, 2, 2 and 2. (1) Give the\nmean absolute error and the root mean squared error of each rule. (2)\nState which rule each loss prefers and what that disagreement says\nabout the two losses. (3) In a separate analysis a rule has\na case-pooled held-out RMSE of 4.3763 while a constant predictor fitted\ninside each analysis fold has 4.5884. Calculate the out-of-sample\n$R^2$. (4)\nExplain what a negative value of that quantity would mean, and why it\ncannot be read as the $R^2$ of a fitted regression.\n\n<!-- prompt-id: CH13-E03 -->\n### Exercise 3: Find the leak (Foundational) {.unnumbered}\n\nAn analyst reports a\ncross-validated RMSE of 4.1493 grade points for a model built as\nfollows: the 212 candidate columns are ranked by their absolute\ncorrelation with the outcome on all 297 development rows, the top 15\nare kept, and the resulting formula is then cross-validated over ten\nfolds. Moving the ranking step inside the loop, so that each fold\nscreens only its own analysis rows, gives 4.6786; a fold-specific\nconstant predictor gives 4.588. (1) Name the leak and say precisely\nwhich outcomes were used twice. (2) State which of the following belong\ninside the resample and which do not: ranking columns by their\ncorrelation with the outcome; deciding from the codebook that `school`\nis a factor; centring all development rows on their grand mean;\nchoosing a cutpoint for a continuous predictor by its association with\nthe outcome; converting a grade recorded in percent to a 0-to-20 scale.\n(3) Ten of the 15 screened columns were pure noise. Explain how that is\nconsistent with 4.1493 being the best-looking number in the set. (4)\nState what the analyst should report. Now suppose each pupil supplies\nthree subject records and the aim is prediction for a new pupil. Explain\nwhy moving the screening inside random row folds is still insufficient,\nand identify the unit that must be withheld.\n\n<!-- prompt-id: CH13-E04 -->\n### Exercise 4: Read a tuning table (Foundational) {.unnumbered}\n\nOn a 77-column\ndesign matrix with 297 rows, ten-fold cross-validation gives these\nminimized RMSE values: ridge 4.3087 at $\\lambda=7.3034$ with 77 nonzero\ncoefficients; elastic net 4.311 at 0.4581 with 15; lasso 4.3082 at\n0.2558 with 14. Twenty repeated ten-fold runs of a comparable rule on\nthe same rows have SD 0.0331. The analyst declares 0.0662 as a practical tolerance for preferring a simpler candidate; it is not an inferential equivalence margin. The lasso's one-standard-error penalty is\n1.2707, with RMSE 4.4963 and one nonzero coefficient. (1) Apply the declared tolerance to the three minima, and explain why it does not prove equal population performance. (2) Give the predictive cost of\nthe one-standard-error rule here and say what is bought with it. (3)\nIn a constructed example generated around a quadratic mean, a quadratic\nfit has training/fresh RMSE\n0.4991/0.6136 and a degree-12 curve has 0.428/0.6713 on the same training\nand fresh cases. Explain how the closer fit to training outcomes can\nlose on fresh outcomes, and why this does not show that simpler rules\nalways predict better. (4) Unpenalized least squares on the same matrix\nhas apparent RMSE 3.5244 and cross-validated RMSE 5.8848. Say in one\nsentence what the penalty recovered.\n\n<!-- prompt-id: CH13-E05 -->\n### Exercise 5: A threshold from declared costs (Integrative) {.unnumbered}\n\nA school\nwill offer tutoring to students whose predicted risk of finishing below\nthe passing standard is at least $t$. (1) Missing an at-risk student is\njudged twice as costly as tutoring one needlessly. Give the threshold\nthe cost ratio implies. (2) Repeat for a ratio of 4 to 1, and state in\none sentence what happens to the size of the tutoring list. (3) At a\nthreshold of .3 on 98 students the rule flags 20 students who are at\nrisk and 22 who are not, and misses 12 who are. Give the proportion\nflagged, the recall, the precision, and the average cost per student\nunder the 2-to-1 ratio. (4) Flagging everybody costs 0.6735 per student\nand flagging nobody costs 0.6531. State what the rule is worth here, and\nwhat would have to change for it to be worth nothing.\n\n<!-- prompt-id: CH13-E06 -->\n### Exercise 6: Critique a predictive claim (Integrative) {.unnumbered}\n\nA district\nreport states: \"Our early-warning model identifies at-risk students\nwith an AUC of .68 and is 87% accurate, so it is ready for use across\nthe region.\" The supporting analysis shows fold-level AUC values from\n.5249 to .8100; a cost analysis in which the recommended policy at an\n8-to-1 cost ratio flags 99.66% of students; an external evaluation in a\nsecond school with out-of-sample $R^2$ $-.2053$ and a bootstrap\ninterval for the transfer AUC of [.4545, .8735]; and a selected\ncoefficient set that changed from 7 to 26 columns across 50 fold\nassignments. (1) Name three elements the quoted sentence omits that a\npredictive claim requires. (2) Explain what the 87% figure silently\nassumes and what should be reported instead. (3) State what the\nexternal evaluation does and does not establish. (4) Rewrite the\nsentence as a bounded claim of at most three sentences.\n\n\n\n## Appendix A: Two useful derivations {.unnumbered}\n\n### Squared error, bias and variance {.unnumbered}\n\nAt a fixed predictor profile $x$, write a new outcome as $Y=f(x)+\\varepsilon$ with $E(\\varepsilon\\mid x)=0$ and variance $\\sigma^2$. Assume its new error is independent of the training sample. Add and subtract $E(\\widehat f(x))$ inside $Y-\\widehat f(x)$, square, and average over both training samples and the new error. The cross-products have expectation zero, leaving\n\n$$\nE\\big((Y-\\widehat f(x))^2\\mid x\\big)=\\sigma^2+\n\\big\\{E(\\widehat f(x))-f(x)\\big\\}^2+\\operatorname{Var}(\\widehat f(x)).\n$$\n\nThe terms are irreducible outcome variance, squared bias and variation of the fitted prediction across training samples. Shrinkage can increase bias while reducing variance enough to lower their sum. This explains why the 77-column fit can benefit from a penalty. It does not prove that greater flexibility always reduces bias or always increases variance in every finite-data comparison.\n\n### Deriving the action threshold {.unnumbered}\n\nFor a correctly calibrated event probability $p$, the expected costs are $(1-p)c_{\\mathrm{tutor}}$ for flagging and $pc_{\\mathrm{miss}}$ for not flagging. Subtracting gives\n\n$$\n(1-p)c_{\\mathrm{tutor}}-pc_{\\mathrm{miss}}\n=c_{\\mathrm{tutor}}-p(c_{\\mathrm{tutor}}+c_{\\mathrm{miss}}).\n$$\n\nFlagging is preferred when this difference is nonpositive, which yields @eq-ch13-threshold. A miscalibrated probability or incomplete cost model changes the decision's justification. An empirically chosen threshold also carries selection uncertainty even when its displayed cost is lowest.\n\n## Appendix B: Nested resampling and extended practice {.unnumbered}\n\nSection 3.1 explains how row, pupil, school and time assessment answer different deployment questions. One more boundary is needed when the evaluated object includes a tuning or selection procedure.\n\nNested resampling separates an inner choice among candidates from an outer assessment of that entire choice procedure. The same principle applies to imputation and screening. A held-out site or period may also differ in measurement or population, so a split is an evaluation design rather than a guarantee of generalizability. James and colleagues [@james2021] and the `tidymodels` documentation develop the implementation; Chapter 9 addresses clustered uncertainty and Chapter 14 the design interpretation.\n\n**Extended practice.** (1) Restate the district's question if each pupil supplies three subject records. Specify the held-out unit and which reported numbers need recomputation. (2) Design a two-year validation scheme for a service deployed next year. State what information each fitting and assessment stage may use, and why a random mix of both years answers a different question.\n\n## References {.unnumbered}\n\n",
    "supporting": [
      "chapter_13_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}