{
  "hash": "e91e904f92585ee4c4440f4d305eec41",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Description and Basic Inference with R\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\widowpenalty=10000\n          \\clubpenalty=10000\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{12\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nThis chapter uses R to connect observations, statistical summaries and\nuncertainty. We describe distributions and groups, then relationships,\nand use repeated samples to see how an estimator varies. Intervals and\ntests connect an estimate with its standard error and a reference\ndistribution. Short R examples sit beside the equations, figures and\ntables whose meaning they illustrate. The central question remains what\nthe records represent and what supports the interpretation of the result.\n:::\n\nThree students scored 50, 60 and 70 points. Their mean is\n$(50+60+70)/3=60$ points. R gives the same result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscores <- c(50, 60, 70)\nmean(scores)\n#> [1] 60\n```\n:::\n\n\nThe result describes the three recorded scores. Using it to estimate\nanother group's mean would add a target and an account of how these\nobservations inform that target. The calculation is simple; deciding\nwhat it answers still depends on the study.\n\n## Read and Prepare Observations {#sec-ch5-inspect}\n\n[]{#sec-ch5-start}\n[]{#ch05-data}\n\n### A calculation that can be checked\n\n**R** is the programming language and statistical computing platform\nused in this chapter. It performs calculations, fits statistical models\nand draws graphs [@rcore2025]. A saved R script records the commands\nbehind an answer so that the calculation can be checked and rerun.\n**RStudio** is an integrated development environment (IDE): a workspace\nthat brings together a code editor, the R Console, plots and Help.\nWe write and run commands in RStudio; R carries out the computations.\n\n**Quarto** is software for professional publication. It brings prose,\nequations, R code, computed results, tables, figures and references\ntogether in one source document, which can be rendered as an HTML page,\na typeset PDF, a Word document or a presentation [@quarto2026]. For\nexample, we can write a report in RStudio that explains the three quiz\nscores, asks R to calculate their mean, and uses Quarto to place the\nanswer beside its explanation. When the scores change, rendering the\ndocument again can update the calculation and the report together.\nThese three tools connect observations to a reported result. A\nreproducible computation can still answer the wrong question, so the\nrecords and their meaning come first.\n\n### A data frame is a table of cases and variables\n\nA **data frame** is a table whose columns can hold different types of\nvalues. The entry $x_{ij}$ is case $i$'s value on variable $j$;\ntext and category columns can sit beside numbers. Its layout should\nmake the observational unit clear. In the next table a row represents\none student; the columns give an identifier, a baseline score and a\nfollow-up score, and student B's follow-up score is unavailable. A row\ncan instead record one person on one occasion or under one condition,\nso count the represented units as well as the rows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsmall <- data.frame(student = c(\"A\", \"B\", \"C\"),\n  baseline = c(50, 60, 70), followup = c(55, NA, 78))\n```\n:::\n\n\n| Student | Baseline | Follow-up |\n|:--|--:|--:|\n| A | 50 | 55 |\n| B | 60 | NA |\n| C | 70 | 78 |\n\n: Three students, with one follow-up unavailable. {#tbl-ch05-records}\n\n`NA` marks an unavailable value, not an observed zero. The available\nfollow-up mean is $(55+78)/2=66.5$ points, a description of two\nrecorded scores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(small$followup, na.rm = TRUE)\n#> [1] 66.5\n```\n:::\n\n\nTreating B's missing score as zero would answer a different question\nwith an invented measurement. A change needs both measurements of the\nsame student, so only A and C contribute:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth <- complete.cases(small)\nmean(small$followup[both] - small$baseline[both])\n#> [1] 6.5\n```\n:::\n\n\nTheir changes, 5 and 8 points, average 6.5 points. Subtracting the two\nseparately available means happens to give $66.5-60=6.5$ as well,\nbut the baseline mean uses three students and the follow-up mean two.\nThe agreement is a coincidence of these numbers; Exercise 3 changes\none score and the two calculations part. The measurement definition\nand codebook must also support any decision to treat a recorded zero\nas an unavailable value.\n\n### The records behind a summary\n\nThe [airquality documentation](https://stat.ethz.ch/R-manual/R-patched/library/datasets/html/airquality.html)\ndescribes daily New York measurements from May to September 1973.\nA row is a day. `Ozone` is ozone in parts per billion (ppb), `Wind`\nwind speed in miles per hour, `Temp` maximum temperature in degrees\nFahrenheit, and `Solar.R` solar radiation in Langleys. `Month` and\n`Day` identify dates within that period. There are 153 days and six\nvariables, but ozone is recorded on only 116 days and missing on 37.\nThe available ozone values are:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair <- airquality\nozone <- na.omit(air$Ozone)\n```\n:::\n\n\nTheir mean describes 116 days. The percentage of days with an ozone\nmeasurement instead uses all 153 as its denominator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n100 * length(ozone) / nrow(air)\n#> [1] 75.81699346\n```\n:::\n\n\nThus $100(116/153)=75.817\\%$ of the days have an ozone measurement.\nEvery summary has a denominator, and naming it is part of the result.\nRestricting the records to July changes the cases: 26 recorded days\nhave mean ozone 59.1154 ppb. Converting Fahrenheit to Celsius instead\nkeeps the same 153 days and changes their units; the mean becomes\n25.4902 degrees Celsius. Naming month codes as categories changes\nhow their labels are read, without changing the observations. A\nrelationship needs both measurements: ozone and solar radiation\nare jointly recorded on 111 days, so their relationship describes\nthose 111 days.\n\nThe 153 days are a historical record for one city and period. Complete\nrecords define the cases of a calculation; they do not establish\nrandom sampling. Treating these records as evidence about other years,\nunrecorded days or all New York summer days adds assumptions about\nselection, time and measurement, which Section 4 makes explicit.\n\n## Describe Distributions and Groups {#sec-ch5-summaries}\n\n[]{#ch05-descriptions}\n\n### Shape, centre, and spread\n\nA distribution shows how the values are arranged. Before reducing the\n116 ozone measurements to numbers, look at their shape. A histogram\ngroups nearby values into intervals and counts the observations in each\ninterval; a boxplot compresses their location and spread.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(ozone, breaks = seq(0, 180, by = 20), xlab = \"Ozone (ppb)\", main = \"\")\nboxplot(ozone, horizontal = TRUE, xlab = \"Ozone (ppb)\")\n```\n\n::: {.cell-output-display}\n![Recorded ozone values on 116 days, displayed as a histogram and a boxplot.](chapter_05_files/figure-html/fig-ch05-ozone-1.png){#fig-ch05-ozone fig-alt='The histogram has a long right tail reaching 168 ppb. The horizontal boxplot places the median near the lower values and marks several high observations beyond its upper whisker.' width=595.2}\n:::\n:::\n\n\nThe histogram uses 20-ppb intervals. Changing their boundaries can\nreveal or conceal detail while the observations stay the same. Most days have lower values, with a long right tail reaching 168\nppb. The boxplot marks the median and a box between its hinges; each\nwhisker reaches the most distant value within 1.5 box lengths of its\nhinge. Points beyond the whiskers invite examination, and the display\nalone does not justify removing them.\n\nThe mean and median describe location; the variance, SD and IQR\ndescribe spread. For observations\n$x_1,\\ldots,x_n$,\n\n$$\n\\bar x=\\frac{1}{n}\\sum_{i=1}^{n}x_i,\\qquad\ns^2=\\frac{\\sum_{i=1}^{n}(x_i-\\bar x)^2}{n-1},\\qquad\ns=\\sqrt{s^2},\\qquad IQR=Q_3-Q_1.\n$$\n\nThe variance measures each value's deviation from the mean, squares the\ndeviations so that positive and negative ones cannot cancel, adds them\nand divides by $n-1$; the square root returns the SD to the original\nunits. For the three scores the deviations from 60 are $-10$, 0 and\n10, their squares sum to 200, and $s^2=200/2=100$ squared points, so\n$s=10$ points. The divisor $n-1$ reflects that deviations around a\nsample mean sum to zero, so once $n-1$ of them are known the last is\ndetermined; under independent sampling from a common distribution it\nalso makes $s^2$ unbiased for the process variance, a property that\nSection 4.4 shows by repetition. For ozone, one call returns the\nsummaries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(mean = mean(ozone), median = median(ozone), SD = sd(ozone),\n  IQR = IQR(ozone))\n#>        mean      median          SD         IQR \n#> 42.12931034 31.50000000 32.98788451 45.25000000\n```\n:::\n\n\nThe mean, 42.1293 ppb, exceeds the median, 31.5 ppb, as the long right\ntail leads us to expect. The SD, 32.9879 ppb, describes spread around\nthe mean; the quartiles 18.00 and 63.25 ppb give an IQR of 45.25 ppb for\nthe middle half of the ordered values; and the range is 1 to 168 ppb.\nEach summary keeps a different feature, which @tbl-ch05-score-sets\nshows with four invented sets of three scores.\n\n| Scores | Mean | Median | SD |\n|:--|--:|--:|--:|\n| 50, 60, 70 | 60 | 60 | 10.0000 |\n| 50, 60, 100 | 70 | 60 | 26.4575 |\n| 58, 60, 62 | 60 | 60 | 2.0000 |\n| 40, 60, 80 | 60 | 60 | 20.0000 |\n\n: What the mean, the median and the SD each keep. {#tbl-ch05-score-sets tbl-colwidths=\"[34,22,22,22]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore <- c(50, 60, 100)\nc(mean(score), median(score), sd(score))\n```\n:::\n\n\nRead the rows in pairs. Replacing 70 by 100 moves the mean from 60 to\n70 and raises the SD from 10 to 26.4575, while the median stays at 60,\nstill the middle ordered value: the median resists one extreme value,\nwhich does not make either centre universally preferable. The last two\nsets balance at the same centre and differ tenfold in spread, so a\nreport of equal means would conceal what distinguishes them. This is\nwhy a group comparison keeps counts, centres and spreads together.\n\nQuartiles also depend on a stated rule. R's default, `type = 7`, places\nthe quartile at position $h=1+(n-1)p$ among the ordered values and\ninterpolates between neighbours. Another familiar rule takes the\nmedians of the two halves. @tbl-ch05-quartile-rules applies both rules to the values 1, 3,\n3 and 5.\n\n| Rule | $Q_1$ | $Q_3$ | IQR |\n|:--|--:|--:|--:|\n| Medians of the two halves | 2.0 | 4.0 | 2 |\n| R's default, `type = 7` | 2.5 | 3.5 | 1 |\n\n: Two quartile rules applied to the same four values. {#tbl-ch05-quartile-rules tbl-colwidths=\"[52,16,16,16]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(c(1, 3, 3, 5), c(.25, .75))\n```\n:::\n\n\nThe observations are the same; the rules differ. Type 7 uses positions\n1.75 and 3.25, so each quartile moves part of the way between\nneighbouring values, and its IQR is half the other value. A\nreproducible report names the rule when it affects the answer, and a\nboxplot's hinges need not equal either rule's quartiles.\n\n### Group summaries and weighted means\n\nFor the ozone records, the month codes identify groups of days. A\n**factor** stores such categories with named levels in a stated order,\nand `tapply()` applies a function within each level:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nair_observed <- na.omit(air[c(\"Ozone\", \"Month\")])\nair_observed$month <- factor(air_observed$Month, labels = month.name[5:9])\ntapply(air_observed$Ozone, air_observed$month, mean)\n#>         May        June        July      August   September \n#> 23.61538462 29.44444444 59.11538462 59.96153846 31.44827586\n```\n:::\n\n\nA group mean needs its count and spread beside\nit, which @tbl-ch05-monthly supplies.\n\n\\Needspace{12\\baselineskip}\n\n| Month | Recorded days | Mean ozone | SD ozone |\n|:--|--:|--:|--:|\n| May | 26 | 23.6154 | 22.2244 |\n| June | 9 | 29.4444 | 18.2079 |\n| July | 26 | 59.1154 | 31.6358 |\n| August | 26 | 59.9615 | 39.6812 |\n| September | 29 | 31.4483 | 24.1418 |\n\n: Recorded ozone by month; means and SDs are in ppb. {#tbl-ch05-monthly tbl-colwidths=\"[28,24,24,24]\"}\n\nJune's mean describes only nine recorded days, and its count matters\nwhen we place it among the other monthly means.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Recorded ozone distributions by month; each box uses that month's available measurements.](chapter_05_files/figure-html/fig-ch05-months-1.png){#fig-ch05-months fig-alt='July and August have higher median ozone than May, June, and September, with different spreads and only nine observed days in June.' width=576}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(Ozone ~ month, data = air_observed)\n```\n:::\n\n\nThe boxes show the higher centres in July and August together with the\nspread within each month, which the monthly means alone cannot show.\nThese differences summarize the record; they do not by themselves\nisolate an effect of season from other changes over the period.\n\nThe **grand mean** over individual observations weights each group mean\nby its count:\n\n$$\n\\bar x=\\frac{\\sum_g n_g\\bar x_g}{\\sum_g n_g}.\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweighted.mean(c(29.4444, 59.1154), c(9, 26))\n```\n:::\n\n\nThe rule applied to the five monthly ozone\nmeans returns 42.1293 ppb, the mean of all 116 recorded days. For June\nand July alone, with 9 and 26 recorded days, the recorded-day mean is\n51.4857 ppb and the equal-month mean 44.2799 ppb. Neither is the\ncorrect one in general: the question decides whether days or months\nreceive equal weight.\n\n### Counts, proportions, and a binary indicator\n\nThe [mtcars documentation](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)\ndescribes 32 car-model records from the 1974 *Motor Trend* magazine,\ncovering 1973--1974 models. Each row is a car model. The variable `mpg`\ngives fuel economy in miles per US gallon, while `am` codes automatic\ntransmission as 0 and manual transmission as 1. Use 20 mpg as a\nteaching threshold, label the transmission categories, and form their\ntwo-way table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncars <- mtcars\ncars$transmission <- factor(cars$am, levels = c(0, 1),\n  labels = c(\"Automatic\", \"Manual\"))\ntab <- table(cars$transmission, cars$mpg >= 20)\ntab\n#>            \n#>             FALSE TRUE\n#>   Automatic    15    4\n#>   Manual        3   10\n100 * prop.table(tab, margin = 1)\n#>            \n#>                   FALSE        TRUE\n#>   Automatic 78.94736842 21.05263158\n#>   Manual    23.07692308 76.92307692\n```\n:::\n\n\nThe table counts 15 automatic models below the threshold and 4 at or\nabove it, against 3 and 10 manual models. `prop.table()` turns counts\ninto proportions; `margin = 1` makes each row its own denominator, and\nmultiplying by 100 gives percentages. One table answers several\nquestions, and each question has its own denominator\n(@tbl-ch05-denominators).\n\n\\Needspace{9\\baselineskip}\n\n| Question | Denominator | Percentage |\n|:--|:--|--:|\n| Automatic models meeting the threshold | 19 automatic models | 21.0526 |\n| Manual models meeting the threshold | 13 manual models | 76.9231 |\n| Threshold-meeting models that are manual | 14 threshold-meeting models | 71.4286 |\n\n: Three percentages from one table, each with its denominator. {#tbl-ch05-denominators tbl-colwidths=\"[46,34,20]\"}\n\nThe first two rows condition on transmission and differ by 55.8704\npercentage points. The third reverses the condition: among the 14\nmodels that meet the threshold, 71.4286% are manual. \"Meeting the\nthreshold among manual models\" and \"manual among threshold-meeting\nmodels\" answer different questions, and naming the denominator keeps\nthem apart. The percentages describe an association among the 32\nrecorded models, whose transmission groups also differ in weight and\nengine. Neither direction of conditioning identifies what changing a transmission would do.\n\nA binary indicator has one further property: its mean is the proportion\ncoded 1. Of the 32 models, 14 meet the threshold, so the indicator\n`cars$mpg >= 20` has mean $14/32=.4375$. The 0/1 `am` variable is such\nan indicator, and Section 3.3 uses it in a point-biserial correlation; Section 5.5\nuses a 0/1 indicator to describe interval coverage.\n\n### Transformations and the Normal model\n\nA linear transformation changes location and units predictably. If\n$y_i=a+bx_i$, the mean becomes $a+b\\bar x$, the variance $b^2s^2$ and\nthe SD $|b|s$. The Celsius conversion has $a=-32(5/9)$ and $b=5/9$, so\nthe mean temperature of 77.8824 and SD of 9.4653 degrees Fahrenheit\nbecome 25.4902 and 5.2585 degrees Celsius: subtracting the constant\nmoves the mean only, and the factor $5/9$ rescales both.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp <- (air$Temp - 32) * 5 / 9\nc(mean(temp), sd(temp))\n```\n:::\n\n\nA standardized value measures distance from the mean in SD units. For\nan ozone reading of 100 ppb,\n\n$$\nz_i=\\frac{x_i-\\bar x}{s},\\qquad\nz_{100\\text{ ppb}}=\\frac{100-42.1293}{32.9879}=1.7543.\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(100 - mean(ozone)) / sd(ozone)\n```\n:::\n\n\nStandardizing changes location and scale while preserving shape:\nright-skewed ozone stays right-skewed. This individual $z$ divides by\nthe observations' SD; Section 5's statistic for a mean divides by an\nSE instead. R names distribution functions by four prefixes:\n`d` gives a density height or a probability mass, `p` a cumulative\nprobability, `q` a quantile and `r` generated observations. Thus\n`pnorm()` is the Normal family's cumulative-probability function, and\n`lower.tail = FALSE` asks for the probability above the value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(100, mean = mean(ozone), sd = sd(ozone), lower.tail = FALSE)\n#> [1] 0.03968944406\n```\n:::\n\n\nA Normal model with the ozone mean and SD puts probability .0397 above\n100 ppb. @tbl-ch05-normal-check sets this and one more model\nprobability beside what the 116 recorded days show.\n\n\\Needspace{8\\baselineskip}\n\n| Event for one recorded day | Normal model | Observed |\n|:--|--:|--:|\n| Ozone of at least 100 ppb | .0397 | .0603 |\n| Ozone within one SD of the mean | .6827 | .7241 |\n\n: A Normal model with the ozone mean and SD, against the 116 recorded values. {#tbl-ch05-normal-check tbl-colwidths=\"[52,24,24]\"}\n\nSeven of the 116 days reach 100 ppb, a larger share than the model\ngives, and more days lie within one SD of the mean than the model\nexpects. The model misses the long right tail and the concentration of\nlow values. A function evaluates the model it is given; it does not\ncertify that the model describes the data, and the familiar\n68--95--99.7 rule belongs to the Normal model, not to every\nstandardized dataset.\n\nFor a separate, stipulated score model $X\\sim N(100,15^2)$, on the\nscale used by intelligence scores such as the WISC, a probability for a range is a difference of cumulative probabilities,\nand `qnorm()` reverses the question by returning the value at a stated\ncumulative probability:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(120, mean = 100, sd = 15) - pnorm(100, mean = 100, sd = 15)\n#> [1] 0.4087887803\nqnorm(c(.025, .975), mean = 100, sd = 15)\n#> [1]  70.60054023 129.39945977\n```\n:::\n\n\nThe probability of a score between 100 and 120 is .4088. The central\n95% of scores under the model lies between 70.6005 and 129.3995; these\nlimits describe individual scores under the model, not a confidence\ninterval for an unknown mean. The same functions give .5000 below 100 and\n.0038 above 140.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Probability is an area under a stipulated Normal density.](chapter_05_files/figure-html/fig-ch05-normal-area-1.png){#fig-ch05-normal-area fig-alt='The score range from 100 to 120 is shaded under a Normal curve with mean 100 and SD 15. Its area is .4088.' width=595.2}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dnorm(x, mean = 100, sd = 15), 40, 160)\n```\n:::\n\n\nThe curve's height is a density. Probability belongs to an area, such\nas the shaded region in @fig-ch05-normal-area, rather than to the height\nat one exact score.\n\n### A compact distribution catalogue in R {#ch05-distributions}\n\nThe binomial model shows how the four prefixes ask different questions\nof one process. $X\\sim\\operatorname{Binomial}(20,.3)$ counts successes\nin 20 independent trials with success probability .3:\n\n\\Needspace{12\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(d = dbinom(4, size = 20, prob = .3),\n  p = pbinom(4, size = 20, prob = .3),\n  q = qbinom(.95, size = 20, prob = .3))\n#>            d            p            q \n#> 0.1304209744 0.2375077789 9.0000000000\nset.seed(20517)\nrbinom(6, size = 20, prob = .3)\n#> [1] 6 8 6 3 5 6\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Four questions asked of one binomial model, 20 trials with success probability .3. (a) The mass at 4 (black bar) is what `dbinom` returns; the masses at 0 to 4 together (dark bars) are what `pbinom` returns; the triangles below the axis are the six counts from `rbinom`. (b) The cumulative probability first reaches .95 at 9, the value `qbinom` returns.](chapter_05_files/figure-html/fig-ch05-dpqr-1.png){#fig-ch05-dpqr fig-alt='Left panel: bars of binomial probability for 0 to 20 successes, highest near 6, with the bar at 4 in black, the bars at 0 to 3 dark grey, and six triangles below the axis at 3, 5, 6, 6, 6 and 8. Right panel: the cumulative probability as a step function, crossing the dashed .95 line at 9.' width=624}\n:::\n:::\n\n\n@fig-ch05-dpqr reads the output. The probability of exactly four\nsuccesses is .1304, one bar; the probability of at most four is .2375,\nthe sum of five bars. The .95 quantile is 9 because the cumulative\nprobability is .8867 at 8 and .9520 at 9: for a discrete model the\nquantile is the first count whose cumulative probability reaches the\nrequested level, which it need not attain exactly. The six generated\nvalues, 6, 8, 6, 3, 5 and 6, are counts from six separate sets of 20\ntrials; the first argument of `rbinom()` is the number of counts\ngenerated, whereas `size = 20` is the number of trials in each. The\nseed makes the draws reproducible; another seed changes the draws and\nleaves the model probabilities unchanged.\n\nThe lookup in @tbl-ch05-models gives the same vocabulary for other\nfamilies. Its support states the possible values, and the parameters\nspecify a member of each family.\n\n\\Needspace{16\\baselineskip}\n\n| Model | Object and parameters | Base-R family |\n|:--|:--|:--|\n| Bernoulli | One 0/1 response, probability $p$ of 1 | `binom`, with `size=1` |\n| Binomial | Success count in $m$ independent trials with common $p$ | `dbinom`, `pbinom`, `qbinom`, `rbinom` |\n| Categorical | One label among categories with stated probabilities | `sample()` with `prob`; a table of masses |\n| Poisson | Nonnegative count with model mean $\\lambda$ | `dpois`, `ppois`, `qpois`, `rpois` |\n| Normal | Continuous value with mean $\\mu$ and SD $\\sigma$ | `dnorm`, `pnorm`, `qnorm`, `rnorm` |\n| Lognormal | Positive value whose log is Normal; parameters on the log scale | `dlnorm`, `plnorm`, `qlnorm`, `rlnorm` |\n| Logistic | Continuous symmetric value with location $\\mu_L$ and positive scale $s_L$ | `dlogis`, `plogis`, `qlogis`, `rlogis` |\n| Student t | Symmetric reference distribution with specified df | `dt`, `pt`, `qt`, `rt` |\n\n: Distribution functions respect the model's support and parameters. {#tbl-ch05-models tbl-colwidths=\"[16,49,35]\"}\n\nLognormal `meanlog` and `sdlog` describe the logarithm, not the mean\nand SD of the positive values. Its density is right-skewed, whereas a\nt density is symmetric with tails heavier than the Normal density.\nThese contrasts reflect different kinds of outcome and variation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve(dlnorm(x, meanlog = 0, sdlog = .8), .01, 6)\ncurve(dt(x, df = 5), -4, 4)\n```\n:::\n\n\n## Describe Relationships {#sec-ch5-relationships}\n\n[]{#ch05-correlations}\n\nThe same 32 complete car-model records support this section's plots,\ncoefficients and matrices. These describe the recorded relationships;\nSection 5.6 adds inference about a process correlation.\n\n### Begin with the plotted observations\n\nMean comparisons group observations by a category. A relationship\nbetween two quantitative variables begins instead with pairs of values.\nFor the 32 car models, `wt` measures weight in thousands of pounds and\n`mpg` fuel economy in miles per US gallon. All 32 rows record both, so\nthe graph and every numerical description use the same rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(mtcars$wt, mtcars$mpg, pch = 16,\n  xlab = \"Weight (thousand pounds)\", ylab = \"Miles per gallon\")\n```\n\n::: {.cell-output-display}\n![Mileage and weight for 32 recorded car models.](chapter_05_files/figure-html/fig-ch05-car-pairs-1.png){#fig-ch05-car-pairs fig-alt='Heavier models generally have lower mpg, with substantial scatter around the decreasing pattern and possible curvature.' width=595.2}\n:::\n:::\n\n\nRead direction, strength and form before reducing the display to a\ncoefficient. Heavier models generally have lower mpg. Inspect unusual\nobservations, the range of weights, possible subgroups and changes in\nspread: a coefficient compresses these features, and the plot shows\nwhat that number can usefully describe.\n\nCovariance averages the products of paired deviations. On the same $n$\nobservations, sample covariance and Pearson correlation are\n\n$$\ns_{xy}=\\frac{\\sum_{i=1}^n(x_i-\\bar x)(y_i-\\bar y)}{n-1},\\qquad\nr_{xy}=\\frac{s_{xy}}{s_xs_y}.\n$$\n\nA pair contributes positively when both values lie above their means or\nboth below, and negatively when they lie on opposite sides. Covariance\nkeeps the product of the two units; dividing by the two SDs gives a\nunit-free coefficient between $-1$ and 1 for variables with nonzero\nspread. For $x=(1,2,3)$ and $y=(2,4,6)$, the deviation products sum to\n4, the covariance is $4/(3-1)=2$, and the SDs are 1 and 2, so $r=1$:\nall points lie on one increasing line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(covariance = cov(mtcars$wt, mtcars$mpg),\n  r = cor(mtcars$wt, mtcars$mpg))\n#>    covariance             r \n#> -5.1166846774 -0.8676593765\n```\n:::\n\n\nThe car covariance is $-5.1167$ thousand-pounds times mpg and $r=-.8677$.\nRecording weight in pounds multiplies the covariance by 1,000, to\n$-5116.6847$ pounds times mpg, and multiplies the weight SD by 1,000 as\nwell, so the correlation stays $-.8677$. Adding a constant changes\nneither statistic; multiplying one variable by a negative constant\nreverses both signs.\n\nA small correlation need not mean little relationship. The five points\n$x=(-2,-1,0,1,2)$ and $y=x^2=(4,1,0,1,4)$ in @fig-ch05-curve follow an\nexact curve, yet their covariance and correlation are zero.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![An exact curved relationship with zero Pearson correlation.](chapter_05_files/figure-html/fig-ch05-curve-1.png){#fig-ch05-curve fig-alt='Five points at x equal to minus two, minus one, zero, one and two have y values four, one, zero, one and four, forming a U.' width=528}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- -2:2\nplot(x, x^2, type = \"b\")\n```\n:::\n\n\nThe cross-products at $x$ and $-x$ cancel by symmetry, although knowing\n$x$ determines $y$. Pearson correlation describes linear association,\nso \"the variables are unrelated\" would overstate this result.\n\n### Covariance and correlation matrices {#ch05-matrices}\n\nA covariance matrix extends the pairwise calculation to several\nvariables: its diagonal holds variances and its off-diagonal entries\ncovariances. A correlation matrix standardizes each entry, with ones on\nthe diagonal for variables with positive variance. Both describe one\ncommon set of rows. For fuel economy, gross horsepower (`hp`) and\nweight, all 32 rows are complete, and three lines produce both\nmatrices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- mtcars[c(\"mpg\", \"hp\", \"wt\")]\nS <- cov(X)\nR <- cov2cor(S)\n```\n:::\n\n\n`mtcars[c(\"mpg\", \"hp\", \"wt\")]` selects three columns by name, `cov()`\nreturns the covariance matrix and `cov2cor()` rescales it into the\ncorrelation matrix. @tbl-ch05-covariance and @tbl-ch05-correlation give\nboth in the same row and column order.\n\n| Variable | mpg | hp | wt |\n|:--|--:|--:|--:|\n| mpg | 36.3241 | $-320.7321$ | $-5.1167$ |\n| hp | $-320.7321$ | 4700.8669 | 44.1927 |\n| wt | $-5.1167$ | 44.1927 | 0.9574 |\n\n: Sample covariance matrix for the same 32 car models. {#tbl-ch05-covariance}\n\n\\Needspace{9\\baselineskip}\n\n| Variable | mpg | hp | wt |\n|:--|--:|--:|--:|\n| mpg | 1.0000 | $-.7762$ | $-.8677$ |\n| hp | $-.7762$ | 1.0000 | .6587 |\n| wt | $-.8677$ | .6587 | 1.0000 |\n\n: Corresponding Pearson correlation matrix. {#tbl-ch05-correlation}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(X)\n```\n\n::: {.cell-output-display}\n![Every off-diagonal matrix entry summarizes a pair of measurements on the same 32 car models. Read a panel using the column variable horizontally and the row variable vertically; opposite panels exchange the axes.](chapter_05_files/figure-html/fig-ch05-matrix-pairs-1.png){#fig-ch05-matrix-pairs fig-alt='A three-by-three scatterplot matrix for mpg, horsepower and weight. Diagonal cells name variables. Mpg declines with horsepower and weight; horsepower generally rises with weight, with substantial scatter.' width=576}\n:::\n:::\n\n\nThe matrix numbers summarize these clouds (@fig-ch05-matrix-pairs).\nThe negative mpg--weight entry describes the descending panels;\nthe positive horsepower--weight entry describes an ascending one.\nThe diagonal of the numerical covariance matrix records each\nvariable's own spread. Curvature and unusual cases remain visible in\nthe plotted pairs even though each matrix entry compresses its cloud\nto one number.\n\nThe mpg variance has squared-mpg units, and its covariance with\nhorsepower has mpg-times-horsepower units; the correlations remove\nthose units. If $\\mathbf D$ is the diagonal matrix of the positive\nsample SDs, the two conversions are\n\n$$\n\\mathbf R=\\mathbf D^{-1}\\mathbf S\\mathbf D^{-1},\\qquad\n\\mathbf S=\\mathbf D\\mathbf R\\mathbf D.\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- sqrt(diag(S))\nR * outer(d, d)\n```\n:::\n\n\nCorrelations alone therefore cannot recover the covariance matrix: the\nSDs and their units are also needed. Multiplying each correlation by\nthe corresponding pair of SDs reconstructs its covariance. A constant column has zero SD\nand an undefined correlation, so it must be detected before\nconverting. Common rows matter when measurements are missing. Computing\neach entry from a different pairwise subset can produce a matrix that\ndescribes no single joint sample and is not positive semidefinite, so\nit can imply an impossible negative variance for a combination of the\nvariables. For airquality's ozone, solar radiation and wind, the\nindividual recorded counts are 116, 146 and 153, but the common set\ncontains 111 days.\n\n### Pearson, rank, and point-biserial coefficients\n\nPearson correlation uses the measured scales and describes linear association. **Spearman correlation** applies Pearson's formula to the\nranks and describes monotone association: values move consistently in\none direction, even along a curve. **Kendall correlation** compares\nconcordant and discordant orderings of pairs, with an adjustment for\nties. For mpg and horsepower:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(Pearson = cor(X$mpg, X$hp),\n  Spearman = cor(X$mpg, X$hp, method = \"spearman\"))\n#>       Pearson      Spearman \n#> -0.7761683718 -0.8946646457\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Mileage and horsepower for the 32 models, (a) on the recorded scales and (b) as ranks. The curved decline in (a) weakens the linear coefficient; ranks straighten a monotone pattern.](chapter_05_files/figure-html/fig-ch05-rank-1.png){#fig-ch05-rank fig-alt='Left panel: mpg falls steeply with horsepower up to about 150 and then levels off, a curved decreasing pattern. Right panel: the ranks of the same models fall along a nearly straight decreasing band.' width=624}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(rank(X$hp), rank(X$mpg))\n```\n:::\n\n\nMileage falls steeply as horsepower rises and then levels off\n(@fig-ch05-rank). The decline is monotone but curved, so the linear\ncoefficient, $-.7762$, is weaker than the rank coefficient, $-.8947$,\nwhich sees only the ordering. A **point-biserial correlation** is\nPearson's coefficient with one variable coded 0/1; @tbl-ch05-coefficients\ncollects the four coefficients.\n\n| Coefficient | What it describes | mtcars value |\n|:--|:--|--:|\n| Pearson, mpg and hp | Linear association on the recorded scales | $-.7762$ |\n| Spearman, mpg and hp | Monotone association: Pearson's coefficient on ranks | $-.8947$ |\n| Kendall, mpg and hp | Concordant minus discordant ordering of pairs, adjusted for ties | $-.7428$ |\n| Point-biserial, `am` and mpg | Pearson's coefficient with manual coded 1 and automatic 0 | .5998 |\n\n: Four coefficients, what each describes, and its value. {#tbl-ch05-coefficients tbl-colwidths=\"[28,54,18]\"}\n\nThe different magnitudes do not make the largest coefficient the best\ndescription in general: the question and the plot decide which\nassociation matters. With average ranks, tied horsepower values share\nthe average of the positions they would occupy; the rank plot and\nSpearman coefficient use those same ranks. Ties also affect test\ncalibration. The point-biserial .5998 corresponds\nto manual and automatic means of 24.3923 and 17.1474 mpg; reversing the\n0/1 coding reverses its sign and leaves the same two groups. For more\nthan two categories, arbitrary numerical labels do not define a\nmeaningful scale for correlation, so the coding must follow the\nvariable's role.\n\n### One-control partial correlation {#ch05-partial}\n\nChanging the cases and adjusting a relationship on the same cases\nanswer different questions. For variables $X$, $Y$ and $Z$, the\n**partial correlation** of $X$ and $Y$ controlling linearly for $Z$ is\n\n$$\nr_{XY\\cdot Z}=\\frac{r_{XY}-r_{XZ}r_{YZ}}\n{\\sqrt{(1-r_{XZ}^2)(1-r_{YZ}^2)}}.\n$$\n\nFor example, practice-time, score and baseline correlations of\n$r_{XY}=.6$, $r_{XZ}=.5$ and $r_{YZ}=.6$, give .433. For mpg and\nhorsepower controlling for weight, the correlations of\n@tbl-ch05-correlation give $-.547$. A second route shows what the\nadjustment does: fit a straight line from weight to each variable, keep\nthe **residuals**, the observed values minus their fitted values, and\ncorrelate what remains.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_mpg <- residuals(lm(mpg ~ wt, data = X))\nresid_hp <- residuals(lm(hp ~ wt, data = X))\ncor(resid_mpg, resid_hp)\n#> [1] -0.5469926242\n```\n:::\n\n\n`lm()` fits the straight line its formula names, the outcome left of\n`~` and the predictor right of it, with an intercept; `residuals()`\nreturns what remains after that fitted linear relationship, for the\nsame 32 rows.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Mileage and horsepower after separately fitting their linear relationships with weight.](chapter_05_files/figure-html/fig-ch05-partial-1.png){#fig-ch05-partial fig-alt='The two residual vectors from the same 32 car models retain a negative association, with partial correlation minus .547.' width=595.2}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(resid_hp, resid_mpg)\n```\n:::\n\n\nBoth routes give $-.547$: the mpg--horsepower association weakens from\n$-.7762$ once each variable's linear relationship with weight is\nremoved, and a negative association remains (@fig-ch05-partial). The\nadjustment uses the same 32 rows; it does not exclude heavy cars. It\nremoves the specified linear relationships and nothing more: not all\nconfounding, omitted nonlinear relationships or measurement problems,\nand it does not establish a causal effect of horsepower.\n\nSection 5.6 supplies the test when this partial coefficient is the\npreselected question. Linear adjustment keeps the same cases;\nrestricting the analysis to lighter cars would instead change the\nrecords, and the two operations need not yield the same relationship.\n\n## Sampling Variation and Standard Errors {#sec-ch5-sampling}\n\n[]{#ch05-sampling}\n\n### A population, a sample, and a target\n\nSection 1 distinguished the recorded days from a wider population.\nA population inference now needs the process by which its observations\nwere selected.\nFiltering recorded values in R describes which observations enter a\nparticular calculation; it supplies no random sampling mechanism. The\ninvented school system, with 20,000 students in schools of\ndifferent types, gives a compact reminder:\n\n\\Needspace{14\\baselineskip}\n\n| Scheme | Selection from the school system |\n|:--|:--|\n| Simple random sampling | Every set of 100 students from the register has the same chance. |\n| Systematic sampling | Choose a random start, then every 200th student; the ordering of the list matters. |\n| Stratified random sampling | Select a probability sample within every school-type stratum. |\n| Cluster sampling | Randomly select schools and include their eligible students. |\n| Multistage sampling | Randomly select schools, then students within those schools. |\n\n: Recognize the sampling procedure before calculating. {#tbl-ch05-sampling-schemes tbl-colwidths=\"[30,70]\"}\n\nProbability sampling gives eligible units known nonzero inclusion\nprobabilities, which need not be equal. An open invitation, convenience\nrecruitment or quotas alone do not supply those probabilities, and\nframe coverage and nonresponse still matter after probability\nselection. A simple random sample of 100 from the register gives each\nstudent inclusion probability $100/20{,}000=.005$. Sampling strata\nconcern selection, whereas blocks concern allocation of conditions; cluster\nsampling and the assignment of whole clusters are different design\ndecisions, even when both produce records grouped within schools.\nGeneral unequal-probability estimation and the SEs for all survey\ndesigns extend beyond the methods developed here.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsample(1:20000, size = 100)\n```\n:::\n\n\nAn estimand names the quantity the question targets; an estimator is\nthe rule applied to a possible sample, and an estimate its realized\nvalue. A sampling distribution requires a specified repetition, not\nsimply a numerical result. We now change the generating process:\ninstead of selecting from a fixed population, R generates independent\nobservations from a probability distribution whose parameters we\nchoose. Let the model be Normal with mean 50 and SD 10, and generate\n30 draws:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(60506)\none_sample <- rnorm(30, mean = 50, sd = 10)\nc(mean = mean(one_sample), SD = sd(one_sample))\n#>         mean           SD \n#> 49.569126166  7.005104058\n```\n:::\n\n\n`rnorm()` takes the number of observations, the model mean and the\nmodel SD; the result is one sample from that model.\n\n\\Needspace{8\\baselineskip}\n\n| Quantity | Model value (parameter) | This sample (statistic) |\n|:--|--:|--:|\n| Mean | $\\mu=50$ | $\\bar x=49.5691$ |\n| SD | $\\sigma=10$ | $s=7.0051$ |\n\n: One sample of 30 draws from a declared Normal model (seed 60506). {#tbl-ch05-parameter-statistic tbl-colwidths=\"[24,38,38]\"}\n\nThe **parameters** are fixed features of the model; the **statistics**\nare calculated from the generated observations and vary with the\ndraws. Running `rnorm()` again without resetting the seed gives another\nsample and generally different statistics, while resetting the seed\nrecreates the same draws. A seed controls the repeatability of the\nnumerical experiment; it supplies no evidence that the Normal model\ndescribes a real study. Nor does knowing the generating SD in a\nsimulation make a sample SD a known population SD in an actual study.\n\nA simulation gives us a known target, but a study usually has a target\nwe cannot observe directly. An invented special-practice study used complete random assignment\nof 120 participants, exactly 60 to Special Practice and 60 to Usual\nPractice, and measured delayed-assessment scores; the group means were 27.1 and 24.0 points, with SDs 6.0 and\n6.4. The **estimand** is the mean effect of assignment to Special\nrather than Usual Practice among these 120 participants. Write $Y_{i1}$\nfor participant $i$'s potential score under Special assignment and\n$Y_{i0}$ for the score under Usual assignment. The target is\n\n$$\n\\Delta\\mu=\\frac{1}{n}\\sum_{i=1}^{n}\\{Y_{i1}-Y_{i0}\\},\n$$\n\nwhere the braces hold one participant's effect and division by $n=120$\ntakes the mean over the 120 assigned participants. Each participant\nreveals only the outcome under the assigned condition, so no individual\neffect is ever recorded and the effects cannot simply be averaged. The\n**estimator**, the difference in assigned-group means\n$\\widehat{\\Delta\\mu}=\\bar y_1-\\bar y_0$, uses the observed outcomes;\n**estimation** applies that rule and checks its inputs; the\n**estimate** is the resulting $27.1-24.0=3.1$ points. The repetition\nbehind its uncertainty reassigns the same 120 participants, exactly 60\nto each condition: the participants and their potential outcomes stay\nfixed while the assigned groups and observed outcomes vary. That\ndiffers from repeatedly sampling new people.\n\n| Object | Working definition | In the special-practice study | In R |\n|:--|:--|:--|:--|\n| Estimand | The precisely specified quantity the question seeks | Mean delayed-score difference caused by Special rather than Usual assignment among the 120 participants | Not an object; stated in words before any code |\n| Estimator | The rule applied in each admissible repetition | Special-group mean minus Usual-group mean | An expression such as `mean_special - mean_usual` |\n| Estimate | The number the estimator produced | $27.1-24.0=3.1$ points | The value that expression returns |\n| Statistic | A numerical function of observed data | A group mean, the 3.1-point estimate | Any computed summary |\n| Parameter | A fixed feature named by the estimand under the chosen interpretation | The participant-specific mean assignment contrast | Unknown here; Section 4.4 changes the target to a known waiting-time variance |\n| Standard error | The modelled spread of the estimator across the declared repetitions | 1.1325 points (Section 4.5) | Computed from the group SDs and counts |\n\n: Inferential objects with their R counterparts. {#tbl-ch05-inferential-objects tbl-colwidths=\"[13,27,34,26]\"}\n\n@tbl-ch05-inferential-objects separates the scientific target from its\ncomputational representation. Storing a result in an object named\n`estimate` does not define its estimand; that definition comes from the\nquestion, the participants, the comparison and the outcome.\n\n### The first repeated-sample calculation\n\nConsider independent exponential waits with mean and SD both 10 minutes, many short and a few long. R's\n`rexp()` uses the **rate**, the reciprocal of the mean, so\n`rate = 1 / 10` gives a ten-minute mean. One call repeats the whole\nsampling operation, drawing five waits and averaging them, 5,000 times:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(60203)\nmeans_5 <- replicate(5000, mean(rexp(5, rate = 1 / 10)))\nc(mean = mean(means_5), SE = sd(means_5))\n#>         mean           SE \n#> 10.014145149  4.539459458\n```\n:::\n\n\n`replicate()` evaluates its second argument repeatedly and collects the\nresults, so `means_5` holds 5,000 sample means, not 5,000 individual\nwaits. Their mean, 10.0141 minutes, lies close to the model mean, and\ntheir SD, 4.5395 minutes, describes how much a mean of five waits\nvaries. A statistic's **standard error** is its SD\nacross the stated repetitions. For independent observations from a\ncommon distribution with SD $\\sigma$, the mean's model SE is\n\n$$\nSE(\\bar Y)=\\frac{\\sigma}{\\sqrt n},\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(means_5)\n10 / sqrt(c(5, 30, 120))\n```\n:::\n\n\nThe SD of simulated means estimates this model SE; we call that SD the\n*empirical SE*. A simulation has two sizes, and they do different\njobs: the study size $n$, the number of waits in each sample, and the\nnumber of repetitions $B$, the number of simulated samples.\n@fig-ch05-repetitions changes one at a time.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![More repetitions or larger studies. Each histogram collects simulated sample means from the waiting-time model; the dashed line marks the model mean, 10 minutes. (a) The first 200 of the 5,000 means of 30 waits; (b) all 5,000; (c) 5,000 means of 120 waits.](chapter_05_files/figure-html/fig-ch05-repetitions-1.png){#fig-ch05-repetitions fig-alt='Three histograms on common axes from 4 to 18 minutes. The first, from 200 means, is ragged; the second, from 5,000 means of the same study size, is smooth with the same spread; the third, from 5,000 means of 120 waits, is about half as wide.' width=624}\n:::\n:::\n\n\n\\Needspace{9\\baselineskip}\n\n| Panel | Study size $n$ | Repetitions $B$ | Mean of sample means | Empirical SE | Model SE |\n|:--|--:|--:|--:|--:|--:|\n| (a) | 30 | 200 | 9.6698 | 1.7484 | 1.8257 |\n| (b) | 30 | 5,000 | 9.9626 | 1.7878 | 1.8257 |\n| (c) | 120 | 5,000 | 9.9922 | 0.9214 | 0.9129 |\n\n: Repetitions and study size change different things (seed 60203). {#tbl-ch05-repetitions tbl-colwidths=\"[10,16,16,20,19,19]\"}\n\nFrom panel (a) to panel (b) only the number of repetitions changes. The\nhistogram becomes smoother and its empirical SE settles near the model\nSE $10/\\sqrt{30}=1.8257$ minutes, which has not changed: more\nrepetitions show the same sampling distribution more steadily. From\npanel (b) to panel (c) the study size quadruples, so the model SE halves\nto $10/\\sqrt{120}=0.9129$ minutes and the histogram narrows. The\ndensity scale makes each bar's area the fraction of generated means in\nits interval, so the three panels are directly comparable. With\nfinitely many repetitions, an empirical SE need not equal its model\nvalue exactly.\n\nKeep three quantities distinct. The 10-minute SD describes individual\nwaits. The SE describes how sample means vary at a stated study size.\nA particular sample's **error**, such as $11.3-10=1.3$ minutes for an\nillustrative mean of 11.3, is one realized departure from the target;\nan SE summarizes the distribution of possible estimates and does not\nreveal the error of a particular one. Halving an SE under this model\ntakes four times as many observations.\n\n### Concentration and sampling shape\n\nTwo results explain the changing distributions of sample means. The\n**law of large numbers** concerns concentration: under its conditions,\nlarger samples make the mean more likely to lie close to the population\nmean. The **central limit theorem** concerns shape: under conditions\nsuch as independent, identically distributed observations with finite\nvariance, the centred and scaled sample mean approaches a Normal\ndistribution. A running mean shows the first idea along one sequence\nof draws: after draw $k$, average the first $k$ waits.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![One running mean from independent exponential waits with model mean ten minutes.](chapter_05_files/figure-html/fig-ch05-running-mean-1.png){#fig-ch05-running-mean fig-alt='The running mean fluctuates irregularly around ten; it is 9.7207 after 400 observations. Adding a draw can move it closer to or farther from the target.' width=595.2}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(60204)\nwait <- rexp(400, rate = 1 / 10)\nplot(cumsum(wait) / seq_along(wait), type = \"l\")\n```\n:::\n\n\nThe running means are 9.0830 minutes after 10 draws, 7.9852 after 50,\n8.8373 after 100 and 9.7207 after 400. The path is irregular: adding\nobservations can move the mean farther from 10 for a while.\nConcentration is a probabilistic statement as the sample grows, not a\npromise of steady improvement along one sequence or a guarantee at a\nparticular size.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(means_5, probability = TRUE)\ncurve(dexp(x, rate = 1 / 10), add = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Individual waits and averages answer different questions. The line in every panel is the same exponential density for a single wait, with mean and SD ten minutes. Histograms show 5,000 independent sample means at each sample size. The dashed line marks their common model mean.](chapter_05_files/figure-html/fig-ch05-waiting-1.png){#fig-ch05-waiting fig-alt='Three panels on common axes compare means of 5, 30 and 100 waits. The density for one wait stays strongly right-skewed in every panel; the histograms of means become narrower and more symmetric around ten.' width=624}\n:::\n:::\n\n\nThe histograms of @fig-ch05-waiting change shape as well as width:\nmeans of larger samples become more nearly symmetric, although\nindividual waits keep their exponential distribution. Concentration describes closeness to\nthe target; the central limit theorem describes the sampling shape\nafter centring and scaling. Neither makes individual observations\nNormal. Strong dependence, extreme tails or a dominating observation\ncan make a familiar approximation poor, and there is no universal\nsample-size cutoff.\n\n### Bias and precision\n\nAn estimator's **expectation** is its probability-weighted average\nacross the declared repetitions, and its **bias** is that expectation\nminus the target. An estimator averaging 3.4 when the target is 3 has\nbias 0.4. **Precision**\nconcerns how tightly the possible values cluster: an estimator can be\ncentred correctly and still vary widely from one sample to the next.\n\nTo compare the two variance divisors, change the target to the variance\nof the waiting-time process, 100 squared minutes. For each of 5,000\nindependent samples of five waits, compute one variance with divisor\n$n-1$ and one with divisor $n$. The second is always four-fifths of\nthe first for samples of five; @tbl-ch05-bias-evidence reports their averages.\n\n\\Needspace{8\\baselineskip}\n\n| Variance rule | Mean over 5,000 samples | Expectation under the model |\n|:--|--:|--:|\n| Divide by $n-1$ | 101.2241 | 100 |\n| Divide by $n$ | 80.9793 | 80 |\n\n: Variance estimates from independent exponential samples of five waits (seed 60501). {#tbl-ch05-bias-evidence tbl-colwidths=\"[34,33,33]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(60501)\nv <- replicate(5000, var(rexp(5, rate = 1 / 10)))\nc(mean(v), mean(v * 4 / 5))\n```\n:::\n\n\nThe expectations in the last column follow from\n\n$$\n\\operatorname{Bias}(\\widehat\\theta)=E(\\widehat\\theta)-\\theta,\\qquad\nE(s^2)=\\sigma^2,\\qquad\nE\\left\\{\\frac{1}{n}\\sum_{i=1}^{n}(X_i-\\bar X)^2\\right\\}=\\frac{n-1}{n}\\sigma^2.\n$$\n\nThe $n-1$ rule is unbiased under the independent common-distribution\nmodel; the $n$ rule has downward bias $\\sigma^2/n=20$ squared minutes\nhere. The simulation average 101.2241 can differ from 100 even for the\nunbiased rule, because 5,000 samples approximate the expectation rather\nthan enumerating every possible sample. Both rules can be far from 100\nin a single sample. The $n$ estimate is always four-fifths of the\n$n-1$ estimate here, so it varies less across repetitions while being\ncentred on the wrong value: an apparently stable estimate can\nsystematically miss its target, which is why precision and bias are\nreported separately.\n\n### SE follows the unit and the comparison {#sec-ch5-reshape}\n\nAn SE follows the observational units that can vary independently. The\n[sleep documentation](https://stat.ethz.ch/R-manual/R-patched/library/datasets/html/sleep.html)\ndescribes extra hours of sleep, relative to a control period, under two\ndrugs for ten people. `ID` identifies a person, `group` a drug and\n`extra` the extra hours; negative values mean less sleep than under\ncontrol. Twenty measurement rows therefore represent ten people, and\nalignment by person comes before subtraction:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsleep_wide <- reshape(sleep, idvar = \"ID\", timevar = \"group\",\n  direction = \"wide\")\nsleep_d <- sleep_wide$extra.2 - sleep_wide$extra.1\nc(mean = mean(sleep_d), SD = sd(sleep_d),\n  SE = sd(sleep_d) / sqrt(length(sleep_d)))\n#>         mean           SD           SE \n#> 1.5800000000 1.2299954833 0.3889587239\n```\n:::\n\n\nEach person's two measurements occupy one row, as `extra.1` and\n`extra.2`. A valid pair matches the same person in both conditions. The subtraction is **drug 2 minus drug 1**. The\nten differences have mean 1.58 hours and SD 1.23 hours, and because the\nsame people enter both conditions, the mean difference equals the\ndifference of the condition means, $2.33-0.75=1.58$. Their variance\nkeeps the pairing:\n\n$$\ns_d^2=s_2^2+s_1^2-2s_{12},\n$$\n\nwhere $s_{12}$ is the covariance of the two measurements.\n@tbl-ch05-paired-se sets the two possible SE calculations for the same\nten people side by side.\n\n\\Needspace{8\\baselineskip}\n\n| Calculation for the ten people | Variance used | SE of the mean difference (hours) |\n|:--|:--|--:|\n| Paired: the ten within-person differences | $s_d^2=1.5129$ | 0.3890 |\n| As if the two conditions were independent groups | $s_1^2+s_2^2=3.2006+4.0090$ | 0.8491 |\n\n: Two SE calculations for the same ten people. {#tbl-ch05-paired-se tbl-colwidths=\"[44,32,24]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(sleep_d) / sqrt(length(sleep_d))\nsqrt((var(sleep_wide$extra.1) + var(sleep_wide$extra.2)) / 10)\n```\n:::\n\n\nThe covariance of the two measurements is positive, 2.8483: people who\ngain more sleep under one drug tend to gain more under the other. The\npaired calculation removes that shared variation; the independent-groups\ncalculation leaves it in and more than doubles the SE. The number of\npeople is ten in both rows, so the variance calculation, not the count,\nis what changed.\n\nFor a single mean of independent observations from a common process,\nthe sample SD estimates the process SD and the estimated SE is\n$\\widehat{SE}(\\bar Y)=s/\\sqrt n$. For the 116 ozone values it is\n$32.9879/\\sqrt{116}=3.0628$ ppb, **under a working assumption of\nindependent observations from a common process**. The historical daily\nrecord does not establish that assumption: nearby days could be\nrelated and the process could change over the summer. The formula\nreturns a number; its inferential use needs a justification for the\nmodel and the target.\n\nFor two independent groups, each mean contributes its own variance\nterm. The special-practice summaries give\n\n$$\n\\widehat{SE}(\\bar y_1-\\bar y_0)=\\sqrt{\\frac{6.0^2}{60}+\\frac{6.4^2}{60}}\n=1.1325\\text{ points},\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(6^2 / 60 + 6.4^2 / 60)\n```\n:::\n\n\nWith 60 participants in each group, this also equals the pooled SE.\nIts interpretation in this\nfixed-participant assignment study differs from independent sampling.\nExactly 60 of the 120 participants are assigned to each group, so the\ntwo assigned-group means are dependent, and the exact assignment\nvariance subtracts a term for variation in individual assignment\neffects, which the observed outcomes cannot recover. The squared SE\nabove omits that term and estimates an upper bound on the assignment\nvariance *on average*; it need not exceed the true variance in every\nrealized study. A t reference adds an approximate calibration to\nthis variance estimate.\n\nTwo other design consequences follow the same principle. If schools\nare independent blocks, uncertainty follows their contrasts rather\nthan the student identifiers within them. Sampling without replacement\nfrom a finite register changes uncertainty through the sampling fraction. Across these settings, the estimand,\ndependence and design decide the uncertainty calculation; row counts\nalone cannot.\n\n## Intervals and Tests for Means and Correlations {#ch05-mean-inference}\n\n### Estimate, SE, critical value, and interval {#ch05-z-t}\n\nAn estimate answers a numerical question; an interval describes\nuncertainty about its target under a stated procedure. Before asking R\nfor either, name the outcome and its units, the included observations,\nthe parameter and the repetition that makes an SE meaningful: the model\nand design determine the calculation, and a function's default cannot\nsupply them. The common construction is\n\n$$\n\\text{interval}=\\widehat\\theta\\pm c^*\n\\widehat{\\operatorname{SE}}(\\widehat\\theta),\\qquad\nT=\\frac{\\widehat\\theta-\\theta_0}\n{\\widehat{\\operatorname{SE}}(\\widehat\\theta)}.\n$$\n\nThe estimate and SE have outcome units. Multiplying the SE by the\n**critical value** $c^*$ gives a margin in those units, and the test\nstatistic expresses the departure from a null value $\\theta_0$ in SE\nunits. The confidence level, the tail convention and the reference\ndistribution determine the critical value and the p-value.\n\nFor a mean of independent Normal observations whose SD $\\sigma$ is\nstipulated independently, the SE is $\\sigma/\\sqrt n$ and the statistic\nhas a standard Normal reference. When the SD is estimated from the\nsame observations, the SE is $s/\\sqrt n$ and the reference is t with\n$n-1$ df, whose heavier tails reflect the uncertainty of the estimated\nscale [@student1908].\nThe critical values that leave .025 in the upper tail show the\ndifference:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(z = qnorm(.975), t5 = qt(.975, 5), t9 = qt(.975, 9),\n  t30 = qt(.975, 30))\n#>           z          t5          t9         t30 \n#> 1.959963985 2.570581836 2.262157163 2.042272456\n```\n:::\n\n\nThe multipliers are 1.96 for the Normal reference and 2.5706, 2.2622\nand 2.0423 for t with 5, 9 and 30 df. A large sample makes the two\nreferences similar; it does not make an estimated SD a known one.\n\nThe 32 recorded car models have mean fuel economy 20.0906 mpg. Take the\nnull process mean to be 20 mpg and let R run the one-sample t\nprocedure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(mtcars$mpg, mu = 20)\n#> \n#> \tOne Sample t-test\n#> \n#> data:  mtcars$mpg\n#> t = 0.085060036, df = 31, p-value = 0.9327606\n#> alternative hypothesis: true mean is not equal to 20\n#> 95 percent confidence interval:\n#>  17.91767851 22.26357149\n#> sample estimates:\n#> mean of x \n#> 20.090625\n```\n:::\n\n\nThe printout names the method, gives the statistic with its df and the\np-value, states the two-sided alternative, and reports the 95% interval\nand the estimated mean. Suppose,\nas a second and explicitly different working assumption, that the\nprocess SD were **known independently to be 5 mpg**; this teaching\nvalue is not an estimate from `mtcars`. @tbl-ch05-one-mean sets the\ntwo procedures side by side.\n\n| Procedure | SE | Statistic | df | Two-sided p | 95% interval |\n|:--|--:|--:|--:|--:|:--|\n| Known-SD z, $\\sigma=5$ | 0.8839 | 0.1025 | -- | .9183 | [18.3582, 21.8230] |\n| Estimated-SD t | 1.0654 | 0.0851 | 31 | .9328 | [17.9177, 22.2636] |\n\n: One mean, two explicitly different uncertainty assumptions. {#tbl-ch05-one-mean tbl-colwidths=\"[27,10,12,5,16,30]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(mtcars$mpg) + c(-1, 1) * qnorm(.975) * 5 / sqrt(32)\n```\n:::\n\n\nThe t row uses the observed SD, 6.0269, and the critical value 2.0395.\nBoth its SE and its multiplier exceed those of the known-SD row, so its\ninterval is wider. Both intervals contain 20 mpg, matching their\ntests' failure to reject that null at .05; this matching holds when\ninterval and test share a method, assumptions and calibration. A\np-value is a tail probability under the null and those conditions, not\nthe probability that the null is true, and including 20 establishes\nneither exact equality nor practical equivalence. An interval for a\nprocess mean also differs from a range containing 95% of individual\ncars. These calculations illustrate working process models: the\nhistorical collection of car models does not become a probability\nsample when `t.test()` runs, and a broader inference needs a supported\ntarget process with appropriate dependence and distribution conditions.\n\n### Supplied summaries and a planned direction\n\nAn invented district study supplies only summaries: $n=25$, mean 52 and\nsample SD 5 under independent Normal sampling. They are enough, so we\nuse them directly rather than inventing observations to pass into\n`t.test()`. For the null mean 50, the estimated SE is $5/\\sqrt{25}=1$\nand the statistic is $t=(52-50)/1=2$ on 24 df. `pt()` turns the\nstatistic into tail areas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(two_sided = 2 * pt(2, df = 24, lower.tail = FALSE),\n  upper = pt(2, df = 24, lower.tail = FALSE))\n#>     two_sided         upper \n#> 0.05693984994 0.02846992497\n```\n:::\n\n\nThe two-sided p-value is .0569; the upper-tail p-value for the\nalternative $\\mu>50$ is .0285. They differ because they answer\ndifferent questions, and a directional alternative must come from the\nquestion before the result is seen. Had the planned alternative been $\\mu<50$, the same statistic would\ngive lower-tail $p=.9715$, above .5; halving a two-sided p-value\nblindly can therefore report the wrong tail. The two-sided 95% interval is\n[49.9361, 54.0639], using R's critical value 2.0639, and it contains\n50, consistent with the two-sided test; the upper-tail test does not\ncorrespond to that interval. The rounded t-table value 2.064\ngives [49.936, 54.064]; a task that stipulates that rounded\ncritical value keeps those endpoints. The difference is rounding, not\na changed conclusion.\n\n### Paired observations and complete pairs {#ch05-paired}\n\nThe sleep measurements return us to a comparison whose unit is a\nperson: ten complete pairs, not twenty independent people. Their\ncondition means are 0.75 and 2.33 hours, and the mean of their aligned\ndifferences is 1.58 hours. Nine differences are positive and one is\nzero, ranging from 0 to 4.6 hours.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Two measurements for each of ten people.](chapter_05_files/figure-html/fig-ch05-pairs-1.png){#fig-ch05-pairs fig-alt='Lines connect drug 1 and drug 2 for each person; nine rise and one is flat.' width=595.2}\n:::\n:::\n\n\nThe inferential target is a process mean difference $\\mu_D$. Under a\nworking model of independent Normal differences between people,\n$s_d/\\sqrt n$ estimates the SE of their mean and the t reference has\n$n-1$ df. Normality concerns the differences, and the dependence\nbetween one person's two measurements is kept in the difference, as\n@fig-ch05-pairs shows line by line. The argument `paired = TRUE` tells\nR to subtract measurements at corresponding positions, which the\nID-based reshaping of Section 4.5 made correct:\n\n\\Needspace{16\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(sleep_wide$extra.2, sleep_wide$extra.1, paired = TRUE)\n#> \n#> \tPaired t-test\n#> \n#> data:  sleep_wide$extra.2 and sleep_wide$extra.1\n#> t = 4.0621277, df = 9, p-value = 0.00283289\n#> alternative hypothesis: true mean difference is not equal to 0\n#> 95 percent confidence interval:\n#>  0.7001142367 2.4598857633\n#> sample estimates:\n#> mean difference \n#>            1.58\n```\n:::\n\n\nThe output gives $t(9)=4.0621$, $p=.0028$ and the 95% interval [0.7001,\n2.4599] hours around the mean difference 1.58. A paired t calculation\nis a one-sample t calculation on the within-person differences, so the\nsame result follows from `t.test(sleep_d)`. Raising the confidence to\n99% widens the interval to [0.3159, 2.8441] while the observations and\nthe estimate stay the same.\n\nWith missing measurements, keep the rows that have both values before\nforming differences; removing missing entries separately from each\ncolumn could align different people. Complete-pair analysis also\nchanges who contributes and may need a missingness justification: a\nsoftware exclusion is not that justification. The interval concerns a\nprocess mean, not a guarantee of benefit for every person, and ten\ndifferences give limited protection against non-Normal tails or\ninfluential cases. Neither the paired call nor the dataset establishes\nrandom sampling, treatment order, absence of carryover or the other\nconditions needed for a causal interpretation.\n\n### Two independent groups and Welch's method {#ch05-welch}\n\nNow compare separate automatic and manual car models. Let\n$\\Delta\\mu=\\mu_A-\\mu_M$ be the automatic-minus-manual process mean mpg\ndifference. Under an independent-groups working model the two means\ncontribute separate variance terms. Welch's method estimates both and\nallows the group variances to differ [@welch1947]. With $a=s_A^2/n_A$ and $b=s_M^2/n_M$,\n\n$$\n\\widehat{\\Delta\\mu}=\\bar y_A-\\bar y_M,\\qquad\n\\widehat{\\operatorname{SE}}=\\sqrt{a+b},\\qquad\n\\nu=\\frac{(a+b)^2}{a^2/(n_A-1)+b^2/(n_M-1)}.\n$$\n\nThe Welch--Satterthwaite df $\\nu$ account approximately for the two\nestimated variance terms and need not be an integer. Extracting the two\ngroups in a stated order makes the subtraction unambiguous:\n\n\\Needspace{18\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nauto <- mtcars$mpg[mtcars$am == 0]\nmanual <- mtcars$mpg[mtcars$am == 1]\nt.test(auto, manual)\n#> \n#> \tWelch Two Sample t-test\n#> \n#> data:  auto and manual\n#> t = -3.7671231, df = 18.332252, p-value = 0.001373638\n#> alternative hypothesis: true difference in means is not equal to 0\n#> 95 percent confidence interval:\n#>  -11.280194355  -3.209684187\n#> sample estimates:\n#>   mean of x   mean of y \n#> 17.14736842 24.39230769\n```\n:::\n\n\nThe 19 automatic and 13 manual models have means 17.1474 and 24.3923\nmpg, a difference of $-7.2449$ mpg. The output reports $t=-3.7671$ on\n$\\nu=18.3323$ df, $p=.0014$ and the 95% interval [$-11.2802$,\n$-3.2097$]. The negative sign describes the declared order; reversing\nit would negate the estimate and exchange the negated endpoints, with\nthe same two-sided p-value. R's two-sample `t.test()` uses Welch's test\nby default, and `var.equal = TRUE` gives the equal-variance (pooled) test, which adds a common-variance assumption.\n@tbl-ch05-welch-pooled compares the two on the same records.\n\n\\Needspace{8\\baselineskip}\n\n| Procedure | SE | df | Two-sided p | 95% interval |\n|:--|--:|--:|--:|:--|\n| Welch's unequal-variance t | 1.9232 | 18.3323 | .0014 | [$-11.2802$, $-3.2097$] |\n| Equal-variance (pooled) t | 1.7644 | 30 | .0003 | [$-10.8484$, $-3.6415$] |\n\n: The same automatic-minus-manual estimate, $-7.2449$ mpg, under two variance assumptions. {#tbl-ch05-welch-pooled tbl-colwidths=\"[34,12,14,14,26]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(auto, manual, var.equal = TRUE)\n```\n:::\n\n\nThe estimate and the observations are unchanged; the variance\nassumption and the calibration differ. The equal-variance t reference\nis exact for independent Normal groups with a common variance, whereas\nWelch's reference remains approximate even for independent Normal\ngroups with unequal variances. The choice comes\nfrom the design and subject knowledge before the analysis: a smaller\np-value, or a preliminary variance test, is not a reason to adopt the\ncommon-variance assumption. Neither method resolves the differences in\nweight, engine and other features that accompany transmission, so\nthese observational comparisons do not isolate a transmission effect.\n\n### Coverage belongs to the procedure {#ch05-coverage}\n\nWhat makes an interval procedure a 95% procedure? A known process lets\nus see. Let independent differences be Normal with mean 1.5 hours and\nSD 1.2 hours; these are teaching constants, not a reconstruction of the\nsleep study. Each repeated study draws fresh differences, estimates\ntheir mean and SE, and forms a 95% t interval; recalculating one\ninterval on the same observations would reproduce that interval, not\ntest the procedure. Before looking at @fig-ch05-coverage, predict what\nwill change when each study grows from 10 to 40 observations: the\ninterval widths, the procedure's nominal coverage, or both?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Fresh data produce different 95% t intervals. Each dot is a sample mean, and its segment uses that study's estimated SE. The vertical line is the fixed true mean, 1.5 hours; dashed segments and open dots mark intervals that miss it. Each panel shows the first 40 of the corresponding table's 2,000 studies, with seed 60610 reset for each sample size. In each panel, 39 of 40 intervals cover.](chapter_05_files/figure-html/fig-ch05-coverage-1.png){#fig-ch05-coverage fig-pos='ht' fig-alt='Two panels share the same horizontal scale. Forty mean-and-interval rows from studies of size 10 vary in centre and width; the twenty-seventh misses 1.5. Forty rows from studies of size 40 are narrower; the twenty-fifth misses 1.5. The true mean stays fixed in both panels.' width=595.2}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(60610)\ny <- rnorm(10, mean = 1.5, sd = 1.2)\nt.test(y)$conf.int\n```\n:::\n\n\nFresh data move the means, and each study's estimated SD also changes\nits interval width. With 40 observations the intervals are generally\nnarrower, while the same 95% procedure is used. Under this Normal model\nits coverage is exactly .95 at either size. The 39 of 40 intervals that\ncover in each panel are this small simulation's outcome; a collection\nof 40 need not contain exactly 38 covering intervals. For any one\nobserved interval, the fixed mean lies inside or outside its endpoints.\n\nRepeating the calculation for 2,000 studies at each of three sample\nsizes estimates coverage more stably (@tbl-ch05-coverage).\n\n\\Needspace{11\\baselineskip}\n\n| n | Mean of estimates | Empirical SE | Model SE | Coverage |\n|--:|--:|--:|--:|--:|\n| 10 | 1.5015 | 0.3766 | 0.3795 | .9515 |\n| 20 | 1.5006 | 0.2591 | 0.2683 | .9510 |\n| 40 | 1.5014 | 0.1886 | 0.1897 | .9460 |\n\n: Coverage of 95% t intervals from the Normal process, using 2,000 repetitions at each sample size and resetting seed 60610 for each row. {#tbl-ch05-coverage tbl-colwidths=\"[10,25,25,20,20]\"}\n\nThe empirical SE is the SD of the generated means and the model SE is\n$1.2/\\sqrt n$; coverage is the fraction of generated intervals that\ncontain 1.5. Under the declared Normal model the t procedure has exact\n95% coverage, so the simulated fractions differ from .95 only through\nthe finite number of studies. That numerical uncertainty has its own\n**Monte Carlo SE**: each study's coverage indicator is a Bernoulli\noutcome, so its mean is a proportion as in Section 2.3, and at coverage .95 with $B=2000$,\n\n$$\n\\operatorname{MCSE}(\\widehat p_{\\mathrm{cover}})\n=\\sqrt{\\frac{.95(.05)}{2000}}=0.0049.\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsqrt(.95 * .05 / 2000)\n```\n:::\n\n\nAll three fractions lie within one MCSE of .95. Increasing $B$ reduces\nthe simulation noise, quadrupling it halves the MCSE. Increasing $n$\nsupplies more information in each study and narrows the intervals,\nfrom 10 to 40 halving the model SE, without raising the nominal 95%\ncoverage above 95%. The individual-difference SD, the mean's SE and the\nsimulation's MCSE describe different sources of variation. For one\nobserved interval the parameter is inside or outside; the 95% describes\nrepeated use of the procedure.\n\n### A selected correlation test {#ch05-correlation-tests}\n\nThe descriptive weight--mpg correlation concerns the recorded models.\nInference adds a target process correlation $\\rho$ and a supporting\nmodel. Suppose we selected the two-sided null $H_0:\\rho=0$ before\nexamining the result, with level $\\alpha=.05$. Under independent\nbivariate-Normal sampling the zero-correlation statistic\n\n$$\nt=r\\sqrt{\\frac{n-2}{1-r^2}},\\qquad df=n-2,\n$$\n\nhas an exact $t_{n-2}$ reference. One call carries out the test on the\nsame 32 pairs:\n\n\\Needspace{15\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(mtcars$wt, mtcars$mpg)\n#> \n#> \tPearson's product-moment correlation\n#> \n#> data:  mtcars$wt and mtcars$mpg\n#> t = -9.5590441, df = 30, p-value = 1.293959e-10\n#> alternative hypothesis: true correlation is not equal to 0\n#> 95 percent confidence interval:\n#>  -0.9338264133 -0.7440871965\n#> sample estimates:\n#>           cor \n#> -0.8676593765\n```\n:::\n\n\nThe output gives $r=-.8677$, $t(30)=-9.559$ and a p-value so small that\nR prints it in scientific notation, $p<.0001$. The result is evidence\nagainst zero process correlation under the stated reference model; a\nsmall p-value does not establish that model or turn the historical car\nrecords into a probability sample. Normality is not needed to calculate\nthe descriptive $r$, whereas independence, form, influential cases and\nthe observed range matter for inference.\n\nThe printed 95% interval, [$-.9338$, $-.7441$], uses Fisher's\ntransformation, a different approximation from the exact zero-null\ntest:\n\n$$\nCI_\\rho=\\tanh\\left\\{\\operatorname{atanh}(r)\n\\pm\\frac{z_{.975}}{\\sqrt{n-3}}\\right\\}.\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- cor(mtcars$wt, mtcars$mpg)\ntanh(atanh(r) + c(-1, 1) * qnorm(.975) / sqrt(32 - 3))\n```\n:::\n\n\nWhy transform? @fig-ch05-fisher simulates 5,000 studies of 32 pairs\nwhose process correlation is $-.8677$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Sample correlations from 5,000 simulated studies of 32 pairs with process correlation $-.8677$. (a) On the correlation scale the distribution is skewed, with a long tail toward zero and a hard limit at $-1$; (b) on the Fisher scale it is nearly Normal, and the curve is the Normal density with SD $1/\\sqrt{29}$. Dashed lines mark the process value on each scale.](chapter_05_files/figure-html/fig-ch05-fisher-1.png){#fig-ch05-fisher fig-alt='Left panel: a histogram of simulated correlations between about minus .97 and minus .6, peaked near minus .88 with a long right tail. Right panel: the same values after the inverse hyperbolic tangent form a symmetric histogram matched by a Normal curve.' width=624}\n:::\n:::\n\n\nNear $-1$ the sample correlations are squeezed against the bound and\ntrail off toward zero, so a margin of equal size on both sides of $r$\nwould misplace the interval. On the Fisher scale the same values are\nnearly Normal, with SD 0.1831 against the model's\n$1/\\sqrt{29}=0.1857$. The interval is therefore built there and both\nendpoints are transformed back, which makes it asymmetric about $r$:\nit extends 0.0662 below $-.8677$ and 0.1236 above. The interval needs\nat least four complete pairs and remains approximate even under\nbivariate Normality, and substantial nonlinearity can make linear\ncorrelation a poor answer to the substantive question whatever the\ninterval's width.\n\nIf the partial coefficient is the preselected inferential question, the\nreference must account for fitting the control. With $k$ controls and\n$n$ common observations the classical statistic is\n\n$$\nt=r_{XY\\cdot Z}\\sqrt{\\frac{n-k-2}{1-r_{XY\\cdot Z}^{\\,2}}},\\qquad df=n-k-2,\n$$\n\nwhich here gives $t=-3.5187$ on 29 df, $p=.0015$. This exact classical\ncalibration requires independent observations, full-rank linear\nadjustment and a Normal conditional-error model, or a multivariate\nNormal model. Applying an ordinary `cor.test()` to the two residual\nvectors would use $n-2=30$ df and ignore the fitted control.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr <- cor(resid_mpg, resid_hp)\nt <- r * sqrt(29 / (1 - r^2))\n2 * pt(abs(t), df = 29, lower.tail = FALSE)\n```\n:::\n\n\nThe rank coefficients of Section 3.3 have their own tests, reporting\nSpearman's S or Kendall's z, using `exact = FALSE` with tied values,\nand supplying no Fisher interval. A\npreselected question supports one test. Choosing whichever method gives\nthe smallest p-value or reporting a matrix of unplanned tests creates\na comparison family that needs calibration for the choices made.\n\nThe point-biserial test of Section 3.3's .5998 gives $t(30)=4.1061$,\n$p=.0003$, the statistic of Section 5.4's equal-variance two-sample t\nwith manual first, under independent, conditionally Normal outcomes\nand a common variance; it generally differs from Welch's test. The\nequivalence concerns that common-variance model; it does not select\nthe appropriate assumptions for the study.\n\n## Report the Study {#sec-ch5-report}\n\n[]{#ch05-report}\n\n### Connect the question, methods and results\n\nA study report lets readers follow a question through the evidence used\nto answer it. Explain what was recorded, how the observations were\nobtained, which comparison addresses the question, and why the analysis\nis appropriate. Then present the results and explain their implications\nand limitations. The code and its output support this account; readers\nalso need the study information that gives the numbers their meaning.\n\nFor the sleep example, the question concerns the difference in extra\nsleep between two drugs. The outcome is measured in hours, and ten\npeople each supply two measurements. This design makes the within-person\ndifference, drug 2 minus drug 1, the relevant comparison. The analysis\nstates its model for those differences; the report also identifies\nmissing information about assignment, treatment order and carryover.\nWithin that account, the result paragraph can read:\n\n> For the ten recorded people, extra sleep under drug 2 averaged\n> 1.58 hours more than under drug 1. The SD of the ten within-person\n> differences was 1.23 hours. Under an independent Normal-differences\n> working model, the mean difference has SE 0.389 hours and a 95% t\n> interval of [0.7001, 2.4599] hours ($t(9)=4.0621$, two-sided $p=.0028$).\n> This uncertainty concerns the stated process mean. A causal account\n> also requires information about treatment assignment, order and carryover.\n\nThe first two sentences describe the recorded people. The next adds\nmodel-based uncertainty for a named target, rather than a range of\nindividual responses. The final sentence identifies the information a\ncausal claim would need. A successful computation supplies the result;\nthe study setting supplies the argument for using it [@peng2011].\n\n### Use Quarto to connect the study and its source\n\nA saved script records calculations. For reporting the study, Quarto\noffers a practical way to bring explanatory prose, mathematical\nequations, R code, computed values, tables, figures, citations and a\nreference list together in one editable source [@quarto2026]. Rendering\nturns that source into a document for readers and can run its R code to\nproduce the results. The source therefore records how a reported number\nor figure was obtained alongside the explanation of what it means.\n\n| Output | Use in communicating a study |\n|:--|:--|\n| HTML | A report read in a browser, with links and navigation. |\n| PDF report | A professionally typeset document for reading, printing or submission. |\n| PDF presentation (Beamer) | Slides that select the study's main question, evidence and conclusions for a talk. |\n\n: Quarto outputs serve different reading and presentation purposes. {#tbl-ch05-report-formats tbl-colwidths=\"[30,70]\"}\n\nThe same calculations, equations and figures can support each format.\nA presentation still needs its content selected and organized for\nslides: changing the output format alone does not decide what an\naudience should see or how much it can read at once.\n\nFor the paired analysis, the same observations and\nsubtraction direction produce the estimate and interval quoted above.\nA change in the confidence level from .95 to .99 widens the interval\nfrom [0.7001, 2.4599] to [0.3159, 2.8441] hours, while the estimate\nstays 1.58. The report must change its confidence statement as well as\nits numbers. A reproducible source makes that connection inspectable;\nautomation cannot decide whether the interpretation remains appropriate.\n\nWhen a data-selection rule or a method changes, rerunning the source\nupdates the computed values; the interpretation still needs to be reread. A\nreproducible report keeps question, data, code, output and explanation\nconsistent. Rendering shows that a document can be produced, while the\nevidence and reasoning determine what its claims establish.\n\n## Reading Bridge {#sec-ch5-summary}\n\nWhen a study reports a mean, interval or association, identify what was\nrecorded, which observations entered the calculation, the statistic\nor comparison and its units. Next locate the repetition or model that\nsupports the SE, reference distribution, interval or test. Finally\nseparate the numerical result from the assumptions needed for population,\npractical or causal claims. R reproduces a computation; the study's\nevidence and design support its interpretation.\n\nThis chapter connected base-R descriptions to sampling variation,\nmean inference and selected correlation inference. Chapter 6 applies\nthe same reading pattern to counts and group models, introduces a small\nggplot2 plotting vocabulary, and examines fitting criteria and procedures\nacross repetitions. Chapters 7--8 extend correlations, comparisons and\nlinear adjustment into regression arguments.\n\n### Key terms {.unnumbered}\n\nUse this short reference to revisit the computing, simulation and\nmatrix terms explained here. The Part One Concept Reference gives the\nprincipal home of the descriptive and inferential terms this chapter\napplies.\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Script and Quarto source | A saved `.R` script records commands so an analysis can be rerun; a `.qmd` source connects prose, mathematics, executable code, tables, figures, and references, and renders to PDF, HTML, or Word. |\n| Simulation and seed (Monte Carlo simulation) | Generating data from a declared process to see what a statistic or procedure does across repetitions. A seed makes the random draws repeatable; it does not make the process true for an actual study. |\n| Monte Carlo standard error | The numerical uncertainty of a simulated probability or mean that comes from using finitely many repetitions; more repetitions shrink it. It is distinct from a study's SE, which depends on the study's sample size. |\n\n: Computing and simulation terms. {#tbl-ch05-computing-terms tbl-colwidths=\"[28,72]\"}\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Covariance matrix | A square table of variances on the diagonal and covariances off the diagonal for a stated set of variables and observations. |\n| Correlation matrix | A square table of pairwise correlation coefficients for a stated set of variables and observations; its diagonal is 1 for variables with positive variance. |\n\n: Data-summary terms. {#tbl-ch05-matrix-terms tbl-colwidths=\"[28,72]\"}\n\n### Further reading {.unnumbered}\n\nR's reference system [@rcore2025] and local Help for `mean`, `sd`,\n`quantile`, `t.test`, `cor`, `cov2cor` and `cor.test` describe their\narguments, defaults and computational conventions. The original papers\nby Student [-@student1908] and Welch [-@welch1947] explain the classical\nmean procedures developed here. Quarto's documentation [@quarto2026]\ngives examples of executable reports, and Peng [-@peng2011] connects\nreproducible computation with broader scientific reporting.\n\n## Exercises {.unnumbered}\n\nUse the stated records and each prompt's supplied summaries. Explain the\nstatistical meaning as well as any calculation, and report numerical\nresults to the requested precision.\n\n<!-- prompt-id: CH05-E01 -->\n\n### Exercise 1: Count the right observations (Foundational) {.unnumbered #ex-ch05-01}\n\nA table contains 40 students with one baseline and one follow-up row each,\nplus one duplicate follow-up row. There are 81 rows. Explain the difference\nbetween a row count and a student count. If four students have missing\nfollow-up scores, give the denominator for the mean observed follow-up score\nafter the documented duplicate is resolved. State what the mean describes.\n\n<!-- END EX05-01 PROMPT -->\n\n<!-- prompt-id: CH05-E02 -->\n\n### Exercise 2: Center, spread and a changed observation (Foundational) {.unnumbered #ex-ch05-02}\n\nSection 2.1's three recorded scores, 50, 60 and 70 points, have mean and\nmedian 60 and sample SD 10 points. Suppose the lowest score had\ninstead been 20.\n\n1. Before calculating, predict whether the mean, the median and the SD\n   rise, fall or stay the same, and give a reason for each.\n2. Calculate the new mean and sample SD (denominator $n-1$), reporting\n   the SD to four decimal places. Compare this SD with the one Section\n   2.1 reports after 70 is replaced by 100, and explain the comparison.\n3. Which center would you report as a typical score, and does the low\n   value alone justify removing it?\n\n<!-- END EX05-02 PROMPT -->\n\n<!-- prompt-id: CH05-E03 -->\n\n### Exercise 3: A missing score is not zero (Foundational) {.unnumbered #ex-ch05-03}\n\nIn Section 1.2, students A, B and C have baseline scores 50, 60 and 70\nand follow-up scores 55, missing and 78, and the complete-pair mean\nchange and the difference of the separate available means both equal\n6.5 points. Suppose instead that B's follow-up score is 66 and C's\nis missing.\n\n1. Before calculating, predict whether the two quantities still agree\n   and, if not, which is larger. Base the reason on which students\n   enter each mean.\n2. Calculate both quantities and state each denominator.\n3. Explain what recording C's missing score as 0 would claim, and why\n   the agreement in Section 1.2 did not show that the two calculations\n   used the same students.\n\n<!-- END EX05-03 PROMPT -->\n\n<!-- prompt-id: CH05-E04 -->\n\n### Exercise 4: Choose the group denominator (Foundational) {.unnumbered #ex-ch05-04}\n\nIn Section 2.3, 4 of 19 automatic and 10 of 13 manual car models meet a\nfuel-economy threshold: 21.0526% and 76.9231% within the transmission\ngroups, and 71.4286% of the 14 threshold-meeting models are manual.\n\n1. A report states, \"71.4286% of manual models meet the threshold.\"\n   Name the denominator the sentence implies and the one the 71.4286%\n   uses, then correct the sentence.\n2. An invented second record has the same 13 manual models and 38\n   automatic models, 8 of which meet the threshold. Before calculating,\n   predict which of the three percentages change, and why. Then\n   calculate the percentage of threshold-meeting models that are manual.\n\n<!-- END EX05-04 PROMPT -->\n\n<!-- prompt-id: CH05-E05 -->\n\n### Exercise 5: Read a relationship before evaluating it (Integrative) {.unnumbered #ex-ch05-05}\n\nSection 3.1 plots five paired observations, $x=(-2,-1,0,1,2)$ and\n$y=(4,1,0,1,4)$, whose covariance and Pearson correlation are both zero.\nDescribe the scatterplot, and use the signs of the paired deviations to\nexplain why the covariance is zero. A report says, \"The correlation is\nzero, so the variables are unrelated.\" First identify its numerical\nresult and reported conclusion, then evaluate whether that conclusion\nfollows. What happens to covariance and correlation if $y$ is\nmultiplied by 10?\n\n<!-- END EX05-05 PROMPT -->\n\n<!-- prompt-id: CH05-E06 -->\n\n### Exercise 6: Report paired differences (Integrative) {.unnumbered #ex-ch05-06}\n\nFour people have condition-1 values 1, 2, 4 and 5 and corresponding\ncondition-2 values 2, 4, 4 and 8 hours. Their condition-2-minus-condition-1\ndifferences are 1, 2, 0 and 3 hours, with mean 1.5 hours and sample SD\n1.291 hours.\n\n1. Calculate the two condition means and confirm that their difference\n   equals the mean of the differences.\n2. Suppose the condition-2 values were attached to the wrong people, in\n   the order 8, 4, 4 and 2. Before calculating anything, predict whether\n   the mean difference and the SD of the differences change, and explain\n   which summary depends on keeping each person's two values together.\n3. Write a descriptive result that names the people, direction and\n   units, and explain why it does not say that every person gained\n   1.5 hours.\n\n<!-- END EX05-06 PROMPT -->\n\n<!-- prompt-id: CH05-E07 -->\n\n### Exercise 7: Simulate a sampling distribution and read its SE (Integrative) {.unnumbered #ex-ch05-07}\n\nThe waiting-time simulation in Section 4.2 reports, for $n=30$, a mean\nof sample means of 9.9626 and an empirical SE of 1.7878 against a model\nSE of 1.8257.\n\n1. Explain what one histogram bar counts and why the empirical and model\n   SEs differ.\n2. Without running R, give the model SE for $n=120$ and for $n=480$ and\n   explain the pattern.\n3. Say what changes, and what does not, if the number of repetitions is\n   raised from 5,000 to 20,000.\n4. Rerun from the same seed with 120 waits in each sample, the\n   simulation gives an empirical SE of 0.9214 minutes. Compare it with\n   your model SE for $n=120$, and explain why the two need not agree\n   exactly.\n5. The running mean and the histograms of repeated sample means show\n   different changes as sample size increases. Explain concentration\n   toward a target and increasingly Normal standardized sampling shape,\n   and say whether either makes individual waiting times Normal.\n\n<!-- END EX05-07 PROMPT -->\n\n<!-- prompt-id: CH05-E08 -->\n\n### Exercise 8: Name the estimand, estimator, and estimate, then read the SE (Integrative) {.unnumbered #ex-ch05-08}\n\nThe special-practice study assigned 60 students to each of two formats;\nthe delayed-assessment means were 27.1 and 24.0 with SDs 6.0 and 6.4.\n\n1. State the estimand, the estimator, and the estimate in one sentence\n   each, and name the repetition behind the uncertainty.\n2. Section 4.5 calculates the SE of the mean difference from these\n   summaries as 1.1325 points. Explain why its square estimates an\n   upper bound on the assignment variance rather than the variance\n   itself.\n3. For the ten sleep differences (SD 1.23 hours), the SE of the mean\n   difference is 0.389 hours. Using the two condition SDs, 1.7890 and\n   2.0022, as if the two sets of condition measurements were independent\n   gives 0.8491 hours instead. Explain why pairing gives the smaller SE\n   for the same ten people.\n4. A separate simulation estimates a waiting-time variance of 100.\n   Across 5,000 samples of five waits, variances using the $n-1$\n   denominator average 101.2241 and those using $n$ average 80.9793.\n   Explain which rule is unbiased, why 101.2241 need not equal 100 in\n   this finite run, and why unbiasedness does not ensure that one\n   estimate is close to the target.\n\n<!-- END EX05-08 PROMPT -->\n\n<!-- prompt-id: CH05-E09 -->\n\n### Exercise 9: An interval and its question (Foundational) {.unnumbered #ex-ch05-09}\n\nTwenty-five independent paired differences have mean 3 and SD 5,\nso the estimated SE of their mean is 1 and the statistic for a zero\nprocess mean is $t=3$. Under the Normal-difference model use\n$t_{.975,24}=2.064$ to calculate the 95% interval, and explain what\n$t=3$ says about the observed mean. Then name the appropriate\nprocedures for (a) the same 20 people measured twice and (b)\nindependent groups of 20 and 25 without equal variances. State why the\ninterval is not a range for individual differences.\n\n<!-- END EX05-09 PROMPT -->\n\n<!-- prompt-id: CH05-E10 -->\n\n### Exercise 10: A selected relationship (Integrative) {.unnumbered #ex-ch05-10}\n\nSections 3 and 5.6 analyse the common 32 rows of mpg, hp and wt. Their\ncorrelations are $-.7762$ for mpg and hp, $-.8677$ for mpg and wt and\n.6587 for hp and wt; the Spearman coefficient for mpg and hp is\n$-.8947$; and `cor.test()` for the preselected weight--mpg question\nreports $t=-9.559$ on 30 df, $p<.0001$ and the 95% interval\n$[-.9338,-.7441]$.\n\n1. Explain which entries of the covariance matrix carry measurement\n   units, and why the correlation matrix alone cannot recover the\n   covariance matrix.\n2. State which association the Pearson and the Spearman coefficients\n   for mpg and hp each describe, and use the scatterplot of mpg against\n   horsepower in Section 3.3 to explain why the rank coefficient is\n   larger in magnitude.\n3. Calculate the partial correlation of mpg and hp controlling linearly\n   for weight from the supplied correlations, give the df of its\n   classical test, and explain why the adjustment alone does not\n   establish a causal effect.\n4. Report the preselected weight--mpg result with its estimate,\n   interval and the conditions supporting its reference, and explain\n   why the interval is not symmetric about $-.8677$.\n\n<!-- END EX05-10 PROMPT -->\n\n## References {.unnumbered}\n",
    "supporting": [
      "chapter_05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}