{
  "hash": "a77fd32478d9818acdb8db663e91b164",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Group Comparisons and Statistical Modelling with R\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: true\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\widowpenalty=10000\n          \\clubpenalty=10000\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\linespread{0.95}\\selectfont\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{10\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\n::: {.callout-note title=\"Chapter overview\"}\nChapter 5 made estimates, intervals and tests executable in base R. Here we\nreturn to Chapter 4's group comparisons and use R to connect a fitted model\nwith the question it answers. We begin with three condition means from\nChapter 4's background-sound experiment and compare selected differences\ninside stated families. We then examine a six-cell pattern from its\nfeedback-by-practice study and test how one comparison changes across a\nsecond factor by comparing two named models on the same records.\n\nCounts require a different response model, and the size of a difference\nbetween two groups' proportions can be stated on several scales, which we\nset side by side. The same counts provide a small example of likelihood,\nwhich makes a fitting criterion explicit. Finally, simulation examines\nprocedures under a stated generating process, and planning relates sample\nsize to either power or interval width. Throughout, a useful result keeps\nits data, target, uncertainty calculation and conditions together.\n:::\n\nStudies rarely stop at one mean. Chapter 4's invented background-sound\nexperiment compares mean reading comprehension under three conditions,\nsilence, instrumental music and music with lyrics, and its second\ninvented study asks how the difference between spaced and massed\npractice changes across three kinds of feedback. Means that differ in a\nrecord differ for more than one reason, so the question is what a stated\nmodel and its conditions let us say about several means at once, and\nwhat a single answer to that question leaves unsettled. Both studies are\ninvented teaching inputs, so each analysis shows what a procedure\nreports, not what background sound or feedback does.\n\n## Fit and read group means {#ch06-group-models}\n\n### Begin with the question and records\n\nDoes mean reading comprehension differ across three background-sound\nconditions? Chapter 4 developed this question with an invented experiment.\nEach of thirty first-year university students read the same passage for\n20 minutes and then answered a 20-item reading-comprehension quiz, scored\nfrom 0 to 20. Ten students were randomly assigned to each sound condition:\nSilence, Instrumental music or Music with lyrics. Each student supplies\none quiz score, so @tbl-ch06-sound-data holds thirty scores from thirty\ndifferent students.\n\n| Sound condition | Scores (out of 20) |\n|:--|:--|\n| Silence | 8, 9, 9, 11, 12, 13, 13, 14, 15, 16 |\n| Instrumental music | 6, 8, 8, 9, 9, 11, 11, 12, 12, 14 |\n| Music with lyrics | 4, 5, 6, 7, 8, 8, 9, 10, 11, 12 |\n\n: The same 30 invented comprehension scores as Chapter 4. {#tbl-ch06-sound-data tbl-colwidths=\"[30,70]\"}\n\nThese values were constructed to keep the calculations transparent. They\nare teaching inputs, not empirical findings about music and reading. The\nstudent is both the unit of random assignment and the unit of\nmeasurement: the ten scores in a condition come from ten different\nstudents, not from repeated measurements of one student. Silence is the\nnatural reference condition, so it comes first.\n\nThe following code creates the complete data. The factor levels fix the\ndisplay order, make Silence the reference level for later model\ncoefficients and fix the direction of each subtraction. The course data\nfile `background_sound.csv` holds the same thirty rows with a student\nidentifier; reading it with `read.csv()` and applying the same `factor()`\nlevels gives identical results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsound_data <- data.frame(\n  sound = factor(rep(c(\"Silence\", \"Instrumental music\",\n    \"Music with lyrics\"), each = 10),\n    levels = c(\"Silence\", \"Instrumental music\",\n      \"Music with lyrics\")),\n  score = c(8, 9, 9, 11, 12, 13, 13, 14, 15, 16,\n    6, 8, 8, 9, 9, 11, 11, 12, 12, 14,\n    4, 5, 6, 7, 8, 8, 9, 10, 11, 12))\ntable(sound_data$sound)\n#> \n#>            Silence Instrumental music  Music with lyrics \n#>                 10                 10                 10\nwith(sound_data, tapply(score, sound, mean))\n#>            Silence Instrumental music  Music with lyrics \n#>                 12                 10                  8\nwith(sound_data, tapply(score, sound, sd))\n#>            Silence Instrumental music  Music with lyrics \n#>        2.708012802        2.403700850        2.581988897\n```\n:::\n\n\nEach condition holds ten students. The condition means are 12, 10 and 8\ncorrect answers, and the grand mean of all thirty scores is 10. The SDs,\n2.7080, 2.4037 and 2.5820, are similar without being identical. Before\nasking whether a difference is large relative to its uncertainty, we can\nsee each difference on the quiz's own scale: Instrumental music lies\n2 points and Music with lyrics 4 points below Silence.\n\n@fig-ch06-sound-groups shows every student beside the three condition\nmeans. Each point is one student's score, moved a small random distance\nsideways so that equal scores in a condition stay visible, and each\ndiamond marks a condition mean. Two kinds of variation appear together.\nThe diamonds step down by 2 points from Silence to Instrumental music and\nby another 2 points to Music with lyrics, while the ten scores in each\ncondition spread across 8 points around their own diamond. Whether a\n2-point step is large depends on that spread within conditions, and the\nmodel below turns this visual comparison into numbers.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Individual comprehension scores and their three condition means.](chapter_06_files/figure-html/fig-ch06-sound-groups-1.png){#fig-ch06-sound-groups fig-alt='Ten scores in each of Silence, Instrumental music and Music with lyrics, spread slightly sideways so that tied scores stay visible, lie around means 12, 10 and 8. Larger diamonds mark the means; the three spreads are similar.' width=614.4}\n:::\n:::\n\n\nThe figure is drawn with the `ggplot2` package, which describes a graph\nas a data frame, a mapping of variables to position or colour, and layers\nof marks; Computer Lab 6 builds it one layer at a time and sets this way\nof working beside base R and the wider tidyverse.\n\n### Fit the group model and read its decomposition\n\nFor student $i$ in sound condition $j$, the one-way model is\n\n$$\nY_{ij}=\\mu_j+\\varepsilon_{ij}.\n$$\n\nHere $\\mu_j$ is the condition's process mean and $\\varepsilon_{ij}$ is its\nstudent's deviation from that mean. Fitting by least squares estimates\neach $\\mu_j$ with the corresponding sample mean, so\n$\\widehat Y_{ij}=\\bar Y_j$. The residual is $e_{ij}=y_{ij}-\\bar y_j$: an\nobserved score minus its fitted condition mean. For Silence the fitted\nvalues are all 12 and the residuals are $-4,-3,-3,-1,0,1,1,2,3,4$.\n\nThe model separates differences between conditions from differences\namong students within a condition. Chapter 4's decomposition becomes\n\n$$\n\\begin{aligned}\nSS_T&=\\sum_{j}\\sum_i(y_{ij}-\\bar y)^2=SS_B+SS_W,\\\\\nSS_B&=\\sum_j n_j(\\bar y_j-\\bar y)^2,\\\\\nSS_W&=\\sum_j\\sum_i(y_{ij}-\\bar y_j)^2.\n\\end{aligned}\n$$\n\nThe total measures deviation from the grand mean. The between-group term\nmeasures deviation of the three condition means from that grand mean,\nweighted by their group counts. The within-group term measures deviation\nof students from their own fitted condition means. In this example,\n$SS_B=10(12-10)^2+10(10-10)^2+10(8-10)^2=80$. The squared residuals\nwithin Silence, Instrumental music and Music with lyrics sum to 66, 52\nand 60, giving $SS_W=178$ and $SS_T=80+178=258$. In\n@fig-ch06-sound-groups these are the steps between the diamonds and the\nspread of the points around them.\n\nThe formula `score ~ sound` tells `aov()` to explain score using the\nsound factor, and `anova()` extracts the decomposition from the fitted\nobject.\n\n\\Needspace{10\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_fit <- aov(score ~ sound, data = sound_data)\nanova(one_fit)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|          | Df| Sum Sq|      Mean Sq|    F value|      Pr(>F)|\n|:---------|--:|------:|------------:|----------:|-----------:|\n|sound     |  2|     80| 40.000000000| 6.06741573| 0.006665059|\n|Residuals | 27|    178|  6.592592593|         NA|          NA|\n\n</div>\n:::\n:::\n\n\nThree fitted condition means use three parameters. Consequently the\nwithin-group degrees of freedom are $30-3=27$. The between-group component\nhas $3-1=2$ degrees of freedom, and the total has $30-1=29$. Dividing each\nsum of squares by its degrees of freedom gives a mean square. The\nwithin-group mean square $MS_W=178/27=6.5926$ estimates the common error\nvariance.\n\n| Source | SS | df | MS | F | p |\n|:--|--:|--:|--:|--:|--:|\n| Sound condition | 80 | 2 | 40.0000 | 6.0674 | .0067 |\n| Within groups | 178 | 27 | 6.5926 | | |\n| Total | 258 | 29 | | | |\n\n: One-way ANOVA on the thirty background-sound scores. {#tbl-ch06-oneway}\n\nThe null hypothesis is $H_0:\\mu_S=\\mu_I=\\mu_L$ for Silence, Instrumental\nmusic and Music with lyrics. Under independent Normal errors with a common\nvariance, the ratio\n\n$$\nF=\\frac{MS_B}{MS_W}=\\frac{40}{178/27}=6.0674\n$$\n\nhas an $F_{2,27}$ reference distribution when that null holds. The p-value\n.0067 is the probability, under this null model, of an F statistic at least\nthis large. At a .05 threshold it provides evidence against equal process\nmeans. It does not say that every pair of conditions differs, that every\nkind of background sound changes comprehension, or that the invented\nresult establishes a real effect of music on reading. The next section\nasks the individual comparison questions.\n\nThe observed share of score variation associated with these condition\nmeans is\n\n$$\n\\eta^2=\\frac{SS_B}{SS_T}=\\frac{80}{258}=.3101.\n$$\n\nThis is an in-sample variation summary, accompanying differences expressed\nin score points. It is neither the probability that background sound\ncaused a result nor a replacement for a confidence interval. The\nbias-adjusted omega-squared of Chapter 4, Appendix B.2, is .2525 for\nthese scores, and the Computer Lab rebuilds both summaries from the scores.\n\n### Express the same fit with indicators\n\nA factor with three levels can also enter a linear model as two indicator\nvariables. Let $D_I=1$ for Instrumental music and 0 otherwise, and let\n$D_L=1$ for Music with lyrics and 0 otherwise. Silence has both indicators\n0. The fitted equation is\n\n$$\n\\widehat y=12-2D_I-4D_L.\n$$\n\nSubstituting the indicators gives 12 for Silence, $12-2=10$ for\nInstrumental music and $12-4=8$ for Music with lyrics. The intercept is\nthe reference mean; each other coefficient is a difference from that mean,\nnegative here because both music conditions have lower means than Silence.\nThe factor order in the original setup makes Silence the reference level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nindicator_fit <- lm(score ~ sound, data = sound_data)\ncoef(indicator_fit)\n#>             (Intercept) soundInstrumental music \n#>                      12                      -2 \n#>  soundMusic with lyrics \n#>                      -4\n```\n:::\n\n\n`lm()` and `aov()` describe the same set of fitted means, so they give the\nsame residuals and the same ANOVA table. The formula names the outcome and\nthe explanatory variable; the study's design supplies the independence\nassumption. A different reference level changes which comparisons the\ncoefficients name, but not the fitted means, the residuals or the table:\nwith Instrumental music as the reference, the coefficients become 10, 2\nand $-2$. This indicator representation prepares the named models of\nSection 3.2. Chapter 7 develops a continuous predictor's slope, and\nChapter 8 extends the conditional interpretation to several predictors.\n\n## Ask comparisons within stated families {#ch06-contrast-families}\n\n### Specify the comparison and its standard error\n\nSuppose the two questions compare each music condition with Silence:\nInstrumental music versus Silence, and Music with lyrics versus Silence.\nIn the order Silence, Instrumental music, Music with lyrics, their\ncoefficient vectors are $(-1,1,0)$ and $(-1,0,1)$. Each vector sums to\nzero. A quantity\n\n$$\nC=\\sum_jc_j\\mu_j,\\qquad \\sum_jc_j=0,\n$$\n\nis a contrast of the process means. Its estimate replaces process means with\nthe observed group means:\n$\\widehat C=\\sum_jc_j\\bar y_j$. Thus our estimates are $-2$ and $-4$\npoints: both music conditions lie below Silence. Calling a comparison a\ncontrast specifies this mathematical form; it does not say whether the\ncomparison was planned before seeing the results or selected afterward.\nThat is additional information about the analysis.\n\nFor independent groups with a common error variance, Chapter 4 extends\nChapter 3's pooled SE, $s_p\\sqrt{1/n_1+1/n_0}$, from two means to a\ncontrast by replacing $s_p^2$ with $MS_W$:\n\n$$\nSE(\\widehat C)=\\sqrt{MS_W\\sum_j\\frac{c_j^2}{n_j}}.\n$$\n\nEach comparison uses two of the means, so both have estimated SE\n$\\sqrt{(178/27)(1/10+1/10)}=1.1483$ points. The third condition still\ncontributes to the common error estimate and its 27 residual degrees of\nfreedom. This matters when comparing these results with an analysis\nrestricted to only two conditions.\n\n### Calibrate the two-comparison family\n\nAn individual 95% interval uses a .05 error probability for that one\ncomparison. The declared family here is *each music condition against\nSilence*. To cover both of its comparisons with at least 95% familywise\nconfidence, Bonferroni allocates .025 to each two-sided comparison. Each\ntail then receives $.05/(2\\times2)=.0125$. The calibration uses the $t$\nreference distribution with the model's 27 residual degrees of freedom\n[@student1908], giving the critical value\n\n$$\nt_{1-.05/(2\\times2),27}=2.3734.\n$$\n\nThe calculations retain the same estimates and SEs but multiply each SE by\nthis larger critical value. The following code extracts the common variance\nestimate from the fitted object and calculates both results from unrounded\ninputs.\n\n\\Needspace{8\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmse <- deviance(one_fit) / df.residual(one_fit)\nmeans <- with(sound_data, tapply(score, sound, mean))\nestimate <- c(Instrumental = unname(means[2] - means[1]),\n  Lyrics = unname(means[3] - means[1]))\nse <- sqrt(mse * (1/10 + 1/10))\ncritical <- qt(1 - .05/(2*2), df.residual(one_fit))\nraw_p <- 2 * pt(-abs(estimate/se), df.residual(one_fit))\ncbind(estimate, SE = se, lower = estimate-critical*se,\n  upper = estimate+critical*se,\n  adjusted_p = p.adjust(raw_p, method = \"bonferroni\"))\n#>              estimate          SE        lower         upper\n#> Instrumental       -2 1.148267616 -4.725318112  0.7253181116\n#> Lyrics             -4 1.148267616 -6.725318112 -1.2746818884\n#>                  adjusted_p\n#> Instrumental 0.185869921135\n#> Lyrics       0.003408398659\n```\n:::\n\n\n| Comparison | Estimate | SE | Simultaneous interval | Adjusted p |\n|:--|--:|--:|:--|--:|\n| Instrumental music minus Silence | $-2$ | 1.1483 | [$-4.7253$, 0.7253] | .1859 |\n| Music with lyrics minus Silence | $-4$ | 1.1483 | [$-6.7253$, $-1.2747$] | .0034 |\n\n: Bonferroni results for the declared family of two comparisons. {#tbl-ch06-bonferroni tbl-colwidths=\"[34,13,11,28,14]\"}\n\nMultiplying each raw p-value by two and capping at one gives the\ncorresponding Bonferroni-adjusted p-value. Music with lyrics minus Silence\nis distinguishable from zero with this familywise calibration: its whole\ninterval lies below zero. The Instrumental-music interval includes zero\nalthough the omnibus ANOVA rejected equality. It allows a difference from\n4.7253 points below Silence to 0.7253 points above it. The two results are\ncompatible, because the omnibus test and each contrast address different\nstatements.\n\nThe family calibration has a purpose and a price. Chapter 4, Section 3.3,\ndefined the familywise error rate as the probability that a declared\nfamily produces at least one false rejection when every null in it holds.\nTwo independent comparisons, each calibrated at .05, would leave that rate\nat $1-.95^2=.0975$. These two comparisons share the Silence mean, and\ndividing .05 across the family bounds the rate at .05 under any\ndependence between them. The guarantee is paid for in width, which\nSection 2.3 compares, and in power. Suppose a replication of this study\nused three balanced groups and took this study's error SD,\n$\\sqrt{178/27}=2.5676$, as its planning value. A 2-point difference would\nfirst reach .8 power at 27 students per group when the comparison stands\nalone, and at 33 per group when it belongs to the two-comparison family.\nSection 6 shows how such targets are calculated, there with the smaller\nplanning SD of the feedback study. Declare the family from the question\nbefore seeing the results; enlarging it afterwards spends that power on\nquestions nobody asked.\n\n### Compare with an all-pairs family\n\nIf the question includes every pair, there are three comparisons. Tukey's\nprocedure uses the joint distribution of pairwise mean differences under the\ncommon-variance Normal-error model. `TukeyHSD()` supplies those simultaneous\nintervals and their adjusted p-values [@tukey1953].\n\n\\Needspace{8\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(one_fit, \"sound\", conf.level = .95)\n#>   Tukey multiple comparisons of means\n#>     95% family-wise confidence level\n#> \n#> Fit: aov(formula = score ~ sound, data = sound_data)\n#> \n#> $sound\n#>                                      diff         lwr\n#> Instrumental music-Silence             -2 -4.84703504\n#> Music with lyrics-Silence              -4 -6.84703504\n#> Music with lyrics-Instrumental music   -2 -4.84703504\n#>                                                upr        p adj\n#> Instrumental music-Silence            0.8470350401 0.2084569155\n#> Music with lyrics-Silence            -1.1529649599 0.0046975772\n#> Music with lyrics-Instrumental music  0.8470350401 0.2084569155\n```\n:::\n\n\nThe output labels each subtraction direction. Music with lyrics minus\nSilence is $-4$, with interval [$-6.847$, $-1.153$] and adjusted p\n.0047. Instrumental music minus Silence and Music with lyrics minus\nInstrumental music both equal $-2$, with interval [$-4.847$, 0.847] and\nadjusted p .2085. @tbl-ch06-calibrations sets one comparison, Instrumental\nmusic minus Silence, under the three calibrations met so far.\n\n\\Needspace{8\\baselineskip}\n\n| Calibration | Family protected | Multiplier | 95% interval |\n|:--|:--|--:|:--|\n| Pointwise t | This comparison alone | 2.0518 | [$-4.3561$, 0.3561] |\n| Bonferroni | The two comparisons with Silence | 2.3734 | [$-4.7253$, 0.7253] |\n| Tukey | All three pairs | 2.4794 | [$-4.8470$, 0.8470] |\n\n: Instrumental music minus Silence, $-2$ points with SE 1.1483, under three calibrations. {#tbl-ch06-calibrations tbl-colwidths=\"[17,39,16,28]\"}\n\nThe estimate, $-2$, and its SE, 1.1483, are the same in every row; only\nthe multiplier changes. A larger protected family needs a larger\nmultiplier to hold its familywise error rate at .05, so its intervals are\nwider. An interval should therefore be read together with the comparison\nand the family it represents.\n\nThe all-pairs family also covers a comparison chosen after seeing the\nmeans. Suppose Music with lyrics minus Silence were reported because it is\nthe largest observed difference. That choice looked at all three pairs, so\nits calibration would come from the all-pairs family, [$-6.8470$,\n$-1.1530$], rather than from the declared two-comparison family,\n[$-6.7253$, $-1.2747$]. An omnibus rejection does not by itself protect\nany comparison selected after examining the means. Conversely, a\nseparately specified contrast can have its own valid uncertainty procedure\nwithout requiring omnibus rejection as an automatic preliminary gate. The\nrelevant information is the question, selection process and calibration,\nrather than a universal sequence of significance decisions.\n\n### Check what changes when the variance model changes\n\nThe common-variance model assumes that within-group variability estimates\none shared error variance. In a real study, design information and observed\npatterns help assess that working model. A small normality or variance test\ncannot certify it, and ten students per condition give limited information\nabout the error distribution. In these invented data the three SDs, 2.7080,\n2.4037 and 2.5820, are similar by construction, and every condition's\nresiduals lie between $-4$ and 4. In @fig-ch06-sound-groups each residual\nis a point's vertical distance from its diamond, and the three conditions\nspread alike.\n\nFor independent groups whose error variances may differ, Welch's one-way\nprocedure provides an alternative [@welch1947]. It is the several-group\ncounterpart of Chapter 3's Welch t test, as Chapter 4's conditions section\nexplains. R selects it by default in `oneway.test()` [@rcore2025]:\n\n\\Needspace{8\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\noneway.test(score ~ sound, data = sound_data)\n#> \n#> \tOne-way analysis of means (not assuming equal variances)\n#> \n#> data:  score and sound\n#> F = 5.5144397, num df = 2.000000, denom df = 17.956056,\n#> p-value = 0.01358053\n```\n:::\n\n\nIt gives $F(2, 17.9561)=5.5144$ and p .0136, beside the pooled\n$F(2,27)=6.0674$ and p .0067. Welch weights each condition mean by\n$n_j/s_j^2$, the inverse of its own estimated sampling variance, and\nrefers the statistic to fewer denominator degrees of freedom because each\ncondition now estimates its own variance. With similar observed SDs the\ntwo procedures reach the same conclusion at .05, while their p-values\ndiffer. Each p-value belongs to its own variance model and small-sample\ncalibration, so the two are results to explain through those assumptions\nrather than votes on which numerical conclusion to prefer. With small\ngroups or clearly unequal spreads, the model choice can matter\nappreciably.\n\nA useful exact identity connects Chapter 3's equal-variance (pooled)\ntwo-sample t test, requested with `var.equal = TRUE`, with a two-group\nANOVA: $F=t^2$, with the same two-sided p-value. It requires the same records,\nequal-variance denominator and group comparison. R's default `t.test()` is\nWelch's test, Chapter 3's last t procedure, and does not meet that\nspecification. Nor is our three-group contrast the same calculation,\nbecause it uses residual information from the third condition. The\nComputer Lab reproduces the matched identity for Silence and Instrumental\nmusic.\n\n## Compare a two-way pattern {#ch06-factorial-comparisons}\n\n### Read cells and margins before fitting\n\nChapter 4's second study asks how one comparison changes across a second\nfactor. In this invented study, each of 24 pupils was individually\nassigned to one combination of feedback (Rereading, Answer feedback or\nExplanatory feedback) and practice (Massed or Spaced). The outcome is the\nnumber correct on a 20-item assessment. A cell is one combination of\nfeedback and practice, and four pupils contribute scores to each cell in\n@tbl-ch06-feedback-data. The question is how the Spaced-minus-Massed\ncomparison changes across feedback conditions.\n\n| Feedback | Massed scores | Spaced scores |\n|:--|:--|:--|\n| Rereading | 4, 5, 7, 8 | 4, 5, 7, 8 |\n| Answer feedback | 6, 7, 9, 10 | 10, 11, 13, 14 |\n| Explanatory feedback | 8, 9, 11, 12 | 16, 17, 19, 20 |\n\n: The same 24 authored scores as Chapter 4. {#tbl-ch06-feedback-data tbl-colwidths=\"[35,32,33]\"}\n\nThese values were constructed to make the calculations transparent. They are\nteaching inputs, not empirical evidence that one feedback condition works\nbetter. Each score comes from a different pupil; the four scores within a cell\nare not repeated measurements of one pupil. Repeated patterns in their\ndeviations were deliberately chosen and cannot establish assumptions about a\npopulation.\n\nThe following code creates the complete data. The factor levels specify\nthe display order and the reference levels for later model coefficients.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeedback_data <- data.frame(\n  student = 1:24,\n  feedback = factor(rep(c(\"Rereading\", \"Answer feedback\",\n    \"Explanatory feedback\"), each = 8),\n    levels = c(\"Rereading\", \"Answer feedback\",\n      \"Explanatory feedback\")),\n  practice = factor(rep(rep(c(\"Massed\", \"Spaced\"),\n    each = 4), 3), levels = c(\"Massed\", \"Spaced\")),\n  score = c(4,5,7,8, 4,5,7,8, 6,7,9,10, 10,11,13,14,\n    8,9,11,12, 16,17,19,20))\n```\n:::\n\n\nComputing cell counts and means before fitting any model makes the six\ncells and their denominators visible.\n\n\\Needspace{15\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith(feedback_data, table(feedback, practice))\n#>                       practice\n#> feedback               Massed Spaced\n#>   Rereading                 4      4\n#>   Answer feedback           4      4\n#>   Explanatory feedback      4      4\ncell_mean <- with(feedback_data,\n  tapply(score, list(feedback, practice), mean))\ncell_mean\n#>                      Massed Spaced\n#> Rereading                 6      6\n#> Answer feedback           8     12\n#> Explanatory feedback     10     18\n```\n:::\n\n\n\\Needspace{12\\baselineskip}\n\n@tbl-ch06-cell-means adds the margins and the three practice changes to\nthese cell means.\n\n| Feedback | Massed | Spaced | Equally weighted margin | Spaced minus Massed |\n|:--|--:|--:|--:|--:|\n| Rereading | 6 | 6 | 6 | 0 |\n| Answer feedback | 8 | 12 | 10 | 4 |\n| Explanatory feedback | 10 | 18 | 14 | 8 |\n| Practice margin | 8 | 12 | 10 | 4 |\n\n: Cell means and equally weighted margins of the balanced design. {#tbl-ch06-cell-means tbl-colwidths=\"[31,12,12,23,22]\"}\n\nEach cell has four pupils, so averaging the two practice cells equally gives\nthe feedback group's overall mean. Similarly, each practice margin averages\nequally across the three feedback conditions. In an unbalanced design, a\nmargin must specify its weights: the observed mix of pupils and an equally\nweighted target can answer different questions.\n\n@fig-ch06-feedback-interaction draws the six cell means with one line for\neach feedback condition. Each line joins two separate cell means; it does\nnot trace individual pupils across repeated measurements.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The practice difference depends on feedback.](chapter_06_files/figure-html/fig-ch06-feedback-interaction-1.png){#fig-ch06-feedback-interaction fig-pos='!ht' fig-alt='Rereading joins 6 to 6, Answer feedback joins 8 to 12, and Explanatory feedback joins 10 to 18 from Massed to Spaced. The lines have different slopes.' width=614.4}\n:::\n:::\n\n\nThe observed changes are 0, 4 and 8 points, so the three lines have\ndifferent slopes. This describes interaction in the observed means.\nInference about a process interaction additionally requires a model and a\nmeasure of residual variation.\n\n### Fit the full model, identify its tests and compare nested models\n\nChapter 4 wrote the two-way model as\n\n$$\nY_{ijk}=\\mu+\\alpha_j+\\beta_k+(\\alpha\\beta)_{jk}\n  +\\varepsilon_{ijk},\n$$\n\nwhere $j$ indexes feedback, $k$ indexes practice and $i$ indexes pupils\nwithin a cell. With the usual sum-to-zero constraints, $\\mu$ is the grand\nmean, $\\alpha_j$ and $\\beta_k$ describe departures of the margins from it,\nand $(\\alpha\\beta)_{jk}$ describes the remaining cell departure. The\nconstraints make this representation identifiable: the effects cannot all\nshift freely while leaving the same fitted means.\n\nThere is one grand-mean parameter, $3-1=2$ feedback degrees of freedom,\n$2-1=1$ practice degree of freedom, and $(3-1)(2-1)=2$ interaction degrees\nof freedom. Together these describe six fitted cell means. The model\ntherefore has $24-6=18$ residual degrees of freedom. In an R formula,\n`feedback * practice` includes both main effects and their interaction.\nIt expands to `feedback + practice + feedback:practice`.\n\n\\Needspace{12\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntwo_fit <- aov(score ~ feedback * practice,\n  data = feedback_data)\nanova(two_fit)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                  | Df| Sum Sq|       Mean Sq| F value|       Pr(>F)|\n|:-----------------|--:|------:|-------------:|-------:|------------:|\n|feedback          |  2|    256| 128.000000000|    38.4| 0.0000003208|\n|practice          |  1|     96|  96.000000000|    28.8| 0.0000422875|\n|feedback:practice |  2|     64|  32.000000000|     9.6| 0.0014540056|\n|Residuals         | 18|     60|   3.333333333|      NA|           NA|\n\n</div>\n:::\n:::\n\n\n\\Needspace{9\\baselineskip}\n\n| Source | SS | df | MS | F | p |\n|:--|--:|--:|--:|--:|--:|\n| Feedback | 256 | 2 | 128.0000 | 38.4 | < .0001 |\n| Practice | 96 | 1 | 96.0000 | 28.8 | < .0001 |\n| Interaction | 64 | 2 | 32.0000 | 9.6 | .0015 |\n| Residual | 60 | 18 | 3.3333 | | |\n| Total | 476 | 23 | | | |\n\n: Full balanced factorial decomposition. {#tbl-ch06-factorial}\n\nThe feedback test concerns equality of feedback margins averaged equally\nover practice. The practice test concerns equality of practice margins\naveraged equally over feedback. The interaction test asks whether the\npractice difference is the same across all feedback conditions. With\nindependent Normal errors of common variance, its null reference is\n$F_{2,18}$; the observed value 9.6 and p .0015 provide evidence against\nthat common-difference null.\n\nThe balanced layout makes the source components orthogonal: the variation\nattributed to one component does not compete with another component for\nthe same fitted direction. A single-model `anova()` table ordinarily uses\nsequential sums of squares, entering terms in formula order. This convenient\nbalanced decomposition should not be extended automatically to unbalanced\ndata.\n\nTo see why, suppose the two Explanatory–Spaced pupils who scored 19 and 20\nwere unavailable. The cell counts become 4, 4, 4, 4, 4 and 2, and the full\nmodel leaves $22-6=16$ residual degrees of freedom. The equally weighted\nSpaced margin is then $(6+12+16.5)/3=11.5$, whereas the mean of the ten\nremaining Spaced pupils is 10.5: two answers to two different questions.\n@tbl-ch06-unbalanced refits the full model to the 22 remaining pupils with\nthe formula written in each order.\n\n\\Needspace{10\\baselineskip}\n\n| Term | Formula `feedback * practice` | Formula `practice * feedback` |\n|:--|--:|--:|\n| Feedback | 139.7576 | 157.7500 |\n| Practice | 52.0833 | 34.0909 |\n| Interaction | 36.2500 | 36.2500 |\n| Residual | 50.5000 | 50.5000 |\n\n: Sequential sums of squares for the 22 remaining pupils, by the order of the formula. {#tbl-ch06-unbalanced tbl-colwidths=\"[28,36,36]\"}\n\nSequential sums of squares give each term only what the terms entered\nbefore it have not taken. The feedback and practice rows therefore move\nwith the order, while the interaction and the residual stay where they\nare. With unequal cells, one sequential table does not supply order-free\ntests of the main effects. Naming the two models to be compared does.\n\nThe interaction row can itself be read as a comparison of two fits to the\nsame 24 pupils. The **additive model**, `score ~ feedback + practice`,\ngives every feedback condition the same Spaced-minus-Massed difference;\nthe **full model**, `score ~ feedback * practice`, lets that difference\nvary. For nested models fitted to the same response and records, with\nresidual sum of squares $RSS_0$ on $df_0$ degrees of freedom for the\nsmaller model and $RSS_1$ on $df_1$ for the larger,\n\n$$\nF=\\frac{(RSS_0-RSS_1)/(df_0-df_1)}{RSS_1/df_1}\n=\\frac{(124-60)/(20-18)}{60/18}=9.6,\n$$\n\nwith the denominator taken from the larger model. The following code fits\nboth models with `lm()` and compares them.\n\n\\Needspace{8\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadditive_fit <- lm(score ~ feedback + practice, data = feedback_data)\nfull_fit <- lm(score ~ feedback * practice, data = feedback_data)\ncoef(additive_fit)\n#>                  (Intercept)      feedbackAnswer feedback \n#>                            4                            4 \n#> feedbackExplanatory feedback               practiceSpaced \n#>                            8                            4\nanova(additive_fit, full_fit)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df| RSS| Df| Sum of Sq|   F|       Pr(>F)|\n|------:|---:|--:|---------:|---:|------------:|\n|     20| 124| NA|        NA|  NA|           NA|\n|     18|  60|  2|        64| 9.6| 0.0014540056|\n\n</div>\n:::\n:::\n\n\nThe additive coefficients, 4 for Rereading under Massed practice, 4 and 8\nfor Answer and Explanatory feedback minus Rereading, and 4 for Spaced\nminus Massed, show the single practice difference that the smaller model\nimposes. The comparison returns $F(2,18)=9.6$ and $p=.0015$: the\ninteraction row of @tbl-ch06-factorial, now read as a question about two\nnamed models. Because it names both models, no term's position in a\nformula enters it. For the 22 remaining pupils, the additive model (RSS\n86.75 on 18 df) against the full model (RSS 50.50 on 16 df) gives\n$F(2,16)=5.7426$ and $p=.0132$, whichever order the formula uses. Keep\nthe response and the records explicitly the same, because default removal\nof missing values can otherwise change the comparison. Chapter 9,\nSection 2, uses the same comparison of named models for the analysis of\ncovariance and its parallel-slopes check.\n\nThe feedback and practice margins remain meaningful descriptions, but the\ninteraction clarifies their limits. For example, the 4-point overall practice\ndifference averages a 0-point, a 4-point and an 8-point difference. A result\nparagraph should convey this varying pattern when the scientific question\nconcerns how practice works across feedback conditions.\n\n### Work the selected difference of differences completely\n\nConsider Answer feedback's practice change minus Rereading's practice change:\n\n$$\n\\widehat{DD}=(12-8)-(6-6)=4.\n$$\n\nThe contrast has coefficients $(1,-1,-1,1)$ in the cell order\nRereading–Massed, Rereading–Spaced, Answer–Massed, Answer–Spaced.\nIts four cell means come from different pupils. Under the common-variance\nmodel, their variances therefore add after multiplying by the squared\ncoefficients:\n\n$$\nSE(\\widehat{DD})=\n\\sqrt{MS_E\\left(\\frac14+\\frac14+\\frac14+\\frac14\\right)}\n=1.8257.\n$$\n\nThe omnibus interaction spans two independent directions. For simultaneous\nconfidence over all contrasts in that two-dimensional interaction space,\nScheffe's method uses the multiplier\n\n$$\n\\sqrt{2F_{.95;2,18}}=2.6663.\n$$\n\nThe complete calculation keeps the cell subtraction, residual variance and\nfamily calibration visible:\n\n\\Needspace{13\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndd <- (cell_mean[\"Answer feedback\", \"Spaced\"] -\n  cell_mean[\"Answer feedback\", \"Massed\"]) -\n  (cell_mean[\"Rereading\", \"Spaced\"] -\n  cell_mean[\"Rereading\", \"Massed\"])\nmse_two <- deviance(two_fit) / df.residual(two_fit)\nse_dd <- sqrt(mse_two * 4/4)\nscheffe <- sqrt(2 * qf(.95, 2, 18))\nc(estimate = dd, SE = se_dd, multiplier = scheffe)\n#>    estimate          SE  multiplier \n#> 4.000000000 1.825741858 2.666292237\ndd + c(-1, 1) * scheffe * se_dd\n#> [1] -0.8679613431  8.8679613431\n```\n:::\n\n\nThe resulting interval is $4\\pm2.6663(1.8257)=[-0.868,8.868]$.\nIt includes zero even though the interaction F test rejects its null.\nThe F test asks whether both interaction directions are zero jointly;\nthis interval addresses one selected direction while allowing for the\nentire family. Other directions can carry substantial evidence, and a\nsimultaneous interval for this direction can remain broad. Neither result\ncancels the other.\n\n@tbl-ch06-dd-quantities sets the selected DD beside Answer feedback's\nsimple practice effect, which happens to share its estimate, 4.\n\n\\Needspace{9\\baselineskip}\n\n| Quantity | Estimate | SE | 95% interval | Calibration |\n|:--|--:|--:|:--|:--|\n| Answer's simple practice effect | 4 | 1.2910 | [1.2877, 6.7123] | Pointwise |\n| Answer-minus-Rereading DD | 4 | 1.8257 | [0.1643, 7.8357] | Pointwise |\n| Answer-minus-Rereading DD | 4 | 1.8257 | [$-0.8680$, 8.8680] | Scheffé |\n\n: Three quantities from the interaction section; the Scheffé interval covers the two-dimensional interaction family. {#tbl-ch06-dd-quantities tbl-colwidths=\"[38,11,10,25,16]\"}\n\nThe simple effect compares only two cell means, so its SE is smaller. It\nalso contains the overall practice component as well as an interaction\ncomponent, so it lies outside the interaction-only family, and the\nScheffé guarantee does not transfer to it. The DD's two intervals differ\nonly in their multiplier: the pointwise interval excludes zero and the\nsimultaneous one includes it. Choosing the narrower interval after seeing\nwhich conclusion it gives does not keep the family's guarantee. State\nwhich quantity was selected, which family was considered and which\ninterval was used before interpreting a result.\n\nReport the interaction's magnitude in score points first. The practice\ndifference is 0 points under Rereading, 4 under Answer feedback and 8 under\nExplanatory feedback, and the selected DD is 4 points with SE 1.8257. A\nvariation share may follow once its denominator is named. The interaction\nsum of squares is $64/476=.1345$ of the total sum of squares, but\n$64/124=.5161$ of the interaction and residual sums of squares together.\nBoth shares are in-sample summaries of an authored design, and neither\nreplaces the pattern of practice differences.\n\n## Analyse proportions and counts {#ch06-counts}\n\n### Keep the event and denominator visible\n\nA score model is not the appropriate starting point for every outcome.\nChapter 3 introduced the invented completion table in\n@tbl-ch06-completion-counts. It contains aggregate counts for 100 records,\nclassified by learning format and completion. These records have no\nlinkage to either score dataset above. The counts themselves establish\nneither random allocation nor representative sampling.\n\n\\Needspace{9\\baselineskip}\n\n| Format | Completed | Not completed | Total |\n|:--|--:|--:|--:|\n| Online | 32 | 18 | 50 |\n| In person | 18 | 32 | 50 |\n| Total | 50 | 50 | 100 |\n\n: The same authored completion counts as Chapter 3. {#tbl-ch06-completion-counts}\n\nFor the Online group, the event is completion and the denominator is its\n50 records. Under an independent Bernoulli model with a common completion\nprobability $p$, the count of completions has a binomial distribution. The\nestimated probability is $\\widehat p=32/50=.64$. If records were clustered\nwithin dependent classes or came from repeated observations of the same\npeople, this ordinary independent-unit uncertainty model would require\nmodification.\n\nSuppose the benchmark is $p_0=.5$. The score test standardizes the difference\nusing the variance under that null:\n\n$$\nz=\\frac{\\widehat p-p_0}{\\sqrt{p_0(1-p_0)/50}}\n=\\frac{.64-.5}{\\sqrt{.5(.5)/50}}=1.9799.\n$$\n\nSquaring gives $X^2=z^2=3.92$, compared with a chi-squared distribution\non one degree of freedom. The procedure uses a large-sample reference;\nthe expected numbers of successes and failures under this null are both 25.\n\n\\Needspace{8\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\none_prop <- prop.test(32, 50, p = .5, correct = FALSE)\none_prop$estimate\n#>    p \n#> 0.64\none_prop$statistic\n#> X-squared \n#>      3.92\none_prop$p.value\n#> [1] 0.04771488024\none_prop$conf.int\n#> [1] 0.5014101688 0.7586125035\n#> attr(,\"conf.level\")\n#> [1] 0.95\n```\n:::\n\n\nThe two-sided p-value is .0477. The estimated completion probability is\n.64, with 95% Wilson score interval [.5014, .7586]. `correct = FALSE`\nexplicitly selects the uncorrected score procedure; accepting R's default\ncontinuity correction would specify a different calculation. The call and\nthe reported result should identify which procedure was used.\n\nThe score interval contains the candidate probabilities that their own\ntwo-sided score tests would retain [@wilson1927]. Each candidate supplies\nthe variance for its null calculation. This inversion explains why the\ninterval is linked to the score test and is not simply\n$\\widehat p\\pm1.96\\sqrt{\\widehat p(1-\\widehat p)/n}$, the Wald interval,\nand why its center lies slightly closer to .5 than .64 does. The Computer\nLab computes the Wilson endpoints directly. The p-value assesses the\nstipulated benchmark; it is not the probability that $p=.5$ is true or a\nmeasure of the completion rate's practical importance.\n\n### Compare the two groups through their full table\n\nNow ask whether completion probability differs by format. This uses both\nrows and a different null: format and completion are independent in the\nworking population model, equivalently equal completion probabilities in\nthis two-group setting. Constructing labelled counts prevents an accidental\nchange in the event or group direction.\n\n\\Needspace{12\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounts <- matrix(c(32, 18, 18, 32), nrow = 2,\n  byrow = TRUE,\n  dimnames = list(Format = c(\"Online\", \"In person\"),\n    Result = c(\"Completed\", \"Not completed\")))\nprop.table(counts, margin = 1)\n#>            Result\n#> Format      Completed Not completed\n#>   Online         0.64          0.36\n#>   In person      0.36          0.64\ncount_test <- chisq.test(counts, correct = FALSE)\ncount_test$expected\n#>            Result\n#> Format      Completed Not completed\n#>   Online           25            25\n#>   In person        25            25\ncount_test$statistic\n#> X-squared \n#>      7.84\ncount_test$p.value\n#> [1] 0.005110260661\ncount_test$residuals\n#>            Result\n#> Format      Completed Not completed\n#>   Online          1.4          -1.4\n#>   In person      -1.4           1.4\n```\n:::\n\n\n`margin = 1` divides each row by its own total. Completion rates are .64\nfor Online and .36 for In person, a difference of .28, or 28 percentage\npoints, in the Online-minus-In-person direction. Under independence the\nfitted expected count in row $j$, column $k$ is\n\n$$\nE_{jk}=\\frac{(\\text{row }j\\text{ total})\n(\\text{column }k\\text{ total})}{N}.\n$$\n\nAll four expected counts here equal $50\\times50/100=25$. Pearson's\nstatistic accumulates the squared discrepancies relative to those expected\ncounts:\n\n$$\nX^2=\\sum_{j,k}\\frac{(O_{jk}-E_{jk})^2}{E_{jk}}\n=4\\left(\\frac{7^2}{25}\\right)=7.84.\n$$\n\nFor a $J$-by-$K$ table the usual independence reference has\n$(J-1)(K-1)$ degrees of freedom. Here $df=1$ and p .0051. The observed\nPearson statistic $X^2$ is a number calculated from the table; $\\chi^2_1$\nnames its approximate reference distribution under the null model.\n\nThe Pearson residuals are $(O-E)/\\sqrt E$: 1.4, $-1.4$, $-1.4$, 1.4\nin row order. Their signs locate the pattern: more Online completions and\nfewer Online non-completions than the independence fit predicts, with the\nopposite departures for In person. Squaring and adding these residuals\nrecovers $X^2$. They are related through the table margins, so their signs\ndo not constitute four independent cell tests.\n\nThe approximation concerns expected counts under the fitted null model,\nalong with independent observational units and a sampling model appropriate\nto the table. Looking only at observed cell counts misses part of this\ncheck. Sparse expected cells may require an alternative reference or a more\ncareful model. In the present example all expected counts are 25, supporting\nthe ordinary chi-squared approximation under the stated unit model.\n\nThe one-proportion test asked whether Online completion probability equals\na fixed .5 benchmark. The complete-table test asks whether the two format\nprobabilities are equal; it estimates their common probability under the\nnull from the full table. Their different p-values answer different\nquestions. Neither test establishes that changing format would cause\ncompletion to change without relevant design information.\n\n### Choose an effect scale and keep alternatives within the analysis {#ch06-categorical-reference}\n\nA chi-square test says whether the table departs from no association, not\nhow large the association is or on which scale. @tbl-ch06-effect-scales\nsets four common scales side by side for the completion table, with\n$p_1$ the Online and $p_0$ the In-person completion proportion, and\ngives the question that each one answers [@agresti2018].\n\n\\Needspace{17\\baselineskip}\n\n| Scale | Definition | Value | What it answers |\n|:--|:--|--:|:--|\n| Difference in proportions | $p_1-p_0$ | .2800 | How many percentage points more often the event occurs in one group: an absolute gap |\n| Risk ratio | $p_1/p_0$ | 1.7778 | How many times as probable the event is in one group: a relative gap, which changes when the other outcome is called the event |\n| Odds ratio | $\\dfrac{p_1/(1-p_1)}{p_0/(1-p_0)}$ | 3.1605 | How many times as large the odds of the event are; it stays the same when rows and columns exchange roles, so a design that samples on the outcome can still estimate it |\n| Cramér's V | $\\sqrt{\\dfrac{X^2}{N\\min(J-1,K-1)}}$ | .2800 | How strong the association is, from 0 to 1, for a table of any size; it carries no direction and names no cell comparison |\n\n: Four effect scales for the completion table, Online versus In person. {#tbl-ch06-effect-scales tbl-colwidths=\"[15,25,9,51]\"}\n\nThe same counts give a gap of 28 percentage points, a risk ratio of\n1.7778 and an odds ratio of 3.1605. The odds ratio lies farther from 1\nthan the risk ratio because completion is common: Online's completion\nodds are $32/18=1.7778$ and In person's are $18/32=.5625$, so an odds\nratio is not read as a risk ratio. Calling non-completion the event\nchanges the risk ratio to $.36/.64=.5625$ and the odds ratio to its\nreciprocal, .3164, so the event and the direction are named beside every\nscale. Cramér's V [@cramer1946] equals the difference in proportions here\nonly because every row and column total is 50. Chapter 11 reads the odds\nratio again as an exponentiated logistic coefficient.\n\nOther procedures change one part of the analysis while keeping the same\ntable, and each answers its own question. The two-proportion interface\ngives a large-sample interval for the difference in proportions, a\ndifferent quantity from the one-probability Wilson interval of\nSection 4.1. A continuity correction changes the calibration of the\nPearson statistic. Fisher's exact test [@fisher1935] conditions on the\ntable margins and uses an exact reference, which matters when expected\ncounts are small. The Computer Lab runs each alternative on this table and\nthen continues the observational student intention-by-pass example of\nChapter 2, Section 3.1, where these scales, the choice of procedure and an\nunresolved source-coding question meet in an existing dataset.\n\n## Fit by an objective function and likelihood {#ch06-likelihood}\n\n### Fix the data and vary a candidate parameter\n\nThe fitted means in Section 1 were chosen by a rule: minimize the sum\nof squared deviations from the observations. We can inspect this rule\nwith the ten Silence scores, 8, 9, 9, 11, 12, 13, 13, 14, 15 and 16.\nThese observations stay fixed. What changes is the proposed center,\ndenoted by $c$.\n\nAn **objective function** assigns a numerical criterion to each candidate\nparameter value for fixed data. For a center fitted by least squares,\nthe objective is\n\n$$\nQ(c)=\\sum_{i=1}^{10}(y_i-c)^2\n     =(8-c)^2+(9-c)^2+\\cdots+(16-c)^2.\n$$\n\nAt $c=12$, the deviations are the Silence residuals of Section 1, and\ntheir squares sum to 66 squared score points. At either 11 or 13, they\nsum to 76. Chapter 2, Section 2.2, states that the sample mean minimizes\nthis criterion, and Chapter 3's Appendix A derives the identity behind\nit. Here the mean is 12 points. A numerical search lets us reproduce the\nminimizing value without writing it into the fitting instruction.\n\n\\Needspace{6\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsilence <- subset(sound_data, sound == \"Silence\")$score\nloss <- function(center) sum((silence - center)^2)\nmean_fit <- optimize(loss, interval = range(silence))\nc(center = mean_fit$minimum, squared_loss = mean_fit$objective)\n#>       center squared_loss \n#>           12           66\n```\n:::\n\n\n`subset()` keeps the Section 1 rows whose condition is Silence, and\n`loss()` returns the sum of squared deviations for any candidate center.\n`optimize()` searches for a minimum of that function over the interval\nsupplied, here `range(silence)`, or $[8,16]$, which contains the sample\nmean. The objective is a single smooth bowl over this interval, so the\nscalar search has one minimum to locate.\n\nThe two returned quantities have different meanings. `minimum` is\nthe **parameter location**, 12 points; `objective` is the function\nvalue there, 66 squared points. The latter is a sum of squared\ndeviations, Silence's contribution to $SS_W$ in Section 1, rather than an\nSE or an estimate of the mean. The search interval\nalso belongs to the fitting instruction: excluding the best center\nwould restrict which answer the search could return. Numerical stopping\ntolerance concerns the accuracy of that search; statistical uncertainty\nconcerns what an estimate would do across the repetitions justified by\nthe study.\n\nThese least-squares identities are arithmetic. An uncertainty statement\nfor the fitted mean adds a model or design and its conditions. Chapter 7\nextends this criterion from one center to a line with an intercept and\nslope. The Computer Lab evaluates the criterion at several centers and\nnarrows the search interval while keeping the observations fixed.\n\n### Change the fitting criterion for a binomial outcome\n\nFor the completion example, the observations are 32 completions in 50\nOnline trials. Let $p$ denote a candidate probability of completion.\nUnder the stipulated model of independent trials with a common\nprobability, the number completed follows a binomial distribution.\nThe model assigns probability\n\n$$\nP_p(X=32)={50\\choose32}p^{32}(1-p)^{18}.\n$$\n\nIn a probability calculation, we choose a value of $p$ and consider\nwhich counts might occur. For fitting, we have already observed the\ncount: 32 stays fixed, as does the total of 50. We now evaluate the\nsame expression at different candidate values of $p$. Viewed in this\ndirection, it is the **likelihood function**,\n\n$$\nL(p)={50\\choose32}p^{32}(1-p)^{18},\\qquad 0\\le p\\le1.\n$$\n\nThe binomial coefficient counts the ways 32 completions can occur\namong 50 trials. It is constant as $p$ varies. In this binomial model, likelihood is the\nprobability of the observed data under each candidate model parameter;\nit is not a probability distribution over that parameter. In\nparticular, a high likelihood at a candidate $p$ does not give the\nprobability that $p$ is true.\n\n**Maximum likelihood estimation** chooses the parameter value that\nmakes the observed data most likely under the declared model. The\nlogarithm is increasing, so maximizing the log-likelihood gives the\nsame parameter value. For $0<p<1$,\n\n$$\n\\ell(p)=\\log {50\\choose32}+32\\log p+18\\log(1-p).\n$$\n\nLogs turn a product of powers into a sum and make calculation easier.\nThe binomial coefficient affects the reported function value, although\nit cannot change the maximizing $p$. Here the interior maximum can also\nbe found analytically. Differentiating with respect to the candidate\nprobability gives\n\n$$\n\\ell'(p)=\\frac{32}{p}-\\frac{18}{1-p}\n         =\\frac{32-50p}{p(1-p)}.\n$$\n\nSetting this slope to zero gives $32-50p=0$, and therefore\n$\\widehat p=32/50=.64$. The denominator is positive inside $(0,1)$.\nThe slope is positive below .64 and negative above .64: the curve rises\nto this point and then falls. This verifies a maximum rather than\nmerely finding a flat point.\n\nTo use the default minimization operation in `optimize()`, supply the\n**negative** log-likelihood. A smaller negative log-likelihood means a\nlarger log-likelihood, so its minimum locates the same fitted probability.\n\n\\Needspace{11\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnegative_loglik <- function(p) {\n  -dbinom(32, size = 50, prob = p, log = TRUE)\n}\nlikelihood_fit <- optimize(negative_loglik, interval = c(0, 1))\nc(numerical = likelihood_fit$minimum, analytic = 32/50,\n  negative_loglik = likelihood_fit$objective)\n#>       numerical        analytic negative_loglik \n#>    0.6400059479    0.6400000000    2.1465474559\nnegative_loglik(.5)\n#> [1] 4.13299674\n```\n:::\n\n\n`dbinom()` evaluates the binomial probability for the fixed count 32.\nWith `log = TRUE`, it computes the log probability directly. The\nnumerical and analytic estimates both round to .64. The small\nnumerical difference from exactly .64 reflects the search tolerance.\nAt the fitted probability the negative log-likelihood is 2.1465,\ncompared with 4.1330 at $p=.5$. The smaller value is the better fit\naccording to this criterion. The parameter estimate .64 is a\ncompletion probability; the criterion value 2.1465 is not.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The binomial log-likelihood is largest at the observed proportion.](chapter_06_files/figure-html/fig-ch06-likelihood-1.png){#fig-ch06-likelihood fig-pos='!ht' fig-alt='For 32 successes in 50 fixed trials, the log-likelihood curve peaks at candidate probability .64. A dashed line at .5 intersects the curve at a lower value.' width=585.6}\n:::\n:::\n\n\nThe horizontal axis contains candidate parameter values, and the\nvertical axis gives the log-likelihood of the same observed count at\neach candidate. Thus the curve displays a fitting criterion, not a\nsampling distribution or a distribution of probabilities over $p$.\nThe peak identifies the fitted value. The score test and interval in\nSection 4 answer additional questions about a proposed null and the\nuncertainty of estimation under their stated calibration.\n\nFinally, check the boundaries of the parameter space. With both\ncompletions and non-completions observed, $p=0$ and $p=1$ each give\nlikelihood zero, so the maximum is interior. If all 50 trials instead\nhad zero completions, the maximum would be at $p=0$; if all completed,\nit would be at $p=1$. An interior numerical search can approach such\nan endpoint without returning it exactly. The endpoint values must\ntherefore be examined explicitly in those cases. Chapter 11 develops\nthese boundary questions further when likelihood is used to fit\nlogistic regression.\n\n## Examine procedures by repetition and plan precision {#ch06-simulation}\n\nThe preceding analyses started with observed data and produced estimates,\nintervals and tests. We can also begin with a declared generating model,\ncreate data from it, and examine what an analysis does over repeated studies.\nChapter 5 used this approach to examine sampling variation and interval\ncoverage. Here the questions concern an omnibus ANOVA procedure and the\nsample size for a specified comparison.\n\n### Follow one generated study before repeating it\n\nImagine three independent groups whose outcomes follow Normal distributions,\neach with standard deviation $\\sqrt{10/3}=1.8257$ points. First set all three\npopulation means to 8, so that the equal-means null hypothesis is true;\nlater the unequal means 6, 8 and 10 describe an alternative. These values\nborrow the scale of the feedback study in Section 3, whose Massed cells\nhave means 6, 8 and 10 with four pupils each and whose factorial fit has\nresidual mean square $10/3$. They define a hypothetical world in which we\nknow the truth; the constructed scores do not establish that this\ngenerating model describes real pupils.\n\nBegin with four observations per group and analyse one generated study.\n\n\\Needspace{13\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(60630)\nn_per_group <- 4\nsim_group <- factor(rep(1:3, each = n_per_group))\nsim_score <- rnorm(3*n_per_group,\n  mean = rep(c(8, 8, 8), each = n_per_group), sd = sqrt(10/3))\nanova(lm(sim_score ~ sim_group))\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|          | Df|       Sum Sq|     Mean Sq|     F value|       Pr(>F)|\n|:---------|--:|------------:|-----------:|-----------:|------------:|\n|sim_group |  2|  7.597715661| 3.798857831| 1.036520926| 0.3934504588|\n|Residuals |  9| 32.985074978| 3.665008331|          NA|           NA|\n\n</div>\n:::\n:::\n\n\n`rep()` and `factor()` label four observations in each of three groups,\n`rnorm()` draws the twelve outcomes from the declared means and common\nSD, and `set.seed()` makes this particular draw reproducible. The formula\n`sim_score ~ sim_group` fits a separate mean for each group; `anova()`\ncompares that fit with a common mean. Its table has 2 group degrees of\nfreedom and $12-3=9$ error degrees of freedom. For these generated data,\n$SS_B=7.5977$ and $SS_W=32.9851$, giving $F=1.0365$ and $p=.3935$.\nApplying the rule $p<.05$ therefore does not reject the equal-means null\nin this study. Although the three generating means are identical, the\nthree sample means vary, so the between-group sum of squares is\npositive. The estimated error variance, $MS_W=3.665$, also varies around\nthe generating variance $10/3$.\n\nOne generated study cannot describe a procedure's long-run behaviour.\nRepeating the same calculation many times gives a collection of p-values\nto compare with .05. @tbl-ch06-simulation reports 2,000 studies for each\nof four conditions. The null conditions use means $(8,8,8)$; the\nalternative conditions use $(6,8,10)$. Each condition retains independent\nNormal observations and the same common SD, and the Computer Lab\nreproduces the table from seed 60630.\n\n| Pupils per group | Null rejection rate | MCSE | Power at means 6/8/10 | MCSE |\n|--:|--:|--:|--:|--:|\n| 4 | .056 | 0.0051 | .6545 | 0.0106 |\n| 12 | .050 | 0.0049 | .9990 | 0.0007 |\n\n: Operating characteristics in the declared generating models, $B=2000$ studies per condition. {#tbl-ch06-simulation}\n\nThe **null rejection rate** estimates the Type I error probability: how\noften this .05 omnibus procedure rejects when all three population means\nare equal. Both estimated rates are close to .05. The **power** column\nestimates the probability of rejecting that same null under the specified\nunequal means. It rises from .6545 with four pupils per group to .9990 with\n12. This is power against the particular means 6, 8 and 10, with the stated\nspread and independence; a smaller separation would give different power.\n\nEach rate is itself an estimate based on finitely many repetitions. If\n$\\widehat q$ is a simulated rejection proportion from $B$ independent studies,\nits approximate Monte Carlo standard error is\n\n$$\nMCSE(\\widehat q)=\\sqrt{\\frac{\\widehat q(1-\\widehat q)}{B}}.\n$$\n\nFor the estimated power .6545, it is $\\sqrt{.6545(1-.6545)/2000}=0.0106$,\nand the table's MCSE columns apply the same formula to each rate. This\nvalue describes the numerical uncertainty from using 2,000 simulations:\na fresh set of 2,000 simulated studies can give a somewhat different\npower estimate. The MCSE is distinct from a pupil outcome's SD or the SE\nof a group mean or contrast within one study. A rate very close to one,\nsuch as .999, also deserves care: only two of the 2,000 studies failed\nto reject, so its tiny plug-in MCSE rests on very few non-rejections.\n\nIncreasing the number of pupils $n$ changes the information within a study,\nits error degrees of freedom and its ability to detect the specified\ndifference. Increasing the number of repetitions $B$ makes the simulated\nrate more precise; it leaves the study being simulated unchanged.\nSimulation describes a procedure under the declared model; agreement with\nits expected behaviour does not establish that the model fits a\nparticular real study.\n\n### Plan for a specified comparison and precision target\n\nThe omnibus simulation asks whether some population group means differ.\nA future study may instead be planned to estimate or detect one particular\ndifference. Consider a future balanced one-factor study of the three\nfeedback conditions, with a declared **two-comparison Bonferroni family**:\nAnswer feedback versus Rereading, and Explanatory feedback versus\nRereading. The family has the same form as Section 2's two comparisons\nwith Silence. Keep it, with family significance level .05, even when\ncalculating power for just one of its comparisons.\n\nSuppose the comparison of interest has a population difference of\n$\\delta=2$ points. Plan equal group sizes $n$, independent Normal outcomes\nand common SD $\\sigma=\\sqrt{10/3}$, the square root of the factorial fit's\nresidual mean square in Section 3. The planning SE for a difference of two\ngroup means is $\\sigma\\sqrt{2/n}$. All three groups contribute to the\npooled error variance, so its degrees of freedom are $3(n-1)$, even though\nthe contrast compares only two of the means.\n\nBonferroni assigns two-sided significance level $.05/2=.025$ to each\ncomparison. Dividing that amount between its two tails puts .0125 in each\ntail. The rejection cutoffs are therefore $-c$ and $c$, where\n\n$$\nc=t_{1-.05/(2\\times2),\\,3(n-1)}=t_{.9875,\\,3(n-1)}.\n$$\n\nUnder the zero-difference null, the test statistic has the central\n$t$ distribution already used for the comparison. Under a specified\nnonzero difference, its distribution moves towards that difference.\nThe **noncentral $t$ distribution** describes this statistic when its\nnumerator has a nonzero mean and its denominator still estimates the\ncommon spread. Its noncentrality parameter expresses the population\ndifference in planning SE units:\n\n$$\n\\lambda=\\frac{\\delta}{\\sigma\\sqrt{2/n}}.\n$$\n\nFor this alternative, power is the area beyond the same two rejection\ncutoffs: $P(T<-c)+P(T>c)$ for a noncentral $t$ variable with $3(n-1)$\ndegrees of freedom and noncentrality $\\lambda$. These are probabilities\nover future studies, rather than a p-value from observed data. Both tails\nbelong to the two-sided procedure, even when the planning difference is\npositive.\n\n\\Needspace{10\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncontrast_power <- function(n, delta = 2, sigma = sqrt(10/3)) {\n  df <- 3*(n-1)\n  critical <- qt(1 - .05/(2*2), df)\n  ncp <- delta / (sigma * sqrt(2/n))\n  pt(-critical, df, ncp = ncp) +\n    pt(critical, df, ncp = ncp, lower.tail = FALSE)\n}\nround(c(n16 = contrast_power(16), n17 = contrast_power(17)), 4)\n#>    n16    n17 \n#> 0.7793 0.8073\n```\n:::\n\n\nThe function accepts a proposed group size and returns power. Its first\n`pt()` call obtains the lower-tail probability; the second obtains the\nupper-tail probability. At $n=17$, the planning SE is 0.6262, the error\ndegrees of freedom are 48, the critical value is 2.3139, and\n$\\lambda=3.1937$. Summing the two tail areas gives power\n.8073. Checking successive integer sizes gives 17 pupils per group,\n51 in total, as the first size reaching .8 power; 16 gives .7793.\n\nThis is the power of **one specified comparison within the declared\nfamily**. It is neither the probability that both comparisons reject nor\nthe power of the omnibus F test. For example, with 12 pupils per group\nthe specified two-point comparison has power .6328, whereas the omnibus\nsimulation in @tbl-ch06-simulation gives estimated power .9990 against\nthe complete pattern $(6,8,10)$. The hypotheses and rejection rules differ,\nso these numbers answer different questions.\n\nA precision target concerns the interval's width rather than its\nprobability of excluding zero. Suppose the aim is a simultaneous interval\nwhose planned half-width is no more than one point. The family and\ndegrees of freedom stay the same, giving\n\n$$\n\\text{planned half-width}\n=t_{.9875,\\,3(n-1)}\\,\\sigma\\sqrt{\\frac{2}{n}}.\n$$\n\nThis calculation substitutes the planning SD $\\sigma$ for the error SD\nthat the future study will estimate. The planned half-width is 1.0078\npoints at 34 per group and 0.9929 at 35, so 35 per group, or 105 pupils\nin total, is the first size meeting this target. The realised interval\nuses the observed $\\sqrt{MS_W}$ and therefore has a random width.\nChoosing 35 does not guarantee that its half-width will be at most one in\nevery study. @fig-ch06-planning shows why a power target and an\ninterval-width target can select quite different sample sizes.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Power and planned interval width impose different sample-size targets.](chapter_06_files/figure-html/fig-ch06-planning-1.png){#fig-ch06-planning fig-alt='For the same two-comparison three-group procedure, power rises above .8 at 17 pupils per group. Planned simultaneous interval half-width falls below one point at 35 pupils per group.' width=614.4}\n:::\n:::\n\n\nFinally, distinguish the desired number of available outcomes from the\nnumber recruited. If outcomes are expected to be available for 90% of\nrecruits, the 17-per-group power target needs\n$\\lceil17/.9\\rceil=19$ recruits per group, 57 in total, with an expected\n17.1 available outcomes per group under that retention assumption. It is\nan average allowance, not a guarantee of 17 outcomes in every group or a\ncorrection for bias from systematically missing outcomes.\n\nThe Computer Lab searches the full grid of sample sizes and changes the\ntarget difference and the retention rate. A two-group power calculation\ndeclares a different study, with different error degrees of freedom, and\ncannot silently replace this three-group calculation. Choose a planning\ndifference from the substantive question and relevant prior evidence. As\nChapter 3's significance-filter example showed, selecting statistically\nsignificant results can favour exaggerated estimates; an observed\ndifference from such a selection is not automatically a suitable planning\nalternative.\n\n## Reading Bridge {#ch06-reading-bridge}\n\nThe chapter compared group means, separated omnibus questions from\ncalibrated contrasts, and read a comparison that changes across another\nfactor, testing that change by comparing two named models on the same\nrecords. Counts required a different response model and their own effect\nscales; likelihood and an objective function made the fitting criterion\nexplicit. Repetition examined procedures under a declared generating\nmodel, while power and precision described different planning aims.\n\nWhen reading a study, identify the question, analysed records, model,\nestimate and uncertainty procedure before evaluating their adequacy.\nFor a group comparison, locate its subtraction direction and the records\nit uses. For a test or interval, identify the null, reference distribution\nand comparison family. For an effect in a table, identify the event and\nthe scale. For a simulation or planning result, locate the generating\nassumptions and the particular procedure being evaluated. These details\nconnect the reported numbers to the claims they can support.\n\n[]{#ch06-appendix-b}Later chapters build on each of these steps. Chapter 7\nextends squared loss from a fitted center to a line: it derives the\nline's normal equations, relates fitted values and residuals through\nprojection, and develops uncertainty for the slope and the fitted mean.\nChapter 8 conditions on several controls and distinguishes a coefficient\nconditional on specified predictors from a fitted mean at a profile, a\nprediction for a new case and an average of fitted values over a named\npopulation. Chapter 9, Section 2, develops the analysis of covariance as\nregression and checks its parallel slopes with the nested-model\ncomparison of Section 3.2. Chapter 11 develops likelihood for binary\nregression, including exact boundary estimates, a likelihood with more\nthan one parameter, and the starting values and convergence checks that\nnumerical fitting then requires.\n\n\\Needspace{10\\baselineskip}\n\n### Key terms and notation {.unnumbered}\n\nANOVA, contrasts, interactions and comparison families keep their main\nexplanations in Chapter 4, and the Part One Concept Reference gives the\nbroader reference and the principal home of each concept. The following\nconcepts were introduced or developed through their R applications here.\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Model formula (R formula) | Notation such as `score ~ group` naming an outcome and the variables that explain it for a fitting function. It does not state whether observations are independent or paired; that comes from the design. |\n| Categorical effect scales (difference in proportions; risk ratio; odds ratio; Cramér's V) | Four ways to state the size of an association in a table, each answering its own question: the difference in proportions gives an absolute gap, the risk ratio a relative gap, the odds ratio a ratio of odds that stays the same when rows and columns exchange roles, and Cramér's V a unit-free strength, from 0 to 1, for a table of any size. |\n| Objective function | A numerical criterion evaluated at candidate parameter values for fixed data; fitting seeks a stated minimum or maximum. |\n| Likelihood and log-likelihood | The probability or density of the observed data under a declared model, viewed as a function of its parameters; the log-likelihood is its logarithm. |\n| Maximum likelihood estimation (MLE) | Choosing parameter values that maximize the likelihood, equivalently the log-likelihood, over the stated parameter space. |\n\n: Selected concepts introduced or developed here. {#tbl-ch06-terms tbl-colwidths=\"[30,70]\"}\n\nThe notation follows the local question. $C=\\sum_jc_j\\mu_j$ is a contrast,\nwhereas $L(\\theta)$ is a likelihood function of a parameter. Similarly, Type II error probability\n$\\beta$ differs from a model coefficient such as $\\beta_x$.\nObserved Pearson $X^2$ differs from the reference distribution $\\chi^2$,\nand $\\Delta p=p_1-p_0$ is a difference in proportions.\nIn simulations, $n$ counts observations per stated study or group and $B$\ncounts repeated studies. An SE describes an estimator's sampling variation;\nan MCSE describes finite-simulation uncertainty in a computed summary.\n\n### Further reading {.unnumbered}\n\nFor the linear-model basis of ANOVA, contrasts and nested-model\ncomparisons, see @kutner2005. @tukey1953 develops simultaneous comparison\nideas, and @wilson1927 provides the score-interval construction for a\nproportion. @agresti2018 develops the effect scales for two-way tables.\n@cohen1988 discusses power and the dependence of a planning result on its\nchosen effect and procedure, and @cetinkaya2024 develops the\nsimulation-based treatment of operating characteristics used in Section 6.\nR's documentation gives the arguments and returned components for `aov`,\n`lm`, `TukeyHSD`, `oneway.test`, `prop.test`, `chisq.test` and `optimize`\n[@rcore2025]. The plotting chapters of @wickham2023 develop the data,\nmapping and layer vocabulary behind the chapter's figures, which the\nComputer Lab builds.\n\n## Exercises {.unnumbered}\n\nThe chapter's printed output, tables and figures supply the values each\nexercise reads, with a calculator for the few calculations that the\nreasoning needs. State the records, working conditions and comparison\ndirection in each interpretation.\n\n<!-- prompt-id: CH06-E01 -->\n\n### Exercise 1: Read the one-way fit from its output {.unnumbered #ex-ch06-01}\n\nFor the thirty background-sound scores, `anova(one_fit)` reports sums of\nsquares 80 and 178 on 2 and 27 df, $F=6.0674$ and $p=.0067$, and\n`coef(indicator_fit)` returns 12, $-2$ and $-4$ with Silence as the\nreference level.\n\n1. Say what each sum of squares measures in these scores, and why\n   Instrumental music, whose mean equals the grand mean of 10, adds\n   nothing to the between-group sum of squares although its ten scores\n   vary.\n2. Explain what the within-group df, 27, count, and why $F$ divides by\n   the residual mean square, 6.5926, rather than by the variance of all\n   thirty scores, $258/29=8.8966$.\n3. State the equal-means null, and interpret $p=.0067$ under the working\n   model, including what the result leaves unanswered about particular\n   pairs of conditions.\n4. Predict the three coefficients if Instrumental music were made the\n   reference level, and say which parts of the ANOVA output would change.\n\n<!-- END EX06-01 PROMPT -->\n\n<!-- prompt-id: CH06-E02 -->\n\n### Exercise 2: Keep the comparison and its family together {.unnumbered #ex-ch06-02}\n\nInstrumental music minus Silence is $-2$ points with SE 1.1483 on 27 df.\nIts 95% interval is $[-4.3561, 0.3561]$ when the comparison stands alone,\n$[-4.7253, 0.7253]$ inside the declared family of the two comparisons\nwith Silence (Bonferroni) and $[-4.8470, 0.8470]$ inside the family of\nall three pairs (Tukey).\n\n1. The estimate and SE are the same in all three intervals. Explain why\n   the limits differ, naming the family that each interval protects.\n2. Explain why the SE uses 27 residual df, although the comparison\n   involves only the twenty students in two conditions.\n3. An analyst reports Music with lyrics minus Silence, $-4$ points,\n   because it is the largest of the three observed differences. Say which\n   family its interval should come from, and why.\n4. The omnibus F rejected equal means, yet all three intervals above\n   include zero. Explain why these results are compatible, and why an\n   interval that includes zero does not show that the two means are\n   equal.\n\n<!-- END EX06-02 PROMPT -->\n\n<!-- prompt-id: CH06-E03 -->\n\n### Exercise 3: Read interaction as a change in comparison {.unnumbered #ex-ch06-03}\n\nIn the 24-pupil feedback-by-practice study, the Massed and Spaced cell\nmeans are 6 and 6 for Rereading, 8 and 12 for Answer feedback and 10 and\n18 for Explanatory feedback, and the full two-way model gives the\ninteraction test $F(2,18)=9.6$, $p=.0015$.\n\n1. Give the three Spaced-minus-Massed changes, and say what the\n   nonparallel lines of the interaction plot show and what they cannot\n   show without a model.\n2. The practice margins are 8 and 12. Explain why the 4-point practice\n   main effect needs the interaction beside it when a reader asks how\n   spaced practice works.\n3. The selected difference of differences, Answer feedback's change\n   minus Rereading's change, is 4 points with SE 1.8257. Its pointwise\n   interval is $[0.1643, 7.8357]$, and its Scheffé interval over the\n   two-dimensional interaction family is $[-0.8680, 8.8680]$. Explain how\n   the Scheffé interval can include zero while the interaction F test\n   rejects, and say which interval is warranted when this direction was\n   chosen after the plot was inspected.\n4. Answer feedback's simple practice effect is also 4 points, with SE\n   1.291. Explain why its SE is smaller and why the interaction family's\n   guarantee does not cover it.\n\n<!-- END EX06-03 PROMPT -->\n\n<!-- prompt-id: CH06-E04 -->\n\n### Exercise 4: Name the two models behind an interaction test {.unnumbered #ex-ch06-04}\n\nThe interaction test for the 24 feedback/practice scores compares two\nmodels fitted to the same pupils: the additive model, with residual sum\nof squares 124 on 20 df, and the full factorial model, with 60 on 18 df.\n\n1. Name the two models and say what the larger one adds.\n2. The comparison gives $F=9.6$ on 2 and 18 df. Explain why its\n   denominator comes from the full model rather than the additive model.\n3. After the two Explanatory-Spaced pupils scoring 19 and 20 are\n   removed, the sequential sums of squares for feedback and practice\n   change with the order of the formula, yet the comparison of the\n   additive and full models gives $F(2,16)=5.7426$ in either order.\n   Explain why.\n4. Say what a nonsignificant result of this comparison would and would\n   not show about additivity.\n\n<!-- END EX06-04 PROMPT -->\n\n<!-- prompt-id: CH06-E05 -->\n\n### Exercise 5: Preserve the event, denominator and expected counts {.unnumbered #ex-ch06-05}\n\nIn the invented table, Online has 32 completions and 18 non-completions;\nIn person has 18 completions and 32 non-completions. For Online, the\nuncorrected score test of $p=.5$ gives $X^2=3.92$ and $p=.0477$, with the\n95% Wilson interval $[.5014, .7586]$. For the complete table, Pearson's\ntest gives $X^2=7.84$ on 1 df and $p=.0051$.\n\n1. State the null and the denominator of each test, and explain why the\n   two p-values answer different questions.\n2. Calculate the expected count of Online completions under\n   independence, and explain why the chi-squared approximation is checked\n   against expected rather than observed counts.\n3. The difference in proportions is .28, the risk ratio 1.7778 and the\n   odds ratio 3.1605. Explain why the odds ratio lies farther from 1 than\n   the risk ratio here, and why Cramér's V, .28, equals the difference in\n   proportions only in a table like this one.\n4. Say what design information a claim that the online format causes\n   completion would additionally need.\n\n<!-- END EX06-05 PROMPT -->\n\n<!-- prompt-id: CH06-E06 -->\n\n### Exercise 6: Distinguish study size, repetitions and planning targets {.unnumbered #ex-ch06-06}\n\nIn the chapter's simulation, each condition repeats 2,000 generated\nstudies of three Normal groups with common SD $\\sqrt{10/3}$ and applies\nthe .05 omnibus ANOVA. With equal means $(8,8,8)$ the rejection rates are\n.056 at four pupils per group and .050 at twelve; with means 6, 8 and\n10 the estimated power is .6545 at four and .9990 at twelve.\n\n1. Say what the rejection rates under equal means estimate, and explain\n   why the power rises from four to twelve pupils per group while those\n   rates stay near .05.\n2. The Monte Carlo standard error (MCSE) of the power estimate .6545\n   with $B=2000$ is 0.0106. Say what it measures, and why it differs\n   from the SE of a contrast within one simulated study.\n3. Predict what quadrupling $B$ to 8,000 would do to this MCSE and to the\n   power that the simulation estimates.\n4. For the declared two-comparison family, 17 pupils per group first\n   reach power .8 for a 2-point comparison, and 35 per group first reach\n   a planned simultaneous half-width of at most one point. Say what each\n   target controls, and why a realised interval can have a different\n   width from its planning value.\n\n<!-- END EX06-06 PROMPT -->\n\n<!-- prompt-id: CH06-E07 -->\n\n### Exercise 7: Distinguish an estimate from its fitting criterion {.unnumbered #ex-ch06-07}\n\nKeep 32 successes in 50 trials fixed. Minimizing the negative binomial\nlog-likelihood with `optimize()` over $[0,1]$ returns `minimum` .64 and\n`objective` 2.1465; at $p=.5$ the negative log-likelihood is 4.1330.\n\n1. Say which returned value is the parameter estimate and which is the\n   criterion value, and why 2.1465 is neither a probability that $p=.64$\n   nor an SE.\n2. The derivative of the log-likelihood is\n   $\\ell'(p)=(32-50p)/\\{p(1-p)\\}$. Use its sign to explain why the\n   maximum lies at $32/50$.\n3. Before calculating, predict how the fitted probability and the fall in\n   log-likelihood from $p=.64$ to $p=.5$ would change with 64 successes in\n   100 trials. Then compare your prediction with the supplied falls,\n   1.9864 for 32 of 50 and 3.9729 for 64 of 100.\n4. Explain why the likelihood curve is not a probability distribution\n   over $p$, and what an interior numerical search would return if all\n   50 trials had been successes.\n\n<!-- END EX06-07 PROMPT -->\n\n<!-- prompt-id: CH06-E08 -->\n\n### Exercise 8: Write a qualified result paragraph {.unnumbered #ex-ch06-08}\n\nChoose the one-way comparisons, the selected interaction contrast or the\ntwo-group count comparison from this chapter. Write a short paragraph giving the\nquestion, data and denominator, estimate, interval and its family or\npointwise status, working conditions and scope. Identify one tempting claim\nthat the numerical result does not establish, and explain the missing support.\n\n<!-- END EX06-08 PROMPT -->\n\n## References {.unnumbered}\n",
    "supporting": [
      "chapter_06_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}