<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jinsong Chen">

<title>Estimation, Confidence Intervals, z and t Tests, and Effect Sizes – QMSBR</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e9e44edca4b01ef481a44d1a821c0118.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Estimation, Confidence Intervals, z and t Tests, and Effect Sizes – QMSBR">
<meta property="og:description" content="Modular chapters for rigorous quantitative reasoning in social and behavioral research.">
<meta property="og:image" content="https://jinsong-chen.github.io/QMSBR/chapters/chapter_03_files/figure-html/fig-confidence-coverage-1.png">
<meta property="og:site_name" content="QMSBR">
<meta property="og:image:alt" content="Forty horizontal confidence intervals are plotted against a vertical truth line at 10. Most cross the truth line and a few do not.">
<meta property="og:image:height" content="1036">
<meta property="og:image:width" content="1382">
<meta name="twitter:title" content="Estimation, Confidence Intervals, z and t Tests, and Effect Sizes – QMSBR">
<meta name="twitter:description" content="Modular chapters for rigorous quantitative reasoning in social and behavioral research.">
<meta name="twitter:image" content="https://jinsong-chen.github.io/QMSBR/chapters/chapter_03_files/figure-html/fig-confidence-coverage-1.png">
<meta name="twitter:image:alt" content="Forty horizontal confidence intervals are plotted against a vertical truth line at 10. Most cross the truth line and a few do not.">
<meta name="twitter:image-height" content="1036">
<meta name="twitter:image-width" content="1382">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">QMSBR</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../library/index.html"> 
<span class="menu-text">Library</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../for-instructors.html"> 
<span class="menu-text">For instructors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about/index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../updates.html"> 
<span class="menu-text">Updates</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Estimation, Confidence Intervals, z and t Tests, and Effect Sizes</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jinsong Chen </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#opening-problem" id="toc-opening-problem">Opening Problem</a></li>
  <li><a href="#five-inferential-objects" id="toc-five-inferential-objects">Five Inferential Objects</a>
  <ul>
  <li><a href="#the-estimand-must-precede-the-calculation" id="toc-the-estimand-must-precede-the-calculation">The estimand must precede the calculation</a></li>
  <li><a href="#an-observed-sample-description-and-a-superpopulation-estimand-are-different-targets" id="toc-an-observed-sample-description-and-a-superpopulation-estimand-are-different-targets">An observed-sample description and a superpopulation estimand are different targets</a></li>
  <li><a href="#estimator-quality-has-more-than-one-dimension" id="toc-estimator-quality-has-more-than-one-dimension">Estimator quality has more than one dimension</a></li>
  </ul></li>
  <li><a href="#sampling-variation-and-standard-errors" id="toc-sampling-variation-and-standard-errors">Sampling Variation and Standard Errors</a>
  <ul>
  <li><a href="#standard-deviation-and-standard-error-answer-different-questions" id="toc-standard-deviation-and-standard-error-answer-different-questions">Standard deviation and standard error answer different questions</a></li>
  <li><a href="#dependence-changes-the-information-count" id="toc-dependence-changes-the-information-count">Dependence changes the information count</a></li>
  <li><a href="#bootstrap-intuition-and-its-boundary" id="toc-bootstrap-intuition-and-its-boundary">Bootstrap intuition and its boundary</a></li>
  <li><a href="#four-distributions-that-must-not-be-collapsed" id="toc-four-distributions-that-must-not-be-collapsed">Four distributions that must not be collapsed</a></li>
  <li><a href="#a-transparent-stratified-bootstrap" id="toc-a-transparent-stratified-bootstrap">A transparent stratified bootstrap</a></li>
  </ul></li>
  <li><a href="#confidence-intervals-and-coverage" id="toc-confidence-intervals-and-coverage">Confidence Intervals and Coverage</a>
  <ul>
  <li><a href="#coverage-belongs-to-the-procedure" id="toc-coverage-belongs-to-the-procedure">Coverage belongs to the procedure</a></li>
  </ul></li>
  <li><a href="#z-tests-and-intervals" id="toc-z-tests-and-intervals">z Tests and Intervals</a>
  <ul>
  <li><a href="#a-worked-one-proportion-z-test" id="toc-a-worked-one-proportion-z-test">A worked one-proportion z test</a></li>
  <li><a href="#the-matching-interval-inverts-that-same-test" id="toc-the-matching-interval-inverts-that-same-test">The matching interval inverts that same test</a></li>
  </ul></li>
  <li><a href="#t-tests-and-intervals" id="toc-t-tests-and-intervals">t Tests and Intervals</a>
  <ul>
  <li><a href="#a-worked-one-sample-t-test-and-its-interval" id="toc-a-worked-one-sample-t-test-and-its-interval">A worked one-sample t test and its interval</a></li>
  <li><a href="#margin-of-error-is-a-property-of-a-plan-not-a-dataset-alone" id="toc-margin-of-error-is-a-property-of-a-plan-not-a-dataset-alone">Margin of error is a property of a plan, not a dataset alone</a></li>
  <li><a href="#the-t-approximation-is-not-a-mechanical-sample-size-rule" id="toc-the-t-approximation-is-not-a-mechanical-sample-size-rule">The t approximation is not a mechanical sample-size rule</a></li>
  </ul></li>
  <li><a href="#hypothesis-tests-and-compatible-values" id="toc-hypothesis-tests-and-compatible-values">Hypothesis Tests and Compatible Values</a>
  <ul>
  <li><a href="#what-a-p-value-is-not" id="toc-what-a-p-value-is-not">What a p-value is not</a></li>
  <li><a href="#a-test-statistic-measures-distance-on-an-uncertainty-scale" id="toc-a-test-statistic-measures-distance-on-an-uncertainty-scale">A test statistic measures distance on an uncertainty scale</a></li>
  <li><a href="#one-sided-tests-require-a-directional-commitment" id="toc-one-sided-tests-require-a-directional-commitment">One-sided tests require a directional commitment</a></li>
  <li><a href="#intervals-display-compatible-values" id="toc-intervals-display-compatible-values">Intervals display compatible values</a></li>
  <li><a href="#decisions-do-not-establish-truth" id="toc-decisions-do-not-establish-truth">Decisions do not establish truth</a></li>
  </ul></li>
  <li><a href="#match-the-method-to-the-design" id="toc-match-the-method-to-the-design">Match the Method to the Design</a>
  <ul>
  <li><a href="#familiar-t-procedures-are-regression-special-cases" id="toc-familiar-t-procedures-are-regression-special-cases">Familiar t procedures are regression special cases</a></li>
  <li><a href="#two-independent-means-add-variances-not-standard-errors" id="toc-two-independent-means-add-variances-not-standard-errors">Two independent means: add variances, not standard errors</a></li>
  <li><a href="#two-independent-proportions" id="toc-two-independent-proportions">Two independent proportions</a></li>
  <li><a href="#paired-observations-become-one-sample-of-differences" id="toc-paired-observations-become-one-sample-of-differences">Paired observations become one sample of differences</a></li>
  <li><a href="#freeze-the-analysis-sample-before-comparing-procedures" id="toc-freeze-the-analysis-sample-before-comparing-procedures">Freeze the analysis sample before comparing procedures</a></li>
  <li><a href="#the-synthetic-program-contrast-reveals-a-design-trap" id="toc-the-synthetic-program-contrast-reveals-a-design-trap">The synthetic program contrast reveals a design trap</a></li>
  </ul></li>
  <li><a href="#errors-power-effect-size-and-practical-importance" id="toc-errors-power-effect-size-and-practical-importance">Errors, Power, Effect Size, and Practical Importance</a>
  <ul>
  <li><a href="#the-significance-filter-distorts-selected-estimates" id="toc-the-significance-filter-distorts-selected-estimates">The significance filter distorts selected estimates</a></li>
  <li><a href="#contrast-magnitude-needs-units-and-uncertainty" id="toc-contrast-magnitude-needs-units-and-uncertainty">Contrast magnitude needs units and uncertainty</a></li>
  <li><a href="#statistical-and-practical-significance-are-separate-judgments" id="toc-statistical-and-practical-significance-are-separate-judgments">Statistical and practical significance are separate judgments</a></li>
  <li><a href="#prospective-precision-comes-before-data-collection" id="toc-prospective-precision-comes-before-data-collection">Prospective precision comes before data collection</a></li>
  <li><a href="#multiplicity-changes-the-evidence-landscape" id="toc-multiplicity-changes-the-evidence-landscape">Multiplicity changes the evidence landscape</a></li>
  </ul></li>
  <li><a href="#from-calculation-to-a-defensible-claim" id="toc-from-calculation-to-a-defensible-claim">From Calculation to a Defensible Claim</a>
  <ul>
  <li><a href="#technical-illustrations-that-stop-at-stat-c" id="toc-technical-illustrations-that-stop-at-stat-c">Technical illustrations that stop at STAT-C</a></li>
  <li><a href="#a-calibrated-results-paragraph" id="toc-a-calibrated-results-paragraph">A calibrated results paragraph</a></li>
  <li><a href="#calculation-follows-the-argument" id="toc-calculation-follows-the-argument">Calculation follows the argument</a></li>
  </ul></li>
  <li><a href="#argument-record-and-three-perspective-close" id="toc-argument-record-and-three-perspective-close">Argument Record and Three-Perspective Close</a>
  <ul>
  <li><a href="#argument-perspective-trace-the-four-role-specific-transitions" id="toc-argument-perspective-trace-the-four-role-specific-transitions">Argument perspective: trace the four role-specific transitions</a></li>
  <li><a href="#workflow-perspective-reconstruct-an-exploratory-analysis" id="toc-workflow-perspective-reconstruct-an-exploratory-analysis">Workflow perspective: reconstruct an exploratory analysis</a></li>
  <li><a href="#evaluation-perspective-calibrate-the-answer" id="toc-evaluation-perspective-calibrate-the-answer">Evaluation perspective: calibrate the answer</a></li>
  </ul></li>
  <li><a href="#reading-bridge" id="toc-reading-bridge">Reading Bridge</a></li>
  <li><a href="#references" id="toc-references">References</a></li>
  <li><a href="#exercises" id="toc-exercises">Exercises</a>
  <ul>
  <li><a href="#distinguish-the-inferential-objects" id="toc-distinguish-the-inferential-objects">Distinguish the Inferential Objects</a></li>
  <li><a href="#interpret-an-interval-procedure" id="toc-interpret-an-interval-procedure">Interpret an Interval Procedure</a></li>
  <li><a href="#match-the-method-to-the-design-1" id="toc-match-the-method-to-the-design-1">Match the Method to the Design</a></li>
  <li><a href="#write-one-bounded-answer" id="toc-write-one-bounded-answer">Write One Bounded Answer</a></li>
  </ul></li>
  </ul>
</nav>
<div style="page-break-after: always;"></div>
<div class="callout callout-style-default callout-tip callout-titled" title="Chapter box">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Chapter box
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Across comparable repetitions of the same two-school enrolment, course, grading, and recording process, how does mean final mathematics grade differ between Gabriel Pereira (GP) and Mousinho da Silveira (MS)?</p>
<p><strong>Candidate answer and status:</strong> No prospective hypothesis was specified. The comparison was chosen after the data were available and is exploratory.</p>
<p><strong>STAT-E — Empirical evidence:</strong> Final grades and observed school membership for 349 GP and 46 MS students. The documented final-grade scale is 0–20, all students have a final grade, and 38 recorded outcomes equal zero under the documented coding.</p>
<p><strong>STAT-J — Statistical justification:</strong> Welch inference is conditioned on the analytic inclusion rule and a stable process with independent students and finite school-specific variances; no probability sampling or school assignment is documented.</p>
<p><strong>STAT-I — Statistical inference:</strong> Estimate the GP-minus-MS mean contrast from all documented records, together with its standard error, interval, and exploratory test.</p>
<p><strong>STAT-C — Bounded statistical claim:</strong> The GP-minus-MS estimate is 0.64 points (95% CI [-0.70, 1.99]); the exploratory interval spans zero, so the direction of the comparable-process contrast remains inconclusive.</p>
<p><strong>SUB-E — Contextualized empirical evidence:</strong> The outcome is one end-of-year mathematics grade on a 0–20 scale for one cohort in each of two schools.</p>
<p><strong>SUB-J — Substantive justification:</strong> School was attended rather than assigned, and one course grade is a narrow measure of mathematics attainment.</p>
<p><strong>SUB-I — Substantive inference and interpretation:</strong> GP has the higher observed mean, but the model-conditioned interval remains compatible with differences in either direction and no educational-importance threshold was prespecified.</p>
<p><strong>SUB-C — Bounded substantive claim:</strong> GP’s observed cohort mean exceeds MS’s by 0.64 grade points. For the corresponding contrast across comparable repetitions, the exploratory 95% CI [-0.70, 1.99] leaves the direction inconclusive; no causal school effect or broader population transport is supported.</p>
</div>
</div>
<section id="opening-problem" class="level2">
<h2 class="anchored" data-anchor-id="opening-problem">Opening Problem</h2>
<p>The sustained research question compares mean final mathematics grade between students represented by GP and MS. The evidence contains 395 students from two Portuguese secondary schools and was curated from the public Student Performance dataset <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>. It is observational: neither students’ entry into the dataset nor school membership arose from a documented probability-sampling or randomized-assignment mechanism.</p>
<p>The observed cohort difference is an exact description of these students. An interval requires a different target: a contrast for comparable repetitions of the same two-school enrolment, course, grading, and curation process. The model extends beyond the observed cohort only under stability and independence conditions; it does not extend to other schools or populations.</p>
<p>The chapter also uses one-mean, one-proportion, paired, bootstrap, power, and simulation examples with a fully stated probability process as <strong>technical illustrations</strong>. Each clarifies a statistical mechanism and may properly stop at a bounded statistical claim (<code>STAT-C</code>) rather than acquire an artificial substantive claim.</p>
<div class="callout callout-style-default callout-important callout-titled" title="The central discipline">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>The central discipline
</div>
</div>
<div class="callout-body-container callout-body">
<p>Statistical inference does not turn a convenience dataset into a random sample, repair attrition, remove measurement error, or create a causal comparison. It quantifies a specified kind of uncertainty under a stated model. A defensible claim keeps that model-based uncertainty separate from design and measurement limitations.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Three perspectives on the same question">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Three perspectives on the same question
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Perspective</th>
<th style="text-align: left;">Work in this chapter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Argument</strong></td>
<td style="text-align: left;">Build <code>STAT-E + STAT-J -&gt; STAT-I -&gt; STAT-C</code>; then let <code>SUB-E</code> situate <code>STAT-E</code>, <code>SUB-J</code> augment and evaluate <code>STAT-J</code>, <code>SUB-I</code> interpret <code>STAT-I</code>, and <code>STAT-C</code> bound and calibrate <code>SUB-C</code>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Workflow</strong></td>
<td style="text-align: left;">Reconstruct how an exploratory question is framed, specify its target and method, estimate and check it, interpret it substantively, and communicate one bounded answer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Evaluation</strong></td>
<td style="text-align: left;">Check Question alignment, Evidence integrity, Justification adequacy, Inferential adequacy, Transition fidelity, Claim calibration, and Cross-question coherence without treating them as a score.</td>
</tr>
</tbody>
</table>
<p>The closing application makes these perspectives explicit. The intervening method blocks supply the statistical mechanisms needed for that application.</p>
</div>
</div>
</section>
<section id="five-inferential-objects" class="level2">
<h2 class="anchored" data-anchor-id="five-inferential-objects">Five Inferential Objects</h2>
<p>Statistical language becomes much clearer when five nouns are kept separate. <a href="#tbl-inferential-objects" class="quarto-xref">Table&nbsp;1</a> names each one, the question it answers, and the form it takes in the school comparison used throughout this chapter.</p>
<p>The two schools in the worked dataset are Gabriel Pereira (<strong>GP</strong>) and Mousinho da Silveira (<strong>MS</strong>).</p>
<div id="tbl-inferential-objects" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[18,50,32]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-inferential-objects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Five inferential objects that must remain distinct.
</figcaption>
<div aria-describedby="tbl-inferential-objects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 50%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Object</th>
<th>Question it answers</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Parameter</strong></td>
<td>What fixed but unknown feature of a population or process is being described?</td>
<td>a population mean final grade, <span class="math inline">\(\mu\)</span></td>
</tr>
<tr class="even">
<td><strong>Estimand</strong></td>
<td>Which parameter or contrast is the analysis intended to learn?</td>
<td><span class="math inline">\(\mu_{GP}-\mu_{MS}\)</span> for two school-specific means</td>
</tr>
<tr class="odd">
<td><strong>Estimator</strong></td>
<td>Which rule will turn a random sample into an estimate?</td>
<td><span class="math inline">\(\bar X_{GP}-\bar X_{MS}\)</span></td>
</tr>
<tr class="even">
<td><strong>Estimate</strong></td>
<td>What number did that rule produce in this dataset?</td>
<td>0.64 grade points</td>
</tr>
<tr class="odd">
<td><strong>Standard error (SE)</strong></td>
<td>How much would the estimator ordinarily vary across repeated studies under the model?</td>
<td>0.672 grade points</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A <strong>statistic</strong> is any numerical function of observed data. An estimator is a statistic used as a rule for learning an estimand. The same observed number can therefore play different roles depending on the question.</p>
<section id="the-estimand-must-precede-the-calculation" class="level3">
<h3 class="anchored" data-anchor-id="the-estimand-must-precede-the-calculation">The estimand must precede the calculation</h3>
<p>Suppose <span class="math inline">\(Y\)</span> is final grade and <span class="math inline">\(G\)</span> identifies school. A marginal difference in school means is</p>
<p><span class="math display">\[
\Delta=E(Y\mid G=GP)-E(Y\mid G=MS).
\]</span></p>
<p>This is not automatically a causal effect of attending one school rather than the other. The recorded students were not randomly assigned to schools, and the two school samples may differ in prior preparation, neighborhood, selection, or other features. The estimand remains a non-causal between-school contrast unless a stronger design argument is supplied. The next section separates its two forms, one fixed to the records in hand and one defined for the process that produced them.</p>
<p>The synthetic program example raises a different issue. Assignment was randomized among consenters, but final scores are missing for some assigned students. A complete-case contrast describes observed completers. It is not automatically the intention-to-treat effect among everyone assigned, because completion occurs after assignment and differs across programs.</p>
</section>
<section id="an-observed-sample-description-and-a-superpopulation-estimand-are-different-targets" class="level3">
<h3 class="anchored" data-anchor-id="an-observed-sample-description-and-a-superpopulation-estimand-are-different-targets">An observed-sample description and a superpopulation estimand are different targets</h3>
<p>Two targets can share the same arithmetic and still be different objects, and Chapter 1 separates them in both of its worked studies.</p>
<p>For the 395 students in the analytic sample, the GP mean minus the MS mean is exactly 0.64 grade points, conditional on the recorded observations and their documented coding. That number is an <strong>observed-sample description</strong>. No sampling interval is needed for this fixed descriptive contrast. Attaching one would confuse a description of the records with inference about a stochastic target.</p>
<p>A confidence interval and a test require a <strong>stochastic</strong> target. For the school comparison this chapter therefore defines the model-based superpopulation estimand</p>
<p><span class="math display">\[
\Delta_{\mathcal S}=
E(Y\mid G=GP,\mathcal S)-E(Y\mid G=MS,\mathcal S),
\]</span></p>
<p>where <span class="math inline">\(\mathcal S\)</span> is a hypothetical superpopulation of student records generated by the same two-school enrolment, course, grading, and curation process that produced these data. <span class="math inline">\(\Delta_{\mathcal S}\)</span> is not a feature of the 395 observed students; it is a feature of the process imagined to have produced them, and it is the only quantity the Welch interval and p-value in this chapter describe.</p>
<p>Naming that target obliges the analysis to state five things before any interval is reported.</p>
<ol type="1">
<li><strong>The repetition being imagined.</strong> Fresh cohorts of records produced by the same two-school process, not a fresh probability sample from all Portuguese students. The repetition is a modelling device; the documentation records no sampling or assignment mechanism that would make it a design fact <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>.</li>
<li><strong>Dependence.</strong> Students are treated as independent within each school-specific distribution, with no residual within-school or within-class dependence left unaccounted for in the standard error. Only two schools appear, so between-school variation cannot be estimated from these data at all.</li>
<li><strong>Missingness and selection.</strong> The curated variables contain no blank cells, so no missing-data model is fitted. The estimand instead <em>conditions on</em> inclusion in the analytic sample, and the 38 grades recorded as zero are retained under the documented coding rather than treated as unrecorded outcomes.</li>
<li><strong>Process stability.</strong> The record-generating process is assumed unchanged across the recorded year, so that each group is a draw from a stable distribution with finite variance.</li>
<li><strong>Prespecification status.</strong> The contrast was chosen to illustrate a two-sample procedure after the data were already available. It is therefore <strong>exploratory</strong>: its p-value is model-based evidence under the working model, not confirmatory control of a prespecified error rate.</li>
</ol>
<p>Those five statements contribute to <code>STAT-J</code>, and <span class="math inline">\(\Delta_{\mathcal S}\)</span> is the target that <code>STAT-I</code>, <code>STAT-C</code>, <code>SUB-I</code>, and <code>SUB-C</code> must continue to describe. The same distinction governs the other estimands below: every interval in this chapter describes a modelled process quantity, while the matching sample summary describes only the observed students.</p>
<p>The four worked procedures use one compact <strong>inferential contract</strong> rather than silently changing targets from section to section. The targets, inferential units, and matched procedures are summarized in <a href="#tbl-shared-inferential-contract" class="quarto-xref">Table&nbsp;2</a>.</p>
<div id="tbl-shared-inferential-contract" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[29,39,32]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-shared-inferential-contract-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Shared stochastic targets for the four performance-data procedures.
</figcaption>
<div aria-describedby="tbl-shared-inferential-contract-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 39%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Recorded question</th>
<th>Model-based estimand in <span class="math inline">\(\mathcal S\)</span></th>
<th>Inferential unit and procedure</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>What fraction passed?</td>
<td><span class="math inline">\(p_{\mathcal S}=P(Y\ge 10\mid\mathcal S)\)</span></td>
<td>student; score test and Wilson interval</td>
</tr>
<tr class="even">
<td>What is mean final grade?</td>
<td><span class="math inline">\(\mu_{\mathcal S}=E(Y\mid\mathcal S)\)</span></td>
<td>student; one-sample <span class="math inline">\(t\)</span> procedure</td>
</tr>
<tr class="odd">
<td>How do schools differ?</td>
<td><span class="math inline">\(\Delta_{\mathcal S}=E(Y\mid G=GP,\mathcal S)-E(Y\mid G=MS,\mathcal S)\)</span></td>
<td>student within school; Welch procedure</td>
</tr>
<tr class="even">
<td>How did grades change?</td>
<td><span class="math inline">\(\mu_{D,\mathcal S}=E(G_2-G_1\mid\mathcal S)\)</span></td>
<td>one paired difference per student; one-sample <span class="math inline">\(t\)</span> procedure</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Here <span class="math inline">\(\mathcal S\)</span> always means a hypothetical repetition of the same two-school enrolment, course, grading, and curation process, not a wider student population. The unpaired procedures treat students as independent; the paired procedure instead treats the student-level differences as independent and retains the two grades’ within-student dependence. Each analysis conditions on inclusion in the analytic sample, fits no missing-data model because the variables used have no blank cells, and retains recorded zeros under the documented coding. It also assumes a stable process with the finite moments required by its procedure. All four questions were chosen after the data were available, so their tests are exploratory. Exact one-sample <span class="math inline">\(t\)</span> inference additionally requires independent Normal observations; the score, Welch, and non-Normal <span class="math inline">\(t\)</span> uses here are model-based approximations whose adequacy must be checked rather than inferred from a universal sample-size rule.</p>
</section>
<section id="estimator-quality-has-more-than-one-dimension" class="level3">
<h3 class="anchored" data-anchor-id="estimator-quality-has-more-than-one-dimension">Estimator quality has more than one dimension</h3>
<p>Across repeated studies, an estimator can be judged by:</p>
<ul>
<li><strong>bias:</strong> whether its sampling distribution is centered on the estimand;</li>
<li><strong>sampling variability:</strong> how widely estimates vary;</li>
<li><strong>mean squared error:</strong> a combination of squared bias and variance; and</li>
<li><strong>robustness:</strong> how sensitive the estimator and its uncertainty are to plausible departures from assumptions.</li>
</ul>
<p>An unbiased estimator can be too variable to be useful. A precise estimator can be precisely wrong if the sample, measurement, or model targets the wrong quantity. Precision is not validity.</p>
</section>
</section>
<section id="sampling-variation-and-standard-errors" class="level2">
<h2 class="anchored" data-anchor-id="sampling-variation-and-standard-errors">Sampling Variation and Standard Errors</h2>
<p>Imagine repeatedly sampling <span class="math inline">\(n\)</span> independent observations from a process with mean 10 and standard deviation 4. Each study produces a different sample mean. The distribution of those means is the <strong>sampling distribution</strong> of <span class="math inline">\(\bar X\)</span>, shown in <a href="#fig-sampling-means" class="quarto-xref">Figure&nbsp;1</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sampling-means" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two histograms are centered near 10. The histogram for sample size 100 is about half as wide as the histogram for sample size 25." data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sampling-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_03_files/figure-html/fig-sampling-means-1.png" class="img-fluid figure-img" data-fig-pos="H" alt="Two histograms are centered near 10. The histogram for sample size 100 is about half as wide as the histogram for sample size 25." width="691">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sampling-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Repeated-sample distributions of the sample mean from the same process. Increasing the sample size from 25 to 100 halves the standard error without changing the population standard deviation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For independent observations with population standard deviation (SD) <span class="math inline">\(\sigma\)</span>, the standard error (SE), the modeled repeated-study SD of the estimator, is</p>
<p><span class="math display">\[
SE(\bar X)=\frac{\sigma}{\sqrt n}.
\]</span></p>
<p>Because <span class="math inline">\(\sigma\)</span> is usually unknown, the one-sample standard error is estimated by <span class="math inline">\(s/\sqrt n\)</span>. The simulation in <a href="#tbl-sampling-se" class="quarto-xref">Table&nbsp;3</a> checks the familiar square-root relationship.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-sampling-se" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sampling-se-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Simulated sampling distribution of the sample mean at two sample sizes. The empirical standard error across 5,000 repeated samples matches the theoretical value <span class="math inline">\(\sigma/\sqrt{n}\)</span>.
</figcaption>
<div aria-describedby="tbl-sampling-se-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(n\)</span></th>
<th style="text-align: right;">Mean of estimates</th>
<th style="text-align: right;">Empirical SE</th>
<th style="text-align: right;">Theoretical SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: right;">9.993</td>
<td style="text-align: right;">0.790</td>
<td style="text-align: right;">0.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">100</td>
<td style="text-align: right;">10.001</td>
<td style="text-align: right;">0.406</td>
<td style="text-align: right;">0.4</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The empirical standard error is approximately 0.79 for <span class="math inline">\(n=25\)</span> and 0.41 for <span class="math inline">\(n=100\)</span>. Four times as many independent observations produce about half the standard error, not one quarter.</p>
<section id="standard-deviation-and-standard-error-answer-different-questions" class="level3">
<h3 class="anchored" data-anchor-id="standard-deviation-and-standard-error-answer-different-questions">Standard deviation and standard error answer different questions</h3>
<ul>
<li>The <strong>standard deviation</strong> describes variation among individual observed values.</li>
<li>The <strong>standard error</strong> describes modeled repeated-study variation in an estimator.</li>
</ul>
<p>Increasing <span class="math inline">\(n\)</span> can make a mean more precise while individual outcomes remain highly variable. Conversely, duplicating observations does not create information: the square-root rule assumes new observations that contribute the kind of independent information specified by the model.</p>
</section>
<section id="dependence-changes-the-information-count" class="level3">
<h3 class="anchored" data-anchor-id="dependence-changes-the-information-count">Dependence changes the information count</h3>
<p>Students in the same class or school can share instruction, policy, peers, and context. Treating clustered observations as independent can make standard errors too small. For equal cluster size <span class="math inline">\(m\)</span> and intraclass correlation <span class="math inline">\(\rho\)</span>, a simple planning approximation for the <strong>design effect (DEFF)</strong> is</p>
<p><span class="math display">\[
DEFF=1+(m-1)\rho.
\]</span></p>
<p>This quantity is not a substitute for a cluster-aware analysis. It shows why 300 students in 12 schools do not necessarily contain the same information as 300 independent students.</p>
</section>
<section id="bootstrap-intuition-and-its-boundary" class="level3">
<h3 class="anchored" data-anchor-id="bootstrap-intuition-and-its-boundary">Bootstrap intuition and its boundary</h3>
<p>A nonparametric bootstrap repeatedly samples observed cases with replacement and recalculates the statistic <span class="citation" data-cites="efron1979">(<a href="#ref-efron1979" role="doc-biblioref">Efron, 1979</a>)</span>. The spread of the bootstrap statistics estimates sampling variation using the empirical distribution as a stand-in for the population <span class="citation" data-cites="efron1993">(<a href="#ref-efron1993" role="doc-biblioref">Efron &amp; Tibshirani, 1993</a>)</span>.</p>
<p>Bootstrap resampling does not recreate unobserved nonrespondents, repair a biased sampling frame, invent missing clusters, correct an unreliable measure, or validate an estimator. The resampling unit must also match the design: independently resampling students is inappropriate when the intended uncertainty requires resampling schools or matched pairs.</p>
</section>
<section id="four-distributions-that-must-not-be-collapsed" class="level3">
<h3 class="anchored" data-anchor-id="four-distributions-that-must-not-be-collapsed">Four distributions that must not be collapsed</h3>
<p>The word “distribution” appears in several roles, and <a href="#tbl-four-inferential-distributions" class="quarto-xref">Table&nbsp;4</a> keeps them apart.</p>
<div id="tbl-four-inferential-distributions" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[20,27,30,23]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-four-inferential-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Four distributions used for different inferential tasks.
</figcaption>
<div aria-describedby="tbl-four-inferential-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 27%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Distribution</th>
<th>What varies?</th>
<th>What is held fixed?</th>
<th>Main use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>data distribution</td>
<td>individual observed values</td>
<td>the realized dataset</td>
<td>describe cases</td>
</tr>
<tr class="even">
<td>sampling distribution</td>
<td>an estimator across repeated samples</td>
<td>population/process and sample size</td>
<td>define bias and SE</td>
</tr>
<tr class="odd">
<td>null distribution</td>
<td>a test statistic across repetitions under <span class="math inline">\(H_0\)</span></td>
<td>null value and test design</td>
<td>calculate p-values</td>
</tr>
<tr class="even">
<td>bootstrap distribution</td>
<td>a statistic across resamples of the observed data</td>
<td>empirical dataset and resampling rule</td>
<td>estimate sampling uncertainty</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The bootstrap distribution is not automatically a null distribution. For an interval, cases are resampled without imposing a null claim. For a randomization test, treatment labels or outcomes are rearranged under a specific no-effect or exchangeability condition. Both are simulations, but they simulate different reference processes.</p>
</section>
<section id="a-transparent-stratified-bootstrap" class="level3">
<h3 class="anchored" data-anchor-id="a-transparent-stratified-bootstrap">A transparent stratified bootstrap</h3>
<p>For the Retrieval-minus-Standard mean difference, a bootstrap resamples students within each observed program group so that both group sizes remain fixed. In each repetition, sample students with replacement separately within the two groups, calculate the difference in sample means, and retain that difference. Percentiles of the resulting distribution form the interval.</p>
<p>The procedure makes three choices explicit: the statistic is a difference in means, the resampling unit is a student, and the observed groups are resampled separately. If schools were the sampling units, this algorithm would be too optimistic because it treats students within a school as if they supplied independent replication.</p>
</section>
</section>
<section id="confidence-intervals-and-coverage" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals-and-coverage">Confidence Intervals and Coverage</h2>
<p>A confidence interval combines an estimate with its modeled sampling uncertainty. A common form is</p>
<p><span class="math display">\[
\text{estimate}\ \pm\ \text{critical value}\times SE.
\]</span></p>
<p>For a mean with unknown population standard deviation, the critical value comes from a <span class="math inline">\(t\)</span> distribution. The degrees of freedom reflect how the standard error was estimated.</p>
<section id="coverage-belongs-to-the-procedure" class="level3">
<h3 class="anchored" data-anchor-id="coverage-belongs-to-the-procedure">Coverage belongs to the procedure</h3>
<p>In repeated use under its assumptions, a 95% confidence-interval procedure covers the fixed estimand in about 95% of studies. A particular computed interval either covers or misses; the frequentist statement does not assign a 95% posterior probability to the fixed parameter. <a href="#fig-confidence-coverage" class="quarto-xref">Figure&nbsp;2</a> displays forty intervals produced by that procedure from the same known process.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-confidence-coverage" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Forty horizontal confidence intervals are plotted against a vertical truth line at 10. Most cross the truth line and a few do not." data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confidence-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_03_files/figure-html/fig-confidence-coverage-1.png" class="img-fluid figure-img" data-fig-pos="H" alt="Forty horizontal confidence intervals are plotted against a vertical truth line at 10. Most cross the truth line and a few do not." width="691">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confidence-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Forty 95 percent confidence intervals from repeated samples of size 25. Dark intervals miss the true mean of 10; misses are expected even when the procedure has correct long-run coverage.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Across 5,000 simulated studies, the estimated coverage was 94.7% for <span class="math inline">\(n=25\)</span> and 95.3% for <span class="math inline">\(n=100\)</span>. The larger sample reduced average interval width from 3.26 to 1.59 while retaining approximately the same coverage.</p>
</section>
</section>
<section id="z-tests-and-intervals" class="level2">
<h2 class="anchored" data-anchor-id="z-tests-and-intervals">z Tests and Intervals</h2>
<p>A <span class="math inline">\(z\)</span> procedure uses a standard Normal reference distribution. For a mean, the classical statistic</p>
<p><span class="math display">\[Z=\frac{\bar X-\mu_0}{\sigma/\sqrt n}\]</span></p>
<p>requires the population standard deviation <span class="math inline">\(\sigma\)</span> to be known from outside the current sample, a rare situation in social and behavioral research <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Its standard Normal reference is exact for independent observations from a Normal population with known <span class="math inline">\(\sigma\)</span>. With non-Normal observations it is an approximation that requires a justified Normal approximation for the sample mean. Replacing <span class="math inline">\(\sigma\)</span> with the sample SD changes the reference procedure to a <span class="math inline">\(t\)</span> procedure, developed in the next section.</p>
<p>One case does justify a <span class="math inline">\(z\)</span> reference with real data. A binary outcome has no separate variance parameter: once the null value <span class="math inline">\(p_0\)</span> is fixed, the standard error is fixed too. The <strong>null standard error</strong> is therefore <span class="math inline">\(\sqrt{p_0(1-p_0)/n}\)</span>, a known number rather than an estimate, and for a large sample the standardized statistic is approximately standard Normal.</p>
<section id="a-worked-one-proportion-z-test" class="level3">
<h3 class="anchored" data-anchor-id="a-worked-one-proportion-z-test">A worked one-proportion z test</h3>
<p>There were 265 recorded passes among 395 students, so <span class="math inline">\(\widehat p=0.671\)</span>. Ask whether these data are compatible with an even split.</p>
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:p=0.50\)</span> against the two-sided <span class="math inline">\(H_A:p\ne0.50\)</span>, where <span class="math inline">\(p\)</span> is the pass probability in the student-level model.</li>
<li><strong>Null standard error.</strong> With <span class="math inline">\(p_0=0.50\)</span> and <span class="math inline">\(n=395\)</span>, <span class="math inline">\(\sqrt{p_0(1-p_0)/n}=0.0252\)</span>.</li>
<li><strong>Test statistic.</strong> <span class="math inline">\(z=(\widehat p-p_0)/\sqrt{p_0(1-p_0)/n}=6.79\)</span>. There are no degrees of freedom to report: the reference distribution is standard Normal, not a family indexed by an estimated variance.</li>
<li><strong>P-value.</strong> Two-sided, <span class="math inline">\(2\Phi(-|z|)\)</span>, where <span class="math inline">\(\Phi\)</span> is the standard Normal cumulative distribution function. The value is &lt; .001.</li>
<li><strong>Interpretation.</strong> The observed pass rate is about 6.8 null standard errors above 0.50. These 395 records are strongly incompatible with an even pass-fail split, under a model that treats the students as independent draws.</li>
</ol>
<p>R’s <code>prop.test()</code> with the continuity correction switched off reports the same test as <span class="math inline">\(\chi^2=46.14\)</span>, which is exactly <span class="math inline">\(z^2=46.14\)</span>, with the same p-value.</p>
</section>
<section id="the-matching-interval-inverts-that-same-test" class="level3">
<h3 class="anchored" data-anchor-id="the-matching-interval-inverts-that-same-test">The matching interval inverts that same test</h3>
<p>The familiar Wald interval <span class="math inline">\(\widehat p\pm z^*\sqrt{\widehat p(1-\widehat p)/n}\)</span> replaces <span class="math inline">\(p_0\)</span> by <span class="math inline">\(\widehat p\)</span> in the standard error. Here that plug-in SE is 0.0236 rather than the null-value 0.0252, and the Wald form can behave poorly with small samples or proportions near 0 or 1.</p>
<p>The <strong>Wilson score interval</strong> avoids the substitution <span class="citation" data-cites="wilson1927">(<a href="#ref-wilson1927" role="doc-biblioref">Wilson, 1927</a>)</span>. It inverts the score test: it collects every null value <span class="math inline">\(p_0\)</span> that the test above would <em>not</em> reject, and each of those tests uses its own null standard error <span class="math inline">\(\sqrt{p_0(1-p_0)/n}\)</span>. Far from avoiding the null standard error, the score interval is built from it; what it declines to use is the plug-in Wald SE. Solving the resulting quadratic gives</p>
<p><span class="math display">\[
\frac{\widehat p+z^{*2}/(2n)}{1+z^{*2}/n}
\ \pm\
\frac{z^*}{1+z^{*2}/n}
\sqrt{\frac{\widehat p(1-\widehat p)}{n}+\frac{z^{*2}}{4n^2}}.
\]</span></p>
<p>The 95% Wilson interval is [0.623, 0.715], which <code>prop.test(..., correct = FALSE)</code> reproduces exactly because it is the same inversion. It stays inside the possible 0-1 range and excludes 0.50, matching the rejection at the 5% level. Its scope is still limited by how the students entered the dataset.</p>
</section>
</section>
<section id="t-tests-and-intervals" class="level2">
<h2 class="anchored" data-anchor-id="t-tests-and-intervals">t Tests and Intervals</h2>
<p>When the SD in the denominator must be estimated from the same sample, that extra uncertainty widens the reference distribution. For independent observations from a Normal population with a common unknown variance, and under <span class="math inline">\(H_0:\mu=\mu_0\)</span>, the standardized statistic follows Student’s <span class="math inline">\(t\)</span> distribution exactly <span class="citation" data-cites="student1908">(<a href="#ref-student1908" role="doc-biblioref">Student, 1908</a>)</span>:</p>
<p><span class="math display">\[T=\frac{\bar X-\mu_0}{s/\sqrt n},\qquad df=n-1.\]</span></p>
<p>The degrees of freedom record how much information was spent estimating the SD. Replacing <span class="math inline">\(\sigma\)</span> by <span class="math inline">\(s\)</span> alone does not create exactness; independence and the Normal-error model are part of the result. In regression, the analogous exact statement is conditional on a fixed, full-rank design with independent Normal errors of constant variance. The same design and model must govern both the test and the interval. Welch’s two-sample procedure estimates a separate variance in each independent group, while paired inference first reduces each pair to one difference.</p>
<section id="a-worked-one-sample-t-test-and-its-interval" class="level3">
<h3 class="anchored" data-anchor-id="a-worked-one-sample-t-test-and-its-interval">A worked one-sample t test and its interval</h3>
<p>Use 10 as an <strong>illustrative benchmark for the modelled mean</strong>. Although 10 is also the individual pass cutoff in this dataset, comparing a mean with 10 does not estimate the fraction of students who passed; that is the distinct <span class="math inline">\(p_{\mathcal S}\)</span> question analyzed above.</p>
<ol type="1">
<li><strong>Hypotheses.</strong> <span class="math inline">\(H_0:\mu_{\mathcal S}=10\)</span> against the two-sided <span class="math inline">\(H_A:\mu_{\mathcal S}\ne10\)</span>.</li>
<li><strong>Estimate and standard error.</strong> <span class="math inline">\(\bar X=10.42\)</span> with <span class="math inline">\(s=4.58\)</span> over <span class="math inline">\(n=395\)</span> students, so <span class="math inline">\(s/\sqrt n=0.231\)</span>. Here <span class="math inline">\(\sigma\)</span> was estimated rather than known, which is exactly why the reference is <span class="math inline">\(t\)</span> and not <span class="math inline">\(z\)</span>.</li>
<li><strong>Test statistic and degrees of freedom.</strong> Dividing the unrounded departure <span class="math inline">\(\bar X-10\)</span> by the unrounded <span class="math inline">\(s/\sqrt n\)</span> gives <span class="math inline">\(t=1.80\)</span> with <span class="math inline">\(df=n-1=394\)</span>.</li>
<li><strong>P-value.</strong> Two-sided, <span class="math inline">\(p=.072\)</span>.</li>
<li><strong>Matching interval.</strong> With <span class="math inline">\(t^*=1.966\)</span>, the 95% interval is [9.96, 10.87] on the original 0-20 grade scale.</li>
<li><strong>Interpretation.</strong> The interval contains the illustrative benchmark of 10 and the two-sided test does not reject it at the 5% level. The two statements agree because they use the same estimator, standard error, and reference distribution. These data remain compatible with a process mean from just below 10 to about nine-tenths of a grade point above it.</li>
</ol>
<p>The interval describes uncertainty for a mean under an independent-student sampling model. The dataset documentation does not justify treating these students as a probability sample of all Portuguese students.</p>
</section>
<section id="margin-of-error-is-a-property-of-a-plan-not-a-dataset-alone" class="level3">
<h3 class="anchored" data-anchor-id="margin-of-error-is-a-property-of-a-plan-not-a-dataset-alone">Margin of error is a property of a plan, not a dataset alone</h3>
<p>The half-width of a symmetric interval is its margin of error. It depends on the confidence level, estimated variability, sample size, design, and estimator. A higher confidence level widens the interval because a larger critical value is needed. A larger effective sample size narrows it. More decimal places do not create precision.</p>
<p>Before collecting data, a precision target can be more defensible than a ritual power target. “Estimate the mean within one grade point” names an outcome-scale goal. The planning calculation must still state the SD used, expected attrition, clustering, and whether the interval concerns one mean or a difference.</p>
</section>
<section id="the-t-approximation-is-not-a-mechanical-sample-size-rule" class="level3">
<h3 class="anchored" data-anchor-id="the-t-approximation-is-not-a-mechanical-sample-size-rule">The t approximation is not a mechanical sample-size rule</h3>
<p>The one-sample <span class="math inline">\(t\)</span> procedure is exact for independent Normal observations and often approximately reliable for a mean with moderate non-Normality. It is not guaranteed by a universal rule such as <span class="math inline">\(n\ge30\)</span>. Severe skew, extreme outliers, dependence, or a mean dominated by rare values can remain important at larger <span class="math inline">\(n\)</span>. Inspect the data, understand the design, and ask whether the mean itself is the intended target.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>What a conventional interval omits
</div>
</div>
<div class="callout-body-container callout-body">
<p>A confidence interval ordinarily quantifies uncertainty from the specified sampling or assignment model. It does not automatically include uncertainty from nonrandom selection, measurement validity, missing-data assumptions, researcher choices, model misspecification, or unmodeled clustering.</p>
</div>
</div>
</section>
</section>
<section id="hypothesis-tests-and-compatible-values" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-tests-and-compatible-values">Hypothesis Tests and Compatible Values</h2>
<p>A hypothesis test compares the observed statistic with values expected under a specified null model. Its parts should be visible.</p>
<ol type="1">
<li><strong>Null hypothesis <span class="math inline">\(H_0\)</span>:</strong> a precise reference claim about the estimand.</li>
<li><strong>Alternative hypothesis <span class="math inline">\(H_A\)</span>:</strong> the prespecified direction or set of departures of scientific interest.</li>
<li><strong>Test statistic:</strong> the observed departure from the null, scaled by its standard error.</li>
<li><strong>Reference distribution:</strong> the distribution of that statistic when the null model and assumptions hold.</li>
<li><strong>P-value:</strong> the null-model probability of a statistic at least as incompatible with <span class="math inline">\(H_0\)</span> as the observed statistic, in the direction(s) specified by <span class="math inline">\(H_A\)</span>.</li>
</ol>
<p>The worked final-grade test above supplies all five parts: <span class="math inline">\(H_0:\mu=10\)</span>; the two-sided <span class="math inline">\(H_A:\mu\ne10\)</span>; the statistic <span class="math inline">\(t(394)=
1.80\)</span>; the <span class="math inline">\(t\)</span> reference distribution on 394 degrees of freedom; and <span class="math inline">\(p=.072\)</span>. The rest of this section examines what that last number does and does not support.</p>
<section id="what-a-p-value-is-not" class="level3">
<h3 class="anchored" data-anchor-id="what-a-p-value-is-not">What a p-value is not</h3>
<p>The American Statistical Association emphasizes that a p-value measures compatibility with a specified model, not the truth or importance of a claim <span class="citation" data-cites="wasserstein2016">(<a href="#ref-wasserstein2016" role="doc-biblioref">Wasserstein &amp; Lazar, 2016</a>)</span>. A p-value is not:</p>
<ul>
<li>the probability that <span class="math inline">\(H_0\)</span> is true;</li>
<li>the probability that the result occurred “by chance”;</li>
<li>the probability that replication will succeed;</li>
<li>the magnitude or importance of the association; or</li>
<li>the study’s false-positive probability after seeing the result.</li>
</ul>
<p>It is conditional on the null model, test statistic, sampling or assignment mechanism, and analysis choices.</p>
</section>
<section id="a-test-statistic-measures-distance-on-an-uncertainty-scale" class="level3">
<h3 class="anchored" data-anchor-id="a-test-statistic-measures-distance-on-an-uncertainty-scale">A test statistic measures distance on an uncertainty scale</h3>
<p>The numerator of a <span class="math inline">\(t\)</span> statistic is an estimated difference from the null. The denominator is the standard error appropriate to that estimate. Thus <span class="math inline">\(t=2\)</span> means the estimate is two modeled standard errors from the null value; it does not mean that the effect is two outcome units or twice as important. <a href="#fig-t-reference" class="quarto-xref">Figure&nbsp;3</a> shows where the observed statistic falls under its null model.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-t-reference" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A t density centered at zero has both tails beyond plus or minus the observed test statistic shaded." data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-t-reference-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_03_files/figure-html/fig-t-reference-1.png" class="img-fluid figure-img" data-fig-pos="H" alt="A t density centered at zero has both tails beyond plus or minus the observed test statistic shaded." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-t-reference-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Two-sided reference distribution for the one-sample final-grade test. The p-value is the total null-model area at least as far from zero as the observed absolute t statistic.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The shaded area is .072. It answers a conditional question about repeated statistics under <span class="math inline">\(H_0:\mu=10\)</span>; it does not assign probability to that hypothesis.</p>
</section>
<section id="one-sided-tests-require-a-directional-commitment" class="level3">
<h3 class="anchored" data-anchor-id="one-sided-tests-require-a-directional-commitment">One-sided tests require a directional commitment</h3>
<p>For an upper-tailed alternative <span class="math inline">\(H_A:\theta&gt;\theta_0\)</span>,</p>
<p><span class="math display">\[p=P_{H_0}(T\ge t_{obs}).\]</span></p>
<p>For a lower-tailed alternative, the lower tail is used. A one-sided test is defensible only when the direction was scientifically meaningful and fixed before seeing the outcome, an effect in the opposite direction would not support the claim, and the reference distribution matches the test.</p>
<p>For a symmetric <span class="math inline">\(t\)</span> reference distribution, a one-sided p-value equals half the two-sided p-value only when the observed statistic points toward the prespecified alternative. The paired grade change is negative. Its two-sided p-value is .050. A prespecified lower-tailed test gives <span class="math inline">\(p=.025\)</span>; an upper-tailed test gives <span class="math inline">\(p=.975\)</span>. Choosing the favorable direction after seeing the negative estimate would invalidate the advertised Type I error rate.</p>
</section>
<section id="intervals-display-compatible-values" class="level3">
<h3 class="anchored" data-anchor-id="intervals-display-compatible-values">Intervals display compatible values</h3>
<p>For the paired difference <span class="math inline">\(D=G_2-G_1\)</span>, the estimated mean change is -0.195 grade points with a 95% interval from -0.390 to 0.000. Values inside this interval are more compatible with the data and <span class="math inline">\(t\)</span> model than values outside it, at the stated confidence level. This does not mean that every inside value is equally plausible or that every outside value is impossible.</p>
<p>The interval is often more informative than a binary decision. Here it rules out a large mean change but does not distinguish a very small negative change from zero at the conventional two-sided 5% threshold.</p>
<p>The test-interval correspondence has conditions. A two-sided level-<span class="math inline">\(\alpha\)</span> test rejects <span class="math inline">\(\theta_0\)</span> exactly when the corresponding <span class="math inline">\(100(1-\alpha)\)</span>% interval excludes <span class="math inline">\(\theta_0\)</span> only when both procedures use the same estimator, standard error, reference model, sidedness, and multiplicity treatment. A bootstrap percentile interval and a parametric <span class="math inline">\(t\)</span> test need not correspond exactly. A one-sided test corresponds to a one-sided confidence bound, not automatically to a two-sided interval.</p>
</section>
<section id="decisions-do-not-establish-truth" class="level3">
<h3 class="anchored" data-anchor-id="decisions-do-not-establish-truth">Decisions do not establish truth</h3>
<p>If a prespecified decision threshold is needed, report <strong>reject <span class="math inline">\(H_0\)</span></strong> or <strong>fail to reject <span class="math inline">\(H_0\)</span></strong>. Do not write “accept the null.” Failing to reject can reflect a small effect, imprecise data, an insensitive design, violated assumptions, or some combination. A decision rule controls long-run error rates under its model; it does not certify either hypothesis in one study.</p>
</section>
</section>
<section id="match-the-method-to-the-design" class="level2">
<h2 class="anchored" data-anchor-id="match-the-method-to-the-design">Match the Method to the Design</h2>
<p>The same inferential grammar applies across several common structures, but the estimand and standard error change, as <a href="#tbl-method-by-design" class="quarto-xref">Table&nbsp;5</a> summarizes.</p>
<div id="tbl-method-by-design" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[34,14,16,36]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-method-by-design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Inferential method matched to outcome form and dependence structure.
</figcaption>
<div aria-describedby="tbl-method-by-design-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 14%">
<col style="width: 16%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Data structure</th>
<th>Estimand</th>
<th>Estimate</th>
<th>Main procedure/reference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>one quantitative sample</td>
<td><span class="math inline">\(\mu\)</span></td>
<td><span class="math inline">\(\bar X\)</span></td>
<td>one-sample <span class="math inline">\(t\)</span></td>
</tr>
<tr class="even">
<td>one binary sample</td>
<td><span class="math inline">\(p\)</span></td>
<td><span class="math inline">\(\widehat p\)</span></td>
<td>score/Wilson for interval</td>
</tr>
<tr class="odd">
<td>two independent quantitative groups</td>
<td><span class="math inline">\(\mu_1-\mu_2\)</span></td>
<td><span class="math inline">\(\bar X_1-\bar X_2\)</span></td>
<td>Welch <span class="math inline">\(t\)</span> by default</td>
</tr>
<tr class="even">
<td>two independent binary groups</td>
<td><span class="math inline">\(p_1-p_2\)</span></td>
<td><span class="math inline">\(\widehat p_1-\widehat p_2\)</span></td>
<td>large-sample Wald interval for the difference</td>
</tr>
<tr class="odd">
<td>paired quantitative measurements</td>
<td><span class="math inline">\(\mu_D\)</span></td>
<td><span class="math inline">\(\bar D\)</span></td>
<td>one-sample <span class="math inline">\(t\)</span> on pair differences</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="familiar-t-procedures-are-regression-special-cases" class="level3">
<h3 class="anchored" data-anchor-id="familiar-t-procedures-are-regression-special-cases">Familiar t procedures are regression special cases</h3>
<p>A one-sample mean procedure is an intercept-only model,</p>
<p><span class="math display">\[Y_i=\beta_0+\varepsilon_i,\]</span></p>
<p>where <span class="math inline">\(\beta_0\)</span> is the process mean. A paired procedure applies the same model to the within-student differences <span class="math inline">\(D_i\)</span>. For two independent groups, code <span class="math inline">\(G_i=0\)</span> for MS and <span class="math inline">\(G_i=1\)</span> for GP in</p>
<p><span class="math display">\[Y_i=\beta_0+\beta_1G_i+\varepsilon_i.\]</span></p>
<p>Then <span class="math inline">\(\beta_1=E(Y\mid G=GP)-E(Y\mid G=MS)\)</span>, so the coefficient estimate is the difference in group means. The conventional pooled-variance two-sample test is the equal-variance version of this model. Welch’s procedure keeps separate group variances and uses a different uncertainty calculation. The common grammar is the same—target, estimate, standard error, interval, and bounded claim—even when the standard-error procedure differs.</p>
</section>
<section id="two-independent-means-add-variances-not-standard-errors" class="level3">
<h3 class="anchored" data-anchor-id="two-independent-means-add-variances-not-standard-errors">Two independent means: add variances, not standard errors</h3>
<p>For independent group means,</p>
<p><span class="math display">\[
SE(\bar X_1-\bar X_2)
=\sqrt{SE(\bar X_1)^2+SE(\bar X_2)^2}
=\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}.
\]</span></p>
<p>The standard errors are not added directly. Variances add under independence, then the square root returns to outcome units.</p>
<p>Welch’s procedure uses that standard error and an approximate degrees of freedom calculation <span class="citation" data-cites="welch1947">(<a href="#ref-welch1947" role="doc-biblioref">Welch, 1947</a>)</span>. It does not require equal variances and is a sensible default for two independent means. A pooled-variance test should be used only when a common-variance model is substantively and empirically defensible, not merely because a preliminary variance test was nonsignificant.</p>
<p>Welch’s degrees of freedom are</p>
<p><span class="math display">\[
\nu=
\frac{(s_1^2/n_1+s_2^2/n_2)^2}
{(s_1^2/n_1)^2/(n_1-1)+(s_2^2/n_2)^2/(n_2-1)}.
\]</span></p>
<p>The value need not be an integer. Software should report it rather than silently replacing it with the pooled value <span class="math inline">\(n_1+n_2-2\)</span>.</p>
<p>The realized GP-minus-MS difference in mean final grade is exactly 0.64 points for these records, with nothing random left in it. The estimand that the Welch procedure addresses is <span class="math inline">\(\Delta_{\mathcal S}\)</span>, defined earlier for the two-school record-generating process. Its estimate is the same 0.64 points, the independently combined SE is 0.672, and Welch’s 95% interval is [-0.70, 1.99], with <span class="math inline">\(t(60.1)=
0.96\)</span> and exploratory <span class="math inline">\(p=.343\)</span>.</p>
<p>The interval and the test therefore say nothing further about the 395 observed students; they describe <span class="math inline">\(\Delta_{\mathcal S}\)</span> under the stated working model. Neither removes differences in who attended the two schools, and neither converts a modelled process contrast into a population or causal one.</p>
<p>The <a href="https://archive.ics.uci.edu/dataset/320/student+performance">official UCI documentation</a> defines final grade <code>G3</code> on the 0–20 scale and reports no missing values. The focal analysis therefore uses all 395 documented grades, including the 38 recorded zeros. The estimate is 0.642 points (95% interval [-0.702, 1.986], exploratory <span class="math inline">\(p=.343\)</span>).</p>
</section>
<section id="two-independent-proportions" class="level3">
<h3 class="anchored" data-anchor-id="two-independent-proportions">Two independent proportions</h3>
<p>The recorded pass proportions were 0.676 in GP and 0.630 in MS. Their difference was 0.046 when written as GP minus MS, with a large-sample Wald 95% interval for the difference from -0.102 to 0.194. The standard one-proportion procedure uses a Wilson/score interval, whereas the two-sample interval used here is a plain Wald construction. The earlier caution about Wald intervals therefore applies. The groups are independent only in the working student-level model; the data are not a probability sample and school is not randomized.</p>
</section>
<section id="paired-observations-become-one-sample-of-differences" class="level3">
<h3 class="anchored" data-anchor-id="paired-observations-become-one-sample-of-differences">Paired observations become one sample of differences</h3>
<p>Period-1 and period-2 grades belong to the same student. Treating the 790 grades as independent would discard the pairing and use the wrong standard error. Define</p>
<p><span class="math display">\[D_i=G_{2i}-G_{1i},\]</span></p>
<p>then analyze the <span class="math inline">\(n=395\)</span> differences with a one-sample procedure. Pairing can improve precision when within-pair measurements are positively correlated, but it does not by itself make a before-after contrast causal. Time, learning, testing, and other changes occur together.</p>
<p>The paired standard error is</p>
<p><span class="math display">\[
SE(\bar D)=\frac{s_D}{\sqrt{n_{pairs}}}.
\]</span></p>
<p>This formula retains the within-pair covariance because it works with the observed differences. If some students have only one measurement, they do not contribute a complete difference under a complete-pair analysis. The reason for missingness then becomes part of the design audit.</p>
</section>
<section id="freeze-the-analysis-sample-before-comparing-procedures" class="level3">
<h3 class="anchored" data-anchor-id="freeze-the-analysis-sample-before-comparing-procedures">Freeze the analysis sample before comparing procedures</h3>
<p>Confidence intervals, tests, and effect sizes should refer to the same students unless a change is explicitly justified. Comparing an estimate based on all 395 students with a sensitivity analysis based on a smaller set of complete cases can confuse an analysis-method difference with a sample-composition difference. Report the inclusion rule and <span class="math inline">\(n\)</span> for every estimand.</p>
<p>A useful pre-calculation checklist is:</p>
<ol type="1">
<li>identify the observational unit and any clusters or pairs;</li>
<li>define the outcome and group coding;</li>
<li>state the estimand and direction of subtraction;</li>
<li>fix the analysis sample and inspect missingness;</li>
<li>choose the standard error and reference model; and</li>
<li>decide whether the goal is estimation, testing, prediction, or a formal decision.</li>
</ol>
</section>
<section id="the-synthetic-program-contrast-reveals-a-design-trap" class="level3">
<h3 class="anchored" data-anchor-id="the-synthetic-program-contrast-reveals-a-design-trap">The synthetic program contrast reveals a design trap</h3>
<p>Among consenters, the completion counts in <a href="#tbl-program-completion" class="quarto-xref">Table&nbsp;6</a> were:</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-program-completion" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-program-completion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Post-program completion among consenting students in the synthetic study. Completion rates differ across assigned programs, so a complete-case contrast conditions on a post-assignment outcome.
</figcaption>
<div aria-describedby="tbl-program-completion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Program</th>
<th style="text-align: right;">Incomplete</th>
<th style="text-align: right;">Complete</th>
<th style="text-align: right;">Completion rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Practice</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">0.856</td>
</tr>
<tr class="even">
<td style="text-align: left;">Retrieval</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">0.773</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Standard</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">0.763</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-program-comparison" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Jittered final scores for Standard and Retrieval completers overlap substantially. The Retrieval mean is modestly higher, with uncertainty bars around each mean." data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-program-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_03_files/figure-html/fig-program-comparison-1.png" class="img-fluid figure-img" data-fig-pos="H" alt="Jittered final scores for Standard and Retrieval completers overlap substantially. The Retrieval mean is modestly higher, with uncertainty bars around each mean." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-program-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Final scores for observed completers in the Standard and Retrieval programs. Large points and error bars show group means and exploratory, model-based 95 percent mean intervals; selective completion limits a causal interpretation.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-program-comparison" class="quarto-xref">Figure&nbsp;4</a> plots the two completer groups with their mean intervals. This is an <strong>exploratory, model-conditioned complete-case association</strong>: it was selected for illustration after the synthetic data were created, treats observed students as independent, and does not adjust the uncertainty for the six school blocks. The Retrieval-minus-Standard mean difference among observed completers is 3.47 score points. Welch’s 95% interval is [0.58, 6.36], with <span class="math inline">\(p=.019\)</span>. A stratified student bootstrap gives a similar nominal percentile interval, conditional on independent resampling within the two observed completer groups, [0.69, 6.22], whose full shape appears in <a href="#fig-program-bootstrap" class="quarto-xref">Figure&nbsp;5</a>. Agreement between two uncertainty calculations does not repair post-assignment attrition or clustering by six schools.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-program-bootstrap" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A nearly symmetric bootstrap histogram is centered near 3.5 score points, with dashed interval endpoints near 0.7 and 6.2." data-fig-pos="H">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-program-bootstrap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_03_files/figure-html/fig-program-bootstrap-1.png" class="img-fluid figure-img" data-fig-pos="H" alt="A nearly symmetric bootstrap histogram is centered near 3.5 score points, with dashed interval endpoints near 0.7 and 6.2." width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-program-bootstrap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Stratified bootstrap distribution of the Retrieval-minus-Standard mean difference among observed completers. Dashed lines mark the percentile interval; the distribution quantifies case-resampling uncertainty, not attrition bias.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="errors-power-effect-size-and-practical-importance" class="level2">
<h2 class="anchored" data-anchor-id="errors-power-effect-size-and-practical-importance">Errors, Power, Effect Size, and Practical Importance</h2>
<p>When a decision rule is used, truth and the decision can combine in the four ways of <a href="#tbl-error-decisions" class="quarto-xref">Table&nbsp;7</a>.</p>
<div id="tbl-error-decisions" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[40,28,32]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-error-decisions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Decision outcomes under a specified null and alternative.
</figcaption>
<div aria-describedby="tbl-error-decisions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 28%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>State of the null model</th>
<th>Reject <span class="math inline">\(H_0\)</span></th>
<th>Fail to reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> is true</td>
<td>Type I error</td>
<td>correct decision</td>
</tr>
<tr class="even">
<td>a specified alternative is true</td>
<td>correct decision</td>
<td>Type II error</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The significance level <span class="math inline">\(\alpha\)</span> controls the Type I error probability under the null model and analysis plan. <strong>Power</strong> is the probability of rejecting <span class="math inline">\(H_0\)</span> under a specified alternative. Power is not a property of a study in the abstract; it depends on the effect, variance, sample size, design, missingness, test, sidedness, and decision rule.</p>
<p>For a planned two-sided two-sample <span class="math inline">\(t\)</span> test with 50 independent observations per group, a 3-point difference, and a 9-point standard deviation, the approximate power is only 0.38. A nonsignificant result from such a design could remain compatible with effects that matter.</p>
<section id="the-significance-filter-distorts-selected-estimates" class="level3">
<h3 class="anchored" data-anchor-id="the-significance-filter-distorts-selected-estimates">The significance filter distorts selected estimates</h3>
<p>The next simulation sets the true standardized effect to 0.20 and repeatedly collects only 25 independent observations. Across all studies, the estimates center near truth. If only <span class="math inline">\(p&lt;.05\)</span> studies are selected for attention, their magnitudes are exaggerated on average, as <a href="#tbl-significance-filter" class="quarto-xref">Table&nbsp;8</a> records.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-significance-filter" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-significance-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: The significance filter in 10,000 simulated studies with a true standardized difference of 0.20 and 25 observations each. Estimates are unbiased across all studies but exaggerated among the studies that reach <span class="math inline">\(p&lt;.05\)</span>.
</figcaption>
<div aria-describedby="tbl-significance-filter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">True standardized difference</td>
<td style="text-align: right;">0.200</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean estimate across all studies</td>
<td style="text-align: right;">0.197</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Proportion with p &lt; .05</td>
<td style="text-align: right;">0.166</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean estimate among selected studies</td>
<td style="text-align: right;">0.488</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wrong-sign share among selected studies</td>
<td style="text-align: right;">0.010</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This is a <strong>significance filter</strong>. Low power does not make every estimate too large. It makes published or highlighted estimates conditional on selection, which can produce magnitude errors (Type M) and sometimes sign errors (Type S). Replication and transparent reporting matter because selection changes what is seen.</p>
</section>
<section id="contrast-magnitude-needs-units-and-uncertainty" class="level3">
<h3 class="anchored" data-anchor-id="contrast-magnitude-needs-units-and-uncertainty">Contrast magnitude needs units and uncertainty</h3>
<p>Effect sizes are most useful when their definition, denominator, uncertainty, and substantive scale are reported explicitly <span class="citation" data-cites="lakens2013">(<a href="#ref-lakens2013" role="doc-biblioref">Lakens, 2013</a>)</span>.</p>
<p>For the synthetic program comparison, the raw descriptive contrast is 3.47 final-score points. It is directly interpretable on the score scale. Hedges’ <span class="math inline">\(g\)</span> standardizes the difference by a pooled within-group SD, following Cohen’s <span class="math inline">\(d\)</span> <span class="citation" data-cites="cohen1988">(<a href="#ref-cohen1988" role="doc-biblioref">Cohen, 1988</a>)</span>, and multiplies by a small-sample correction factor <span class="math inline">\(J\)</span>:</p>
<p><span class="math display">\[
g=J\frac{\bar X_1-\bar X_2}{s_p}.
\]</span></p>
<p>Here <span class="math inline">\(g=0.400\)</span>, with a nominal 95% percentile-bootstrap interval from 0.065 to 0.764, conditional on independent resampling within each observed program group. The interval represents that particular case-resampling scheme; it does not incorporate school clustering or repair post-assignment attrition. This standardization can help compare scales, but it is not a universal measure of importance. It depends on the outcome’s reliability, population variability, group composition, and estimator definition.</p>
<p>For paired grades, the standardized mean change <span class="math inline">\(d_z=\bar D/s_D=-0.10\)</span>. It uses the standard deviation of within-student differences and is not interchangeable with an independent groups <span class="math inline">\(g\)</span>. It is included only as a point-estimate technical illustration; no uncertainty interval for <span class="math inline">\(d_z\)</span> is claimed here. Always name the denominator.</p>
<p>Raw and standardized estimates answer different questions. The raw interval asks how many final-score points separate the group means. The <span class="math inline">\(g\)</span> interval asks how large that separation is relative to a pooled within-group SD in these observed completers. Reporting both can help, as <a href="#tbl-program-effect-sizes" class="quarto-xref">Table&nbsp;9</a> does, but the raw-scale result usually carries the substantive decision.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-program-effect-sizes" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-program-effect-sizes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: The Retrieval-minus-Standard program contrast on two scales among observed completers, each with a 95% interval from the method that matches it.
</figcaption>
<div aria-describedby="tbl-program-effect-sizes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Effect scale</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">95% lower</th>
<th style="text-align: right;">95% upper</th>
<th style="text-align: left;">Interval method</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Final-score points</td>
<td style="text-align: right;">3.467</td>
<td style="text-align: right;">0.576</td>
<td style="text-align: right;">6.357</td>
<td style="text-align: left;">Welch t</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hedges g</td>
<td style="text-align: right;">0.400</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">0.764</td>
<td style="text-align: left;">nominal percentile bootstrap</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="statistical-and-practical-significance-are-separate-judgments" class="level3">
<h3 class="anchored" data-anchor-id="statistical-and-practical-significance-are-separate-judgments">Statistical and practical significance are separate judgments</h3>
<p>A small p-value can accompany a negligible effect in a large sample. A wide interval can contain both negligible and important effects. Practical importance therefore needs a context-specific threshold, cost, consequence, or decision model. Labels such as “small,” “medium,” and “large” should not replace substantive reasoning.</p>
<p>One useful report asks three separate questions:</p>
<ol type="1">
<li><strong>Magnitude:</strong> what effects are estimated on a meaningful scale?</li>
<li><strong>Precision:</strong> which values remain compatible with the model and data?</li>
<li><strong>Importance:</strong> which compatible values would matter for the decision or theory?</li>
</ol>
</section>
<section id="prospective-precision-comes-before-data-collection" class="level3">
<h3 class="anchored" data-anchor-id="prospective-precision-comes-before-data-collection">Prospective precision comes before data collection</h3>
<p>If the goal is to estimate one mean with approximate 95% margin of error <span class="math inline">\(m\)</span>,</p>
<p><span class="math display">\[
n\approx\left(\frac{1.96\sigma}{m}\right)^2.
\]</span></p>
<p>With planning SD 9 and desired half-width 1, the normal approximation gives <span class="math inline">\(n=312\)</span> independent observations. For two equally sized independent groups and a margin of error 1 for their difference, the same planning assumptions give about 623 per group. The calculation is only as credible as its assumed SD, effect or precision target, retention, clustering, and analysis plan.</p>
<p>With average cluster size 25 and <span class="math inline">\(\rho=.05\)</span>, the simple design effect is 2.20. Attrition and unequal clusters require further adjustment. A sample-size number without its inputs is not a reproducible plan.</p>
<p>Precision planning should also allow for uncertainty in the planning inputs. If the SD might plausibly be 7, 9, or 12, calculate all three scenarios. If retention might be 70%-90%, show that range. A sensitivity table makes the cost of optimistic assumptions visible before recruitment begins.</p>
</section>
<section id="multiplicity-changes-the-evidence-landscape" class="level3">
<h3 class="anchored" data-anchor-id="multiplicity-changes-the-evidence-landscape">Multiplicity changes the evidence landscape</h3>
<p>Testing many outcomes, subgroups, transformations, exclusion rules, or model forms raises the chance of at least one attractive result. With <span class="math inline">\(m\)</span> independent null tests at level <span class="math inline">\(\alpha\)</span>, the familywise chance of at least one rejection is</p>
<p><span class="math display">\[1-(1-\alpha)^m.\]</span></p>
<p>For 20 independent tests at <span class="math inline">\(\alpha=.05\)</span>, this probability is about 0.64. Real analyses may have correlated tests, but the lesson remains: distinguish prespecified analyses from exploration, report the full analysis family, and use a multiplicity strategy appropriate to the claims.</p>
</section>
</section>
<section id="from-calculation-to-a-defensible-claim" class="level2">
<h2 class="anchored" data-anchor-id="from-calculation-to-a-defensible-claim">From Calculation to a Defensible Claim</h2>
<p>Inference should end with a claim whose strength matches the evidence production process. The public UCI dataset contains nonsensitive variables from two Portuguese schools and a derived pass indicator defined as final grade at least 10. Its official source is the <a href="https://archive.ics.uci.edu/dataset/320/student+performance">UCI Student Performance repository</a>, which documents the observational data and their provenance.</p>
<section id="technical-illustrations-that-stop-at-stat-c" class="level3">
<h3 class="anchored" data-anchor-id="technical-illustrations-that-stop-at-stat-c">Technical illustrations that stop at STAT-C</h3>
<p><a href="#tbl-performance-inference" class="quarto-xref">Table&nbsp;10</a> collects four statistical targets used to explain the inferential grammar. Each is a model-based quantity for the same process, estimated from one analytic sample of 395 students, and each carries the interval produced by the method its design requires. The estimates are also exact descriptions of the observed students; the intervals are not, because a fixed set of records has no sampling error of its own.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-performance-inference" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-performance-inference-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Four model-based statistical targets for one process, each with the 95% interval produced by the method matched to its design.
</figcaption>
<div aria-describedby="tbl-performance-inference-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 42%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Question</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">95% lower</th>
<th style="text-align: right;">95% upper</th>
<th style="text-align: left;">Scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean final grade</td>
<td style="text-align: right;">10.415</td>
<td style="text-align: right;">9.962</td>
<td style="text-align: right;">10.868</td>
<td style="text-align: left;">grade points</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pass proportion</td>
<td style="text-align: right;">0.671</td>
<td style="text-align: right;">0.623</td>
<td style="text-align: right;">0.715</td>
<td style="text-align: left;">proportion</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GP - MS mean grade</td>
<td style="text-align: right;">0.642</td>
<td style="text-align: right;">-0.702</td>
<td style="text-align: right;">1.986</td>
<td style="text-align: left;">grade points</td>
</tr>
<tr class="even">
<td style="text-align: left;">Period 2 - Period 1 mean grade</td>
<td style="text-align: right;">-0.195</td>
<td style="text-align: right;">-0.390</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: left;">grade points</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="a-calibrated-results-paragraph" class="level3">
<h3 class="anchored" data-anchor-id="a-calibrated-results-paragraph">A calibrated results paragraph</h3>
<blockquote class="blockquote">
<p>Among the 395 students recorded in these two schools, 67.1% achieved a final grade of at least 10 (Wilson 95% interval: 62.3% to 71.5%). Mean final grade was 10.42 points (model-based 95% <span class="math inline">\(t\)</span> interval: 9.96 to 10.87). The realized GP-minus-MS mean difference was exactly 0.64 points; the corresponding modelled two-school process contrast is estimated at the same value (Welch 95% interval: -0.70 to 1.99, exploratory <span class="math inline">\(p=.343\)</span>), so negative, zero, and positive values of that contrast remain compatible with this evidence. The Period-2-minus-Period-1 mean change was -0.19 points (paired 95% interval: -0.39 to 0.00). The estimates describe the observed cohorts exactly; every interval describes a modelled quantity for the process assumed to have generated those outcomes. The observational dataset does not support a probability-sampling claim about all students, a causal school effect, or a causal effect of time between grading periods.</p>
</blockquote>
<p>This paragraph reports estimates before test decisions, gives intervals in original units, avoids “accepting” a null, and separates modeled sampling uncertainty from design scope.</p>
</section>
<section id="calculation-follows-the-argument" class="level3">
<h3 class="anchored" data-anchor-id="calculation-follows-the-argument">Calculation follows the argument</h3>
<p>Software can reproduce each calculation, but it does not choose the estimand, establish independence, justify a one-sided alternative, or determine generalization. Those decisions belong to the argument and must be recorded before the procedure is run.</p>
</section>
</section>
<section id="argument-record-and-three-perspective-close" class="level2">
<h2 class="anchored" data-anchor-id="argument-record-and-three-perspective-close">Argument Record and Three-Perspective Close</h2>
<p>The sustained question ends with two linked arguments. Each component is kept short because the statistical details have already been established.</p>
<div id="tbl-ch03-argument-record" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[15,85]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch03-argument-record-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Argument record for the exploratory school comparison.
</figcaption>
<div aria-describedby="tbl-ch03-argument-record-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 85%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Code</th>
<th style="text-align: left;">Concise argument record</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>STAT-E</strong></td>
<td style="text-align: left;">Final grades and observed school membership for 349 GP and 46 MS students; all documented 0–20 grades are retained, including 38 recorded zeros.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>STAT-J</strong></td>
<td style="text-align: left;">Welch inference for <span class="math inline">\(\Delta_{\mathcal S}\)</span> assumes comparable repetitions of the same two-school process, independent students, finite group variances, stable grading and inclusion, and the documented outcome definition.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>STAT-I</strong></td>
<td style="text-align: left;">Exploratory GP-minus-MS estimate 0.642, SE 0.672, 95% interval [-0.702, 1.986], <span class="math inline">\(p=.343\)</span>.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>STAT-C</strong></td>
<td style="text-align: left;">For comparable repetitions of the same two-school process, the GP-minus-MS mean-grade contrast is estimated at 0.64 points (SE 0.672; 95% interval [-0.70, 1.99]; exploratory p = .343). The direction remains inconclusive under the working independence, stability, inclusion, and finite-variance conditions; neither wider population generalization nor causality is supported.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>SUB-E</strong></td>
<td style="text-align: left;">One end-of-year mathematics grade on a 0–20 scale for one recorded cohort at each of two Portuguese schools.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SUB-J</strong></td>
<td style="text-align: left;">School was attended, not assigned; no probability sample is documented; one course grade narrowly represents mathematics attainment.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>SUB-I</strong></td>
<td style="text-align: left;">GP’s observed mean is higher, but compatible process contrasts include both directions; no meaningful-difference threshold was prespecified.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SUB-C</strong></td>
<td style="text-align: left;">GP’s observed cohort mean exceeded MS’s by 0.64 points. Evidence about comparable repetitions is inconclusive, and the study does not support a causal school effect or generalization to other schools or populations.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The compact record in <a href="#tbl-ch03-argument-record" class="quarto-xref">Table&nbsp;11</a> keeps the statistical result and its substantive boundaries traceable in one place.</p>
<section id="argument-perspective-trace-the-four-role-specific-transitions" class="level3">
<h3 class="anchored" data-anchor-id="argument-perspective-trace-the-four-role-specific-transitions">Argument perspective: trace the four role-specific transitions</h3>
<div id="tbl-ch03-transitions" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[28,72]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch03-transitions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Statistical-to-substantive transition and traceability for the school comparison.
</figcaption>
<div aria-describedby="tbl-ch03-transitions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 72%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Shared role</th>
<th style="text-align: left;">Statistical-to-substantive transition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Evidence — situates</strong></td>
<td style="text-align: left;"><code>SUB-E</code> <strong>situates</strong> <code>STAT-E</code> by identifying the students, schools, course, scale, cohort, and setting represented by the evidence.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Justification — augments and evaluates</strong></td>
<td style="text-align: left;"><code>SUB-J</code> <strong>augments and evaluates</strong> <code>STAT-J</code> with what school membership and grades mean, while exposing what random sampling, assignment, and measurement do not support.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Inference — interprets</strong></td>
<td style="text-align: left;"><code>SUB-I</code> <strong>interprets</strong> the <code>STAT-I</code> estimate and interval in grade points and in the school context.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Claim — bounds and calibrates</strong></td>
<td style="text-align: left;"><code>STAT-C</code> <strong>bounds and calibrates</strong> <code>SUB-C</code> by limiting its direction, uncertainty, status, and scope.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-ch03-transitions" class="quarto-xref">Table&nbsp;12</a> makes the same-role transition explicit: contextual meaning is added without weakening the statistical reservation.</p>
</section>
<section id="workflow-perspective-reconstruct-an-exploratory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="workflow-perspective-reconstruct-an-exploratory-analysis">Workflow perspective: reconstruct an exploratory analysis</h3>
<div id="tbl-ch03-workflow" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[8,39,53]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch03-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13: The eight workflow stages applied without pretending the retrospective analysis was prespecified.
</figcaption>
<div aria-describedby="tbl-ch03-workflow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 39%">
<col style="width: 53%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Stage</th>
<th style="text-align: left;">Activity</th>
<th style="text-align: left;">Application to the school question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;"><strong>Conduct the literature review</strong></td>
<td style="text-align: left;">Understand grades, schools, and collection context.</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;"><strong>Frame the research question and candidate answer</strong></td>
<td style="text-align: left;">State the school question; note that no prospective hypothesis was specified.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;"><strong>Plan design, measurement, and method of inference</strong></td>
<td style="text-align: left;">Declare <span class="math inline">\(\Delta_{\mathcal S}\)</span>, retention of all documented grades, Welch inference, and its assumptions.</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;"><strong>Align and synthesize across questions: proposal phase</strong></td>
<td style="text-align: left;">Separate the substantive question from technical demonstrations.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;"><strong>Conduct the study and collect or acquire data and contextual information</strong></td>
<td style="text-align: left;">Acquire the observational evidence and context.</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;"><strong>Conduct statistical estimation, checking, and analysis</strong></td>
<td style="text-align: left;">Estimate the GP-minus-MS contrast and its model-conditioned uncertainty.</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: left;"><strong>Contextualize, justify, and interpret substantively</strong></td>
<td style="text-align: left;">Interpret grade points without treating school membership as assigned.</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: left;"><strong>Synthesize across questions: implementation phase</strong></td>
<td style="text-align: left;">Give the inconclusive exploratory answer; keep demonstrations subordinate.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The reconstruction in <a href="#tbl-ch03-workflow" class="quarto-xref">Table&nbsp;13</a> is operationally iterative even though the stages are numbered for traceability.</p>
</section>
<section id="evaluation-perspective-calibrate-the-answer" class="level3">
<h3 class="anchored" data-anchor-id="evaluation-perspective-calibrate-the-answer">Evaluation perspective: calibrate the answer</h3>
<div id="tbl-ch03-evaluation" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[28,72]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch03-evaluation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14: Seven evaluation lenses applied as a profile rather than a score.
</figcaption>
<div aria-describedby="tbl-ch03-evaluation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 72%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Lens</th>
<th style="text-align: left;">Focused evaluation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Question alignment</strong></td>
<td style="text-align: left;">The marginal school contrast answers the stated associational question, not a causal policy question.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Evidence integrity</strong></td>
<td style="text-align: left;">Group imbalance, only two schools, possible within-school dependence, and the documented inclusion rule remain consequential.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Justification adequacy</strong></td>
<td style="text-align: left;">Welch handles unequal variances but cannot supply sampling, assignment, measurement, or transport support.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Inferential adequacy</strong></td>
<td style="text-align: left;">The estimand, uncertainty, exploratory status, and approximation are explicit.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Transition fidelity</strong></td>
<td style="text-align: left;">Substantive interpretation retains the magnitude, interval, and design limitations.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Claim calibration</strong></td>
<td style="text-align: left;">The observed-cohort description is exact; the comparable-process direction is inconclusive; wider and causal claims are excluded.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Cross-question coherence</strong></td>
<td style="text-align: left;">One substantive question receives one answer; the other examples remain clearly labelled statistical illustrations.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-ch03-evaluation" class="quarto-xref">Table&nbsp;14</a> shows why an inconclusive, local, noncausal answer is a calibrated result rather than a failed analysis.</p>
<p>The superpopulation <span class="math inline">\(\mathcal S\)</span> extends the target from the observed cohort to comparable repetitions of the same two-school process under the declared stability conditions. It does not extend the answer to other schools, other populations, or a causal school comparison.</p>
</section>
</section>
<section id="reading-bridge" class="level2">
<h2 class="anchored" data-anchor-id="reading-bridge">Reading Bridge</h2>
<p>IMS is <em>Introduction to Modern Statistics</em> <span class="citation" data-cites="cetinkaya2024">(<a href="#ref-cetinkaya2024" role="doc-biblioref">Çetinkaya-Rundel &amp; Hardin, 2024</a>)</span>, the open OpenIntro textbook. Every linked resource below is publicly accessible.</p>
<ul>
<li><strong>Foundations:</strong> <a href="https://openintrostat.github.io/ims/foundations-randomization.html">randomization tests</a>, <a href="https://openintrostat.github.io/ims/foundations-bootstrapping.html">bootstrap intervals</a>, <a href="https://openintrostat.github.io/ims/foundations-mathematical.html">mathematical models</a>, and <a href="https://openintrostat.github.io/ims/foundations-errors.html">decision errors and power</a>.</li>
<li><strong>Common designs:</strong> <a href="https://openintrostat.github.io/ims/inference-one-prop.html">one proportion</a>, <a href="https://openintrostat.github.io/ims/inference-one-mean.html">one mean</a>, <a href="https://openintrostat.github.io/ims/inference-two-means.html">two independent means</a>, and <a href="https://openintrostat.github.io/ims/inference-paired-means.html">paired means</a>.</li>
<li><strong>Worked-data provenance:</strong> <a href="https://archive.ics.uci.edu/dataset/320/student+performance">UCI Student Performance</a> documents the source, variables, and access conditions for the school comparison.</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-cetinkaya2024" class="csl-entry" role="listitem">
Çetinkaya-Rundel, M., &amp; Hardin, J. (2024). <em>Introduction to modern statistics</em> (2nd ed.). OpenIntro. <a href="https://openintro.org/book/ims/">https://openintro.org/book/ims/</a>
</div>
<div id="ref-cohen1988" class="csl-entry" role="listitem">
Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em> (2nd ed.). Lawrence Erlbaum Associates.
</div>
<div id="ref-cortez2008data" class="csl-entry" role="listitem">
Cortez, P. (2008). <em>Student performance</em> [Dataset]. UCI Machine Learning Repository. <a href="https://doi.org/10.24432/C5TG7T">https://doi.org/10.24432/C5TG7T</a>
</div>
<div id="ref-efron1979" class="csl-entry" role="listitem">
Efron, B. (1979). Bootstrap methods: Another look at the jackknife. <em>The Annals of Statistics</em>, <em>7</em>(1), 1–26. <a href="https://doi.org/10.1214/aos/1176344552">https://doi.org/10.1214/aos/1176344552</a>
</div>
<div id="ref-efron1993" class="csl-entry" role="listitem">
Efron, B., &amp; Tibshirani, R. J. (1993). <em>An introduction to the bootstrap</em>. <span>Chapman and Hall/CRC</span>. <a href="https://doi.org/10.1201/9780429246593">https://doi.org/10.1201/9780429246593</a>
</div>
<div id="ref-lakens2013" class="csl-entry" role="listitem">
Lakens, D. (2013). Calculating and reporting effect sizes to facilitate cumulative science: A practical primer for t-tests and <span>ANOVAs</span>. <em>Frontiers in Psychology</em>, <em>4</em>, 863. <a href="https://doi.org/10.3389/fpsyg.2013.00863">https://doi.org/10.3389/fpsyg.2013.00863</a>
</div>
<div id="ref-moore2014" class="csl-entry" role="listitem">
Moore, D. S., McCabe, G. P., &amp; Craig, B. A. (2014). <em>Introduction to the practice of statistics</em> (8th ed.). W. H. Freeman.
</div>
<div id="ref-student1908" class="csl-entry" role="listitem">
Student. (1908). The probable error of a mean. <em>Biometrika</em>, <em>6</em>(1), 1–25. <a href="https://doi.org/10.2307/2331554">https://doi.org/10.2307/2331554</a>
</div>
<div id="ref-wasserstein2016" class="csl-entry" role="listitem">
Wasserstein, R. L., &amp; Lazar, N. A. (2016). The <span>ASA</span> statement on p-values: Context, process, and purpose. <em>The American Statistician</em>, <em>70</em>(2), 129–133. <a href="https://doi.org/10.1080/00031305.2016.1154108">https://doi.org/10.1080/00031305.2016.1154108</a>
</div>
<div id="ref-welch1947" class="csl-entry" role="listitem">
Welch, B. L. (1947). The generalization of <span>“<span>Student</span>’s”</span> problem when several different population variances are involved. <em>Biometrika</em>, <em>34</em>(1–2), 28–35. <a href="https://doi.org/10.1093/biomet/34.1-2.28">https://doi.org/10.1093/biomet/34.1-2.28</a>
</div>
<div id="ref-wilson1927" class="csl-entry" role="listitem">
Wilson, E. B. (1927). Probable inference, the law of succession, and statistical inference. <em>Journal of the American Statistical Association</em>, <em>22</em>(158), 209–212. <a href="https://doi.org/10.1080/01621459.1927.10502953">https://doi.org/10.1080/01621459.1927.10502953</a>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<section id="distinguish-the-inferential-objects" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="distinguish-the-inferential-objects">Distinguish the Inferential Objects</h3>
<p>A volunteer study reports mean weekly study time of 6.4 hours with SE 0.7. Name a plausible estimand, estimator, estimate, and standard error. Then state one population claim that the volunteer design does not support and explain why the small SE cannot repair it.</p>
</section>
<section id="interpret-an-interval-procedure" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="interpret-an-interval-procedure">Interpret an Interval Procedure</h3>
<p>A simulation produces 200 nominal 95% confidence intervals, of which 187 cover the true mean. Explain why this result is not by itself evidence of failure, predict how quadrupling the independent sample size should affect average width, and correct the statement, “There is a 95% chance that the true mean lies in this computed interval.”</p>
</section>
<section id="match-the-method-to-the-design-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="match-the-method-to-the-design-1">Match the Method to the Design</h3>
<p>For two independent groups, <span class="math inline">\(n_1=36\)</span>, <span class="math inline">\(\bar x_1=74\)</span>, <span class="math inline">\(s_1=12\)</span> and <span class="math inline">\(n_2=49\)</span>, <span class="math inline">\(\bar x_2=69\)</span>, <span class="math inline">\(s_2=10\)</span>. Estimate <span class="math inline">\(\mu_1-\mu_2\)</span>, calculate its standard error, and construct an approximate 95% interval using critical value 2.00. In one sentence, explain why an independent analysis would be wrong if the same values instead came from matched pairs.</p>
</section>
<section id="write-one-bounded-answer" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="write-one-bounded-answer">Write One Bounded Answer</h3>
<p>Use the reported GP–MS results based on all documented grades. Write one sentence each for <code>STAT-C</code> and <code>SUB-C</code>. Then identify the most consequential issue under <strong>Evidence integrity</strong>, <strong>Transition fidelity</strong>, and <strong>Claim calibration</strong>. Keep the answer to the stated school-comparison question; do not introduce a causal school-effect question.</p>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jinsong-chen\.github\.io\/QMSBR\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Jinsong Chen · Text licensed CC BY 4.0 unless otherwise noted.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../about/index.html#citation">
<p>Citation</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../about/index.html#licences">
<p>Licences</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="mailto:jinsong.chen@live.com">
<p>Contact</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>