<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jinsong Chen">

<title>Describing Data, Relationships, Probability, and Sampling – QMSBR</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-e9e44edca4b01ef481a44d1a821c0118.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Describing Data, Relationships, Probability, and Sampling – QMSBR">
<meta property="og:description" content="Modular chapters for rigorous quantitative reasoning in social and behavioral research.">
<meta property="og:image" content="https://jinsong-chen.github.io/QMSBR/chapters/chapter_02_files/figure-html/fig-final-grade-distribution-1.png">
<meta property="og:site_name" content="QMSBR">
<meta property="og:image:alt" content="Histogram of final mathematics grades from zero to twenty. The distribution is centered near eleven, contains a visible group at zero, and is bounded at both ends.">
<meta property="og:image:height" content="691">
<meta property="og:image:width" content="1344">
<meta name="twitter:title" content="Describing Data, Relationships, Probability, and Sampling – QMSBR">
<meta name="twitter:description" content="Modular chapters for rigorous quantitative reasoning in social and behavioral research.">
<meta name="twitter:image" content="https://jinsong-chen.github.io/QMSBR/chapters/chapter_02_files/figure-html/fig-final-grade-distribution-1.png">
<meta name="twitter:image:alt" content="Histogram of final mathematics grades from zero to twenty. The distribution is centered near eleven, contains a visible group at zero, and is bounded at both ends.">
<meta name="twitter:image-height" content="691">
<meta name="twitter:image-width" content="1344">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">QMSBR</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../library/index.html"> 
<span class="menu-text">Library</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../for-instructors.html"> 
<span class="menu-text">For instructors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about/index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../updates.html"> 
<span class="menu-text">Updates</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Describing Data, Relationships, Probability, and Sampling</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jinsong Chen </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#opening-problem" id="toc-opening-problem">Opening Problem</a></li>
  <li><a href="#understanding-the-evidence" id="toc-understanding-the-evidence">Understanding the Evidence</a>
  <ul>
  <li><a href="#cases-units-and-occasions-must-be-distinguished" id="toc-cases-units-and-occasions-must-be-distinguished">Cases, units, and occasions must be distinguished</a></li>
  <li><a href="#variable-form-and-substantive-role-are-separate" id="toc-variable-form-and-substantive-role-are-separate">Variable form and substantive role are separate</a></li>
  <li><a href="#coding-is-part-of-the-analysis" id="toc-coding-is-part-of-the-analysis">Coding is part of the analysis</a></li>
  <li><a href="#missingness-changes-the-evidence-behind-a-summary" id="toc-missingness-changes-the-evidence-behind-a-summary">Missingness changes the evidence behind a summary</a></li>
  <li><a href="#a-compact-evidence-audit-before-calculation" id="toc-a-compact-evidence-audit-before-calculation">A compact evidence audit before calculation</a></li>
  </ul></li>
  <li><a href="#describing-distributions-honestly" id="toc-describing-distributions-honestly">Describing Distributions Honestly</a>
  <ul>
  <li><a href="#a-distribution-is-an-organized-account-of-values" id="toc-a-distribution-is-an-organized-account-of-values">A distribution is an organized account of values</a></li>
  <li><a href="#center-answers-a-particular-question" id="toc-center-answers-a-particular-question">Center answers a particular question</a></li>
  <li><a href="#spread-is-not-an-optional-decoration" id="toc-spread-is-not-an-optional-decoration">Spread is not an optional decoration</a></li>
  <li><a href="#equal-means-can-hide-different-empirical-worlds" id="toc-equal-means-can-hide-different-empirical-worlds">Equal means can hide different empirical worlds</a></li>
  <li><a href="#honest-displays-preserve-the-comparison" id="toc-honest-displays-preserve-the-comparison">Honest displays preserve the comparison</a></li>
  </ul></li>
  <li><a href="#relationships-across-variable-types" id="toc-relationships-across-variable-types">Relationships Across Variable Types</a>
  <ul>
  <li><a href="#begin-with-the-pair-of-variable-forms" id="toc-begin-with-the-pair-of-variable-forms">Begin with the pair of variable forms</a></li>
  <li><a href="#quantitative---quantitative-form-before-coefficient" id="toc-quantitative---quantitative-form-before-coefficient">Quantitative - quantitative: form before coefficient</a></li>
  <li><a href="#zero-correlation-does-not-imply-independence" id="toc-zero-correlation-does-not-imply-independence">Zero correlation does not imply independence</a></li>
  <li><a href="#quantitative---categorical-retain-the-within-group-data" id="toc-quantitative---categorical-retain-the-within-group-data">Quantitative - categorical: retain the within-group data</a></li>
  <li><a href="#categorical---categorical-declare-the-denominator" id="toc-categorical---categorical-declare-the-denominator">Categorical - categorical: declare the denominator</a></li>
  </ul></li>
  <li><a href="#probability-as-a-model-of-uncertainty" id="toc-probability-as-a-model-of-uncertainty">Probability as a Model of Uncertainty</a>
  <ul>
  <li><a href="#probability-begins-with-a-repeatable-story" id="toc-probability-begins-with-a-repeatable-story">Probability begins with a repeatable story</a></li>
  <li><a href="#conditional-probability-changes-the-reference-set" id="toc-conditional-probability-changes-the-reference-set">Conditional probability changes the reference set</a></li>
  <li><a href="#independence-is-a-model-restriction" id="toc-independence-is-a-model-restriction">Independence is a model restriction</a></li>
  <li><a href="#probability-language-must-name-the-source" id="toc-probability-language-must-name-the-source">Probability language must name the source</a></li>
  </ul></li>
  <li><a href="#random-variables-and-generative-models" id="toc-random-variables-and-generative-models">Random Variables and Generative Models</a>
  <ul>
  <li><a href="#a-random-variable-connects-outcomes-to-numbers" id="toc-a-random-variable-connects-outcomes-to-numbers">A random variable connects outcomes to numbers</a></li>
  <li><a href="#the-binomial-model-is-a-four-part-story" id="toc-the-binomial-model-is-a-four-part-story">The binomial model is a four-part story</a></li>
  <li><a href="#the-normal-model-is-symmetric" id="toc-the-normal-model-is-symmetric">The Normal model is symmetric</a></li>
  <li><a href="#simulation-exposes-assumptions-it-does-not-validate-them" id="toc-simulation-exposes-assumptions-it-does-not-validate-them">Simulation exposes assumptions; it does not validate them</a></li>
  </ul></li>
  <li><a href="#sampling-repeated-samples-and-statistical-reasoning" id="toc-sampling-repeated-samples-and-statistical-reasoning">Sampling, Repeated Samples, and Statistical Reasoning</a>
  <ul>
  <li><a href="#population-sample-parameter-and-statistic" id="toc-population-sample-parameter-and-statistic">Population, sample, parameter, and statistic</a></li>
  <li><a href="#sampling-variability-is-not-a-data-error" id="toc-sampling-variability-is-not-a-data-error">Sampling variability is not a data error</a></li>
  <li><a href="#the-law-of-large-numbers-concerns-stabilization" id="toc-the-law-of-large-numbers-concerns-stabilization">The law of large numbers concerns stabilization</a></li>
  <li><a href="#the-central-limit-theorem-concerns-shape-after-standardization" id="toc-the-central-limit-theorem-concerns-shape-after-standardization">The central limit theorem concerns shape after standardization</a></li>
  <li><a href="#keep-three-distributions-separate" id="toc-keep-three-distributions-separate">Keep three distributions separate</a></li>
  <li><a href="#from-a-sample-description-to-a-bounded-claim" id="toc-from-a-sample-description-to-a-bounded-claim">From a sample description to a bounded claim</a></li>
  </ul></li>
  <li><a href="#argument-record-and-three-perspectives" id="toc-argument-record-and-three-perspectives">Argument Record and Three Perspectives</a>
  <ul>
  <li><a href="#argument-perspective" id="toc-argument-perspective">Argument perspective</a></li>
  <li><a href="#workflow-perspective" id="toc-workflow-perspective">Workflow perspective</a></li>
  <li><a href="#evaluation-perspective" id="toc-evaluation-perspective">Evaluation perspective</a></li>
  </ul></li>
  <li><a href="#reading-bridge" id="toc-reading-bridge">Reading Bridge</a></li>
  <li><a href="#references" id="toc-references">References</a></li>
  <li><a href="#exercises" id="toc-exercises">Exercises</a>
  <ul>
  <li><a href="#identify-the-evidence-structure" id="toc-identify-the-evidence-structure">Identify the evidence structure</a></li>
  <li><a href="#choose-a-defensible-description" id="toc-choose-a-defensible-description">Choose a defensible description</a></li>
  <li><a href="#separate-probability-from-repeated-sampling" id="toc-separate-probability-from-repeated-sampling">Separate probability from repeated sampling</a></li>
  <li><a href="#critique-a-graph-and-claim" id="toc-critique-a-graph-and-claim">Critique a graph and claim</a></li>
  <li><a href="#modify-a-relationship-analysis" id="toc-modify-a-relationship-analysis">Modify a relationship analysis</a></li>
  <li><a href="#modify-a-categorical-comparison" id="toc-modify-a-categorical-comparison">Modify a categorical comparison</a></li>
  <li><a href="#construct-an-open-argument-record" id="toc-construct-an-open-argument-record">Construct an open argument record</a></li>
  </ul></li>
  </ul>
</nav>
<div style="page-break-after: always;"></div>
<div class="callout callout-style-default callout-tip callout-titled" title="Chapter box">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Chapter box
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Research question:</strong> Among the 395 students recorded in two Portuguese secondary schools, what descriptive relationship is visible between absences and final mathematics grade?</p>
<p><strong>Analytic status:</strong> Exploratory; no prospective hypothesis is claimed.</p>
<p><strong>Evidence and inference:</strong> The observational records provide absence counts and final grades on the documented 0–20 scale, with no missing values in the source data <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>. All 395 records are retained. A scatterplot with a smooth curve, Pearson’s correlation, and Spearman’s rank correlation examine linear, monotone, and possible nonlinear features of the realized association.</p>
<p><strong>Bounded answer:</strong> Pearson’s <span class="math inline">\(r\)</span> and Spearman’s rank correlation are both near zero, so these records show little overall linear or monotone association. The scatterplot remains necessary because neither coefficient rules out nonlinear or subgroup patterns. The evidence does not support a causal effect or generalization beyond these students.</p>
</div>
</div>
<section id="opening-problem" class="level2">
<h2 class="anchored" data-anchor-id="opening-problem">Opening Problem</h2>
<p>A brief school report makes a confident claim:</p>
<blockquote class="blockquote">
<p>Recorded absences were almost uncorrelated with final mathematics grades, so attendance does not matter for achievement.</p>
</blockquote>
<p>The sentence sounds quantitative, but it compresses several different questions. What does one observation represent? How were absences and grades recorded? How were the students selected? Is the relationship linear, monotone, nonlinear, or different across subgroups? Most importantly, can a small observational correlation establish what would happen if attendance changed? Answering that last question needs a design that supports a causal contrast, not a longer list of summaries <span class="citation" data-cites="shadish2002">(<a href="#ref-shadish2002" role="doc-biblioref">Shadish et al., 2002</a>)</span>.</p>
<p>Chapter 1 showed that a quantitative question needs a traceable statistical argument and a substantive argument. Here that structure is applied to one exploratory relationship question. The statistical argument describes the observed association through complementary summaries; the substantive argument asks what that pattern can mean in the educational setting without exceeding the observational design.</p>
<p>The curated student-performance data contain 395 observations from two Portuguese secondary schools <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>. Absences range from 0 to 75, and final grade is documented on a bounded 0–20 scale with no missing values. The 38 recorded zeros fall within that documented scale and are retained without recoding because no alternative coding rule is documented. Pearson’s <span class="math inline">\(r\)</span> is 0.034 and Spearman’s rank correlation is 0.018. Their agreement near zero, together with the scatterplot and observational design, shows both what the records say and why the headline outruns its evidence.</p>
<p>This chapter develops the reasoning needed before formal inference. It begins with the analytic table, describes individual variables and relationships, uses probability models to state assumptions precisely, and then imagines repeated samples. The goal is not to calculate every available summary. It is to choose summaries that answer a declared question and to keep the resulting claim within the design and data.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Where this chapter sits in the workflow">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Where this chapter sits in the workflow
</div>
</div>
<div class="callout-body-container callout-body">
<p>The proposal decisions in <strong>Frame the research question and candidate answer</strong> and <strong>Plan design, measurement, and method of inference</strong> determine what must be observed and summarized. The worked analysis then emphasizes <strong>Conduct the study and collect or acquire data and contextual information</strong>, <strong>Conduct statistical estimation, checking, and analysis</strong>, and <strong>Contextualize, justify, and interpret substantively</strong>. The closing record supports <strong>Synthesize across questions: implementation phase</strong>. The most consequential evaluation lenses here are <strong>Evidence integrity</strong>, <strong>Inferential adequacy</strong>, <strong>Transition fidelity</strong>, and <strong>Claim calibration</strong>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="A mechanism to carry through the chapter">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>A mechanism to carry through the chapter
</div>
</div>
<div class="callout-body-container callout-body">
<p>A statistic from one sample cannot reveal by itself how stable it would be in another sample. Repeated sampling holds a target process and sampling rule fixed, draws new samples, and recalculates the statistic. The resulting sampling distribution exposes modeled variation. Its standard error can quantify that source of uncertainty, but it cannot repair weak measurement, selection, or causal design.</p>
</div>
</div>
</section>
<section id="understanding-the-evidence" class="level2">
<h2 class="anchored" data-anchor-id="understanding-the-evidence">Understanding the Evidence</h2>
<section id="cases-units-and-occasions-must-be-distinguished" class="level3">
<h3 class="anchored" data-anchor-id="cases-units-and-occasions-must-be-distinguished">Cases, units, and occasions must be distinguished</h3>
<p>An <strong>analytic table</strong> is a rectangular representation in which observations identify units or occasions and variables record their characteristics. Classical texts require both to be named before any calculation <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. The intended unit matters: a table can contain repeated records for one person, school-level values attached to students, or several waves for each participant. Before describing anything, identify what one observation means and whether the same unit appears more than once <span class="citation" data-cites="wickham2014">(<a href="#ref-wickham2014" role="doc-biblioref">Wickham, 2014</a>)</span>.</p>
<p>The first six observations from the public data source, shown in <a href="#tbl-student-preview" class="quarto-xref">Table&nbsp;1</a>, illustrate several forms of information.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-student-preview" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-student-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Selected variables from the first six records of the curated student-performance data.
</figcaption>
<div aria-describedby="tbl-student-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Student ID</th>
<th style="text-align: left;">Study-time category</th>
<th style="text-align: right;">Absences</th>
<th style="text-align: right;">Final grade</th>
<th style="text-align: left;">Pass</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">U001</td>
<td style="text-align: left;">2-5 hours</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">U002</td>
<td style="text-align: left;">2-5 hours</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">U003</td>
<td style="text-align: left;">2-5 hours</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">U004</td>
<td style="text-align: left;">5-10 hours</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">U005</td>
<td style="text-align: left;">2-5 hours</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">U006</td>
<td style="text-align: left;">2-5 hours</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Yes</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><code>student_id</code> labels a unit but is not an outcome to average. <code>study_time</code> uses ordered numeric codes to represent categories; subtracting code 1 from code 4 does not prove that the underlying study-time difference is three equal units. <code>absences</code> is a count. <code>final_grade</code> is a bounded quantitative score on its original 0-20 scale. <code>pass</code> is derived from the convention that a final grade of at least 10 counts as passing and therefore contains no new information about the score until a decision explicitly needs that threshold.</p>
</section>
<section id="variable-form-and-substantive-role-are-separate" class="level3">
<h3 class="anchored" data-anchor-id="variable-form-and-substantive-role-are-separate">Variable form and substantive role are separate</h3>
<p>A variable has a <strong>recorded form</strong> and a <strong>role in a particular question</strong>. Classical treatments separate <em>categorical</em> variables, which place a case into a group, from <em>quantitative</em> variables, which take numerical values for which arithmetic is meaningful <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>; social-science texts refine the categorical side into nominal and ordered categories <span class="citation" data-cites="agresti2018">(<a href="#ref-agresti2018" role="doc-biblioref">Agresti, 2018</a>)</span>. The same variable can be an outcome in one analysis, a predictor in another, or a description of the sample in a third. Its role does not by itself establish causal status, and <a href="#tbl-variable-form-role" class="quarto-xref">Table&nbsp;2</a> keeps the three labels apart.</p>
<div id="tbl-variable-form-role" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[20,24,56]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variable-form-role-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Recorded form, analysis role, and causal interpretation are different features of a variable.
</figcaption>
<div aria-describedby="tbl-variable-form-role-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Audit feature</th>
<th style="text-align: left;">Examples</th>
<th style="text-align: left;">Why it matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Identifier</td>
<td style="text-align: left;">student ID</td>
<td style="text-align: left;">Checks uniqueness; usually not analyzed as a quantity</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quantitative</td>
<td style="text-align: left;">final grade, absences</td>
<td style="text-align: left;">Units and scale determine meaningful differences</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nominal categorical</td>
<td style="text-align: left;">school, support status</td>
<td style="text-align: left;">Categories need labels and an explicit reference or denominator</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ordered categorical</td>
<td style="text-align: left;">study-time category</td>
<td style="text-align: left;">Order is meaningful; equal spacing may not be</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Derived variable</td>
<td style="text-align: left;">pass from final grade</td>
<td style="text-align: left;">The rule should be documented and sensitivity to the threshold considered</td>
</tr>
<tr class="even">
<td style="text-align: left;">Question-specific role</td>
<td style="text-align: left;">outcome, predictor, grouping variable</td>
<td style="text-align: left;">A statistical role is not a design-based causal label</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Rigid scale labels can distract from the real decisions. Ask instead what values mean, which comparisons are defensible, whether distances are meaningful, and how the variable was produced. Treating an ordered code as continuous may sometimes be a useful approximation, but it must be argued, not inferred from the storage format.</p>
</section>
<section id="coding-is-part-of-the-analysis" class="level3">
<h3 class="anchored" data-anchor-id="coding-is-part-of-the-analysis">Coding is part of the analysis</h3>
<p>Values such as <code>0</code>, <code>9</code>, <code>99</code>, and a blank cell can mean a real zero, a category, refusal, not applicable, or missing. A data dictionary should state:</p>
<ul>
<li>the observational unit and time point;</li>
<li>the variable label, storage type, and units;</li>
<li>allowable values and category meanings;</li>
<li>how missing values are encoded;</li>
<li>whether the variable was recorded directly or derived;</li>
<li>any range, skip-pattern, or consistency rule.</li>
</ul>
<p>An impossible age, duplicated identifier, or final score recorded for a student who never completed follow-up is not an “outlier problem.” It is a data-quality question requiring a traceable resolution, because a reported result is only as reconstructible as the record of the decisions that produced it <span class="citation" data-cites="nationalAcademies2019">(<a href="#ref-nationalAcademies2019" role="doc-biblioref">National Academies of Sciences, Engineering, and Medicine, 2019</a>)</span>. An unusual but valid case should not be deleted simply because it changes a summary.</p>
</section>
<section id="missingness-changes-the-evidence-behind-a-summary" class="level3">
<h3 class="anchored" data-anchor-id="missingness-changes-the-evidence-behind-a-summary">Missingness changes the evidence behind a summary</h3>
<p>The synthetic foundations study deliberately contains several stages. All 360 fictional students were invited. Consent was more likely for students with higher baseline scores. Only consenting students were randomly assigned to a program, and not every participant completed follow-up.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-foundations-funnel" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-foundations-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: The denominator narrows across stages of the synthetic foundations study.
</figcaption>
<div aria-describedby="tbl-foundations-funnel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Stage</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Invited</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">100.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Consented</td>
<td style="text-align: right;">271</td>
<td style="text-align: right;">75.3%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Completed follow-up</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">60.0%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Final score recorded</td>
<td style="text-align: right;">216</td>
<td style="text-align: right;">60.0%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-foundations-funnel" class="quarto-xref">Table&nbsp;3</a> records how the denominator narrows. A mean baseline score can use all invited cases because baseline is complete. A mean final score uses only 216 completers. That smaller denominator is not merely a software detail: follow-up completion depends partly on attendance and program in the known generating process. Consequently, the complete-case distribution describes a selected subset. It does not automatically redefine the intended target population: any move from that subset to the original target requires a missingness assumption and an appropriate method.</p>
<p>The symbol <code>NA</code> means “not available to this analysis,” not zero. It also does not reveal <em>why</em> the value is unavailable. Reporting standards therefore ask for the flow of cases from invitation to analysis, together with the amount and handling of missing data <span class="citation" data-cites="appelbaum2018">(<a href="#ref-appelbaum2018" role="doc-biblioref">Appelbaum et al., 2018</a>)</span>. A defensible report names the denominator and the rule that produced it:</p>
<blockquote class="blockquote">
<p>Among the 216 fictional students with recorded follow-up scores, the mean final score was 74.60 points.</p>
</blockquote>
<p>This is better than “the mean score was …” because it makes the analytic population visible.</p>
</section>
<section id="a-compact-evidence-audit-before-calculation" class="level3">
<h3 class="anchored" data-anchor-id="a-compact-evidence-audit-before-calculation">A compact evidence audit before calculation</h3>
<p>The six checks below are a local working device within <strong>Evidence integrity</strong>. They help establish STAT-E and STAT-J; they do not create a new framework or replace the seven evaluation lenses.</p>
<ol type="1">
<li>State the observational unit and check whether identifiers are unique.</li>
<li>Match every variable to a definition, unit, allowable range, and missing code.</li>
<li>Count cases at the invitation, response, eligibility, and analysis stages.</li>
<li>Check impossible combinations and derived-variable rules.</li>
<li>Declare the denominator for every planned percentage, graph, or summary.</li>
<li>Reconnect the resulting analytic sample to the design and intended claim.</li>
</ol>
<p>Software can automate counts, but it cannot decide which unit, code, or denominator answers the research question.</p>
</section>
</section>
<section id="describing-distributions-honestly" class="level2">
<h2 class="anchored" data-anchor-id="describing-distributions-honestly">Describing Distributions Honestly</h2>
<section id="a-distribution-is-an-organized-account-of-values" class="level3">
<h3 class="anchored" data-anchor-id="a-distribution-is-an-organized-account-of-values">A distribution is an organized account of values</h3>
<p>The <strong>sample distribution</strong> of a variable records which values occurred and how frequently. The classical strategy is to plot the data first, describe the overall pattern by shape, center, and spread, and only then note striking deviations such as outliers <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. This chapter states that strategy as five linked features:</p>
<ul>
<li><strong>shape:</strong> symmetric or skewed, unimodal or multimodal, continuous-looking or heaped;</li>
<li><strong>center:</strong> where typical values lie;</li>
<li><strong>spread:</strong> how far cases differ;</li>
<li><strong>unusual observations:</strong> values separated from most of the sample;</li>
<li><strong>substantive scale:</strong> units, bounds, and meaningful reference points.</li>
</ul>
<p>The final mathematics grades are bounded at 0 and 20 and recorded as whole numbers. A histogram should preserve those facts, as <a href="#fig-final-grade-distribution" class="quarto-xref">Figure&nbsp;1</a> does.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-final-grade-distribution" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Histogram of final mathematics grades from zero to twenty. The distribution is centered near eleven, contains a visible group at zero, and is bounded at both ends.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-final-grade-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-final-grade-distribution-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" alt="Histogram of final mathematics grades from zero to twenty. The distribution is centered near eleven, contains a visible group at zero, and is bounded at both ends.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-final-grade-distribution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of final mathematics grades in the curated two-school student data.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The sample mean is 10.42, the median is 11, and the standard deviation (SD), a measure of spread expressed in the original grade points, is 4.58. Those numbers summarize the recorded cases; they do not imply that a Normal model generated the grades.</p>
</section>
<section id="center-answers-a-particular-question" class="level3">
<h3 class="anchored" data-anchor-id="center-answers-a-particular-question">Center answers a particular question</h3>
<p>For observations <span class="math inline">\(x_1,\ldots,x_n\)</span>, the sample mean is</p>
<p><span class="math display">\[
\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_i.
\]</span></p>
<p>It is the balance point of the observed values and uses every numerical distance. The <strong>median</strong> <span class="math inline">\(M\)</span> is a positional summary: order the observations and take the value in position <span class="math inline">\((n+1)/2\)</span>, averaging the two central values when <span class="math inline">\(n\)</span> is even, so that half the ordered observations are at or below <span class="math inline">\(M\)</span> and half are at or above it <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. The <strong>mode</strong> is the most frequent recorded value or category.</p>
<p>These summaries answer different questions. The mean is useful when additive differences and totals matter. The median describes a middle position and is <em>resistant</em> in the classical sense: a single extreme value can move the mean arbitrarily far but changes the median very little <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. The mode can be meaningful for a categorical variable. None is universally “best,” and reporting only one can hide the shape of the data.</p>
</section>
<section id="spread-is-not-an-optional-decoration" class="level3">
<h3 class="anchored" data-anchor-id="spread-is-not-an-optional-decoration">Spread is not an optional decoration</h3>
<p>The range uses only the minimum and maximum. Quantiles use positions in the ordered sample: the quartiles <span class="math inline">\(Q_{0.25}\)</span> and <span class="math inline">\(Q_{0.75}\)</span> bracket the middle half of the ordered data, and the classical rule takes each as the median of one half of the observations <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Software interpolates between order statistics, so reported quartiles can differ slightly from the hand rule; the values here use R’s default type-7 interpolation <span class="citation" data-cites="rcore2025">(<a href="#ref-rcore2025" role="doc-biblioref">R Core Team, 2025</a>)</span>. The interquartile range (IQR), the width of that middle half, is</p>
<p><span class="math display">\[
IQR=Q_{0.75}-Q_{0.25}.
\]</span></p>
<p>The sample variance and sample standard deviation are</p>
<p><span class="math display">\[
s^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar{x})^2,
\qquad
s=\sqrt{s^2}.
\]</span></p>
<div class="cell" data-layout-align="center" data-tbl-pos="H">
<div id="tbl-student-distributions" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-student-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Center, spread, and range for two variables in the student-performance data.
</figcaption>
<div aria-describedby="tbl-student-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">IQR</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">Maximum</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Final grade</td>
<td style="text-align: right;">395</td>
<td style="text-align: right;">10.42</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">4.58</td>
<td style="text-align: right;">6.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">20.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Absences</td>
<td style="text-align: right;">395</td>
<td style="text-align: right;">5.71</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">75.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The SD returns to the original measurement units; the variance is in squared units. The denominator <span class="math inline">\(n-1\)</span> is the <em>degrees of freedom</em> of <span class="math inline">\(s^2\)</span>: the <span class="math inline">\(n\)</span> deviations from <span class="math inline">\(\bar{x}\)</span> must sum to zero, so only <span class="math inline">\(n-1\)</span> of them can vary freely. Under independent and identically distributed sampling from one population with finite variance <span class="math inline">\(\sigma^2\)</span>, the corresponding expectation calculation gives <span class="math inline">\(E(s^2)=\sigma^2\)</span> <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. The zero-sum identity explains the lost degree of freedom; it is not, by itself, a proof of unbiasedness.</p>
<p>This correction is <strong>not</strong> the finite-population correction. Define the finite-population variance as</p>
<p><span class="math display">\[
S_N^2=\frac{1}{N-1}\sum_{i=1}^{N}(y_i-\bar y_N)^2.
\]</span></p>
<p>Under simple random sampling without replacement of <span class="math inline">\(n\)</span> units from those <span class="math inline">\(N\)</span> units,</p>
<p><span class="math display">\[
SE(\bar Y)=\sqrt{\left(1-\frac{n}{N}\right)\frac{S_N^2}{n}}.
\]</span></p>
<p>The factor <span class="math inline">\(\sqrt{1-n/N}\)</span> reduces the usual <span class="math inline">\(S_N/\sqrt n\)</span> expression when the sampling fraction is not negligible <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. The two corrections solve different problems.</p>
<p>Absences show why several summaries matter (<a href="#tbl-student-distributions" class="quarto-xref">Table&nbsp;4</a>). The median is 4, the mean is 5.71, and the maximum is 75. A large right tail pulls the mean upward. The maximum should be checked against the source definition, but it should not be erased merely for being influential.</p>
</section>
<section id="equal-means-can-hide-different-empirical-worlds" class="level3">
<h3 class="anchored" data-anchor-id="equal-means-can-hide-different-empirical-worlds">Equal means can hide different empirical worlds</h3>
<p>The three small distributions in <a href="#fig-same-mean-different-shape" class="quarto-xref">Figure&nbsp;2</a> all have mean 10. They do not have the same median, SD, shape, or practical interpretation.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-same-mean-different-shape" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Faceted dot plots show a concentrated distribution near ten, an evenly spread distribution from two to eighteen, and a right-skewed distribution with a value at twenty-one.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-same-mean-different-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-same-mean-different-shape-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" alt="Faceted dot plots show a concentrated distribution near ten, an evenly spread distribution from two to eighteen, and a right-skewed distribution with a value at twenty-one.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-same-mean-different-shape-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Three constructed distributions share a mean of 10 but differ in shape and spread.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A mean without a graph and spread can make these distributions look interchangeable. A graph without units, denominator, or transparent axes can mislead in a different way.</p>
</section>
<section id="honest-displays-preserve-the-comparison" class="level3">
<h3 class="anchored" data-anchor-id="honest-displays-preserve-the-comparison">Honest displays preserve the comparison</h3>
<p>Match the graph to the variable and question, as <a href="#tbl-graph-choice" class="quarto-xref">Table&nbsp;5</a> sets out.</p>
<div id="tbl-graph-choice" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[28,34,38]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-graph-choice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: A graph is chosen from the research question and recorded variable types.
</figcaption>
<div aria-describedby="tbl-graph-choice-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 34%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Question</th>
<th style="text-align: left;">Useful display</th>
<th style="text-align: left;">Required checks</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Distribution of one quantitative variable</td>
<td style="text-align: left;">dotplot, histogram, density plot, boxplot</td>
<td style="text-align: left;">bin width, bounds, heaping, all cases, units</td>
</tr>
<tr class="even">
<td style="text-align: left;">Distribution of one categorical variable</td>
<td style="text-align: left;">count or percentage bar chart</td>
<td style="text-align: left;">denominator, missing category, zero baseline</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Two quantitative variables</td>
<td style="text-align: left;">scatterplot</td>
<td style="text-align: left;">range, overlap, nonlinear form, overplotting, unusual cases</td>
</tr>
<tr class="even">
<td style="text-align: left;">Quantitative outcome across categories</td>
<td style="text-align: left;">jittered points, boxplots, violin/density plus summaries</td>
<td style="text-align: left;">group sizes, same scale, within-group distributions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Two categorical variables</td>
<td style="text-align: left;">counts plus conditional-percentage bars</td>
<td style="text-align: left;">event, reference group, conditioning denominator</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Histogram shape depends partly on bin width. Boxplots compactly show a median, quartiles, and flagged points, but they can conceal multimodality and sample size. In the classical modified boxplot the whiskers stop at the most extreme observations lying within <span class="math inline">\(1.5\times IQR\)</span> of the quartiles, and points beyond that distance are drawn individually as suspected outliers <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Bar charts for counts or percentages ordinarily begin at zero because bar length encodes magnitude <span class="citation" data-cites="cetinkaya2024">(<a href="#ref-cetinkaya2024" role="doc-biblioref">Çetinkaya-Rundel &amp; Hardin, 2024</a>)</span>. Truncated axes may sometimes reveal small differences in point-and-interval plots, but the scale break must be explicit and the substantive size must remain visible.</p>
<p>An <strong>outlier flag</strong> is a request for investigation, not an instruction to delete: the classical advice is to look for observations outside the overall pattern and try to explain them <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Verify the record, compare analyses transparently when justified, and explain how the case affects the result.</p>
</section>
</section>
<section id="relationships-across-variable-types" class="level2">
<h2 class="anchored" data-anchor-id="relationships-across-variable-types">Relationships Across Variable Types</h2>
<section id="begin-with-the-pair-of-variable-forms" class="level3">
<h3 class="anchored" data-anchor-id="begin-with-the-pair-of-variable-forms">Begin with the pair of variable forms</h3>
<p>A relationship is always a relationship between specified variables in a specified sample. The useful first display depends on their forms:</p>
<p><span class="math display">\[
\begin{array}{c|c}
\text{Variable pair} &amp; \text{Starting description} \\
\hline
\text{quantitative - quantitative} &amp; \text{scatterplot and conditional pattern} \\
\text{quantitative - categorical} &amp; \text{within-group distributions and contrasts} \\
\text{categorical - categorical} &amp; \text{two-way counts and conditional percentages}
\end{array}
\]</span></p>
<p>The order of analysis is stable: state the question and units, show the data, summarize a pattern, inspect unusual cases and support, then bound the claim.</p>
</section>
<section id="quantitative---quantitative-form-before-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="quantitative---quantitative-form-before-coefficient">Quantitative - quantitative: form before coefficient</h3>
<p>A scatterplot should be read for direction, form, strength, unusual cases, and the range of observed support; that reading order is the classical one for a pair of quantitative variables <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. <a href="#fig-absence-grade" class="quarto-xref">Figure&nbsp;3</a> uses horizontal and vertical jitter because both variables are discrete.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-absence-grade" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="A jittered scatterplot of absences against final grade shows most students below twenty absences, a few much larger counts, and little overall linear pattern.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-absence-grade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-absence-grade-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" alt="A jittered scatterplot of absences against final grade shows most students below twenty absences, a few much larger counts, and little overall linear pattern.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-absence-grade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Recorded absences and final mathematics grade in the observational student sample.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The Pearson sample correlation is</p>
<p><span class="math display">\[
r=\frac{\sum_i(x_i-\bar{x})(y_i-\bar{y})}
{\sqrt{\sum_i(x_i-\bar{x})^2}\sqrt{\sum_i(y_i-\bar{y})^2}},
\qquad -1\le r\le 1.
\]</span></p>
<p>Equivalently, <span class="math inline">\(r\)</span> is the average product of standardized values,</p>
<p><span class="math display">\[
r=\frac{1}{n-1}\sum_{i=1}^{n}
\left(\frac{x_i-\bar{x}}{s_x}\right)
\left(\frac{y_i-\bar{y}}{s_y}\right),
\]</span></p>
<p>which is the form used in classical presentations and shows directly why the coefficient has no units <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Both variables must be quantitative. It summarizes the direction and strength of a <strong>linear</strong> sample association and is unchanged by swapping <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> or by changing the units of either variable. In this sample, <span class="math inline">\(r=0.034\)</span>. That value does not mean absences are unrelated in every sense, does not show that the population correlation is zero, and does not estimate the causal consequence of preventing an absence.</p>
<p>Like the mean and the SD, <span class="math inline">\(r\)</span> is not resistant: it can be distorted by a few unusual points, restricted ranges, mixtures of groups, and nonlinear patterns <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Always read it with the scatterplot and the sampling/design story.</p>
<p>The source documentation defines final grade on the 0–20 scale and reports no missing values <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>. The 38 grades recorded as zero are therefore retained under the documented coding rather than recoded or excluded; the documentation does not independently establish what produced each zero. With all 395 students included, Pearson’s correlation is 0.034 and Spearman’s rank correlation is 0.018. Pearson’s coefficient targets linear association; Spearman’s coefficient targets monotone association through the ranks and is less driven by numerical spacing and unusually large absence counts. Both are near zero. Their agreement supports a narrow claim of little overall linear or monotone association in these records, while the scatterplot and smooth curve remain necessary for detecting nonlinear form, clusters, or sparsely supported parts of the absence range.</p>
</section>
<section id="zero-correlation-does-not-imply-independence" class="level3">
<h3 class="anchored" data-anchor-id="zero-correlation-does-not-imply-independence">Zero correlation does not imply independence</h3>
<p>Let <span class="math inline">\(X\)</span> be generated symmetrically between -2 and 2 and set <span class="math inline">\(Y=X^2\)</span>. Knowing <span class="math inline">\(X\)</span> determines <span class="math inline">\(Y\)</span>, so the variables are deterministically dependent. Yet the positive-<span class="math inline">\(X\)</span> and negative-<span class="math inline">\(X\)</span> linear components cancel, producing the near-zero correlation reported in <a href="#fig-zero-correlation-dependence" class="quarto-xref">Figure&nbsp;4</a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-zero-correlation-dependence" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="Points follow an exact U-shaped curve Y equals X squared, while the displayed sample Pearson correlation is near zero.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-zero-correlation-dependence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-zero-correlation-dependence-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" alt="Points follow an exact U-shaped curve Y equals X squared, while the displayed sample Pearson correlation is near zero.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-zero-correlation-dependence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: A strong nonlinear relationship can have nearly zero Pearson correlation.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Under suitable finite-moment conditions, independence implies zero covariance and hence zero Pearson correlation <span class="citation" data-cites="cramer1946">(<a href="#ref-cramer1946" role="doc-biblioref">Cramér, 1946</a>)</span>. The converse is generally false. Correlation is therefore not a general test of independence.</p>
</section>
<section id="quantitative---categorical-retain-the-within-group-data" class="level3">
<h3 class="anchored" data-anchor-id="quantitative---categorical-retain-the-within-group-data">Quantitative - categorical: retain the within-group data</h3>
<p>The study-time variable consists of four ordered categories. Compare the entire grade distributions and group sizes before comparing only means; the classical display for a quantitative variable across groups is a set of side-by-side distributions rather than a table of means alone <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>.</p>
<div class="cell" data-layout-align="center" data-tbl-pos="H">
<div id="tbl-study-time-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-study-time-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Final-grade summaries by reported weekly study-time category.
</figcaption>
<div aria-describedby="tbl-study-time-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Study-time category</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Median</th>
<th style="text-align: right;">IQR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">&lt;2 hours</td>
<td style="text-align: right;">105</td>
<td style="text-align: right;">10.05</td>
<td style="text-align: right;">4.96</td>
<td style="text-align: right;">10.00</td>
<td style="text-align: right;">5.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">2-5 hours</td>
<td style="text-align: right;">198</td>
<td style="text-align: right;">10.17</td>
<td style="text-align: right;">4.22</td>
<td style="text-align: right;">11.00</td>
<td style="text-align: right;">5.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5-10 hours</td>
<td style="text-align: right;">65</td>
<td style="text-align: right;">11.40</td>
<td style="text-align: right;">4.64</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">5.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">&gt;10 hours</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">11.26</td>
<td style="text-align: right;">5.28</td>
<td style="text-align: right;">12.00</td>
<td style="text-align: right;">5.50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-grade-by-study-time" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" alt="Boxplots and lightly jittered student grades show overlapping distributions and unequal group sizes across four study-time categories." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-grade-by-study-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-grade-by-study-time-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" data-fig-pos="H" alt="Boxplots and lightly jittered student grades show overlapping distributions and unequal group sizes across four study-time categories.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-grade-by-study-time-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Final-grade distributions across four reported study-time categories.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The distributions in <a href="#fig-grade-by-study-time" class="quarto-xref">Figure&nbsp;5</a> overlap substantially, and <a href="#tbl-study-time-summary" class="quarto-xref">Table&nbsp;6</a> shows why the overlap matters: the largest sample mean occurs in the 5-10 hour category, not the highest category, and only 27 students report more than 10 hours. A bounded description is:</p>
<blockquote class="blockquote">
<p>In these two schools, recorded final grades tended to be somewhat higher in the two upper study-time categories, but distributions overlapped and the observational data do not identify what would happen if study time were changed.</p>
</blockquote>
</section>
<section id="categorical---categorical-declare-the-denominator" class="level3">
<h3 class="anchored" data-anchor-id="categorical---categorical-declare-the-denominator">Categorical - categorical: declare the denominator</h3>
<p>The same count table can support percentages conditioned on support, percentages conditioned on passing, or overall percentages. They answer different questions. These are <em>conditional distributions</em>, and the classical instruction is to choose the conditioning variable from the question before reading any percentage <span class="citation" data-cites="moore2014 agresti2018">(<a href="#ref-agresti2018" role="doc-biblioref">Agresti, 2018</a>; <a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. For school support and pass status:</p>
<div class="cell" data-layout-align="center">
<div id="tbl-support-pass" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-support-pass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Counts and within-support percentages for recorded school support and final-grade pass status.
</figcaption>
<div aria-describedby="tbl-support-pass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 26%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">School support</th>
<th style="text-align: right;">No: count</th>
<th style="text-align: right;">Yes: count</th>
<th style="text-align: right;">No: within-support %</th>
<th style="text-align: right;">Yes: within-support %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">no</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">237</td>
<td style="text-align: right;">31.1%</td>
<td style="text-align: right;">68.9%</td>
</tr>
<tr class="even">
<td style="text-align: left;">yes</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">45.1%</td>
<td style="text-align: right;">54.9%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Among the 51 students recorded as receiving school support, 28 (54.9%) passed; among the 344 students without recorded support, 237 (68.9%) passed (<a href="#tbl-support-pass" class="quarto-xref">Table&nbsp;7</a>). This local demonstration ends with a descriptive comparison. STAT-E records who was marked as supported and who passed; STAT-I reports two conditional proportions differing by 14.0 percentage points among these students. A bounded STAT-C retains the absence of a sampling model or assignment mechanism.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-support-pass" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="A one-hundred-percent stacked bar chart shows a lower observed pass percentage among students recorded as receiving school support, with different group sizes noted in the text.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-support-pass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-support-pass-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" alt="A one-hundred-percent stacked bar chart shows a lower observed pass percentage among students recorded as receiving school support, with different group sizes noted in the text.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-support-pass-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Pass-status percentages within each recorded school-support group.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The observed direction does not reveal whether support helped or harmed (<a href="#fig-support-pass" class="quarto-xref">Figure&nbsp;6</a>). SUB-E situates the recorded comparison: support is a service the two schools allocate, and the source documentation records that a student received extra educational support without recording who decided, on what evidence, or at what point in the year <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>.</p>
<p>One <em>plausible but unsourced</em> explanation of the reversal is that support is directed toward students already judged to be struggling. If that were the allocation rule, prior difficulty would be a common cause of both support and passing, a pattern generally called confounding by indication. That sentence is a candidate explanation offered in this chapter, not a documented mechanism, and it is marked as unsourced here precisely so that it cannot be read later as a recorded design fact. SUB-J is therefore limited: the proposed explanation is not established support.</p>
<p>The data source includes past failures and two earlier grade periods, but those variables do not recover the allocation rule. Past failures are nearly equal across support groups, while the earlier grades occur within the same course year and therefore cannot separate difficulty that prompted support from an effect of support. The confounding-by-indication explanation remains plausible but unverified.</p>
<p>SUB-I is consequently descriptive, not causal. If the groups differ on characteristics connected to the very decision that produced the support, the gap reports their composition at least as much as anything about the service, and nothing in the evidence settles how much of each. SUB-C records that result with what the design cannot reach: these observations cannot say whether support helped, harmed, or did nothing, because support was not assigned, the allocation rule is undocumented, the recorded prior variables do not recover it, and the schools are not a probability sample of any population. Writing out what is out of range completes the structure; a stronger sentence with a caveat attached would not.</p>
<p>Chapter 4 develops formal categorical-association procedures. The essential prerequisite here is choosing the denominator and separating sample pattern, population generalization, and causal interpretation.</p>
</section>
</section>
<section id="probability-as-a-model-of-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="probability-as-a-model-of-uncertainty">Probability as a Model of Uncertainty</h2>
<section id="probability-begins-with-a-repeatable-story" class="level3">
<h3 class="anchored" data-anchor-id="probability-begins-with-a-repeatable-story">Probability begins with a repeatable story</h3>
<p>A probability is not simply an observed percentage with a mathematical symbol. It belongs to a specified model for uncertain outcomes. A probability model defines:</p>
<ol type="1">
<li>the possible outcomes or sample space;</li>
<li>the event of interest;</li>
<li>the mechanism assigning probabilities;</li>
<li>what is regarded as fixed and what is allowed to vary.</li>
</ol>
<p>For event <span class="math inline">\(A\)</span> in sample space <span class="math inline">\(S\)</span>, the axioms require <span class="math inline">\(0\le P(A)\le 1\)</span> and <span class="math inline">\(P(S)=1\)</span>, together with additivity over disjoint events <span class="citation" data-cites="cramer1946">(<a href="#ref-cramer1946" role="doc-biblioref">Cramér, 1946</a>)</span>. The complement rule follows:</p>
<p><span class="math display">\[
P(A^c)=1-P(A).
\]</span></p>
<p>For two events, the general addition rule is</p>
<p><span class="math display">\[
P(A\cup B)=P(A)+P(B)-P(A\cap B).
\]</span></p>
<p>The subtraction prevents cases in both events from being counted twice. Mutually exclusive (disjoint) events satisfy <span class="math inline">\(P(A\cap B)=0\)</span>; they cannot occur together in one trial, and for them the addition rule reduces to <span class="math inline">\(P(A\cup B)=P(A)+P(B)\)</span> <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>.</p>
</section>
<section id="conditional-probability-changes-the-reference-set" class="level3">
<h3 class="anchored" data-anchor-id="conditional-probability-changes-the-reference-set">Conditional probability changes the reference set</h3>
<p>The probability of <span class="math inline">\(A\)</span> conditional on <span class="math inline">\(B\)</span> is defined by</p>
<p><span class="math display">\[
P(A\mid B)=\frac{P(A\cap B)}{P(B)},\qquad P(B)&gt;0,
\]</span></p>
<p>which is the classical definition, not a derived result <span class="citation" data-cites="cramer1946">(<a href="#ref-cramer1946" role="doc-biblioref">Cramér, 1946</a>)</span>. Conditioning replaces the full sample space with cases in <span class="math inline">\(B\)</span>. In a table, this is the same denominator discipline used for conditional percentages. In the student data,</p>
<p><span class="math display">\[
\widehat P(\text{pass}\mid\text{support})
=\frac{28}{51}
=0.549,
\]</span></p>
<p>where the hat emphasizes an empirical sample proportion rather than a known population probability. The corresponding proportion among students without recorded support is <span class="math inline">\(237/344=0.689\)</span>.</p>
<p>The multiplication rule rearranges the definition:</p>
<p><span class="math display">\[
P(A\cap B)=P(A\mid B)P(B).
\]</span></p>
<p>It supports probability trees because each path multiplies probabilities conditional on the preceding branch, and the probabilities of mutually exclusive paths are then added <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>.</p>
</section>
<section id="independence-is-a-model-restriction" class="level3">
<h3 class="anchored" data-anchor-id="independence-is-a-model-restriction">Independence is a model restriction</h3>
<p>Events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent when their joint probability factorizes:</p>
<p><span class="math display">\[
P(A\cap B)=P(A)P(B).
\]</span></p>
<p>When <span class="math inline">\(P(B)&gt;0\)</span>, this is equivalent to the conditional statement</p>
<p><span class="math display">\[
P(A\mid B)=P(A).
\]</span></p>
<p>The factorization is the general definition; the conditional equality is available only when the conditioning event has positive probability <span class="citation" data-cites="cramer1946">(<a href="#ref-cramer1946" role="doc-biblioref">Cramér, 1946</a>)</span>. In the observed student table,</p>
<div class="cell" data-layout-align="center">
<div id="tbl-empirical-probabilities" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-empirical-probabilities-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Empirical proportions used to compare the observed table with an independence factorization.
</figcaption>
<div aria-describedby="tbl-empirical-probabilities-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">P-hat(pass)</td>
<td style="text-align: right;">0.6709</td>
</tr>
<tr class="even">
<td style="text-align: left;">P-hat(support)</td>
<td style="text-align: right;">0.1291</td>
</tr>
<tr class="odd">
<td style="text-align: left;">P-hat(pass and support)</td>
<td style="text-align: right;">0.0709</td>
</tr>
<tr class="even">
<td style="text-align: left;">P-hat(pass) x P-hat(support)</td>
<td style="text-align: right;">0.0866</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The empirical quantities in <a href="#tbl-empirical-probabilities" class="quarto-xref">Table&nbsp;8</a> differ, but the sample is not itself the complete probability model. Formal uncertainty about a population association is deferred to Chapter 4. More importantly, statistical independence is not causal independence.</p>
<p>Mutual exclusivity and independence are also different. If two nonzero- probability events are mutually exclusive, observing one makes the other impossible, so they are dependent rather than independent.</p>
</section>
<section id="probability-language-must-name-the-source" class="level3">
<h3 class="anchored" data-anchor-id="probability-language-must-name-the-source">Probability language must name the source</h3>
<p>Three statements can use the same number while making different claims:</p>
<ul>
<li><strong>empirical proportion:</strong> 67.1% of the recorded students passed;</li>
<li><strong>finite-population proportion:</strong> 67.1% of students in a fully enumerated target population passed;</li>
<li><strong>model probability:</strong> a future outcome has probability 0.671 under a specified stochastic process.</li>
</ul>
<p>The data alone supply the first statement. Moving to the second or third requires a population definition or model. Good probability reasoning makes that extra structure explicit.</p>
</section>
</section>
<section id="random-variables-and-generative-models" class="level2">
<h2 class="anchored" data-anchor-id="random-variables-and-generative-models">Random Variables and Generative Models</h2>
<section id="a-random-variable-connects-outcomes-to-numbers" class="level3">
<h3 class="anchored" data-anchor-id="a-random-variable-connects-outcomes-to-numbers">A random variable connects outcomes to numbers</h3>
<p>A <strong>random variable</strong> is a variable whose value is a numerical outcome of a random phenomenon: it assigns a number to each outcome in a probability model <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. A discrete random variable has countable possible values; a continuous random variable is represented over intervals. The distinction belongs to the model, not merely to whether a computer stores decimals.</p>
<p>A <strong>probability mass function</strong> gives <span class="math inline">\(P(X=x)\)</span> for discrete values. A <strong>density</strong> for a continuous variable assigns probabilities to intervals as areas under a curve of total area one; the probability of one exact continuous value is zero even where the density is high <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>.</p>
</section>
<section id="the-binomial-model-is-a-four-part-story" class="level3">
<h3 class="anchored" data-anchor-id="the-binomial-model-is-a-four-part-story">The binomial model is a four-part story</h3>
<p>If <span class="math inline">\(X\)</span> counts successes in <span class="math inline">\(m\)</span> trials, then</p>
<p><span class="math display">\[
X\sim\operatorname{Binomial}(m,p)
\]</span></p>
<p>requires a fixed number <span class="math inline">\(m\)</span> of trials, two coded outcomes per trial, the same success probability <span class="math inline">\(p\)</span>, and independence under the model <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Classical texts write <span class="math inline">\(B(n,p)\)</span>; the number of trials is called <span class="math inline">\(m\)</span> here only to keep it distinct from the sample size <span class="math inline">\(n\)</span> used elsewhere in the chapter. Its mass function is</p>
<p><span class="math display">\[
P(X=k)={m\choose k}p^k(1-p)^{m-k},
\qquad k=0,1,\ldots,m,
\]</span></p>
<p>with mean <span class="math inline">\(mp\)</span> and SD <span class="math inline">\(\sqrt{mp(1-p)}\)</span> <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>.</p>
<p><a href="#fig-binomial-model" class="quarto-xref">Figure&nbsp;7</a> shows a hypothetical story with 10 independent trials and <span class="math inline">\(p=0.70\)</span>. These assumptions are adopted for the demonstration, not claims learned from the student data.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-binomial-model" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="A discrete probability plot peaks at seven successes and assigns progressively smaller probabilities toward zero and ten successes.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-binomial-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-binomial-model-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" alt="A discrete probability plot peaks at seven successes and assigns progressively smaller probabilities toward zero and ten successes.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-binomial-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Binomial probabilities for 10 hypothetical independent trials with constant success probability 0.70.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The number passing among 10 students is binomial only when those 10 trials are fixed in advance, each has the same modeled pass probability, and the outcomes are independent under the model. Merely observing a group of students and counting passes does not supply those conditions; the generating story does.</p>
</section>
<section id="the-normal-model-is-symmetric" class="level3">
<h3 class="anchored" data-anchor-id="the-normal-model-is-symmetric">The Normal model is symmetric</h3>
<p>A Normal random variable with mean <span class="math inline">\(\mu\)</span> and SD <span class="math inline">\(\sigma&gt;0\)</span> has density</p>
<p><span class="math display">\[
f(x)=\frac{1}{\sigma\sqrt{2\pi}}
\exp\left[-\frac{(x-\mu)^2}{2\sigma^2}\right].
\]</span></p>
<p>The density is continuous, unimodal, and <strong>symmetric</strong> around <span class="math inline">\(\mu\)</span>, with inflection points at <span class="math inline">\(\mu\pm\sigma\)</span> <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. The mean, median, and mode coincide under the exact model, and values equally far above and below <span class="math inline">\(\mu\)</span> have the same density, as <a href="#fig-normal-symmetry" class="quarto-xref">Figure&nbsp;8</a> shows.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-normal-symmetry" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center" alt="A symmetric bell-shaped density is centered at seventy, with equal heights at values equally far below and above the mean.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-symmetry-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-normal-symmetry-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" alt="A symmetric bell-shaped density is centered at seventy, with equal heights at values equally far below and above the mean.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-symmetry-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: A hypothetical Normal density with mean 70 and standard deviation 10.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Standardizing expresses distance from the mean in SD units:</p>
<p><span class="math display">\[
Z=\frac{X-\mu}{\sigma}.
\]</span></p>
<p>The value <span class="math inline">\(Z\)</span> is the classical <em>z</em>-score: it counts how many SDs an observation lies above or below the mean, and under an exact Normal model <span class="math inline">\(Z\)</span> itself has mean 0 and SD 1 <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Standardizing changes the location and scale, not the rank or shape. An observed histogram need not be exactly Normal for a Normal approximation to be useful, and a bell-looking histogram does not prove independent Normal generation. The purpose and sensitivity of the calculation determine how close an approximation must be.</p>
</section>
<section id="simulation-exposes-assumptions-it-does-not-validate-them" class="level3">
<h3 class="anchored" data-anchor-id="simulation-exposes-assumptions-it-does-not-validate-them">Simulation exposes assumptions; it does not validate them</h3>
<p>A simulation follows this contract:</p>
<ol type="1">
<li>state the population or stochastic process;</li>
<li>identify fixed parameter values and independence assumptions;</li>
<li>state the sample size and statistic;</li>
<li>repeat the sampling operation many times;</li>
<li>summarize what happened under those chosen assumptions;</li>
<li>keep the claim conditional on the simulated process.</li>
</ol>
<p>Simulation is now a standard way of building intuition about repeated sampling before any formula is applied <span class="citation" data-cites="cetinkaya2024">(<a href="#ref-cetinkaya2024" role="doc-biblioref">Çetinkaya-Rundel &amp; Hardin, 2024</a>)</span>. It can show how skewness, dependence, or sample size affects a statistic. It cannot establish that the same assumptions describe a real study. That requires design knowledge, measurement evidence, and model checking.</p>
</section>
</section>
<section id="sampling-repeated-samples-and-statistical-reasoning" class="level2">
<h2 class="anchored" data-anchor-id="sampling-repeated-samples-and-statistical-reasoning">Sampling, Repeated Samples, and Statistical Reasoning</h2>
<section id="population-sample-parameter-and-statistic" class="level3">
<h3 class="anchored" data-anchor-id="population-sample-parameter-and-statistic">Population, sample, parameter, and statistic</h3>
<p>A <strong>target population</strong> is the collection of units about which a claim is intended. A <strong>sample</strong> is the set observed under a sampling and response process. A <strong>parameter</strong> is a numerical feature of the population or model, such as a population mean <span class="math inline">\(\mu\)</span>; a <strong>statistic</strong> is a function of observed sample data, such as <span class="math inline">\(\bar X\)</span>, used to estimate a parameter. Keeping the two apart, and reserving Greek letters for parameters, is the classical convention <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. <a href="#tbl-sampling-objects" class="quarto-xref">Table&nbsp;9</a> records what each object is and whether repetition holds it fixed.</p>
<div id="tbl-sampling-objects" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[22,30,48]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sampling-objects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Repeated sampling varies the sample while holding the target process fixed.
</figcaption>
<div aria-describedby="tbl-sampling-objects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 30%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Object</th>
<th style="text-align: left;">Example</th>
<th style="text-align: left;">Fixed or variable in repeated sampling?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Population/model</td>
<td style="text-align: left;">Distribution with mean <span class="math inline">\(\mu=10\)</span></td>
<td style="text-align: left;">Fixed by the simulation</td>
</tr>
<tr class="even">
<td style="text-align: left;">One sample</td>
<td style="text-align: left;"><span class="math inline">\(X_1,\ldots,X_n\)</span></td>
<td style="text-align: left;">Changes across repetitions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Statistic</td>
<td style="text-align: left;"><span class="math inline">\(\bar X\)</span></td>
<td style="text-align: left;">Changes because the sample changes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sampling distribution</td>
<td style="text-align: left;">Distribution of <span class="math inline">\(\bar X\)</span> across repetitions</td>
<td style="text-align: left;">Induced by the sampling process</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The real-data example is a curated subset of the Student Performance dataset in the UCI Machine Learning Repository <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>, which the repository distributes under CC BY 4.0 reuse terms. It is a real sample of records from two schools, but the available documentation does not make it a probability sample of all Portuguese students or students elsewhere. How far a result travels beyond the observed cases is settled by the sampling and study design, not by the analysis <span class="citation" data-cites="cetinkaya2024">(<a href="#ref-cetinkaya2024" role="doc-biblioref">Çetinkaya-Rundel &amp; Hardin, 2024</a>)</span>. A large number of observations cannot repair an undefined target population or a nonprobability selection process.</p>
</section>
<section id="sampling-variability-is-not-a-data-error" class="level3">
<h3 class="anchored" data-anchor-id="sampling-variability-is-not-a-data-error">Sampling variability is not a data error</h3>
<p>Imagine repeatedly drawing samples of size <span class="math inline">\(n\)</span> from the same population by the same procedure. Each sample produces a different mean, proportion, or correlation. The distribution of those repeated statistics is the <strong>sampling distribution</strong>: the distribution of values taken by the statistic in all possible samples of the same size from the same population <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>.</p>
<p>The <strong>standard error</strong> (SE), the SD of a statistic’s sampling distribution and therefore a measure of how much the statistic moves from sample to sample, is the basic precision summary. For an independent sample mean from a population with finite SD <span class="math inline">\(\sigma\)</span>,</p>
<p><span class="math display">\[
SE(\bar X)=\frac{\sigma}{\sqrt n},
\]</span></p>
<p>and <span class="math inline">\(\bar X\)</span> is unbiased for <span class="math inline">\(\mu\)</span> under that same sampling model <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. When <span class="math inline">\(\sigma\)</span> is unknown, <span class="math inline">\(s/\sqrt n\)</span> estimates this quantity under the same sampling assumptions. The formula explains a square-root relationship: quadrupling <span class="math inline">\(n\)</span> halves the idealized SE. It does not cover bias from nonresponse, measurement error, dependence, or model misspecification.</p>
</section>
<section id="the-law-of-large-numbers-concerns-stabilization" class="level3">
<h3 class="anchored" data-anchor-id="the-law-of-large-numbers-concerns-stabilization">The law of large numbers concerns stabilization</h3>
<p>Under the classical independent-and-identically-distributed (iid), finite-mean conditions, the law of large numbers says that a running sample mean becomes increasingly likely to fall within any fixed distance of <span class="math inline">\(\mu\)</span> as the number of observations grows <span class="citation" data-cites="moore2014 cramer1946">(<a href="#ref-cramer1946" role="doc-biblioref">Cramér, 1946</a>; <a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>:</p>
<p><span class="math display">\[
\bar X_n \xrightarrow{p} \mu.
\]</span></p>
<p><a href="#fig-lln" class="quarto-xref">Figure&nbsp;9</a> begins with independent Exponential draws having population mean 10. Early running means vary substantially; later values stabilize near 10. This is one simulated sequence, not a guarantee that every later running mean is closer than every earlier one.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-lln" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" alt="A running mean fluctuates widely over the first draws and gradually stabilizes near the horizontal population-mean line at ten by four hundred draws." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lln-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-lln-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" data-fig-pos="H" alt="A running mean fluctuates widely over the first draws and gradually stabilizes near the horizontal population-mean line at ten by four hundred draws.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lln-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: One running mean from independent Exponential draws with known population mean 10.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The law does not say that the raw observations become less variable or more Normal. It concerns stabilization of an average under a continuing sampling process.</p>
</section>
<section id="the-central-limit-theorem-concerns-shape-after-standardization" class="level3">
<h3 class="anchored" data-anchor-id="the-central-limit-theorem-concerns-shape-after-standardization">The central limit theorem concerns shape after standardization</h3>
<p>For independent, identically distributed observations with finite mean and variance, a classical central limit theorem states</p>
<p><span class="math display">\[
\frac{\bar X_n-\mu}{\sigma/\sqrt n}
\xrightarrow{d}N(0,1)
\]</span></p>
<p>as <span class="math inline">\(n\)</span> grows <span class="citation" data-cites="cramer1946">(<a href="#ref-cramer1946" role="doc-biblioref">Cramér, 1946</a>)</span>. Thus the sampling distribution of <span class="math inline">\(\bar X\)</span> becomes approximately Normal with mean <span class="math inline">\(\mu\)</span> and SD <span class="math inline">\(\sigma/\sqrt n\)</span> under the stated conditions <span class="citation" data-cites="moore2014">(<a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. This asymptotic result neither makes the raw data Normal nor supplies a universal finite-sample cutoff.</p>
<p><a href="#fig-clt-sampling-means" class="quarto-xref">Figure&nbsp;10</a> uses 5,000 independent samples from a strongly right-skewed Exponential population with mean and SD 10, retaining only each sample mean.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-clt-sampling-means" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-pos="H" alt="Three histograms show sample means from five thousand repetitions at sample sizes five, thirty, and one hundred. All three panels share one horizontal axis, so the distributions visibly narrow and become more symmetric as sample size increases, while remaining centered near ten." data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clt-sampling-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="chapter_02_files/figure-html/fig-clt-sampling-means-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:86.0%" data-fig-pos="H" alt="Three histograms show sample means from five thousand repetitions at sample sizes five, thirty, and one hundred. All three panels share one horizontal axis, so the distributions visibly narrow and become more symmetric as sample size increases, while remaining centered near ten.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clt-sampling-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Sampling distributions of the mean from a known right-skewed Exponential population, drawn on one shared horizontal scale.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div id="tbl-clt-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-clt-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Repeated-sampling summaries under the stated Exponential population model.
</figcaption>
<div aria-describedby="tbl-clt-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">n</th>
<th style="text-align: right;">Theoretical SE</th>
<th style="text-align: right;">Mean of sample means</th>
<th style="text-align: right;">Empirical SE</th>
<th style="text-align: right;">Skewness</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4.472</td>
<td style="text-align: right;">9.911</td>
<td style="text-align: right;">4.444</td>
<td style="text-align: right;">0.930</td>
</tr>
<tr class="even">
<td style="text-align: right;">30</td>
<td style="text-align: right;">1.826</td>
<td style="text-align: right;">10.003</td>
<td style="text-align: right;">1.812</td>
<td style="text-align: right;">0.346</td>
</tr>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">10.020</td>
<td style="text-align: right;">0.985</td>
<td style="text-align: right;">0.186</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The sampling distributions in <a href="#fig-clt-sampling-means" class="quarto-xref">Figure&nbsp;10</a> center near 10. The three panels share one horizontal scale, so the narrowing is visible directly rather than inferred: only the vertical density scale is allowed to float, and letting both axes float would have made three differently scaled pictures look alike. Their empirical SDs, reported in <a href="#tbl-clt-summary" class="quarto-xref">Table&nbsp;10</a>, track <span class="math inline">\(10/\sqrt n\)</span>, and skewness declines. But <span class="math inline">\(n=30\)</span> is neither a theorem nor a pass/fail boundary; how large a sample must be depends on how far the population departs from Normality <span class="citation" data-cites="moore2014 cetinkaya2024">(<a href="#ref-cetinkaya2024" role="doc-biblioref">Çetinkaya-Rundel &amp; Hardin, 2024</a>; <a href="#ref-moore2014" role="doc-biblioref">Moore et al., 2014</a>)</span>. Approximation quality depends on the population tails, dependence, the statistic, and the intended use. A mean from a mildly skewed population, an extreme quantile, a rare-event proportion, and a clustered sample can behave very differently at the same <span class="math inline">\(n\)</span>.</p>
</section>
<section id="keep-three-distributions-separate" class="level3">
<h3 class="anchored" data-anchor-id="keep-three-distributions-separate">Keep three distributions separate</h3>
<div id="tbl-three-distributions" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[17,27,23,33]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-three-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Data, probability, and sampling distributions answer different questions.
</figcaption>
<div aria-describedby="tbl-three-distributions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 27%">
<col style="width: 23%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Distribution</th>
<th style="text-align: left;">What varies?</th>
<th style="text-align: left;">Example</th>
<th style="text-align: left;">Primary question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Data distribution</td>
<td style="text-align: left;">Recorded values across observed units</td>
<td style="text-align: left;">395 final grades</td>
<td style="text-align: left;">What does this sample contain?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Probability distribution</td>
<td style="text-align: left;">Hypothetical outcome under a model</td>
<td style="text-align: left;"><span class="math inline">\(X\sim N(70,10^2)\)</span></td>
<td style="text-align: left;">What outcomes does the model make more or less probable?</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sampling distribution</td>
<td style="text-align: left;">A statistic across repeated samples</td>
<td style="text-align: left;">means from 5,000 samples</td>
<td style="text-align: left;">How would the statistic vary under the sampling model?</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Confusing the objects in <a href="#tbl-three-distributions" class="quarto-xref">Table&nbsp;11</a> creates familiar errors. A Normal sampling distribution of a mean does not make the individual observations Normal. A Normal-looking histogram does not guarantee a Normal sampling distribution under dependence. A probability model does not describe an empirical sample until its assumptions are connected to the study.</p>
</section>
<section id="from-a-sample-description-to-a-bounded-claim" class="level3">
<h3 class="anchored" data-anchor-id="from-a-sample-description-to-a-bounded-claim">From a sample description to a bounded claim</h3>
<p>A coherent descriptive paragraph connects the cases and variables in STAT-E, the design and analytic support in STAT-J, the target and checks in STAT-I, and the reservations retained in STAT-C. Reporting standards ask for this combination of evidence, summaries, and limits <span class="citation" data-cites="appelbaum2018">(<a href="#ref-appelbaum2018" role="doc-biblioref">Appelbaum et al., 2018</a>)</span>.</p>
<p>For the public observational data:</p>
<blockquote class="blockquote">
<p>The analytic table contained 395 mathematics-course records from two Portuguese schools, with no missing values in the curated variables. Final grades on the 0-20 scale had mean 10.42, median 11, SD 4.58, and IQR 6. Absences were right-skewed (median 4, maximum 75). The Pearson sample correlation between absences and final grade was 0.034, indicating little linear sample association. Spearman’s rank correlation was 0.018, likewise indicating little overall monotone association. The scatterplot should remain primary because of discreteness, possible nonlinearity, and unusual absence counts. Grade distributions overlapped across the four reported study-time categories. All 38 recorded zeros were retained because they lie within the documented grade scale and no alternative recoding rule is documented. These summaries describe the recorded students and do not identify effects of changing absence or study time, nor do they establish generalization beyond the source schools.</p>
</blockquote>
<p>Chapter 3 adds confidence intervals, tests, effect sizes, and prospective precision. Those tools deepen STAT-I and STAT-C; they do not replace the measurement, denominator, support, and scope audits that STAT-E and STAT-J supply here.</p>
</section>
</section>
<section id="argument-record-and-three-perspectives" class="level2">
<h2 class="anchored" data-anchor-id="argument-record-and-three-perspectives">Argument Record and Three Perspectives</h2>
<p>The four shared roles below contain all eight concise components. Reading across each role makes the corresponding statistical-to-substantive relation traceable.</p>
<div id="tbl-ch02-argument-record" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[18,38,44]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ch02-argument-record-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Argument record for the exploratory absence–grade question.
</figcaption>
<div aria-describedby="tbl-ch02-argument-record-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 38%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Shared role</th>
<th style="text-align: left;">Statistical argument</th>
<th style="text-align: left;">Substantive argument and transition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Evidence – situates</strong></td>
<td style="text-align: left;"><strong>STAT-E:</strong> Absence counts and documented 0–20 final grades for all 395 students in two Portuguese schools; the source reports no missing values.</td>
<td style="text-align: left;"><strong>SUB-E:</strong> The observations concern recorded attendance and mathematics attainment in one school context; it situates the variables, students, setting, and time represented by STAT-E.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Justification – augments and evaluates</strong></td>
<td style="text-align: left;"><strong>STAT-J:</strong> Pearson’s <span class="math inline">\(r\)</span> describes linear sample association, Spearman’s coefficient describes rank-based monotone association, and the scatterplot checks visible form and support. No probability sampling, assignment, or superpopulation model supports wider inference.</td>
<td style="text-align: left;"><strong>SUB-J:</strong> Measurement and design information augments and evaluates STAT-J: absence counts do not reveal missed instruction, grades are bounded, and the observational source supplies no basis for a causal effect.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Inference – interprets</strong></td>
<td style="text-align: left;"><strong>STAT-I:</strong> Across the same 395 records, Pearson’s <span class="math inline">\(r\)</span> is 0.034 and Spearman’s rank correlation is 0.018; no interval or test is attached.</td>
<td style="text-align: left;"><strong>SUB-I:</strong> Interpreting STAT-I with the scatterplot, the records show little overall linear or monotone association, but these summaries do not exclude nonlinear or subgroup patterns and do not estimate the effect of preventing absence.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Claim – bounds and calibrates</strong></td>
<td style="text-align: left;"><strong>STAT-C:</strong> Among all 395 recorded students, Pearson’s r was 0.034 and Spearman’s rank correlation was 0.018. Both are near zero, so the records show little overall linear or monotone association. This exploratory description does not rule out nonlinear or subgroup patterns and is not a wider-population or causal estimate.</td>
<td style="text-align: left;"><strong>SUB-C:</strong> Among these recorded students, Pearson’s <span class="math inline">\(r\)</span> was 0.034 and Spearman’s rank correlation was 0.018, indicating little overall linear or monotone association. The answer is exploratory, retains possible nonlinear or subgroup structure, and is limited to a noncausal description of these students. STAT-C bounds and calibrates this answer.</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="argument-perspective" class="level3">
<h3 class="anchored" data-anchor-id="argument-perspective">Argument perspective</h3>
<p>STAT-E and STAT-J jointly support STAT-I, which supports the bounded STAT-C. The substantive argument is logically parallel: SUB-E and SUB-J support SUB-I, which supports SUB-C. The transitions have distinct roles: SUB-E <strong>situates</strong> STAT-E, SUB-J <strong>augments and evaluates</strong> STAT-J, SUB-I <strong>interprets</strong> STAT-I, and STAT-C <strong>bounds and calibrates</strong> SUB-C.</p>
</section>
<section id="workflow-perspective" class="level3">
<h3 class="anchored" data-anchor-id="workflow-perspective">Workflow perspective</h3>
<p>The complete workflow is:</p>
<ol type="1">
<li><strong>Conduct the literature review</strong></li>
<li><strong>Frame the research question and candidate answer</strong></li>
<li><strong>Plan design, measurement, and method of inference</strong></li>
<li><strong>Align and synthesize across questions: proposal phase</strong></li>
<li><strong>Conduct the study and collect or acquire data and contextual information</strong></li>
<li><strong>Conduct statistical estimation, checking, and analysis</strong></li>
<li><strong>Contextualize, justify, and interpret substantively</strong></li>
<li><strong>Synthesize across questions: implementation phase</strong></li>
</ol>
<p>This chapter concentrates on the fifth through seventh activities. Comparing the scatterplot, Pearson’s coefficient, and Spearman’s coefficient shows how checking can revisit the analytic summary without dropping observations or changing the population represented by the evidence.</p>
</section>
<section id="evaluation-perspective" class="level3">
<h3 class="anchored" data-anchor-id="evaluation-perspective">Evaluation perspective</h3>
<p>The seven lenses are <strong>Question alignment</strong>, <strong>Evidence integrity</strong>, <strong>Justification adequacy</strong>, <strong>Inferential adequacy</strong>, <strong>Transition fidelity</strong>, <strong>Claim calibration</strong>, and <strong>Cross-question coherence</strong>. For this one-question example, Evidence integrity confirms the documented grade range and retention of all records; Inferential adequacy compares graphical form with linear and rank-based summaries; Transition fidelity carries their limits into the substantive interpretation; and Claim calibration keeps the answer exploratory, noncausal, and local.</p>
</section>
</section>
<section id="reading-bridge" class="level2">
<h2 class="anchored" data-anchor-id="reading-bridge">Reading Bridge</h2>
<p>These links lead directly to publicly accessible chapters of <em>Introduction to Modern Statistics</em> <span class="citation" data-cites="cetinkaya2024">(<a href="#ref-cetinkaya2024" role="doc-biblioref">Çetinkaya-Rundel &amp; Hardin, 2024</a>)</span> and of an open research methods text, plus the source documentation for the observational example <span class="citation" data-cites="cortez2008data">(<a href="#ref-cortez2008data" role="doc-biblioref">Cortez, 2008</a>)</span>. They extend the discussion without replacing the vocabulary and guardrails used here.</p>
<ul>
<li><a href="https://openintrostat.github.io/ims/data-hello.html">Introduction to Modern Statistics, Chapter 1: Hello data</a>
<ul>
<li>observational units, variables, data structures, and variation;</li>
</ul></li>
<li><a href="https://openintrostat.github.io/ims/data-design.html">Introduction to Modern Statistics, Chapter 2: Study design</a>
<ul>
<li>sampling, assignment, observational studies, and experiments;</li>
</ul></li>
<li><a href="https://openintrostat.github.io/ims/explore-categorical.html">Introduction to Modern Statistics, Chapter 4: Exploring categorical data</a>
<ul>
<li>counts, proportions, and graphical comparisons;</li>
</ul></li>
<li><a href="https://openintrostat.github.io/ims/explore-numerical.html">Introduction to Modern Statistics, Chapter 5: Exploring numerical data</a>
<ul>
<li>distribution shape, center, spread, and relationships;</li>
</ul></li>
<li><a href="https://openintrostat.github.io/ims/foundations-mathematical.html">Introduction to Modern Statistics, Chapter 13: Inference with mathematical models</a>
<ul>
<li>mathematical probability models and sampling distributions;</li>
</ul></li>
<li><a href="https://archive.ics.uci.edu/dataset/320/student+performance">UCI Student Performance dataset page</a>
<ul>
<li>source documentation, variable meanings, DOI, and reuse terms for the observational example;</li>
</ul></li>
<li><a href="https://kpu.pressbooks.pub/psychmethods4e/chapter/describing-single-variables/">Research Methods in Psychology: Describing Single Variables</a>
<ul>
<li>an additional open treatment of distributions and summaries;</li>
</ul></li>
<li><a href="https://kpu.pressbooks.pub/psychmethods4e/chapter/describing-statistical-relationships/">Research Methods in Psychology: Describing Statistical Relationships</a>
<ul>
<li>an additional open treatment of bivariate description.</li>
</ul></li>
</ul>
<p>While reading, mark whether each example concerns a data distribution, a probability distribution, or a sampling distribution. Then identify the observational unit, denominator, and strongest claim supported by the stated design.</p>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-agresti2018" class="csl-entry" role="listitem">
Agresti, A. (2018). <em>Statistical methods for the social sciences</em> (5th ed.). Pearson.
</div>
<div id="ref-appelbaum2018" class="csl-entry" role="listitem">
Appelbaum, M., Cooper, H., Kline, R. B., Mayo-Wilson, E., Nezu, A. M., &amp; Rao, S. M. (2018). Journal article reporting standards for quantitative research in psychology: The <span>APA</span> publications and communications board task force report. <em>American Psychologist</em>, <em>73</em>(1), 3–25. <a href="https://doi.org/10.1037/amp0000191">https://doi.org/10.1037/amp0000191</a>
</div>
<div id="ref-cetinkaya2024" class="csl-entry" role="listitem">
Çetinkaya-Rundel, M., &amp; Hardin, J. (2024). <em>Introduction to modern statistics</em> (2nd ed.). OpenIntro. <a href="https://openintro.org/book/ims/">https://openintro.org/book/ims/</a>
</div>
<div id="ref-cortez2008data" class="csl-entry" role="listitem">
Cortez, P. (2008). <em>Student performance</em> [Dataset]. UCI Machine Learning Repository. <a href="https://doi.org/10.24432/C5TG7T">https://doi.org/10.24432/C5TG7T</a>
</div>
<div id="ref-cramer1946" class="csl-entry" role="listitem">
Cramér, H. (1946). <em>Mathematical methods of statistics</em>. Princeton University Press.
</div>
<div id="ref-moore2014" class="csl-entry" role="listitem">
Moore, D. S., McCabe, G. P., &amp; Craig, B. A. (2014). <em>Introduction to the practice of statistics</em> (8th ed.). W. H. Freeman.
</div>
<div id="ref-nationalAcademies2019" class="csl-entry" role="listitem">
National Academies of Sciences, Engineering, and Medicine. (2019). <em>Reproducibility and replicability in science</em>. The National Academies Press. <a href="https://doi.org/10.17226/25303">https://doi.org/10.17226/25303</a>
</div>
<div id="ref-rcore2025" class="csl-entry" role="listitem">
R Core Team. (2025). <em><span>R</span>: A language and environment for statistical computing</em>. <span>R</span> Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>
</div>
<div id="ref-shadish2002" class="csl-entry" role="listitem">
Shadish, W. R., Cook, T. D., &amp; Campbell, D. T. (2002). <em>Experimental and quasi-experimental designs for generalized causal inference</em>. Houghton Mifflin.
</div>
<div id="ref-wickham2014" class="csl-entry" role="listitem">
Wickham, H. (2014). Tidy data. <em>Journal of Statistical Software</em>, <em>59</em>(10), 1–23. <a href="https://doi.org/10.18637/jss.v059.i10">https://doi.org/10.18637/jss.v059.i10</a>
</div>
</div>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<p>These answer-free tasks emphasize reasoning. The two focused computing tasks may be completed in R or SPSS; syntax itself is not assessed.</p>
<section id="identify-the-evidence-structure" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="identify-the-evidence-structure">Identify the evidence structure</h3>
<p>For the student-performance example, identify the observational unit, the two variables in the focal question, their recorded scales, and the strongest population and causal scope supported by the design.</p>
</section>
<section id="choose-a-defensible-description" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="choose-a-defensible-description">Choose a defensible description</h3>
<p>For completion times <code>18, 19, 20, 20, 21, 22, 23, 24, 65</code>, calculate the mean, median, SD, and IQR. For the quartiles, use the type-7 interpolation rule <span class="math inline">\(h=1+(n-1)p\)</span> and interpolate linearly between the surrounding ordered values; this is R’s default. Choose a primary display and pair of summaries, justify them in minutes, and state what should be checked about 65 before any exclusion.</p>
</section>
<section id="separate-probability-from-repeated-sampling" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="separate-probability-from-repeated-sampling">Separate probability from repeated sampling</h3>
<p>Among 200 students, 120 submitted a practice quiz, 150 passed, and 100 did both. Calculate the two conditional pass proportions and assess the empirical independence factorization. Then explain why this descriptive check is neither a causal effect nor a sampling-distribution analysis.</p>
</section>
<section id="critique-a-graph-and-claim" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="critique-a-graph-and-claim">Critique a graph and claim</h3>
<p>A report presents an unjittered absence–grade scatterplot, adds only a straight line, and concludes, “Attendance does not matter because <span class="math inline">\(r=.034\)</span>.” Identify at least three problems in the graph or claim. Describe one improved display and write a bounded replacement claim.</p>
</section>
<section id="modify-a-relationship-analysis" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="modify-a-relationship-analysis">Modify a relationship analysis</h3>
<p>Using all 395 student records, reproduce an absence–grade scatterplot and then modify it to reveal overlapping integer-valued observations and possible nonlinear form. Compute both Pearson’s and Spearman’s correlations. Explain what the modified graph and second coefficient add to the original analysis.</p>
</section>
<section id="modify-a-categorical-comparison" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="modify-a-categorical-comparison">Modify a categorical comparison</h3>
<p>Starting from the support-by-pass table, modify the analysis to report both pass percentages within each support group and support percentages within each pass-status group. Label every denominator and explain which comparison answers a question about pass rates among students with versus without recorded support.</p>
</section>
<section id="construct-an-open-argument-record" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="construct-an-open-argument-record">Construct an open argument record</h3>
<p>Choose one quantitative relationship question from the student data. Write one short entry for each of STAT-E, STAT-J, STAT-I, STAT-C, SUB-E, SUB-J, SUB-I, and SUB-C. Select a graph and summaries that fit the question, make the four transitions traceable, and label the analysis confirmatory or exploratory. Finish with a bounded claim. More than one analysis can be defensible if its question, support, and boundaries are explicit.</p>


</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jinsong-chen\.github\.io\/QMSBR\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Jinsong Chen · Text licensed CC BY 4.0 unless otherwise noted.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../about/index.html#citation">
<p>Citation</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../about/index.html#licences">
<p>Licences</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="mailto:jinsong.chen@live.com">
<p>Contact</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>