{
  "hash": "d0e4d92408f7389c151ea13ebb3db538",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Group Comparisons with Analysis of Variance\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\widowpenalty=10000\n          \\clubpenalty=10000\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{12\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\usepackage{xcolor}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\n\n\\clearpage\n\n::: {.callout-note title=\"Chapter overview\"}\nThis chapter compares means by examining variation. Two invented studies\nprovide the observations: a one-way experiment on background sound while\nstudying carries the first analyses, and a two-factor experiment\ncrossing feedback with practice schedule carries the factorial analysis,\nwhich asks how a comparison changes across practice schedules. We follow\nthe one-way ANOVA from individual scores to its F distribution,\ndistinguish its omnibus question from a particular contrast, and explain\nhow the comparison family determines an interval's coverage. Cell means\nand simple effects then reveal what main effects can conceal. A worked\nthree-way table, set beside the two-way table of the same study, shows\nhow a third factor adds rows and how a two-way pattern can itself\nchange, and what a fourth factor would add. By the end, you will be able\nto read an ANOVA table and the F distribution behind it, interpret a\ncontrast and its uncertainty within a family of comparisons, and connect\na factorial pattern to the design and model conditions that support its\ninterpretation.\n:::\n\nTwo **invented studies** supply the observations. In the first, thirty\nfirst-year university students each read the same passage for 20\nminutes and then answer a 20-item reading-comprehension quiz. Each\nstudent reads in an individual session and is randomly assigned to one\nof three background-sound conditions, ten to each: *Silence*,\n*Instrumental music*, or *Music with lyrics* playing during the reading.\nIn the second, twenty-four students study the same fractions material\nunder one of three kinds of feedback and one of two practice schedules,\nfour different students in each combination, and take a common 20-item\nquiz one week after their final practice. These design details and all\nscores are invented for teaching.\n\nOur first question concerns the background-sound study: how do the\nthree sound-condition means compare? Chapter 3 built, step by step, the\ntools for one comparison: an estimate and its standard error, a\nconfidence interval, a hypothesis test with its p-value, and the t tests\nfor one sample, paired samples and two independent samples. For two\nindependent groups sharing one spread, the equal-variance t test pooled\nthe two group variances. We extend that reasoning to several groups,\nkeeping the difference between an overall pattern and particular\ncomparisons visible.\n\nOur later question concerns the feedback-by-practice study: how does\nthe feedback comparison depend on practice schedule? Section 4 answers\nit, and Section 4.7 adds a third factor, the timing of the quiz.\n\n## Comparison Questions and Designs {#sec-ch04-design}\n\n### Outcomes, factors and levels\n\nBoth outcomes count correct answers. A comprehension score is the\nnumber of reading-comprehension items answered correctly, and a quiz\nscore is the number of fractions items answered correctly; each runs\nfrom 0 to 20, and higher values mean more correct answers. A four-point\ndifference therefore means four more correct answers on average; it\ndoes not by itself describe every aspect of reading comprehension or of\nlearning fractions.\n\nA **factor** in analysis of variance is a categorical variable defining\ngroups or conditions. Its categories are **levels**. Background sound is\none factor with three levels, so its analysis is **one-way**. The second\nstudy crosses two factors, feedback with three levels and practice\nschedule with two, so its analysis is **two-way** (Section 4). One-way\nand two-way refer to the number of factors, not to the number of\nlevels: a one-way analysis can compare three, four or more groups, and a\nthird or fourth crossed factor gives a three-way or four-way layout\n(Section 4.7). This use of *factor* differs from a latent factor used to\nrepresent shared indicator variation in a measurement model.\n\n\\Needspace{10\\baselineskip}\n\n| Sound condition | Comprehension scores of ten different students |\n|:--|:--|\n| Silence | 8, 9, 9, 11, 12, 13, 13, 14, 15, 16 |\n| Instrumental music | 6, 8, 8, 9, 9, 11, 11, 12, 12, 14 |\n| Music with lyrics | 4, 5, 6, 7, 8, 8, 9, 10, 11, 12 |\n\n: Invented reading-comprehension scores, ten different students per sound condition, on a 0--20 scale. {#tbl-ch04-sound-scores tbl-colwidths=\"[30,70]\"}\n\nEach score in @tbl-ch04-sound-scores belongs to a different student:\nthe ten scores of one sound condition describe ten different students,\nnot repeated measurements, and the student is both the stipulated\nassignment unit and the measurement unit. The scores are fixed teaching\nvalues. They place the three group means two points apart with similar,\nunequal spreads, so every calculation reproduces by hand, but they do\nnot establish a Normal model, equal variances or a real effect of\nbackground sound. The complete course data file, `background_sound.csv`,\nholds the same table in one row per student, with columns `student`,\n`sound` and `score`; students S01--S30 appear ten to each condition in\nthe order Silence, Instrumental music, Music with lyrics, and Silence is\nthe reference condition for the comparisons of Section 3.\n\n### Design determines the relevant comparison\n\nRandom allocation is stipulated in each invented story. If implemented\nin a real study, it could support a causal comparison among the\nparticipating students, subject to adherence, relevant interference and\nmissing outcomes. It would not make the participants a random sample of\nall students, and the data table alone establishes neither the\nimplementation of assignment nor representativeness.\n\nDifferent designs can produce superficially similar tables. If students\nwho heard one sound condition read together in one room, they would\nshare that session's influences, such as noise from a corridor or a\ndisruption partway through the reading. If whole classes received\nconditions, students within a class would share influences and the\nclass could be the assignment unit. If each student were measured twice,\nthe two outcomes would form a pair. For a real study, identify the\nallocation, any repeated measurements, shared sessions or classroom\nclustering, and any losses before choosing the error term: an\nuncertainty formula must reflect these connections rather than treat\nevery row as an independent assignment.\n\n\\Needspace{12\\baselineskip}\n\n## One-Way ANOVA {#sec-mean-comparison}\n\n### Grouped observations and the idea of ANOVA\n\nThe three sound conditions have means 12, 10 and 8 comprehension points\n(@tbl-ch04-group-summary). Each has ten scores, and the sample SDs,\n2.7080, 2.4037 and 2.5820, are similar. The ranges overlap widely: some\nstudents who read with lyrics playing, scoring 11 or 12, outscored some\nwho read in silence, scoring 8 or 9. A difference between means\nsummarizes group distributions; it does not say that every student in\none group outperformed every student in another.\n\n\\Needspace{12\\baselineskip}\n\n| Sound condition | n | Mean | SD | Range |\n|:--|--:|--:|--:|:--|\n| Silence | 10 | 12 | 2.7080 | 8--16 |\n| Instrumental music | 10 | 10 | 2.4037 | 6--14 |\n| Music with lyrics | 10 | 8 | 2.5820 | 4--12 |\n\n: Descriptions of the thirty background-sound scores. {#tbl-ch04-group-summary tbl-colwidths=\"[36,10,18,18,18]\"}\n\nWhy not compare the conditions two at a time? Three conditions give\nthree pairwise differences, and a t test of each at the .05 level asks\nthree questions. If all three model means were equal, the chance that\nat least one of the three tests rejects wrongly would be about .12,\nmore than twice the .05 that each test states. The three tests are not\nindependent, because each group mean enters two of them; three\nindependent tests would give $1-.95^3=.1426$. Chapter 3, Section 7.3,\nnoted that several tests raise the chance of at least one false\nrejection. Analysis of variance therefore asks the overall question\nfirst, in one test at .05: do the three means differ at all? Particular\ncomparisons follow, declared in advance or calibrated as a family\n(Section 3.3).\n\nHow can one test compare three means at once?\n@fig-ch04-separation-spread draws the thirty scores in its left panel:\neach box shows a group's median and middle half, and the points keep\nevery student visible, which a bar chart of the three means would hide.\nThe right panel is a constructed version with every score's distance\nfrom its group mean doubled, so the group means and counts stay fixed\nwhile the spread doubles. The same two-point steps between the means\nstand out against the narrow spread on the left and are lost in the\nwide spread on the right. That is the idea of analysis of variance: it\njudges how far apart the group means lie relative to how widely scores\nvary within the groups [@cetinkaya2024; @kutner2005]. Section 2.3 turns\nthis comparison into the F statistic and returns to the right panel with\nnumbers.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The idea of ANOVA: the same group means with different within-group spread. Left: the thirty invented scores. Right: a constructed version in which every score's distance from its group mean is doubled, so the group means and counts are unchanged, although the medians that the boxes mark can shift. Boxes show each group's median and middle half; each point is a student, jittered sideways so that equal scores stay visible.](chapter_04_files/figure-html/fig-ch04-separation-spread-1.png){#fig-ch04-separation-spread fig-pos='!ht' fig-alt='Two panels of vertical boxplots with jittered points for Silence, Instrumental music and Music with lyrics, on a 0 to 20 score axis. In the left panel the invented scores span 4 to 16, with medians 12.5, 10 and 8. In the right panel every deviation from the group mean is doubled, so the scores span 0 to 20, the boxes are about twice as tall and the Silence median moves to 13, while the group means stay at 12, 10 and 8.' width=100%}\n:::\n:::\n\n\n### The group-mean model and the partition of variation\n\nWrite $Y_{ij}$ for the random score of student $i$ in sound condition $j$.\nHere $j$ indexes a group, rather than a data-file column. The one-way\nmodel is\n\n$$\nY_{ij}=\\mu_j+\\varepsilon_{ij}.\n$$\n\nThe unknown $\\mu_j$ is the group mean in the model, and\n$\\varepsilon_{ij}$ is that student's unknown departure from it. After\nfitting the group means, the **fitted value** is\n$\\widehat y_{ij}=\\bar y_j$, and the **residual** is\n$e_{ij}=y_{ij}-\\bar y_j$. A residual is calculated from observed scores\nand fitted means; a model error is a departure from an unknown model\nmean. This distinction will recur in regression.\n\nThe comparison concerns two explanations of the same thirty scores.\nA **one-mean model**, $Y_{ij}=\\mu+\\varepsilon_{ij}$, gives every sound\ncondition the same mean. The **group-mean model** lets each condition\nhave its own mean, $Y_{ij}=\\mu_j+\\varepsilon_{ij}$. Both allow students\nto differ around their model mean. The second model can reproduce the\nfirst by setting its three means equal. Fitting separate means can\ntherefore reduce the residual variation even when the population means\nare equal; a smaller residual sum of squares alone cannot settle the\ncomparison. Section 2.3 judges that improvement relative to the\nremaining within-group variation and the two extra mean parameters.\n\nThe observed grand mean is $\\bar y=10$, the average of the three\ngroup means because the groups are equally sized. Every score's\ndistance from the grand mean splits into two parts, the group's\ndeparture from the grand mean and the student's residual:\n\n$$\ny_{ij}-\\bar y=(\\bar y_j-\\bar y)+(y_{ij}-\\bar y_j).\n$$\n\nFor the Music-with-lyrics student who scored 4, $4-10=(8-10)+(4-8)$:\nthe group mean lies two points below the grand mean, and this student\nanother four points below the group mean. The first part is shared by\nevery student in the group; the second differs from student to\nstudent.\n\n[]{#app-ch04-small-data}Squaring the parts and adding over all thirty\nstudents turns the split into a partition of the total squared\nvariation, $SS_T=SS_B+SS_W$, where\n\n$$\n\\begin{aligned}\nSS_T&=\\sum_{j=1}^J\\sum_{i=1}^{n_j}(y_{ij}-\\bar y)^2,\\\\\nSS_B&=\\sum_{j=1}^Jn_j(\\bar y_j-\\bar y)^2,\\\\\nSS_W&=\\sum_{j=1}^J\\sum_{i=1}^{n_j}(y_{ij}-\\bar y_j)^2.\n\\end{aligned}\n$$\n\nThe **total sum of squares** $SS_T$ measures variation around the one\ngrand mean. The **between-group sum of squares** $SS_B$ counts each\ngroup's departure once for every student in that group, so it grows as\nthe group means separate. The **within-group sum of squares** $SS_W$\nadds the squared residuals around the group means. The partition holds\nbecause, within each group, the cross-products\n$2(\\bar y_j-\\bar y)(y_{ij}-\\bar y_j)$ sum to zero: the group's departure\nis the same for every student, and the residuals of a group sum to zero.\nFor the background-sound study, $SS_B=80$, $SS_W=178$ and\n$SS_T=258$, in squared comprehension points. The Instrumental-music\ngroup adds nothing to $SS_B$, because its mean equals the grand mean,\nalthough its scores still vary. The partition is arithmetic; it needs no\nNormality or independence assumption. Those conditions enter when the\npartition is used for inference, in Section 2.3.\n\n### Degrees of freedom, mean squares and the F test {#sec-ch04-f-test}\n\nThe F statistic puts the idea of @fig-ch04-separation-spread into one\nnumber, the variation among the group means divided by the variation\nwithin the groups, each measured as an average squared departure. A sum\nof squares grows with both the size of the departures and the number of\nthem, so each is divided by its **degrees of freedom** (df), the number\nof departures that can vary freely, before the two sources are compared.\nThe F statistic has two kinds of df.\n\n- The **between-groups df**, $J-1=2$, are the numerator df. The three\n  group means can take any values, but once the grand mean is fixed\n  their departures from it, weighted by group size, sum to zero, so\n  only two of them are free.\n- The **within-groups df**, $N-J=27$, are the denominator df. The ten\n  residuals of each group sum to zero, so nine of them are free in each\n  group, and three groups give 27.\n\nThe two kinds add to the total df, $N-1=29$, because the thirty\ndepartures from the grand mean sum to zero. Dividing each sum of squares\nby its df gives a **mean square**,\n\n$$\nMS_B=\\frac{SS_B}{J-1},\\qquad MS_W=\\frac{SS_W}{N-J},\\qquad\nF=\\frac{MS_B}{MS_W}.\n$$\n\nThe within-group mean square is the pooled variance of Chapter 3,\nSection 2.2, extended from two groups to $J$: each group's sample\nvariance $s_j^2$ is weighted by its own df,\n\n$$\nMS_W=\\frac{\\sum_{j=1}^J(n_j-1)s_j^2}{\\sum_{j=1}^J(n_j-1)}.\n$$\n\nWith equal group sizes it is the plain average of the group variances,\nhere 7.3333, 5.7778 and 6.6667. @tbl-ch04-one-way-anova gathers the\nparts.\n\n\\Needspace{9\\baselineskip}\n\n| Source | SS | df | What the df count | MS | F | p |\n|:--|--:|--:|:--|--:|--:|--:|\n| Sound condition | 80 | 2 | Group means free to vary, $J-1$ | 40.0000 | 6.0674 | .0067 |\n| Within groups | 178 | 27 | Residuals free to vary after fitting three means, $N-J$ | 6.5926 | | |\n| Total | 258 | 29 | Departures from the grand mean free to vary, $N-1$ | | | |\n\n: One-way ANOVA for the 30 students of the background-sound study, with what each df counts. {#tbl-ch04-one-way-anova tbl-colwidths=\"[20,10,5,39,10,9,7]\"}\n\n[]{#sec-ch04-anova-table}Read the table as one sentence about the\nobservations, $\\text{Data}=\\text{fit}+\\text{residual}$. The\nsound-condition row is the fit, what the three group means account for;\nthe within-groups row is the residual, what is left around them; and the\ntotal row is the data, measured around the grand mean. The sums of\nsquares add across the rows, $80+178=258$, and so do the df, $2+27=29$,\nwhich makes a quick check of any printed table. $MS_W=6.5926$ estimates\nthe common error variance of the model; it is smaller than the total\nsample variance, $258/29=8.8966$, because it leaves out the separation\nof the means. Statistical software fits the same model from the thirty\nrecords and often prints a longer layout, with rows such as an intercept\nand an uncorrected total that serve the fitting rather than the\ncomparison question; the Computer Lab reads one such layout row by row.\n\n\\Needspace{10\\baselineskip}\n\n| Fitted mean model | Fitted values | Residual SS | Residual df |\n|:--|:--|--:|--:|\n| One common mean | 10 for every student | 258 | 29 |\n| Three group means | 12, 10 and 8 for the respective conditions | 178 | 27 |\n\n: The same thirty scores fitted by one mean or three group means. {#tbl-ch04-oneway-models tbl-colwidths=\"[28,42,15,15]\"}\n\nAllowing the means to differ removes 80 squared score points from the\nresidual variation, the between-group SS in the ANOVA table, while\nusing two more mean parameters. Its mean square is 40, compared with\n6.5926 left within groups, giving the same F of 6.0674. Thus the\nbetween/within reading and the model-comparison reading explain one\ntest. The reference distribution asks how large this improvement could\nbe when one common mean and the stated error conditions hold. It does\nnot ask whether adding parameters improves the observed fit at all.\n\nWrite $\\mu_S$, $\\mu_I$ and $\\mu_L$ for the model means of Silence,\nInstrumental music and Music with lyrics. The omnibus null hypothesis is\n$H_0:\\mu_S=\\mu_I=\\mu_L$; the alternative says that at least two of these\nmeans differ. Judging whether 6.0674 is large needs the distribution\nthat the statistic would follow if the null were true.\n\nThree conditions support this reference distribution;\n@fig-ch04-model draws the last two. **Independent observations**: one student's\ndeparture from a group mean carries no information about another\nstudent's departure. Here that rests on the design (Section 1.2), with\nstudents individually assigned, each reading in an individual session\nand scored once; no display of the scores can establish it.\n**Approximately Normal errors**: the departures around each group mean,\nnot the pooled mixture of all thirty scores, have a roughly Normal\nshape. **A common variance**: one error variance $\\sigma^2$ describes\nevery group, which is what allows $MS_W$ to pool the three group\nvariances. In model shorthand, the errors $\\varepsilon_{ij}$ are\nindependent Normal with mean zero and common variance $\\sigma^2$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The one-way model for the background-sound study: the scores of each condition vary Normally around that condition's model mean, with one spread common to all three. The curves are drawn at the observed means 12, 10 and 8 with the common SD estimated by the square root of the within-group mean square, 2.5676.](chapter_04_files/figure-html/fig-ch04-model-1.png){#fig-ch04-model fig-pos='!ht' fig-alt='Three bell-shaped Normal curves of identical width on a comprehension-score axis from 0 to 20, centred at 8 for Music with lyrics, 10 for Instrumental music and 12 for Silence, each marked at its centre by a dotted line, with a legend naming the three conditions; the curves overlap widely.' width=100%}\n:::\n:::\n\n\nUnder the null, both mean squares estimate the same error variance, so\ntheir ratio tends to lie near 1; the numerator also grows with the\nseparation of the model means, so a large ratio is evidence against\nequality. Under the three conditions and the null, F follows an\n**F distribution**, one of a family of right-skewed distributions on\npositive values, each indexed by its two df, numerator first: here\n$F(2,27)$. The left panel of @fig-ch04-f-reference shows three members\nof the family and marks each one's 5% point, the value beyond which 5%\nof the distribution lies. With few denominator df, as in $F(2,8)$, the\nerror variance is poorly estimated and large ratios occur more often by\nchance: its curve looks much like that of $F(2,27)$, but its heavier\ntail moves the 5% point from 3.3541 to 4.4590. With more numerator df,\nas in $F(5,27)$, the distribution gathers near 1 and its 5% point falls\nto 2.5719.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![F distributions and the one-way statistic. Left: three F distributions, each indexed by its numerator and denominator df; a vertical mark in each curve's colour and line type, labelled with its value, shows the point beyond which 5% of that distribution lies. Right: the right tail of F(2, 27), enlarged. The shaded areas together are the .05 beyond the critical value 3.3541; the dark area beyond the observed statistic 6.0674 is the p-value, .0067.](chapter_04_files/figure-html/fig-ch04-f-reference-1.png){#fig-ch04-f-reference fig-pos='!ht' fig-alt='Left panel, titled F distributions and 5% points: three right-skewed density curves over F values from 0 to 6. F(2, 27) and F(2, 8) both start near 1 at zero and decline almost together, F(2, 8) with a slightly heavier right tail; F(5, 27) rises from zero to a peak of about 0.73 near 0.6 and then declines. A labelled vertical mark in each curve\\'s colour and line type stands at its 5% point: 2.5719 for F(5, 27), 3.3541 for F(2, 27) and 4.4590 for F(2, 8), so the heavier tail of F(2, 8) shows as a mark further to the right. Right panel: the F(2, 27) density from 2 to 9 on a vertical scale enlarged to 0.10. A dotted line marks the critical value 3.3541 and the area to its right is shaded light grey; a dashed line marks the observed F = 6.0674, and the dark area to its right is labelled p = .0067.' width=100%}\n:::\n:::\n\n\nThe dark area in the right panel of @fig-ch04-f-reference, .0067, is\nread in the same way as the tail areas and p-values of Chapter 3,\nSection 4. Only the right tail counts, because greater separation of the\nmeans produces a larger ratio. Under the null and the model conditions,\na ratio at least as large as 6.0674 occurs with that probability. The\nobserved F lies beyond the critical value 3.3541, so at a prespecified\n.05 significance level the equality null is rejected; comparing F with\nthe critical value and comparing p with .05 give the same decision. This\nis evidence about the three-mean pattern, not a probability that the\nnull is true and not an identification of which particular comparisons\ndiffer.\n\nThe box below states, in the four lines used since Chapter 3, what this\nF test addresses, what it rests on, what the data can check and what the\nresult supports.\n\n[]{#ch04-justify-oneway}\n\n::: {.callout-tip title=\"Justifying the analysis\"}\n- **Target:** whether the model means of the three sound conditions,\n  $\\mu_S$, $\\mu_I$ and $\\mu_L$, are all equal for the thirty students of\n  the background-sound study, on the 0--20 comprehension scale; the\n  observed means 12, 10 and 8 estimate them.\n- **Conditions:**\n  - *Secured by design:* individual random assignment, ten students to\n    each condition, and one score per student from an individual\n    session, so the scores are independent and a difference among the\n    means reads as an effect of sound among these students, not in a\n    wider population (Sections 1.2 and 2.3).\n  - *Model assumptions:* Normal errors with one common variance (Section\n    2.3), estimated by $MS_W=6.5926$ on 27 df.\n  - *Choices and defaults:* all thirty students, none missing; a .05\n    level fixed in advance; the right tail of $F(2,27)$; the classical\n    calibration that pools the group variances.\n- **Check:** the group SDs, 2.7080, 2.4037 and 2.5820, are similar, the\n  largest 1.1266 times the smallest, with ten students in each group,\n  and the boxplots show no outlying score; markedly unequal SDs would\n  call for Welch's one-way ANOVA, chosen in advance (Section 5.2). Ten\n  scores per group say little about shape, and independence rests on\n  the design.\n- **Bound:** $F(2,27)=6.0674$, $p=.0067$ is evidence at the .05 level\n  against equal means for these thirty students under the model. It\n  does not say which means differ or by how much (Section 3), and,\n  with invented scores, says nothing about real studying.\n:::\n\nWith equal group sizes $n$, the numerator of F shows directly what the\nstatistic compares:\n\n$$\nF=\\frac{n\\sum_{j=1}^J(\\bar y_j-\\bar y)^2/(J-1)}{MS_W}.\n$$\n\nThree quantities move it, the same three that moved Chapter 3's t\nstatistic (Section 4.4): the separation of the group means, the group\nsize $n$ and the within-group spread in $MS_W$.\n@tbl-ch04-what-moves-f changes one of them at a time; its second row is\nthe right panel of @fig-ch04-separation-spread.\n\n\\Needspace{11\\baselineskip}\n\n| Version of the study | $n$ | Group means | $MS_B$ | $MS_W$ | F | p |\n|:--|--:|:--|--:|--:|--:|--:|\n| The thirty invented scores | 10 | 12, 10, 8 | 40 | 6.5926 | 6.0674 | .0067 |\n| Spread doubled | 10 | 12, 10, 8 | 40 | 26.3704 | 1.5169 | .2375 |\n| Separation halved | 10 | 11, 10, 9 | 10 | 6.5926 | 1.5169 | .2375 |\n| Group size doubled | 20 | 12, 10, 8 | 80 | 6.5926 | 12.1348 | <.0001 |\n\n: What moves the F statistic: one change at a time to the background-sound study. The last three rows are constructed variations of the invented scores, not further studies; the last has 2 and 57 df, the others 2 and 27. {#tbl-ch04-what-moves-f tbl-colwidths=\"[34,7,17,11,11,11,9]\"}\n\nDoubling every distance from the group mean doubles each group's SD and\nmultiplies $MS_W$ by four; halving every mean's distance from the grand\nmean divides $MS_B$ by four. Each change alone quarters F, from 6.0674\nto 1.5169, and moves p from .0067 to .2375: F reads separation relative\nto spread, never either alone. Doubling the group size with the same\nmeans and SDs leaves every boxplot looking the same, yet doubles $MS_B$\nand so F: more students supply more information about the same pattern.\nSection 2.4 shows that eta squared barely responds to that third change.\n\n### Two groups, direction and magnitude\n\nWith two groups, $MS_W$ is Chapter 3's pooled variance $s_p^2$, so the\nclassical one-way F test and Chapter 3's **equal-variance two-sample t\ntest** (Section 5.3) share one model, one pooled variance and one\nresidual df, and $F(1,N-2)=t_{N-2}^2$. Chapter 3 labels its two groups 1\nand 0; this chapter numbers groups $j=1,\\ldots,J$, so its two-group case\nuses 1 and 2.\n\nFor Silence and Music with lyrics alone, the pooled variance is 7\non 18 df, and $t(18)=3.3806$ and $F(1,18)=11.4286=3.3806^2$ have the\nsame two-sided $p=.0033$. Squaring removes direction, so the signed\ndifference, Silence minus Music with lyrics, 4 points, carries it.\nThis matched fit reads with the [*Justifying the analysis*\nbox](chapter_03.qmd#ch03-justify-equal-variance) that Chapter 3 gave the\nequal-variance t test; only the target changes, to the\nSilence-minus-Music-with-lyrics difference for these twenty students,\nwhose SDs, 2.708 and 2.582, are similar. The two-group refit pools\n7.0000 on 18 df rather than the three-group $MS_W=6.5926$ on 27, because\nit leaves out the Instrumental group, and it answers a narrower question\nthan the three-group F: one pairwise comparison rather than the whole\npattern. [Appendix A](#app-ch04-pooled-identity) derives the identity,\nand Section 5.2 returns to groups whose spreads may differ.\n\nMagnitude begins on the comprehension scale. The observed\nInstrumental-music-minus-Silence difference is $-2$ points and the\nMusic-with-lyrics-minus-Silence difference is $-4$: two and four\nfewer items answered correctly, on average, than in silence. Whether a\ndifference of this size matters for studying needs a substantive\ncriterion, not only a p-value. One descriptive summary of the overall\nseparation is **eta squared**,\n\n$$\n\\eta^2=\\frac{SS_B}{SS_T}=\\frac{80}{258}=.3101:\n$$\n\ngroup means account for .3101 of the observed squared variation in these\nthirty records. It is the fit's share of the table's total, the quantity\nthat later chapters call the $R^2$ of a fitted model. This is a fraction\nof a sample decomposition, not the proportion of comprehension caused by\nbackground sound. Eta squared and F answer different questions: in the\nlast row of @tbl-ch04-what-moves-f, twenty students per group double F\nwhile eta squared barely moves, from .3101 to .2986, because the means\naccount for about the same share of the variation while the larger study\ngives stronger evidence that they differ. A small p-value therefore does\nnot signal a large difference. Because sample means differ even when\nmodel means are equal, eta squared slightly overstates the share in the\nmodel; omega squared adjusts for that and gives .2525 here\n([Appendix B](#app-ch04-effect-sizes)). A standardized mean difference,\nexplained in [Chapter 3, Section 7.1](chapter_03.qmd#sec-ch03-interpretation),\ndivides a difference by a stated SD; dividing it by an individual-score\nSD gives a different quantity from dividing it by the SE of that\ndifference.\n\n\\Needspace{12\\baselineskip}\n\n## Contrasts and Multiple Comparisons {#sec-ch04-contrasts}\n\n### Contrasts and their weights\n\nThe omnibus question asks whether all three model means agree. A\n**contrast** states a particular comparison as a weighted combination\nof means whose weights sum to zero:\n\n$$\nC=\\sum_{j=1}^Jc_j\\mu_j,\\qquad \\sum_{j=1}^Jc_j=0,\n\\qquad \\widehat C=\\sum_{j=1}^Jc_j\\bar y_j.\n$$\n\nThe symbol $C$ here names a contrast, and $\\widehat C$ its estimate.\nThe weights specify both the comparison and its direction.\n\nThe study plan declares two questions, each music condition against\nSilence: Instrumental music minus Silence and Music with lyrics minus\nSilence. A negative estimate means fewer items answered correctly than\nin silence. A broader question compares the equal average of the two\nmusic conditions with Silence. In the declared order Silence,\nInstrumental music, Music with lyrics, the three comparisons have these\nweights:\n\n\\Needspace{12\\baselineskip}\n\n| Comparison | Weights | Estimate |\n|:--|:--|--:|\n| Instrumental music minus Silence | $(-1,1,0)$ | $-2$ |\n| Music with lyrics minus Silence | $(-1,0,1)$ | $-4$ |\n| Equal average of the two music conditions minus Silence | $(-1,1/2,1/2)$ | $-3$ |\n\n: Three contrast meanings in the background-sound study. {#tbl-ch04-weights tbl-colwidths=\"[55,25,20]\"}\n\nOnly the first two form the declared family whose intervals Section 3.3\ncalibrates together. The third gives the two music conditions equal\nweight; its $-3$ hides that they fall 2 and 4 points below Silence, so it\ndoes not replace both separate comparisons when both are required. The\nweights also fix the scale: weights such as $(-2,1,1)$ double the\nestimate and its SE and report twice a mean difference, whereas\n$(-1,1/2,1/2)$ keeps the estimate in comprehension points. With unequal\ngroup sizes, equal weights and weights proportional to student counts\nanswer different questions ([Appendix B.1](#app-ch04-weighting)).\n\n### The standard error of a contrast\n\nThe SE of a contrast extends the two-group SE of Chapter 3,\nSection 2.2. A difference between two means is the contrast with\nweights $+1$ and $-1$, and Chapter 3's pooled SE can be written with\nthose weights visible:\n\n$$\ns_p\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_0}}\n=\\sqrt{s_p^2\\left(\\frac{1^2}{n_1}+\\frac{(-1)^2}{n_0}\\right)}.\n$$\n\nUnder the independent common-variance model, each estimated group mean\nhas variance $\\sigma^2/n_j$, and the variance of a weighted sum of\nindependent means uses the **squared weights**. Opposite signs define a\ndifference; they do not make independent sources of uncertainty cancel.\nSeveral groups make two changes to Chapter 3's form: the weights $c_j$\ncan describe any comparison, and $s_p^2$ is replaced by $MS_W$, the\nvariance pooled over all $J$ groups (Section 2.3). Then\n\n$$\n\\widehat{SE}(\\widehat C)=\n\\sqrt{MS_W\\sum_{j=1}^J\\frac{c_j^2}{n_j}}.\n$$\n\nFor each difference with Silence,\n\n$$\n\\widehat{SE}=\n\\sqrt{\\frac{178}{27}\\left(\\frac{1}{10}+\\frac{1}{10}\\right)}\n=1.1483\\text{ points}.\n$$\n\nEach contrast uses the three-group estimate 6.5926 and its 27 error df,\nalthough it uses only two of the three means: under the common-variance\nmodel all three groups estimate the same $\\sigma^2$, so pooling them\nuses more information than the two-group refit of Section 2.4, whose\n7.0000 on 18 df gives an SE of 1.1832. For the equal-average contrast,\nthe squared weights $1$, $1/4$ and $1/4$ give $\\widehat{SE}=0.9944$.\nThis smaller SE belongs to a different estimand, an average of two\nmeans compared with the reference; it does not make either separate\ncomparison more precise. The\n[NIST contrast explanation](https://www.itl.nist.gov/div898/handbook/prc/section4/prc436.htm)\ndevelops the same weighted-mean variance calculation.\n\n### Families of comparisons and the familywise error rate {#sec-ch04-families}\n\nSection 2.1 showed that several tests of one study raise the chance of\nat least one false rejection, so a reader needs to know how many\ncomparisons were made and when each was chosen. A **planned\ncomparison** is declared before the results are seen, as this study's\nplan declares each music condition against Silence. A **post hoc\ncomparison** is chosen after the results are seen, often because it\nlooks large, such as the largest of the three pairwise differences.\n[Chapter 3, Section 7.3](chapter_03.qmd#sec-ch03-selection),\nshowed that a result chosen because it looks large tends to overstate\nits target; the same selection problem arises among the several\ncomparisons of one study.\n\nEach comparison tested at level .05 has a **per-comparison error rate**,\nalso called the testwise rate, of .05: when its null hypothesis is true,\nit rejects wrongly with probability .05. A reader of the whole report,\nhowever, cares whether any of its comparisons is a false rejection. The\n**familywise error rate** is the probability of at least one Type I\nerror (Chapter 3, Section 7.2) among all the comparisons of a family.\nFor $m$ independent comparisons whose null hypotheses are all true, each\ntested at .05, it is $1-(1-.05)^m$, which @fig-ch04-familywise draws\nagainst $m$: already .1426 for three comparisons and .2262 for five.\n\nTo hold the familywise rate at .05, **Bonferroni's method** tests each\nof the $m$ comparisons at level $.05/m$, or builds each interval with\nconfidence $1-.05/m$. Its guarantee needs no independence, because the\nprobability that at least one of several events occurs is at most the\nsum of their probabilities:\n\n$$\nP(\\text{at least one false rejection})\n\\le\\sum_{k=1}^mP(\\text{false rejection }k)\n=m\\cdot\\frac{.05}{m}=.05.\n$$\n\n[]{#app-ch04-families}The lower line of @fig-ch04-familywise stays at or\nbelow .05 for every $m$. The price is width: each interval is wider and\neach comparison has less power, so a family should contain the\ncomparisons that matter rather than every comparison that could be\nmade. Bonferroni's method suits any declared set; other methods are\ncalibrated for particular families and give narrower intervals when\ntheir family fits the question (@tbl-ch04-families) [@tukey1953;\n@kutner2005].\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The familywise error rate for m hypothetical independent comparisons whose null hypotheses are all true, each tested at .05 (upper line) or at Bonferroni's .05/m (lower line).](chapter_04_files/figure-html/fig-ch04-familywise-1.png){#fig-ch04-familywise fig-pos='!ht' fig-alt='Two lines over the number of comparisons m, from 1 to 10. The upper line, each comparison tested at .05, rises from .05 at m = 1 through .0975 and .1426, marked at m = 3, and .1855 and .2262, marked at m = 5, to .4013 at m = 10. The lower line, Bonferroni\\'s allocation of .05/m to each comparison, stays just below a dotted reference line at .05 for every m.' width=100%}\n:::\n:::\n\n\n\\Needspace{16\\baselineskip}\n\n| Family of comparisons | When it fits | Method that holds the familywise rate |\n|:--|:--|:--|\n| One comparison | The plan names it in advance as the study's only question | None needed: the ordinary 95% interval, $\\widehat C\\pm t_{.975}\\,\\widehat{SE}$ |\n| A declared set of $m$ comparisons | The plan names the set before the data are seen | Bonferroni: each comparison at $.05/m$ |\n| Each group against one reference | The plan compares every condition with a control or reference condition | Dunnett's method |\n| All pairs of groups | Every pairwise difference matters, or a pair is picked after the means are seen | Tukey's method |\n| Every contrast, including averages of groups | Any comparison may be formed after the data are seen | Scheffé's method |\n\n: Families of comparisons and the methods that hold the familywise error rate for each. {#tbl-ch04-families tbl-colwidths=\"[28,42,30]\"}\n\nThe wider the family, the more comparisons its intervals must cover\ntogether, and the larger the critical value. For one difference between\ntwo sound conditions, on 27 error df, the value for a single planned\ncomparison is 2.0518 and Scheffé's value for every contrast of the three\nmeans is 2.5900; the declared pair, Tukey's all pairs and Bonferroni's\nthree pairs fall in between. The family comes from the comparisons for\nwhich coverage is owed, fixed before looking at which interval excludes\nzero. An omnibus rejection is not required before a planned comparison,\nand it does not by itself protect comparisons chosen afterward.\n\nThe study plan declares two comparisons, each music condition against\nSilence, so the family is that pair, and Bonferroni gives each interval\n97.5% confidence, with .0125 in each tail: the critical value is\n$t_{.9875;27}=2.3734$. @tbl-ch04-contrasts gives the two intervals,\n$\\widehat C\\pm2.3734\\,\\widehat{SE}$. Both estimates use the Silence\nmean, a dependence that the union bound allows\n([Appendix B.3](#app-ch04-dependence)).\n\n\\Needspace{10\\baselineskip}\n\n| Comparison | Estimate | SE | Family lower | Family upper |\n|:--|--:|--:|--:|--:|\n| Instrumental music minus Silence | $-2$ | 1.1483 | $-4.7253$ | 0.7253 |\n| Music with lyrics minus Silence | $-4$ | 1.1483 | $-6.7253$ | $-1.2747$ |\n\n: Bonferroni 95% simultaneous intervals for the two declared comparisons with Silence. {#tbl-ch04-contrasts tbl-colwidths=\"[36,16,16,16,16]\"}\n\n[]{#ch04-justify-contrasts}These intervals read with the\n[one-way box](#ch04-justify-oneway) of Section 2.3, with three changes.\nThe target becomes two contrasts in comprehension points, $\\mu_I-\\mu_S$\nand $\\mu_L-\\mu_S$, rather than the equality of all three means; the\nchoices add the declared family and Bonferroni's calibration, fixed\nbefore the scores were seen, which only the analysis record can confirm;\nand the bound belongs to this declared pair, not to comparisons chosen\nafter the means were inspected.\n\nThe omnibus F and these intervals answer different questions. The F\ntest says that the three model means are not all equal; the intervals\nsay which declared differences are established and how large they may\nbe. Jointly, Music with lyrics minus Silence is negative, between\n$-6.7253$ and $-1.2747$ points. The Instrumental-music interval,\n$[-4.7253,0.7253]$, includes zero: it is compatible with a small\nbenefit, no difference or a loss of several points, so it establishes\nno equivalence, which would need a declared margin and an analysis\ndesigned for it. These are calculations for invented scores, not a\nfinding about studying with music.\n\n## Multi-Way (Factorial) ANOVA {#sec-ch04-two-way}\n\nAnalysis of variance with two or more crossed factors is **multi-way**,\nor **factorial**, ANOVA; this section works the two-way case in full\nwith the feedback-by-practice study and closes, in Section 4.7, with a\nworked three-way analysis and the structure of four-way designs.\n\n### The two-way design and what interaction means {#sec-ch04-interaction-idea}\n\nIn the feedback-by-practice study, twenty-four students study the same\nfractions material and complete a common 20-item quiz one week after\ntheir final practice. *Rereading* offers the worked material again;\n*Answer feedback* supplies the correct answer after an attempt;\n*Explanatory feedback* supplies the answer with a worked explanation.\n*Massed* practice occurs in one session and *Spaced* practice in two\nshorter sessions with the same total practice time. Random allocation\nplaces four different students in each combination of feedback and\npractice (@tbl-ch04-feedback-scores).\n\n\\Needspace{10\\baselineskip}\n\n| Feedback condition | Massed practice | Spaced practice |\n|:--|:--|:--|\n| Rereading | 4, 5, 7, 8 | 4, 5, 7, 8 |\n| Answer feedback | 6, 7, 9, 10 | 10, 11, 13, 14 |\n| Explanatory feedback | 8, 9, 11, 12 | 16, 17, 19, 20 |\n\n: Invented fractions-quiz scores, four different students per cell, on a 0--20 scale. {#tbl-ch04-feedback-scores tbl-colwidths=\"[38,31,31]\"}\n\nA **cell** contains the cases that share one level of each factor;\nAnswer feedback with Spaced practice is one cell. Crossing three\nfeedback levels with two practice levels gives six cells, and four\nstudents in every cell make the layout **balanced**, as ten students\nper condition balance the one-way layout. Each score belongs to a\ndifferent student, the stipulated assignment and measurement unit: the\nfour scores of a cell are not repeated measurements, and the Massed and\nSpaced scores are not paired. Each cell's scores lie 2 and 1 points\nbelow and above its mean, a repeated pattern that simplifies the\narithmetic; it is a teaching construction, not evidence of Normal\nerrors, equal variances or an educational effect. The course data file\n`feedback_practice.csv` holds the same scores in one row per student,\nwith columns `student`, `feedback`, `practice` and `score`, ordered by\nfeedback, then practice, then student.\n\nA two-way ANOVA compares a numerical score across combinations of two\nfactors. Chapter 3's two-way frequency table (Section 6) instead counts\ncases in combinations of two categorical variables: *two-way* describes\na layout, not a shared statistical test.\n\nTwo factors **interact** when the effect of one factor differs across\nthe levels of the other. Here is one invented illustration, outside the\nchapter's two studies. Suppose a short vocabulary preview is given\nbefore a reading passage, and that students are also grouped by whether\nthey began with weak or strong vocabulary. The preview raises\ncomprehension scores substantially for the students who began weak, and\nbarely changes them for the students who began strong. The effect of the\npreview *depends on* prior vocabulary: that dependence is the\ninteraction. Describing only an average preview effect would tell a\nreader that the preview helps somewhat, and would conceal that it helps\none group a great deal and the other hardly at all.\n\nStudying two factors together in one crossed design has three\nadvantages over running two separate one-factor studies.\n\n1. **It is more efficient.** Every student contributes to both factor\n   comparisons at once, because the levels of one factor are spread\n   across the levels of the other. A crossed design therefore needs\n   fewer cases per condition than a series of separate one-factor\n   studies aimed at the same comparisons.\n2. **It reduces residual variation.** A second factor that influences\n   the outcome moves variation out of the error term and into the fit.\n   Section 4.4 shows what leaving practice out does to these scores.\n3. **It makes interaction examinable.** Only a crossed design supports\n   the question of whether a comparison changes across the other\n   factor's levels. A series of one-factor studies supplies no\n   estimate of that change, however carefully each one is run.\n\nPractice schedule therefore gives each feedback comparison a context.\nWe can compare feedback conditions within Massed practice, within Spaced\npractice, or after averaging over the two schedules, and these are\ndistinct quantities. A **main effect** compares one factor's levels\nafter averaging across the other factor with stated weights. A\n**simple effect** makes the comparison at a specified level of the\nother factor. **Interaction** means that a comparison changes across\nthose levels.\n\n### Main effects and interaction through graphs\n\nIn a two-factor design either main effect, the interaction, or any\ncombination of the three can be present. Six schematic two-by-two\npatterns make the whole range visible before we return to the full\nthree-by-two data. Each line in @fig-ch04-interaction-patterns is one\nlevel of a two-level feedback factor, Feedback 1 or Feedback 2; the\nhorizontal positions are Massed and Spaced practice. These are\nmean-only drawings, not additional observed studies, and they carry no\nsignificance claim.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Six schematic patterns of cell means, covering the whole range of main-effect and interaction combinations. The two lines are two levels of a feedback factor; the drawings illustrate averages and changing differences, without significance claims.](chapter_04_files/figure-html/fig-ch04-interaction-patterns-1.png){#fig-ch04-interaction-patterns fig-pos='!ht' fig-alt='Six panels. No effects: Feedback 1 and Feedback 2 coincide as one flat line at 10. One main effect: two separated flat lines at 8 and 12. Two main effects: parallel rising lines. Interaction only: crossing lines with equal marginal means. Interaction qualifies: both lines rise from 8, Feedback 2 more steeply. Interaction reverses: Feedback 1 rises from 8 to 10 while Feedback 2 falls from 16 to 10.' width=100%}\n:::\n:::\n\n\nRead each pattern by taking differences, not only by recognizing a\nshape. Define a schedule difference as Spaced minus Massed and a\ndifference of differences as Feedback 2's schedule difference minus\nFeedback 1's.\n\n\\Needspace{16\\baselineskip}\n\n| Pattern | Feedback 1: Massed, Spaced | Feedback 2: Massed, Spaced | Schedule differences 1, 2 | Difference of differences |\n|:--|:--|:--|:--|--:|\n| No effects | 10, 10 | 10, 10 | 0, 0 | 0 |\n| One main effect | 8, 8 | 12, 12 | 0, 0 | 0 |\n| Two main effects | 8, 10 | 12, 14 | 2, 2 | 0 |\n| Interaction only | 8, 14 | 14, 8 | 6, $-6$ | $-12$ |\n| Interaction qualifies | 8, 10 | 8, 14 | 2, 6 | 4 |\n| Interaction reverses | 8, 10 | 16, 10 | 2, $-6$ | $-8$ |\n\n: Arithmetic behind the six schematic patterns. {#tbl-ch04-patterns tbl-colwidths=\"[25,19,19,19,18]\"}\n\nThe first three panels have a zero difference of differences. Nothing\nvaries in the first; in the second, Feedback 2 exceeds Feedback 1 by 4\npoints under either schedule, one main effect; in the third, Spaced\nalso exceeds Massed by 2 points everywhere, two main effects. Parallel\nlines express those constant comparisons.\n\nThe last three panels have a nonzero difference of differences. In\nthe crossing panel, both feedback marginal means are 11 and both\npractice marginal means are 11 when cells receive equal weight. Both\naveraged comparisons are zero despite large conditional differences,\nwhich is why a small main effect need not mean that a factor is\nirrelevant at every level of another factor.\n\nIn the qualifying panel the schedule comparison is 2 for Feedback 1 and\n6 for Feedback 2. Both are positive, so the averaged 4-point schedule\ncomparison points the right way for both feedback levels but describes\nneither exactly. The lines need not cross for interaction to be\npresent. In the reversing panel the schedule comparison is 2 for\nFeedback 1 and $-6$ for Feedback 2, so the averaged comparison of $-2$\npoints the wrong way for Feedback 1. Reporting only the two main effects\nwould then mislead a reader about every conditional comparison. Examine\nthe interaction first, and read a main effect as an average whose parts\nare still visible. These drawings establish only the numerical\npatterns: significance also needs information about variation, sample\nsize and the reference distribution.\n\n### Cells, marginal means and the full data\n\nTurn to the six cells of the feedback-by-practice study, whose units\nSection 4.1 described: this analysis uses six separate groups of four,\nwhere the background-sound analysis used three groups of ten.\n\nWrite $\\bar y_{jk}$ for a cell mean, with $j=1,2,3$ indexing feedback\nand $k=1,2$ indexing practice. A dot replaces an index that has been\naveraged over: $\\bar y_{j\\cdot}$ averages a feedback level over\npractice, and $\\bar y_{\\cdot k}$ averages a practice level over\nfeedback. An **effect** in this layout is a marginal mean's departure\nfrom the grand mean, 10. @tbl-ch04-cell-means gives the cell means, the\nequally weighted marginal means and the effects.\n\n\\Needspace{15\\baselineskip}\n\n| Feedback | Massed | Spaced | Feedback mean | Feedback effect |\n|:--|--:|--:|--:|--:|\n| Rereading | 6 | 6 | 6 | $-4$ |\n| Answer feedback | 8 | 12 | 10 | 0 |\n| Explanatory feedback | 10 | 18 | 14 | 4 |\n| Practice mean | 8 | 12 | Grand mean 10 | |\n| Practice effect | $-2$ | 2 | | |\n\n: Cell means, equally weighted marginal means and effects for the complete invented study. {#tbl-ch04-cell-means tbl-colwidths=\"[27,13,13,26,21]\"}\n\nEach marginal mean averages its cell means with equal weights; with four\nstudents in every cell it is also the mean of that condition's students.\nThe feedback effects, $-4$, 0 and 4, and the practice effects, $-2$ and\n2, each sum to zero. The practice comparison, Spaced minus Massed,\naverages 4 points over the three feedback conditions, but its\ncomponents, the schedule differences within the rows, are 0,\n4 and 8. A four-point main effect is therefore a meaningful\nstated average that describes none of the conditional comparisons except\nAnswer feedback's.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Quiz cell means across practice schedules in the full 3 × 2 example. Each line joins means of different students; the schedule differences are 0, 4 and 8 points.](chapter_04_files/figure-html/fig-ch04-cell-means-1.png){#fig-ch04-cell-means fig-pos='!ht' fig-alt='Rereading stays at 6 from Massed to Spaced practice. Answer feedback rises from 8 to 12. Explanatory feedback rises from 10 to 18. The nonparallel lines show that the schedule comparison changes across feedback conditions.' width=100%}\n:::\n:::\n\n\nThe connected lines in @fig-ch04-cell-means organize cell means. They\ndo not show individual students moving from one condition to another.\nThe nonparallel pattern describes interaction in the observed means;\nthe full model supplies the uncertainty calculation for an inferential\nclaim.\n\n### Additivity and the full model {#sec-ch04-full-model}\n\nIf feedback and practice combined additively, every cell mean would be\nthe grand mean plus its feedback effect plus its practice effect, and\nthe schedule difference would be the same in every row.\n@tbl-ch04-interaction-departures sets these **additive predictions**\nbeside the observed cell means. The difference between an observed cell\nmean and its additive prediction is an **interaction departure**.\n\n\\Needspace{12\\baselineskip}\n\n| Cell | Observed mean | Additive prediction | Interaction departure |\n|:--|--:|--:|--:|\n| Rereading, Massed | 6 | 4 | 2 |\n| Rereading, Spaced | 6 | 8 | $-2$ |\n| Answer feedback, Massed | 8 | 8 | 0 |\n| Answer feedback, Spaced | 12 | 12 | 0 |\n| Explanatory feedback, Massed | 10 | 12 | $-2$ |\n| Explanatory feedback, Spaced | 18 | 16 | 2 |\n\n: Observed cell means, additive predictions from the grand mean and both effects, and interaction departures. {#tbl-ch04-interaction-departures tbl-colwidths=\"[37,19,22,22]\"}\n\nAnswer feedback's two cells sit exactly on their predictions, but the\nother four do not: Rereading gains less from spacing than the average,\nand Explanatory feedback more, by 2 points in each cell. Agreement in\none row does not make the whole layout additive.\n\nThe full mean model includes such departures:\n\n$$\nY_{ijk}=\\mu+\\alpha_j+\\beta_k+(\\alpha\\beta)_{jk}\n        +\\varepsilon_{ijk}.\n$$\n\nHere $i=1,\\ldots,4$ identifies a student within a cell, $j=1,2,3$\nidentifies feedback and $k=1,2$ identifies practice. The grand model\nmean is $\\mu$; $\\alpha_j$ and $\\beta_k$ are the factor effects;\n$(\\alpha\\beta)_{jk}$ is the interaction departure; and\n$\\varepsilon_{ijk}$ is the individual error around the cell mean.\nThese indexed effects are distinct from the unindexed error\nprobabilities $\\alpha$ and $\\beta$ used in hypothesis testing.\n\nIn the balanced decomposition, main effects sum to zero, and\ninteraction departures sum to zero along each row and each column, so\nthey carry only the pattern left after the two main effects. With two\ncolumns, a row's second departure is the negative of its first, and the\nthree first-column departures, 2, 0 and $-2$, sum to zero, so only two\nof them are free. Thus the interaction has $(3-1)(2-1)=2$ df. It\ndescribes a two-dimensional pattern, rather than one particular\nfour-cell difference.\n\n[]{#app-ch04-two-way-arithmetic}Each score's distance from the grand\nmean now splits into four parts, a feedback effect, a practice effect,\nan interaction departure and the student's residual. Squaring the parts\nand adding over all 24 students gives, in this balanced layout as in\nSection 2.2, four sums of squares with matching df:\n\n$$\nSS_T=SS_A+SS_B+SS_{AB}+SS_E,\\qquad\ndf_T=df_A+df_B+df_{AB}+df_E.\n$$\n\nIn this two-way table A denotes feedback and B practice, so $SS_B$ now\nmeans the practice component, not the between-group component of the\none-way table, and $SS_E$ is the within-cell error:\n\n$$\n\\begin{aligned}\nSS_A&=2n\\sum_j(\\bar y_{j\\cdot}-\\bar y)^2=256,\\\\\nSS_B&=3n\\sum_k(\\bar y_{\\cdot k}-\\bar y)^2=96,\\\\\nSS_{AB}&=n\\sum_j\\sum_k\n (\\bar y_{jk}-\\bar y_{j\\cdot}-\\bar y_{\\cdot k}+\\bar y)^2\n =64,\\\\\nSS_E&=\\sum_j\\sum_k\\sum_i(y_{ijk}-\\bar y_{jk})^2=60.\n\\end{aligned}\n$$\n\nEach component counts its effects or departures once for every student\nwho shares them. The partition reads\n$476=256+96+64+60$ on $23=2+1+2+18$ df: each of\nthe six cells uses one mean, so the error has $24-6=18$ df, and the fit\npart is $256+96+64=416$ on five df.\n\n\\Needspace{14\\baselineskip}\n\n| Source | SS | df | MS | F | p |\n|:--|--:|--:|--:|--:|--:|\n| Feedback (A) | 256 | 2 | 128.0000 | 38.4 | <.0001 |\n| Practice (B) | 96 | 1 | 96.0000 | 28.8 | <.0001 |\n| A × B | 64 | 2 | 32.0000 | 9.6 | .0015 |\n| Within cells | 60 | 18 | 3.3333 | | |\n| Total | 476 | 23 | | | |\n\n: Full two-way ANOVA using all 24 students. {#tbl-ch04-two-way-anova}\n\nRead this table as in [Section 2.3](#sec-ch04-anova-table): the three\nsource rows are the fit, the within-cells row the residual and the total the\ndata, and the sums of squares and df add across the rows. Read the\ninteraction row first, because it decides how the two main-effect rows\ncan be read.\n\n\\Needspace{11\\baselineskip}\n\n| Fitted mean model | Comparison it allows | Residual SS | Residual df |\n|:--|:--|--:|--:|\n| Additive: four mean parameters | One practice difference shared by all feedback conditions | 124 | 20 |\n| Full: six cell means | A separate practice difference in each feedback condition | 60 | 18 |\n\n: Two mean models fitted to the same twenty-four students. {#tbl-ch04-factorial-models tbl-colwidths=\"[28,42,15,15]\"}\n\nThis comparison repeats the logic of Section 2.3. The additive model\nrestricts all three practice differences to be equal. The full model\nrelaxes those restrictions, using two more mean parameters. The\nresulting reduction in residual SS, 64, is the interaction SS; its\nmean square is 32, compared with the full model's residual mean square\nof 3.3333. That is the interaction F of 9.6. The two extra df count\ndepartures from a common practice difference, rather than two\nadditional groups of students. Both models use the same outcomes and\nobservations. The full model supplies the denominator, so unexplained\ninteraction is not put back into the error estimate used to test it.\n\nThe within-cells row of @tbl-ch04-two-way-anova holds only the variation of\nstudents around their own cell means. @fig-ch04-ignore-practice shows\nwhat happens to that row if practice is left out of the model, so that\neach feedback condition becomes one group of eight students. This is\nnot an analysis the design calls for; it shows what the second factor\nremoves from the error term.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The 24 feedback-by-practice scores analysed two ways. Left: practice is left out, so each feedback condition is one group of eight; filled circles mark Massed and triangles Spaced students. Right: the six cells of the full model, with a bar at each cell mean. Leaving practice out moves the practice and interaction variation into the within-group term.](chapter_04_files/figure-html/fig-ch04-ignore-practice-1.png){#fig-ch04-ignore-practice fig-pos='!ht' fig-alt='Two panels on a 0 to 20 quiz-score axis. Left: three boxplots of eight scores each. Rereading runs from 4 to 8, its Massed and Spaced scores identical; Answer feedback runs from 6 to 14; Explanatory feedback runs from 8 to 20, its Massed scores 8 to 12 and Spaced scores 16 to 20 forming two clusters. Beneath it: within-group MS 10.4762 on 21 df, feedback F(2, 21) = 12.2182. Right: the same scores in six cells of four, each spanning four points around its cell mean: 6 and 6 for Rereading, 8 and 12 for Answer feedback, 10 and 18 for Explanatory feedback, Massed then Spaced. Beneath it: within-cell MS 3.3333 on 18 df, feedback F(2, 18) = 38.4.' width=100%}\n:::\n:::\n\n\nLeaving practice out changes neither the feedback means, 6, 10 and 14,\nnor the feedback sum of squares, 256; it changes the error term. The\npractice and interaction components stay inside the within-group\nvariation, which becomes $220=60+96+64$ on 21 df, so the within-group\nmean square, 10.4762, is more than three times the full model's 3.3333,\nand the feedback F falls from 38.4000 to 12.2182, $p=.0003$. The left\npanel shows where the extra variation comes from: each group mixes two\nschedules, so the Explanatory group splits into two clusters eight\npoints apart and its SD, 4.5981, is 2.7203 times Rereading's 1.6903,\nwhose two schedules do not differ. One pooled variance would\nmisdescribe all three groups. A factor that influences the outcome\nbelongs in the model, which is the second advantage of a crossed design\nin Section 4.1.\n\nEvery displayed F divides its source mean square by the same\n$MS_E=60/18=10/3$. The corresponding null hypotheses address\ndifferent features of the model:\n\n\\Needspace{12\\baselineskip}\n\n| Source | Null hypothesis | Comparison represented |\n|:--|:--|:--|\n| Feedback | $\\mu_{R\\cdot}=\\mu_{A\\cdot}=\\mu_{E\\cdot}$ | Equal feedback means, each averaging the two schedules equally |\n| Practice | $\\mu_{\\cdot M}=\\mu_{\\cdot S}$ | Equal schedule means, each averaging the three feedback levels equally |\n| Interaction | $(\\alpha\\beta)_{jk}=0$ for every cell | Each feedback comparison is constant across schedules, equivalently each schedule difference is the same across feedback levels |\n\n: Three null hypotheses with their averaging rules. {#tbl-ch04-factorial-nulls tbl-colwidths=\"[17,37,46]\"}\n\nUnder the conditions of Section 2.3, now applied to the six cells, the\ninteraction result $F(2,18)=9.6$, $p=.0015$, gives evidence against an\nadditive pattern. Both main effects also have small p-values, but they\nremain averaged comparisons; reading them as “each factor works equally\nwell everywhere” would discard the interaction.\n\nThe clean component decomposition uses the balanced layout. With\nunequal cell counts, the averaging target and the model comparison\nneed more care; different software sums of squares can address\ndifferent hypotheses. The [weighting reference](#app-ch04-weighting)\nexplains the first distinction without changing these data.\n\n\\Needspace{28\\baselineskip}\n\n[]{#ch04-justify-factorial}\n\n::: {.callout-tip title=\"Justifying the analysis\"}\n- **Target:** the six cell means $\\mu_{jk}$ of the feedback-by-practice\n  layout for the 24 students, in quiz points. The three F tests ask\n  whether the equally weighted feedback means are equal, whether the two\n  equally weighted practice means are equal, and whether every\n  interaction departure is zero.\n- **Conditions:**\n  - *Secured by design:* individual random assignment to the six cells,\n    four different students in each, one score per student (Section\n    4.1; independence as in Section 2.3).\n  - *Model assumptions:* Normal errors with one common variance in every\n    cell (Section 2.3), estimated by $MS_E=3.3333$ on 18 df. The model\n    includes the interaction, so it does not assume additivity; reading\n    a main effect as the effect at every level would.\n  - *Choices and defaults:* the full model with interaction; equal cell\n    weights for the marginal means; a .05 level fixed in advance; with\n    four students in every cell, every sums-of-squares convention gives\n    the same table.\n- **Check:** every cell has residuals $-2$, $-1$, 1 and 2, so the six\n  spreads agree by construction; residuals fanning out as the fitted\n  mean grows would question the common variance, and four scores per\n  cell say little about shape. The interaction row, $F(2,18)=9.6$,\n  $p=.0015$, with the cell-mean plot, shows that additivity fails for\n  these scores.\n- **Bound:** under the model, the evidence is against an additive\n  pattern. The main effects, $F(2,18)=38.4$ and $F(1,18)=28.8$, both\n  $p<.0001$, describe equally weighted averages; the schedule\n  differences within the three feedback conditions, 0, 4 and 8 points,\n  show what those averages conceal. The scores are invented, so the\n  result describes a calculation, not an educational finding.\n:::\n\n### Simple effects and a declared interaction contrast\n\nThe Answer-feedback schedule comparison, Spaced minus Massed, is a\n**simple effect**: $12-8=4$ points. Under the full model its SE is\n$\\sqrt{(10/3)(1/4+1/4)}=1.291$, and with 18 error df a pointwise 95%\ninterval is $[1.2877,6.7123]$. The two means come from different\nstudents, so this is an independent-cell calculation, not a paired one.\n\nThe study plan also declared one interaction comparison before any\nscores were seen: whether spacing helps more under Answer feedback\nthan under Rereading. In model means the target is\n\n$$\nC=(\\mu_{A,S}-\\mu_{A,M})-(\\mu_{R,S}-\\mu_{R,M}),\n$$\n\none **difference of differences**, estimated as $(12-8)-(6-6)=4$.\nIts four cell means come from different students and carry weights 1,\n$-1$, $-1$ and 1, so squaring the weights gives\n$\\widehat{SE}(\\widehat C)=\\sqrt{(10/3)(1/4+1/4+1/4+1/4)}=1.8257$.\nDeclared in advance as the study's one interaction question, the\ncontrast is a family of one, so its 95% interval uses the ordinary\nmultiplier $t_{.975;18}=2.1009$ and is $[0.1643,7.8357]$. It excludes\nzero: under the model, spacing helps more under Answer feedback than\nunder Rereading, by between 0.1643 and 7.8357 quiz points. This interval\nreads with the [factorial box](#ch04-justify-factorial) of Section 4.4,\nwith two changes: the target becomes this one contrast of four cell\nmeans, and the choices add its declaration before the scores were seen.\n\nAs in Section 3.3, the history of the comparison sets its family. The\ninteraction test, $F(2,18)=9.6$, $p=.0015$, says that some departure\nfrom additivity exists but not which one, and had this contrast been\npicked after inspecting the plot, its interval would need a family that\ncovers every comparison the plot could have suggested, with a larger\nmultiplier than 2.1009. Each interval here likewise covers its one\nstated comparison, not every simple effect or contrast a reader might\ninspect afterward.\n\n### A connected interpretation\n\nThree rules order the reading of a factorial result: plot the cell\nmeans first; examine the interaction before the main effects; and when\nan interaction is present, report the cell means and conditional\ncomparisons, reading each main effect as a stated average. Applied to\nthis study, the schedule differences are 0, 4 and 8 quiz points for\nRereading, Answer feedback and Explanatory feedback; the interaction\ntest gives $F(2,18)=9.6$, $p=.0015$, under the stated conditions; and\nthe declared Answer-versus-Rereading difference of schedule differences\nis 4 points, with 95% interval $[0.1643,7.8357]$. The feedback and\npractice marginal means summarize explicit equal weights, and the cell\nmeans show what those averages conceal.\n\nThese conclusions use the 24 students of the feedback-by-practice study\nand 18 error df, whereas the one-way conclusions of Sections 2 and 3\nconcern the background-sound study. They are analyses of invented data,\nnot evidence that a teaching method succeeds in a population of\nstudents.\n\n### Three and four factors {#sec-ch04-multiway}\n\nThe students of Section 4.1 took their quiz one week after their final\npractice. Suppose the study had also allocated 24 further students in\nthe same way, four to each feedback-by-practice cell, and quizzed them\nright after their final practice. With quiz timing as a third crossed\nfactor, the 48 students fill twelve cells, a $3\\times2\\times2$ three-way\nlayout with four different students in each; we take all 48 to have been\nrandomly allocated. The added cell means are Rereading 9 (Massed) and 11\n(Spaced), Answer feedback 12 and 14, and Explanatory feedback 16 and 18;\neach added cell's four scores lie at its mean minus 2, minus 1, plus 1\nand plus 2, the pattern of Section 4.1. The course data file\n`feedback_practice_timing.csv` holds all 48 scores, with columns\n`student`, `feedback`, `practice`, `timing` and `score`: students 1--24\nare the one-week students of `feedback_practice.csv`, and students\n25--48 were quizzed right after practice. @fig-ch04-three-way draws the\ncell means for the two timings.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Cell means of the three-way study. Each panel is the feedback-by-practice plot for one quiz timing, with each line joining means of different students. Right after practice the lines are parallel, so Answer's schedule difference minus Rereading's is 0; one week later they fan out, and the same difference of differences is 4. That change across timing is a three-way interaction.](chapter_04_files/figure-html/fig-ch04-three-way-1.png){#fig-ch04-three-way fig-pos='!ht' fig-alt='Two panels of cell means on a 0 to 20 quiz-score axis, with practice schedule on the horizontal axis and one line per feedback condition. Left panel, quiz right after practice: Rereading rises from 9 to 11, Answer feedback from 12 to 14 and Explanatory feedback from 16 to 18, three parallel lines; beneath it, Spaced minus Massed: 2, 2 and 2. Right panel, quiz one week later: Rereading stays at 6, Answer feedback rises from 8 to 12 and Explanatory feedback from 10 to 18, so the lines fan out; beneath it, Spaced minus Massed: 0, 4 and 8.' width=100%}\n:::\n:::\n\n\nRead each panel as @fig-ch04-cell-means was read. Right after practice\nthe three lines are parallel: spacing adds 2 points under every kind of\nfeedback, so Answer's schedule difference minus Rereading's is\n$2-2=0$, and this panel shows no two-way interaction. One week later\nthe lines fan out: spacing adds 0, 4 and 8 points, and the same\ndifference of differences is $4-0=4$. The feedback-by-practice\ninteraction therefore differs between the two timings, and that change\nis a **three-way interaction**: a two-way pattern that changes across\nthe levels of a third factor. One three-way contrast is the change in\nthe difference of differences, $4-0=4$ points, a difference of\ndifferences of differences.\n\nThe three-way model adds to the two-way model of Section 4.4 a timing\neffect and every interaction that contains timing. With $l$ indexing\ntiming,\n\n$$\nY_{ijkl}=\\mu+\\alpha_j+\\beta_k+\\gamma_l+(\\alpha\\beta)_{jk}\n+(\\alpha\\gamma)_{jl}+(\\beta\\gamma)_{kl}+(\\alpha\\beta\\gamma)_{jkl}\n+\\varepsilon_{ijkl},\n$$\n\nand each set of effects becomes one row of the ANOVA table.\n@tbl-ch04-two-three-way sets the two-way analysis of the 24 one-week\nstudents beside the three-way analysis of all 48, with A for feedback and B\nfor practice, as in Section 4.4, and C for timing.\n\n\\Needspace{16\\baselineskip}\n\n+------------------+----------------------+------------------------------------------------+\n| Source           | Two-way table        | Three-way table                                |\n|                  +------+-------+-------+------+-----------+-----------+-------+---------+\n|                  | df   | SS    | F     | df   | SS        | MS        | F     | p       |\n+:=================+:====:+======:+======:+:====:+==========:+==========:+======:+========:+\n| Feedback (A)     | 2    | 256   | 38.4  | 2    | 450.6667  | 225.3333  | 67.6  | <.0001  |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| Practice (B)     | 1    | 96    | 28.8  | 1    | 108.0000  | 108.0000  | 32.4  | <.0001  |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| Timing (C)       | —    | —     | —     | 1    | 133.3333  | 133.3333  | 40.0  | <.0001  |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| A × B            | 2    | 64    | 9.6   | 2    | 32.0000   | 16.0000   | 4.8   | .0142   |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| A × C            | —    | —     | —     | 2    | 2.6667    | 1.3333    | 0.4   | .6733   |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| B × C            | —    | —     | —     | 1    | 12.0000   | 12.0000   | 3.6   | .0658   |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| A × B × C        | —    | —     | —     | 2    | 32.0000   | 16.0000   | 4.8   | .0142   |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| Within cells     | 18   | 60    |       | 36   | 120.0000  | 3.3333    |       |         |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n| Total            | 23   | 476   |       | 47   | 890.6667  |           |       |         |\n+------------------+------+-------+-------+------+-----------+-----------+-------+---------+\n\n: The two-way ANOVA of the 24 students quizzed one week after practice beside the three-way ANOVA of all 48 students; a dash marks a row that the two-way table does not have. {#tbl-ch04-two-three-way}\n\nFour rows are new. The timing row, C, compares the two timings averaged\nover the six feedback-by-practice cells: scores right after practice\naverage 13.3333 against 10 a week later, $F(1,36)=40$. The other three\nnew rows contain timing: A × C asks whether the feedback comparison\nchanges with timing, and hardly finds it does, $F(2,36)=0.4$; B × C\ncompares the average spacing benefit, 2 points right after practice\nagainst 4 a week later, $F(1,36)=3.6$, $p=.0658$; and A × B × C, the\nthree-way row, compares the whole feedback-by-practice pattern between\nthe timings.\n\nThe effect rows that the two tables share change their meaning: in the\nthree-way table each averages over the two timings and rests on all 48\nstudents. The feedback row compares feedback means of 8.0, 11.5 and\n15.5, each averaged over timing and resting on 16 students; the\none-week means 6, 10 and 14 rest on 8. The averaged means spread\nslightly less, but twice as many students stand behind each one, so the\nfeedback sum of squares is larger. The practice row compares the\nspacing benefit averaged over timing, 3 points, the average of the 2\nright after practice and the 4 a week later, with 24 students per\nschedule instead of 12. Because the within-cell mean square is 3.3333\nin both tables, each F follows its row's mean square: the practice F\nrises from 28.8 to 32.4 although the spacing benefit it tests falls\nfrom 4 points to 3, because each schedule mean now rests on twice as\nmany students.\n\nIn the three-way table the A × B row is the feedback-by-practice\ninteraction averaged over the two timings: its sum of squares falls from 64 in the\none-week study to 32, because right after practice the lines are\nparallel. The three-way row, $F(2,36)=4.8$, $p=.0142$, says that the\nfeedback-by-practice pattern differs between the timings, so the\naveraged row describes neither panel: averaged over timing, Answer's\nschedule difference minus Rereading's is 2 points, against 0 right after\npractice and 4 a week later. A multi-way table is therefore read from\nthe highest-order row down. Section 4.4 read the interaction row before\nthe main effects, because a main effect averages over a pattern that the\ninteraction says is changing; one level up the rule is the same. With a\nthree-way interaction present, report the two-way pattern within each\nlevel of the third factor, and read a lower-order row alone only when\nthe design and the evidence make the higher-order interactions\nnegligible [@kutner2005].\n\nThe within-cells row keeps its meaning. Its df grow with the students,\nfrom $24-6=18$ to $48-12=36$, while its mean square stays 3.3333,\nbecause every cell's residuals are $-2$, $-1$, 1 and 2 in both\nanalyses; in each table every F divides its row's mean square by that\none within-cell estimate.\n\nA fourth factor extends the table in the same way. Suppose the study\nalso crossed the reading medium, paper or screen, with the twelve cells,\neach student reading the practice material in one medium, again with\nfour different students in each of now 24 cells, 96 students in all. A\n**four-way interaction** would mean that the three-way pattern itself\ndiffers between the two media: for example, that the pattern of\n@fig-ch04-three-way holds for students who read on paper, while for\nstudents who read on screen the lines stay parallel at both timings.\n@tbl-ch04-multiway lists the rows of each design's table, with D for\nthe medium.\n\n\\Needspace{16\\baselineskip}\n\n| Rows of the table | Two-way, A\\ ×\\ B | Three-way, A\\ ×\\ B\\ ×\\ C | Four-way, A\\ ×\\ B\\ ×\\ C\\ ×\\ D, with the df of each row |\n|:--|:--|:--|:--|\n| Main effects | A, B | A, B, C | A\\ (2), B\\ (1), C\\ (1), D\\ (1) |\n| Two-way interactions | A\\ ×\\ B | A\\ ×\\ B, A\\ ×\\ C, B\\ ×\\ C | A\\ ×\\ B\\ (2), A\\ ×\\ C\\ (2), A\\ ×\\ D\\ (2), B\\ ×\\ C\\ (1), B\\ ×\\ D\\ (1), C\\ ×\\ D\\ (1) |\n| Three-way interactions | --- | A\\ ×\\ B\\ ×\\ C | A\\ ×\\ B\\ ×\\ C\\ (2), A\\ ×\\ B\\ ×\\ D\\ (2), A\\ ×\\ C\\ ×\\ D\\ (2), B\\ ×\\ C\\ ×\\ D\\ (1) |\n| Four-way interaction | --- | --- | A\\ ×\\ B\\ ×\\ C\\ ×\\ D\\ (2) |\n| Source rows, $2^k-1$ | 3 | 7 | 15, with 23 df in all |\n| Cells; students at four per cell | 6; 24 | 12; 48 | 24; 96 |\n| Within-cells df, students minus cells | 18 | 36 | 72 |\n\n: The rows of the two-way, three-way and four-way tables as quiz timing and then reading medium are added to the feedback-by-practice design, four students per cell, with the df of each four-way row. {#tbl-ch04-multiway tbl-colwidths=\"[25,13,21,41]\"}\n\nA design with $k$ factors has $k$ main effects and one interaction for\nevery pair, triple and larger set of factors, $2^k-1$ rows of effects\nin all: 3, 7 and 15. A row's df multiply the df of its factors, so every\nrow that contains feedback has 2 df and every other row 1; the effect\ndf of the four-way table add to the cells minus one, 23, and its\nwithin-cells df are the students minus the cells, 72. Each added\ntwo-level factor doubles the cells, so four students per cell means 24,\nthen 48, then 96 students.\n\nAdded factors have costs. A three-way contrast combines eight cell\nmeans where a difference of differences combines four, so with the same\nstudents per cell and the same error variance its SE is $\\sqrt2$, about\n1.4, times as large, and matching the precision of a difference of\ndifferences takes twice as many students per cell. The seven F tests of\na three-factor table, each at .05, also form a family in the sense of\n[Section 3.3](#sec-ch04-families): for seven independent tests whose\nnull hypotheses are all true, the chance of at least one false\nrejection is .3017, where the upper line of @fig-ch04-familywise stands\nat $m=7$, and the fifteen tests of a four-factor table raise it\nfurther. More cells also make unequal or empty cells more likely:\nunequal counts make each marginal mean depend on its weights\n([Appendix B.1](#app-ch04-weighting)), and an empty cell leaves some\ninteractions without an estimate.\n\nA study with several factors therefore declares in advance the few\ncomparisons it was built for, such as whether the spacing benefit under\nAnswer feedback grows between the two timings, and reads the other rows\nand cells as description. Twelve cells allow 66 pairwise comparisons and\nmany more contrasts, so a comparison found by searching them needs a\nfamily that covers the search, as Section 3.3 showed for three groups.\n\n## Checking the Conditions {#sec-ch04-conditions}\n\n### What the design and the data can show {#sec-ch04-deeper-checks}\n\nSection 2.3 stated the conditions where the F test first relied on\nthem, and each *Justifying the analysis* box recorded what the data\ncould check; @tbl-ch04-conditions gathers them with what the design or\nthe data can show about each and the response when one fails. A\ncondition is judged from the design, subject knowledge and displays such\nas @fig-ch04-residuals together, not from a sequence of Normality or\nvariance tests, which have least power in the small samples where the\nchoice matters most [@kutner2005].\n\n\\Needspace{20\\baselineskip}\n\n| Condition | What the design or the data can show | Response if it fails |\n|:--|:--|:--|\n| Independent observations | Only the design record: individual assignment, individual sessions, one score per student. No display of the scores can establish it | An analysis that represents the dependence: comparisons within blocks, as in Chapter 3's paired schools (Section 2.3), or models for classes and repeated measurements. Treating dependent rows as independent misstates every SE; positive clustering makes it too small, by about the square root of the design effect of Chapter 2, Section 4.4 |\n| Roughly Normal errors around the group or cell means | A residual display and a Normal quantile plot of the residuals, not of the pooled scores; small groups reveal only pronounced departures | With moderate skew and larger groups the F reference remains a reasonable approximation; with small groups and strong skew or a dominating value, disclose the weaker approximation and examine the influential scores |\n| One common variance | The group or cell SDs beside the group sizes; a fan in the residuals as the fitted mean grows | Welch's one-way ANOVA, chosen before the analysis (Section 5.2); for a contrast, an SE built from its groups' own variances, which for a pair is Chapter 3's Welch t |\n| Additivity, when a main effect is read as the effect at every level | The interaction row and the cell-mean plot | Report cell means and simple effects, and read each main effect as a stated average (Section 4) |\n\n: Conditions of the chapter's analyses, what can show whether each holds, and the response if it fails. {#tbl-ch04-conditions tbl-colwidths=\"[22,38,40]\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residuals of the one-way fit to the background-sound scores. Left: each student's residual, the score minus the group mean, by condition, jittered sideways so that equal values stay visible. Right: the thirty residuals against Normal quantiles, with a reference line.](chapter_04_files/figure-html/fig-ch04-residuals-1.png){#fig-ch04-residuals fig-pos='!ht' fig-alt='Left panel: three vertical strips of ten points, for Silence, Instrumental music and Music with lyrics, each spread from -4 to 4 around a dashed line at zero, with similar spread in every group. Right panel: a Normal quantile plot of the thirty residuals; the points rise in whole-number steps and follow a dashed reference line, the residuals of -4 and of 4 at the two ends sitting flatter than the line, and no point is far from it.' width=100%}\n:::\n:::\n\n\nFor the background-sound study the residuals spread similarly around\nzero in all three groups, each from $-4$ to 4, and in the quantile plot\nthey follow the line, with no outlying value; the residuals of $-4$ and\n4 at the two ends sit a little flatter than a Normal tail. Thirty\nresiduals can show only pronounced departures, so the display is\nconsistent with the model rather than proof of it, and independence\nstill rests on the design. The factorial scores were built with\nresiduals $-2$, $-1$, 1 and 2 in every cell, a teaching construction\nthat no display could treat as evidence.\n\nNeither invented dataset has missing scores; a real report compares\nassigned and analysed counts and explains known losses, because missing\noutcomes can change who contributes to a comparison and call for\nassumptions beyond the ANOVA model. Keep three claims distinct in every\nreport: the observed means and sums of squares describe these records;\nintervals and tests express uncertainty under a stated model; and\ncausal or population interpretations need the support that Section 1.2\ndescribes.\n\n### When spreads differ: Welch's one-way ANOVA {#sec-ch04-welch}\n\nWhen a common variance is doubtful, **Welch's one-way ANOVA** is the\ncounterpart of Welch's unequal-variance t test in Chapter 3,\nSection 5.4. It keeps each group's own variance instead of pooling them\ninto $MS_W$, weights each group mean by the precision implied by its own\nvariance and size, $n_j/s_j^2$, and uses an approximate F reference\nwhose denominator df are estimated from the group variances\n[@welch1951]; with two groups its F is the square of Welch's t.\n[]{#ch04-justify-welch}It reads with the\n[one-way box](#ch04-justify-oneway) of Section 2.3, with two changes:\nthe model assumption of one common variance is dropped, so each group\nmean needs only a near-Normal sampling distribution, and the calibration\nchanges with it. For the background-sound study it gives\n$F(2,17.9561)=5.5144$, $p=.0136$, beside the classical\n$F(2,27)=6.0674$, $p=.0067$: with similar spreads and equal group sizes\nthe two calibrations lead to the same conclusion at .05, although\nWelch's p is about twice as large. Its F is slightly smaller, and its\ndenominator df fall from 27 to 17.9561 because each weight rests on a\nvariance estimated from its own ten scores. Welch's\nmethod has the scope of one factor: clustering still needs an analysis\nthat represents the design, and crossed factors with unequal cell\nspreads take each stated contrast's SE from the cells' own variances.\n\nThe classical F test applies one pooled variance to every group mean.\nChapter 3, Section 5.4, showed for two groups that a pooled variance\nmisstates the variance of a small group's mean when spreads differ.\n@tbl-ch04-welch-consequence shows what this does with three groups: each\nrow simulates 50,000 studies of three Normal groups with equal means and\nthe stated SDs, so every rejection at level .05 rejects a true null.\n\n\n\n\\Needspace{14\\baselineskip}\n\n| Group sizes | Population SDs | Classical F | Welch's one-way ANOVA |\n|:--|:--|--:|--:|\n| 10, 20 and 40 | 8, 4 and 4: the smallest group varies most | .1572 | .0511 |\n| 10, 20 and 40 | 4, 4 and 8: the largest group varies most | .0126 | .0499 |\n| 20, 20 and 20 | 8, 4 and 4 | .0610 | .0502 |\n\n: Rejection rates of a true null of equal means at nominal level .05, from 50,000 simulated studies per design. {#tbl-ch04-welch-consequence tbl-colwidths=\"[18,42,20,20]\"}\n\nWhen the smallest group varies most, the variance that pooling targets,\n22.4478, gives that group's mean a variance of 2.2448 instead of the\n6.4000 its own SD implies, and the classical F rejects the true null in\n.1572 of the studies, more than three times the nominal .05; when the\nlargest group varies most it rejects in only .0126, and with equal group\nsizes it rises only to .0610. Welch's one-way ANOVA stays near .05 in all\nthree designs, which is why unequal group sizes with spreads that may\ndiffer call for it.\n\nAs in Chapter 3, choose between the common-variance and Welch\ncalibrations before the analysis, from the design and subject knowledge,\nrather than from a preliminary variance test or from whichever p-value\nis smaller [@delacre2017; @delacre2019]. Many statistical programs\nreport Welch's t by default for two groups; that default is Chapter 3's\nlast t procedure, not the equal-variance test whose square equals the\nclassical F of Section 2.4. Chapter 6 runs the Welch alternative beside\nthe common-variance calculation.\n\n## Reading Bridge {#sec-ch04-bridge}\n\nComparing several means extends the estimate-and-SE reasoning of\nChapter 3. ANOVA separates sources of variation to ask an omnibus\nquestion; a contrast states a narrower question and its uncertainty.\nMain effects average across factor levels, while cell means and\nsimple effects show the conditional pattern, and a third factor adds\nrows to the table and can change a two-way pattern itself. A joint\ninteraction test and one declared interaction contrast answer different\nquestions, and the history of a comparison sets the family its interval\nmust cover.\n\nThe same group-mean model can be written using indicator variables,\nas Chapter 6 does in R. A measured baseline can also enter an adjusted\nmodel, called analysis of covariance (ANCOVA), which Chapter 9,\nSection 2, develops as regression after Chapters 7--8 develop the\nregression mathematics, several controls and standardized\npredictions. Baseline adjustment accounts for a measured\nsource of score variation and compares fitted outcomes at a stated common\nbaseline value, or averages them over the same stated baseline distribution.\nThe groups need adequate overlap in those baseline values, often called\ncommon support, for those comparisons to be informed by observations.\nAdjustment is not a general cure for confounding or missing outcomes.\n\n**Blocking** makes condition comparisons within groups of similar\nunits. Chapter 3, Section 2.3, illustrates it with paired schools: in\neach of twelve schools one class is assigned to each format, so the\nuncertainty follows twelve independent within-school comparisons rather\nthan 480 students. Sampling strata, which organize selection into a\nsample, and allocation blocks, which organize treatment comparisons,\nhave different roles. The three sound conditions and the\nfeedback-by-practice cells of this chapter instead contain distinct,\nindividually assigned students. Repeated measurements and classroom\nclustering change the covariance structure and the relevant error term;\nthe shape of a data table cannot settle these design questions.\nChapters 5--6 now make the statistical foundations executable while\nkeeping the question, records and interpretation beside each\ncalculation.\n\n### Key terms {.unnumbered}\n\nUse this reference to revisit the concepts principally explained here.\nThe Part One Concept Reference collects earlier terms, including\nestimand, SE and confidence interval.\n\n```{=latex}\n\\small\n```\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Factor (grouping factor) | In ANOVA, a categorical variable defining groups or conditions; its categories are levels. This meaning differs from a latent factor used to model shared indicator variation. |\n| Analysis of variance (ANOVA) | A method for studying mean differences through sources of variation. One-way ANOVA uses one grouping factor, and multi-way (factorial) ANOVA uses two or more crossed factors, as two-way and three-way ANOVA do; each factor can have several levels. |\n| Fitted value | The value a fitted model assigns to an observed case. In a one-way group-mean model, it is that case's group mean. |\n| Residual | An observed outcome minus its fitted value. A residual is calculated from the fitted model; an error is the corresponding unknown departure in the population model. |\n| Mean square (MS) | A sum of squares divided by its degrees of freedom. In classical ANOVA, the within-group mean square estimates the common error variance under the model's conditions. |\n| F statistic (F ratio) | In classical ANOVA, a ratio of the mean square for a tested source to the appropriate error mean square. Its null F reference depends on the model and both degrees of freedom. |\n| Omnibus test | A test of one joint null hypothesis about a whole pattern, such as equality of all group means. Rejecting it does not identify which comparisons differ or how large they are. |\n| Eta squared | The proportion of total observed variation attributed to a specified source in an ANOVA decomposition. In one-way ANOVA, it is between-group divided by total sum of squares. |\n| Contrast (linear contrast) | A weighted combination of means whose weights sum to zero, expressing a specific comparison. The means, weights, and target population determine the quantity compared. |\n| Familywise error rate (FWER) | The probability of at least one Type I error among a defined family of tests. Procedures such as Bonferroni allocate the error allowance across that family. |\n| Simultaneous confidence intervals | A set of intervals calibrated so that, under their conditions, all of them cover their estimands together at the stated familywise rate; Bonferroni, Tukey, and Dunnett are different calibrations for different families. |\n| Cell mean and marginal mean | In a two-factor layout, a cell mean is the mean of the cases sharing one level of each factor; a marginal mean averages the cell means across the levels of the other factor, with stated weights. |\n| Main effect | A comparison across one factor's levels averaged over the other factor's levels, using stated weights. It remains an average when the conditional pattern differs across levels. |\n| Interaction | A pattern in which a comparison across one factor's levels changes with the other factor's level. A difference of differences expresses one such comparison. |\n| Simple effect | A comparison across one factor's levels at a specified level of the other factor. It describes a conditional comparison within the factorial design. |\n| Three-way interaction (higher-order interaction) | A pattern in which a two-way interaction changes across the levels of a third factor. Each added factor multiplies the cells and adds interactions, so the highest-order interaction is read first and a few comparisons are declared in advance. |\n\n: Selected concepts for group comparisons and ANOVA. {#tbl-ch04-key-terms tbl-colwidths=\"[28,72]\"}\n\n```{=latex}\n\\normalsize\n```\n\n### Further reading {.unnumbered}\n\n- *Introduction to Modern Statistics* develops the transition from\n  grouped observations to [inference for many means](https://openintro-ims.netlify.app/inference-many-means)\n  [@cetinkaya2024].\n- [Penn State STAT 200, Lesson 10](https://online.stat.psu.edu/stat200/Lesson10)\n  provides an introductory ANOVA treatment; its\n  [factorial-design lesson](https://online.stat.psu.edu/stat503/Lesson05)\n  develops main effects and interaction.\n- The NIST handbook explains [contrasts and their SEs](https://www.itl.nist.gov/div898/handbook/prc/section4/prc436.htm)\n  and [Bonferroni simultaneous intervals](https://www.itl.nist.gov/div898/handbook/prc/section4/prc473.htm).\n\n## Exercises {.unnumbered}\n\nThe printed scores and the supplied tables and results support each\ninterpretation, with a calculator for the few calculations that the\nreasoning needs. Retain full precision until reporting calculated\nresults to four decimal places. State the relevant records, conditions\nand comparison direction in each interpretation.\n\n<!-- prompt-id: CH04-E01 -->\n### Exercise 1: Read grouped observations (Foundational) {.unnumbered #ex-ch04-01}\n\nUse the thirty background-sound scores of the invented study, printed\nin Section 1.\n\n1. The group means are 12, 10 and 8, and the sample SDs are 2.7080,\n   2.4037 and 2.5820. Use them with the ranges to compare the centers,\n   spreads and overlap of the three groups, and say what an SD of\n   about 2.5 points describes for these students.\n2. Suppose every student's distance from their group mean were\n   doubled, so that the three means stay at 12, 10 and 8. Before\n   calculating, say whether the evidence against equal means would\n   become stronger or weaker, and why. Then compare the supplied\n   results, $F(2,27)=6.0674$, $p=.0067$ for the actual scores and\n   $F(2,27)=1.5169$, $p=.2375$ for the doubled version, and explain\n   why F falls to one quarter.\n3. The three SDs are similar. Explain why that similarity does not\n   establish that a common-variance Normal model will hold in a real\n   study.\n4. Identify the assignment and measurement units stipulated in this\n   invented study. Explain what the scores alone cannot establish\n   about causal interpretation or generalization.\n\n<!-- prompt-id: CH04-E02 -->\n### Exercise 2: Read the one-way table (Foundational) {.unnumbered #ex-ch04-02}\n\nUse Exercise 1's scores. There are $J=3$ groups and $N=30$ students,\nand the classical analysis assumes independent Normal errors with a\ncommon variance. Statistical software reports this table:\n\n| Source | SS | df | MS | F | p |\n|:--|--:|--:|--:|--:|--:|\n| Sound condition | 80 | 2 | 40.0000 | 6.0674 | .0067 |\n| Within groups | 178 | 27 | 6.5926 | | |\n| Total | 258 | 29 | | | |\n\n1. Explain what the between-groups df, 2, and the within-groups df,\n   27, each count, and why they add to the total df, 29. Name the\n   reference distribution of F under the null.\n2. Explain why the Instrumental-music group contributes nothing to\n   $SS_B$ although its scores vary. Say what $MS_W$ estimates and why\n   it is smaller than the total sample variance, $258/29=8.8966$.\n3. State the omnibus null. Interpret $p=.0067$ at $\\alpha=.05$,\n   including the model conditions and what the conclusion leaves\n   unanswered about particular comparisons.\n4. Without refitting, predict how $SS_B$, $SS_W$ and F would change\n   if (a) every Music-with-lyrics score rose by 2 points, or (b) all\n   thirty scores rose by 5 points. Then check prediction (a) against\n   the supplied result $SS_B=26.6667$, $F(2,27)=2.0225$, $p=.1519$,\n   and say what change (a) makes to the conclusion of part 3.\n\n<!-- prompt-id: CH04-E03 -->\n### Exercise 3: Define and estimate contrasts (Foundational) {.unnumbered #ex-ch04-03}\n\nThe sound-condition means are 12, 10 and 8 in the order Silence,\nInstrumental music, Music with lyrics. Each group has ten students and\nthe common-variance estimate is $MS_W=178/27$, with 27 residual df.\n\n1. Identify which weight vectors define contrasts: $(-1,1,0)$,\n   $(-1,0,1)$, $(-1,1/2,1/2)$ and $(1/3,1/3,1/3)$. State the\n   ordinary-language question represented by each contrast.\n2. The vectors $(-1,1,0)$, $(-1,0,1)$ and $(-1,1/2,1/2)$ give\n   estimates $-2$, $-4$ and $-3$ with SEs 1.1483, 1.1483 and 0.9944,\n   each from $\\sqrt{MS_W\\sum_j c_j^2/n_j}$. Explain, through the squared\n   weights, why the equal-average contrast has the smallest SE, and\n   why all three SEs use the full three-group error estimate.\n3. Explain why the equal-average contrast cannot replace both separate\n   music-versus-Silence comparisons when both are required.\n4. For a weighting illustration only, suppose the Instrumental-music\n   and Music-with-lyrics means stay at 10 and 8 but their counts are 10\n   and 30. The Silence mean stays at 12. Compare the equally weighted\n   music-average difference with the student-weighted difference. State\n   the question answered by each. These illustrative counts do not\n   change the chapter's actual balanced dataset.\n\n<!-- prompt-id: CH04-E04 -->\n### Exercise 4: Interpret comparison families (Integrative) {.unnumbered #ex-ch04-04}\n\nIn the invented background-sound study, thirty first-year students were\nindividually and randomly assigned to three sound conditions, ten to a\ncondition, and each answered the 0--20 comprehension quiz once after\nreading the same passage. The group means are 12 for Silence, 10 for\nInstrumental music and 8 for Music with lyrics. Under the independent\ncommon-variance Normal model, $MS_W=178/27$ on 27 error df, so each\ndifference between two of these means has\n$SE=\\sqrt{(178/27)(1/10+1/10)}=1.148267616$; this SE and the critical\nvalues below carry nine decimals so that the printed four-decimal\nlimits can be reproduced by hand. Two reports give the same estimate,\n$-4$ comprehension points for Music with lyrics minus Silence, but the\ncomparison has a different history in each:\n\n- **Report A.** Before any scores were seen, the study plan declared\n  a family of two comparisons, each music condition against Silence:\n  Instrumental music minus Silence and Music with lyrics minus Silence,\n  with 95% simultaneous coverage for the pair.\n- **Report B.** No comparison was declared in advance. After\n  inspecting the three means, an analyst reports the largest pairwise\n  difference, Music with lyrics minus Silence.\n\nThe Bonferroni critical value for two comparisons is 2.373417201, and\nReport A's 95% simultaneous intervals are $[-4.7253,0.7253]$ for\nInstrumental music minus Silence and $[-6.7253,-1.2747]$ for Music\nwith lyrics minus Silence. Tukey's 95% all-pairs intervals are\n$[-4.847,0.847]$ for Instrumental music minus Silence,\n$[-6.847,-1.153]$ for Music with lyrics minus Silence and\n$[-4.847,0.847]$ for Music with lyrics minus Instrumental music.\n\n1. Before calculating, state what differs between the two reports and\n   what effect the difference has on the family of comparisons that\n   the uncertainty statement must cover. Give your reasons.\n2. For Report A, explain how dividing a .05 familywise error\n   allowance between the two intervals and their tails leads to the\n   quantile .9875 behind its critical value. Interpret the two\n   intervals together, and explain why an interval containing zero\n   does not establish equivalence.\n3. For Report B, identify the family from which the comparison was\n   selected and the interval warranted for Music with lyrics minus\n   Silence. Compare it with Report A's interval for the same\n   comparison, say which one describes the uncertainty under Report\n   B's history and why, and state what each history lets you conclude\n   about the comparison. A Bonferroni bound over Report B's family\n   uses $t_{1-.05/6;27}=2.552458806$: calculate its half-width and\n   explain why it exceeds both Report A's half-width, 2.7253, and\n   Tukey's, 2.8470.\n4. Report A's two comparisons share the Silence mean. Explain why\n   this creates dependence between the two estimates and why it does\n   not invalidate the Bonferroni bound (Appendix B.3).\n\n\\Needspace{16\\baselineskip}\n\n<!-- prompt-id: CH04-E05 -->\n### Exercise 5: Read the factorial pattern (Foundational) {.unnumbered #ex-ch04-05}\n\nUse the 24 feedback-by-practice scores of the invented study, printed\nin Section 4.1. There are four different students per cell,\nindividually allocated to the six combinations.\n\n1. Identify the outcome, the two factors and their levels, the\n   assignment unit, the number of cells and the meaning of balance.\n2. Leave practice aside for a moment, so that each feedback condition\n   is one group of eight students. The three feedback means are then\n   6, 10 and 14, and the two practice means 8 and 12; explain why they\n   equal the equally weighted marginal means here. Analysed this way,\n   the feedback groups have SDs 1.6903, 2.7255 and 4.5981, a within-group mean\n   square of 10.4762 on 21 df and $F(2,21)=12.2182$, whereas the full\n   two-way model has $MS_E=3.3333$ on 18 df and feedback\n   $F(2,18)=38.4000$. Explain where the extra within-group variation\n   comes from and why the Explanatory group's SD is the largest.\n3. The additive prediction for Explanatory-Spaced, the grand mean\n   plus the Explanatory-feedback and Spaced-practice effects, is\n   16, and the observed cell mean is 18. Explain what the\n   interaction departure of 2 says about spacing under\n   Explanatory feedback, and why the other departures in its row and\n   column must balance it.\n4. The Spaced-minus-Massed differences are 0, 4 and 8 points for\n   Rereading, Answer feedback and Explanatory feedback, so Answer's\n   schedule difference minus Rereading's is 4 points. Explain how\n   these values appear in the cell-mean plot, and what the plot would\n   show if the three differences were equal.\n5. Explain why the four-cell difference in part 4 is one interaction\n   contrast, while the full three-by-two interaction has two df.\n   Explain why the connected lines do not represent paired students.\n\n<!-- prompt-id: CH04-E06 -->\n### Exercise 6: Distinguish joint and declared results (Integrative) {.unnumbered #ex-ch04-06}\n\nFor the full feedback-by-practice model, the ANOVA table gives\nfeedback $F(2,18)=38.4$, practice $F(1,18)=28.8$ and interaction\n$F(2,18)=9.6$, with p-values below .0001, below .0001 and .0015,\nand error mean square $MS_E=60/18=10/3$ on 18 df. Assume independent\ncommon-variance Normal errors. The critical value in parts 3 and 4\ncarries extra decimals so that the printed limits can be reproduced by\nhand.\n\n1. State in words the joint null hypothesis that each of the three\n   rows tests, the order in which to read the rows, and the reason\n   for that order.\n2. The schedule marginal means are 8 and 12, but the conditional\n   schedule differences are 0, 4 and 8. Explain what the practice\n   main effect averages and why it does not describe every condition.\n3. Answer's 4-point schedule difference has $SE=\\sqrt{5/3}$, and\n   with $t_{.975,18}=2.10092204$ its pointwise 95% interval is\n   $[1.2877,6.7123]$. State the family limitation of this\n   single-comparison interval.\n4. The study plan declared one interaction comparison before any\n   scores were seen: Answer's schedule difference minus Rereading's,\n   estimated as 4. Its SE from four independent cell means of size 4\n   and $MS_E=10/3$ is 1.8257, and with the same critical value its 95%\n   interval is $[0.1643,7.8357]$. Explain why this single-comparison\n   interval is warranted for the declared contrast, and what it says\n   about spacing under the two kinds of feedback.\n5. Explain why the interaction test's $p=.0015$ does not by itself\n   establish the direction in part 4, and why the interval of part 4\n   would need a wider family had the same contrast been picked after\n   the plot was inspected.\n\n<!-- prompt-id: CH04-E07 -->\n### Exercise 7: Repair a claim about teaching (Integrative) {.unnumbered #ex-ch04-07}\n\nRepair this claim about the invented study:\n\n> Spaced practice improves every student's learning by four points,\n> whatever feedback is provided. The significant interaction proves\n> that Answer feedback benefits more from spacing than Rereading,\n> and the results apply to all students.\n\nAll 24 quiz scores are observed. The stipulated design allocates\nfour different students to each cell. The equal-weight practice\nmain effect is 4 points; conditional schedule differences\nare 0, 4 and 8. The interaction test gives\n$F(2,18)=9.6$, $p=.0015$. The study plan declared one interaction\ncomparison in advance, Answer's schedule difference minus\nRereading's; it is 4, with 95% interval $[0.1643,7.8357]$.\n\n1. Identify at least four words or claims that exceed the\n   supplied statistical and design information.\n2. Write a bounded replacement retaining the conditional pattern,\n   the joint interaction result, the declared estimate and interval,\n   the 0--20 quiz scale, and the invented nature of the example.\n3. Explain what random allocation could support in a real study\n   and what it would not establish about population sampling or\n   individual treatment effects.\n4. Explain how class-level assignment, repeated observations or\n   missing outcomes would affect the information needed for the\n   analysis. Do not invent losses in the present dataset. State\n   why four observations per cell limit diagnostic reassurance.\n\n<!-- prompt-id: CH04-E08 -->\n### Exercise 8: Relate two-group ANOVA to the t test (Integrative) {.unnumbered #ex-ch04-08}\n\nUse the Silence and Music-with-lyrics scores printed in Section 1,\nwhich belong to twenty different students. For these two groups alone\nthe pooled within-group variance is 7 on 18 df. Silence minus Music\nwith lyrics is 4 points, with $SE=\\sqrt{7(1/10+1/10)}=1.1832$ and\npooled $t=3.3806$ on 18 df, and a one-way ANOVA of the same two groups\ngives $F(1,18)=11.4286$; both two-sided p-values are .0033.\n\n1. Explain why F equals $t^2$ here and why the two p-values agree.\n2. Say what F loses that t and the signed difference keep.\n3. The three-group analysis of Section 2.3 estimates the error\n   variance as 6.5926 on 27 df. Explain why the two-group fit gives 7\n   on 18 df instead, and which question each fit answers.\n\n<!-- prompt-id: CH04-E09 -->\n### Exercise 9: Match the analysis to the design (Integrative) {.unnumbered #ex-ch04-09}\n\nIn the background-sound study, the Silence and Music-with-lyrics\nscores printed in Section 1 belong to twenty different students, each\nrandomly assigned to one condition.\n\n1. Suppose instead that each of ten students read one passage in\n   silence and a comparable passage with lyrics, in a random order.\n   Explain why a paired analysis would use within-student differences\n   and why an independent-group calculation, such as Exercise 8's,\n   would no longer be the appropriate starting point. Name the\n   dependence information needed to calculate its SE.\n2. Explain how assigning one class to each condition within each\n   school creates a blocked comparison. Identify the comparison\n   units in Chapter 3's paired-school example (Section 2.3) and\n   distinguish an allocation block from a sampling stratum.\n3. A researcher proposes measuring a fractions pretest before\n   assigning feedback in the feedback-by-practice study. Explain what\n   baseline adjustment adds, why an adjusted comparison needs a\n   specified common value or averaging distribution, and why\n   adjustment alone does not establish a causal interpretation.\n\n## Appendix A: Deriving the Matched Pooled-t Identity {.unnumbered #app-ch04-pooled-identity}\n\n[]{#app-ch04-calculations}\n\nSection 2.4 states this identity and its conditions; the derivation\nshows where it comes from. For two independent groups, let\n$\\widehat{\\Delta\\mu}=\\bar y_1-\\bar y_2$ and $N=n_1+n_2$. Their grand mean is\n\n$$\n\\bar y=\\frac{n_1\\bar y_1+n_2\\bar y_2}{N}.\n$$\n\nSubtracting it from each group mean gives\n\n$$\n\\bar y_1-\\bar y=\\frac{n_2}{N}\\widehat{\\Delta\\mu},\n\\qquad\n\\bar y_2-\\bar y=-\\frac{n_1}{N}\\widehat{\\Delta\\mu}.\n$$\n\nConsequently,\n\n$$\n\\begin{aligned}\nSS_B\n&=n_1\\left(\\frac{n_2}{N}\\widehat{\\Delta\\mu}\\right)^2\n  +n_2\\left(-\\frac{n_1}{N}\\widehat{\\Delta\\mu}\\right)^2\\\\\n&=\\frac{n_1n_2}{N}\\widehat{\\Delta\\mu}^2.\n\\end{aligned}\n$$\n\nThere is one numerator df, so $MS_B=SS_B$. Define the pooled\nvariance $s_p^2=SS_W/(N-2)$, which is Chapter 3's pooled variance and\nequals $MS_W$ when $J=2$. Because\n$n_1n_2/N=1/(1/n_1+1/n_2)$,\n\n$$\nF=\\frac{SS_B}{s_p^2}\n=\\frac{\\widehat{\\Delta\\mu}^2}{s_p^2(1/n_1+1/n_2)}=t^2,\n$$\n\nwhere $t=\\widehat{\\Delta\\mu}/\\{s_p\\sqrt{1/n_1+1/n_2}\\}$ is the\nequal-variance t statistic.\n\nThe equality is algebraic for these matched definitions; the equal\np-values add the test conditions and a two-sided t alternative. It\nconnects the one-way F test to the equal-variance t test of Chapter 3,\nSection 5.3. The paired-samples t test (Chapter 3, Section 5.2) and\nWelch's t test (Chapter 3, Section 5.4) have their own SEs and df, so\nthis algebra supplies neither; Welch's several-group counterpart is\nthe Welch one-way ANOVA of Section 5.2.\n\n## Appendix B: Reference Notes on Weights, Effect Sizes and a Shared Reference Mean {.unnumbered #app-ch04-comparisons}\n\n### B.1 Unequal-cell weights {.unnumbered #app-ch04-weighting}\n\nIn the chapter's balanced data, equal-cell and student-weighted\nmarginal means coincide. For unequal cell counts, define them\nseparately:\n\n$$\n\\bar y_{j\\cdot}^{\\text{students}}\n=\\frac{\\sum_kn_{jk}\\bar y_{jk}}{\\sum_kn_{jk}},\n\\qquad\n\\bar y_{j\\cdot}^{\\text{equal cells}}\n=\\frac1K\\sum_k\\bar y_{jk}.\n$$\n\nThe first describes the mixture of students observed in that\nfeedback group. The second gives each of the $K$ practice conditions\nthe same weight. Neither is automatically the right target for\nevery question.\n\nFor an illustration, retain Answer's cell means 8 and 12 but\nimagine counts of 2 Massed and 6 Spaced students. The equally\nweighted mean is $(8+12)/2=10$; the student-weighted mean is\n$(2\\times8+6\\times12)/8=11$. These are hypothetical weights,\nnot changes to the actual four-per-cell dataset. A comparison of\nfeedback groups using different schedule mixtures can combine a\nfeedback comparison with a weighting difference. Adjusted means in\nlater chapters make their common profile or averaging distribution\nexplicit for this reason.\n\n### B.2 Effect-size denominators {.unnumbered #app-ch04-effect-sizes}\n\nSection 2.4 used one omnibus summary, eta squared. Software reports\nseveral related summaries whose denominators differ, so each needs its\nname and its denominator before it is interpreted.\n\n\\Needspace{14\\baselineskip}\n\n| Summary | Formula | Denominator | Value here |\n|:--|:--|:--|--:|\n| Eta squared, one-way | $SS_B/SS_T$ | All observed variation | .3101 |\n| Omega squared, one-way | $\\dfrac{SS_B-(J-1)MS_W}{SS_T+MS_W}$ | All observed variation plus one error mean square; the numerator first removes the variation expected from noise | .2525 |\n| Eta squared for a factorial term | $SS_{\\text{term}}/SS_T$ | All observed variation, including the other factors | Interaction .1345 |\n| Partial eta squared | $\\dfrac{SS_{\\text{term}}}{SS_{\\text{term}}+SS_E}$ | The term and the error only | Interaction .5161 |\n\n: Four effect-size summaries and their denominators. {#tbl-ch04-effect-sizes tbl-colwidths=\"[24,25,37,14]\"}\n\nHere $\\eta^2=80/258=.3101$, $\\omega^2=\\{80-2(178/27)\\}/(258+178/27)=.2525$,\nand the interaction's two summaries are $64/476=.1345$ and\n$64/(64+60)=.5161$. Omega squared subtracts the between-group\nvariation that group means show even when the model means are equal;\nit rests on the common-variance model, can fall below zero in a small\nsample, and like eta squared says nothing about causation. The two\nfactorial rows show why the name matters: the same interaction is\n.5161 of its partial denominator but .1345 of all the variation,\nbecause the partial version leaves the feedback and practice\ncomponents out. In one-way ANOVA the two eta squared versions agree,\nsince the total holds only the factor and error. The raw mean\ndifferences remain necessary for understanding the outcome scale.\n\n### B.3 Two comparisons that share a reference mean {.unnumbered #app-ch04-dependence}\n\nThe two declared comparisons of Section 3.3, Instrumental music minus\nSilence and Music with lyrics minus Silence, both subtract the Silence\nmean, so their estimates are positively related: a Silence mean that\nhappens to fall high lowers both differences together, and their\ncovariance under independent group means is\n$\\operatorname{Var}(\\bar Y_S)=\\sigma^2/10$. The union bound needs no\nindependence, so the joint coverage of at least 95% stands; it\ndescribes repeated use of the whole procedure, not a probability\nassigned to the two realized intervals. Dunnett's method, calibrated\nfor exactly this family of comparisons with one reference, would give\nslightly narrower intervals; Bonferroni's arithmetic is the more\ntransparent. The\n[NIST Bonferroni reference](https://www.itl.nist.gov/div898/handbook/prc/section4/prc473.htm)\nexplains the joint-coverage bound.\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_04_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}