{
  "hash": "927d69d23ff50903ea52dc54f3bdd038",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Interaction and Moderation\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{16\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nAn additive straight-line model gives each predictor one partial slope.\nThis chapter asks when a comparison should instead vary across another\npredictor's values or groups. A product term makes that possibility\nexplicit. We follow its meaning from generated practice-and-preparation\nrecords to faculty salaries and conformity responses: interpret the\ncoefficients at their anchors, estimate conditional comparisons, show\nwhere the records support them, and evaluate their uncertainty. By the end,\nyou can distinguish a varying association from a causal explanation and\nwrite an informative report even when the slopes are poorly distinguished.\n:::\n\nThe same equation can pose different research questions. An extra hour\nof practice may have different associations with achievement at different\npreparation levels. A year's service may have different salary associations\nacross academic ranks. We begin with the comparison that an additive model\nholds fixed, then examine what changes when it is allowed to vary.\n\n## A Comparison That Depends on Another Predictor {#ch10-question}\n\n\n### The restriction the additive model imposes\n\nSuppose a researcher asks whether students who spend more time in\ndeliberate practice tend to achieve higher posttest scores. An additive\nregression can allow students with stronger prior preparation to have\nhigher scores while requiring the practice-score relationship to be the\nsame at every preparation level. That requirement may be the very claim\nthe researcher needs to examine. Perhaps an additional hour of practice\nis associated with a small score difference for students with lower\nprior preparation and a larger difference for students with higher\nprior preparation. Or perhaps the apparent difference is only sampling\nnoise.\n\nThe central question is therefore conditional:\n\n> How does the expected outcome difference associated with one unit of a\n> focal predictor vary across meaningful values or groups of another\n> predictor?\n\nAn **interaction** is the model term that permits such variation. On the\nmodeled scale, interaction means departure from additivity. Parallel\nlines are additive; nonparallel lines are interactive. The lines need\nnot cross inside the observed data, and a statistically detectable\nproduct term does not by itself identify a causal mechanism.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same practice model with and without its product term. Arrows compare two with four practice hours at baseline 60 and 80: both differences are 5 under additivity, versus 2.6 and 7.4 under interaction. These are conditional model means.](chapter_10_files/figure-html/fig-ch10-additive-interactive-1.png){#fig-ch10-additive-interactive fig-pos='H' fig-alt='Two panels show expected score against practice. Additive lines at baseline 60 and 80 have equal two-hour differences of 5. Interactive lines have two-hour differences of 2.6 and 7.4, shown by arrows. The lines do not cross.' width=604.8}\n:::\n:::\n\n\n\nRead the arrows as conditional comparisons. In the interactive panel,\ntwo additional practice hours correspond to 2.6 score points at baseline\n60 and 7.4 at baseline 80. Their difference is 4.8 points. The product\nterm will express this changing comparison in one equation. The lines\nare model means at two named baseline values: they are neither individual\nstudents' trajectories nor separate regressions fitted after splitting\nthe students into groups. Section 2.4 declares this model and generates\none sample from it.\n\nThis chapter first uses a simulation in which the conditional\nrelationship is known. It then studies a real observational example:\nnine-month salary, years of service, and academic rank for the faculty\nof one U.S. college in 2008-09, from the package-distributed\n`carData::Salaries` data. The two examples play different roles. The\nsimulation verifies algebra and repeated-sample logic against known\ntruth. The salary analysis forces the harder decisions about units,\nseverely unequal support, factor coding, uncertainty, diagnostics, and\nbounded reporting — and it shows what an honest interaction report looks\nlike when the data do not clearly distinguish rank-specific slopes from\none common slope.\n\n\n### The same idea for groups and continuous predictors\n\nChapter 4's factorial model allowed the practice-schedule difference to\nvary across feedback groups: its interaction test gave $F(2,18)=9.6$,\n$p=.0015$, and its declared difference of differences was 4 with SE 1.8257.\nChapter 6 fitted that model in R. Here a continuous predictor replaces one\nfactor, so a surface replaces a finite cell table and a moving slope\nreplaces a single difference of differences. The ANOVA foundations remain\nthe same; what changes is the form of the conditional comparison.\n\n### Interaction is defined on a stated scale\n\nAdditivity is always defined on a scale. Lines that are nonparallel for\nsalary in dollars remain nonparallel after converting dollars to\nthousands of dollars, although every outcome coefficient is divided by\n1,000. A\nnonlinear transformation such as a logarithm can change whether a\npattern appears additive because it changes the model itself, not merely\nthe label on the axis.\n\nThe same caution matters in later generalized linear models: interaction\non a linear-predictor scale need not look the same on a response scale.\nThis chapter stays with continuous outcomes and the identity-link linear\nmodel. Logistic interaction, multilevel interaction, and three-way\ninteraction are outside its worked scope.\n\n::: {.callout-warning title=\"Moderation is not mediation or mechanism\"}\nA moderator names where a focal relationship is allowed to vary. That\nreading describes when an association differs, rather than how an effect\nis transmitted. An intervening variable and a causal mechanism need\nadditional design and identification evidence. Chapter 14 develops those\nrequirements.\n:::\n\n## The Product Term and Its Coefficients {#ch10-product}\n\n\n### The product coefficient is a difference in slopes\n\nBegin with two continuous predictors, $X$ and $W$, and a continuous\noutcome, $Y$. An additive conditional-mean model is\n\n$$\nE(Y_i\\mid X_i,W_i)=\\beta_0+\\beta_X X_i+\\beta_W W_i.\n$$\n\nHolding $W$ fixed, the expected difference associated with a one-unit\ndifference in $X$ is always $\\beta_X$. Holding $X$ fixed, the expected\ndifference associated with a one-unit difference in $W$ is always\n$\\beta_W$. The model permits different levels but not different slopes.\n\nThe product-term model is\n\n$$\nE(Y_i\\mid X_i,W_i)\n=\\beta_0+\\beta_X X_i+\\beta_W W_i+\\beta_{XW}X_iW_i.\n$$ {#eq-continuous-interaction}\n\nRegrouping the terms that involve $X$ gives\n\n$$\nE(Y_i\\mid X_i,W_i)\n=\\left(\\beta_0+\\beta_W W_i\\right)\n + \\left(\\beta_X+\\beta_{XW}W_i\\right)X_i.\n$$\n\nThe conditional slope of $X$ at $W=w$ is therefore\n\n$$\n\\frac{\\partial E(Y\\mid X,W)}{\\partial X}\n=\\beta_X+\\beta_{XW}w.\n$$ {#eq-conditional-slope-x}\n\nIf $\\beta_{XW}=0$, the slope does not vary with $W$ and the model is\nadditive. If $\\beta_{XW}\\ne0$, a one-unit difference in $W$ changes the\nconditional slope of $X$ by $\\beta_{XW}$. This is what the product\ncoefficient measures. It is a **difference in slopes**, not the slope of\n$X$ at every value of $W$.\n\nThe same model can be regrouped around $W$:\n\n$$\n\\frac{\\partial E(Y\\mid X,W)}{\\partial W}\n=\\beta_W+\\beta_{XW}x.\n$$ {#eq-conditional-slope-w}\n\nThe algebra is symmetric: each predictor's conditional slope depends on\nthe other. Substantive language need not be symmetric. Researchers often\ncall $W$ a **moderator** when theory makes $X$ the focal predictor and\n$W$ the variable across which the $X$ relationship is expected to vary;\nthe conditional slope $\\beta_X+\\beta_{XW}w$ is then called a **simple\nslope** or conditional effect at $w$ [@aiken1991; @hayes2022]. That label\ncomes from the research question, not from a privileged side of the\nmultiplication sign.\n\nFor two values $x_a$ and $x_b$ at the same moderator value $w$, the\nconditional mean contrast is\n\n$$\nE(Y\\mid x_b,w)-E(Y\\mid x_a,w)\n=(x_b-x_a)\\left(\\beta_X+\\beta_{XW}w\\right).\n$$\n\nThat sentence contains several safeguards:\n\n- it identifies the outcome scale;\n- it identifies the focal predictor difference;\n- it holds the other predictor at a stated value;\n- it describes a conditional mean, not every case; and\n- it remains associational unless the research design supports a causal\n  interpretation.\n\n\n### Hierarchy: the lower-order terms stay\n\nThe formula\n\n```r\ny ~ x * w\n```\n\nexpands to `x + w + x:w`. The lower-order terms belong with their\nproduct term. This **hierarchy principle** has both mathematical and\ninterpretive reasons [@cohen2003; @kutner2005].\n\nFirst, deleting $X$ while retaining $XW$ constrains the slope of $X$ to\nzero when $W=0$. Deleting $W$ imposes the analogous constraint at\n$X=0$. Such constraints are rarely part of the research question.\nSecond, shifting either predictor changes which lower-order coefficients\nrepresent slopes and differences. A hierarchical model remains the same\nfitted surface after a change of origin; a product-only model generally\ndoes not. Third, factor product terms are often represented by several\ncolumns, so retaining the full lower-order structure keeps the block's\nmeaning coherent.\n\nHierarchy does not mean every possible product must be added. The\ninteraction should be motivated by the research question, graph, design,\nor a prespecified model comparison. It means that once a product is in\nthe model, its component terms remain.\n\n\n### Centering changes the question at zero\n\nLet $W_c=W-c$. Substituting $W=W_c+c$ into\n@eq-continuous-interaction gives\n\n$$\nE(Y\\mid X,W_c)\n=(\\beta_0+c\\beta_W)\n +(\\beta_X+c\\beta_{XW})X\n +\\beta_WW_c+\\beta_{XW}XW_c.\n$$\n\nCentering $W$ at $c$ therefore changes the intercept and the\nlower-order coefficient of $X$. The new $X$ coefficient is the\nconditional slope at the original value $W=c$. It does not change the\ninteraction coefficient, fitted values, residuals, or the corresponding\nfull-versus-reduced product-block test. Centering is a\n**reparameterization**: it puts zero at a value that makes a coefficient\nworth interpreting [@aiken1991].\n\nCentering is not a remedy for confounding, selection bias, measurement\nerror, omitted nonlinearity, lack of overlap, or a poorly specified\nresearch question. It can change correlations among constructed columns\nand may make numerical output easier to read, but it does not add\ninformation or make unsupported comparisons valid.\n\nScaling is another reparameterization. If $X_{10}=X/10$, then a one-unit\ndifference in $X_{10}$ is a ten-unit difference in $X$. Coefficients and\nstandard errors change units together; fitted values and substantive\nconclusions should agree after correct translation.\n\n\n### A known-truth example: what one sample recovers\n\nConsider a deliberately simplified educational setting. Each row is one\nstudent. The focal predictor is weekly deliberate practice in hours,\n$X$. The second predictor is a baseline assessment score, $W$. The\noutcome is a posttest score, $Y$. The simulation asks an associational\nmodel question under known conditions: how does the practice-score slope\nvary with baseline score?\n\nThe data-generating process centers baseline score at 70:\n\n$$\n\\begin{aligned}\nY_i={}&60+2.5X_i+0.4(W_i-70)\\\\\n &+0.12X_i(W_i-70)+\\varepsilon_i,\\\\\n\\varepsilon_i&\\sim\\mathcal N(0,5^2).\n\\end{aligned}\n$$ {#eq-simulation-dgp}\n\nThe coefficients are fixed by design. At a baseline score of 70, the\ntrue practice slope is 2.5 score points per hour. Ten baseline points\nbelow that anchor, it is\n$2.5+0.12(-10)=1.3$ points per hour. Ten points above, it is\n$2.5+0.12(10)=3.7$ points per hour. The positive product coefficient\ndoes not say that practice changes baseline preparation, or vice versa;\nit says that the conditional mean surface is nonadditive.\n\nPractice hours and baseline scores are generated independently here so\nthat the interaction mechanics are transparent. Real educational data\nwould demand attention to attendance, access to support, prior courses,\nmeasurement reliability, clustering within classrooms or schools, and\nthe process by which practice time was chosen. None of those design\ncomplications is solved by fitting a product term.\n\n\nThe explicit seed makes this one sample reproducible. It does not make\nthe sample representative of a real population. The observed baseline\nrange is 42.8747 to\n96, and practice lies between\n0.0141 and\n7.9802 hours. Conditional estimates\noutside this rectangle would be extrapolations even though the generating\nequation is known to us.\n\nThe working object `sim` holds `score`, `hours`, `base` and\n`baseline_c = base - 70`. Generating the baseline, practice and independent\nerror in that order with seed 909 gives the declared sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(909)\nbase <- pmin(pmax(rnorm(320, 70, 10), 42), 96)\nhours <- runif(320, 0, 8)\nbaseline_c <- base - 70\nscore <- 60 + 2.5*hours + .4*baseline_c +\n  .12*hours*baseline_c + rnorm(320, 0, 5)\nsim <- data.frame(score, hours, base, baseline_c)\nm1 <- lm(score ~ hours * baseline_c, data = sim)\n```\n:::\n\n\nThe R formula uses `*` to include both lower-order terms and their\nproduct. The table below reports each estimate with its standard error\n(SE), the estimated standard deviation of that estimate across\nhypothetical repeated samples, and a 95% confidence interval.\n\n\n| Term | Target | Estimate | SE | 95% lower | 95% upper |\n|:--|--:|--:|--:|--:|--:|\n| Intercept | 60.00 | 59.6123 | 0.5550 | 58.5204 | 60.7043 |\n| Practice | 2.50 | 2.6972 | 0.1244 | 2.4524 | 2.9421 |\n| Centered baseline | 0.40 | 0.3822 | 0.0625 | 0.2593 | 0.5051 |\n| Practice by centered baseline | 0.12 | 0.1149 | 0.0139 | 0.0875 | 0.1422 |\n\n: One generated sample against its declared targets (seed 909, 320 rows). {#tbl-ch10-recovery tbl-colwidths=\"[34,14,14,12,13,13]\"}\n\n\nOne noisy sample does not reproduce every truth exactly. The fitted\npractice slope at baseline 70 is\n2.6972 points per\nhour, compared with the true value 2.5. The fitted interaction is\n0.1149\npoints per hour per baseline-score point, compared with the true value\n0.12. Its interval is\n[0.0875,\n0.1422]. The interval\nquantifies repeated-sample uncertainty under the fitted model; it does\nnot quantify every possible source of design or measurement error.\n\nThe fitted lower-order coefficient for centered baseline,\n0.3822, is the baseline\nscore slope when practice is zero. It is not a baseline-score slope\naveraged over all practice values. In an interaction model, every\nlower-order coefficient is conditional on the other component being at\nits coded zero or reference level.\n\n\n### The product block against the additive restriction\n\nThe reduced model is written first because it states the restriction\nbeing evaluated: one common practice slope and one common baseline\nslope. The full model releases the common-slope restriction by adding\nthe product.\n\n\nThe nested comparison gives\n\n$$\nF=\\frac{(RSS_R-RSS_F)/q}{RSS_F/(n-p)}\n=\\frac{(9108.7071-7488.7866)/1}{7488.7866/316}=68.3548,\n\\qquad p<.0001.\n$$\n\nHere $q=1$ added coefficient and $p=4$ total coefficients. The product\ncoefficient's $t=8.2677$ has the same squared statistic from full precision.\nBoth models use the same 320 outcomes.\n\nHere the product block has one degree of freedom because both predictors\nare continuous. The comparison asks whether allowing the practice slope\nto vary linearly with baseline score reduces residual variation beyond\nthe additive model. It does not test whether the entire model is true,\nwhether the relationship is causal, or whether the interaction is large\nenough to matter in a particular decision.\n\nIn the one-degree-of-freedom case, the block $F$ statistic equals the\nsquared $t$ statistic for the product coefficient. That identity does\nnot generalize to a factor with three levels: a continuous-by-three-level\nfactor interaction requires two product columns and a joint two-degree-\nof-freedom test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- lm(score ~ hours + baseline_c, data = sim)\nanova(m0, m1)\n```\n:::\n\n\n\n### Recentering leaves the surface alone\n\nThe centered model uses baseline 70 as zero. A raw-score model uses the\nunobserved and impossible baseline score zero as its anchor.\n\n\n| Quantity | Raw-score model | Centered model |\n|:--|--:|--:|\n| Coefficient of practice at the coded zero | $-5.3448$ | 2.6972 |\n| Lower-order baseline coefficient | 0.3822 | 0.3822 |\n| Product coefficient | 0.1149 | 0.1149 |\n| Product block $F$ | 68.3548 | 68.3548 |\n| Maximum fitted-value difference | below $10^{-12}$ | below $10^{-12}$ |\n\n: What centering changes and what it leaves alone. {#tbl-ch10-centering tbl-colwidths=\"[46,27,27]\"}\n\n\nThe raw model's practice coefficient is the fitted practice slope at a\nbaseline score of zero. Its unattractive value is not evidence that the\nmodel failed; it answers an unsupported question. After centering, the\npractice coefficient answers the supported question at baseline 70.\nThe product coefficient and every fitted value agree to numerical\nprecision.\n\nCentering can change the p-values of lower-order coefficients because it\nchanges the hypotheses they test. It should not change the one-degree-\nof-freedom product test in this corresponding model. A lower-order\np-value becoming smaller after centering is not repaired confounding;\nit is a different conditional comparison.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nraw <- lm(score ~ hours * base, data = sim)\nmax(abs(fitted(raw) - fitted(m1)))\n```\n:::\n\n\n\n## Probe the Conditional Comparison {#ch10-probe}\n\n\n### A conditional slope needs the covariance\n\nAt a centered baseline value $w$, the fitted practice slope is\n\n$$\n\\widehat\\beta_X(w)=\\widehat\\beta_X+w\\widehat\\beta_{XW}.\n$$\n\nBecause the two estimated coefficients are correlated, its variance is\nnot obtained by adding their variances alone:\n\n$$\n\\begin{aligned}\n\\operatorname{Var}\\{\\widehat\\beta_X(w)\\}\n={}&\\operatorname{Var}(\\widehat\\beta_X)\n+w^2\\operatorname{Var}(\\widehat\\beta_{XW})\\\\\n&+2w\\operatorname{Cov}\n(\\widehat\\beta_X,\\widehat\\beta_{XW}).\n\\end{aligned}\n$$ {#eq-simple-slope-variance}\n\nThe conditional-slope table applies this covariance formula to three\nmeaningful baseline scores. Each interval uses $t_{.975,316}=1.9675$.\n\n\n| Baseline score | Target slope | Fitted slope | SE | 95% lower | 95% upper |\n|:--|--:|--:|--:|--:|--:|\n| 60 | 1.3 | 1.5484 | 0.1780 | 1.1982 | 1.8986 |\n| 70 | 2.5 | 2.6972 | 0.1244 | 2.4524 | 2.9421 |\n| 80 | 3.7 | 3.8461 | 0.1947 | 3.4630 | 4.2291 |\n\n: Conditional practice slopes at three supported baseline scores, with their declared targets. {#tbl-ch10-slopes tbl-colwidths=\"[20,16,16,12,18,18]\"}\n\n\nThe estimated practice association rises from\n1.5484 points per hour at baseline 60\nto 3.8461 points per hour at baseline\n80. These are three evaluations of one fitted surface, not three\nseparate regressions and not evidence that students belong to three\nlatent types.\n\nThe `emtrends()` function in the `emmeans` package calculates these\nconditional trends and their covariance-based intervals directly.\n\n\nAgreement with the manual table is a computational check. The software\ndoes not choose defensible probe values. That responsibility remains\nwith the analyst.\n\nFor the slope at centered baseline $w=10$, applying the variance formula\nto the full-precision covariance matrix gives variance 0.0379 and\nSE 0.1947. Keep the entries at their stored precision until the final\nresult is reported: early rounding of small covariance terms can alter\nthe reconstructed SE.\n\nOmitting covariance gives 0.1865. Adding the focal SE to ten times the\nproduct SE gives 0.2634. Neither computes the uncertainty of the fitted\nlinear combination. A short contrast-vector calculation includes every\nneeded covariance automatically:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb <- coef(m1); V <- vcov(m1)\ncvec <- c(0, 1, 0, 10)  # intercept, hours, baseline_c, product\nsum(cvec * b)\nsqrt(drop(cvec %*% V %*% cvec))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans::emtrends(m1, ~ baseline_c, var = \"hours\",\n  at = list(baseline_c = c(-10, 0, 10)))\n```\n:::\n\n\n\nA **simple slope** fixes the moderator and reads the focal comparison\nfrom the whole fitted model. For a two-hour comparison, multiply the\nslope and both endpoints by two: the fitted differences are 3.0969 at\nbaseline 60 and 7.6923 at baseline 80. A different practice interval\nchanges that multiplier, not the fitted relationship.\n\nNow ask the interaction question directly: how much greater is the\npractice slope at 80 than at 60? Because both slopes use the same model,\nthe focal coefficient cancels:\n\n$$\n\\widehat\\beta_X(10)-\\widehat\\beta_X(-10)\n=20\\widehat\\beta_{XW}=2.2977,\n\\qquad SE=20\\,SE(\\widehat\\beta_{XW})=0.2779.\n$$\n\nThe 95% interval is [1.7509, 2.8445]. This compares **two slopes**, whereas\neach row of @tbl-ch10-slopes compares **one slope with zero**. Their\nuncertainty calculations answer different questions. In general,\n$\\operatorname{Var}(\\widehat s_2-\\widehat s_1)=\n\\operatorname{Var}(\\widehat s_2)+\\operatorname{Var}(\\widehat s_1)\n-2\\operatorname{Cov}(\\widehat s_2,\\widehat s_1)$.\nThe two slope estimates share coefficients; subtracting interval\nendpoints or adding their SEs ignores that relationship.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n20 * coef(m1)[\"hours:baseline_c\"]\n20 * confint(m1)[\"hours:baseline_c\", ]\n```\n:::\n\n\nA large simple slope can coexist with zero interaction: both preparation\nlevels might have the same strong practice association. Conversely, a\nchanging slope can pass through zero at one baseline. Neither a test\nagainst zero at a chosen probe nor two separate significance labels\nreplace a direct slope contrast [@gelman2006].\n\n### Choosing probe values and showing where the data are\n\nThe **pick-a-point** approach — also called the analysis of simple\nslopes — evaluates conditional slopes at a small set of substantively\nchosen moderator values [@aiken1991; @hayes2022]. There is no rule that\nthese values must be the mean and one standard deviation above and below\nit. Those values may be\nuninterpretable, outside the data, or different across studies. Better\nchoices come from the measurement scale and the research question:\npolicy thresholds, clinically or educationally meaningful cutoffs,\nprespecified percentiles, or values needed for an actual decision.\n\nThe 60, 70, and 80 probes work here because baseline score has an\ninterpretable unit and all three values are well supported. A complete\nreport also displays the moderator distribution rather than presenting\nthe probes as if observations were equally dense everywhere.\n\n\n### The conditional-slope curve is the primary display\n\nThree probe values are readings of one\ncontinuous object: the fitted conditional slope\n$\\widehat\\beta_X(w)=\\widehat\\beta_X+w\\widehat\\beta_{XW}$ with its pointwise\nband, drawn over the moderator values the data actually support. That\ncurve, not a boundary number, is the primary display for a continuous\nmoderator [@bauer2005; @hayes2022]. The marked zero-crossing boundaries are explained in Section 3.4.\nTheir position relative to the observed support matters as much as\ntheir numerical value in @fig-ch10-slope-curve.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Fitted practice slope across the supported baseline-score range with a 95% pointwise band. Dashed vertical lines mark the two Johnson-Neyman boundaries, the shaded panel marks baseline scores below the smallest generated value, and the rug shows the observed baseline distribution.](chapter_10_files/figure-html/fig-ch10-slope-curve-1.png){#fig-ch10-slope-curve fig-pos='!ht' fig-alt='The fitted practice slope rises almost linearly from slightly below zero at the lowest observed baseline score to nearly six score points per hour at the highest. Its confidence band leaves zero at the upper Johnson-Neyman boundary near baseline 51, while the lower boundary near baseline 39 sits inside the shaded unsupported region where no data exist.' width=604.8}\n:::\n:::\n\n\n\nRead left to right, the curve tells one continuous story rather than\nthree separate group findings. At the lowest supported baseline scores\nthe fitted slope is slightly negative — about\n$-0.4191$ score points per hour — and\nits band covers zero. The band leaves zero at the upper boundary,\n51.284, and the slope then rises steadily to\nabout 5.6843 score points per hour\nat the highest observed baseline score. The three pick-a-point probes are\nthree readings of this same curve. The band widens toward both ends\nbecause a conditional slope evaluated far from the centering value\nborrows heavily from the product coefficient, whose own uncertainty is\nthen multiplied by a large $w$.\n\nMarking the boundaries on the curve also makes the support limitation visible\nrather than hidden in a table: the lower boundary sits inside the shaded\npanel, where no student was generated, so nothing in these data speaks to\nit.\n\n\n### Levels, cases and the limit of the algebra\n\nA slope compares changes; a fitted mean describes a level. At four\npractice hours and baseline 70, the fitted mean is 70.4013 with mean-response\ninterval [69.8644, 70.9382]. The new-case interval [60.8082, 79.9944] is\nwider because it also includes individual error variance. At baselines 60\nand 80, the fitted means are 61.9836 and 78.8189. Precision about a mean\ndoes not imply precise prediction of each student.\n\nA **Johnson-Neyman** calculation searches the moderator continuum for\nvalues at which a pointwise confidence interval for a conditional slope\ntouches zero, and it labels the values on one side of those boundaries a\n**region of significance** [@johnson1936; @bauer2005; @hayes2022]. It can\ncomplement pick-a-point probes when the moderator is genuinely continuous\nand no small set of theory-based values captures the question. It\nreplaces neither the conditional-slope curve, the magnitude estimates,\nnor the support audit.\n\nFor this fitted curve the pointwise interval excludes zero below baseline\n39.039 and above 51.284; between these values it covers zero. Appendix A\nshows how the boundary equation and its sign determine those regions.\nThe figure lets us check what those numbers mean before interpreting them.\n\nThis example reveals a support\nlimitation that a pair of printed roots would conceal. The lower boundary,\n39.039, lies below the smallest generated\nbaseline score, 42.8747, so\n0 of the 320 simulated\nstudents fall in the “significantly negative” region: it exists in the\nalgebra and nowhere in the data. The upper boundary,\n51.284, does lie inside the observed range, and\n313 students\n(97.8125 percent\nof the sample) sit above it. The supported reading is therefore\none-sided: across almost the entire baseline range these data cover, the\npractice slope is positive and separated from zero, and only a thin\nlow-baseline sliver of\n7 students falls in the\ninterval-covers-zero region.\n\nAny boundary is descriptive of that fitted model and its pointwise\nprocedure. Scanning many moderator values raises multiplicity questions;\na pointwise band is not a simultaneous band. A root outside the observed\nrange has no empirical support, and a root inside a sparse tail may still\nbe unstable. The phrase “region of significance” can also distract from\nmagnitude and uncertainty. Pick-a-point answers questions at chosen\nvalues; Johnson-Neyman locates model-based zero-crossing boundaries.\nNeither method discovers a uniquely correct moderator cutoff, protects\nagainst specification search, or supplies simultaneous error control\n[@preacher2006].\n\n\nA **simultaneous band** answers a wider question: does one band cover the\nentire conditional-slope curve? Under the correctly specified linear model\nwith independent Normal errors of constant variance, a Scheffé band for\nthe two coefficients determining that curve replaces 1.9675 by\n$\\sqrt{2F_{.95;2,316}}=2.4594$ in the estimate-plus-or-minus-SE calculation.\nIt is wider because its coverage applies jointly to every linear\ncombination of those two coefficients, hence every conditional slope.\nThe two counts the dimensions of this slope family, not all four\ncoefficients in the fitted mean model. Showing only the supported range\nmakes the display useful; it does not validate extrapolation. Section 6.4\ncompares this band with pointwise intervals from two calculations.\n\n\n## Continuous by Categorical: Rank-Specific Slopes {#ch10-salary}\n\n\n### The question, the records and the analysis sample\n\nThe sustained empirical question is:\n\n> Among the faculty of this college in 2008-09, how does the linear\n> association between years of service and mean nine-month salary differ\n> across the assistant, associate, and full professor ranks?\n\nEach row is one faculty member. The outcome is nine-month salary,\nrescaled to thousands of dollars. The focal continuous predictor is\nyears of service at the institution. Rank is a three-level categorical\npredictor. The target is a rank-conditional descriptive association and\nconditional mean prediction within observed support. It is not a return\nto loyalty, a promotion effect, or a claim about faculty salaries in\ngeneral.\n\n::: {.callout-note title=\"Data and software source\"}\n\nThe `Salaries` data are called directly from the\n[`carData` package](https://cran.r-project.org/package=carData)\n([package DOI](https://doi.org/10.32614/CRAN.package.carData)), which\ndocuments them as the 2008-09 nine-month salaries of the assistant,\nassociate, and full professors at one U.S. college, collected as part of\nthe administration's ongoing monitoring of salary differences between\nmale and female faculty [@carData2022; @fox2019]. This chapter uses only\nthe package-distributed data and does not copy a local data file. One college\nin one year is not a probability sample of academia, so all inferential\nlanguage below is bounded to these faculty under the working model.\n\nConditional trends are computed with the official\n[`emmeans` package](https://rvlenth.github.io/emmeans/), whose\n`emtrends()` function evaluates fitted slopes from a model reference\ngrid. The chapter also verifies key calculations from the fitted\ncoefficient vector and covariance matrix.\n:::\n\nThe package dataset has 397 rows. The analysis rule is fixed before\nmodel fitting: retain a row only when salary, years of service, and rank\nare all observed, and use exactly the same rows for the additive and\ninteraction models. Completeness is verified rather than assumed.\n\n\nThe fixed analytic sample contains 397 faculty members:\n67 assistant professors,\n64 associate professors, and\n266 full professors. Here the\ncomplete-case rule excludes nothing, but stating and checking it is\nstill part of a prespecified analysis: the audit is what shows the rule\nto be harmless rather than an untested assumption.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd0 <- carData::Salaries\ndat <- d0[complete.cases(d0[c(\"salary\", \"yrs.service\", \"rank\")]), ]\ndat$rank <- droplevels(dat$rank)\ndat$salary_k <- dat$salary/1000\ndat$service_c <- dat$yrs.service - 5\n```\n:::\n\n\n\n### Support first: where each rank actually lives\n\nAn interaction graph can tempt analysts to compare fitted lines where a\nrank has few or no observations. Support must therefore be examined\nwithin ranks, not only in the pooled sample.\n\n\n| Rank | $n$ | Minimum | First quartile | Median | Third quartile | Maximum | Mean salary | SD |\n|:--|--:|--:|--:|--:|--:|--:|--:|--:|\n| Assistant | 67 | 0 | 1 | 3 | 3 | 6 | 80.7760 | 8.1741 |\n| Associate | 64 | 1 | 7 | 8 | 11 | 53 | 93.8764 | 13.8317 |\n| Full | 266 | 0 | 15 | 21 | 30 | 60 | 126.7721 | 27.7187 |\n\n: Years-of-service support and salary summaries by rank (thousand dollars). {#tbl-ch10-support tbl-colwidths=\"[14,8,11,15,10,16,11,9,6]\"}\n\n\nThe support asymmetry here is extreme, and it is the most important fact\nin this analysis. Assistant professors span only\n0 to\n6 years of\nservice, while associate and full professors extend past fifty years.\nThe range common to all three ranks is only\n1 to 6 years.\nWhatever the model later reports about the assistant-professor slope is\nestimated from that six-year window; the model can say nothing about\nassistant professors with long service because none appear in these data.\nThe dataset cannot establish whether such faculty existed at the college\noutside the recorded observations.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Rank-specific years-of-service support. Thick segments show interquartile ranges, thin segments show observed ranges, and points mark medians.](chapter_10_files/figure-html/fig-ch10-support-1.png){#fig-ch10-support fig-pos='!ht' fig-alt='Assistant-professor service years span only zero to six, while associate and full professors extend past fifty years. Only the narrow interval from one to six years is common to all ranks.' width=604.8}\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(dat$yrs.service, dat$rank, range)\n```\n:::\n\n\n\n### The centered model and its two product columns\n\nThe model centers years of service at 5:\n\n$$\nS_c=S-5.\n$$\n\nThis anchor lies in the observed range of all three ranks — it is inside\neven the narrow assistant-professor window. It is chosen so that rank\nlower-order coefficients represent salary differences at a supported\ncommon service value. It is not chosen to force a desired p-value or to\nmake the ranks comparable in every other respect.\n\nWith assistant professor as the reference level, the model is\n\n$$\n\\begin{aligned}\nE(Y\\mid S_c,R)={}&\\beta_0+\\beta_SS_c\n +\\beta_A I(R=\\text{AssocProf})\\\\\n&+\\beta_P I(R=\\text{Prof})\n +\\beta_{SA}S_c I(R=\\text{AssocProf})\\\\\n&+\\beta_{SP}S_c I(R=\\text{Prof}).\n\\end{aligned}\n$$ {#eq-salary-interaction}\n\nThe three lines have the following interpretations:\n\n$$\n\\begin{array}{ll}\n\\text{Assistant:}&\\beta_0+\\beta_SS_c,\\\\\n\\text{Associate:}&(\\beta_0+\\beta_A)+(\\beta_S+\\beta_{SA})S_c,\\\\\n\\text{Professor:}&(\\beta_0+\\beta_P)+(\\beta_S+\\beta_{SP})S_c.\n\\end{array}\n$$\n\nThe two product coefficients are slope differences from the assistant\nrank. They are not the associate and full-professor slopes themselves.\n\n\n| Conditional term | Estimate | SE | 95% lower | 95% upper |\n|:--|--:|--:|--:|--:|\n| Assistant mean salary at 5 years | 82.8231 | 5.8693 | 71.2837 | 94.3625 |\n| Assistant slope | 0.7793 | 1.9452 | $-3.0450$ | 4.6036 |\n| Associate $-$ assistant at 5 years | 13.7977 | 6.8835 | 0.2644 | 27.3310 |\n| Full $-$ assistant at 5 years | 46.0748 | 6.4445 | 33.4046 | 58.7449 |\n| Associate $-$ assistant slope | $-1.1740$ | 1.9674 | $-5.0420$ | 2.6940 |\n| Full $-$ assistant slope | $-0.8986$ | 1.9492 | $-4.7309$ | 2.9336 |\n\n: Coefficients of the service-by-rank interaction model, read at their own anchors. {#tbl-ch10-salary-fit tbl-colwidths=\"[38,14,12,18,18]\"}\n\n\nAt five years of service, the fitted mean salary for assistant\nprofessors is\n82.8231 thousand\ndollars. The fitted associate-minus-assistant difference at that service\nvalue is\n13.7977 thousand\ndollars, with an interval from\n0.2644 to\n27.331. The fitted\nprofessor-minus-assistant difference is\n46.0748 thousand dollars,\nwith an interval from 33.4046 to\n58.7449.\n\nThose are conditional comparisons at one service value. They are not\noverall rank differences and are not comparisons at each rank's typical\nservice. The product terms further show that the associate slope differs\nfrom the assistant slope by an estimated\n$-1.174$\nthousand dollars per year, while the professor slope differs by\n$-0.8986$ — both\nwith wide intervals, dominated by the six-year assistant support window.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns1 <- lm(salary_k ~ service_c * rank, data = dat)\ncoef(s1)\n```\n:::\n\n\n\n### The two-degree-of-freedom product block\n\nBecause rank has three levels, its interaction with one continuous\npredictor contributes two columns. The appropriate nested comparison\ntests them jointly, and this omnibus block question comes before any\nexamination of individual slopes or their pairwise differences.\n\n\n| Variance procedure | Numerator df | Denominator df | $F$ | $p$ |\n|:--|--:|--:|--:|--:|\n| Classical nested-model $F$ | 2 | 391 | 0.4860 | .6155 |\n| Approximate HC3 joint Wald $F$ | 2 | 391 | 1.3138 | .2700 |\n\n: Classical and approximate robust tests of the two-column service-by-rank product block. {#tbl-ch10-blocks tbl-colwidths=\"[40,16,18,13,13]\"}\n\n\nThe block comparison gives\n$F(2, 391)=\n0.486$,\n$p=.6155$. Under the linear-model working\nassumptions, the data provide no clear evidence against one common\nservice slope for the three ranks. That is a statement about what these\ndata can distinguish, not a demonstration that the three slopes are\nequal — the later interval estimates show how wide a range of slope\ndifferences remains compatible. The test also does not say whether the\nlines are exactly linear or whether rank causally changes the salary\nreturn to service.\n\nAn approximate joint Wald sensitivity check using the HC3 covariance matrix — the\nestimator named in the chapter box, which keeps the ordinary least\nsquares (OLS) coefficients that minimize the residual sum of squares but\nrebuilds their covariance from leverage-adjusted squared residuals\ninstead of one pooled variance [@long2000] — gives\n$F(2,\n391)=\n1.3138$,\n$p=.27$. Dividing the robust Wald statistic by\nthe number of restrictions and comparing it with an $F$ distribution using\nthe residual degrees of freedom is a transparent finite-sample approximation,\nnot an exact robust $F$ reference result. The robust and classical block\nprocedures therefore support the same bounded conclusion here, although\nthe p-values differ because the procedures use different variance models,\nnot because the fitted slopes changed.\n\nThe order of `anova(reduced, full)` matters for readable output and for\nthe narrative. Both models must use the same response and exactly the\nsame rows. If the full model silently loses more observations because a\nnew variable is missing, the models are not nested on a common dataset\nand the comparison no longer answers the intended block question. Here\nthe analysis sample was fixed once, before fitting, so the printed row\ncounts agree by construction.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ns0 <- lm(salary_k ~ service_c + rank, data = dat)\nanova(s0, s1)\n```\n:::\n\n\n\n### Rank-specific slopes and their comparisons\n\nWith the joint block assessed, the rank slopes are more direct than the\nreference-coded product coefficients. `emtrends()` obtains the fitted\nservice trend within each rank.\n\n\n| Rank | Slope (thousand dollars per year) | SE | 95% lower | 95% upper |\n|:--|--:|--:|--:|--:|\n| Assistant | 0.7793 | 1.9452 | $-3.0450$ | 4.6036 |\n| Associate | $-0.3947$ | 0.2949 | $-0.9744$ | 0.1850 |\n| Full | $-0.1193$ | 0.1253 | $-0.3656$ | 0.1270 |\n\n: Rank-specific fitted service slopes with covariance-based standard errors. {#tbl-ch10-rank-slopes tbl-colwidths=\"[20,34,14,16,16]\"}\n\n\nWithin the observed rank-specific ranges, one additional year of service\nis associated with an estimated mean salary difference of about\n0.7793\nthousand dollars for assistant professors,\n$-0.3947$\nfor associate professors, and\n$-0.1193$\nfor full professors. Every classical interval includes zero, and the\nassistant-professor interval is several times wider than the others —\nits slope is estimated from a six-year window. The rank, unit, support and associational reading belong together. The\nslightly negative continuing-rank estimates are compatible with cohort\nand market effects that these cross-sectional data cannot separate from\nservice itself.\n\nPairwise slope differences address a different family of questions. We\nuse a Tukey-style adjustment for the three pairwise comparisons; the\nprespecified omnibus block test reported above remains the primary check\nof whether slopes vary somewhere across ranks.\n\n\\Needspace{8\\baselineskip}\n\n\nThe adjusted $p$-values are 0.8220, 0.8895 and 0.6661 for associate-minus-assistant,\nfull-minus-assistant and full-minus-associate slopes. The multiplier is\n2.3527 on 391 degrees of freedom. This calibration is approximate for\nunequal slope-estimation variances, rather than the exact balanced\none-way Tukey result. No pairwise slope contrast is distinguishable from zero, in agreement\nwith the omnibus block. This coherent presentation — an omnibus check,\nthen interval estimates for every slope and contrast — is more\ninformative than announcing that one reference-coded product term is\nsmall and another is not.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans::emtrends(s1, ~ rank, var = \"service_c\")\n```\n:::\n\n\n\n### Coordinates, common-value contrasts and the picture\n\nTo verify that claim, refit the salary model with full professor as the\nreference rank. Coefficient labels and lower-order interpretations\nchange, but the fitted surface does not.\n\n\nThe maximum fitted-value difference is numerical noise. Reference coding\nchanges which line is described directly by $\\beta_0$ and $\\beta_S$ and\nwhich slope differences appear as product coefficients. It does not\nchange the three lines, residuals, predictions, or the interaction-block\ntest.\n\nThe same principle applies to centering years of service. Had we\ncentered at 3 instead of 5 years, rank lower-order coefficients would\ncompare fitted means at 3 years. The slopes and slope differences would\nremain the same. An analyst should choose the anchor before looking for\na more favorable coefficient table.\n\n| Question | Quantity | Salary example |\n|:--|:--|:--|\n| How does salary vary with service within a rank? | Conditional slope | $-0.1193$ thousand dollars per year for full professors |\n| How do ranks differ at one common service value? | Conditional mean contrast | Full $-$ assistant 46.0748 at 5 years |\n| What mean salary does the model fit for a rank and service value? | Conditional mean | Associate 96.6208 at 5 years |\n| What range is plausible for one new case under the model? | New-case interval | [49.6127, 143.6288] for one associate at 5 years |\n| Is one common slope adequate across the ranks? | Product-block test | $F(2,391)=0.486$ |\n\n: Four conditional questions and one block question, each with its own quantity. {#tbl-ch10-question-map tbl-colwidths=\"[38,22,40]\"}\n\nAt two, three, five and six service years, the fitted full-minus-assistant\nsalary contrasts are 48.7706, 47.8720, 46.0748 and 45.1762 thousand dollars,\nwith SEs 4.2152, 4.2532, 6.4445 and 8.0405. These are linked readings of\none fitted surface, all inside the common service window. Their uncertainty\ngrows toward the edge of the short assistant range.\n\nA single grid from the pooled minimum to pooled maximum would draw the\nassistant-professor line across fifty unsupported years. The plotted prediction\ngrid uses the minimum and maximum service within each rank.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Rank-specific fitted mean salary with 95% mean-response bands. Each line and band stop at that rank's observed service limits.](chapter_10_files/figure-html/fig-ch10-salary-fitted-1.png){#fig-ch10-salary-fitted fig-pos='!ht' fig-alt='Three nearly flat rank-specific salary lines sit at clearly different levels. The assistant-professor line and band cover only zero to six years of service, while the other lines extend past fifty years. No line is extended beyond its rank\\'s observed range.' width=604.8}\n:::\n:::\n\n\n\nThe visual and the trend table agree: rank differences in salary level\ndominate, the fitted within-rank service trends are close to flat, and\nthe assistant-professor line is both short and imprecisely estimated.\nThe graph also keeps a limitation visible that a coefficient table can\nhide: the ranks occupy drastically different parts of the service range.\nThe model estimates each within-rank slope from its own support; a\ncross-rank comparison at a particular service value is most credible\ninside the narrow common support of\n1 to 6 years.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(s1, newdata = data.frame(service_c = 0,\n  rank = factor(\"AssocProf\", levels = levels(dat$rank))),\n  interval = \"confidence\")\n```\n:::\n\n\n\n## Factor by Factor: Cell Means Revisited {#ch10-cells}\n\n\n### Two factors: the same nonadditive question\n\nWhen both predictors are factors, an interaction is nonadditivity among\ncell means. The `carData::Moore` data provide a compact\nillustration from social psychology: 45 participants in a conformity\nexperiment [@moore1971], with the number of conforming\nresponses as the outcome, the manipulated status of a partner (low or\nhigh) as one factor, and the participant's measured authoritarianism\ncategory (low, medium, or high F-scale score) as a three-level factor.\nThe package documentation describes partner status as manipulated but\ndoes not document random assignment or the full experimental protocol;\nthe example therefore treats it as an experimental-condition contrast\nrather than assuming causal identification from the dataset description\nalone.\nThis example is separate from the salary analysis and is not needed for\nits conclusions. Under the classical common-variance linear model, its\nproduct block is statistically detectable; the conclusion is sensitive\nto the variance model and outcome scale, as shown below. The cell\nsummary reports, for each of the six cells, its size, its mean number of\nconforming responses, and its standard deviation (SD), the typical\ndistance of a participant's score from that cell's mean.\n\n\n| Authoritarianism | Partner status | $n$ | Mean conformity | SD |\n|:--|:--|--:|--:|--:|\n| Low | Low | 10 | 8.9000 | 2.6437 |\n| Low | High | 5 | 17.4000 | 4.5056 |\n| Medium | Low | 4 | 7.2500 | 3.9476 |\n| Medium | High | 11 | 14.2727 | 3.9520 |\n| High | Low | 8 | 12.6250 | 7.3473 |\n| High | High | 7 | 11.8571 | 3.9340 |\n\n: Conformity cell counts, means and standard deviations. {#tbl-ch10-moore-cells tbl-colwidths=\"[24,20,10,24,22]\"}\n\n\nAn additive factor model requires the partner-status difference to be\nthe same at every authoritarianism level. The product model allows that\ndifference to vary. Its factor levels are ordered low, medium, high for\nauthoritarianism and low, high for partner status.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Moore conformity cell means by partner status and authoritarianism category. The status difference is large at low and medium authoritarianism and essentially absent at high authoritarianism, a crossing nonadditive profile.](chapter_10_files/figure-html/fig-ch10-moore-cells-1.png){#fig-ch10-moore-cells fig-pos='!ht' fig-alt='Mean conformity is much higher with a high-status partner among low- and medium-authoritarianism participants, but the two partner-status lines meet at the high-authoritarianism category.' width=604.8}\n:::\n:::\n\n\n\n### The block, simple differences and interaction contrast\n\nThe block has two degrees of freedom because a three-level\nauthoritarianism factor contributes two indicator columns and therefore\ntwo product columns. No middle category is discarded to manufacture a\n2-by-2 table. The classical test gives\n$F(2, 39)=\n4.1846$,\n$p=.0226$, whereas the approximate HC3\njoint Wald test gives $F(2,\n39)=\n2.8294$,\n$p=.0712$. The cells are small and unbalanced,\ntheir spreads differ, and conformity is a bounded count. Ordinary linear\nmodel inference is therefore a working approximation here, not a\nscale-robust verdict. The cell-mean pattern remains pedagogically useful;\nthe strength of inferential evidence must be reported as\nvariance-model-sensitive.\n\nFor any two authoritarianism categories, a **statistical\ndifference-in-differences (DiD)** — the difference between two group\ndifferences — is an interaction contrast. Comparing the low and high\ncategories gives\n\n$$\n\\begin{aligned}\n\\widehat C_{\\mathrm{DD}}={}&(\\bar y_{\\text{low},H}-\\bar y_{\\text{low},L})\\\\\n&-(\\bar y_{\\text{high},H}-\\bar y_{\\text{high},L}),\n\\end{aligned}\n$$\n\nwhere $H$ and $L$ denote high- and low-status partners.\n\n\nThe contrast is 9.2679 conforming responses: the\npartner-status difference is about\n8.5\nresponses among low-authoritarianism participants and about\n$-0.7679$\namong high-authoritarianism participants. Algebraically it is a\nproduct-term contrast. Partner status is described as manipulated, but\nthe package documentation alone does not establish random assignment,\nimplementation fidelity, or the absence of post-assignment complications.\nThe status comparison should therefore be described as an\nexperimental-condition contrast unless the original study documentation\nsupplies those warrants. Authoritarianism is measured rather than\nassigned, so any variation of the status contrast across F-scale\ncategories also depends on observational group comparability. In a policy\nor before-after study, a causal difference-in-differences\ninterpretation would additionally require a defensible treatment and\ntiming design, a counterfactual trend argument such as parallel trends,\nabsence of relevant anticipatory or spillover behavior, and uncertainty\nappropriate to the assignment and dependence structure. Those\ndesign-based methods are outside this chapter.\n\n### What the difference of differences does not carry\n\n::: {.callout-warning title=\"Statistical interaction is not a causal design\"}\n\nA product term describes nonadditivity in a model. Causal interpretation\ncomes from design and assumptions outside the coefficient algebra. The\nsame product term can appear in an observational cross-section, a\nrandomized factorial experiment, or a longitudinal policy comparison;\nthose settings do not inherit the same causal meaning.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoore <- carData::Moore\nwith(moore, tapply(conformity, list(fcategory, partner.status), mean))\nc1 <- lm(conformity ~ partner.status * fcategory, data = moore)\n```\n:::\n\n\nFor low versus high authoritarianism, the interaction contrast is\n\n$$\n\\widehat C_{\\mathrm{DD}}\n=(\\bar y_{\\mathrm{low},H}-\\bar y_{\\mathrm{low},L})\n-(\\bar y_{\\mathrm{high},H}-\\bar y_{\\mathrm{high},L})\n=\\mathbf c{}^{\\mathsf T}\\widehat{\\boldsymbol\\beta}=9.2679,\n\\qquad SE=\\sqrt{\\mathbf c{}^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf c}=3.4507.\n$$\n\nThe classical pointwise interval is [2.2883, 16.2475]. If this comparison\nwas selected after inspecting the cell pattern, the comparison family\nneeds a simultaneous calibration as in Chapter 4; an attractive contrast\nis not retroactively prespecified.\n\n## Check, Qualify and Resample {#ch10-checks}\n\n\n### Where the model is likely to strain\n\nThe salary interaction model assumes an adequately linear conditional\nmean within each rank, independent information from the modeled rows,\nand sufficient joint service-by-rank support. Classical standard errors\nand prediction intervals additionally use a common residual variance;\nsmall-sample exact $t$ and $F$ results use a conditional Normal-error\nmodel. Leverage and influence matter because product columns can make\nsparse predictor combinations especially consequential. Residual plots\ndo not certify these assumptions; they show where parts of the\napproximation may be incomplete [@fox2016; @gelman2020].\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residuals versus fitted values for the salary interaction model. Points are marked by rank and the smooth summarizes remaining mean pattern.](chapter_10_files/figure-html/fig-ch10-salary-residuals-1.png){#fig-ch10-salary-residuals fig-pos='!ht' fig-alt='Residuals scatter around zero across fitted salary, with visibly larger spread at the higher fitted values that belong mostly to full professors.' width=604.8}\n:::\n:::\n\n\n\nThe residual-versus-fitted plot should be read with the raw plot and\nsupport display. Ranks occupy different fitted ranges, and residual\nspread is visibly larger at professor-level fitted values, so the\ncommon-variance working assumption deserves the HC3 sensitivity check\nbelow rather than silent acceptance.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Normal quantile plot of standardized residuals from the salary interaction model. Tail departures matter most for small-sample interval calibration and unusual cases.](chapter_10_files/figure-html/fig-ch10-salary-qq-1.png){#fig-ch10-salary-qq fig-pos='!ht' fig-alt='Standardized residuals track a reference line through most of the distribution with heavier departures in the upper tail.' width=604.8}\n:::\n:::\n\n\n\nThe Q-Q plot is an approximation check, not a requirement that the\nsalaries themselves be Normally distributed. The linear-model assumption\nconcerns the conditional errors used for exact small-sample reference\nresults.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntapply(residuals(s1), dat$rank, sd)\nplot(fitted(s1), residuals(s1))\nabline(h = 0, lty = 2)\n```\n:::\n\n\n\n### The same slopes under a different covariance\n\nThe HC3 standard errors introduced with the block test replace the\ncommon-variance coefficient covariance matrix with a leverage-adjusted,\nresidual-based estimate while retaining the OLS coefficients and the\nfitted mean model [@long2000; @zeileis2004]. Standard errors, approximate\nintervals, and approximate joint Wald tests derived from that matrix can\nchange. Applied to the rank-specific trends, they are a sensitivity analysis\nfor uncertainty, not a repair for a wrong conditional mean and not a license\nto ignore dependence.\n\n\\Needspace{8\\baselineskip}\n\n\n| Rank | Slope | Classical SE | HC3 SE | Approximate HC3 lower | Approximate HC3 upper |\n|:--|--:|--:|--:|--:|--:|\n| Assistant | 0.7793 | 1.9452 | 0.8686 | $-0.9284$ | 2.4870 |\n| Associate | $-0.3947$ | 0.2949 | 0.1679 | $-0.7248$ | $-0.0645$ |\n| Full | $-0.1193$ | 0.1253 | 0.1884 | $-0.4898$ | 0.2512 |\n\n: Rank-specific slopes under the classical and HC3 coefficient covariances. {#tbl-ch10-hc3 tbl-colwidths=\"[16,12,18,12,21,21]\"}\n\n\nHere the two variance treatments disagree in an instructive way. The\nHC3 standard errors are smaller for the two junior ranks — whose\nresidual spread is below the pooled level — and larger for full\nprofessors. The approximate HC3 sensitivity interval for the\nassociate-professor slope excludes zero\nwhile the classical interval does not. A borderline conclusion that\nmoves when the variance model changes should be reported as sensitive,\nnot resolved by quietly choosing whichever calculation looks better.\nThere is a second trap here. Under HC3 the associate slope interval\nexcludes zero and the full-professor interval covers zero. That does not\nshow that the two slopes differ. Their directly estimated\nassociate-minus-full contrast is $-0.2754$, with approximate HC3 SE\n0.2524 and interval [$-0.7716$, 0.2209] using the same residual-df\nreference ($p=.2759$). The interval leaves substantial uncertainty about\nthe direction of the slope difference. Comparing two labels discards the\nvery covariance that the contrast needs; its nonrejection also does not\nestablish equal slopes.\n\nNeither calculation repairs the fitted mean, the design, or the\ndependence structure.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV <- sandwich::vcovHC(s1, type = \"HC3\")\ncvec <- c(0, 1, 0, 0, 1, 0)  # associate slope\nsqrt(drop(cvec %*% V %*% cvec))\n```\n:::\n\n\n\n### Influence and a competing explanation\n\nThe most influential row is a full professor with\n60 years of service and a salary of\n192.253 thousand dollars — a\nlong-service, high-leverage point at the far edge of the professor\nrange. Omitting it moves the professor slope slightly and leaves the\nother slopes essentially unchanged; the largest Cook's distance is\nsmall, and the broad pattern of imprecise, overlapping slopes remains.\nThis leave-one-out fit is a sensitivity description. Deletion would\nrequire a documented recording error, an explicit target-population\nrule, or another substantive reason independent of Cook's distance.\n\nIf the true relationship is curved and ranks occupy different ranges,\nseparate straight lines can appear to have different slopes even when\nthe same curved function applies. A compact sensitivity model adds one\ncommon quadratic service term while retaining the full lower-order\ninteraction structure.\n\n\nThis one-degree-of-freedom check provides little evidence that a shared\nquadratic term materially improves the fitted mean. It does not prove\nthat every rank relationship is exactly linear. Rank-specific curvature\nwould require additional terms and, for assistant professors,\nsubstantially more support than a six-year window can offer. A\nsensitivity model should clarify a plausible failure mode, not become an\nunrestricted search for significance.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwhich.max(cooks.distance(s1))\nanova(s1, lm(salary_k ~ service_c * rank + I(service_c^2), dat))\n```\n:::\n\n\n\n### Bootstrap the conditional comparison\n\nResampling follows the question. For the generated students, that\nquestion is the practice slope at baseline 60, 70 or 80, or the difference\nbetween two such slopes. One complete-row resample supplies one new fit,\nand that fit supplies **all** these answers. Resampling each data column\nseparately would destroy the observed association. Resampling the two\nslopes separately would destroy their shared estimation uncertainty.\n\nTreating the generated student rows as independent and identically\ndistributed, draw 320 complete rows with replacement and refit the same\nhierarchical model. Repeat 2,000 times with seed 90910. This approximates\nrepeating the sampling and fitting process for the stated slope\nestimands; it does not generate new independent evidence [@efron1993;\n@freedman1981]. The three distributions in @fig-ch10-bootstrap-slopes\ncontain estimates, not individual students' scores. Their centers and\nwidths differ because the three probes ask different conditional\nquestions of the same records.\n\n| Baseline | Original slope | Bootstrap SE | Percentile lower | Percentile upper |\n|:--|--:|--:|--:|--:|\n| 60 | 1.5484 | 0.1764 | 1.1866 | 1.8790 |\n| 70 | 2.6972 | 0.1262 | 2.4532 | 2.9328 |\n| 80 | 3.8461 | 0.1954 | 3.4523 | 4.2187 |\n\n: The same three simple slopes followed through 2,000 complete-row resamples. {#tbl-ch10-practice-bootstrap tbl-colwidths=\"[12,20,20,24,24]\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Bootstrap distributions of the three conditional practice slopes. Solid lines mark original estimates; dashed lines mark the 2.5th and 97.5th percentiles. Each panel uses the same 2,000 row resamples, with a shared horizontal scale for comparing their spreads.](chapter_10_files/figure-html/fig-ch10-bootstrap-slopes-1.png){#fig-ch10-bootstrap-slopes fig-pos='H' fig-alt='Three histograms for baseline 60, 70 and 80 center near slopes 1.55, 2.70 and 3.85. The middle probe has the smallest spread. Solid estimate lines and dashed percentile limits distinguish centers from uncertainty.' width=604.8}\n:::\n:::\n\n\nFor every resample, subtract its slope at 60 from **that same resample's**\nslope at 80. The resulting difference has bootstrap SE 0.2737 and\npercentile interval [1.7404, 2.8368], close to the classical interval\n[1.7509, 2.8445]. If `draws` holds one slope per row and one resample per\ncolumn, the calculation is short:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff <- draws[3, ] - draws[1, ]\nsd(diff)\nquantile(diff, c(.025, .975))\n```\n:::\n\n\nThe agreement here is expected from a deliberately simple, well-behaved\ngenerating model. It is not a general promise that bootstrap intervals\nare wider, more conservative or more accurate. A percentile interval\nreads quantiles of a resampling distribution; it is not a statement that\nthis realized interval contains the true slope with 95% posterior\nprobability. More resamples make those quantiles less sensitive to Monte\nCarlo variation. They do not make the study's 320 observations more\ninformative.\n\n@fig-ch10-calibrations answers another question: what changes when the\ncoverage statement concerns a whole curve? All panels use the same\noriginal estimate. The first two show **pointwise** intervals: one\nclassical, one percentile bootstrap. The third uses Section 3.4's\nclassical simultaneous multiplier and is visibly wider. Its additional\nprotection concerns the family of slopes, under the classical model\nassumptions; it is not a correction for a wrong model or weak design.\nTaking percentiles at many grid points does not turn the second panel\ninto a simultaneous band.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![One slope curve, three coverage statements. Classical and bootstrap pointwise bands concern a fixed moderator value; the wider classical Scheffé band simultaneously covers the slope family under its stated linear-model assumptions. All displays stop at observed support.](chapter_10_files/figure-html/fig-ch10-calibrations-1.png){#fig-ch10-calibrations fig-pos='H' fig-alt='Three panels show the same rising conditional-slope curve. Classical and bootstrap pointwise bands are similar. The classical simultaneous band is wider, especially at the ends. Rugs show sparse support in the tails.' width=604.8}\n:::\n:::\n\n\nReturn now to the salary example, where unequal spread made the choice\nof uncertainty calculation consequential.\n\nThe associate slope is the quantity whose reading changed under HC3.\nA case bootstrap asks what another sampling approximation says about it:\ndraw whole faculty records with replacement and refit the same model.\nThis preserves the empirical association of rank, service and spread,\nwhile treating rows as independent and exchangeable. With seed 90909,\nall 2,000 resamples here contain all three ranks. The bootstrap machinery\nis the case-resampling scheme of Chapter 9 [@efron1993; @freedman1981].\n\n\\Needspace{9\\baselineskip}\n\n| Rank slope | Estimate | Classical SE | HC3 SE | Bootstrap SE | Percentile 2.5% | Percentile 97.5% |\n|:--|--:|--:|--:|--:|--:|--:|\n| Assistant | 0.7793 | 1.9452 | 0.8686 | 0.8074 | $-0.7172$ | 2.3841 |\n| Associate | $-0.3947$ | 0.2949 | 0.1679 | 0.1736 | $-0.8066$ | $-0.1436$ |\n| Full | $-0.1193$ | 0.1253 | 0.1884 | 0.1872 | $-0.4928$ | 0.2522 |\n\n: Three uncertainty calculations for the same three conditional slopes (seed 90909, $B=2000$). {#tbl-ch10-bootstrap tbl-colwidths=\"[18,13,15,12,15,13,14]\"}\n\nThe associate bootstrap SE 0.1736 is close to HC3's 0.1679 rather than\nthe classical 0.2949. Its percentile interval also excludes zero. The\nresampling skewness is $-0.8463$, so a symmetric normal approximation,\n[$-0.7350$, $-0.0544$], conveys a somewhat different shape than the\npercentile interval [$-0.8066$, $-0.1436$]. The interval method belongs in\nthe report. Neither interval is an independent replication of the study.\n\nIf `draws` holds one bootstrap associate-slope estimate per element,\nthese two operations summarize that resampling distribution:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(draws)\nquantile(draws, c(.025, .975))\n```\n:::\n\n\nRow resampling cannot represent unknown departmental dependence, create\nlong-serving assistant professors, repair measurement problems, or identify\na promotion effect. A design with clusters, strata or weights requires\na resampling scheme that follows them. Agreement between HC3 and the\ncase bootstrap is a sensitivity result about these same observations.\n\n## From Analysis to a Defensible Claim {#ch10-report}\n\n\n### The pattern before the verdict\n\nThe interaction block answers whether one common slope is adequate under\nthe fitted linear model. A defensible report does not stop there. It\ndescribes the conditional pattern, gives interval estimates in original\nunits, shows where the comparisons are supported, and states what the\ndesign does not identify.\n\nFor the salary analysis, the main pieces are:\n\n- 397 faculty members at one college in 2008-09, with\n  rank-specific service ranges shown explicitly;\n- a hierarchical model with salary in thousands of dollars, service\n  centered at 5 years, and a two-degree-of-freedom product block;\n- an omnibus interaction comparison of\n  $F(2, 391)=\n  0.486$,\n  $p=.6155$;\n- estimated within-rank slopes with confidence intervals;\n- fitted means or contrasts at a supported common service value;\n- residual, unequal-variance, influence, curvature, and support checks;\n- three uncertainty procedures for the same conditional slopes, including\n  the one slope whose approximate sensitivity interval excludes zero under\n  HC3 and case resampling but not under the classical common-variance model;\n  and\n- an observational interpretation bounded to the represented data.\n\n::: {.callout-tip title=\"A bounded report\"}\n\nAmong the 397 faculty members of this college in\n2008-09, rank differences in mean nine-month salary were large, but the\ndata provided no clear evidence that the linear service-salary\nassociation differed across ranks\n($F(2, 391)=\n0.486$,\n$p=.6155$). Within each rank's observed range,\nthe estimated slopes were\n0.7793 thousand dollars per\nservice year for assistant professors\n(95% confidence interval [$-3.045$,\n4.6036]),\n$-0.3947$ for associate\nprofessors ([$-0.9744$,\n0.185]), and\n$-0.1193$ for full professors\n([$-0.3656$,\n0.127]). Every classical interval includes zero\nand the intervals overlap; the assistant-professor slope rests on a\nservice range of only\n0 to\n6 years. The\nassociate-professor slope was the one quantity sensitive to the variance\nprocedure: its approximate sensitivity interval excluded zero under both an HC3 variance model\n([$-0.7248$,\n$-0.0645$]) and a 2,000-resample\ncase bootstrap\n([$-0.8066$,\n$-0.1436$]) but not under\nthe classical common-variance model, and its resampling distribution was\nskewed, so the interval type matters as well. The result is a descriptive\nconditional association for these faculty; it does not estimate a return\nto service, identify promotion or cohort mechanisms, or support\nextrapolation beyond observed rank-service combinations.\n:::\n\nThis paragraph reports a null block result without converting it into a\nclaim that the slopes are equal, and it reports the variance-model\nsensitivity instead of quietly resolving it. Reporting what the data\ncannot distinguish is as much a finding as reporting what they can.\n\n\n### A reusable template and the statements it blocks\n\nA reusable interaction report can be organized in six sentences.\n\n1. **Target and unit:** “Among [analytic units], we examined whether the\n   [outcome-unit] association between [focal predictor] and [outcome]\n   varied across [moderator values or groups].”\n2. **Model and support:** “We fit a hierarchical [model scale] model on\n   [fixed sample], with probes restricted to [observed joint support].”\n3. **Block evidence:** “Adding the [named] product block changed model fit\n   by [degrees of freedom, statistic, interval or p-value].”\n4. **Conditional estimates:** “At [prespecified supported values], the\n   estimated slopes or contrasts were [estimates and intervals in units].”\n5. **Checks:** “Residual, variance, influence, curvature, and alternative-\n   coding checks suggested [specific consequences].”\n6. **Boundary:** “The result supports [bounded associational or predictive\n   conclusion] but does not establish [causality, mechanism,\n   generalization, or unsupported extrapolation].”\n\nNot every paper must use these exact sentences. Every report should make\ntheir information recoverable.\n\n| Attractive statement | Why it fails | Defensible replacement |\n|:--|:--|:--|\n| \"The interaction proves moderation.\" | A product term is model-based nonadditivity; substantive moderation needs a theory-defined role and a design. | \"The fitted conditional slope varied across the named values or groups.\" |\n| \"There is no effect of $X$.\" | The lower-order coefficient is the slope only at the coded zero or reference value. | \"At $W=0$ under this coding the estimated slope of $X$ was ...\" |\n| \"The lines interact only if they cross.\" | Interaction means nonparallelism on the modelled scale. | \"The estimated slopes differed over the displayed support.\" |\n| \"Centering fixed the collinearity and the confounding.\" | Centering changes the origin, not the information, the omitted variables, or the design. | \"Centering made the zero-value comparison interpretable.\" |\n| \"The product $p$-value shows where the effect exists.\" | One block test does not describe conditional magnitudes across the moderator. | \"The slope curve with its band and support shows where the comparison is estimated and how precisely.\" |\n| \"One group's slope is significant and another's is not, so they differ.\" | Two significance verdicts are not a test of their difference. | \"The slope contrast was ... with interval ...\" |\n| \"A large product $p$-value shows the slopes are equal.\" | Nonrejection is not evidence of no difference. | \"A slope difference between ... and ... remains compatible with these records; claims are restricted to observed joint support.\" |\n\n: Common interaction overclaims and their defensible replacements. {#tbl-ch10-overclaims tbl-colwidths=\"[28,38,34]\"}\n\nThe sustained salary example is exactly this situation, so it deserves\nits own statement of principle. A large product p-value is not proof\nthat conditional slopes are exactly equal. It says the data and model do\nnot distinguish the product block from zero with the chosen precision\nand reference procedure. A bounded null report gives the estimated\ndifference and its interval, then asks whether values of practical\nimportance remain compatible with the data.\n\nFor example, suppose an estimated slope difference is 0.08 outcome units\nper predictor unit with a 95% interval from $-0.12$ to 0.28. “No\ninteraction” hides the fact that modest negative and positive differences\nremain compatible. The relevant next question is substantive: would any\npart of that interval change the decision or theory?\n\nWhy can a study estimate a large average association while leaving\nmoderation imprecise? A product coefficient needs information about how\ncomparisons vary across **joint predictor combinations**. Consider the\nsame 320 generated students. Keep practice hours and each student's\noriginal generated error fixed, compress the centered baseline scores\nto 30% of their original deviations, and generate scores again from the\nsame equation, including the true product coefficient 0.12. This changes\nthe design's predictor coverage, not the true interaction or error SD.\n\n\\Needspace{5\\baselineskip}\n\n**Predict before reading the intervals:** would retaining 320 students\nand the same error realization preserve the precision of the interaction\nestimate? Which part of the information has changed?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same sample size and true interaction, with different predictor coverage. Left: compression narrows baseline variation while preserving all practice values. Right: the product-coefficient interval widens around the unchanged generating coefficient 0.12 (dashed line).](chapter_10_files/figure-html/fig-ch10-precision-1.png){#fig-ch10-precision fig-pos='H' fig-alt='The left panel overlays the original broad baseline-by-practice cloud and a compressed cloud concentrated near baseline 70. The right panel shows the original product interval about 0.09 to 0.14 and the much wider compressed interval about 0.01 to 0.19; both refer to a true product coefficient of 0.12.' width=604.8}\n:::\n:::\n\n\nBaseline support contracts from 42.8747--96 to 61.8624--77.8000. The product\nestimate changes from 0.1149 (SE 0.0139, [0.0875, 0.1422]) to 0.103\n(SE 0.0463, [0.0118, 0.1941]). Both samples arise from a true coefficient\nof 0.12, yet the compressed design leaves much more uncertainty about its\nsize. The same row count is not the same information. In this controlled\ncomparison the SE is multiplied by $1/0.3$; that numerical relation uses\nthe shared predictor values and errors, not a universal rule for every\nrestricted dataset.\n\nSparse tails, imbalanced groups and noisy measurements can similarly\nweaken an interaction comparison [@gelman2020]. A single simulated\nsample does not estimate statistical power. It shows what a design\ncalculation should investigate: which effect sizes and intervals could\nthis joint predictor distribution resolve? More bootstrap repetitions\ncannot replace missing predictor variation. Probing baseline 60 in the\ncompressed sample would also be extrapolation, although it was supported\nin the original sample.\n\n### The research record for this analysis\n\n| Element | Closing answer for the faculty-salary analysis |\n|:--|:--|\n| Question | Whether the service-salary association varies across academic ranks, rather than assuming one common slope or searching over possible products |\n| Records and design | One faculty member per row, one U.S. college, one academic year; rank and service were observed, not assigned, and no broader sampling scheme is documented |\n| Measurement | Nine-month salary and years of service are recorded administrative variables; they do not measure productivity, market conditions, or the mechanisms behind a salary structure |\n| Estimand and support | Rank-specific fitted service slopes and their differences over each rank's own support; cross-rank contrasts are credible only inside the 1-to-6 year common window |\n| Model and estimation | One hierarchical OLS model with two product columns, service centered at a supported value, and every reported quantity built as a linear combination of the coefficients |\n| Uncertainty and checks | The additive restriction compared by a two-degree-of-freedom block test; classical, HC3 and case-bootstrap uncertainty for the same slopes; residual form, influence, curvature, support and scale examined and reported |\n| Bounded claim | These records do not clearly distinguish three rank-specific slopes from one common linear association; the weak interaction evidence is a bounded association, not a moderator mechanism |\n\n: Closing research record for the faculty-salary interaction analysis. {#tbl-ch10-record tbl-colwidths=\"[24,76]\"}\n\nThe record includes the package datasets, complete-case rule, scales,\nmodel formulas, anchors, probes and resampling unit. The generated example\nuses seed 909 with 320 rows. The practice and salary bootstraps use\nseeds 90910 and 90909 respectively, each with 2,000 whole-row resamples. Reproducibility recovers the numerical calculation;\nthe design record establishes which interpretation it can carry.\n\n## Reading Bridge\n\nA product term releases a common-slope restriction. Lower-order\ncoefficients are comparisons at stated anchors; centering and releveling\nmove the coordinates without changing the fitted surface. Conditional\nslopes, group contrasts and differences of differences all use coefficient\ncovariance for their uncertainty. The block test examines additivity;\ncurves, intervals and support show what the comparison means.\n\nThe salary records illustrated an honest weak-interaction result and one\nslope sensitive to the variance assumption. Chapter 11 changes the outcome\nto binary and the mean scale to the logit. The conditional question\ncontinues, but interaction on the linear-predictor and probability scales\nwill become different statements about the same fit.\n\n### Key terms {.unnumbered}\n\n| Term and common alternatives | Meaning or essential distinction |\n|:--|:--|\n| Product term (interaction term; multiplicative term) | A column formed by multiplying two predictors, so that each one's fitted comparison depends on the other's value. Its coefficient is a difference in slopes, not a slope, and nonadditivity is defined on the modelled scale: a nonlinear change of outcome scale can create or remove it. |\n| Conditional slope (simple slope; conditional effect) | The fitted difference in outcome per one-unit difference in a focal predictor evaluated at a stated value or group of the other predictor. It is a linear combination of coefficients, so its SE uses their covariance, and it describes a conditional mean, not an individual case. |\n| Moderator (moderating variable; moderation) | The variable across whose values or groups a named focal relationship is allowed to vary. The product-term algebra is symmetric in the two predictors, so the label comes from the research question; a moderation reading describes when a relationship differs, not how an effect is transmitted. |\n| Hierarchy principle (marginality; well-formulated model) | The rule that a model containing a product also contains both component terms. Dropping a component forces the other's slope to zero at its coded zero and makes the fitted surface depend on the origin; hierarchy does not require that every possible product be added. |\n| Centering a predictor (anchoring; reparameterization) | Replacing a predictor by its difference from a chosen value, so that coefficients anchored at zero become comparisons at that value. It changes the intercept and the lower-order coefficients and leaves the product coefficient, the fitted values, the residuals and the product-block test unchanged; it repairs no design, selection, or measurement problem. |\n| Probe value (pick-a-point value) | A stated value of the moderator at which a conditional slope or contrast is evaluated, chosen from the measurement scale, a threshold, or a decision need rather than by an automatic mean-and-SD rule, and restricted to values the records support. |\n| Johnson--Neyman boundary (region of significance) | A moderator value at which a pointwise interval for a conditional slope touches zero, found as a root of a quadratic whose leading coefficient decides which side is the region. A boundary outside the observed support describes the algebra and not the data, and a pointwise band is not a simultaneous band. |\n| Interaction contrast (difference in differences within a model) | A linear combination of coefficients comparing two conditional comparisons, such as one group's difference minus another group's difference. Under reference coding it equals a product coefficient up to sign; its SE uses the coefficient covariance, and its causal reading depends on design, not on the algebra. |\n\n: Concepts introduced here. {#tbl-ch10-terms tbl-colwidths=\"[30,70]\"}\n\n### Further reading {.unnumbered}\n\nAiken and West [@aiken1991] and Cohen and colleagues [@cohen2003]\ndevelop centering and conditional comparisons. Bauer and Curran\n[@bauer2005] and Preacher and colleagues [@preacher2006] explain probing\nand significance boundaries. Fox and Weisberg [@fox2019] supply the data\nand regression software route. The [emmeans interaction vignette](https://rvlenth.github.io/emmeans/articles/interactions.html)\nconnects conditional comparisons to implementation.\n\n{{< pagebreak >}}\n\n## Exercises {.unnumbered}\n\n<!-- prompt-id: CH10-E01 -->\n\n### Exercise 1: Read the graph before the table (Foundational) {.unnumbered}\n\nA study\nplots a continuous outcome against weekly practice hours for two program\ngroups. Over the observed range of 0 to 6 hours, the fitted Group A line\nrises from 50 to 62 and the fitted Group B line rises from 58 to 76. The\nconfidence bands overlap at some practice values and the lines do not\ncross. (1) Calculate each fitted slope in outcome units per hour and\ntheir difference. (2) Give the fitted group gap at 0 hours and at 6\nhours, and the difference between those two gaps. (3) Describe the\npattern as additive or nonadditive without using a $p$-value, and say\nwhy crossing is not required. (4) A reader concludes from the\noverlapping bands that the two slopes are the same. State what would\nhave to be estimated instead.\n\n<!-- END exercise-id: CH10-E01 -->\n\n<!-- prompt-id: CH10-E02 -->\n\n### Exercise 2: A conditional slope needs the covariance (Foundational) {.unnumbered}\n\nIn a fitted product-term model the focal coefficient is 2.6972 and the\nproduct coefficient is 0.1149. At centered moderator $w=10$, the full\ncovariance calculation gives a combined slope variance of 0.0379; the\nresidual degrees of freedom are 316 and $t_{.975,316}=1.9675$.\nHere $w=10$ means ten units above the anchor. (1) Write the conditional\nslope and its three-term variance formula, retaining the covariance;\ncalculate the slope at $w=10$. (2) Use the supplied combined variance\nto calculate its SE and 95% interval. (3) A student omits the covariance\nterm and reports 0.1865; another adds the focal standard error to ten\ntimes the product standard error and reports 0.2634. Say what each\nnumber is and why neither is the standard error required here. (4)\nTo compare the slopes at $w=-10$ and $w=10$, which quantity should be estimated directly? Explain why subtracting the endpoints of their two separate intervals does not supply an interval for that difference.\n\n<!-- END exercise-id: CH10-E02 -->\n\n<!-- prompt-id: CH10-E03 -->\n\n### Exercise 3: Translate a centered model (Foundational) {.unnumbered}\n\nA model\nfitted with the raw moderator has intercept 32.8571, focal coefficient\n$-5.3448$, moderator coefficient 0.3822 and product coefficient 0.1149;\nthe raw focal coefficient has $t=-5.5131$. The moderator is a test score\nand the analyst now centers it at 70. (1) Give the focal coefficient and\nthe intercept of the centered model. (2) State which of the following\nchange: the product coefficient, the fitted values, the residuals, the\nproduct-block $F=68.3548$. (3) Explain what the raw focal coefficient's\nsmall $p$-value is a test of, and why that does not make the raw\nparameterization preferable. (4) A colleague says centering removed a\nconfounder. State what centering did and did not do.\n\n<!-- END exercise-id: CH10-E03 -->\n\n<!-- prompt-id: CH10-E04 -->\n\n### Exercise 4: A two-column product block (Foundational) {.unnumbered}\n\nOn the same\n397 records, a model with a common service slope for three academic\nranks has residual sum of squares 219014.23 on 393 degrees of freedom,\nand the model adding two service-by-rank product columns has 218471.17\non 391. The 5% critical value of $F(2,391)$ is 3.0188. (1) Calculate\nthe block $F$ statistic. (2) State the decision at 5% and what it does\nand does not say about the three rank-specific slopes. (3) Explain why\nthe result would be unchanged if the full professor rather than the\nassistant rank were the reference, while the two individual product\n$t$ tests would not be. (4) Name one quantity a reader needs before\naccepting \"the slopes are the same\" as a summary.\n\n<!-- END exercise-id: CH10-E04 -->\n\n<!-- prompt-id: CH10-E05 -->\n\n### Exercise 5: A difference of differences from cell means (Integrative) {.unnumbered}\n\nIn a conformity experiment the mean number of conforming responses is\n8.9 with a low-status partner and 17.4 with a high-status partner\namong low-authoritarianism participants; 7.2500 and 14.2727 among\nmedium-authoritarianism participants; and 12.6250 and 11.8571 among\nhigh-authoritarianism participants. (1) Give the partner-status\ndifference in each authoritarianism category. (2) Give the difference of\ndifferences comparing the low and high categories. (3) Its standard\nerror is 3.4507 on 39 degrees of freedom, with $t_{.975,39}=2.0227$;\ngive the 95% interval and the $t$ statistic. (4) The cell counts are\n10, 5, 4, 11, 8 and 7 and the cell standard deviations range from 2.6437\nto 7.3473. State one consequence for the reference distribution used in\n(3), and one thing the contrast does not establish about partner status.\n\n<!-- END exercise-id: CH10-E05 -->\n\n<!-- prompt-id: CH10-E06 -->\n\n### Exercise 6: Report a sensitive conditional slope (Integrative) {.unnumbered}\n\nA\nconditional slope is estimated as $-0.3947$ thousand dollars per year.\nThree standard errors are available for it: 0.2949 from the classical\ncommon-variance model, 0.1679 from an HC3 covariance, and 0.1736 from a\n2,000-resample case bootstrap whose percentile interval is\n[$-0.8066$, $-0.1436$]. Use $t_{.975,391}=1.966$ for the first two.\nResidual standard deviations in the three groups are 8.0906, 13.2448 and\n27.6842 against a pooled 23.6379. (1) Give the classical and HC3\nintervals. (2) Say which intervals exclude zero and explain, using the\nresidual standard deviations, why the calculations disagree. (3) Write\none sentence reporting this slope for a reader, without choosing a\nwinner. (4) A student joins pointwise bootstrap intervals into a curve and claims 95% simultaneous coverage. Explain the error and name one study problem that resampling does not repair.\n\n<!-- END exercise-id: CH10-E06 -->\n\n\n{{< pagebreak >}}\n\n## Appendix A: Conditional quantities as linear combinations {.unnumbered}\n\n### One formula for four questions {.unnumbered}\n\nA conditional slope, conditional mean, group contrast and interaction\ncontrast can all be written $\\mathbf c{}^{\\mathsf T}\\boldsymbol\\beta$. The vector $\\mathbf c$ names the\nquestion; the estimated variance is $\\mathbf c{}^{\\mathsf T}\\widehat{\\mathbf V}\\mathbf c$. For coefficient order\n$(\\beta_0,\\beta_X,\\beta_W,\\beta_{XW})$:\n\n| Quantity | Contrast vector $\\mathbf c{}^{\\mathsf T}$ |\n|:--|:--|\n| Practice slope at $w$ | $(0,1,0,w)$ |\n| Mean at $(x,w)$ | $(1,x,w,xw)$ |\n| Mean difference $x_b-x_a$ at $w$ | $(0,x_b-x_a,0,w(x_b-x_a))$ |\n| Slope difference at $w_b$ and $w_a$ | $(0,0,0,w_b-w_a)$ |\n\n: Different questions use the same coefficient covariance. {#tbl-ch10-linear tbl-colwidths=\"[50,50]\"}\n\nAt $w=10$ the first row gives 3.8461 with SE 0.1947 from full precision.\nThe faculty associate slope uses $\\mathbf c{}^{\\mathsf T}=(0,1,0,0,1,0)$ and gives $-0.3947$\nwith classical SE 0.2949. The uncertainty belongs to the whole comparison,\nnot a sum of separate coefficient SEs.\n\n### Centering translates the coefficients {.unnumbered}\n\nFor $W_c=W-c$,\n\n$$\n\\boldsymbol\\beta^{\\mathrm{new}}=\\mathbf T\\boldsymbol\\beta,\n\\qquad T=\\begin{pmatrix}1&0&c&0\\\\0&1&0&c\\\\0&0&1&0\\\\0&0&0&1\\end{pmatrix},\n\\qquad \\mathbf V^{\\mathrm{new}}=\\mathbf T\\mathbf V\\mathbf T{}^{\\mathsf T}.\n$$\n\nThe last row fixes the product coefficient. The first two translate the\nanchor. With $c=70$, the full-precision raw estimates give intercept\n59.6123 and practice coefficient 2.6972. A translated contrast uses the\ntranslated covariance; its estimate and SE then agree with the original.\n\n### The boundary quadratic {.unnumbered}\n\nWriting $a=\\widehat\\beta_X$, $b=\\widehat\\beta_{XW}$,\n$v_a=\\widehat{\\mathbf V}_{XX}$, $v_b=\\widehat{\\mathbf V}_{XW,XW}$ and\n$v_{ab}=\\widehat{\\mathbf V}_{X,XW}$, the squared endpoint condition becomes\n\n$$\nAw^2+Bw+C=0,\\quad A=b^2-t^2v_b,\\quad\nB=2ab-2t^2v_{ab},\\quad C=a^2-t^2v_a.\n$$\n\nFor distinct real roots, the band excludes zero outside them if $A>0$\nand inside if $A<0$. With $A=0$ the condition is linear; with no real\nroots the sign is constant and must be checked at a supported value.\nThe generated fit has $A=0.0125$ and baseline roots 39.039 and 51.284.\nSubstitution into the quadratic gives numerical zero, and the pointwise\ninterval touches zero there. The lower root remains outside the data.\n\n## Appendix B: What changes beyond this chapter {.unnumbered}\n\nA three-way product $XWZ$ allows a two-way pattern to vary with a third\npredictor. Hierarchy keeps all two-way products and all component terms.\nIts interpretation requires conditional comparisons across three dimensions;\nChapter 4's three-way table gives the categorical reading.\n\nWith a nonlinear link, additivity on the linear-predictor scale and on\nthe response scale are different properties. Even without a product, a\nlogistic model can give probability differences that vary with another\npredictor. Always name the scale.\n\nA conditional indirect effect concerns mediation. Its causal interpretation\nneeds defensible temporal ordering, adequate functional form and assumptions\nabout common causes of the intervening variable and outcome. An interval\naround an unidentified causal quantity leaves that problem in place.\n\nDepartment, classroom or school dependence changes the appropriate\nuncertainty calculation. Adding a product changes a conditional mean;\nit does not make records independent.\n\n**Extended practice.** (1) Refit the faculty model with log salary.\nExplain how the comparison changes from dollars to proportional changes,\nand why raw residual sums of squares or likelihood criteria on different\noutcome scales cannot be compared without accounting for the transformation.\n(2) Resample faculty within rank rather than across all records. Explain\nwhich sampling story fixes the rank counts and which lets them vary.\nCompare the associate slope intervals without treating the two schemes\nas independent substantive evidence.\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_10_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}