{
  "hash": "1fa3970a554ed2185c769bcdc0bca4a9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploratory Factor Analysis and Model Development\"\nauthor: \"Jinsong Chen\"\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\nformat:\n  pdf:\n    output-file: chapter_02.pdf\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{caption}\n          \\captionsetup[table]{position=above,format=plain,justification=raggedright,singlelinecheck=false,labelsep=newline,labelfont=bf,textfont=it}\n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-tip title=\"Chapter box\"}\n**Five themes.**\n\n*The direction of work reverses.* The preceding chapter built a covariance\nmatrix from declared parameters. Here a sample correlation matrix comes\nfirst, and no simple model reproduces it exactly.\n\n*Every diagnostic compares against a reference.* Extraction, retention and\nrotation each state what the data are being held up against. Naming the\nreference is what makes a result interpretable, and what makes two\nprocedures with the same name different.\n\n*Axes are chosen, not found.* Rotation changes the loading display\nwithout changing the fitted covariance, so pattern coefficients, structure\ncorrelations and factor correlations are three different quantities that\nmust be read together.\n\n*Discrepancy has a location.* A residual correlation matrix says where a\nretained solution strains; an average residual cannot.\n\n*A development sample cannot confirm what it was used to develop.* The\nanalysis produces a candidate whose restrictions are stated explicitly, and\nthe evidence for it has to come from records not yet inspected.\n\n**Prerequisites.** Sample covariance and correlation, elementary matrix\nalgebra, and the common-factor model, communalities, uniquenesses and\nscale and rotational indeterminacies developed in the preceding chapter. Basic R helps\nreproduction; the printed matrices, equations and output support the\nreasoning without running it.\n\n**Record.** Sample A contains 360 complete, simulated continuous records on\ntwelve Student Learning Experiences indicators. No observations concern\nactual students. Samples B and C are not analyzed here.\n\n**Scope.** We develop a candidate measurement model on Sample A and stop\nthere. Neither confirmation sample is analyzed or inspected for\nmodel-development decisions, no restricted model is estimated,\nand no fit index is interpreted as evidence for a construct. Indicators are\ntreated as continuous throughout Part Two. This is model development, not\ninstrument validation or individual scoring.\n:::\n\n# Define the exploratory measurement problem {#sec-efa-problem}\n\nChapter 1 began with known loadings and factor covariances and worked\nforward to an implied covariance matrix. Here the direction of work\nchanges. We observe a sample of indicator values, calculate their\nassociations, and ask which common-factor representation is defensible.\nThe observed correlations fluctuate from sample to sample. Their pattern\ndoes not arrive with a factor count, a preferred rotation, or substantive\nnames attached. Those have to be developed and documented.\n\nExploratory factor analysis, or **EFA**, leaves most loading restrictions\nopen while seeking a comparatively low-dimensional representation of\nshared covariation. It is not a procedure with no assumptions. Selecting\nthe indicators, defining the population, choosing an association matrix,\nrestricting residual covariance, considering a range of dimensions, and\nchoosing rotation criteria all shape what the analysis can reveal. A\ncarefully designed exploratory study therefore has substantial work to\ndo before an extraction routine runs.\n\nThe distinction between a provisional representation and a confirmed\nrestriction is important from the outset. Suppose an EFA suggests that\nan indicator of adaptive planning also relates to strategy adjustment.\nThat can be a useful discovery. It is not evidence that a cross-loading\nspecified after seeing these observations was predicted before them.\nThe later CFA can evaluate the resulting restriction on unused data,\nbut changing the name of the fitting function does not change the\nhistory of the decision.\n\n## The common-factor model is not restriction-free\n\nFor person or observational unit $i$, retain Chapter 1's notation:\n\n$$\n\\mathbf y_i=\\boldsymbol\\nu+\\boldsymbol\\Lambda\\boldsymbol\\eta_i\n +\\boldsymbol\\epsilon_i,\\qquad\n\\boldsymbol\\Sigma=\\boldsymbol\\Lambda\\boldsymbol\\Phi\n \\boldsymbol\\Lambda^{\\mathsf T}+\\boldsymbol\\Theta.\n$$ {#eq-efa-model}\n\nThere are $p$ indicators and $m$ factors. Thus $\\boldsymbol\\Lambda$ is\n$p\\times m$, $\\boldsymbol\\Phi$ is $m\\times m$, and\n$\\boldsymbol\\Theta$ and $\\boldsymbol\\Sigma$ are $p\\times p$.\nThe factor-residual covariance is zero. Classical EFA initially makes\n$\\boldsymbol\\Theta$ diagonal: remaining indicator-specific variation\ndoes not covary across indicators. That restriction can be wrong even\nwhen most loadings are freely estimated.\n\nThe loading pattern is initially open, but its dimension is not. A\ntwo-factor and a three-factor EFA are different covariance models.\nScale restrictions are also necessary. One convenient extraction\nrepresentation uses unit-variance, uncorrelated factors; a subsequent\noblique transformation expresses the same common covariance using\ncorrelated axes. Orthogonality at this computational stage does\nnot establish independence of substantively named attributes.\n\nThe latent intercept $\\boldsymbol\\alpha$ equals the factor mean in\nthis model without structural paths or separate predictors. It remains\nan intercept symbol throughout Part Two. Likewise $\\boldsymbol\\Phi$\ndenotes total factor covariance, not residual covariance and not the\nlater structural-disturbance matrix. These distinctions prevent the\nsame letter from silently changing meaning between EFA, CFA, and SEM.\n\n## A twelve-indicator content record\n\nThe sustained example concerns **Student Learning Experiences (SLE)**.\nThe proposed domains are Planning, Strategy, and Belonging. These names\norganize the starting content questions; they do not determine how many\nfactors Sample A will support. All twelve variables are explicitly\nsimulated continuous process indices. Their units are index points,\nnot response categories, percentages, or counts. The statements below\nclarify intended content, but they are not presented as an administered\nand validated questionnaire.\n\n\n::: {#tbl-efa-items .cell layout-align=\"center\" tbl-cap='Proposed content before factor analysis. All indices are positively directed.'}\n::: {.cell-output-display}\n\n\n|item |domain    |wording                                                     |\n|:----|:---------|:-----------------------------------------------------------|\n|P1   |Planning  |I establish a study plan before beginning a task.           |\n|P2   |Planning  |I identify which study tasks deserve attention first.       |\n|P3   |Planning  |I compare my progress with the plan I made.                 |\n|P4   |Planning  |I revise my plan when a study method is not working.        |\n|S1   |Strategy  |I change my learning strategy when understanding is weak.   |\n|S2   |Strategy  |I select a learning method suited to the task.              |\n|S3   |Strategy  |I revise my explanation after checking my understanding.    |\n|S4   |Strategy  |I use discussion with others to improve my learning method. |\n|B1   |Belonging |I feel accepted by other students.                          |\n|B2   |Belonging |I feel able to join other students in learning activities.  |\n|B3   |Belonging |I feel able to express my views in class.                   |\n|B4   |Belonging |I feel connected to the university as a whole.              |\n\n\n:::\n:::\n\n\nP4 concerns changing a plan when a learning method fails. S4 concerns\nusing discussion with others to improve a learning method. Their content\nalready suggests possible overlap between domains. A cross-loading\nwould not automatically make either indicator defective. Conversely,\nclear wording does not guarantee that its covariance pattern will\nmatch the intended domain.\n\nThe twelve columns have different raw dispersions. All are coded so\nthat larger values mean more of the stated attribute, and none is\nreverse-scored. The simulation imposes neither missing observations\nnor response limits. Its unbounded normal records are a deliberate\nteaching design, not a claim that actual student experiences are\nnormally distributed or measured without limits.\n\nDownload [sle_continuous.csv](sle_continuous.csv), the only SLE data file\nneeded for the examples. The [SLE data appendix](#sec-sle-data) contains\nthe complete codebook and sample manifest. Its `sample` column identifies\nthree independent 360-case samples, not three groups to pool. Select A\nbefore inspecting indicators or calculating statistics in this chapter.\nPopulation parameters are documented in Appendix A, separate from the\nlearner-facing analysis: knowing the recipe is not a substitute for\nreasoning from Sample A. No empirical\nsummary, correlation, factor solution, or fit statistic from B or C\nhas been used to make the decisions reported here.\n\n## Check the indicators before interpreting correlations\n\nData examining is part of defining the statistical input. An unintended\nreverse code can change signs. A nearly constant indicator can make a\ncorrelation unstable. Duplicate records alter the apparent amount of\ninformation. Pairwise deletion can produce different effective samples\nfor different correlations, and sometimes a matrix that is not positive\ndefinite. None of these problems is repaired merely by rotating a\nloading matrix until it looks recognizable.\n\n\n::: {#tbl-efa-audit .cell layout-align=\"center\" tbl-cap='Sample A audit, in raw process-index points; skewness is the third standardized central moment.'}\n::: {.cell-output-display}\n\n\n|Item |Mean  |SD    |Min   |Max   |Skew  |Missing |\n|:----|:-----|:-----|:-----|:-----|:-----|:-------|\n|P1   |50.27 |7.93  |25.76 |73.42 |-0.05 |0       |\n|P2   |52.76 |10.20 |25.66 |84.47 |0.26  |0       |\n|P3   |49.02 |12.12 |8.28  |86.27 |-0.08 |0       |\n|P4   |51.44 |9.36  |25.88 |75.07 |0.05  |0       |\n|S1   |48.59 |10.17 |21.39 |75.02 |0.00  |0       |\n|S2   |50.28 |7.81  |26.68 |71.48 |-0.12 |0       |\n|S3   |51.28 |10.91 |24.32 |79.54 |0.02  |0       |\n|S4   |48.09 |8.70  |22.76 |73.89 |-0.17 |0       |\n|B1   |51.26 |10.07 |18.59 |82.73 |0.02  |0       |\n|B2   |49.62 |12.60 |17.60 |96.23 |-0.08 |0       |\n|B3   |50.09 |8.25  |28.04 |74.26 |0.07  |0       |\n|B4   |51.50 |11.30 |22.14 |92.91 |0.16  |0       |\n\n\n:::\n:::\n\n\nThere are 360 distinct rows, no missing values, and positive\nvariance in every indicator. The minimum eigenvalue of the Pearson\nmatrix is 0.223, so its\ninverse exists without matrix repair. This is a useful computational\ncheck, not evidence that the factor model is true. Normal-theory ML\nalso needs an appropriate sampling and distributional interpretation.\nThe simulation supplies independent normal factor/residual draws; a\nreal study would have to justify or investigate those assumptions.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Raw distributions in Sample A. Different dispersions motivate an explicit scaling choice.](chapter_02_files/figure-html/fig-efa-distributions-1.png){#fig-efa-distributions fig-align='center' fig-pos='H' fig-alt='Boxplots of twelve continuous SLE indices, grouped by Planning, Strategy, and Belonging; all have nonzero dispersion.' width=1120}\n:::\n:::\n\n\nIn an actual application, an unusual observation deserves examination\nof provenance and measurement, not automatic removal because it makes\nnormality less convenient. A miscoded value, a genuine extreme case,\nand a member of another target population call for different actions.\nAny exclusion changes the estimand's population or the analyzed record\nand must be described. Here no item or case is removed. That keeps the\nsame twelve-variable target available for later confirmatory comparisons.\n\n# Choose the matrix and extraction target {#sec-efa-target}\n\n## Covariance and correlation answer different scaling questions\n\nLet $\\mathbf S$ denote the ordinary sample covariance matrix computed\nwith denominator $n-1$, and let\n$\\mathbf D_S=\\operatorname{diag}(s_{11},\\ldots,s_{pp})$.\nThe Pearson correlation matrix is\n\n$$\n\\mathbf R=\\mathbf D_S^{-1/2}\\mathbf S\\mathbf D_S^{-1/2}.\n$$ {#eq-efa-standardization}\n\nThis operation divides each covariance by the two sample standard\ndeviations. It does not remove dependencies, correct measurement error,\nor make a nonnormal distribution normal. It changes the units in which\nthe association structure is represented. Covariance-scale analysis\npreserves raw variances; correlation-scale analysis gives each observed\nvariable a unit diagonal.\n\nOur primary analysis uses $\\mathbf R$. The rationale is that the\nprocess-index dispersions are not intended to set the relative weight\nof the content domains. Raw $\\mathbf S$, means, and standard deviations\nare retained, however. Later CFA fits raw observations, and an explicit\nscale transformation connects those fits with this standardized EFA.\nNo variable is replaced by an ordinal score or a new construct along\nthe way.\n\nThe observations are synthetic samples generated from a prespecified\ncontinuous latent-variable population, and the exact released records are\ndistributed as `sle_continuous.csv`. Throughout the fragments below, `X` is\nSample A's 360-by-12 indicator matrix and `R` is its correlation matrix:\n\n```r\nsle <- read.csv(\"sle_continuous.csv\")\n\nitems <- c(paste0(\"P\", 1:4),\n           paste0(\"S\", 1:4),\n           paste0(\"B\", 1:4))\n\nX <- sle[sle$sample == \"A\", items]\nR <- cor(X)\n```\n For\nthese complete observations, standardizing the covariance matrix gives the\nsame Pearson matrix as direct calculation. That identity checks the\ntransformation, not the suitability of Pearson correlation for every dataset.\nNumeric codes for categories would require a separate\nmeasurement treatment; that topic belongs to other courses or later\nseries. Categorical group labels and coded predictors remain possible\nin later multigroup or MIMIC work. This brief boundary introduces no\ncategorical-estimator track here.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Sample A Pearson correlations, with a fixed scale from -1 to 1. The ordering follows the content map, not a fitted cluster algorithm.](chapter_02_files/figure-html/fig-efa-correlation-1.png){#fig-efa-correlation fig-align='center' fig-pos='H' fig-alt='Twelve-by-twelve Pearson matrix with generally stronger within-domain correlations and positive relations between domains.' width=1040}\n:::\n:::\n\n\nThe broad blocks are suggestive, not conclusive. A correlation between\na Planning and a Strategy indicator might arise from correlated\nfactors, a cross-loading, residual dependence, or some combination.\nThe same visible association can therefore be represented by different\nrestrictions. The task is not to give each colored block a name and\nstop; it is to evaluate a coherent factor representation of the matrix.\n\n## PCA: a decomposition of total observed variance\n\nFor a symmetric positive-definite correlation matrix,\n\n$$\n\\mathbf R=\\mathbf V\\mathbf D\\mathbf V^{\\mathsf T},\\qquad\n\\mathbf V^{\\mathsf T}\\mathbf V=\\mathbf I,\n$$ {#eq-efa-spectral}\n\nwhere the columns of $\\mathbf V$ are orthonormal eigenvectors and\n$\\mathbf D=\\operatorname{diag}(d_1,\\ldots,d_p)$ contains ordered\neigenvalues. A rank-$m$ PCA reconstruction uses\n\n$$\n\\mathbf A_m=\\mathbf V_m\\mathbf D_m^{1/2},\\qquad\n\\widehat{\\mathbf R}_{\\mathrm{PCA},m}=\\mathbf A_m\\mathbf A_m^{\\mathsf T}.\n$$ {#eq-efa-pca}\n\nThe full decomposition is exact; a truncated one generally is not.\nPCA chooses directions of high observed variance. Component scores\nare weighted functions of observed variables, not unobserved random\nvariables whose common contribution is separated from item residuals.\nCalling $\\mathbf A_m$ a loading matrix in software does not change\nthat distinction.\n\nThe first three Sample A component eigenvalues sum to\n7.809, or\n65.1% of the twelve units\nof standardized observed variance. This is a PCA summary. It is not\nthe common variance attributed to three latent factors by the ML model.\nThe two summaries can differ because their objectives differ, even\nwhen their broad dimensional patterns look similar.\n\nPCA may be appropriate when compact prediction, compression, or a\ndescriptive orientation is the objective. The problem is not\nusing PCA; it is interpreting its output as if a common-factor\nmeasurement model had been estimated. A method should be judged\nagainst the task it actually solves.\n\n## Principal-axis factoring: estimate the diagonal contribution\n\nPrincipal-axis factoring, or PAF, works with a reduced correlation\nmatrix. At iteration $t$, replace the unit diagonal by estimated\ncommunalities:\n\n$$\n\\mathbf R_c^{(t)}=\\mathbf R-\n \\operatorname{diag}(1-\\widehat{\\mathbf h}^{2(t)}).\n$$ {#eq-efa-paf}\n\nDecompose this matrix, use its leading positive eigenvalues to form\na provisional loading matrix, and update the communalities from its\nrow sums of squared loadings in an orthogonal representation. Repeat\nuntil a declared rule indicates sufficiently small changes. The\ninitial diagonal, handling of nonpositive roots, and stopping rule\nare implementation choices, not properties of factor analysis itself.\n\nOne common initialization is the squared multiple correlation of\neach variable with the remaining variables. This quantity is the **squared\nmultiple correlation**, written SMC throughout: for indicator $j$ it is the\n$R^2$ from regressing $Y_j$ on all eleven other indicators, so it says how much\nof that indicator the rest of the set can already account for. For nonsingular\n$\\mathbf R$,\n\n$$\n\\widehat h_{j,0}^{2}=1-\n \\frac{1}{(\\mathbf R^{-1})_{jj}}.\n$$ {#eq-efa-smc}\n\nThese are regression summaries of the observed matrix, not known\ncommon variances. They can underestimate some true communalities and\ncan be unstable when predictors are highly redundant. They provide\na starting point, not an answer to the factor-count question.\n\n\n::: {#tbl-efa-paf-update .cell layout-align=\"center\" tbl-cap='A single three-factor PAF-style spectral update from an SMC diagonal. This is an illustration, not the primary ML fit or a converged PAF solution.'}\n::: {.cell-output-display}\n\n\n|Item |SMC   |First update |\n|:----|:-----|:------------|\n|P1   |0.496 |0.576        |\n|P2   |0.458 |0.535        |\n|P3   |0.424 |0.494        |\n|P4   |0.550 |0.616        |\n|S1   |0.455 |0.545        |\n|S2   |0.409 |0.483        |\n|S3   |0.369 |0.439        |\n|S4   |0.410 |0.472        |\n|B1   |0.637 |0.720        |\n|B2   |0.599 |0.665        |\n|B3   |0.335 |0.383        |\n|B4   |0.243 |0.271        |\n\n\n:::\n:::\n\n\nFor P1, the SMC start is 0.496 and the\nfirst updated communality is 0.576.\nRepeating that update would change the reduced diagonal again. This\nexplains why a PAF root is not automatically the same as a root of\nthe original unit-diagonal correlation matrix.\n\n## Minimum residual and maximum likelihood extraction\n\nMinimum-residual extraction seeks small discrepancies between observed\nand reproduced off-diagonal correlations. A representative objective is\n\n$$\nF_{\\mathrm{minres}}=\n \\sum_{j<k}\\left[r_{jk}-(\\boldsymbol\\Lambda\\boldsymbol\\Phi\n \\boldsymbol\\Lambda^{\\mathsf T})_{jk}\\right]^2.\n$$ {#eq-efa-minres}\n\nThe diagonal residual variances then complete the observed variances.\nThis criterion gives the same squared-error weight to each displayed\noff-diagonal discrepancy. Software algorithms can differ in numerical\ndetails; the objective, convergence criteria, and resulting covariance\nstill need to be checked. PAF and minres are both common-factor\napproaches, but they are not names for the same algorithm.\n\nThe primary method here is **maximum-likelihood common-factor\nextraction**. For an observed covariance matrix $\\mathbf S$ and a\npositive-definite model-implied covariance\n$\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)$, the normal-theory\ndiscrepancy can be written\n\n$$\nF_{\\mathrm{ML}}(\\boldsymbol\\vartheta)=\n \\log|\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)|\n +\\operatorname{tr}\\!\\left[\\mathbf S\\boldsymbol\\Sigma(\\boldsymbol\\vartheta)^{-1}\\right]\n -\\log|\\mathbf S|-p.\n$$ {#eq-efa-ml}\n\nHere $\\boldsymbol\\vartheta$ collects free parameters; it is not the\nresidual matrix $\\boldsymbol\\Theta$. The determinant terms measure\ncovariance volume, while the trace term measures discrepancy relative\nto the model's covariance geometry. The two sample-only terms set\nthe discrepancy to zero for exact reproduction. Minimization chooses\nparameter values under the model's restrictions, rather than choosing\na covariance matrix independently of them.\n\nThe same expression applies to our correlation-scale analysis with\n$\\mathbf R$ in place of $\\mathbf S$. Under freely rescalable loadings\nand residual variances, transforming observed units has a corresponding\nparameter transformation. This does not mean every arbitrary\nconstraint is invariant to units. Equal unstandardized loadings,\nfor example, must be re-expressed when the indicators change scale.\n\nNormal ML supplies a distributional framework for standard errors and\ntest statistics when its assumptions and regularity conditions hold.\nIndependent observations, a suitable population sampling interpretation,\nidentification, and admissible covariance matrices matter. Good-looking\nloadings cannot supply any of these by themselves. Numerical convergence\nonly says that the optimizer met a stopping rule; it does not show that\nthe fitted representation is adequate or that the solution is uniquely\nidentified.\n\n| Method | Immediate target | What the output does not establish |\n|:--|:--|:--|\n| PCA | Low-rank reconstruction of total observed variance | A latent measurement decomposition |\n| PAF | Iterative reduced-matrix factor representation | A universal diagonal start or stopping tolerance |\n| Minres | Small off-diagonal squared residuals | Normal-likelihood inference without additional work |\n| ML factor analysis | Best normal likelihood within the factor model | Substantive truth, validity, or acceptable fit merely from convergence |\n\nThe maintained sequence is therefore Pearson correlations, ML\nextraction, and oblimin rotation. Minres is a bounded sensitivity\ncomparison on the same matrix. The later CFA uses the same continuous\nML family; it is not a transition from one response model to another.\n\n# Determine a plausible factor count {#sec-efa-retention}\n\n## Underfactoring and overfactoring have different costs\n\nToo few factors force distinctions into an inadequate space. Indicators\nof an omitted dimension can acquire misleading loadings on the retained\ndimensions, factor correlations can shift, and structured residuals can\nremain. Too many factors can divide one broad pattern into weak or\nunstable directions, make residual variances approach a boundary, and\nencourage names for sample-specific features. Adding a dimension is not\nfree just because numerical reconstruction improves.\n\nRetention is therefore a question about the representation to carry\nforward, not a race to maximize variance accounted for. We consider\none through five factors before examining the results. Three is a\ncontent-based expectation, not a required outcome of the analysis.\nThe full range is retained in the record even when neighboring models\ngive inconvenient results.\n\n## Specify the matrix whose eigenvalues are being read\n\nA spectral eigenvalue satisfies\n\n$$\n\\mathbf R\\mathbf v_k=d_k\\mathbf v_k.\n$$ {#eq-efa-eigenvalue}\n\nIts meaning depends on the matrix. Eigenvalues of the full Pearson\nmatrix include all standardized observed variance and sum to $p$.\nEigenvalues of an SMC-reduced matrix use a different diagonal and need\nnot all be positive. An estimated common covariance has yet another\nspectrum. A printed column headed \"eigenvalue\" must therefore be\ninterpreted alongside the software's construction of that column.\n\nThe post-rotation column statistic\n\n$$\nSS_k=\\sum_{j=1}^p\\lambda_{jk}^2\n$$ {#eq-efa-ss}\n\nis an **SS loading**, not generally a spectral eigenvalue. In suitable\nunrotated orthogonal decompositions these quantities coincide; after\nrotation the column allocation can change while common covariance\nstays fixed. With correlated factors, pattern-column SS values do not\nprovide a unique additive partition of common variance. Chapter 1's\nrotated two-factor example already demonstrated the simpler orthogonal\nversion of this distinction.\n\n## Scree and the eigenvalue-greater-than-one heuristic\n\nThe familiar Kaiser--Guttman heuristic retains roots above one in a\nunit-diagonal correlation analysis. It compares a component's variance\nwith one observed standardized variable's variance. Sampling variation\nalone can create roots above one, so this is neither a necessary\ncondition for a useful common factor nor a reliable stand-alone count.\nApplying the same threshold to a reduced matrix changes the comparison\nand should not be treated as an interchangeable implementation.\n\nA scree plot instead asks where large decreases give way to a flatter\nsequence. It can reveal a distinct elbow, multiple plausible elbows,\nor no clear break. The method involves judgment: a visually appealing\nelbow does not supply a sampling reference. Full- and reduced-matrix\nplots need not agree, even when they do in the present example.\n\nIn Sample A, the first three full-matrix roots are\n4.380, 1.942, 1.487, followed by\n0.705. That drop makes three a plausible\ncandidate. It becomes more informative when compared with what equally\nsized data containing no cross-variable dependence would produce.\n\n## Parallel analysis compares against a matched null\n\nThe leading eigenvalues reported just above are comfortably greater than one. That is not by itself evidence of anything, because\n*random* data behave the same way. Correlate twelve unrelated variables in a\nsample of 360 and the largest eigenvalue will still exceed one, simply because\nsampling noise produces some correlations by chance and the leading eigenvalue\ncollects whatever structure happens to be there. The question a retention rule\nhas to answer is not \"is this eigenvalue large?\" but \"is it larger than chance\nalone would produce, in a dataset of exactly this shape?\"\n\nParallel analysis answers that question directly [@horn1965;\n@bujaEyuboglu1992]. It builds datasets that have no common factors but match\nthe real one in the two respects that govern the size of a chance eigenvalue -\nthe sample size and the empirical marginal distribution of each variable -\ncomputes their eigenvalues, and uses those as the yardstick. A dimension is retained while the observed eigenvalue stands\nabove what the no-factor datasets produced at the same rank.\n\n**Building the null.** The trick is to destroy the relationships between\nindicators while leaving everything else alone. Independently shuffling each\ncolumn does exactly that. After shuffling, item P1 still has its own 360\nvalues, its own mean, spread and skew - but which respondent's P1 sits beside\nwhich respondent's S3 is now arbitrary, so any correlation between them is\naccidental. Repeating this many times gives a distribution of eigenvalues under\n\"same items, same sample size, no common structure.\"\n\n**Choosing the threshold.** We compare each observed eigenvalue with the 95th\npercentile of its null distribution, not the mean:\n\n$$\nd_k^{\\mathrm{observed}}>\n Q_{.95}\\{d_{k,1}^{\\mathrm{null}},\\ldots,d_{k,B}^{\\mathrm{null}}\\}.\n$$ {#eq-efa-pa}\n\nThe difference matters. The mean is a central summary of the null\ndistribution, so an eigenvalue only a little above it clears the bar; the 95th\npercentile asks the eigenvalue to exceed all but the most extreme five per cent\nof chance results. The percentile reference is the more stringent of the two\nand generally retains no more dimensions than the mean, though which performs\nbetter depends on the population, the sample size and the strength of the\nfactors. They are two different decision rules, not two labels for one.\n\n**Counting.** We retain the *leading consecutive run* of dimensions that clear\ntheir references, and stop at the first that does not. Without that rule, an\nisolated crossing among the small trailing eigenvalues - where observed and\nnull curves nearly coincide and either may edge ahead - would be counted as a\nfurther meaningful dimension.\n\n@tbl-efa-pa-settings records the choices that would change the answer if made\ndifferently; anyone rerunning the analysis needs all four.\n\n| Choice | Value used here | Why it matters |\n|:--|:--|:--|\n| Null construction | Independent within-column permutation, without replacement | Preserves each item's own distribution while removing between-item structure |\n| Matrix compared | Pearson correlations, computed the same way for observed and null | Comparing an observed correlation matrix with a null covariance matrix is not a like-for-like test |\n| Reference | 95th percentile | The mean retains more dimensions; the choice is a decision rule, not a detail |\n| Replications and seed | 100, seed 12345 | Enough for a stable retained count in this example; the seed makes that count reproducible |\n\n: *The parallel-analysis settings that affect the retained count.* {#tbl-efa-pa-settings}\n\nA short note on implementation, because a function name can hide the rule it\napplies. The installed `psych` version's `fa.parallel(sim = FALSE)` resamples\neach column **with replacement**, which is a bootstrap rather than the\npermutation described above. Both are defensible null constructions, but they\nare not the same one, so this chapter uses an explicit loop:\n\n```r\nset.seed(12345)\nnull_roots <- replicate(100, {\n  X0 <- vapply(X, function(v) sample(v, replace = FALSE), numeric(nrow(X)))\n  eigen(cor(X0), symmetric = TRUE, only.values = TRUE)$values\n})\nreference_95 <- apply(null_roots, 1, quantile, probs = .95, type = 7)\n```\n\nRead from the inside out: `sample(v, replace = FALSE)` shuffles one column;\n`vapply` does that to all twelve, producing one null dataset; `eigen(cor(X0))`\nreturns its twelve eigenvalues; `replicate` repeats the whole thing 100 times,\ngiving a 12-by-100 matrix of null eigenvalues; and the last line takes the 95th\npercentile at each rank. A hundred replications is ample here - going to a\nthousand moves the reference values by about $.01$ and changes no retained\ncount.\n\n**Two targets, two panels.** @fig-efa-pa runs this comparison twice, and the\ndifference between its panels is the diagonal of the matrix being decomposed.\nThe left panel uses the full Pearson matrix, whose diagonal is all ones: its\neigenvalues describe *total* standardized variance, which is what a principal\ncomponent analysis decomposes. The right panel replaces that diagonal with SMCs\nbefore taking eigenvalues, so it describes only the variance each indicator\nshares with the others - closer to what a common-factor model tries to explain.\nReduced-matrix eigenvalues are smaller, and the later ones can be negative,\nwhich is why the two panels have different vertical scales and why an observed\ncurve must only ever be read against the reference drawn beside it. The same\ndiagonal rule is applied to every permuted matrix as well, so each panel is an\ninternally consistent comparison.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Scree and parallel-analysis evidence. Each observed sequence is compared only with its matching permutation reference.](chapter_02_files/figure-html/fig-efa-pa-1.png){#fig-efa-pa fig-align='center' fig-pos='H' fig-alt='Two panels show full Pearson and SMC-reduced eigenvalues against their separate permutation 95th percentiles. The first three observed roots exceed their references in each panel.' width=1152}\n:::\n:::\n\n\n\n::: {#tbl-efa-pa .cell layout-align=\"center\" tbl-cap='Leading observed and null-reference eigenvalues; full and reduced targets are not pooled.'}\n::: {.cell-output-display}\n\n\n|Dimension |Component |Component 95 |Factor |Factor 95 |\n|:---------|:---------|:------------|:------|:---------|\n|1         |4.380     |1.389        |3.849  |0.433     |\n|2         |1.942     |1.285        |1.430  |0.318     |\n|3         |1.487     |1.212        |0.918  |0.250     |\n|4         |0.705     |1.152        |-0.010 |0.189     |\n|5         |0.566     |1.092        |-0.021 |0.123     |\n\n\n:::\n:::\n\n\nBoth comparisons retain a leading run of three dimensions. For the\nthird component root, 1.487 exceeds\n1.212; for the fourth,\n0.705 does not exceed\n1.152. The reduced-matrix comparison\nreaches the same count by a different set of numerical comparisons.\nAgreement makes the candidate less dependent on this particular\ndiagonal choice, but does not turn the procedure into a proof that\nthree substantive attributes exist.\n\nPA addresses a matched null reference, not every plausible alternative\npopulation. Factor correlations, weak factors, minor dimensions,\nsample size, and the chosen root algorithm can change its performance.\nIt should be read alongside content, neighboring solutions, and\nresiduals.\n\n## A wider family of retention rules {#sec-efa-family}\n\nRetention is the decision an exploratory analysis most often gets wrong, and\nthe familiar heuristics are among the weaker available options.\n@auerswaldMoshagen2019 compared the main extraction criteria across realistic\nconditions - correlated factors, unequal loadings, minor factors, non-normal\nresponses, varying sample sizes - and found the eigenvalue-greater-than-one\nrule and the unaided scree plot performing poorly enough that neither should\ncarry a retention decision alone. Several better-behaved alternatives exist,\nand they are worth knowing not as a longer checklist but because each states a\ndifferent reference, and knowing the reference is what lets a disagreement be\ninterpreted.\n\n**Parallel analysis is a family, not a method.** Two choices generate four\ndistinct procedures. The roots may come from the full Pearson matrix, as in a\ncomponent analysis, or from a reduced matrix with communality estimates on the\ndiagonal, closer to the common-factor model. The null reference may be the\nmean of the simulated roots or their 95th percentile. Across\n@auerswaldMoshagen2019's conditions the component-based versions generally\noutperformed the reduced-matrix versions, and the mean reference tends to\nretain more dimensions than the percentile reference. All four share one\nstructural weakness: the reference data are uncorrelated by construction, so\nafter a strong first factor has absorbed much of the observed covariance, the\ncomparison for the second and later roots is no longer like for like, and a\ngenuine second dimension can be missed.\n\n**The empirical Kaiser criterion** repairs the Kaiser--Guttman rule rather\nthan discarding it [@braekenVanAssen2017]. Under the null model the sample\neigenvalues of uncorrelated variables are described asymptotically by a\nMarchenko--Pastur law\nwhose upper bound is $(1+\\sqrt{p/n})^2$; this is the reference for the first\nroot. Later roots are corrected for the variance already accounted for, and\nthe reference is never allowed below one:\n\n$$\n\\text{EKC}_j=\\max\\!\\left\\{(1+\\sqrt{p/n})^{2}\\,\n\\frac{p-\\sum_{i<j} d_i}{p-j+1},\\; 1\\right\\}.\n$$ {#eq-efa-ekc}\n\nWith $p=12$ and $n=360$ the first reference is\n1.398, appreciably above one: a leading root of\n$1.1$ would satisfy Kaiser--Guttman and fail the EKC. From the second root\nonward the correction term falls below one in this record, so the floor\napplies and the remaining references equal one. The criterion is therefore\nstricter than Kaiser--Guttman at the first root and identical afterwards -\nhere, on this data, which is exactly the sort of detail that a printed count\nconceals.\n\n**Sequential model tests** use the exact-fit statistic rather than an\neigenvalue. Fit a one-factor model; if its test is significant, fit two, and\ncontinue until a test is not significant. The logic is clean, but it carries a\ncaveat worth stating: once the number of factors exceeds the true number, the\nregularity conditions behind the $\\chi^2$ reference fail, so the sequence is\nonly trustworthy while it is still under-fitting. An earlier test that was\nsignificant by chance therefore propagates into further over-extraction rather\nthan being corrected.\n\n**Two further methods** appear in the comparison literature, though neither is\ncomputed here. The Hull method chooses the count at which the balance\nbetween fit and number of parameters stops improving, borrowing the convex-hull\nidea from model selection [@lorenzoSeva2011]. Comparison data generates\nreference datasets that *reproduce* the observed correlation matrix under a\nknown factorial structure of $1,2,3,\\ldots$ factors, rather than under\nindependence, and retains the smallest count whose reference data resemble the\nobserved data [@ruscioRoche2012]. Both address the same weakness in parallel\nanalysis: an uncorrelated null is not the relevant comparison once one factor\nis granted.\n\n@tbl-efa-family applies seven of these rules to the present record. The four\nparallel-analysis rows share the same permutation replications, so they differ\nonly in the target matrix and the reference statistic; Kaiser--Guttman, the\nempirical Kaiser criterion and the sequential tests use no permutations at all,\nand are included because they answer the same question from different\npremises.\n\n\n::: {#tbl-efa-family .cell layout-align=\"center\" tbl-cap='Seven retention rules on the same development record. What separates them is the reference each uses, not the data.'}\n::: {.cell-output-display}\n\n\n|Rule                        |Reference                                                  |Retained |\n|:---------------------------|:----------------------------------------------------------|:--------|\n|Kaiser-Guttman              |Root exceeds 1                                             |3        |\n|Empirical Kaiser criterion  |Root exceeds a sample-adjusted bound, floored at 1         |3        |\n|PA, component roots, mean   |Root exceeds the mean null root                            |3        |\n|PA, component roots, 95th   |Root exceeds the 95th-percentile null root                 |3        |\n|PA, reduced roots, mean     |Reduced root exceeds the mean null reduced root            |3        |\n|PA, reduced roots, 95th     |Reduced root exceeds the 95th-percentile null reduced root |3        |\n|Sequential chi-square tests |First non-significant exact-fit test                       |3        |\n\n\n:::\n:::\n\n\nEvery rule returns three. That agreement is a fact about this record, not a\ngeneral property of the methods, and it is what a well-behaved simulated\npopulation with three clearly separated factors is expected to produce. Real\nrecords disagree often, which is why @auerswaldMoshagen2019 recommend\n**combination rules** rather than any single criterion: when sequential model\ntests agree with either the 95th-percentile component parallel analysis or the\nempirical Kaiser criterion, the pair identified the correct count with high\nconsistency across their conditions. Sequential tests perform well with highly\ncorrelated factors but over-extract in the presence of minor factors and under\nnon-normality; the other two are robust and do not over-extract, which is why\nthey pair well.\n\nThe value of a combination rule is not that it counts votes. It is that\ndisagreement is informative: when these criteria diverge, the dimensions are\ngenuinely hard to detect in the available evidence, and the appropriate\nresponse is usually more data or a narrower claim rather than a casting vote.\nA majority vote among heuristics cannot replace explaining what each\ndiagnostic is comparing.\n\n# Estimate neighboring dimensional solutions\n\n## Count effective parameters, not every printed loading\n\nFor $p$ indicators, the symmetric covariance matrix supplies\n$u=p(p+1)/2$ distinct second moments. An exploratory model with $m$\northonormal factors appears to contain $pm$ loadings and $p$ uniquenesses.\nHowever, orthogonal rotations leave its implied covariance unchanged.\nThe $m(m-1)/2$ rotational degrees of freedom do not add independently\nrecoverable covariance parameters. The effective count is therefore\n\n$$\nt_m=pm+p-\\frac{m(m-1)}2,\n\\qquad\ndf_m=\\frac{p(p+1)}2-t_m\n=\\frac{(p-m)^2-p-m}{2}.\n$$\n\nThis is a dimension count for the unrestricted common-factor covariance\nmodel at regular points. An oblique rotation does not add factor\ncorrelations to this count: it re-expresses the same fitted covariance.\nCounting every oblique loading, every factor correlation, and every\nuniqueness as independently identified would count the same freedom\nmore than once.\n\n\n::: {#tbl-efa-counts .cell layout-align=\"center\" tbl-cap='Covariance-moment accounting for 12 indicators.'}\n::: {.cell-output-display}\n\n\n|Factors |Moments |Effective parameters |Candidate df |\n|:-------|:-------|:--------------------|:------------|\n|1       |78      |24                   |54           |\n|2       |78      |35                   |43           |\n|3       |78      |45                   |33           |\n|4       |78      |54                   |24           |\n|5       |78      |62                   |16           |\n\n\n:::\n:::\n\n\nThe nonnegative-df condition also yields the **Ledermann bound**, the largest\nfactor count the moments can generically support:\n\n$$\nm\\leq\\frac{2p+1-\\sqrt{8p+1}}2 ,\n\\qquad\\text{equivalently}\\qquad\n(p-m)^{2}\\ \\geq\\ p+m .\n$$ {#eq-ledermann}\n\nThe two forms state the same condition, and the second shows what it is doing:\nthe supply of distinct moments has to keep pace with the demand for\nparameters. For $p=12$ the bound is about $7.58$, so at most seven factors,\nand the accounting above passes through zero exactly there - three degrees of\nfreedom at seven factors, $-2$ at eight. The bound is not a recommendation to\nextract seven, a count of positive eigenvalues, or a proof of identification.\n\n## What the count leaves undetermined {#sec-efa-identification}\n\nChapter 1 separated counting from **identification**: counting can rule a model\nout, but a nonnegative $df$ never establishes that the moments determine the\nparameters. Exploratory analysis is the clearest illustration, because an\nunrestricted factor model is *by construction* unidentified. There is really\none problem here rather than three - the model is invariant under a family of\ntransformations of the factors - but that family has a continuous part and two\ndiscrete parts, and they show up differently in practice.\n\n**Rotational indeterminacy** is the substantial one. For any nonsingular\n$m\\times m$ matrix $\\mathbf T$,\n\n$$\n\\boldsymbol\\Lambda^{*}=\\boldsymbol\\Lambda\\mathbf T^{-1},\n\\qquad\n\\boldsymbol\\Phi^{*}=\\mathbf T\\boldsymbol\\Phi\\mathbf T^{\\mathsf T}\n$$ {#eq-efa-rotation}\n\nleaves $\\boldsymbol\\Lambda\\boldsymbol\\Phi\\boldsymbol\\Lambda^{\\mathsf T}$\nunchanged, so a continuous family of loading matrices reproduces the observed\ncovariance identically. Restricting $\\mathbf T$ to be orthogonal leaves a\nfamily of dimension $m(m-1)/2$ - precisely the quantity subtracted in the\nparameter count above. The count has therefore already paid for this freedom;\nit has not removed it.\n\n**Sign reversal** and **column permutation** are the discrete members of the\nsame family: both are special cases of $\\mathbf T$, one a diagonal matrix of\n$\\pm 1$ and the other a permutation matrix. Reversing the sign of an entire loading column together with its\nfactor changes nothing observable, so $2^{m}$ sign patterns are equivalent;\nand the factors carry no intrinsic order, so any of the $m!$ permutations of\nthe columns describes the same model. Neither costs a degree of freedom,\nbecause neither is a continuous direction, which is why $df$ is silent about\nthem. They are still real. Two runs of the same routine on the same data can\nreturn one solution with a column negated or two columns exchanged, and\ncomparing the two naively would suggest a difference that does not exist. It\nis why the sensitivity comparisons later in this chapter align column order\nand sign before anything is compared.\n\nWhat an exploratory analysis identifies is therefore the *common space* the\nfactors span - not the particular axes that get printed. At regular,\ngenerically identified parameter values the communalities and residual\nvariances are also determined, since they are invariant under the whole\ntransformation family; exceptional configurations, such as a boundary solution\nor a rank-deficient loading matrix, are not covered by that statement. Rotation does not resolve the\nindeterminacy; it selects one member of the family on stated grounds, which is\nexactly why the criterion has to be declared rather than accepted as a\ndefault. A confirmatory model takes the other route, fixing enough loadings in\nadvance that no nontrivial $\\mathbf T$ preserves the pattern - at which point\nidentification stops being automatic and has to be argued.\n\n## Fit one through five; inspect two, three, and four closely\n\nWe estimate normal-theory ML common-factor models for one through five\nfactors. Each fit uses the same Pearson matrix, $n=360$, SMC starts,\nand the same uniqueness-bound convention. The primary extraction is\nunrotated; rotation is a subsequent choice of axes. The printed code\nshows the essential calls; the chapter source carries the convergence checks\nand the full settings.\n\n```r\nfit3 <- psych::fa(R, nfactors = 3, n.obs = nrow(X),\n                  fm = \"ml\", rotate = \"none\", SMC = TRUE,\n                  smooth = FALSE, scores = \"none\")\nA <- unclass(fit3$loadings)\n```\n\nTwo details about this call repay attention, because both are easy to\nmisread. `psych::fa()` accepts `min.err` and `max.iter`, and it is tempting to\npresent them as convergence controls for every extraction method. Under\n`fm = \"ml\"` in the installed version they do not govern the optimizer: the\nsame solution is returned whether they are set tightly or loosely. They\ncontrol the iterative principal-axis path instead. Second, the smallest\nuniqueness this implementation will return under ML is bounded below at\n$.005$, which is why the four- and five-factor solutions in the table below\nreport a minimum uniqueness at exactly that value rather than at zero. Neither\nfact is a defect; both are reasons to read a function's documentation for the\nmethod actually being used rather than for the function as a whole.\n\nThe implemented analysis also checks the ML objective using\n`stats::factanal()` with five starting values. Agreement of independently\ncomputed objectives is a useful numerical check, not proof that the\nscientific model is correct. A numerical algorithm can converge perfectly\nto an inadequate model.\n\n\n::: {#tbl-efa-neighbors .cell layout-align=\"center\" tbl-cap='Neighboring ML solutions. RMS uses distinct off-diagonal correlation residuals.'}\n::: {.cell-output-display}\n\n\n|Factors |df |F ML  |RMS offdiag |Max residual |Min uniqueness |Boundary |\n|:-------|:--|:-----|:-----------|:------------|:--------------|:--------|\n|1       |54 |2.063 |0.146       |0.497        |0.445          |FALSE    |\n|2       |43 |0.797 |0.086       |0.321        |0.245          |FALSE    |\n|3       |33 |0.089 |0.015       |0.034        |0.202          |FALSE    |\n|4       |24 |0.050 |0.013       |0.030        |0.005          |TRUE     |\n|5       |16 |0.022 |0.009       |0.027        |0.005          |TRUE     |\n\n\n:::\n:::\n\n\nThe two-factor solution leaves a largest absolute residual correlation\nof 0.321, compared with\n0.034 for three factors. That is a\nsubstantial change in the covariance reconstruction, not merely an\nadditional column of interpretable words. Adding a fourth factor reduces\nthe discrepancy further, but its smallest uniqueness is approximately\n.005, at the numerical lower bound. The fifth-factor solution does the\nsame. A bound prevents an optimizer from reporting a negative uniqueness;\nit does not make that boundary estimate substantively credible.\n\nAn interior uniqueness of .20 and a bound-constrained uniqueness of .005\nare qualitatively different evidence. The latter can signal too many\nfactors, a highly redundant pair, sampling fluctuation, or a misspecified\ncommon-factor model. Inspect its indicator and neighboring pattern before\nassigning a new construct name. Do not silently omit the bound from the\nreport or describe it as evidence of nearly perfect measurement.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Oblimin patterns for neighboring dimensions. Column signs and order are arbitrary across different factor counts; compare item groupings, not column numbers.](chapter_02_files/figure-html/fig-efa-neighbors-1.png){#fig-efa-neighbors fig-align='center' fig-pos='H' fig-alt='Three heatmaps display all loadings in the two-, three-, and four-factor solutions, allowing comparison of merged and split item groups.' width=1152}\n:::\n:::\n\n\nRead this display in two directions. Down a column, ask which items\ndefine a coherent factor. Across a row, ask whether an item has a stable\nprimary relation or is distributed across factors. A smaller model must\nrepresent more covariance using fewer common directions; it may merge\ndomains or leave patterned residuals. A larger model can separate narrow\nitem-specific covariance that does not justify an additional broad\nconstruct. In neither case is a short label an adequate diagnostic.\n\n## An exact-fit test is one piece of evidence\n\nFor reference, `psych` reports a corrected ML statistic of the form\n\n$$\nT_m=\\left[n-1-\\frac{2p+5}{6}-\\frac{2m}{3}\\right]\n\\widehat F_{\\mathrm{ML}}.\n$$\n\nUnder the exact factor model and suitable regularity conditions, its\nreference is approximately $\\chi^2_{df_m}$. For the three-factor fit,\n$T_3=$ 31.327 with 33 df, giving\n$p=$ 0.551. This does not establish that\nthe factor interpretation is true; it says that this discrepancy is not\nunusual under the exact-model reference used by the test. Power and\nmisspecification size matter. A nonsignificant test cannot establish\nequivalence or rule out consequential departures.\n\nThe fourth- and fifth-factor solutions reach a variance boundary, where\nordinary interior-point chi-square arguments need additional care. Their\nlarge conventional $p$ values should not be used to endorse extra factors.\nNor should one subtract any two displayed factor tests and automatically\ndeclare a regular nested likelihood-ratio test: changes of factor count\ninvolve singular or boundary configurations under the smaller model.\n\nChapter 3 uses raw-data ML with an explicit normal-likelihood convention.\nIts test multiplier is not this small-sample EFA correction. Comparability\nof estimation families does not mean every package reports an identical\nfinite-sample test statistic.\n\n# Resolve the orientation by rotation\n\n## What rotation changes, and what it preserves\n\nAn unrotated solution is convenient for estimation but often inconvenient\nfor interpretation. Suppose the extracted common covariance is\n$\\mathbf A\\mathbf A^{\\mathsf T}$. For an orthogonal matrix $\\mathbf Q$,\nwith $\\mathbf Q^{\\mathsf T}\\mathbf Q=\\mathbf I$,\n\n$$\n\\mathbf P=\\mathbf A\\mathbf Q\n\\quad\\Longrightarrow\\quad\n\\mathbf P\\mathbf P^{\\mathsf T}\n=\\mathbf A\\mathbf A^{\\mathsf T}.\n$$\n\nThe rows of $\\mathbf P$ locate the indicators in a rotated axis\nsystem. The reproduced covariance, communalities, uniquenesses, and\nextraction discrepancy are unchanged. The individual loading coefficients\nchange because they refer to different axes.\n\nThe general nonsingular transformation requires a paired change. Let\n$\\boldsymbol\\eta^*=\\mathbf T\\boldsymbol\\eta$, where the original\nfactor covariance is $\\mathbf I$. Then\n\n$$\n\\mathbf P=\\mathbf A\\mathbf T^{-1},\\qquad\n\\boldsymbol\\Phi^*=\\mathbf T\\mathbf T^{\\mathsf T},\n$$\n\nand\n\n$$\n\\begin{aligned}\n\\mathbf P\\boldsymbol\\Phi^*\\mathbf P^{\\mathsf T}\n&=\\mathbf A\\mathbf T^{-1}\\mathbf T\\mathbf T^{\\mathsf T}\n  (\\mathbf T^{-1})^{\\mathsf T}\\mathbf A^{\\mathsf T}\\\\\n&=\\mathbf A\\mathbf A^{\\mathsf T}.\n\\end{aligned}\n$$\n\nIf the transformed factor variances are subsequently rescaled to one,\nthe loading columns must be rescaled correspondingly. Multiplying the\nloadings by an arbitrary matrix while leaving $\\boldsymbol\\Phi$\nunchanged is not an equivalent oblique rotation. This inverse-paired\ntransformation is the same principle introduced in Chapter 1.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![A change of axes in a two-dimensional illustration. These are illustrative loadings, not a second empirical data set.](chapter_02_files/figure-html/fig-efa-rotation-1.png){#fig-efa-rotation fig-align='center' fig-pos='H' fig-alt='Three panels show the same four indicators under original, orthogonal, and oblique factor coordinates; oblique coordinates require a matching factor covariance.' width=1152}\n:::\n:::\n\n\n## Orthogonal and oblique simple structure\n\nSimple structure favors interpretable differentiation: relatively few\nsubstantial relations per item and identifiable groups of indicators.\nIt is an orientation criterion, not a new criterion of fit to the observed\ncovariance matrix. Rotation does not improve $F_{\\mathrm{ML}}$.\n\nVarimax is an orthogonal criterion. In an unnormalized version it\nmaximizes, across columns, the dispersion of squared loadings:\n\n$$\nV(\\mathbf P)=\\sum_{a=1}^m\n\\left\\{\\frac1p\\sum_{j=1}^p p_{ja}^4\n-\\left(\\frac1p\\sum_{j=1}^p p_{ja}^2\\right)^2\\right\\}.\n$$\n\nA column with some larger and some smaller squared loadings has a higher\ncriterion than a column whose squared loadings are all similar. The\northogonality constraint remains in force; a clean-looking varimax\npattern does not establish that the substantive attributes are unrelated.\n\nOblique criteria permit factor correlations while seeking a simpler\npattern. Here the primary rotation is direct oblimin with $\\gamma=0$\n(quartimin), no Kaiser normalization, convergence tolerance $10^{-7}$,\nup to 10,000 iterations, and 20 random starts. At $\\gamma=0$, the\ncriterion discourages a row from having large squared coefficients in\nseveral columns. It does not set the factor correlations to zero.\n\n```r\nset.seed(12345)\nrot3 <- GPArotation::oblimin(A, gam = 0, normalize = FALSE,\n                            eps = 1e-7, maxit = 10000,\n                            randomStarts = 20)\npattern <- unclass(rot3$loadings)\nfactor_correlations <- rot3$Phi\n```\n\nKaiser normalization, when requested, divides each row by its\ncommunality-based length before optimizing and restores its scale\nafterward. That changes the criterion's relative weighting of indicators.\nIt is not the same operation as standardizing the original observed\nvariables. Because implementation details can affect the chosen\norientation, the rotation name alone is not a sufficient specification.\n\nMultiple starts reduce dependence on a single starting orientation but\ndo not prove that a global optimum was found. Signs and column order are\nalso arbitrary. Our reported solution aligns columns with the first\nthree content anchors in each domain and makes their summed primary\nloadings positive. This is a labeling convention applied after fitting;\nit is not an extra model restriction.\n\n## Why the oblique solution is primary here\n\nPlanning, strategy adjustment, and belonging need not be independent.\nThe oblimin solution estimates the following factor correlations:\n\n\n::: {#tbl-efa-phi .cell layout-align=\"center\" tbl-cap='Factor correlation matrix in the aligned three-factor oblimin solution.'}\n::: {.cell-output-display}\n\n\n|Factor    |Planning |Strategy |Belonging |\n|:---------|:--------|:--------|:---------|\n|Planning  |1.000    |0.464    |0.312     |\n|Strategy  |0.464    |1.000    |0.336     |\n|Belonging |0.312    |0.336    |1.000     |\n\n\n:::\n:::\n\n\nThese are estimated relations between the chosen common-factor\naxes. They are not causal paths, observed scale correlations, or\nproof that the same orientation would be uniquely recovered in another\nsample. Varimax provides a useful comparison precisely because it\nrepresents the same common covariance with orthogonal axes.\nThe maximum absolute difference in reproduced common covariance between\nthe reported oblimin and varimax solutions is\n8.9e-16.\nThe near-zero value verifies invariance; it does not make their loading\ntables interchangeable.\n\n# Read an oblique factor system\n\n## Pattern coefficients and structure correlations\n\nWith standardized indicators and unit-variance factors, the pattern\nmatrix $\\mathbf P$ contains the coefficients in\n\n$$\n\\mathbf z_i=\\mathbf P\\boldsymbol\\eta_i+\\boldsymbol\\epsilon_i.\n$$\n\nEach row is a simultaneous linear decomposition. A coefficient describes\nthe relation of that factor to the indicator conditional on the other\nfactors in this representation. The structure matrix instead gives the\nzero-order indicator--factor correlations:\n\n$$\n\\mathbf C=\\operatorname{Cov}(\\mathbf z,\\boldsymbol\\eta)\n=\\mathbf P\\boldsymbol\\Phi.\n$$\n\nSince both sides have unit marginal variances, those covariances are\ncorrelations. In an orthogonal solution $\\boldsymbol\\Phi=\\mathbf I$,\nso pattern and structure coincide. In an oblique solution they generally\ndo not.\n\n\n::: {#tbl-efa-pattern .cell layout-align=\"center\" tbl-cap='All pattern coefficients. Small entries remain visible; none were suppressed at .30.'}\n::: {.cell-output-display}\n\n\n|Item |Planning |Strategy |Belonging |\n|:----|:--------|:--------|:---------|\n|P1   |0.783    |0.018    |-0.040    |\n|P2   |0.784    |-0.056   |-0.021    |\n|P3   |0.720    |-0.062   |0.066     |\n|P4   |0.679    |0.188    |0.033     |\n|S1   |0.000    |0.794    |-0.037    |\n|S2   |0.057    |0.677    |0.016     |\n|S3   |-0.002   |0.685    |-0.036    |\n|S4   |0.030    |0.536    |0.261     |\n|B1   |0.045    |-0.047   |0.894     |\n|B2   |-0.044   |0.055    |0.829     |\n|B3   |-0.031   |0.041    |0.610     |\n|B4   |0.046    |-0.047   |0.515     |\n\n\n:::\n:::\n\n\n\n::: {#tbl-efa-structure .cell layout-align=\"center\" tbl-cap='Structure correlations for the same orientation.'}\n::: {.cell-output-display}\n\n\n|Item |Planning |Strategy |Belonging |\n|:----|:--------|:--------|:---------|\n|P1   |0.779    |0.368    |0.210     |\n|P2   |0.751    |0.300    |0.205     |\n|P3   |0.712    |0.294    |0.270     |\n|P4   |0.777    |0.514    |0.308     |\n|S1   |0.357    |0.781    |0.229     |\n|S2   |0.376    |0.709    |0.261     |\n|S3   |0.305    |0.672    |0.193     |\n|S4   |0.361    |0.638    |0.451     |\n|B1   |0.303    |0.274    |0.892     |\n|B2   |0.240    |0.313    |0.834     |\n|B3   |0.179    |0.232    |0.614     |\n|B4   |0.185    |0.147    |0.513     |\n\n\n:::\n:::\n\n\nFor P4, the Strategy structure correlation is\n\n$$\nc_{\\mathrm{P4,S}}\n=p_{\\mathrm{P4,P}}\\phi_{\\mathrm{PS}}\n +p_{\\mathrm{P4,S}}+p_{\\mathrm{P4,B}}\\phi_{\\mathrm{BS}}.\n$$\n\nSubstituting the unrounded estimates gives\n0.514. The direct Strategy\npattern coefficient is only 0.188.\nMuch of the zero-order relation reflects P4's Planning loading together\nwith the Planning--Strategy association. Reading the structure matrix as\nif every entry were a separate direct loading would therefore exaggerate\ncross-loading complexity.\n\nConversely, dismissing every secondary pattern coefficient below .30\nwould conceal the two content-relevant relations under consideration.\nP4 concerns revising a plan when a method fails; S4 concerns using others\nto improve a learning strategy. Their secondary coefficients,\n0.188 and\n0.261, are evidence to evaluate alongside\ncontent, orientation sensitivity, and later independent estimation.\nThey are not established nonzero population coefficients merely because\nwe can give them plausible names.\n\n## Communality is a quadratic form\n\nFor indicator $j$, let $\\mathbf p_j^{\\mathsf T}$ be row $j$ of the\npattern matrix. Its common variance is\n\n$$\nh_j^2=\\mathbf p_j^{\\mathsf T}\\boldsymbol\\Phi\\mathbf p_j,\n\\qquad\nu_j^2=1-h_j^2.\n$$\n\nFor three standardized factors this expands to\n\n$$\nh_j^2=p_{j1}^2+p_{j2}^2+p_{j3}^2\n +2p_{j1}p_{j2}\\phi_{12}\n +2p_{j1}p_{j3}\\phi_{13}\n +2p_{j2}p_{j3}\\phi_{23}.\n$$\n\nThe cross-products are part of the common variance. Summing squared\npattern coefficients alone drops them. For P4, the row sum of squared\npattern coefficients is 0.498, whereas the\ncommunality is 0.635. Neither number should be\nlabeled the variance uniquely explained by Planning.\n\n\n::: {#tbl-efa-communalities .cell layout-align=\"center\" tbl-cap='Common and unique variance in the standardized metric. Row sums of squared pattern coefficients are included only to expose the oblique distinction.'}\n::: {.cell-output-display}\n\n\n|Item |Pattern SS |Communality |Uniqueness |\n|:----|:----------|:-----------|:----------|\n|P1   |0.616      |0.609       |0.391      |\n|P2   |0.618      |0.568       |0.432      |\n|P3   |0.527      |0.512       |0.488      |\n|P4   |0.498      |0.635       |0.365      |\n|S1   |0.631      |0.612       |0.388      |\n|S2   |0.462      |0.505       |0.495      |\n|S3   |0.471      |0.453       |0.547      |\n|S4   |0.356      |0.470       |0.530      |\n|B1   |0.803      |0.798       |0.202      |\n|B2   |0.693      |0.698       |0.302      |\n|B3   |0.374      |0.379       |0.621      |\n|B4   |0.269      |0.266       |0.734      |\n\n\n:::\n:::\n\n\nThe column sums of squared loadings reported by software are useful\ndescriptions of an orientation, but correlated factors do not provide a\nunique additive allocation of common variance to separate constructs.\nOne cannot turn overlapping factor relations into mutually exclusive\npercentages simply by dividing each column sum by $p$.\n\nA low communality can mean that an indicator is weakly represented by\nthis common-factor system. It does not by itself show poor wording or\njustify removal. An indicator may intentionally cover content absent\nfrom the other items. Removing it can make the covariance model cleaner\nwhile narrowing the construct. A high communality can likewise arise\nfrom redundancy rather than desirable breadth.\n\n## Reconstruct a pair, then the whole matrix\n\nUnder diagonal uniqueness, the reproduced correlation of distinct\nindicators $j$ and $k$ is\n\n$$\n\\widehat r_{jk}=\\widehat{\\mathbf p}_j^{\\mathsf T}\n\\widehat{\\boldsymbol\\Phi}\\widehat{\\mathbf p}_k.\n$$\n\nAll primary and secondary coefficients participate. For P4 and S4,\nthe observed correlation is 0.368 and the\nreproduced correlation is 0.380.\nThe residual, defined as observed minus reproduced, is\n-0.012. Its sign is interpretable only\nafter the subtraction convention is stated.\n\n```r\ncommon <- pattern %*% factor_correlations %*% t(pattern)\ncommunality <- diag(common)\nreproduced <- common + diag(fit3$uniquenesses)\nresidual <- R - reproduced\n```\n\nThis short calculation is more informative than memorizing the names of\nseveral output tables. It links loadings, factor correlations,\ncommunalities, uniquenesses, and residuals to one covariance equation.\nWhen a table cannot be reconstructed from that equation, first check\nthe standardization and rotation conventions rather than inventing a\nsubstantive explanation.\n\n## What is uncertain about this interpretation?\n\nSampling affects extraction, factor count, orientation, and the apparent\nstability of item assignments. A coefficient reported to three decimals\nis not thereby precise to three decimals. The comparisons below examine\nspecified analytic alternatives on one sample; they do not provide a\nsampling confidence interval. Bootstrap analysis would additionally\nrequire re-estimation, alignment, and a decision about whether the factor\ncount is held fixed. Unaligned bootstrap columns cannot sensibly be\naveraged.\n\nFactor scores are another distinct object. EFA estimates a population\ncovariance representation; individual latent values are not observed\nmerely because loadings have been estimated. Alternative scoring rules\ncan produce different scores under the same factor model. Chapter 4\ndevelops this issue after measurement-model evaluation.\n\n# Check reconstruction and analytic sensitivity\n\n## Examine local residuals, not only an average\n\nDefine the correlation residual matrix\n\n$$\n\\mathbf E=\\mathbf R-\\widehat{\\mathbf R},\n\\qquad\n\\mathrm{RMS}_{\\mathrm{off}}\n=\\sqrt{\\frac{2}{p(p-1)}\\sum_{j<k}e_{jk}^2}.\n$$\n\nThe off-diagonal average deliberately excludes variances. It is not\nautomatically identical to every software statistic called RMSR or SRMR.\nIts definition here is transparent and reproducible. The largest\nabsolute residual supplies different information: one problematic pair\ncan be concealed by averaging many small residuals.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Observed minus reproduced correlations for the three-factor ML solution. The scale is centered on zero.](chapter_02_files/figure-html/fig-efa-residual-1.png){#fig-efa-residual fig-align='center' fig-pos='H' fig-alt='A labeled residual heatmap shows small positive and negative discrepancies across the twelve indicators, with values printed in every cell.' width=1008}\n:::\n:::\n\n\n\n::: {#tbl-efa-residual-pairs .cell layout-align=\"center\" tbl-cap='Eight largest absolute off-diagonal residuals, with observed and reproduced values.'}\n::: {.cell-output-display}\n\n\n|Item1 |Item2 |Observed |Reproduced |Residual |\n|:-----|:-----|:--------|:----------|:--------|\n|B2    |S3    |0.150    |0.184      |-0.034   |\n|B4    |S3    |0.049    |0.082      |-0.033   |\n|S4    |S2    |0.487    |0.459      |0.027    |\n|S4    |P2    |0.264    |0.237      |0.027    |\n|B4    |S1    |0.123    |0.098      |0.026    |\n|B3    |P2    |0.139    |0.114      |0.025    |\n|B1    |S3    |0.180    |0.155      |0.025    |\n|B2    |P4    |0.225    |0.249      |-0.024   |\n\n\n:::\n:::\n\n\nAsk whether residuals concentrate within a domain, between two domains,\nor around a particular item. Those patterns suggest different questions\nabout omitted common dimensions, secondary loadings, and local residual\nrelations. A residual is evidence of unreproduced covariance, not a label\nfor its cause. An unrestricted exploratory loading pattern can also\nabsorb a local relation into its common part. Small EFA residuals therefore\ndo not certify that every later simple-structure CFA restriction is safe.\n\n## KMO and Bartlett answer preliminary questions\n\nLet $a_{jk}$ be the partial correlation between indicators $j$ and $k$\ncontrolling the remaining indicators. A common overall KMO statistic is\n\n$$\n\\mathrm{KMO}=\n\\frac{\\sum_{j<k}r_{jk}^2}\n{\\sum_{j<k}r_{jk}^2+\\sum_{j<k}a_{jk}^2}.\n$$\n\nThe sample value is 0.843. It is larger when the squared\npartial correlations are small relative to the squared zero-order\ncorrelations. That is a useful compact description, but it neither\nselects the number of factors nor establishes the meaning of any factor.\nIt is also not a universal minimum-sample-size calculation.\n\nBartlett's sphericity test addresses $H_0:\\mathbf R_{\\mathrm{population}}\n=\\mathbf I$. A familiar normal-theory approximation is\n\n$$\nT_B=-\\left[n-1-\\frac{2p+5}{6}\\right]\\log|\\mathbf R|,\n\\qquad df_B=\\frac{p(p-1)}2.\n$$\n\nHere $T_B=$ 1675.5 on 66 df. Rejecting an identity\ncorrelation matrix says that the indicators are not mutually uncorrelated\nin the population under the test assumptions. It does not show that a\nparticular low-dimensional factor model fits. A matrix with complicated\nlocal dependencies can readily reject sphericity.\n\nUse these summaries to characterize the input, not as entrance tickets\nthat replace inspecting the correlation matrix, positive definiteness,\nindicator content, and the fitted model.\n\n## Change one analytic choice at a time\n\nTwo bounded sensitivity analyses use the same observations, variables,\nand Pearson matrix. First, keep ML extraction and use oblique geomin\nrotation with $\\delta=.01$, no normalization, and 20 starts. Second,\nkeep three factors and oblimin but replace ML extraction by minres.\nThe first changes the orientation criterion; the second changes how\nthe covariance discrepancy is weighted.\n\nSigns and factor order are aligned before comparing coefficients.\nFor loading columns $\\mathbf a$ and $\\mathbf b$, Tucker's congruence\ncoefficient is\n\n$$\nc(\\mathbf a,\\mathbf b)=\n\\frac{\\mathbf a^{\\mathsf T}\\mathbf b}\n{\\sqrt{\\mathbf a^{\\mathsf T}\\mathbf a}\n \\sqrt{\\mathbf b^{\\mathsf T}\\mathbf b}}.\n$$\n\nIt compares the directions of two coefficient vectors, not the\ncorrelation between participant scores. Near-one congruence can coexist\nwith an important difference for one item, so also inspect the largest\ncoefficient difference and the relevant rows.\n\n\n::: {#tbl-efa-sensitivity .cell layout-align=\"center\" tbl-cap='Aligned sensitivity comparisons against primary ML oblimin. These are same-sample analytic checks, not independent replications.'}\n::: {.cell-output-display}\n\n\n|Analysis       |Max pattern difference |Max Phi difference |Min congruence |\n|:--------------|:----------------------|:------------------|:--------------|\n|ML oblimin     |0.000                  |0.000              |1.000          |\n|ML geomin      |0.029                  |0.022              |0.999          |\n|Minres oblimin |0.011                  |0.001              |1.000          |\n\n\n:::\n:::\n\n\nThe largest pattern change under geomin is\n0.029; under minres\nit is 0.011.\nThe principal item groupings and the two content-relevant secondary\nrelations persist. This supports carrying a specific candidate forward\nwithout claiming that all reasonable analyses have been exhausted.\nChanging the item set, sample, distributional assumptions, or factor\ncount would be a different sensitivity question.\n\nThe defensible conclusion is deliberately narrower than “the scale is\nvalidated.” Three correlated dimensions summarize Sample A better than\ntwo, the main orientation is interpretable and stable across these\nlimited checks, and the larger fitted solutions encounter boundaries.\nThese observations justify a candidate to test elsewhere.\n\n# Summary and reading bridge {#sec-summary-bridge}\n\nEFA is a sequence of linked decisions. The input matrix establishes the\nobserved metric. Extraction states which covariance structure is being\napproximated and how discrepancies are weighted. Retention selects a\nplausible dimension using matched reference comparisons, content, and\nneighboring solutions. Rotation chooses interpretable axes\nwithout changing the fitted covariance. Interpretation then requires\npattern, structure, factor correlations, and the quadratic-form\ncommunality to be read together.\n\nThe Sample A record supports a three-factor candidate, not a final\nmeasurement verdict. Both declared parallel analyses retain three\ndimensions; two factors leave appreciably larger residuals; four and\nfive reach uniqueness bounds. The primary oblique pattern and limited\nsame-sample sensitivity checks support three content-defined domains -\nPlanning, Strategy and Belonging - together with two secondary loadings that\nare retained on content grounds rather than by a numerical cutoff: P4 on\nStrategy and S4 on Belonging. All twelve indicators are kept, in the codebook\norder, and every other cross-loading and every residual covariance would be\nfixed at zero in a restricted version of this model. That specification, and\nthe stricter simple-structure alternative that fixes both secondary loadings\nto zero, are what a confirmatory analysis on unused data would have to test.\n\nNaming those alternatives now is part of the transition, because a comparison\ndecided in advance is interpretable and one invented after seeing the\nconfirmation data is not. Five models are therefore fixed here, before any\nconfirmation outcomes or statistics are inspected or used:\n\n| Label | Specification | Free covariance parameters | Candidate df |\n|:--|:--|--:|--:|\n| **M1-cross** | The primary candidate: three correlated factors, P4 also on Strategy, S4 also on Belonging | 29 | 49 |\n| **M0-simple** | Both secondary loadings fixed at zero | 27 | 51 |\n| **M2-orthogonal** | All three factor correlations fixed at zero | 26 | 52 |\n| **M3-equal** | The raw P1 and P2 Planning loadings constrained equal | 28 | 50 |\n| **M4-one** | A single common factor for all twelve indicators | 24 | 54 |\n\n: *The five models fixed before any confirmation outcome is inspected or used.* {#tbl-efa-rivals}\n\nAll five use the same twelve indicators in codebook order, fixed-factor\nscaling, and no residual covariances. M0, M2 and M3 are restrictions of\nM1-cross; M4-one is a broader dimensional rival whose relation to a correlated\nthree-factor model is not an ordinary nested comparison, for reasons taken up\nwhere models are compared.\n\nA compact report could read:\n\n> We analyzed Pearson correlations for 12 complete continuous indicators\n> in a simulated development sample of 360 cases. Matched 95th-percentile\n> permutation references for full and SMC-reduced eigenvalues both\n> retained three dimensions. Neighboring ML models and residual inspection\n> supported examining a three-factor representation; four- and five-factor\n> fits reached uniqueness bounds. Direct oblimin with stated settings\n> produced interpretable correlated domains. Geomin and minres checks\n> gave closely aligned patterns. A 12-indicator CFA candidate with two\n> content-motivated secondary loadings was fixed for independent-sample\n> estimation; this development analysis is not itself confirmation.\n\nFor mathematical background, connect the common-factor representation\nand rotational indeterminacy to @mulaik2010 and @bartholomewKnott1999.\nRead @horn1965 for the parallel-analysis idea and @bujaEyuboglu1992 for\nthe permutation perspective and qualifications. The historical oblique\nrotation literature includes @jennrichSampson1966. Software documentation\nis indispensable for implementation details, especially distinctions\nbetween simulation, resampling, and permutation.\n\nChapter 3 now changes the question: **given the fixed zero, free, and\nequality restrictions, can a CFA be specified, identified, and estimated\ncoherently?** An exploratory orientation becomes a confirmatory model\nonly when its restrictions and analytic history are made explicit.\n\n# Exercises {.unnumbered}\n\nThe following exercises are answer-free. Use the printed tables where\npossible; code is optional unless a prompt explicitly asks for it.\n\n1. **Identify the target.** An analyst extracts principal\n   components from $\\mathbf R$ and calls the discarded component variance\n   “measurement error.” Explain the missing common-factor assumptions.\n   For $\\mathbf R=\\begin{bmatrix}1&.6\\\\.6&1\\end{bmatrix}$, obtain its\n   eigenvalues and the variance represented by the first component.\n2. **Update a diagonal.** For the three-variable matrix\n   $\\mathbf R=\\begin{bmatrix}1&.5&.4\\\\.5&1&.3\\\\.4&.3&1\\end{bmatrix}$,\n   calculate the SMCs using $1-1/(\\mathbf R^{-1})_{jj}$. Form the reduced\n   matrix and describe one principal-axis update. Explain why a negative\n   reduced-matrix eigenvalue is not automatically a negative variance.\n3. **Examine the count.** Derive the effective parameter\n   counts and candidate df for $p=8$, $m=1,2,3$. Explain the rotational\n   subtraction and why a nonnegative count does not prove identification.\n4. **Match the null.** At ranks 1--4, observed roots are\n   $3.8,1.5,.9,.2$, and matching permutation 95th percentiles are\n   $.5,.3,.2,.1$. Determine the leading crossing count. Explain why this\n   table cannot be interpreted without knowing which matrix generated\n   the roots, and why a full-matrix reference cannot replace a reduced one.\n5. **Read an oblique row.** For pattern row $(.6,.3)$ and\n   factor correlation .4, compute the two structure correlations,\n   communality, and uniqueness of a standardized indicator. Explain why\n   the sum of squared pattern coefficients gives a different result.\n6. **Compare dimensions.** Using the one-to-five-factor\n   table and neighboring-pattern figure, recommend a dimension for further\n   study. Discuss the uniqueness boundary and explain why neither the\n   smallest discrepancy nor the largest conventional $p$ value is a\n   sufficient decision rule.\n7. **Evaluate an item.** Contrast P4 and B4 using wording,\n   pattern, structure, and communalities. Propose what additional evidence\n   would be needed before deleting either. Do not use a loading cutoff\n   as the complete rationale.\n8. **State the transition.** Write the free/fixed relation\n    ledger for two restricted models: the three-factor candidate that keeps the\n    P4 and S4 secondary loadings free, and the stricter version that fixes both\n    at zero. Give the free-parameter count and candidate df for each against\n    the 78 distinct moments of twelve indicators. Then identify which evidence\n    could and could not be used to choose between them, and explain what\n    changes if a model is revised after inspecting a second sample.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n# Appendix A: SLE data dictionary and sample manifest {#sec-sle-data .unnumbered}\n\n```{=latex}\n\\Needspace{6\\baselineskip}\n```\n\nThe downloadable file [sle_continuous.csv](sle_continuous.csv) contains 1,080\nsimulated records in 14 columns: two identifiers and twelve continuous\nindicators. The three samples are combined for distribution only, and no\nobservations have been pooled, rounded, standardized, reassigned or\nregenerated for analysis.\n\n## Fields and common coding {.unnumbered}\n\n\n::: {#tbl-sle-fields .cell layout-align=\"center\" tbl-cap='CSV fields and coding rules. Neither sample nor id is a factor indicator.'}\n::: {.cell-output-display}\n\n\n|Field                 |Meaning                                                                                         |\n|:---------------------|:-----------------------------------------------------------------------------------------------|\n|sample                |A = development; B = confirmation; C = revalidation.                                            |\n|id                    |Unique synthetic record ID; the first letter agrees with sample.                                |\n|P1-P4                 |Proposed Planning domain.                                                                       |\n|S1-S4                 |Proposed Strategy domain.                                                                       |\n|B1-B4                 |Proposed Belonging domain.                                                                      |\n|All twelve indicators |Continuous, unbounded process-index points.                                                     |\n|Direction             |Higher values mean more of the stated attribute; no reverse coding.                             |\n|Missing values        |NA is the missing-value code; the supplied records have no missing observations.                |\n|Response format       |Hypothetical continuous indices, not single ordered-category responses, percentages, or counts. |\n\n\n:::\n:::\n\n\n## Item codebook {.unnumbered}\n\nThe wording gives illustrative content, not evidence that a questionnaire\nwas administered or validated. Proposed domains precede EFA and do not\nguarantee the recovered factor structure.\n\n\n::: {#tbl-sle-codebook .cell layout-align=\"center\" tbl-cap='Complete SLE item definitions and illustrative wording; the common coding rules above apply to every row.'}\n::: {.cell-output-display}\n\n\n|Item |Domain    |Definition                         |Wording                                                     |\n|:----|:---------|:----------------------------------|:-----------------------------------------------------------|\n|P1   |Planning  |Planning-routine consistency       |I establish a study plan before beginning a task.           |\n|P2   |Planning  |Priority-setting clarity           |I identify which study tasks deserve attention first.       |\n|P3   |Planning  |Progress-monitoring regularity     |I compare my progress with the plan I made.                 |\n|P4   |Planning  |Adaptive planning                  |I revise my plan when a study method is not working.        |\n|S1   |Strategy  |Strategy-adjustment flexibility    |I change my learning strategy when understanding is weak.   |\n|S2   |Strategy  |Method-selection deliberateness    |I select a learning method suited to the task.              |\n|S3   |Strategy  |Reflective revision                |I revise my explanation after checking my understanding.    |\n|S4   |Strategy  |Socially supported strategy change |I use discussion with others to improve my learning method. |\n|B1   |Belonging |Peer acceptance                    |I feel accepted by other students.                          |\n|B2   |Belonging |Peer participation                 |I feel able to join other students in learning activities.  |\n|B3   |Belonging |Classroom voice                    |I feel able to express my views in class.                   |\n|B4   |Belonging |Institutional connection           |I feel connected to the university as a whole.              |\n\n\n:::\n:::\n\n\nThe Planning and Strategy indicators are hypothetical continuous process\nindices; Belonging indicators are hypothetical continuous experience\nindices. The following qualifications make overlapping content explicit.\nThey do not disclose an estimated loading or authorize a model change.\n\n\n::: {#tbl-sle-process .cell layout-align=\"center\" tbl-cap='Indicator-specific response-process qualifications.'}\n::: {.cell-output-display}\n\n\n|Item      |Qualification                                        |\n|:---------|:----------------------------------------------------|\n|P4        |Combines planning and method adjustment.             |\n|S4        |Combines learning strategy and social participation. |\n|B1 and B2 |Both refer to a shared peer context.                 |\n|B4        |Broad institutional content rather than one setting. |\n\n\n:::\n:::\n\n\n```{=latex}\n\\Needspace{14\\baselineskip}\n```\n\n## Population parameters {.unnumbered}\n\nThe three samples are drawn from the population in @tbl-sle-population, using\nthe seeds in @tbl-sle-manifest below. Standardized loadings and factor\ncorrelations are given; residual variances are whatever makes each\nstandardized indicator variance one, apart from the single residual covariance\nshown. Indicator means and scale factors convert the standardized system to\nthe recorded units.\n\nThis table documents the *generating population* and the role of each sample.\nIt is not a complete recipe for reproducing the released numbers, which would\nadditionally require the random-number convention, the order in which the\nfactor and residual draws are made, and the factorization used to impose the\ncovariance structure. The exact observations analysed in Chapters 2 to 4 are\nthe ones distributed in `sle_continuous.csv`; the chapter source regenerates\nthem during rendering and checks them against that file.\n\n\n::: {#tbl-sle-population .cell layout-align=\"center\" tbl-cap='The generating population. Loadings are standardized; a blank means the loading is fixed at zero.'}\n::: {.cell-output-display}\n\n\n|Item |Planning |Strategy |Belonging |Intercept |Scale |\n|:----|:--------|:--------|:---------|:---------|:-----|\n|P1   |0.78     |         |          |50        |8     |\n|P2   |0.74     |         |          |52        |10    |\n|P3   |0.70     |         |          |48        |12    |\n|P4   |0.55     |0.32     |          |51        |9     |\n|S1   |         |0.76     |          |49        |10    |\n|S2   |         |0.72     |          |50        |8     |\n|S3   |         |0.68     |          |52        |11    |\n|S4   |         |0.55     |0.30      |48        |9     |\n|B1   |         |         |0.80      |51        |10    |\n|B2   |         |         |0.74      |49        |12    |\n|B3   |         |         |0.67      |50        |8     |\n|B4   |         |         |0.50      |52        |11    |\n\n\n:::\n:::\n\n\nFactor correlations are\n$\\phi_{12}=0.42$,\n$\\phi_{13}=0.30$ and\n$\\phi_{23}=0.35$, with all three factor variances\nfixed at one. One residual covariance is nonzero,\n$\\theta_{\\mathrm{B1,B2}}=0.12$ on the\nstandardized scale, representing shared peer context that the three broad\nfactors do not capture. Every other residual covariance is zero.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n```\n\n## Sample manifest {.unnumbered}\n\n\n::: {#tbl-sle-manifest .cell layout-align=\"center\" tbl-cap='Three independent samples in one file. The first-use rules concern analytical evidence, not physical file accessibility.'}\n::: {.cell-output-display}\n\n\n|Sample          |N   |IDs       |Seed     |Permitted first use                                                       |\n|:---------------|:---|:---------|:--------|:-------------------------------------------------------------------------|\n|A: development  |360 |A001-A360 |20260921 |Chapter 2: EFA development.                                               |\n|B: confirmation |360 |B001-B360 |20260922 |Chapter 3: estimate the candidate frozen after A; Chapter 4: evaluate it. |\n|C: revalidation |360 |C001-C360 |20260923 |Chapter 4: retest the revision frozen after B.                            |\n\n\n:::\n:::\n\n\nEach row belongs to one sample only. The 360-case sample sizes are\npedagogical choices, not general adequacy recommendations. Importing the\ncombined file does not authorize earlier use of B or C. Select the eligible\nsample before descriptive summaries, missing-data decisions, rescaling,\ncorrelations, extraction, estimation, or diagnostics. Keep `sample` and\n`id` out of the indicator matrix.\n\nThe records are simulated from the declared population with the seeds in\n@tbl-sle-manifest. The source generates Sample A internally and, when the\nreleased CSV is present, verifies agreement across all three samples, their\ncase identifiers and all twelve indicators. Readers reproduce the released\nanalysis from `sle_continuous.csv`. The generation specification was declared\nbefore any sample was inspected, and no seed was chosen for its fit results.\n\n# Appendix B: Spectral and rotation details {.unnumbered}\n\n## Why a truncated eigendecomposition is a component solution {.unnumbered}\n\nFor a symmetric positive-semidefinite matrix,\n$\\mathbf R=\\mathbf V\\mathbf D\\mathbf V^{\\mathsf T}$ with orthonormal\neigenvectors. Retaining the first $m$ eigenpairs gives\n$\\mathbf R_m=\\mathbf V_m\\mathbf D_m\\mathbf V_m^{\\mathsf T}$.\nIts trace is the sum of the retained eigenvalues. Among unrestricted\nrank-$m$ approximations, this truncation minimizes squared Frobenius\nerror. The omitted diagonal is not required to be a diagonal residual\ncovariance from a latent-variable measurement model. That is the key\nreason a convenient low-rank approximation and common-factor estimation\nanswer different questions.\n\nReplacing the diagonal by communality estimates changes the eigenproblem.\nThe reduced matrix need not be positive semidefinite: its diagonal is\nno longer the full variance of an observed random vector. In a\nprincipal-axis iteration, the retained positive roots define a current\ncommon part whose diagonal supplies the next communality estimates.\nConvergence of that iteration and its sensitivity to starts are numerical\nquestions separate from whether the resulting factors make sense.\n\n## Other retention summaries are not interchangeable votes {.unnumbered}\n\nThe minimum average partial (MAP) idea progressively removes component\ndirections and examines the remaining partial-correlation structure.\nIt is not the same reference comparison as parallel analysis. Very\nsimple structure (VSS) compares approximations obtained by simplifying\nloading patterns to a small number of entries per row; it consequently\ndepends on the kind of simplicity one is prepared to impose. Sequential\nmodel tests target exact covariance restrictions under their reference\nconditions. Information criteria trade likelihood against parameter\ncount but also require a carefully specified likelihood and admissible\ncandidate family.\n\nThese methods can disagree because they target different features. A\nuseful extension would state each target, its tuning choices, and the\nimplications of disagreement, rather than assemble a majority-vote\nfactor count. Newer eigenvalue corrections likewise require their own\nderivation and calibration; they should not be introduced merely by\nrenaming the eigenvalue-greater-than-one rule.\n\n## Two explicit oblique criteria {.unnumbered}\n\nIgnoring a positive multiplicative constant, the quartimin objective is\n\n$$\nQ_{\\mathrm{quartimin}}(\\mathbf P)\n=\\sum_{j=1}^p\\sum_{a<b}p_{ja}^2p_{jb}^2.\n$$\n\nLarge coefficients in two columns of the same row increase this\nobjective. A geomin objective takes the form\n\n$$\nQ_{\\mathrm{geomin}}(\\mathbf P)\n=\\sum_{j=1}^p\n\\left[\\prod_{a=1}^m(p_{ja}^2+\\delta)\\right]^{1/m},\n\\qquad\\delta>0.\n$$\n\nThe small positive $\\delta$ regularizes behavior near zero. These\ncriteria may have several local optima. Convergence checks, multiple\nstarts, and sensitivity comparisons are therefore part of a complete\nrotation report. Neither objective supplies a probability that a factor\nname is correct, and neither changes the fitted common covariance when\nimplemented as an equivalent rotation.\n\n## Factor-score indeterminacy in one equation {.unnumbered}\n\nIf factors and indicators are jointly normal, a model-based conditional\nmean score in the standardized metric is\n\n$$\nE(\\boldsymbol\\eta\\mid\\mathbf z)\n=\\boldsymbol\\Phi\\mathbf P^{\\mathsf T}\n\\boldsymbol\\Sigma_z^{-1}\\mathbf z.\n$$\n\nThe conditional variance generally remains positive. Thus knowing the\nmodel parameters does not identify each person's latent value without\nerror. Other scoring criteria lead to other point estimates. This\nappendix supplies the conceptual warning; Chapter 4 develops scoring\nand its uncertainty after the CFA model has been evaluated.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}