{
  "hash": "8033ecad0a15860d717fe7b43993f62f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estimates, Uncertainty, and Statistical Tests\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{12\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\usepackage{xcolor}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nThis chapter builds on the ideas Chapter 2 developed: population and\nsample, parameter and statistic, sampling distribution and standard\nerror. We first say precisely what quantity a study seeks and which rule\nestimates it, and name the repetition behind its uncertainty. We then\ncalculate standard errors for a mean and for a difference between two\ngroup means, build confidence intervals and read their confidence level,\nand carry out hypothesis tests, reading p-values and statistical\nsignificance. Each idea appears first with one mean and then with the\ncontinuing two-group comparison. The t tests for one sample, paired\nsamples and two independent samples follow as one family: the\nequal-variance test used for the continuing study, then Welch's test for\ngroups whose spreads may differ. The same test logic then carries over\nto the association between two categorical variables, with the\nchi-square distribution as its reference, and a three-way table is read\nas two-way tables within layers. We close by weighing the size of a\ndifference, the errors a\ndecision rule can make and the choices made after seeing results, so\nthat one qualified conclusion can be written.\n:::\n\nA first-year course wanted to know whether a new practice format helps\nstudents remember what they have learned. Its instructors recruited 120\nconsenting students and randomly assigned 60 to Special Practice and 60\nto Usual Practice. Both formats covered the same content over four\nsessions with equal total study time. Two weeks later, all 120 completed\nthe same assessment, scored from 0 to 40. Special Practice averaged 27.1\npoints and Usual Practice 24.0, a difference of 3.1 points. This study is\ninvented for the chapter.\n\nIs 3.1 points a difference we should trust, and is it large enough\nto matter?\n\nSection 1 names the target and the repetition behind its uncertainty;\nSections 2, 3 and 4 then calculate a standard error, build a confidence\ninterval and carry out a hypothesis test, each meeting its idea first\nwith one mean and then with the practice study. Section 5 gathers the\nt tests into one family, Section 6 carries the same logic to the\nassociation between two categorical variables, and Section 7 returns to\nwhether 3.1 points is large enough to matter.\n\n## From a Sample to an Estimate {#sec-ch03-estimation}\n\n### The study and its estimated difference\n\nThe study asks about the **mean effect of assignment to Special rather\nthan Usual Practice on the delayed assessment among these 120\nparticipants**. Each part matters. Assignment is the intervention being\ncompared; attending every session would be a different comparison. A mean\neffect summarizes the participants and allows individual responses to\ndiffer. The two-week assessment measures a specified outcome at a\nspecified time. An effect on durable learning or among students elsewhere\nwould require additional information.\n\nThe course team also chose a practical benchmark before seeing the\noutcomes. It treated two points as the smallest average difference that\nwould change its recommendation: the marking scheme awards two points\nfor one completed application task, and the new format adds little\npreparation time. The benchmark is course-specific, and Section 7\nreturns to it after uncertainty has been calculated.\n\n| Item | Special Practice | Usual Practice |\n|:--|--:|--:|\n| Assigned students | 60 | 60 |\n| Delayed assessments observed | 60 | 60 |\n| Delayed-assessment mean | 27.1 | 24.0 |\n| Delayed-assessment SD | 6.0 | 6.4 |\n\n: Observed summaries for the invented special-practice study. {#tbl-ch03-observed tbl-colwidths=\"[50,25,25]\"}\n\nThe standard deviations describe differences among students' scores\nwithin each group. @fig-ch03-scores draws the study's own 120 records,\nso that the 3.1-point shift between the means can be set against the\nvariation among students that makes an uncertainty calculation\nnecessary. It shows why the difference needs more than arithmetic.\nThe two groups overlap heavily: 17 of the 60 Usual Practice students\nscored at or above the Special Practice median of 27, and scores within\neach group spread over almost 30 points, with SDs of about six. Against\nthat spread the means differ by 3.1 points. A different assignment\nof the same students would have placed different students in each\ngroup and produced a different difference, so the next sections ask\nhow far such differences would vary. The figure also lets us check the\nrecords directly: no single score stands far from the rest, and the\nthree scores beyond the whiskers lie within two points of the whisker\nends. Measuring that variation begins by naming the target and the\nrule used to estimate it.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Delayed scores of the 120 students by assigned format. Each dot is one student; boxes span the quartiles, whiskers reach the most extreme scores within 1.5 IQR of the box, open circles mark the three scores beyond them, and diamonds mark the group means, 27.1 and 24.0 points. The figure draws the chapter's 120 invented teaching records, whose SDs, 5.9992 and 6.3992, round to the 6.0 and 6.4 of @tbl-ch03-observed; the chapter's calculations use those rounded summaries.](chapter_03_files/figure-html/fig-ch03-scores-1.png){#fig-ch03-scores fig-pos='!ht' fig-alt='Two horizontal boxplots with stacked dots on a score axis from 10 to 40, Special Practice above Usual Practice. Special Practice has quartiles 24, 27 and 31, whiskers from 14 to 40 and one low score of 13 beyond them; Usual Practice has quartiles 20, 24 and 27, whiskers from 11 to 37 and scores of 38 and 39 beyond them. A red bracket marks the 3.1-point gap between the group means, small beside the spread of each group\\'s scores.' width=691.2}\n:::\n:::\n\n\n### Estimand, estimator, estimation, and estimate\n\nChapter 2 distinguished the population and sample, introduced parameter\nand statistic, and explained sampling distributions and standard error.\nWe now use those ideas to distinguish the quantity sought, the\nestimation rule, and the estimate obtained.\n\nAn **estimand** is the precisely specified quantity the question seeks.\nFor this study, it is the mean assignment effect just described. To make\nthe target explicit, let $Y_{i1}$ be student $i$'s delayed score if\nassigned to Special Practice and $Y_{i0}$ the score if assigned to Usual\nPractice. These are the student's two **potential outcomes**. Only the\none corresponding to the actual assignment is observed; Chapter 1 called\nthe unobserved alternative the counterfactual outcome. The target is\n\n$$\n\\Delta\\mu=\\frac{1}{n}\\sum_{i=1}^{n}\\{Y_{i1}-Y_{i0}\\}.\n$$\n\nInside the braces is one student's assignment effect. The sum adds all\neffects, and division by $n=120$ takes their mean. Written this way, $\\Delta\\mu$ is a mean\ndifference over these 120 participants, not a population quantity. The notation allows different students to\nhave different effects. We assume the two formats have a consistent\nmeaning and one student's assignment does not change another student's\noutcome in a relevant way.\n\nAn **estimator** is a rule for using observed data to approximate this\ntarget. Here the rule subtracts the Usual assigned-group mean from the\nSpecial assigned-group mean. **Estimation** is the process of applying\nand checking that rule and characterizing its uncertainty. The\n**estimate** is the numerical value obtained:\n\n$$\n\\widehat{\\Delta\\mu}=\\bar y_1-\\bar y_0=27.1-24.0=3.1\\text{ points}.\n$$\n\nThe bar denotes a group mean, and the hat marks an estimate. The rule\nwould stay the same under another admissible assignment, although the\nobserved outcomes and the two group means could change. Reversing the\nsubtraction gives $-3.1$; it expresses the reverse comparison using the\nsame information.\n\nThe observed difference exactly describes the two realized means. That\ndescription is known. The participant mean assignment effect remains\nunknown because no student reveals both potential outcomes. This is why\nan exact piece of arithmetic can still be an uncertain estimate.\n\n| Object | Working definition | In this study | Common reading error |\n|:--|:--|:--|:--|\n| Estimand | The precisely specified quantity the question seeks | Mean delayed-score difference caused by Special rather than Usual assignment among the 120 randomized participants | Naming only \"the treatment effect\" |\n| Estimator | The rule that would be applied in each admissible repetition | Special-group mean minus Usual-group mean | Treating the rule as the observed result |\n| Estimation | Applying and checking the estimator for the specified estimand and characterizing the estimate and its uncertainty | Apply the mean-difference rule, verify its inputs and conditions, and quantify uncertainty | Treating estimation as another number |\n| Estimate | The number the estimator produced in this study | $27.1-24.0=3.1$ points | Reporting a number without units or direction |\n| Parameter | The fixed feature named by the estimand under the chosen population or process interpretation | The participant-specific mean assignment contrast | Assuming it is the sample estimate or a universal truth |\n| Statistic | A numerical function of observed data | A group mean, the 3.1-point estimate, or the 2.7372 test statistic | Assuming every statistic estimates the same thing |\n| Standard error | The modeled spread of an estimator across the declared repetitions | 1.1325 points for the mean-difference estimator | Calling it variation among students |\n\n: Inferential objects in the special-practice study. {#tbl-ch03-inferential-objects tbl-colwidths=\"[13,29,33,25]\"}\n\nA parameter is fixed within the specified population or process\ninterpretation, but fixed does not mean universal: changing the\nparticipant set, outcome, time, or condition comparison may change the\nestimand and its parameter.\n\n### Name the repetition and working model\n\nUncertainty needs a description of what could have varied. In a sampling\nquestion, different people might have been selected from a population.\nIn the special-practice study, the primary target concerns these same\n120 participants. The relevant repetition assigns exactly 60 of them to\neach format again. Their potential outcomes remain fixed; the assigned\ngroups and observed outcomes can change.\n\nRandom assignment makes the difference of assigned-group means useful\nfor estimating the participant effect. It does not turn these consenting\nstudents into a representative sample of all first-year students.\nInference about a wider population would need a stated model or sampling\njustification and an explicit extension of the target.\n\nThe numerical analysis uses a familiar working model: two independent\ngroups whose scores share one population spread. Under that model the\ntwo observed variances estimate the same quantity, so Section 2 combines\nthem into one pooled estimate, and the interval and test use a t\nreference with $60+60-2=118$ degrees of freedom. The observed SDs, 6.0\nand 6.4 points, are similar, and the two formats differ only in the\npractice activity, so a common spread is a reasonable starting\nassumption. Section 5 shows what changes when the groups' spreads or\nsizes differ.\n\nThe model's formulas come from independent sampling, but complete\nassignment of 60 of the 120 students does not make the two\nassigned-group means independent. The model therefore serves as an\napproximate calibration for this design rather than an exact\nrandomization distribution. Section 2 explains what the familiar\nformula estimates here, and [Appendix A](#app-ch03-assignment) gives the\ndesign-based variance identity and the distinction between an\naverage-effect null and a sharp null.\n\n### Expectation, bias, and precision\n\nImagine applying the estimator over all repetitions allowed by the\ndesign or model. Its expectation, in Chapter 2's sense, is the probability-weighted\naverage of the values it would produce across those repetitions. If an estimator averages 3.4 points when\nthe target is 3.0, its bias is $3.4-3.0=0.4$ points. This describes the\nrule's systematic displacement, not the error of one particular result.\n\nUnder complete random assignment and the stated potential-outcome\nconditions, each assigned-group mean is centered on the corresponding\nparticipant mean potential outcome. Their difference is therefore\nunbiased for the participant mean assignment effect:\n\n$$\n\\operatorname{Bias}(\\bar Y_1-\\bar Y_0)\n=E_{\\mathrm{assign}}(\\bar Y_1-\\bar Y_0)-\\Delta\\mu=0.\n$$\n\nThe equality does not say that this estimate, 3.1, equals the unknown\neffect. **Precision** concerns how tightly the estimator's values cluster\nacross assignments:\n\n$$\nSE(\\bar Y_1-\\bar Y_0)=SD(\\bar Y_1-\\bar Y_0\\text{ across possible assignments}).\n$$\n\nAn unbiased rule can be imprecise; a tightly concentrated rule can be\nbiased. A third useful consideration is how its behavior changes under\nunusual observations or departures from its conditions. A small SE under\nan unsuitable model can give unwarranted confidence.\n\n[]{#app-ch03-mse}\n\nAccuracy combines both qualities. The mean squared error, the average\nsquared distance of an estimator from its estimand over the\nrepetitions, adds the variance and the squared bias,\n$\\operatorname{MSE}(\\widehat\\theta)=\\operatorname{Var}(\\widehat\\theta)+\\operatorname{Bias}(\\widehat\\theta)^2$.\nAn unbiased estimator with SD 2 has MSE $2^2=4.00$, while one with SD\n1 and bias 1.5 has MSE $1+1.5^2=3.25$: under this criterion the\nbiased but more precise rule lands closer on average, a verdict that\ndepends on the criterion chosen.\n\n## Standard Errors {#sec-ch03-se}\n\n### From the visible sampling pattern to the SE of a mean\n\nChapter 2, Sections 4.2--4.4, drew the pattern this section explains.\nIts waiting-time model had mean and SD both equal to 10 minutes, and its\nsampling-means figure set the individual waits beside 5,000 sample\nmeans at each of three sample sizes, 5, 30 and 100. The individual\nwaits kept their 10-minute spread at every size, while the sample means\nvaried less when each sample contained more observations. Increasing\nthe number of simulated repetitions made their distribution easier to\nsee; increasing the size of each sample changed its spread.\n\nWe can now explain that spread algebraically. Suppose $Y_1,\\ldots,Y_n$\nare independent observations from the same distribution, with finite\nvariance $\\sigma^2$. The sum has variance $n\\sigma^2$, because\nindependent variances add. The mean divides that sum by $n$; multiplying\na variable by $1/n$ multiplies its variance by $1/n^2$. Thus\n\n$$\n\\operatorname{Var}(\\bar Y)=\\frac{n\\sigma^2}{n^2}=\\frac{\\sigma^2}{n},\n\\qquad SE(\\bar Y)=\\frac{\\sigma}{\\sqrt n},\n\\qquad \\widehat{SE}(\\bar Y)=\\frac{s}{\\sqrt n}.\n$$\n\nThe last expression estimates the unknown population SD with the sample\nSD. The estimated SE is calculated from one sample; the SE it estimates\ndescribes the mean across repetitions. Both are standard deviations,\nbut of different distributions from the individual waiting times.\n\nApplied to the waiting-time model, $\\sigma/\\sqrt n$ gives the model\nSEs of Chapter 2's sampling table, which the simulated sample means\napproximate, and its square root explains why halving an SE takes four\ntimes as many independent observations: at $n=120$ the model SE is\n0.9129 minutes, half its value at $n=30$.\n\nThe estimated SE uses the sample SD $s$, whose squared deviations from\nthe sample mean are divided by $n-1$. Chapter 2 noted that the sample\nmean is the value that makes the sum of squared deviations smallest;\nthe deviations from it sum to zero, so once $n-1$ of them are known the\nlast is fixed. [Appendix A](#app-ch03-variance) derives both facts and\nshows why the divisor $n-1$ makes $s^2$ unbiased for $\\sigma^2$.\n\n### Uncertainty for a difference in means {#sec-ch03-pooled}\n\nFor two independent samples, uncertainty comes from both means. Their\nvariances add when one mean is subtracted from the other:\n\n$$\n\\operatorname{Var}(\\bar Y_1-\\bar Y_0)\n=\\frac{\\sigma_1^2}{n_1}+\\frac{\\sigma_0^2}{n_0}.\n$$\n\nThe minus sign changes the direction of a difference, not the sign of a\nvariance contribution. Independence removes the covariance term; the\nnext subsection shows what happens when that condition fails.\n\nSection 1.3 stated the working model for the practice study: two\nindependent groups whose scores share one population spread. If both\npopulations have the same variance $\\sigma^2$, the two contributions\nshare that factor:\n\n$$\n\\sigma_1^2=\\sigma_0^2=\\sigma^2:\\quad\n\\operatorname{Var}(\\bar Y_1-\\bar Y_0)\n=\\sigma^2\\left(\\frac{1}{n_1}+\\frac{1}{n_0}\\right).\n$$\n\nEach group's sample variance then estimates the same $\\sigma^2$. The\n**pooled variance** $s_p^2$ combines them, weighting each by its degrees\nof freedom, $n-1$; its square root $s_p$ is the pooled SD:\n\n$$\ns_p^2=\\frac{(n_1-1)s_1^2+(n_0-1)s_0^2}{n_1+n_0-2},\n\\qquad\n\\widehat{SE}(\\bar y_1-\\bar y_0)=s_p\\sqrt{\\frac{1}{n_1}+\\frac{1}{n_0}}.\n$$\n\nA larger group estimates the common spread from more observations, so\nits variance receives more weight. The denominator $n_1+n_0-2$ counts\nthe degrees of freedom that remain after estimating the two group means.\nFor the practice study the pooled estimate therefore uses $60+60-2=118$\ndf, which is why the interval in Section 3 and the test in Section 4 use\na t reference with 118 df. Substitution gives\n\n$$\n\\begin{aligned}\ns_p^2&=\\frac{59(6.0^2)+59(6.4^2)}{118}=38.48,\n\\qquad s_p=6.2032\\text{ points},\\\\\n\\widehat{SE}(\\bar y_1-\\bar y_0)&=6.2032\\sqrt{\\frac{1}{60}+\\frac{1}{60}}\n=1.1325\\text{ points}.\n\\end{aligned}\n$$\n\nWith 60 students in each group the pooled variance is simply the\naverage of the two variances, in squared points, and the pooled SD lies\nbetween the two group SDs. The pooled SE is then algebraically the same\nas the square root of the two estimated mean variances added,\n$\\sqrt{s_1^2/n_1+s_0^2/n_0}$, so both routes give 1.1325 points. With\nunequal group sizes the two forms generally differ, and Section 5.4\nreturns to that case. Equal group sizes make the two SEs coincide; they\ndo not by themselves establish equal population variances.\n\nFor the fixed 120 participants, the SE describes how the estimate would\nvary across the possible assignments of 60 students to each format.\nRe-assigning these records under the null of no effect, as Section 4.4\ndescribes and the R support page runs, gives differences whose spread,\n1.1671 points, is close to this 1.1325. The exact\nassignment variance subtracts a term for the variability of individual\neffects, which no record reveals, so the familiar estimated\nvariance, and with equal group sizes the pooled squared SE, estimates\nan upper bound on that variance on average.\n[Appendix A](#app-ch03-assignment) gives the identity [@bai2024]. The\nworking t reference also needs adequate information in each group and\nno dominating observations; random assignment alone does not make it\nexact.\n\n### Pairing, clustering, and sampling without replacement\n\nThe independence calculation fails in several common designs, and each\nfailure is a covariance story. For any two quantities with finite\nvariances,\n\n$$\n\\operatorname{Var}(U-V)=\\operatorname{Var}(U)+\\operatorname{Var}(V)\n-2\\operatorname{Cov}(U,V).\n$$\n\nIf paired measurements tend to be high or low together, subtracting\nwithin a pair removes some shared variation. In a separate illustration,\nsuppose both measurements have SD 4, their covariance is 12, and there\nare 25 independent pairs. Let $d$ be the within-pair difference. Then\n\n$$\n\\begin{aligned}\n\\operatorname{Var}(d)&=4^2+4^2-2(12)=8,\\\\\n\\widehat{SE}(\\bar d)&=\\sqrt{\\frac{8}{25}}=0.5657,\\\\\n\\text{ignoring the pairing: }&\\sqrt{\\frac{16+16}{25}}=1.1314.\n\\end{aligned}\n$$\n\nThe reduction comes from the positive covariance, not from a change in\nthe number of observations. Actual paired-data analysis computes each\ndifference and uses the SD of those differences. Negative covariance\nwould change the result in the opposite direction.\n\n[]{#app-ch03-dependence}\n\nSampling without replacement from a fixed list also changes the\nvariance, even when selection is random. For a simple random sample of\n$n$ units from $N$ fixed values whose variance $\\sigma^2$ uses the\ndivisor $N$,\n\n$$\nSE(\\bar Y)=\\frac{\\sigma}{\\sqrt n}\\sqrt{\\frac{N-n}{N-1}}.\n$$\n\nThe **finite-population correction** $\\sqrt{(N-n)/(N-1)}$ shrinks the\nSE as the sample covers more of the list, reaching zero at a census. In\nChapter 2's invented system of $N=20{,}000$ students with\n$\\sigma=4.4259$ grade points, a simple random sample of 100 has SE\n0.4426 grade points under independent sampling and 0.4415 with the\ncorrection factor .9975; with 400 students the factor is .9900. Other\nselection schemes need their own design-based calculation.\n\nClustering works in the opposite direction. Chapter 2, Section 4.4,\nshowed that a sample of 4 schools with 25 students each spreads its\nmeans about twice as widely as a simple random sample of 100 students,\nand introduced the design effect,\n\n$$\n\\mathrm{deff}=1+(m-1)\\,\\mathrm{ICC},\n$$\n\nfor a mean from equal clusters of $m$ units. The covariance terms\nexplain it: each student has $m-1$ school-mates whose scores covary\nwith theirs by $\\mathrm{ICC}\\times\\sigma^2$, and those terms multiply\nthe independent-sampling variance of the mean by $\\mathrm{deff}$. With\n$m=25$ and Chapter 2's intraclass correlation .1304, the design effect\nis 4.1299. The SE of the multistage mean, the simple-random-sample SE\nmultiplied by the square root of the design effect, is then about\n0.8972 grade points, close to the 0.8730 that Chapter 2's simulation\nshowed. The 100 students came from only four sampled schools; the SE\nfollows the design, not the count of students.\n\n[]{#sec-ch03-school-pairs}\n\nAn invented school-blocked extension of Chapter 1's feedback study\nshows pairing and clustering together. Each of twelve participating\nschools contributed two classes of 20 students, and within every school\none class was randomly assigned to explanatory feedback and the other\nto usual feedback; all 480 students took the same delayed 0--40\nassessment. The class is the unit of assignment, and each school\nsupplies one explanatory-minus-usual difference of its two class means.\n@fig-ch03-school-pairs shows the twelve differences, $-2$, 0, 1, 1, 2,\n2, 3, 3, 4, 4, 5 and 7 points, with mean 2.5 and SD 2.3932. Their\nuncertainty comes from these twelve independent within-school\ncomparisons: $\\widehat{SE}(\\bar d)=2.3932/\\sqrt{12}=0.6908$ points.\nDividing the same SD by $\\sqrt{480}$, as if the 480 students rather\nthan the twelve school comparisons were the independent units, would\ngive 0.1092 points, an SE $\\sqrt{40}=6.3246$ times too small. That\ncalculation mixes levels: the SD describes class-mean differences,\nwhereas 480 counts students, who were assigned in whole classes.\nSection 5.2 completes the paired analysis of the twelve differences.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Twelve school differences in class means under within-school assignment (invented data). Each dot is one school's explanatory-minus-usual difference; the vertical line marks their mean, 2.5 points. The upper bar spans one SE either side of the mean from the twelve school comparisons, 0.6908 points; the lower bar spans the 0.1092 that wrongly counting the 480 students as the independent units would give.](chapter_03_files/figure-html/fig-ch03-school-pairs-1.png){#fig-ch03-school-pairs fig-pos='!ht' fig-alt='A dot plot of twelve differences from minus 2 to 7 points, stacked where values repeat, with a vertical line at 2.5 and a dashed line at zero. Below the dots a blue bar from about 1.8 to 3.2 marks one SE either side of the mean from the twelve school comparisons, and a much shorter red bar from about 2.4 to 2.6 marks the SE that wrongly treating the 480 students as the independent units would give.' width=691.2}\n:::\n:::\n\n\nThis is a **blocked assignment**: each school forms a block, and the\ntwo conditions are allocated within every block, so each comparison is\nmade inside a school and school-level variation drops out of it.\n**Stratified sampling** instead selects units within population\nstrata; it decides who enters a sample, whereas blocking allocates\nconditions after entry, and grouping records by school does not make\neither mechanism imply the other.\n\n### Concentration, shape, and the conditions behind them\n\n[]{#app-ch03-limits}\n\nChapter 2's sampling-means figure shows two different things happening\nas the sample size grows. The **law of large numbers** describes\nconcentration: for independent, identically distributed observations\nwith a finite mean, the chance that $\\bar Y_n$ lies farther than any\nfixed distance from $\\mu$ shrinks toward zero. The **central limit\ntheorem** describes shape: with finite variance $\\sigma^2$, the\nstandardized mean approaches a standard Normal distribution,\n\n$$\n\\frac{\\bar Y_n-\\mu}{\\sigma/\\sqrt n}\\ \\text{approaches}\\ N(0,1)\n\\quad\\text{as } n \\text{ grows}.\n$$\n\nThe individual waiting times in the figure's first panel stay skewed\nat every sample size; only the means concentrate and become nearly\nNormal. Both results concern increasing sample size, not repeatedly\nsimulating the same small sample, and both need conditions: strong\ndependence, extreme tails, or an observation that dominates the mean\ncan make a Normal approximation poor, and no universal sample-size\ncutoff settles the issue for every distribution and design. The SE\nformula answers how wide a sampling distribution is; its approximate\nshape then helps choose an interval or test.\n\n## Confidence Intervals and Confidence Level {#sec-ch03-intervals}\n\n### Estimate, SE, critical value, and interval\n\nA confidence interval combines an estimate with a multiple of its SE.\nFor the symmetric procedures used here,\n\n$$\n\\text{estimate}\\pm\\text{critical value}\\times\\text{standard error}.\n$$\n\nThe SE supplies a scale. A **critical value** says how far to extend in\nSE units to obtain the intended coverage under a reference distribution.\nChapter 2 introduced the standard Normal distribution, centered at zero\nwith SD one. Its .975 quantile is about 1.96: .025 of the probability\nlies beyond that point, and another .025 lies below $-1.96$.\n\nThe Normal critical value suits a mean whose population SD is known\nindependently of the sample. Usually the SD must be estimated from the\nsame observations, and that estimate is itself uncertain. A **t\ndistribution** accounts for this extra uncertainty. It is symmetric\naround zero, like the standard Normal, but has heavier tails. Its\n**degrees of freedom** (df) index how much information the estimated SD\ncarries; for one mean they equal $n-1$, the divisor of the sample\nvariance ([Appendix A](#app-ch03-variance)).\nWith few df the tails are heavy and the critical value is larger; as df\nincrease, the t reference approaches the standard Normal. An estimated\nspread does not make every statistic exactly t-distributed: the exact\none-mean result requires independent Normal sampling, and the two-group\nreference for the practice study is an approximate working calibration\n(Section 1.3).\n\nFor a separate, invented illustration, suppose a simple random sample\nof 25 students from a large district completes a reading scale whose\npublished reference mean is 50 points. The sample mean is $\\bar x=52$\npoints and the SD is $s=5$ points. The estimand is the district's\npopulation mean score, $\\mu$. Treating the scores as independent\nobservations from an approximately Normal population, Section 2.1\ngives $\\widehat{SE}(\\bar X)=5/\\sqrt{25}=1$ point. Because the SD\nis estimated from the same 25 scores, the reference is a t\ndistribution with $25-1=24$ degrees of freedom. Its .975 quantile,\n2.064 in a t table, leaves .025 in each tail:\n\n$$\n52\\pm2.064(1)=52\\pm2.064=[49.936,\\ 54.064]\\text{ points}.\n$$\n\nThe interval estimates the district mean in points under the sampling\nmodel. Its estimand and repetition differ from the participant\nassignment effect of the practice study.\n\nThe 95% reference values below leave .025 in each tail. The table gives\nfull-precision quantiles, so the t-table value 2.064 appears as 2.0639,\nand its third row previews the Special Practice reference of Section\n3.4.\n\n| Reference | 95% critical value | Role in the examples |\n|:--|--:|:--|\n| Standard Normal | 1.9600 | Mean with a population SD known independently of the sample, under a suitable Normal model |\n| t with 24 df | 2.0639 | The one-mean illustration: SD estimated from 25 independent Normal observations |\n| t with 118 df | 1.9803 | The Special Practice comparison under the equal-variance working model (Section 3.4) |\n\n: Reference choice and critical values. {#tbl-ch03-critical-values tbl-colwidths=\"[25,20,55]\"}\n\nThe t curves in @fig-ch03-z-t spread more probability into their tails\nthan the standard Normal, most visibly with few degrees of freedom,\nwhich is why their critical values are larger.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Normal and t references at the same location and scale of the test statistic. The heavier t tails are most visible with few degrees of freedom.](chapter_03_files/figure-html/fig-ch03-z-t-1.png){#fig-ch03-z-t fig-pos='!ht' fig-alt='Overlaid standard Normal and t curves with 9 and 99 degrees of freedom. Vertical lines mark minus and plus 2; the t curve with 9 degrees of freedom has the largest probability beyond them.' width=652.8}\n:::\n:::\n\n\nThe procedure and its conditions determine the reference. Choosing the\nsmaller critical value merely to narrow an interval would change the\nprocedure without justification.\n\n### Confidence level and coverage\n\nThe **confidence level** names the procedure's target coverage: a 95%\nprocedure aims to cover the fixed estimand in 95% of its repeated\napplications under its conditions. The level enters the calculation\nthrough the critical value. For the district sample, a 90% interval\nuses the t quantile that leaves .05 in each tail, 1.711 in a t table,\ninstead of 2.064.\n\nPredict the change before calculating. The estimate and its SE stay the\nsame and only the multiplier becomes smaller, so the 90% interval must\nbe narrower, as @tbl-ch03-confidence-levels in Section 3.4 confirms.\nThe 95% interval contains the published reference value 50, whereas the\n90% interval, [50.289, 53.711], excludes it; Section 4.3 uses this\npair to connect intervals with tests.\n\nWhat does the target coverage describe? @fig-interval-coverage\nsimulates 40 district samples under a stipulated population mean of 52\npoints and a known SE of 1, and gives each estimate an interval of\n$\\pm1.9600$ SEs at 95% and $\\pm1.6449$ SEs at 90%.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same 40 simulated district samples under two confidence levels. The population mean, 52 points, is fixed for display, and each sample's estimate carries its interval with it. At 95%, 38 of the 40 intervals cover the mean; at 90%, with the smaller multiplier 1.6449 in place of 1.9600, 36 do.](chapter_03_files/figure-html/fig-interval-coverage-1.png){#fig-interval-coverage fig-pos='!ht' fig-alt='Two panels of 40 horizontal intervals around a vertical line at 52 points, with the same estimates in both panels. In the 95 percent panel, studies 11 and 22 miss the line and are drawn in red; in the shorter 90 percent intervals, studies 2, 11, 14 and 22 miss.' width=691.2}\n:::\n:::\n\n\nAcross repetitions the samples, estimates and endpoints vary while the\ntarget stays fixed. A miss involves no calculation error: an estimate\nthat happens to fall far from the population mean carries its interval\nwith it, so even a valid 95% procedure misses occasionally. The two\npanels of @fig-interval-coverage use the same 40 estimates, and only\nthe multiplier changes. Studies 2 and 14, whose estimates fell between\n1.6449 and 1.9600 SEs from 52, are covered at 95% but missed at 90%: a\nlower level buys a narrower interval at the price of more misses. A\nbatch of 40 need not show exactly 38 or 36 successes; the target\ncoverage describes the procedure over many repetitions. Because the\ndisplay uses a simplified Normal model with known SE, its coverage is a\nproperty of the illustration, and fixing the mean at 52 is a display\nchoice rather than a claim about the unknown district mean.\n\nOnce an interval has been calculated, the coverage statement describes\nthe success rate of the *interval-producing procedure*; it does not\nassign a 95% probability to the fixed estimand, and it does not say that\n95% of the district's students score between 49.936 and 54.064. Read\nthe endpoints in points as values compatible with the observations under\nthe procedure: the 95% interval allows district means slightly below\nthe reference value 50 as well as means near 54 points, with no natural\ncliff at its rounded endpoints.\n\n### What a narrower interval can and cannot resolve\n\nHolding the model and data fixed, a higher confidence level needs a\nwider interval. More outcome variability generally widens it, while\nmore relevant information narrows it, and changes in the design or\nvariance estimator can also change its width. The 90% interval of\nSection 3.2 is narrower because it asks for less coverage, not because\nthe sample holds more information: changing the level adds no\nobservations and changes neither the estimate nor its SE. An interval\nalso quantifies only the uncertainty its procedure represents. A narrow\ninterval can coexist with systematic selection, poor measurement,\nunmodeled dependence, unavailable outcomes, or an unsupported\ngeneralization. Measuring the wrong outcome very consistently can yield\na small SE for the wrong target, and adding many pupils from a few\njointly assigned classes does not reproduce the information from the same number of individually assigned pupils. Precision helps only when the\nprocedure remains aligned with the question and design.\n\n### The Special Practice interval\n\nThe same construction applies to the continuing study. Its estimate is\n3.1 points, Section 2.2 gave the pooled SE 1.1325 points, and the\nequal-variance t reference has 118 df, whose 95% critical value is\n1.9803. Under the equal-variance working model, whose calibration is\napproximate for the assignment design (Section 1.3), the interval is\n\n$$\n(\\bar y_1-\\bar y_0)\\pm t_{.975,\\,118}\\,\\widehat{SE}(\\bar y_1-\\bar y_0)\n\\approx3.1\\pm1.9803(1.1325)\n\\approx[0.8572,\\ 5.3428]\\text{ points}.\n$$\n\nThe endpoints retain the Special-minus-Usual direction and\nassessment-point units. They allow positive effects near one point and\neffects above five points. The data therefore give a useful estimate\nwithout pinpointing its magnitude.\n\nChanging only the confidence level gives the intervals below; in each\nexample the estimate, the SE and the observations stay the same.\n\n| Example and confidence level | Critical value | Margin | Interval in points | Full width |\n|:--|--:|--:|:--|--:|\n| District mean, 90% | 1.711 | 1.7110 | [50.2890, 53.7110] | 3.4220 |\n| District mean, 95% | 2.064 | 2.0640 | [49.9360, 54.0640] | 4.1280 |\n| Special Practice difference, 90% | 1.6579 | 1.8776 | [1.2224, 4.9776] | 3.7552 |\n| Special Practice difference, 95% | 1.9803 | 2.2428 | [0.8572, 5.3428] | 4.4855 |\n\n: Changing only the confidence level: the estimate and SE stay fixed, and the critical value alone moves each interval. {#tbl-ch03-confidence-levels tbl-colwidths=\"[40,13,11,22,14]\"}\n\nThe district critical values are the supplied t-table values; the\nSpecial Practice values are full-precision quantiles of t with 118 df.\nIn both examples the smaller critical value narrows the 90% interval\nwithout adding observations or reducing the SE; the narrower interval\nhas a lower coverage target. Both Special Practice intervals lie above\nzero and span the two-point benchmark: they can support a positive mean\nassignment effect under the procedure while leaving its practical\nimportance to Section 7.\n\n## Hypothesis Tests, p-Values and Significance {#sec-ch03-tests}\n\n### Hypotheses, test statistics, and reference distributions\n\nA statistical hypothesis makes a proposition about a target. Return to\nthe district sample. A natural question asks whether the district's\nmean differs from the published reference value. A **null hypothesis**\nstates the reference proposition, $H_0:\\mu=50$; the two-sided\n**alternative hypothesis** $H_A:\\mu\\ne50$ allows a difference in either\ndirection. A **test statistic** measures the estimate's departure from\nthe null value in SE units:\n\n$$\nt=\\frac{\\bar x-\\mu_0}{s/\\sqrt n}=\\frac{52-50}{5/\\sqrt{25}}=\\frac{2}{1}=2,\n\\qquad df=24.\n$$\n\nThe sample mean lies two estimated SEs above 50. If the null and the\nsampling model hold, the statistic follows a t distribution with 24\ndegrees of freedom, its **reference distribution**.\n\nMany test statistics share this common form:\n\n$$\n\\text{test statistic}=\n\\frac{\\text{estimate}-\\text{null value}}\n{\\text{standard error under the test procedure}}.\n$$\n\nThe numerator measures departure in outcome units. The denominator\nexpresses how large that departure is relative to the procedure's\nuncertainty. The reference distribution then shows which values of the\nstatistic would be common, and which unusual, if the null and the\nprocedure's conditions held. Equivalently, subtracting 50 from every\nscore creates a centered variable whose null mean is zero; the question\nstays the same. A **test** is the procedure for assessing the null\nproposition, while a test result is the numerical output obtained from\nthe data.\n\n### Tail areas, p-values, and statistical significance\n\nThe p-value comes from a tail area of the reference distribution: the\narea beyond the observed statistic, in the direction or directions the\nalternative names. The district alternative counts departures in both\ndirections, so the two tails beyond $\\pm2$ are added:\n\n$$\np=P(T_{24}\\le-2)+P(T_{24}\\ge2)=2P(T_{24}\\ge2)=.0569,\n\\qquad\nP(T_{24}\\ge2)=.0285.\n$$\n\nThe symbol $T_{24}$ denotes a variable with the reference t distribution\non 24 df. Software or a reference table supplies the area; each tail\nholds .0285.\n\nA **p-value** is a conditional tail probability. If the null and the\nprocedure's conditions hold, a result at least as far from the null\nvalue as the one observed would occur with probability .0569 here. A\n**significance level**, $\\alpha$, is a threshold chosen before the\nresult is inspected; a level-.05 rule rejects the null when the p-value\nis below .05. Because .0569 is not below .05, the district result is\nnot **statistically significant** at the .05 level. The test does not\nreject 50, and that decision does not show the mean equals 50.\n\nThe label *statistically significant* records a comparison with the\nthreshold. The p-value calculation starts by assuming the null for its\nreference; it does not calculate the probability that the null itself\nis true [@wasserstein2016]. Other values, including means near 54, remain\ncompatible with the district data. The size of a difference, its\nimportance, and the probability that a claim is true are different\nquestions.\n\nThe district test is two-sided because either direction counts. A\none-sided test needs an alternative whose direction was chosen before\nthe result was inspected. Had the study specified $H_A:\\mu>50$ in\nadvance, its p-value would be the single upper tail, .0285. Choosing\nthat tail after seeing a positive estimate, so that .0285 falls below\n.05, changes the testing procedure and its error calibration. A large\ndeparture in the opposite direction does not support a one-sided\nalternative either.\n\n### A test and an interval built from one procedure\n\nA two-sided test at level $\\alpha$ and a $100(1-\\alpha)\\%$ interval\nbuilt from the same procedure agree about any null value. The district\nsample shows the agreement at two levels. With the null value 50, the\nstatistic is the 2 of Section 4.1. Against the supplied two-sided\n95% critical value\n2.064 the statistic falls short, and the interval [49.936, 54.064]\ncontains 50: the level-.05 test does not reject. Against the 90%\ncritical value 1.711 the statistic exceeds the cutoff, and the interval\n[50.289, 53.711] excludes 50: a level-.1 test chosen in advance would\nreject. In both cases the interval contains exactly the null values the\nmatching two-sided test would not reject.\n\nAlgebra explains the agreement. A null value $\\theta_0$ lies outside the\ninterval $\\widehat\\theta\\pm t^*\\widehat{SE}$ exactly when its distance\nfrom the estimate exceeds the margin, $|\\widehat\\theta-\\theta_0|>\nt^*\\widehat{SE}$. Dividing both sides by the SE gives the test's\ncomparison of its statistic with the critical value:\n\n$$\n\\text{the null value }\\theta_0\\text{ lies outside }\\widehat\\theta\\pm t^*\\widehat{SE}\n\\quad\\Longleftrightarrow\\quad\n\\frac{|\\widehat\\theta-\\theta_0|}{\\widehat{SE}}>t^*.\n$$\n\nThe interval is therefore the set of null values the test would not\nreject. The agreement requires the same estimator, SE, reference\ndistribution, sidedness, and comparison, and two calculations aligned in\nthis way can still share an inadequate model. Nor does the correspondence at each level license choosing\nthe level after seeing where 50 falls: the 90% rejection counts only if\nthat level was chosen before the data were examined.\n\n### The Special Practice test\n\nReturn to the continuing study. For two populations, the null\n$H_0:\\Delta\\mu=0$ concerns $\\Delta\\mu=\\mu_1-\\mu_0$, the difference\nbetween their means; the subscripts 1 and 0 identify the two groups,\nhere Special and Usual, in that order, so $\\mu_0$ now names a group\nmean rather than the one-mean null value of Section 4.1. For Special\nPractice, $\\Delta\\mu$ remains the fixed participants' mean assignment\neffect defined in Section 1.2, and its null preserves that target:\n\n$$\nH_0:\\Delta\\mu=0\\qquad\\text{versus}\\qquad H_A:\\Delta\\mu\\ne0.\n$$\n\nThe null says the participant mean assignment effect is zero; the\nalternative allows either a positive or a negative effect. Under the\nequal-variance working model, the statistic divides the estimate by the\npooled SE of Section 2.2 and uses the t reference with 118 df:\n\n$$\nt=\\frac{\\widehat{\\Delta\\mu}-0}{\\widehat{SE}(\\bar y_1-\\bar y_0)}\n\\approx2.7372,\\qquad df=118,\\qquad\np=2P(T_{118}\\ge|t_{\\mathrm{obs}}|)\\approx.0072.\n$$\n\nThe estimate is about 2.7372 estimated SEs above zero. Its upper-tail\nprobability is .0036, and the two-sided test adds the equally extreme\nnegative tail, giving .0072. The null and the procedure's conditions\ndefine the reference; the observed statistic selects the tail area. At\n$\\alpha=.05$ the result is statistically significant, and the 95%\ninterval of Section 3.4, [0.8572, 5.3428], excludes zero, as Section\n4.3 predicts.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The Special Practice test read two ways; panel (a) is adapted from @biau2010. (a) The t reference with 118 df on the scale of the test statistic: the dashed lines mark the two-sided .05 critical values $\\pm1.9803$, beyond which the light regions hold .025 each, and the red marks show the observed statistic 2.7372 and its mirror image $-2.7372$, which lie beyond them. (b) The upper tail, enlarged on its own vertical scale: the dark area beyond 2.7372 holds .0036, and with the matching lower tail it gives the two-sided p-value .0072. (c) The 95% and 90% intervals from the same equal-variance procedure, read against zero and the two-point benchmark.](chapter_03_files/figure-html/fig-test-interval-1.png){#fig-test-interval fig-pos='!ht' fig-alt='Three panels. The first shows a bell-shaped t density with 118 degrees of freedom on a test-statistic axis from about minus 5 to 5; dashed grey lines at minus and plus 1.9803, labelled at the top, mark the .05 critical values, the regions beyond them are shaded light red, and red marks labelled minus and plus 2.7372 stand farther out, where the tails are too thin to see. The second enlarges the upper tail from 1.6 to 4.6 on a density axis up to 0.12: the light region beyond the critical value is labelled critical 1.9803, .025 beyond, and the dark red region beyond the observed statistic is labelled observed 2.7372, .0036 beyond. The third shows the estimate 3.1 with a 95 percent interval from 0.8572 to 5.3428 and a 90 percent interval from 1.2224 to 4.9776, beside a dashed line at zero, labelled no difference, and a dotted line at the two-point benchmark; both intervals exclude zero and cross the benchmark.' width=691.2}\n:::\n:::\n\n\nPanel (a) of @fig-test-interval draws the reference the test uses, as\nSection 4.2 did in words for the district mean. The dashed lines at\n$\\pm1.9803$ mark the two-sided .05 critical values, the same multiplier\nthat built the 95% interval in Section 3.4, and the light regions\nbeyond them hold .025 each. The observed statistic lies beyond them, so\nthe level-.05 test rejects. The tails beyond $\\pm2.7372$ are too thin\nto see at this scale, so panel (b) enlarges the upper tail: the dark\narea beyond the observed statistic holds .0036, the matching lower tail\nholds the same, and together they give the two-sided p-value .0072.\nPanel (c) reads the same result as intervals: the 95% and the 90%\ninterval both exclude zero, and both span the two-point benchmark.\n\nThe same p-value can be checked against the design itself. If no\nstudent's score depended on format, re-assigning the 120 records at\nrandom to two groups of 60 would reproduce the design's repetition\nunder that null, and in 10,000 such re-assignments a share of .0077\ngave a difference at least 3.1 points from zero, close to the t test's\n.0072; the chapter's R support page runs them. The two need not agree\nexactly, because the re-assignments test the stronger null that no\nstudent's score depends on format, using the actual records, whereas\nthe t test models the average effect\n([Appendix A](#app-ch03-assignment)). Such re-assignments form a **null\ndistribution**, built by imposing the null on the design; a bootstrap\ndistribution ([Appendix B](#app-ch03-resampling)) instead resamples the\ndata without imposing a null and describes the estimate's variability,\nso it is not a reference for testing zero.\n\nWhat moves the test statistic? @tbl-ch03-what-moves-t starts from the\nSpecial Practice summaries and changes one input at a time, the last\nrow two.\n\n| Change from the observed study | SE (points) | t (df) | Two-sided p | 95% interval (points) |\n|:--|--:|--:|--:|:--|\n| As observed: difference 3.1, SDs 6.0 and 6.4, 60 per group | 1.1325 | 2.7372 (118) | .0072 | [0.8572, 5.3428] |\n| Spread 1.5 times larger: SDs 9.0 and 9.6 | 1.6988 | 1.8248 (118) | .0706 | $[-0.2641,\\ 6.4641]$ |\n| Smaller groups: 15 per group | 2.2651 | 1.3686 (28) | .1820 | $[-1.5398,\\ 7.7398]$ |\n| Separation halved: difference 1.55 | 1.1325 | 1.3686 (118) | .1737 | $[-0.6928,\\ 3.7928]$ |\n| Separation halved, 240 per group | 0.5663 | 2.7372 (478) | .0064 | [0.4373, 2.6627] |\n\n: What moves the test statistic: stipulated variations of the Special Practice summaries under the equal-variance procedure. {#tbl-ch03-what-moves-t tbl-colwidths=\"[40,13,16,12,19]\"}\n\nThe statistic divides the separation between the means by an SE that\ngrows with the spread of the scores and shrinks with the group sizes,\n$\\widehat{SE}=s_p\\sqrt{1/n_1+1/n_0}$. Making both SDs 1.5 times larger\nmultiplies the SE by 1.5, and the same 3.1-point difference no longer\nexcludes zero, $p=.0706$; a quarter of the students doubles the SE,\n$p=.1820$; halving the separation halves the statistic while the SE\nstays the same, $p=.1737$. The last row halves the separation and\nquadruples the groups. Its statistic returns exactly to 2.7372, so a\nstudy with half the effect and four times the students is just as\nsignificant, $p=.0064$ on 478 df, yet its interval, [0.4373, 2.6627],\nis centered at 1.55 points, below the two-point benchmark. A test\nstatistic measures separation relative to its SE, not the size of an\neffect; the estimate, its interval and the benchmark carry the\nmagnitude.\n\nCalling the result statistically significant records that .0072 is\nbelow the advance threshold .05. It supplies neither the size of the\neffect nor a study-specific probability of having made an error. The\ntable below collects six common mistranslations of the displayed\np-value and their repairs; reporting the estimate and interval alongside\nthe p-value keeps these distinctions visible.\n\n\\Needspace{22\\baselineskip}\n\n| Mistranslation | Why it fails | Repair |\n|:--|:--|:--|\n| \"There is a 0.72% chance the null is true.\" | The p-value conditions on the null; it does not assign probability to it | Under the zero-contrast null and procedure, results at least this incompatible have probability .0072 |\n| \"There is a 0.72% chance the result happened by chance.\" | Chance is not a complete model; the result already happened | Name the null, design, statistic, and reference process |\n| \"The study has a 99.28% chance of replicating.\" | Replication depends on the effect, design, sample, and analysis | Report the current estimate and uncertainty; discuss replication separately |\n| \"The effect is large or important because $p=.0072$.\" | A p-value is not an effect-size or importance measure | Interpret 3.1 points and its interval against a defensible benchmark |\n| \"The study's false-positive probability is 0.72%.\" | A long-run error rule and a data-dependent p-value differ | State any prespecified decision rule; avoid a posterior error claim |\n| \"The p-value keeps its usual meaning after this outcome or model was selected from inspected results.\" | The selection rule is part of the procedure and can alter calibration | Report the family of analyses and whether the comparison was chosen in advance; interpret the selected result accordingly |\n\n: Six mistranslations of the displayed $p=.0072$ and their repairs. {#tbl-ch03-p-mistranslations tbl-colwidths=\"[30,32,38]\"}\n\n## t Tests for One, Paired and Two Independent Samples {#sec-ch03-t-tests}\n\nSections 3 and 4 used two members of a family of named t tests, one for\na single mean and one for the difference between two group means. The\nmembers differ in which observations carry the information, how the SE\nis calculated, and which df the reference uses; their shared name does\nnot make paired and independent data interchangeable. The table lists\nthem in the order this section teaches them.\n\n\\Needspace{10\\baselineskip}\n\n| Procedure | Data and null | SE and reference |\n|:--|:--|:--|\n| One-sample t | One quantitative sample; $H_0:\\mu=\\mu_{\\mathrm{null}}$ | $s/\\sqrt n$; $df=n-1$ |\n| Paired-samples t | Correctly matched observations, independent pairs; $H_0:\\mu_D=0$ | $s_d/\\sqrt n$ on pair differences; $df=n-1$ |\n| Equal-variance two-sample t | Two independent samples with a common population variance; $H_0:\\mu_1-\\mu_0=0$ | $s_p\\sqrt{1/n_1+1/n_0}$; $df=n_1+n_0-2$ |\n| Welch's unequal-variance t | Two independent samples whose variances may differ; same mean null | $\\sqrt{s_1^2/n_1+s_0^2/n_0}$; approximate df estimated from the data |\n\n: Named t tests and the observations that carry information. {#tbl-ch03-t-procedures tbl-colwidths=\"[24,40,36]\"}\n\nTwo of these procedures, the one-sample t test (Section 5.1) and the\nequal-variance two-sample t test (Section 5.3), are followed after\ntheir worked result by a box titled *Justifying the analysis*, and\nSection 6 gives one to the chi-square test of association. Chapter 1,\nSection 6.1, used the word *justification* for the reasons and\nconditions invoked to support a comparison, analytical move or\ninterpretation, and its Section 3.4 introduced the assumptions such\nreasons invoke. The box makes that justification concrete for one\nanalysis in four labelled lines. **Target** states what the number\nestimates, in its units and for which units. **Conditions** sorts what\nthe analysis relies on into three kinds: conditions *secured by\ndesign*, such as random assignment, random sampling, pairing and\nindependent units; *model assumptions* the procedure adds, such as a\ncommon spread or the shape of a sampling distribution; and *choices and\ndefaults* the analyst sets, such as the sidedness, the confidence level\nand the variance model. **Check** gives the evidence the data offer\nabout each model assumption and the result that would change the\ndecision, or says plainly that the data cannot check it. **Bound**\nstates what the result supports and what it does not. The paired and\nWelch t tests are variants of the procedures with boxes, so each states\nin a sentence or two what changes, and a later use of any procedure\nrefers to its box and adds only what changes.\n[Appendix B](#app-ch03-procedure-guide) collects the five procedures in\none table with their conditions and the usual response when a condition\nfails.\n\n### One-sample t test and its z counterpart\n\nThe district calculation of Sections 3 and 4 is a **one-sample t test**\nwith its matching interval: SE 1 point, a t reference with 24 df,\nthe statistic 2, the two-sided p-value .0569 and the 95% interval\n[49.936, 54.064]. A close relative uses a known SD instead of an\nestimated one.\n\nChapter 2 used a **z score**, $z_i=(x_i-\\mu)/\\sigma$, to locate\none observation in population SD units. Sample standardization,\n$(x_i-\\bar x)/s$, describes an observation relative to its sample.\nNeither operation makes the original distribution Normal. For a mean,\nthe quantity being standardized is instead its estimator, so the\ndenominator is an SE:\n\n$$\nz=\\frac{\\bar x-\\mu_0}{\\sigma/\\sqrt n},\\qquad\nt=\\frac{\\bar x-\\mu_0}{s/\\sqrt n},\\qquad df=n-1.\n$$\n\nThe **one-sample z test** uses a population SD known independently of\nthe sample. The **one-sample t test** estimates that SD with $s$.\nIts exact t reference requires independent observations from a Normal\npopulation; suitable distributional conditions and enough information\ncan support an approximation more broadly. A large sample does not turn\nan unknown SD into a known one or remove dependence.\n\nFor the same statistic 2, the two-sided probabilities beyond the\nlines of @fig-ch03-z-t in Section 3.1 are .0455 under the Normal, .0766\nunder t with 9 df and .0482 under t with 99 df. If the district's\npopulation SD were known independently to be 5 points, the z test would\ngive .0455 rather than the t test's .0569. The change comes from the\nreference tails, not from the arithmetic of the statistic, and only\ngenuine knowledge of the SD justifies the z reference; falling on the\nother side of .05 does not. Changing a study's sample size can also\nchange its SE and observed statistic, which is a separate comparison.\n\n\\Needspace{6\\baselineskip}\n\n[]{#ch03-justify-one-sample}\n\n::: {.callout-tip title=\"Justifying the analysis\"}\n- **Target:** The mean reading score $\\mu$ of the district's students,\n  in scale points, compared with the published reference value 50.\n- **Conditions:**\n  - *Secured by design:* A simple random sample of 25 students from a\n    large district, each measured once, so the scores are independent\n    observations.\n  - *Model assumptions:* An approximately Normal population of scores,\n    so that the t reference with 24 df applies to a mean whose SD is\n    estimated from the same 25 scores.\n  - *Choices and defaults:* A two-sided alternative, $H_A:\\mu\\ne50$,\n    chosen in advance; 95% confidence and level .05; one planned test;\n    all 25 scores observed.\n- **Check:** The summaries, mean 52 and SD 5, cannot show the shape of\n  the scores. With the 25 scores in hand, strong skew or one score far\n  from the rest would weaken the t approximation and call for a\n  bootstrap comparison ([Appendix B](#app-ch03-resampling)). The\n  decision is close, $p=.0569$ against .05, so the reference must follow from the conditions: the\n  z reference's .0455 would need an SD known independently of the\n  sample.\n- **Bound:** The interval [49.936, 54.064] describes the district mean\n  under the sampling model: means from just below 50 to about 54 points\n  remain compatible, and the level-.05 test does not reject 50. The\n  result does not show that the mean equals 50, and it concerns this\n  district only.\n:::\n\n### Paired-samples t test {#sec-ch03-paired}\n\nIn a paired design each observation in one set is matched with one in\nthe other, most often because the same person is measured twice. The\npair, not the single score, is then the unit that carries the\ninformation. Eight invented students, separate from the Special\nPractice records, completed the same assessment before and after a\nshort practice session (@tbl-ch03-student-pairs). Define each student's\ndifference as $d_i=\\mathrm{after}_i-\\mathrm{before}_i$, keeping the\nperson and the subtraction direction before any summary is calculated.\n\n\\Needspace{13\\baselineskip}\n\n| Student | Before | After | Difference |\n|:--|--:|--:|--:|\n| 1 | 50 | 49 | $-1$ |\n| 2 | 54 | 54 | 0 |\n| 3 | 48 | 49 | 1 |\n| 4 | 60 | 62 | 2 |\n| 5 | 55 | 57 | 2 |\n| 6 | 58 | 61 | 3 |\n| 7 | 62 | 66 | 4 |\n| 8 | 53 | 58 | 5 |\n\n: Invented paired student scores; these are not Special Practice records. {#tbl-ch03-student-pairs tbl-colwidths=\"[25,25,25,25]\"}\n\nOnce the differences are formed, the **paired-samples t test** is the\none-sample t test of Section 5.1 applied to them: the null is a zero\nmean change, $H_0:\\mu_D=0$, the SE is $s_d/\\sqrt n$ for the $n$ pairs,\nand the reference is t with $n-1$ df. For the eight students the mean\nchange is 2 points with SD 2, so\n$\\widehat{SE}(\\bar d)=0.7071$, $t(7)=2.8284$, $p=.0255$, and the 95%\ninterval is [0.328, 3.672] points.\n\n[]{#ch03-justify-paired}\n\nThe justification of the one-sample t test in\n[Section 5.1](#ch03-justify-one-sample) carries over with the pair as\nthe unit: the design forms the pairs, the eight pairs must be\nindependent of one another, which rests on how the students were\nchosen, and the near-Normal shape concerns the differences, so they,\nnot the two sets of scores, are what to inspect. The bound changes\ntoo: without an untreated comparison, a mean change of 2 points\ndoes not separate the practice session from time trends, repeated\ntesting or other changes between the two measurements.\n\nWhy must the pairing be kept? The variance identity of Section 2.3\ngives\n$\\operatorname{Var}(Y_{\\mathrm{after}}-Y_{\\mathrm{before}})\n=\\operatorname{Var}(Y_{\\mathrm{after}})+\\operatorname{Var}(Y_{\\mathrm{before}})\n-2\\operatorname{Cov}(Y_{\\mathrm{after}},Y_{\\mathrm{before}})$:\nwhen a student's two scores rise and fall together, the covariance term\nremoves the variation they share.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The eight invented students' scores three ways. (a) Before and after as two separate sets, with their means; (b) each student's two scores joined; (c) the eight after-minus-before differences, with the paired 95% interval, [0.3280, 3.6720] (blue), and the interval from analysing the scores as two independent groups, $[-3.8877,\\ 7.8877]$ (red).](chapter_03_files/figure-html/fig-ch03-paired-1.png){#fig-ch03-paired fig-pos='!ht' fig-alt='Three panels. In the first, eight before scores from 48 to 62 and eight after scores from 49 to 66 overlap heavily, with means 55 and 57 marked. In the second, lines join each student\\'s two scores and run nearly parallel, most rising slightly. In the third, the eight differences from minus 1 to 5 sit above a short blue interval from 0.3280 to 3.6720 and a long red interval from minus 3.8877 to 7.8877 that crosses zero.' width=691.2}\n:::\n:::\n\n\n@fig-ch03-paired shows what the covariance term does. Panel (a) is\nwhat an analysis of two independent groups sees: two overlapping sets\nof eight scores whose spread, SDs of about 5 and 6 points, swamps a\n2-point shift. Panel (b) restores the pairing: students who scored high\nbefore also scored high after, so the lines run nearly parallel and the\nscores correlate at .9599. The differences in panel (c) keep the change\nand drop the shared between-student variation. Their interval is short\nand excludes zero, whereas analysing the same scores as two independent\ngroups gives an SE of 2.7451 rather than 0.7071 and the interval\n$[-3.8877,\\ 7.8877]$, which spans zero. The data did not change; the\nrelevant variation did. Because the pairing comes from how the scores\nwere obtained, only the paired analysis describes their uncertainty.\nChapter 4's term *pairwise comparisons* refers to several group\ncontrasts, a different use of the word.\n\nThe school-blocked design of [Section 2.3](#sec-ch03-school-pairs) is\na paired design too: each school supplies one explanatory-minus-usual\ndifference of class means, and the paired t test applied to the twelve\ndifferences gives $t(11)=3.6187$, $p=.004$ and the 95% interval\n[0.9795, 4.0205] points. Here each pair is a school, and random\nassignment of the two classes within each school supports a causal\nreading for these participating schools, which the before-and-after\nscores could not; the schools were not sampled, so the result does not\nby itself reach other schools.\n\n### Equal-variance two-sample t test {#sec-ch03-equal-variance}\n\nThe procedure used for Special Practice throughout Sections 3 and 4 is\nthe **equal-variance two-sample t test**, also called the pooled or\nStudent's two-sample t test. Its model has two independent groups whose\npopulations share one variance. With Normal populations its t reference\nis exact; with adequate group sizes and moderate departures from\nNormality it is a good approximation. Its SE is the pooled SE of\nSection 2.2, $s_p\\sqrt{1/n_1+1/n_0}$, and its reference has $n_1+n_0-2$\ndf. For Special Practice, Sections 2.2, 3.4 and 4.4 have already\nproduced the complete result: SE 1.1325 points on 118 df, $t=2.7372$,\n$p=.0072$ and the 95% interval [0.8572, 5.3428] points. The new step is\nto read the procedure's conditions against the design, which the box\nbelow does.\n\n\\Needspace{6\\baselineskip}\n\n[]{#ch03-justify-equal-variance}\n\n::: {.callout-tip title=\"Justifying the analysis\"}\n- **Target:** The mean effect $\\Delta\\mu$ of assignment to Special rather\n  than Usual Practice on the delayed 0--40 assessment, in points, for\n  these 120 participants.\n- **Conditions:**\n  - *Secured by design:* Random assignment of 60 students to each\n    format, which supports a causal comparison among the participants;\n    different students in the two groups.\n  - *Model assumptions:* One population spread shared by the two\n    groups; a near-Normal sampling distribution for the difference in\n    means; no relevant interference, so one student's format does not\n    change another's score. The t reference with 118 df is an\n    approximate calibration for the assignment design (Section 1.3).\n  - *Choices and defaults:* Special minus Usual; a two-sided test of\n    zero; 95% confidence and level .05; the equal-variance model, chosen\n    from the design before the analysis; one comparison and the\n    two-point benchmark, both fixed before the outcomes were seen;\n    complete follow-up of all 120, so no missing scores to handle.\n- **Check:** The SDs, 6.0 and 6.4 points, are similar, and with 60\n  students in each group the pooled and unpooled SEs are identical\n  whatever the spreads; Welch's procedure gives the same statistic with\n  117.5119 df and the same p-value to four decimals (Section 5.4). The\n  records in @fig-ch03-scores (Section 1.1) show no score dominating\n  either mean: the three scores beyond the whiskers, 13 in Special\n  Practice and 38 and 39 in Usual Practice, lie within two points of\n  the whisker ends, and each mean averages 60 scores. Interference\n  cannot be checked from the scores; it rests on how the sessions were\n  run.\n- **Bound:** A positive mean assignment effect among these participants\n  is supported, 3.1 points, 95% CI [0.8572, 5.3428]. Its practical\n  importance against the two-point benchmark remains open (Section 7.1),\n  and the result does not speak to attendance, mechanisms, longer-term\n  learning or students elsewhere.\n:::\n\nA results sentence names the procedure and reports the df beside the\nstatistic:\n\n> Under the equal-variance working model, Special Practice scored 3.1\n> points higher on average, 95% CI [0.8572, 5.3428], *t*(118) = 2.7372,\n> *p* = .0072.\n\n### Welch's unequal-variance t test {#sec-ch03-welch}\n\nPooling assumes that both groups estimate one population variance.\n**Welch's unequal-variance t test** drops that assumption and keeps\neach group's own variance in the SE [@welch1947]:\n\n$$\n\\widehat{SE}_{\\mathrm{Welch}}=\\sqrt{\\frac{s_1^2}{n_1}+\\frac{s_0^2}{n_0}},\n\\qquad\nt=\\frac{\\bar y_1-\\bar y_0}{\\widehat{SE}_{\\mathrm{Welch}}}.\n$$\n\nIts reference is an approximate t distribution whose df, the\n**Welch--Satterthwaite degrees of freedom**, are estimated from the two\nvariance contributions $s_1^2/n_1$ and $s_0^2/n_0$. They lie between\n$\\min(n_1,n_0)-1$ and $n_1+n_0-2$. When one group's mean carries almost\nall the uncertainty, they fall toward that group's own $n-1$, which is\nthe lower bound when it is the smaller group. They reach the upper\nbound, the equal-variance test's df, only when each contribution is\nproportional to its group's df, $n_1-1$ or $n_0-1$, as with equal sizes\nand equal SDs. Software computes them, and fractional df describe the\napproximation rather than counting people.\n\nWelch's test is therefore not simply a more cautious version of the\nequal-variance test: it asks the same question under a weaker\nassumption, and how much the choice matters depends on the design.\nWith equal group sizes the two SEs and t statistics coincide\n(Section 2.2), but the df differ unless the two SDs are equal too. With\ngroups of moderate size that difference barely moves the p-value, and\nWelch's test gives up almost no power; with small groups and very\nunequal spreads it can change the conclusion. With five students per\ngroup, SDs 10 and 1, and $t=2.5$, the equal-variance test gives\n$p=.0369$ on 8 df and Welch's test $p=.0655$ on 4.08 df. With equal\nspreads but unequal sizes Welch's test gives up a little power. With\nunequal group sizes and unequal spreads, however, the pooled variance, a\ndf-weighted average dominated by the larger group, misstates the\nvariance of the smaller group's mean, and the equal-variance test's\nerror rate drifts in one direction or the other.\n\nFor a separate, invented comparison, suppose a district draws two\nindependent random samples of students who took the same 0--40\nassessment: 10 from a small intensive-support programme and 40 from its\nusual programme. The intensive group averaged 29 points with SD 8;\nthe usual group averaged 24 with SD 4. The estimand is the\ndifference between the two programmes' population mean scores, a\ncomparison of populations rather than an effect of assignment. Before\nseeing these scores, staff expected a wider spread in the intensive\nprogramme, which enrols students with a broad range of prior attainment\nand may help some of them much more than others.\n@tbl-ch03-welch-example sets the two analyses side by side.\n\n\\Needspace{9\\baselineskip}\n\n| Result for the 5-point difference | Equal-variance t | Welch's t |\n|:--|--:|--:|\n| SE of the difference (points) | 1.7678 | 2.6077 |\n| t statistic | 2.8284 | 1.9174 |\n| Degrees of freedom | 48 | 10.151 |\n| Two-sided p-value | .0068 | .0837 |\n| 95% interval (points) | [1.4457, 8.5543] | $[-0.7986,\\ 10.7986]$ |\n\n: The same summaries under two variance models. {#tbl-ch03-welch-example tbl-colwidths=\"[44,28,28]\"}\n\nThe equal-variance SE is much smaller than Welch's because the pooled\nvariance lies near the usual group's small spread, which supplies 39 of\nits 48 df, and pooling lends that small spread to the intensive group's\nmean. The equal-variance interval therefore excludes zero while Welch's\nincludes it. Welch's df, 10.151, lie close to the lower bound of 9\nbecause the intensive group's mean carries almost all of the\nuncertainty. Because the staff expected unequal spreads before seeing\nthe scores, Welch's procedure is the one this design calls for.\n@fig-ch03-welch-dots draws one invented set of 50 scores with exactly\nthese summaries and shows what pooling does to each group's mean.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![One invented set of scores with the two programmes' summaries: 10 intensive-programme scores (mean 29, SD 8) and 40 usual-programme scores (mean 24, SD 4). Below each group's dots, the blue bar spans one SE either side of the mean from the group's own SD, and the red bar one SE from the pooled SD, 5.](chapter_03_files/figure-html/fig-ch03-welch-dots-1.png){#fig-ch03-welch-dots fig-pos='!ht' fig-alt='Two stacked dot plots on an assessment scale from 14 to 42. The ten intensive scores spread from 18 to 40 in two loose clusters, 18 to 24 and 29 to 40; the forty usual scores run from 16 to 33, most between 19 and 30. For the intensive mean of 29 the blue own-SD bar, plus or minus 2.5298, is much wider than the red pooled bar, plus or minus 1.5811; for the usual mean of 24 the blue bar, plus or minus 0.6325, is slightly shorter than the red one, plus or minus 0.7906.' width=691.2}\n:::\n:::\n\n\nPooling lends the usual group's tighter spread to the intensive group's\nmean: the SE of that mean shrinks from its own 2.5298 points to 1.5811,\nwhile the usual group's grows only from 0.6325 to 0.7906. The pooled SE\nof the difference therefore understates the uncertainty that the ten\nwidely spread intensive scores carry.\n\n[]{#ch03-justify-welch}\n\nThe justification of the equal-variance test in\n[Section 5.3](#ch03-justify-equal-variance) carries over with three\nchanges: the target is a difference between two populations' means,\nbecause the programmes were sampled rather than assigned; no common\nspread is assumed, so the model assumptions concern each group mean,\nabove all the ten intensive scores, whose dot plot shows no single\ndominating score; and Welch's variance model was chosen before the\nscores were seen. Its bound is correspondingly modest: the interval\n$[-0.7986,\\ 10.7986]$, $p=.0837$, does not establish which programme\nhas the higher population mean.\n\nHow much does the variance model matter? @tbl-ch03-welch-simulation\nanswers by simulation. Each row generates 50,000 studies of two\nindependent samples from Normal populations with equal means and the\nstated SDs, so every rejection of a zero difference rejects a true\nnull, and records how often each procedure's two-sided test at level\n.05 rejects.\n\n\\Needspace{8\\baselineskip}\n\n| Group sizes | Population SDs | Equal-variance t | Welch's t |\n|:--|:--|--:|--:|\n| 10 and 40 | 8 and 4, as in the two-programme comparison | .1848 | .0507 |\n| 10 and 40 | 4 and 8 | .0055 | .0513 |\n| 25 and 25 | 8 and 4 | .0514 | .0493 |\n\n: Rejection rates of a true zero difference at nominal level .05, from 50,000 simulated studies per design. {#tbl-ch03-welch-simulation tbl-colwidths=\"[16,48,18,18]\"}\n\nWhen the smaller group is the more variable, the equal-variance test\nrejects the true null in .1848 of the studies instead of .05, so only\n81.52% of its nominal 95% intervals cover the true difference; when the\nsmaller group is the less variable it rejects in only .0055, a test\nthat has become needlessly conservative and lost power. With equal\ngroup sizes both tests stay near .05, and Welch's test stays near .05\nin all three designs. This is why many texts recommend Welch's test\nwhenever the spreads may differ, and statistical software such as R\nuses it by default [@delacre2017].\n\nFor Special Practice the two procedures nearly coincide: with 60\nstudents in each group both SEs are 1.1325 points, so both give\n$t=2.7372$, and Welch's df, 117.5119, fall just below 118 because the\nSDs 6.0 and 6.4 are close but not equal, so both p-values display as\n.0072. The agreement follows from equal group sizes and similar SDs; it\ndoes not by itself establish equal population variances.\n\nChoose between the procedures before the analysis, from the design and\nsubject knowledge: whether a common spread is plausible given how the\ngroups were formed and what the conditions might do to individual\nresponses, and whether the group sizes are equal. A preliminary test of\nequal variances is not a good basis for the choice: the two-stage\nprocedure alters the error rates it is meant to protect, such tests\nhave least power in the small samples where the choice matters most,\nand a nonsignificant variance test does not establish equal variances\n[@zimmerman2004; @delacre2017]. Choosing whichever procedure excludes\nzero is selecting an analysis after inspection, a problem Section 7.3\ntakes up.\n\n## Association Between Categorical Variables: The Chi-Square Test {#sec-categorical-comparison}\n\nThe test logic of Section 4 is not limited to means. Chapter 2,\nSection 3.1, described the relationship between two categorical\nvariables with conditional proportions, comparing passing among\nstudents with and without a higher-education intention. Such a\nrelationship is an **association** between categorical variables: the\ndistribution of one variable changes across the categories of the\nother. When the outcome is a category, such as completed or not, each\nrecord falls in one cell of a table and the data are counts. This\nsection builds a test of association with the same three parts as the\ntests of Section 4: a null hypothesis, a statistic that measures\ndeparture from it, and a reference distribution for that statistic.\nIts last subsection reads tables of three or more categorical\nvariables.\n\n### Counts, proportions and expected counts\n\nConsider an invented teaching model with 100 independently sampled\nlearners. For each learner the participation format, Online or In\nperson, and whether the learner completed the course were recorded. The\nformat was observed rather than randomly assigned, so the question\nconcerns association: is completion related to format?\n@tbl-ch03-two-way crosses the two variables in a **two-way table**,\nwith one cell for each combination and the totals in the margins. The\nnumber of ways counts the variables crossed, not their categories: a\ntable of three formats by completion would still be a two-way table.\n\n\\Needspace{8\\baselineskip}\n\n| Participation format | Completed | Did not complete | Total | Completion proportion |\n|:--|--:|--:|--:|--:|\n| Online | 32 | 18 | 50 | .64 |\n| In person | 18 | 32 | 50 | .36 |\n| Total | 50 | 50 | 100 | .50 |\n\n: Invented counts of completion by participation format for 100 learners. {#tbl-ch03-two-way tbl-colwidths=\"[28,16,20,12,24]\"}\n\nAmong the 50 Online learners 32 completed, a **conditional proportion**\nof $32/50=.64$; among the 50 In-person learners 18 completed,\n$18/50=.36$. Each proportion divides by its own format's total, so\nthe two formats can be compared even when their sizes differ. The\nOnline-minus-In-person difference is .28, or 28 percentage\npoints. @fig-ch03-completion draws the two proportions beside the\n.5 of all 100 learners.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Completion by participation format in the invented table of 100 learners. Each bar divides one format's 50 learners into those who completed (dark) and those who did not (light); the dashed line marks the completion proportion of all 100 learners, .5, which both formats would share if format and completion were independent.](chapter_03_files/figure-html/fig-ch03-completion-1.png){#fig-ch03-completion fig-pos='!ht' fig-alt='Two horizontal bars, Online above In person, each running from 0 to 1. The dark completed part reaches .64 for Online and .36 for In person, with the remainders .36 and .64 in a light shade. A dashed red line at .5 is labelled as the proportion of all 100 learners; the Online bar\\'s completed part extends past it and the In-person bar\\'s stops short of it.' width=691.2}\n:::\n:::\n\n\n\\Needspace{8\\baselineskip}\n\nAre the two rates different enough, beyond sampling variation, to\nindicate an association in the population? The test sets two\nhypotheses about the stipulated population or process:\n\n$$\n\\begin{aligned}\nH_0&:\\ \\text{format and completion are not associated},\\\\\nH_A&:\\ \\text{format and completion are associated}.\n\\end{aligned}\n$$\n\nNo association means that format and completion are **independent**:\nthe completion probability is the same in both formats. Estimated from\nall the records, that common probability is\n$50/100=.5$, so independence predicts 25 completions among the 50\nOnline learners and 25 among the 50 In-person learners. In general a\ncell's **expected count** is\n\n$$\nE_{rc}=\\frac{(\\text{row }r\\text{ total})(\\text{column }c\\text{ total})}{n},\n$$\n\nwhich for the Online/Completed cell gives $50\\times50/100=25$. Expected\ncounts keep the observed margins while imposing the null relationship,\nand in other tables they need not be whole numbers.\n@tbl-ch03-counts sets the observed counts beside the expected ones.\n\n\\Needspace{8\\baselineskip}\n\n| Participation format | Observed: completed | Observed: did not | Expected: completed | Expected: did not |\n|:--|--:|--:|--:|--:|\n| Online | 32 | 18 | 25 | 25 |\n| In person | 18 | 32 | 25 | 25 |\n| Total | 50 | 50 | 50 | 50 |\n\n: Observed counts and the counts expected under independence, with the same margins. {#tbl-ch03-counts tbl-colwidths=\"[24,19,19,19,19]\"}\n\nEvery observed count lies 7 from its expected count: more Online and\nfewer In-person learners completed than independence predicts.\n\n### The chi-square statistic and its distribution\n\nPearson's **chi-square statistic** gathers the departures into one\nnumber. Each observed-minus-expected difference is squared, so that\ndepartures in either direction count, and divided by its expected\ncount, so that a departure is judged against the size of its cell:\n\n$$\nX^2=\\sum_{\\text{cells}}\\frac{(O_{rc}-E_{rc})^2}{E_{rc}}.\n$$\n\nHere each of the four cells contributes $(32-25)^2/25=1.96$, so\n$X^2=7.84$. A table that matched independence exactly would give 0,\nand larger values mean larger departures.\n\nHow large is large? If format and completion are independent, $X^2$\nfollows approximately a **chi-square distribution**. Panel (a) of\n@fig-ch03-chisq shows that this is a family of right-skewed\ndistributions on positive values whose shape is set by the degrees of\nfreedom: the mean of each curve equals its df, so the curves move right\nand spread out as the df grow. For a two-way table with $r$ rows and\n$c$ columns the df are $(r-1)(c-1)$. In a two-by-two table, once the\nrow and column totals are fixed, the count in one cell determines the\nother three, so only one cell is free to depart from independence and\n$df=(2-1)(2-1)=1$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The chi-square reference. (a) Chi-square distributions with 1, 4 and 8 degrees of freedom: right-skewed curves on positive values whose centre and spread grow with the df. (b) The upper tail of the distribution with 1 df, the reference for a two-by-two table, enlarged on its own vertical scale: the shaded area beyond the .05 critical value 3.8415 holds .05, and the dark part beyond the observed statistic 7.84 is the p-value, $p=.0051$.](chapter_03_files/figure-html/fig-ch03-chisq-1.png){#fig-ch03-chisq fig-pos='!ht' fig-alt='Two panels. The first shows three density curves on an axis from 0 to 20: with 1 degree of freedom the curve falls steeply from a high value near zero; with 4 it peaks near 2; with 8 it peaks near 6 and spreads further right. The second enlarges the upper tail of the curve with 1 degree of freedom, from 3 to 12 on a density axis up to 0.04: a dashed grey line at 3.8415 is labelled critical 3.8415, .05 beyond, and the region beyond it is shaded light red; a red mark at 7.84 is labelled observed 7.84, p = .0051 beyond, and the smaller region beyond it is dark red.' width=691.2}\n:::\n:::\n\n\nOnly the upper tail counts. Because every contribution is squared,\ndepartures from independence in either direction make $X^2$ larger, so\nthe p-value is the area beyond the observed statistic in the upper\ntail. Panel (b) enlarges the upper tail of the chi-square distribution\nwith 1 df: 5% of it lies beyond the critical value 3.8415, and the\nobserved 7.84 lies well beyond that, cutting off the dark upper-tail\narea $p=.0051$. If format and completion were\nindependent, a table departing from independence at least this much\nwould arise in about 5 of every 1,000 samples of 100 learners.\n\n### Reading the result and its conditions\n\nUnder the stipulated model, the table gives evidence against\nindependence. The proportions give the direction and size that the\nsquared statistic discards: completion is 28 percentage points\nmore frequent in the Online group. This observed association does not\nestablish that assigning a format would change completion, because\nlearners chose or were placed in their formats by processes the table\ndoes not record.\n\n\\Needspace{6\\baselineskip}\n\n[]{#ch03-justify-counts}\n\n::: {.callout-tip title=\"Justifying the analysis\"}\n- **Target:** Whether participation format and completion are associated\n  in the stipulated population, with direction and size given by the\n  completion proportions, .64 Online and .36 In person.\n- **Conditions:**\n  - *Secured by design:* 100 independently sampled learners, each\n    counted once in exactly one of the four cells. The format was\n    observed, not assigned.\n  - *Model assumptions:* Expected counts large enough for the chi-square\n    reference with 1 df to approximate the statistic's distribution\n    under independence.\n  - *Choices and defaults:* Pearson's statistic without a continuity\n    correction, as calculated above; the upper tail, because only large\n    discrepancies count against independence; level .05; Online minus\n    In person for the proportion difference.\n- **Check:** Every expected count is 25, far above the small counts at\n  which the approximation weakens; a common guideline flags expected\n  counts below 5, where an exact test (Chapter 6) would take its place.\n  Independence of the records cannot be checked from the table: learners\n  counted twice or sharing a class would make the counts overstate the\n  information.\n- **Bound:** Evidence against independence in the stipulated\n  population, $X^2(1)=7.84$, $p=.0051$, with a completion proportion\n  .28 higher Online. Because the format was observed rather than\n  assigned, the table does not show that assigning a format would change\n  completion.\n:::\n\nStatistical software often applies a continuity correction to a\ntwo-by-two table by default, a related but different calculation;\nChapter 6 reproduces the uncorrected statistic taught here in R and\ndevelops further categorical analyses. Exercise 7 supplies a separate\n200-record table for applying the same reasoning.\n\n### Three or more categorical variables {#sec-ch03-multiway}\n\nA two-way table holds two categorical variables. Crossing a third gives\na **three-way table**, and a fourth a four-way table; any table of\nthree or more is a **multiway table**. Suppose the invented record had\nalso noted whether each learner had studied the subject before, with\n25 learners of each format in each prior-study group.\n@tbl-ch03-three-way arranges the same 100 learners by prior study,\nformat and completion. It is read as two-way tables within the\n**layers** of the third variable: one format-by-completion table for\nthe learners who had studied the subject before, and one for those new\nto it. Adding the two layers cell by cell returns the two-way table of\nSection 6.1.\n\n\\Needspace{12\\baselineskip}\n\n| Prior study | Participation format | Completed | Did not complete | Total | Completion proportion |\n|:--|:--|--:|--:|--:|--:|\n| Studied before | Online | 19 | 6 | 25 | .76 |\n|  | In person | 15 | 10 | 25 | .60 |\n| New to the subject | Online | 13 | 12 | 25 | .52 |\n|  | In person | 3 | 22 | 25 | .12 |\n| Both layers added | Online | 32 | 18 | 50 | .64 |\n|  | In person | 18 | 32 | 50 | .36 |\n\n: Invented counts of completion by participation format within two layers of prior study, for the same 100 learners. {#tbl-ch03-three-way tbl-colwidths=\"[25,19,15,16,9,16]\"}\n\nWithin each layer, Online learners completed more often: .76 against\n.60 among those who had studied the subject before, a difference of\n.16, and .52 against .12 among those new to it, a difference of .40.\nPrior study also goes with completion in both formats. Because each\nlayer holds the same number of learners of each format, the added\ntable's difference, .28, lies midway between the layer differences.\nWhen the layers hold different mixes of the groups compared, the added\ntable can differ from every layer; Chapter 14 reads a real admissions\ntable in which the added comparison points the other way from most of\nits layers.\n\nThe chi-square test of Sections 6.1--6.3 applies to any one two-way\ntable in the display. Applied to one layer, it asks whether format and\ncompletion are associated among that layer's 50 learners; applied to\nthe added table, it asks the question of Section 6.1, with prior study\nset aside. No test of one two-way table answers a question about the\nthree variables jointly: whether the format difference is the same in\nboth layers, or whether format and completion are associated once\nprior study is held fixed, with all 100 learners used at once. Such\nquestions need a method that uses all three variables at once, such as\nthe models for multiway tables that begin with logistic regression in\nChapter 11.\n\nComparing the two layers' tests does not settle whether their\nassociations differ. Each layer's p-value depends on the size of its\nassociation and on the number of learners in the layer, so a p-value\nbelow .05 in one layer beside one above .05 in the other shows that the\nevidence differs, not that the associations do [@gelman2006]. The\ndifference between the layer differences, .40 against .16, is a\nquantity with its own uncertainty, which a joint model estimates.\n\nA fourth variable, such as the term in which a learner enrolled, adds a\nsecond layer variable. The four-way table is read as two-way tables\nwithin each combination of the two layer variables, four layers when\neach has two categories, and every added variable divides the same\nlearners among more layers, leaving fewer records in each.\n\n## Magnitude, Uncertainty, and Several Results {#sec-ch03-interpretation}\n\n### Magnitude and practical importance\n\nThe special-practice estimate, interval, test, and benchmark answer\ndifferent parts of the substantive question. The raw difference is\n3.1 points. Its approximate interval [0.8572, 5.3428] lies above zero and\nagrees with the two-sided $p=.0072$ result. It also spans the\ncourse-specific two-point importance criterion.\n\nConsequently, a positive mean assignment effect is supported under\nthe procedure, while its practical importance remains unresolved.\nEffects below the criterion and effects clearly above it are both\ncompatible with the data. The estimate exceeding two points does not\nsettle this issue. Nor would an interval crossing zero automatically\nmean that all effects of practical interest had been ruled out.\n\nA **standardized mean difference** expresses a raw difference relative\nto a named SD. One familiar denominator is the pooled SD of Section 2.2,\n$s_p=6.2032$ points, which gives\n\n$$\nd=\\frac{\\bar y_1-\\bar y_0}{s_p}=\\frac{3.1}{6.2032}=.4997.\n$$\n\nThe mean difference is about half of this particular within-group SD.\nHedges' correction adjusts $d$ for small-sample bias under its\nreference model; its usual approximation multiplies $d$ by a factor\njust below one [@lakens2013]:\n\n$$\ng\\approx d\\left(1-\\frac{3}{4(n_1+n_0)-9}\\right)=.4966.\n$$\n\nChanging the denominator changes the comparison's scale. It does not\nbroaden the participant scope or supply a universal importance threshold.\nFor the current course decision, assessment points and the two-point\nbenchmark remain the most direct terms. Chapter 4 develops effect-size\ninterpretation across group comparisons.\n\n### Errors, power, and precision planning\n\nA test ends in a decision, to reject the null or not to reject it, and\nthe decision can be wrong in two ways. A **Type I error** rejects a\nnull hypothesis that is true. Its probability is the significance level\n$\\alpha$, chosen in advance: a level-.05 rule applied when the null and\nthe procedure's conditions hold rejects in 5% of repetitions. A **Type\nII error** fails to reject a null that is false. Its probability,\n$\\beta$, depends on how far the truth lies from the null, so it is\ndefined only under a specified alternative, such as a true difference\nof three points. The **power** of the test at that alternative is the\nprobability that it rejects there, $1-\\beta$: the chance that the study\ndetects an effect of that size. @tbl-ch03-errors sets out the four\ncombinations of decision and truth; it says *do not reject* because\nthe decision does not reveal that the null is true.\n\n\\Needspace{9\\baselineskip}\n\n| Decision | Null is true | Specified alternative is true |\n|:--|:--|:--|\n| Do not reject $H_0$ | Correct nonrejection; probability $1-\\alpha$ for an exactly calibrated continuous test | Type II error; probability $\\beta$ at this alternative |\n| Reject $H_0$ | Type I error; probability $\\alpha$ for that calibrated test | Correct rejection; power $1-\\beta$ at this alternative |\n\n: Decisions and error probabilities under specified states of the model. {#tbl-ch03-errors tbl-colwidths=\"[22,39,39]\"}\n\nBoth error probabilities condition on a state of the model; neither is\nthe probability that the decision in one completed study is wrong. For\nan approximately calibrated procedure, nominal $\\alpha$ need not equal\nthe actual rejection probability, as the Welch demonstration of Section\n5.4 showed.\n\nThese probabilities matter most when a study is planned, and planning\ncan serve two purposes. **Precision planning** asks for an interval\nnarrow enough for the intended use. For a separate independent\ntwo-group study, suppose each group has anticipated SD 6.2 points and\nwe want a 95% interval with half-width 2 points. With $n$ per group the\nhalf-width is about $h=z^*\\sigma\\sqrt{2/n}$, and solving for $n$ gives\n\n$$\nn\\approx2\\left(\\frac{z^*\\sigma}{h}\\right)^2\n=2\\left(\\frac{1.96\\times6.2}{2}\\right)^2=73.8356,\n$$\n\nso 74 observed outcomes per group. The calculation uses a stipulated SD\nand an independent-sampling approximation; it does not redesign the\nfixed 120-participant study.\n\n**Power planning** asks how likely the study is to reject a zero\ndifference when a specified difference is real. At 74 per group the SE\nof the estimated difference is $6.2\\sqrt{2/74}=1.0193$ points. Treating\nthe planning SD as known, so that the Normal reference applies, a\ntwo-sided .05 test rejects when the estimate lies beyond $\\pm1.9977$\npoints. Panel (a) of @fig-ch03-errors-power draws two sampling\ndistributions of the estimate on one axis, under the null, centred at\nzero, and under an alternative with a true difference of 3 points,\ntogether with that one rejection rule. The null's two outer tails hold\n$\\alpha/2=.025$ each: a rejection there is a Type I error. Under the\nalternative, the hatched area between the boundaries, $\\beta=.1627$, is\nthe probability of a Type II error, and the rest of its curve, .8373,\nis the power at 3 points. Moving the alternative further from zero, or\nnarrowing both curves with a larger sample, shrinks $\\beta$ and raises\nthe power.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Errors and power for a planned study with 74 per group, outcome SD 6.2 and a two-sided .05 test, adapted from @biau2010. (a) Sampling distributions of the estimated difference under the null (true difference 0) and under an alternative (true difference 3), with the rejection boundaries $\\pm1.9977$: the null's dark outer tails hold $\\alpha/2=.025$ each; under the alternative, the hatched area between the boundaries is $\\beta=.1627$ and the light area beyond them is the power, .8373. (b) Power of the same rule across true differences for 37, 74 and 148 per group.](chapter_03_files/figure-html/fig-ch03-errors-power-1.png){#fig-ch03-errors-power fig-pos='!ht' fig-alt='Two panels. The first shows two bell-shaped curves of equal height on an estimated-difference axis, a solid null curve centred at 0 and a dashed alternative curve centred at 3, with dashed boundary lines at minus and plus 1.9977 marked on the axis. The null curve\\'s two small outer tails are dark blue; under the alternative curve the region between the boundaries is hatched red and labelled beta = .1627, and the larger region beyond 1.9977 is light blue and labelled power = .8373. The second plots power against true differences from 0 to 5 points for 37, 74 and 148 per group; every curve starts at .05, the 74-per-group curve passes .5009 at 2 and .8373 at 3, and the 148-per-group curve reaches .7925 at 2, just below a dotted line at .8.' width=691.2}\n:::\n:::\n\n\nPanel (b) repeats the calculation across true differences for three\ngroup sizes. Every curve starts at .05 at a true difference of zero,\nwhere a rejection is a Type I error, and rises with the true difference\nand the group size; a smaller outcome SD would raise it too. At 74 per\ngroup, the size chosen for a two-point half-width, power is .5009 at a\ntrue difference of 2 points, about an even chance of rejecting at the\nbenchmark itself, and .8373 at 3 points; doubling to 148 per group\nraises power at 2 points to .7925. Reaching power .8 at 2 points takes\nabout 151 per group (152 with the t reference), roughly twice the\nnumber that precision planning gave. A study has a power curve, not one\npower value, and a sample size chosen for precision is not\nautomatically a power target.\n\nPlanning also needs a plausible spread, allocation, dependence\nstructure, procedure, sidedness, threshold, measurement quality and\nfeasible follow-up. For a class-assigned study, additional randomly assigned classes supply information that more students\nwithin existing classes cannot replace, as the design effect of Section\n2.3 quantifies. If 10% of outcomes are expected to be unavailable\nindependently of relevant outcomes, recruiting at least 83 per group\n($74/.9=82.2222$) gives 74 on average, which neither guarantees\ncomplete data nor repairs bias from selective attrition.\n\n[]{#app-ch03-thousand-studies}\n\nError probabilities describe a rule applied over many studies, not a\nsingle result. Suppose, as stipulated expected counts rather than data,\nthat 900 of 1,000 studies test a true null and 100 test a specified\nalternative, each at $\\alpha=.05$ with power .8 at its alternative\n(@tbl-ch03-thousand).\n\n\\Needspace{8\\baselineskip}\n\n| Model state | Reject | Do not reject | Total |\n|:--|--:|--:|--:|\n| True null | 45 | 855 | 900 |\n| Specified alternative | 80 | 20 | 100 |\n| Total | 125 | 875 | 1,000 |\n\n: Expected decisions under stipulated prevalence, alpha and power. {#tbl-ch03-thousand tbl-colwidths=\"[40,20,20,20]\"}\n\nThe Type I error probability is $45/900=.05$ and the Type II error\nprobability $20/100=.2$, but among the 125 expected rejections,\n$45/125=.36$ come from true nulls. This false-positive fraction has a\ndifferent denominator: it changes with the share of true nulls and with\nthe power, and it is neither an observed p-value nor a probability for\none completed study.\n\n### Choices made after seeing the results {#sec-ch03-selection}\n\nOne analysis can be part of a larger search. A researcher might inspect\nseveral outcomes, subgroups, models, exclusion rules or stopping\npoints, then report the most favorable result. The reported tail area\ncan still be calculated, but a calibration for one advance-specified\ntest does not cover that selection process [@simmons2011]. A report\nshould therefore say which decisions were made before and which after\nthe relevant results were examined. Choosing in advance makes the\nintended comparison and the scope for selection visible; a comparison\nnoticed later can still be informative when its exploratory origin is\nreported with it.\n\nSelection also changes what the retained estimates look like. Consider\na Normal sampling model with true difference 1 point and known SE 2\npoints. A two-sided .05 test of zero using the critical value 1.96\nretains only estimates above 3.92 or below $-3.92$\n(@fig-ch03-selection).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![A significance filter retains both tails of a Normal estimate distribution centered at the true difference of one point, with known SE two points.](chapter_03_files/figure-html/fig-ch03-selection-1.png){#fig-ch03-selection fig-pos='!ht' fig-alt='Normal density centered at one, with a gold line at the true difference labelled above the peak and dashed red lines at minus and plus 3.92. The shaded tails beyond them are labelled: selected estimates below minus 3.92 have the wrong sign, and selected estimates above 3.92 substantially exceed the true effect.' width=652.8}\n:::\n:::\n\n\nThe selected positive estimates are much larger than the truth; the\nselected negative estimates have the wrong sign. The underlying estimand\nstays at one point, while selection changes which estimates are retained.\nThe estimator's original unbiasedness and its interval's unconditional\ncoverage need not hold within this selected set.\n\n[]{#app-ch03-planning}\n\nRunning several tests raises a related problem. Each test at level .05\ncarries its own 5% chance of a false rejection, so five independent\ntests of true nulls have probability $1-.95^5=.2262$ of at least one.\nChapter 4 develops how a declared family of comparisons controls that\nchance.\n\n\\Needspace{16\\baselineskip}\n\n### Report the result with its conditions and scope\n\n| Item | Result |\n|:--|:--|\n| Design and follow-up | 120 consenting students, 60 randomly assigned to each format; all 120 delayed scores observed |\n| Mean difference, Special minus Usual | 3.1 points (27.1 versus 24.0) |\n| Standard error of the difference | 1.1325 points |\n| 95% confidence interval | [0.8572, 5.3428] points |\n| Two-sided test from the same procedure | $t(118)=2.7372$, $p=.0072$ |\n| Benchmark for potential importance | 2 points; fixed before outcome access, course-specific |\n\n: The invented special-practice study and its results. {#tbl-ch03-study-record tbl-colwidths=\"[44,56]\"}\n\nThe table assembles results already developed; the group summaries stay\nin @tbl-ch03-observed. A useful results paragraph explains how they\nrelate, rather than substituting the phrase “Special Practice worked”\nfor the comparison:\n\n> Among the 120 consenting first-year students randomly assigned to\n> Special Practice or Usual Practice, the mean delayed-assessment\n> score was 3.1 points higher under Special Practice (27.1 versus\n> 24.0 on the 0--40 assessment), with an approximate 95% interval\n> from 0.8572 to 5.3428 points and $p=.0072$ for the two-sided test of\n> no difference. The comparison and the two-point benchmark for\n> practical importance were chosen before the outcomes were seen. The\n> interval excludes zero but spans the benchmark, so the direction is\n> well supported while the practical importance of the difference\n> remains unresolved. The result concerns these participants, this\n> assessment two weeks after four sessions, and the equal-variance\n> working procedure; it does not by itself speak to attendance,\n> mechanisms, durable learning, or students elsewhere.\n\nRandom assignment supports the participant comparison, and complete\nfollow-up avoids missing outcomes for this assessment, as\n[the box in Section 5.3](#ch03-justify-equal-variance) records. This\ncombination of estimates, conditions, and scope makes the result\ninterpretable [@appelbaum2018].\n\nSuppose the researchers now replace the primary assessment because a\ndifferent one gives a larger difference. They have changed the outcome\nand selected it after inspection. The report should identify the\noriginal result, the new comparison, the timing and reason for the\nchange, and the analyses considered. The new result can motivate\nfurther work; its ordinary p-value cannot be presented as if it arose\nfrom the original advance-specified procedure.\n\n## Reading Bridge {#sec-ch03-bridge}\n\nThis chapter used a stated repetition to quantify uncertainty about one\nestimate. We specified the estimand and the estimator, named the\nrepetition behind the uncertainty, and calculated standard errors,\npooling two group variances under a common spread. We built confidence\nintervals, read their confidence level, and carried out tests from the\nsame procedure, first for one mean and then for the practice study. The\nt tests formed one family, from one sample through paired scores to two\nindependent groups with equal or unequal spreads, and the same test\nlogic carried over to the association between two categorical\nvariables through expected counts and the chi-square distribution,\nwith a three-way table read as two-way tables within layers. Pairing,\nclustering and the school-blocked\ndesign showed that the units which vary independently, not the count of\nrecords, carry the uncertainty. We closed by reading magnitude, the\nerrors a decision rule can make and the choices made after seeing\nresults together in one qualified conclusion.\n\nChapter 4 compares several groups at once. It extends the pooled\nvariance to several groups as the within-group mean square, splits\nvariation into between-group and within-group parts, forms the F ratio,\nestimates specific contrasts with a calibration for the family of\ncomparisons, and reads main effects and interaction in a two-factor\ndesign. The SE, interval, testing and selection ideas developed here\nwill be used at each step.\n\n### Key terms {.unnumbered}\n\nUse this short reference to revisit the main concepts as needed. The\nPart One Concept Reference gives the broader reference and the\nprincipal home of each concept, including the sampling ideas developed\nin Chapter 2.\n\n```{=latex}\n\\begingroup\\small\n```\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Estimate | A numerical approximation to an estimand, calculated from the available data. A point estimate expresses the approximation as one value. |\n| Estimator | The rule used to calculate an estimate from data. Its bias and precision concern how the rule behaves across the repetitions specified by the study's procedure or model. |\n| Bias (of an estimator) | The difference between an estimator's expected value over the specified repetitions and the estimand. An unbiased estimator has bias zero; precision describes its spread, a separate quality. |\n| Pooled variance ($s_p^2$; pooled within-group variance) | A weighted average of within-group sample variances, each weighted by its degrees of freedom: $s_p^2=\\{(n_1-1)s_1^2+(n_0-1)s_0^2\\}/(n_1+n_0-2)$ for two groups. It estimates a variance the groups are assumed to share; its square root is the pooled SD. |\n| Confidence interval (CI) | An interval expressing uncertainty about an estimand. Under its conditions, the procedure covers that estimand at its stated rate across repetitions; the rate describes the procedure. |\n| Critical value | The cut-point of a reference distribution, such as the Normal or t, selected by a confidence or significance level. It multiplies the SE in an interval and marks the rejection region of a test. |\n| Coverage | The proportion of repetitions in which an interval procedure contains the estimand under its conditions. The confidence level is the procedure's target coverage, not a probability for one realized interval. |\n| Null hypothesis | The statistical proposition used as the reference for a test, such as equality of specified population means. The alternative hypothesis states the departure being considered. |\n| Test statistic | A quantity calculated from data to assess departure from a null hypothesis. The test compares it with a reference distribution justified under that null and stated conditions. |\n| p-value | Under a specified null hypothesis and conditions, the probability of a test result at least as extreme as the observed one, using the test's stated tail rule. |\n| Significance level (alpha) | The threshold used for rejecting a null hypothesis, chosen to control the probability of rejecting a true null under the test's conditions. This error is called a Type I error. |\n| One-sample z test; one-sample t test | Both compare a sample mean with a stated null mean using its SE; z uses a known process SD under its model, whereas t estimates that SD and uses the appropriate t reference. Neither choice follows an automatic sample-size cutoff. |\n| Paired-samples t test | A one-sample t test of within-pair differences against a specified mean difference, with independent pairs under the stated model. |\n| Equal-variance two-sample t test (pooled t test; Student's two-sample t test) | One of the two independent-samples t tests. It compares two independent group means under the condition that the populations share one variance: its SE is $s_p\\sqrt{1/n_1+1/n_0}$, and its reference is t with $n_1+n_0-2$ df. |\n| Welch's unequal-variance t test (Welch test) | The other independent-samples t test. It compares two independent group means without assuming a common variance: its SE adds the two estimated mean variances, and its approximate t reference uses Welch--Satterthwaite df. With equal group sizes its statistic equals the equal-variance statistic, and only the df can differ. |\n| Expected count | The count a cell of a two-way table would have under a stated null pattern such as independence, given the observed margins: row total times column total, divided by the overall total. |\n| Pearson's chi-square statistic ($X^2$) | The sum over cells of squared differences between observed and expected counts, each divided by its expected count, compared with a chi-square reference with $(R-1)(C-1)$ degrees of freedom under the stated model. |\n| Multiway table (three-way table; layered two-way tables) | A table that cross-classifies three or more categorical variables: a two-way table holds two variables, a three-way table three, and a four-way table four. A three-way table is read as two-way tables within the layers of the third variable; a chi-square test of one two-way table cannot test the variables jointly, which needs a method that uses all three variables at once, such as a model for multiway tables. |\n| Standardized mean difference | A difference in means divided by a specified SD. The chosen denominator determines the standardized quantity; the raw difference retains the outcome's original units. |\n| Power (statistical power) | The probability of rejecting the null under a specified alternative, design, and test. Failure to reject under that alternative is a Type II error; power is one minus its probability. |\n\n: Selected concepts for estimates, uncertainty, and tests. {#tbl-ch03-key-terms tbl-colwidths=\"[28,72]\"}\n\n```{=latex}\n\\endgroup\n```\n\n### Further reading {.unnumbered}\n\nThe GAISE College Report emphasizes statistical investigation,\nconceptual understanding, and interpretation [@asa2016gaise].\n*Introduction to Modern Statistics* develops inference through\nrepetition, with separate treatments of paired means and two-way\ntables [@cetinkaya2024]. [Penn State STAT 200, Lesson 4](https://online.stat.psu.edu/stat200/Lesson04)\nconnects interval construction with its interpretation. The ASA\np-value statement [@wasserstein2016] and [Moving to a World Beyond\n$p<.05$](https://doi.org/10.1080/00031305.2019.1583913) explain why\nuncertainty and context deserve more attention than a threshold label.\n\n\n## Exercises {.unnumbered}\n\nThese exercises use the information supplied and a standard calculator. They practise interpretation, the reading of the chapter's figures and tables, and the conditions behind a conclusion, with a short calculation where the reasoning needs it.\n\n<!-- prompt-id: CH03-E01 -->\n### Exercise 1: Name the inferential objects (Foundational) {.unnumbered #ex-ch03-01}\n\nA report states:\n\n> The estimand was the mean Special-minus-Usual assignment contrast in\n> delayed-assessment score among the 120 randomized participants. In every\n> admissible repetition, the analyst would subtract the Usual assigned-group\n> mean from the Special assigned-group mean. The observed difference was\n> 3.1 points, with an estimated standard error of 1.1325 points.\n\nIdentify:\n\n1. the estimand;\n2. the estimator;\n3. the estimation process;\n4. the estimate and one statistic used in obtaining it;\n5. the standard error and what varies in its repeated-process interpretation;\n6. the parameter; and\n7. two bounds that must remain in the answer.\n\nExplain why the estimate and the parameter should not be given the same label.\n\n\\Needspace{6\\baselineskip}\n\\phantomsection\n\n<!-- prompt-id: CH03-E02 -->\n### Exercise 2: Match the SE to the unit of assignment (Foundational) {.unnumbered #ex-ch03-02}\n\nAn invented first-year course compared Special and Usual Practice on a common\n0--40 assessment taken two weeks after four practice sessions. Its 120\nstudents belonged to six tutorial classes of 20. The course randomly\nassigned whole classes, three to each format, so every student\npractised in the format given to their class. Each format therefore\nhas 60 students. The Special and Usual Practice means are 27.1 and\n24.0 points, a difference of 3.1 points, and their delayed-score\nSDs are 6.0 and 6.4 points. The three Special Practice classes had\nmeans of 29.4, 26.6 and 25.3 points; the three Usual Practice classes\nhad means of 26.3, 24.2 and 21.5 points.\n\nAn analyst proposes this SE for the Special-minus-Usual difference,\n\n$$\n\\widehat{SE}=\\sqrt{\\frac{s_1^2}{n_1}+\\frac{s_0^2}{n_0}},\n$$\n\nwith $n_1=n_0=60$ students.\n\n1. What changed from assigning students one at a time? Name the\n   independent units of assignment, and explain whether the proposed\n   SE describes the uncertainty of the Special-minus-Usual difference\n   under this design. Does the change affect the estimate, its SE, or\n   both?\n2. With these inputs the proposed SE is 1.1325 points. How many units\n   of assignment does this calculation assume, and what would have to\n   be true of the students' scores for it to describe the uncertainty\n   under class assignment?\n3. Treat each class mean as one observation. The SDs of the three\n   class means are 2.0952 points for Special Practice and 2.4062 points\n   for Usual Practice. Calculate the SE from the same formula with\n   $n_1=n_0=3$ classes and compare it with 1.1325 points. On a t\n   reference with 4 df, the 95% interval for the difference is\n   $[-2.0145,\\ 8.2145]$. Which conclusion about Special Practice\n   remains supported?\n4. Which quantities describe variation among students' scores, which\n   describe variation among class means, and which estimates variation\n   of the mean difference across possible assignments of the classes?\n\n\\Needspace{6\\baselineskip}\n\\phantomsection\n\n<!-- prompt-id: CH03-E03 -->\n### Exercise 3: Interpret interval coverage (Foundational) {.unnumbered #ex-ch03-03}\n\nA student writes:\n\n> The 95% confidence interval [0.8572, 5.3428] means there is a 95%\n> probability that the true mean assignment effect lies between\n> 0.8572 and 5.3428 points. If the method is valid, every 95%\n> interval should contain the true effect.\n\nRewrite the statement using repeated-procedure language. Then:\n\n1. The coverage figure in Section 3.2 draws the same 40 district\n   samples twice: at 95%, 38 of the 40 intervals cover the fixed\n   population mean; at 90%, 36 do. Explain why more intervals miss\n   at 90% although no sample changed, and why one study cannot tell\n   whether its own interval is one of the misses.\n2. Explain what the endpoints contribute to reading this study.\n3. Name three sources of uncertainty or bias that the conventional\n   interval may omit.\n\n\\Needspace{6\\baselineskip}\n\\phantomsection\n\n<!-- prompt-id: CH03-E04 -->\n### Exercise 4: Translate a p-value (Foundational) {.unnumbered #ex-ch03-04}\n\nFor the matching two-sided zero-contrast test, *t*(118) = 2.7372 and\n*p* = .0072. Consider four interpretations:\n\nA. There is a 0.72% probability that the null hypothesis is true.\n\nB. There is a 99.28% probability that Special Practice will work again.\n\nC. Under the zero-contrast null model and the stated procedure, results at\nleast as incompatible as the observed one have probability about .0072.\n\nD. The 3.1-point effect is educationally important because *p* = .0072.\n\nChoose the defensible interpretation and diagnose each rejected one.\nThen:\n\n1. Section 4.4 re-assigns the 120 students' scores at random to two\n   groups of 60, 10,000 times, supposing that no student's score\n   depends on format; 77 re-assignments give a difference at least 3.1\n   points from zero.\n   State what the re-assignments held fixed and what they re-drew,\n   and what the share 77/10,000 = .0077 estimates.\n2. Explain why .0077 is close to, but need not equal, the t test's\n   *p* = .0072.\n3. The 95% interval from the same procedure as the t test is\n   [0.8572, 5.3428]. Explain why its exclusion of zero agrees with\n   the two-sided *p* < .05 result, without implying exact\n   randomization calibration.\n4. Write one sentence reporting estimate, interval, and p-value\n   without using **prove**, **accept**, or **worked**.\n\nNo calculation is needed; the tail areas and the interval are\nsupplied.\n\n\\Needspace{6\\baselineskip}\n\\phantomsection\n\n<!-- prompt-id: CH03-E05 -->\n### Exercise 5: Interpret one published active-learning result (Integrative) {.unnumbered #ex-ch03-05}\n\nDeslauriers and colleagues (2019) used a randomized crossover study in introductory\ncollege physics: students were randomly assigned to two groups, and each\ngroup experienced both instructional conditions in successive class meetings,\nin opposite orders. In a regression model, performance on a test of learning was\n0.46 SD higher under active instruction than under passive instruction,\n*p* < .001. The brief result supplied here does not report a confidence\ninterval [@deslauriers2019].\n\nUse the supplied description to:\n\n1. mark the participant set, condition contrast, outcome, estimate, units,\n   p-value, and design;\n2. explain what the estimate and p-value each tell you;\n3. identify the information supplied and what else would help you understand\n   the result; and\n4. state a bounded one-sentence version of the reported answer.\n\nThen explain which design and analysis details would help judge the uncertainty\ncalculation and scope. State what further information you would seek in the\nMethods or supplement and name one broader claim this excerpt cannot support.\n\n\n\n\\Needspace{6\\baselineskip}\n\\phantomsection\n\n<!-- prompt-id: CH03-E06 -->\n### Exercise 6: Repair the special-practice conclusion (Integrative) {.unnumbered #ex-ch03-06}\n\nRewrite:\n\n> Special Practice worked, *p* < .05.\n\nUse this study record (the same one summarized in the chapter's study-and-results table):\n120 consenting students in one course were randomly assigned, 60 per group,\nto four sessions of Special or Usual Practice with equal total study time.\nAll completed a common 0--40 assessment two weeks later. Special had mean\n27.1 (SD 6.0), and Usual had mean 24.0 (SD 6.4). The prespecified primary\ncomparison gave 3.1 points, 95% CI [0.8572, 5.3428], approximate equal-variance\n*t*(118) = 2.7372, *p* = .0072. Before outcome access, the protocol specified\nthe two-point benchmark as potentially important: the course team treated two\npoints as the smallest average difference that would change its recommendation,\nbecause the marking scheme awards two points to one completed application task\nand the new format would add little preparation time. Your revision must\nretain:\n\n1. the participant set and assignment comparison;\n2. the outcome, time, direction, and raw units;\n3. the estimate and 95% interval;\n4. the reported numerical p-value only after the estimate and interval;\n5. the choice of the primary comparison before outcome access;\n6. what random assignment and complete follow-up support;\n7. the interval's relation to the prespecified, course-specific two-point\n   benchmark for potential importance;\n   and\n8. at least three scope boundaries.\n\nAfter the rewrite, choose three phrases and explain what each repairs in the\noriginal sentence.\n\nAfter viewing the outcomes, the researchers decide that a different assessment\nshould replace the planned assessment as primary because it gives a larger\ndifference. Explain how this changes the comparison and its interpretation.\nState what information should be reported about the original and new analyses,\nwhat advance-planning claim can no longer be made, and why the new assessment's\np-value cannot be read as if that assessment had been chosen before inspection.\n\n<!-- prompt-id: CH03-E07 -->\n### Exercise 7: Check expected counts and a chi-square result (Foundational) {.unnumbered #ex-ch03-07}\n\nAn invented study records participation format and completion. It is\ndistinct from the UCI student data.\n\n| Participation format | Completed | Did not complete | Total |\n|:--|--:|--:|--:|\n| Online | 84 | 36 | 120 |\n| In person | 63 | 17 | 80 |\n| Total | 147 | 53 | 200 |\n\n: Participation-format outcomes for Exercise 7. {#tbl-ch03-ex07-counts tbl-colwidths=\"[34,22,28,16]\"}\n\nThe expected counts under independence are 88.2, 31.8, 58.8,\nand 21.2.\nThe Online/Completed contribution is $(84-88.2)^2/88.2=0.2$; the\nfour contributions (0.2000, 0.5547, 0.3000, 0.8321) sum to\n$X^2=1.8868$ on $(2-1)(2-1)=1$ df, giving $p=.1696$.\nReport calculated results to four decimal places. The completion proportions are\n$84/120=.7000$ and $63/80=.7875$.\n\n1. Explain what the Online/Completed expected count, 88.2,\n   represents, using the overall completion proportion\n   $147/200=.735$ and the 120 online learners, and why the table has\n   one degree of freedom.\n2. Identify the cells in which the observed count exceeds the expected count.\n3. State the omnibus null in words.\n4. Write one conclusion that distinguishes the observed proportion\n   difference, evidence against independence, association magnitude,\n   and causation, and explain why $p=.1696$ is not proof that format\n   and completion are independent.\n5. Suppose every count were doubled, so that the completion\n   proportions stay .7000 and .7875. Predict what happens to the\n   expected counts, to each cell's contribution, to $X^2$ and to the\n   proportion difference, then check your prediction against\n   $X^2(1)=3.7736$, $p=.0521$ for the doubled table. What does this\n   say about reading $X^2$ or its p-value as the strength of an\n   association?\n6. Suppose the same 200 learners had also been recorded as working or\n   not working while they studied (@tbl-ch03-ex07-layers, invented).\n   Compare the two formats' completion proportions within each layer\n   with the added table's .7000 and .7875, and explain why the added\n   In-person-minus-Online difference, .0875, is larger than both layer\n   differences. Then name one question about format, completion and\n   work that no chi-square test of a single two-way table in the\n   display can answer.\n\n\\Needspace{12\\baselineskip}\n\n| Work while studying | Participation format | Completed | Did not complete | Total | Completion proportion |\n|:--|:--|--:|--:|--:|--:|\n| Working | Online | 52 | 28 | 80 | .6500 |\n|  | In person | 14 | 6 | 20 | .7000 |\n| Not working | Online | 32 | 8 | 40 | .8000 |\n|  | In person | 49 | 11 | 60 | .8167 |\n\n: Invented counts of completion by participation format within two layers of work while studying, for Exercise 7's 200 learners. {#tbl-ch03-ex07-layers tbl-colwidths=\"[25,19,15,16,9,16]\"}\n\n\n## Appendix A: Probability and Repetition Foundations {.unnumbered #app-probability}\n\nThis appendix derives two results behind the chapter's uncertainty\ncalculations, each for its stated repetition: drawing observations from\na model, or reassigning the same participants.\n\n### Variance, sample variance, and least squares {.unnumbered #app-ch03-variance}\n\nThe variance of a random variable is its expected squared distance from\nits expectation: $\\operatorname{Var}(Y)=E\\{(Y-E(Y))^2\\}$. For fixed\nweights $a_i$ and observations with finite second moments,\n\n$$\n\\operatorname{Var}\\left(\\sum_i a_iY_i\\right)\n=\\sum_i a_i^2\\operatorname{Var}(Y_i)\n+2\\sum_{i<j}a_ia_j\\operatorname{Cov}(Y_i,Y_j).\n$$\n\nHere covariance is the expected product of two centered observations,\nand $i<j$ includes each distinct pair once. Expanding the square of the\nweighted sum gives the squared terms and the cross-products in this\nidentity. For an average, every weight is $1/n$; independent\nobservations have zero covariance, so with common variance $\\sigma^2$\nthe expression becomes $n\\sigma^2/n^2=\\sigma^2/n$. For a difference,\nweights $1$ and $-1$ instead give\n$\\operatorname{Var}(U)+\\operatorname{Var}(V)-2\\operatorname{Cov}(U,V)$.\nThese two applications explain the mean, independent-group, and\npaired-difference calculations, and the covariance terms are those\nSection 2.3 uses for pairing, clustering and the design effect.\n\nEstimating $\\sigma^2$ uses the sample variance\n$s^2=\\sum_i(Y_i-\\bar Y)^2/(n-1)$. For independent observations with\ncommon mean $\\mu$ and variance $\\sigma^2$,\n\n$$\n\\sum_i(Y_i-\\bar Y)^2=\\sum_i(Y_i-\\mu)^2-n(\\bar Y-\\mu)^2 .\n$$\n\nThe first term on the right has expectation $n\\sigma^2$ and the second\n$n(\\sigma^2/n)=\\sigma^2$, so $E(s^2)=(n\\sigma^2-\\sigma^2)/(n-1)=\\sigma^2$.\nFor the values 2, 4 and 6 the mean is 4 and the squared deviations sum\nto 8, so $s^2=8/2=4.0000$, whereas dividing by 3 gives 2.6667.\nNormality is unnecessary for this result, and an unbiased $s^2$ does not\nmake $s$ unbiased for $\\sigma$. The same algebra with observed values\nand any proposed center $a$ gives\n\n$$\n\\sum_i(y_i-a)^2=\\sum_i(y_i-\\bar y)^2+n(\\bar y-a)^2 ,\n$$\n\nwhose last term is nonnegative and vanishes at $a=\\bar y$: the mean\nminimizes the sum of squared deviations, the **least-squares** property\nChapter 2 states.\n\n### Random assignment and the familiar SE {.unnumbered #app-ch03-assignment}\n\nFor the fixed $N=120$ Special Practice participants, let $S_1^2$ and\n$S_0^2$ be the potential-outcome variances under the two assignments,\nwith divisor $N-1$. Let $S_{\\mathrm{eff}}^2$ be the variance of the\nindividual effects $Y_{i1}-Y_{i0}$, using the same divisor. Under\ncomplete random assignment of $n_1$ and $n_0$ participants, consistent\nconditions and no relevant interference [@bai2024],\n\n$$\n\\operatorname{Var}_{\\mathrm{assign}}(\\bar Y_1-\\bar Y_0)\n=\\frac{S_1^2}{n_1}+\\frac{S_0^2}{n_0}-\\frac{S_{\\mathrm{eff}}^2}{N},\n\\qquad\nE_{\\mathrm{assign}}\\left(\\frac{s_1^2}{n_1}+\\frac{s_0^2}{n_0}\\right)\n=\\operatorname{Var}_{\\mathrm{assign}}(\\bar Y_1-\\bar Y_0)+\\frac{S_{\\mathrm{eff}}^2}{N}.\n$$\n\nOnly one potential outcome is observed per participant, so the\nindividual-effect variance is unidentified. The familiar summed\nvariance is therefore conservative in expectation under this\ncomplete-assignment design, with equality when individual effects are\nconstant; with equal group sizes it equals the pooled squared SE of\nSection 2.2. A particular estimate need not be too large, and the\nproperty does not by itself make the equal-variance or Welch t reference\nexact or ensure conservative finite-sample coverage.\n\nA zero average effect allows positive and negative individual effects\nto cancel, whereas the stronger **sharp null** says that every\nparticipant's effect is zero. The re-assignments of Section 4.4 test\nthat sharp null by reproducing the actual assignment mechanism, so\ntheir reference owes nothing to a Normal or t model.\n\n## Appendix B: Inferential Extensions {.unnumbered #app-procedures}\n\nThis appendix gathers two references for the chapter's procedures: a\ntable of their conditions and the steps of a bootstrap, which the\nchecks of the procedures call on.\n\n### Procedures and their conditions {.unnumbered #app-ch03-procedure-guide}\n\n@tbl-ch03-procedures collects the five procedures of Sections 5 and 6\nwith the conditions each relies on, the evidence that checks them and the\nresponse when a condition fails. Each procedure's choices and defaults\nstay with its *Justifying the analysis* box, because they vary with the\nstudy rather than the procedure.\n\n```{=latex}\n\\begingroup\\footnotesize\n```\n\n| Procedure and target | Secured by design | Model assumptions and how to check them | If a condition fails | Main explanation |\n|:--|:--|:--|:--|:--|\n| One-sample t test: the mean $\\mu$ of the sampled population, in outcome units, compared with a stated null value | Random sampling from the named population; independent units, each measured once | A Normal population gives an exact t reference; otherwise the sample mean needs a near-Normal sampling distribution. Look for strong skew, heavy tails or one dominating value in the scores; no sample-size cutoff settles the question | Dependent units: an SE that represents the pairs or clusters (Ch. 3, Sec. 2.3). Strong skew with few units: disclose the weaker approximation and compare a bootstrap interval (Ch. 3, App. B). Without random sampling, a population reading needs a stated model | Ch. 3, Sec. 5.1 |\n| Paired-samples t test: the mean within-pair difference $\\mu_D$, in outcome units, with the subtraction direction stated | Pairs formed by the design, such as one student measured twice or two classes in one school; independent pairs. Random assignment within pairs supports a causal reading | Near-Normal pair differences give the t reference: inspect the differences themselves rather than the two sets of scores; a few pairs say little about shape | Ignoring the pairing: an independent-groups analysis omits the within-pair covariance and misstates the SE (Ch. 3, Sec. 5.2). No untreated comparison: a mean change alone cannot be separated from time trends or repeated testing. Skewed differences: resample whole pairs (Ch. 3, App. B) | Ch. 3, Sec. 5.2 |\n| Equal-variance two-sample t test: a difference between two means, in outcome units, either a mean assignment effect over the participants or a difference between two populations' means | Random assignment of individuals, supporting a causal comparison among the participants, or two independent random samples; different units in the two groups | One common population variance and a near-Normal sampling distribution of the difference: compare the group SDs with the group sizes and look for skew or dominating values in each group. After random assignment the t reference is approximate. No interference between units is argued from the setting; the data cannot check it | Unequal spreads with unequal group sizes: the pooled SE is too small when the smaller group varies more, so choose Welch's t in advance from the design (Ch. 3, Sec. 5.4), not from a preliminary variance test. With equal group sizes the two SEs coincide | Ch. 3, Sec. 5.3 |\n| Welch's unequal-variance t test: a difference between two means, in outcome units, when the two groups' variances may differ | Two independent random samples or randomly assigned groups, with different units in each group | No common variance is assumed. Each group mean needs a near-Normal sampling distribution, and the Welch--Satterthwaite df approximate the reference: inspect each group's distribution, especially the smaller group's | Skew or a dominating value in a small group: disclose the weaker approximation and compare a bootstrap that resamples within each group (Ch. 3, App. B). Paired or clustered units: an SE that represents them (Ch. 3, Sec. 2.3) | Ch. 3, Sec. 5.4 |\n| Pearson chi-square test of association: whether two categorical variables are associated in the stipulated population or process, against the null of no association (independence); conditional proportions give the direction and size | Independent sampling of units, each counted once in one of mutually exclusive categories | Adequate expected counts for the chi-square approximation: calculate every expected count, row total times column total divided by $n$, before reading the p-value | Small expected counts: an exact conditional test such as Fisher's (Ch. 6, Sec. 4). Repeated or clustered records: the counts overstate the independent information. An observed rather than assigned grouping supports association only | Ch. 3, Sec. 6 |\n\n: Procedures and their conditions. {#tbl-ch03-procedures tbl-colwidths=\"[17,15,26,27,15]\"}\n\n```{=latex}\n\\endgroup\n```\n\n### Resampling and uncertainty {.unnumbered #app-ch03-resampling}\n\nA **bootstrap distribution** approximates an estimator's variability by\nrepeatedly resampling from observed data. Its center is usually near the\nobserved estimate. In a simple case bootstrap for independent observations:\n\n1. Identify the independent observational unit and the original number of units.\n2. Draw that many units with replacement from the observed units.\n3. Apply the same estimator to the resampled data.\n4. Repeat the resampling and estimation many times.\n5. Use the distribution of estimates to examine variability or construct an appropriate interval.\n\nThe bootstrap SE is the sample SD of the resulting estimates. It is\ndistinct from the SD of individual observations and from the uncertainty\ncaused by using only finitely many simulation repetitions. Preserve the\nstudy structure: resample pairs together, or clusters when independent\nclusters are the appropriate units. Resampling individual students from\nclustered classes can misrepresent uncertainty, and the number\nresampled is the observed unit count. As Section 4.4 explains, a\nbootstrap distribution centered near the estimate is not a reference\nfor testing zero, and resampling cannot recover unobserved cases or\nrepair biased selection, invalid measurement, or an unsuitable estimand.\n\n## References {.unnumbered}\n\n\\small\n\n::: {#refs}\n:::\n\n\\normalsize\n",
    "supporting": [
      "chapter_03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}