{
  "hash": "9ba15d2f945b58ca3c227c07f5734b83",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression Pitfalls and Causal Design\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    latex-auto-install: false\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{16\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nA correct regression calculation can support an incorrect research claim.\nThis chapter connects adjustment, composition, selection, measurement and\ndependence with the comparison each analysis actually makes. Generated\nstudies reveal mechanisms with known truth; Berkeley admissions,\noccupation records and Project STAR show what the same questions mean in\nreal evidence. By the end, you can choose an estimand, explain when\nadjustment helps or harms, recognize a change of unit or population, and\nwrite a claim that respects the design and the uncertainty. The chapter\nteaches how to audit a claim; it introduces causal-design vocabulary\nwithout supplying an advanced causal estimator.\n:::\n\nIn the autumn of 1973 the six largest graduate departments at the\nUniversity of California, Berkeley, returned decisions to 4,526\napplicants. Among the 2,691 men, 1,198 were admitted, a rate of\n44.5188 percent; among the 1,835 women, 557 were admitted, a rate of\n30.3542 percent. A gap of 14.1645 percentage points on more than four\nthousand decisions is not a rounding artifact, and a logistic\nregression of admission on applicant gender returns a coefficient\nmany standard errors from zero. Now add one column that was in the\nfile all along: the department applied to. Four of the six\ndepartments admitted women at a higher rate than men, the two\nexceptions differed little, and the same regression with department\nincluded moves the gender coefficient to the other side of zero with\nan interval that comfortably contains equality. Both calculations are\ncorrect, and they are not contradictory, because they answer\ndifferent questions: one describes the applicant pool as it was\ncomposed, in which men and women applied to very differently\nselective departments, and the other describes applicants within a\ndepartment. Neither is by itself an account of how the decisions were\nmade; the original authors said so explicitly [@bickel1975]. This\nchapter is about the distance between a number that is correct and a\nclaim that is credible: what comparison did this model make, who was\nin it, what was measured, how many analyses were tried, and does the\nfinal sentence describe that comparison or a more attractive one?\n\n## Credibility Is Alignment {#ch14-alignment}\n\n### Six commitments that must line up\n\nA quantitative claim rests on a chain of commitments and is credible\nonly when they agree. The failures in this chapter are misalignments,\nnot computational errors: the regression runs, the standard errors\nprint, and nothing in the output announces that the quantity named in\nthe introduction and the quantity the model computed differ.\n\n| Element | Question it answers |\n|:--|:--|\n| Research question | What do we want to know, and in what mode: descriptive, associational, predictive, or causal? |\n| Estimand | What quantity, for which units and conditions, would answer that question? |\n| Design | How were units produced, selected, observed, assigned, and retained? |\n| Data | Which rows and columns survive into the analysis, and what do they measure? |\n| Model | What comparison does the fitted specification actually compute? |\n| Claim | What sentence is written at the end, and how far does it reach? |\n\n: The six commitments behind a credible claim. {#tbl-ch14-commitments tbl-colwidths=\"[24,76]\"}\n\nThree habits keep them aligned, and none of them is a diagnostic plot.\nName the estimand in words before fitting anything [@lundberg2021].\nDescribe the comparison the model makes in one sentence that names the\nunit, the contrast, and what is held fixed. Then check that the\nconcluding sentence uses no verb the design cannot support.\n\n### Pooled, within-group, and between-group comparisons\n\nLet $Y$ be an outcome, $X$ a focal predictor, and $Z$ a grouping or\nadjustment variable. Three quantities recur in this chapter and are\ndifferent: pooling mixes groups, conditioning compares within them,\nand aggregation makes the groups themselves the rows.\n\n$$\n\\Delta\\mu_{\\mathrm{pooled}}=E(Y\\mid X=x+1)-E(Y\\mid X=x),\n$$\n\n$$\n\\Delta\\mu_{\\mathrm{within}}(z)=E(Y\\mid X=x+1, Z=z)-E(Y\\mid X=x, Z=z),\n$$\n\n$$\n\\Delta\\mu_{\\mathrm{between}}=E(\\bar Y_z\\mid \\bar X_z=x+1)\n-E(\\bar Y_z\\mid \\bar X_z=x).\n$$\n\nThe first averages over whatever mixture of $Z$ the data contain. The\nsecond removes that mixture, and an additive regression including $Z$\nestimates a common value when the stratum-specific comparisons are\nsimilar. The third changes the unit of analysis, since its rows are\ngroups, and can take any sign relative to the other two. Section 3.3\nadds a fourth, the **standardized** comparison, which reweights the\nstratum-specific comparisons by a declared common distribution of $Z$.\n\nA **strict Simpson reversal** occurs when the pooled comparison and\nevery stratified comparison point in opposite directions [@simpson1951;\n@yule1903]. The broader **aggregation reversal** also covers a sign\nchange between a pooled comparison and an adjusted or standardized\nsummary when the stratum-specific comparisons are heterogeneous. Nothing\nparadoxical has happened: composition changes the weights and, usually,\nthe quantity estimated. Section 3.1's tutoring reversal is strict;\nSection 3.3's Berkeley reversal is the broader kind.\n\n### Four modes of claim and their verbs\n\nChapters 1 and 7 introduced the typology of questions. It returns here\nas the vocabulary of the final audit, because most overclaiming is a\nsilent change of mode between the analysis and the conclusion.\n\n| Mode | Legitimate verbs | What the design must supply |\n|:--|:--|:--|\n| Descriptive | is, was, differed, ranged | A defined population and unit, and data that represent them |\n| Associational | is associated with, differs by, tends to be higher among | Defined units, measurements, conditioning set and observed support |\n| Predictive | predicts, forecasts, is expected to be | Predictors available at the intended decision time and an honest held-out performance estimate for the named deployment population (Chapter 13) [@shmueli2010] |\n| Causal | causes, raises, reduces, would change | A defined intervention and target population, with assignment or an identification argument under explicit, defensible assumptions [@shadish2002] |\n\n: Four modes of claim, their verbs, and what each requires. {#tbl-ch14-modes tbl-colwidths=\"[14,30,56]\"}\n\nThe verbs are not decoration. \"Pupils who received more tutoring\nscored lower\" and \"tutoring lowered scores\" are different claims, and\nthe same regression output can be made to look like support for\neither. A reader who has only the output cannot tell which claim was\nintended; a reader who has the estimand, the design and the\nconditioning set can.\n\n## Adjustment: Confounders, Mediators, and Colliders {#ch14-adjustment}\n\n### A diagram records assumptions\n\nTo decide whether conditioning on $Z$ helps, something must be assumed\nabout how $X$, $Y$ and $Z$ were produced. The minimum vocabulary is\nthree structures, drawn as a **directed acyclic graph**: an arrow means\n\"is a direct cause of\", and no directed path returns to its starting point\n[@pearl2009]. A **confounder** $Z$ causes both $X$ and $Y$, so leaving\nit out mixes the direct path with the back-door path through $Z$ and\nadjusting removes that mixture. A **mediator** $M$ lies on a causal path from $X$ to $Y$, so\nconditioning on it blocks that pathway in a total-effect comparison.\nA mediator is one kind of **post-treatment variable**. The broader term\nalso includes consequences of treatment that do not mediate its effect,\nincluding the collider in the next example; timing alone does not\nidentify a variable's causal role. A\n**collider** $C$ is caused by both $X$ and an unmeasured $U$ that also\ncauses $Y$; the path through $C$ is blocked while $C$ is left alone, and\nconditioning on it opens that path, creating an $X$-$U$ association that\ndid not exist [@elwert2014]. The practical rule reverses \"adjust for\neverything available\": choose the adjustment set for the stated estimand\nfrom an explicit structure. Pre-treatment common causes are usually\nneeded; for a total-effect target, mediators and colliders are not.\nTiming rules out some roles without settling any\n[@vanderweele2019; @pearl2009], which is why measurement timing and\nthe assumed structure belong in the data audit.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Three minimal causal structures. $\\textbf{(a)}$ A common cause $Z$ of the focal predictor $X$ and the outcome $Y$. $\\textbf{(b)}$ A mediator $M$ lying on a causal path from $X$ to $Y$. $\\textbf{(c)}$ A collider $C$ influenced by $X$ and by an unmeasured variable $U$ that also influences $Y$.](chapter_14_files/figure-html/fig-ch14-structures-1.png){#fig-ch14-structures fig-pos='H' fig-alt='Three small node-and-arrow diagrams. In the first, an upper node Z sends arrows down to X on the left and Y on the right, and X also sends an arrow to Y. In the second, X sends an arrow to M above and to Y, and M sends an arrow to Y. In the third, X and an unmeasured node U both send arrows into a lower node C, U also sends an arrow to Y, and X sends an arrow to Y.' width=100%}\n:::\n:::\n\n\n::: {.callout-note title=\"What a diagram is and is not\"}\nA diagram of this kind records assumptions. It is not evidence, it is\nnot produced by the data, and drawing one does not make an\nobservational comparison causal. Its value is that it makes the\nadjustment decision arguable in public: a reader can dispute an\narrow, and cannot dispute an unstated intuition.\n:::\n\n### Adjusting for a mediator on a randomized programme\n\n\n\n\n\n\nBoth examples in this section randomize assignment. The particular\npost-treatment variables considered here change or distort the total-effect\ncomparison; this is not a claim that adjustment for baseline predictors\nis harmful in randomized studies. A\ndistrict randomizes 600 pupils to a study-skills programme, which raises\nhomework completion, which raises achievement; a direct pathway does not\nrun through homework.\n\n$$\n\\begin{aligned}\n\\text{program}_i &\\sim \\text{Bernoulli}(.5),\\\\\n\\text{homework}_i &= 6+2\\,\\text{program}_i+u_i,\n&& u_i\\sim\\text{Normal}(0, 2^2),\\\\\n\\text{achievement}_i &= 50+3\\,\\text{program}_i\n+2.5\\,\\text{homework}_i+\\varepsilon_i,\n&& \\varepsilon_i\\sim\\text{Normal}(0, 5^2).\n\\end{aligned}\n$$\n\nThe total effect is the direct path plus the indirect path,\n$3+2.5\\times2=8$ points; the direct effect, holding homework\nfixed, is 3. These are two estimands, and the question decides which\nmatters: a district deciding whether to fund the programme wants the\ntotal effect. With seed 14007 the unadjusted regression gives 8.0198\n[6.8566, 9.1830] and the regression adding homework gives 3.066\n[2.1023, 4.0297]. Both are correct. If the report asks whether the\nprogramme raises achievement and by how much, the adjusted model answers\na question nobody asked and understates the total by more than half.\nNothing in the coefficient table warns of this; the clue is temporal,\nbecause homework completion follows randomization and is a consequence\nof the programme.\n\n::: {.callout-warning title=\"The most common version of this mistake\"}\n\"We controlled for baseline motivation, homework, attendance and\nengagement to isolate the effect of the programme.\" If the programme\nchanged any of those variables, they are post-treatment and the\nresulting coefficient is not the programme's total effect. Adding\ncovariates is not automatically conservative.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(achievement ~ program, data = med)\nlm(achievement ~ program + homework, data = med)\n```\n:::\n\n\n\n\n\n**Change one assumption: family support also affects homework and achievement.**\nThe original recipe makes the homework and achievement disturbances\nindependent. Now keep its 600 assignments and both error draws, and add\nan independent pre-programme support variable $S_i\\sim\\mathrm{Normal}(0,1)$,\ndrawn under seed 14016:\n\n$$\n\\begin{aligned}\n\\text{homework}_i &= 6+2\\,\\text{program}_i+2S_i+u_i,\\\\\n\\text{achievement}_i &= 50+3\\,\\text{program}_i+\n  2.5\\,\\text{homework}_i+4S_i+\\varepsilon_i.\n\\end{aligned}\n$$\n\nThe programme still has total effect 8 and direct effect 3 in this\ngenerated process. Before looking at the estimates, predict which\ncomparison remains supported by random assignment. Assignment makes\nprogramme independent of support, but it does not randomize homework.\nAmong pupils with the same homework amount, programme participation can\ngo together with less support; support also affects achievement.\nHolding homework fixed therefore opens a noncausal path unless support\nis adequately controlled.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The same programme pathway with and without a common cause of homework and achievement. In the second diagram, holding homework fixed opens the programme--support path through homework; adjusting for measured support blocks that path under the stated recipe.](chapter_14_files/figure-html/fig-ch14-mediator-change-1.png){#fig-ch14-mediator-change fig-pos='H' fig-alt='Two causal diagrams both show programme causing homework and achievement, and homework causing achievement. The second adds family support with arrows into both homework and achievement. Programme has no arrow to support.' width=672}\n:::\n:::\n\n\n| Fitted programme comparison | Original independent disturbances | Added common cause |\n|:--|--:|--:|\n| Programme only: total effect target | 8.0198 | 8.4296 |\n| Programme and homework | 3.0660 | 1.1101 |\n| Programme, homework and support | -- | 3.0659 |\n\n: Changing mediator--outcome confounding while retaining random programme assignment. {#tbl-ch14-mediator-change tbl-colwidths=\"[46,27,27]\"}\n\nThe changed recipe's unadjusted interval is [6.5256, 10.3335]. Its\nhomework-adjusted interval is [0.0856, 2.1345], excluding the known direct\neffect 3. Adding the accurately observed support variable gives\n[2.1014, 4.0304]. Randomization continues to justify the total-effect\ncomparison in repeated assignments; it does not guarantee an exact\nsample estimate or identify a direct effect after arbitrary adjustment.\nThe repaired direct reading here depends on the stated linear,\nadditive recipe and its independent disturbances. Real studies need\nevidence for those conditions; a measured proxy need not suffice.\n\n### Adjusting for a collider on the same programme\n\n\n\n\n\n\n\n\nNow the third variable is caused by two things at once. The same\nrandomized programme runs; unmeasured family support raises achievement;\nand both programme participation and family support make a high score on\nan optional end-of-year portfolio more likely. The portfolio score is\nrecorded and looks like a sensible covariate.\n\n$$\n\\begin{aligned}\n\\text{program}_i &\\sim \\text{Bernoulli}(.5),\n&&\\text{support}_i\\sim\\text{Normal}(0, 1),\\\\\n\\text{achievement}_i &= 50+4\\,\\text{program}_i\n+5\\,\\text{support}_i+\\varepsilon_i,\n&& \\varepsilon_i\\sim\\text{Normal}(0, 4^2),\\\\\n\\text{portfolio}_i &= 1\\,\\text{program}_i+1\\,\\text{support}_i+\\nu_i,\n&& \\nu_i\\sim\\text{Normal}(0, 0.7^2).\n\\end{aligned}\n$$\n\nWith seed 14069 the unadjusted estimate is 4.1052 [3.0316, 5.1788],\nclose to the true 4 because randomization made programme and support\nindependent. Adjusting for the portfolio score gives 0.1726 [$-0.6755$,\n1.0206]: the whole comparison vanishes, and a researcher reading only\nthat model would report a null. Adjusting instead for the true cause\ngives 4.0396 [3.4011, 4.6781]. The mechanism is visible directly. In the\nwhole sample the correlation between programme and support is .0061; in\nthe lower, middle and upper thirds of the portfolio distribution, each\nof 200 records, it is $-.4106$, $-.4978$ and $-.2240$, because a high\nportfolio score can be reached either through the programme or through\nfamily support. Conditioning manufactured an association the design had\neliminated, and because support also causes achievement, that\nmanufactured association contaminates the programme coefficient\n[@elwert2014].\n\n### An adjustment decision table\n\n\\Needspace{30\\baselineskip}\n\n| Role of the candidate variable | Timing relative to the focal predictor | Adjust? | Consequence of adjusting |\n|:--|:--|:--|:--|\n| Common cause of predictor and outcome (confounder) | Before | Include in a sufficient causal adjustment set | Blocks the represented back-door path under the assumed structure and a suitable model |\n| Cause of the outcome only, unrelated to the predictor | Before | Optional | No systematic change; can improve precision |\n| Consequence of the predictor on the path to the outcome (mediator) | After | No, for a total-effect target | Changes the target to a conditional comparison; a direct causal reading needs additional conditions |\n| Consequence of both the predictor and an outcome cause (collider) | After | No | Creates an association that did not exist; can reverse or nullify the estimate |\n| Consequence of the outcome | After | No | Selects on information about the outcome; the conditional comparison no longer answers the original causal target |\n| Proxy measured with substantial error | Before | Partially useful | Leaves residual confounding; see Section 5.1 |\n\n: What adjusting for a candidate variable does, by its assumed role. {#tbl-ch14-adjustment tbl-colwidths=\"[30,18,14,38]\"}\n\nThe direct-effect reading in the mediator row requires a suitable model\nand control of mediator--outcome confounding; randomization of the programme\nalone does not establish it. The generated linear recipe supplies those\nconditions. A sufficient adjustment set blocks the relevant back-door\npaths without opening another path; merely including one plausible common\ncause need not remove all confounding.\n\nThe table summarizes assumptions; it is not a test. No procedure applied\nto the observed data classifies a variable into these rows, because\nevery row can produce the same coefficient movement. Timing, substantive\ntheory and documented measurement are what distinguish them.\n\n::: {.callout-warning title=\"A coefficient that changes is not a diagnosis\"}\nAdding $Z$ moved the focal coefficient from 0.9 to 0.2. That is\ncompatible with $Z$ being a confounder whose removal was necessary, a\nmediator whose inclusion destroyed the target, a collider whose\ninclusion introduced bias, or a variable so strongly related to $X$\nthat the movement is sampling noise on an imprecise estimate.\nReporting the movement is useful; reading it as evidence of\nconfounding is not warranted by the movement alone.\n:::\n\n## Reversals and Simpson's Paradox {#ch14-reversals}\n\n### A reversal built on purpose\n\n\n\n\n\n\nA generated example is preferable here because the comparison structure\nis known and can be altered deliberately. A district records, for every\npupil, weekly hours of supplementary tutoring and an end-of-year reading\nscore. Better-resourced schools offer more tutoring on average and also\nhave higher average scores for reasons unrelated to tutoring, while\nwithin any one school tutoring goes to pupils who are struggling, so\npupils receiving more tutoring tend to score lower.\n\n$$\n\\begin{aligned}\n\\text{hours}_{ig} &= \\mu_g+u_{ig},\n&& u_{ig}\\sim\\text{Normal}(0, 0.7^2),\\\\\n\\text{score}_{ig} &= \\alpha_g+\\beta_W(\\text{hours}_{ig}-\\mu_g)\n+\\varepsilon_{ig},\n&& \\varepsilon_{ig}\\sim\\text{Normal}(0, 4^2),\n\\end{aligned}\n$$\n\nwith school means $\\mu_g\\in\\{1.5, 3, 4.5, 6\\}$ hours, baselines\n$\\alpha_g\\in\\{30, 42, 54, 66\\}$ points, a true within-school slope\n$\\beta_W=-1.6$, and 60 pupils per school. Seed 14001 gives school mean\nhours 1.4945, 3.0833, 4.3461 and 6.1030 with mean scores 29.7655,\n42.1576, 54.1161 and 65.3627. In @fig-ch14-reversal, four\nclouds march up and to the right, and inside each cloud the trend runs\ndown and to the right. A model that never sees the school label can only\nsummarize the march.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Simulated tutoring hours and reading scores for 240 students in four schools. The dashed line is the pooled fit ignoring school; the four solid lines are the separate within-school fits. The pooled and within-school relationships have opposite signs.](chapter_14_files/figure-html/fig-ch14-reversal-1.png){#fig-ch14-reversal fig-pos='H' fig-alt='A scatterplot of 240 points forms four separated school clusters running from lower left to upper right. A dashed line through all points rises steeply with a slope of about 6.6 points per hour, while the four short solid lines inside the clusters each fall with slopes between about -1.3 and -2.6 points per hour.' width=672}\n:::\n:::\n\n\n### Three fits, three estimands\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nFit the three models and put their values beside the recipe. The pooled\nslope is 6.5784 [6.0565, 7.1003] with $R^2=.7215$; the school-adjusted\nslope is $-2.0018$ [$-2.8533$, $-1.1504$], covering the true $-1.6$; the\nbetween-school slope, from four rows and 2 residual df, is 7.8372\n[6.0877, 9.5866]. Only one estimates the parameter in the recipe. The\nother two correctly estimate how score and tutoring covary in the\ndistrict as composed and how school averages covary; both would be wrong\nas answers to a question about pupils inside a school.\n\nWith groups $g=1,\\dots,G$ and\nthe within and between sums of squares and cross-products\n$S_{xx}^{W}=\\sum_g\\sum_{i\\in g}(x_{ig}-\\bar x_g)^2$ and\n$S_{xx}^{B}=\\sum_g n_g(\\bar x_g-\\bar x)^2$, and $S_{xy}^{W}$, $S_{xy}^{B}$\ndefined the same way, the totals split as $S_{xx}=S_{xx}^{W}+S_{xx}^{B}$\nand $S_{xy}=S_{xy}^{W}+S_{xy}^{B}$, so\n\n$$\n\\widehat\\beta_{\\mathrm{pooled}}=\\frac{S_{xy}}{S_{xx}}\n=w_W\\widehat\\beta_W+w_B\\widehat\\beta_B,\\qquad\nw_W=\\frac{S_{xx}^{W}}{S_{xx}},\\quad w_B=\\frac{S_{xx}^{B}}{S_{xx}}.\n$$\n\nThe pooled slope is a weighted average of a within-group and a\nbetween-group slope, weighted by the shares of predictor variation\ninside and between groups; the weights are non-negative and sum to one,\nand the slopes they combine are unrestricted. Here $S_{xx}^{W}=100.5503$\nand $S_{xx}^{B}=685.3977$ of a total 785.948, so $w_W=.1279$ and\n$w_B=.8721$: only about an eighth of the predictor variation lies inside\nschools, the weighted average returns the fitted 6.5784 at full\nprecision, and the pooled slope is dominated by a comparison of school\naverages. Make the schools more alike in average tutoring and $w_B$\nshrinks; make them more different and it grows. Composition is a\nproperty of the sample, not of the phenomenon, so the reversal can be\ncreated or removed while the within-school association stays fixed. This\nrecipe specifies an observed joint distribution, not the effect of\nintervening on tutoring. Appendix A gives\nthe derivation and its categorical counterpart.\n\n| Research question | Estimand | Fit | Value |\n|:--|:--|:--|--:|\n| Across this district's pupils, how do reading scores compare between those receiving more and fewer tutoring hours? | Pooled | `score ~ hours` | 6.5784 |\n| Among pupils at the same school, how do scores compare between those receiving more and fewer hours? | Within-group | `score ~ hours + school` | $-2.0018$ |\n| Do schools that provide more tutoring on average have higher average scores? | Between-group, school as unit | mean score on mean hours | 7.8372 |\n\n: One dataset, three questions, three estimands. {#tbl-ch14-estimands tbl-colwidths=\"[48,16,22,14]\"}\n\nTake each school separately before accepting one adjusted number. The\nfour school-specific slopes are $-2.1063$ [$-4.0928$, $-0.1197$],\n$-1.8864$ [$-3.3807$, $-0.3920$], $-1.2688$ [$-3.0443$, 0.5067] and\n$-2.6281$ [$-4.3226$, $-0.9335$]: all negative, one interval covering\nzero. The additive model reports a single precision-weighted summary of\nthose four, which is useful when they are similar and misleading when\nthey are not; Chapter 10 supplies the check, and the `hours:school`\nproduct block here gives $F(3,232)=0.4345$, $p=.7285$, unsurprisingly,\nbecause the recipe gave all four schools the same slope. Subtracting\neach school's mean from `hours` removes all between-school variation in\nthe predictor, and an ordinary regression on that centred predictor\nreproduces $-2.0018$ exactly, without any group indicator.\n\nEverything above comes from `lm()` on clearly defined rows. The\nwithin-between distinction is the entry point to multilevel and linear\nmixed models, which are outside this collection; Section 6.3 explains\nwhy ordinary standard errors from a pooled fit on clustered data need\ncare.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(score ~ hours, data = tutoring)\nlm(score ~ hours + school, data = tutoring)\n```\n:::\n\n\n### Berkeley admissions: the same arithmetic on a census\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nThe best-known reversal in the social sciences is a two-by-two-by-six\ntable of graduate admissions decisions, a good empirical case because\nthe reversal is real, well documented and routinely overinterpreted in\nboth directions. Chapter 3, Section 6.4, reads a table of three\ncategorical variables as two-way tables within the layers of the third\nand notes that the added table can point the other way from most of its\nlayers; the Berkeley table is that case, with department as the layer.\nThe question: among applicants to the six largest\ngraduate departments at Berkeley in autumn 1973, how did the probability\nof admission compare between women and men, before and after\nconditioning on the department applied to? One row of the analysis file\nis a department-by-gender cell of counts; the unit of the question is\none application decision, the outcome is admitted against rejected, the\nfocal predictor is applicant gender with male as the reference, the\ndesign is an administrative census, the estimands are the pooled and the\ndepartment-conditional contrast, and the scope is these six departments\nin one term. The counts and the composition figure reveal why the\npooled comparison differs from comparisons within departments.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Why the pooled comparison is dominated by composition. For each department, the figure shows the department's overall admission rate and the percentage of each gender's own applications that were sent there, all on a percentage scale.](chapter_14_files/figure-html/fig-ch14-composition-1.png){#fig-ch14-composition fig-pos='H' fig-alt='Three connected series across departments A to F. The department admission rate falls from about 64 and 63 percent in A and B to 35, 34, 25 and 6 percent in C, D, E and F. Men send about 31 and 21 percent of their applications to A and B, whereas women send only about 6 and 1 percent; women instead send about 32, 20, 21 and 19 percent to C, D, E and F.' width=691.2}\n:::\n:::\n\n\n| Department | Men: admitted / applicants | Women: admitted / applicants |\n|:--|--:|--:|\n| A | 512 / 825 | 89 / 108 |\n| B | 353 / 560 | 17 / 25 |\n| C | 120 / 325 | 202 / 593 |\n| D | 138 / 417 | 131 / 375 |\n| E | 53 / 191 | 94 / 393 |\n| F | 22 / 373 | 24 / 341 |\n\n: Berkeley admissions in six departments, autumn 1973. {#tbl-ch14-ucb-cells tbl-colwidths=\"[20,40,40]\"}\n\nThe outcome is binary, so the model is the logistic regression of\nChapter 11 with the logit link and a binomial response. The pooled fit\ngives a female log-odds coefficient of $-0.6104$ (SE 0.0639, $z=-9.5527$,\n$p<.0001$), an odds ratio of 0.5432 [0.4792, 0.6156]: women's odds of\nadmission across the pooled pool were about 46 percent lower than men's.\nThat sentence is true, it describes the pooled applicant pool, and it\ncontains no information about what any department did. Adding department\nreverses the sign: the female coefficient becomes 0.0999 (SE 0.0808,\n$z=1.2353$, $p=.2167$), an odds ratio of 1.105 [0.9431, 1.2948] whose\ninterval comfortably includes 1. Under that additive model the interval is compatible with equal odds\nand with modest differences in either direction; it does not establish\nequality. Each reported odds-ratio interval here is the exponentiated\nWald interval from `confint.default()`, matching the reported $z$ and\n$p$; `confint()` applied to a `glm` object returns profile-likelihood\nintervals instead, which differ in the third decimal here, so state\nwhich one a report used.\n\nTwo facts in the cell table produce the reversal. Admission rates differ\nenormously across departments, from .0644 in F to .6442 in A, and\napplications were distributed very differently: A and B received 1,385\napplications from men and 133 from women, while C and E each received\nmore from women than from men (593 against 325 and 393 against 191). The\npooled rate for each gender is the composition-weighted average\n$\\sum_d q_dp_d$ of department-specific rates, so replacing each gender's\nown weights $q_d$ with a common set isolates composition, the\ncalculation called **direct standardization**. Using the combined\napplication counts as common weights gives 38.7319 percent for men and\n42.9955 for women, turning a pooled gap of 14.1645 points in men's\nfavour into a standardized gap of 4.2637 points in women's. Only the\nweights changed, so this is a third estimand: the rate each gender would\nhave experienced had both applied in the same proportions to these six\ndepartments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- glm(cbind(admitted, rejected) ~ gender, binomial, data = ucb)\nm1 <- glm(cbind(admitted, rejected) ~ gender + dept, binomial, data = ucb)\nexp(cbind(coef(m1), confint.default(m1)))\n```\n:::\n\n\n### One adjusted number needs checking\n\nThe additive model is itself an assumption and deserves the scrutiny the\npooled model gets. Comparing it with the model that lets the odds ratio\nvary gives a likelihood-ratio deviance of 20.2043 on 5 df, $p=.0011$;\nthe department-specific odds ratios run from 0.8186 in E to 2.8636 in A,\nand A is the main source of the departure, admitting 82.4074 percent of\nits 108 female applicants against 62.0606 percent of its 825 male ones.\nThe adjusted number that reverses the pooled result is therefore itself\na summary the data do not fully support.\n\n::: {.callout-warning title=\"A reversal is a descriptive fact, not an explanation\"}\nThe table shows that a pooled and a department-conditional comparison\npoint in opposite directions. It does not show why women and men\napplied where they did, whether departmental capacity and funding were\nthemselves shaped by the fields women entered, or whether any\nindividual decision was fair. @bickel1975 were explicit that their\nanalysis concerned the aggregation, and that no bias within\ndepartments is compatible with disadvantage arising earlier, in the\nprocesses that channel applicants toward differently funded fields.\nFor that broader question department is a mediator, not a confounder,\nand conditioning on it removes exactly the pathway the question is\nabout. Neither comparison answers whether the process was fair.\n:::\n\n## Selection, Support, and Regression to the Mean {#ch14-selection}\n\nAdjustment changes what is held fixed. Selection changes who is in the\ncomparison at all, and it operates before any model is fitted.\n\n### Regression toward the mean after selection on a noisy baseline\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nIn standard units a regression line predicts $\\widehat z_y=r\\,z_x$.\nWhen $0<r<1$, its prediction for an extreme first value is nearer the\nmean on the second measurement. The spread of individual second\nmeasurements remains: the whole population does not converge on its\nmean. Here that distinction reveals why a before--after comparison can\nmislead when entry depends on a noisy baseline.\n\nSuppose 400 pupils take a reading test, the lowest-scoring 15 percent\nenter a support programme, and they are retested at the end of the year.\nTheir average score rises substantially, and the obvious reading is that\nthe programme worked. The recipe below contains no programme effect at\nall.\n\n$$\n\\begin{aligned}\nT_i &\\sim\\text{Normal}(50, 8^2)\n&&\\text{(stable ability, unobserved)},\\\\\n\\text{pretest}_i &= T_i+\\varepsilon_{i1},\n&& \\varepsilon_{i1}\\sim\\text{Normal}(0, 6^2),\\\\\n\\text{posttest}_i &= T_i+\\varepsilon_{i2},\n&& \\varepsilon_{i2}\\sim\\text{Normal}(0, 6^2).\n\\end{aligned}\n$$\n\nBoth measurements are the same stable quantity plus independent noise,\nso the correlation between them, the reliability under this model, is\n$8^2/(8^2+6^2)=.64$; with seed 14002 the observed correlation is\n.6371. Selecting the lowest scorers on the pretest selects pupils with\ngenuinely low ability **and** pupils whose measurement error happened to\nbe negative, and the second group cannot repeat that luck\n[@galton1886; @barnett2005]. The 60 selected pupils, all below\n38.3371, average 33.5726 on the pretest and 39.0568 on the posttest, a\ngain of 5.4842 points with a paired $t(59)=4.8378$, $p<.0001$ and a\n95 percent interval of [3.2158, 7.7526]. Every number is computed\ncorrectly, and the effect written into the recipe is zero. The mirror\nimage confirms the mechanism: the highest 15 percent show an apparent\ndecline of $-5.823$.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Regression to the mean with no intervention. Points are 400 simulated students; the vertical dotted lines mark the lowest and highest 15% of pretest scores. The solid line is the identity, the dashed line is the fitted regression, and the fitted line is flatter, so the selected extremes move toward the middle on retest.](chapter_14_files/figure-html/fig-ch14-rtm-1.png){#fig-ch14-rtm fig-pos='H' fig-alt='A scatterplot of posttest against pretest for 400 students, with a positive but noisy association of about 0.64. Two vertical dotted lines at roughly 38 and 60 mark the lowest and highest 15 percent of pretest scores. The diagonal identity line, of slope 1, is steeper than the dashed fitted line, whose slope is about 0.63, and the two cross near the middle of the range, so points in the low band average above the identity line and points in the high band average below it.' width=633.6}\n:::\n:::\n\n\nA bigger sample does not repair this: the phenomenon is systematic, and\nmore pupils estimate the spurious gain more precisely. A comparison\ngroup selected the same way does repair it, because both arms are then\nsubject to identical regression to the mean. Keep the 60 selected pupils\nin their original row order rather than sorting them by pretest, assign\narms with `sample(rep(c(\"Program\", \"Comparison\"), length.out = 60))`\nunder seed 14003, and compare the arms' change scores with a Welch\ntwo-sample test: the arms gain 6.4651 and 4.5033 points, a difference of\n1.9618 [$-2.5867$, 6.5103], $p=.3915$. A pooled-variance or `lm()`\ninterval differs in the fourth decimal, so name the test. A second\nbaseline with an independent measurement error, used for selection but\nnot for the change score, removes this particular selection-on-error\nartifact in the recipe; it does not by itself identify a programme effect.\nThe artifact also has a regression signature. On the original scales,\nthe fitted slope of change on baseline is\n$b_{\\mathrm{post,pre}}-1=r(s_{\\mathrm{post}}/s_{\\mathrm{pre}})-1=-0.3707$.\nWhen each measurement is standardized separately, the corresponding\nslope is $r-1=-0.3629$. These are distinct calculations; the raw-scale\nslope equals $r-1$ only when the two sample SDs agree. Thus \"pupils who\nstarted lowest gained most\" can arise with a zero programme effect.\n\n::: {.callout-warning title=\"What regression to the mean is not\"}\nIt is not a claim that an intervention failed, and it is not a claim\nthat one succeeded. In this recipe it is a consequence of two things holding\ntogether: repeated noisy measurement of the same quantity, and\nselection on an extreme value of the first measurement. Where either\nis absent, this particular mechanism is absent. Where both are present, a\nsingle-arm pre-post comparison cannot distinguish a real effect from\nthe artifact, whatever the p-value [@barnett2005].\n:::\n\n### Selection on the predictor and selection on the outcome\n\n\n\n\nSelection on the predictor and selection on the outcome are often\ndiscussed together and behave very differently. The recipe below is a\ncorrectly specified linear model over the whole range: an admission-test\nscore predicts first-year grade point average with a true slope of 0.02\ngrade points per test point, 500 applicants, score\n$\\sim\\text{Normal}(100, 15^2)$ and error SD 0.45. With seed 14006 the\nfull-sample slope is 0.021 (SE 0.0014, $R^2=.3091$, $r=.556$).\n\nEach row is `lm(gpa ~ score)` on the rows its rule\nkeeps.\n\n\\Needspace{10\\baselineskip}\n\n| Rows kept | Selection rule | Slope | SE | $R^2$ | $r$ |\n|:--|:--|--:|--:|--:|--:|\n| 500 | None | 0.0210 | 0.0014 | .3091 | .5560 |\n| 148 | Score at least 110: on the predictor | 0.0234 | 0.0053 | .1178 | .3433 |\n| 261 | Grade point average at least 3: on the outcome | 0.0106 | 0.0015 | .1636 | .4045 |\n\n: What predictor and outcome selection do to the same fit. {#tbl-ch14-restriction tbl-colwidths=\"[11,43,12,11,11,12]\"}\n\nUnder a correctly specified linear model with errors independent of the\npredictor, restricting the predictor range preserves the population slope;\nsample estimates still vary. What\nit destroys is precision and apparent strength. A selective institution\nconcluding that \"the admission test barely predicts grades\" from a\nwithin-admitted correlation has confused a restricted correlation with a\nweak relationship. Selecting on the outcome instead halves the slope,\nbecause that rule removes low-outcome applicants disproportionately at\nlow test scores. Selection on the outcome, and attrition related to the\noutcome, are threats of a different order from selection on the\npredictor.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(gpa ~ score, data = applicants)\nlm(gpa ~ score, data = subset(applicants, score >= 110))\n```\n:::\n\n\n**When the conditional mean is curved.**\n\nPredict whether restricting the predictor still preserves one slope.\nThe reassuring result just established depended on\na correct linear mean model. Now use 500 observations under seed 14012,\ndraw study hours uniformly from 0 to 20, and generate\n\n$$E(\\mathrm{learning}\\mid h)=20+4h-0.14h^2,\\qquad\n\\varepsilon\\sim\\mathrm{Normal}(0,4^2).$$\n\nThe 187 observations at eight hours or fewer occupy the steep rising\npart of the curve. Their fitted line has slope 2.6951; the line through\nall observations has slope 1.0845. Neither slope is the constant effect\nof an hour over the whole range, because the derivative $4-0.28h$\nchanges with $h$.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![A curved conditional mean seen through a restricted window. The curve is the true mean; the solid line is fitted to all 500 observations; the dashed line is fitted only to observations with at most 8 study hours and then extended across the full range.](chapter_14_files/figure-html/fig-curved-restriction-1.png){#fig-curved-restriction fig-pos='H' fig-alt='A scatterplot of learning against study hours from 0 to 20 with a true mean curve that rises steeply, peaks near 14 hours around 48 points, and then falls slightly. A solid straight line fitted to all points rises gently with slope near 1.1. A dashed line fitted only to the observations at 8 hours or fewer rises much more steeply with slope near 2.7 and, when extended, reaches about 71 at 18 hours where the true mean is about 47.' width=652.8}\n:::\n:::\n\n\nExtending the restricted line to 18 hours predicts 71.1765, while the\nknown conditional mean is 46.64. A narrow model-based interval around\nthe line would describe uncertainty within that assumed line, not\nevidence that the line remains adequate outside its observed window.\n\n\n### Missingness and attrition are selection by another name\n\nThe same logic covers rows that disappear rather than rows never\nrecruited. Three standard labels describe how missingness relates to the\ndata [@little2002; @littlerubin2019]. **Missing completely at random**\nis unrelated to observed and unobserved values, so a complete-case\nregression loses observations without systematic selection on their values.\n**Missing at random** means that, conditional on the observed information,\nmissingness does not depend on the missing values. It can bias a\ncomplete-case analysis, but need not do so: missing outcomes depending only\non a fully observed predictor can preserve its correctly specified\nconditional regression. **Missing not at random** means that dependence on\nmissing values remains after conditioning on the observed information.\nThe observed records alone cannot identify that mechanism; analyses require\nexplicit assumptions and sensitivity checks. The target and the missingness\nprocess together determine whether a complete-case result is adequate.\n\nTwo habits matter more than the labels. Report the funnel, how many\nunits were eligible, invited, observed, retained and analysed, with the\nreason at each step; Chapters 1 and 9 built that discipline and Section\n7.1 applies it to Project STAR. And resist the idea that adding\npredictors repairs selection: a larger model changes what is held fixed\namong the units that remain and restores none that left. Where dropout\ndepends on the outcome, the analytic sample is a selected-on-the-outcome\nsample, and Section 4.2 shows what that does.\n\n::: {.callout-warning title=\"Selection changes who is being compared\"}\nA regression estimates a comparison among the rows it receives. If\nthose rows arose through participation decisions, attrition,\neligibility cutoffs or an institution's admission rules, the estimand\nquietly becomes a statement about that selected group. This is a\ndesign and data problem. Fitting an ordinary regression to the retained\nrows does not by itself repair it; explicit selection methods require\nadditional information and defensible assumptions.\n:::\n\n## Measurement, Aggregation, and the Unit of Analysis {#ch14-unit}\n\nThe previous sections asked which comparison was made and among whom.\nThis one asks what the columns actually contain and what the rows\nactually are.\n\n### Measurement error in a predictor and in a control\n\n\n\n\n\n\nChapter 7 separated the conditions of the least-squares algebra from the\nrequirement that a recorded predictor adequately represent the construct\nthe estimand names, and no residual plot assesses that requirement.\nMotivation measured with a scale whose error variance is $0.75^2$ against\na true-score variance of 1 has reliability $1/(1+0.75^2)=.64$; with\nseed 14008 and 800 records the slope falls from 4.8327 with the true\npredictor to 3.0577 with the measured one, close to the predicted\n$5\\times.64=3.2$. The SE 0.1683 does not warn of this, the\nresidual plot cannot show it, and the p-value stays below .001: the\nestimate is aimed at the wrong quantity. In this single-predictor linear\nmodel, classical measurement error multiplies the population slope by the\npredictor's reliability. With several mismeasured or correlated predictors,\nbias need not be toward zero [@cohen2003; @fox2016].\n\nThe more damaging consequence appears when the mismeasured variable is a\ncontrol. Suppose a programme has no effect but socioeconomic status\ncauses both participation and the outcome.\n\nDraw the four columns in the\norder shown, so that the seed reproduces the printed values.\n\n$$\n\\begin{aligned}\n\\text{status}_i &\\sim\\text{Normal}(0, 1),\\\\\n\\text{participation}_i &= 0.9\\,\\text{status}_i+v_i,\n&& v_i\\sim\\text{Normal}(0, 1),\\\\\n\\text{outcome}_i &= 50+0\\,\\text{participation}_i+3\\,\\text{status}_i\n+\\varepsilon_i,\n&& \\varepsilon_i\\sim\\text{Normal}(0, 3^2),\\\\\n\\text{proxy}_i &= \\text{status}_i+w_i,\n&& w_i\\sim\\text{Normal}(0, 0.9^2).\n\\end{aligned}\n$$\n\nThe proxy's reliability is $1/(1+0.9^2)=.5525$. With seed 14009 and 800\nrecords, `outcome ~ participation` gives 1.3709 for a true effect of\nzero, `outcome ~ participation + status` recovers $-0.113$, and\n`outcome ~ participation + proxy` gives 0.7377, leaving about 54 percent\nof the unadjusted bias in place. \"We controlled for socioeconomic status\" is\ntherefore an incomplete sentence: what matters is how well status was\nmeasured [@aeraApaNcme2014]. **Construct drift** is the same problem\nwith a different face, since a variable named `engagement` in a 2015 and\na 2020 wave may be two constructs if the items, response scale or\nadministration changed. Regressions do not notice; a codebook and a\ndocumented measurement history do.\n\n### Ecological inference: the rows are not people\n\n\n\n\n\n\nAn **ecological inference** transfers a relationship estimated among\naggregates to the individuals inside them, and the two need not agree in\nmagnitude or in sign [@robinson1950]. The recipe makes the\ndisagreement exact. Sixty occupations of 40 workers vary in their share\nof women, drawn Uniform(.05, .95); the occupation level is\n$40-18\\,\\text{share}+\\varepsilon$ with error SD 3; within any\noccupation women earn 2 thousand dollars more than men, with worker\nnoise SD 4.\n\nWith seed 14010 the three numbers are $-3.0228$ at worker level pooled,\n1.9869 at worker level within occupation, and $-14.3063$ [$-17.3278$,\n$-11.2847$] at occupation level. Only the middle one estimates the\nquantity in the recipe. The occupation-level slope, read as a gender\ngap, is about seven times the true gap and points the wrong way: it is\nnot wrong about occupations, it is wrong about workers. The\nwithin-occupation differences average 1.9602 and run from $-2.2702$ to\n6.0976, with 90 percent positive. The worker-level pooled estimate is\nnegative although its rows are individuals, because the omitted\noccupational structure does the work composition did in Section 3.1.\nThis is a reversal and the ecological fallacy in one dataset.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Aggregate and within-group relationships in the same simulated data. Panel (a) plots the 60 occupation means with the occupation-level fitted line. Panel (b) shows the distribution of the within-occupation income differences between women and men; the dashed line marks the true within-occupation difference of plus 2 thousand dollars.](chapter_14_files/figure-html/fig-ch14-ecological-1.png){#fig-ch14-ecological fig-pos='H' fig-alt='Panel (a) shows 60 points falling steeply from about 40 thousand dollars at a five percent share of women to about 22 thousand dollars at a ninety-five percent share, with a fitted line whose slope is about -14 thousand dollars per unit share. Panel (b) is a histogram of the 60 within-occupation differences between women and men, centered near plus 2 thousand dollars with most values between about -2 and plus 6, and a dashed vertical reference line at plus 2.' width=710.4}\n:::\n:::\n\n\n### The same problem in real occupation records\n\n\n\n\n\n\n\n\nChapters 7 and 8 used the 1971 Canadian census occupation records, which\ncarry the percentage of incumbents who were women, and it is tempting to\nregress occupation-average income on it. Across the 102 occupations the\nfitted contrast is $-0.059$ thousand 1971 dollars per percentage point\n(SE 0.012, [$-0.0829$, $-0.0352$], $R^2=.1945$), so ten points of share\ncorresponds to about 0.5903 thousand dollars of lower occupational\naverage income. That is a defensible occupation-level description, not\nan estimate of what a woman and a man in the same job earned, and\nSection 5.2 shows the two can differ in sign. These records contain no\nindividuals, so the aggregate association alone cannot identify the\nindividual comparison; state\nthe occupation-level claim and stop.\n\n\\Needspace{18\\baselineskip}\n\n| Symptom | Question to ask |\n|:--|:--|\n| The conclusion names people; the rows are schools, occupations, regions, or years | What does one row represent, and was that unit used consistently from question to claim? |\n| A percentage or an average is used as a predictor | Is it a property of the group, or a stand-in for an unobserved individual variable? |\n| A relationship is much stronger in aggregate than at the individual level | Has averaging removed the individual variation that would weaken it? |\n| A construct label is reused across waves, sites, or instruments | Were the items, scale, and administration the same? |\n| A control variable is a scale score, index, or proxy | What is its reliability, and what residual confounding remains? |\n\n: A checklist for unit-of-analysis mistakes. {#tbl-ch14-unit-checklist tbl-colwidths=\"[42,58]\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(income_k ~ women, data = occupations)\n```\n:::\n\n\n## Specification Sensitivity and Dependence {#ch14-sensitivity}\n\n### Analyst degrees of freedom\n\n\n\n\nEverything so far assumed one analysis. In practice a defensible\nanalysis has many defensible versions, and the choice among them is made\nby a person who can see the results. Modest undisclosed flexibility\nsuffices to produce significant support for essentially any hypothesis\n[@simmons2011]; the response is to run the reasonable specifications\nand report the distribution rather than one selected member of it\n[@steegen2016].\n\nThe Chapter 7 and 8 question supplies a natural example: how does\noccupation-average income differ across occupations with different\naverage education? Five adjustment sets (education alone, adding\nprestige, adding the percentage of women, adding both, and adding occupational type alone) and three sample rules (all 98 type-complete rows,\nthe 93 remaining after dropping the five largest Cook's distances from\nthe education-only fit, the 96 with income at or below 20 thousand) give\nfifteen plausible descriptive specifications, each an `lm()` of\n`income` on `education` and the set's other terms, with 95 percent\nintervals from `confint()`. The education coefficient, read in thousands\nof dollars per year of average education, runs from $-0.2179$ to 0.9370\nwith a median of 0.7301; eleven of the fifteen have $p<.05$, three are\nnegative, and four intervals cover zero. Reported by adjustment set,\neducation alone gives 0.6472 to 0.8830, adding the percentage of women\n0.7301 to 0.9292, adding occupational type 0.7983 to 0.9370, and the six\nspecifications containing prestige collapse to $-0.2179$ to 0.3023, which\nis where every interval covering zero sits. The spread is not\nmysterious: education and prestige correlate\n.8665 across these occupations, so models containing both split the\nshared variation between them, which is the collinearity Chapter 8\nexamined and also a change of estimand, because the coefficient now\ncompares occupations at the same prestige.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The education coefficient across fifteen specifications, with 95% confidence intervals, grouped by adjustment set and distinguished by sample rule. The vertical line marks zero.](chapter_14_files/figure-html/fig-ch14-multiverse-1.png){#fig-ch14-multiverse fig-pos='H' fig-alt='Fifteen horizontal interval estimates. Education-only specifications lie between about 0.65 and 0.88; those adding percentage women lie between about 0.73 and 0.93; those adding occupational type lie between about 0.80 and 0.94. These nine intervals exclude zero. The six specifications containing prestige have estimates from about -0.22 to 0.30, and four intervals cover zero.' width=710.4}\n:::\n:::\n\n\nAn analyst who reports only the specification that best fits an expected\nstory is not lying about a number, and it survives replication of that\nspecification; what is lost is the reader's ability to know how much of\nthe result was a choice.\n\n::: {.callout-warning title=\"Robustness is evidence about specification, not about bias\"}\nA stable coefficient across fifteen models shows that the result does\nnot depend on those fifteen choices. It says nothing about an omitted\ncommon cause that none of the fifteen contains, about selection that\nshaped all fifteen samples identically, or about measurement error\npresent in every version. A robustness table is a useful disclosure;\nit is not a proof of causality and not a substitute for design.\n:::\n\n### Multiplicity and the four disclosures\n\nChapter 4, Section 3.3, developed multiplicity: as the number of comparisons grows,\nso does the chance that at least one crosses a conventional threshold\nunder a true null, and it calibrated a declared family. In an\napplied project the comparisons are rarely counted, because they\naccumulate informally across outcomes, subgroups, covariate sets,\ntransformations and exclusion rules. The practical response is\ndisclosure rather than arithmetic [@wasserstein2016; @appelbaum2018].\nFour disclosures do most of the work.\n\n::: {.callout-note title=\"Four disclosures\"}\n1. **Prespecify.** Write the primary specification and the primary\n   outcome before seeing results, which separates confirmation from\n   exploration.\n2. **Count.** Report the number and nature of the analyses performed,\n   so that a reader can calibrate the p-values.\n3. **Show the set.** Present the sensitivity set rather than its best\n   member, and label subgroup findings exploratory unless they were\n   prespecified.\n4. **Open the file.** Share code and data where permitted, which makes\n   the specification auditable [@nationalAcademies2019; @peng2011;\n   @nosek2018].\n:::\n\n### Dependence is a design fact {#ch14-dependence}\n\n\n\n\n\n\nEvery standard error in this collection assumes that rows carry\nindependent information, or that the calculation represents the\ndependence. When pupils share a classroom, measurements repeat within a\nperson, or records repeat within a site, treating rows as independent\ncan misrepresent uncertainty. Positive classroom clustering in the examples\nbelow makes independent-row standard errors too small; ignoring a useful\npairing can instead make them too large. Treating dependent observations as\nindependent replicates is **pseudoreplication**.\n\nProject STAR is the worked case, and Chapter 9 §7 owns its mechanics, so\nrecall its result rather than re-deriving it. Among the 3,745\nobserved-reading pupils in 79 schools, kindergarten reading averaged\n434.7323 in regular classes and 440.5474 in small ones, a difference of\n5.8151 points. Treating pupils as independent gives an SE of 1.0377; HC3\ngives 1.0416, barely different; clustering pupils within their schools\ngives 1.8476, about 1.7805 times the row-level value, so with\n$t_{.975,78}=1.9908$ the clustered interval is [2.1368, 9.4935] against\nthe row-level [3.7807, 7.8496]. Unequal spread across pupils was not the\nissue addressed by the clustered calculation; it allows residual\ndependence within schools while treating schools as independent. This\ncluster-based approximation needs enough independent schools and a\nsuitable model. The within-school randomization is a separate design\nfact: it neither uniquely selects this covariance estimator nor makes\nthe interval an exact randomization interval.\n\nA short calibration check makes the cost of the wrong choice visible\nwithout leaving the collection's methods. Twenty classrooms of 15\npupils, treatment assigned at classroom level with a true effect of\nzero, classroom SD 6 against pupil SD 5 and therefore\n$\\rho_I=6^2/(6^2+5^2)=.5902$.\n\nDraw the three random\nquantities in the order shown, so that the seed reproduces the printed\nvalues; `rbinom(20, 1, .5)` assigns each classroom independently rather\nthan forcing a 10-and-10 split, and each classroom's draw is repeated to\nits 15 pupils.\n\n$$\n\\begin{aligned}\n\\text{treat}_g &\\sim\\text{Bernoulli}(.5),\n&&\\text{repeated to the 15 pupils of classroom }g,\\\\\na_g &\\sim\\text{Normal}(0, 6^2),\n&&\\text{one draw per classroom},\\\\\n\\text{score}_{ig} &= 60+0\\,\\text{treat}_g+a_g+\\varepsilon_{ig},\n&& \\varepsilon_{ig}\\sim\\text{Normal}(0, 5^2).\n\\end{aligned}\n$$\n\nWith seed 14011 one dataset gives the same estimate 0.2343 from pupil\nrows and from classroom means, the latter from `score ~ treatment` on\nthe 20 classroom averages, but standard errors of 1.0021 and 3.3249. One\ndataset proves nothing about calibration, so repeating the same recipe\n1,000 times with seed 14013 counts how often each nominal 95 percent\ninterval covers zero: 48.2 percent from pupil rows and 94.3 percent from\nclassroom means. The pupil-row analysis is not slightly optimistic; it\nis wrong about the information the design supplied.\n\n::: {.callout-warning title=\"Dependence is a design fact, not a modelling preference\"}\nAn analysis does not become appropriate for clustered data because the\ncluster identifier was not recorded. When treatment is assigned by\nclassroom, the assignment unit is the classroom and the analysis must\nreflect it: analysing classroom means is the simplest honest response,\nChapter 9's cluster-robust covariance is the one used for Project\nSTAR, and multilevel models are the standard alternative outside this\ncollection. Sampling pupils within classrooms is a distinct design;\nthe sampling and dependence structure, not the presence of a classroom\nlabel, determines the unit of inference.\n:::\n\n## What a Design Supplies That Adjustment Cannot {#sec-ch14-design}\n\n### What randomization supplied in Project STAR\n\nA causal effect compares outcomes for the same unit under two conditions.\nWrite $Y_i(0)$ for pupil $i$'s outcome without the programme and $Y_i(1)$\nfor the outcome with it. Only the outcome under the assigned condition\nis observed. This notation assumes well-defined conditions and no\nspillover from one pupil's assignment to another pupil's outcome.\n\n| Pupil | Assigned condition | $Y_i(0)$ | $Y_i(1)$ |\n|:--|:--|--:|--:|\n| A | Without programme | 12 | ? |\n| B | With programme | ? | 19 |\n| C | Without programme | 20 | ? |\n| D | With programme | ? | 16 |\n\n: Four invented pupils: each row is missing the other potential outcome. {#tbl-ch14-counterfactual tbl-colwidths=\"[16,40,22,22]\"}\n\nCould any row establish its pupil's programme effect? Could the observed\ngroup difference do so? The treated mean is 17.5 and the untreated mean\nis 16, a difference of 1.5, but the groups contain different pupils.\nFor this constructed illustration alone, reveal the missing outcomes:\nA would score 18 with the programme, B would score 15 without it, C would\nscore 27 with it, and D would score 11 without it. Their individual effects\nare 6, 4, 7 and 5, averaging 5.5. The observed difference is not that\naverage in this allocation.\n\nRandomly assigning exactly two of these four pupils, with all six pairs\nequally likely, would make the unadjusted difference unbiased for their\naverage effect across repeated assignments; it would neither fill the missing cells nor\nmake every realized difference equal 5.5. A sound uncertainty calculation\nrepresents that variation. The small table separates an individual effect,\nan average effect and an observed group comparison before a fitted model\ncan blur them together.\n\nSections 2 to 6 catalogued what adjustment cannot do: remove a\nconfounder nobody measured, repair a mismeasured control, restore rows\nthat left, tell a confounder from a mediator or a collider, or decide\nwhich comparison the question wants. A design supplies what adjustment\ncannot, because it acts before the data exist.\n\nProject STAR assigned kindergarten pupils to class types within their\nschools by a known probability mechanism [@finn1990; @mosteller1995],\nand that mechanism supplies three things at once.\n\n::: {.callout-note title=\"What randomization supplied in Project STAR\"}\n1. **Independence under the assignment mechanism**, conditional on\n   school and any other variables used to set allocation probabilities,\n   between assignment and baseline characteristics or potential outcomes.\n   This concerns measured and unmeasured characteristics and does not\n   guarantee exact balance in one realized sample. On the same 3,735\n   primary records, the adjusted comparison is 6.6575 (SE 1.6974,\n   [3.2782, 10.0368]) and the unadjusted one 5.8955 (SE 1.8491,\n   [2.2143, 9.5767]); adjustment changes precision and the fitted\n   comparison without supplying the randomization warrant.\n2. **Fixed timing**, so class type is settled before the kindergarten\n   year and no within-year measure can be a pre-treatment common\n   cause; nothing in the data would show that after the fact.\n3. **A named assignment mechanism** against which uncertainty can be\n   assessed. Assignment was within schools. Section 6.3's interval\n   additionally treats schools as approximately independent clusters,\n   allowing dependence within them. It is a cluster-asymptotic\n   approximation, not an exact randomization interval or a unique\n   consequence of the assignment protocol.\n:::\n\nWhat randomization does\nnot supply is equally explicit, and Chapter 9 listed it: 349 of the\n4,094 eligible pupils have no recorded reading score, and their absence\nis a selection question randomization does not answer; the link from\nrecorded class type to original assignment is unverified in the\ndistributed file; the raw arm means weight schools by arm-specific\ncounts; and the result concerns assigned class type, one kindergarten\nreading outcome and participating Tennessee schools, not a realized\nheadcount or a portable policy dose response [@krueger1999;\n@hanushek1999; @nye2000; @chetty2011].\n\n### Four designs, named and bounded\n\nWhen assignment is not available, some studies borrow an event or a rule\nthat behaves, under stated assumptions, like part of an assignment\nmechanism. Read the vocabulary, recognize the claim and check the\nassumption that carries it; the procedures are a separate course.\n\n| Design | Identifying idea in one sentence | The assumption that carries it | What it does not remove |\n|:--|:--|:--|:--|\n| Natural experiment | An external event or administrative accident allocates exposure in a way the units did not choose | The event is unrelated to the units' potential outcomes | Selection into the affected population; measurement and dependence |\n| Difference in differences | Compare the change over time in an exposed group with the change in an unexposed group | The two groups' outcomes would have moved in parallel without the exposure | Differential composition change, anticipation, and other events at the same time |\n| Regression discontinuity | Compare units just above and just below a threshold that determines exposure | Potential-outcome means would be continuous at the cut without the exposure; precise manipulation or another change at the same cut can undermine this | Anything away from the threshold; the estimate is local |\n| Instrumental variables | Use a variable that shifts exposure but has no other route to the outcome | Relevance, independence and exclusion; a complier-effect reading also needs monotonicity and a well-defined exposure | Weak-instrument imprecision; under these conditions the effect concerns compliers |\n\n: Four designs as reading vocabulary, with the assumption each rests on. {#tbl-ch14-designs tbl-colwidths=\"[18,32,26,24]\"}\n\nChapter 1 §3.2 gave one short illustration, and recalling it fixes the\npattern. A lottery offer of a programme place changes take-up; if the\nlottery is independent of the outcome and affects it only by changing\ntake-up, the offer can identify an effect for those whose take-up the\nlottery changed. Independence and exclusion require support rather than\nassertion, further assumptions decide which effect is identified and for\nwhom, and none of it makes the volunteers represent a wider\npopulation.\n\n### Where this chapter's reasoning stops\n\nThe audit is a discipline, not a method: it supplies no estimator and\ncannot supply a design the study did not have.\n\n::: {.callout-note title=\"Four boundaries\"}\n1. **No new causal estimator.** The chapter develops identification questions\n   but does not implement an observational causal estimator. Recognizing that department is a\n   mediator for one question and a confounder for another says what a\n   regression cannot do, not what to fit instead.\n2. **Dependence.** Aggregating to the cluster is honest but discards\n   within-cluster information; Chapter 9's clustered covariance is the\n   calculation used here, and multilevel models are the natural\n   continuation outside this collection.\n3. **Missing data.** They receive an audit and a bounded claim, not a\n   method; multiple imputation is the continuation.\n4. **Measurement error.** It is diagnosed and its direction stated,\n   not corrected; errors-in-variables models are the continuation.\n:::\n\nWhat the\nchapter does supply is transferable: naming the estimand, describing the\ncomparison a model computes, checking who is in it and what was\nmeasured, disclosing how many analyses were run, and writing a final\nsentence that stays inside all of it.\n\n## From Analysis to a Credible Claim {#ch14-claim}\n\n### Five stages for auditing a results paragraph\n\nThe chapter closes by auditing one results paragraph against five stages\nand rewriting it. The paragraph concerns the generated district data of\nSection 3.1, so every number can be checked and the truth is known.\n\nThe five stages are this chapter's reading device for one results\nparagraph, not the collection's account of the research process, and they complement the broader schemes introduced in Chapter 1: §6.3's six quality-evaluation questions ---\nQuestion alignment under Alignment; Evidence integrity, Justification\nadequacy and Inferential adequacy under Support; Transition fidelity and\nClaim calibration under Translation --- and §7.3's six-stage, two-phase\nconstruction workflow. The workflow explains when a problem arose, while\nthe audit judges the completed record; the five stages group the audit\nquestions in @tbl-ch14-audit and replace neither scheme.\n\n::: {.callout-note title=\"The five stages of this chapter's audit\"}\n1. **Research question:** state the substantive question and its mode.\n2. **Population and unit, measurement and design:** define what one\n   row represents, how variables were produced, how units entered and\n   left, and what comparisons the design warrants.\n3. **Estimand, data, model, and estimation:** name the target\n   comparison explicitly, construct the analytic sample, specify the\n   model that computes that comparison, and estimate it.\n4. **Assumption checking and sensitivity, uncertainty and evidence:**\n   examine mean structure, dependence, support, measurement and\n   specification sensitivity, and report what moved.\n5. **Interpretation, prediction, scope, and bounded claim:** write a\n   conclusion whose unit, verb, population and range the previous four\n   stages support.\n\nStage 5 is not a formatting step. Failures can originate at any\nearlier stage; many computations in this chapter ran exactly as\nspecified, and Stage 5 is where an unresolved mismatch upstream\nbecomes a false sentence.\n:::\n\n### One paragraph, audited and rewritten\n\n::: {.callout-important title=\"Draft results paragraph, as submitted\"}\nUsing data on 240 pupils across four schools, we examined the effect\nof supplementary tutoring on reading achievement. A regression of\nend-of-year reading score on weekly tutoring hours showed that each\nadditional hour of tutoring raised scores by 6.5784 points\n($p<.0001$), explaining 72 percent of the variance in achievement. The\neffect was highly significant, confirming that tutoring is an\neffective intervention. Because the relationship was so strong, we\nrecommend that the district expand tutoring to 10 hours per week for\nall pupils, which the model predicts would produce scores of\napproximately 89 points. Robustness checks confirmed the finding.\n:::\n\nEvery number in that paragraph is arithmetically correct, and the\nparagraph is indefensible at four of the five stages.\n\n**Stage 1.** The paragraph uses causal verbs, \"effect\", \"raised\",\n\"effective intervention\", for an observational regression with no\nassignment mechanism and no identification argument. The mode changed\nsilently between the analysis and the sentence: the analysis supports\nan associational claim and the sentence makes a causal one.\n\n**Stage 2.** One row is a pupil in one of four fixed schools, not\nsampled at random, differing systematically in tutoring provision and\nbaseline achievement. Nothing is said about how tutoring was\nallocated, which Section 3.1 showed to be decisive, about who was\nmeasured with what instrument, or about pupils missing an end-of-year\nscore.\n\n**Stage 3.** The fitted model is `score ~ hours`, whose coefficient is\nthe pooled comparison. That is a legitimate estimand, but not the one\nthe sentence describes: 87 percent of the predictor variation lies\nbetween schools, so the reported number is largely a comparison of\nschool averages, and the within-school comparison $-2.0018$ has the\nopposite sign.\n\n**Stage 4.** \"Highly significant\" is offered as confirmation, but a\nsmall p-value states compatibility with a null model, not size,\nimportance or causal status [@wasserstein2016]; \"explaining 72\npercent of the variance\" is an algebraic decomposition of sample\nvariation; and \"robustness checks confirmed the finding\" names neither\nthe checks, nor their number, nor their spread. The intervals suit\nthis recipe's independent residual errors conditional on four fixed\nschools, which a real report would have to justify rather than infer\nfrom a missing cluster column.\n\n**Stage 5.** The recommended prediction is made at 10 tutoring hours\nper week, and the observed range is 0.1496 to 7.5722 hours, with no\npupil at or above 8. The pooled model returns 88.9215 points there and\nthe school-adjusted model returns 57.5615 at School 4: outside the\nsupport the two fits of the same data separate by more than 31 points\nbecause nothing constrains them. The recommendation also assumes the\nassociation would survive an intervention that changes how tutoring is\nallocated, which is precisely what the design cannot license.\n\n\\Needspace{34\\baselineskip}\n\n::: {.callout-tip title=\"Revised results paragraph\"}\nWe analysed end-of-year reading scores and weekly tutoring hours for\n240 pupils in four schools in one district. Tutoring is allocated by\nschools rather than assigned by the study, so every estimate below is\na comparison, not an effect. Pooling across schools, pupils receiving\none more hour of tutoring per week scored 6.5784 points higher on\naverage (95 percent interval [6.0565, 7.1003]). This pooled figure\nmainly reflects differences between schools: only 12.79 percent of the\nvariation in tutoring hours occurs within schools, and\nbetter-resourced schools both provide more tutoring and have higher\naverage scores. Within schools the comparison reverses: adjusting for\nschool, pupils receiving one more hour scored 2.0018 points lower\n(95 percent interval [$-2.8533$, $-1.1504$]), all four school-specific\nslopes were negative, from $-2.6281$ to $-1.2688$, and a\nschool-by-hours product block did not improve fit ($F(3,232)=0.4345$,\n$p=.7285$). Leaving out any one school left the adjusted comparison\nbetween $-2.2289$ and $-1.7504$. The negative within-school pattern is\nconsistent with tutoring being allocated to pupils who are already\nstruggling, and these data cannot separate that allocation from any\nbenefit of tutoring itself. The intervals are model-based and\nappropriate for independent residual errors conditional on four fixed\nschools; real school data would require a residual-dependence check.\nObserved tutoring ranges from 0.1496 to 7.5722 hours per week, so we\nmake no statement about ten-hour provision. Answering the district's\nactual question would require either random assignment of tutoring or\nan explicit identification argument with adequate pre-allocation\nmeasurements and defensible assumptions about confounding, support and\nmeasurement. Baseline achievement would be relevant evidence, not a\nguarantee by itself.\n:::\n\nThe revision reports more numbers than the original, retracts the causal\nverb, names the estimand each number belongs to, states the support\nlimit, discloses the dependence question, and ends by saying what design\nwould answer the question. It is a weaker claim and a stronger piece of\nresearch.\n\n### A template and a closing audit table\n\n::: {.callout-tip title=\"Template for a credible regression claim\"}\nAmong **[population and unit]**, over **[supported range or observed\nlevels]**, **[focal contrast]** was associated with a **[estimate,\nunits]** difference in mean **[outcome]** (95 percent interval\n**[lower, upper]**), holding **[conditioning set]** fixed. This is a\n**[pooled / within-group / between-group / standardized]** comparison;\nthe **[alternative estimand]** comparison gives **[value]**, and the\ntwo differ because **[composition, adjustment, or unit reason]**. The\nanalysis rests on **[design]**, in which units entered through\n**[selection and retention description]**, and **[key predictor]** was\nmeasured by **[instrument, reliability]**. Across **[k]**\nprespecified specifications the estimate ranged from **[min]** to\n**[max]**. The interval **[includes / excludes]** no difference, so\nthe result is reported as **[an inconclusive or null comparison / a\ndifference of the stated size]** rather than as an absent effect, and\n**[plausible alternative explanation]** remains consistent with the\npattern. Because **[design, support, measurement, or dependence\nlimit]**, this result does not establish **[the specific unsupported\ncausal, individual-level, out-of-range, or population claim]**.\n:::\n\nFollowing one estimate from output to prose checks that its unit, scale,\ndirection, magnitude, uncertainty, weak or null status, claim mode,\nplausible alternative explanations and supported range all survive the\ntranslation. The template and the audit table's Stage 5 row name the\nweak or null status and the plausible alternative explanations\nexplicitly, so that a null is reported as a null rather than as an\nabsent effect and an alternative account of the pattern is not dropped\nbetween the results and the conclusion.\n\nThe table connects each audit question with a concrete failure case.\n\n| Stage | Audit question | Where it failed in this chapter |\n|:--|:--|:--|\n| 1. Question | Is the mode descriptive, associational, predictive or causal, and does the concluding verb match? | \"Tutoring lowers scores\" from a pooled associational fit |\n| 2. Unit | What does one row represent, and does the claim use the same unit? | Occupation-level income read as a worker-level gender gap |\n| 2. Entry and exit | How did rows enter and leave: eligibility, participation, attrition, missingness? | Selection on the outcome halving the admission-test slope |\n| 2. Dependence | Do rows carry independent information? | Classroom-assigned pupils analysed as independent rows |\n| 2. Measurement | What is each column's construct, units and reliability, and did they change across waves? | A noisy status proxy leaving residual confounding |\n| 3. Estimand | Is the target pooled, stratified, between-group, standardized or causal? | Berkeley's pooled and department-conditional odds ratios |\n| 3. Model | Is each adjustment variable justified by the estimand and the assumed structure, rather than being a mediator, collider or unsupported proxy? | Homework as a mediator; the portfolio as a collider |\n| 3. Support | Are the compared values observed jointly, and is any prediction interpolation? | Extending a line fitted below 8 study hours to 18 |\n| 4. Sensitivity | How much does the result move across defensible specifications, samples and codings? | The education coefficient from $-0.2179$ to 0.9370 |\n| 4. Uncertainty | Is the interval calibrated for the design that produced the data? | Nominal 95 percent intervals covering 48.2 percent of the time |\n| 5. Claim | Does the final sentence stay inside the unit, population, support, design and measurement, and do the direction, magnitude, uncertainty, weak or null status and plausible alternative explanations survive into it? | The audited paragraph above |\n\n: The regression-credibility audit, by stage. {#tbl-ch14-audit tbl-colwidths=\"[16,46,38]\"}\n\nThe author performs the audit first, as a documented self-evaluation,\nand any reader, collaborator, supervisor or reviewer repeats it\nafterwards on the accessible record. Its output is a profile of what\neach stage supports, together with the revision priorities that follow,\nrather than a total score, a pass mark or a publication verdict.\n\n## Reading Bridge\n\nA credible claim is an aligned one: the question, the estimand, the\ndesign, the rows, the fitted comparison and the final sentence must\ndescribe the same thing. Adjustment is a decision about an assumed\nstructure, helpful for a pre-treatment common cause and harmful for a\nmediator or a collider, and a coefficient that moves is not a\ndiagnosis. A pooled slope is a composition-weighted average of a\nwithin-group and a between-group slope, so a reversal is arithmetic\nabout weights rather than a paradox, and Berkeley's pooled,\nconditional and standardized comparisons are three answers to three\nquestions. Selection, restriction, attrition and regression to the\nmean change who is compared before any model runs; measurement error\nand aggregation change what a column and a row mean; fifteen\ndefensible specifications can spread an estimate across zero; and\ndependence follows the design, as Project STAR's clustered interval\nshowed. Randomization supplies a known allocation mechanism: conditional on\nits allocation variables, assignment is independent of pre-treatment\nattributes in the randomization distribution. It also fixes timing and\ndefines repetitions for design-based inference; a cluster-based model\ninterval remains an approximation. The\nquasi-experimental designs are named so that you can read them. Carry\nthe five-stage audit and the claim template into your own project,\nwhere the first question is not which model to fit but which\ncomparison the question asks for. Part Two turns to measurement\nitself, where the constructs this chapter asked you to audit become\nthe objects modelled.\n\nUse the table to revisit a tool when the question in your own study\nrequires it. The chapter's cases explain the comparisons needed here;\nthe references offer further depth without requiring every preceding\nchapter to be taken as one course.\n\n| Audit question | Where the tool was built |\n|:--|:--|\n| Is the question descriptive, associational, predictive or causal, and what population and unit does it name? | Chapter 1 |\n| What do the distributions and relationships look like before any model, and how much would they vary across samples? | Chapter 2 |\n| What does an interval mean, and what does a p-value not mean? | Chapter 3 |\n| Which comparison among group means is asked, and does its calibration cover the family it belongs to? | Chapter 4 |\n| Is the analysis reproducible from a clean session, with seeds and versions recorded? | Chapters 5 and 6 |\n| What does one slope mean, and where is it supported? | Chapter 7 |\n| What changes when a predictor is added, and what do the checks interrogate? | Chapter 8 |\n| How do factors, contrasts and nested comparisons work, and when does the uncertainty need a robust or clustered calculation? | Chapter 9 |\n| Does the comparison vary across groups or values, and is the probe value supported? | Chapter 10 |\n| How is a binary outcome modelled, and on which scale is the claim made? | Chapter 11 |\n| How are unordered, ordered and count outcomes kept distinct? | Chapter 12 |\n| Is the performance estimate honest and out of sample? | Chapter 13 |\n| Does the final claim match the comparison actually made? | Chapter 14 |\n\n: Each audit question and the chapter that built its tool. {#tbl-ch14-callback tbl-colwidths=\"[72,28]\"}\n\n\n## Key terms {.unnumbered}\n\nUse this reference to revisit the concepts introduced here. The Part One\nConcept Reference gives the broader reference and the principal home of\neach concept.\n\n| Term and common alternatives | Meaning or essential distinction |\n|:--|:--|\n| Directed acyclic graph (causal diagram; DAG) | A diagram whose arrows state assumed direct causes and whose directed paths cannot return to their starting point; it records assumptions that can be questioned, rather than conclusions produced by the data. |\n| Mediator (intermediate variable) | A variable caused by the focal predictor and lying on a path to the outcome; one kind of post-treatment variable, not a synonym for every variable measured after treatment. Conditioning on it changes a total-effect comparison; a direct causal reading needs additional identification and modelling conditions. |\n| Collider (common effect) | A variable caused by two others. A path through a collider is blocked unless the collider or a descendant is conditioned on; such conditioning can induce an association along that path. |\n| Adjustment set | The variables conditioned on for a stated estimand under an assumed structure, justified by that structure and the timing rather than by the available columns or a coefficient's movement. |\n| Aggregation reversal (Simpson's paradox; strict Simpson reversal) | A sign difference between a pooled comparison and the stratified or standardized comparisons, strict when every stratum points the opposite way to the pooled result; it arises from composition, not from a computational error. |\n| Within-group, between-group, and pooled comparison | Three estimands from one dataset: inside a level of the grouping variable, across group summaries, and across all rows ignoring the grouping, with the pooled slope a weighted average of the other two by the within and between shares of predictor variation. |\n| Direct standardization (standardized comparison) | Recomputing each group's summary under one declared common distribution of a stratifying variable; a third estimand rather than a compromise between the pooled and conditional comparisons. |\n| Range restriction (restriction of range) | Keeping only part of the observed range; restricting the predictor under a correctly specified linear model costs precision, apparent strength and support outside the window, while restricting on the outcome also moves the slope. |\n| Missingness mechanisms (MCAR; MAR; MNAR) | MCAR means missingness is unrelated to observed and missing values; MAR means it is unrelated to missing values conditional on observed information; MNAR means dependence on missing values remains. Complete-case validity depends on the target and mechanism, and MNAR requires assumptions not identified by the observed data alone. |\n| Attenuation from measurement error | In a single-predictor linear model, classical predictor error multiplies the population slope by reliability. With several predictors the direction can differ; a mismeasured control can leave residual confounding. |\n| Ecological inference (ecological fallacy) | Inferring an individual-level relationship from aggregate records. Aggregate and individual relationships can differ in sign and magnitude; the aggregate relationship alone does not identify the individual comparison. |\n| Specification sensitivity (multiverse analysis; analyst degrees of freedom) | The spread of an estimate across the defensible analyses that could have been run; a disclosure about specification, not evidence about an omitted common cause, selection or measurement shared by every version. |\n| Pseudoreplication (dependence as a design fact) | Treating dependent observations as independent replicates, misrepresenting uncertainty. The relevant dependence, sampling and assignment structure must be represented; its effect on a standard error depends on the comparison. |\n| Identification argument (design warrant) | The explicit reasons a comparison estimates the intended causal quantity, whether assignment or a named quasi-experimental design with its stated assumption; naming a design is not meeting its assumption. |\n| Bounded regression claim (credible-claim template) | A concluding statement whose unit, verb, conditioning set, supported range, design and disclosed sensitivity all match the analysis that produced it. |\n\n: Concepts introduced in this chapter. {#tbl-ch14-key-terms tbl-colwidths=\"[30,70]\"}\n\n## Further reading {.unnumbered}\n\n*Regression and Other Stories*\n(<https://avehtari.github.io/ROS-Examples/>) for regression to the mean\nin its Section 6.5 and its chapters on causal inference and adjustment\nin observational studies [@gelman2020]; *The Effect*\n(<https://theeffectbook.net/>) for a free book-length treatment of\ncausal diagrams and adjustment; *ModernDive* (2e)\n(<https://moderndive.com/v2/06-multiple-regression.html>) for the\nmultiple-regression chapter and its Simpson's paradox exercises;\n*Introduction to Modern Statistics*\n(<https://openintrostat.github.io/ims/>) chapters 1 and 2 on\nobservational data, confounding and study design; the R documentation\nfor `UCBAdmissions`, which carries its own worked reversal;\n@shadish2002 for quasi-experimental vocabulary; and @lundberg2021 on\nwriting the estimand before the model.\n\n## Exercises {.unnumbered}\n\n<!-- prompt-id: CH14-E01 -->\n### Exercise 1: Choose the estimand before the model (Foundational) {.unnumbered #ex-ch14-01}\n\nA\ndistrict has the tutoring records of this chapter: 240 pupils in four\nschools, with a pooled slope of 6.5784, a school-adjusted slope of\n$-2.0018$, and a between-school slope of 7.8372 points per hour, and\nwith $w_W=.1279$ and $w_B=.8721$.\n\n1. For each question below, say\nwhich of the three numbers answers it and write that answer as one\nsentence naming the unit and the comparison: (a) in this district, do\npupils who receive more tutoring have higher or lower reading scores?\n(b) among pupils at the same school, do those receiving more tutoring\nscore higher or lower? (c) do schools that provide more tutoring have\nhigher average scores?\n\n2. A colleague says the pooled slope is wrong\nand the adjusted slope right. Use the decomposition to explain why\nthat framing is incorrect, and give one question for which the pooled\nslope is the correct target.\n\n3. Suppose the four schools were made\nmuch more alike in average tutoring hours while every within-school\nslope stayed identical: predict what happens to $w_B$ and justify it\nfrom the decomposition.\n\n4. The district now asks whether expanding\ntutoring would raise scores. Explain why none of the three numbers\nanswers that, and name the design feature that would be needed.\n\n<!-- prompt-id: CH14-E02 -->\n### Exercise 2: Read the Berkeley table without overreading it (Foundational) {.unnumbered #ex-ch14-02}\n\nAmong 4,526 decisions in six departments, the pooled\nadmission odds ratio for women against men was 0.5432 (95 percent\ninterval [0.4792, 0.6156]); conditioning on department it was 1.105\n([0.9431, 1.2948]); the model letting the odds ratio vary by department\nimproved fit with a deviance of 20.2043 on 5 df, $p=.0011$. Men sent\n.3066 and .2081 of their applications to departments A and B, whose\nadmission rates were .6442 and .6325; women sent .0589 and .0136.\n\n1. Write one sentence interpreting each odds ratio, making clear what is\nheld fixed and which population of decisions is described.\n\n2. Using\nthe shares and rates above, explain why the two estimates differ, without\nusing the word bias.\n\n3. A reader concludes that the admissions\nprocess was fair. Give two distinct reasons this is unsupported, one\nabout what conditioning on department does to the question and one\nabout what an administrative census of six departments can establish.\n\n4. Explain what the varying-odds-ratio result implies about reporting\none adjusted number, and say what you would report instead.\n\n<!-- prompt-id: CH14-E03 -->\n### Exercise 3: Classify the adjustment (Foundational) {.unnumbered #ex-ch14-03}\n\nFor each\nscenario, state the assumed role of the named variable using the three\nminimal structures, say whether adjusting for it helps or harms the\nstated target, and say what the coefficient would estimate instead if\nit harms.\n\n1. Target: the total effect of a randomized reading\nprogramme on comprehension; candidate: minutes of independent reading\nduring the programme year. Assume the programme increases reading time\nand reading time affects comprehension. Now add family support as\na cause of both reading time and comprehension. Predict whether randomizing\nthe programme still justifies its total-effect comparison, and whether\nadjusting for reading time alone now identifies its direct effect.\n\n2. Target:\nthe total effect of neighbourhood income on adolescent mental\nhealth; assume parental education predates neighbourhood selection\nand causes both neighbourhood income and mental health. Candidate:\nparental education.\n\n3. Target: the effect of an after-school\nprogramme on attendance, in a study whose analytic sample holds only\npupils who returned an optional end-of-year survey, where both\nparticipation and family engagement raise the chance of returning it,\nand family engagement also causes attendance.\n\n4. Target: the association between class size and achievement across\nschools; candidate: teacher-reported classroom disruption, measured at\nthe end of the year. Only timing is known here; say what additional\ninformation would be needed before assigning a causal role.\n\n5. For scenario 3, explain why the harm occurs\neven though the survey variable never enters the model.\n\n<!-- prompt-id: CH14-E04 -->\n### Exercise 4: Separate the artifact from the effect (Foundational) {.unnumbered #ex-ch14-04}\n\nFour hundred pupils were measured twice on the same reading construct\nwith a reliability of .64. The lowest-scoring 15 percent, 60 pupils,\naveraged 33.5726 at pretest and 39.0568 at posttest, a gain of 5.4842\nwith a paired $t(59)=4.8378$ and interval [3.2158, 7.7526]. Splitting\nthose 60 pupils at random into 30 receiving a programme and 30 not\ngives a between-arm difference of 1.9618 ([$-2.5867$, 6.5103]). In a\nseparate admission study with a true slope of 0.02 grade points per\ntest point, the full 500-applicant fit gives 0.021 (SE 0.0014,\n$R^2=.3091$); keeping only the 148 applicants scoring 110 or more\ngives 0.0234 (SE 0.0053, $R^2=.1178$); keeping instead the 261\napplicants whose grade point average exceeded 3 gives 0.0106.\n\n1. Explain the 5.4842-point gain without referring to any programme, and\nname the two conditions that together produce it.\n\n2. Say what the\nrandomized split changes and why the second analysis is the credible\none.\n\n3. Compare what predictor restriction and outcome restriction do\nto the slope, the SE and $R^2$, and say which of the three quantities\nis the odd one out.\n\n4. Explain in one sentence why collecting more\npupils would not repair the first analysis.\n\n<!-- prompt-id: CH14-E05 -->\n### Exercise 5: Name the unit before naming the gap (Integrative) {.unnumbered #ex-ch14-05}\n\nIn\na generated economy of 60 occupations with 40 workers each, women earn\n2 thousand dollars more than men inside every occupation, and\noccupations with more women pay less. Three fitted numbers are\n$-3.0228$ from a worker-level regression of income on being a woman,\n1.9869 from the same regression adding occupation indicators, and\n$-14.3063$ from a regression of occupation mean income on the\noccupation's share of women. In the real 1971 Canadian census records,\noccupation mean income on the percentage of incumbents who are women\ngives $-0.059$ thousand dollars per percentage point ([$-0.0829$,\n$-0.0352$], $R^2=.1945$).\n\n1. State, for each generated number, the\nunit of the rows and the question it answers.\n\n2. Explain why the\nworker-level pooled number is negative although its rows are\nindividuals.\n\n3. Write the one defensible sentence the real records\nsupport, then the sentence a careless reader would write instead,\nmarking the word that makes it indefensible.\n\n4. State what further\ndata would answer the individual-level question, and why no model\napplied to the 102 occupation rows can supply it.\n\n<!-- prompt-id: CH14-E06 -->\n### Exercise 6: Choose the uncertainty, then name what a design supplies (Integrative) {.unnumbered #ex-ch14-06}\n\nIn Project STAR the small-minus-regular kindergarten\nreading difference on 3,745 observed records is 5.8151 points, with\nstandard errors of 1.0377 treating pupils as independent, 1.0416 with\nHC3, and 1.8476 clustering pupils within their 79 schools; use\n$t_{.975}=1.9606$ for the first two and 1.9908 for the third. In a\nseparate check of 20 classrooms of 15 pupils with classroom-level\nassignment and a true effect of zero, nominal 95 percent intervals\ncovered zero in 48.2 percent of 1,000 repetitions from pupil rows and\n94.3 percent from classroom means.\n\n1. Give the interval under the\nfirst and the third calculation. Explain when the clustered interval\nis appropriate, distinguish assignment within schools from dependence\nwithin schools, and state the independence approximation it uses.\n\n2. Explain what the\ncoverage check adds that the single STAR comparison cannot show.\n\n3. Name three things randomization supplied in STAR that adjustment of an\nobservational file could not.\n\n4. Name two limitations of the STAR\nresult that randomization does not remove.\n\n## Appendix A: Composition Arithmetic {.unnumbered}\n\n### How the pooled slope splits {.unnumbered}\n\nThe decomposition in Section 3.2 follows by separating a pupil's deviation\nfrom the district mean into a deviation from the school mean and the\nschool mean's deviation from the district mean:\n\n$$x_{ig}-\\bar x=(x_{ig}-\\bar x_g)+(\\bar x_g-\\bar x).$$\n\nSquaring and summing gives a within term, a between term and a cross-term.\nWithin each school, $\\sum_{i\\in g}(x_{ig}-\\bar x_g)=0$, so the cross-term\nvanishes. The same argument for the product of the $x$ and $y$\ndeviations gives\n\n$$\nS_{xx}=S_{xx}^{W}+S_{xx}^{B},\\qquad\nS_{xy}=S_{xy}^{W}+S_{xy}^{B}.\n$$\n\nDivide by $S_{xx}$ and multiply each component by its own denominator:\n\n$$\n\\frac{S_{xy}}{S_{xx}}=\n\\frac{S_{xx}^{W}}{S_{xx}}\\frac{S_{xy}^{W}}{S_{xx}^{W}}+\n\\frac{S_{xx}^{B}}{S_{xx}}\\frac{S_{xy}^{B}}{S_{xx}^{B}}.\n$$\n\nThe two ratios at the right are the common within-school slope and the\nbetween-school slope weighted by school size. Because this example has\n60 pupils in every school, ordinary regression on the four school means\ngives that same between-school slope. With unequal school sizes, the\nbetween-school fit for this identity must weight each school by its size.\nThe weights displayed as .1279 and .8721 combine slopes displayed as\n$-2.0018$ and 7.8372 to recover 6.5784 from the full-precision values.\nRounded ingredients can give a slightly different last digit.\n\nThe identity explains the source of a pooled coefficient; it does not\nestablish that one component has a causal interpretation. Nor does\nreducing the between-school weight alone guarantee a smaller pooled\nslope: the between-school slope can change at the same time.\n\n### Standardization changes the weights {.unnumbered}\n\nFor gender $a$ and department $d$, let $p_{ad}$ be the admission rate and\n$q_{ad}$ the share of that gender's applications sent to the department.\nThe observed pooled rate is\n\n$$p_a=\\sum_d q_{ad}p_{ad}.$$\n\nChoose one declared set of weights $q_d$ that sums to one. The standardized\nrate is $p_a^*=\\sum_d q_dp_{ad}$, so the contrast becomes\n\n$$p_{\\mathrm{women}}^*-p_{\\mathrm{men}}^*\n=\\sum_d q_d(p_{\\mathrm{women},d}-p_{\\mathrm{men},d}).$$\n\nUsing each department's share of all 4,526 decisions gives 42.9955 percent\nfor women and 38.7319 percent for men. The 4.2637-point difference concerns\nthat common distribution. It is a rate difference, not the conditional\nodds ratio from a logistic model; changing the scale and changing the\nweights are separate decisions.\n\n### The change-score identity {.unnumbered}\n\nLet $X$ be pretest and $Y$ posttest on their original scales. The fitted\nslope from regressing change $Y-X$ on $X$ is exactly\n\n$$\nb_{Y-X,X}\n=\\frac{\\operatorname{Cov}(X,Y-X)}{s_X^2}\n=\\frac{\\operatorname{Cov}(X,Y)}{s_X^2}-1\n=r\\frac{s_Y}{s_X}-1=b_{Y,X}-1.\n$$\n\nIn the generated records it is $-0.3707$. If both measurements are first\nstandardized separately, their SDs are one and the corresponding slope\nis $r-1=-0.3629$. The raw-scale expression reduces to $r-1$ only when the\ntwo sample SDs agree. In the generating population of Section 4.1 they\nare equal, so the population change slope is $\\rho-1=.64-1=-0.36$.\nSampling variation need not preserve equality of the two sample SDs.\n\n## Appendix B: Extended Selection, Support, and Dependence Studies {.unnumbered}\n\n### Reliability changes the apparent gain {.unnumbered}\n\nKeep the 400 stable abilities and the seed 14002 recipe, but change both\nmeasurement-error SDs together to 2, 6 or 10. Select the lowest 15 percent\nseparately in each version. The error variance increases while the true\nability variance stays at $8^2$, so reliability decreases. Every\nprogramme effect remains zero.\n\n\\Needspace{10\\baselineskip}\n\n| Error SD | Reliability | Observed correlation | Apparent gain | Paired $p$ |\n|--:|--:|--:|--:|--:|\n| 2 | .9412 | .9385 | 1.0570 | .0082 |\n| 6 | .6400 | .6371 | 5.4842 | < .0001 |\n| 10 | .3902 | .3952 | 13.1818 | < .0001 |\n\n: Less reliable selection produces a larger apparent gain in this recipe. {#tbl-ch14-reliability tbl-colwidths=\"[15,20,23,22,20]\"}\n\nThe lower reliability gives unusually low measurement errors a larger\nrole in who enters the selected group. Repeating the measurement does\nnot repeat those errors, and the selected group rises further. The\np-values test zero mean change among selected records; they cannot\nconvert that change into a programme effect.\n\n### Repeated sampling checks an interval procedure {.unnumbered}\n\nFor the classroom recipe in Section 6.3, each of 1,000 repetitions\ndraws 20 classroom assignments, 20 classroom offsets and 300 pupil\nerrors, in that order, under seed 14013. Each repetition fits the\npupil-row regression and the regression on 20 classroom means, then\nrecords whether its 95 percent interval covers the true effect zero.\nWith equal classroom sizes and classroom-level assignment, aggregation\nleaves the estimated contrast unchanged but represents the independent\nunits in its standard error.\n\n\\Needspace{10\\baselineskip}\n\n| Calculation | Unit treated as independent | Coverage in 1,000 repetitions |\n|:--|:--|--:|\n| Pupil-row regression | 300 pupils | 48.2% |\n| Classroom-mean regression | 20 classrooms | 94.3% |\n\n: Interval coverage under the declared classroom recipe. {#tbl-ch14-coverage tbl-colwidths=\"[34,34,32]\"}\n\nCoverage is a property of repeated intervals under a specified\ndata-generating process. It cannot be read off a single interval, and\nthese results do not certify either procedure under every possible\nclassroom process. Here the classroom-mean interval has the usual\nNormal linear-model justification conditional on nondegenerate\nclassroom assignments. The pupil-row calculation ignores the common\noffset and counts information repeatedly.\n\n**Extended practice 1 (Integrative).** Change the design to 40 classrooms\nwith eight pupils each. Predict which change matters for independent\ninformation, repeat the coverage comparison and explain the difference.\n\n**Extended practice 2 (Integrative).** Repeat the fifteen specifications\nusing log income. Explain how the estimand changes and why unadjusted\nresidual sums of squares or AIC values computed on different response\nscales cannot directly rank the two sets.\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_14_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}