{
  "hash": "8f702a21bdca133da3f7ebf7b263c932",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How to Read a Quantitative Study as an Argument\"\nsubtitle: \"Argument Chapter A\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nreferences:\n  - id: bloom2015wfh\n    type: article-journal\n    title: \"Does working from home work? Evidence from a Chinese experiment\"\n    author:\n      - family: Bloom\n        given: Nicholas\n      - family: Liang\n        given: James\n      - family: Roberts\n        given: John\n      - family: Ying\n        given: Zhichun Jenny\n    issued:\n      date-parts: [[2015]]\n    container-title: The Quarterly Journal of Economics\n    volume: 130\n    issue: 1\n    page: 165-218\n    DOI: 10.1093/qje/qju032\n  - id: realinho2022\n    type: article-journal\n    title: \"Predicting student dropout and academic success\"\n    author:\n      - family: Realinho\n        given: Valentim\n      - family: Machado\n        given: Jorge\n      - family: Baptista\n        given: Luís\n      - family: Martins\n        given: Mónica V.\n    issued:\n      date-parts: [[2022]]\n    container-title: Data\n    volume: 7\n    issue: 11\n    page: 146\n    DOI: 10.3390/data7110146\n  - id: uci697\n    type: dataset\n    title: \"Predict students' dropout and academic success\"\n    author:\n      - family: Realinho\n        given: Valentim\n      - family: Vieira Martins\n        given: Mónica\n      - family: Machado\n        given: Jorge\n      - family: Baptista\n        given: Luís\n    issued:\n      date-parts: [[2021]]\n    publisher: UCI Machine Learning Repository\n    DOI: 10.24432/C5MC89\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    documentclass: scrartcl\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    latex-auto-install: false\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - ../koma_heading_tags.tex\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{16\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n{{< pagebreak >}}\n\n::: {.callout-note title=\"Chapter overview\"}\nRead one research question and the answer a study offers. Follow the specific\ninformation supporting that answer across the paper, protocol, measurements\nand analytical materials. Distinguish a procedure from its rationale, an\nanalysis from its claim, and identifying an argument from judging its quality.\nA documented construction history shows how researchers produce that support.\nThe principal case is an invented feedback experiment; shorter prediction and\nregression reports show how the reading transfers. All necessary records are\nsupplied here. This optional argument tutorial requires no programming and is\nnot a prerequisite for the numbered methods chapters.\n:::\n\nA published study asks a question and offers an answer. Between them are\nobservations, the circumstances in which they arose, reasons for trusting a\ncomparison, analytical work, and an interpretation. Much of that support lies\noutside the sentence reporting the main result. A protocol may explain\nallocation, an instrument may reveal what an outcome measures, and a supplement\nmay show what changed when an unusual observation was omitted. Learning to\nconnect those records is part of understanding quantitative research.\n\nThe invented feedback study will provide a complete example. Its reported\nassignment effect is 2.5 points, with a 95% interval from 1 to 4 points.\nReading those numbers alone cannot tell us whether the study compared students\nor classes, what the score represents, or why the comparison could support an\neffect of assignment. The following sections make these connections explicit,\nthen give less structured cases in which you must decide which connection matters.\n\n## From a Research Question to a Traceable Argument\n\n### Start with what the study asks and answers\n\nConsider two extracts from the invented study. Their labels are illustrative\nlocations in the teaching record, not quotations from an actual publication.\n\n> **Paper, aim:** We examined whether assigning explanatory rather than usual\n> feedback changes average delayed achievement for the 480 eligible students\n> in 24 participating classes.\n>\n> **Protocol, allocation:** Twelve classes were randomly assigned to each\n> format across the full pool of 24 classes. The comparison uses equally\n> weighted class means and an uncertainty procedure reflecting class assignment.\n\nThe aim can be restated as a question: *What is the average effect of assigning\nexplanatory rather than usual feedback on delayed achievement for these eligible\nstudents?* This is a reader's formulation of the stated aim. It names a causal\ncomparison, an outcome and a scope. An aim such as \"improve education\" would\nneed these details before it could identify a quantitative question.\n\nThe **estimand** is the target quantity, here the student-average assignment\neffect for the eligible cohort. The **estimate** is the reported 2.5-point\nresult. The **reported answer** is the study's conclusion about that question.\nIt can be cautious or overstated; the reader first identifies the answer that\nwas actually given. Replacing it with a more defensible statement is an\nevaluation and revision, not a discovery about what the original sentence said.\n\nA **question-answer pair** gives an argument its task. Evidence and methods\nare relevant through their contribution to this task. A well-computed coefficient\ncan still concern the wrong outcome, follow-up time or unit. Conversely, a\ncarefully supported answer can remain inconclusive. A research argument need\nnot end with a positive result to succeed.\n\n### Four functions in two linked layers\n\nAn **argument component** names a function of information. Evidence supplies\nobservations and their production record; Justification supplies invoked\nreasons and conditions; Inference connects those contributions through analysis\nand reasoning; a bounded Claim states the conclusion with its limits.\nThe statistical and substantive layers are coordinated parts of one argument.\nThe statistical layer follows the numerical target and analysis; the substantive\nlayer keeps their meaning connected to the people, practices and question.\n\n| Component | Statistical function | Substantive function | Connection |\n|:--|:--|:--|:--|\n| **Evidence (E)** | **STAT-E:** information about the observations, variables, and procedures through which the analysis data were produced or acquired | **SUB-E:** information about the people, setting, activities, and substantive meaning represented by those data | SUB-E **situates** STAT-E |\n| **Justification (J)** | **STAT-J:** reasons and conditions invoked to support the intended statistical comparison and inference | **SUB-J:** domain-based reasons supporting measurement meaning, implementation, explanation, and applicability | SUB-J **augments and contextualizes** STAT-J |\n| **Inference (I)** | **STAT-I:** the analytical reasoning and work connecting evidence and justification to statistical conclusions, including estimates, uncertainty, comparisons, and checks | **SUB-I:** interpretation of that statistical inference in substantive terms, retaining the relevant uncertainty and conditions | SUB-I **interprets** STAT-I |\n| **Bounded claim (C)** | **STAT-C:** the reported statistical conclusion about the estimand, with uncertainty, conditions, and scope | **SUB-C:** the reported question-facing answer, with its substantive scope, qualifications, and unresolved matters | SUB-C **bounds** the substantive reach of STAT-C |\n\n: Four component functions and their linked meanings. {#tbl-supa-components tbl-colwidths=\"[13,31,31,25]\"}\n\nIn the feedback study, class assignments and assessment records contribute\nEvidence. The reason that random allocation supports the assigned-group\ncomparison contributes Justification. Computing the mean contrast, its interval\nand influence checks contributes Inference. Saying that assignment increased\naverage assessed performance in these classes contributes a bounded Claim.\nThese functions are not section headings: Methods can contain both a procedure\nand its rationale, and Results can contain both a calculation and a conclusion.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Four functions in two linked layers. Evidence plus Justification support Inference, which supports a bounded Claim; vertical links identify the substantive contribution.](chapter_arg_a_files/figure-html/fig-supa-functions-1.png){#fig-supa-functions fig-pos='H' fig-alt='Substantive Evidence, Justification, Inference and Claim form the top row. The statistical functions form the bottom row. Downward links say situates, augments and contextualizes, interprets, and bounds substantive reach. Horizontal links show E plus J supporting I, and I supporting C. These are logical support links, not causal effects or a time sequence.' width=672}\n:::\n:::\n\n\nThe score's content situates the statistical measurement. Reasons why the\nassessment represents the taught objectives augment its interpretation.\nReading the interval in course terms interprets the numerical result. Limiting\nthe answer to assessed performance in these classes bounds its substantive\nreach. Numerical statements can do substantive work: \"one application task\"\nis a domain interpretation of two score points. The layers are not numbers\nversus words, and substantive reasoning starts when the question and measures\nare chosen, not only after calculations finish.\n\n### Connect a function to an inspectable location\n\n**Traceable information** is specific study content through which a component's\nfunction can be identified. A **documentary location** is where that content\ncan be inspected: a paragraph, table, protocol item, codebook entry or analysis\nfile. \"Research design\" names a topic. \"Twelve classes were randomly assigned\nto each format across the full class pool\" identifies a particular procedure.\n\nThe useful connection is **question-answer pair → component function → specific\ninformation → documentary location**. You can follow it in either direction.\nStarting from Evidence, look for how groups arose; starting from an allocation\nparagraph, identify its contribution to evidence production. Keep enough of the\nlocation for another reader to find the same information.\n\nProfessional knowledge helps recognize the contribution. Knowing what a\nconfidence interval concerns helps identify which estimate's uncertainty is\nreported. Recognizing a reason does not certify its quality. \"Our software\nestimates causal effects\" is still a reason the authors offered, although\nrunning software cannot supply a causal design. Reading records the offered\nreason; evaluation judges it.\n\nWhen information remains unclear, explain the particular gap. \"The article\nreports 480 scores but the participant-flow table reports 460; neither explains\nthe difference\" is more informative than an overall label. A missing account\nin accessible materials does not establish that the action never occurred.\nDo not fill the gap with a procedure you would have preferred. These habits\nmake a reading useful without turning every paper into a compulsory checklist.\n\n## Tracing Information Through E, J, I, and C in Both Layers\n\nThe following tables collect fifteen recurring information types: four for\nEvidence, four for Justification, five for Inference and two for Claim. They\nare reference aids, not an exhaustive list to memorize. The information in an\nactual reading is the particular study's account. Return to a row when a\nstatistical term or an unfamiliar analysis makes its function difficult to see.\n\n### Statistical Evidence: observations and their production\n\nSTAT-E includes observations and the record of their production.\n@tbl-supa-stat-e distinguishes the structure of the records,\nmeasurement, selection and implementation, and the observations\nactually analyzed.\n\n```{=latex}\n\\Needspace{13\\baselineskip}\n```\n\nAn *observed variable* is a characteristic recorded for study units. In the\nfeedback-format example, each student has an assessment score and a\nrecorded feedback format. The score is numerical, so a mean and a\nmeasure of variation can help describe it. Practice format is\ncategorical, so counts or percentages show how students are distributed\nacross the categories. The recorded values contribute to STAT-E;\ncalculations that summarize them contribute to STAT-I.\n\nA variable's *role* concerns how it enters a particular analysis. An *outcome*\n(or dependent variable) is what the analysis describes, explains, or\npredicts. If the question asks how assessment scores differ between\nformats, score is the outcome and feedback format identifies the\ncomparison groups. A predictor, such as a prior assessment score, can\nhelp model the outcome. Papers may use \"independent variable\" for a\npredictor or an experimentally manipulated condition. Identify the role\nfrom the question and analysis, then follow the design and justification\nto understand whether the relationship receives a causal interpretation.\nThe same variable can serve a different role in another analysis.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\begingroup\n\\small\n\\setlength{\\tabcolsep}{4pt}\n\\renewcommand{\\arraystretch}{1.08}\n```\n\n| Traceable information | What to identify | Common cases | Likely documentary location |\n|:----------------------|:-----------------|:-------------|:----------------------------|\n| Data structure, units, and variable roles | What a record represents; repeated or grouped observations; outcome and predictor roles. | Students are recorded within classes; assessment score is the outcome and assigned format is the grouping variable. | Data description; Measures; dictionary |\n| Measurement scales, instruments, and procedures | The response scale, instrument, scoring, and administration actually reported. | Responses use ordered categories; an assessment is scored from 0 to 40 and administered two weeks after instruction. | Measures; instrument; scoring guide; Procedures |\n| Design and implementation information | Whom the study concerns; sample selection or recruitment; assignment or exposure; comparison structure and timing. | Classes are recruited from schools and randomly assigned to formats; another study observes existing exposures without assigning them. | Participants; Design; Procedures; protocol |\n| Analysis sample, exclusions, and missing data | Which units and observations entered each analysis, their counts, and reported omissions or exclusions. | Some recruited participants lack follow-up scores; an analysis uses the records meeting a stated inclusion rule. | Participant flow; Results; data-processing record |\n\n: Statistical Evidence: Traceable Information {#tbl-supa-stat-e tbl-colwidths=\"[24,27,30,19]\"}\n\n*Note.* Identify both the number entering the study and the number\nincluded in each analysis. A participant may contribute several\nobservations, so distinguish participant counts from observation counts.\n\n```{=latex}\n\\endgroup\n```\n\n**Measurement information is classified by its use.** The instrument,\nscoring, and administration record contribute to STAT-E. Reasons for\nusing those measurements in a statistical procedure belong in STAT-J.\nWhat the scores mean substantively belongs in SUB-E, while reasons\nsupporting that meaning belong in SUB-J. To identify Justification,\nlook for the reasons given for using or interpreting the instrument.\n\n### Statistical Justification: invoked reasons and conditions\n\nSTAT-J identifies the reasons and conditions the study invokes for its\nstatistical reasoning. @tbl-supa-stat-j separates support from the\ndesign, sample-size planning, method choice, and assumptions.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\begingroup\n\\small\n\\setlength{\\tabcolsep}{4pt}\n\\renewcommand{\\arraystretch}{1.08}\n```\n\n| Traceable information | What to identify | Common cases | Likely documentary location |\n|:----------------------|:-----------------|:-------------|:----------------------------|\n| Design-based support for inference | How sampling, assignment, or comparison design is invoked to support the intended inference. | Probability sampling is invoked for population inference; random assignment is invoked to support an assigned-group comparison. | Design rationale; sampling plan; protocol |\n| Sample-size, power, and precision rationale | Why the amount of evidence was planned in relation to an inferential goal. | Planned sample size aims at a stated confidence-interval width or power for a specified effect. | Sample-size calculation; protocol; planning supplement |\n| Rationale for selecting statistical methods and models | Reasons connecting the chosen procedure to the estimand, measurement scale, or data structure. | Welch's method is chosen because it allows unequal group variances; within-class dependence is allowed because students share classes. | Statistical Analysis; analysis plan |\n| Statistical assumptions invoked | Conditions the study relies on for its comparison, model, or uncertainty calculation. | Independence between observations is assumed for a standard-error calculation; a model assumes a linear relationship. | Statistical Analysis; assumptions statement; technical supplement |\n\n: Statistical Justification: Traceable Information {#tbl-supa-stat-j tbl-colwidths=\"[24,27,30,19]\"}\n\n*Note.* Alongside the named plan or method, identify the reasons invoked\nfor its use. Evaluate those reasons' adequacy separately.\n\n```{=latex}\n\\endgroup\n```\n\n```{=latex}\n\\Needspace{13\\baselineskip}\n```\n\n**Sampling and assignment are distinct parts of study design.** Sampling\nconcerns which units enter a study; assignment concerns which conditions\nthey receive. Random sampling provides a basis for population inference\nunder the sampling design, contributing to generalizability or external\nvalidity. Random assignment supports a causal comparison of assigned\nconditions, contributing to internal validity. Both forms of support\ndepend on the relevant implementation and analysis conditions. A study\nmay use either form of randomization or both. To trace assignment, look\nfor the allocation procedure used to form the groups. A protocol\ndocuments the planned procedure; implementation records document\nwhat was carried out.\n\n**A procedure and its rationale do different work.** \"Students were\nrandomly assigned\" records a production procedure in STAT-E.\n\"Random assignment provides the basis for estimating the effect of\nassignment from the comparison\" identifies the reason invoked in\nSTAT-J. Locate this connection in an explicit rationale or by following\nthe documented links among design, estimand, and analysis.\n\n```{=latex}\n\\Needspace{8\\baselineskip}\n```\n\nLikewise, \"100 participants were analyzed\" records the analysis sample.\n\"The sample size was planned to achieve the desired precision\" supplies\na planning rationale. *Precision* concerns estimation uncertainty;\n*power* concerns the probability of rejecting a null hypothesis under\na specified alternative and procedure. The reader identifies the stated\ngoal before considering whether the planning was adequate.\n\nA statistical *model* represents selected relationships or variation\nmathematically. When a study invokes an assumption as a condition\nsupporting inference, that contribution belongs in STAT-J. The\nspecification actually fitted, and the reported analytical checks,\ncontribute to STAT-I. A passage can describe the fitted model and\ninvoke its assumptions as support; identify what each contribution\ndoes. \"We used SPSS\" helps identify the software used for computation.\nLook for the method-selection rationale to identify the reasons for\nthe analytical choice.\n\n### Statistical Inference: analytical work and its consequences\n\nSTAT-I is often the most demanding component to understand, both\ntechnically and in its statistical reasoning, especially in large-scale,\ncomplex studies. It traces the central statistical information of the\nargument: how evidence, analyzed under the study's stated conditions and\njustification, supports a statistical conclusion. Understanding this\ntransition requires reasoning about variation, uncertainty, models, and\nalternative analyses. Some of these ideas challenge everyday intuition,\nso learning to follow the reasoning is as important as learning the\nprocedures. Much of the statistical reasoning developed in later chapters\ntherefore relates directly to STAT-I. Its contribution becomes clear\nthrough its connections with evidence production, justification,\nsubstantive interpretation, and the bounded answer.\n\nSTAT-I connects the estimand with the analysis performed, its results,\nuncertainty, and relevant checks. *Model building* specifies the\nstatistical relationships to be estimated. *Diagnostics* examine how\nthe fitted model and estimation procedure behave; *sensitivity analysis*\nexamines how results change under alternative analytical choices.\nA *statistical hypothesis* expresses a proposition to be examined,\nsuch as a zero mean difference. @tbl-supa-stat-i connects these\nactivities to their traceable information and reported results.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\begingroup\n\\small\n\\setlength{\\tabcolsep}{4pt}\n\\renewcommand{\\arraystretch}{1.08}\n```\n\n| Traceable information | What to identify | Common cases | Likely documentary location |\n|:----------------------|:-----------------|:-------------|:----------------------------|\n| Describing data and relationships | How observations and associations are summarized. | Means and standard deviations describe scores; a correlation describes a linear association between two numerical variables. | Descriptive tables; Results; figures |\n| Model building and estimation | Model specification in equations, diagrams, or syntax; connection to declared estimands; estimation procedure, computational implementation, and point estimates. | A regression equation specifies score differences by feedback format; software estimates its coefficients and the declared contrast. | Statistical Analysis; model diagram; Results; syntax or code |\n| Model diagnostics, modification, and sensitivity analysis | Fit and computational checks; model or analysis changes; sensitivity to analytical choices or priors; predictive validation and its results. | Residuals suggest a curved relationship; an alternative prior changes estimates; held-out observations assess prediction. | Diagnostic figures; analytical supplement; validation results; code |\n| Statistical uncertainty and interval estimates | The reported uncertainty for an estimate or prediction, including its procedure and stated level. | A standard error and confidence interval accompany a mean difference; a prediction interval accompanies a new-case prediction. | Results; interval tables; figures |\n| Statistical hypotheses, testing, and comparison | Hypotheses or restrictions examined; tests and comparison criteria; competing models where relevant; test statistics, p-values, or other comparison results. | A test examines a zero mean difference or equal coefficients; competing models are compared by a test or predictive performance. | Hypothesis statement; Statistical Analysis; Results; model-comparison table |\n\n: Statistical Inference: Traceable Information {#tbl-supa-stat-i tbl-colwidths=\"[24,27,30,19]\"}\n\n*Note.* Some descriptive questions are answered by summaries alone.\nFor analyses and modifications, record whether they were prospectively\nspecified, exploratory, or revised when known. \"Primary\" describes\npriority. Separately describe when and how the analysis was specified or\nchanged, and whether relevant outcomes had already been examined.\n\n```{=latex}\n\\endgroup\n```\n\n**Connect a calculation to the question it addresses.** A group mean\ndifference may estimate the declared contrast between feedback formats.\nFor a question about how two numerical variables vary together, a\ncorrelation summarizes their linear association. Regression describes\nan outcome in relation to one or more predictors; the coefficients\naddress particular relationships in the fitted model. The reported\ncalculation and its role in answering the question belong together\nwhen you read STAT-I.\n\n**Follow model building through to the estimates.** An equation or a\nstatistical path diagram might represent assessment score as an outcome\nrelated to feedback format and prior score. Identify how the model\nrepresents the declared estimand, which could be a coefficient or a\ncontrast calculated from several coefficients. Then follow the\nestimation procedure to its point estimates. Computational information\nmay appear in R scripts, software syntax, menu settings, or a Methods\ndescription; each can help identify what was implemented.\n\nSpecifying the model and fitting it contribute to STAT-I. Reasons for\nchoosing that specification or estimation method contribute to STAT-J.\nLikewise, a diagram expressing the fitted statistical relationships\nhelps trace STAT-I, while a diagram explaining a substantive mechanism\nmay contribute to SUB-J. The diagram's contribution depends on what\nit represents in this study.\n\n```{=latex}\n\\Needspace{10\\baselineskip}\n```\n\n**Distinguish variation in the observations from estimation uncertainty.**\nStudents' assessment scores vary, and a standard deviation describes\nthat variation. An estimated mean difference also has uncertainty:\nits standard error describes how the estimate would vary under the\nspecified sampling, assignment, or model conditions. A confidence\ninterval concerns the mean difference. For example, an interval from\n1 to 5 points expresses uncertainty about the difference between means,\nrather than the range of individual students' scores.\n\nA p-value addresses a null hypothesis under the test's assumptions;\nit is not the probability that the null is true. These concepts receive\nfuller statistical treatment later. For now, identify what each output\nconcerns and follow the reported uncertainty into the substantive\ninterpretation and the study's conclusions.\n\n**Follow the checks, changes, and their consequences.** Diagnostics can\nexamine model fit, unusual observations, or whether the estimation\nalgorithm reached a stable solution. A modification changes the model\nor analysis, for example by adding a curved relationship after examining\nresiduals. Record what changed, why the study says it changed, and the\nresult. A stated reason for the change may also contribute to STAT-J.\n\nSensitivity analysis asks how estimates or conclusions change under\nalternative choices or assumptions. In a Bayesian analysis, a *prior\ndistribution* expresses information or assumptions about model\nparameters before incorporating the current data. Repeating an analysis\nwith alternative priors can show how sensitive its findings are to those\nchoices. The prior used is part of the model specification; reasons\ninvoked for choosing it can contribute to STAT-J. Predictive validation\nasks how the model predicts outcomes,\nfor example for held-out observations. Checks, modifications, and\nsensitivity analyses can inform one another. During reading, identify\nthe study's reported checks and assessments; quality evaluation then\nconsiders whether they provide adequate support.\n\n**Distinguish specifying a restriction from examining it.** A model\n*constraint* restricts the values parameters may take, for example by\nsetting a coefficient to zero or requiring two coefficients to be equal.\nUsing such a constraint to specify a model belongs with model building.\nExamining the restriction through a test or comparison belongs with\nstatistical hypotheses, testing, and comparison. Some constraints instead\nserve to define a model's scale or make its parameters estimable; identify\nthe role of each constraint from the study's account.\n\nModel comparisons can also use criteria other than hypothesis tests,\nsuch as prediction error on held-out observations. Record which models\nwere compared, by what criterion, and with what result. The same\nanalysis may contribute both predictive validation and a comparison;\nidentify these connected uses without treating them as separate analyses.\n\n### Statistical Claim: the conclusion and its scope\n\nSTAT-C records the statistical proposition the study concludes, together\nwith its stated qualifications. @tbl-supa-stat-c uses familiar\nideas from the analysis in the different function of stating an answer.\n\n```{=latex}\n\\Needspace{18\\baselineskip}\n\\begingroup\n\\small\n\\setlength{\\tabcolsep}{4pt}\n\\renewcommand{\\arraystretch}{1.08}\n```\n\n| Traceable information | What to identify | Common cases | Likely documentary location |\n|:----------------------|:-----------------|:-------------|:----------------------------|\n| Reported statistical conclusion | What is concluded about direction, magnitude, or pattern, including a testing conclusion when reported. | The study concludes that mean scores are higher in one group; it describes an association as negative. | Results summary; Abstract; Discussion |\n| Remaining uncertainty and scope of the conclusion | What remains unresolved and which units, comparisons, conditions, or periods the conclusion covers. | Whether an effect reaches a stated size remains unresolved; the conclusion is restricted to participating units. | Results interpretation; limitations; Conclusion |\n\n: Statistical Claim: Traceable Information {#tbl-supa-stat-c tbl-colwidths=\"[24,27,30,19]\"}\n\n```{=latex}\n\\endgroup\n```\n\n**Connect analytical outputs to the statistical conclusion.** A calculated mean\ndifference with its interval contributes to STAT-I. \"The comparison\nindicates a positive mean difference for the participating students\"\nstates a conclusion in STAT-C. A reported claim of statistical\nsignificance may be part of C; the p-value producing that claim remains\nan analytical result in I. Include a significance claim when the study\nmakes one, and record the answer with its reported bounds. Keep any\nreader-proposed revisions separate. \"We investigated whether the\ngroups differ\" identifies the question; look for the reported finding\nto identify its answer.\n\n### Following substantive meaning across the linked layers\n\nThe substantive layer builds on the statistical layer and connects it\nto the people, measures, practices, and settings named by the question.\nIts information is more domain-dependent and can be directly documented:\nlook for what an assessment covers or what an intervention involved.\n@tbl-supa-sub retains four component rows;\nthe cases illustrate different possible studies.\n\n```{=latex}\n\\Needspace{12\\baselineskip}\n\\begingroup\n\\small\n\\setlength{\\tabcolsep}{3pt}\n\\renewcommand{\\arraystretch}{1.08}\n```\n\n| Component | Traceable information | What to identify | Common cases | Likely documentary location |\n|:----------|:----------------------|:-----------------|:-------------|:----------------------------|\n| **SUB-E** | People and setting, measure meanings, and implemented practices | What the recorded units, scores, conditions, or exposures represent in the substantive domain. | A course assessment covers application tasks; guided practice consists of worked examples and feedback. | Participants; Measures; instrument; intervention description |\n| **SUB-J** | Theory, mechanisms, and reasons supporting interpretation | Reasons invoked about measurement, implementation, comparability, alternatives, practical benchmarks, or applicability elsewhere. | Assessment coverage supports the score interpretation; an importance benchmark is linked to expected benefits and effort. | Introduction; measurement rationale; protocol; Discussion |\n| **SUB-I** | Contextual interpretation of statistical inference and uncertainty | How findings and uncertainty relate to substantive meanings, expectations, benchmarks, or proposed explanations. | An interval spans gains below and above a practical benchmark; the reported pattern is related to a proposed mechanism. | Results interpretation; Discussion |\n| **SUB-C** | Question-facing answer, scope, and qualifications | The reported answer to the substantive question or answerable aim, with its stated limits and unresolved matters. | A practice improved delayed course performance in the studied setting, while the importance of the gain remains unresolved. | Abstract; Discussion; Conclusion |\n\n: Substantive Components: Traceable Information {#tbl-supa-sub tbl-colwidths=\"[12,21,24,26,17]\"}\n\n*Note.* A numerical statement can perform a substantive function when\nit expresses domain meaning. Identify the interpretation during reading\nand assess its support during quality evaluation.\n\n```{=latex}\n\\endgroup\n```\n\n**Identify what a measure means and the reasons offered for that meaning.**\nA description of an assessment's application tasks tells you what the\nassessment covers, contributing to SUB-E. An explanation that these\ntasks cover the course objectives offers a reason for interpreting the\nscore as course performance, contributing to SUB-J. Follow the\ninstrument name to its description and the reasons given for\ninterpreting its scores.\n\nThe same distinction helps with theory and mechanisms. A paper might\ndescribe a theory in its Introduction and later invoke one of its\npredictions to explain why feedback could improve performance.\nIdentify the particular connection offered as substantive support.\nThis makes the theory's role in SUB-J visible, beyond simply recording\nthat the paper mentions it. Apply the same reasoning to implementation,\nalternative explanations, and applicability elsewhere.\n\n**SUB-I retains the statistical uncertainty.** When interpreting an\ninterval against a practical benchmark, retain its full range and the\npossibilities it leaves open. Distinguish a pattern described as\nconsistent with a proposed mechanism from evidence establishing that\nmechanism.\nSUB-C then states the study's question-facing answer and its\nqualifications. Readers identify these interpretations and claims;\nquality evaluation asks whether the support warrants them.\n\n```{=latex}\n\\Needspace{24\\baselineskip}\n```\n\n\n\nA condition may be invoked even though the study has not checked it, and a\ncheck may later be invoked as support for another inference. Identify the use\nmade of the information. Assuming independent classrooms is Justification for\nan uncertainty calculation. Examining dependence indicators and reporting the\nresult is Inference. Using that result as a reason for a subsequent comparison\ngives it an additional justificatory role.\n\nFor missing outcomes, the number absent is Evidence; the assumption used to\nanalyze incomplete records is Justification; imputation or a sensitivity\nanalysis and its results are Inference. A method's name alone does not settle\nwhat missingness mechanism would make its use defensible [@littlerubin2019].\nSensitivity analysis can make the conclusion's dependence on an unverifiable\nassumption visible [@nrc2010]. It need not remove that dependence.\n\n\n## Reading One Argument Across a Paper and Its Related Materials\n\n### The complete feedback packet\n\nThe following invented packet expands the same supplied feedback result. It\nadds documentary detail without generating a second experiment. The estimate\nand interval are stipulated teaching results; no set of student records is\nclaimed to reproduce them. The class allocation is across the whole pool,\nnot one class of each format forced within every school.\n\n> **F1 -- Abstract.** We asked whether assignment to explanatory feedback\n> changes average delayed achievement for eligible students in participating\n> classes. Assignment increased average assessed course-topic performance\n> under these conditions; the practical size remains uncertain.\n>\n> **F2 -- Methods.** Twelve schools contributed two classes each, with 20\n> eligible students per class. Before a six-week program, 12 of the 24 classes\n> were randomly assigned to explanatory feedback and 12 to usual feedback\n> across the full class pool. All 480 students supplied the common 0--40\n> assessment two weeks after the program and were analyzed by class assignment.\n>\n> **F3 -- Protocol.** Random allocation supplies the basis for the assignment\n> comparison. Equally weighted class means give students equal weight because\n> all classes have 20 eligible students. The uncertainty procedure reflects\n> assignment of classes. The inference assumes implementation of allocation,\n> a common outcome definition, complete follow-up and no influence of one\n> class's assignment on another class's outcomes.\n>\n> **F4 -- Assessment and implementation supplement.** Both formats used the\n> same topics and scheduled time. Explanatory feedback added explanations of\n> errors; usual feedback supplied correctness feedback. Delivery logs documented\n> the activities and separate materials. The assessment blueprint linked tasks\n> to taught topics, and scorers worked without knowledge of format. The curriculum\n> team judged two points, full credit on one application task, worth considering\n> against the additional preparation.\n>\n> **F5 -- Results and analytical supplement.** The estimated student-average\n> assignment effect was 2.5 points, approximate 95% CI [1, 4], with uncertainty\n> reflecting class assignment. Checks confirmed score ranges, allocation,\n> denominators and complete outcomes. Recalculating the contrast with each\n> school omitted in turn left its point estimate positive. These are influence\n> checks; the full eligible cohort remains the basis of the primary answer.\n>\n> **F6 -- Discussion.** Assignment improved average assessed performance on\n> the taught topics in these classes and conditions. The compatible magnitudes\n> include gains below and above the local two-point benchmark. Broader learning,\n> durable effects beyond this follow-up and effects for every individual remain\n> unresolved.\n\nThe claim in F1 is brief. F5 supplies its uncertainty, and F6 explains its\nscope. Reading these together preserves what the abstract alone leaves implicit.\nThe protocol's conditions also matter: the words \"random assignment\" cannot\nsubstitute for the allocation actually used or a matching uncertainty procedure.\n\n### Follow the comparison through both layers\n\n| Quantity or feature | Supplied result | Meaning in the argument |\n|:--|:--|:--|\n| Eligible students / assigned classes | 480 / 24 | Students define the target; classes receive assignment |\n| Explanatory-minus-usual estimate | 2.5 points | Estimated student-average assignment effect |\n| Approximate 95% interval | [1, 4] points | Uncertainty reflecting class assignment |\n| Local importance benchmark | 2 points | One application task, considered against preparation effort |\n| Assessment occasion | Two weeks after a six-week program | Delayed course-topic performance at the specified follow-up |\n\n: The result and the information needed to interpret it. {#tbl-supa-feedback-results tbl-colwidths=\"[29,23,48]\"}\n\nThe distinction between students and classes connects several components.\nThe recorded score belongs to a student; allocation belongs to a class; the\nestimand weights students equally; and equal class sizes make equally weighted\nclass means compatible with that target. Treating all 480 rows as independently\nassigned would change the inferential justification. The number of records in\na file does not determine the number of independent assignments.\n\n| Function | Particular contribution | Location |\n|:--|:--|:--|\n| STAT-E | Class allocation, eligible records, scoring occasion and complete analysis sample | F2, with implementation in F4 |\n| STAT-J | Allocation rationale, equal-size weighting and conditions of the class-based uncertainty procedure | F3 |\n| STAT-I | Estimated contrast and interval; coding, denominator and influence checks | F5 |\n| STAT-C | Positive eligible-cohort average assignment-effect conclusion, with uncertainty | F1, F5--F6 |\n| SUB-E | Students, course topics, feedback activities and delayed assessment | F2 and F4 |\n| SUB-J | Blueprint, common conditions, delivery records and the local benchmark's rationale | F4 |\n| SUB-I | Interval read against the application-task benchmark at this follow-up | F5--F6 |\n| SUB-C | Bounded answer about assessed course-topic performance, with broader claims unresolved | F6 |\n\n: A completed reading of the feedback argument. {#tbl-supa-feedback-traces tbl-colwidths=\"[15,63,22]\"}\n\nOne document can contribute to several functions, but locating it twice does\nnot create two independent pieces of evidence. The blueprint's description\nof tasks helps situate the outcome; its alignment with course objectives is\nalso invoked as a reason for interpreting it. The statistical result supports\na mean effect; it does not show that every student's score increased by 2.5.\n\n::: {.callout-note title=\"Predict, then explain: keep the numbers, change the design\"}\nSuppose the same reported estimate and interval appear in a different study\nwhere teachers selected their preferred feedback format. Before reading on,\npredict which part of the argument would change first and whether the same\ncausal answer would remain warranted.\n:::\n\nThe allocation account changes Evidence and removes the random-assignment\nreason in Justification. Selection could be related to prior achievement,\nteacher resources or other causes of outcomes. The numerical table can remain\nthe same while its causal warrant changes. Its interval also needs a stated\nuncertainty justification for the new design; copying the numbers does not\ncarry the old calibration with them. A descriptive difference remains\nreportable, but it answers a different question from an assignment effect.\n\n### A missing explanation and a conflicting count\n\nTwo variants of the packet show why identification and judgment remain distinct.\nIn the first, F3 is omitted from the paper but available in its protocol. The\nrationale is accessible: state that the protocol explains weighting and\nassignment-based uncertainty. Publication outside the article does not by\nitself weaken the reason, although readers need a way to find it.\n\nIn the second variant, F2 says all 480 students were analyzed, while a supplied\nflow table says 460 completed follow-up. The discrepancy is unresolved; the\npacket gives no reconciliation. State both accounts and their locations. Do\nnot silently choose the number that makes the result easier to interpret.\nThe target still concerns 480 eligible students, while the actual analysis\nmembership and handling of missing outcomes need clarification. This may\nlimit Evidence integrity and the ability to judge the whole answer.\n\nThe task is specific: which students are absent from which calculation, why,\nand how were their outcomes handled? Neither \"the report has a supplement\"\nnor \"missing data were handled statistically\" answers it. A useful reading\nidentifies what further information could resolve the question.\n\n### A shorter transfer: predicting recorded student outcomes\n\nThe real data of Realinho and colleagues contain 4,424 students from the\nPolytechnic Institute of Portalegre, Portugal [@realinho2022; @uci697]. Outcomes\nwere recorded at the normal degree duration. Dropout can include changing\ncourse or institution; Enrolled means still enrolled at that endpoint; Graduate\nmeans completed. The binary teaching analysis compares recorded Dropout with\nthe other categories combined, while preserving all three labels in the data.\n\nThe question is whether admission grade and age at enrollment improve\nprediction of that recorded outcome for held-out students from the same source.\nBoth predictors are available at enrollment. Semester results would be too late\nfor this intended prediction time. The teaching analysis uses a fixed,\nstratified approximately 70% training split and fits a logistic rule; this is\na simplified analysis, not a reproduction of the source authors' classifiers.\n\n| Records | Dropout | Enrolled | Graduate | Total |\n|:--|--:|--:|--:|--:|\n| Full release | 1,421 | 794 | 2,209 | 4,424 |\n| Training | 994 | 562 | 1,540 | 3,096 |\n| Held out | 427 | 232 | 669 | 1,328 |\n\n: Counts supporting the prediction comparison. {#tbl-supa-prediction-records}\n\nThe fitted rule assigns a probability to each held-out student's recorded\nDropout status. Average squared probability error is 0.2000, against 0.2182\nfor assigning everyone the training-data dropout proportion; lower is better.\nThese errors compare probability predictions, rather than count correct alerts.\nAt a probability cutoff of 0.5, the fitted rule flags 73 of the 427 held-out\nDropout records, or 17.096%. A better average probability score therefore\ncoexists with missing most eventual Dropout records at this threshold.\n\nOutcome definitions, predictors, split and denominators are Evidence. Their\navailability at the intended time and separation of fitting from assessment\nsupply reasons in Justification. The fit, probabilities, error comparison and\nthreshold calculation are Inference. The reported Claim is that this simple\nrule improves average probability prediction on the internal held-out records,\nwhile this cutoff identifies only a small fraction of recorded Dropout.\n\nIn substantive terms, an alert is about this administrative outcome, not\nnecessarily departure from higher education. The released data have no\ncohort-year field for an independent later-cohort assessment. Predicting well\nwithin this split neither establishes performance for a future cohort nor\nshows that an intervention prompted by an alert would help. Those are\nseparately owed questions with different evidence requirements.\n\n### Focused passages from three other settings\n\n**Working from home.** Bloom and colleagues' experiment randomly assigned\neligible volunteer employees, 131 to home work and 118 to office work\n(Appendix Table A.2, p. 214). The nine-month arrangement and four home-working\ndays per week are described on p. 169. Table II, column 4, p. 187 reports a\nweekly log-call analysis for 134 order takers, using employee and week effects\nand uncertainty clustered by employee; the authors interpret the result on\np. 188 as about 13% more weekly calls [@bloom2015wfh]. These are the paper's\nrounded reporting choices. The 134 analysis employees are not a contradictory\ncount of all 249 assigned employees: follow the outcome and employee group\nfor the selected analysis. Allocation documents production; its invoked causal\nreason belongs to Justification; a regression and its reported comparison\nbelong to Inference. The [author's materials](https://nbloom.people.stanford.edu/research)\nallow a reader to inspect the underlying reports. Repeated weekly outcomes\nalso explain why counting weeks as independent employees would be a mistake.\n\n**Confidence and belonging.** In an invented study, three 0--100 confidence\nindicators ask about explaining, applying and checking learning tasks; three\nbelonging indicators concern acceptance, inclusion and participation. The\nquestions, scoring and administration supply measurement records. Their\ncontent situates the scores in a substantive domain. Reasons why these items\nrepresent the intended constructs provide substantive Justification. A scoring\nrule alone cannot establish that interpretation. Reading these contributions\nrequires no factor analysis in this chapter.\n\n**Language progress.** An invented student scores 58, 65, 68 and 76 at equally\nspaced occasions; another scores 62, 63, 67 and 68. Their average gains per\ninterval are 6 and 2, but successive observed gains are 7, 3, 8 and 1, 4, 1.\nA constant average is not a constant observed trajectory. Student and occasion\nidentifiers document the repeated structure. A reason for modeling within-student\ndependence is distinct from the data layout. A missing assessment is also\ndifferent from a student who was never observed or eligible for this study.\n\n### Follow the organization and the reporting\n\nTwo auxiliary tasks help when a reading becomes difficult. **Identifying\norganization** asks which result belongs to which question, what information\nis shared, and which results support rather than replace the focal answer.\nThe feedback influence checks support the one assignment-effect argument;\neach omitted-school calculation does not create a new substantive question.\nA separate question about preparation burden would need its own stated answer\nunless it had been defined as a strand required for one integrated decision.\n\n**Following reporting** connects an abstract's conclusion to a Results table's\ninterval and a Discussion's scope. F1, F5 and F6 form that chain. The task\nadds no new component: it follows how the existing contributions are expressed\nand located. A concise abstract and a qualified Discussion need to be read\ntogether, but the fuller passage does not excuse a plainly contradictory\nheadline. Argument B develops these tasks when several answers depend on one\nanother. Here they organize a reading without adding another taxonomy.\n\n### Read a reported regression argument\n\nThe following teaching report concerns 102 historical occupation records from\n`carData::Prestige` [@carData2022]. It is written for this tutorial. R1--R4 are\nlocations within the teaching report, not quotations from the dataset's authors.\nA slope describes how fitted occupation-average income changes with education;\n$R^2$ describes the fraction of recorded income variation accounted for by the\nline, and residual SD describes remaining vertical scatter in income units.\nThese local reminders support the reading; no regression calculation is required.\n\n::: {.callout-note title=\"Teaching report: an occupation-level description\"}\n> **R1 -- Question and evidence.** We described the education--income\n> relationship in the 102 *carData::Prestige* occupation records. Income\n> was expressed in thousand 1971 Canadian dollars. All records had both\n> modeled measurements. Each occupation was weighted equally; the observed\n> education range was 6.38--15.97 years.\n>\n> **R2 -- Offered reasons.** The upward scatterplot motivated a\n> straight-line summary. OLS was chosen because it minimizes squared\n> vertical discrepancies. The aim was a summary of these records, not a\n> constant causal effect or an individual-level comparison. The source\n> documentation identifies the measurements as historical occupational\n> averages. No probability-sampling justification was available in the\n> record consulted.\n>\n> **R3 -- Analysis and interpretation.** The fitted slope was 0.8988\n> thousand dollars per education year, with $R^2=.3336$ and residual SD\n> 3.4834 thousand dollars. The residual pattern and a curved-fit\n> sensitivity qualified the line as an incomplete description. The fit and\n> sensitivities were exploratory. The descriptive result itself was not\n> assigned sampling uncertainty.\n>\n> **R4 -- Reported answer.** Across these 102 recorded occupations, higher\n> average education accompanied higher average income overall. The\n> least-squares line summarized that pattern by about 899 additional 1971\n> dollars of fitted occupation-average income per education year over the\n> observed range. It did not describe every occupation closely or establish\n> an individual or causal return to education.\n:::\n\n| Function | Content read in this report | Where the information is found |\n|:--|:--|:--|\n| STAT-E | Records, measurements, scaling, and complete sample | R1 |\n| STAT-J | Reasons for OLS as a descriptive, noncausal summary | R2 |\n| STAT-I | Slope, fit, sensitivity, and exploratory status | R3 |\n| STAT-C | Positive but incomplete description over recorded support | R4 |\n| SUB-E | Historical occupation averages, not individual measurements | R1 and the dataset documentation |\n| SUB-J | Measurement meanings supporting an occupation-level reading | R2 and the dataset documentation |\n| SUB-I | Meaning of about 899 dollars per education year | R3--R4 |\n| SUB-C | Bounded historical answer, without a causal or individual return | R4 |\n\n: Reading one regression argument with linked statistical and substantive layers. {#tbl-supa-regression-traces tbl-colwidths=\"[12,42,46]\"}\n\nR4 names the 102 recorded occupations and the descriptive line. It does not\nclaim a population slope, so the reader attaches no confidence interval to that\nanswer. The fitted slope is one statistical strand; fit summaries and checks\nsupport its interpretation rather than supply separately owed substantive answers.\n\nNow replace R2's reason with \"We used R, so our slope is an unbiased causal\neffect.\" The offered reason is identifiable STAT-J content even though it is\ninadequate. Reading records it as given. The next section judges whether it\nsupports the claim. A reader does not silently supply random assignment or\nreplace the report's question with a better one.\n\n\n## Evaluating the Quality of the Question-Level Argument\n\n### Six questions, with reasons rather than scores\n\nEvaluation depends on the argument that has been read. Its six questions focus\nattention on a particular weakness or strength; they are not six new components\nand their judgments are not a total quality score. Some questions overlap in\nthe consequence they reveal. Name where a problem first arises, then explain\nwhat it changes later in the argument.\n\n| Group | Evaluation question | What to consider |\n|:--|:--|:--|\n| **Alignment** | **Question alignment** | Whether the question, estimand, design, evidence, analysis, and answer remain directed at the same aim |\n| **Support** | **Evidence integrity** | Whether the observations and contextual records, their production, and their representation are trustworthy, traceable, and appropriate |\n| **Support** | **Justification adequacy** | Whether the statistical, design, measurement, and contextual reasons warrant the proposed moves |\n| **Support** | **Inferential adequacy** | Whether reasoning within both layers is adequate, including estimation, uncertainty, checks, sensitivity, and substantive interpretation |\n| **Translation** | **Transition fidelity** | Whether the links between layers retain meaning, uncertainty, design status, and scope |\n| **Translation** | **Claim calibration** | Whether the reported answer's strength and breadth match its support |\n\n: Six questions for evaluating one question-level argument. {#tbl-supa-evaluation tbl-colwidths=\"[17,28,55]\"}\n\nA local judgment is **adequate for this purpose**, **needs revision**,\n**insufficient information to judge**, or **not applicable**. Accompany it with\na reason: \"the complete cohort supports the stated denominator\" is informative;\n\"Evidence integrity: adequate\" alone does not show what was inspected.\n\nThe whole question-answer pair can be **supported as stated**, **supported\nonly after narrowing or revision**, **not supported**, or **not assessable from\nthe accessible record**. These outcomes distinguish a warranted answer from an\nunwarranted one and an unresolved documentary gap from a demonstrated failure.\nAn inconclusive answer can be supported as stated. A study need not discover\na benefit to provide a defensible answer to its question.\n\n### Evaluate the feedback claim and its variants\n\nThe baseline feedback answer retains the eligible cohort, assigned classes,\nassessment meaning and follow-up. Its interval is above zero but crosses the\ntwo-point benchmark. Within the supplied conditions, the positive average\nassignment-effect conclusion is supported as stated, with practical size\nuncertain. That judgment is about this bounded answer, not a certificate that\nthe study has answered every educational question.\n\n| Evaluation question | Application to the feedback packet |\n|:--|:--|\n| Question alignment | The answer remains about the eligible-cohort assignment effect at the stated occasion |\n| Evidence integrity | Allocation, common scoring, denominators and complete follow-up are documented |\n| Justification adequacy | The class-assignment comparison and equal-size weighting address the target, under the stated implementation and no-between-class-influence conditions |\n| Inferential adequacy | The stated uncertainty reflects assignment; checks inform the calculation without establishing every assumption |\n| Transition fidelity | Two score points retain their course-specific meaning; a cohort-average effect does not become each student's gain |\n| Claim calibration | A positive delayed-assessment conclusion retains an unresolved practical magnitude and limited reach |\n\n: Applying evaluation to the supplied feedback answer. {#tbl-supa-feedback-quality tbl-colwidths=\"[28,72]\"}\n\nNow consider \"the format produces substantial, lasting improvements in all\nforms of learning for every student.\" The result has not changed. Transition\nfidelity needs revision because an assessment of taught topics has become all\nlearning and an average has become every individual. Claim calibration needs\nrevision because the two-week follow-up has become indefinitely lasting and\npractical importance has been settled despite the interval crossing the\nbenchmark. Narrowing that overstatement back to the declared cohort-average\nquestion preserves a supported answer. Claiming an individual response instead\nwould introduce a different estimand requiring different evidence.\n\nFor the conflicting-count variant, Evidence integrity is unresolved. If the\nmissing outcomes could change the comparison and their handling is unknown,\nthe whole answer may be not assessable from the accessible record. This differs\nfrom a documented coding error that demonstrably changes the result: then the\ncalculation and answer need revision. Different concerns call for different\nremedies, not a common penalty score.\n\n::: {.callout-note title=\"Predict, then explain: the estimate stays the same\"}\nA separate invented study reports the same 2.5-point estimate but an interval\nfrom $-1$ to 6 points. Its local benchmark is still two points. What changes in\nthe conclusion about direction and importance, and what stays unchanged?\n:::\n\nThe point estimate stays positive, but the interval now includes a negative\neffect, zero and gains both below and above the benchmark. The study cannot\nsettle direction or practical size at the stated level. Reporting that\nuncertainty can be a supported answer. \"No effect\" would discard compatible\npositive and negative values; \"2.5 points proves a meaningful benefit\" would\ndiscard the uncertainty. The interval concerns an average effect, not the range\nof individual student effects.\n\n### Evaluate the prediction promise\n\nThe student prediction comparison supports a limited promise: lower average\nsquared probability error than the training-prevalence rule on this internal\nheld-out set. Evidence integrity concerns the outcome coding and disjoint fit\nand assessment records. Justification adequacy concerns predictor availability\nat enrollment and an assessment population relevant to the intended use.\nInferential adequacy concerns the specified error measure and any uncertainty\nor stability needed for a stronger comparative claim.\n\nThe 0.5 cutoff identifies 73 of 427 Dropout records. Claim calibration therefore\nrequires a distinction between improved probability predictions and useful\nscreening. A threshold could be changed, but deciding its value requires the\nconsequences of missed cases and false alerts. An appropriate future evaluation\nwould preserve the chosen rule and threshold before measuring performance in\nthe new setting. Trying thresholds on the same assessment set and reporting\nonly the best would spend that set on selection.\n\nA future-cohort promise remains unassessed because the released record does not\npermit a later-cohort split. A causal claim that acting on alerts prevents\ndropout is also unassessed by this prediction analysis. More elaborate software\ncannot replace the missing time information or evidence about intervention\nconsequences. The way forward is to identify the additional question and obtain\nevidence suited to it, rather than make the same error score carry it.\n\n### Evaluate the regression answer already read\n\n| Quality-evaluation question | Application to the reported descriptive argument |\n|:--|:--|\n| Question alignment | Does the answer remain about the 102 occupations and the declared straight-line summary? |\n| Evidence integrity | Are the source, aggregate unit, scaling, exclusions, and unusual records traceable? |\n| Justification adequacy | Are the offered reasons adequate for a descriptive line, rather than stretched into random sampling or causal identification? |\n| Inferential adequacy | Do the calculation and substantive reasoning support the reported pattern while retaining curvature and scatter? |\n| Transition fidelity | Does the interpretation preserve occupation-level measurements, units, and exploratory status? |\n| Claim calibration | Does the answer retain historical scope, supported range, and the limits of a linear summary? |\n\n: Evaluating the regression argument already read. {#tbl-supa-regression-quality tbl-colwidths=\"[30,70]\"}\n\nR4 is supported as stated: it reports a checkable summary of named records and\nretains their unit and historical scope. Missing information about national\nsampling does not invalidate arithmetic on those named records. It would matter\nfor a proposed national generalization. No fit summary establishes that the\nline describes every occupation closely; R3 acknowledges substantial scatter\nand a curved-fit sensitivity.\n\nA model-based extension is a separate commitment. An interval for a process\nslope needs an appropriate mean model and uncertainty assumptions. The residual\npattern and curvature qualify that extension. Changing only the covariance\nestimator might address a variance condition; it cannot make a straight\nconditional-mean relationship true or provide random sampling.\n\nThe news claim \"another year of education increases income by about 900 dollars\"\nis not supported by these records [@robinson1950]. It moves from occupation\naverages to individuals and from description to causation. Replacing it with R4\nchanges the question-answer pair, not merely the tone of the conclusion.\nA causal comparison needs a design or identification argument. In Project STAR,\nfor example, the within-school random assignment supplies a reason for causal\ncomparison; the fact that a binary-regression slope equals a group-mean\ndifference does not itself supply that reason [@finn1990; @mosteller1995].\n\n## From a Reading to a Documented Construction Cycle\n\n### Six stages organize the work\n\nA finished article is organized for communication. Its polished order does not\nprove when researchers made their decisions. A **construction workflow**\ndescribes how an argument is produced, whereas the component map describes\nhow its support functions. A Methods paragraph may report a plan, a later\nrepair or a post-inspection choice; dated records help distinguish them.\n\nThe six-stage cycle has two phases. **Understand and plan** develops a question\nand a coherent way to answer it. **Produce and complete** obtains the\nquestion-specific evidence, analyzes it and completes a bounded answer.\nSubstantive reasons belong in both phases: measurement meaning and practical\nbenchmarks should not be invented after the preferred result appears.\n\n| Phase and stage | Feedback construction example |\n|:--|:--|\n| Understand and plan: 1. Review the problem, setting, and relevant literature | Review what feedback activities could support learning and what earlier assessments measured |\n| 2. Frame the question and, where useful, a candidate answer | Ask about the eligible-cohort average assignment effect on delayed course-topic performance |\n| 3. Align design, measurement, estimand, evidence-production or acquisition plan, and inferential plan | Commit to class allocation, equal student weighting, a common delayed assessment, complete follow-up and matching uncertainty; document the two-point rationale |\n| Produce and complete: 4. Produce or acquire, and document, empirical and contextual evidence | Preserve allocation, delivery, scoring, follow-up and analysis-membership records |\n| 5. Estimate, check, and analyse | Estimate the contrast and interval; check coding, denominators and influential schools |\n| 6. Contextualize, interpret, and complete the bounded answer | Interpret the interval against its course benchmark and retain scope and unresolved practical size |\n\n: A six-stage construction cycle for the feedback question. {#tbl-supa-cycle-stages tbl-colwidths=\"[45,55]\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The six-stage cycle has one forward handoff between planning and production. Iteration stays within each phase; changing anchored commitments starts a revised or additional cycle.](chapter_arg_a_files/figure-html/fig-supa-cycle-1.png){#fig-supa-cycle fig-pos='H' fig-alt='Review, Frame and Align form the first phase, Understand and plan. Produce or acquire and document, Estimate check and analyse, and Contextualize interpret and complete form the second phase, Produce and complete. A one-way arrow links Align to Produce. Iteration is allowed within a phase; no return arrow crosses phases within this cycle.' width=672}\n:::\n:::\n\n\n### Read the decision history, not just the final order\n\nThe following chronology is an invented extension of the feedback protocol.\nIt teaches how timing contributes to interpretation; it adds no new results.\n\n| Decision time | Documented action | What the record allows a reader to conclude |\n|:--|:--|:--|\n| Before recruitment | The team specifies the eligible-cohort question, assessment occasion and two-point benchmark | These commitments precede relevant outcomes |\n| During planning | A pilot reveals ambiguous delivery instructions; the team clarifies them and realigns the plan | A refinement within Phase 1, before production for this question |\n| At production | The allocation list, class membership and scoring records are preserved | The plan can be compared with implementation |\n| During analysis | A duplicated score entry is found; the original record is checked and the affected calculation corrected | A Phase 2 repair, retaining the original estimand and commitments |\n| After inspecting outcomes | The team adds a question about baseline-score subgroups | An additional exploratory question and cycle, not a retrospectively planned primary question |\n| At completion | The original answer retains the 2.5-point estimate and [1, 4] interval with practical size uncertain | Normal completion can preserve an unresolved practical judgment |\n\n: A decision history distinguishes refinement, repair and a new question. {#tbl-supa-history tbl-colwidths=\"[19,41,40]\"}\n\nThe **Phase 1 anchor** records the question and mode, estimand, design,\nmeasurement, evidence-production or acquisition plan, inferential plan and,\nwhere relevant, a stopping rule. The one-way handoff makes changes to those\ncommitments visible. It is a convention for documenting research, not a claim\nthat investigators can never learn from outcomes and redesign a study.\n\nFor existing data, Stage 4 can mean obtaining or designating the records for\nthis question, rather than the first time anyone has opened the original\nfile. A decision is prospective with respect to relevant evidence only if its\ntiming supports that claim. Calling a later reanalysis \"Phase 1\" does not erase\nprior outcome access. Conversely, a documented revision before relevant\noutcome access need not be called exploratory merely because it is a revision.\n\n### Completion, repair and a revised question\n\nThree endings make the record honest. **Normal completion** answers the\nplanned question, possibly inconclusively or against an expectation.\n**Phase 2 repair** corrects work while retaining its anchored question and\ncommitments. An **additional or revised cycle** makes a changed question,\nestimand or inferential commitment explicit and gives the earlier cycle a\nvisible outcome. If the intended delayed assessment was administered immediately,\nthe original delayed-performance question is not answerable as planned. The\nimmediate scores can support another question with its own scope.\n\nChanging a score-coding error is a repair; replacing the planned outcome after\nseeing a disappointing result is a revised question and must preserve that\ntiming. A prespecified sensitivity can be run within the planned cycle. A new\nsensitivity motivated by a surprising diagnostic can also be documented as\nsuch; it does not acquire prospective status by being sensible. If it changes\na prior inferential commitment, record a revised cycle rather than overwrite\nthe original.\n\nA new cycle can reuse literature, records, measures and code. Reuse saves work,\nbut does not transfer a causal warrant, population scope or prospective status\nautomatically. For the occupation report, planning would declare historical\noccupation units, a finite-record slope and checks. Completion would preserve\nthe records, estimate and examine the line, and report the bounded description.\nChanging to an individual causal return would require a different question and\nevidence, rather than a different coefficient label.\n\nResearchers can use the six evaluation questions during construction to judge\nwhat a stage produces. The questions do not become workflow stages. Reading\nidentifies support; evaluation judges its adequacy; construction documents how\nsupport is developed. Keeping these tasks distinct makes room for judgment\nwithout requiring a ritual sequence every time a paper is opened.\n\n## Summary and Reading Bridge\n\nA useful reading connects the question and reported answer to particular\ninformation at inspectable locations. Procedures, invoked reasons, analysis\nand conclusions can appear in the same paragraph while doing different work.\nThe substantive layer follows what those contributions mean for the study's\npeople, measures and setting. An inadequate offered reason is still part of\nthe argument to be read; its adequacy is a separate judgment.\n\nThe feedback packet showed how allocation, weighting, assessment meaning and\nuncertainty support one bounded answer. The student example distinguished an\ninternal probability comparison from a useful alert or future-cohort promise.\nThe occupation report separated a finite-record description from individual\ncausal claims. In each case, changing one fact can change the support even\nwhen the numerical output stays the same.\n\nThis approach is a teaching synthesis, informed by Toulmin's warrants and\nqualifications [@toulmin2003], LeMire's connection between statistical testing\nand substantive reasoning [@lemire2010], and Kane's argument-based account of\ninterpretations and uses [@kane2013]. Work on estimands [@lundberg2021] and\nquantitative reporting [@appelbaum2018] develops the link between a target and\nthe inspectable record. These sources complement statistical method knowledge;\nthe component labels cannot replace that knowledge.\n\nArgument B extends the reading to several statistical strands required for\none answer and to separate questions whose support depends on one another.\nEach argument chapter supplies its own local recap and cases. Courses can\nselect one without requiring a running case carried through every chapter.\n\n### Key terms {.unnumbered}\n\nThe Part One Concept Reference brings the shared terms together. This table\nselects the terms developed in this argument chapter.\n\n| Concept group | Term and common alternatives | Meaning or essential distinction | Main explanation |\n|:--|:--|:--|:--|\n| Argument-based reading | Argument component | One of the four functions, evidence, justification, inference, and bounded claim, that a piece of study information performs in the statistical or the substantive layer. A reader identifies the function before judging its adequacy. | Arg. A, Sec. 2 |\n| Argument-based reading | Documentary location | The place in a report or its related materials, such as Methods, a protocol, a codebook, or an analytical supplement, where the traceable information for a component is found. | Arg. A, Sec. 1 |\n| Argument-based reading | Evaluation question | One of the six questions on alignment, support, and translation used to judge the quality of a question-level argument after it has been read. Each receives a reasoned judgment, not a score. | Arg. A, Sec. 4 |\n\n: Selected terms introduced in Argument Chapter A. {#tbl-supa-key-terms tbl-colwidths=\"[18,21,44,17]\"}\n\n## Exercises {.unnumbered}\n\nEach prompt supplies its own record. Explain the consequential connection; a\ncomplete component map is needed only when the question asks for one.\n\n<!-- prompt-id: CH01-E01 -->\n### Exercise 1: Find the question and the reported answer (Foundational) {.unnumbered #ex-ch01-01}\n\nAn invented abstract states: \"We examined whether assigning weekly planning\nmessages rather than usual course messages changes the average final-assessment\nscore for 100 consenting students in one course. The planning group averaged\n78 and the usual group 73 on a 100-point assessment. We conclude that planning\nmessages improve achievement for every university student.\" The excerpt gives\nno allocation procedure or interval.\n\n1. Formulate the research question from the aim, identifying your wording as\n   a reader's formulation. Locate the numerical result and reported answer.\n2. Identify the question's mode and estimand. Distinguish the five-point\n   estimate from that target.\n3. Name one specific piece of supporting information to seek and a plausible\n   documentary location. State one way the reported answer exceeds the record.\n\n<!-- END EX01-01 PROMPT -->\n\n<!-- prompt-id: CH01-E02 -->\n### Exercise 2: Distinguish a procedure, a reason and a result (Foundational) {.unnumbered #ex-ch01-02}\n\nAn invented report contains these passages:\n\n- **M1:** Twelve of 24 classes were randomly allocated to each feedback format.\n- **P1:** Random allocation supports comparing the assigned formats for the\n  participating classes; uncertainty must reflect class assignment.\n- **R1:** The estimated eligible-cohort average assignment effect is 2.5 points,\n  approximate 95% CI [1, 4].\n- **D1:** Assignment increased average assessed performance in these classes;\n  practical magnitude remains uncertain against the two-point benchmark.\n\n1. Identify the main statistical function of each passage and its location.\n2. Explain why locating P1 in a protocol rather than the paper does not change\n   its function. Is its location itself a judgment of adequacy?\n3. In a variant, P1 says \"Random assignment makes these classes representative\n   of all schools.\" Identify its function first, then explain the problem with\n   the offered reason.\n\n<!-- END EX01-02 PROMPT -->\n\n<!-- prompt-id: CH01-E03 -->\n### Exercise 3: Follow an interval into an answer (Integrative) {.unnumbered #ex-ch01-03}\n\nA separate invented workshop study randomly assigns 80 participants equally\nto two feedback formats. Everyone completes the same immediate 20-point quiz.\nThe estimated assigned-group mean difference is 1.1 points, 95% CI [-0.2, 2.4].\nThe documented uncertainty procedure matches assignment. Before outcomes were\nexamined, a 1.5-point difference was identified as potentially important.\n\n1. State the estimate, uncertainty and substantive benchmark, explaining what\n   each contributes. Does the interval describe individual participants' gains?\n2. Which directions and practical-size conclusions remain compatible with the\n   interval? Write a bounded answer of no more than two sentences.\n3. Explain what additional evidence would be needed to turn this answer about\n   an immediate quiz into a claim about durable professional learning.\n\n<!-- END EX01-03 PROMPT -->\n\n<!-- prompt-id: CH01-E04 -->\n### Exercise 4: Read incomplete or conflicting materials (Integrative) {.unnumbered #ex-ch01-04}\n\nIn an invented feedback report, Methods says all 480 eligible students were\nincluded. A linked flow table says 460 supplied follow-up scores. The analysis\ncode is unavailable. The protocol explains class allocation and equal-size\nweighting, but does not explain missing outcomes.\n\n1. State what each source contributes and the specific unresolved difference.\n   Which information would you seek next, and why?\n2. Explain why the protocol is useful support even though it does not resolve\n   this discrepancy. Do two references to the protocol create independent evidence?\n3. Give a reasoned local evaluation and explain when \"not assessable from the\n   accessible record\" is preferable to declaring the whole answer unsupported.\n\n<!-- END EX01-04 PROMPT -->\n\n<!-- prompt-id: CH01-E05 -->\n### Exercise 5: Predict the consequence of a changed design (Integrative) {.unnumbered #ex-ch01-05}\n\nA supplied invented report gives a 2.5-point mean difference and 95% interval\n[1, 4] for 480 students in 24 classes, and concludes that assigning explanatory\nfeedback improved average delayed performance in those classes. In Version A,\nclasses were randomly assigned and uncertainty reflects that allocation. In\nVersion B, teachers chose their preferred format; the numerical table is\nidentical, and no adjustment or identification argument is supplied.\n\n1. Predict whether the same causal answer remains supported in Version B.\n   Explain which changed fact matters before referring to the interval.\n2. Apply Justification adequacy and Claim calibration selectively. Distinguish\n   a numerical difference from the support for its causal interpretation and\n   its uncertainty calculation.\n3. If you replace the causal answer with a description of the observed groups,\n   are you only narrowing the same answer or answering a different question?\n4. For Version A, change only the interval to [-1, 6]. Explain what changes in\n   the conclusion about direction and the two-point importance benchmark.\n\n<!-- END EX01-05 PROMPT -->\n\n<!-- prompt-id: CH01-E06 -->\n### Exercise 6: Read a documented construction history (Integrative) {.unnumbered #ex-ch01-06}\n\nAn invented team makes these decisions about its planned delayed-assessment\nfeedback study:\n\nA. Before recruitment, a pilot reveals ambiguous instructions; the team clarifies\n   delivery and realigns its plan.\n\nB. During analysis, a verified duplicated score is corrected and the declared\n   comparison is recalculated.\n\nC. After viewing outcomes, the team chooses an immediate quiz instead of its\n   planned delayed assessment because the result looks more favorable.\n\nD. The declared analysis is completed, but its interval leaves meaningful\n   benefit and harm compatible; the team reports that uncertainty.\n\n1. Classify each decision as refinement within Phase 1, repair within Phase 2,\n   a revised/additional cycle, or normal completion. Give a reason.\n2. State what the record of C must preserve. Name one useful resource that can\n   be reused and one status that does not transfer automatically.\n3. If the delayed assessment was never administered, what should be recorded\n   about the original question? Explain why an orderly final Methods section\n   cannot establish that decisions were prospective.\n\n<!-- END EX01-06 PROMPT -->\n\n<!-- prompt-id: CH01-E07 -->\n### Exercise 7: Locate the reasons, then judge the answers (Integrative) {.unnumbered #ex-ch01-07}\n\nThe report below is invented for this exercise. It is the whole\nreport; no assignment or sampling documentation accompanies it.\n\n**S1.** We describe how average weekly study time relates to average\ntest score in 60 secondary schools, using each school's recorded\naverages for one term. School-average study time ranged from 2 to 6\nhours a week, and every school had both averages.\n\n**S2.** A scatterplot of the 60 schools showed a roughly straight\nupward pattern, so we summarized it with a least-squares line. We used\na regression program, so the coefficient is a causal effect.\n\n**S3.** The fitted slope was 4 test-score points per additional hour of\nschool-average weekly study time.\n\n**S4.** Across these 60 schools, schools with more average study time\nhad higher average scores: the least-squares line summarized the\npattern by about 4 points of fitted school-average score per\nadditional hour over the observed 2--6 hours.\n\n**S5.** Each additional hour a student studies raises that student's\nscore by 4 points.\n\n1. Locate the reasons the report offers and its reported answers. Name\n   the function each performs and the paragraph where you find it.\n2. Before judging it, say what function the sentence \"We used a\n   regression program, so the coefficient is a causal effect\" performs.\n   Then apply Justification adequacy to it.\n3. Judge S4 as the answer to a descriptive question about these 60\n   schools. Is it supported as stated? Does it need an interval?\n4. Apply Transition fidelity and Claim calibration to S5. Is it\n   supported? Explain whether replacing S5 with S4 narrows the same\n   answer or answers a different question.\n\n<!-- END EX01-07 PROMPT -->\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_arg_a_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}