{
  "hash": "6770a235567f2c1dc1d6b7897668eb1f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Linear Regression\"\nauthor: \"Jinsong Chen\"\n\nbibliography: ../references.bib\ncsl: ../apa.csl\nlink-citations: true\nlang: en\ntbl-cap-location: top\nfig-cap-location: bottom\n\nexecute:\n  echo: false\n  warning: false\n  message: false\n  cache: false\n\nformat:\n  pdf:\n    pdf-engine: lualatex\n    pdf-standard: ua-2\n    colorlinks: false\n    latex-min-runs: 3\n    number-sections: true\n    toc: true\n    toc-depth: 2\n    fig-align: center\n    include-in-header:\n      - text: |\n          % QMSBR local compatibility backport for luatex.def 2025/09/29 v1.2f.\n          % Adapted from latex3/graphics-def PR 48 (Joseph Wright), commit\n          % edda2fc20708ead2b7c18ed4e4f66cae4d7b1ee7:\n          % https://github.com/latex3/graphics-def/pull/48\n          % https://github.com/latex3/graphics-def/issues/47\n          % The upstream PR was unmerged when this local backport was made.\n          % Original driver copyright: LaTeX3 Project and its listed contributors.\n          % This adaptation is distributed under LPPL 1.3c or later:\n          % https://www.latex-project.org/lppl.txt\n          %\n          % Preserve the imported PDF's transparency group. Put the driver's additional\n          % group on a separate outer Form XObject, avoiding conflicting duplicate /Group\n          % keys. Do not replace this with PDF post-processing or disabling transparency.\n          % Exact-token patches deliberately fail on an unexpected/new driver: review\n          % whether the upstream fix is then installed before removing this backport.\n          \\usepackage{etoolbox}\n          \\makeatletter\n          \\newcommand{\\QMSBRgraphicsPatchError}[1]{%\n            \\PackageError{qmsbr-graphics-compat}{Graphics compatibility patch #1 failed}%\n              {Expected LuaTeX graphics driver 2025/09/29 v1.2f. Review the upstream fix and local header before rendering.}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup 1\\fi}{}{}{\\QMSBRgraphicsPatchError{1}}\n          \\patchcmd{\\Gread@@pdftex}{\\ifGread@transgroup/Group<</S/Transparency/K false/I false>>\\fi}{}{}{\\QMSBRgraphicsPatchError{2}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}}\n            {\\setbox\\@tempboxa=\\hbox{\\useimageresource\\lastsavedimageresourceindex}%\n             \\ifGread@transgroup\n               \\saveboxresource attr{/Group<</S/Transparency/K false/I false>>}\\@tempboxa\n               \\setbox\\@tempboxa=\\hbox{\\useboxresource\\lastsavedboxresourceindex}%\n             \\fi}\n            {}{\\QMSBRgraphicsPatchError{3}}\n          \\patchcmd{\\Gread@@pdftex}\n            {\\useimageresource\\the\\lastsavedimageresourceindex}\n            {\\ifGread@transgroup\\useboxresource\\the\\lastsavedboxresourceindex\\else\\useimageresource\\the\\lastsavedimageresourceindex\\fi}\n            {}{\\QMSBRgraphicsPatchError{4}}\n          \\makeatother\n          \\setlength{\\parindent}{0pt}\n          \\widowpenalty=10000\n          \\clubpenalty=10000\n          \\ifdefined\\pdfinfoomitdate\\pdfinfoomitdate=1\\fi\n          \\ifdefined\\pdftrailerid\\pdftrailerid{}\\fi\n          \\ifdefined\\pdfsuppressptexinfo\\pdfsuppressptexinfo=-1\\fi\n          \\ifdefined\\pdfvariable\n            \\pdfvariable suppressoptionalinfo \\numexpr1+2+4+8+16+32+64+128+256+512\\relax\n          \\fi\n          \\AtBeginDocument{\\hypersetup{pdfcreator={},pdfproducer={},pdfcreationdate={},pdfmoddate={}}}\n          \\addtokomafont{sectionentry}{\\small}\n          \\let\\chapteroldtableofcontents\\tableofcontents\n          \\renewcommand{\\tableofcontents}{\\begingroup\\small\\chapteroldtableofcontents\\endgroup}\n          \\usepackage{caption}\n          \\captionsetup[table]{\n            position=above,\n            format=plain,\n            justification=raggedright,\n            singlelinecheck=false,\n            labelsep=newline,\n            labelfont=bf,\n            textfont=it\n          }\n          \\usepackage{booktabs}\n          \\usepackage{longtable}\n          \\usepackage{array}\n          \\usepackage{float}\n          \\usepackage{needspace}\n          \\AddToHook{cmd/section/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AddToHook{cmd/subsubsection/before}{\\Needspace{6\\baselineskip}\\phantomsection}\n          \\AtBeginDocument{\\renewcommand{\\boldsymbol}[1]{\\symbf{#1}}}\n  html:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    toc-location: body\n    number-sections: false\n  docx:\n    df-print: kable\n    toc: true\n    toc-depth: 3\n    number-sections: false\n\neditor_options:\n  chunk_output_type: console\n\neditor:\n  markdown:\n    wrap: 72\n---\n\n\n\n\\clearpage\n\n::: {.callout-note title=\"Chapter overview\"}\nThis chapter reads a fitted line. Starting from a reported claim about\neducation and income, we state an occupation-level question, plot the\nrecords, and fit a straight line to them. We read the slope, intercept,\nfitted values, and residuals; see how least squares chooses the line and\nhow the slope is covariance divided by predictor variation; and describe\nhow much variation the line leaves. We then declare a separate process\nquestion, derive the slope's standard error and interval, and watch\nfitted slopes vary across repetitions of a known process. We distinguish\na mean response from one new outcome, check form, spread, influence, and\nsupport, and close with Galton's heights of fathers and sons, where the\nline in standard units explains regression toward the mean. By the end\nof the chapter you will be able to fit and read a simple regression in R,\nstate what its descriptive and model-based answers concern, and recognize\nregression toward the mean in a before-and-after claim. An appendix\ndevelops the mathematics further.\n:::\n\nSuppose a report says, \"Another year of education increases income by about\n900 dollars.\" Before examining its significance, ask whose education and whose\nincome were measured. The same number could refer to individuals, households,\nor occupational averages. Those are different comparisons.\n\n\\Needspace{6\\baselineskip}\n\nOur question is deliberately narrower:\n\n> Among the 102 recorded Canadian occupations, how did occupation-average\n> income differ across the supported range of occupation-average education in\n> 1971, as summarized by a fitted straight line?\n\nOne row represents an **occupation**, not a worker. An occupation with higher\naverage education need not contain the same people as an occupation with lower\naverage education. A comparison between their averages does not describe what\nwould happen to one person's income after another year of schooling.\nAggregate and individual relationships can differ substantially [@robinson1950].\n\nChapter 5 connected covariance and correlation to recorded values and\nmade mean and correlation inference executable in R. Chapter 6 fitted\ngroup means through indicator coefficients in a model formula. Here we\ndevelop the fitted line for a continuous predictor: how its slope is\ncalculated, what its uncertainty requires, and which comparisons and\npredictions the records support.\n\n## A Question About Occupations and a Line Through Their Records {#sec-ch7-question}\n\n### Begin with the unit and the question\n\nThe data are distributed as *carData::Prestige* [@carData2022; @fox2019].\nThe package documentation attributes education and income to the *Census of\nCanada* (1971), volume 3, part 6, pages 19-1 to 19-21.\nWe read the package documentation as a source record, not as evidence that\nthese occupations form a probability sample. The chapter's calculations are\nour reanalysis, not statements attributed to an original research paper.\n\n| Feature | Meaning in this chapter |\n|:--|:--|\n| Unit and record count | 102 occupations; each occupation receives equal weight |\n| Education, $x$ | Average years of education of occupational incumbents in 1971 |\n| Income, $y$ | Average income of incumbents, divided by 1,000; thousand 1971 Canadian dollars |\n| Missingness for the fit | No missing education or income values; no modeled rows excluded |\n| Observed support | Education: 6.38--15.97 years; income: 0.611--25.879 thousand dollars |\n| Descriptive estimand | Least-squares slope summarizing these 102 fixed occupation records |\n| Limits of the source record | No probability-sampling basis or individual-level analysis established here |\n\n: Record, measurements, and scope for the focal analysis. {#tbl-ch7-record tbl-colwidths=\"[30,70]\"}\n\nEqual weighting matters. A small occupation and a large occupation contribute\none row each. Without suitable counts and a different estimand, this analysis\ndoes not describe an average worker's experience. Historical dollars also\ncannot be read as contemporary purchasing power.\n\n### Look before fitting\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprestige <- carData::Prestige\nprestige$income_k <- prestige$income / 1000\nlibrary(ggplot2)\n```\n:::\n\n\nThe package-qualified name `carData::Prestige` selects the supplied dataset.\nDividing income by 1,000 changes its units while preserving every occupation.\nThe Computer Lab supplies installation and operating practice if needed; the\noccupation example requires no separate data file.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(prestige, aes(education, income_k)) +\n  geom_point(shape = 1, size = 2) +\n  labs(x = \"Average education (years)\",\n       y = \"Average income (thousand 1971 dollars)\")\n```\n\n::: {.cell-output-display}\n![Education and income in the 102 occupation records, before fitting a line.](chapter_07_files/figure-html/fig-ch7-scatter-1.png){#fig-ch7-scatter fig-pos='H' fig-alt='Occupation-average income generally rises with occupation-average education, with considerable scatter and some especially high-income occupations.' width=604.8}\n:::\n:::\n\n\nThe scatterplot gives the line a job: summarize an overall upward pattern\namid substantial variation. It also shows why the line cannot describe every\noccupation equally well. General managers, for example, have an average\neducation of 12.26 years and an average income of 25.879 thousand dollars;\nuniversity teachers have corresponding values of 15.97 and 12.480.\nMore education does not order every pair of occupations by income.\n\nThe scatterplot motivates fitting a straight-line summary. Save that fit\nas `model`, and keep its coefficients in `b` for calculations that follow.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(income_k ~ education, data = prestige)\nb <- coef(model)\ncoef(model)\n#>   (Intercept)     education \n#> -2.8535855824  0.8988128418\n```\n:::\n\n\nThe formula puts the outcome to the left of the tilde and the predictor to its\nright. The command finds coefficients. It does not choose a population,\nestablish a causal design, or justify a confidence interval.\n\n## Read the Fitted Line and Understand How OLS Finds It {#sec-ch7-line}\n\n### Fitted values, slopes, and residuals\n\nA straight-line summary assigns each observed predictor value $x_i$ a\n**fitted value** $\\widehat y_i$:\n\n$$\n\\widehat y_i=\\widehat\\beta_0+\\widehat\\beta_1x_i,\n\\qquad e_i=y_i-\\widehat y_i.\n$$\n\nThe subscript $i$ indexes a record. The hat marks a fitted quantity.\nThe **residual** $e_i$ is observed income minus fitted income. A positive\nresidual places an occupation above the line; a negative residual places it\nbelow. A residual is calculated after fitting and is not the same as an\nunobservable error from a population model.\n\nFor the occupation records, the line is\n\n$$\n\\widehat{\\mathrm{income}}=-2.8536+0.8988\\,\\mathrm{education}.\n$$\n\nIncome is still in thousands of dollars. The slope says that the fitted\nincome differs by 0.8988 thousand dollars, about 899 dollars, for a one-year\ndifference in occupation-average education. A two-year difference along this\nline corresponds to $2\\widehat\\beta_1\\approx1.7976$ thousand dollars.\n\nFor university teachers, use the fitted coefficients before rounding:\n\n$$\n\\widehat y=\\widehat\\beta_0+\\widehat\\beta_1(15.97)\n\\approx11.5005,\\qquad\ne=12.4800-\\widehat y\\approx0.9795.\n$$\n\nTheir recorded average income is about 980 dollars above the fitted value.\nThe printed regression equation abbreviates the coefficients; the stored\nmodel retains the digits needed for these calculations. R reproduces the\nfitted value and signed residual directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nteacher <- prestige[\"university.teachers\", ]\nteacher_fit <- predict(model, teacher)\nc(fitted = unname(teacher_fit),\n  residual = teacher$income_k - unname(teacher_fit),\n  at_12 = unname(predict(model, data.frame(education = 12))))\n#>        fitted      residual         at_12 \n#> 11.5004555017  0.9795444983  7.9321685196\n```\n:::\n\n\nFor an occupation averaging 12 years of education, the fitted value is\n7.9322 thousand dollars. `predict()` applies the saved line to the named\neducation value; it does not refit the model.\n\n@tbl-ch7-slope-readings sets the slope's reading beside two sentences a\nreport might also write about it.\n\n\\Needspace{12\\baselineskip}\n\n| A sentence about the slope 0.8988 | What it compares | Do these records support it? |\n|:--|:--|:--|\n| Occupations whose average education is one year higher have fitted average income about 899 dollars higher | Different occupations, along the fitted line | Yes, as a description of the 102 records over 6.38--15.97 years |\n| If an occupation's average education rose by one year, its average income would rise by about 899 dollars | One occupation before and after a change | No: it needs records of occupations over time and a design that isolates the change |\n| Another year of schooling raises a worker's income by about 899 dollars | One person before and after more schooling | No: it needs records of individuals and a causal design; occupation averages cannot supply either |\n\n: Three readings of one slope; only the first is a comparison these records make. {#tbl-ch7-slope-readings tbl-colwidths=\"[40,26,34]\"}\n\nOnly the first sentence compares what the records compare: occupations\nthat differ in average education. The second describes a change within\none occupation over time and the third a change within one person. The\nrecords observe neither, and a comparison between occupation averages\ncannot stand in for either one [@robinson1950]. The slope supports the\nfirst reading and is silent about the other two.\n\nThe intercept places the line vertically: it is its fitted income at\neducation zero. Zero is outside the observed range, so the negative intercept\nis not evidence that any recorded occupation has negative average income.\nCentering education at 12 would change the intercept to 7.9322 while leaving\nthe slope and all fitted values unchanged.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![The least-squares line passes through the mean point; the marked vertical segment is the university-teacher residual.](chapter_07_files/figure-html/fig-ch7-line-residual-1.png){#fig-ch7-line-residual fig-pos='H' fig-alt='A fitted line crosses the mean education and income. At 15.97 years, a vertical segment joins the fitted value to the higher university-teacher observation.' width=604.8}\n:::\n:::\n\n\n### Why this particular line?\n\nOrdinary least squares (**OLS**) chooses the intercept and slope that minimize\nthe **residual sum of squares**:\n\n$$\nRSS=\\sum_{i=1}^{n}(y_i-\\widehat\\beta_0-\\widehat\\beta_1x_i)^2.\n$$\n\nThe summation sign says to add the squared residual from every record.\nSquaring prevents positive and negative deviations from cancelling and gives\nlarge deviations more influence on the criterion. \"Best\" here means best by\nthis criterion among straight lines with an intercept, not best for every\nresearch purpose.\n\nTwo centered sums lead directly to the solution:\n\n$$\nS_{xx}=\\sum_i(x_i-\\bar x)^2,\\qquad\nS_{xy}=\\sum_i(x_i-\\bar x)(y_i-\\bar y),\n$$\n\n$$\n\\widehat\\beta_1=\\frac{S_{xy}}{S_{xx}}\n=\\frac{s_{xy}}{s_x^2}\n=r\\frac{s_y}{s_x},\n\\qquad\n\\widehat\\beta_0=\\bar y-\\widehat\\beta_1\\bar x.\n$$\n\nHere $\\bar x,\\bar y$ are means; $s_x,s_y$ are sample standard deviations;\n$s_{xy}$ is sample covariance; and $r$ is Pearson's correlation.\nThe variance and covariance both divide their centered sums by $n-1$, so\nthat divisor cancels in their ratio. The slope has income-per-education units;\ncorrelation has no units.\n\nFor these data,\n\n$$\n\\widehat\\beta_1=\\frac{675.8041}{751.8852}\\approx0.8988,\n\\qquad\n\\widehat\\beta_0=\\bar y-\\widehat\\beta_1\\bar x\\approx-2.8536.\n$$\n\nChapter 5's covariance and correlation matrices give the same calculation\nin a reusable form. For the same 102 complete education--income pairs, in\neducation--income order,\n\n$$\n\\mathbf S=\\begin{pmatrix}7.4444&6.6911\\\\6.6911&18.0279\\end{pmatrix},\n\\qquad\n\\mathbf R=\\begin{pmatrix}1&.5776\\\\.5776&1\\end{pmatrix}.\n$$\n\nThe covariance matrix records education variance in years squared, income\nvariance in squared thousand dollars, and their covariance in\nthousand-dollar-years. Dividing covariance by education variance cancels\nthe common $n-1$ divisor and gives the slope's thousand-dollars-per-year\nunits. Correlation removes units; multiplying it by the income SD divided\nby the education SD restores those same slope units. Computed from the\nunrounded entries, both routes return 0.8988: they reproduce the\ncentered-sum calculation rather than define a different fitted line. The\nComputer Lab carries out the centered sums and both matrix routes from the\nrecords.\n\nThe shared records matter as much as the formula. Entries formed by\nseparate pairwise deletion can describe different sets of occupations;\nthey need not reconstruct a regression fitted on one common set. No such\nmissingness occurs in these two columns.\n\nPositive covariance produces a positive slope, provided education varies at all.\nIf every occupation had the same education, $S_{xx}=0$ and a slope could\nnot be identified.\n\nThe fitted line passes through $(\\bar x,\\bar y)$, because substituting\n$\\bar x$ into the intercept formula gives $\\bar y$.\nWith an intercept, the residuals also sum to zero and their products with\n$x$ sum to zero. Otherwise the line could be shifted or tilted to reduce\nRSS. These are algebraic properties of OLS, not tests of independence or\nlinearity. Full normal-equation and projection-matrix derivations are retained\nin **Appendix A**.\n\n### A tiny calculation you can inspect completely\n\nThree teaching records, $(x,y)=(1,2),(2,4),(3,3)$, show the whole\nleast-squares calculation at once. Their means are $\\bar x=2$ and\n$\\bar y=3$. @tbl-ch7-tiny lays out the centered values, their squares and\nproducts, the fitted values and the residuals; its last row sums each\ncolumn.\n\n\\Needspace{12\\baselineskip}\n\n| $x$ | $y$ | $x-\\bar x$ | $y-\\bar y$ | $(x-\\bar x)^2$ | $(x-\\bar x)(y-\\bar y)$ | $\\widehat y$ | $e$ | $e^2$ |\n|--:|--:|--:|--:|--:|--:|--:|--:|--:|\n| 1 | 2 | $-1$ | $-1$ | 1 | 1 | 2.5 | $-0.5$ | 0.25 |\n| 2 | 4 | 0 | 1 | 0 | 0 | 3.0 | 1.0 | 1.00 |\n| 3 | 3 | 1 | 0 | 1 | 0 | 3.5 | $-0.5$ | 0.25 |\n| Sum |  | 0 | 0 | 2 | 1 | 9.0 | 0.0 | 1.50 |\n\n: The complete least-squares calculation for three records; the column sums give $S_{xx}$, $S_{xy}$ and $RSS$. {#tbl-ch7-tiny tbl-colwidths=\"[9,9,11,11,12,17,11,10,10]\"}\n\nThe sums give $S_{xx}=2$ and $S_{xy}=1$, so\n\n$$\n\\widehat\\beta_1=\\frac{S_{xy}}{S_{xx}}=\\frac12=0.5,\\qquad\n\\widehat\\beta_0=\\bar y-\\widehat\\beta_1\\bar x=3-0.5(2)=2.\n$$\n\nThe fitted values 2.5, 3.0 and 3.5 lie on this line. The residuals sum to\nzero, as the OLS properties above require, and their squares sum to\n$RSS=1.5$. No normality assumption is needed for these calculations. A\nstochastic model becomes necessary when we ask about repeated-sample\nuncertainty.\n\n### Compare candidate lines with the OLS minimum\n\nThe least-squares criterion also lets us compare the fitted line with\nalternatives. To keep the comparison transparent, make every candidate line\npass through $(\\bar x,\\bar y)$ and vary only its slope. For such a line,\n\n$$\nRSS(b_1)=RSS(\\widehat\\beta_1)\n       +S_{xx}(b_1-\\widehat\\beta_1)^2.\n$$\n\nThe added term is zero only at the OLS slope and positive for every other\nslope when $S_{xx}>0$. The following table checks five deliberately chosen\nlines on the occupation records. These are alternative summaries of the same\nrecords, not repeated samples.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-ch7-candidate-lines .cell tbl-cap='Candidate lines through the mean point and their residual sums of squares.'}\n::: {.cell-output-display}\n\n\n| Intercept|  Slope|       RSS|\n|---------:|------:|---------:|\n|    3.5892| 0.2988| 1484.0707|\n|    0.3678| 0.5988| 1281.0617|\n|   −2.8536| 0.8988| 1213.3920|\n|   −6.0750| 1.1988| 1281.0617|\n|   −9.2964| 1.4988| 1484.0707|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Five candidate lines through the sample mean. The OLS line has the smallest residual sum of squares.](chapter_07_files/figure-html/fig-ch7-candidate-lines-1.png){#fig-ch7-candidate-lines fig-pos='H' fig-alt='Five lines with different slopes cross at the mean occupation point. The highlighted OLS line runs centrally through the data; steeper and flatter alternatives have larger residual sums of squares.' width=604.8}\n:::\n:::\n\n\nEvery alternative has a larger RSS than the OLS line, and slopes the same\ndistance above and below 0.8988 add the same excess, as the identity\npredicts. The comparison also explains why high-income occupations can exert\nsubstantial influence: squaring gives large vertical discrepancies extra\nweight. That is a feature of the criterion, not evidence that those\noccupations are invalid.\n\n### Centering changes the reference point, not the line\n\nThe fitted equation can be written\n\n$$\n\\widehat y_i=\\bar y+\\widehat\\beta_1(x_i-\\bar x).\n$$\n\nCentering education at its observed mean makes the intercept equal to\n$\\bar y=6.7979$ thousand dollars, the fitted income at average education.\nIt leaves the slope, fitted values, residuals, RSS, and $R^2$ unchanged.\nCentering at 12 instead makes the intercept the already computed fitted value\n7.9322. Thus centering can make the intercept interpretable without changing\nthe comparison represented by the line. The Computer Lab refits the centered\nline and checks that every fitted value is unchanged.\n\nChanging income from thousands of dollars to dollars would multiply the\nintercept, slope, residual SD, and coefficient SEs by 1,000, while leaving\n$t$ statistics, $p$ values, correlation, and $R^2$ unchanged. A unit change\nis not new evidence or a stronger relationship.\n\n### How much variation remains? {#sec-ch7-fit}\n\nA fitted line can show a clear linear trend and still leave large differences\nbetween occupations unexplained by its fitted values.\n\nFor OLS with an intercept,\n\n$$\nTSS=\\sum_i(y_i-\\bar y)^2=RegSS+RSS,\n\\qquad RegSS=\\sum_i(\\widehat y_i-\\bar y)^2.\n$$\n\nFor the occupation records, $1820.8134=607.4214+1213.3920$.\nThis is a decomposition of squared deviations, in squared thousand-dollar\nunits. It holds because the cross-product of fitted deviations and residuals\nis zero.\n\nThe coefficient of determination is\n\n$$\nR^2=1-\\frac{RSS}{TSS}\n=1-\\frac{1213.3920}{1820.8134}\\approx.3336.\n$$\n\nThe fitted line accounts for 33.3599% of the variation in recorded income\naround its mean, according to this squared-deviation measure.\n\"Accounts for\" or \"explains\" in this algebraic sense does not mean causes.\nFor simple regression with an intercept, $R^2=r^2$:\n$.5776^2\\approx.3336$. The identity need not hold for other models or a\nno-intercept fit.\n\nThe residual standard deviation is\n\n$$\ns_e=\\sqrt{\\frac{RSS}{n-2}}\n=\\sqrt{\\frac{1213.392}{100}}=3.4834.\n$$\n\nIts units are thousand dollars, the same as income. Fitting an intercept and\nslope imposes two independent residual constraints, leaving $n-2$ residual\ndegrees of freedom. Under the constant-variance model introduced next,\n$s_e$ estimates the error standard deviation. Without that model it remains\na scaled measure of residual scatter; it is not the standard error of the\nslope or a guaranteed typical prediction error in new records.\n\n`sigma()` returns the residual SD of a fitted model, and `summary()`\nreports its $R^2$ among the other fit summaries:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(residual_SD = sigma(model), R_squared = summary(model)$r.squared)\n#>  residual_SD    R_squared \n#> 3.4833777071 0.3335989192\n```\n:::\n\n\nHere and below, $SE$ denotes an estimated standard error. The final row\nanticipates the separately declared process in the next section; it is\nnot uncertainty about the already computed finite-record slope.\n\n| Quantity | Occupation result | What it describes |\n|:--|--:|:--|\n| Slope | 0.8988 | Change in fitted thousand-dollar income per education year |\n| Residual SD | 3.4834 | Remaining income scatter on the outcome scale |\n| $R^2$ | .3336 | Proportion of centered squared variation accounted for in these records |\n| Classical slope SE | 0.1270 | Model-based repetition variability of the slope, under the next assumptions |\n\n: Different summaries have different units and jobs. {#tbl-ch7-quantities tbl-colwidths=\"[24,22,54]\"}\n\n\\Needspace{16\\baselineskip}\n\n## Make and Read a Model-Based Inference {#sec-ch7-inference}\n\n### Announce the inferential extension before its interval\n\nThe finite-record slope is not waiting to be discovered in a larger population:\nwe have computed it for all 102 records named in the focal question.\nA confidence interval answers an additional question.\n\nFor a **separable teaching extension**, suppose occupations' outcomes arose\nindependently from a process with conditional mean\n\n$$\nE(Y_i\\mid X_i=x_i)=\\beta_0+\\beta_1x_i.\n$$\n\nThe estimand $\\beta_1$ is now a constant conditional-mean slope in that\nhypothetical process, not the fixed slope of these 102 records. Repetition\nmeans generating new outcomes from that process at the stated predictor values\nand refitting. It does not mean that the documented occupations were randomly\nsampled. Changing the estimand changes the question--answer pair.\n\nWrite the process as\n\n$$\nY_i=\\beta_0+\\beta_1x_i+\\varepsilon_i,\\qquad\nE(\\varepsilon_i\\mid\\mathbf X)=0,\\qquad\n\\operatorname{Var}(\\varepsilon_i\\mid\\mathbf X)=\\sigma^2.\n$$\n\nFor the exact classical $t$ procedure, errors are independent and conditionally\nnormal with this common variance, and $S_{xx}>0$. The $x_i$ values need not\nbe normal; neither must the marginal distribution of $Y$. It is the\nconditional error distribution, not the histogram of every variable, that\nappears in the model. Independence is supported by how records arise, not by a\ngood-looking residual plot.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![What the process conditions claim, drawn on the occupation records: at each education value, a Normal distribution of incomes centred on the line, with the same spread everywhere.](chapter_07_files/figure-html/fig-ch7-conditional-1.png){#fig-ch7-conditional fig-pos='H' fig-alt='The 102 occupation records and the fitted line rising from about 3 to 12 thousand dollars over education 6 to 16. At 8, 10, 12 and 14 years, an identical bell-shaped curve stands sideways on the line, spreading about 10 thousand dollars above and below it; the curve at 8 years extends below zero income, while several high-income records at 12 years and above lie beyond the curves\\' upper tails.' width=604.8}\n:::\n:::\n\n\n@fig-ch7-conditional draws what these conditions claim, using the fitted\nline and the residual SD, 3.4834, in place of the unknown $\\beta_0$,\n$\\beta_1$ and $\\sigma$. At every education value the model places a Normal\ndistribution of incomes centred on the line, with one common spread. The\nrecords do not look like that everywhere: at higher education they spread\nmore widely, and several incomes lie far beyond the upper tails, which\nSection 6 examines. At 8 years the curve reaches below zero, a first sign\nthat a Normal model for a nonnegative outcome is an approximation, which\nSection 5 meets again.\n\nTo see where slope uncertainty comes from, substitute the process equation\ninto the OLS slope formula. Here $\\mathbf X$ denotes the predictor values on which\nwe condition. Since $\\sum_i(x_i-\\bar x)=0$,\n\n$$\n\\widehat\\beta_1-\\beta_1\n=\\frac{\\sum_i(x_i-\\bar x)\\varepsilon_i}{S_{xx}}.\n$$\n\nThe fitted slope differs from the process slope because the realized errors\nneed not cancel when weighted by distance from mean education. Independence\nmakes their covariance terms zero; common variance gives\n\n$$\n\\operatorname{Var}(\\widehat\\beta_1\\mid\\mathbf X)\n=\\frac{\\sigma^2\\sum_i(x_i-\\bar x)^2}{S_{xx}^2}\n=\\frac{\\sigma^2}{S_{xx}}.\n$$\n\nThis variance identity does not require normal errors. Normality enters the\nexact $t$ reference. Taking the square root and estimating $\\sigma$ by $s_e$\ngives the slope standard error:\n\n$$\nSE(\\widehat\\beta_1)=\\frac{s_e}{\\sqrt{S_{xx}}}\n=\\frac{3.4834}{\\sqrt{751.8852}}=0.127,\n$$\n\n$$\n\\widehat\\beta_1\\ \\pm\\ t_{.975,n-2}SE(\\widehat\\beta_1)\n\\approx0.8988\\pm1.984(0.127)\n\\approx[0.6468,\\ 1.1508].\n$$\n\nThe critical value 1.984 is the 97.5th percentile of a $t$ distribution with\n100 degrees of freedom. More error variation raises the SE; greater predictor\nspread lowers it when the other quantities are held fixed. More observations\nusually improve precision through their contribution to $S_{xx}$, but\ndependent observations do not supply independent information merely by\nincreasing the row count.\n\nThe null test $H_0:\\beta_1=0$ uses\n$t=\\widehat\\beta_1/SE(\\widehat\\beta_1)\\approx7.0753$ and a two-sided\n$p<.0001$.\nThis is evidence against that zero-slope model under the stated procedure.\nIt is not the probability that the null is true, the probability that the\ndata occurred by chance, evidence of causation, or a measure of practical\nimportance. The interval describes the range produced by this uncertainty\nmethod, not a 95% probability assigned to the fixed parameter after observing\nthis interval. The next section makes the repeated-sample interpretation\nvisible before prediction is introduced.\n\nThe coefficient table gives the estimate, its SE, and the test; the interval\ncall returns the corresponding two-sided limits. The function's default\nconfidence level is .95.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef(summary(model))\n#>                  Estimate   Std. Error      t value        Pr(>|t|)\n#> (Intercept) -2.8535855824 1.4070392470 -2.028078171 4.521163138e-02\n#> education    0.8988128418 0.1270354112  7.075293679 2.079192410e-10\nconfint(model, \"education\")\n#>                  2.5 %      97.5 %\n#> education 0.6467782042 1.150847479\n```\n:::\n\n\nThe assumptions are a proposed justification, not facts created by the formula.\nCurvature, changing spread, or dependence can invalidate the exact coverage\nclaim. Section 6 examines these conditions on the occupation records.\n\n### Connect the Pearson and slope tests {#ch07-correlation-test}\n\nChapter 5 tested a zero Pearson correlation. The simple regression now\nlets us connect that familiar statistic to the slope calculation. For an\nOLS line with an intercept, fitted to the same complete pairs,\n\n$$\n\\begin{aligned}\nt_{\\mathrm{slope}}\n&=\\frac{\\widehat\\beta_1}{s_e/\\sqrt{S_{xx}}}\n=r\\sqrt{\\frac{n-2}{1-r^2}}\n=t_{\\mathrm{Pearson}},\\\\\nF_{\\mathrm{regression}}\n&=t_{\\mathrm{slope}}^2\n=\\frac{R^2}{1-R^2}(n-2).\n\\end{aligned}\n$$\n\nThe first identity follows by substituting the covariance expression for\nthe slope and using $RSS=(1-r^2)TSS$. The second compares the\nintercept-only mean model with the intercept-and-slope model: their\nnumerator degrees of freedom differ by one. The signed $t$ retains the\nslope's direction; squaring it gives the nondirectional $F$ statistic.\n\nFor the occupation line, Chapter 5's Pearson test and the slope test both\ngive $t=7.0753$ on 100 df, and the $F$ statistic that `summary()` prints\nis $F(1,100)=50.0598=t^2$; the matched two-sided $t$ and upper-tail $F$\np-values are below .0001. These entries express the same\none-parameter comparison, not three independent pieces of evidence. The\nComputer Lab reproduces all three from the fitted model.\n\nEquality of the statistics is algebraic. Their exact classical references\nuse the independent, constant-variance Normal error model already stated.\nFor randomly sampled bivariate-Normal pairs, a zero population correlation\nis also equivalent to a zero linear conditional-mean slope. The documented\noccupation records provide no probability-sampling warrant: here the\nPearson call reproduces the declared process calculation numerically,\nrather than adding a new population-correlation claim.\n\nMatch the intercept, rows, weights, and covariance convention before\ncomparing outputs. An HC3 slope test uses a different covariance estimate;\nit need not equal the ordinary ANOVA $F$ calculation. Section 6 uses that\nchange to examine uncertainty while keeping the fitted line fixed.\n\n### A binary predictor: the two-group comparison as a line {#ch07-binary-predictor}\n\nA predictor need not be continuous. Chapter 4's invented feedback study\nrecorded a practice schedule for each of its 24 pupils, twelve under\nmassed practice and twelve under spaced practice, with a score out of 20;\nChapter 6 fitted the same scores by feedback condition with a model\nformula. Code the schedule as $x_i=0$ for massed and $x_i=1$ for spaced,\nand fit the same kind of line. With only two predictor values, the\nleast-squares line passes through the two group means\n(@fig-ch7-binary): the intercept is the massed mean and the slope is the\ndifference of means,\n\n$$\n\\widehat\\beta_0=\\bar y_0=8,\\qquad\n\\widehat\\beta_1=\\bar y_1-\\bar y_0=12-8=4.\n$$\n\nThe residual SD is the pooled SD of the equal-variance procedure,\n$s_e=4.156$ on $24-2=22$ df, and the slope SE formula becomes\n$SE(\\widehat\\beta_1)=s_e\\sqrt{1/n_0+1/n_1}=4.156\\sqrt{1/12+1/12}=1.6967$,\nso $t=4/1.6967=2.3575$ on 22 df with $p=.0277$ and interval\n$[0.4813,\\ 7.5187]$, which the Computer Lab reproduces with `t.test()`.\nThese are exactly the equal-variance two-sample $t$\ntest and interval for a difference in means (Chapters 3 and 5): a\nregression on a 0/1 predictor is that procedure written as a line. The\nmatched statistics hold as well, with $R^2=.2017$ and\n$F(1,22)=5.5579=t^2$.\n\n\\Needspace{14\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscore <- c(4, 5, 7, 8, 4, 5, 7, 8, 6, 7, 9, 10, 10, 11, 13, 14,\n           8, 9, 11, 12, 16, 17, 19, 20)\nspaced <- rep(rep(c(0, 1), each = 4), 3)\ntwo_groups <- lm(score ~ spaced)\ncoef(summary(two_groups))\n#>             Estimate  Std. Error     t value        Pr(>|t|)\n#> (Intercept)        8 1.199747448 6.668070028 1.053846789e-06\n#> spaced             4 1.696699113 2.357518767 2.770679048e-02\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![With a 0/1 predictor, the least-squares line joins the two group means: the intercept is the massed mean and the slope the difference in means.](chapter_07_files/figure-html/fig-ch7-binary-1.png){#fig-ch7-binary fig-pos='H' fig-alt='Twenty-four invented scores plotted at 0 for massed and 1 for spaced practice, massed scores from 4 to 12 and spaced from 7 to 20. A line joins the massed mean 8 to the spaced mean 12, both marked with filled diamonds.' width=537.6}\n:::\n:::\n\n\nWelch's unequal-variance test (Chapter 3) uses the separate group SDs,\n2.3741 and 5.3767, and gives 15.1322 df and $p=.0323$. The one-line\nregression assumes a common error variance; that is the model's\nassumption, not a fact about the pupils. The HC3 covariance of Section 6\nkeeps the fitted line and gives a slope SE of 1.7721 under the same\nindependence assumption. A factor with more than two levels needs more\nthan one 0/1 column; Chapter 9 develops that coding, its contrasts, and\nthe equivalence with the analysis of variance of Chapter 4.\n\n\\Needspace{16\\baselineskip}\n\n## See Sampling Uncertainty Through Repetition {#sec-ch7-repetition}\n\n### A known-truth line and one fitted sample\n\nGenerate 20 outcomes at predictor values equally spaced from 6 to 16:\n\n$$\nY_i=2+0.5x_i+\\varepsilon_i,\\qquad\n\\varepsilon_i\\overset{\\mathrm{ind}}\\sim\\mathcal N(0,1).\n$$\n\nThese units and values are a teaching construction, not occupation records.\nThe true intercept is 2, true slope is 0.5, and true error SD is 1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nknown_data <- data.frame(x = seq(6, 16, length.out = 20))\nknown_data$y <- 2 + 0.5 * known_data$x + rnorm(20, sd = 1)\nknown_model <- lm(y ~ x, data = known_data)\n```\n:::\n\n\n`set.seed()` fixes the random start, so the same 20 errors are drawn each\ntime, and `rnorm()` draws them with SD 1. @tbl-ch7-known-sample reports\nthe fitted coefficients, their SEs and the residual SD of `known_model`.\n\n\\Needspace{10\\baselineskip}\n\n\n::: {#tbl-ch7-known-sample .cell tbl-cap='One fitted sample from a process with known coefficients and error SD.'}\n::: {.cell-output-display}\n\n\n|Quantity    | Estimate| Model SE|\n|:-----------|--------:|--------:|\n|Intercept   |   2.4770|   0.8362|\n|Slope       |   0.4695|   0.0733|\n|Residual SD |   0.9945|         |\n\n\n:::\n:::\n\n\nThe last cell is blank because residual SD is a scale estimate, not a\ncoefficient with a coefficient standard error.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Known and fitted lines for one simulated dataset. The true process is programmed; the fitted line responds to the realized errors.](chapter_07_files/figure-html/fig-ch7-core-true-fitted-1.png){#fig-ch7-core-true-fitted fig-pos='H' fig-alt='Twenty simulated points surround the known line with intercept two and slope one half. A solid fitted line and dashed true line differ slightly.' width=672}\n:::\n:::\n\n\nThe fitted slope and intercept need not equal their programmed values in\none sample. The unobserved error is the deviation from the true mean;\nthe residual is the observed deviation from the fitted line. Even when\nthe errors are independent, fitted residuals are linked by their zero-sum\nand zero-covariance constraints. A residual plot is an imperfect diagnostic\nwindow on error behavior, not a direct sample of observed true errors.\n\n### Repeated samples and the sources of slope precision\n\nRecall the generate--estimate--repeat route from Chapters 5 and 6.\nThe next experiment holds 40 predictor values fixed and regenerates only\nthe errors, 2,000 times. The study size is 40; the repetition count is\n2,000. Increasing the latter refines the simulation's description of the\nsame study-level procedure. It records slopes, estimated standard errors,\nand whether each classical interval covers the known slope 0.5.\n\nFor one repetition, generate new independent errors, add them to the same\n40 process means, fit a line, and record its slope and estimated SE. Check\nwhether its interval contains the programmed slope, then start the next\nrepetition with new errors. Holding the predictor grid fixed isolates\noutcome variation; it does not resample the historical occupations. The Computer\nLab provides the complete loop and a small change in the repetition count.\n\n\n::: {.cell}\n\n:::\n\n\n\\Needspace{9\\baselineskip}\n\n\n::: {#tbl-ch7-repeated-slopes .cell tbl-cap='Slope behavior across 2,000 repetitions of the known process.'}\n::: {.cell-output-display}\n\n\n|Quantity                           |Value  |\n|:----------------------------------|:------|\n|Mean estimated slope               |0.5018 |\n|SD of estimated slopes             |0.0528 |\n|Mean estimated SE                  |0.0531 |\n|Theoretical slope SD               |0.0534 |\n|Fraction of intervals covering 0.5 |.9455  |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Slopes in 2,000 repetitions of the known process. The vertical reference is the true slope, 0.5.](chapter_07_files/figure-html/fig-ch7-core-repetition-1.png){#fig-ch7-core-repetition fig-pos='H' fig-alt='A roughly symmetric histogram of repeated fitted slopes is centered near one half; its spread represents repeated-sample slope variation.' width=604.8}\n:::\n:::\n\n\nThe empirical SD of the slopes estimates their repeated-sample spread. Each\nfitted SE tries to estimate that spread using just one sample. Coverage is a\nproperty of the repeated interval-producing procedure, not a probability\nassigned to a fixed parameter after one interval is realized. The empirical\ncoverage will not be exactly .95: at true .95 coverage, its Monte Carlo SE\nwith 2,000 independent repetitions is\n$\\sqrt{.95(.05)/2000}\\approx0.0049$.\n\nThe theoretical slope SD is $\\sigma/\\sqrt{S_{xx}}$. More noise increases\nit; greater predictor spread decreases it. More observations typically\ndecrease it when the predictor distribution is held comparable.\n@tbl-ch7-precision-conditions changes one feature at a time and applies the\nformula to each design.\n\n\n::: {.cell}\n\n:::\n\n\n\\Needspace{9\\baselineskip}\n\n\n::: {#tbl-ch7-precision-conditions .cell tbl-cap='How sample size, predictor support, and error SD affect theoretical slope precision.'}\n::: {.cell-output-display}\n\n\n|Condition        |   n| Lower| Upper| Error SD|Slope SD |\n|:----------------|---:|-----:|-----:|--------:|:--------|\n|Baseline         |  40|   6.0|  16.0|        1|0.0534   |\n|More rows        | 160|   6.0|  16.0|        1|0.0272   |\n|Narrower support |  40|   8.5|  13.5|        1|0.1068   |\n|More noise       |  40|   6.0|  16.0|        2|0.1068   |\n\n\n:::\n:::\n\n\nHalving the predictor range at the same sample size doubles the slope SD;\ndoubling $\\sigma$ also doubles it. Quadrupling the number of equally spaced\npoints over the same range approximately halves it; the small difference\nfrom an exact half comes from the finite grids' variances. Using `x <- 1:n`\nwhile increasing $n$ would change both sample size and predictor range.\nMore rows do not automatically remove confounding, measurement error,\ndependence, or misspecification. These simulations establish behavior only\nunder the mechanisms programmed into them.\n\n\\Needspace{9\\baselineskip}\n\n## Distinguish a Mean Response from a New-Case Prediction {#sec-ch7-prediction}\n\nSlope uncertainty concerns one process coefficient. Prediction introduces a\ndifferent distinction: estimating a conditional mean versus anticipating one\nnew outcome from the same declared process.\n\n### A fitted mean is not a new occupation\n\nAt $x_0=12$, the fitted income is 7.9322 thousand dollars. Under the model,\nthis estimates the conditional mean for occupations with that average\neducation. The standard error for the fitted mean is\n\n$$\nSE(\\widehat y_0)\n=s_e\\sqrt{\\frac1n+\\frac{(x_0-\\bar x)^2}{S_{xx}}}.\n$$\n\nSubstitution gives\n\n$$\n3.4834\\sqrt{\\frac1{102}+\n \\frac{(12-10.738)^2}{751.8852}}=0.3803.\n$$\n\nThe resulting 95% mean interval is\n$7.9322\\pm1.984(0.3803)\\approx[7.1776,8.6868]$.\n\nA new occupation's outcome also varies around its process mean.\nWrite $\\mu_0=\\beta_0+\\beta_1x_0$, $\\widehat\\mu_0=\\widehat y_0$, and\n$Y_0=\\mu_0+\\varepsilon_0$. The prediction error has two parts:\n\n$$\nY_0-\\widehat\\mu_0\n=\\varepsilon_0-(\\widehat\\mu_0-\\mu_0).\n$$\n\nIf this new error is independent of the fitted data and comes from the same\ncommon-variance process, the two variance contributions add:\n\n$$\n\\operatorname{Var}(Y_0-\\widehat\\mu_0\\mid\\mathbf X,x_0)\n=\\sigma^2+\\operatorname{Var}(\\widehat\\mu_0\\mid\\mathbf X,x_0).\n$$\n\nThe first term is new outcome variation; the second is uncertainty in the\nestimated mean. Substituting the fitted-mean variance and estimating $\\sigma$\nby $s_e$ gives\n\n$$\nSE_{\\mathrm{new}}\n=s_e\\sqrt{1+\\frac1n+\\frac{(x_0-\\bar x)^2}{S_{xx}}}\n=3.5041.\n$$\n\nThus the 95% prediction interval is approximately\n$7.9322\\pm1.984(3.5041)\\approx[0.9802,14.8842]$.\nThe extra 1 is the new outcome's own error variance, expressed as a multiple\nof $\\sigma^2$; it does not disappear as the estimation sample grows.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Mean-response intervals and new-case prediction intervals under the same working model.](chapter_07_files/figure-html/fig-ch7-intervals-1.png){#fig-ch7-intervals fig-pos='H' fig-alt='The mean-confidence band is narrowest near average education. The new-case prediction band is much wider throughout the observed education range.' width=604.8}\n:::\n:::\n\n\nBoth intervals get wider away from $\\bar x$, even within the observed range.\nOutside that range, numerical output is not a warrant for extrapolation.\nA lower prediction bound below zero also exposes the limitations of an\nunrestricted normal-error model for a nonnegative outcome; it is not a\nplausible negative-income forecast.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model, data.frame(education = 12), interval = \"confidence\")\n#>          fit        lwr         upr\n#> 1 7.93216852 7.17757965 8.686757389\npredict(model, data.frame(education = 12), interval = \"prediction\")\n#>          fit          lwr        upr\n#> 1 7.93216852 0.9801724429 14.8841646\n```\n:::\n\n\nA separately owed new-case prediction answer is a separable question, not\nautomatically another strand of the original descriptive question.\nMoreover, a model prediction interval is not a test of a learning algorithm\non unseen records. Held-out prediction performance is a distinct estimand,\ndeveloped with multiple regression. Appendix A retains the interval\nderivations and further supported-value comparisons.\n\n\n## Check Form, Spread, Influence, and Support {#sec-ch7-check}\n\n### Checks should change an interpretation or a decision\n\nThe fitted line does not have to satisfy a stochastic model to exist.\nBut claims that it describes a linear conditional mean, that its classical\ninterval has exact coverage, or that it predicts new occupations reliably\nneed additional support.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Residual pattern and influence invite different follow-up questions.](chapter_07_files/figure-html/fig-ch7-checks-1.png){#fig-ch7-checks fig-pos='H' fig-alt='The left panel shows curvature and uneven scatter in residuals. The right panel shows Cook\\'s distances, with physicians most influential for this fit.' width=614.4}\n:::\n:::\n\n\nA curve in residuals suggests that one straight conditional mean leaves\nsystematic variation. A changing residual spread challenges a common-variance\nuncertainty calculation. Leverage concerns unusual predictor positions;\ninfluence concerns how much the fitted model changes when a record's\ncontribution changes. A large residual, high leverage, and high influence are\nrelated but different properties.\n\n\\Needspace{7\\baselineskip}\n\nFor a straight line with an intercept, leverage is\n\n$$\nh_i=\\frac1n+\\frac{(x_i-\\bar x)^2}{S_{xx}}.\n$$\n\nIt grows as a predictor value moves away from $\\bar x$. Cook's distance then\ncombines leverage and residual magnitude:\n\n$$\nD_i=\\frac{e_i^2}{2s_e^2}\\frac{h_i}{(1-h_i)^2}.\n$$\n\nCook's distance summarizes how much the fitted values change when case $i$\nis omitted, relative to residual variation and the two fitted coefficients.\nIt is a prompt to inspect provenance and sensitivity, not an automatic\ndeletion cutoff.\n\nFor these data, adding education squared lets the fitted relationship bend.\nThe following same-record comparison makes the change in shape visible. It\nis an exploratory check, not a retrospectively prespecified new final model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquad <- lm(income_k ~ education + I(education^2), data = prestige)\nmost <- which.max(cooks.distance(model))\nwithout <- lm(income_k ~ education, data = prestige[-most, ])\nc(full = unname(coef(model)[2]), without = unname(coef(without)[2]))\n#>         full      without \n#> 0.8988128418 0.7982204353\ncoef(summary(quad))[\"I(education^2)\", ]\n#>       Estimate     Std. Error        t value       Pr(>|t|) \n#> 0.134179313419 0.047636405684 2.816738825952 0.005856544055\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Straight and quadratic fits to the same 102 records. The curve is an exploratory sensitivity, not a selected final model.](chapter_07_files/figure-html/fig-ch7-curvature-1.png){#fig-ch7-curvature fig-pos='H' fig-alt='The quadratic fit bends upward toward higher education, unlike the constant-slope straight line. Both fits use all 102 occupation records on the same income scale.' width=604.8}\n:::\n:::\n\n\nThe quadratic coefficient has $p=.0059$ under that model's classical\nreference calculation. This is a reason to examine the visible curvature,\nnot a sufficient model-selection rule: unequal spread and choosing the\ncomparison after inspecting the records also qualify that number.\n\nRemoving physicians, the record with the largest Cook's\ndistance (0.3983), changes the slope from 0.8988 to 0.7982.\nNothing in that result proves physicians were recorded incorrectly. The\ndeletion is a sensitivity calculation; it is not our replacement analytic\nsample or a licence to hide a valid unusual occupation.\n\n\\Needspace{7\\baselineskip}\n\nAn HC3 heteroskedasticity-consistent covariance calculation gives a slope SE\nof 0.1491 rather than 0.1270. Using the same $t_{100}$ critical value as an\napproximate sensitivity procedure gives $[0.6031,1.1945]$.\nThe line does not change. This procedure relaxes a variance assumption under\nsuitable independent-observation conditions; it does not repair curvature,\ndependence, confounding, or measurement error [@white1980; @mackinnon1985;\n@long2000; @zeileis2004].\nIts finite-sample interval is not the exact classical normal-model interval.\nThe short R calculation makes the covariance choice explicit:\n\n\\Needspace{10\\baselineskip}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nV_hc3 <- sandwich::vcovHC(model, type = \"HC3\")\nc(classical = coef(summary(model))[\"education\", \"Std. Error\"],\n  HC3 = sqrt(V_hc3[\"education\", \"education\"]))\n#>    classical          HC3 \n#> 0.1270354112 0.1490510028\n```\n:::\n\n\nLater chapters take these questions further. Chapter 8, Appendix B,\nassembles the HC3 matrix from its parts. Chapter 9, Appendix A, defines\nthe target that a least-squares line estimates when the conditional mean\nis not linear, and its Section 5.3 shows that measurement error in the\npredictor attenuates a slope, which no covariance choice repairs. Nothing\nin this chapter relies on any of them.\n\n\\Needspace{20\\baselineskip}\n\n| Check | What needs to be examined | Consequence |\n|:--|:--|:--|\n| Form | Residual curve and a curved-fit comparison | A straight line may remain a description but fail as a constant conditional-mean slope account |\n| Spread | Residual variation over fitted values | Classical SEs may need revision; HC3 is a variance sensitivity, not a universal repair |\n| Influence | Source record and result with/without a consequential case | Disclose sensitivity; correct errors only when verified |\n| Independence | How occupations and measurements were generated or related | A plot cannot establish independent process realizations |\n| Support | Actual education range and density of observations | Restrict comparisons; avoid extrapolation and individual-level claims |\n\n: Diagnostic questions and their consequences. {#tbl-ch7-diagnostic-consequences tbl-colwidths=\"[16,38,46]\"}\n\n\\Needspace{24\\baselineskip}\n\n## Regression Toward the Mean {#sec-ch7-rtm}\n\n### A line in standard units\n\nFrancis Galton, who gave regression its name, measured the adult heights\nof parents and their grown children in 205 families in the 1880s\n[@galton1886]. We use James Hanley's transcription of Galton's notebook\n[@hanley2004], distributed in the R package HistData [@friendly2025], and\nkeep one row per family: among the 179 families with at least one son,\none son was drawn at random from each, so every father appears once and\nthe rows describe separate families. Heights are in inches, mostly\nrecorded to the nearest half inch. The small extract `galton1886_sons.csv` is\nsupplied with the chapter under this note: *Galton's family heights\n(published 1886), transcribed by J. A. Hanley and distributed in the R\npackage HistData under the GPL; one son per family drawn for QMSBR. The\nmeasurements are historical records in the public domain; the extract is\nredistributed with this attribution.*\n\nChapter 2 measured a value's distance from its mean in standard units,\n$z_x=(x-\\bar x)/s_x$, and Section 2.2 wrote the slope as\n$\\widehat\\beta_1=r\\,s_y/s_x$. Substituting that slope into the line\nthrough the mean point, $\\widehat y-\\bar y=\\widehat\\beta_1(x-\\bar x)$, and\ndividing both sides by $s_y$ gives the line in standard units:\n\n$$\n\\frac{\\widehat y-\\bar y}{s_y}=r\\,\\frac{x-\\bar x}{s_x},\n\\qquad\\text{that is,}\\qquad\n\\widehat z_y=r\\,z_x .\n$$\n\nThe line passes through the origin with slope $r$. Unless the correlation\nis perfect, $\\lvert r\\rvert<1$, so a case $z_x$ SDs from the mean on the\npredictor is predicted only $r\\,z_x$ SDs from the mean on the outcome,\neach measured in its own SDs. Galton called this regression toward\nmediocrity; we call it **regression toward the mean**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngalton <- read.csv(\"galton1886_sons.csv\")\nsapply(galton[c(\"father\", \"son\")], sd)\n#>      father         son \n#> 2.546555039 2.647465487\nc(r = cor(galton$father, galton$son),\n  z_slope = unname(coef(lm(scale(son) ~ scale(father),\n    data = galton))[2]))\n#>            r      z_slope \n#> 0.4269305719 0.4269305719\n```\n:::\n\n\n`sapply()` applies `sd()` to both columns, and `scale()` converts a column\nto standard units. The fathers average 69.0989 inches with SD 2.5466, the\nsons 69.2140 inches with SD 2.6475, and their correlation is $r=.4269$. In\ninches the fitted slope is 0.4438 inch of son's height per inch of\nfather's height; fitted to the standardized heights it is .4269, which is\n$r$, as the equation says. A father 1.6 SD above the fathers' mean has a\nson predicted $.4269\\times1.6=0.6831$ SD above the sons' mean: still\ntaller than average, but less than half as far out.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Galton's 179 fathers and sons in standard units. The fitted line has slope $r=.4269$, flatter than the dashed line of slope 1; the filled points are the mean positions of the fathers more than 1 SD above and below their mean, with their sons.](chapter_07_files/figure-html/fig-ch7-rtm-1.png){#fig-ch7-rtm fig-pos='H' fig-alt='A cloud of 179 points, fathers\\' heights in standard units from about −2.8 to 3.7 across and sons\\' from about −3.5 to 2.8 up. A dashed line of slope 1 and a solid fitted line of slope about 0.43 cross at the origin. Two filled diamonds, near (1.6, 0.7) and (−1.5, −0.6), sit close to the solid line, inside the dashed one.' width=518.4}\n:::\n:::\n\n\nIn @fig-ch7-rtm the dashed line of slope 1 marks where a son would sit if\nhe were exactly as many SDs from his mean as his father. The fitted line\nis flatter. To the right of the mean it lies below the dashed line and to\nthe left above it: tall fathers have sons predicted less tall, and short\nfathers sons predicted less short, in standard units. The two filled\npoints mark the average positions of the fathers more than 1 SD above and\nbelow their mean, with their sons; both sit near the fitted line, well\ninside the dashed one.\n\n### Extreme groups move toward the mean; the spread does not\n\n@tbl-ch7-rtm-groups groups the men in bands of 1 SD, first by the fathers'\nheights and then by the sons'. Each band includes its upper bound, so the\nfour bands of each block hold all 179 men.\n\n\\Needspace{14\\baselineskip}\n\n| Selected on | Band (SDs) | Men | Mean $z$ of the selected height | Mean $z$ of the other height | $r$ times the selected mean |\n|:--|:--|--:|--:|--:|--:|\n| Fathers | Above $+1$ | 24 | 1.6072 | 0.7029 | 0.6862 |\n| Fathers | 0 to $+1$ | 60 | 0.4978 | 0.2251 | 0.2125 |\n| Fathers | $-1$ to 0 | 65 | $-0.3463$ | $-0.2058$ | $-0.1479$ |\n| Fathers | Below $-1$ | 30 | $-1.5310$ | $-0.5668$ | $-0.6536$ |\n| Sons | Above $+1$ | 31 | 1.4057 | 0.6224 | 0.6001 |\n| Sons | 0 to $+1$ | 60 | 0.4650 | 0.1431 | 0.1985 |\n| Sons | $-1$ to 0 | 61 | $-0.4610$ | $-0.0697$ | $-0.1968$ |\n| Sons | Below $-1$ | 27 | $-1.6057$ | $-0.8751$ | $-0.6855$ |\n\n: Groups of Galton's fathers and sons in standard units, selected on either height. {#tbl-ch7-rtm-groups tbl-colwidths=\"[12,14,8,22,22,22]\"}\n\nRead the first block row by row. The 24 fathers more than 1 SD above\ntheir mean average $z=1.6072$, or 73.1917 inches; their sons average\n0.7029, or 71.0750 inches, close to the line's prediction\n$.4269\\times1.6072=0.6862$. The 30 short fathers mirror them. In every\nrow the other height's mean lies between zero and the selected mean,\nnear $r$ times it; bands nearer the middle move less, because they start\nnearer the mean.\n\nThe second block selects on the sons, and the movement toward the mean\nappears again, now running backward in time: the 31 sons more than 1 SD\nabove their mean, at 1.4057, had fathers averaging only 0.6224. No force\npulls heights toward the average from one generation to the next; such a\nforce could not act backward in time. An imperfect correlation is\nenough for the fitted line: its predictions lie closer to the mean, in\nstandard units, than the values they are predicted from. For groups of\nmen, the pattern also needs the mean of one height to follow a straight\nline in the other, as it roughly does in these families; then selecting\nmen for an extreme value of one height selects, on average, men whose\nother height is less extreme. On average is the operative phrase: a\ngroup's observed mean scatters around its prediction, so an imperfect\ncorrelation does not guarantee that every group selected for an extreme\nvalue sits nearer the mean on the other height.\n\nIf tall fathers have sons nearer the mean and short fathers do too,\nshould the sons' heights be less spread out than their fathers'? They are\nnot: the sons' SD, 2.6475 inches, is slightly larger than the fathers',\n2.5466. This is the **regression paradox**. The fitted values carry only\nthe part of a son's height that his father's height predicts, and they\nspread only $r\\,s_y=1.1303$ inches. The residuals carry the rest, with\nspread $s_y\\sqrt{1-r^2}=2.3941$ inches (both SDs with the $n-1$ divisor;\n`sigma()` divides by $n-2$ and gives 2.4008). The two parts combine\nthrough their variances, not their SDs: $1.1303^2+2.3941^2=2.6475^2$,\nSection 2.6's decomposition of total variation, in which the fitted part\nholds the share $R^2=r^2=.1823$. Some sons of average fathers are very\ntall or very short, so the sons' generation is as varied as the\nfathers'. Regression toward the mean describes predictions for selected\ngroups, not a population growing more uniform.\n\n### The regression fallacy\n\nRegression toward the mean becomes a fallacy when the movement it\npredicts is credited to a cause. Tversky and Kahneman [-@tversky1974] recount a conversation with flight instructors: a trainee praised for an\nunusually smooth landing tended to land less well next time, and a\ntrainee reprimanded for a rough landing tended to do better, so the\ninstructors concluded that praise hurts and criticism helps.\n\nThe line in standard units explains the pattern without either\nconclusion. A landing's quality reflects the trainee's skill and the\nchance conditions of that attempt, so two landings by the same trainee\nare correlated, but not perfectly. The landings that drew comment were\nselected for being extreme, and the next landing is predicted nearer the\ntrainee's usual level whatever the instructor says: the praise and the\ncriticism coincided with regression toward the mean. Crediting that\nmovement to the feedback is the **regression fallacy**.\n\nThe same pattern appears whenever cases are selected for an extreme first\nmeasurement and measured again: pupils chosen for their low test scores\nand given extra help, patients enrolled when their symptoms peak, schools\nplaced on a list after their worst year. On the second measurement such\ngroups move toward the mean on average even if nothing done in between\nhas any effect. A comparison group selected the same way and measured at the same\ntwo times shows how much movement selection alone produces. Assigning the\nhelp at random among the selected cases does better still, since both\ngroups then regress alike and their difference estimates the help's\neffect [@barnett2005]. Chapter 14, Section 4.1, applies this reasoning to\nselection on a noisy baseline.\n\n## Reading Bridge {#sec-ch7-summary}\n\nA simple regression starts with a comparison and a unit. Its fitted values\nand residuals are calculations on records. Least squares connects the\nslope to covariance and predictor variation and puts the line through the\nmean point. Residual SD, $R^2$, slope uncertainty, and new-case variation\nanswer different questions; the matched Pearson, slope, and $F$ statistics\nconnect calculations without supplying a sampling design.\n\nAcross the 102 recorded occupations, fitted income rises by 0.8988 thousand\n1971 Canadian dollars---about 899 dollars---per additional year of\noccupation-average education over the observed 6.38--15.97-year range.\nThis is a bounded description of the records, not an individual, causal,\nor population return. Known-truth repetition showed how a separately\ndeclared process gives slope uncertainty and coverage. In standard units\nthe line predicts $r$ times a case's distance from the mean, so groups\nselected for extreme values are predicted nearer the mean on another\nmeasurement while the spread stays the same; a before-and-after gain in\nsuch a group needs a comparison selected the same way before it is read\nas an effect. Supplementary A reads a short report of the occupation line\nas an argument, locating its reasons before judging its answer.\n\nChapter 8 refits the education-only line on the same 98 type-complete\noccupations before adding prestige, percentage of women, and occupation\ntype. Moving from 102 to 98 changes the records; it is not an adjustment\neffect. The chapter develops conditional comparisons and standardized\nfitted quantities, and asks a separate held-out prediction question.\nChapter 9 collects the regression toolbox these chapters use only\nbriefly, from factors with several levels to robust and resampled\nuncertainty. Chapter 9, Section 7 (Project STAR), then reads a randomized\nclass-size experiment whose uncertainty follows its school-clustered\ndesign [@finn1990; @mosteller1995]; Chapter 10 extends the factorial\ninteractions from Chapters 4 and 6 to comparisons involving regression\npredictors.\n\n### Key terms {.unnumbered}\n\nUse this short reference to revisit the regression concepts introduced\nhere. The Part One Concept Reference gives the broader reference and the\nprincipal home of each concept; fitted values, residuals, standard errors,\nintervals, standardized values, and the reading vocabulary are explained\nin Chapters 1--4.\n\n| Term and common alternatives | Meaning |\n|:--|:--|\n| Simple linear regression (regression line) | A straight-line summary of how one outcome differs across one predictor: fitted value equals intercept plus slope times the predictor. Its descriptive use concerns the records fitted; a model-based use needs a declared process. |\n| Intercept | The fitted outcome at predictor value zero. It places the line vertically; when zero is outside the observed support, it is a mathematical anchor rather than a supported prediction. Centering the predictor moves it to a supported reference point. |\n| Slope (regression coefficient) | The difference in fitted outcome per one-unit difference in the predictor, in outcome units per predictor unit. It compares units that differ in the predictor; it is not a change within one unit unless a design supports that reading. |\n| Ordinary least squares (OLS) | The rule that chooses the intercept and slope minimizing the residual sum of squares. With an intercept, the fitted line passes through the mean point and the residuals sum to zero; the slope equals covariance divided by predictor variance. |\n| Residual sum of squares (RSS) | The sum of squared residuals from a fitted line, in squared outcome units. Total squared variation about the mean splits into a regression part and RSS when the model has an intercept. |\n| Residual standard deviation (residual standard error) | The square root of RSS divided by its residual degrees of freedom, in outcome units; with an intercept and one predictor the degrees of freedom are $n-2$. Under the process model it estimates the error SD. |\n| R-squared (coefficient of determination) | One minus RSS divided by total squared variation: the proportion of centered squared outcome variation accounted for by the fit in these records. In simple regression with an intercept it equals the squared correlation. |\n| Confidence interval for a mean response (mean-response interval) | An interval for the process mean outcome at a stated predictor value, using the SE of the fitted value. It concerns an average, narrows near the predictor mean, and does not cover individual outcomes. |\n| Prediction interval (new-case interval) | An interval for one new outcome at a stated predictor value from the same process. Its variance adds the error variance to the fitted-mean variance, so it is wider than the mean-response interval and keeps a nonzero floor as the sample grows. |\n| Leverage | A measure of how unusual a record's predictor value is relative to the others; it grows with distance from the predictor mean and appears in the SE of a fitted value and in influence measures. |\n| Cook's distance (influence) | A summary of how much the fitted values change when one record is omitted, combining its residual and its leverage. It prompts inspection of provenance and a disclosed sensitivity, not automatic deletion. |\n| Heteroskedasticity-consistent covariance (HC3; sandwich estimator) | A coefficient covariance estimate that allows unequal error variance across predictor values under independence. It changes SEs and intervals, not the fitted coefficients, and does not repair curvature, dependence, measurement error, or confounding. |\n| Extrapolation (predictor support) | Using a fitted line at predictor values outside the observed range or where observations are sparse. Software returns a number there; the data do not support it. |\n| Regression toward the mean (regression to the mean) | In standard units a case's predicted outcome is $r$ times its predictor value, $\\widehat z_y=r\\,z_x$, so with $\\lvert r\\rvert<1$ cases extreme on one measurement are predicted nearer the mean on the other, and a group selected for an extreme noisy first value is expected to move toward the mean on a second measurement, on average rather than in every group. The outcome's spread does not shrink (the regression paradox). |\n| Regression fallacy | Attributing to a treatment, a talent or another cause the movement toward the mean that selection on an extreme noisy measurement produces by itself. A comparison group selected the same way, or random assignment, separates a real change from regression toward the mean. |\n\n: Selected concepts for simple linear regression. {#tbl-ch07-key-terms tbl-colwidths=\"[28,72]\"}\n\n### Further reading {.unnumbered}\n\nFor another accessible account of lines, residuals, and fit, see\n[OpenIntro's single-predictor regression tutorial](https://openintro-ims.netlify.app/model-slr).\nFor a compact executable route from a fitted model to intervals and checks, see\nthe [ISLR authors' Chapter 3 R lab](https://hastie.su.domains/ISLR2/Labs/Rmarkdown_Notebooks/Ch3-linreg-lab.html)\n[@james2021].\nThese provide complementary practice; the present chapter additionally makes\nthe finite-record and model-based questions explicit. Consult\n[the carData reference manual](https://cran.r-project.org/web/packages/carData/carData.pdf)\n[@carData2022] for data documentation, @barnett2005 on regression to the\nmean in repeated measurements, and @fox2016, @fox2019, and @gelman2020 for\nbroader regression treatments.\n\n\\Needspace{18\\baselineskip}\n\n## Exercises {.unnumbered}\n\nThe prompts below use **Foundational** and **Integrative** levels. Where\nrounded summaries are supplied, answers within 0.02 in the stated units are\nsufficient. Exercises 1--6 draw on the main chapter.\n\n<!-- prompt-id: CH07-E01 -->\n### Exercise 1: Read the unit and the line (Foundational) {.unnumbered #ex-ch07-01}\n\n<!-- exercise-id: ch07-ex01 -->\n\nA teaching report describes 80 occupations with\n$\\widehat{\\mathrm{income}}=-1.5+0.7\\,\\mathrm{education}$, where income is in\nthousand dollars and average education ranges from 7 to 16 years.\nInterpret the slope and the intercept. Calculate the fitted income at 12 years\nand the residual for an occupation at 12 years with income 9.\nExplain why the slope does not give an individual's gain from another year\nof schooling.\n\n<!-- prompt-id: CH07-E02 -->\n### Exercise 2: Connect covariance and the fitted line (Foundational) {.unnumbered #ex-ch07-02}\n\n<!-- exercise-id: ch07-ex02 -->\n\nA set of records has $\\bar x=4,\\bar y=10,S_{xx}=20,S_{xy}=30$.\nCalculate the OLS slope and intercept, and the fitted value at $x=5$.\nShow that the line passes through the mean point. If $s_x=2$ and\n$s_y=5$, calculate the correlation implied by these summaries.\nWhat would prevent fitting a slope if every $x$ were equal?\n\n<!-- prompt-id: CH07-E03 -->\n### Exercise 3: Separate fit and uncertainty (Foundational) {.unnumbered #ex-ch07-03}\n\n<!-- exercise-id: ch07-ex03 -->\n\nAn intercept-and-slope regression has $n=22$, $RSS=80$, $TSS=144$,\n$S_{xx}=100$, and fitted slope 0.8. Calculate residual SD, $R^2$, and the\nclassical slope SE. Use $t_{.975,20}=2.086$ to obtain a 95% slope interval.\nState the process assumptions needed for that interval and explain why it\ndoes not by itself establish that the line fits closely or identifies a cause.\n\n<!-- prompt-id: CH07-E04 -->\n### Exercise 4: Mean or new case? (Foundational) {.unnumbered #ex-ch07-04}\n\n<!-- exercise-id: ch07-ex04 -->\n\nUnder the stated independent normal-error constant-variance model, a fitted\nvalue at $x_0=\\bar x$ is 12, $n=25$, and $s_e=3$.\nUse $t_{.975,23}=2.069$. Calculate the SE and 95% interval for the conditional\nmean, then the corresponding prediction SE and interval for one independent\nnew case at the same $x_0$. Explain the extra 1 in the prediction expression.\nWould either interval validate the model in a different population?\n\n\\Needspace{23\\baselineskip}\n\n<!-- prompt-id: CH07-E05 -->\n### Exercise 5: Tell regression toward the mean from an effect (Integrative) {.unnumbered #ex-ch07-05}\n\n<!-- exercise-id: ch07-ex05 -->\n\nIn an invented study, a school records a reading test in September and\nagain in June for all 200 of its pupils. Both tests have mean 50 and SD\n10, and their correlation is .6. The 20 pupils with the lowest September\nscores, averaging 32 points, receive extra tutoring, and their June mean\nis 42.8 points. These figures include the tutored pupils' June scores, so\nby themselves they cannot show what those scores would have been without\ntutoring. The school's records from earlier years, when no pupil was\ntutored, supply that benchmark: the two tests again had means 50, SDs 10\nand correlation .6, and the mean June score of pupils with the same\nSeptember score followed a straight line in that score. Assume that this\nyear's pupils would have followed the same pattern without tutoring. (1)\nExpress the tutored group's September mean in standard units, and give\nthe June mean that this pattern's line in standard units predicts for\npupils with that September score, in standard units and in points. (2)\nThe school reports that tutoring raised the group by 10.8 points. Name\nthe error in reading the whole gain as an effect of tutoring, and say how\nmuch of the gain regression toward the mean predicts by itself under\nthis pattern. (3) The report adds that, since the lowest\nscorers caught up, the June scores of all 200 pupils must be less spread\nout than September's. Split a June score into the part that the\nSeptember score predicts and the part it does not, give the SD of each\npart, and explain why regression toward the mean leaves the June SD at 10.\n(4) Describe a comparison that would separate an effect of tutoring from\nregression toward the mean.\n\n<!-- prompt-id: CH07-E06 -->\n\n\\Needspace{16\\baselineskip}\n\n### Exercise 6: Respond to sensitivity (Integrative) {.unnumbered #ex-ch07-06}\n\n<!-- exercise-id: ch07-ex06 -->\n\nIn a descriptive analysis of 102 occupations, the slope is 0.9.\nA valid, high-income occupation has the largest Cook's distance; removing it\ngives 0.79. A curved-fit check changes the shape, and an HC3 calculation changes\nthe slope SE from 0.13 to 0.15 without changing the line.\n\nWhat does each check tell you? What does it not tell you? Explain why deleting\nthe occupation automatically is inappropriate. Distinguish a variance repair\nfor the same estimand from replacing a constant process slope with a different\nestimand. Write a short sensitivity disclosure for the descriptive analysis.\n\n{{< pagebreak >}}\n\n## Appendix A: Extended regression mathematics and interval derivations {.unnumbered #sec-ch7-app-a}\n\nThe main text uses the identities needed to read a fitted line. This appendix\nderives them and distinguishes identities about the observed records from\nclaims about hypothetical repetitions. All occupation calculations retain\nthe same 102 rows, education in years, and income in thousand 1971 Canadian\ndollars.\n\n### Derivatives, normal equations, and the minimizing line {.unnumbered}\n\nStart with a fitted model that predicts one common center $m$ for every\nobservation. Chapter 2 Section 2.2 states that the mean minimizes the\nsum of squared deviations, and Chapter 3 Appendix A derives the identity\nbehind it:\n\n$$\nL(m)=\\sum_i(y_i-m)^2\n=\\sum_i(y_i-\\bar y)^2+n(m-\\bar y)^2.\n$$\n\nWrite $y_i-m=(y_i-\\bar y)+(\\bar y-m)$ and expand the square. The cross\nterm is zero because $\\sum_i(y_i-\\bar y)=0$. For $n>0$, the last term\nis nonnegative and vanishes only at $m=\\bar y$, so the mean uniquely\nminimizes this criterion.\n\nThe three outcomes $2,4,3$ from Section 2.3 have mean 3 and\n$L(m)=2+3(m-3)^2$, so their best constant line has loss 2. Allowing the\nfitted value to depend on the three predictor values reduces RSS to 1.5,\nas @tbl-ch7-tiny showed. Neither result\nrequires Normal errors or a probability sample. Chapter 6's likelihood\nexample chose a parameter by optimizing a different stated criterion;\nhere we develop the least-squares line algebraically. An uncertainty or\ncausal claim still needs its own supporting conditions.\n\nThe intercept-and-slope criterion has two coefficients to determine.\nInstead of setting one derivative to zero, we set its two partial\nderivatives to zero and verify that the resulting line is the minimum.\n\nFor candidate intercept $b_0$ and slope $b_1$, define\n\n$$\nQ(b_0,b_1)=\\sum_{i=1}^n(y_i-b_0-b_1x_i)^2.\n$$\n\nSquared residuals cannot cancel and give large vertical discrepancies greater\nweight. Differentiating with respect to each candidate coefficient gives\n\n$$\n\\frac{\\partial Q}{\\partial b_0}\n=-2\\sum_i(y_i-b_0-b_1x_i),\\qquad\n\\frac{\\partial Q}{\\partial b_1}\n=-2\\sum_i x_i(y_i-b_0-b_1x_i).\n$$\n\nAt the minimum both derivatives are zero. The resulting **normal equations**\nare\n\n$$\nn\\widehat\\beta_0+\\widehat\\beta_1\\sum_i x_i=\\sum_i y_i,\n\\qquad\n\\widehat\\beta_0\\sum_i x_i+\\widehat\\beta_1\\sum_i x_i^2\n=\\sum_i x_iy_i.\n$$\n\nThe first equation gives\n$\\widehat\\beta_0=\\bar y-\\widehat\\beta_1\\bar x$.\nSubstitution into the second yields\n\n$$\n\\widehat\\beta_1\n=\\frac{\\sum_i x_iy_i-n\\bar x\\bar y}\n       {\\sum_i x_i^2-n\\bar x^2}\n=\\frac{S_{xy}}{S_{xx}}.\n$$\n\nHere $S_{xx}=\\sum_i(x_i-\\bar x)^2>0$ is required: a slope cannot be\nidentified when every predictor value is the same. Because sample covariance\nand variance use the same denominator $n-1$,\n\n$$\n\\widehat\\beta_1\n=\\frac{s_{xy}}{s_x^2}\n=r\\frac{s_y}{s_x},\n\\qquad\n\\widehat\\beta_0=\\bar y-\\widehat\\beta_1\\bar x.\n$$\n\nIn the occupation data,\n\n$$\n\\widehat\\beta_1\n=\\frac{675.8041}{751.8852}\\approx0.8988,\n\\qquad\n\\widehat\\beta_0=\\bar y-\\widehat\\beta_1\\bar x\\approx-2.8536.\n$$\n\nThe ratio has units of thousand dollars per education year. Unlike a\ncorrelation, the slope changes when a variable's units change. Standardizing\nboth variables makes their sample standard deviations one, so the simple\nintercept-model slope becomes $r$; Section 7 reads that line.\n\nTo verify that the stationary point is the unique minimum, write any other\nline as $\\widehat\\beta_0+d_0+(\\widehat\\beta_1+d_1)x_i$. The normal\nequations make the cross term with the OLS residuals vanish, leaving\n\n$$\nQ(\\widehat\\beta_0+d_0,\\widehat\\beta_1+d_1)\n=RSS+n(d_0+d_1\\bar x)^2+d_1^2S_{xx}.\n$$\n\nWith $S_{xx}>0$, every different line has larger RSS. If a candidate line is\nconstrained to pass through $(\\bar x,\\bar y)$, its excess RSS is simply\n$S_{xx}(b_1-\\widehat\\beta_1)^2$. Section 2.4 makes this\ncomparison visible with five candidate lines.\n\n### Residual constraints and projection geometry {.unnumbered}\n\nAt the OLS solution the derivative equations become\n$\\sum_i e_i=0$ and $\\sum_i x_ie_i=0$. Thus the residuals have zero\nsample covariance with the predictor and mean zero **by construction**.\nThey are not evidence that the unknown population errors are independent,\nnormally distributed, or conditionally mean zero.\n\nFor the geometry, let $\\mathbf X$ be the $n\\times2$ matrix with first\ncolumn all ones and second column containing the predictor. Bold\n$\\mathbf X$ is a matrix, distinct from a single predictor value $x_i$.\nThe normal equations can be written\n\n$$\n\\mathbf X^{\\mathsf T}(\\mathbf y-\\mathbf X\\widehat{\\boldsymbol\\beta})\n=\\mathbf0,\n\\qquad\n\\widehat{\\boldsymbol\\beta}\n=(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf X^{\\mathsf T}\\mathbf y.\n$$\n\nThe fitted vector is the projection of $\\mathbf y$ onto the two-dimensional\nspace spanned by the intercept and predictor columns. The residual vector\nis perpendicular to that space. Writing\n$\\mathbf H=\\mathbf X(\\mathbf X^{\\mathsf T}\\mathbf X)^{-1}\\mathbf X^{\\mathsf T}$,\nwe have $\\widehat{\\mathbf y}=\\mathbf H\\mathbf y$ and\n$\\mathbf e=(\\mathbf I-\\mathbf H)\\mathbf y$.\n\nBecause the model includes an intercept, both $\\widehat{\\mathbf y}$ and\nthe constant vector $\\bar y\\mathbf1$ lie in the fitted space. Consequently,\n\n$$\n\\begin{aligned}\n\\sum_i(y_i-\\bar y)^2\n&=\\sum_i\\{(\\widehat y_i-\\bar y)+e_i\\}^2\\\\\n&=\\sum_i(\\widehat y_i-\\bar y)^2+\\sum_i e_i^2,\n\\end{aligned}\n$$\n\nsince $\\sum_i(\\widehat y_i-\\bar y)e_i=0$. This proves\n$TSS=RegSS+RSS$, an algebraic decomposition of observed variation, not\na division into causal contributions. For these records,\n$1820.8134=607.4214+1213.3920$, in squared thousand-dollar units.\n\nAlso $RegSS=\\widehat\\beta_1^2S_{xx}=S_{xy}^2/S_{xx}$. Dividing by\n$TSS=S_{yy}$ proves $R^2=S_{xy}^2/(S_{xx}S_{yy})=r^2$ for simple\nregression **with an intercept**. The identities need not hold for a\nno-intercept fit. When fitted values are nonconstant,\n$\\operatorname{cor}(y,\\widehat y)^2=R^2$ as well.\n\nThere are two fitted directions and $n-2$ residual directions. Under a\ncorrect linear mean with independent constant-variance errors,\n$E(RSS\\mid\\mathbf X)=(n-2)\\sigma^2$. Thus\n$s_e^2=RSS/(n-2)$ estimates the error variance, while $s_e$ estimates its\nstandard deviation in the outcome's units. The square root is not itself\nan exactly unbiased estimator of $\\sigma$. Without that stochastic model,\n$s_e$ remains a computable residual-scale summary, not proof of a common\npopulation error variance.\n\n### From an error model to slope and intercept uncertainty {.unnumbered}\n\nThe 102-record least-squares line is already determined by those records.\nThe next derivation concerns a **separate model-based question**: what\nconstant conditional-mean coefficient generated hypothetical independent\noccupation outcomes at the observed education values? Assume\n\n$$\nY_i=\\beta_0+\\beta_1x_i+\\varepsilon_i,\n\\quad E(\\varepsilon_i\\mid\\mathbf X)=0,\n\\quad \\operatorname{Var}(\\boldsymbol\\varepsilon\\mid\\mathbf X)\n=\\sigma^2\\mathbf I.\n$$\n\nThese are offered working conditions, not consequences of the package's\navailability or of fitting `lm()`. The slope error is\n\n$$\n\\widehat\\beta_1-\\beta_1\n=\\frac{\\sum_i(x_i-\\bar x)\\varepsilon_i}{S_{xx}}.\n$$\n\nIndependence and common variance then give\n\n$$\n\\operatorname{Var}(\\widehat\\beta_1\\mid\\mathbf X)\n=\\frac{\\sigma^2}{S_{xx}},\n\\qquad\nSE(\\widehat\\beta_1)=\\frac{s_e}{\\sqrt{S_{xx}}}.\n$$\n\nBecause $\\widehat\\beta_0=\\bar Y-\\widehat\\beta_1\\bar x$ and\n$\\operatorname{Cov}(\\bar Y,\\widehat\\beta_1\\mid\\mathbf X)=0$,\n\n$$\n\\operatorname{Var}(\\widehat\\beta_0\\mid\\mathbf X)\n=\\sigma^2\\left(\\frac1n+\\frac{\\bar x^2}{S_{xx}}\\right),\n\\qquad\n\\operatorname{Cov}(\\widehat\\beta_0,\\widehat\\beta_1\\mid\\mathbf X)\n=-\\frac{\\bar x\\sigma^2}{S_{xx}}.\n$$\n\nThis covariance explains why simply adding the variances of an uncentered\nintercept and slope prediction would be wrong. If the predictor is centered\nat its observed mean, the intercept and slope estimates are uncorrelated\nunder the classical model, and the intercept SE is $s_e/\\sqrt n$.\n\nUnder the stated linear-mean, uncorrelated, equal-variance conditions, OLS\nis the best linear unbiased estimator: it has the smallest variance among\nestimators linear in the outcomes and unbiased for the coefficients. This\nGauss--Markov statement does not require normal errors and does not establish\ncausal identification, valid measurement, or population coverage [@fox2016;\n@kutner2005].\n\nAdd a jointly normal error vector conditional on the predictor values. Then\nthe standardized coefficient error is normal, $RSS/\\sigma^2$ has a\n$\\chi^2_{n-2}$ distribution, and these quantities are independent. Their\nratio gives\n\n$$\n\\frac{\\widehat\\beta_j-\\beta_j}{SE(\\widehat\\beta_j)}\n\\sim t_{n-2},\\qquad j=0,1.\n$$\n\nThat is the basis of exact classical conditional coverage for\n$\\widehat\\beta_j\\pm t_{.975,n-2}SE(\\widehat\\beta_j)$, and of the\ncorresponding null test. For the occupation slope the calculation is\n$0.8988\\pm1.984(0.127)=[0.6468,1.1508]$ thousand dollars per year.\nIt illustrates the model-based procedure; the diagnostics in Section 6\ndo not support treating its nominal exact coverage as established here.\n\nFixed-$X$ derivations condition on the predictor values; those values need\nnot literally have been experimentally fixed. A random-$X$ conditional-mean\nmodel can use the same conditional argument when its error conditions hold.\nNeither route demonstrates that these occupations were probability sampled.\nNormality of the marginal distribution of education or income is not required.\nThe assumptions concern conditional errors, not the two marginal histograms.\n\n### Why a new-case interval has an additional variance term {.unnumbered}\n\nFor a supported value $x_0$, define the model mean\n$\\mu_0=\\beta_0+\\beta_1x_0$ and its estimate\n$\\widehat\\mu_0=\\widehat\\beta_0+\\widehat\\beta_1x_0$.\nSubstituting the coefficient variances and covariance above gives\n\n$$\n\\begin{aligned}\n\\operatorname{Var}(\\widehat\\mu_0\\mid\\mathbf X)\n&=\\operatorname{Var}(\\widehat\\beta_0)\n +x_0^2\\operatorname{Var}(\\widehat\\beta_1)\n +2x_0\\operatorname{Cov}(\\widehat\\beta_0,\\widehat\\beta_1)\\\\\n&=\\sigma^2\\left\\{\\frac1n+\\frac{(x_0-\\bar x)^2}{S_{xx}}\\right\\}.\n\\end{aligned}\n$$\n\nThe common conditioning on $\\mathbf X$ is suppressed in the first line.\nA confidence interval for this mean uses the square root of this expression\nwith $s_e$ replacing $\\sigma$.\n\nA new occupation outcome is instead $Y_0=\\mu_0+\\varepsilon_0$.\nIf its error is independent of the fitted data and comes from the same\nnormal, equal-variance process,\n\n$$\n\\operatorname{Var}(Y_0-\\widehat\\mu_0\\mid\\mathbf X,x_0)\n=\\sigma^2\\left\\{1+\\frac1n+\\frac{(x_0-\\bar x)^2}{S_{xx}}\\right\\}.\n$$\n\nThe extra $1$ is new outcome variation; it does not disappear even if the\nmodel mean were known. Both standard errors use the same $t_{.975,n-2}$\ncritical value for their classical 95% intervals under the full model.\n\nThe table applies both formulas at four supported education values, the\nsame calculation as Section 5's two `predict()` calls, and puts both sets\nof limits beside the common fitted values.\n\n\\Needspace{12\\baselineskip}\n\n| Education | Fitted | Mean lower | Mean upper | Case lower | Case upper |\n|--:|--:|--:|--:|--:|--:|\n| 8 | 4.3369 | 3.3651 | 5.3087 | $-2.6420$ | 11.3158 |\n| 10 | 6.1345 | 5.4254 | 6.8437 | $-0.8127$ | 13.0818 |\n| 12 | 7.9322 | 7.1776 | 8.6868 | 0.9802 | 14.8842 |\n| 15 | 10.6286 | 9.3550 | 11.9022 | 3.6013 | 17.6559 |\n\n: Mean-response and new-case intervals at four supported education values. {#tbl-ch07-app-a-intervals tbl-colwidths=\"[16,16,17,17,17,17]\"}\n\nAt 10 years, the point prediction is 6.1345 thousand dollars, the mean\ninterval is [5.4254, 6.8437], and the new-occupation interval is\n[$-0.8127$, 13.0818]. The\nnegative endpoint exposes the lower-tail limitation of this unbounded\nnormal-linear model. Cutting it off at zero does not produce a validated\n95% interval. An outcome transformation or a model respecting the boundary\nwould change the analysis and would need its own interpretation and checks.\n\nBoth intervals widen away from $\\bar x$; their narrowest point is the mean\neducation value. With more comparable independent observations and stable\npredictor spread, mean uncertainty tends to shrink. The new-case interval\nretains a nonzero error-variation floor. None of these formulas includes\nuncertainty from an inappropriate mean function, biased measurement, or a\nshift to another labour market. They are pointwise model intervals, not a\nsimultaneous band or empirical out-of-sample validation. Their target is a\nnew occupation-level record from the declared process, never an individual\nworker's income.\n\n## References {.unnumbered}\n\n::: {#refs}\n:::\n",
    "supporting": [
      "chapter_07_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}